import Link from "next/link";
import {getBlogPosts} from "@/lib/blog";
import {clinicalSystems} from "@/lib/clinical-systems";
import {ArrowRight,BookOpen,Brain,Clock3,Flame,Search,ShieldCheck,Target} from "lucide-react";
export const dynamic="force-dynamic";
const topics=["ACE Inhibitors & ARBs","Antibiotics","Diuretics","Drug Interaction","Anticoagulants","Pharmacokinetics","Drug Law","Endocrine","CNS","Calculation"];
export default async function BlogPage(){const posts=await getBlogPosts().catch(()=>[]);return <div className="min-h-screen bg-[#fffefd]">
<section className="border-b bg-gradient-to-br from-emerald-50 via-white to-cyan-50"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-10 sm:px-6 lg:grid-cols-[1.15fr_.85fr] lg:px-8"><div><span className="inline-flex rounded-xl bg-emerald-700 px-4 py-2 text-sm font-bold text-white">PharmRU Blog</span><h1 className="mt-4 text-4xl font-black leading-tight text-[#102a4c] sm:text-5xl">ทบทวนก่อนสอบ<br/><span className="text-emerald-700">อ่านจากเรื่องที่ออกข้อสอบบ่อย</span></h1><p className="mt-4 text-lg text-slate-600">สรุปจากคลังข้อสอบ PharmRU ให้เข้าใจ Concept พร้อม Exam Pearl • จุดหลอก • ตัวอย่างข้อสอบ</p><div className="mt-6 flex max-w-xl items-center rounded-2xl border bg-white p-2 shadow-sm"><Search className="ml-3 h-5 w-5 text-slate-400"/><span className="flex-1 px-3 text-sm text-slate-400">ค้นหาบทความ เช่น ACEi, Diuretics, PK...</span><span className="rounded-xl bg-emerald-700 p-3 text-white"><Search className="h-4 w-4"/></span></div></div><div className="relative min-h-72 overflow-hidden rounded-[2rem] bg-white/60"><div className="absolute left-12 top-8 rotate-[-5deg] rounded-lg bg-amber-50 p-4 text-center font-semibold shadow">Good Pharmacists<br/>Create Healthier<br/>Tomorrows. ♡</div><div className="absolute bottom-4 left-36 space-y-1">{["PHARMACOLOGY","PHARMACOTHERAPY","PHARMACEUTICS","CLINICAL PHARMACY"].map(x=><div className="w-56 rounded border bg-white px-4 py-2 text-center text-sm font-bold shadow-sm" key={x}>{x}</div>)}</div><div className="absolute right-4 top-6 w-48 rounded-3xl bg-emerald-700 p-5 text-white shadow-lg"><b className="text-lg">เรียนรู้<br/>จากข้อสอบจริง</b>{["สรุปกระชับ","ตรงประเด็น","มีตัวอย่างข้อสอบ"].map(x=><div className="mt-3 flex gap-2 text-xs" key={x}><ShieldCheck className="h-4 w-4"/>{x}</div>)}</div></div></div><div className="mx-auto flex max-w-7xl flex-wrap gap-2 px-4 pb-7 sm:px-6 lg:px-8">{["ทั้งหมด","💊 Pharmacology","🩺 Pharmacotherapy","🧪 Pharmaceutics","🧮 Calculation","⚖️ Drug Law","••• อื่น ๆ"].map((x,i)=><span key={x} className={"rounded-xl border px-4 py-2 text-sm font-medium "+(i===0?"bg-emerald-700 text-white":"bg-white")}>{x}</span>)}</div></section>
<main className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8">
<section><div className="mb-5"><h2 className="text-3xl font-black text-[#102a4c]">👑 บทความแนะนำ</h2><p className="mt-1 text-slate-500">เรื่องสำคัญที่ออกข้อสอบบ่อย ไม่ควรพลาด</p></div><div className="grid gap-5 lg:grid-cols-[1fr_1fr_280px]">
<div className="self-start overflow-hidden rounded-3xl border bg-white shadow-sm">
<div className="relative h-72 overflow-hidden bg-gradient-to-br from-rose-100 via-pink-50 to-white">
<div className="absolute left-7 top-6 z-10"><div className="flex gap-2"><span className="rounded-full bg-rose-500 px-3 py-1 text-xs font-bold text-white">Pharmacology</span><span className="rounded-full bg-white/80 px-3 py-1 text-xs font-bold text-slate-700">Clinical Review</span></div><h3 className="mt-5 text-4xl font-black leading-none text-[#102a4c]">ACE<br/>Inhibitors</h3><div className="mt-4 space-y-1 text-sm font-semibold text-slate-700"><div>✓ RAAS</div><div>✓ Indications</div><div>✓ Adverse effects</div><div>✓ Exam points</div></div></div>
<div className="absolute right-8 top-9 h-56 w-48"><div className="absolute left-8 top-8 h-44 w-36 rotate-[-5deg] rounded-[48%_52%_58%_42%] bg-gradient-to-br from-rose-300 via-red-400 to-rose-600 shadow-xl"></div><div className="absolute left-16 top-0 h-20 w-8 -rotate-6 rounded-full bg-red-500"></div><div className="absolute left-24 top-1 h-20 w-9 rotate-12 rounded-full bg-blue-500"></div><div className="absolute left-6 top-9 h-16 w-8 -rotate-[32deg] rounded-full bg-blue-400"></div><div className="absolute left-20 top-16 h-28 w-1 rotate-[18deg] rounded-full bg-rose-100/80"></div><div className="absolute left-28 top-16 h-24 w-1 -rotate-[20deg] rounded-full bg-red-900/30"></div><div className="absolute bottom-0 left-0 h-8 w-16 rotate-12 rounded-full bg-white shadow"></div><div className="absolute bottom-3 left-10 h-8 w-16 -rotate-12 rounded-full bg-rose-300 shadow"></div></div><div className="absolute bottom-5 right-5 rotate-[-5deg] rounded-lg bg-amber-50 px-3 py-2 text-xs font-semibold text-slate-600 shadow">Lower BP<br/>Protect kidney<br/>Pass exam! ♡</div></div>
<div className="p-5 pb-6"><div className="flex items-center gap-2 text-xs text-slate-400"><span className="rounded-full bg-emerald-50 px-2 py-1 text-emerald-700">Pharmacology</span><Clock3 className="h-3.5 w-3.5"/>7 นาที</div><h3 className="mt-3 text-xl font-black leading-7 text-[#102a4c]">ACE Inhibitors ก่อนสอบ: กลไก ผลข้างเคียง จุดหลอก และ Hyperkalemia</h3><p className="mt-2 text-sm leading-6 text-slate-500">ทบทวน ACE inhibitors แบบเข้าใจง่าย ตั้งแต่กลไก RAAS ไปถึง adverse effects และข้อสอบที่ชอบออก</p><Link href="/blog/ace-inhibitors-exam-review" className="mt-5 flex items-center font-bold text-emerald-700">อ่านบทความ <ArrowRight className="ml-2 h-4 w-4"/></Link></div></div>
<div className="self-start overflow-hidden rounded-3xl border bg-white shadow-sm">
<div className="relative h-72 overflow-hidden bg-gradient-to-br from-cyan-50 via-emerald-50 to-white"><div className="absolute left-7 top-7"><span className="rounded-full bg-emerald-600 px-3 py-1 text-xs font-bold text-white">ทบทวนสอบ PLE</span><h3 className="mt-5 text-3xl font-black text-[#102a4c]">สรุปยา 8 กลุ่มเสี่ยง<br/><span className="text-emerald-700">ที่ออกสอบบ่อย</span></h3><div className="mt-4 space-y-2 text-sm text-slate-700"><div>✓ สรุปสั้น กระชับ</div><div>✓ เน้นจุดที่ออกสอบ</div><div>✓ พร้อม Exam Tips</div></div></div><div className="absolute bottom-6 right-7 space-y-[-2px]">{["Antibiotics","Anticoagulants","Diuretics","ACEIs / ARBs","Drug Interaction","Endocrine","CNS","Pharmacokinetics"].map((x,j)=><div key={x} className={"w-40 rounded-md border border-white/60 px-3 py-1 text-center text-[11px] font-bold text-white shadow "+(["bg-rose-400","bg-orange-400","bg-amber-400","bg-emerald-500","bg-sky-500","bg-violet-500","bg-indigo-600","bg-slate-600"][j])}>{x}</div>)}</div><div className="absolute bottom-5 left-7 rotate-[-4deg] rounded-lg bg-amber-50 px-4 py-3 text-xs font-semibold leading-4 text-slate-600 shadow">Same Concepts<br/>New Confidence :)</div></div>
<div className="p-5 pb-6"><div className="flex items-center gap-2 text-xs text-slate-400"><span className="rounded-full bg-emerald-50 px-2 py-1 text-emerald-700">ทบทวนสอบ PLE</span><Clock3 className="h-3.5 w-3.5"/>3 นาที</div><h3 className="mt-3 text-xl font-black leading-7 text-[#102a4c]">สรุปยา 8 กลุ่มเสี่ยงที่ออกสอบ PLE บ่อยที่สุด</h3><p className="mt-2 text-sm leading-6 text-slate-500">รวมกลุ่มยาที่มีความเสี่ยงสูงและจุดที่นักศึกษาเภสัชมักตอบผิด</p><Link href="/blog/ple-high-risk-drug-classes-review" className="mt-5 flex items-center font-bold text-emerald-700">อ่านบทความ <ArrowRight className="ml-2 h-4 w-4"/></Link></div></div>
<aside className="space-y-4"><div className="rounded-3xl border bg-slate-50 p-5"><div className="mb-3 flex items-center gap-2 font-black"><Flame className="h-5 w-5 text-orange-500"/>หัวข้อฮอตฮิต</div>{topics.map((x,i)=><div className="mb-2 flex items-center gap-3 rounded-xl bg-white px-3 py-2 text-xs" key={x}><span className="flex h-6 w-6 items-center justify-center rounded-full bg-amber-100 font-bold text-amber-700">{i+1}</span><span className="flex-1">{x}</span></div>)}</div><div className="rounded-3xl bg-emerald-700 p-5 text-white"><Target className="h-7 w-7"/><h3 className="mt-3 text-xl font-black">อยากเก่งขึ้นอีกขั้น?</h3><p className="mt-2 text-sm text-white/80">ฝึกทำข้อสอบเรื่องนี้ได้เลย</p><Link href="/ple/practice" className="mt-4 flex justify-center rounded-xl bg-white px-4 py-3 text-sm font-bold text-emerald-800">ไปยังชุดข้อสอบ →</Link></div></aside></div></section>
<section className="mt-12"><div className="mb-5"><h2 className="text-3xl font-black text-[#102a4c]">เลือกทบทวนตามโรคและระบบ</h2><p className="text-slate-500">เริ่มจากโรคที่อยากอ่าน แล้วค่อยเจาะยา กลไก และข้อสอบ</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{clinicalSystems.map(s=><Link key={s.slug} href={"/blog/system/"+s.slug} className="rounded-2xl border bg-white p-5 transition hover:-translate-y-1 hover:shadow-md"><div className="text-3xl">{s.icon}</div><h3 className="mt-3 font-bold">{s.name}</h3><p className="mt-1 text-xs text-slate-500">{s.description}</p><div className="mt-3 text-sm font-bold text-emerald-700">ดูบททบทวน →</div></Link>)}</div></section>
<section className="mt-12 border-t pt-8"><div className="grid gap-4 text-center sm:grid-cols-4">{[["📖","สรุปจากข้อสอบจริง"],["🧠","เข้าใจ Concept"],["💡","มี Exam Pearl"],["📋","พร้อมตัวอย่างข้อสอบ"]].map(([i,t])=><div key={t} className="rounded-2xl bg-emerald-50/60 p-5"><div className="text-3xl">{i}</div><b className="mt-2 block">{t}</b></div>)}</div></section>
</main></div>}