"use client";
import Link from "next/link"; import {useState} from "react"; import {ArrowRight,Check,X} from "lucide-react";
const dose=[["Captopril","25 mg BID–TID","50 mg BID–TID"],["Enalapril","5 mg OD","up to 40 mg/day"],["Lisinopril","10 mg OD","up to 40 mg/day"],["Ramipril","2.5 mg OD","2.5–20 mg/day"]];
export default function ACEIReview(){const[a,setA]=useState<number|null>(null);const ch=["Thiazide diuretics","Potassium-sparing diuretics","Loop diuretics","Dihydropyridine CCBs"];return <div className="bg-[#fffdfc] text-slate-800">
<section className="bg-gradient-to-br from-rose-50 via-white to-emerald-50"><div className="mx-auto grid max-w-7xl gap-8 px-6 py-10 lg:grid-cols-[1.2fr_.8fr] lg:items-center"><div><div className="flex gap-2"><b className="rounded-full bg-rose-100 px-3 py-1 text-xs text-rose-600">Pharmacology</b><b className="rounded-full bg-emerald-100 px-3 py-1 text-xs text-emerald-700">Clinical Review</b></div><h1 className="mt-4 text-5xl font-black leading-tight text-[#102a4c]">ACE Inhibitors<br/><span className="text-emerald-700">ก่อนสอบ: กลไก ผลข้างเคียง<br/>จุดหลอก และตัวอย่างข้อสอบ</span></h1><p className="mt-4 text-lg text-slate-600">ทบทวนจากกลไก RAAS ไปถึง adverse effects, drug interaction และโจทย์ที่ชอบออก</p><p className="mt-5 text-sm text-slate-500">👨‍⚕️ PharmRU Team　⏱ 7 นาที　Clinical Review</p></div><div className="relative min-h-80 rounded-[2.5rem] bg-rose-100"><div className="absolute right-14 top-8 text-[9rem]">❤️</div><div className="absolute bottom-7 right-8 space-y-2">{["ACE Inhibitors","ARBs","Beta-blockers","Diuretics"].map(x=><div className="w-44 rounded-lg bg-white px-4 py-2 text-center text-sm font-bold shadow" key={x}>{x}</div>)}</div><div className="absolute left-7 top-8 rotate-[-5deg] rounded-xl bg-amber-50 p-4 text-center font-bold shadow">Same Concepts<br/>New Confidence :)</div></div></div></section>
<main className="mx-auto max-w-7xl space-y-6 px-6 py-7"><div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-rose-50 p-5"><b className="text-rose-700">“เข้าใจกลไก → จำผลข้างเคียง → ระวังจุดหลอก → ทำข้อสอบได้จริง”</b><Link href="/ple/practice" className="rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white">ฝึกข้อสอบเรื่องนี้ →</Link></div>
<div className="grid gap-4 lg:grid-cols-3"><Box t="💡 Key Takeaways" items={["ACE inhibition → Ang II ↓, bradykinin ↑","จำ dry cough, hyperkalemia, angioedema","ติดตาม BP, renal function และ K⁺","หลีกเลี่ยงใน pregnancy"]}/><Box t="📚 สารบัญ" items={["กลไกการออกฤทธิ์","ข้อบ่งใช้","รายชื่อยา/ขนาดยา","ผลข้างเคียง","จุดหลอก","ตัวอย่างข้อสอบ"]}/><div className="flex items-center justify-center rounded-3xl border bg-emerald-50 p-6 text-center text-2xl font-bold text-emerald-800">“ยาที่ดี...<br/>เมื่อรู้วิธีใช้<br/>และรู้ข้อจำกัด” 💚</div></div>
<S title="1　กลไกการออกฤทธิ์ (Mechanism of Action)"><div className="grid gap-3 text-center md:grid-cols-5">{[["🧬","Angiotensinogen"],["🫘","Renin"],["⚪","Angiotensin I"],["⛔","ACE inhibited"],["🔴","Angiotensin II ↓"]].map(([i,t])=><div className="rounded-2xl bg-slate-50 p-5" key={t}><div className="text-4xl">{i}</div><b className="mt-2 block">{t}</b></div>)}</div><div className="mt-4 grid gap-2 sm:grid-cols-4">{["↓ Vasoconstriction","↓ Aldosterone","↓ Blood pressure","K⁺ ↑ tendency"].map(x=><b className="rounded-xl bg-emerald-50 p-3 text-center text-sm text-emerald-800" key={x}>{x}</b>)}</div></S>
<section><h2 className="mb-4 text-2xl font-black text-emerald-800">2　ข้อบ่งใช้ทางคลินิก</h2><div className="grid gap-3 sm:grid-cols-5">{[["🩸","HTN"],["❤️","Heart failure"],["💓","Post-MI"],["🫘","CKD / proteinuria"],["💧","Diabetic kidney disease"]].map(([i,t])=><div className="rounded-2xl border bg-blue-50/50 p-5 text-center" key={t}><div className="text-4xl">{i}</div><b>{t}</b></div>)}</div></section>
<S title="3　รายชื่อยาและขนาดที่ใช้บ่อย"><div className="overflow-x-auto"><table className="w-full min-w-[600px] text-sm"><thead className="bg-blue-50"><tr><th className="p-4 text-left">ยา</th><th className="p-4 text-left">Initial HTN</th><th className="p-4 text-left">Titration / range</th></tr></thead><tbody>{dose.map(r=><tr className="border-t" key={r[0]}>{r.map((x,i)=><td className={"p-4 "+(i===0?"font-bold":"")} key={x}>{x}</td>)}</tr>)}</tbody></table></div><p className="mt-3 text-xs text-slate-500">ตัวอย่างขนาดผู้ใหญ่จาก prescribing information; ต้องปรับตาม indication, renal function และ clinical response</p></S>
<section><h2 className="mb-4 text-2xl font-black text-emerald-800">4　ผลข้างเคียงและข้อควรระวัง</h2><div className="grid gap-4 md:grid-cols-3"><Box c="bg-rose-50" t="🫁 พบบ่อย/ควรรู้" items={["Dry cough","Hypotension","Hyperkalemia","Renal function change"]}/><Box c="bg-amber-50" t="⚠️ สำคัญ" items={["Angioedema","Symptomatic hypotension","AKI in susceptible patients"]}/><Box c="bg-slate-50" t="🚫 หลีกเลี่ยง/ระวัง" items={["Pregnancy","Prior ACEI angioedema","Bilateral renal artery stenosis","Hyperkalemia"]}/></div></section>
<div className="grid gap-5 lg:grid-cols-2"><S title="5　จุดหลอกที่ออกข้อสอบบ่อย"><Box items={["ACEI cough เชื่อมกับ bradykinin","ACEI + K⁺-sparing → hyperkalemia","ติดตาม renal function และ K⁺","Pregnancy: ไม่ควรใช้"]}/></S><S title="6　ตัวอย่างข้อสอบ"><p className="font-bold">ผู้ป่วยได้รับ enalapril ยากลุ่มใดเพิ่มความเสี่ยง hyperkalemia?</p><div className="mt-4 space-y-2">{ch.map((x,i)=><button onClick={()=>setA(i)} key={x} className={"flex w-full justify-between rounded-xl border p-3 text-left "+(a!==null&&i===1?"bg-emerald-50 border-emerald-400":a===i?"bg-rose-50":"bg-white")}><span>{String.fromCharCode(65+i)}. {x}</span>{a!==null&&i===1?<Check className="text-emerald-600"/>:a===i?<X className="text-rose-500"/>:null}</button>)}</div>{a!==null&&<div className="mt-4 rounded-xl bg-emerald-50 p-4 text-sm"><b>เฉลย B</b> — ACEI ลด aldosterone จึงลดการขับ K⁺; ใช้ร่วมกับ potassium-sparing diuretic เพิ่มความเสี่ยง hyperkalemia</div>}</S></div>
<div className="grid gap-4 md:grid-cols-2"><div className="rounded-3xl bg-emerald-50 p-6"><h2 className="text-xl font-black text-emerald-800">🧠 สรุปจำก่อนสอบ</h2><p className="mt-2">ACEI → Ang II ↓ + aldosterone ↓ + bradykinin ↑ → จำ ไอ, K⁺ สูง, angioedema</p></div><div className="rounded-3xl bg-rose-50 p-6"><h2 className="text-xl font-black text-rose-700">จำด้วย “ACE”</h2><p className="mt-2"><b>A</b> = Ang II ↓　<b>C</b> = Cough　<b>E</b> = Electrolyte K⁺ ↑</p></div></div>
<section><div className="flex justify-between"><h2 className="text-2xl font-black text-[#102a4c]">🔗 บทความที่เกี่ยวข้อง</h2><Link href="/blog" className="font-bold text-emerald-700">ดูทั้งหมด →</Link></div><div className="mt-4 grid gap-3 sm:grid-cols-5">{[["💊","ARBs"],["⚪","Thiazide"],["β","Beta-blockers"],["❤️","Heart Failure"],["🫘","CKD"]].map(([i,t])=><Link href="/blog" className="rounded-2xl border bg-white p-5" key={t}><div className="text-4xl">{i}</div><b className="mt-3 block">{t}</b><ArrowRight className="mt-4 h-4 w-4 text-emerald-600"/></Link>)}</div></section>
</main></div>}
function S({title,children}:{title:string,children:React.ReactNode}){return <section className="rounded-3xl border border-emerald-100 bg-white p-6 shadow-sm"><h2 className="mb-5 text-2xl font-black text-emerald-800">{title}</h2>{children}</section>}
function Box({t,items,c="bg-blue-50/50"}:{t?:string,items:string[],c?:string}){return <div className={"rounded-3xl border p-6 "+c}>{t&&<h3 className="text-xl font-black text-[#102a4c]">{t}</h3>}<div className="mt-3 space-y-2">{items.map(x=><div className="flex gap-2 text-sm" key={x}><span className="text-emerald-600">✓</span>{x}</div>)}</div></div>}