import type { McqQuestion } from "@/lib/types-mcq";
const cases=[
["HFrEF","ชาย 62 ปี HFrEF LVEF 30% NYHA II, eGFR 65, K 4.3 ใช้ enalapril และ furosemide",["เพิ่ม evidence-based beta-blocker หากไม่มีข้อห้าม","ติดตาม BP/HR/volume status หลังปรับยา","หลีกเลี่ยง NSAID ใช้เองเป็นประจำ","สอนชั่งน้ำหนักและสังเกตอาการคั่งน้ำ"]],
["AF","หญิง 76 ปี AF, HTN, DM, eGFR 58 ไม่มี active bleeding",["ประเมิน thromboembolic risk เพื่อวางแผน anticoagulation","ติดตาม adherence/bleeding/renal function","ทบทวน NSAID/antiplatelet ที่เพิ่ม bleeding risk","สอน red flags ของ bleeding และไม่หยุดยาเอง"]],
["T2DM+CKD","หญิง 66 ปี T2DM, CKD G3a, UACR 620 mg/g, BP 148/86, HbA1c 8.0%",["พิจารณา RAAS blockade เมื่อเหมาะสมเพื่อ BP/albuminuria","ติดตาม creatinine และ potassium หลังเริ่ม/ปรับ RAAS blocker","พิจารณา SGLT2 inhibitor เพื่อ cardiorenal benefit ในผู้ป่วยที่เหมาะสม","ช่วง fasting/ผ่าตัดต้องจัดการ SGLT2 inhibitor เพื่อลด DKA risk"]],
["Hyperkalemia","ชาย 68 ปี CKD G4, K 6.1 mEq/L ใช้ ACEI+spironolactone และมี peaked T waves",["hyperkalemia with ECG change เป็นภาวะฉุกเฉิน","ทบทวนยาที่เพิ่ม K และ renal function","หลีกเลี่ยง potassium supplement/เกลือทดแทนที่มี K โดยไม่จำเป็น","สอนหลีกเลี่ยง OTC/supplement ที่เพิ่ม K และมาตรวจตามนัด"]],
["CAP","หญิง 70 ปี community-acquired pneumonia, CKD G3 ไม่มี MRSA/Pseudomonas risk factors",["เลือก empiric therapy ตาม severity/comorbidity/local resistance","ปรับ dose ตาม renal function เมื่อยานั้นต้องปรับ","de-escalate เมื่อมี culture และ clinical response","สอน adherence และ red flags"]],
["Asthma","หญิง 28 ปี asthma ใช้ SABA หลายครั้งต่อสัปดาห์และตื่นกลางคืน",["ใช้ ICS-containing strategy ไม่พึ่ง SABA อย่างเดียว","ประเมิน inhaler technique/adherence ก่อน step-up","ทบทวน trigger และยาที่อาจทำให้อาการแย่ลง","ทำ written action plan และสอน inhaler technique"]],
["Lithium","หญิง 55 ปี bipolar stable on lithium เริ่ม thiazide แล้วมี tremor, ataxia, diarrhea",["สงสัย lithium toxicity และตรวจ level/renal function พร้อมจัดการเร่งด่วน","thiazide สามารถเพิ่ม lithium concentration","NSAID/ACEI บางบริบทเพิ่ม lithium exposure ได้","สอน hydration และแจ้งก่อนเริ่มยาใหม่"]],
["Methotrexate","หญิง 48 ปี RA ใช้ methotrexate รายสัปดาห์ มี oral ulcers และ CBC ผิดปกติ",["สงสัย methotrexate toxicity และประเมิน CBC/LFT/renal function","ย้ำว่า methotrexate สำหรับ RA ใช้ weekly ไม่ใช่ daily","trimethoprim-sulfamethoxazole อาจเพิ่ม toxicity","สอน dosing day และ folate ตามแผน"]],
["Anaphylaxis","ชาย 30 ปีหลังฉีดยามี urticaria, wheeze, BP 78/46",["IM epinephrine เป็น first-line treatment","ติดตาม airway/breathing/circulation และอาการ biphasic","antihistamine ไม่แทน epinephrine","สอน avoidance และ emergency plan"]],
["Polypharmacy","หญิง 82 ปีใช้ยา 12 รายการ มี falls, orthostasis และ confusion หลังเพิ่มยานอนหลับ",["ทำ medication review หา potentially inappropriate/duplicate drugs","วัด orthostatic BP และประเมิน fall risk","ยากดประสาทหลายตัวเพิ่ม fall/confusion risk","deprescribing ต้องวางแผนและติดตาม ไม่หยุดทุกยาแบบฉับพลัน"]]
] as const;
const wrong=["เพิ่มยาทุกชนิดเป็นขนาดสูงสุดทันทีโดยไม่ประเมินผู้ป่วย","หยุดยาประจำทั้งหมดทันทีโดยไม่ประเมินความเสี่ยง","ใช้ผลตรวจเพียงค่าเดียวตัดสินใจโดยไม่ดูอาการและแนวโน้ม","ให้ยารักษาตามอาการอย่างเดียวและไม่ทบทวนสาเหตุ"];
const prompts=["การจัดการใดเหมาะสมที่สุด?","ประเด็นติดตามใดสำคัญที่สุด?","เมื่อทบทวนยาร่วมและความปลอดภัย ข้อใดถูกต้องที่สุด?","คำแนะนำก่อนจำหน่ายข้อใดเหมาะสมที่สุด?"];
export const PC1_MOCK_001:McqQuestion[]=[];
let n=1;
for(let variant=0;variant<3;variant++)for(let ci=0;ci<cases.length;ci++){const [title,base,points]=cases[ci];for(let qi=0;qi<4;qi++){const labels=["A","B","C","D","E"];const pos=(ci+qi+variant)%5;const opts=[...wrong];opts.splice(pos,0,points[qi]);const answer=labels[pos];PC1_MOCK_001.push({id:`pc1m001q${String(n).padStart(3,"0")}`,subject_id:"pc1",exam_type:"PLE-PC",exam_source:"PharmRU PC1 Mock Set 001",exam_day:null,question_number:n,scenario:`Case PC1-${String(variant*10+ci+1).padStart(3,"0")}: ${title}\n${base}\nVariant ${variant+1}: ทีมรักษามีข้อมูลและบริบทผู้ป่วยแตกต่างจากรอบก่อน ให้เลือก single best answer\n\nคำถามที่ ${qi+1}/4: ${prompts[qi]}`,image_url:null,choices:opts.map((text,i)=>({label:labels[i],text})),correct_answer:answer,explanation:`${points[qi]} — ทบทวนตาม guideline ปัจจุบันและหลัก pharmaceutical care`,detailed_explanation:{summary:`เฉลย ${answer}: ${points[qi]}`,reason:"คำตอบนี้เหมาะสมที่สุดเมื่อพิจารณาประสิทธิผล ความปลอดภัย โรคร่วม ยาร่วม และบริบทของผู้ป่วยร่วมกัน",choices:opts.map((text,i)=>({label:labels[i],text,is_correct:labels[i]===answer,explanation:labels[i]===answer?"เหมาะสมที่สุดในบริบทของเคสนี้":"ไม่ใช่ single best answer เพราะละเลยการประเมินประโยชน์-ความเสี่ยงหรือบริบทสำคัญ"})),key_takeaway:points[qi]},difficulty:qi<2?"medium":"hard",is_ai_enhanced:true,ai_notes:"Original PharmRU PC1 educational item; guideline-updated; editorial review recommended.",status:"active",created_at:"2026-09-22 12:00:00",mcq_subjects:{id:"pc1",name:"PC1",name_th:"บริบาลเภสัชกรรม PC1",icon:"🩺",exam_type:"PLE-PC",question_count:120,created_at:"2026-09-22 12:00:00"}});n++;}}
