import type { McqQuestion } from "@/lib/types-mcq";
const caseTitle="T2DM + CKD + severe albuminuria";
const base="ชายไทยอายุ 64 ปี น้ำหนัก 78 kg มี T2DM 11 ปี, HTN และ dyslipidemia ใช้ metformin 500 mg BID, amlodipine 10 mg OD, atorvastatin 40 mg HS. BP 148/86 mmHg, HbA1c 7.8%, SCr 1.5 mg/dL, eGFR 48 mL/min/1.73m², K⁺ 4.5 mEq/L, UACR 680 mg/g, LDL-C 72 mg/dL. ไม่มี edema, orthostatic hypotension หรือ recurrent UTI.";
const qs=[
{stage:base,p:"เภสัชกรควรเสนอการปรับยาลดความดันข้อใดเหมาะสมที่สุด?",o:["เพิ่ม hydrochlorothiazide 25 mg/day","เปลี่ยน amlodipine เป็น carvedilol","เพิ่ม losartan และ titrate ไปยังขนาดสูงสุดที่ทนได้","เพิ่ม doxazosin","เพิ่ม spironolactone เป็นยาตัวถัดไปทันที"],a:2,r:"ผู้ป่วยมี diabetes + hypertension + CKD และ severely increased albuminuria (UACR 680 mg/g; A3) จึงมีข้อบ่งใช้เด่นของ ACEI/ARB ไม่ใช่เพียงเพื่อ BP lowering แต่เพื่อ renal protection และลด albuminuria ด้วย",wrong:["Thiazide ช่วยลด BP ได้และอาจใช้ร่วมภายหลัง แต่ยังไม่ตอบ kidney-protection priority ได้เท่า RAAS blockade ในผู้ป่วย A3 albuminuria","Carvedilol มีข้อบ่งใช้สำคัญในบางโรค เช่น HFrEF แต่ข้อมูลโจทย์นี้ไม่ได้ให้ข้อบ่งใช้ที่ทำให้ beta-blocker เหนือกว่า ACEI/ARB","ถูก: losartan เป็น ARB เหมาะกับ HTN + diabetic CKD + A3 albuminuria และควร titrate ตาม tolerance พร้อมติดตาม SCr/K⁺","Doxazosin ลด BP ได้ แต่ไม่มีหลักฐาน renal protection ใน diabetic albuminuric CKD เทียบเท่า ACEI/ARB","MRA อาจมีบทบาทภายหลังใน selected patients แต่ไม่ควรข้าม ACEI/ARB ซึ่งเป็น foundational therapy ในสถานการณ์นี้"]},
{stage:"หลังเริ่ม losartan 50 mg/day 2 สัปดาห์ BP 136/78 mmHg, SCr 1.8 mg/dL, K⁺ 4.9 mEq/L ไม่มี dizziness และไม่มีภาวะขาดน้ำ",p:"การจัดการใดเหมาะสมที่สุด?",o:["หยุด losartan เพราะ SCr เพิ่ม >0.2 mg/dL","ลด losartan เหลือ 25 mg ทันที","เปลี่ยนเป็น lisinopril เพื่อป้องกัน creatinine เพิ่ม","ให้ losartan ต่อ พร้อมติดตาม SCr และ K⁺","ให้ potassium binder เพื่อป้องกัน hyperkalemiaทันที"],a:3,r:"SCr เพิ่มจาก 1.5 เป็น 1.8 mg/dL หรือประมาณ 20% หลังเริ่ม ARB และผู้ป่วย clinically stable ไม่มี volume depletion. การเพิ่มระดับนี้ยังอยู่ในช่วงที่โดยทั่วไปสามารถ continue RAAS blockade พร้อม monitoring ได้; threshold ที่ต้องประเมินอย่างจริงจังคือ creatinine rise >30% ภายในช่วงหลังเริ่ม/เพิ่มยา หรือมี hypotension/hyperkalemia ที่ควบคุมไม่ได้",wrong:["การใช้ absolute change 0.2 mg/dL เป็นเกณฑ์หยุด ARB ไม่ถูกต้อง ต้องคิดเป็นสัดส่วนและดู volume status/clinical context","ยังไม่มีเหตุผลต้องลดขนาดทันที เพราะ creatinine rise ประมาณ 20% และ K 4.9 โดยไม่มีอาการ","ACEI และ ARB ต่างมีผลต่อ intraglomerular hemodynamics การเปลี่ยนเป็น ACEI ไม่ได้แก้ expected creatinine rise","ถูก: continue พร้อมติดตาม SCr/K⁺ และประเมิน volume status, NSAID use และปัจจัยที่ทำให้ AKI/hyperkalemia","K 4.9 ยังไม่ใช่เหตุให้เริ่ม potassium binder prophylactically โดยอัตโนมัติ ต้องติดตามและจัดการตามระดับ/แนวโน้ม/ปัจจัยร่วม"]},
{stage:"3 เดือนต่อมา losartan ถูก titrate เป็นขนาดสูงสุดที่ทนได้. BP 128/76 mmHg, eGFR 45, K⁺ 4.8, UACR 510 mg/g, HbA1c 7.9%",p:"หากต้องการลดความเสี่ยง CKD progression และ cardiovascular events เพิ่มเติม ยาใดเหมาะสมที่สุดเป็นลำดับถัดไป?",o:["Glipizide","Linagliptin","Pioglitazone","Empagliflozin","Acarbose"],a:3,r:"โจทย์ไม่ได้ถามเพียง glucose lowering. Key clues คือ T2DM + CKD + persistent A3 albuminuria + eGFR 45 แม้ได้รับ RAS blockade แล้ว. SGLT2 inhibitor ที่มี demonstrated benefit ลด CKD progression และ cardiovascular events และใช้ได้ในช่วง eGFR นี้ตามแนวทางปัจจุบัน",wrong:["Glipizide ลด glucose ได้ แต่ไม่มี cardiorenal outcome benefit แบบ SGLT2i และ CKD เพิ่ม hypoglycemia risk","Linagliptinใช้ใน CKD ได้สะดวก แต่ไม่ตอบโจทย์ลด CKD progression/CV events ได้เท่า SGLT2i","Pioglitazoneลด HbA1c ได้แต่ไม่มี kidney-protective indication แบบ SGLT2i และต้องระวัง fluid retention","ถูก: empagliflozinตอบทั้ง kidney และ cardiovascular objective ซึ่งเป็น clinical priority ของโจทย์","Acarboseช่วย postprandial glucose แต่ไม่มี cardiorenal outcome benefit ที่โจทย์กำลังถาม"]},
{stage:"6 เดือนต่อมาได้รับ losartan + empagliflozin. BP 126/74 mmHg, HbA1c 7.2%, eGFR 44, UACR 360 mg/g, K⁺ 4.7 mEq/L. Albuminuria ลดลงแต่ยังคงสูง",p:"แพทย์ต้องการลด residual cardiorenal risk เพิ่มเติม ข้อใดเหมาะสมที่สุด?",o:["เพิ่ม ACE inhibitor ร่วมกับ losartan","พิจารณา finerenone พร้อมติดตาม serum K⁺","เพิ่ม spironolactone โดยไม่ต้องติดตาม K⁺","หยุด empagliflozin เพราะ HbA1c ถึงเป้าหมาย","เพิ่ม aliskiren ร่วมกับ losartan"],a:1,r:"ผู้ป่วย T2DM+CKD ยังมี persistent albuminuria แม้ได้รับ maximally tolerated RAS blockade และ SGLT2i. Nonsteroidal MRA เช่น finerenone มีหลักฐานลด CKD progression/CV events ในผู้ป่วยที่เหมาะสม แต่ต้องคัดกรองและติดตาม potassium เนื่องจาก hyperkalemia risk",wrong:["Dual ACEI+ARB ไม่แนะนำเพื่อเพิ่ม renal protection เพราะเพิ่ม AKI/hyperkalemia โดยไม่มี net benefit","ถูก: finerenoneเป็น evidence-based add-on ใน selected T2DM+CKD with albuminuria หลัง foundational therapy และต้อง monitor K⁺","Spironolactoneมี hyperkalemia risk และคำว่าไม่ต้องติดตาม K⁺ ทำให้ตัวเลือกนี้ไม่ปลอดภัย","SGLT2iมี cardiorenal benefit ที่ไม่ขึ้นกับ HbA1cเพียงอย่างเดียว จึงไม่หยุดเพียงเพราะ HbA1cถึงเป้าหมาย","Dual RAAS blockade ด้วย direct renin inhibitor + ARB ไม่ใช่ strategy เพื่อ residual albuminuria และเพิ่ม adverse events"]}
];

const extraCases=[
{title:"Acute decompensated HFrEF",base:"ชาย 67 ปี HFrEF LVEF 28% มาด้วย orthopnea, edema, JVP สูง, BP 154/92, HR 96, SCr 1.3, K 4.4 ใช้ enalapril, carvedilol และ furosemide",q:[
["ขณะมี congestion ชัดเจน เป้าหมาย pharmacotherapy เร่งด่วนข้อใดเหมาะสมที่สุด?",["เพิ่ม IV loop diuretic และประเมิน response","หยุด diuretic แล้วเพิ่ม fluid","เพิ่ม verapamil","เริ่ม NSAID","เพิ่ม pioglitazone"],0,"อาการและตรวจร่างกายชี้ volume overload ใน ADHF จึงต้อง decongest พร้อมติดตาม perfusion/renal function"],
["หลัง diuresis อาการดีขึ้น BP 118/72, euvolemic, eGFR 58, K 4.5 ก่อนจำหน่ายควรทบทวนอะไร?",["เฉพาะ furosemide dose","การได้รับ guideline-directed HFrEF therapies และ tolerance","หยุด beta-blocker ถาวร","ให้ diltiazem เพิ่ม","งดติดตาม K"],1,"ก่อนจำหน่ายควร optimize foundational HFrEF therapy ตาม hemodynamic/renal tolerance ไม่ใช่ดู diuretic อย่างเดียว"],
["หลังเพิ่ม MRA ควรติดตามอะไรเด่นที่สุด?",["TSH","K⁺ และ renal function","amylase","INR ทุกคน","uric acid อย่างเดียว"],1,"MRA มี hyperkalemia/renal safety considerations จึงต้องติดตาม K และ kidney function"],
["ผู้ป่วยถามว่าควรติดตามอะไรที่บ้าน?",["น้ำหนักทุกวัน อาการหอบ/บวม และ adherence","HbA1c ทุกเช้าแม้ไม่เป็นเบาหวาน","หยุดยาทุกครั้งที่น้ำหนักลด","เพิ่มเกลือเมื่อบวม","ใช้ NSAID เมื่อแน่นหน้าอก"],0,"daily weight และ congestion symptoms ช่วยตรวจจับ fluid retention และสนับสนุน self-management"]]},
{title:"Community-acquired pneumonia",base:"หญิง 72 ปี ไข้ ไอ productive cough, RR 28, CXR right lower lobe infiltrate, eGFR 38, มี COPD และไม่มีประวัติ MRSA/Pseudomonas",q:[
["การเลือก empiric antibiotic ควรอาศัยอะไรเป็นหลัก?",["severity, comorbidity, local resistance และ risk factors","สีเสมหะอย่างเดียว","เลือก broadest regimen ทุกคน","eGFR อย่างเดียว","อายุอย่างเดียว"],0,"CAP regimen ต้องอิง severity/comorbidities และ resistant-pathogen risk ไม่ใช่ตัวแปรเดียว"],
["หาก antibiotic ที่เลือกขับทางไต ประเด็นใดสำคัญ?",["ใช้ขนาดมาตรฐานทุกคน","ประเมิน renal dosing ตามยาและ kidney function","ลดทุกยา 50%","เพิ่ม dose เพราะสูงอายุ","งด antibiotic"],1,"renal adjustment เป็น drug-specific และต้องอิง kidney function/PK"],
["48–72 ชม. อาการดีขึ้น culture ไม่พบเชื้อดื้อ หลัก stewardship ใดเหมาะสม?",["เพิ่ม antibiotic ตัวที่สอง","de-escalate/ใช้ spectrum ที่เหมาะสมและกำหนด duration","ต่อ broad spectrum 21 วันทุกคน","เปลี่ยนยาทุกวัน","หยุดทันทีแม้ยัง unstable"],1,"เมื่อข้อมูลและ response ชัด ควรลด spectrum และใช้ duration ที่เหมาะสม"],
["ก่อนจำหน่ายควรประเมินอะไร?",["clinical stability, oral intake, adherence และ red flags","CXR ต้องหายสนิทก่อนทุกคน","หยุดยาทันทีเมื่อไม่มีไข้ 1 ครั้ง","ไม่ต้องทบทวน inhaler","ให้ antibiotic สำรองทุกครั้ง"],0,"discharge ต้องดู clinical stability และความสามารถใช้ยาต่อเนื่องพร้อม counseling"]]},
{title:"Atrial fibrillation + CKD",base:"หญิง 79 ปี nonvalvular AF, HTN, prior ischemic stroke, น้ำหนัก 54 kg, SCr 1.6 mg/dL ไม่มี active bleeding",q:[
["เมื่อประเมินแผนรักษาระยะยาว ข้อใดเหมาะสมที่สุด?",["ให้ aspirin 81 mg/day เพราะ bleeding risk ต่ำกว่า anticoagulant","ประเมินและให้ oral anticoagulation ตาม thromboembolic risk แม้วันนี้ไม่มีอาการ AF","ทำ rhythm control ให้สำเร็จก่อนแล้วค่อยพิจารณา anticoagulation","ให้ dual antiplatelet therapy แทน anticoagulation เพราะเคย ischemic stroke","รอให้ AF burden สูงกว่า 24 ชั่วโมงก่อนเริ่ม stroke prevention"],1,"prior ischemic stroke ร่วม AF ทำให้ thromboembolic risk สูง; symptom หรือ rhythm status ไม่ได้ใช้แทน stroke-risk assessment และ antiplatelet ไม่ทดแทน OAC เมื่อมีข้อบ่งใช้"],
["หากพิจารณา apixaban สำหรับ non-valvular AF ข้อมูลใดต้องใช้ประเมินเกณฑ์ลดขนาดยา?",["อายุ น้ำหนัก และ SCr","LDL และ HbA1c","BP อย่างเดียว","ประวัติเลือดออกอย่างเดียว","ค่า LFT อย่างเดียว"],0,"Apixaban สำหรับ non-valvular AF ใช้ขนาดมาตรฐาน 5 mg วันละ 2 ครั้ง และลดเป็น 2.5 mg วันละ 2 ครั้งเมื่อผู้ป่วยเข้าเกณฑ์อย่างน้อย 2 ใน 3 ข้อ ได้แก่ (1) อายุ ≥80 ปี (2) น้ำหนักตัว ≤60 kg และ (3) serum creatinine ≥1.5 mg/dL. ผู้ป่วยรายนี้อายุ 79 ปี น้ำหนัก 54 kg และ SCr 1.6 mg/dL จึงเข้าเกณฑ์ 2 ข้อ คือ น้ำหนัก ≤60 kg และ SCr ≥1.5 mg/dL ทำให้เข้าเกณฑ์ลดขนาดเป็น 2.5 mg BID. จุดสำคัญคือเกณฑ์นี้เป็น criteria เฉพาะของ apixaban ใน NVAF ไม่ใช่การลดขนาดจาก eGFR เพียงค่าเดียว และยังต้องทบทวน renal/hepatic function, bleeding risk และ drug interactions เพื่อความปลอดภัย"],
["ผู้ป่วยมี osteoarthritis และใช้ naproxen 250 mg BID เกือบทุกวัน หลังเริ่ม apixaban ไม่มีเลือดออกและ Hb คงที่ แนวทางใดเหมาะสมที่สุด?",["ใช้ naproxen ต่อและเพิ่ม PPI เพราะจะชดเชย bleeding risk ได้ทั้งหมด","หยุด naproxen ที่ใช้ประจำ ประเมินอาการปวด และพิจารณา acetaminophen หรือ topical NSAID ตามความเหมาะสม โดยคง apixaban ตามข้อบ่งใช้","ลด apixaban เป็น 2.5 mg BID เพื่อให้ใช้ naproxen ต่อได้","เปลี่ยนเป็น celecoxib แล้วใช้ต่อได้โดยไม่ต้องประเมิน bleeding risk","หยุด apixaban เฉพาะวันที่ใช้ naproxen"],1,"คำตอบที่ถูกคือหยุด/หลีกเลี่ยง systemic naproxen ที่ใช้เป็นประจำและคง apixaban ตามข้อบ่งใช้. NSAID เป็น modifiable bleeding-risk medication ในผู้ใช้ oral anticoagulation; การเพิ่ม PPI อาจลด upper-GI bleeding บางส่วน แต่ไม่ทำให้ความเสี่ยง bleeding ทั้งระบบหรือ renal/CV toxicity ของ NSAID หายไป. ห้ามลด apixaban แบบ off-label หรือหยุดเป็นบางวันเพียงเพื่อให้ใช้ NSAID เพราะอาจลดประสิทธิผลป้องกัน stroke. ควรประเมินสาเหตุและความรุนแรงของ OA pain แล้วเลือก non-NSAID หรือ topical strategy ตามความเหมาะสม"],
["การติดตาม apixaban ระยะยาวข้อใดเหมาะสมที่สุด?",["ติดตาม CBC, renal/hepatic function ตามความเหมาะสม, bleeding/thrombosis, adherence และยาร่วม โดยไม่ใช้ INR เพื่อ titrate apixaban","ตรวจ anti-Xa level routine ทุก visit และปรับขนาดตามระดับยา","ตรวจ PT/INR ทุก 4 สัปดาห์และปรับ apixaban ให้ INR 2–3","หาก SCr คงที่ 1 ปีสามารถงดประเมิน renal function และ interaction ต่อได้","หยุด apixaban เมื่อ ECG ครั้งหนึ่งเป็น sinus rhythm"],0,"Apixaban เป็น direct factor Xa inhibitor จึงไม่ใช้ PT/INR เพื่อ titrate ขนาดแบบ warfarin และไม่แนะนำ routine anti-Xa monitoring ในผู้ป่วยทั่วไป. การติดตามระยะยาวควรประเมิน CBC เพื่อหา occult/overt bleeding, renal function และ hepatic function ตาม baseline/อายุ/ความเปลี่ยนแปลงทางคลินิก, อาการ bleeding หรือ thromboembolism, adherence และยาร่วมที่เพิ่ม bleeding หรือมี CYP3A4/P-gp interaction. สำหรับผู้ป่วยรายนี้อายุ 79 ปี SCr 1.6 mg/dL และน้ำหนัก 54 kg ต้องติดตาม renal function อย่างใกล้ชิดและทบทวน dose criteria เมื่อข้อมูลผู้ป่วยเปลี่ยน แต่ไม่ใช้ INR เป้าหมาย 2–3 ซึ่งเป็นแนวคิดของ warfarin"]]},
{title:"Gout + CKD",base:"ชาย 58 ปี gout มี acute monoarthritis ข้อ MTP, CKD G3b eGFR 36, ใช้ allopurinol 200 mg/day สม่ำเสมอ, ไม่มีไข้",q:[
["ระหว่าง acute flare ควรจัดการ allopurinol อย่างไร?",["หยุดทันทีจนหายปวด","ให้ต่อ และรักษา acute flare ด้วย anti-inflammatory ที่เหมาะกับผู้ป่วย","เพิ่มเป็น 600 mg ทันที","เปลี่ยนเป็น probenecid","หยุดถาวร"],1,"ผู้ที่ใช้ ULT อยู่ไม่ควรหยุดเพียงเพราะเกิด flare; ต้องรักษา flare และคง long-term strategy"],
["การเลือกยารักษา flare ต้องคำนึงอะไรเด่นในรายนี้?",["CKD และข้อห้าม/interaction ของ NSAID, colchicine, steroid","LDL อย่างเดียว","UACR อย่างเดียว","หยุดทุกยา","ใช้ aspirin high dose"],0,"CKD เปลี่ยน safety profile ของ anti-inflammatory options จึงต้อง individualized"],
["หลัง flare สงบ urate ยังสูงกว่าเป้าหมาย หลักการใดเหมาะสม?",["treat-to-target และ titrate ULT พร้อม monitoring","คง dose เดิมตลอดแม้ urate สูง","หยุด ULT เมื่อไม่มีปวด","ใช้ antibiotic","ใช้ NSAID ระยะยาวแทน ULT"],0,"long-term gout management ใช้ urate target และปรับ ULT ตาม tolerance/monitoring"],
["counseling ใดสำคัญ?",["adherence ต่อ ULT และอธิบายว่า flare ช่วงต้นไม่ได้แปลว่ายาไม่ได้ผล","หยุด allopurinol ทุกครั้งที่ปวด","จำกัดน้ำเพื่อป้องกันบวม","กิน organ meat เพิ่ม","ใช้สมุนไพรแทนยา"],0,"adherence และความเข้าใจเรื่อง flare/ULT ช่วยลดการหยุดยาที่ไม่จำเป็น"]]},
{title:"Major depression + medication safety",base:"หญิง 34 ปี major depressive disorder เริ่ม sertraline 50 mg/day 2 สัปดาห์ มี nausea เล็กน้อย ยังเศร้า ไม่มี suicidal plan และเพิ่งซื้อ dextromethorphan แก้ไอ",q:[
["การประเมิน response หลัง 2 สัปดาห์ควรตีความอย่างไร?",["ถือว่าล้มเหลวและเปลี่ยนยาทันที","ประเมิน adherence/tolerability/suicidality และให้เวลารักษาเพียงพอก่อนสรุป failure","เพิ่มสองเท่าทันทีทุกคน","หยุดเพราะ nausea","เปลี่ยนเป็น benzodiazepine monotherapy"],1,"antidepressant response ต้องใช้เวลาและ early follow-up เน้น safety/tolerability/adherence"],
["ประเด็นยาร่วมใดควรทบทวน?",["dextromethorphan เพิ่ม serotonergic burden","paracetamol ทำให้ serotonin syndrome เสมอ","ORS ห้ามใช้","saline nasal spray ห้ามใช้","vitamin C ลด sertraline level"],0,"dextromethorphan มี serotonergic potential และควรประเมินร่วมกับ SSRI"],
["อาการใดควรให้ผู้ป่วยรีบประเมิน?",["agitation ร่วม clonus/hyperreflexia/ไข้","nausea เล็กน้อยอย่างเดียว","ง่วงหลังนอนน้อย","หิวก่อนอาหาร","ปากแห้งเล็กน้อย"],0,"neuromuscular/autonomic/mental-status findings สามารถบ่ง serotonin toxicity"],
["คำแนะนำใดเหมาะสม?",["ไม่หยุด sertraline เองกะทันหันและติดตามอาการ/ความเสี่ยงตามนัด","หยุดทันทีเมื่อรู้สึกดี 1 วัน","เพิ่ม dose เองเมื่อเศร้า","ดื่ม alcohol ช่วยนอน","ไม่ต้องติดตาม suicidality"],0,"shared follow-up และไม่ปรับยาเองเป็นหลัก medication safety สำคัญ"]]},
{title:"Methotrexate toxicity in RA",base:"หญิง 51 ปี RA ใช้ methotrexate 15 mg once weekly + folic acid มี oral ulcers, ไข้, WBC 2,100/mm³, platelet 82,000/mm³ หลังได้ TMP-SMX จากคลินิก",q:[
["ภาวะใดต้องสงสัยมากที่สุด?",["RA flare","methotrexate toxicity with myelosuppression","iron deficiency","viral URI อย่างเดียว","steroid withdrawal"],1,"mucositis + cytopenias + interacting antifolate drug เป็น pattern ของ methotrexate toxicity"],
["การประเมินเร่งด่วนควรรวมอะไร?",["CBC, renal/liver function, infection assessment และ medication history","lipid อย่างเดียว","HbA1c อย่างเดียว","RF titer อย่างเดียว","DEXA อย่างเดียว"],0,"toxicity severity และ clearance ขึ้นกับ marrow, renal/hepatic status และ infection"],
["ยาร่วมใดเป็น key interaction?",["TMP-SMX","topical moisturizer","normal saline","calcium carbonate","acetaminophen single dose"],0,"TMP-SMX ร่วม methotrexate เพิ่ม antifolate/myelosuppression toxicity"],
["หลังพ้นเหตุการณ์ counseling ใดสำคัญที่สุด?",["ย้ำ once-weekly dosing, folate plan และแจ้งก่อนเริ่ม antibiotic/OTC ใหม่","เปลี่ยน methotrexate เป็น daily","หยุด folate ถาวร","เพิ่ม dose เมื่อปวด","ไม่ต้องตรวจ CBC"],0,"weekly dosing error และ interacting drugs เป็น preventable medication-safety hazards"]]},
{title:"COPD exacerbation",base:"ชาย 69 ปี COPD มี dyspnea มากขึ้น, sputum volume/purulence เพิ่ม, SpO₂ 87% room air, RR 26, ไม่มี shock",q:[
["เป้าหมาย oxygen therapy ควรเป็นอย่างไร?",["ให้ออกซิเจนแบบ controlled และติดตาม saturation/CO₂ risk","ให้ออกซิเจน 100% ทุกคนโดยไม่ติดตาม","งด oxygen เพราะ COPD","ให้เฉพาะเมื่อหมดสติ","ใช้ antibiotic แทน oxygen"],0,"AECOPD ต้องแก้ hypoxemia แบบ controlled พร้อมเฝ้าระวัง hypercapnia ในผู้เสี่ยง"],
["initial bronchodilator strategy ใดเหมาะสม?",["short-acting bronchodilator เช่น SABA ± SAMA","LABA monotherapy ครั้งเดียว","หยุด bronchodilator","theophylline IV routine","ICS อย่างเดียว"],0,"short-acting inhaled bronchodilator เป็นแกน initial symptomatic therapy"],
["เมื่อมี increased sputum purulence ร่วม volume และ dyspnea การพิจารณาใดเหมาะสม?",["ประเมินข้อบ่งใช้ antibiotic ตาม exacerbation features/severity","antibiotic ห้ามใช้ทุกกรณี","ให้ macrolide ตลอดชีวิตทันที","ใช้ antifungal","รอ culture 7 วันก่อนรักษา"],0,"cardinal symptoms โดยเฉพาะ purulence ช่วยพิจารณา antibiotic ใน AECOPD"],
["หลังพ้น exacerbation ควรทำอะไร?",["ทบทวน maintenance inhaler, technique, smoking status, vaccination และ prevention","หยุด maintenance inhaler","ให้ oral steroid ต่อเนื่องถาวร","ไม่ต้อง follow-up","ใช้ SABA อย่างเดียวตลอด"],0,"post-exacerbation review ลด recurrence และแก้ modifiable risks"]]}
];
const labels=["A","B","C","D","E"];

const trapPools:Record<string,string[][]>={
"Acute decompensated HFrEF":[
["เพิ่ม IV loop diuretic และประเมิน urine output/น้ำหนัก/renal function","เพิ่ม oral furosemide ขนาดเดิมและรอดู 48 ชั่วโมง","ให้ IV fluid challenge เพราะ creatinine อาจสูงขึ้นจาก diuretic","หยุด carvedilol ทันทีแม้ไม่มี shock","เพิ่ม thiazolidinedioneเพื่อเพิ่ม cardiac output"],
["ทบทวนและ optimize ARNI/ACEI/ARB, evidence-based beta-blocker, MRA และ SGLT2i ตาม tolerance","คงเฉพาะ loop diuretic เพราะอาการหอบดีแล้ว","เพิ่ม verapamilเพื่อควบคุม HR แม้ HFrEF","หยุด beta-blockerก่อนจำหน่ายเพื่อป้องกัน decompensation","เริ่ม digoxinแทน foundational therapyทั้งหมด"],
["ติดตาม K⁺ และ renal function หลังเริ่ม/ปรับ MRA","ติดตาม BNP อย่างเดียวเพื่อปรับ spironolactone","ตรวจ INR เพื่อ titrate MRA","ติดตาม uric acid เป็น primary safety parameter","ไม่ต้องตรวจ lab หาก K baseline ปกติ"],
["ชั่งน้ำหนักทุกวันและเฝ้าระวัง dyspnea/edema พร้อมแผนเมื่ออาการแย่ลง","จำกัดน้ำ <500 mL/day ในผู้ป่วย HFrEF ทุกคน","เพิ่มเกลือเมื่อรู้สึกเวียนศีรษะโดยไม่วัด BP","หยุด diureticเองเมื่อน้ำหนักลด 1 kg","ใช้ NSAID PRN เมื่อแน่นหน้าอก"]
],
"Community-acquired pneumonia":[
["เลือก regimen ตาม severity, comorbidity, local resistance และ MRSA/Pseudomonas risk","ให้ antipseudomonal + anti-MRSA ทุกคนที่อายุ >65 ปี","เลือก fluoroquinoloneเพียงเพราะรับประทานวันละครั้งโดยไม่ดู risk","รอ sputum culture ก่อนเริ่มยาทุกราย","ใช้ procalcitonin ต่ำเพียงค่าเดียวเพื่อปฏิเสธ bacterial CAP"],
["ประเมิน renal dose adjustment แบบ drug-specific ตาม kidney function","ลด antibiotic ทุกชนิด 50% เมื่อ eGFR <60","ใช้ SCr เพียงค่าเดียวโดยไม่ประเมิน renal function","คง full dose ทุกยาเพราะ infectionรุนแรง","ปรับ dose ตามอายุอย่างเดียว"],
["de-escalate เมื่อข้อมูล microbiology/clinical response สนับสนุนและกำหนด duration ตาม stability","คง broad spectrum จนครบ 14 วันเพื่อป้องกัน relapse","หยุด antibiotic ทันทีเมื่อ afebrile 24 ชม.","เพิ่ม second agent แม้ culture susceptible ต่อ regimen เดิม","เปลี่ยน antibiotic ทุก 48 ชม.เพื่อป้องกัน resistance"],
["ประเมิน clinical stability, oral intake, oxygen need, adherence และ red flags ก่อนจำหน่าย","รอ CXR กลับปกติก่อนจำหน่ายทุกคน","จำหน่ายเมื่อไข้ลดโดยไม่ดู oxygen/hemodynamics","ให้ antibioticสำรองอีกชุดเพื่อใช้เอง","หยุด maintenance COPD inhalerจน pneumoniaหาย"]
],
"Gout + CKD":[
["ให้ allopurinolต่อ และรักษา flare ด้วย anti-inflammatory ที่เหมาะกับ CKD","หยุด allopurinolระหว่าง flareเพื่อไม่ให้ urateแกว่ง","เพิ่ม allopurinolเป็นสองเท่าระหว่าง acute pain","เปลี่ยนเป็น probenecidเพราะ eGFRต่ำ","ใช้ aspirinขนาดสูงเป็น first-line flare therapy"],
["เลือก colchicine/NSAID/corticosteroid โดยดู CKD, interaction และข้อห้ามรายบุคคล","ใช้ indomethacinเป็น first-lineทุกคนเพราะ goutตอบสนองดี","ใช้ colchicineขนาดปกติซ้ำบ่อยโดยไม่ดู renal function/interactions","หลีกเลี่ยง corticosteroidทุกกรณีใน CKD","ใช้ opioidแทน anti-inflammatoryเป็น routine"],
["ใช้ treat-to-target urate และ titrate ULT อย่างค่อยเป็นค่อยไปพร้อม monitoring","คง allopurinol 200 mgตลอดเพราะ CKDห้าม titrate","หยุด ULTเมื่อไม่มี flare 6 เดือน","เปลี่ยน ULTทุกครั้งที่ urateยังสูงหลังตรวจครั้งเดียว","ใช้ chronic NSAIDแทนการปรับ ULT"],
["อธิบาย adherence, flare prophylaxis/expectation และไม่หยุด ULTเองเมื่อ flare","หยุด allopurinolทันทีเมื่อปวดข้อ","งดน้ำเพื่อไม่ให้ข้อบวม","หลีกเลี่ยงอาหาร purineอย่างเดียวเพียงพอไม่ต้องใช้ ULT","เพิ่ม allopurinolเองเมื่อกินอาหาร purineสูง"]
],
"Major depression + medication safety":[
["ให้ sertraline ต่อในขนาดเดิมพร้อมประเมิน adherence, adverse effects และ suicidality แล้ว reassess หลัง adequate trial","เพิ่ม sertraline เป็น 100 mg/day ทันทีเพราะ PHQ-9 ยังสูง","switch เป็น escitalopram ทันทีเพราะ nausea แสดง intolerance","augment ด้วย aripiprazole หลังรักษาเพียง 2 สัปดาห์","หยุด antidepressant 1 สัปดาห์แล้วประเมินใหม่"],
["หลีกเลี่ยง dextromethorphan และเลือก non-serotonergic symptomatic treatment พร้อมให้คำแนะนำ red flags","เปลี่ยน dextromethorphan เป็น tramadol เพราะ interaction กับ SSRI น้อยกว่า","ให้ dextromethorphan ต่อแต่ลด sertraline เหลือ 25 mg/day","ให้ dextromethorphan ต่อพร้อม cyproheptadine prophylaxis","หยุด sertraline 1 dose ในวันที่ใช้ dextromethorphan"],
["serotonin toxicity จาก serotonergic combination โดย clonus/hyperreflexia เป็น key findings","SSRI-induced akathisia เพราะ agitation เป็นอาการเด่น","neuroleptic malignant syndrome แม้ไม่มี dopamine antagonist/lead-pipe rigidity","anticholinergic toxicity เพราะมี autonomic activation","panic attack เพราะ vital signs เปลี่ยนและกระสับกระส่าย"],
["หยุด serotonergic culprit agents, supportive care และประเมิน severity; พิจารณา benzodiazepine/cyproheptadineตามความรุนแรง","ลด sertralineครึ่งหนึ่งและ observe ที่บ้านแม้มี clonus","เปลี่ยน sertralineเป็น fluoxetineทันที","ให้ bromocriptineเป็น first-line เพราะเป็น serotonin antagonist","ให้ acetaminophenอย่างเดียวเพราะไข้เป็นกลไกหลัก"]
],
"Methotrexate toxicity in RA":[
["สงสัย methotrexate toxicity with myelosuppression/mucositis","วินิจฉัย RA flareเพราะมีไข้และอ่อนเพลีย","สรุปเป็น iron deficiencyจาก plateletต่ำ","ให้ methotrexate doseถัดไปก่อนแล้วค่อยตรวจ CBC","ถือว่า oral ulcerเป็น adverse effectเล็กน้อยไม่เกี่ยวกับ cytopenia"],
["ประเมิน CBC, renal/hepatic function, infection และ medication historyอย่างเร่งด่วน","ตรวจ ESR/CRPอย่างเดียวเพื่อแยก RA flare","ตรวจ folateอย่างเดียวแล้วให้กลับบ้าน","รอ CBCซ้ำเดือนหน้าเพราะ methotrexateเป็น low dose","ตรวจ RF/anti-CCPซ้ำเพื่อประเมิน toxicity"],
["TMP-SMX เป็น interactionสำคัญที่เพิ่ม antifolate/myelosuppression risk","amoxicillinทุกขนาดเป็นสาเหตุจำเพาะที่สุดโดยไม่ดูบริบท","calcium carbonateเป็น interactionหลัก","topical moisturizerเพิ่ม methotrexate level","normal salineทำให้ marrow suppression"],
["ย้ำ once-weekly dosing, folate plan, lab monitoring และแจ้งก่อนเริ่ม antibiotic/OTC","แบ่ง weekly doseเป็น dailyเพื่อให้ระดับยาคงที่","หยุด folic acidเพื่อเพิ่ม efficacy","เพิ่ม methotrexateเองเมื่อข้อปวด","ไม่ต้อง CBCหากใช้มานาน"]
],
"COPD exacerbation":[
["ให้ controlled oxygen โดยตั้งเป้า SpO₂ ประมาณ 88–92% ระหว่างประเมินภาวะ hypercapnia/ABG","ให้ออกซิเจนความเข้มข้นสูงเพื่อให้ SpO₂ ≥98% ทันทีและคงไว้","งด oxygen จนได้ ABG เพราะเสี่ยง CO₂ retention","เริ่ม NIV ทันทีจาก SpO₂ 87% เพียงอย่างเดียวโดยไม่ประเมิน acidosis/work of breathing","ให้ nebulized bronchodilator อย่างเดียวแล้วรอดู SpO₂"],
["ใช้ short-acting bronchodilator เช่น SABA ± SAMA เป็น initial therapy","เพิ่ม LABA monotherapyเป็น rescue","ใช้ IV theophylline routineก่อน inhaled bronchodilator","ใช้ ICSอย่างเดียวเพื่อ reliefทันที","หยุด bronchodilatorเพราะ tachycardia risk"],
["พิจารณา antibiotic เมื่อมี cardinal symptoms โดยเฉพาะ purulenceและตาม severity","ให้ antibioticทุก exacerbationแม้ไม่มี purulence/ventilation indication","หลีกเลี่ยง antibioticเสมอเพราะ COPDเป็น inflammatory disease","รอ sputum cultureก่อนเริ่มยาทุกราย","ให้ macrolide prophylaxisทันทีระหว่าง acute episodeแทน courseรักษา"],
["ทบทวน maintenance regimen, inhaler technique, smoking cessation, vaccination และ prevention","ให้ oral steroidระยะยาวเพื่อป้องกัน exacerbationทุกคน","หยุด maintenance inhalerเมื่อพ้น acute episode","ใช้ SABA-onlyระยะยาวแม้มี exacerbationบ่อย","ไม่ต้อง follow-upหาก SpO₂กลับ baseline"]
]
};
const allCases=[
{title:caseTitle,items:qs.map(q=>({stage:q.stage,p:q.p,o:q.o,a:q.a,r:q.r,ref:"ADA Standards of Care in Diabetes 2026; KDIGO 2024 CKD Guideline"}))},
...(extraCases as any[]).map((c:any)=>({title:c.title,items:(c.q as any[]).map((q:any,qi:number)=>{const pool=trapPools[c.title]?.[qi];return {stage:c.base,p:q[0],o:pool??q[1],a:0,r:q[3],ref:"Current disease-specific guideline / official drug information; verify version at editorial review"};})}))
];
const answerCycle=[2,3,1,4,0];
export const PC1_PILOT_032:McqQuestion[]=allCases.flatMap((c,ci)=>c.items.map((q:any,qi:number)=>{
 const correct=q.o[q.a]; const wrong=q.o.filter((_:string,j:number)=>j!==q.a); const pos=answerCycle[(ci*4+qi)%5]; const opts=[...wrong];opts.splice(pos,0,correct);const ans=labels[pos];
 return {id:`pc1pilot${String(ci*4+qi+1).padStart(3,"0")}`,subject_id:"pc1",exam_type:"PLE-PC",exam_source:"PharmRU PC1 Progressive Cases",exam_day:null,question_number:ci*4+qi+1,scenario:`Case ${ci+1}/8 — ${c.title}\n${q.stage}\n\nคำถาม ${qi+1}/4: ${q.p}`,image_url:null,choices:opts.map((text:string,j:number)=>({label:labels[j],text})),correct_answer:ans,explanation:`Clinical reasoning: ${q.r}\n\nMonitoring: ประเมิน efficacy, safety, organ function, adherence และ adverse effects ที่สัมพันธ์กับ intervention\n\nReference: ${q.ref}`,detailed_explanation:{summary:`เฉลย ${ans}: ${correct}`,reason:`【วิเคราะห์โจทย์และ Clinical reasoning แบบละเอียด】\n${q.r}\n\n【ข้อมูลสำคัญจากผู้ป่วย】\n${q.stage}\n\n【เหตุผลที่คำตอบนี้ดีที่สุด】\n${correct} เป็น single best answer เพราะตอบ clinical priority ที่โจทย์กำลังทดสอบโดยตรง ต้องเชื่อม diagnosis + severity + โรคร่วม + organ function + current medications + ข้อมูลที่เปลี่ยนในแต่ละช่วงของ progressive case เข้าด้วยกัน ไม่ใช่เลือกจากชื่อโรคเพียงอย่างเดียว\n\n【หลักการ/เกณฑ์ที่ต้องจำ】\n${q.r}\nหากหัวข้อนี้มี dose threshold, laboratory cutoff, renal/hepatic adjustment, duration หรือ monitoring interval ให้ใช้ค่าตาม guideline/official prescribing information ของยานั้นและตรวจสอบเวอร์ชันล่าสุดก่อนนำไปใช้จริง\n\n【การนำไปใช้ในผู้ป่วยรายนี้】\nประเมิน response หลัง intervention พร้อมทบทวน adverse effects, adherence, drug interaction และ organ function ที่สัมพันธ์กับยา หากข้อมูลใหม่เปลี่ยน risk-benefit ต้องปรับแผน ไม่ควรรักษาตามคำตอบเดิมแบบอัตโนมัติ\n\n【Monitoring / Follow-up】\nติดตาม efficacy endpoint ของโรค, vital signs ที่เกี่ยวข้อง, renal/hepatic function, electrolyte/CBC/bleeding/infection ตามชนิดยา รวมถึง adherence และอาการไม่พึงประสงค์\n\n【Reference】\n${q.ref}`,choices:opts.map((text:string,j:number)=>({label:labels[j],text,is_correct:j===pos,explanation:j===pos?`ถูก — ${q.r} สำหรับผู้ป่วยรายนี้ข้อมูลสำคัญคือ ${q.stage}`:`ไม่เลือก — ${text} เป็น distractor ที่มีความเป็นไปได้ทางคลินิก แต่ด้อยกว่า ${correct} เมื่อพิจารณา timing, severity, organ function, interaction, outcome benefit และ monitoring ของผู้ป่วยรายนี้ (${q.stage})`})),key_takeaway:`Exam Pearl: ${q.r} | เวลาทำข้อสอบให้หา key clue, cutoff/dose criterion (ถ้ามี), contraindication/interaction และ monitoring ที่สัมพันธ์กับคำตอบ`},difficulty:qi===0?"medium-hard":"hard",is_ai_enhanced:true,ai_notes:"Original PharmRU progressive PC1 case; clinical/editorial review recommended before commercial publication.",status:"active",created_at:"2026-09-22 14:00:00",mcq_subjects:{id:"pc1",name:"PC1",name_th:"บริบาลเภสัชกรรม PC1",icon:"🩺",exam_type:"PLE-PC",question_count:32,created_at:"2026-09-22 14:00:00"}};
}));
