#!/usr/bin/env python3
"""Build supabase/seed_pharmacy_law_day1.sql from batch JSON files.

Usage: python3 scripts/build-law-day1-seed.py law_A.json law_B.json law_C.json law_D.json
Ids are md5('pharmacy-law-day1-<n>') so re-running the SQL is idempotent.
"""
import hashlib, json, re, sys
from collections import Counter

OUT = "supabase/seed_pharmacy_law_day1.sql"

def check(q, where):
    assert isinstance(q["scenario"], str) and q["scenario"].strip(), where
    labels = [c["label"] for c in q["choices"]]
    assert labels == list("ABCDE"), (where, labels)
    ans = q["correct_answer"]
    assert ans in "ABCDE", where
    assert q["difficulty"] in ("easy", "medium", "hard"), where
    de = q["detailed_explanation"]
    marked = [c["label"] for c in de["choices"] if c.get("is_correct") is True]
    assert marked == [ans], (where, marked, ans)
    m = re.search(r"คำตอบที่ถูกต้อง\s*[:：]?\s*(?:ข้อ\s*)?([A-E])\b", de["summary"])
    assert m and m.group(1) == ans, (where, de["summary"][:60])
    assert de.get("reason") and de.get("key_takeaway"), where

def lit(s):
    return "'" + s.replace("'", "''") + "'"

rows, answers, n = [], Counter(), 0
for path in sys.argv[1:]:
    for i, q in enumerate(json.load(open(path, encoding="utf-8"))):
        check(q, f"{path}[{i}]")
        n += 1
        answers[q["correct_answer"]] += 1
        qid = hashlib.md5(f"pharmacy-law-day1-{n}".encode()).hexdigest()
        tag = q.get("topic_tag", "")
        rows.append(
            f"({lit(qid)}, {n}, {lit(q['scenario'].strip())}, "
            f"{lit(json.dumps(q['choices'], ensure_ascii=False))}::jsonb, {lit(q['correct_answer'])}, "
            f"{lit(json.dumps(q['detailed_explanation'], ensure_ascii=False))}::jsonb, {lit(q['difficulty'])}, "
            f"{lit('law-day1 • ' + tag)})"
        )

print("answer distribution:", dict(sorted(answers.items())))

with open(OUT, "w", encoding="utf-8") as f:
    f.write(f"""-- PLE-CC1 Day 1 · กฎหมายยาและจริยธรรม ({n} ข้อ)
-- Original questions: พ.ร.บ.ยา/GPP, ประมวลกฎหมายยาเสพติด 2564, พ.ร.บ.วิชาชีพ/จรรยาบรรณ,
-- พ.ร.บ.อาหาร/เครื่องสำอาง/เครื่องมือแพทย์/ผลิตภัณฑ์สมุนไพร/คุ้มครองผู้บริโภค, pharmacovigilance.
-- Generated by scripts/build-law-day1-seed.py — idempotent (ON CONFLICT DO NOTHING).
INSERT INTO public.mcq_questions
  (id, subject_id, exam_type, exam_day, question_number, scenario, choices, correct_answer,
   detailed_explanation, difficulty, is_ai_enhanced, ai_notes, status)
SELECT v.id, s.id, 'PLE-CC1', 1, v.qn, v.scenario, v.choices, v.correct_answer,
       v.detailed_explanation, v.difficulty, true, v.ai_notes, 'active'
FROM (VALUES
""")
    f.write(",\n".join(rows))
    f.write("""
) AS v(id, qn, scenario, choices, correct_answer, detailed_explanation, difficulty, ai_notes)
CROSS JOIN (SELECT id FROM public.mcq_subjects WHERE name = 'PharmacyLaw') s
ON CONFLICT (id) DO NOTHING;
""")
print(f"wrote {OUT}: {n} questions")
