import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  'https://knxidnzexqehusndquqg.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtueGlkbnpleHFlaHVzbmRxdXFnIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NDM2OTA3NiwiZXhwIjoyMDg5OTQ1MDc2fQ.t47-1W_kcZL9215ZA9vFEf51sptFWMyUsdHrOCkzPCQ'
);

const EXAM1_ID = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890';
const EXAM2_ID = 'b2c3d4e5-f6a7-8901-bcde-f12345678901';

async function seed() {
  // Insert main exams with specific IDs
  const { data: examData, error: e1 } = await supabase.from('exams').insert([
    { title: 'ภาวะเลือดออกในทางเดินอาหารส่วนบน (Upper GI Bleeding)', category: 'อายุรศาสตร์', difficulty: 'hard', status: 'published', is_free: true, publish_date: '2026-03-25' },
    { title: 'โรคปอดอักเสบรุนแรง (Severe Community-Acquired Pneumonia)', category: 'อายุรศาสตร์', difficulty: 'hard', status: 'published', is_free: false, publish_date: '2026-03-24' },
  ]).select();
  console.log('Main exams:', e1 ? e1.message : 'OK', examData?.map(e => e.id));

  const realExam1Id = examData?.[0]?.id;
  const realExam2Id = examData?.[1]?.id;

  // Insert mock exams (no parts)
  const { error: em } = await supabase.from('exams').insert([
    { title: 'ไส้ติ่งอักเสบเฉียบพลัน (Acute Appendicitis)', category: 'ศัลยศาสตร์', difficulty: 'medium', status: 'published', is_free: true, publish_date: '2026-04-01' },
    { title: 'ไข้ชัก (Febrile Seizure) ในเด็ก', category: 'กุมารเวชศาสตร์', difficulty: 'medium', status: 'published', is_free: false, publish_date: '2026-04-05' },
    { title: 'ครรภ์เป็นพิษ (Preeclampsia)', category: 'สูติศาสตร์-นรีเวชวิทยา', difficulty: 'hard', status: 'published', is_free: false, publish_date: '2026-04-10' },
    { title: 'กระดูกต้นขาหัก (Femoral Shaft Fracture)', category: 'ออร์โธปิดิกส์', difficulty: 'easy', status: 'published', is_free: true, publish_date: '2026-04-15' },
  ]);
  console.log('Mock exams:', em ? em.message : 'OK');

  if (!realExam1Id || !realExam2Id) { console.log('ERROR: No exam IDs!'); return; }

  // Exam 1 parts
  const { error: ep1 } = await supabase.from('exam_parts').insert([
    { exam_id: realExam1Id, part_number: 1, title: 'ตอนที่ 1: ประวัติและการตรวจเบื้องต้น', scenario: 'ชายไทยอายุ 55 ปี มาห้องฉุกเฉินด้วยอาการอาเจียนเป็นเลือดสดประมาณ 2 แก้ว เมื่อ 3 ชั่วโมงก่อนมาโรงพยาบาล มีประวัติปวดข้อเข่าเรื้อรัง ซื้อยา NSAIDs (Ibuprofen) กินเองมานาน 6 เดือน ดื่มเหล้าเป็นประจำ 1-2 แก้ว/วัน\n\nตรวจร่างกาย: BP 90/60 mmHg, HR 120 bpm, RR 24, Temp 37.2\u00B0C\nลักษณะทั่วไป: ซีด เหงื่อออก กระสับกระส่าย\nท้อง: กดเจ็บบริเวณ epigastrium ไม่มี guarding', question: 'จงระบุปัญหาเร่งด่วนที่สุดของผู้ป่วยรายนี้ และแนวทางการ resuscitate เบื้องต้น', answer: 'ปัญหาเร่งด่วนที่สุด: Hypovolemic shock จาก Upper GI bleeding\n\nแนวทาง Resuscitation:\n1. Airway: ประเมินทางเดินหายใจ วางท่าศีรษะสูง\n2. Breathing: ให้ O2 supplement\n3. Circulation: เปิด IV 2 เส้น large bore, ให้ NSS bolus 1-2 L\n4. ส่ง CBC, BUN/Cr, Coagulation, Cross-match 4 units\n5. ใส่ NG tube, Foley catheter\n6. NPO\n7. IV PPI: Omeprazole 80 mg bolus แล้ว 8 mg/hr drip', key_points: ['Hematemesis + Hypotension + Tachycardia = Hypovolemic shock', 'ABC approach ต้องทำทันที', 'IV PPI high dose ลด rebleeding rate', 'Cross-match blood เตรียมไว้เสมอ'], time_minutes: 10 },
    { exam_id: realExam1Id, part_number: 2, title: 'ตอนที่ 2: การส่งตรวจและผลการตรวจ', scenario: 'หลังให้สารน้ำ 2,000 mL: BP 100/70 mmHg, HR 100 bpm\n\nผล Lab:\n- Hb 7.2 g/dL\n- Hct 22%\n- BUN 45 mg/dL, Cr 1.0\n- BUN/Cr ratio = 45\n- Platelet 180,000\n- PT/INR ปกติ', question: 'แปลผล lab และวางแผนการตรวจเพิ่มเติม รวมถึงการเตรียมทำ EGD', answer: 'การแปลผล Lab:\n1. Hb 7.2 = moderate-severe anemia ต้องให้เลือด\n2. BUN/Cr ratio = 45 (>20) สนับสนุน upper GI bleeding\n3. Coagulation ปกติ = ไม่มี coagulopathy\n\nการจัดการ:\n1. Transfuse PRC เป้า Hb > 7-8\n2. เตรียม EGD ภายใน 24 ชม.\n3. IV Erythromycin 250 mg ก่อนทำ EGD 30 นาที\n4. Monitor V/S ทุก 15-30 นาที', key_points: ['BUN/Cr ratio > 20 บ่งชี้ upper GI bleeding', 'Transfusion threshold: Hb < 7 g/dL', 'IV Erythromycin ก่อนทำ EGD ช่วยเคลียร์เลือด', 'EGD ควรทำภายใน 24 ชม.'], time_minutes: 10 },
    { exam_id: realExam1Id, part_number: 3, title: 'ตอนที่ 3: ผล EGD และการรักษา', scenario: 'ผล EGD:\n- Esophagus: ปกติ ไม่มี varices\n- Stomach: พบ gastric ulcer 2 cm ที่ lesser curvature มี visible vessel (Forrest Ia)\n- Duodenum: erythematous mucosa', question: 'จงให้การวินิจฉัยตาม Forrest classification และวางแผนการรักษาผ่าน endoscopy', answer: 'การวินิจฉัย: Gastric ulcer, Forrest Ia (Active arterial spurting)\nRisk of rebleeding: สูงมาก (>90%)\n\nการรักษา Endoscopy:\n1. Combination therapy:\n   - Injection: Epinephrine 1:10,000\n   - Thermal/Mechanical: Hemoclip\n2. หลัง hemostasis: ต่อ IV PPI 72 ชม.\n3. ส่ง biopsy ขอบแผล rule out malignancy\n4. ทดสอบ H. pylori', key_points: ['Forrest Ia = active spurting = rebleeding risk สูงสุด', 'Combination therapy ดีกว่า monotherapy', 'Gastric ulcer ต้อง biopsy เสมอ', 'ทดสอบ H. pylori ทุกราย'], time_minutes: 10 },
    { exam_id: realExam1Id, part_number: 4, title: 'ตอนที่ 4: ภาวะแทรกซ้อนหลังทำ EGD', scenario: 'หลังทำ EGD hemostasis สำเร็จ 12 ชม.\nผู้ป่วยอาเจียนเป็นเลือดสดอีกครั้ง 300 mL\nV/S: BP 85/55, HR 130, RR 28\nHb 6.5 g/dL', question: 'จัดการภาวะ rebleeding และตัดสินใจว่าควรทำอย่างไรต่อ', answer: 'การจัดการ Rebleeding:\n1. Resuscitation อีกครั้ง: IV fluid + Transfuse PRC\n2. Repeat EGD เป็น first-line\n3. หาก repeat EGD ล้มเหลว:\n   - Interventional radiology: Angiographic embolization\n   - Surgery: หาก IR ไม่พร้อม\n4. Criteria สำหรับ surgery:\n   - Rebleeding หลัง 2 ครั้ง endoscopic treatment\n   - Transfusion > 6 units ใน 24 ชม.', key_points: ['Repeat EGD เป็น first-line สำหรับ rebleeding', 'Angiographic embolization เป็นทางเลือกก่อน surgery', 'Massive transfusion protocol เตรียมไว้เสมอ', 'Rebleeding rate ของ Forrest Ia สูงแม้ทำ hemostasis แล้ว'], time_minutes: 10 },
    { exam_id: realExam1Id, part_number: 5, title: 'ตอนที่ 5: การดูแลหลังเลือดหยุดและผลชิ้นเนื้อ', scenario: 'หลัง repeat EGD + hemoclip สำเร็จ เลือดหยุด\nวันที่ 5: อาการดีขึ้น Hb 9.0 (stable)\nเริ่มรับประทานอาหารเหลวได้\n\nผล Biopsy: Chronic gastritis with H. pylori, No malignancy\nCLO test: Positive', question: 'วางแผนการรักษา H. pylori และ long-term management', answer: 'การรักษา H. pylori (Triple therapy 14 วัน):\n1. Omeprazole 20 mg bid\n2. Clarithromycin 500 mg bid\n3. Amoxicillin 1 g bid\n\nLong-term Management:\n1. ต่อ PPI อีก 8-12 สัปดาห์\n2. ยืนยัน H. pylori eradication: UBT หลังหยุดยา 4 สัปดาห์\n3. Follow-up EGD 8-12 สัปดาห์\n4. หยุด NSAIDs ถาวร\n5. ใช้ Paracetamol แทน\n6. งดแอลกอฮอล์', key_points: ['H. pylori eradication ลด ulcer recurrence จาก 80% เหลือ < 5%', 'Triple therapy 14 วัน เป็น first-line', 'ต้อง confirm eradication หลังรักษา', 'หยุด NSAIDs ถาวร เปลี่ยนเป็น Paracetamol'], time_minutes: 10 },
    { exam_id: realExam1Id, part_number: 6, title: 'ตอนที่ 6: การวางแผนจำหน่ายและป้องกัน', scenario: 'วันที่ 7: อาการดี รับประทานอาหารอ่อนได้\nHb 10.2 g/dL\nไม่มีอาการปวดท้อง ไม่มีเลือดออก\nถ่ายสีน้ำตาลปกติ', question: 'วางแผนจำหน่ายผู้ป่วย รวมถึงยากลับบ้าน คำแนะนำ และนัดติดตาม', answer: 'แผนจำหน่าย:\n1. ยากลับบ้าน:\n   - H. pylori triple therapy 14 วัน\n   - หลังจบ ATB ต่อ Omeprazole 20 mg OD อีก 8-10 สัปดาห์\n   - Paracetamol prn แทน NSAIDs\n2. คำแนะนำ:\n   - ห้ามใช้ NSAIDs เด็ดขาด\n   - งดแอลกอฮอล์ งดสูบบุหรี่\n   - สังเกตอาการเตือน: อาเจียนเลือด ถ่ายดำ\n3. นัดติดตาม:\n   - 2 สัปดาห์: ตรวจทั่วไป\n   - 4 สัปดาห์หลังจบ ATB: UBT\n   - 8-12 สัปดาห์: Follow-up EGD', key_points: ['ห้ามใช้ NSAIDs เด็ดขาด', 'ต้อง confirm H. pylori eradication', 'Follow-up EGD สำคัญสำหรับ gastric ulcer', 'ให้ความรู้ผู้ป่วยเรื่องอาการเตือน'], time_minutes: 10 },
  ]);
  console.log('Exam 1 parts:', ep1 ? ep1.message : 'OK');

  // Exam 2 parts
  const { error: ep2 } = await supabase.from('exam_parts').insert([
    { exam_id: realExam2Id, part_number: 1, title: 'ตอนที่ 1: การประเมินเบื้องต้นและ Triage', scenario: 'ชายไทยอายุ 68 ปี โรคประจำตัว DM type 2 (10 ปี) และ COPD\nมาห้องฉุกเฉินด้วยไข้สูง 39.5\u00B0C หนาวสั่น ไอมีเสมหะสีเขียวข้น 3 วัน หายใจหอบเหนื่อย 1 วัน\n\nV/S: BP 85/50, HR 125, RR 32, SpO2 85% RA, Temp 39.8\u00B0C\nPE: Confused, ใช้ accessory muscles, crackles Lt lower lung\nCBS: 350 mg/dL', question: 'ประเมินความรุนแรงและจัดลำดับความสำคัญในการดูแลผู้ป่วยรายนี้', answer: 'การประเมิน:\n1. Sepsis + Septic shock (hypotension)\n2. CURB-65 = 4 (Severe)\n\nHour-1 Bundle:\n1. O2 high flow เป้า SpO2 88-92% (COPD)\n2. IV fluid bolus 30 mL/kg\n3. Blood culture 2 sets ก่อนให้ ATB\n4. IV ATB ภายใน 1 ชม.: Ceftriaxone 2g + Azithromycin 500 mg\n5. วัด Lactate\n6. Regular insulin IV แก้ hyperglycemia\n7. Monitor V/S ทุก 15 นาที', key_points: ['Septic shock = Sepsis + Hypotension', 'Hour-1 bundle สำคัญมาก', 'COPD: เป้า SpO2 88-92%', 'ATB ต้องให้ภายใน 1 ชม.'], time_minutes: 10 },
    { exam_id: realExam2Id, part_number: 2, title: 'ตอนที่ 2: ผลตรวจทางห้องปฏิบัติการ', scenario: 'ผล Lab:\n- WBC 18,500 (N 92%), Hb 11.5, Plt 95,000\n- BUN 48, Cr 2.1 (baseline 1.0)\n- Lactate 4.5 mmol/L\n- Procalcitonin 15 ng/mL\n- ABG: pH 7.28, pCO2 32, pO2 58, HCO3 15\n- CXR: LLL consolidation with air bronchogram\n- Blood glucose 380 mg/dL', question: 'แปลผล lab และ CXR พร้อมวิเคราะห์ ABG', answer: 'การแปลผล:\n1. Leukocytosis with left shift = bacterial infection\n2. Thrombocytopenia = sepsis-related\n3. AKI stage 2 (Cr 2.1 จาก baseline 1.0)\n4. Lactate 4.5 = tissue hypoperfusion\n5. Procalcitonin 15 = bacterial sepsis\n6. ABG: Metabolic acidosis (lactic) with respiratory compensation\n7. CXR: Lobar pneumonia LLL\n\nสรุป: Severe CAP with Septic Shock, AKI, Metabolic acidosis', key_points: ['Lactate > 4 = severe hypoperfusion', 'Procalcitonin > 10 = bacterial sepsis', 'ABG วิเคราะห์เป็นขั้นตอน', 'AKI ใน sepsis พบบ่อย'], time_minutes: 10 },
    { exam_id: realExam2Id, part_number: 3, title: 'ตอนที่ 3: การรักษาใน ICU', scenario: 'หลังให้ IV fluid 2L:\nBP 80/45 (ยังต่ำ), HR 120, SpO2 90% O2 mask 10L\nUrine output: 15 mL/hr\nLactate ซ้ำ: 5.2 (เพิ่มขึ้น)', question: 'วางแผนการรักษาใน ICU: vasopressor, ventilatory support, organ support', answer: 'การรักษา ICU:\n1. Hemodynamic: Norepinephrine 0.1-0.5 mcg/kg/min เป้า MAP >= 65\n2. Respiratory: พิจารณา intubation + Lung protective ventilation (TV 6 mL/kg)\n3. Renal: IV fluid ระมัดระวัง, หลีกเลี่ยง nephrotoxic drugs\n4. DM: IV Insulin drip เป้า glucose 140-180\n5. ATB: ต่อ Ceftriaxone + Azithromycin', key_points: ['Norepinephrine เป็น first-line vasopressor', 'MAP target >= 65 mmHg', 'Lung protective ventilation: TV 6 mL/kg', 'Glucose target ใน ICU: 140-180'], time_minutes: 10 },
    { exam_id: realExam2Id, part_number: 4, title: 'ตอนที่ 4: ผลเพาะเชื้อและการปรับยา', scenario: 'วันที่ 3: Blood culture 2/2: Streptococcus pneumoniae\nSensitivity: Penicillin (MIC 0.5 - Intermediate), Ceftriaxone (Sensitive)\nผู้ป่วย: ยังใช้เครื่องช่วยหายใจ FiO2 ลดจาก 80% เป็น 50%\nNE ลดเหลือ 0.05 mcg/kg/min', question: 'ปรับยาปฏิชีวนะตามผลเพาะเชื้อ และวางแผน weaning', answer: 'De-escalation ATB:\n1. เปลี่ยนเป็น Ceftriaxone 2g IV OD alone\n2. ระยะเวลา 7-10 วัน\n3. หยุด Azithromycin\n\nWeaning criteria:\n- FiO2 <= 40%, PEEP <= 8\n- ไม่ต้องการ vasopressor สูง\n- ผู้ป่วยรู้สึกตัวดี\n- ผู้ป่วยรายนี้: FiO2 50% ยังไม่ถึง\n- เตรียม NIV standby หลัง extubation (COPD)', key_points: ['De-escalation ATB เมื่อรู้ผลเพาะเชื้อ', 'S. pneumoniae = สาเหตุ CAP ที่พบบ่อยที่สุด', 'SBT criteria ต้องจำ', 'COPD: เตรียม NIV standby'], time_minutes: 10 },
    { exam_id: realExam2Id, part_number: 5, title: 'ตอนที่ 5: ภาวะแทรกซ้อนระหว่างรักษา', scenario: 'วันที่ 7: มีไข้ขึ้นใหม่ 38.5\u00B0C หลังไข้ลง 2 วัน\nCXR: ยังมี LLL infiltrate + new RLL infiltrate\nWBC 22,000 (เพิ่มจาก 12,000)\nSputum: สีเหลืองข้น ปริมาณมากขึ้น', question: 'วิเคราะห์สาเหตุไข้ขึ้นใหม่ และวางแผนตรวจรักษา', answer: 'Differential Diagnosis:\n1. Hospital-Acquired Pneumonia (HAP) - สงสัยมากที่สุด\n2. Parapneumonic effusion / Empyema\n3. Line infection / UTI\n\nการตรวจ:\n1. Sputum + Blood culture ใหม่\n2. CT chest, Urine culture\n3. ตรวจ CVC site\n\nการรักษา:\n1. เปลี่ยน ATB: Piperacillin-Tazobactam หรือ Meropenem\n2. พิจารณา Vancomycin ถ้าสงสัย MRSA\n3. De-escalate เมื่อได้ผล culture', key_points: ['New fever + new infiltrate = สงสัย HAP', 'Late-onset HAP เสี่ยง MDR organisms', 'ต้อง culture ก่อนเริ่ม ATB ใหม่', 'Anti-pseudomonal coverage สำหรับ late-onset HAP'], time_minutes: 10 },
    { exam_id: realExam2Id, part_number: 6, title: 'ตอนที่ 6: การวางแผนจำหน่ายและป้องกัน', scenario: 'วันที่ 15: เดินได้ ไม่มีไข้ รับประทานอาหารได้ดี\nSpO2 95% room air\nCXR: infiltrate ลดลงมาก\nCr กลับมา 1.1', question: 'วางแผน discharge plan, follow-up, และมาตรการป้องกัน', answer: 'Discharge Plan:\n1. ยากลับบ้าน: ATB oral ครบ course, DM meds, COPD inhalers\n2. Follow-up:\n   - 1-2 สัปดาห์: ตรวจทั่วไป CBC BUN/Cr\n   - 4-6 สัปดาห์: CXR confirm resolution\n\nมาตรการป้องกัน:\n1. Vaccination: Pneumococcal + Influenza + COVID-19\n2. Smoking cessation\n3. DM optimization: HbA1c < 7-8%\n4. COPD optimization: LABA/LAMA, Pulmonary rehabilitation\n5. Follow-up CXR confirm resolution', key_points: ['Pneumococcal + Influenza vaccine ป้องกัน recurrent CAP', 'Smoking cessation = single most important for COPD', 'Follow-up CXR confirm resolution สำคัญ', 'DM + COPD optimization ลดความเสี่ยง'], time_minutes: 10 },
  ]);
  console.log('Exam 2 parts:', ep2 ? ep2.message : 'OK');

  console.log('Seed complete!');
}

seed();
