/* eslint-disable */
const { Client } = require("pg");
const { randomUUID } = require("crypto");

// NLE Batch 2 — 200 questions across the 8 nursing subjects.
// Run with: DATABASE_URL=... node scripts/seed_nursing_batch2.js
//
// Format conventions (matches lib/types-mcq.ts):
//   choices: [{ label, text }, ...]
//   detailed_explanation: { summary, reason, choices: [...], key_takeaway }
//
// Content reflects the NLE (สภาการพยาบาล) curriculum; please review with a
// subject-matter expert before relying on it for high-stakes preparation.

const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) {
  console.error("ERROR: DATABASE_URL env var is required");
  process.exit(1);
}

const LABELS = ["A", "B", "C", "D"];

function q(
  subjectName,
  scenario,
  choices,
  correct,
  summary,
  reason,
  choiceExp,
  key,
  difficulty = "medium"
) {
  return {
    subjectName,
    scenario,
    choices: choices.map((text, i) => ({ label: LABELS[i], text })),
    correct_answer: correct,
    explanation: summary,
    detailed_explanation: {
      summary,
      reason,
      choices: choices.map((text, i) => ({
        label: LABELS[i],
        text,
        is_correct: correct === LABELS[i],
        explanation: choiceExp[i],
      })),
      key_takeaway: key,
    },
    difficulty,
  };
}

const ADULT = "NursingAdult";
const GERI = "NursingGeriatric";
const PEDS = "NursingPediatric";
const MAT = "NursingMaternal";
const MID = "NursingMidwifery";
const PSY = "NursingPsych";
const COM = "NursingCommunity";
const LAW = "NursingLawEthics";

const all = [
  // ============================================================
  // 1) NursingAdult — การพยาบาลผู้ใหญ่ (25)
  // ============================================================
  q(ADULT,
    "ผู้ป่วยชายอายุ 65 ปี มี acute MI พยาบาลควรประเมินสิ่งใดเป็นลำดับแรกเมื่อมาถึง ER",
    ["ABC + 12-lead ECG ภายใน 10 นาที", "เจาะ troponin แล้วรอผล", "ให้ aspirin เคี้ยวอย่างเดียว", "ส่งทำ echocardiogram ทันที"],
    "A",
    "Suspected ACS: ทำ 12-lead ECG ภายใน 10 นาทีหลังถึง พร้อมประเมิน ABC + vital signs",
    "AHA chest-pain protocol: ECG ใน 10 นาทีเพื่อแยก STEMI/NSTEMI และตัดสินใจ reperfusion; oxygen/aspirin/nitrate ตามมาภายหลัง",
    ["ECG เป็น time-critical step ที่นำการตัดสินใจ reperfusion", "Troponin ใช้ rule out แต่ไม่ delay การประเมิน initial", "Aspirin ให้คู่กับ assessment ไม่ใช่แทน", "Echo ทำในขั้น hemodynamic instability หรือ complication"],
    "STEMI = ECG ภายใน 10 นาที, door-to-balloon < 90 นาที"),
  q(ADULT,
    "ผู้ป่วย STEMI ได้รับ thrombolytic 30 นาทีก่อน เกิด chest pain ลดลง, ST segment กลับมาใกล้ปกติ พยาบาลตีความว่า",
    ["Thrombolytic ล้มเหลว ต้องส่ง PCI", "มี reperfusion arrhythmia อาจเกิดขึ้นได้", "ผู้ป่วยเริ่ม cardiogenic shock", "ต้องหยุดยา heparin ทันที"],
    "B",
    "Reperfusion markers: ↓ pain, ST resolution > 50%, อาจมี reperfusion arrhythmia (AIVR, VT) — ปกติ self-limited",
    "การกลับมาของเลือด → free radical + Ca overload กระตุ้น ectopic foci ทำให้ accelerated idioventricular rhythm พบบ่อยและมัก benign",
    ["ตรงข้าม การลด ST = success criteria", "ใช่ — AIVR เป็น classic reperfusion sign", "Shock ดูจาก BP/perfusion ไม่ใช่ปวดลด", "Heparin ยังให้ต่อใน STEMI หลัง lytic"],
    "Reperfusion = pain↓ + ST↓ + อาจมี AIVR ชั่วคราว"),
  q(ADULT,
    "ผู้ป่วย acute decompensated heart failure NYHA IV มี orthopnea pulmonary congestion ท่าทางการจัดให้นอนที่เหมาะสมคือ",
    ["Supine flat", "Trendelenburg", "High-Fowler 60–90 องศา ห้อยขา", "Left lateral"],
    "C",
    "High-Fowler + dangling legs ลด venous return และเพิ่ม lung expansion → บรรเทา dyspnea",
    "Cardiac preload ลดลงจาก venous pooling ขาส่วนล่าง + diaphragm ลงต่ำเพิ่ม functional residual capacity",
    ["Supine เพิ่ม venous return กลับหัวใจ ทำให้หายใจแย่ลง", "Trendelenburg ใช้ใน shock แต่ห้ามใน pulmonary edema", "ใช่ — ท่ามาตรฐานสำหรับ acute pulmonary edema", "Lateral ไม่ลด preload อย่างมีนัยสำคัญ"],
    "Acute pulmonary edema: นั่ง 60–90° + ห้อยขา + O₂ + IV diuretic"),
  q(ADULT,
    "ค่าก๊าซในเลือดแดง: pH 7.28, PaCO₂ 60, HCO₃ 26 ผู้ป่วยภาวะใด",
    ["Metabolic acidosis", "Respiratory acidosis (uncompensated)", "Respiratory alkalosis", "Metabolic alkalosis"],
    "B",
    "pH ลด + PaCO₂ สูง + HCO₃ ปกติ = respiratory acidosis ที่ยังไม่ compensate",
    "ถ้า metabolic compensation จะมี HCO₃ สูงขึ้น (chronic) ที่นี่ HCO₃ ยังปกติ → acute",
    ["pH ↓ จริง แต่ HCO₃ ปกติไม่ใช่ metabolic", "ใช่ — acute respiratory acidosis", "Alkalosis ต้อง pH > 7.45", "Metabolic alkalosis ต้อง HCO₃ สูง"],
    "↑PaCO₂ + ↓pH + HCO₃ ปกติ = acute respiratory acidosis"),
  q(ADULT,
    "ผู้ป่วยมี hyperkalemia (K = 6.8) ECG มี peaked T wave ขั้นแรกของการรักษาเพื่อ stabilize myocardium คือ",
    ["IV calcium gluconate 10%", "IV regular insulin + glucose", "Kayexalate ทางปาก", "Sodium bicarbonate IV"],
    "A",
    "IV calcium gluconate ช่วย stabilize cardiac membrane ภายในไม่กี่นาที (ไม่ลด K แต่ป้องกัน arrhythmia)",
    "ลำดับการรักษา hyperkalemia: 1) stabilize membrane (Ca) 2) shift K เข้าเซลล์ (insulin/glucose, β2-agonist, bicarb) 3) remove K (diuretic, resin, dialysis)",
    ["ใช่ — first step เมื่อมี ECG changes", "Shift K เข้าเซลล์ แต่ไม่ stabilize membrane โดยตรง", "Remove K ออกร่างกาย ช้ากว่า", "Shift K โดย alkalosis ใช้ใน acidosis"],
    "Hyperkalemia + ECG change → Ca gluconate ก่อน"),
  q(ADULT,
    "ผู้ป่วย DKA ค่า blood sugar 480, pH 7.15 พยาบาลควรให้ IV fluid ใดในชั่วโมงแรก",
    ["0.45% NaCl", "0.9% NaCl 15–20 mL/kg/hr", "D5W", "Dextran"],
    "B",
    "DKA: เริ่ม rehydration ด้วย 0.9% NaCl 1–1.5 L ในชั่วโมงแรก แล้วประเมิน Na/K ก่อนเปลี่ยน",
    "DKA มี total body water deficit 5–10 L; isotonic saline ขยาย intravascular volume ก่อนพิจารณา half-saline ตาม corrected Na",
    ["Hypotonic ใช้ในระยะ maintenance เมื่อ Na สูง", "ใช่ — initial resuscitation fluid มาตรฐาน", "D5W ใช้เมื่อ glucose < 200 mg/dL", "Dextran ไม่ใช่ first-line crystalloid"],
    "DKA hour-1: NSS 15–20 mL/kg + ดู K ก่อน insulin"),
  q(ADULT,
    "ผู้ป่วย septic shock MAP 55 mmHg หลัง crystalloid 30 mL/kg แล้ว vasopressor ตัวแรกคือ",
    ["Dopamine", "Norepinephrine", "Dobutamine", "Epinephrine"],
    "B",
    "Norepinephrine เป็น first-line vasopressor ใน septic shock ตาม SSC guideline",
    "α1 vasoconstriction เพิ่ม SVR + β1 mild inotropy โดยมี tachyarrhythmia น้อยกว่า dopamine",
    ["Dopamine เพิ่ม arrhythmia ไม่เป็น first-line", "ใช่ — Norepi คือ first-line", "Dobutamine ใช้เพิ่ม CO ในภาวะ low CO ไม่ใช่ vasopressor หลัก", "Epi เป็น second-line เพิ่มเมื่อ MAP ยังไม่ถึง"],
    "Septic shock: NSS แล้วต่อด้วย Norepi"),
  q(ADULT,
    "ผู้ป่วย mechanical ventilation มี ETT cuff pressure ที่เหมาะสมคือ",
    ["10–15 cmH₂O", "20–30 cmH₂O", "35–40 cmH₂O", "50–60 cmH₂O"],
    "B",
    "Cuff pressure 20–30 cmH₂O ป้องกัน aspiration และไม่ทำลาย tracheal mucosa",
    ">30 cmH₂O ลด capillary perfusion ของ trachea → necrosis; <20 → micro-aspiration",
    ["ต่ำเกินไป leak + aspiration", "ใช่ — มาตรฐาน", "เสี่ยง tracheal ischemia", "อันตรายมาก necrosis"],
    "Cuff pressure: 20–30 cmH₂O เช็คทุก shift"),
  q(ADULT,
    "ผู้ป่วยใส่ chest drain ICD ขวด underwater seal สังเกตเห็น tidaling หายไป สิ่งที่ควรประเมินคือ",
    ["ปอดขยายเต็มแล้วหรือสายตัน", "Air leak มาก", "ต้อง clamp สาย", "ปกติ"],
    "A",
    "Tidaling หาย = ปอดขยายเต็ม (full re-expansion) หรือ tube obstruction/kink",
    "ต้องตรวจสาย, ตำแหน่ง, รวมถึง CXR เพื่อแยกสองภาวะนี้ก่อนตัดสินใจ",
    ["ใช่ — สองสาเหตุหลัก", "Air leak จะเห็น bubbling, ไม่ใช่ tidaling", "ห้าม clamp routine — เสี่ยง tension pneumothorax", "ไม่ปกติ ต้องประเมิน"],
    "Tidaling หาย = ปอดขยายเต็ม หรือ ตัน — เช็กก่อน"),
  q(ADULT,
    "ผู้ป่วยได้รับ blood transfusion 15 นาที มีไข้ 38.5°C, หนาวสั่น, BP ปกติ ขั้นตอนแรกคือ",
    ["หยุดเลือดทันที + maintain IV line ด้วย NSS", "ลดอัตราการให้ลงครึ่ง", "ให้ paracetamol แล้วให้เลือดต่อ", "เปลี่ยนชุดเลือดใหม่"],
    "A",
    "Suspected transfusion reaction: หยุดเลือดทันที, เปลี่ยน IV line เป็น NSS, รายงานแพทย์, ส่งชุดเลือดและตัวอย่างกลับ blood bank",
    "ต้องแยกระหว่าง febrile non-hemolytic vs hemolytic reaction — ห้ามเอาเลือดต่อก่อนประเมิน",
    ["ใช่ — protocol มาตรฐาน", "ห้าม — ต้องหยุดก่อน", "ห้ามให้ยา premed แล้วเลือดต่อในขณะยังไม่แยกประเภท", "ไม่ใช่ขั้นแรก ต้องเก็บส่ง investigate"],
    "Transfusion reaction → STOP → NSS → Notify → Send back to blood bank"),
  q(ADULT,
    "ผู้ป่วย COPD on home oxygen 2 LPM via nasal cannula มา ER ด้วย acute exacerbation ค่า SpO₂ 86% เป้าหมาย SpO₂ ที่ปลอดภัยคือ",
    ["88–92%", "94–98%", "99–100%", "85–88%"],
    "A",
    "COPD: ให้ controlled O₂ เป้า SpO₂ 88–92% เพื่อหลีกเลี่ยง CO₂ narcosis",
    "Chronic hypercapnia ทำให้ hypoxic drive เป็นตัวกระตุ้น respiration; over-oxygenation → ↓minute ventilation",
    ["ใช่ — มาตรฐาน BTS/GOLD", "เป้าของผู้ป่วยทั่วไป", "เสี่ยง CO₂ retention", "ต่ำเกินไป ไม่พอเลี้ยงเนื้อเยื่อ"],
    "COPD target: 88–92%"),
  q(ADULT,
    "ผู้ป่วย CKD stage 4 มี hyperkalemia เรื้อรัง อาหารที่ควรหลีกเลี่ยงคือ",
    ["ข้าวสวย", "กล้วย ส้ม มะเขือเทศ", "ขนมปังขาว", "น้ำเปล่า"],
    "B",
    "High-K foods: ผลไม้อย่างกล้วย ส้ม มะเขือเทศ มันฝรั่ง อโวคาโด ต้องจำกัด",
    "เป้าหมาย K intake < 2–3 g/วันใน advanced CKD",
    ["K ต่ำ ปลอดภัย", "ใช่ — เป็น high-K foods", "K ต่ำ", "ไม่มี K"],
    "CKD: หลีกเลี่ยง กล้วย ส้ม มะเขือเทศ มันฝรั่ง อโวคาโด"),
  q(ADULT,
    "ผู้ป่วย hemodialysis มี AV fistula ที่แขนซ้าย คำแนะนำในการดูแลคือ",
    ["วัด BP และเจาะเลือดแขนซ้ายได้", "ห้ามวัด BP / เจาะเลือด / IV ที่แขนซ้าย", "นอนทับแขนซ้ายเพื่อช่วยให้แข็งแรง", "ห้ามคลำเส้นเลือดที่ fistula"],
    "B",
    "ป้องกัน fistula thrombosis/damage: ห้ามวัด BP, เจาะเลือด, IV, นอนทับแขนนั้น",
    "ผู้ป่วยควรคลำ thrill ฟัง bruit ทุกวันเพื่อเช็คความ patency",
    ["ผิด — เพิ่มความเสี่ยง", "ใช่ — มาตรฐาน", "ห้าม — เพิ่ม pressure → thrombosis", "ตรงข้าม — ต้องคลำ thrill ทุกวัน"],
    "AV fistula: NO BP, NO IV, NO blood draw, CHECK thrill daily"),
  q(ADULT,
    "ผู้ป่วย ischemic stroke onset 2 ชั่วโมง CT brain ไม่พบเลือดออก คะแนน NIHSS 10 การรักษาที่เหมาะสมคือ",
    ["IV alteplase (rtPA) ภายใน 4.5 ชม", "Aspirin อย่างเดียว", "Warfarin เริ่มทันที", "Mannitol"],
    "A",
    "Eligible ischemic stroke: rtPA ภายใน 4.5 ชม. หลัง onset ลด disability",
    "ต้องไม่มี contraindication (เช่น เลือดออก, INR สูง, recent surgery) — รีบ door-to-needle < 60 นาที",
    ["ใช่ — first-line ใน eligible patient", "ใช้ในผู้ป่วยที่ไม่เข้า lytic หรือหลัง 24 hr", "Warfarin ใช้ป้องกัน secondary ไม่ใช่ acute", "Mannitol ใช้ใน ↑ICP / มวลเลือดในสมอง"],
    "Ischemic stroke: rtPA ≤ 4.5 hr, door-to-needle < 60 นาที"),
  q(ADULT,
    "ผู้ป่วย stroke มี dysphagia ต้องประเมิน swallowing ก่อนให้อาหารโดย",
    ["ให้น้ำลำเลียงดูทันที 200 mL", "Bedside swallowing screen เช่น 3-oz water test หรือ Gugging swallowing screen", "งดอาหาร NPO ตลอดไป", "ใส่ NG ทันทีโดยไม่ประเมิน"],
    "B",
    "ก่อนให้อาหารทางปาก: ใช้ standardized bedside swallowing screen เพื่อ ลด aspiration pneumonia",
    "ถ้า fail screen → NPO แล้วส่ง speech therapist หรือใส่ NG ตามแผน",
    ["อันตราย — เสี่ยง aspiration", "ใช่ — มาตรฐานก่อนเริ่ม PO", "ไม่ใช่ทุกราย — ต้องประเมินก่อน", "ใส่ NG ตามผล screen ไม่ใช่ default"],
    "Stroke + PO order = ผ่าน swallowing screen ก่อน"),
  q(ADULT,
    "ผู้ป่วย type 2 DM ใช้ basal insulin ทุกคืน FBS 200 mg/dL พยาบาลควรประเมิน Somogyi vs dawn phenomenon โดย",
    ["ตรวจ glucose ตอน 02:00–03:00", "ตรวจ HbA1c ใหม่", "เพิ่มขนาดยาเลย", "ตรวจ C-peptide"],
    "A",
    "Somogyi = rebound hyper หลัง hypo กลางคืน; Dawn = morning surge ไม่ผ่าน hypo; วัด glucose 02:00–03:00 เพื่อแยก",
    "Somogyi → ลดขนาด basal; Dawn → เพิ่มหรือเปลี่ยน timing",
    ["ใช่ — สำคัญในการตัดสินใจ", "บอกค่าเฉลี่ย ไม่แยกสาเหตุ", "อาจซ้ำเติม hypoglycemia ถ้าเป็น Somogyi", "ใช้ดูการผลิต insulin ภายใน ไม่เกี่ยวกับ Dawn"],
    "FBS สูง: เช็คน้ำตาลตี 3 ก่อนปรับยา"),
  q(ADULT,
    "ผู้ป่วยใช้ warfarin มี INR 5.8 ไม่มี bleeding การจัดการที่เหมาะสมคือ",
    ["หยุด warfarin 1–2 dose + ติดตาม INR", "ให้ FFP ทันที", "ให้ vitamin K 10 mg IV", "ให้ protamine sulfate"],
    "A",
    "INR 4.5–10 ไม่มี bleeding: หยุดยา + ติดตาม; ให้ vitamin K oral 1–2.5 mg ถ้าเสี่ยง bleeding สูง",
    "FFP/PCC ใช้เมื่อ major bleeding; protamine กลับ heparin ไม่ใช่ warfarin",
    ["ใช่ — guideline ACCP", "Reserve สำหรับ major bleeding", "ขนาดสูงเกิน ใช้เมื่อ life-threatening", "Protamine = heparin antagonist"],
    "Warfarin: ปรับตาม INR + bleeding status"),
  q(ADULT,
    "ผู้ป่วยได้รับยา heparin IV drip ค่า aPTT 95 วินาที (target 60–80) ต้องทำอย่างไร",
    ["เพิ่ม rate", "ลด rate และเจาะ aPTT ซ้ำใน 6 ชม", "หยุดยา 24 ชม", "เปลี่ยนเป็น warfarin ทันที"],
    "B",
    "aPTT เกิน therapeutic: ลด rate ตาม nomogram และตรวจซ้ำใน 6 ชั่วโมง",
    "อย่าหยุดทั้งหมดถ้าไม่มี bleeding — เสี่ยง thrombosis; ปรับตาม protocol",
    ["ผิด — จะเพิ่ม bleeding risk", "ใช่ — nomogram-based titration", "อาจ undertreat ถ้าไม่มี bleeding", "Bridge ใช่ แต่ยังต้อง active control aPTT ก่อน"],
    "Heparin: titrate ตาม aPTT + reassess 6 hr"),
  q(ADULT,
    "ผู้ป่วยมะเร็งระยะสุดท้ายปวด 8/10 ใช้ morphine PRN ไม่เพียงพอ การปรับยาที่ถูกหลัก WHO คือ",
    ["เปลี่ยนเป็น tramadol", "ให้ scheduled morphine + breakthrough doses + adjuvant", "ใช้ paracetamol อย่างเดียว", "งดยา opioid เพราะติด"],
    "B",
    "WHO step 3: long-acting opioid scheduled + immediate-release breakthrough + adjuvant (NSAID, neuropathic agents)",
    "Around-the-clock dosing ป้องกัน pain peaks; breakthrough = 10–15% ของ total daily dose",
    ["Tramadol อ่อนกว่า morphine — step down ผิด", "ใช่ — strong opioid + ATC + rescue", "ไม่พอใน severe cancer pain", "การติดยาในผู้ป่วย terminal ไม่ใช่ประเด็นหลัก"],
    "Cancer pain: ATC + rescue + adjuvant"),
  q(ADULT,
    "ผู้ป่วย deep partial-thickness burn 25% TBSA น้ำหนัก 60 kg ตาม Parkland formula ปริมาณ Lactated Ringer's ใน 24 ชม คือ",
    ["3,000 mL", "4,500 mL", "6,000 mL", "9,000 mL"],
    "C",
    "Parkland: 4 mL × kg × %TBSA = 4×60×25 = 6,000 mL ใน 24 ชม. (ครึ่งแรกใน 8 ชม.)",
    "ครึ่งแรก = 3,000 mL ใน 8 ชม นับจาก burn time; อีกครึ่ง = 16 ชม. ถัดมา",
    ["น้อยเกินไป", "ผิดสูตร", "ใช่ — ตาม Parkland", "เกือบเป็นสองเท่า"],
    "Parkland = 4 × kg × %TBSA, ครึ่งแรกใน 8 ชม."),
  q(ADULT,
    "หลังผ่าตัด total hip replacement ผู้ป่วยควรหลีกเลี่ยงท่าใดเพื่อป้องกัน dislocation",
    ["Hip flexion < 60°", "Hip flexion > 90°, internal rotation, adduction", "External rotation 30°", "เดินด้วย walker"],
    "B",
    "Posterior approach THR: ห้าม flex > 90°, adduct, internal rotate (high-risk dislocation positions)",
    "ใช้ abduction pillow + ห้ามนั่งเก้าอี้ต่ำ ห้ามไขว้ขา 6 สัปดาห์",
    ["ปลอดภัยถ้า < 90°", "ใช่ — high-risk positions", "External ปลอดภัย", "แนะนำให้ใช้ assistive device"],
    "THR: NO flex >90°, NO adduct, NO internal rotation × 6 wk"),
  q(ADULT,
    "ผู้ป่วยใส่ NG tube สำหรับ feeding ก่อนให้ feeding ครั้งใหม่พยาบาลควรประเมิน residual gastric volume ตามแนวทางใด",
    ["ไม่ต้องเช็คเลย", "เช็ค residual ก่อนให้, ถ้า > 500 mL พิจารณาหยุด/ลดอัตรา", "ให้ feeding ตามเวลาทุกครั้งโดยไม่สนใจ residual", "เช็คเฉพาะเมื่อมีอาเจียน"],
    "B",
    "Residual > 500 mL: hold/ลด rate และประเมิน intolerance; 250–500 mL: monitor closely",
    "การ stop ที่ < 250 mL ทำให้ underfeeding โดยไม่จำเป็นตาม ASPEN guideline",
    ["เสี่ยง aspiration/overfill", "ใช่ — ตาม ASPEN", "ผิด — ไม่ปลอดภัย", "Symptomatic only ตกเกณฑ์ early detection"],
    "GRV > 500 mL = hold; 250–500 = monitor"),
  q(ADULT,
    "ผู้ป่วย sepsis ได้ IV antibiotic ภายใน 1 ชม ตาม sepsis bundle ตัวชี้วัดที่บอกว่าควรเริ่ม vasopressor คือ",
    ["MAP < 65 หลังให้ crystalloid 30 mL/kg แล้ว", "BP systolic ต่ำกว่า 100", "HR > 100", "Lactate > 2"],
    "A",
    "Surviving Sepsis Campaign: start vasopressor ถ้า MAP < 65 หลัง initial fluid resuscitation",
    "Crystalloid 30 mL/kg ใน 3 ชม.แรก เป็น standard; ถ้ายัง hypotensive → norepi",
    ["ใช่ — เกณฑ์มาตรฐาน", "SBP เพียงอย่างเดียวไม่ใช้เป็น threshold", "Tachycardia พบทั่วไปใน sepsis", "Lactate ใช้ประเมิน perfusion ไม่ใช่ threshold ของ vasopressor"],
    "Septic shock: MAP < 65 หลัง 30 mL/kg = ให้ norepi"),
  q(ADULT,
    "ผู้ป่วย acute pancreatitis การพยาบาลที่สำคัญที่สุดในระยะ 24 ชม.แรก",
    ["ให้อาหารทางปากทันที", "Aggressive IV fluid resuscitation + pain control + NPO", "ให้ antibiotic ทุกราย", "ใส่ NG เพื่อ feeding"],
    "B",
    "Acute pancreatitis: IV crystalloid 5–10 mL/kg/hr + pain management + NPO ใน 24–48 hr แรก",
    "Antibiotic ไม่ routine ใน mild case; early enteral feeding หลัง 24–48 hr ลด infection",
    ["NPO ก่อนใน acute phase", "ใช่ — มาตรฐาน", "ไม่ทุกราย", "ใช้เมื่อ persistent severe ใน sub-acute phase"],
    "Acute pancreatitis: IVF + pain + NPO 24–48 hr"),
  q(ADULT,
    "ผู้ป่วย cirrhosis with esophageal varices หลังควบคุมเลือดออก ยาที่ใช้ป้องกัน rebleed คือ",
    ["Propranolol non-selective", "Atenolol", "Amlodipine", "Furosemide"],
    "A",
    "Non-selective β-blocker (propranolol, nadolol) ลด portal pressure ป้องกัน rebleed",
    "β1 blockade ลด CO + β2 blockade เพิ่ม splanchnic vasoconstriction → ลด portal flow",
    ["ใช่ — first-line secondary prophylaxis", "Cardioselective ไม่ลด portal pressure", "CCB ไม่มี indication", "ใช้แก้ ascites ไม่ใช่ป้องกัน rebleed"],
    "Variceal rebleed: NSBB + EVL"),

  // ============================================================
  // 2) NursingGeriatric — การพยาบาลผู้สูงอายุ (25)
  // ============================================================
  q(GERI,
    "การประเมินความเสี่ยงต่อการหกล้มในผู้สูงอายุที่เหมาะสมในห้องผู้ป่วยคือ",
    ["Glasgow Coma Scale", "Morse Fall Scale หรือ Timed Up and Go", "Braden scale", "MMSE"],
    "B",
    "Morse Fall Scale, TUG, STRATIFY เป็นเครื่องมือ validated สำหรับ fall risk",
    "Braden = pressure ulcer; MMSE = cognition; GCS = consciousness",
    ["ใช้ประเมินระดับสติ", "ใช่ — fall risk tools", "ประเมินแผลกดทับ", "ประเมิน cognition"],
    "Fall risk: Morse / TUG / STRATIFY"),
  q(GERI,
    "ผู้สูงอายุ admit ด้วย pneumonia อยู่ ๆ มีสับสน hallucination ใน 48 ชม ภาวะที่น่าจะเป็นคือ",
    ["Dementia", "Delirium", "Depression", "Psychosis"],
    "B",
    "Acute onset confusion + fluctuating course + inattention = delirium ตาม CAM",
    "Dementia ค่อย ๆ เปลี่ยนแปลง; delirium มี trigger (infection, drug, dehydration)",
    ["Dementia onset เป็นเดือน/ปี", "ใช่ — CAM positive", "Depression onset เป็นสัปดาห์–เดือน", "ไม่มี acute change without trigger"],
    "Acute confusion = think delirium → หา cause"),
  q(GERI,
    "Beers Criteria ระบุว่ายาใดควรหลีกเลี่ยงในผู้สูงอายุ",
    ["Paracetamol", "Diphenhydramine (anticholinergic)", "Lisinopril", "Vitamin D"],
    "B",
    "1st-gen antihistamines มี strong anticholinergic effect: confusion, urinary retention, falls",
    "ทดแทนด้วย 2nd-gen (loratadine, cetirizine) ในผู้สูงอายุ",
    ["Safe ในขนาดมาตรฐาน", "ใช่ — Beers list", "ใช้ได้ ระวัง renal", "Safe"],
    "Beers: หลีกเลี่ยง 1st-gen antihistamine, BZD, anticholinergic"),
  q(GERI,
    "ผู้สูงอายุ 80 ปี GFR ลดลง ตามการเปลี่ยนแปลงของวัย ยาขับทาง renal ที่ต้องลดขนาดคือ",
    ["Paracetamol", "Digoxin", "Amlodipine", "Atorvastatin"],
    "B",
    "Digoxin clearance ขึ้นกับ renal function — ผู้สูงอายุเสี่ยง toxicity",
    "Therapeutic range แคบ 0.5–2 ng/mL; symptom: N/V, visual, arrhythmia",
    ["Hepatic metabolism", "ใช่ — ต้อง renal dose adjustment", "Hepatic metabolism", "Hepatic"],
    "Digoxin ในผู้สูงอายุ: ระวัง CrCl + serum level"),
  q(GERI,
    "Pressure ulcer stage II ลักษณะที่ตรงต้องคือ",
    ["Intact skin, non-blanchable redness", "Partial-thickness loss, exposed dermis, shallow open ulcer", "Full-thickness skin loss with visible fat", "Full-thickness with exposed bone/tendon"],
    "B",
    "Stage II = partial-thickness loss involving dermis, ดู moist red/pink wound bed",
    "Stage I intact; III subcutaneous fat; IV bone/muscle exposed",
    ["Stage I", "ใช่ — Stage II", "Stage III", "Stage IV"],
    "Stage I→IV: intact → dermis → fat → bone"),
  q(GERI,
    "การประเมิน functional status ของผู้สูงอายุที่ใช้บ่อยที่สุดในชุมชนคือ",
    ["MMSE", "ADL/IADL (Barthel index, Lawton)", "Glasgow Coma Scale", "HAM-D"],
    "B",
    "ADL/IADL ประเมินความสามารถในการทำกิจวัตรประจำวัน — เป็นตัวชี้วัด functional",
    "Functional decline = predictor ของ mortality และ institutionalization",
    ["Cognition tool", "ใช่ — functional assessment", "Consciousness", "Depression scale"],
    "Functional: ADL (basic) + IADL (instrumental)"),
  q(GERI,
    "ผู้สูงอายุ urinary incontinence type 'stress' ลักษณะคือ",
    ["ปัสสาวะเล็ดเมื่อไอ จาม หรือออกกำลังกาย", "ปัสสาวะบ่อย ปวดอั้นไม่ไหว", "ปัสสาวะไม่ออกแต่มีหยดล้น", "ทำกิจวัตรไม่ทันเพราะเดินช้า"],
    "A",
    "Stress UI = involuntary leak จาก ↑intra-abdominal pressure; treatment: Kegel + pelvic floor PT",
    "Urge = overactive bladder; Overflow = retention; Functional = mobility/cognition issue",
    ["ใช่ — Stress UI", "Urge UI", "Overflow UI", "Functional UI"],
    "Stress = ไอ/จาม; Urge = อั้นไม่ทัน"),
  q(GERI,
    "Polypharmacy ในผู้สูงอายุนิยามตามมาตรฐานสากลคือ",
    ["ใช้ยา ≥ 5 ชนิดพร้อมกัน", "ใช้ยา ≥ 10 ชนิดพร้อมกัน", "ใช้ยาเกินขนาดที่กำหนด", "ใช้สมุนไพรร่วมกับยาแผนปัจจุบัน"],
    "A",
    "Polypharmacy = การใช้ยา 5 ชนิดขึ้นไป; เพิ่มเสี่ยง drug interaction, falls, ADRs",
    "Excessive polypharmacy = ≥ 10 ชนิด",
    ["ใช่ — มาตรฐาน", "Excessive polypharmacy", "ไม่ใช่ definition", "Herbal interaction เป็นอีกประเด็น"],
    "Polypharmacy ≥ 5 medications"),
  q(GERI,
    "ผู้ป่วย Alzheimer's ระยะกลาง ครอบครัวบ่นว่าผู้ป่วยซ้ำเรื่องบ่อย ลืมชื่อหลาน เทคนิคการสื่อสารที่เหมาะสมคือ",
    ["ขัดจังหวะให้หยุดถาม", "ใช้ประโยคสั้น ตรงประเด็น ทวนช้า ๆ มอง eye contact", "บอกความจริงทุกอย่างย้ำ ๆ", "เปลี่ยนสภาพแวดล้อมบ่อยเพื่อให้ตื่นตัว"],
    "B",
    "Therapeutic communication: ประโยคสั้น น้ำเสียงสงบ ทำให้ผู้ป่วยรู้สึกปลอดภัย",
    "Reality orientation ใช้กับ delirium แต่ไม่เหมาะกับ moderate dementia — อาจใช้ validation therapy",
    ["เพิ่ม agitation", "ใช่ — therapeutic communication", "อาจเพิ่ม distress", "เปลี่ยนสิ่งแวดล้อม → agitation"],
    "Dementia: short, calm, predictable + validation"),
  q(GERI,
    "ผู้สูงอายุน้ำหนักลด 3 กก. ใน 1 เดือน แนวทางคัดกรอง malnutrition ที่เหมาะสมคือ",
    ["BMI ตอนเดียว", "Mini Nutritional Assessment (MNA)", "Hemoglobin", "BUN/Cr"],
    "B",
    "MNA-SF เป็น tool validated ในผู้สูงอายุ — คัดกรอง malnutrition risk",
    "BMI อย่างเดียวไม่จับ early decline; Hb/BUN เป็น downstream",
    ["ข้อจำกัดสูง", "ใช่ — gold standard screening", "บอก anemia", "บอก renal/dehydration"],
    "Malnutrition screen ผู้สูงอายุ: MNA-SF"),
  q(GERI,
    "End-of-life planning: 'Living will' ตามกฎหมายไทย (พ.ร.บ.สุขภาพแห่งชาติ ม.12) มีลักษณะใด",
    ["คำสั่งให้ทำการุณยฆาต", "หนังสือแสดงเจตนาปฏิเสธการรักษาที่ยืดความตาย", "บังคับแพทย์ทุกราย", "ใช้กับผู้ป่วยจิตเวชเท่านั้น"],
    "B",
    "ม.12 ให้สิทธิแสดงเจตนาล่วงหน้าปฏิเสธการรักษาที่ยืดความตายในวาระสุดท้าย — ไม่ใช่ euthanasia",
    "แพทย์/พยาบาลที่ปฏิบัติตามไม่ถือว่าผิดวิชาชีพ",
    ["ไม่ใช่ — กฎหมายไม่อนุญาต euthanasia", "ใช่ — มาตรา 12", "เป็นสิทธิผู้ป่วย ไม่บังคับสถานพยาบาล", "ใช้กับผู้ป่วยทุกประเภท"],
    "ม.12: ปฏิเสธการยืดความตาย ≠ euthanasia"),
  q(GERI,
    "Orthostatic hypotension ในผู้สูงอายุ definition คือ",
    ["BP ลด ≥ 20/10 mmHg เมื่อเปลี่ยนท่ายืนภายใน 3 นาที", "BP ลด ≥ 5/2 mmHg", "HR เพิ่ม > 30 bpm", "BP ลดขณะนั่ง"],
    "A",
    "Orthostatic HT: SBP ลด ≥ 20 หรือ DBP ลด ≥ 10 ภายใน 3 นาทีเมื่อเปลี่ยนเป็นท่ายืน",
    "เพิ่มเสี่ยง falls; สาเหตุ: dehydration, antihypertensive, autonomic neuropathy",
    ["ใช่ — definition", "เกณฑ์ต่ำเกินไป", "นั่นคือ POTS ไม่ใช่ OH", "Definition ใช้ท่ายืนเทียบ"],
    "Orthostatic HT: ↓SBP ≥20 / ↓DBP ≥10 ภายใน 3 นาที"),
  q(GERI,
    "Vaccination ที่แนะนำสำหรับผู้สูงอายุ ≥ 65 ปี ในไทย ได้แก่",
    ["BCG", "Influenza ปีละครั้ง + Pneumococcal + COVID-19 booster", "MMR", "Yellow fever"],
    "B",
    "ผู้สูงอายุ ≥ 65: flu ปีละ 1 + PCV/PPSV + COVID booster ตามคำแนะนำ",
    "BCG/MMR/YF ไม่จำเป็น routinely ในผู้สูงอายุไทย",
    ["ใช้ในทารก", "ใช่ — แนะนำ", "ไม่จำเป็น routine", "ใช้กับเดินทางเขตเสี่ยง"],
    "Elder vaccines: Flu + Pneumococcal + COVID"),
  q(GERI,
    "ผู้สูงอายุท้องผูกเรื้อรัง ขั้นแรกที่พยาบาลควรแนะนำคือ",
    ["ให้ stimulant laxative ทุกวัน", "เพิ่มน้ำ ใยอาหาร และ activity", "สวนอุจจาระประจำ", "ใช้ enema"],
    "B",
    "First-line constipation: น้ำ 1.5–2 L/วัน + fiber 25–30 g + เคลื่อนไหว + ฝึกขับถ่ายเป็นเวลา",
    "Stimulant laxative ใช้ระยะสั้น; sennoside, bisacodyl",
    ["ระยะสั้น", "ใช่ — first-line", "ทำให้ depend", "ใช้เมื่อ impaction"],
    "Constipation: น้ำ + ใย + เคลื่อนไหว ก่อนเสมอ"),
  q(GERI,
    "ผู้สูงอายุมีอาการ depression ลักษณะแตกต่างจากวัยทำงานคือ",
    ["มี somatic complaint, ความจำลด, ปลีกตัว มากกว่า sad mood ที่ชัดเจน", "Mania ชัดเจน", "Insight ดีเสมอ", "เลือก ECT ก่อนเสมอ"],
    "A",
    "Geriatric depression มักแสดงเป็น somatization, pseudo-dementia, withdrawal มากกว่า low mood ที่ verbal",
    "Tool: Geriatric Depression Scale (GDS-15)",
    ["ใช่ — atypical presentation", "Mania พบน้อย", "Insight มัก poor", "ECT reserve สำหรับ severe/treatment-resistant"],
    "Geriatric depression: ใช้ GDS-15"),
  q(GERI,
    "ผู้สูงอายุใช้ NSAID เรื้อรัง เพิ่มความเสี่ยงสำคัญที่สุดต่อ",
    ["GI bleeding และ AKI", "Hypoglycemia", "Hypothyroidism", "Iron overload"],
    "A",
    "NSAIDs ในผู้สูงอายุ: GI bleed, renal injury, HF exacerbation, hypertension",
    "Beers แนะนำหลีกเลี่ยง chronic NSAIDs > 65 ปี",
    ["ใช่ — major ADRs", "ไม่ใช่ NSAID", "ไม่ใช่", "ไม่ใช่"],
    "NSAID elders: หลีกเลี่ยง / ระวัง GI + renal"),
  q(GERI,
    "ผู้สูงอายุ delirium ใน ICU การจัดการ non-pharmacological ที่ถูกต้องคือ",
    ["มัดผู้ป่วยให้สงบ", "ให้แสงตามเวลากลางวัน-กลางคืน, reorientation, ครอบครัวเยี่ยม, ลด noise/sedative", "เพิ่ม BZD", "Isolate room"],
    "B",
    "Non-pharm: orientation, mobility, sleep promotion, family presence ลด delirium duration",
    "BZD เพิ่ม risk; restraints เพิ่ม agitation",
    ["ทำให้แย่ลง", "ใช่ — ABCDEF bundle", "BZD = delirium driver", "Isolation = sensory deprivation"],
    "ICU delirium: ABCDEF bundle, ไม่ใช่ BZD"),
  q(GERI,
    "Sarcopenia ในผู้สูงอายุ คือ",
    ["การลดมวลกล้ามเนื้อและความแข็งแรงตามวัย", "การลดมวลกระดูก", "กล้ามเนื้อกระตุก", "ภาวะแก่เร็ว"],
    "A",
    "Sarcopenia: ↓muscle mass + ↓strength/function; เพิ่ม fall, frailty",
    "การจัดการ: resistance exercise + protein 1.0–1.2 g/kg/วัน + vitamin D",
    ["ใช่ — definition", "Osteoporosis", "Myoclonus", "Progeria"],
    "Sarcopenia: ออกกำลังกาย + protein + วิตามินดี"),
  q(GERI,
    "ผู้สูงอายุ DM type 2 HbA1c target ที่เหมาะสมขึ้นกับ",
    ["ตั้งเป้า < 6.5% ทุกราย", "Individualize: 7–7.5% ในคนแข็งแรง, 8–8.5% ใน frail/limited life expectancy", "ต่ำสุดเท่าที่ทำได้เสมอ", "ไม่ต้องตั้งเป้า"],
    "B",
    "ADA: HbA1c target ขึ้นกับ life expectancy, comorbidities, hypoglycemia risk",
    "Frail elder: เป้าหลีกเลี่ยง hypoglycemia สำคัญกว่า tight control",
    ["Tight target = เสี่ยง hypo", "ใช่ — individualized", "เพิ่ม hypoglycemia/falls", "ต้องมีเป้าหมาย"],
    "Elder DM: target ตาม frailty & life expectancy"),
  q(GERI,
    "ผู้สูงอายุที่เริ่มใช้ walker การสอนเดินที่ถูกต้องคือ",
    ["ยก walker ก่อน → ก้าวขาที่เจ็บ → ขาดี", "ก้าวขาดีไปก่อน → walker → ขาเจ็บ", "วาง walker ไว้กับที่ ดันตัวข้ามไป", "ยก walker เหนือศีรษะ"],
    "A",
    "Walker gait: walker ออกก่อน, ตามด้วยขาเจ็บ, แล้วขาแข็งแรง",
    "ลด weight bearing ของขาเจ็บและเพิ่ม stability",
    ["ใช่ — มาตรฐาน partial weight-bearing", "ผิดลำดับ — เสี่ยง fall", "ไม่ปลอดภัย", "อันตราย"],
    "Walker: 'walker → bad leg → good leg'"),
  q(GERI,
    "ผู้สูงอายุได้ Furosemide ระยะยาว ต้องตรวจ electrolyte ใดสม่ำเสมอ",
    ["Sodium, Potassium, Magnesium, Calcium", "Iron level", "Lead level", "Mercury"],
    "A",
    "Loop diuretics ทำให้ ↓K, ↓Mg, ↓Na, ↓Ca → arrhythmia, weakness",
    "ต้องติดตาม electrolyte ทุก 3–6 เดือนหรือเมื่อปรับยา",
    ["ใช่ — มาตรฐาน", "ไม่เกี่ยว", "ไม่เกี่ยว", "ไม่เกี่ยว"],
    "Furosemide: เช็ค Na/K/Mg/Ca"),
  q(GERI,
    "Frailty syndrome ตาม Fried criteria ประกอบด้วยข้อใด",
    ["Weight loss, exhaustion, low activity, slow walking, weak grip (≥3)", "Hypertension + DM", "Cognitive impairment เพียงอย่างเดียว", "Falls ครั้งเดียว"],
    "A",
    "Fried phenotype: ≥3 จาก 5 criteria = frail; 1–2 = pre-frail",
    "เพิ่ม mortality, disability, hospitalization",
    ["ใช่ — Fried 5 items", "เป็น comorbidities", "Cognitive only ≠ frailty", "Falls = consequence ไม่ใช่ definition"],
    "Frail = ≥3/5 Fried criteria"),
  q(GERI,
    "ผู้สูงอายุนอนยาวบนเตียง 3 วัน เริ่มเห็นรอยแดงไม่จาง ที่ sacrum การจัดการขั้นแรกคือ",
    ["พลิกตะแคงทุก 2 ชม + offload + ใช้ pressure-redistribution mattress", "ทำแผลด้วย iodine แล้วปิด occlusive", "นวดบริเวณแดง", "เปลี่ยนยา IV antibiotic"],
    "A",
    "Stage I: relieve pressure + repositioning q2h + risk assessment + skin care",
    "การนวดบริเวณ pressure ห้าม — เพิ่มความเสียหายต่อหลอดเลือดเล็ก",
    ["ใช่ — first action", "Iodine ไม่ใช่ first-line, จะ delay healing", "ห้ามนวด", "ยังไม่มี infection"],
    "Stage I PU: pressure relief + reposition q2h"),
  q(GERI,
    "Advance Care Planning ในผู้สูงอายุที่เหมาะสมที่สุดเริ่มเมื่อ",
    ["รอจนเข้า ICU", "เริ่มในขณะที่ยังตัดสินใจได้ ในชุมชนหรือ OPD", "ครอบครัวเป็นคนตัดสินใจฝ่ายเดียว", "เริ่มเมื่อมี dementia ขั้นรุนแรง"],
    "B",
    "ACP ควรเริ่มเชิงรุกขณะ capacity ยังดี เพื่อให้ผู้ป่วยกำหนดเป้าหมาย และเลือกผู้แทน",
    "หากเริ่มในวิกฤต ครอบครัวต้องเดาเจตนา — สร้าง moral distress",
    ["สายเกินไปและไม่ปลอดภัย", "ใช่ — early ACP", "ขัด autonomy", "ตอนนั้น capacity หาย"],
    "ACP: เริ่ม early, ขณะมี capacity"),
  q(GERI,
    "Geriatric pharmacology: 'start low, go slow' มีเหตุผลทาง pharmacokinetic หลักคือ",
    ["↑ hepatic clearance + ↑ renal clearance", "↓ renal clearance + ↑ Vd ของยาที่ละลายในไขมัน + ↓ albumin (↑ free fraction)", "เนื้อเยื่อตอบสนองยาน้อยลง", "ไม่มีเหตุผล"],
    "B",
    "ผู้สูงอายุ: ↓CrCl, ↑Vd ของ lipophilic drugs (BZD), ↓ albumin → ต้องลดขนาดเริ่มและ titrate ช้า",
    "GFR ลด ~1 mL/min/year หลัง 40 ปี; ปรับ dose ตาม Cockcroft-Gault หรือ CKD-EPI",
    ["ตรงข้าม — clearance ลด", "ใช่ — มาตรฐาน", "ไม่ใช่ PK", "มีเหตุผลทาง PK"],
    "Elder Rx: start low, go slow — PK changes"),

  // ============================================================
  // 3) NursingPediatric — การพยาบาลเด็กและวัยรุ่น (25)
  // ============================================================
  q(PEDS,
    "ทารกแรกเกิดน้ำหนัก 3,200 g อายุ 6 ชม. พบ jaundice ใต้คาง พยาบาลควร",
    ["ส่ง phototherapy ทันที", "ถือเป็น pathological — รายงานแพทย์เพื่อตรวจ bilirubin", "อธิบายว่าเป็นปกติ", "ให้นมเพิ่ม"],
    "B",
    "Jaundice ภายใน 24 ชม.แรก = pathological — ต้องหาสาเหตุ (ABO/Rh incompatibility, G6PD)",
    "Physiological jaundice เริ่มหลัง 24 ชม. และสูงสุดวัน 3–5",
    ["ก่อนหา cause", "ใช่ — pathological จนกว่าจะพิสูจน์", "อันตราย", "ช่วยได้แต่ไม่ใช่ขั้นแรก"],
    "Jaundice < 24 hr = pathological"),
  q(PEDS,
    "เด็ก 2 ปี dehydration moderate (~7%) ตามแนว WHO ORS ให้",
    ["ให้น้ำเปล่า", "ORS 75 mL/kg ภายใน 4 ชม.", "IV 100 mL/kg ทุกราย", "งดน้ำเพื่อพักลำไส้"],
    "B",
    "Some dehydration: ORS 75 mL/kg ในรอบ 4 ชม. แล้วประเมินซ้ำ",
    "Severe (>10%) หรือ shock = IV rehydration",
    ["Hypotonic + ไม่มี electrolyte", "ใช่ — WHO Plan B", "ใช้ใน severe เท่านั้น", "ผิด — feed early"],
    "Some dehydration: ORS 75 mL/kg × 4 hr"),
  q(PEDS,
    "วัคซีน EPI อายุ 9 เดือน คือ",
    ["BCG + HBV1", "MMR + JE", "DTP-HB-Hib3", "Tdap"],
    "B",
    "EPI ไทยอายุ 9 เดือน: MMR เข็มแรก + JE (encephalitis)",
    "DTP-HB-Hib3 ที่ 6 เดือน; BCG/HBV ที่แรกเกิด",
    ["ที่แรกเกิด", "ใช่ — 9 เดือน", "6 เดือน", "11–12 ปี (booster)"],
    "9 เดือน: MMR + JE"),
  q(PEDS,
    "เด็ก 3 ปี croup มีอาการหายใจ stridor, barking cough ขั้นแรกที่ ER",
    ["ให้ adrenaline IV ทันที", "ให้ humidified O₂ ถ้า hypoxic + nebulized epinephrine + dexamethasone PO/IM", "ใส่ ET tube ทันที", "Aspirin"],
    "B",
    "Moderate-severe croup: dexamethasone 0.6 mg/kg + nebulized epinephrine ถ้า stridor at rest",
    "Intubation reserve สำหรับ impending respiratory failure",
    ["IV epi ไม่ใช่ first-line", "ใช่ — มาตรฐาน", "ทำเมื่อ fail medical", "ห้าม < 16 ปี (Reye)"],
    "Croup: dex + neb epi"),
  q(PEDS,
    "เด็ก 8 ปี asthma exacerbation moderate ขั้นแรกของการรักษาคือ",
    ["Oxygen + SABA (salbutamol) nebulized + systemic steroid", "IV theophylline", "Sedation", "Antibiotic"],
    "A",
    "Asthma attack: O₂ + nebulized salbutamol q20min × 3 + prednisolone oral",
    "Antibiotic ไม่ routine ถ้าไม่มี bacterial co-infection",
    ["ใช่ — first-line", "Reserve — narrow therapeutic", "ห้าม — กด respiration", "เฉพาะถ้ามี evidence ติดเชื้อ"],
    "Asthma: O₂ + SABA + steroid"),
  q(PEDS,
    "เด็ก 5 ปี ไข้สูง 39.5°C ปวดศีรษะ คอแข็ง พบ petechial rash อาการที่กังวลคือ",
    ["Meningococcal meningitis — ต้อง isolate + IV ceftriaxone ทันที", "Roseola", "Hand-foot-mouth", "Varicella"],
    "A",
    "Fever + neck stiffness + petechiae = meningococcemia/meningitis ฉุกเฉิน",
    "Empiric ceftriaxone IV + droplet precaution + รายงานควบคุมโรค",
    ["ใช่ — emergency", "Roseola: ไข้ 3–5 วันแล้วผื่น maculopapular", "HFM: ตุ่มใสมือเท้าปาก", "Varicella: ตุ่มน้ำ vesicles"],
    "ไข้ + คอแข็ง + petechiae = meningococcus"),
  q(PEDS,
    "ทารกแรกเกิด Apgar 1 นาที = 5 (HR 110, RR irregular, tone หย่อน, ตอบสนองน้อย, สีปลายมือเท้าเขียว) ขั้นแรก",
    ["Drying + warmth + stimulation + O₂ ถ้าจำเป็น", "Intubation ทันที", "CPR + epinephrine", "Glucose IV bolus"],
    "A",
    "NRP: dry, warm, stimulate ภายใน 30 วินาที; ประเมิน HR เป็นหลัก",
    "ถ้า HR < 100 → PPV; < 60 → CPR",
    ["ใช่ — first step", "เมื่อ PPV ไม่ effective", "เมื่อ HR < 60", "ไม่ใช่ first step"],
    "NRP: dry → warm → stimulate → HR"),
  q(PEDS,
    "ขนาดยา paracetamol oral ในเด็ก",
    ["5 mg/kg q4–6 hr", "10–15 mg/kg q4–6 hr (max 75 mg/kg/day)", "30 mg/kg q4 hr", "1 mg/kg q12 hr"],
    "B",
    "Paracetamol pediatric: 10–15 mg/kg/dose ทุก 4–6 ชม., max 75 mg/kg/day",
    "Overdose → hepatotoxicity; antidote = N-acetylcysteine",
    ["ต่ำเกินไป", "ใช่ — มาตรฐาน", "เกิน max — toxicity", "ต่ำเกินไป"],
    "Paracetamol เด็ก: 10–15 mg/kg q4–6 hr"),
  q(PEDS,
    "เด็ก 6 ปี nephrotic syndrome อาหารที่ถูกต้องคือ",
    ["High protein, high sodium", "Adequate protein (1–1.5 g/kg), low sodium", "No protein", "High fat"],
    "B",
    "Nephrotic: protein พอเหมาะ (ไม่ high), จำกัด sodium ลด edema",
    "High protein เคยเชื่อกัน แต่ปัจจุบันแนะนำ normal protein",
    ["High Na = edema", "ใช่ — มาตรฐาน", "ขาด protein", "ไม่เกี่ยวกับ pathology"],
    "Nephrotic kids: adequate protein, low Na"),
  q(PEDS,
    "การวัด head circumference ในทารก ช่วงวัยที่สำคัญที่สุดในการ monitor คือ",
    ["0–2 ปี", "3–5 ปี", "6–10 ปี", "ตลอดชีวิต"],
    "A",
    "Brain growth สูงสุด 0–2 ปี → HC sensitive marker ของ macro/microcephaly",
    "พล็อตบน growth chart ทุก well-child visit",
    ["ใช่ — critical period", "Growth velocity ลดลง", "ลดลงมาก", "ไม่ routine ผู้ใหญ่"],
    "HC: monitor 0–2 ปี"),
  q(PEDS,
    "ทารก 4 เดือน normal milestone ประมาณคือ",
    ["เดิน", "ชันคอได้, ยิ้มทักทาย, คว้าจับสิ่งของ", "พูดเป็นประโยค", "วิ่ง"],
    "B",
    "4 เดือน: head control, social smile, reaches for objects, rolls",
    "Walking ~12 เดือน; sentences ~24 เดือน",
    ["12 เดือน", "ใช่ — 4 เดือน milestones", "24 เดือน", "18 เดือน"],
    "4 mo: head control + reach + smile"),
  q(PEDS,
    "เด็ก 2 ปี กลืน button battery การจัดการที่ถูกต้องคือ",
    ["รอ 24 ชม. ดูถ้าออกเอง", "ส่ง X-ray + เร่งเอาออกถ้าค้างที่ esophagus ภายใน 2 ชม", "ให้ดื่มนม", "ให้ activated charcoal"],
    "B",
    "Button battery in esophagus = surgical emergency; lithium burn ภายใน 2 ชม",
    "ถ้าผ่าน stomach แล้ว และไม่มีอาการ → monitor",
    ["อันตราย — necrosis", "ใช่ — emergency endoscopic removal", "ไม่ช่วย", "ไม่ใช่ poisoning โดยตรง"],
    "Button battery esophagus = emergency!"),
  q(PEDS,
    "เด็กที่สงสัย child abuse พยาบาลควร",
    ["ตักเตือนพ่อแม่และปล่อยกลับบ้าน", "รายงานตามกฎหมาย (พ.ร.บ.คุ้มครองเด็ก พ.ศ. 2546) และทำ documentation ละเอียด", "ลงมือสอบสวนเอง", "ปกปิดเพื่อรักษาความสัมพันธ์ครอบครัว"],
    "B",
    "Mandatory reporting ตาม พ.ร.บ.คุ้มครองเด็ก; บันทึก injury, history mismatch, photo",
    "ปฏิเสธ/ปกปิด = ผิดวิชาชีพและกฎหมาย",
    ["อันตรายเด็ก", "ใช่ — duty to report", "ไม่ใช่หน้าที่พยาบาล", "ผิดทั้งกฎหมายและจริยธรรม"],
    "Child abuse: รายงาน + document"),
  q(PEDS,
    "Salmonella gastroenteritis ในเด็ก management หลักคือ",
    ["Antibiotic ทุกราย", "Rehydration เป็นหลัก, ใช้ ATB เฉพาะ invasive disease หรือ < 3 เดือน/immunocompromised", "Antimotility (loperamide)", "งดน้ำ"],
    "B",
    "Self-limited; ATB ในกลุ่มเสี่ยงเท่านั้น เพื่อลด carrier state",
    "Loperamide ห้ามในเด็ก ↑risk megacolon",
    ["Overuse + resistance", "ใช่ — ตาม IDSA", "ห้ามในเด็กที่มี invasive disease", "ผิด — ต้อง rehydrate"],
    "Salmonella เด็ก: rehydrate, ATB selective"),
  q(PEDS,
    "เด็ก 18 เดือน ปฏิเสธอาหาร น้ำหนักลด พ่อแม่กังวล คำแนะนำที่ถูกต้องคือ",
    ["บังคับให้กิน", "Offer healthy food หลายอย่าง, ทานพร้อมครอบครัว, ไม่บังคับ, ใช้ portion ขนาดเด็ก", "ตัดอาหารหลักออก ให้เฉพาะขนม", "ให้ใช้ supplement formula แทนอาหาร"],
    "B",
    "Toddler 'physiological anorexia' พบบ่อย; division of responsibility: ผู้ใหญ่เลือกอาหาร เด็กตัดสินใจเอง",
    "Force-feeding เพิ่มปัญหา; supplement ใช้เฉพาะ failure to thrive",
    ["เสีย relationship กับอาหาร", "ใช่ — feeding guidance", "Nutritional imbalance", "ต้องประเมินก่อน"],
    "Toddler picky eater: offer, no force, family meals"),
  q(PEDS,
    "Pediatric BLS อัตรา compression : ventilation ในเด็ก 1 rescuer คือ",
    ["15:2", "30:2", "5:1", "100:2"],
    "B",
    "Pediatric BLS 1-rescuer = 30:2; 2-rescuer = 15:2; rate 100–120/min, depth 1/3 AP diameter",
    "ผู้ใหญ่ใช้ 30:2 เสมอ",
    ["2-rescuer เด็ก", "ใช่ — single rescuer", "นานเกินไป", "ผิด"],
    "Pediatric BLS: 30:2 (1R), 15:2 (2R)"),
  q(PEDS,
    "เด็ก 5 ปี acute otitis media first-line antibiotic คือ",
    ["Amoxicillin 80–90 mg/kg/day", "Vancomycin", "Ciprofloxacin", "Erythromycin"],
    "A",
    "AOM: amoxicillin high-dose 80–90 mg/kg/day แบ่ง 2–3 ครั้ง เป็น first-line ทุก guideline",
    "ถ้าแพ้ penicillin → cefdinir / azithromycin",
    ["ใช่ — first-line", "ไม่ใช่ outpatient first-line", "Not in young kids — cartilage", "Resistance สูงในไทย"],
    "AOM: high-dose amoxicillin"),
  q(PEDS,
    "Hemolytic Disease of Newborn จาก Rh incompatibility การป้องกันคือ",
    ["ให้ Rho(D) Ig 28 สัปดาห์ของหญิงตั้งครรภ์ Rh- และภายใน 72 ชม. หลังคลอดถ้าทารก Rh+", "ให้กับทารกหลังคลอด", "ตรวจ HbA1c", "ฉีด vitamin K"],
    "A",
    "RhoGAM ที่ 28 wks + postpartum (Rh- mom กับ Rh+ baby) ลด maternal sensitization",
    "Vitamin K ป้องกัน hemorrhagic disease ของทารก ไม่ใช่ HDN",
    ["ใช่ — มาตรฐาน", "ให้แม่ ไม่ใช่ทารก", "ไม่เกี่ยว", "Different indication"],
    "Rh-: RhoGAM 28 wk + within 72 hr postpartum"),
  q(PEDS,
    "เด็ก 7 ปี ADHD การจัดการ first-line ที่แนะนำคือ",
    ["Stimulant + behavioral therapy", "ECT", "Antipsychotic เริ่มก่อน", "BZD"],
    "A",
    "ADHD: stimulant (methylphenidate) + behavior therapy เป็น first-line; non-stimulant (atomoxetine) เป็น second",
    "Behavioral parent training ใน < 6 ปี อาจให้ก่อนยา",
    ["ใช่ — มาตรฐาน", "ไม่ใช่ first-line", "ไม่ใช่ first-line", "เพิ่มเสี่ยง dependence"],
    "ADHD: stimulant + behavior therapy"),
  q(PEDS,
    "Sickle cell crisis เด็ก ความสำคัญในการพยาบาลคือ",
    ["Hydration + pain control + O₂ ถ้า hypoxic + identify trigger", "งดน้ำ", "ใช้ tourniquet ที่แขน", "ออกกำลังกายเต็มที่"],
    "A",
    "Vaso-occlusive crisis: IV fluid, opioid analgesia, O₂ ถ้า SpO₂ < 95%, ลด trigger",
    "หา/ป้องกัน infection ซึ่งเป็น trigger สำคัญ",
    ["ใช่ — มาตรฐาน", "อันตราย — กระตุ้น sickling", "ไม่ใช่", "ในระยะ crisis ห้าม"],
    "SCD crisis: IVF + analgesia + O₂"),
  q(PEDS,
    "ทารกแรกเกิดอายุ 1 ชม. มี grunting RR 70 retraction พยาบาลควร",
    ["รอดูอาการ", "แจ้งแพทย์ทันที สงสัย respiratory distress syndrome หรือ TTN", "ให้นม", "ห่อผ้าให้อุ่นอย่างเดียว"],
    "B",
    "Respiratory distress signs in newborn → ประเมิน, monitor O₂, support, รายงาน MD",
    "Causes: TTN, RDS, sepsis, MAS, congenital heart",
    ["อันตราย", "ใช่ — ต้องประเมินทันที", "เพิ่ม aspiration", "ไม่ครอบคลุม cause"],
    "Newborn distress = urgent assessment"),
  q(PEDS,
    "การให้ ORS ในเด็กที่มีท้องเสีย ปริมาณที่ถูกต้องคือ",
    ["50–100 mL หลังถ่ายเหลวแต่ละครั้ง (อายุ < 2)", "1 ลิตรทันที", "งด ORS", "ใช้ Coca-Cola แทน"],
    "A",
    "WHO Plan A: < 2 ปี ให้ 50–100 mL หลังถ่ายแต่ละครั้ง; ≥ 2 ปี 100–200 mL",
    "ห้ามใช้น้ำหวาน/น้ำอัดลม — osmotic load สูงทำ diarrhea หนัก",
    ["ใช่ — Plan A", "Volume overload", "ผิด", "อันตราย — high sugar"],
    "ORS Plan A: 50–100 mL/stool ใน < 2 ปี"),
  q(PEDS,
    "เด็ก vaccine ที่ห้ามฉีดให้ผู้ที่ immunocompromised severe คือ",
    ["Inactivated influenza", "MMR / BCG / OPV (live vaccines)", "DTP", "Hepatitis B"],
    "B",
    "Live attenuated vaccines (MMR, BCG, OPV, varicella) ห้ามใน severe immunocompromised",
    "Inactivated vaccines ปลอดภัย",
    ["Safe", "ใช่ — ห้าม", "Inactivated", "Recombinant"],
    "Immunocompromised: NO live vaccines"),
  q(PEDS,
    "เด็ก 2 ปี ingestion paracetamol overdose 200 mg/kg ทำอย่างไร",
    ["รอดูอาการ", "ส่งวัด acetaminophen level 4 ชม.หลัง ingestion + ให้ N-acetylcysteine ถ้าอยู่บน Rumack-Matthew line", "ให้นมล้าง", "ใช้ ipecac"],
    "B",
    "Toxic dose > 150 mg/kg; 4-hr level plot บน Rumack-Matthew nomogram ตัดสินใจ NAC",
    "NAC effective สูงสุดใน 8–10 ชม.แรก",
    ["อันตราย", "ใช่ — มาตรฐาน", "ไม่ป้องกัน toxicity", "Ipecac ห้ามใช้ในปัจจุบัน"],
    "Paracetamol OD: level @ 4hr + NAC"),
  q(PEDS,
    "Pediatric IV calculation: ให้ D5W 500 mL ใน 8 ชม drop factor 60 gtt/mL อัตรา drop คือ",
    ["62 gtt/min", "63 gtt/min", "31 gtt/min", "16 gtt/min"],
    "A",
    "(500 × 60) / (8 × 60) = 30000/480 ≈ 62.5 → 62–63 gtt/min",
    "Drop rate = volume × drop factor / total minutes",
    ["ใช่ — ถูกต้อง", "ปัดต่างกัน — ยอมรับได้", "ครึ่งหนึ่ง", "1/4"],
    "Drop rate = (mL × gtt/mL) / min"),

  // ============================================================
  // 4) NursingMaternal — การพยาบาลมารดาและทารก (25)
  // ============================================================
  q(MAT,
    "หญิงตั้งครรภ์ 28 สัปดาห์ ตรวจพบ proteinuria 2+, BP 150/100 อาการนี้สงสัย",
    ["Gestational hypertension", "Preeclampsia", "Chronic HTN", "Normal"],
    "B",
    "Preeclampsia = HT (≥140/90) + proteinuria หลัง 20 สัปดาห์",
    "Severe features: BP ≥ 160/110, plt < 100k, LFT สูง, headache/visual change, pulmonary edema",
    ["ขาด proteinuria", "ใช่ — เกณฑ์ครบ", "ต้องมีก่อน 20 wk", "ผิด"],
    "Preeclampsia: HT + proteinuria > 20 wk"),
  q(MAT,
    "การให้ MgSO₄ ใน severe preeclampsia เพื่อป้องกัน eclampsia ขนาด loading คือ",
    ["1 g IV", "4–6 g IV ใน 15–20 นาที แล้ว 1–2 g/hr drip", "10 g IV bolus", "0.5 g IM"],
    "B",
    "MgSO₄ loading 4–6 g IV + maintenance 1–2 g/hr; monitor DTR, RR, urine output",
    "Antidote = calcium gluconate ถ้า toxicity",
    ["น้อยเกินไป", "ใช่ — มาตรฐาน", "Toxic", "เป็น IM regimen เก่า ไม่ใช้ทั่วไป"],
    "MgSO₄: 4–6 g load + 1–2 g/hr"),
  q(MAT,
    "Sign of MgSO₄ toxicity คือ",
    ["DTR หาย, RR < 12, urine < 30 mL/hr", "ปัสสาวะมาก", "BP สูง", "ไข้สูง"],
    "A",
    "Toxicity: DTR หาย → respiratory depression → cardiac arrest",
    "Antidote: 10% calcium gluconate 1 g IV",
    ["ใช่ — มาตรฐาน sign", "ไม่ใช่ toxicity", "ไม่ใช่ sign", "ไม่ใช่ sign"],
    "MgSO₄ toxicity: ↓DTR, ↓RR, ↓urine → Ca"),
  q(MAT,
    "หญิงตั้งครรภ์ ANC แรกที่ควรตรวจคือ",
    ["Pap smear เท่านั้น", "ABO/Rh, CBC, VDRL, HBsAg, HIV, urinalysis, blood sugar", "X-ray pelvis", "Mammogram"],
    "B",
    "ANC แรก: routine labs ครบ + การประเมิน risk + GA",
    "Mammogram/X-ray หลีกเลี่ยงในไตรมาสแรกถ้าไม่จำเป็น",
    ["ไม่ใช่ routine ตอนตั้งครรภ์", "ใช่ — มาตรฐาน", "Radiation", "ไม่ใช่ routine"],
    "ANC1: blood group + CBC + VDRL + HBsAg + HIV"),
  q(MAT,
    "GDM screening ตามแนวทาง: OGTT 75g ที่ GA",
    ["12–16 wk", "24–28 wk", "36 wk", "หลังคลอด"],
    "B",
    "Universal GDM screening 24–28 wk ด้วย 75g OGTT (fasting, 1hr, 2hr)",
    "เกณฑ์ Carpenter-Coustan หรือ IADPSG",
    ["Early test ใช้ใน high risk", "ใช่ — มาตรฐาน", "ช้าไป", "หลังคลอดเป็น postpartum DM screen"],
    "GDM: OGTT 24–28 wk"),
  q(MAT,
    "Placenta previa อาการนำคือ",
    ["Painful vaginal bleeding", "Painless vaginal bleeding หลัง 20 wk", "ไม่มีเลือดเลย", "ปวดท้องน้อยรุนแรง"],
    "B",
    "Placenta previa: painless bleeding (vs placental abruption = painful)",
    "ห้าม PV exam จนกว่าจะ ultrasound ยืนยัน",
    ["= abruption", "ใช่ — classic", "ทุกรายมี bleeding", "= abruption"],
    "Previa: painless bleed; Abruption: painful"),
  q(MAT,
    "Placental abruption สัญญาณคือ",
    ["Painless bleeding", "Painful bleeding + uterine tetany + fetal distress", "ทารกดิ้นมาก", "ไม่มีการเปลี่ยนแปลง"],
    "B",
    "Abruption: pain + tetanic uterus + fetal heart abnormality; ความเสี่ยงสูงต่อ mother & fetus",
    "อาจไม่มี external bleed ถ้า concealed",
    ["Previa", "ใช่ — classic abruption", "Tetany ทำให้ fetal compromise", "ผิด — life-threatening"],
    "Abruption: pain + rigid uterus + distress"),
  q(MAT,
    "Postpartum hemorrhage definition (vaginal birth) คือ",
    ["EBL > 100 mL", "EBL > 500 mL (vaginal) / > 1000 mL (C/S) หรือ signs of hypovolemia", "EBL > 5000 mL", "ไม่นับเลือดเลย"],
    "B",
    "PPH: EBL > 500/1000 mL หรือ signs of hypovolemia ใน 24 ชม.หลังคลอด",
    "4 T causes: Tone, Trauma, Tissue, Thrombin",
    ["Normal lochia", "ใช่ — definition", "Massive PPH", "ผิด"],
    "PPH: 500/1000 mL; 4T causes"),
  q(MAT,
    "การจัดการ PPH atonic uterus ขั้นแรกคือ",
    ["Massage uterus + ให้ uterotonic (oxytocin 10–40 IU/L)", "หยุดให้ IV fluid", "ผ่าตัด hysterectomy ทันที", "รอดูอาการ"],
    "A",
    "Atony: fundal massage + uterotonic (oxytocin → methergine → carboprost → misoprostol)",
    "Hysterectomy เป็น last resort",
    ["ใช่ — first action", "ห้าม — ต้อง resuscitate", "ทำเมื่อ medical fail", "Life-threatening — ต้องทำทันที"],
    "Atonic PPH: massage + oxytocin"),
  q(MAT,
    "หญิง Rh- คลอดทารก Rh+ ต้องให้",
    ["RhoGAM ภายใน 72 ชม.หลังคลอด", "ให้ทารก", "ไม่ต้องทำอะไร", "ตัด umbilical cord ทันที"],
    "A",
    "Postpartum RhoGAM ใน Rh- mother + Rh+ baby ภายใน 72 ชม. ลด sensitization",
    "Also ที่ 28 wk antenatal ทุก Rh- pregnancy",
    ["ใช่ — มาตรฐาน", "ให้แม่", "อันตราย — future pregnancy HDN", "ไม่ช่วย"],
    "Rh-: postpartum RhoGAM ใน 72 hr"),
  q(MAT,
    "Postpartum mother day 3 บ่นเศร้า ร้องไห้ง่าย นอนไม่หลับเป็นพัก ๆ ไม่มี suicidal ลักษณะนี้",
    ["Postpartum blues — ให้กำลังใจ + support ปกติหายเอง 2 wk", "Postpartum depression รุนแรง", "Postpartum psychosis", "Schizophrenia"],
    "A",
    "Postpartum blues พบ ~50–80% เริ่มวัน 3–5 หายเองภายใน 2 wk; PPD > 2 wk + functional impairment",
    "ถ้า > 2 wk หรือ severe → screen ด้วย Edinburgh PDS",
    ["ใช่ — blues", "ต้อง > 2 wk + impairment", "Hallucination/delusion", "ผิด"],
    "Blues vs PPD: blues < 2 wk; ไม่มี dysfunction"),
  q(MAT,
    "การประเมิน fundal height ใน postpartum day 1",
    ["บริเวณ symphysis pubis", "ที่ระดับสะดือ", "ใต้ลิ้นปี่", "ใต้ tide ใส้แตก"],
    "B",
    "Day 1: fundus อยู่ระดับสะดือ; ลงประมาณ 1 finger breadth/day; วันที่ 10 คลำไม่ได้",
    "Boggy uterus = atony → massage + uterotonic",
    ["10 วันหลังคลอด", "ใช่ — day 1", "ผิด", "ผิด"],
    "Postpartum fundus day 1: umbilicus"),
  q(MAT,
    "Lochia ในวันที่ 4 หลังคลอดควรเป็น",
    ["Rubra (สีแดงสด)", "Serosa (สีชมพู-น้ำตาล)", "Alba (สีขาว/เหลือง)", "ไม่มีเลย"],
    "B",
    "Day 1–3: Rubra; 4–10: Serosa; 11–14+: Alba",
    "Rubra ที่ยังต่อเนื่อง > 7 วัน = สงสัย retained placenta",
    ["Day 1–3", "ใช่ — day 4–10", "Day 11–14", "ผิด"],
    "Lochia: Rubra → Serosa → Alba"),
  q(MAT,
    "การให้นมแม่ที่ถูกต้องในชั่วโมงแรกหลังคลอด (Early initiation) มีประโยชน์",
    ["ไม่จำเป็น", "เพิ่ม bonding, กระตุ้น oxytocin → uterine contraction → ลด PPH, success breastfeeding", "เพิ่ม jaundice", "ไม่มีผล"],
    "B",
    "WHO/UNICEF Baby-friendly: skin-to-skin + breastfeeding ภายใน 1 ชั่วโมงแรก",
    "Colostrum รวยใน Ig และ growth factors",
    ["ตรงข้าม", "ใช่ — มาตรฐาน", "ผิด — ลด jaundice", "ผิด"],
    "Early breastfeeding: 1st hour skin-to-skin"),
  q(MAT,
    "Anemia in pregnancy ตาม WHO: Hb < ?",
    ["< 8", "< 11 g/dL", "< 13", "< 15"],
    "B",
    "Hb < 11 g/dL ทุกไตรมาส; ไตรมาส 2 cutoff < 10.5",
    "First-line: iron supplementation 60–120 mg elemental Fe + folate",
    ["Severe", "ใช่ — WHO", "Normal lower limit", "ไม่ใช่"],
    "Pregnancy anemia: Hb < 11"),
  q(MAT,
    "Hyperemesis gravidarum การจัดการ first-line คือ",
    ["NPO อย่างเดียว", "Pyridoxine + doxylamine, IV fluid (NSS หรือ LR), antiemetics (ondansetron/metoclopramide)", "Aspirin", "Steroid ทุกราย"],
    "B",
    "First-line: dietary + B6 (pyridoxine) ± doxylamine; ถ้ายัง vomiting → metoclopramide/ondansetron + IV rehydration",
    "Steroid reserve สำหรับ refractory case",
    ["ไม่พอ", "ใช่ — มาตรฐาน", "ไม่ใช่", "Reserved"],
    "HG: B6 + doxylamine + IVF"),
  q(MAT,
    "การประเมิน fetal well-being ที่ใช้ใน prenatal บ่อยที่สุดคือ",
    ["Fetal movement count (kick count)", "MRI", "CT scan", "Bone scan"],
    "A",
    "Daily fetal kick count: < 10 movements ใน 2 ชม. = ต้องประเมินเพิ่ม (NST)",
    "NST, BPP สำหรับการประเมินเพิ่มเติม",
    ["ใช่ — simplest", "ไม่ routine", "Radiation", "ไม่เกี่ยว"],
    "Daily kick count: < 10/2hr → call"),
  q(MAT,
    "NST (Non-stress test) ผลปกติ (reactive) คือ",
    ["≥ 2 accelerations 15 bpm above baseline, lasting ≥ 15 sec, ใน 20 นาที", "Baseline 80 bpm", "Late deceleration", "Variable deceleration"],
    "A",
    "Reactive NST = good fetal oxygenation; non-reactive → BPP",
    "Variable deceleration = cord compression; late = placental insufficiency",
    ["ใช่ — มาตรฐาน", "Bradycardia", "อันตราย — placental insufficiency", "Cord compression"],
    "NST reactive: ≥2 accels 15×15 ใน 20 นาที"),
  q(MAT,
    "การจัดการแม่ติดเชื้อ HIV ในระยะตั้งครรภ์เพื่อลด vertical transmission",
    ["ไม่ต้องให้ ART", "ART ตลอดตั้งครรภ์ + intrapartum AZT + neonatal prophylaxis + งดให้นมแม่ในไทย", "ทำคลอดท้องเสมอ", "ฉีดวัคซีนกันให้ทารก"],
    "B",
    "PMTCT: ART triple therapy + intrapartum AZT IV + neonatal NVP/AZT 4–6 wk + formula feeding (Thai guideline)",
    "C/S เฉพาะ VL > 1000 หรือไม่ทราบ VL",
    ["ลด transmission ไม่ได้", "ใช่ — Thai PMTCT", "ไม่ใช่ทุกราย", "ยังไม่มีวัคซีน HIV"],
    "PMTCT: ART + AZT + neonatal prophy + no breastfeed"),
  q(MAT,
    "ความถี่ของ ANC visit ตาม WHO 2016 (ขั้นต่ำ) คือ",
    ["1 ครั้ง", "8 contacts", "20 ครั้ง", "30 ครั้ง"],
    "B",
    "WHO 2016: 8 ANC contacts (เพิ่มจาก 4 visits เดิม) ลด perinatal mortality",
    "Thai practice ปรับใช้ตามบริบท",
    ["น้อยเกินไป", "ใช่ — WHO 2016", "เกิน", "เกิน"],
    "WHO: ≥ 8 ANC contacts"),
  q(MAT,
    "การให้ folic acid ก่อนตั้งครรภ์/ไตรมาสแรก ป้องกัน",
    ["Neural tube defects", "Cleft lip", "Down syndrome", "Hyperthyroidism"],
    "A",
    "Folic acid 400 mcg/day (สูงขึ้นใน high-risk) ก่อนตั้งครรภ์ 1–3 เดือนถึงสัปดาห์ที่ 12 ลด NTDs",
    "High-risk: 4 mg/day",
    ["ใช่ — มาตรฐาน", "ไม่เกี่ยว", "ไม่ได้ป้องกัน", "ไม่เกี่ยว"],
    "Folic acid: 400 mcg pre-conception → 12 wk"),
  q(MAT,
    "การให้ vitamin K ทารกแรกเกิด",
    ["1 mg IM ภายใน 1 ชั่วโมงแรก", "ทาน oral 100 mg", "ไม่จำเป็น", "ฉีด 10 mg IV"],
    "A",
    "Phytonadione 0.5–1 mg IM single dose ป้องกัน vitamin K deficiency bleeding (VKDB)",
    "ทารก preterm 0.5 mg",
    ["ใช่ — มาตรฐาน", "Oral form มี early-only protection", "เสี่ยง VKDB", "Overdose"],
    "Vitamin K newborn: 1 mg IM"),
  q(MAT,
    "Cervical dilation Stage I ของการคลอดสิ้นสุดเมื่อ",
    ["3 cm", "10 cm (fully dilated)", "Crowning", "Placenta คลอด"],
    "B",
    "Stage I: เริ่ม → cervix fully dilated 10 cm; Stage II = dilated → birth; Stage III = birth → placenta",
    "Active phase: 6–10 cm",
    ["Early labor", "ใช่ — definition", "Stage II", "Stage III"],
    "Stage I: → 10 cm"),
  q(MAT,
    "Fetal heart rate baseline ปกติคือ",
    ["80–100 bpm", "110–160 bpm", "180–200 bpm", "60–80 bpm"],
    "B",
    "FHR baseline 110–160 bpm; bradycardia < 110 > 10 นาที, tachycardia > 160",
    "Variability moderate (6–25 bpm) = healthy autonomic",
    ["Bradycardia", "ใช่ — มาตรฐาน", "Tachycardia", "Severe bradycardia"],
    "FHR baseline: 110–160 bpm"),
  q(MAT,
    "Apgar score component",
    ["Appearance, Pulse, Grimace, Activity, Respiration (each 0–2)", "Age, Pulse, Growth, BP, Reflex", "BP only", "Sex/weight"],
    "A",
    "5 components × 0–2 = total 0–10; ประเมิน 1 และ 5 นาที (+ 10 ถ้าต่ำ)",
    "Apgar ไม่ใช่ตัวบอก long-term outcome แต่ใช้ประเมิน immediate need",
    ["ใช่ — มาตรฐาน", "ไม่ใช่ Apgar", "ผิด", "ผิด"],
    "Apgar: A-P-G-A-R, 5 items 0–2"),

  // ============================================================
  // 5) NursingMidwifery — การผดุงครรภ์ (25)
  // ============================================================
  q(MID,
    "Leopold maneuver ขั้นที่ 1 ประเมิน",
    ["ส่วนของทารกที่ fundus", "Engagement", "Presenting part", "Position back"],
    "A",
    "Leopold 1: fundal grip ตรวจสิ่งที่อยู่ส่วนยอดมดลูก (head vs breech)",
    "L2: lateral grip → back; L3: pawlik → presenting part; L4: pelvic grip → engagement",
    ["ใช่ — fundal", "L4", "L3", "L2"],
    "Leopold 1: fundus"),
  q(MID,
    "Partograph alert line ใช้สำหรับ",
    ["บันทึก vital sign แม่", "เตือนเมื่อ labor progression ช้ากว่าที่ควร (cervix 1 cm/hr)", "วัดน้ำหนักทารก", "บันทึกประจำเดือน"],
    "B",
    "Alert line: cervical dilation < 1 cm/hr; action line ห่าง 4 ชม. → ต้อง intervene",
    "ช่วยตัดสินใจ active management of labor",
    ["ไม่ใช่ alert line", "ใช่ — มาตรฐาน WHO", "ไม่ใช่", "ไม่ใช่"],
    "Partograph alert line: 1 cm/hr threshold"),
  q(MID,
    "Stages of labor — Stage III ที่สำคัญ พยาบาลควร",
    ["Massage uterus + ดู placenta + signs of separation + active management (oxytocin)", "ปล่อยทิ้งไว้", "ดึง cord แรง ๆ", "ส่งกลับห้องคลอด"],
    "A",
    "Active management of 3rd stage: oxytocin 10 IU IM + controlled cord traction + uterine massage ลด PPH 60%",
    "Signs of separation: cord ยาวขึ้น, gush of blood, uterus กลม",
    ["ใช่ — AMTSL", "เพิ่ม retained placenta", "เสี่ยง inversion", "ไม่ใช่"],
    "AMTSL: oxytocin + CCT + massage"),
  q(MID,
    "Cardinal movements of labor ลำดับคือ",
    ["Engagement → descent → flexion → internal rotation → extension → external rotation → expulsion", "ผิดลำดับ", "Extension → flexion → expulsion", "External → internal"],
    "A",
    "ลำดับการเคลื่อนตัวของทารกผ่าน pelvis 7 ขั้นตอน",
    "ใช้ประเมิน normal progress",
    ["ใช่ — มาตรฐาน", "ผิด", "ผิดลำดับ", "ผิดลำดับ"],
    "Cardinal: E-D-F-IR-E-ER-Exp"),
  q(MID,
    "Episiotomy routine คำแนะนำปัจจุบันคือ",
    ["ทำทุกราย", "ทำเฉพาะ indication (fetal distress, shoulder dystocia, instrumental) — restrictive use", "ทำเฉพาะ primigravida", "งดทำตลอด"],
    "B",
    "WHO/ACOG: restrictive episiotomy ลด trauma รุนแรง vs routine",
    "Indication: severe perineal rigid, fetal distress, OVD",
    ["ตรงข้าม guideline", "ใช่ — restrictive", "ไม่ใช่ตาม indication", "ไม่ใช่นโยบาย"],
    "Episiotomy: restrictive, not routine"),
  q(MID,
    "Variable deceleration ของ FHR แสดงถึง",
    ["Head compression", "Cord compression", "Placental insufficiency", "Fetal hypoxia ลึก"],
    "B",
    "Variable decel: U/V/W shape, sudden drop = cord compression; treat: reposition mother, O₂, IV fluid",
    "Late decel = placental; Early = head",
    ["Early", "ใช่ — variable = cord", "Late", "Severe ของ late"],
    "VEAL CHOP: Variable=Cord"),
  q(MID,
    "Late deceleration ของ FHR ที่ recurrent แสดงถึง",
    ["Cord compression", "Uteroplacental insufficiency", "Maternal fever", "Normal pattern"],
    "B",
    "Late decel: gradual onset, nadir หลัง contraction peak; UPI → fetal hypoxia",
    "Action: reposition, O₂, fluid, หยุด oxytocin, แจ้งแพทย์",
    ["Variable", "ใช่ — UPI", "อาจ tachy แต่ไม่ late", "อันตราย"],
    "Late decel = UPI = bad"),
  q(MID,
    "Early deceleration หมายถึง",
    ["Cord compression", "Head compression — benign", "UPI", "Fetal hypoxia"],
    "B",
    "Early decel: mirror image ของ contraction; benign physiological",
    "ไม่ต้อง intervene",
    ["Variable", "ใช่ — head compression", "Late", "Late"],
    "Early decel = Head = benign"),
  q(MID,
    "Shoulder dystocia: maneuver ที่ทำก่อนเสมอ (1st-line)",
    ["McRoberts + suprapubic pressure", "Wood's screw", "Zavanelli", "Symphysiotomy"],
    "A",
    "HELPERR mnemonic: McRoberts + suprapubic pressure first; ถ้า fail → internal maneuvers",
    "Zavanelli = last resort (replace head + C/S)",
    ["ใช่ — first-line", "Second-line", "Last resort", "Rare"],
    "Shoulder dystocia: McRoberts first"),
  q(MID,
    "การประเมิน lochia: lochia ที่ผิดปกติคือ",
    ["Foul-smelling, large clot, soaking pad ใน 1 ชม.", "Pinkish day 5", "White day 14", "Rubra day 1"],
    "A",
    "Endometritis: foul smell + fever; PPH: pad soak ใน 1 ชม.",
    "Normal: rubra (1–3) → serosa (4–10) → alba (11–14+)",
    ["ใช่ — abnormal", "Normal serosa", "Normal alba", "Normal rubra"],
    "Abnormal lochia: foul smell / clot / soak"),
  q(MID,
    "Umbilical cord clamping ใน term newborn ที่แข็งแรง: WHO แนะนำ",
    ["Immediate clamp", "Delayed clamping 1–3 นาที (หลังคลอดและสาย pulsation หยุด)", "Wait > 30 นาที", "Cut ทันทีและล้าง"],
    "B",
    "Delayed cord clamping ≥ 1 นาที เพิ่ม iron stores ทารกใน 6 เดือนแรก",
    "Immediate clamp ใช้ใน emergency neonatal resuscitation, severe abruption",
    ["ลด iron stores", "ใช่ — WHO/ACOG", "ไม่จำเป็น", "ผิด"],
    "Delayed cord clamping: ≥ 60 sec"),
  q(MID,
    "การประเมิน Bishop score ใช้สำหรับ",
    ["พิจารณาภาวะพร้อมของ cervix ก่อน induction of labor", "วัด fetal weight", "ประเมิน Apgar", "วัด BP"],
    "A",
    "Bishop score (0–13): cervix dilation, effacement, station, consistency, position; ≥ 8 = favorable",
    "< 6 → cervical ripening agents ก่อน",
    ["ใช่ — มาตรฐาน", "ไม่ใช่", "Newborn", "ไม่เกี่ยว"],
    "Bishop ≥ 8 = induction favorable"),
  q(MID,
    "Ergometrine มี contraindication ใน",
    ["Hypertension / preeclampsia", "Hypotension", "Anemia", "Diabetes"],
    "A",
    "Ergometrine ทำให้ vasoconstriction → BP สูงขึ้น; ห้ามใน HT/PE",
    "ใช้ oxytocin หรือ misoprostol แทน",
    ["ใช่ — มาตรฐาน", "ใช้ได้ระวัง", "ไม่ใช่ CI", "ไม่ใช่ CI"],
    "Ergot ห้ามใน HT/PE"),
  q(MID,
    "Misoprostol สำหรับ PPH ขนาดที่ใช้",
    ["100 mcg IV", "800–1000 mcg PR (rectal) หรือ 600 mcg sublingual", "10 mcg PO", "50 mg IM"],
    "B",
    "Miso 800–1000 mcg PR / 600 mcg SL — heat-stable ทางเลือกในพื้นที่ขาด cold chain",
    "ผลข้างเคียง: fever, shivering",
    ["ไม่มี IV form", "ใช่ — มาตรฐาน WHO", "Underdose", "Overdose"],
    "Miso PPH: 800–1000 mcg PR"),
  q(MID,
    "Active phase ของ labor stage I คือ",
    ["0–6 cm", "6–10 cm", "10+ cm", "หลังคลอด"],
    "B",
    "ใหม่ ACOG: latent < 6 cm, active 6–10 cm; ลด primary C/S rate",
    "ก่อนหน้านี้ใช้ 4 cm",
    ["Latent", "ใช่ — active phase", "Stage II", "Stage III"],
    "Active phase: 6 cm onward"),
  q(MID,
    "Cord prolapse: ขั้นแรกที่ต้องทำ",
    ["รอผ่า", "Knee-chest position แม่ + push presenting part ขึ้น + เรียก emergency C/S", "บีบ cord", "ใส่ cord กลับ"],
    "B",
    "Obstetric emergency: ลด cord compression โดย position + manual elevation จนทำคลอดได้",
    "ห้ามดัน cord กลับ — ทำให้ vasospasm",
    ["รอ = fetal death", "ใช่ — มาตรฐาน", "Vasospasm", "ห้าม"],
    "Cord prolapse: position + lift + emergency C/S"),
  q(MID,
    "การวัด cervical dilation อย่างปลอดภัยทำเมื่อ",
    ["ตรวจ PV ทุกชั่วโมง", "ตรวจตาม indication (e.g., labor onset, status change) ไม่ตรวจถี่เกินจำเป็น", "ตรวจ 30 นาทีครั้ง", "ตรวจหลัง bath"],
    "B",
    "Frequent PV exams เพิ่มเสี่ยง chorioamnionitis; ทำเมื่อมี clinical reason",
    "Aseptic technique ทุกครั้ง",
    ["Over-exam", "ใช่ — มาตรฐาน", "Over-exam", "ไม่จำเป็น"],
    "PV exams: minimize, aseptic"),
  q(MID,
    "Prolonged latent phase definition (nullipara) คือ",
    ["> 8 ชม", "> 20 ชม", "> 12 ชม", "ไม่กำหนด"],
    "B",
    "Friedman: latent > 20 hr (nulli) / > 14 hr (multi) = prolonged",
    "ไม่บ่งใช้ augmentation ทันที — ต้องประเมิน individualized",
    ["ไม่ใช่", "ใช่ — มาตรฐาน", "Multipara", "ไม่ใช่"],
    "Prolonged latent: > 20h (nulli), > 14h (multi)"),
  q(MID,
    "Postpartum hemorrhage 4T causes",
    ["Tone, Trauma, Tissue, Thrombin", "Time, Talk, Test, Treat", "Tear, Trim, Trick, Toss", "ไม่มี"],
    "A",
    "4T: Tone (atony 70%), Trauma (laceration), Tissue (retained), Thrombin (coagulopathy)",
    "Atony เป็นสาเหตุ #1",
    ["ใช่ — มาตรฐาน", "ไม่ใช่", "ไม่ใช่", "ผิด"],
    "PPH causes: 4T's"),
  q(MID,
    "Engagement หมายถึง",
    ["Cervix dilate 10 cm", "Biparietal diameter ผ่าน pelvic inlet (station 0)", "Placenta คลอด", "เริ่มเจ็บครรภ์"],
    "B",
    "Engagement = head reaches station 0 (level of ischial spines)",
    "Usually ก่อน labor ใน nullipara; ระหว่าง labor ใน multipara",
    ["Stage I end", "ใช่ — station 0", "Stage III", "False labor"],
    "Engagement: BPD ผ่าน inlet = station 0"),
  q(MID,
    "FHR baseline tachycardia (> 160) สาเหตุที่พบบ่อย",
    ["Maternal fever / infection / hypoxia ระยะแรก", "Hypothermia", "Normal", "Oxytocin"],
    "A",
    "Fetal tachycardia: maternal fever, chorioamnionitis, dehydration, fetal anemia, hypoxia",
    "ต้องประเมิน cause + intrauterine resuscitation",
    ["ใช่ — common", "ไม่ใช่", "อันตราย", "อาจเพิ่ม contraction ไม่ใช่ HR direct"],
    "FHR tachy → fever/infection/hypoxia"),
  q(MID,
    "การให้ oxytocin augmentation ที่ปลอดภัยคือ",
    ["Start 1–6 mU/min titrate ทุก 30–40 นาที พร้อม CTG monitor", "Bolus 10 IU IV", "Start 50 mU ทันที", "ไม่ต้อง monitor"],
    "A",
    "Low-dose protocol: 1–2 mU/min เพิ่ม q30 นาที จน adequate contraction (3–5/10min)",
    "Risk: hyperstimulation, fetal distress, uterine rupture",
    ["ใช่ — มาตรฐาน", "อันตราย — bolus = hypotension", "Hyperstim", "Negligence"],
    "Augmentation: low-dose + CTG"),
  q(MID,
    "Retained placenta definition คือ",
    ["Placenta ไม่ออกภายใน 30 นาทีหลังคลอด (active management)", "1 นาที", "5 ชม", "1 วัน"],
    "A",
    "Retained: > 30 นาที AMTSL หรือ > 60 นาที expectant",
    "Management: manual removal under anesthesia + uterotonic",
    ["ใช่ — มาตรฐาน", "เร็วเกินไป", "Sepsis แล้ว", "ห้ามรอ"],
    "Retained placenta: > 30 min"),
  q(MID,
    "Breech presentation: ECV (external cephalic version) ทำที่ GA",
    ["20 wk", "36–37 wk", "30 wk", "หลังคลอด"],
    "B",
    "ECV ที่ 36–37 wk เพื่อ rotate breech → vertex; success rate 50–70%",
    "Need tocolytic, US, CTG ก่อน-หลัง",
    ["เร็วเกินไป", "ใช่ — มาตรฐาน", "เร็วไป", "ผิด"],
    "ECV: 36–37 wk"),
  q(MID,
    "Postpartum mother day 3 มี fundus ที่ระดับสูงกว่าที่คาด + tender + foul lochia + fever 38.5°C อาการสงสัย",
    ["Endometritis", "Normal involution", "PPH", "Mastitis"],
    "A",
    "Endometritis postpartum: fever + uterine tenderness + foul lochia + subinvolution",
    "Treatment: IV ampicillin + gentamicin + clindamycin",
    ["ใช่ — endometritis", "Subinvolution = abnormal", "PPH = heavy bleed", "Breast not uterus"],
    "Endometritis: fever + tender + foul lochia"),

  // ============================================================
  // 6) NursingPsych — การพยาบาลสุขภาพจิตและจิตเวชศาสตร์ (25)
  // ============================================================
  q(PSY,
    "ผู้ป่วยเข้ารับการรักษาที่หอผู้ป่วยจิตเวช มีอาการ paranoid delusion คิดว่ามีคนตามฆ่า การสื่อสารที่เหมาะสมคือ",
    ["ยืนยันว่าความคิดของผู้ป่วยถูกต้อง", "ไม่ขัด ไม่เห็นด้วย ฟังอย่างเข้าใจ ('I understand that feels real to you, but I don't see anyone…')", "หัวเราะเยาะ", "บอกว่าเขาคิดมาก"],
    "B",
    "Therapeutic communication: neither agree (reinforce delusion) nor confront (defensive) — acknowledge feeling, reality test gently",
    "สร้าง trust ก่อน → ภายหลังอาจ challenge delusion เมื่อ rapport ดี",
    ["Reinforce delusion", "ใช่ — therapeutic", "Damage rapport", "Dismissive"],
    "Delusion: don't agree, don't argue — validate feeling"),
  q(PSY,
    "ผู้ป่วยใช้ Lithium carbonate ค่า lithium 1.8 mEq/L มีอาการ tremor, vomiting, ataxia ต้อง",
    ["ปกติ ไม่ต้องทำอะไร", "หยุดยาทันทีและรายงานแพทย์ — toxicity (therapeutic 0.6–1.2)", "เพิ่มขนาดเป็น 2 เท่า", "ให้น้ำตาล"],
    "B",
    "Lithium toxicity: > 1.5 mEq/L; severe > 2.0 → seizure, coma",
    "Treatment: hold + hydration + dialysis ถ้า > 4.0 หรือ severe symptom",
    ["อันตราย", "ใช่ — toxicity", "Lethal", "ไม่เกี่ยว"],
    "Lithium therapy: 0.6–1.2, toxic > 1.5"),
  q(PSY,
    "Neuroleptic Malignant Syndrome (NMS) อาการคือ",
    ["Hyperpyrexia + rigidity + autonomic instability + altered mental status + ↑CK", "Hypotension เพียงอย่างเดียว", "Rash", "Cataract"],
    "A",
    "NMS: hyperthermia (> 40°C), rigidity, autonomic instability, AMS, ↑CK, leukocytosis",
    "Treatment: หยุด antipsychotic + cooling + dantrolene/bromocriptine + supportive",
    ["ใช่ — มาตรฐาน", "ไม่พอ", "ไม่ใช่ NMS", "ไม่ใช่ NMS"],
    "NMS: 4H — Hyperpyrexia, rigidity (Hyper-tonia), AMS, autonomic"),
  q(PSY,
    "Suicide risk assessment ที่สำคัญที่สุดคือ",
    ["ถามตรงเรื่องความคิดทำร้ายตัวเอง / แผน / วิธี / เครื่องมือ", "หลีกเลี่ยงคำถามเพราะกลัวสาเหตุ", "ถามครอบครัวเท่านั้น", "ถามแพทย์เท่านั้น"],
    "A",
    "Asking about suicide ไม่เพิ่ม risk; ตรงประเด็น: ideation, plan, means, intent, lethality",
    "ระดับความเสี่ยงสูง = plan + means + intent",
    ["ใช่ — มาตรฐาน", "Myth — ถามไม่เพิ่มความเสี่ยง", "ไม่พอ", "พยาบาลก็มีหน้าที่"],
    "Suicide: ถามตรง ไม่อ้อม"),
  q(PSY,
    "Schizophrenia positive symptoms ได้แก่",
    ["Apathy, anhedonia, alogia", "Hallucination, delusion, disorganized speech/behavior", "Memory loss", "Tremor"],
    "B",
    "Positive: hallucinations, delusions, disorganized; negative: 5A (affect flat, alogia, anhedonia, avolition, asociality)",
    "First-line: 2nd-gen antipsychotic (risperidone, olanzapine)",
    ["Negative symptoms", "ใช่ — positive", "ไม่ใช่", "ไม่ใช่"],
    "Pos = add (hallu/delu); Neg = subtract"),
  q(PSY,
    "Therapeutic milieu คือ",
    ["Recreational area เท่านั้น", "การจัดสิ่งแวดล้อมที่ปลอดภัย มีโครงสร้าง ส่งเสริม recovery และ socialization", "ห้องแยกเดี่ยว", "ใช้ restraints ตลอดเวลา"],
    "B",
    "Milieu therapy: safe physical + psychological environment + structured activities + peer interaction",
    "ลด ใช้ restraint/seclusion",
    ["ไม่ใช่", "ใช่ — มาตรฐาน", "ตรงข้าม", "ขัดหลัก"],
    "Milieu: safe + structured + therapeutic"),
  q(PSY,
    "ผู้ป่วย bipolar I disorder manic episode การจัดการ first-line คือ",
    ["Lithium / valproate / 2nd-gen antipsychotic + ลด stimulation", "ปล่อยให้ตื่นตัวเต็มที่", "Benzodiazepine alone", "ECT first-line"],
    "A",
    "Acute mania: mood stabilizer (Li/VPA) ± antipsychotic (risperidone, olanzapine, quetiapine); reduce environmental stimulation",
    "ECT reserve สำหรับ severe / treatment-resistant / pregnancy",
    ["ใช่ — มาตรฐาน", "ทำให้อาการแย่", "Adjunct ไม่ใช่หลัก", "Reserved"],
    "Acute mania: Li/VPA + antipsychotic + low-stim"),
  q(PSY,
    "Major depressive disorder first-line pharmacotherapy คือ",
    ["MAOI", "SSRI (sertraline, fluoxetine, escitalopram)", "Lithium", "Stimulant"],
    "B",
    "SSRI = first-line MDD; ดู effect 4–6 wk",
    "Stop suicidal monitoring ในช่วง 1–2 wk แรกเพราะ energy เพิ่มก่อน mood ดี",
    ["Reserved — drug interactions", "ใช่ — มาตรฐาน", "Augment", "ใช้ใน ADHD"],
    "MDD: SSRI first-line, monitor 1–2 wk"),
  q(PSY,
    "Serotonin syndrome triad คือ",
    ["Mental status change + autonomic hyperactivity + neuromuscular abnormality", "Bradycardia", "Hypothermia", "Constipation"],
    "A",
    "SS: agitation, hyperthermia, hyperreflexia, clonus, diaphoresis; เกิดจาก SSRI + MAOI/tramadol/linezolid",
    "Treatment: หยุดยา + cooling + cyproheptadine",
    ["ใช่ — มาตรฐาน triad", "ตรงข้าม", "ตรงข้าม", "ไม่ใช่"],
    "SS: AMS + autonomic + neuromuscular"),
  q(PSY,
    "ผู้ป่วย alcohol withdrawal เริ่ม 12 ชม.หลังหยุดดื่ม first-line treatment คือ",
    ["Naltrexone", "Benzodiazepine (lorazepam/diazepam) ตาม CIWA-Ar", "Disulfiram", "Acamprosate"],
    "B",
    "BZD ลด seizure, delirium tremens; lorazepam ดีในโรคตับ",
    "Naltrexone/acamprosate/disulfiram ใช้ relapse prevention หลัง detox",
    ["Maintenance", "ใช่ — first-line", "Aversive maintenance", "Maintenance"],
    "Alcohol withdrawal: BZD by CIWA"),
  q(PSY,
    "Delirium tremens เกิดเมื่อ",
    ["6 ชม. หลังหยุดดื่ม", "48–96 ชม. หลังหยุดดื่ม — autonomic instability + hallucination + seizure", "1 wk", "1 เดือน"],
    "B",
    "DTs: peak 48–96 ชม.; mortality 5–15% if untreated",
    "Manage in monitored setting + IV BZD + thiamine",
    ["Tremor/anxiety phase", "ใช่ — DTs window", "Late", "ผิด"],
    "DTs: 48–96 hr, urgent"),
  q(PSY,
    "Wernicke encephalopathy triad",
    ["Confusion + ophthalmoplegia + ataxia", "Headache + fever", "Hallucination + delusion", "Tremor + rigidity"],
    "A",
    "Thiamine deficiency: COA triad — ต้องให้ thiamine IV ก่อน glucose ใน alcoholic",
    "Korsakoff = memory + confabulation ถาวร",
    ["ใช่ — มาตรฐาน", "ไม่ใช่", "ไม่ใช่", "ไม่ใช่"],
    "WE: Confusion + Ocular + Ataxia → thiamine"),
  q(PSY,
    "Anorexia nervosa diagnostic feature สำคัญที่สุด",
    ["Severe weight loss + intense fear of weight gain + distorted body image", "ทานเก่ง", "นอนมาก", "ขาดประจำเดือน — required"],
    "A",
    "DSM-5: restriction → low body weight + fear + body image distortion (amenorrhea ถูกตัดออก)",
    "Refeeding syndrome: ระวัง P/K/Mg ลด",
    ["ใช่ — DSM-5", "ตรงข้าม", "ไม่ใช่ core", "DSM-5 ตัดออก"],
    "AN: weight loss + fear + body image"),
  q(PSY,
    "Bulimia nervosa การจัดการ first-line คือ",
    ["CBT + SSRI (fluoxetine)", "Antipsychotic", "Lithium", "ECT"],
    "A",
    "BN: CBT-ED + fluoxetine 60 mg/d (only SSRI FDA-approved)",
    "Bupropion ห้าม — เพิ่ม seizure risk ใน eating disorder",
    ["ใช่ — มาตรฐาน", "ไม่ใช่ first-line", "ไม่ใช่", "Reserved"],
    "BN: CBT + fluoxetine 60 mg"),
  q(PSY,
    "PTSD first-line therapy คือ",
    ["Trauma-focused CBT, EMDR + SSRI", "Antipsychotic", "Lithium", "MAOI"],
    "A",
    "First-line: TF-CBT + EMDR; pharm: SSRI (sertraline, paroxetine)",
    "BZD ห้าม long-term — เพิ่ม dependence + worsen PTSD",
    ["ใช่ — มาตรฐาน", "ไม่ใช่", "ไม่ใช่", "Reserved"],
    "PTSD: TF-CBT/EMDR + SSRI"),
  q(PSY,
    "OCD first-line pharmacotherapy",
    ["High-dose SSRI ± ERP", "Antipsychotic alone", "Stimulant", "MAOI"],
    "A",
    "OCD: SSRI ขนาดสูงกว่า MDD (e.g., fluoxetine 60–80 mg) + ERP (exposure-response prevention)",
    "Response อาจช้า 8–12 wk",
    ["ใช่ — มาตรฐาน", "Adjunct", "ไม่ใช่", "Reserved"],
    "OCD: high-dose SSRI + ERP"),
  q(PSY,
    "ECT (Electroconvulsive Therapy) indication หลัก",
    ["Severe MDD with suicidal ideation, treatment-resistant, catatonia, pregnancy", "Mild anxiety", "Insomnia", "ADHD"],
    "A",
    "ECT effective ใน severe MDD, mania, catatonia, schizophrenia บางราย; ปลอดภัยใน pregnancy",
    "ผลข้างเคียง: short-term memory loss",
    ["ใช่ — มาตรฐาน", "Over-treatment", "ไม่ใช่", "ไม่ใช่"],
    "ECT: severe MDD/cata/preg/treatment-resistant"),
  q(PSY,
    "Restraint และ seclusion ใน psych ward ต้อง",
    ["ใช้ first-line", "เป็น last resort, ต้อง MD order, monitor q15min, time-limited, review บ่อย", "ใช้ตลอดทั้ง shift", "ไม่ต้อง document"],
    "B",
    "Joint Commission: least restrictive, MD order ≤ 4 hr adult, ≤ 2 hr child, q15 monitoring",
    "Document indication, alternative tried, behavior, vitals, debrief",
    ["ผิด", "ใช่ — มาตรฐาน", "ผิด ต้องประเมินบ่อย", "ผิดกฎหมาย"],
    "Restraint: last resort + ordered + monitored"),
  q(PSY,
    "ผู้ป่วย schizophrenia ใช้ clozapine ต้องตรวจอะไรประจำ",
    ["Lipid", "CBC (ANC) เพื่อตรวจ agranulocytosis", "Vitamin C", "TSH"],
    "B",
    "Clozapine → agranulocytosis 1%; ตรวจ ANC weekly × 6 mo, then biweekly, then monthly",
    "หยุดยาทันทีถ้า ANC < 1500",
    ["ปกติทำเป็น routine", "ใช่ — มาตรฐาน", "ไม่ใช่ priority", "ไม่ใช่ priority"],
    "Clozapine: ANC monitoring"),
  q(PSY,
    "Therapeutic communication: 'reflection' หมายถึง",
    ["ทวนความรู้สึก/เนื้อหาที่ผู้ป่วยพูด สะท้อนกลับเพื่อสร้าง understanding", "บอกความเห็นตัวเอง", "เปลี่ยนเรื่อง", "ตัดสิน"],
    "A",
    "Reflection: 'You sound frustrated about…' ช่วยผู้ป่วยรู้สึกถูกเข้าใจ",
    "Avoid: false reassurance, why-questions, advice-giving",
    ["ใช่ — มาตรฐาน", "Non-therapeutic", "Avoidance", "Judgmental"],
    "Reflection: mirror feeling/content"),
  q(PSY,
    "Substance Use Disorder: opioid overdose antidote คือ",
    ["Flumazenil", "Naloxone IM/IN/IV", "Atropine", "Pralidoxime"],
    "B",
    "Naloxone reverses opioid overdose; repeat ตาม half-life",
    "Flumazenil = BZD; atropine/pralidoxime = OP poisoning",
    ["BZD reversal", "ใช่ — opioid antidote", "Anticholinergic", "OP/CARBAMATE"],
    "Opioid OD: Naloxone"),
  q(PSY,
    "Pediatric autism spectrum disorder การจัดการแบบ first-line คือ",
    ["Behavioral therapy (ABA) + early intervention + supportive education", "Antipsychotic เสมอ", "ECT", "Restraint"],
    "A",
    "ASD: early behavioral intervention; antipsychotic (risperidone, aripiprazole) ใช้กับ irritability/aggression",
    "ไม่มี curative pharmacotherapy",
    ["ใช่ — มาตรฐาน", "Adjunct", "ไม่ใช่", "ผิด"],
    "ASD: ABA + early intervention"),
  q(PSY,
    "ผู้ป่วยพยายามฆ่าตัวตายโดยกินยา ทันทีที่มาถึง การประเมิน safety ที่สำคัญที่สุด",
    ["ประเมิน airway/breathing/circulation + ระดับ consciousness + access to means", "ถามอย่างเดียวว่า 'ทำไมทำแบบนี้'", "ปล่อยกลับบ้าน", "ใส่กุญแจมือ"],
    "A",
    "ABC + medical stabilization ก่อน; ภายหลัง psychiatric evaluation, safety plan, hospitalization",
    "นำของอันตรายออก, 1:1 observation",
    ["ใช่ — มาตรฐาน", "ไม่ใช่ priority", "อันตราย", "ไม่ใช่ first action"],
    "Suicide attempt: ABC + remove means + 1:1"),
  q(PSY,
    "Anxiety disorder GAD first-line",
    ["SSRI/SNRI + CBT", "BZD long-term", "Lithium", "MAOI"],
    "A",
    "GAD: CBT + SSRI/SNRI (sertraline, escitalopram, venlafaxine)",
    "BZD ใช้ short-term ระหว่างรอ SSRI ออกฤทธิ์",
    ["ใช่ — มาตรฐาน", "Dependence risk", "ไม่ใช่", "Reserved"],
    "GAD: SSRI/SNRI + CBT"),
  q(PSY,
    "Tardive dyskinesia สัมพันธ์กับยาใด",
    ["1st-gen antipsychotic (haloperidol, chlorpromazine)", "SSRI", "Lithium", "BZD"],
    "A",
    "TD: involuntary movements (face, tongue) จาก long-term D2 blockade; อาจไม่กลับเป็นปกติ",
    "Treatment: VMAT2 inhibitor (valbenazine, deutetrabenazine)",
    ["ใช่ — typical antipsychotic", "ไม่เกี่ยว", "Tremor ต่างหาก", "Sedation"],
    "TD: typical antipsychotics — irreversible"),

  // ============================================================
  // 7) NursingCommunity — การพยาบาลอนามัยชุมชนและการรักษาพยาบาลขั้นต้น (25)
  // ============================================================
  q(COM,
    "การให้ DOTS (Directly Observed Treatment Short-course) ใน TB คือ",
    ["ผู้ป่วยกินยาเองที่บ้าน", "เจ้าหน้าที่/ผู้ดูแลเฝ้าดูการกินยาทุกครั้ง อย่างน้อยใน 2 เดือนแรก", "ฉีดยาทุกวัน", "ตรวจ X-ray ทุกสัปดาห์"],
    "B",
    "DOTS: observed swallowing ทุก dose ระยะ intensive 2 เดือน, ลด non-adherence + MDR-TB",
    "Continuation phase 4 เดือน HR/HE ตาม regimen",
    ["ไม่ใช่ DOTS", "ใช่ — มาตรฐาน WHO", "ไม่ใช่ TB tx", "ติดตามแต่ไม่ใช่ DOTS"],
    "DOTS: observed dosing reduces MDR-TB"),
  q(COM,
    "การสำรวจ Aedes mosquito control ใน community: BI (Breteau Index) ต่ำกว่าเท่าไรถือว่าควบคุมได้",
    ["< 50", "< 5", "ไม่กำหนด", "> 50"],
    "B",
    "BI = จำนวนภาชนะที่มีลูกน้ำ / 100 หลังคาเรือน; เป้า < 5 (ลดการระบาด dengue)",
    "HI < 10%, CI < 5%",
    ["สูงเกิน", "ใช่ — เป้า WHO/MOPH", "ต้องมีเป้า", "ระบาดสูง"],
    "Dengue control: BI < 5"),
  q(COM,
    "วัคซีน EPI Thailand: ทารกที่ HBsAg+ mother ต้องได้อะไรเพิ่มเติม",
    ["HBV vaccine + HBIG ภายใน 12 ชม.หลังคลอด", "งดวัคซีน", "BCG เพิ่ม", "MMR เพิ่ม"],
    "A",
    "PMTCT HBV: HBV birth dose + HBIG 0.5 mL IM ที่ขาคนละข้าง ภายใน 12 ชม.",
    "ตรวจ HBsAg/anti-HBs ที่ 9–12 เดือน",
    ["ใช่ — มาตรฐาน", "เพิ่ม transmission", "ไม่จำเป็นเพิ่ม", "ไม่ใช่ HBV ProtocolE"],
    "HBsAg+ mother: HBV + HBIG ภายใน 12 hr"),
  q(COM,
    "Home visit ใน CKD stage 4 ที่ชุมชน priorities ที่ประเมินคือ",
    ["BP, diet (Na/K/P), medication adherence, edema, urine, weight", "การรับโทรศัพท์", "เพศ ๆ บ้าน", "ราคาบ้าน"],
    "A",
    "Community CKD care: monitor BP, dietary compliance, fluid status, med adherence, mental health",
    "Care plan + referral เมื่อ deterioration",
    ["ใช่ — relevant", "ไม่เกี่ยว", "ไม่เกี่ยว", "ไม่เกี่ยว"],
    "Home CKD: BP + diet + meds + edema"),
  q(COM,
    "การให้คำปรึกษา family planning ที่ effective สำหรับคู่สมรสอายุ 30 ปี ที่มีลูก 2 คน วิธีคุมกำเนิดที่ reversible และเหมาะสำหรับ DM ที่ควบคุมดีคือ",
    ["COC (estrogen-progestin pill)", "Copper IUD หรือ progestin-only methods", "ฉีด yearly", "ไม่มี option"],
    "B",
    "DM: COC สัมพันธ์กับ ↑VTE/CV risk; LARC (Cu-IUD, LNG-IUS) หรือ POP/DMPA ปลอดภัยกว่า",
    "Cu-IUD ไม่มี hormone — เหมาะกับ DM/HT",
    ["Higher CV risk", "ใช่ — มาตรฐาน WHO MEC", "ไม่มีจริง", "มี option"],
    "DM contraception: prefer LARC / progestin-only"),
  q(COM,
    "การควบคุม emerging disease outbreak ขั้นแรกของพยาบาลในชุมชนคือ",
    ["รีบให้ยาทุกราย", "Surveillance + case identification + isolation + report ผู้บังคับบัญชา/กรมควบคุมโรค", "ปกปิดข้อมูล", "ไม่ทำอะไร"],
    "B",
    "Outbreak: detect → confirm → control → communicate; รายงาน 506 + 506/1 ตามระเบียบ",
    "Communication เป็นส่วนสำคัญลด panic",
    ["ไม่มียา empirical สำหรับ unknown", "ใช่ — มาตรฐาน", "ผิดกฎหมาย", "Negligence"],
    "Outbreak: detect → confirm → control → communicate"),
  q(COM,
    "การตรวจคัดกรองมะเร็งปากมดลูกในผู้หญิงไทย แนวทาง NCI 2563 คือ",
    ["Pap smear ทุก 6 เดือน", "HPV test หรือ Pap smear ทุก 3–5 ปีในผู้หญิง 30–60 ปี", "เริ่มที่ 12 ปี", "ไม่จำเป็น"],
    "B",
    "ปัจจุบันใช้ HPV testing primary screening; Pap ก็ยังใช้ได้, ทุก 3–5 ปีตามวิธี",
    "Vaccinated ก็ยังต้อง screen",
    ["บ่อยเกิน", "ใช่ — มาตรฐาน", "เร็วเกิน", "ผิด"],
    "CxCa screen: HPV/Pap ทุก 3–5 ปี"),
  q(COM,
    "การควบคุม HT ในชุมชน DASH diet เน้น",
    ["ผัก ผลไม้ ธัญพืช เนื้อไม่ติดมัน ลด Na < 2.3 g/วัน", "เกลือมาก", "อาหารแปรรูป", "เครื่องดื่มแอลกอฮอล์"],
    "A",
    "DASH: fruits, vegetables, low-fat dairy, whole grains, lean protein; Na 1.5–2.3 g/d ลด BP 5–11/3–5 mmHg",
    "Physical activity 150 min/wk; lose weight ถ้า BMI สูง",
    ["ใช่ — มาตรฐาน", "ตรงข้าม", "เพิ่ม Na", "เพิ่ม BP"],
    "DASH: low Na + ผัก/ผลไม้/whole grain"),
  q(COM,
    "Primary prevention ของ stroke ในชุมชน ได้แก่",
    ["BP control, DM control, lipid, smoking cessation, activity", "การฟื้นฟูหลัง stroke", "การให้ rtPA", "การให้ Plt fresh"],
    "A",
    "Primary = ก่อนเกิดโรค; Secondary = หลังเกิดป้องกันซ้ำ; Tertiary = ฟื้นฟู",
    "Risk factor control = primary",
    ["ใช่ — primary", "Tertiary", "Acute treatment", "ไม่ใช่ prevention"],
    "Primary prev: control risk factors"),
  q(COM,
    "Maternal & Child Health (MCH) bag เครื่องมือพื้นฐานในการเยี่ยมบ้านเด็กแรกเกิด",
    ["BP cuff + ห่วงคุมกำเนิด", "เทอร์โมมิเตอร์ + สายวัด + เครื่องชั่ง + form ANC/EPI + soap", "เครื่องวัดน้ำตาล + อินซูลิน", "X-ray portable"],
    "B",
    "MCH home visit kit: vitals tools + measuring + records",
    "เน้น well-baby check + breastfeeding + immunization",
    ["ไม่ relevant", "ใช่ — มาตรฐาน MCH", "ไม่ใช่ neonate priority", "ไม่ใช่"],
    "MCH kit: vitals + record + measurement"),
  q(COM,
    "School health: BMI cutoff สำหรับ 'overweight' ของเด็กไทย ใช้ percentile ใด",
    ["BMI-for-age > 85th percentile", "> 50th", "< 5th", "ไม่เกี่ยว"],
    "A",
    "WHO: > 85th = overweight, > 95th = obese, < 5th = underweight",
    "ใช้ growth chart by age & sex",
    ["ใช่ — มาตรฐาน WHO", "Median", "Underweight", "มี cutoff"],
    "Peds BMI: > 85th OW / > 95th OB"),
  q(COM,
    "Occupational health ผู้ใช้ยาฆ่าแมลง organophosphate ตรวจ marker คือ",
    ["Plasma/RBC cholinesterase activity", "Glucose", "HbA1c", "Lead level"],
    "A",
    "OP poisoning: ↓cholinesterase; symptom: SLUDGE/DUMBELS",
    "Antidote: atropine + pralidoxime",
    ["ใช่ — มาตรฐาน", "ไม่เกี่ยว", "ไม่เกี่ยว", "Heavy metal"],
    "OP: ↓cholinesterase; antidote atropine + 2-PAM"),
  q(COM,
    "การเฝ้าระวังโรคไข้เลือดออกในชุมชน วิธี Larva Survey เน้น",
    ["สำรวจในแหล่งน้ำขังในบ้านและรอบบ้าน", "เจาะเลือดทุกคน", "ปูพรมพ่นยา", "ไม่ทำอะไร"],
    "A",
    "Container survey + larva index ในและรอบบ้าน 100 หลัง",
    "5 ป. ปิด/เปลี่ยน/ปล่อย/ปรับ/ปฏิบัติ",
    ["ใช่ — มาตรฐาน", "Cost", "Reactive ไม่ใช่ preventive", "ผิด"],
    "Dengue control: container survey + 5 ป."),
  q(COM,
    "การให้สุขศึกษาในชุมชนที่ effective ที่สุดควรใช้",
    ["บรรยายฝ่ายเดียวยาว 2 ชม", "Two-way communication + participatory + ใช้สื่อหลายแบบ + วัดผล", "แจกแผ่นพับเท่านั้น", "ไม่ต้องประเมิน"],
    "B",
    "Health education effective: assess needs, set objective, two-way, multi-modal, evaluate",
    "ใช้ทฤษฎี HBM/TTM",
    ["Low retention", "ใช่ — มาตรฐาน", "ไม่พอ", "ขาดการประเมิน"],
    "Health ed: needs → multi-modal → evaluate"),
  q(COM,
    "Universal Health Coverage (UHC) ในไทยครอบคลุมโดย",
    ["UC (บัตรทอง/30 บาท), ประกันสังคม, ข้าราชการ + อื่น ๆ", "เฉพาะ private insurance", "เฉพาะข้าราชการ", "ไม่มี"],
    "A",
    "Thai UHC: 3 main schemes (UC, SSO, CSMBS); coverage > 99%",
    "ผ่าน พ.ร.บ.หลักประกันสุขภาพแห่งชาติ 2545",
    ["ใช่ — มาตรฐาน", "ผิด", "เพียงส่วนหนึ่ง", "ผิด"],
    "Thai UHC: UC + SSO + CSMBS"),
  q(COM,
    "การประเมินชุมชน (Community assessment) ใช้แนวคิดใดเป็นหลัก",
    ["Windshield survey + Key informant interview + Statistics + Community walk + Health profile", "เฉพาะแบบสอบถาม", "ดู Facebook", "Internet search"],
    "A",
    "Community assessment ใช้หลาย sources: ข้อมูล demographic, environment, services, perception",
    "Triangulation เพิ่ม validity",
    ["ใช่ — มาตรฐาน", "ขาด triangulation", "ไม่ valid", "ไม่ valid"],
    "Community assessment: triangulate sources"),
  q(COM,
    "การให้บริการ NCD clinic ในคลินิกชุมชน 'ปิงปอง 7 สี' คือ",
    ["การคัดกรอง stage ของ DM/HT ตามสี", "การเล่นกีฬา", "การออกกำลังกาย", "เครื่องมือผ่าตัด"],
    "A",
    "ปิงปอง 7 สี: เครื่องมือคัดกรองและจำแนกระดับความเสี่ยง DM/HT/CKD",
    "สีเขียว/ทอง/เหลือง/ส้ม/แดง/ดำ ตาม risk + complication",
    ["ใช่ — มาตรฐาน MOPH", "ไม่ใช่", "ไม่ใช่", "ไม่ใช่"],
    "ปิงปอง 7 สี = NCD stratification tool"),
  q(COM,
    "Primary care: การให้ยาที่ Sub-district Health Promoting Hospital (รพ.สต.) ขีดจำกัดที่สำคัญคือ",
    ["ไม่จำกัด", "บัญชียาตามขอบเขตของรพ.สต. และ scope ของผู้ปฏิบัติ", "ให้ทุก antibiotic", "ให้ chemotherapy ได้"],
    "B",
    "บัญชียาที่กำหนดไว้สำหรับ รพ.สต. (essential drugs) + ขอบเขตวิชาชีพพยาบาลผู้ประกอบโรคศิลปะขั้นพื้นฐาน",
    "ส่งต่อเมื่อเกินขอบเขต",
    ["ผิด", "ใช่ — มาตรฐาน", "เกินขอบเขต", "เกินขอบเขต"],
    "รพ.สต.: drug list + scope of practice"),
  q(COM,
    "Disaster nursing: การทำ triage ตามระบบ START สำหรับ adults",
    ["RPM = Respiration, Perfusion, Mental status", "สีตามอายุ", "เลือกตามชาติ", "ไม่ใช่ triage"],
    "A",
    "START: walking wounded (green) → assess RPM → red/yellow/black",
    "Respiration > 30 → red; capillary refill > 2 sec → red; ไม่ทำตามคำสั่ง → red",
    ["ใช่ — มาตรฐาน", "ไม่ใช่ START", "ผิด", "ผิด"],
    "START triage: R-P-M"),
  q(COM,
    "การควบคุม HIV ในชุมชน (Test and Treat strategy) ระบุว่า",
    ["รักษาเมื่อ CD4 < 200", "เริ่ม ART ทันทีเมื่อยืนยัน HIV (regardless CD4)", "ไม่ต้องรักษา", "รักษาเฉพาะ symptom"],
    "B",
    "WHO 2016: ART ทันทีหลังยืนยัน HIV; ลด transmission + improve survival; 'U=U' (undetectable=untransmittable)",
    "ไทยใช้นโยบายนี้ตั้งแต่ 2014",
    ["ล้าสมัย", "ใช่ — มาตรฐาน", "ผิด", "ผิด"],
    "HIV: Test & Treat + U=U"),
  q(COM,
    "การให้บริการ palliative care ในชุมชน เน้น",
    ["ยืดชีวิตให้นานที่สุด", "บรรเทาทุกข์ทางกาย/จิต/สังคม/จิตวิญญาณ ของผู้ป่วยและครอบครัว", "ยุติชีวิต", "ปฏิเสธบริการ"],
    "B",
    "Palliative = total care ครอบคลุม 4 มิติ; ไม่ใช่ end-of-life เท่านั้น เริ่มได้ตั้งแต่ diagnosis",
    "ม.12 สิทธิปฏิเสธการยืดความตาย",
    ["ขัดกับเป้าหมาย", "ใช่ — มาตรฐาน WHO", "Euthanasia ผิดกฎหมายไทย", "ผิดจริยธรรม"],
    "Palliative: 4 dimensions, not only EoL"),
  q(COM,
    "การส่งเสริมการเลี้ยงลูกด้วยนมแม่ในชุมชน สโลแกน '1-6-2' หมายถึง",
    ["ดูดเร็วภายใน 1 ชม., นมแม่อย่างเดียว 6 เดือน, นมแม่ร่วมอาหารตามวัยจนถึง 2 ปี", "ดื่ม 1 ครั้ง วันละ 6 ครั้ง 2 ปี", "ไม่ใช่", "ไม่ใช่"],
    "A",
    "Thai MOPH breastfeeding promotion '1-6-2': early initiation + exclusive 6 เดือน + continued ≥ 2 ปี",
    "WHO-UNICEF aligned",
    ["ใช่ — มาตรฐาน MOPH", "ผิด", "ผิด", "ผิด"],
    "Breastfeeding 1-6-2"),
  q(COM,
    "การให้บริการ home health care สำหรับผู้สูงอายุ ติดบ้าน-ติดเตียง กลุ่ม contact 3 หรือ 'ติดเตียง' ความถี่ที่เหมาะสมในการเยี่ยมคือ",
    ["ปีละครั้ง", "อย่างน้อย 1 ครั้ง/เดือน หรือบ่อยกว่าตามแผน", "ทุก 5 ปี", "ไม่ต้องเยี่ยม"],
    "B",
    "Thai 3C: ติดสังคม / ติดบ้าน / ติดเตียง; ติดเตียงต้องการ active home care 1+ ครั้ง/เดือน",
    "Care manager + caregiver + family",
    ["น้อยเกิน", "ใช่ — มาตรฐาน", "ผิด", "Negligence"],
    "ติดเตียง: home visit ≥ 1×/month"),
  q(COM,
    "Health Belief Model ประกอบด้วยตัวแปร",
    ["Perceived susceptibility, severity, benefits, barriers, cues to action, self-efficacy", "Bell, ball, base, basket", "PDCA", "SWOT"],
    "A",
    "HBM ใช้คาดการณ์พฤติกรรมสุขภาพ; intervention ออกแบบให้แตะ 6 ตัวแปรนี้",
    "TTM = stages of change (precontemplation → maintenance)",
    ["ใช่ — มาตรฐาน", "ผิด", "Quality improvement", "Strategic planning"],
    "HBM: 6 constructs (S-S-B-B-C-E)"),
  q(COM,
    "การส่งต่อผู้ป่วยจากชุมชน (referral) ข้อมูลใดต้อง 'ต้อง' มีเสมอใน referral form",
    ["ราคาบ้าน", "ประวัติเจ็บป่วย, vital signs ล่าสุด, การรักษาที่ให้, ยาแพ้, เหตุผลการส่งต่อ", "เบอร์โทรหมอ", "ที่อยู่ของพยาบาล"],
    "B",
    "Referral essentials: SBAR / summary + reason + vitals + meds + allergies + investigations + contact",
    "ลด communication error → patient safety",
    ["ไม่เกี่ยว", "ใช่ — มาตรฐาน", "ไม่เกี่ยว", "ไม่เกี่ยว"],
    "Referral: SBAR + allergies + reason"),

  // ============================================================
  // 8) NursingLawEthics — กฎหมายและจรรยาบรรณวิชาชีพ (25)
  // ============================================================
  q(LAW,
    "พ.ร.บ.วิชาชีพการพยาบาลและการผดุงครรภ์ พ.ศ. 2528 (และที่แก้ไข) ระบุว่าใครเป็นผู้ออกใบประกอบวิชาชีพ",
    ["กระทรวงแรงงาน", "สภาการพยาบาล", "กรมการแพทย์", "อย."],
    "B",
    "สภาการพยาบาล เป็นองค์กรวิชาชีพออกใบประกอบวิชาชีพและกำกับมาตรฐาน",
    "ใบประกอบฯ 5 ปีต่ออายุ; ต้องสะสม CNE",
    ["ไม่ใช่", "ใช่ — มาตรฐาน", "ไม่ใช่", "อย. = ยาและอาหาร"],
    "สภาการพยาบาล = ออกใบประกอบ"),
  q(LAW,
    "หลักจริยธรรมข้อใดเน้น 'การเคารพการตัดสินใจของผู้ป่วย'",
    ["Beneficence", "Autonomy", "Justice", "Nonmaleficence"],
    "B",
    "Autonomy = สิทธิการตัดสินใจของผู้ป่วยรวมถึงข้อมูลตน",
    "Beneficence = ทำคุณ; Nonmaleficence = ไม่ทำร้าย; Justice = ความเป็นธรรม",
    ["ทำประโยชน์", "ใช่ — autonomy", "ความยุติธรรม", "ไม่ทำอันตราย"],
    "Autonomy = self-decision"),
  q(LAW,
    "Informed consent ที่ valid ต้องประกอบด้วย",
    ["มีลายเซ็นพอ", "Voluntary + capacity + adequate information + comprehension", "ผู้ป่วยรู้แค่ว่ามีการรักษา", "ไม่ต้องบอก risk"],
    "B",
    "Valid IC: 4 องค์ประกอบ; เซ็นเอกสารเพียงอย่างเดียวไม่พอ",
    "Special: minor → ผู้แทนโดยชอบธรรม; emergency → implied consent",
    ["ไม่เพียงพอ", "ใช่ — มาตรฐาน", "ไม่ครบ", "ผิดกฎหมาย"],
    "IC = voluntary + capacity + info + comprehension"),
  q(LAW,
    "Negligence ในวิชาชีพประกอบด้วย 4 องค์ประกอบ (4 D)",
    ["Duty, Dereliction, Damage, Direct cause", "Don't, Do, Discuss, Discharge", "ไม่มี", "Diagnose, Disease, Drug, Dose"],
    "A",
    "Malpractice 4D: หน้าที่ + ละเลย + เสียหาย + เป็นเหตุโดยตรง",
    "ขาดข้อใดข้อหนึ่ง ไม่ถือเป็น malpractice",
    ["ใช่ — มาตรฐาน", "ผิด", "ต้องมีกรอบ", "ผิด"],
    "Malpractice = 4D"),
  q(LAW,
    "Confidentiality ในวิชาชีพ ข้อยกเว้นที่อาจเปิดเผยข้อมูลผู้ป่วยได้คือ",
    ["เพื่อนถาม", "เมื่อมีกฎหมายบังคับ (เช่น รายงานโรคติดต่อ, ศาลออกหมาย, อันตรายต่อผู้อื่น)", "ทุกกรณี", "ไม่มีข้อยกเว้น"],
    "B",
    "Tarasoff principle, mandatory reporting, court order, public health = legitimate exceptions",
    "ต้อง document และเปิดเฉพาะส่วนที่จำเป็น",
    ["Violation", "ใช่ — มาตรฐาน", "Violation", "มี exceptions"],
    "Confidentiality: exceptions by law/safety"),
  q(LAW,
    "ผู้ป่วย competent อายุ 65 ปี ปฏิเสธ blood transfusion ด้วยเหตุผลทางศาสนา การพยาบาลที่เหมาะสมคือ",
    ["บังคับให้รับเลือด", "เคารพสิทธิ documenting decision + offer alternatives + ensure understanding", "ขู่ครอบครัวให้บังคับ", "ไม่บอกครอบครัว"],
    "B",
    "Adult competent: ปฏิเสธการรักษาได้แม้ life-threatening — autonomy principle",
    "Document advance refusal, alternatives, support",
    ["ผิดกฎหมาย & ethics", "ใช่ — มาตรฐาน", "Coercion", "Hide info"],
    "Competent adult refusal: respect autonomy"),
  q(LAW,
    "Mandatory reporting ในไทย: child abuse ต้องรายงานตามพ.ร.บ.",
    ["คุ้มครองเด็ก พ.ศ. 2546", "ยา", "การศึกษา", "ไม่มี"],
    "A",
    "พ.ร.บ.คุ้มครองเด็ก พ.ศ. 2546 มาตรา 29 กำหนดผู้พบเห็นต้องแจ้งเจ้าหน้าที่",
    "หากไม่แจ้ง = ความผิด",
    ["ใช่ — มาตรฐาน", "ไม่ใช่", "ไม่ใช่", "ผิดกฎหมาย"],
    "Child abuse: report ตาม พ.ร.บ. 2546"),
  q(LAW,
    "Do-Not-Resuscitate (DNR) order ในไทย",
    ["ไม่มีพื้นฐานทางกฎหมาย", "อยู่ภายใต้ ม.12 พ.ร.บ.สุขภาพแห่งชาติ + ต้องเป็น written advance directive หรือเขียนใน chart", "ทำได้โดยพยาบาลตามอำเภอใจ", "เป็น euthanasia"],
    "B",
    "DNR/NTBR: ผู้ป่วยมีสิทธิตาม ม.12; ต้องมีเอกสารแสดงเจตนาที่ชัดเจนหรือบันทึกตามวิจารณญาณทางการแพทย์",
    "ไม่ใช่ euthanasia (active killing)",
    ["ผิด", "ใช่ — มาตรฐาน", "ผิดวิชาชีพ", "ผิด"],
    "DNR ≠ euthanasia; ม.12 พ.ร.บ.สุขภาพ"),
  q(LAW,
    "Capacity assessment สำหรับ informed consent ประเมินอะไร",
    ["Understanding + appreciation + reasoning + ability to communicate decision", "ระดับการศึกษา", "อายุ", "ฐานะ"],
    "A",
    "4 capacity criteria; assessed for specific decision (decision-specific)",
    "Capacity ≠ competence (legal term)",
    ["ใช่ — มาตรฐาน", "ไม่เกี่ยว", "Adult ไม่จำเป็น", "ผิด"],
    "Capacity: 4 elements, decision-specific"),
  q(LAW,
    "Conflict of interest ในวิชาชีพการพยาบาล ตัวอย่าง",
    ["รับ commission จากบริษัทยาเพื่อแนะนำสินค้า", "ดูแลผู้ป่วยตามมาตรฐาน", "เรียนต่อ", "พักผ่อน"],
    "A",
    "COI: financial/personal interest ขัดกับ patient welfare",
    "ต้องเปิดเผยและจัดการ — ICN code of ethics",
    ["ใช่ — COI", "ทำตามวิชาชีพ", "Education", "ไม่ใช่ COI"],
    "COI: disclose + manage"),
  q(LAW,
    "ผู้ป่วยอายุ 17 ปี ตั้งครรภ์ ต้องการทำหัตถการ พยาบาลควร",
    ["รับ consent จากผู้ป่วยเพียงคนเดียว", "รับ consent จากผู้ปกครองตามกฎหมาย (parental consent) + assent ของเยาวชน", "ไม่ต้อง consent", "Refuse to treat"],
    "B",
    "Thai law: minor < 20 ปี ต้องมี parental consent (มีข้อยกเว้น emergency/abuse case)",
    "Assent ของวัยรุ่นเป็นส่วน ethics",
    ["ไม่ครบ", "ใช่ — มาตรฐาน", "ผิดกฎหมาย", "ผิด"],
    "Minor consent: parental + assent"),
  q(LAW,
    "Code of ethics ของพยาบาลไทยกำหนดให้พยาบาลต้อง",
    ["รักษาผลประโยชน์บริษัทยาก่อน", "ปฏิบัติด้วยความซื่อสัตย์ เคารพศักดิ์ศรี รักษาความลับ ไม่เลือกปฏิบัติ", "ปฏิเสธผู้ป่วยติดเชื้อ", "ปกปิดความผิดของเพื่อนร่วมงาน"],
    "B",
    "ICN/Thai code of ethics: respect, equity, accountability, confidentiality, integrity",
    "ห้าม discrimination ตาม disease, race, status",
    ["Violation", "ใช่ — มาตรฐาน", "Discrimination", "Cover-up"],
    "Ethics: respect + equity + integrity"),
  q(LAW,
    "Documentation: หลักการ 'If you didn't chart it, you didn't do it' หมายถึง",
    ["ถ้าไม่บันทึก ถือว่าไม่ได้ทำ — ผลทางกฎหมาย", "ไม่ต้องบันทึก", "บันทึกทีหลังได้", "ลบบันทึกได้"],
    "A",
    "Legal principle: medical record คือหลักฐาน; การไม่บันทึกอาจเป็น negligence",
    "บันทึกตามจริง, ทันที, ใช้ภาษาวิชาชีพ, ห้ามลบ",
    ["ใช่ — มาตรฐาน", "ผิด", "ผิด", "ผิด/อาจเป็นอาชญากรรม"],
    "Chart: accurate, timely, complete"),
  q(LAW,
    "Patient's right ตามคำประกาศสิทธิและข้อพึงปฏิบัติของผู้ป่วย (Thai) ครอบคลุม",
    ["ได้รับข้อมูล / ตัดสินใจ / รักษาความลับ / refuse / second opinion / dignity", "เฉพาะอันใดอันหนึ่ง", "ไม่มีสิทธิ refuse", "ไม่มีในไทย"],
    "A",
    "Thai patient rights declaration 2562: รวมสิทธิครอบคลุมจริยธรรมและกฎหมาย",
    "พยาบาลต้องสื่อสาร + facilitate",
    ["ใช่ — มาตรฐาน", "ไม่ครบ", "ผิด", "มี"],
    "Patient rights: comprehensive set"),
  q(LAW,
    "Whistleblowing เมื่อเห็นเพื่อนร่วมงานทำผิดมาตรฐาน",
    ["เพิกเฉย", "รายงานผู้บังคับบัญชา/คณะกรรมการจริยธรรมตามขั้นตอน + protect patient first", "โทรเข้า hotline ของสื่อทันที", "Block social media"],
    "B",
    "Internal reporting ตามลำดับขั้น; protect patient + document + follow up",
    "External whistleblowing เมื่อ internal ไม่ตอบสนอง",
    ["Negligence", "ใช่ — มาตรฐาน", "Skipping process", "ไม่ใช่ professional response"],
    "Whistleblowing: internal first, patient first"),
  q(LAW,
    "End-of-life: การถอน ventilator ใน vegetative state มี living will (ม.12) — พยาบาลทำได้ไหม",
    ["ทำไม่ได้", "ทำได้ตามแผนหลัง physician order + ครอบครัว/ผู้ป่วยตามเจตนา — ไม่ใช่ euthanasia", "ผิดกฎหมายเสมอ", "เป็น murder"],
    "B",
    "Withdraw of life-sustaining treatment ตาม advance directive ถูกต้องตาม ม.12 (พ.ร.บ.สุขภาพแห่งชาติ 2550)",
    "ต่างจาก active euthanasia ซึ่งยังผิดกฎหมายไทย",
    ["ผิด", "ใช่ — มาตรฐาน", "ผิด", "ผิด"],
    "Withdraw ≠ euthanasia (ม.12 ok)"),
  q(LAW,
    "Restraint ใน Thai psychiatric law (พ.ร.บ.สุขภาพจิต 2551) กำหนดให้",
    ["ใช้ได้ตามใจ", "ใช้เท่าที่จำเป็น มีคำสั่งแพทย์ บันทึกเหตุผล ติดตามอาการ", "ใช้กับทุกราย", "ไม่จำเป็นต้องบันทึก"],
    "B",
    "พ.ร.บ.สุขภาพจิต กำหนดมาตรฐานการใช้กำลัง/มัด อย่างมีหลักจริยธรรมและความปลอดภัย",
    "ตรวจสอบทุก 15 นาที + offer release ASAP",
    ["Violation", "ใช่ — มาตรฐาน", "ผิด", "ผิด"],
    "Restraint: necessary + ordered + recorded"),
  q(LAW,
    "Telemedicine ในไทย พยาบาลที่ให้บริการต้อง",
    ["ไม่ต้องมีใบประกอบ", "มีใบประกอบฯ ที่ยัง valid + ทำตามแนวทาง telehealth ของสภาการพยาบาล + ขอบเขตวิชาชีพ", "ฟรีเรียก หมอเลย", "ไม่ต้องบันทึก"],
    "B",
    "ต้องมี license, scope of practice, informed consent, privacy, documentation",
    "Telehealth guideline จาก กระทรวงสาธารณสุข & สภาการพยาบาล",
    ["ผิดกฎหมาย", "ใช่ — มาตรฐาน", "ไม่ใช่ scope", "Mandatory"],
    "Telehealth: license + scope + privacy + chart"),
  q(LAW,
    "Privacy: HIPAA-like principle ในไทย กฎหมายหลักคือ",
    ["พ.ร.บ.คุ้มครองข้อมูลส่วนบุคคล (PDPA) พ.ศ. 2562", "พ.ร.บ.อาวุธปืน", "พ.ร.บ.ภาษี", "ไม่มี"],
    "A",
    "PDPA 2562 + พ.ร.บ.สุขภาพแห่งชาติ ม.7 ห้ามเปิดเผยข้อมูลสุขภาพโดยไม่ได้รับยินยอม",
    "Violation = ปรับและความรับผิดวิชาชีพ",
    ["ใช่ — มาตรฐาน", "ไม่เกี่ยว", "ไม่เกี่ยว", "มี"],
    "Privacy: PDPA + ม.7 พ.ร.บ.สุขภาพ"),
  q(LAW,
    "Organ donation ในไทย หลักการสำคัญที่สุดคือ",
    ["บังคับ", "Voluntary + informed consent + brain death certification by 3 physicians + ไม่ซื้อขาย", "ขายได้", "ครอบครัวไม่เกี่ยว"],
    "B",
    "Organ donation: 3-doctor brain death + voluntary + free of charge ตาม WHO guiding principles + กฎหมายไทย",
    "Living donor = relative only (in Thai practice)",
    ["ผิดจริยธรรม", "ใช่ — มาตรฐาน", "ผิดกฎหมาย", "Family role"],
    "Organ donation: voluntary + brain death + non-commercial"),
  q(LAW,
    "พยาบาล ถูกคำสั่งให้ให้ยาที่สงสัยขนาดผิด ต้อง",
    ["ให้ตามคำสั่งโดยไม่ถาม", "ตรวจสอบกับ MD/ตำรา ก่อนให้ — ใช้ professional judgment + document", "ปฏิเสธทันทีโดยไม่บอก", "เรียกตำรวจ"],
    "B",
    "Nurses have independent professional accountability — must verify before executing questionable order",
    "ไม่ใช่ blind obedience; document concern + supervisor",
    ["Negligence", "ใช่ — มาตรฐาน", "ไม่ professional", "ไม่จำเป็น"],
    "Questionable order: verify + document"),
  q(LAW,
    "ใบประกอบวิชาชีพการพยาบาลในไทยต่ออายุ",
    ["10 ปี", "5 ปี ต้องมี CNE 50 หน่วยกิต", "ไม่ต้องต่อ", "ทุก 1 ปี"],
    "B",
    "สภาการพยาบาล: ต่ออายุทุก 5 ปี + CNE 50 หน่วย ก่อนหมดอายุ",
    "ไม่ต่อ = ใบหมดอายุ = ห้ามประกอบวิชาชีพ",
    ["ผิด", "ใช่ — มาตรฐาน", "ผิด", "ผิด"],
    "License renewal: 5 yr + CNE 50"),
  q(LAW,
    "Professional misconduct ตามสภาการพยาบาล โทษสูงสุดคือ",
    ["ตักเตือน", "เพิกถอนใบประกอบวิชาชีพ", "ปรับ 100 บาท", "พักงาน 1 วัน"],
    "B",
    "Sanctions: ตักเตือน → ภาคทัณฑ์ → พักใช้ → เพิกถอน",
    "พิจารณาตามมาตรฐานวิชาชีพและจริยธรรม",
    ["ขั้นต้น", "ใช่ — สูงสุด", "ไม่ใช่", "ไม่พอ"],
    "Misconduct sanctions: warn → suspend → revoke"),
  q(LAW,
    "Beneficence vs Nonmaleficence ความแตกต่างหลักคือ",
    ["เหมือนกัน", "Beneficence = ทำคุณ; Nonmaleficence = ไม่ทำร้าย (primum non nocere)", "ไม่มีต่าง", "ตรงข้ามกัน"],
    "B",
    "Beneficence = active good; Nonmaleficence = avoid harm — สองหลักต่างกันแต่เกี่ยวข้อง",
    "บางครั้งขัดกัน → risk-benefit analysis",
    ["ผิด", "ใช่ — มาตรฐาน", "ผิด", "ไม่ใช่ตรงข้าม — เสริมกัน"],
    "Bene = do good; Non-mal = don't harm"),
  q(LAW,
    "หน้าที่หลักของพยาบาลตามคำจำกัดความ ICN",
    ["รักษาโรค", "Promote health, prevent illness, restore health, alleviate suffering ทุกบุคคล/ครอบครัว/ชุมชน", "เฉพาะวัยทำงาน", "ทำตามคำสั่งแพทย์อย่างเดียว"],
    "B",
    "ICN nursing definition: 4 functions, holistic, person/family/community",
    "Independent practice ตามขอบเขต",
    ["ผิด — ขอบเขตแคบ", "ใช่ — มาตรฐาน", "ผิด", "ผิด — autonomy ของวิชาชีพ"],
    "Nursing = promote + prevent + restore + alleviate"),
];

async function run() {
  const client = new Client({
    connectionString: DATABASE_URL,
    ssl: { rejectUnauthorized: false },
  });
  await client.connect();

  const subjectRows = await client.query(
    "SELECT id, name FROM mcq_subjects WHERE exam_type = 'NLE'"
  );
  const subjectIdByName = Object.fromEntries(
    subjectRows.rows.map((r) => [r.name, r.id])
  );

  const missing = [...new Set(all.map((q) => q.subjectName))].filter(
    (n) => !subjectIdByName[n]
  );
  if (missing.length > 0) {
    console.error("ERROR: missing nursing subjects:", missing.join(", "));
    process.exit(1);
  }

  let inserted = 0;
  const perSubject = {};
  for (const item of all) {
    const subjectId = subjectIdByName[item.subjectName];
    const id = randomUUID();
    await client.query(
      `INSERT INTO mcq_questions
       (id, subject_id, exam_type, scenario, choices, correct_answer,
        explanation, detailed_explanation, difficulty, is_ai_enhanced,
        ai_notes, status)
       VALUES ($1, $2, 'NLE', $3, $4, $5, $6, $7, $8, false, $9, 'active')`,
      [
        id,
        subjectId,
        item.scenario,
        JSON.stringify(item.choices),
        item.correct_answer,
        item.explanation,
        JSON.stringify(item.detailed_explanation),
        item.difficulty,
        "NLE batch 2 — manual seed, review before high-stakes use",
      ]
    );
    inserted++;
    perSubject[item.subjectName] = (perSubject[item.subjectName] || 0) + 1;
  }

  // Refresh question_count per subject
  await client.query(`
    UPDATE mcq_subjects s
    SET question_count = (
      SELECT COUNT(*) FROM mcq_questions q
      WHERE q.subject_id = s.id AND q.status = 'active'
    )
    WHERE s.exam_type = 'NLE'
  `);

  console.log("=== Per-subject inserted ===");
  for (const [name, count] of Object.entries(perSubject)) {
    console.log(`  ${name}: ${count}`);
  }
  console.log(`\n=== Done: inserted ${inserted} NLE questions ===`);
  await client.end();
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
