import type { Ip1MockDomainContent } from "@/lib/ip1-mock/types";

export const ANALYSIS: Ip1MockDomainContent = [
  // Mock Set 1
  [
    {
      t: "ICH Q3C Class 1 solvents",
      p: "ในการพัฒนากระบวนการสังเคราะห์ API ทีม R&D เสนอให้ใช้ตัวทำละลายต่อไปนี้ ข้อใดเป็น Class 1 solvent ตาม ICH Q3C ซึ่งควรหลีกเลี่ยงการใช้ในการผลิตยา",
      o: ["Benzene", "Methanol", "Ethanol", "Acetone", "Ethyl acetate"],
      a: 0,
      r: "ICH Q3C แบ่ง residual solvents เป็น 3 class ตามความเป็นพิษ: Class 1 คือ solvents ที่ควรหลีกเลี่ยง (known/strongly suspected human carcinogen หรือเป็นอันตรายต่อสิ่งแวดล้อม) เช่น benzene (2 ppm), carbon tetrachloride (4 ppm), 1,2-dichloroethane (5 ppm), 1,1-dichloroethene (8 ppm) และ 1,1,1-trichloroethane (1500 ppm; สิ่งแวดล้อม)\n\nClass 2 คือ solvents ที่ควรจำกัดปริมาณ (มี PDE) เช่น methanol, acetonitrile, dichloromethane, hexane ส่วน Class 3 เป็น solvents ความเป็นพิษต่ำ (PDE ≥ 50 mg/day) เช่น ethanol, acetone, ethyl acetate หากจำเป็นต้องใช้ Class 1 จริงต้องมีเหตุผลด้าน risk–benefit ที่ชัดเจนและควบคุมไม่เกิน limit",
      w: [
        "ถูก — benzene เป็น human carcinogen จัดเป็น Class 1 (limit 2 ppm) ควรหลีกเลี่ยงการใช้",
        "Methanol เป็น Class 2 (PDE 30 mg/day, 3000 ppm) ใช้ได้แต่ต้องจำกัดปริมาณ",
        "Ethanol เป็น Class 3 ความเป็นพิษต่ำ ใช้ได้ทั่วไป",
        "Acetone เป็น Class 3 ความเป็นพิษต่ำ",
        "Ethyl acetate เป็น Class 3 ความเป็นพิษต่ำ",
      ],
      k: "Class 1 = หลีกเลี่ยง (benzene 2 ppm, CCl4 4 ppm); Class 2 = จำกัดด้วย PDE; Class 3 = พิษต่ำ (≤0.5% ไม่ต้องให้เหตุผลเพิ่ม)",
      d: "easy",
      ref: "ICH Q3C(R9) Impurities: Guideline for Residual Solvents",
    },
    {
      t: "Primary vs secondary reference standard",
      p: "ห้อง QC ต้องการลดค่าใช้จ่ายจากการใช้ USP Reference Standard ในการ assay ประจำวัน จึงเตรียม in-house working standard จาก API lot ที่มีความบริสุทธิ์สูง ข้อใดเป็นแนวปฏิบัติที่ถูกต้องที่สุด",
      o: [
        "Qualify working standard โดยทดสอบเทียบกับ primary (pharmacopeial) reference standard บันทึกค่า assigned purity และกำหนด re-test date",
        "ใช้ API lot นั้นได้ทันทีโดยถือว่า purity 100% เพราะผ่าน release specification แล้ว",
        "ใช้ COA ของผู้ผลิต API เป็นค่า purity ของ working standard โดยไม่ต้องทดสอบเพิ่ม",
        "Qualify โดยเทียบกับ working standard lot เก่าที่หมดอายุแล้วเพราะเป็น lot เดียวกันกับที่เคยใช้",
        "ใช้ working standard แทน primary standard ได้ในทุกการทดสอบรวมถึงข้อพิพาททางกฎหมาย",
      ],
      a: 0,
      r: "Primary reference standard (เช่น USP RS, Ph.Eur. CRS, WHO ICRS) ถือว่ามีคุณสมบัติเหมาะสมสำหรับวัตถุประสงค์โดยไม่ต้องเทียบกับสารอื่น ส่วน secondary/working standard คือสารที่ถูก qualify โดยเทียบกับ primary standard และใช้ในงานประจำ\n\nการ qualify ต้องมีการยืนยัน identity, ทดสอบ purity/assay เทียบกับ primary standard (มักทำซ้ำหลายครั้ง), กำหนด assigned value, เงื่อนไขการเก็บ และ re-test/expiry date รวมทั้งมีเอกสารที่ trace กลับไปยัง primary ได้ (traceability) เมื่อเกิดข้อสงสัยหรือข้อพิพาท ผลที่อ้างอิงได้คือผลที่ใช้ primary (compendial) standard",
      w: [
        "ถูก — working standard ต้องถูก qualify เทียบกับ primary standard มี assigned value และ re-test date เพื่อให้ traceable",
        "การผ่าน release spec (เช่น 98.0–102.0%) ไม่ได้หมายความว่า purity เท่ากับ 100% การสมมติเช่นนี้ทำให้ผล assay เอนเอียง",
        "COA ของผู้ผลิตไม่ได้พิสูจน์ traceability กับ primary standard ของห้องปฏิบัติการผู้ใช้",
        "การเทียบกับ standard ที่หมดอายุไม่ถูกต้อง และไม่ trace กลับไปยัง primary standard",
        "เมื่อเกิดข้อพิพาท ผลที่อ้างอิงได้ตาม pharmacopoeia คือผลที่ใช้ compendial (primary) reference standard",
      ],
      k: "Working/secondary standard = qualify เทียบ primary RS, มี assigned purity + re-test date และ traceability",
      d: "easy",
      ref: "WHO TRS 943 Annex 3 (General guidelines for the establishment, maintenance and distribution of chemical reference substances); USP <11>",
    },
    {
      t: "HPLC resolution from half-height widths",
      p: "การวิเคราะห์ related substances ด้วย HPLC ได้ peak ของ impurity A ที่ tR = 6.20 min (width at half height = 0.20 min) และ peak ของ API ที่ tR = 6.95 min (width at half height = 0.22 min) Resolution (Rs) ระหว่างสอง peak มีค่าประมาณเท่าใด",
      o: ["1.0", "1.8", "2.1", "3.6", "4.2"],
      a: 2,
      r: "สูตร resolution ใช้ได้ 2 แบบตาม width ที่วัด: ถ้าใช้ baseline width (tangent) Rs = 2(tR2 − tR1)/(W1 + W2) แต่ถ้าใช้ width at half height Rs = 1.18(tR2 − tR1)/(W0.5,1 + W0.5,2) (Ph.Eur./USP <621>)\n\nแทนค่า: Rs = 1.18 × 0.75 / 0.42 = 2.1 ซึ่งมากกว่า 1.5 (baseline separation) และผ่านเกณฑ์ SST ทั่วไปของ related substances ที่มักกำหนด Rs ≥ 1.5–2.0 ระหว่าง critical pair",
      w: [
        "ไม่ตรงกับสูตรใดเลย ค่าต่ำเกินไป",
        "เป็นผลจาก (tR2 − tR1)/(W0.5,1 + W0.5,2) ซึ่งลืมคูณด้วย 1.18",
        "ถูก — Rs = 1.18 × (6.95 − 6.20)/(0.20 + 0.22) = 2.1",
        "เป็นผลจากการใช้สูตร baseline width 2Δt/(W1+W2) กับ width at half height ทำให้ค่าสูงเกินจริง",
        "ค่าสูงเกินจริง ไม่ได้มาจากสูตรที่ถูกต้อง",
      ],
      k: "Rs = 2Δt/(Wb1+Wb2) หรือ 1.18Δt/(W0.5,1+W0.5,2); Rs ≥ 1.5 = baseline separation",
      d: "medium",
      ref: "USP <621> Chromatography; Ph.Eur. 2.2.46",
      c: [
        "Δt = 6.95 − 6.20 = 0.75 min",
        "ΣW0.5 = 0.20 + 0.22 = 0.42 min",
        "Rs = 1.18 × 0.75 / 0.42 = 2.1",
      ],
    },
    {
      t: "UV assay using A(1%, 1 cm)",
      p: "Assay ยาเม็ดขนาด 100 mg/เม็ด (น้ำหนักเฉลี่ย 0.3000 g) ด้วย UV ที่ λmax: ชั่งผงยาบด 0.1500 g ละลายและปรับปริมาตรเป็น 100 mL กรอง แล้วปิเปต 2.0 mL เจือจางเป็น 100 mL วัดค่า absorbance ใน cell 1 cm ได้ 0.702 กำหนด A(1%, 1 cm) = 715 ปริมาณยาคิดเป็น % label claim เท่าใด",
      o: ["95.4%", "96.8%", "98.2%", "101.9%", "103.6%"],
      a: 2,
      r: "A(1%, 1 cm) คือ absorbance ของสารละลายเข้มข้น 1 g/100 mL ใน cell 1 cm ดังนั้นความเข้มข้น (g/100 mL) = A / A(1%, 1 cm) เมื่อ path length = 1 cm\n\nความเข้มข้นใน cuvette = 0.702/715 = 9.818 × 10⁻⁴ g/100 mL คูณ dilution factor 50 (2 → 100 mL) ได้ 0.04909 g/100 mL ในสารละลายแรก = 49.09 mg ในผง 0.1500 g ซึ่งเทียบเท่าครึ่งเม็ด (0.1500/0.3000) จึงได้ 98.2 mg/เม็ด = 98.2% LC\n\nPearl: ต้องคิดผ่านน้ำหนักเฉลี่ยของเม็ด (ไม่ใช่สมมติว่าผงทั้งหมดเป็นตัวยา) และตรวจว่า absorbance อยู่ในช่วง linear (~0.2–0.8)",
      w: [
        "ค่าต่ำกว่าผลคำนวณที่ถูกต้อง อาจเกิดจากใช้ dilution factor ผิด",
        "ค่าต่ำกว่าผลคำนวณที่ถูกต้อง",
        "ถูก — 0.702/715 × 50 = 0.04909 g/100 mL = 49.09 mg ในผงครึ่งเม็ด → 98.2 mg/เม็ด = 98.2% LC",
        "เป็นผลจากการกลับสัดส่วน (A ที่คาดหวัง 0.715 ÷ A ที่วัดได้ 0.702) ซึ่งผิดทิศทาง",
        "ค่าสูงเกินจริง ไม่สอดคล้องกับ absorbance ที่วัดได้ซึ่งต่ำกว่าค่าคาดหวัง (0.715)",
      ],
      k: "C (g/100 mL) = A / [A(1%,1cm) × b]; อย่าลืม dilution factor และการแปลงผงยาเป็นต่อเม็ดด้วยน้ำหนักเฉลี่ย",
      d: "medium",
      ref: "BP Appendix II B (Ultraviolet and Visible Absorption Spectrophotometry); Beckett & Stenlake, Practical Pharmaceutical Chemistry Part 2",
      c: [
        "C ใน cuvette = 0.702 / 715 = 9.818 × 10⁻⁴ g/100 mL",
        "C ในสารละลายแรก = 9.818 × 10⁻⁴ × (100/2) = 0.04909 g/100 mL = 49.09 mg ใน 100 mL",
        "ผง 0.1500 g = 0.1500/0.3000 = 0.5 เม็ด → ต่อเม็ด = 49.09 × 2 = 98.18 mg",
        "% LC = 98.18/100 × 100 = 98.2%",
      ],
    },
    {
      t: "Volumetric Karl Fischer water calculation",
      p: "หาปริมาณน้ำใน API ด้วย volumetric Karl Fischer: KF reagent มี water equivalence factor (F) = 4.85 mg H₂O/mL ตัวอย่าง 0.2500 g ใช้ reagent 1.62 mL และ blank ของ solvent ใช้ 0.10 mL ปริมาณน้ำในตัวอย่างเป็นเท่าใด",
      o: ["2.75% w/w", "2.95% w/w", "3.14% w/w", "3.30% w/w", "7.37% w/w"],
      a: 1,
      r: "Volumetric KF อาศัยปฏิกิริยา I₂ + SO₂ + H₂O ในสภาวะที่มี base และ alcohol (1 mol I₂ ทำปฏิกิริยากับ 1 mol H₂O) titer ของ reagent (F) หาโดย standardize กับ sodium tartrate dihydrate (15.66% น้ำ) หรือน้ำบริสุทธิ์\n\nปริมาณน้ำ = (V sample − V blank) × F = (1.62 − 0.10) × 4.85 = 7.372 mg ในตัวอย่าง 250 mg = 2.95% w/w\n\nการไม่หัก blank ทำให้ผลสูงเกินจริง (3.14%) ซึ่งสำคัญมากเมื่อ spec ใกล้ขีดจำกัด",
      w: [
        "ค่าต่ำเกินไป ไม่สอดคล้องกับการคำนวณ",
        "ถูก — (1.62 − 0.10) × 4.85 = 7.372 mg ÷ 250 mg × 100 = 2.95%",
        "เป็นผลจากการไม่หัก blank: 1.62 × 4.85/250 × 100 = 3.14%",
        "ค่าสูงเกินจริง ไม่ได้มาจากการคำนวณที่ถูกต้อง",
        "นี่คือปริมาณน้ำเป็น mg (7.37 mg) ไม่ใช่ % w/w",
      ],
      k: "Water (%) = (Vs − Vb) × F / W × 100; F หาจาก sodium tartrate dihydrate (15.66% H₂O)",
      d: "medium",
      ref: "USP <921> Water Determination, Method I; Ph.Eur. 2.5.12",
      c: [
        "Net volume = 1.62 − 0.10 = 1.52 mL",
        "Water = 1.52 × 4.85 = 7.372 mg",
        "% water = 7.372 / 250 × 100 = 2.95% w/w",
      ],
    },
    {
      t: "Non-aqueous titration of weak bases",
      p: "Monograph กำหนดให้ assay ยาที่เป็น weak organic base (pKa ของ conjugate acid ประมาณ 5) โดยละลายใน glacial acetic acid แล้วไทเทรตด้วย 0.1 M perchloric acid ใช้ crystal violet เป็น indicator เหตุผลหลักของการใช้ระบบนี้คือข้อใด",
      o: [
        "Glacial acetic acid เป็น protogenic solvent ที่เสริมความเป็นเบสของ weak base และ HClO₄ เป็นกรดแรงที่สุดในตัวทำละลายนี้ ทำให้ end point คมชัด",
        "Glacial acetic acid ช่วยให้ weak base แตกตัวเป็นไอออนลบ จึงไทเทรตด้วยกรดได้",
        "น้ำทำให้ perchloric acid ระเหิด จึงต้องใช้ตัวทำละลายไม่มีน้ำ",
        "Glacial acetic acid เป็น aprotic solvent จึงไม่มีผลต่อความเป็นกรดเบสของตัวอย่าง",
        "ระบบนี้ใช้เพื่อเพิ่มการละลายเท่านั้น ส่วนความแรงของเบสไม่เปลี่ยนแปลง",
      ],
      a: 0,
      r: "ในน้ำ weak base ที่มี pKa ต่ำ (เบสอ่อนมาก) ให้ end point ไม่คมเพราะน้ำแข่งขันเป็นเบสและเป็นกรด (leveling/competition) เมื่อใช้ glacial acetic acid ซึ่งเป็น protogenic (acidic) solvent สารเบสอ่อนจะรับโปรตอนได้มากขึ้น (ความเป็นเบสถูกเสริม) และ HClO₄ ในกรดอะซิติกให้ CH₃COOH₂⁺ ซึ่งเป็นกรดแรงที่สุดในระบบ\n\nผลคือการเปลี่ยนแปลงศักย์/สีที่ end point ชัดเจน ใช้ crystal violet หรือ potentiometric detection ข้อควรระวัง: ต้องควบคุมน้ำ (เติม acetic anhydride) และแก้ค่า titrant ตามอุณหภูมิเพราะ acetic acid มี coefficient of expansion สูง สำหรับเกลือ hydrohalide แบบเดิมจะเติม mercuric acetate แต่ปัจจุบันหลายตำรับเปลี่ยนเป็น potentiometric titration ในสารละลายผสมเพื่อเลี่ยงปรอท",
      w: [
        "ถูก — protogenic solvent เสริมความเป็นเบสของ weak base และ HClO₄ เป็นกรดแรงที่สุดในระบบ ทำให้ end point ชัด",
        "เบสรับโปรตอนกลายเป็นไอออนบวก (BH⁺) ไม่ใช่แตกตัวเป็นไอออนลบ",
        "Perchloric acid ไม่ได้ระเหิดในน้ำ เหตุผลที่ต้องเลี่ยงน้ำคือน้ำแข่งขันรับโปรตอนทำให้ end point ไม่คม",
        "Glacial acetic acid เป็น protic (protogenic) solvent ไม่ใช่ aprotic",
        "ประเด็นสำคัญคือการเพิ่มความแรงของเบสสัมพัทธ์ ไม่ใช่เพียงการละลาย",
      ],
      k: "Weak base → ไทเทรตใน glacial acetic acid ด้วย HClO₄ (crystal violet/potentiometric); ควบคุมน้ำและอุณหภูมิ",
      d: "medium",
      ref: "Beckett & Stenlake, Practical Pharmaceutical Chemistry Part 1 (Non-aqueous titrations); USP <541> Titrimetry",
    },
    {
      t: "ICH Q2 parameters for impurity limit test",
      p: "ห้อง QC พัฒนาวิธี TLC แบบ limit test เพื่อตรวจว่า impurity B ไม่เกิน 0.2% (ไม่รายงานค่าเชิงปริมาณ) ตาม ICH Q2(R2) validation characteristics ใดที่จำเป็นสำหรับการทดสอบประเภทนี้",
      o: [
        "Specificity และ detection limit",
        "Accuracy, precision และ linearity",
        "Specificity, accuracy, precision, quantitation limit และ range",
        "Linearity และ quantitation limit เท่านั้น",
        "Repeatability และ intermediate precision เท่านั้น",
      ],
      a: 0,
      r: "ICH Q2 จำแนกการทดสอบเป็น identification, impurity test (quantitative หรือ limit), และ assay ซึ่งต้องการ validation characteristics ต่างกัน\n\nLimit test สำหรับ impurity ตอบเพียง 'ผ่าน/ไม่ผ่าน' ณ ระดับที่กำหนด จึงต้องพิสูจน์ specificity (แยก impurity ออกจาก API และสารอื่นได้) และ detection limit (ตรวจพบได้ที่หรือต่ำกว่า limit) ส่วน quantitative impurity test ต้องมี specificity, accuracy, precision, QL, linearity/range ครบ และ assay ไม่ต้องการ DL/QL",
      w: [
        "ถูก — limit test ต้องการ specificity และ detection limit ที่ต่ำกว่าระดับที่กำหนด",
        "Accuracy/precision/linearity จำเป็นสำหรับการทดสอบเชิงปริมาณ ไม่ใช่ limit test",
        "เป็นชุด parameters ของ quantitative impurity test ไม่ใช่ limit test",
        "QL ใช้กับการวัดเชิงปริมาณ ส่วน limit test ใช้ DL",
        "Precision ไม่ใช่ข้อกำหนดหลักของ limit test และขาด specificity ซึ่งจำเป็นเสมอ",
      ],
      k: "Limit test (impurity) = specificity + DL; quantitative impurity = เต็มชุด + QL; assay = ไม่ต้อง DL/QL",
      d: "medium",
      ref: "ICH Q2(R2) Validation of Analytical Procedures",
    },
    {
      t: "OOS Phase I assignable laboratory error",
      p: "ผล assay ยาเม็ดได้ 92.1% (spec 95.0–105.0%) ระหว่าง Phase I laboratory investigation หัวหน้าห้องพบจากสมุดบันทึกและ log ของเครื่อง ultrasonic bath ว่านักวิเคราะห์ sonicate สกัดตัวอย่างเพียง 5 นาที แทนที่จะเป็น 20 นาทีตามวิธี (ยาละลายช้า) ขณะที่ system suitability และ standard ผ่านทั้งหมด ขั้นตอนต่อไปที่เหมาะสมที่สุดคือข้อใด",
      o: [
        "บันทึกว่าเป็น assignable laboratory error ทำให้ผลเดิมเป็น invalid แล้วทดสอบใหม่ตาม SOP และดำเนิน CAPA สำหรับความผิดพลาดนั้น",
        "ยืนยันผล OOS และ reject batch ทันทีโดยไม่ต้องทดสอบใหม่",
        "เปิด Phase II full-scale investigation ในฝ่ายผลิตทันทีเพราะผลต่ำกว่า spec",
        "นำผลเดิมไปเฉลี่ยกับผลใหม่เพื่อรายงานเป็นค่าเดียว",
        "ลบผลเดิมออกจากระบบและรายงานเฉพาะผลใหม่เพื่อไม่ให้สับสน",
      ],
      a: 0,
      r: "ตาม FDA guidance on OOS results, Phase I คือการสืบสวนในห้องปฏิบัติการเพื่อหาความผิดพลาดที่ระบุได้ (assignable cause) เช่น การคำนวณ, การเตรียมสารละลาย, เครื่องมือ หากพบความผิดพลาดที่มีหลักฐานชัดเจนและอธิบายผลได้ สามารถ invalidate ผลเดิมแล้วทดสอบใหม่ได้\n\nการ sonicate สั้นกว่าวิธีที่ validate ไว้ทำให้สกัดยาออกจากเม็ดไม่สมบูรณ์ ผล assay จึงต่ำผิดปกติ — เป็นความเบี่ยงเบนจากวิธีที่มีหลักฐานและอธิบายทิศทางของผลได้\n\nข้อมูลเดิมต้องถูกเก็บไว้ (ไม่ลบ) พร้อมเหตุผลการ invalidate และต้องมี CAPA (เช่น retraining) ถ้า Phase I ไม่พบ assignable cause จึงขยายเป็น Phase II (full-scale investigation รวมการผลิต)",
      w: [
        "ถูก — มี assignable laboratory error ที่มีหลักฐานชัดเจน จึง invalidate ผลเดิม ทดสอบใหม่ และทำ CAPA",
        "ผลเดิมไม่สะท้อนคุณภาพ batch เพราะมีความผิดพลาดของห้องปฏิบัติการที่ระบุได้แล้ว",
        "Phase II ใช้เมื่อ Phase I ไม่พบ assignable cause ในห้องปฏิบัติการ",
        "ห้ามเฉลี่ยผลที่ invalid กับผลใหม่ เพราะผลเดิมไม่ถูกต้องตั้งแต่ต้น",
        "ข้อมูลดิบต้องเก็บไว้ทั้งหมดตามหลัก data integrity การลบข้อมูลเป็นการละเมิด GMP",
      ],
      k: "Phase I พบ assignable lab error ที่มีหลักฐาน → invalidate + retest + CAPA; ไม่พบ → Phase II (full-scale)",
      d: "hard",
      ref: "FDA Guidance for Industry: Investigating Out-of-Specification (OOS) Test Results for Pharmaceutical Production (2006, rev. 2022)",
    },
    {
      t: "ICH Q3A identification threshold decision",
      p: "Drug substance ที่มี maximum daily dose 500 mg/day พบ unknown impurity ที่ RRT 1.35 ระดับ 0.12% ตาม ICH Q3A(R2) ข้อใดสรุปการดำเนินการได้ถูกต้องที่สุด",
      o: [
        "ต้องรายงานและระบุโครงสร้าง (identify) แต่ยังไม่ถึงเกณฑ์ที่ต้อง qualify",
        "รายงานเท่านั้น เพราะยังไม่ถึง identification threshold",
        "ต้องรายงาน ระบุโครงสร้าง และ qualify ทางพิษวิทยา",
        "ไม่ต้องรายงาน เพราะต่ำกว่า reporting threshold",
        "ต้อง qualify แต่ไม่จำเป็นต้องระบุโครงสร้าง",
      ],
      a: 0,
      r: "ICH Q3A(R2) สำหรับ drug substance ที่ MDD ≤ 2 g/day: reporting threshold 0.05%, identification threshold 0.10% หรือ 1.0 mg/day TDI (แล้วแต่ค่าใดต่ำกว่า), qualification threshold 0.15% หรือ 1.0 mg/day TDI (แล้วแต่ค่าใดต่ำกว่า)\n\nที่ MDD 500 mg: 0.10% = 0.5 mg/day < 1.0 mg จึงใช้ 0.10% เป็น identification threshold และ 0.15% = 0.75 mg/day < 1.0 mg จึงใช้ 0.15% เป็น qualification threshold\n\nImpurity 0.12% จึง > 0.05% (ต้องรายงาน) > 0.10% (ต้อง identify) แต่ < 0.15% (ยังไม่ต้อง qualify)",
      w: [
        "ถูก — 0.12% เกิน identification threshold 0.10% แต่ยังต่ำกว่า qualification threshold 0.15%",
        "0.12% เกิน identification threshold (0.10%) แล้ว จึงต้องระบุโครงสร้าง",
        "ยังไม่ถึง qualification threshold 0.15% จึงไม่ต้อง qualify",
        "Reporting threshold คือ 0.05% ซึ่ง 0.12% เกินแล้ว",
        "ลำดับเกณฑ์คือ report → identify → qualify; ระดับนี้ยังไม่ต้อง qualify",
      ],
      k: "Q3A (MDD ≤ 2 g): report 0.05%, identify 0.10%/1.0 mg, qualify 0.15%/1.0 mg (ค่าที่ต่ำกว่า)",
      d: "hard",
      ref: "ICH Q3A(R2) Impurities in New Drug Substances, Attachment 1",
    },
    {
      t: "Interpreting TAMC acceptance criterion 10^3",
      p: "ยาเม็ด (non-aqueous preparation for oral use) มีเกณฑ์ TAMC ≤ 10³ CFU/g และ TYMC ≤ 10² CFU/g ผลการตรวจได้ TAMC = 1,500 CFU/g, TYMC = 150 CFU/g และไม่พบ E. coli ใน 1 g ข้อใดสรุปได้ถูกต้องตาม USP <1111>/Ph.Eur. 5.1.4",
      o: [
        "ผ่านเกณฑ์ทั้งหมด เพราะเกณฑ์ 10³ ยอมรับได้สูงสุด 2,000 CFU/g และ 10² ยอมรับได้สูงสุด 200 CFU/g",
        "ไม่ผ่าน TAMC เพราะ 1,500 > 1,000 CFU/g",
        "ไม่ผ่าน TYMC เพราะ 150 > 100 CFU/g",
        "ไม่ผ่านทั้ง TAMC และ TYMC ต้อง reject batch",
        "ผลใช้ไม่ได้เพราะ TYMC ต้องต่ำกว่า TAMC อย่างน้อย 100 เท่า",
      ],
      a: 0,
      r: "USP <1111> และ Ph.Eur. 5.1.4 กำหนดการตีความ acceptance criteria แบบ log: เมื่อกำหนด 10¹ CFU ยอมรับสูงสุด 20, 10² ยอมรับสูงสุด 200, 10³ ยอมรับสูงสุด 2,000 เป็นต้น เนื่องจากความแปรปรวนโดยธรรมชาติของวิธีนับเชื้อ\n\nสำหรับ non-aqueous oral preparations: TAMC 10³, TYMC 10², และ absence of E. coli (1 g) ผล TAMC 1,500 และ TYMC 150 จึงยังผ่าน แต่ควรติดตาม trend ของ bioburden เพราะเข้าใกล้ขีดสูงสุด",
      w: [
        "ถูก — เกณฑ์ 10³ ตีความเป็นสูงสุด 2,000 และ 10² เป็นสูงสุด 200 ผลทั้งสองจึงผ่าน",
        "ตีความเกณฑ์ตามตัวเลขตรงๆ ซึ่งผิด เพราะเกณฑ์ 10³ ยอมรับได้ถึง 2,000",
        "เกณฑ์ 10² ยอมรับได้ถึง 200 CFU/g ดังนั้น 150 ผ่าน",
        "ทั้งสองค่าอยู่ภายในเกณฑ์ที่ตีความตาม pharmacopoeia",
        "ไม่มีข้อกำหนดเรื่องอัตราส่วน TAMC/TYMC",
      ],
      k: "เกณฑ์จุลินทรีย์ 10ⁿ → ยอมรับได้สูงสุด 2 × 10ⁿ (10¹→20, 10²→200, 10³→2000)",
      d: "hard",
      ref: "USP <1111> Microbiological Examination of Nonsterile Products: Acceptance Criteria; Ph.Eur. 5.1.4",
    },
  ],
  // Mock Set 2
  [
    {
      t: "Elution order in reversed-phase HPLC",
      p: "วิเคราะห์สารผสม 3 ชนิดด้วย reversed-phase HPLC (C18, mobile phase methanol:water 60:40) ได้แก่ caffeine (log P ≈ −0.1), paracetamol (log P ≈ 0.5) และ ibuprofen (log P ≈ 4, ไอออไนซ์ถูกกดด้วย mobile phase pH 3) ลำดับการ elute ที่คาดว่าจะเกิดขึ้นคือข้อใด",
      o: [
        "Caffeine → paracetamol → ibuprofen",
        "Ibuprofen → paracetamol → caffeine",
        "Paracetamol → ibuprofen → caffeine",
        "Ibuprofen → caffeine → paracetamol",
        "ทั้งสามออกพร้อมกันเพราะ C18 แยกตามขนาดโมเลกุล",
      ],
      a: 0,
      r: "Reversed-phase ใช้ stationary phase ไม่มีขั้ว (C18) และ mobile phase มีขั้ว สารที่มีขั้วมาก (log P ต่ำ) ชอบอยู่ใน mobile phase จึง elute ก่อน ส่วนสาร lipophilic (log P สูง) ถูก retain นานกว่า\n\nเมื่อ pH 3 ต่ำกว่า pKa ของ ibuprofen (~4.4) โมเลกุลอยู่ในรูป unionized จึง hydrophobic มากและออกช้าสุด ส่วน caffeine กับ paracetamol log P ต่ำ ออกก่อนตามลำดับขั้ว ใน normal-phase ลำดับจะกลับกัน",
      w: [
        "ถูก — RP-HPLC: สารมีขั้วมาก (log P ต่ำ) ออกก่อน สาร lipophilic ออกหลัง",
        "เป็นลำดับของ normal-phase chromatography ซึ่งกลับกับ reversed-phase",
        "Ibuprofen lipophilic ที่สุด จึงไม่ควรออกก่อน caffeine",
        "ลำดับไม่สอดคล้องกับ log P",
        "C18 แยกตาม hydrophobicity ไม่ใช่ขนาดโมเลกุล (นั่นคือ size-exclusion)",
      ],
      k: "RP-HPLC: polar ออกก่อน, non-polar ออกหลัง; pH < pKa ของกรดอ่อน → unionized → retain นานขึ้น",
      d: "easy",
      ref: "Snyder, Kirkland & Dolan, Introduction to Modern Liquid Chromatography 3rd ed.; USP <621>",
    },
    {
      t: "Reference and retention sample requirements",
      p: "ตาม PIC/S GMP Annex 19 ข้อใดถูกต้องเกี่ยวกับ reference sample ของผลิตภัณฑ์สำเร็จรูป (finished product)",
      o: [
        "เก็บปริมาณเพียงพอสำหรับทดสอบตาม release specification ครบอย่างน้อย 2 ครั้ง และเก็บไว้อย่างน้อย 1 ปีหลังวันหมดอายุ",
        "เก็บปริมาณเพียงพอสำหรับทดสอบ 1 ครั้ง และเก็บจนถึงวันหมดอายุเท่านั้น",
        "เก็บเฉพาะ batch ที่มี deviation เท่านั้น",
        "เก็บไว้ 5 ปีหลัง release โดยไม่ขึ้นกับวันหมดอายุ",
        "อนุญาตให้เก็บในบรรจุภัณฑ์ใดก็ได้ที่สะดวกต่อการจัดเก็บ",
      ],
      a: 0,
      r: "Annex 19 แยก reference sample (ตัวอย่างสำหรับวิเคราะห์ภายหลังหากจำเป็น) และ retention sample (ผลิตภัณฑ์ในบรรจุภัณฑ์สุดท้ายเพื่อการระบุตัว เช่น ตรวจฉลาก/บรรจุภัณฑ์) โดยในทางปฏิบัติมักเป็นชุดเดียวกัน\n\nปริมาณ reference sample ต้องเพียงพอสำหรับการวิเคราะห์ตาม specification ครบอย่างน้อย 2 ครั้ง เก็บอย่างน้อย 1 ปีหลังวันหมดอายุ และควรเก็บในบรรจุภัณฑ์สุดท้าย (final pack) ภายใต้สภาวะตามฉลาก สำหรับ starting materials ทั่วไปเก็บอย่างน้อย 2 ปีหลังการ release ผลิตภัณฑ์",
      w: [
        "ถูก — ปริมาณพอสำหรับ full analysis ≥ 2 ครั้ง และเก็บ ≥ 1 ปีหลังวันหมดอายุ",
        "ปริมาณน้อยเกินไป และระยะเวลาสั้นกว่าที่กำหนด",
        "ต้องเก็บตัวอย่างทุก batch ไม่ใช่เฉพาะที่มี deviation",
        "ระยะเวลาผูกกับวันหมดอายุ (≥ 1 ปีหลังหมดอายุ)",
        "ควรเก็บในบรรจุภัณฑ์สุดท้ายเพื่อสะท้อนสภาพจริงของผลิตภัณฑ์",
      ],
      k: "Reference sample (FP): พอทดสอบครบ ≥ 2 ครั้ง, เก็บ ≥ 1 ปีหลังหมดอายุ, ใน final pack",
      d: "easy",
      ref: "PIC/S GMP Guide PE 009 Annex 19 Reference and Retention Samples",
    },
    {
      t: "HPLC theoretical plates from half-height width",
      p: "ใน system suitability test ของ HPLC assay ได้ peak หลักที่ tR = 8.40 min และ width at half height (W0.5) = 0.14 min จำนวน theoretical plates (N) ของคอลัมน์ต่อ peak นี้ใกล้เคียงค่าใดที่สุด",
      o: ["3,600", "9,970", "14,400", "19,900", "57,600"],
      a: 3,
      r: "Column efficiency แสดงด้วย N ซึ่งคำนวณได้ 2 แบบ: N = 16(tR/Wb)² เมื่อใช้ baseline (tangent) width หรือ N = 5.54(tR/W0.5)² เมื่อใช้ width at half height\n\ntR/W0.5 = 8.40/0.14 = 60 → N = 5.54 × 3,600 = 19,944 ≈ 19,900 plates N สูงหมายถึง peak แคบ ใช้เป็นเกณฑ์ SST เพื่อยืนยันว่าคอลัมน์ยังมีประสิทธิภาพ (เช่น N ≥ 2,000) ค่า N ลดลงเรื่อยๆ บ่งชี้คอลัมน์เสื่อม void หรือ dead volume ในระบบ",
      w: [
        "เป็นเพียง (tR/W0.5)² โดยไม่คูณ 5.54",
        "ประมาณครึ่งหนึ่งของค่าที่ถูกต้อง ไม่ตรงสูตร",
        "เป็น 4 × 3,600 ไม่ใช่สูตรมาตรฐาน",
        "ถูก — N = 5.54 × (8.40/0.14)² = 5.54 × 3,600 ≈ 19,900",
        "ใช้สูตร 16(tR/W)² กับ width at half height ซึ่งผิด (16 ใช้กับ baseline width)",
      ],
      k: "N = 16(tR/Wb)² หรือ 5.54(tR/W0.5)² — เลือกค่าคงที่ให้ตรงกับชนิดของ width",
      d: "medium",
      ref: "USP <621> Chromatography (System Suitability); Ph.Eur. 2.2.46",
      c: ["tR/W0.5 = 8.40/0.14 = 60", "(60)² = 3,600", "N = 5.54 × 3,600 = 19,944 ≈ 19,900"],
    },
    {
      t: "Complexometric EDTA assay with molarity factor",
      p: "Assay zinc oxide: ชั่งตัวอย่าง 0.1500 g ละลายใน dilute HCl ปรับ pH ด้วย ammonia–ammonium chloride buffer ใช้ eriochrome black T เป็น indicator ไทเทรตด้วย 0.05 M disodium edetate (factor = 0.996) ใช้ไป 36.20 mL กำหนด 1 mL ของ 0.05 M EDTA ≡ 4.069 mg ZnO ความบริสุทธิ์ของ ZnO เป็นเท่าใด",
      o: ["48.9%", "96.5%", "97.8%", "98.2%", "195.6%"],
      a: 2,
      r: "EDTA ทำ complex กับ metal ion ส่วนใหญ่ในอัตรา 1:1 เสมอ (ไม่ขึ้นกับประจุของโลหะ) ดังนั้น equivalence factor ของ ZnO = MW × M = 81.38 × 0.05 = 4.069 mg/mL\n\nปริมาณ ZnO = V × factor × equivalence = 36.20 × 0.996 × 4.069 = 146.71 mg จากตัวอย่าง 150.0 mg = 97.8%\n\nBuffer pH ~10 จำเป็นเพราะ stability ของ metal–EDTA complex และการเปลี่ยนสีของ eriochrome black T ขึ้นกับ pH (สีแดงม่วงของ Zn–indicator → สีน้ำเงินของ free indicator ที่ end point)",
      w: [
        "เป็นผลจากการคิด stoichiometry เป็น 2:1 (EDTA:Zn) ซึ่งผิด",
        "ค่าต่ำเกินไป ไม่สอดคล้องกับการคำนวณ",
        "ถูก — 36.20 × 0.996 × 4.069 = 146.71 mg ÷ 150.0 mg = 97.8%",
        "เป็นผลจากการลืมคูณ factor 0.996 ของ titrant",
        "เป็นผลจากการคิดว่า 1 mol EDTA ทำปฏิกิริยากับ 2 mol Zn ซึ่งผิด",
      ],
      k: "EDTA : metal = 1 : 1 เสมอ; mg สาร = V × f × (MW × M); ต้องคุม pH ด้วย buffer",
      d: "medium",
      ref: "BP monograph Zinc Oxide; Beckett & Stenlake, Practical Pharmaceutical Chemistry Part 1 (Complexometric titrations)",
      c: [
        "Equivalence: 1 mL 0.05 M EDTA ≡ 81.38 × 0.05 = 4.069 mg ZnO",
        "ZnO = 36.20 × 0.996 × 4.069 = 146.71 mg",
        "% purity = 146.71 / 150.0 × 100 = 97.8%",
      ],
    },
    {
      t: "HPLC detector for non-chromophoric analytes",
      p: "ห้อง QC ต้องพัฒนาวิธี HPLC สำหรับ related substances ของสารกลุ่ม aminoglycoside ซึ่งไม่มี chromophore และต้องใช้ gradient elution เพื่อแยก impurities หลายตัว detector ใดเหมาะสมที่สุด",
      o: [
        "Charged aerosol detector (CAD) หรือ evaporative light scattering detector (ELSD)",
        "Refractive index (RI) detector",
        "UV detector ที่ 254 nm",
        "Fluorescence detector โดยไม่ต้อง derivatize",
        "Photodiode array (PDA) detector ที่ 280 nm",
      ],
      a: 0,
      r: "สารไม่มี chromophore (เช่น aminoglycosides, sugars, lipids บางชนิด) ตอบสนองต่อ UV ได้น้อยมาก ทางเลือกคือ universal detectors หรือ derivatization\n\nRI detector ตอบสนองต่อการเปลี่ยน refractive index ของ mobile phase จึงใช้ได้เฉพาะ isocratic elution และมี sensitivity ต่ำ ส่วน ELSD/CAD เป็น aerosol-based detectors ที่ระเหย mobile phase ออกก่อนตรวจวัดอนุภาคสาร จึงใช้กับ gradient ได้ (ต้องใช้ volatile mobile phase/buffer เช่น ammonium formate หรือ TFA) และมี sensitivity ดีกว่า RI นอกจากนี้ยังมีทางเลือก pulsed amperometric detection (PAD) หรือ MS",
      w: [
        "ถูก — CAD/ELSD เป็น universal detector ที่ใช้กับ gradient ได้ เหมาะกับสารไม่มี chromophore",
        "RI ไม่เหมาะกับ gradient เพราะ baseline เปลี่ยนตามองค์ประกอบ mobile phase และ sensitivity ต่ำ",
        "สารไม่มี chromophore จึงแทบไม่ดูดกลืนแสง UV ที่ 254 nm",
        "Fluorescence ต้องมี fluorophore หรือต้อง derivatize ก่อน",
        "PDA ยังเป็น UV detection ซึ่งไม่ช่วยถ้าสารไม่ดูดกลืนแสง",
      ],
      k: "ไม่มี chromophore + gradient → CAD/ELSD (volatile buffer); RI ใช้ได้เฉพาะ isocratic",
      d: "medium",
      ref: "USP <621> Chromatography; Snyder, Kirkland & Dolan, Introduction to Modern Liquid Chromatography 3rd ed. Ch.4",
    },
    {
      t: "Static headspace GC for residual solvents",
      p: "ตาม USP <467> การวิเคราะห์ residual solvents ในยาเม็ดมักใช้ static headspace GC ร่วมกับ FID เหตุผลหลักของการใช้ headspace sampling แทนการฉีดสารละลายตัวอย่างโดยตรงคือข้อใด",
      o: [
        "ฉีดเฉพาะไอระเหยของ solvent เข้าคอลัมน์ ป้องกัน non-volatile matrix ปนเปื้อน inlet และคอลัมน์ ลด interference",
        "ทำให้วัดสารที่ไม่ระเหยได้ดีขึ้น เช่น excipients",
        "ทำให้ไม่ต้องใช้ reference standard ในการวัด",
        "เพิ่มความไวต่อ water มากกว่า Karl Fischer",
        "ทำให้ไม่ต้องควบคุมอุณหภูมิของ vial",
      ],
      a: 0,
      r: "Static headspace: ตัวอย่างละลายใน diluent ที่เหมาะสม (เช่น น้ำ หรือ DMSO/DMF สำหรับตัวอย่างไม่ละลายน้ำ) ปิดใน vial แล้ว equilibrate ที่อุณหภูมิคงที่ ไอระเหยของ solvent ใน gas phase ถูกเก็บไปฉีดเข้า GC\n\nข้อดี: matrix ที่ไม่ระเหย (API, excipients) ไม่เข้าระบบ จึงไม่สะสมที่ liner/คอลัมน์ ลด ghost peaks และ interference ผลขึ้นกับ partition ระหว่าง liquid–gas จึงต้องควบคุมอุณหภูมิ เวลา equilibration และ matrix ให้เหมือนกันระหว่าง standard และ sample USP <467> ใช้ G43 (6% cyanopropylphenyl-94% dimethylpolysiloxane) เป็นหลักใน Procedure A และ G16 (PEG) ใน Procedure B",
      w: [
        "ถูก — headspace นำเฉพาะสารระเหยเข้าคอลัมน์ ป้องกันการปนเปื้อนจาก matrix ที่ไม่ระเหย",
        "Headspace ใช้วัดสารระเหย ไม่ใช่ excipients ที่ไม่ระเหย",
        "ยังต้องใช้ reference standard ของ solvent เพื่อเปรียบเทียบเสมอ",
        "การวัดน้ำใช้ Karl Fischer หรือ LOD ไม่ใช่ headspace GC-FID (FID ไม่ตอบสนองต่อน้ำ)",
        "อุณหภูมิ vial มีผลโดยตรงต่อ partition จึงต้องควบคุมอย่างเข้มงวด",
      ],
      k: "Residual solvents: static headspace GC-FID (USP <467>) — เฉพาะไอระเหยเข้าคอลัมน์; ต้องคุมอุณหภูมิ/เวลา equilibration",
      d: "medium",
      ref: "USP <467> Residual Solvents; Ph.Eur. 2.4.24",
    },
    {
      t: "Robustness vs intermediate precision",
      p: "ระหว่าง method validation ของ HPLC assay ทีมได้ทดลองเปลี่ยน column temperature ±5 °C, mobile phase pH ±0.2 และ flow rate ±10% โดยตั้งใจ แล้วดูผลต่อ resolution และ assay การศึกษานี้คือ validation characteristic ใดตาม ICH Q2(R2)/Q14",
      o: [
        "Robustness",
        "Intermediate precision",
        "Reproducibility",
        "Repeatability",
        "Specificity",
      ],
      a: 0,
      r: "Robustness คือความสามารถของวิธีที่ไม่ได้รับผลกระทบจากการเปลี่ยนแปลงเล็กน้อยของ method parameters โดยตั้งใจ (deliberate variations) เช่น pH, อุณหภูมิ, flow rate, องค์ประกอบ mobile phase, lot ของคอลัมน์ ใน ICH Q2(R2)/Q14 แนะนำให้ประเมินในช่วง development และใช้ผลเพื่อกำหนด system suitability และ method operable ranges\n\nIntermediate precision คือความแปรปรวนภายในห้องปฏิบัติการเดียวกันจาก 'ปัจจัยตามธรรมชาติ' เช่น ต่างวัน ต่างนักวิเคราะห์ ต่างเครื่อง ส่วน reproducibility คือระหว่างห้องปฏิบัติการ",
      w: [
        "ถูก — การเปลี่ยน method parameters เล็กน้อยโดยตั้งใจคือ robustness",
        "Intermediate precision ศึกษาต่างวัน/นักวิเคราะห์/เครื่องมือ ไม่ใช่การเปลี่ยน parameter ของวิธีโดยตั้งใจ",
        "Reproducibility เป็นความแม่นยำระหว่างห้องปฏิบัติการ (collaborative study)",
        "Repeatability คือการวัดซ้ำภายใต้สภาวะเดียวกันในเวลาสั้น",
        "Specificity คือความสามารถในการวัดสารที่สนใจท่ามกลางสารอื่น",
      ],
      k: "Robustness = deliberate small changes ของ method parameter; intermediate precision = ต่างวัน/คน/เครื่อง ใน lab เดียว",
      d: "medium",
      ref: "ICH Q2(R2) Validation of Analytical Procedures; ICH Q14 Analytical Procedure Development",
    },
    {
      t: "OOS retesting rules and testing into compliance",
      p: "ผล impurity C ได้ 0.28% (spec ≤ 0.20%) Phase I ไม่พบ assignable laboratory error ผู้จัดการ QC เสนอให้ทดสอบซ้ำไปเรื่อยๆ จนได้ผลผ่าน 2 ครั้งติดกันแล้ว release batch ข้อใดเป็นแนวปฏิบัติที่ถูกต้องตาม FDA OOS guidance",
      o: [
        "Retest ต้องทำตามแผนที่กำหนดล่วงหน้าใน SOP (จำนวนครั้งระบุไว้) โดยใช้ตัวอย่างเดิม ควรให้นักวิเคราะห์คนอื่นทำ และต้องประเมินผลทั้งหมดรวมผล OOS เดิมในการตัดสิน",
        "ทดสอบซ้ำจนได้ผลผ่านแล้วรายงานเฉพาะผลที่ผ่าน",
        "เก็บตัวอย่างใหม่จาก batch แล้วรายงานผลใหม่แทนผลเดิมทันที",
        "เฉลี่ยผล 0.28% กับผล retest ที่ได้ 0.12% แล้วรายงานค่าเฉลี่ย 0.20% ว่าผ่าน",
        "ใช้ outlier test เพื่อตัดผล 0.28% ออก",
      ],
      a: 0,
      r: "FDA ห้าม 'testing into compliance' คือการทดสอบซ้ำจนได้ผลที่ต้องการ การ retest ต้องมีเหตุผลทางวิทยาศาสตร์ กำหนดจำนวนครั้งไว้ล่วงหน้าใน SOP (ไม่ขึ้นกับผลที่ได้) ใช้ portion ใหม่จากตัวอย่างเดิม (same homogeneous sample) และควรทำโดยนักวิเคราะห์คนอื่นที่มีประสบการณ์\n\nเมื่อไม่พบ assignable lab cause ผล OOS เดิมไม่สามารถ invalidate ได้ ต้องเข้าสู่ Phase II (full-scale investigation รวมการผลิต) และการตัดสิน batch ต้องพิจารณาผลทั้งหมด ไม่ใช่เฉพาะผลที่ผ่าน การเฉลี่ยผลที่ทำให้ OOS ถูกซ่อน และการใช้ outlier test กับการทดสอบทางเคมีไม่เป็นที่ยอมรับ",
      w: [
        "ถูก — retest ตามแผนล่วงหน้า ใช้ตัวอย่างเดิม นักวิเคราะห์อีกคน และประเมินผลทั้งหมด",
        "เป็น testing into compliance ที่ FDA ห้ามโดยตรง",
        "Resampling ทำได้เฉพาะเมื่อมีหลักฐานว่าตัวอย่างเดิมไม่ representative/เตรียมผิด และผลเดิมต้องไม่ถูกแทนที่",
        "การเฉลี่ยเพื่อซ่อนผล OOS ไม่ยอมรับ โดยเฉพาะ impurity ซึ่งต้องดูผลรายตัว",
        "Outlier test ไม่ใช้กับ chemical assay ที่ precise ตาม FDA guidance (ใช้ได้บางกรณีใน bioassay)",
      ],
      k: "Retest: จำนวนกำหนดล่วงหน้า + ตัวอย่างเดิม + analyst อื่น + ประเมินทุกผล; ห้าม testing into compliance",
      d: "hard",
      ref: "FDA Guidance for Industry: Investigating OOS Test Results for Pharmaceutical Production (2006, rev. 2022)",
    },
    {
      t: "ICH Q3C Option 2 limit calculation",
      p: "ยาแคปซูลชนิดหนึ่งมี daily dose รวม 2.0 g/day ใช้ acetonitrile (Class 2, PDE = 4.1 mg/day, Option 1 limit = 410 ppm) ในการผลิต หากใช้ Option 2 ตาม ICH Q3C ปริมาณ acetonitrile สูงสุดที่ยอมรับได้ในผลิตภัณฑ์คือเท่าใด",
      o: ["205 ppm", "410 ppm", "820 ppm", "2,050 ppm", "8,200 ppm"],
      a: 3,
      r: "Option 1 คำนวณจาก daily dose สมมติ 10 g: Concentration (ppm) = 1000 × PDE / dose = 1000 × 4.1/10 = 410 ppm ใช้ได้กับทุกส่วนประกอบโดยไม่ต้องคำนวณเพิ่ม\n\nOption 2 ใช้ daily dose จริงของผลิตภัณฑ์: 1000 × 4.1 / 2.0 = 2,050 ppm (เทียบเท่า 4.1 mg/day เมื่อรับ 2 g/day) โดยต้องแสดงว่าผลรวมจากทุกส่วนประกอบในผลิตภัณฑ์ไม่เกิน PDE เมื่อ dose < 10 g/day Option 2 จะให้ limit ที่สูงกว่า Option 1 เสมอ",
      w: [
        "เป็นผลจากคูณ dose แทนการหาร หรือใช้ dose 20 g ซึ่งผิด",
        "เป็น Option 1 limit (สมมติ dose 10 g/day) ไม่ใช่ Option 2",
        "ค่าไม่สอดคล้องกับสูตร 1000 × PDE / dose",
        "ถูก — 1000 × 4.1 mg/day ÷ 2.0 g/day = 2,050 ppm",
        "เป็นผลจากใช้ dose 0.5 g หรือผิดหลักทศนิยม",
      ],
      k: "ppm = 1000 × PDE (mg/day) / dose (g/day); Option 1 ใช้ 10 g, Option 2 ใช้ dose จริง",
      d: "hard",
      ref: "ICH Q3C(R9) Impurities: Guideline for Residual Solvents (Options for describing limits of Class 2 solvents)",
      c: [
        "Option 2: ppm = 1000 × PDE / dose",
        "= 1000 × 4.1 / 2.0",
        "= 2,050 ppm",
      ],
    },
    {
      t: "Volhard back titration of chloride",
      p: "Assay sodium chloride ด้วยวิธี Volhard: เติม 0.1 M silver nitrate มากเกินพอ แล้วไทเทรตย้อน (back titration) ส่วนเกินด้วย 0.1 M ammonium thiocyanate โดยใช้ ferric ammonium sulfate เป็น indicator ในวิธีนี้ทำไมจึงต้องกรอง AgCl ออกหรือเติม dibutyl phthalate/nitrobenzene ก่อนไทเทรตย้อน",
      o: [
        "AgCl ละลายได้มากกว่า AgSCN จึงทำปฏิกิริยากับ thiocyanate ทำให้ใช้ titrant มากเกินและผล chloride ต่ำกว่าความจริง",
        "AgCl เป็นสาร indicator จึงต้องแยกออกเพื่อไม่ให้เปลี่ยนสีก่อน end point",
        "AgCl ทำปฏิกิริยากับ ferric ion ให้ตะกอนสีแดง",
        "เพื่อเพิ่ม pH ของสารละลายให้เป็นด่างตามที่ indicator ต้องการ",
        "เพราะ AgCl ดูดซับ silver nitrate ทำให้ผล chloride สูงกว่าความจริง",
      ],
      a: 0,
      r: "Volhard เป็น argentometric back titration ในสภาวะกรด (HNO₃) Cl⁻ + Ag⁺ (excess) → AgCl↓ แล้ว Ag⁺ ส่วนเกิน + SCN⁻ → AgSCN↓ เมื่อ Ag⁺ หมด SCN⁻ ส่วนเกินจับ Fe³⁺ ให้สีแดง [Fe(SCN)]²⁺ เป็น end point\n\nเนื่องจาก Ksp ของ AgCl (~1.8 × 10⁻¹⁰) มากกว่า AgSCN (~1 × 10⁻¹²) AgCl จะค่อยๆ เปลี่ยนเป็น AgSCN เมื่อมี SCN⁻ ทำให้ใช้ thiocyanate มากขึ้น → คำนวณ Ag⁺ ส่วนเกินสูงเกินจริง → chloride ต่ำเกินจริง แก้โดยกรอง AgCl หรือเคลือบตะกอนด้วย dibutyl phthalate/nitrobenzene ปัญหานี้ไม่เกิดกับ bromide/iodide เพราะ AgBr, AgI ละลายน้อยกว่า AgSCN",
      w: [
        "ถูก — AgCl ละลายได้มากกว่า AgSCN จึงถูกแทนที่ด้วย SCN⁻ ทำให้ผล chloride ต่ำเกินจริง",
        "Indicator คือ Fe³⁺ (ferric ammonium sulfate) ไม่ใช่ AgCl",
        "Fe³⁺ ให้สีแดงกับ SCN⁻ ไม่ใช่กับ AgCl",
        "Volhard ทำในสภาวะกรด (HNO₃) เพื่อป้องกัน Fe³⁺ ตกตะกอนเป็น hydroxide",
        "ปัญหาคือผลต่ำเกินจริงจากการแลกเปลี่ยนเป็น AgSCN ไม่ใช่ผลสูงจากการดูดซับ",
      ],
      k: "Volhard: back titration ด้วย SCN⁻ ในกรด, indicator Fe³⁺; สำหรับ Cl⁻ ต้องกรอง AgCl หรือเคลือบด้วย dibutyl phthalate",
      d: "hard",
      ref: "Beckett & Stenlake, Practical Pharmaceutical Chemistry Part 1 (Argentimetric titrations); Skoog, Fundamentals of Analytical Chemistry",
    },
  ],
];
