import type { Ip1MockDomainContent } from "@/lib/ip1-mock/types";

export const BIOPHARM: Ip1MockDomainContent = [
  // Mock Set 1
  [
    {
      t: "Passive diffusion characteristics",
      p: "ยา X ซึ่งเป็นโมเลกุลขนาดเล็ก lipophilic ไม่แตกตัวที่ pH ลำไส้ ถูกดูดซึมผ่านเยื่อบุลำไส้ด้วย passive transcellular diffusion เป็นหลัก ข้อใดเป็นลักษณะของกลไกนี้",
      o: [
        "อัตราการดูดซึมแปรผันตรงกับ concentration gradient และไม่อิ่มตัวเมื่อเพิ่มขนาดยา",
        "อัตราการดูดซึมคงที่เมื่อขนาดยาสูง เพราะ carrier อิ่มตัว",
        "ต้องใช้พลังงานจาก ATP และเคลื่อนที่สวน concentration gradient ได้",
        "ถูกยับยั้งแบบแข่งขันได้ด้วยสารที่มีโครงสร้างคล้ายกัน",
        "เกิดเฉพาะบริเวณ upper small intestine ที่มี transporter เฉพาะ (absorption window)",
      ],
      a: 0,
      r: "Passive diffusion อธิบายด้วย Fick's first law: อัตราการผ่านเยื่อ (dM/dt) = D·A·K·(C_gut − C_blood)/h ซึ่งขึ้นกับ diffusion coefficient, พื้นที่ผิว, partition coefficient และความหนาของเยื่อ โดยแรงขับคือ concentration gradient เท่านั้น\n\nเนื่องจากไม่มี carrier จึงไม่มีจุดอิ่มตัว (linear kinetics) ไม่ต้องใช้พลังงาน ไม่เกิด competitive inhibition และไม่จำกัดเฉพาะบริเวณใดของลำไส้ ยาส่วนใหญ่ (โดยเฉพาะ BCS class I/II) ถูกดูดซึมด้วยกลไกนี้ ดังนั้นปริมาณที่ถูกดูดซึมจึงเพิ่มตามขนาดยาแบบเป็นสัดส่วน",
      w: [
        "ถูก — passive diffusion ขับเคลื่อนด้วย concentration gradient ตาม Fick's law จึงเป็น first-order และไม่อิ่มตัว",
        "การอิ่มตัว (saturable, Michaelis–Menten) เป็นลักษณะของ carrier-mediated transport ไม่ใช่ passive diffusion",
        "การใช้พลังงานและสวน gradient คือ active transport (เช่น ผ่าน ABC transporter หรือ secondary active) ไม่ใช่ passive",
        "Competitive inhibition เกิดเมื่อสารแย่งจับ carrier ตัวเดียวกัน passive diffusion ไม่มีจุดจับจึงไม่เกิด",
        "Absorption window มักเกิดกับยาที่อาศัย transporter ที่มีการกระจายเฉพาะที่ เช่น riboflavin ไม่ใช่ลักษณะของ passive diffusion",
      ],
      k: "Passive diffusion = Fick's law, ตาม gradient, ไม่อิ่มตัว, ไม่ใช้พลังงาน, ไม่มี competitive inhibition",
      d: "easy",
      ref: "Shargel & Yu, Applied Biopharmaceutics & Pharmacokinetics 7th ed., Ch.13",
    },
    {
      t: "P-glycoprotein efflux interaction",
      p: "ผู้ป่วยรับประทาน digoxin ขนาดคงที่มานาน ต่อมาแพทย์เริ่มให้ verapamil ร่วมด้วย พบระดับ digoxin ในเลือดสูงขึ้นชัดเจน ทั้งที่ digoxin แทบไม่ถูก metabolize ด้วย CYP กลไกหลักทาง biopharmaceutics ที่อธิบายได้ดีที่สุดคือข้อใด",
      o: [
        "Verapamil ยับยั้ง P-glycoprotein ที่ apical membrane ของ enterocyte และที่ไต ทำให้ efflux และการขับ digoxin ลดลง",
        "Verapamil เหนี่ยวนำ P-glycoprotein ทำให้ digoxin ถูกดูดซึมกลับมากขึ้น",
        "Verapamil ยับยั้ง CYP3A4 ใน hepatocyte ทำให้ hepatic first-pass ของ digoxin ลดลง",
        "Verapamil เพิ่ม gastric pH ทำให้ digoxin ละลายได้ดีขึ้น",
        "Verapamil ทำให้เกิด complex กับ digoxin ในลำไส้และเพิ่ม permeability",
      ],
      a: 0,
      r: "P-glycoprotein (P-gp, ABCB1) เป็น ATP-dependent efflux transporter อยู่ที่ apical (luminal) membrane ของ enterocyte, canalicular membrane ของ hepatocyte และ proximal tubule ของไต ทำหน้าที่ปั๊มยากลับออกสู่ลำไส้ น้ำดี และปัสสาวะ\n\nDigoxin เป็น P-gp substrate ที่ไม่ค่อยถูก metabolize ดังนั้นปฏิกิริยาที่เพิ่มระดับ digoxin จาก verapamil, quinidine, amiodarone หรือ clarithromycin จึงเกิดจากการยับยั้ง P-gp เป็นหลัก ทั้งที่ลำไส้ (fraction absorbed เพิ่มขึ้น) และที่ไต (renal secretion ลดลง) ในทางกลับกัน P-gp inducer เช่น rifampicin หรือ St John's wort จะลดระดับ digoxin",
      w: [
        "ถูก — การยับยั้ง P-gp ทั้งที่ลำไส้และ tubule ของไตเพิ่ม bioavailability และลดการขับ digoxin",
        "การ induce P-gp จะเพิ่ม efflux ทำให้ระดับยาลดลง ไม่ใช่เพิ่มขึ้น",
        "Digoxin แทบไม่ผ่าน CYP3A4 ดังนั้นการยับยั้ง CYP3A4 ไม่ใช่กลไกหลักในกรณีนี้",
        "Verapamil ไม่มีผลเพิ่ม gastric pH อย่างมีนัยสำคัญ และ digoxin ไม่ใช่ยาที่การละลายขึ้นกับ pH",
        "ไม่มีหลักฐานการเกิด complex ระหว่าง verapamil กับ digoxin และ complexation มักลดการดูดซึมมากกว่าเพิ่ม",
      ],
      k: "Digoxin เป็น probe substrate ของ P-gp; P-gp inhibitor (verapamil, quinidine, clarithromycin) เพิ่มระดับ digoxin",
      d: "medium",
      ref: "FDA Guidance: In Vitro Drug Interaction Studies — Cytochrome P450 Enzyme- and Transporter-Mediated Drug Interactions (2020)",
    },
    {
      t: "BCS solubility across pH range",
      p: "ยา Y มีขนาดยาสูงสุดต่อครั้ง (highest single therapeutic dose) 400 mg ผลการหา equilibrium solubility ที่ 37 °C เป็นดังนี้: pH 1.2 = 8.0 mg/mL, pH 4.5 = 2.5 mg/mL, pH 6.8 = 1.2 mg/mL ตามเกณฑ์ ICH M9 ข้อใดสรุปได้ถูกต้อง",
      o: [
        "Low solubility เพราะที่ pH 6.8 ต้องใช้ตัวทำละลายประมาณ 333 mL ซึ่งเกิน 250 mL",
        "High solubility เพราะที่ pH 1.2 ต้องใช้ตัวทำละลายเพียง 50 mL",
        "High solubility เพราะค่าเฉลี่ยของ solubility ทั้งสาม pH สูงกว่า 1 mg/mL",
        "Low solubility เพราะ solubility ที่ pH 4.5 ต่ำกว่า 5 mg/mL",
        "สรุปไม่ได้ เพราะ ICH M9 ใช้ปริมาตรอ้างอิง 900 mL ตามปริมาตร dissolution vessel",
      ],
      a: 0,
      r: "ICH M9 นิยาม high solubility ว่า highest single therapeutic dose ต้องละลายได้หมดในตัวทำละลาย ≤ 250 mL ตลอดช่วง pH 1.2–6.8 ที่ 37 ± 1 °C ดังนั้นต้องใช้ค่า solubility ที่ต่ำที่สุดในช่วง pH ที่ทดสอบมาตัดสิน\n\nปริมาตรที่ต้องใช้ (dose/solubility) ที่ pH 1.2 = 400/8.0 = 50 mL, pH 4.5 = 400/2.5 = 160 mL และ pH 6.8 = 400/1.2 ≈ 333 mL เนื่องจากที่ pH 6.8 ต้องใช้มากกว่า 250 mL ยา Y จึงเป็น low solubility (ยาที่เป็น weak base มักมีปัญหาที่ pH สูงแบบนี้) ค่า 250 mL มาจากน้ำประมาณ 1 แก้ว (8 ออนซ์) ที่ใช้รับประทานยาใน BE study",
      w: [
        "ถูก — ใช้ pH ที่ solubility ต่ำที่สุด: 400/1.2 ≈ 333 mL > 250 mL จึงเป็น low solubility",
        "ต้องผ่านทุก pH ในช่วง 1.2–6.8 การดูเฉพาะ pH ที่ละลายดีที่สุดเป็นการตัดสินที่ผิด",
        "เกณฑ์ไม่ได้ใช้ค่าเฉลี่ยของ solubility แต่ใช้ปริมาตรที่ต้องใช้ละลาย dose ที่ pH เลวร้ายที่สุด",
        "ไม่มีเกณฑ์ solubility 5 mg/mL ใน BCS และที่ pH 4.5 ใช้เพียง 160 mL ซึ่งยังผ่าน",
        "ปริมาตรอ้างอิงของ BCS คือ 250 mL ไม่ใช่ 900 mL ของ dissolution vessel",
      ],
      k: "BCS high solubility: dose สูงสุดละลายใน ≤ 250 mL ทุก pH 1.2–6.8 (37 °C) ตัดสินจาก pH ที่ละลายแย่ที่สุด",
      d: "medium",
      ref: "ICH M9 Biopharmaceutics Classification System-based Biowaivers (2019), Section 2.1.1",
      c: [
        "Volume ที่ pH 1.2 = 400 mg ÷ 8.0 mg/mL = 50 mL",
        "Volume ที่ pH 4.5 = 400 ÷ 2.5 = 160 mL",
        "Volume ที่ pH 6.8 = 400 ÷ 1.2 ≈ 333 mL > 250 mL → low solubility",
      ],
    },
    {
      t: "USP 711 stage S1 decision",
      p: "ยาเม็ด immediate-release มี monograph กำหนด Q = 80% ใน 30 นาที ผล dissolution Stage S1 (6 เม็ด) ได้ 92, 88, 86, 90, 84 และ 95% ของ label claim ข้อใดเป็นการตัดสินที่ถูกต้องตาม USP <711>",
      o: [
        "ยังไม่ผ่าน S1 เพราะมี 1 เม็ดต่ำกว่า Q + 5% (85%) ต้องทดสอบต่อ Stage S2 อีก 6 เม็ด",
        "ผ่าน S1 เพราะทุกเม็ดมากกว่า Q (80%)",
        "ผ่าน S1 เพราะค่าเฉลี่ย 89.2% มากกว่า Q + 5%",
        "ไม่ผ่านทันที (reject batch) เพราะมีเม็ดต่ำกว่า Q + 5%",
        "ต้องทดสอบซ้ำ S1 ใหม่ทั้ง 6 เม็ด แล้วใช้ผลชุดใหม่แทน",
      ],
      a: 0,
      r: "USP <711> สำหรับ immediate-release กำหนดการทดสอบเป็นขั้น: S1 ทดสอบ 6 หน่วย เกณฑ์คือ 'แต่ละหน่วย ≥ Q + 5%' หากไม่ผ่านจึงไป S2 (เพิ่ม 6 หน่วยรวม 12; ค่าเฉลี่ย ≥ Q และไม่มีหน่วยใด < Q − 15%) และ S3 (เพิ่ม 12 รวม 24)\n\nในกรณีนี้ Q + 5% = 85% มีเม็ดหนึ่งได้ 84% จึงไม่ผ่าน S1 แต่ไม่ได้หมายความว่า batch ไม่ผ่าน ต้องทำ S2 ต่อ ค่าเฉลี่ยไม่ใช่เกณฑ์ของ S1 และการทดสอบซ้ำแทนผลเดิมถือเป็น testing into compliance ซึ่งไม่ยอมรับใน GMP",
      w: [
        "ถูก — S1 ต้องทุกหน่วย ≥ Q + 5% = 85%; มี 84% จึงต้องต่อ S2",
        "เกณฑ์ S1 ไม่ใช่ ≥ Q แต่เป็น ≥ Q + 5% สำหรับทุกหน่วย",
        "S1 ไม่ได้ใช้ค่าเฉลี่ย ค่าเฉลี่ยเป็นเกณฑ์ของ S2 และ S3",
        "การไม่ผ่าน S1 ไม่ใช่ความล้มเหลวของ batch แต่เป็นการเลื่อนไปทดสอบขั้นถัดไปตามแผน acceptance table",
        "การทดสอบซ้ำเพื่อแทนผลเดิมโดยไม่มีเหตุ invalidation คือ testing into compliance ซึ่งยอมรับไม่ได้",
      ],
      k: "USP <711> IR: S1 = 6 หน่วย ทุกหน่วย ≥ Q+5%; ไม่ผ่านให้ไป S2 ไม่ใช่ reject",
      d: "easy",
      ref: "USP <711> Dissolution, Acceptance Table 1",
    },
    {
      t: "USP Apparatus 4 flow-through selection",
      p: "ทีม R&D พัฒนาวิธี dissolution ของยาเม็ดที่ API ละลายน้ำได้ต่ำมาก (practically insoluble) ใน paddle 900 mL ไม่สามารถรักษา sink condition ได้แม้เติม surfactant ในระดับที่ยอมรับได้ และต้องการเปลี่ยน pH ของ medium ระหว่างการทดสอบได้ง่าย อุปกรณ์ USP ใดเหมาะสมที่สุด",
      o: [
        "Apparatus 4 (flow-through cell) แบบ open-loop ที่ปั๊ม medium ใหม่ผ่าน cell ตลอดเวลา",
        "Apparatus 1 (basket) ที่ 100 rpm ใน 900 mL",
        "Apparatus 5 (paddle over disk)",
        "Apparatus 6 (rotating cylinder)",
        "Apparatus 2 (paddle) ที่ลดปริมาตรเป็น 500 mL",
      ],
      a: 0,
      r: "USP Apparatus 4 (flow-through cell) ให้ medium ไหลผ่าน cell ที่บรรจุตัวอย่างอย่างต่อเนื่อง ในแบบ open-loop จะใช้ medium ใหม่ตลอด จึงรักษา sink condition ได้แม้ยาละลายน้อยมาก และสามารถเปลี่ยน medium (เช่น pH gradient) ได้ระหว่างการทดสอบ เหมาะกับยาละลายยาก, powders/granules, implants, suppositories และ microspheres\n\nApparatus 1/2 เป็นระบบปริมาตรคงที่ (closed vessel) การลดปริมาตรยิ่งทำให้ sink แย่ลง ส่วน Apparatus 5 และ 6 ออกแบบมาสำหรับ transdermal delivery systems",
      w: [
        "ถูก — flow-through cell แบบ open-loop ให้ medium ใหม่ต่อเนื่อง จึงรักษา sink และเปลี่ยน pH ได้สะดวก",
        "Basket ยังเป็น vessel ปริมาตรคงที่ 900 mL จึงไม่แก้ปัญหา sink ของยาที่ละลายยากมาก",
        "Paddle over disk ใช้สำหรับ transdermal patch ไม่ใช่ยาเม็ดรับประทาน",
        "Rotating cylinder ใช้สำหรับ transdermal patch เช่นกัน",
        "การลดปริมาตร medium ยิ่งทำให้ความเข้มข้นเข้าใกล้ saturation มากขึ้น ทำให้ sink condition แย่ลง",
      ],
      k: "App 4 flow-through (open-loop) = ยาละลายยากมาก/ต้องการ sink ไม่จำกัด/เปลี่ยน pH ได้; App 5, 6 = transdermal",
      d: "medium",
      ref: "USP <711> Dissolution; USP <1092> The Dissolution Procedure: Development and Validation",
    },
    {
      t: "f2 similarity factor calculation",
      p: "เปรียบเทียบ dissolution profile ของ test กับ reference (n = 12, CV ผ่านเกณฑ์) ค่าเฉลี่ย % dissolved ที่ 10, 15, 20, 30 นาที: Reference = 40, 58, 72, 86 และ Test = 46, 62, 70, 83 ค่า f2 ประมาณเท่าใด",
      o: ["5.9", "38.2", "54.5", "69.1", "83.1"],
      a: 3,
      r: "f2 = 50 × log₁₀{[1 + (1/n) Σ(Rt − Tt)²]^−0.5 × 100} เป็นการแปลงค่า mean squared difference ระหว่างสอง profile ให้เป็นสเกล 0–100 โดย f2 = 100 เมื่อเหมือนกันทุกจุด และ f2 = 50 สอดคล้องกับความต่างเฉลี่ยประมาณ 10% ทุกจุด เกณฑ์ similarity คือ f2 ≥ 50\n\nในโจทย์มี 4 จุดเวลา และมีเพียงจุดเดียว (30 นาทีของ reference) ที่เกิน 85% จึงใช้ครบ 4 จุดได้ ผลรวมกำลังสองของผลต่าง = 36 + 16 + 4 + 9 = 65 หาร n = 4 ได้ 16.25 จึงได้ f2 ≈ 69.1 ซึ่งแสดงว่า profile คล้ายกัน",
      w: [
        "5.9 คือค่า f1 (Σ|R−T|/ΣR × 100 = 15/256) ไม่ใช่ f2",
        "38.2 เกิดจากลืมยกกำลัง −0.5 (ไม่ถอดราก) ของ [1 + MSD]",
        "54.5 เกิดจากใช้ผลรวมกำลังสอง (65) โดยไม่หารด้วยจำนวนจุดเวลา n",
        "ถูก — Σ(R−T)² = 65, /4 = 16.25, f2 = 50·log(100/√17.25) ≈ 69.1",
        "83.1 เกิดจากใช้ผลรวมค่าสัมบูรณ์ของผลต่าง (15) แทนผลรวมกำลังสอง",
      ],
      k: "f2 = 50·log{100/√[1 + Σ(R−T)²/n]}; f2 ≥ 50 = similar; หาร n ก่อนบวก 1 แล้วถอดราก",
      d: "hard",
      ref: "FDA Guidance: Dissolution Testing of Immediate Release Solid Oral Dosage Forms (1997); EMA CPMP/EWP/QWP/1401/98 Rev.1 Appendix I",
      c: [
        "ผลต่าง R − T = −6, −4, +2, +3",
        "Σ(R − T)² = 36 + 16 + 4 + 9 = 65",
        "MSD = 65/4 = 16.25 → 1 + 16.25 = 17.25",
        "17.25^−0.5 × 100 = 100/4.153 = 24.08",
        "f2 = 50 × log₁₀(24.08) = 50 × 1.382 ≈ 69.1",
      ],
    },
    {
      t: "Absolute bioavailability calculation",
      p: "ในการศึกษาใน healthy volunteers ให้ยา Z ทางหลอดเลือดดำขนาด 50 mg ได้ AUC₀–∞ = 10 mg·h/L และให้ยาเม็ดรับประทานขนาด 200 mg (crossover ในคนเดียวกัน) ได้ AUC₀–∞ = 28 mg·h/L สมมติ PK เป็นแบบ linear ค่า absolute bioavailability (F) ของยาเม็ดเป็นเท่าใด",
      o: ["14%", "20%", "70%", "143%", "280%"],
      a: 2,
      r: "Absolute bioavailability เปรียบเทียบ extravascular กับ IV (F_IV = 1) โดยต้องปรับด้วยขนาดยา: F = (AUC_oral/Dose_oral)/(AUC_IV/Dose_IV) ซึ่งใช้ได้เมื่อ clearance คงที่ (linear PK) และวัดในคนเดียวกัน\n\nAUC ต่อ mg ของ oral = 28/200 = 0.14 ส่วนของ IV = 10/50 = 0.20 ดังนั้น F = 0.14/0.20 = 0.70 หรือ 70% ความผิดพลาดที่พบบ่อยคือไม่ปรับขนาดยา (ได้ 280%) หรือปรับขนาดยากลับด้าน ค่า F ที่ได้สะท้อนผลรวมของ fraction absorbed และ first-pass ทั้งที่ลำไส้และตับ",
      w: [
        "14% คือ AUC/dose ของยารับประทาน (0.14) โดยยังไม่ได้หารด้วยค่าของ IV",
        "20% คือ AUC/dose ของ IV (10/50 = 0.20) ซึ่งเป็นตัวหาร ไม่ใช่ค่า F",
        "ถูก — F = (28/200)/(10/50) = 0.14/0.20 = 0.70",
        "143% เกิดจากหารกลับด้าน (0.20/0.14) ค่า F เกิน 100% ไม่สมเหตุผลสำหรับ absolute BA",
        "280% คือ AUC_oral/AUC_IV โดยไม่ได้ปรับขนาดยาที่ต่างกัน 4 เท่า",
      ],
      k: "F_abs = (AUC_po/D_po)/(AUC_iv/D_iv) — ต้อง dose-normalize เสมอ และใช้ได้เมื่อ PK เป็น linear",
      d: "medium",
      ref: "Shargel & Yu, Applied Biopharmaceutics & Pharmacokinetics 7th ed., Ch.16",
      c: [
        "AUC/Dose (oral) = 28/200 = 0.14 h/L",
        "AUC/Dose (IV) = 10/50 = 0.20 h/L",
        "F = 0.14/0.20 = 0.70 = 70%",
      ],
    },
    {
      t: "Washout period in crossover BE",
      p: "บริษัทวางแผน BE study แบบ 2×2 crossover สำหรับยาเม็ด IR ที่มี terminal elimination half-life ประมาณ 20 ชั่วโมง (ไม่มี metabolite ที่มี half-life ยาวกว่า) ระยะ washout ระหว่าง 2 periods ข้อใดเหมาะสมที่สุด",
      o: [
        "อย่างน้อยประมาณ 100 ชั่วโมง (≥ 5 half-lives) เช่น กำหนด 7 วัน",
        "24 ชั่วโมง เพราะยาให้วันละครั้ง",
        "40 ชั่วโมง (2 half-lives) ก็เพียงพอเพราะยาเหลือ 25%",
        "ไม่ต้องมี washout ถ้าสุ่มลำดับการได้รับยา (randomized sequence)",
        "อย่างน้อย 30 วัน ทุกกรณีเพื่อความปลอดภัย",
      ],
      a: 0,
      r: "Washout ใน crossover design มีไว้ป้องกัน carry-over จาก period แรกไปปน period ที่สอง หลัก EMA/FDA คือ washout ควร ≥ 5 elimination half-lives ของ analyte (ยาหรือ metabolite ที่วัด) ซึ่งเหลือยาประมาณ 3% ของเดิม\n\nสำหรับ t½ = 20 h, 5 × 20 = 100 h (~4.2 วัน) การเลือก 7 วันจึงปลอดภัยและสะดวกในการจัดการ หากพบความเข้มข้น pre-dose ใน period 2 เกิน 5% ของ Cmax ต้องตัดข้อมูลของอาสาสมัครรายนั้นออกจากการวิเคราะห์ ส่วนการกำหนดนานเกินจำเป็นมากเพิ่ม dropout โดยไม่ได้ประโยชน์",
      w: [
        "ถูก — 5 × 20 h = 100 h ยาเหลือ ~3% การปัดเป็น 7 วันเป็นทางปฏิบัติที่เหมาะสม",
        "24 ชั่วโมงเท่ากับ 1.2 half-lives ยายังเหลือเกือบครึ่ง ทำให้เกิด carry-over",
        "2 half-lives ยังเหลือยา 25% ซึ่งมาก จะรบกวน PK ของ period ถัดไป",
        "Randomization ช่วยกระจาย period/sequence effect แต่ไม่ได้กำจัด carry-over จึงยังต้องมี washout",
        "ไม่จำเป็นต้องนานถึง 30 วัน การนานเกินไปเพิ่ม dropout และอาจเปลี่ยนสภาวะทางสรีรวิทยาของอาสาสมัคร",
      ],
      k: "Washout ≥ 5 t½ ของ analyte; pre-dose > 5% Cmax ใน period ถัดไป → ตัดข้อมูลรายนั้น",
      d: "medium",
      ref: "EMA Guideline on the Investigation of Bioequivalence CPMP/EWP/QWP/1401/98 Rev.1, Section 4.1.1",
    },
    {
      t: "90% CI decision with Cmax failing",
      p: "ผล BE study (2×2 crossover, fasting, n = 28) ของยาเม็ด generic เทียบ reference: AUC₀–t GMR = 98.4% (90% CI 92.10–105.13%) และ Cmax GMR = 89.9% (90% CI 79.62–101.47%) ข้อใดสรุปได้ถูกต้องที่สุด",
      o: [
        "ไม่แสดง BE เพราะ lower limit ของ 90% CI ของ Cmax ต่ำกว่า 80.00% แม้ point estimate จะอยู่ในช่วง",
        "แสดง BE เพราะ point estimate ของทั้ง AUC และ Cmax อยู่ในช่วง 80.00–125.00%",
        "แสดง BE เพราะ AUC เป็นตัวแปรหลัก ส่วน Cmax ใช้ประกอบเท่านั้น",
        "แสดง BE เพราะปัด 79.62% เป็น 80% ได้",
        "ไม่แสดง BE เพราะ GMR ของ Cmax ไม่อยู่ในช่วง 90–110%",
      ],
      a: 0,
      r: "เกณฑ์ BE มาตรฐาน (average bioequivalence) คือ 90% confidence interval ของ geometric mean ratio (test/reference) ของทั้ง AUC และ Cmax ต้องอยู่ภายใน 80.00–125.00% ทั้งช่วง ไม่ใช่เฉพาะ point estimate\n\nการทดสอบนี้เทียบเท่า two one-sided tests (TOST) ที่ α = 0.05 แต่ละด้าน ในกรณีนี้ Cmax มี lower limit 79.62% ซึ่งต่ำกว่า 80.00% (EMA กำหนดให้รายงานและตัดสินที่ทศนิยม 2 ตำแหน่ง ห้ามปัดเข้า) จึงไม่ผ่าน แม้ AUC ผ่าน ทั้งนี้ point estimate ที่ต่ำ (~90%) ร่วมกับ CI ที่กว้าง แสดงว่าอัตราการดูดซึมของ test อาจช้ากว่าและ/หรือ variability สูง ซึ่งอาจต้องการ sample size มากขึ้นหรือปรับสูตร",
      w: [
        "ถูก — ต้องให้ 90% CI ทั้งช่วงของทั้ง AUC และ Cmax อยู่ใน 80.00–125.00%; Cmax lower limit 79.62% ไม่ผ่าน",
        "Point estimate ในช่วงยังไม่พอ เกณฑ์ใช้ 90% CI ทั้งช่วง",
        "Cmax เป็น primary parameter สำหรับ rate of absorption ต้องผ่านเกณฑ์เช่นเดียวกับ AUC",
        "เกณฑ์ใช้ค่า 80.00% ที่ทศนิยม 2 ตำแหน่ง ไม่อนุญาตให้ปัดค่าเพื่อให้ผ่าน",
        "ช่วง 90–110% ไม่ใช่เกณฑ์ point estimate ของ BE มาตรฐาน (ช่วงแคบใช้กับ CI ของยา NTI)",
      ],
      k: "BE ผ่านเมื่อ 90% CI ของ GMR (AUC และ Cmax) อยู่ใน 80.00–125.00% ทั้งช่วง ห้ามปัดเศษ",
      d: "hard",
      ref: "EMA Guideline on the Investigation of Bioequivalence CPMP/EWP/QWP/1401/98 Rev.1, Section 4.1.8",
    },
    {
      t: "Pharmaceutical alternatives vs equivalents",
      p: "ผลิตภัณฑ์ A คือ doxycycline hyclate 100 mg capsule ผลิตภัณฑ์ B คือ doxycycline monohydrate 100 mg tablet (ปริมาณ doxycycline base เท่ากัน) ทั้งสองผ่านมาตรฐานตำรายา ความสัมพันธ์ระหว่าง A และ B ตรงกับข้อใดมากที่สุด",
      o: [
        "Pharmaceutical alternatives เพราะมี therapeutic moiety เดียวกันแต่ต่างทั้ง salt form และ dosage form",
        "Pharmaceutical equivalents เพราะมี doxycycline base ในปริมาณเท่ากัน",
        "Therapeutic equivalents โดยอัตโนมัติ เพราะผ่านมาตรฐานตำรายาเหมือนกัน",
        "Bioequivalent โดยไม่ต้องทำการศึกษา เพราะ doxycycline เป็น BCS class I",
        "Generic ของกันและกัน ใช้แทนกันได้โดยไม่ต้องมีข้อมูลเพิ่มเติม",
      ],
      a: 0,
      r: "Pharmaceutical equivalents ต้องมี active ingredient เดียวกัน (salt/ester เดียวกัน) ในปริมาณเท่ากัน dosage form เดียวกัน และ route เดียวกัน ผ่านมาตรฐานเดียวกัน ส่วน pharmaceutical alternatives คือมี therapeutic moiety เดียวกันแต่ต่าง salt, ester, complex, dosage form หรือ strength\n\nA กับ B ต่างทั้ง salt (hyclate vs monohydrate) และ dosage form (capsule vs tablet) จึงเป็น pharmaceutical alternatives การเป็น therapeutic equivalent ต้องเป็น pharmaceutical equivalent และ bioequivalent พร้อมกัน ดังนั้น alternatives ไม่สามารถถือว่า interchangeable โดยอัตโนมัติ แม้ผ่านมาตรฐานตำรายาทั้งคู่",
      w: [
        "ถูก — therapeutic moiety เดียวกันแต่ต่าง salt และ dosage form = pharmaceutical alternatives",
        "Pharmaceutical equivalents ต้องเป็น salt และ dosage form เดียวกัน ปริมาณ base เท่ากันยังไม่พอ",
        "การผ่านมาตรฐานตำรายาไม่ได้รับประกัน bioequivalence; TE = PE + BE",
        "BCS-based biowaiver ไม่ได้ทำให้เป็น BE โดยอัตโนมัติ และไม่ครอบคลุมการเปลี่ยน dosage form และ salt แบบนี้โดยไม่มีการประเมิน",
        "การใช้แทนกัน (interchangeability) ต้องมีหลักฐาน therapeutic equivalence ไม่ใช่สรุปจากการมี moiety เดียวกัน",
      ],
      k: "PE = same API/salt, strength, dosage form, route; ต่าง salt/dosage form = pharmaceutical alternatives; TE = PE + BE",
      d: "hard",
      ref: "FDA Orange Book Preface (Approved Drug Products with Therapeutic Equivalence Evaluations), Section 1.2",
    },
  ],
  // Mock Set 2
  [
    {
      t: "Saturable carrier-mediated absorption",
      p: "ข้อมูลยา gabapentin ระบุว่า bioavailability ลดลงเมื่อเพิ่มขนาดยา (ประมาณ 60% ที่ 900 mg/วัน เหลือราว 27% ที่ 4,800 mg/วัน) ปรากฏการณ์นี้อธิบายได้ดีที่สุดด้วยกลไกใด",
      o: [
        "การดูดซึมอาศัย L-amino acid transporter ซึ่งอิ่มตัวได้ที่ขนาดยาสูง",
        "Hepatic first-pass metabolism เพิ่มขึ้นเมื่อขนาดยาสูงขึ้น",
        "ยาเกิด precipitation ในกระเพาะเพราะ solubility ต่ำมากในกรด",
        "P-glycoprotein ถูก induce เมื่อได้รับยาขนาดสูง",
        "Passive diffusion ลดลงเพราะ concentration gradient สูงเกินไป",
      ],
      a: 0,
      r: "Carrier-mediated transport มีจำนวน transporter จำกัด จึงเป็นไปตาม Michaelis–Menten: ที่ความเข้มข้นต่ำอัตราการดูดซึมเพิ่มตามความเข้มข้น แต่เมื่อความเข้มข้นในลำไส้สูงกว่า Km มาก carrier จะอิ่มตัว อัตราการดูดซึมเข้าใกล้ Vmax ทำให้สัดส่วนที่ถูกดูดซึม (F) ลดลงเมื่อเพิ่มขนาดยา (less than dose-proportional)\n\nGabapentin เป็น amino acid analogue ที่ถูกดูดซึมผ่าน system-L amino acid transporter ในลำไส้เล็กส่วนต้น จึงมี bioavailability ลดลงตามขนาดยา และไม่ถูก metabolize (ขับทางไตเป็นรูปเดิม) ทางแก้ในทางคลินิกคือแบ่งให้หลายครั้งต่อวัน ตัวอย่างอื่นของ saturable uptake เช่น riboflavin และ levodopa",
      w: [
        "ถูก — transporter มีจำนวนจำกัด อิ่มตัวที่ขนาดยาสูง ทำให้ F ลดลงแบบ dose-dependent",
        "Gabapentin แทบไม่ถูก metabolize และ first-pass ที่อิ่มตัวได้จะทำให้ F เพิ่มขึ้นเมื่อขนาดยาสูง ไม่ใช่ลดลง",
        "Gabapentin ละลายน้ำได้ดีมาก (BCS high solubility) ปัญหาไม่ได้อยู่ที่การละลาย",
        "Gabapentin ไม่ใช่ P-gp substrate ที่สำคัญ และ induction ต้องใช้เวลา ไม่อธิบายความสัมพันธ์กับขนาดยาครั้งเดียว",
        "Passive diffusion ยิ่ง gradient สูงยิ่งดูดซึมมาก ไม่มีการลดลงของสัดส่วนที่ดูดซึม",
      ],
      k: "F ลดลงเมื่อเพิ่มขนาดยา → นึกถึง saturable uptake transporter (เช่น gabapentin ผ่าน LAT)",
      d: "medium",
      ref: "Shargel & Yu, Applied Biopharmaceutics & Pharmacokinetics 7th ed., Ch.13; Neurontin (gabapentin) Prescribing Information",
    },
    {
      t: "Gastric emptying and Tmax",
      p: "ผู้ป่วยรับประทานยาเม็ด paracetamol ซึ่งถูกดูดซึมส่วนใหญ่ที่ลำไส้เล็ก โดยรับประทานพร้อม metoclopramide ผลต่อ PK ของ paracetamol ที่คาดได้คือข้อใด",
      o: [
        "Tmax สั้นลงและ Cmax สูงขึ้น เพราะ gastric emptying เร็วขึ้น",
        "Tmax ยาวขึ้นและ Cmax ต่ำลง เพราะยาค้างในกระเพาะนานขึ้น",
        "AUC ลดลงครึ่งหนึ่ง เพราะยาผ่านลำไส้เร็วเกินไป",
        "ไม่มีผลใด ๆ เพราะ paracetamol ถูกดูดซึมแบบ passive diffusion",
        "Tmax ไม่เปลี่ยนแต่ elimination half-life สั้นลง",
      ],
      a: 0,
      r: "สำหรับยาที่ดูดซึมได้ดีที่ลำไส้เล็ก gastric emptying เป็นขั้นตอนกำหนดอัตรา (rate-limiting) ของการเข้าถึงบริเวณดูดซึม Metoclopramide (prokinetic) เร่ง gastric emptying ทำให้ยาไปถึงลำไส้เล็กเร็ว Tmax สั้นลงและ Cmax สูงขึ้น ในขณะที่ยาที่ชะลอ gastric emptying เช่น anticholinergic (propantheline) หรือ opioids ให้ผลตรงข้าม\n\nสำหรับยาที่ดูดซึมได้สมบูรณ์อย่าง paracetamol AUC (extent) มักเปลี่ยนน้อย เพราะการเปลี่ยนแปลงหลักคือ rate การดูดซึม paracetamol absorption จึงถูกใช้เป็น marker ของ gastric emptying ในงานวิจัย",
      w: [
        "ถูก — prokinetic เร่ง gastric emptying ยาถึงลำไส้เล็กเร็ว จึงดูดซึมเร็ว Tmax สั้น Cmax สูง",
        "ผลแบบนี้เกิดกับยาที่ชะลอ gastric emptying เช่น propantheline ไม่ใช่ metoclopramide",
        "Paracetamol ดูดซึมเร็วและสมบูรณ์ การเร่ง transit ไม่ได้ลด extent ลงมากถึงครึ่ง",
        "แม้เป็น passive diffusion แต่อัตราการดูดซึมยังขึ้นกับเวลาที่ยาไปถึงลำไส้เล็ก",
        "Metoclopramide ไม่ได้เปลี่ยน elimination ของ paracetamol ผลอยู่ที่ระยะ absorption",
      ],
      k: "Gastric emptying กำหนด rate: เร่ง (metoclopramide) → Tmax สั้น Cmax สูง; ชะลอ (anticholinergic, opioid) → ตรงข้าม",
      d: "easy",
      ref: "Aulton's Pharmaceutics 5th ed., Ch.19 Gastrointestinal Tract — Physiology and Drug Absorption",
    },
    {
      t: "ICH M9 high permeability criterion",
      p: "ตามแนวทาง ICH M9 การจัดยาเป็น high permeability โดยใช้ข้อมูลในมนุษย์ ข้อใดเป็นเกณฑ์ที่ถูกต้อง",
      o: [
        "Absolute bioavailability ≥ 85% หรือ ≥ 85% ของขนาดยาถูกพบในปัสสาวะเป็นยาเดิมรวมกับ metabolites (mass balance)",
        "Absolute bioavailability ≥ 50% ในอาสาสมัครอย่างน้อย 12 คน",
        "Log P ของยามากกว่า 3",
        "ยาถูก metabolize ผ่าน CYP3A4 ไม่น้อยกว่า 50%",
        "Cmax ถึงภายใน 1 ชั่วโมงหลังรับประทาน",
      ],
      a: 0,
      r: "ICH M9 ใช้ extent of absorption ในมนุษย์เป็นหลักในการตัดสิน permeability: high permeability เมื่อ absolute bioavailability ≥ 85% หรือ mass balance แสดงว่า ≥ 85% ของขนาดยาที่ให้ถูกพบในปัสสาวะเป็นยาเดิม หรือรวมกับ phase 1 oxidative และ phase 2 conjugative metabolites (หรือพบในอุจจาระเฉพาะในรูป metabolite)\n\nข้อมูลจาก Caco-2 monolayer ที่ validate แล้วใช้สนับสนุนได้ แต่ค่า log P, รูปแบบ metabolism หรือ Tmax ไม่ใช่เกณฑ์ของ BCS permeability เพราะไม่ได้บอก fraction absorbed โดยตรง",
      w: [
        "ถูก — ICH M9 ใช้ absolute BA ≥ 85% หรือ mass balance ≥ 85% เป็นเกณฑ์ high permeability",
        "50% เป็นเกณฑ์ที่ต่ำเกินไป ICH M9 ใช้ 85% (แนวทางเดิมบางฉบับใช้ 90%)",
        "Log P บ่งบอก lipophilicity แต่ไม่ใช่เกณฑ์ BCS และ log P สูงไม่รับประกันการดูดซึม",
        "การถูก metabolize ผ่าน CYP3A4 ไม่ได้บอก fraction absorbed (BDDCS ใช้ extent of metabolism รวมแต่ไม่ใช่เกณฑ์นี้)",
        "Tmax สะท้อน rate of absorption ไม่ใช่ extent ของการดูดซึม",
      ],
      k: "ICH M9 high permeability: absolute BA ≥ 85% หรือ mass balance ≥ 85% (ยาเดิม + metabolites ในปัสสาวะ)",
      d: "easy",
      ref: "ICH M9 Biopharmaceutics Classification System-based Biowaivers (2019), Section 2.1.2",
    },
    {
      t: "BCS class III biowaiver conditions",
      p: "บริษัทต้องการขอ BCS-based biowaiver สำหรับยาเม็ด IR ของ API ที่เป็น BCS class III (high solubility, low permeability) ข้อใดเป็นเงื่อนไขตาม ICH M9 ที่ถูกต้อง",
      o: [
        "ทั้ง test และ reference ต้อง very rapidly dissolving (≥ 85% ใน 15 นาที) และ excipients ต้องเหมือนกันเชิงคุณภาพและใกล้เคียงกันเชิงปริมาณ",
        "ต้อง rapidly dissolving (≥ 85% ใน 30 นาที) และมี f2 ≥ 50 ใน 3 media โดย excipients ต่างกันได้อย่างอิสระ",
        "ต้องมี dissolution ≥ 85% ใน 60 นาทีใน FaSSIF เท่านั้น",
        "Class III ไม่สามารถขอ biowaiver ได้ในทุกกรณี ต้องทำ in vivo BE",
        "ต้องแสดง IVIVC Level A ก่อนจึงขอ biowaiver ได้",
      ],
      a: 0,
      r: "สำหรับ BCS class III การดูดซึมถูกจำกัดด้วย permeability ซึ่ง excipients บางชนิดสามารถเปลี่ยนได้ (เช่น sugar alcohols อย่าง sorbitol/mannitol ลด transit time และลดการดูดซึม, surfactant อาจเพิ่ม permeability) ICH M9 จึงเข้มงวดกว่า class I\n\nเงื่อนไขคือ test และ reference ต้อง very rapidly dissolving (≥ 85% ใน 15 นาที) ในทั้ง pH 1.2, 4.5, 6.8 และ excipients ต้องเหมือนกันเชิงคุณภาพ (qualitatively the same) และใกล้เคียงกันเชิงปริมาณ (quantitatively very similar) ตามขอบเขตที่กำหนด ส่วน class I ยอมให้ rapidly dissolving (≥ 85% ใน 30 นาที) พร้อม f2 และ excipients ต่างได้มากกว่า โดยยังต้องประเมินผลของ excipient ต่อการดูดซึม",
      w: [
        "ถูก — class III ต้อง very rapid dissolution (≥ 85%/15 นาที) และ excipients qualitatively same, quantitatively very similar",
        "เกณฑ์ rapid (30 นาที) + f2 เป็นทางเลือกสำหรับ class I ไม่ใช่ class III และ excipients ต่างอย่างอิสระไม่ได้",
        "BCS biowaiver ใช้ compendial buffers pH 1.2, 4.5, 6.8 ไม่ใช่ FaSSIF และเวลา 60 นาทีไม่ใช่เกณฑ์",
        "ICH M9 อนุญาต biowaiver สำหรับ class III ภายใต้เงื่อนไขที่เข้มงวด ไม่ได้ห้ามทุกกรณี",
        "IVIVC ไม่ใช่เงื่อนไขของ BCS-based biowaiver ซึ่งเป็นคนละแนวทางกัน",
      ],
      k: "Biowaiver class I: ≥ 85% ใน 30 นาที (+f2) หรือ 15 นาที; class III: ต้อง ≥ 85% ใน 15 นาที + excipients Q1/Q2 ใกล้เคียง",
      d: "hard",
      ref: "ICH M9 Biopharmaceutics Classification System-based Biowaivers (2019), Sections 3.1–3.2",
    },
    {
      t: "USP 711 stage S2 evaluation",
      p: "ยาเม็ด IR มี Q = 80% ใน 45 นาที Stage S1 ได้ 88, 83, 90, 79, 86, 91% จึงทดสอบ S2 อีก 6 เม็ดได้ 84, 82, 87, 76, 81, 85% ข้อใดสรุปได้ถูกต้อง",
      o: [
        "ผ่านที่ S2 เพราะค่าเฉลี่ย 12 เม็ด (84.3%) ≥ Q และไม่มีเม็ดใดต่ำกว่า Q − 15% (65%)",
        "ไม่ผ่าน S2 เพราะมี 2 เม็ดต่ำกว่า Q (79% และ 76%) ต้องทำ S3",
        "ไม่ผ่าน S2 เพราะมีหลายเม็ดต่ำกว่า Q + 5%",
        "ผ่านที่ S2 แต่ต้องรายงานเฉพาะค่าเฉลี่ยของ S2 (82.5%)",
        "ต้องไป S3 เพราะ S2 ต้องให้ทุกเม็ดอยู่ในช่วง Q ถึง Q + 10%",
      ],
      a: 0,
      r: "เกณฑ์ S2 ของ USP <711>: ใช้ผลรวม 12 หน่วย (S1 + S2) ค่าเฉลี่ย ≥ Q และไม่มีหน่วยใดต่ำกว่า Q − 15% เกณฑ์ไม่ได้ห้ามมีหน่วยที่ต่ำกว่า Q\n\nผลรวม S1 = 517 และ S2 = 495 รวม 1,012 หาร 12 = 84.3% ≥ 80% และค่าต่ำสุด 76% ยังสูงกว่า Q − 15% = 65% จึงผ่านที่ S2 การมีบางเม็ดต่ำกว่า Q เป็นสิ่งที่เกณฑ์ S2 ยอมรับได้ ตราบใดที่ไม่ต่ำกว่า Q − 15%",
      w: [
        "ถูก — mean 12 หน่วย = 84.3% ≥ 80% และค่าต่ำสุด 76% > 65% ผ่าน S2",
        "S2 ยอมให้บางเม็ดต่ำกว่า Q ได้ ข้อห้ามคือต่ำกว่า Q − 15%",
        "เกณฑ์ Q + 5% ต่อหน่วยใช้เฉพาะ S1",
        "ค่าเฉลี่ยของ S2 ต้องคิดรวม 12 หน่วย (S1 + S2) ไม่ใช่เฉพาะ 6 หน่วยหลัง",
        "ไม่มีเกณฑ์ช่วง Q ถึง Q + 10% สำหรับ IR ใน USP <711>",
      ],
      k: "S2: 12 หน่วย mean ≥ Q และไม่มีหน่วยใด < Q − 15%",
      d: "medium",
      ref: "USP <711> Dissolution, Acceptance Table 1",
      c: [
        "ผลรวม S1 = 88 + 83 + 90 + 79 + 86 + 91 = 517",
        "ผลรวม S2 = 84 + 82 + 87 + 76 + 81 + 85 = 495",
        "Mean 12 หน่วย = 1,012/12 = 84.3% ≥ 80%",
        "Q − 15% = 65%; ค่าต่ำสุด 76% > 65% → ผ่าน S2",
      ],
    },
    {
      t: "FaSSIF vs FeSSIF composition",
      p: "นักวิจัยต้องการทำนาย food effect ของยา BCS class II ที่เป็น lipophilic โดยใช้ biorelevant dissolution ข้อใดอธิบายความแตกต่างระหว่าง FaSSIF และ FeSSIF (สูตรดั้งเดิม) ได้ถูกต้อง",
      o: [
        "FeSSIF มี sodium taurocholate และ lecithin สูงกว่า (ประมาณ 15 mM vs 3 mM ของ bile salt) และ pH ต่ำกว่า (5.0 vs 6.5)",
        "FeSSIF มี pH สูงกว่า (7.5 vs 6.5) และไม่มี bile salt",
        "FaSSIF มี pepsin และ pH 1.2 ส่วน FeSSIF มี pancreatin และ pH 6.8",
        "ทั้งสองมีองค์ประกอบเหมือนกัน ต่างกันเพียงปริมาตรที่ใช้ทดสอบ",
        "FaSSIF ใช้ SLS 1% เพื่อเลียนแบบ bile salt ส่วน FeSSIF ใช้ SLS 2%",
      ],
      a: 0,
      r: "Biorelevant media จำลองของเหลวในลำไส้เล็กส่วนต้นในสภาวะอดอาหาร (fasted) และหลังอาหาร (fed) FaSSIF ดั้งเดิมมี sodium taurocholate 3 mM และ lecithin 0.75 mM ที่ pH 6.5 ส่วน FeSSIF มี taurocholate 15 mM และ lecithin 3.75 mM ที่ pH 5.0 (อาหารและกรดไขมันทำให้ pH ต่ำลง และ bile ถูกหลั่งมากขึ้น)\n\nMixed micelles ของ bile salt/lecithin ช่วยเพิ่ม solubilization ของยา lipophilic ดังนั้นถ้ายา BCS II ละลายใน FeSSIF ได้มากกว่า FaSSIF อย่างชัดเจน มักทำนายได้ว่าจะมี positive food effect ส่วน SLS เป็น synthetic surfactant ใน QC media ไม่ใช่ biorelevant",
      w: [
        "ถูก — FeSSIF มี bile salt/lecithin สูงกว่าราว 4–5 เท่า และ pH 5.0 ต่ำกว่า FaSSIF (6.5)",
        "FeSSIF มี pH ต่ำกว่า FaSSIF และมี bile salt สูงกว่า ไม่ใช่ไม่มี",
        "Medium ที่มี pepsin pH ~1.6 คือ FaSSGF (gastric) ไม่ใช่ FaSSIF; FeSSIF ไม่ได้ใช้ pancreatin เป็นองค์ประกอบหลัก",
        "องค์ประกอบต่างกันชัดเจนทั้งความเข้มข้นของ bile salt, lecithin และ pH",
        "SLS เป็น synthetic surfactant สำหรับ QC media ไม่ใช่องค์ประกอบของ biorelevant media",
      ],
      k: "FaSSIF: pH 6.5, taurocholate 3 mM; FeSSIF: pH 5.0, taurocholate 15 mM — ใช้ทำนาย food effect ของ BCS II",
      d: "medium",
      ref: "Galia E, Dressman JB et al. Pharm Res 1998;15:698–705; USP <1092>",
    },
    {
      t: "IVIVC Level A definition and use",
      p: "บริษัทพัฒนา extended-release tablet และได้ IVIVC จากการ deconvolution ข้อมูล plasma concentration ของ 3 สูตรที่มี release rate ต่างกัน ได้ความสัมพันธ์เชิงเส้นแบบจุดต่อจุดระหว่าง % dissolved in vitro กับ % absorbed in vivo ข้อใดถูกต้องที่สุด",
      o: [
        "เป็น Level A correlation ซึ่งเมื่อ validate แล้วสามารถใช้ dissolution ทำนาย plasma profile และสนับสนุน biowaiver สำหรับการเปลี่ยนแปลงบางประเภทได้",
        "เป็น Level B correlation เพราะใช้ mean dissolution time เทียบกับ mean residence time",
        "เป็น Level C correlation เพราะเทียบ dissolution จุดเดียวกับ AUC",
        "เป็น Level A แต่ใช้ได้เฉพาะการตั้ง dissolution specification ไม่สามารถใช้ขอ biowaiver ได้",
        "ใช้ได้ทันทีโดยไม่ต้องทดสอบ predictability เพราะ r² ของความสัมพันธ์สูง",
      ],
      a: 0,
      r: "IVIVC Level A คือความสัมพันธ์แบบ point-to-point ระหว่าง in vitro dissolution กับ in vivo input rate (fraction absorbed) ที่ได้จาก deconvolution เช่น Wagner–Nelson หรือ numerical deconvolution มักเป็นเชิงเส้น เป็นระดับที่มีประโยชน์สูงสุดเพราะสามารถทำนาย plasma concentration–time profile ทั้งเส้นจาก dissolution ได้\n\nเมื่อผ่านการ validate (internal/external predictability ของ Cmax และ AUC) จะใช้สนับสนุน biowaiver สำหรับการเปลี่ยนแปลงหลังอนุมัติ (เช่น SUPAC level 3 บางกรณี) และใช้ตั้ง dissolution specification ที่มีความหมายทางคลินิก ส่วน Level B ใช้ statistical moment (MDT vs MRT) และ Level C ใช้จุดเดียว",
      w: [
        "ถูก — point-to-point ระหว่าง % dissolved กับ % absorbed = Level A ใช้ทำนาย profile และ biowaiver ได้เมื่อ validate",
        "Level B ใช้ statistical moment (MDT/MRT) ไม่ใช่ความสัมพันธ์แบบจุดต่อจุด",
        "Level C เทียบ dissolution parameter จุดเดียวกับ PK parameter เดียว ซึ่งไม่ตรงกับข้อมูลในโจทย์",
        "Level A ที่ validate แล้วเป็นระดับเดียวที่สนับสนุน biowaiver ได้กว้างที่สุด",
        "r² สูงไม่พอ ต้องประเมิน prediction error ของ Cmax และ AUC ก่อนนำไปใช้",
      ],
      k: "IVIVC Level A = point-to-point (deconvolution); ทำนาย profile ได้ ใช้ biowaiver ได้หลัง validate",
      d: "medium",
      ref: "FDA Guidance: Extended Release Oral Dosage Forms — Development, Evaluation, and Application of IVIVC (1997); USP <1088>",
    },
    {
      t: "AUC trapezoidal with extrapolation",
      p: "ข้อมูลความเข้มข้นในพลาสมาหลังรับประทานยาครั้งเดียว: 0 h = 0, 1 h = 4.0, 2 h = 6.0, 4 h = 4.0, 6 h = 2.5, 8 h = 1.6 mg/L และ terminal elimination rate constant (λz) = 0.25 h⁻¹ ค่า AUC₀–∞ โดย linear trapezoidal rule ประมาณเท่าใด",
      o: ["27.6 mg·h/L", "28.0 mg·h/L", "34.0 mg·h/L", "35.4 mg·h/L", "51.6 mg·h/L"],
      a: 2,
      r: "AUC₀–t คำนวณด้วย linear trapezoidal rule โดยรวมพื้นที่สี่เหลี่ยมคางหมูทุกช่วง: ช่วง 0–1 = 2.0, 1–2 = 5.0, 2–4 = 10.0, 4–6 = 6.5, 6–8 = 4.1 รวม 27.6 mg·h/L\n\nส่วนที่เหลือหลังจุดสุดท้าย (AUC_t–∞) ประมาณได้จาก C_last/λz = 1.6/0.25 = 6.4 mg·h/L ดังนั้น AUC₀–∞ = 34.0 mg·h/L สัดส่วนที่ extrapolate = 6.4/34.0 ≈ 19% ซึ่งใกล้ขีด 20% ที่แนวทาง EMA ใช้พิจารณาว่าช่วงเก็บตัวอย่างเพียงพอหรือไม่ (AUC₀–t ควรครอบคลุม ≥ 80% ของ AUC₀–∞) ข้อควรระวังคือต้องใช้ C_last ไม่ใช่ Cmax และหารด้วย λz ไม่ใช่คูณ",
      w: [
        "27.6 คือ AUC₀–t เท่านั้น ยังไม่ได้รวมส่วน extrapolate ไปถึง infinity",
        "28.0 เกิดจากคูณ C_last ด้วย λz (1.6 × 0.25 = 0.4) แทนการหาร",
        "ถูก — AUC₀–t 27.6 + C_last/λz (1.6/0.25 = 6.4) = 34.0 mg·h/L",
        "35.4 เกิดจากใช้ left-rectangle (ใช้ค่าต้นช่วงคูณช่วงเวลา) แทน trapezoid แล้วบวก 6.4",
        "51.6 เกิดจากใช้ Cmax (6.0/0.25 = 24) แทน C_last ในการ extrapolate",
      ],
      k: "AUC₀–∞ = AUC₀–t (trapezoid) + C_last/λz; ส่วน extrapolate ควร ≤ 20%",
      d: "hard",
      ref: "Shargel & Yu, Applied Biopharmaceutics & Pharmacokinetics 7th ed., Ch.2 and Ch.16",
      c: [
        "0–1 h: (0 + 4.0)/2 × 1 = 2.0",
        "1–2 h: (4.0 + 6.0)/2 × 1 = 5.0",
        "2–4 h: (6.0 + 4.0)/2 × 2 = 10.0",
        "4–6 h: (4.0 + 2.5)/2 × 2 = 6.5",
        "6–8 h: (2.5 + 1.6)/2 × 2 = 4.1 → AUC₀–t = 27.6",
        "AUC_t–∞ = 1.6/0.25 = 6.4 → AUC₀–∞ = 34.0 mg·h/L",
      ],
    },
    {
      t: "Relative bioavailability calculation",
      p: "เปรียบเทียบ capsule ใหม่ขนาด 250 mg (AUC₀–∞ = 45 mg·h/L) กับ oral solution อ้างอิงขนาด 100 mg (AUC₀–∞ = 20 mg·h/L) ในอาสาสมัครกลุ่มเดียวกัน (linear PK) relative bioavailability ของ capsule เทียบกับ solution เป็นเท่าใด",
      o: ["18%", "44%", "90%", "111%", "225%"],
      a: 2,
      r: "Relative bioavailability (F_rel) เปรียบเทียบ extent of absorption ของสองผลิตภัณฑ์ที่ไม่ใช่ IV โดยมักใช้ oral solution หรือ reference product เป็นตัวเทียบ: F_rel = (AUC_test/Dose_test)/(AUC_ref/Dose_ref)\n\nCapsule: 45/250 = 0.18 ส่วน solution: 20/100 = 0.20 ได้ F_rel = 0.90 หรือ 90% แปลว่า capsule ให้ exposure ต่อ mg ประมาณ 90% ของ solution ซึ่งมักสะท้อนข้อจำกัดด้านการปลดปล่อย/การละลายของ solid dosage form ค่า F_rel เกิน 100% ได้ (ต่างจาก absolute BA) หาก test ดีกว่า reference",
      w: [
        "18% คือ AUC/dose ของ capsule (0.18) ยังไม่ได้หารด้วยค่าของ solution",
        "44% เกิดจากหาร AUC กลับด้าน (20/45) โดยไม่ปรับขนาดยา",
        "ถูก — (45/250)/(20/100) = 0.18/0.20 = 0.90",
        "111% เกิดจากหารกลับด้าน (0.20/0.18)",
        "225% คือ AUC_test/AUC_ref โดยไม่ปรับขนาดยาที่ต่างกัน 2.5 เท่า",
      ],
      k: "F_rel = (AUC_T/D_T)/(AUC_R/D_R); reference เป็น oral product ไม่ใช่ IV และ F_rel เกิน 100% ได้",
      d: "medium",
      ref: "Shargel & Yu, Applied Biopharmaceutics & Pharmacokinetics 7th ed., Ch.16",
      c: [
        "AUC/Dose (capsule) = 45/250 = 0.18",
        "AUC/Dose (solution) = 20/100 = 0.20",
        "F_rel = 0.18/0.20 = 0.90 = 90%",
      ],
    },
    {
      t: "NTI drug tightened BE limits",
      p: "บริษัทยื่นทะเบียน generic tacrolimus capsule ซึ่งเป็นยา narrow therapeutic index (NTI) ตามแนวทาง EMA ช่วงยอมรับ (acceptance range) ของ 90% CI สำหรับ AUC ควรเป็นข้อใด",
      o: [
        "69.84–143.19%",
        "80.00–125.00%",
        "85.00–117.65%",
        "90.00–111.11%",
        "95.00–105.00%",
      ],
      a: 3,
      r: "ยา NTI เช่น tacrolimus, ciclosporin, warfarin, phenytoin, levothyroxine และ digoxin มีช่วงระหว่างขนาดที่ได้ผลกับขนาดที่เป็นพิษแคบ ความแตกต่างของ exposure เล็กน้อยอาจมีผลทางคลินิก EMA จึงกำหนดให้ AUC ใช้ช่วงแคบ 90.00–111.11% (และใช้กับ Cmax ด้วยหาก Cmax สำคัญเป็นพิเศษต่อความปลอดภัย ประสิทธิภาพ หรือการติดตามระดับยา)\n\nช่วงนี้สมมาตรบน log scale (ln 0.9 = −ln 1.1111) เหมือนกับ 80.00–125.00% ส่วน FDA ใช้ reference-scaled approach ร่วมกับเกณฑ์เปรียบเทียบ within-subject variability ระหว่าง test และ reference ซึ่งต้องใช้ fully replicate design",
      w: [
        "69.84–143.19% เป็นขีดสูงสุดของการขยายเกณฑ์ (ABEL) สำหรับ Cmax ของยา highly variable ซึ่งตรงข้ามกับยา NTI",
        "80.00–125.00% เป็นเกณฑ์มาตรฐานของยาทั่วไป ไม่เพียงพอสำหรับยา NTI",
        "85.00–117.65% ไม่ใช่เกณฑ์ที่ EMA กำหนดสำหรับยา NTI",
        "ถูก — EMA กำหนด AUC ของยา NTI ที่ 90.00–111.11% (สมมาตรบน log scale)",
        "95.00–105.00% ไม่ใช่เกณฑ์ BE ที่ใช้ในแนวทางใด ๆ และแคบเกินจริง",
      ],
      k: "EMA: NTI → AUC 90.00–111.11% (และ Cmax เมื่อจำเป็น); HVD → ขยาย Cmax ได้ถึง 69.84–143.19%",
      d: "hard",
      ref: "EMA Guideline on the Investigation of Bioequivalence CPMP/EWP/QWP/1401/98 Rev.1, Section 4.1.9",
    },
  ],
];
