import type { Ip1MockDomainContent } from "@/lib/ip1-mock/types";

export const BIOPHARM: Ip1MockDomainContent = [
  // Mock Set 1
  [
    {
      t: "Passive diffusion characteristics",
      p: "ยา X ซึ่งเป็นโมเลกุลขนาดเล็ก lipophilic ไม่แตกตัวที่ pH ลำไส้ ถูกดูดซึมผ่านเยื่อบุลำไส้ด้วย passive transcellular diffusion เป็นหลัก ข้อใดเป็นลักษณะของกลไกนี้",
      o: [
        "อัตราการดูดซึมแปรผันตรงกับ concentration gradient และไม่อิ่มตัวเมื่อเพิ่มขนาดยา",
        "อัตราการดูดซึมคงที่เมื่อขนาดยาสูง เพราะ carrier อิ่มตัว",
        "ต้องใช้พลังงานจาก ATP และเคลื่อนที่สวน concentration gradient ได้",
        "ถูกยับยั้งแบบแข่งขันได้ด้วยสารที่มีโครงสร้างคล้ายกัน",
        "เกิดเฉพาะบริเวณ upper small intestine ที่มี transporter เฉพาะ (absorption window)",
      ],
      a: 0,
      r: "Passive diffusion อธิบายด้วย Fick's first law: อัตราการผ่านเยื่อ (dM/dt) = D·A·K·(C_gut − C_blood)/h ซึ่งขึ้นกับ diffusion coefficient, พื้นที่ผิว, partition coefficient และความหนาของเยื่อ โดยแรงขับคือ concentration gradient เท่านั้น\n\nเนื่องจากไม่มี carrier จึงไม่มีจุดอิ่มตัว (linear kinetics) ไม่ต้องใช้พลังงาน ไม่เกิด competitive inhibition และไม่จำกัดเฉพาะบริเวณใดของลำไส้ ยาส่วนใหญ่ (โดยเฉพาะ BCS class I/II) ถูกดูดซึมด้วยกลไกนี้ ดังนั้นปริมาณที่ถูกดูดซึมจึงเพิ่มตามขนาดยาแบบเป็นสัดส่วน",
      w: [
        "ถูก — passive diffusion ขับเคลื่อนด้วย concentration gradient ตาม Fick's law จึงเป็น first-order และไม่อิ่มตัว",
        "การอิ่มตัว (saturable, Michaelis–Menten) เป็นลักษณะของ carrier-mediated transport ไม่ใช่ passive diffusion",
        "การใช้พลังงานและสวน gradient คือ active transport (เช่น ผ่าน ABC transporter หรือ secondary active) ไม่ใช่ passive",
        "Competitive inhibition เกิดเมื่อสารแย่งจับ carrier ตัวเดียวกัน passive diffusion ไม่มีจุดจับจึงไม่เกิด",
        "Absorption window มักเกิดกับยาที่อาศัย transporter ที่มีการกระจายเฉพาะที่ เช่น riboflavin ไม่ใช่ลักษณะของ passive diffusion",
      ],
      k: "Passive diffusion = Fick's law, ตาม gradient, ไม่อิ่มตัว, ไม่ใช้พลังงาน, ไม่มี competitive inhibition",
      d: "easy",
      ref: "Shargel & Yu, Applied Biopharmaceutics & Pharmacokinetics 7th ed., Ch.13",
    },
    {
      t: "P-glycoprotein efflux interaction",
      p: "ผู้ป่วยรับประทาน digoxin ขนาดคงที่มานาน ต่อมาแพทย์เริ่มให้ verapamil ร่วมด้วย พบระดับ digoxin ในเลือดสูงขึ้นชัดเจน ทั้งที่ digoxin แทบไม่ถูก metabolize ด้วย CYP กลไกหลักทาง biopharmaceutics ที่อธิบายได้ดีที่สุดคือข้อใด",
      o: [
        "Verapamil ยับยั้ง P-glycoprotein ที่ apical membrane ของ enterocyte และที่ไต ทำให้ efflux และการขับ digoxin ลดลง",
        "Verapamil เหนี่ยวนำ P-glycoprotein ทำให้ digoxin ถูกดูดซึมกลับมากขึ้น",
        "Verapamil ยับยั้ง CYP3A4 ใน hepatocyte ทำให้ hepatic first-pass ของ digoxin ลดลง",
        "Verapamil เพิ่ม gastric pH ทำให้ digoxin ละลายได้ดีขึ้น",
        "Verapamil ทำให้เกิด complex กับ digoxin ในลำไส้และเพิ่ม permeability",
      ],
      a: 0,
      r: "P-glycoprotein (P-gp, ABCB1) เป็น ATP-dependent efflux transporter อยู่ที่ apical (luminal) membrane ของ enterocyte, canalicular membrane ของ hepatocyte และ proximal tubule ของไต ทำหน้าที่ปั๊มยากลับออกสู่ลำไส้ น้ำดี และปัสสาวะ\n\nDigoxin เป็น P-gp substrate ที่ไม่ค่อยถูก metabolize ดังนั้นปฏิกิริยาที่เพิ่มระดับ digoxin จาก verapamil, quinidine, amiodarone หรือ clarithromycin จึงเกิดจากการยับยั้ง P-gp เป็นหลัก ทั้งที่ลำไส้ (fraction absorbed เพิ่มขึ้น) และที่ไต (renal secretion ลดลง) ในทางกลับกัน P-gp inducer เช่น rifampicin หรือ St John's wort จะลดระดับ digoxin",
      w: [
        "ถูก — การยับยั้ง P-gp ทั้งที่ลำไส้และ tubule ของไตเพิ่ม bioavailability และลดการขับ digoxin",
        "การ induce P-gp จะเพิ่ม efflux ทำให้ระดับยาลดลง ไม่ใช่เพิ่มขึ้น",
        "Digoxin แทบไม่ผ่าน CYP3A4 ดังนั้นการยับยั้ง CYP3A4 ไม่ใช่กลไกหลักในกรณีนี้",
        "Verapamil ไม่มีผลเพิ่ม gastric pH อย่างมีนัยสำคัญ และ digoxin ไม่ใช่ยาที่การละลายขึ้นกับ pH",
        "ไม่มีหลักฐานการเกิด complex ระหว่าง verapamil กับ digoxin และ complexation มักลดการดูดซึมมากกว่าเพิ่ม",
      ],
      k: "Digoxin เป็น probe substrate ของ P-gp; P-gp inhibitor (verapamil, quinidine, clarithromycin) เพิ่มระดับ digoxin",
      d: "medium",
      ref: "FDA Guidance: In Vitro Drug Interaction Studies — Cytochrome P450 Enzyme- and Transporter-Mediated Drug Interactions (2020)",
    },
    {
      t: "BCS solubility across pH range",
      p: "ยา Y มีขนาดยาสูงสุดต่อครั้ง (highest single therapeutic dose) 400 mg ผลการหา equilibrium solubility ที่ 37 °C เป็นดังนี้: pH 1.2 = 8.0 mg/mL, pH 4.5 = 2.5 mg/mL, pH 6.8 = 1.2 mg/mL ตามเกณฑ์ ICH M9 ข้อใดสรุปได้ถูกต้อง",
      o: [
        "Low solubility เพราะที่ pH 6.8 ต้องใช้ตัวทำละลายประมาณ 333 mL ซึ่งเกิน 250 mL",
        "High solubility เพราะที่ pH 1.2 ต้องใช้ตัวทำละลายเพียง 50 mL",
        "High solubility เพราะค่าเฉลี่ยของ solubility ทั้งสาม pH สูงกว่า 1 mg/mL",
        "Low solubility เพราะ solubility ที่ pH 4.5 ต่ำกว่า 5 mg/mL",
        "สรุปไม่ได้ เพราะ ICH M9 ใช้ปริมาตรอ้างอิง 900 mL ตามปริมาตร dissolution vessel",
      ],
      a: 0,
      r: "ICH M9 นิยาม high solubility ว่า highest single therapeutic dose ต้องละลายได้หมดในตัวทำละลาย ≤ 250 mL ตลอดช่วง pH 1.2–6.8 ที่ 37 ± 1 °C ดังนั้นต้องใช้ค่า solubility ที่ต่ำที่สุดในช่วง pH ที่ทดสอบมาตัดสิน\n\nปริมาตรที่ต้องใช้ (dose/solubility) ที่ pH 1.2 = 400/8.0 = 50 mL, pH 4.5 = 400/2.5 = 160 mL และ pH 6.8 = 400/1.2 ≈ 333 mL เนื่องจากที่ pH 6.8 ต้องใช้มากกว่า 250 mL ยา Y จึงเป็น low solubility (ยาที่เป็น weak base มักมีปัญหาที่ pH สูงแบบนี้) ค่า 250 mL มาจากน้ำประมาณ 1 แก้ว (8 ออนซ์) ที่ใช้รับประทานยาใน BE study",
      w: [
        "ถูก — ใช้ pH ที่ solubility ต่ำที่สุด: 400/1.2 ≈ 333 mL > 250 mL จึงเป็น low solubility",
        "ต้องผ่านทุก pH ในช่วง 1.2–6.8 การดูเฉพาะ pH ที่ละลายดีที่สุดเป็นการตัดสินที่ผิด",
        "เกณฑ์ไม่ได้ใช้ค่าเฉลี่ยของ solubility แต่ใช้ปริมาตรที่ต้องใช้ละลาย dose ที่ pH เลวร้ายที่สุด",
        "ไม่มีเกณฑ์ solubility 5 mg/mL ใน BCS และที่ pH 4.5 ใช้เพียง 160 mL ซึ่งยังผ่าน",
        "ปริมาตรอ้างอิงของ BCS คือ 250 mL ไม่ใช่ 900 mL ของ dissolution vessel",
      ],
      k: "BCS high solubility: dose สูงสุดละลายใน ≤ 250 mL ทุก pH 1.2–6.8 (37 °C) ตัดสินจาก pH ที่ละลายแย่ที่สุด",
      d: "medium",
      ref: "ICH M9 Biopharmaceutics Classification System-based Biowaivers (2019), Section 2.1.1",
      c: [
        "Volume ที่ pH 1.2 = 400 mg ÷ 8.0 mg/mL = 50 mL",
        "Volume ที่ pH 4.5 = 400 ÷ 2.5 = 160 mL",
        "Volume ที่ pH 6.8 = 400 ÷ 1.2 ≈ 333 mL > 250 mL → low solubility",
      ],
    },
    {
      t: "USP 711 stage S1 decision",
      p: "ยาเม็ด immediate-release มี monograph กำหนด Q = 80% ใน 30 นาที ผล dissolution Stage S1 (6 เม็ด) ได้ 92, 88, 86, 90, 84 และ 95% ของ label claim ข้อใดเป็นการตัดสินที่ถูกต้องตาม USP <711>",
      o: [
        "ยังไม่ผ่าน S1 เพราะมี 1 เม็ดต่ำกว่า Q + 5% (85%) ต้องทดสอบต่อ Stage S2 อีก 6 เม็ด",
        "ผ่าน S1 เพราะทุกเม็ดมากกว่า Q (80%)",
        "ผ่าน S1 เพราะค่าเฉลี่ย 89.2% มากกว่า Q + 5%",
        "ไม่ผ่านทันที (reject batch) เพราะมีเม็ดต่ำกว่า Q + 5%",
        "ต้องทดสอบซ้ำ S1 ใหม่ทั้ง 6 เม็ด แล้วใช้ผลชุดใหม่แทน",
      ],
      a: 0,
      r: "USP <711> สำหรับ immediate-release กำหนดการทดสอบเป็นขั้น: S1 ทดสอบ 6 หน่วย เกณฑ์คือ 'แต่ละหน่วย ≥ Q + 5%' หากไม่ผ่านจึงไป S2 (เพิ่ม 6 หน่วยรวม 12; ค่าเฉลี่ย ≥ Q และไม่มีหน่วยใด < Q − 15%) และ S3 (เพิ่ม 12 รวม 24)\n\nในกรณีนี้ Q + 5% = 85% มีเม็ดหนึ่งได้ 84% จึงไม่ผ่าน S1 แต่ไม่ได้หมายความว่า batch ไม่ผ่าน ต้องทำ S2 ต่อ ค่าเฉลี่ยไม่ใช่เกณฑ์ของ S1 และการทดสอบซ้ำแทนผลเดิมถือเป็น testing into compliance ซึ่งไม่ยอมรับใน GMP",
      w: [
        "ถูก — S1 ต้องทุกหน่วย ≥ Q + 5% = 85%; มี 84% จึงต้องต่อ S2",
        "เกณฑ์ S1 ไม่ใช่ ≥ Q แต่เป็น ≥ Q + 5% สำหรับทุกหน่วย",
        "S1 ไม่ได้ใช้ค่าเฉลี่ย ค่าเฉลี่ยเป็นเกณฑ์ของ S2 และ S3",
        "การไม่ผ่าน S1 ไม่ใช่ความล้มเหลวของ batch แต่เป็นการเลื่อนไปทดสอบขั้นถัดไปตามแผน acceptance table",
        "การทดสอบซ้ำเพื่อแทนผลเดิมโดยไม่มีเหตุ invalidation คือ testing into compliance ซึ่งยอมรับไม่ได้",
      ],
      k: "USP <711> IR: S1 = 6 หน่วย ทุกหน่วย ≥ Q+5%; ไม่ผ่านให้ไป S2 ไม่ใช่ reject",
      d: "easy",
      ref: "USP <711> Dissolution, Acceptance Table 1",
    },
    {
      t: "USP Apparatus 4 flow-through selection",
      p: "ทีม R&D พัฒนาวิธี dissolution ของยาเม็ดที่ API ละลายน้ำได้ต่ำมาก (practically insoluble) ใน paddle 900 mL ไม่สามารถรักษา sink condition ได้แม้เติม surfactant ในระดับที่ยอมรับได้ และต้องการเปลี่ยน pH ของ medium ระหว่างการทดสอบได้ง่าย อุปกรณ์ USP ใดเหมาะสมที่สุด",
      o: [
        "Apparatus 4 (flow-through cell) แบบ open-loop ที่ปั๊ม medium ใหม่ผ่าน cell ตลอดเวลา",
        "Apparatus 1 (basket) ที่ 100 rpm ใน 900 mL",
        "Apparatus 5 (paddle over disk)",
        "Apparatus 6 (rotating cylinder)",
        "Apparatus 2 (paddle) ที่ลดปริมาตรเป็น 500 mL",
      ],
      a: 0,
      r: "USP Apparatus 4 (flow-through cell) ให้ medium ไหลผ่าน cell ที่บรรจุตัวอย่างอย่างต่อเนื่อง ในแบบ open-loop จะใช้ medium ใหม่ตลอด จึงรักษา sink condition ได้แม้ยาละลายน้อยมาก และสามารถเปลี่ยน medium (เช่น pH gradient) ได้ระหว่างการทดสอบ เหมาะกับยาละลายยาก, powders/granules, implants, suppositories และ microspheres\n\nApparatus 1/2 เป็นระบบปริมาตรคงที่ (closed vessel) การลดปริมาตรยิ่งทำให้ sink แย่ลง ส่วน Apparatus 5 และ 6 ออกแบบมาสำหรับ transdermal delivery systems",
      w: [
        "ถูก — flow-through cell แบบ open-loop ให้ medium ใหม่ต่อเนื่อง จึงรักษา sink และเปลี่ยน pH ได้สะดวก",
        "Basket ยังเป็น vessel ปริมาตรคงที่ 900 mL จึงไม่แก้ปัญหา sink ของยาที่ละลายยากมาก",
        "Paddle over disk ใช้สำหรับ transdermal patch ไม่ใช่ยาเม็ดรับประทาน",
        "Rotating cylinder ใช้สำหรับ transdermal patch เช่นกัน",
        "การลดปริมาตร medium ยิ่งทำให้ความเข้มข้นเข้าใกล้ saturation มากขึ้น ทำให้ sink condition แย่ลง",
      ],
      k: "App 4 flow-through (open-loop) = ยาละลายยากมาก/ต้องการ sink ไม่จำกัด/เปลี่ยน pH ได้; App 5, 6 = transdermal",
      d: "medium",
      ref: "USP <711> Dissolution; USP <1092> The Dissolution Procedure: Development and Validation",
    },
    {
      t: "f2 similarity factor calculation",
      p: "เปรียบเทียบ dissolution profile ของ test กับ reference (n = 12, CV ผ่านเกณฑ์) ค่าเฉลี่ย % dissolved ที่ 10, 15, 20, 30 นาที: Reference = 40, 58, 72, 86 และ Test = 46, 62, 70, 83 ค่า f2 ประมาณเท่าใด",
      o: ["5.9", "38.2", "54.5", "69.1", "83.1"],
      a: 3,
      r: "f2 = 50 × log₁₀{[1 + (1/n) Σ(Rt − Tt)²]^−0.5 × 100} เป็นการแปลงค่า mean squared difference ระหว่างสอง profile ให้เป็นสเกล 0–100 โดย f2 = 100 เมื่อเหมือนกันทุกจุด และ f2 = 50 สอดคล้องกับความต่างเฉลี่ยประมาณ 10% ทุกจุด เกณฑ์ similarity คือ f2 ≥ 50\n\nในโจทย์มี 4 จุดเวลา และมีเพียงจุดเดียว (30 นาทีของ reference) ที่เกิน 85% จึงใช้ครบ 4 จุดได้ ผลรวมกำลังสองของผลต่าง = 36 + 16 + 4 + 9 = 65 หาร n = 4 ได้ 16.25 จึงได้ f2 ≈ 69.1 ซึ่งแสดงว่า profile คล้ายกัน",
      w: [
        "5.9 คือค่า f1 (Σ|R−T|/ΣR × 100 = 15/256) ไม่ใช่ f2",
        "38.2 เกิดจากลืมยกกำลัง −0.5 (ไม่ถอดราก) ของ [1 + MSD]",
        "54.5 เกิดจากใช้ผลรวมกำลังสอง (65) โดยไม่หารด้วยจำนวนจุดเวลา n",
        "ถูก — Σ(R−T)² = 65, /4 = 16.25, f2 = 50·log(100/√17.25) ≈ 69.1",
        "83.1 เกิดจากใช้ผลรวมค่าสัมบูรณ์ของผลต่าง (15) แทนผลรวมกำลังสอง",
      ],
      k: "f2 = 50·log{100/√[1 + Σ(R−T)²/n]}; f2 ≥ 50 = similar; หาร n ก่อนบวก 1 แล้วถอดราก",
      d: "hard",
      ref: "FDA Guidance: Dissolution Testing of Immediate Release Solid Oral Dosage Forms (1997); EMA CPMP/EWP/QWP/1401/98 Rev.1 Appendix I",
      c: [
        "ผลต่าง R − T = −6, −4, +2, +3",
        "Σ(R − T)² = 36 + 16 + 4 + 9 = 65",
        "MSD = 65/4 = 16.25 → 1 + 16.25 = 17.25",
        "17.25^−0.5 × 100 = 100/4.153 = 24.08",
        "f2 = 50 × log₁₀(24.08) = 50 × 1.382 ≈ 69.1",
      ],
    },
    {
      t: "Absolute bioavailability calculation",
      p: "ในการศึกษาใน healthy volunteers ให้ยา Z ทางหลอดเลือดดำขนาด 50 mg ได้ AUC₀–∞ = 10 mg·h/L และให้ยาเม็ดรับประทานขนาด 200 mg (crossover ในคนเดียวกัน) ได้ AUC₀–∞ = 28 mg·h/L สมมติ PK เป็นแบบ linear ค่า absolute bioavailability (F) ของยาเม็ดเป็นเท่าใด",
      o: ["14%", "20%", "70%", "143%", "280%"],
      a: 2,
      r: "Absolute bioavailability เปรียบเทียบ extravascular กับ IV (F_IV = 1) โดยต้องปรับด้วยขนาดยา: F = (AUC_oral/Dose_oral)/(AUC_IV/Dose_IV) ซึ่งใช้ได้เมื่อ clearance คงที่ (linear PK) และวัดในคนเดียวกัน\n\nAUC ต่อ mg ของ oral = 28/200 = 0.14 ส่วนของ IV = 10/50 = 0.20 ดังนั้น F = 0.14/0.20 = 0.70 หรือ 70% ความผิดพลาดที่พบบ่อยคือไม่ปรับขนาดยา (ได้ 280%) หรือปรับขนาดยากลับด้าน ค่า F ที่ได้สะท้อนผลรวมของ fraction absorbed และ first-pass ทั้งที่ลำไส้และตับ",
      w: [
        "14% คือ AUC/dose ของยารับประทาน (0.14) โดยยังไม่ได้หารด้วยค่าของ IV",
        "20% คือ AUC/dose ของ IV (10/50 = 0.20) ซึ่งเป็นตัวหาร ไม่ใช่ค่า F",
        "ถูก — F = (28/200)/(10/50) = 0.14/0.20 = 0.70",
        "143% เกิดจากหารกลับด้าน (0.20/0.14) ค่า F เกิน 100% ไม่สมเหตุผลสำหรับ absolute BA",
        "280% คือ AUC_oral/AUC_IV โดยไม่ได้ปรับขนาดยาที่ต่างกัน 4 เท่า",
      ],
      k: "F_abs = (AUC_po/D_po)/(AUC_iv/D_iv) — ต้อง dose-normalize เสมอ และใช้ได้เมื่อ PK เป็น linear",
      d: "medium",
      ref: "Shargel & Yu, Applied Biopharmaceutics & Pharmacokinetics 7th ed., Ch.16",
      c: [
        "AUC/Dose (oral) = 28/200 = 0.14 h/L",
        "AUC/Dose (IV) = 10/50 = 0.20 h/L",
        "F = 0.14/0.20 = 0.70 = 70%",
      ],
    },
    {
      t: "Washout period in crossover BE",
      p: "บริษัทวางแผน BE study แบบ 2×2 crossover สำหรับยาเม็ด IR ที่มี terminal elimination half-life ประมาณ 20 ชั่วโมง (ไม่มี metabolite ที่มี half-life ยาวกว่า) ระยะ washout ระหว่าง 2 periods ข้อใดเหมาะสมที่สุด",
      o: [
        "อย่างน้อยประมาณ 100 ชั่วโมง (≥ 5 half-lives) เช่น กำหนด 7 วัน",
        "24 ชั่วโมง เพราะยาให้วันละครั้ง",
        "40 ชั่วโมง (2 half-lives) ก็เพียงพอเพราะยาเหลือ 25%",
        "ไม่ต้องมี washout ถ้าสุ่มลำดับการได้รับยา (randomized sequence)",
        "อย่างน้อย 30 วัน ทุกกรณีเพื่อความปลอดภัย",
      ],
      a: 0,
      r: "Washout ใน crossover design มีไว้ป้องกัน carry-over จาก period แรกไปปน period ที่สอง หลัก EMA/FDA คือ washout ควร ≥ 5 elimination half-lives ของ analyte (ยาหรือ metabolite ที่วัด) ซึ่งเหลือยาประมาณ 3% ของเดิม\n\nสำหรับ t½ = 20 h, 5 × 20 = 100 h (~4.2 วัน) การเลือก 7 วันจึงปลอดภัยและสะดวกในการจัดการ หากพบความเข้มข้น pre-dose ใน period 2 เกิน 5% ของ Cmax ต้องตัดข้อมูลของอาสาสมัครรายนั้นออกจากการวิเคราะห์ ส่วนการกำหนดนานเกินจำเป็นมากเพิ่ม dropout โดยไม่ได้ประโยชน์",
      w: [
        "ถูก — 5 × 20 h = 100 h ยาเหลือ ~3% การปัดเป็น 7 วันเป็นทางปฏิบัติที่เหมาะสม",
        "24 ชั่วโมงเท่ากับ 1.2 half-lives ยายังเหลือเกือบครึ่ง ทำให้เกิด carry-over",
        "2 half-lives ยังเหลือยา 25% ซึ่งมาก จะรบกวน PK ของ period ถัดไป",
        "Randomization ช่วยกระจาย period/sequence effect แต่ไม่ได้กำจัด carry-over จึงยังต้องมี washout",
        "ไม่จำเป็นต้องนานถึง 30 วัน การนานเกินไปเพิ่ม dropout และอาจเปลี่ยนสภาวะทางสรีรวิทยาของอาสาสมัคร",
      ],
      k: "Washout ≥ 5 t½ ของ analyte; pre-dose > 5% Cmax ใน period ถัดไป → ตัดข้อมูลรายนั้น",
      d: "medium",
      ref: "EMA Guideline on the Investigation of Bioequivalence CPMP/EWP/QWP/1401/98 Rev.1, Section 4.1.1",
    },
    {
      t: "90% CI decision with Cmax failing",
      p: "ผล BE study (2×2 crossover, fasting, n = 28) ของยาเม็ด generic เทียบ reference: AUC₀–t GMR = 98.4% (90% CI 92.10–105.13%) และ Cmax GMR = 89.9% (90% CI 79.62–101.47%) ข้อใดสรุปได้ถูกต้องที่สุด",
      o: [
        "ไม่แสดง BE เพราะ lower limit ของ 90% CI ของ Cmax ต่ำกว่า 80.00% แม้ point estimate จะอยู่ในช่วง",
        "แสดง BE เพราะ point estimate ของทั้ง AUC และ Cmax อยู่ในช่วง 80.00–125.00%",
        "แสดง BE เพราะ AUC เป็นตัวแปรหลัก ส่วน Cmax ใช้ประกอบเท่านั้น",
        "แสดง BE เพราะปัด 79.62% เป็น 80% ได้",
        "ไม่แสดง BE เพราะ GMR ของ Cmax ไม่อยู่ในช่วง 90–110%",
      ],
      a: 0,
      r: "เกณฑ์ BE มาตรฐาน (average bioequivalence) คือ 90% confidence interval ของ geometric mean ratio (test/reference) ของทั้ง AUC และ Cmax ต้องอยู่ภายใน 80.00–125.00% ทั้งช่วง ไม่ใช่เฉพาะ point estimate\n\nการทดสอบนี้เทียบเท่า two one-sided tests (TOST) ที่ α = 0.05 แต่ละด้าน ในกรณีนี้ Cmax มี lower limit 79.62% ซึ่งต่ำกว่า 80.00% (EMA กำหนดให้รายงานและตัดสินที่ทศนิยม 2 ตำแหน่ง ห้ามปัดเข้า) จึงไม่ผ่าน แม้ AUC ผ่าน ทั้งนี้ point estimate ที่ต่ำ (~90%) ร่วมกับ CI ที่กว้าง แสดงว่าอัตราการดูดซึมของ test อาจช้ากว่าและ/หรือ variability สูง ซึ่งอาจต้องการ sample size มากขึ้นหรือปรับสูตร",
      w: [
        "ถูก — ต้องให้ 90% CI ทั้งช่วงของทั้ง AUC และ Cmax อยู่ใน 80.00–125.00%; Cmax lower limit 79.62% ไม่ผ่าน",
        "Point estimate ในช่วงยังไม่พอ เกณฑ์ใช้ 90% CI ทั้งช่วง",
        "Cmax เป็น primary parameter สำหรับ rate of absorption ต้องผ่านเกณฑ์เช่นเดียวกับ AUC",
        "เกณฑ์ใช้ค่า 80.00% ที่ทศนิยม 2 ตำแหน่ง ไม่อนุญาตให้ปัดค่าเพื่อให้ผ่าน",
        "ช่วง 90–110% ไม่ใช่เกณฑ์ point estimate ของ BE มาตรฐาน (ช่วงแคบใช้กับ CI ของยา NTI)",
      ],
      k: "BE ผ่านเมื่อ 90% CI ของ GMR (AUC และ Cmax) อยู่ใน 80.00–125.00% ทั้งช่วง ห้ามปัดเศษ",
      d: "hard",
      ref: "EMA Guideline on the Investigation of Bioequivalence CPMP/EWP/QWP/1401/98 Rev.1, Section 4.1.8",
    },
    {
      t: "Pharmaceutical alternatives vs equivalents",
      p: "ผลิตภัณฑ์ A คือ doxycycline hyclate 100 mg capsule ผลิตภัณฑ์ B คือ doxycycline monohydrate 100 mg tablet (ปริมาณ doxycycline base เท่ากัน) ทั้งสองผ่านมาตรฐานตำรายา ความสัมพันธ์ระหว่าง A และ B ตรงกับข้อใดมากที่สุด",
      o: [
        "Pharmaceutical alternatives เพราะมี therapeutic moiety เดียวกันแต่ต่างทั้ง salt form และ dosage form",
        "Pharmaceutical equivalents เพราะมี doxycycline base ในปริมาณเท่ากัน",
        "Therapeutic equivalents โดยอัตโนมัติ เพราะผ่านมาตรฐานตำรายาเหมือนกัน",
        "Bioequivalent โดยไม่ต้องทำการศึกษา เพราะ doxycycline เป็น BCS class I",
        "Generic ของกันและกัน ใช้แทนกันได้โดยไม่ต้องมีข้อมูลเพิ่มเติม",
      ],
      a: 0,
      r: "Pharmaceutical equivalents ต้องมี active ingredient เดียวกัน (salt/ester เดียวกัน) ในปริมาณเท่ากัน dosage form เดียวกัน และ route เดียวกัน ผ่านมาตรฐานเดียวกัน ส่วน pharmaceutical alternatives คือมี therapeutic moiety เดียวกันแต่ต่าง salt, ester, complex, dosage form หรือ strength\n\nA กับ B ต่างทั้ง salt (hyclate vs monohydrate) และ dosage form (capsule vs tablet) จึงเป็น pharmaceutical alternatives การเป็น therapeutic equivalent ต้องเป็น pharmaceutical equivalent และ bioequivalent พร้อมกัน ดังนั้น alternatives ไม่สามารถถือว่า interchangeable โดยอัตโนมัติ แม้ผ่านมาตรฐานตำรายาทั้งคู่",
      w: [
        "ถูก — therapeutic moiety เดียวกันแต่ต่าง salt และ dosage form = pharmaceutical alternatives",
        "Pharmaceutical equivalents ต้องเป็น salt และ dosage form เดียวกัน ปริมาณ base เท่ากันยังไม่พอ",
        "การผ่านมาตรฐานตำรายาไม่ได้รับประกัน bioequivalence; TE = PE + BE",
        "BCS-based biowaiver ไม่ได้ทำให้เป็น BE โดยอัตโนมัติ และไม่ครอบคลุมการเปลี่ยน dosage form และ salt แบบนี้โดยไม่มีการประเมิน",
        "การใช้แทนกัน (interchangeability) ต้องมีหลักฐาน therapeutic equivalence ไม่ใช่สรุปจากการมี moiety เดียวกัน",
      ],
      k: "PE = same API/salt, strength, dosage form, route; ต่าง salt/dosage form = pharmaceutical alternatives; TE = PE + BE",
      d: "hard",
      ref: "FDA Orange Book Preface (Approved Drug Products with Therapeutic Equivalence Evaluations), Therapeutic Equivalence-Related Terms",
    },
  ],
  // Mock Set 2
  [
    {
      t: "Saturable carrier-mediated absorption",
      p: "ข้อมูลยา gabapentin ระบุว่า bioavailability ลดลงเมื่อเพิ่มขนาดยา (ประมาณ 60% ที่ 900 mg/วัน เหลือราว 27% ที่ 4,800 mg/วัน) ปรากฏการณ์นี้อธิบายได้ดีที่สุดด้วยกลไกใด",
      o: [
        "การดูดซึมอาศัย L-amino acid transporter ซึ่งอิ่มตัวได้ที่ขนาดยาสูง",
        "Hepatic first-pass metabolism เพิ่มขึ้นเมื่อขนาดยาสูงขึ้น",
        "ยาเกิด precipitation ในกระเพาะเพราะ solubility ต่ำมากในกรด",
        "P-glycoprotein ถูก induce เมื่อได้รับยาขนาดสูง",
        "Passive diffusion ลดลงเพราะ concentration gradient สูงเกินไป",
      ],
      a: 0,
      r: "Carrier-mediated transport มีจำนวน transporter จำกัด จึงเป็นไปตาม Michaelis–Menten: ที่ความเข้มข้นต่ำอัตราการดูดซึมเพิ่มตามความเข้มข้น แต่เมื่อความเข้มข้นในลำไส้สูงกว่า Km มาก carrier จะอิ่มตัว อัตราการดูดซึมเข้าใกล้ Vmax ทำให้สัดส่วนที่ถูกดูดซึม (F) ลดลงเมื่อเพิ่มขนาดยา (less than dose-proportional)\n\nGabapentin เป็น amino acid analogue ที่ถูกดูดซึมผ่าน system-L amino acid transporter ในลำไส้เล็กส่วนต้น จึงมี bioavailability ลดลงตามขนาดยา และไม่ถูก metabolize (ขับทางไตเป็นรูปเดิม) ทางแก้ในทางคลินิกคือแบ่งให้หลายครั้งต่อวัน ตัวอย่างอื่นของ saturable uptake เช่น riboflavin และ levodopa",
      w: [
        "ถูก — transporter มีจำนวนจำกัด อิ่มตัวที่ขนาดยาสูง ทำให้ F ลดลงแบบ dose-dependent",
        "Gabapentin แทบไม่ถูก metabolize และ first-pass ที่อิ่มตัวได้จะทำให้ F เพิ่มขึ้นเมื่อขนาดยาสูง ไม่ใช่ลดลง",
        "Gabapentin ละลายน้ำได้ดีมาก (BCS high solubility) ปัญหาไม่ได้อยู่ที่การละลาย",
        "Gabapentin ไม่ใช่ P-gp substrate ที่สำคัญ และ induction ต้องใช้เวลา ไม่อธิบายความสัมพันธ์กับขนาดยาครั้งเดียว",
        "Passive diffusion ยิ่ง gradient สูงยิ่งดูดซึมมาก ไม่มีการลดลงของสัดส่วนที่ดูดซึม",
      ],
      k: "F ลดลงเมื่อเพิ่มขนาดยา → นึกถึง saturable uptake transporter (เช่น gabapentin ผ่าน LAT)",
      d: "medium",
      ref: "Shargel & Yu, Applied Biopharmaceutics & Pharmacokinetics 7th ed., Ch.13; Neurontin (gabapentin) Prescribing Information",
    },
    {
      t: "Gastric emptying and Tmax",
      p: "ผู้ป่วยรับประทานยาเม็ด paracetamol ซึ่งถูกดูดซึมส่วนใหญ่ที่ลำไส้เล็ก โดยรับประทานพร้อม metoclopramide ผลต่อ PK ของ paracetamol ที่คาดได้คือข้อใด",
      o: [
        "Tmax สั้นลงและ Cmax สูงขึ้น เพราะ gastric emptying เร็วขึ้น",
        "Tmax ยาวขึ้นและ Cmax ต่ำลง เพราะยาค้างในกระเพาะนานขึ้น",
        "AUC ลดลงครึ่งหนึ่ง เพราะยาผ่านลำไส้เร็วเกินไป",
        "ไม่มีผลใด ๆ เพราะ paracetamol ถูกดูดซึมแบบ passive diffusion",
        "Tmax ไม่เปลี่ยนแต่ elimination half-life สั้นลง",
      ],
      a: 0,
      r: "สำหรับยาที่ดูดซึมได้ดีที่ลำไส้เล็ก gastric emptying เป็นขั้นตอนกำหนดอัตรา (rate-limiting) ของการเข้าถึงบริเวณดูดซึม Metoclopramide (prokinetic) เร่ง gastric emptying ทำให้ยาไปถึงลำไส้เล็กเร็ว Tmax สั้นลงและ Cmax สูงขึ้น ในขณะที่ยาที่ชะลอ gastric emptying เช่น anticholinergic (propantheline) หรือ opioids ให้ผลตรงข้าม\n\nสำหรับยาที่ดูดซึมได้สมบูรณ์อย่าง paracetamol AUC (extent) มักเปลี่ยนน้อย เพราะการเปลี่ยนแปลงหลักคือ rate การดูดซึม paracetamol absorption จึงถูกใช้เป็น marker ของ gastric emptying ในงานวิจัย",
      w: [
        "ถูก — prokinetic เร่ง gastric emptying ยาถึงลำไส้เล็กเร็ว จึงดูดซึมเร็ว Tmax สั้น Cmax สูง",
        "ผลแบบนี้เกิดกับยาที่ชะลอ gastric emptying เช่น propantheline ไม่ใช่ metoclopramide",
        "Paracetamol ดูดซึมเร็วและสมบูรณ์ การเร่ง transit ไม่ได้ลด extent ลงมากถึงครึ่ง",
        "แม้เป็น passive diffusion แต่อัตราการดูดซึมยังขึ้นกับเวลาที่ยาไปถึงลำไส้เล็ก",
        "Metoclopramide ไม่ได้เปลี่ยน elimination ของ paracetamol ผลอยู่ที่ระยะ absorption",
      ],
      k: "Gastric emptying กำหนด rate: เร่ง (metoclopramide) → Tmax สั้น Cmax สูง; ชะลอ (anticholinergic, opioid) → ตรงข้าม",
      d: "easy",
      ref: "Aulton's Pharmaceutics 5th ed., Ch.19 Gastrointestinal Tract — Physiology and Drug Absorption",
    },
    {
      t: "ICH M9 high permeability criterion",
      p: "ตามแนวทาง ICH M9 การจัดยาเป็น high permeability โดยใช้ข้อมูลในมนุษย์ ข้อใดเป็นเกณฑ์ที่ถูกต้อง",
      o: [
        "Absolute bioavailability ≥ 85% หรือ ≥ 85% ของขนาดยาถูกพบในปัสสาวะเป็นยาเดิมรวมกับ metabolites (mass balance)",
        "Absolute bioavailability ≥ 50% ในอาสาสมัครอย่างน้อย 12 คน",
        "Log P ของยามากกว่า 3",
        "ยาถูก metabolize ผ่าน CYP3A4 ไม่น้อยกว่า 50%",
        "Cmax ถึงภายใน 1 ชั่วโมงหลังรับประทาน",
      ],
      a: 0,
      r: "ICH M9 ใช้ extent of absorption ในมนุษย์เป็นหลักในการตัดสิน permeability: high permeability เมื่อ absolute bioavailability ≥ 85% หรือ mass balance แสดงว่า ≥ 85% ของขนาดยาที่ให้ถูกพบในปัสสาวะเป็นยาเดิม หรือรวมกับ phase 1 oxidative และ phase 2 conjugative metabolites (หรือพบในอุจจาระเฉพาะในรูป metabolite)\n\nข้อมูลจาก Caco-2 monolayer ที่ validate แล้วใช้สนับสนุนได้ แต่ค่า log P, รูปแบบ metabolism หรือ Tmax ไม่ใช่เกณฑ์ของ BCS permeability เพราะไม่ได้บอก fraction absorbed โดยตรง",
      w: [
        "ถูก — ICH M9 ใช้ absolute BA ≥ 85% หรือ mass balance ≥ 85% เป็นเกณฑ์ high permeability",
        "50% เป็นเกณฑ์ที่ต่ำเกินไป ICH M9 ใช้ 85% (แนวทางเดิมบางฉบับใช้ 90%)",
        "Log P บ่งบอก lipophilicity แต่ไม่ใช่เกณฑ์ BCS และ log P สูงไม่รับประกันการดูดซึม",
        "การถูก metabolize ผ่าน CYP3A4 ไม่ได้บอก fraction absorbed (BDDCS ใช้ extent of metabolism รวมแต่ไม่ใช่เกณฑ์นี้)",
        "Tmax สะท้อน rate of absorption ไม่ใช่ extent ของการดูดซึม",
      ],
      k: "ICH M9 high permeability: absolute BA ≥ 85% หรือ mass balance ≥ 85% (ยาเดิม + metabolites ในปัสสาวะ)",
      d: "easy",
      ref: "ICH M9 Biopharmaceutics Classification System-based Biowaivers (2019), Section 2.1.2",
    },
    {
      t: "BCS class III biowaiver conditions",
      p: "บริษัทต้องการขอ BCS-based biowaiver สำหรับยาเม็ด IR ของ API ที่เป็น BCS class III (high solubility, low permeability) ข้อใดเป็นเงื่อนไขตาม ICH M9 ที่ถูกต้อง",
      o: [
        "ทั้ง test และ reference ต้อง very rapidly dissolving (≥ 85% ใน 15 นาที) และ excipients ต้องเหมือนกันเชิงคุณภาพและใกล้เคียงกันเชิงปริมาณ",
        "ต้อง rapidly dissolving (≥ 85% ใน 30 นาที) และมี f2 ≥ 50 ใน 3 media โดย excipients ต่างกันได้อย่างอิสระ",
        "ต้องมี dissolution ≥ 85% ใน 60 นาทีใน FaSSIF เท่านั้น",
        "Class III ไม่สามารถขอ biowaiver ได้ในทุกกรณี ต้องทำ in vivo BE",
        "ต้องแสดง IVIVC Level A ก่อนจึงขอ biowaiver ได้",
      ],
      a: 0,
      r: "สำหรับ BCS class III การดูดซึมถูกจำกัดด้วย permeability ซึ่ง excipients บางชนิดสามารถเปลี่ยนได้ (เช่น sugar alcohols อย่าง sorbitol/mannitol ลด transit time และลดการดูดซึม, surfactant อาจเพิ่ม permeability) ICH M9 จึงเข้มงวดกว่า class I\n\nเงื่อนไขคือ test และ reference ต้อง very rapidly dissolving (≥ 85% ใน 15 นาที) ในทั้ง pH 1.2, 4.5, 6.8 และ excipients ต้องเหมือนกันเชิงคุณภาพ (qualitatively the same) และใกล้เคียงกันเชิงปริมาณ (quantitatively very similar) ตามขอบเขตที่กำหนด ส่วน class I ยอมให้ rapidly dissolving (≥ 85% ใน 30 นาที) พร้อม f2 และ excipients ต่างได้มากกว่า โดยยังต้องประเมินผลของ excipient ต่อการดูดซึม",
      w: [
        "ถูก — class III ต้อง very rapid dissolution (≥ 85%/15 นาที) และ excipients qualitatively same, quantitatively very similar",
        "เกณฑ์ rapid (30 นาที) + f2 เป็นทางเลือกสำหรับ class I ไม่ใช่ class III และ excipients ต่างอย่างอิสระไม่ได้",
        "BCS biowaiver ใช้ compendial buffers pH 1.2, 4.5, 6.8 ไม่ใช่ FaSSIF และเวลา 60 นาทีไม่ใช่เกณฑ์",
        "ICH M9 อนุญาต biowaiver สำหรับ class III ภายใต้เงื่อนไขที่เข้มงวด ไม่ได้ห้ามทุกกรณี",
        "IVIVC ไม่ใช่เงื่อนไขของ BCS-based biowaiver ซึ่งเป็นคนละแนวทางกัน",
      ],
      k: "Biowaiver class I: ≥ 85% ใน 30 นาที (+f2) หรือ 15 นาที; class III: ต้อง ≥ 85% ใน 15 นาที + excipients Q1/Q2 ใกล้เคียง",
      d: "hard",
      ref: "ICH M9 Biopharmaceutics Classification System-based Biowaivers (2019), Sections 3.1–3.2",
    },
    {
      t: "USP 711 stage S2 evaluation",
      p: "ยาเม็ด IR มี Q = 80% ใน 45 นาที Stage S1 ได้ 88, 83, 90, 79, 86, 91% จึงทดสอบ S2 อีก 6 เม็ดได้ 84, 82, 87, 76, 81, 85% ข้อใดสรุปได้ถูกต้อง",
      o: [
        "ผ่านที่ S2 เพราะค่าเฉลี่ย 12 เม็ด (84.3%) ≥ Q และไม่มีเม็ดใดต่ำกว่า Q − 15% (65%)",
        "ไม่ผ่าน S2 เพราะมี 2 เม็ดต่ำกว่า Q (79% และ 76%) ต้องทำ S3",
        "ไม่ผ่าน S2 เพราะมีหลายเม็ดต่ำกว่า Q + 5%",
        "ผ่านที่ S2 แต่ต้องรายงานเฉพาะค่าเฉลี่ยของ S2 (82.5%)",
        "ต้องไป S3 เพราะ S2 ต้องให้ทุกเม็ดอยู่ในช่วง Q ถึง Q + 10%",
      ],
      a: 0,
      r: "เกณฑ์ S2 ของ USP <711>: ใช้ผลรวม 12 หน่วย (S1 + S2) ค่าเฉลี่ย ≥ Q และไม่มีหน่วยใดต่ำกว่า Q − 15% เกณฑ์ไม่ได้ห้ามมีหน่วยที่ต่ำกว่า Q\n\nผลรวม S1 = 517 และ S2 = 495 รวม 1,012 หาร 12 = 84.3% ≥ 80% และค่าต่ำสุด 76% ยังสูงกว่า Q − 15% = 65% จึงผ่านที่ S2 การมีบางเม็ดต่ำกว่า Q เป็นสิ่งที่เกณฑ์ S2 ยอมรับได้ ตราบใดที่ไม่ต่ำกว่า Q − 15%",
      w: [
        "ถูก — mean 12 หน่วย = 84.3% ≥ 80% และค่าต่ำสุด 76% > 65% ผ่าน S2",
        "S2 ยอมให้บางเม็ดต่ำกว่า Q ได้ ข้อห้ามคือต่ำกว่า Q − 15%",
        "เกณฑ์ Q + 5% ต่อหน่วยใช้เฉพาะ S1",
        "ค่าเฉลี่ยของ S2 ต้องคิดรวม 12 หน่วย (S1 + S2) ไม่ใช่เฉพาะ 6 หน่วยหลัง",
        "ไม่มีเกณฑ์ช่วง Q ถึง Q + 10% สำหรับ IR ใน USP <711>",
      ],
      k: "S2: 12 หน่วย mean ≥ Q และไม่มีหน่วยใด < Q − 15%",
      d: "medium",
      ref: "USP <711> Dissolution, Acceptance Table 1",
      c: [
        "ผลรวม S1 = 88 + 83 + 90 + 79 + 86 + 91 = 517",
        "ผลรวม S2 = 84 + 82 + 87 + 76 + 81 + 85 = 495",
        "Mean 12 หน่วย = 1,012/12 = 84.3% ≥ 80%",
        "Q − 15% = 65%; ค่าต่ำสุด 76% > 65% → ผ่าน S2",
      ],
    },
    {
      t: "FaSSIF vs FeSSIF composition",
      p: "นักวิจัยต้องการทำนาย food effect ของยา BCS class II ที่เป็น lipophilic โดยใช้ biorelevant dissolution ข้อใดอธิบายความแตกต่างระหว่าง FaSSIF และ FeSSIF (สูตรดั้งเดิม) ได้ถูกต้อง",
      o: [
        "FeSSIF มี sodium taurocholate และ lecithin สูงกว่า (ประมาณ 15 mM vs 3 mM ของ bile salt) และ pH ต่ำกว่า (5.0 vs 6.5)",
        "FeSSIF มี pH สูงกว่า (7.5 vs 6.5) และไม่มี bile salt",
        "FaSSIF มี pepsin และ pH 1.2 ส่วน FeSSIF มี pancreatin และ pH 6.8",
        "ทั้งสองมีองค์ประกอบเหมือนกัน ต่างกันเพียงปริมาตรที่ใช้ทดสอบ",
        "FaSSIF ใช้ SLS 1% เพื่อเลียนแบบ bile salt ส่วน FeSSIF ใช้ SLS 2%",
      ],
      a: 0,
      r: "Biorelevant media จำลองของเหลวในลำไส้เล็กส่วนต้นในสภาวะอดอาหาร (fasted) และหลังอาหาร (fed) FaSSIF ดั้งเดิมมี sodium taurocholate 3 mM และ lecithin 0.75 mM ที่ pH 6.5 ส่วน FeSSIF มี taurocholate 15 mM และ lecithin 3.75 mM ที่ pH 5.0 (อาหารและกรดไขมันทำให้ pH ต่ำลง และ bile ถูกหลั่งมากขึ้น)\n\nMixed micelles ของ bile salt/lecithin ช่วยเพิ่ม solubilization ของยา lipophilic ดังนั้นถ้ายา BCS II ละลายใน FeSSIF ได้มากกว่า FaSSIF อย่างชัดเจน มักทำนายได้ว่าจะมี positive food effect ส่วน SLS เป็น synthetic surfactant ใน QC media ไม่ใช่ biorelevant",
      w: [
        "ถูก — FeSSIF มี bile salt/lecithin สูงกว่าราว 4–5 เท่า และ pH 5.0 ต่ำกว่า FaSSIF (6.5)",
        "FeSSIF มี pH ต่ำกว่า FaSSIF และมี bile salt สูงกว่า ไม่ใช่ไม่มี",
        "Medium ที่มี pepsin pH ~1.6 คือ FaSSGF (gastric) ไม่ใช่ FaSSIF; FeSSIF ไม่ได้ใช้ pancreatin เป็นองค์ประกอบหลัก",
        "องค์ประกอบต่างกันชัดเจนทั้งความเข้มข้นของ bile salt, lecithin และ pH",
        "SLS เป็น synthetic surfactant สำหรับ QC media ไม่ใช่องค์ประกอบของ biorelevant media",
      ],
      k: "FaSSIF: pH 6.5, taurocholate 3 mM; FeSSIF: pH 5.0, taurocholate 15 mM — ใช้ทำนาย food effect ของ BCS II",
      d: "medium",
      ref: "Galia E, Dressman JB et al. Pharm Res 1998;15:698–705; USP <1092>",
    },
    {
      t: "IVIVC Level A definition and use",
      p: "บริษัทพัฒนา extended-release tablet และได้ IVIVC จากการ deconvolution ข้อมูล plasma concentration ของ 3 สูตรที่มี release rate ต่างกัน ได้ความสัมพันธ์เชิงเส้นแบบจุดต่อจุดระหว่าง % dissolved in vitro กับ % absorbed in vivo ข้อใดถูกต้องที่สุด",
      o: [
        "เป็น Level A correlation ซึ่งเมื่อ validate แล้วสามารถใช้ dissolution ทำนาย plasma profile และสนับสนุน biowaiver สำหรับการเปลี่ยนแปลงบางประเภทได้",
        "เป็น Level B correlation เพราะใช้ mean dissolution time เทียบกับ mean residence time",
        "เป็น Level C correlation เพราะเทียบ dissolution จุดเดียวกับ AUC",
        "เป็น Level A แต่ใช้ได้เฉพาะการตั้ง dissolution specification ไม่สามารถใช้ขอ biowaiver ได้",
        "ใช้ได้ทันทีโดยไม่ต้องทดสอบ predictability เพราะ r² ของความสัมพันธ์สูง",
      ],
      a: 0,
      r: "IVIVC Level A คือความสัมพันธ์แบบ point-to-point ระหว่าง in vitro dissolution กับ in vivo input rate (fraction absorbed) ที่ได้จาก deconvolution เช่น Wagner–Nelson หรือ numerical deconvolution มักเป็นเชิงเส้น เป็นระดับที่มีประโยชน์สูงสุดเพราะสามารถทำนาย plasma concentration–time profile ทั้งเส้นจาก dissolution ได้\n\nเมื่อผ่านการ validate (internal/external predictability ของ Cmax และ AUC) จะใช้สนับสนุน biowaiver สำหรับการเปลี่ยนแปลงหลังอนุมัติ (เช่น SUPAC level 3 บางกรณี) และใช้ตั้ง dissolution specification ที่มีความหมายทางคลินิก ส่วน Level B ใช้ statistical moment (MDT vs MRT) และ Level C ใช้จุดเดียว",
      w: [
        "ถูก — point-to-point ระหว่าง % dissolved กับ % absorbed = Level A ใช้ทำนาย profile และ biowaiver ได้เมื่อ validate",
        "Level B ใช้ statistical moment (MDT/MRT) ไม่ใช่ความสัมพันธ์แบบจุดต่อจุด",
        "Level C เทียบ dissolution parameter จุดเดียวกับ PK parameter เดียว ซึ่งไม่ตรงกับข้อมูลในโจทย์",
        "Level A ที่ validate แล้วเป็นระดับเดียวที่สนับสนุน biowaiver ได้กว้างที่สุด",
        "r² สูงไม่พอ ต้องประเมิน prediction error ของ Cmax และ AUC ก่อนนำไปใช้",
      ],
      k: "IVIVC Level A = point-to-point (deconvolution); ทำนาย profile ได้ ใช้ biowaiver ได้หลัง validate",
      d: "medium",
      ref: "FDA Guidance: Extended Release Oral Dosage Forms — Development, Evaluation, and Application of IVIVC (1997); USP <1088>",
    },
    {
      t: "AUC trapezoidal with extrapolation",
      p: "ข้อมูลความเข้มข้นในพลาสมาหลังรับประทานยาครั้งเดียว: 0 h = 0, 1 h = 4.0, 2 h = 6.0, 4 h = 4.0, 6 h = 2.5, 8 h = 1.6 mg/L และ terminal elimination rate constant (λz) = 0.25 h⁻¹ ค่า AUC₀–∞ โดย linear trapezoidal rule ประมาณเท่าใด",
      o: ["27.6 mg·h/L", "28.0 mg·h/L", "34.0 mg·h/L", "35.4 mg·h/L", "51.6 mg·h/L"],
      a: 2,
      r: "AUC₀–t คำนวณด้วย linear trapezoidal rule โดยรวมพื้นที่สี่เหลี่ยมคางหมูทุกช่วง: ช่วง 0–1 = 2.0, 1–2 = 5.0, 2–4 = 10.0, 4–6 = 6.5, 6–8 = 4.1 รวม 27.6 mg·h/L\n\nส่วนที่เหลือหลังจุดสุดท้าย (AUC_t–∞) ประมาณได้จาก C_last/λz = 1.6/0.25 = 6.4 mg·h/L ดังนั้น AUC₀–∞ = 34.0 mg·h/L สัดส่วนที่ extrapolate = 6.4/34.0 ≈ 19% ซึ่งใกล้ขีด 20% ที่แนวทาง EMA ใช้พิจารณาว่าช่วงเก็บตัวอย่างเพียงพอหรือไม่ (AUC₀–t ควรครอบคลุม ≥ 80% ของ AUC₀–∞) ข้อควรระวังคือต้องใช้ C_last ไม่ใช่ Cmax และหารด้วย λz ไม่ใช่คูณ",
      w: [
        "27.6 คือ AUC₀–t เท่านั้น ยังไม่ได้รวมส่วน extrapolate ไปถึง infinity",
        "28.0 เกิดจากคูณ C_last ด้วย λz (1.6 × 0.25 = 0.4) แทนการหาร",
        "ถูก — AUC₀–t 27.6 + C_last/λz (1.6/0.25 = 6.4) = 34.0 mg·h/L",
        "35.4 เกิดจากใช้ left-rectangle (ใช้ค่าต้นช่วงคูณช่วงเวลา) แทน trapezoid แล้วบวก 6.4",
        "51.6 เกิดจากใช้ Cmax (6.0/0.25 = 24) แทน C_last ในการ extrapolate",
      ],
      k: "AUC₀–∞ = AUC₀–t (trapezoid) + C_last/λz; ส่วน extrapolate ควร ≤ 20%",
      d: "hard",
      ref: "Shargel & Yu, Applied Biopharmaceutics & Pharmacokinetics 7th ed., Ch.2 and Ch.16",
      c: [
        "0–1 h: (0 + 4.0)/2 × 1 = 2.0",
        "1–2 h: (4.0 + 6.0)/2 × 1 = 5.0",
        "2–4 h: (6.0 + 4.0)/2 × 2 = 10.0",
        "4–6 h: (4.0 + 2.5)/2 × 2 = 6.5",
        "6–8 h: (2.5 + 1.6)/2 × 2 = 4.1 → AUC₀–t = 27.6",
        "AUC_t–∞ = 1.6/0.25 = 6.4 → AUC₀–∞ = 34.0 mg·h/L",
      ],
    },
    {
      t: "Relative bioavailability calculation",
      p: "เปรียบเทียบ capsule ใหม่ขนาด 250 mg (AUC₀–∞ = 45 mg·h/L) กับ oral solution อ้างอิงขนาด 100 mg (AUC₀–∞ = 20 mg·h/L) ในอาสาสมัครกลุ่มเดียวกัน (linear PK) relative bioavailability ของ capsule เทียบกับ solution เป็นเท่าใด",
      o: ["18%", "44%", "90%", "111%", "225%"],
      a: 2,
      r: "Relative bioavailability (F_rel) เปรียบเทียบ extent of absorption ของสองผลิตภัณฑ์ที่ไม่ใช่ IV โดยมักใช้ oral solution หรือ reference product เป็นตัวเทียบ: F_rel = (AUC_test/Dose_test)/(AUC_ref/Dose_ref)\n\nCapsule: 45/250 = 0.18 ส่วน solution: 20/100 = 0.20 ได้ F_rel = 0.90 หรือ 90% แปลว่า capsule ให้ exposure ต่อ mg ประมาณ 90% ของ solution ซึ่งมักสะท้อนข้อจำกัดด้านการปลดปล่อย/การละลายของ solid dosage form ค่า F_rel เกิน 100% ได้ (ต่างจาก absolute BA) หาก test ดีกว่า reference",
      w: [
        "18% คือ AUC/dose ของ capsule (0.18) ยังไม่ได้หารด้วยค่าของ solution",
        "44% เกิดจากหาร AUC กลับด้าน (20/45) โดยไม่ปรับขนาดยา",
        "ถูก — (45/250)/(20/100) = 0.18/0.20 = 0.90",
        "111% เกิดจากหารกลับด้าน (0.20/0.18)",
        "225% คือ AUC_test/AUC_ref โดยไม่ปรับขนาดยาที่ต่างกัน 2.5 เท่า",
      ],
      k: "F_rel = (AUC_T/D_T)/(AUC_R/D_R); reference เป็น oral product ไม่ใช่ IV และ F_rel เกิน 100% ได้",
      d: "medium",
      ref: "Shargel & Yu, Applied Biopharmaceutics & Pharmacokinetics 7th ed., Ch.16",
      c: [
        "AUC/Dose (capsule) = 45/250 = 0.18",
        "AUC/Dose (solution) = 20/100 = 0.20",
        "F_rel = 0.18/0.20 = 0.90 = 90%",
      ],
    },
    {
      t: "NTI drug tightened BE limits",
      p: "บริษัทยื่นทะเบียน generic tacrolimus capsule ซึ่งเป็นยา narrow therapeutic index (NTI) ตามแนวทาง EMA ช่วงยอมรับ (acceptance range) ของ 90% CI สำหรับ AUC ควรเป็นข้อใด",
      o: [
        "69.84–143.19%",
        "80.00–125.00%",
        "85.00–117.65%",
        "90.00–111.11%",
        "95.00–105.00%",
      ],
      a: 3,
      r: "ยา NTI เช่น tacrolimus, ciclosporin, warfarin, phenytoin, levothyroxine และ digoxin มีช่วงระหว่างขนาดที่ได้ผลกับขนาดที่เป็นพิษแคบ ความแตกต่างของ exposure เล็กน้อยอาจมีผลทางคลินิก EMA จึงกำหนดให้ AUC ใช้ช่วงแคบ 90.00–111.11% (และใช้กับ Cmax ด้วยหาก Cmax สำคัญเป็นพิเศษต่อความปลอดภัย ประสิทธิภาพ หรือการติดตามระดับยา)\n\nช่วงนี้สมมาตรบน log scale (ln 0.9 = −ln 1.1111) เหมือนกับ 80.00–125.00% ส่วน FDA ใช้ reference-scaled approach ร่วมกับเกณฑ์เปรียบเทียบ within-subject variability ระหว่าง test และ reference ซึ่งต้องใช้ fully replicate design",
      w: [
        "69.84–143.19% เป็นขีดสูงสุดของการขยายเกณฑ์ (ABEL) สำหรับ Cmax ของยา highly variable ซึ่งตรงข้ามกับยา NTI",
        "80.00–125.00% เป็นเกณฑ์มาตรฐานของยาทั่วไป ไม่เพียงพอสำหรับยา NTI",
        "85.00–117.65% ไม่ใช่เกณฑ์ที่ EMA กำหนดสำหรับยา NTI",
        "ถูก — EMA กำหนด AUC ของยา NTI ที่ 90.00–111.11% (สมมาตรบน log scale)",
        "95.00–105.00% ไม่ใช่เกณฑ์ BE ที่ใช้ในแนวทางใด ๆ และแคบเกินจริง",
      ],
      k: "EMA: NTI → AUC 90.00–111.11% (และ Cmax เมื่อจำเป็น); HVD → ขยาย Cmax ได้ถึง 69.84–143.19%",
      d: "hard",
      ref: "EMA Guideline on the Investigation of Bioequivalence CPMP/EWP/QWP/1401/98 Rev.1, Section 4.1.9",
    },
  ],
  // Mock Set 3
  [
    {
      t: "Oral bioavailability F = Fa x Fg x Fh",
      p: "ยา W ถูกดูดซึมผ่านเยื่อบุลำไส้ได้ 90% (Fa = 0.90) ถูก CYP3A4 ใน enterocyte เมแทบอไลซ์ไป 20% ของส่วนที่ผ่านเข้าเซลล์ ยามี hepatic blood clearance 0.6 L/min และ hepatic blood flow 1.5 L/min (ไม่ถูกกำจัดที่อวัยวะอื่นก่อนเข้าสู่ systemic circulation) oral bioavailability ประมาณเท่าใด",
      o: ["29%", "36%", "43%", "54%", "72%"],
      a: 2,
      r: "Oral bioavailability เป็นผลคูณของสัดส่วนที่ผ่านแต่ละด่าน: F = Fa × Fg × Fh โดย Fa คือ fraction absorbed เข้าสู่ enterocyte, Fg คือ fraction ที่รอดจาก gut-wall metabolism และ Fh คือ fraction ที่รอดจาก hepatic first-pass\n\nHepatic extraction ratio E_H = CL_H/Q_H = 0.6/1.5 = 0.4 ดังนั้น Fh = 1 − 0.4 = 0.6 ส่วน Fg = 1 − 0.2 = 0.8 จึงได้ F = 0.90 × 0.80 × 0.60 = 0.432 ≈ 43% ยาที่มี E_H สูง (> 0.7) เช่น propranolol, verapamil จะมี F ต่ำแม้ดูดซึมได้ดี และไวต่อการเปลี่ยน hepatic blood flow",
      w: [
        "29% เกิดจากใช้ E_H (0.4) แทน Fh ในการคูณ (0.90 × 0.80 × 0.40)",
        "36% เกิดจากคูณ Fa กับ E_H (0.90 × 0.40) และลืม Fg",
        "ถูก — Fh = 1 − 0.6/1.5 = 0.6; F = 0.90 × 0.80 × 0.60 = 0.432",
        "54% คือ Fa × Fh โดยลืมรวม gut-wall metabolism (Fg)",
        "72% คือ Fa × Fg โดยลืม hepatic first-pass",
      ],
      k: "F = Fa·Fg·Fh; Fh = 1 − E_H = 1 − CL_H/Q_H",
      d: "hard",
      ref: "Rowland & Tozer, Clinical Pharmacokinetics and Pharmacodynamics 4th ed., Ch.5",
      c: [
        "E_H = CL_H/Q_H = 0.6/1.5 = 0.40 → Fh = 0.60",
        "Fg = 1 − 0.20 = 0.80",
        "F = 0.90 × 0.80 × 0.60 = 0.432 ≈ 43%",
      ],
    },
    {
      t: "Chelation with polyvalent cations",
      p: "ผู้ป่วยได้รับ tetracycline รับประทานพร้อมนมและยาลดกรดที่มี aluminium/magnesium hydroxide พบว่าการรักษาไม่ได้ผล กลไกที่อธิบายได้ดีที่สุดคือข้อใด",
      o: [
        "Tetracycline เกิด chelate complex กับ Ca²⁺, Mg²⁺ และ Al³⁺ ซึ่งละลายน้ำน้อยและดูดซึมได้น้อย",
        "นมเพิ่ม gastric emptying ทำให้ยาผ่านลำไส้เร็วเกินไป",
        "ยาลดกรดทำให้ tetracycline ถูก metabolize ที่ตับมากขึ้น",
        "Calcium ไป induce P-glycoprotein ในลำไส้",
        "นมทำให้ tetracycline ละลายดีขึ้นจนตกตะกอนในลำไส้ใหญ่",
      ],
      a: 0,
      r: "Tetracyclines และ fluoroquinolones มีหมู่ที่จับกับ polyvalent metal ions (Ca²⁺, Mg²⁺, Al³⁺, Fe²⁺/Fe³⁺, Zn²⁺) เกิด chelate ที่ไม่ละลายน้ำหรือมีขนาดใหญ่และมีขั้ว จึงผ่านเยื่อบุลำไส้ได้น้อย ทำให้ AUC ลดลงอย่างมาก\n\nนี่คือตัวอย่างของ complexation ที่ลดการดูดซึม ทางปฏิบัติคือแยกเวลารับประทานยาห่างจากนม ยาลดกรด หรือธาตุเหล็กอย่างน้อย 2–3 ชั่วโมง (ขึ้นกับยา) ในทางกลับกัน complexation บางแบบ เช่น cyclodextrin inclusion complex สามารถเพิ่มการละลายและการดูดซึมได้",
      w: [
        "ถูก — polyvalent cations จับ tetracycline เป็น chelate ที่ดูดซึมได้น้อย",
        "นมไม่ได้เร่ง gastric emptying อย่างมีนัยสำคัญ และกลไกหลักคือ chelation",
        "ยาลดกรดไม่ได้เหนี่ยวนำ hepatic metabolism ของ tetracycline",
        "Calcium ไม่ใช่ P-gp inducer และไม่ใช่กลไกของปฏิกิริยานี้",
        "Chelate ลดการละลาย/การดูดซึม ไม่ได้เพิ่มการละลาย",
      ],
      k: "Tetracycline/fluoroquinolone + Ca/Mg/Al/Fe → chelation → การดูดซึมลดลง; แยกเวลารับประทาน",
      d: "easy",
      ref: "Shargel & Yu, Applied Biopharmaceutics & Pharmacokinetics 7th ed., Ch.14",
    },
    {
      t: "BDDCS classification basis",
      p: "ยา V มี solubility สูง ถูกเมแทบอไลซ์ในร่างกายน้อยกว่า 10% และขับออกทางไตเป็นยาเดิมเป็นส่วนใหญ่ ข้อมูล permeability ในมนุษย์ไม่ชัดเจน ตามระบบ BDDCS ข้อใดถูกต้อง",
      o: [
        "จัดเป็น BDDCS class 3 เพราะ BDDCS ใช้ extent of metabolism แทน permeability และ uptake transporter มีบทบาทสำคัญต่อการดูดซึม",
        "จัดเป็น BDDCS class 1 เพราะ solubility สูง",
        "จัดเป็น BDDCS class 2 และคาดว่า efflux transporter ในลำไส้มีผลเด่น",
        "BDDCS ใช้ Caco-2 permeability เท่านั้นในการจัดกลุ่ม จึงจัดไม่ได้",
        "BDDCS ใช้แทน BCS ในการขอ biowaiver ตาม ICH M9 ได้โดยตรง",
      ],
      a: 0,
      r: "BDDCS (Biopharmaceutics Drug Disposition Classification System; Wu & Benet 2005) ใช้ solubility ร่วมกับ extent of metabolism แทน permeability โดยยาที่ถูก metabolize ≥ 90% ถือเป็นกลุ่ม 'extensive metabolism' (สัมพันธ์กับ high permeability) ส่วนที่ถูก metabolize น้อยเป็นกลุ่ม 'poor metabolism'\n\nยา V มี solubility สูงและ metabolism น้อย จึงเป็น class 3 ซึ่งมักต้องอาศัย uptake transporter ในการดูดซึมและการเข้าสู่ hepatocyte ขณะที่ class 2 (low solubility, extensive metabolism) มักได้รับผลจาก efflux transporter ในลำไส้และ transporter–enzyme interplay BDDCS ใช้ทำนาย disposition, DDI ด้าน transporter และ food effect ไม่ใช่เกณฑ์ biowaiver ตาม ICH M9",
      w: [
        "ถูก — high solubility + poor metabolism = BDDCS class 3 ซึ่ง uptake transporter มีความสำคัญ",
        "Class 1 ต้องมีทั้ง high solubility และ extensive metabolism (≥ 90%) ซึ่งยา V ไม่เข้าเกณฑ์",
        "Class 2 คือ low solubility + extensive metabolism ไม่ตรงกับยา V",
        "BDDCS ใช้ข้อมูล extent of metabolism ในมนุษย์เป็นหลัก ไม่ได้อาศัย Caco-2",
        "ICH M9 ใช้ BCS (permeability) สำหรับ biowaiver; BDDCS เป็นเครื่องมือทำนาย disposition",
      ],
      k: "BDDCS = solubility + extent of metabolism (≥ 90% = extensive); class 2 → efflux เด่น, class 3 → uptake สำคัญ",
      d: "medium",
      ref: "Wu CY, Benet LZ. Pharm Res 2005;22:11–23",
    },
    {
      t: "ICH M9 biowaiver scope exclusions",
      p: "ข้อใดต่อไปนี้ไม่เข้าข่ายขอ BCS-based biowaiver ตาม ICH M9 แม้ API จะเป็น BCS class I",
      o: [
        "Sublingual tablet ที่ออกแบบให้ดูดซึมผ่านเยื่อบุช่องปาก",
        "Immediate-release film-coated tablet สำหรับรับประทาน",
        "Immediate-release hard capsule สำหรับรับประทาน",
        "Fixed-dose combination IR tablet ที่ API ทุกตัวเป็น BCS class I และเข้าเกณฑ์",
        "Additional strength ของ IR tablet ที่ API เป็น class I และสูตรเข้าเกณฑ์",
      ],
      a: 0,
      r: "ICH M9 ใช้กับ immediate-release solid oral dosage forms หรือ suspensions ที่ออกฤทธิ์ทั่วร่างกาย (systemic action) และดูดซึมในทางเดินอาหาร รวมถึง fixed-dose combinations เมื่อ API ทุกตัวเข้าเกณฑ์\n\nผลิตภัณฑ์ที่ออกแบบให้ดูดซึมในช่องปาก (buccal/sublingual) ไม่เข้าข่าย เพราะการดูดซึมไม่ได้เกิดผ่านกลไกที่ BCS ใช้ประเมิน (การละลายในทางเดินอาหารและ intestinal permeability) นอกจากนี้ยา NTI และผลิตภัณฑ์ modified-release ก็อยู่นอกขอบเขต ส่วน orally disintegrating tablets ใช้ได้เฉพาะเมื่อไม่มีการดูดซึมทางช่องปาก",
      w: [
        "ถูก — ผลิตภัณฑ์ที่มุ่งให้ดูดซึมผ่าน buccal/sublingual อยู่นอกขอบเขตของ ICH M9",
        "IR film-coated tablet สำหรับรับประทานเป็นรูปแบบหลักที่เข้าข่าย",
        "IR capsule สำหรับรับประทานเข้าข่าย (capsule shell ไม่ถือเป็นปัญหา)",
        "FDC เข้าข่ายได้เมื่อ API ทุกตัวเข้าเกณฑ์ BCS และสูตรเป็นไปตามข้อกำหนด",
        "ICH M9 ใช้กับ additional strengths ได้หากเข้าเกณฑ์ BCS และ excipients",
      ],
      k: "ICH M9 ครอบคลุม IR oral systemic (รวม FDC); ไม่รวม buccal/sublingual, NTI, MR",
      d: "medium",
      ref: "ICH M9 Biopharmaceutics Classification System-based Biowaivers (2019), Section 1.3 Scope",
    },
    {
      t: "USP 711 stage S3 evaluation",
      p: "ยาเม็ด IR มี Q = 75% ใน 30 นาที ไม่ผ่าน S2 จึงทดสอบจนครบ S3 (24 เม็ด) ได้ค่าเฉลี่ย 78.1% โดยมี 2 เม็ดได้ 57% และ 59% ส่วนที่เหลือทุกเม็ด ≥ 63% ข้อใดสรุปได้ถูกต้อง",
      o: [
        "ผ่าน S3 เพราะค่าเฉลี่ย ≥ Q, มีไม่เกิน 2 เม็ดที่ต่ำกว่า Q − 15% (60%) และไม่มีเม็ดใดต่ำกว่า Q − 25% (50%)",
        "ไม่ผ่าน เพราะมีเม็ดที่ต่ำกว่า Q − 15% ซึ่ง S3 ห้ามโดยเด็ดขาด",
        "ไม่ผ่าน เพราะค่าเฉลี่ยต้อง ≥ Q + 5% ที่ S3",
        "ผ่าน S3 เพียงแค่ค่าเฉลี่ย ≥ Q โดยไม่ต้องดูค่ารายเม็ด",
        "ต้องทดสอบ S4 อีก 12 เม็ดเพื่อยืนยัน",
      ],
      a: 0,
      r: "เกณฑ์ S3 ของ USP <711> (24 หน่วย): ค่าเฉลี่ย ≥ Q, ไม่เกิน 2 หน่วยที่ต่ำกว่า Q − 15% และไม่มีหน่วยใดต่ำกว่า Q − 25%\n\nเมื่อ Q = 75%: Q − 15% = 60% และ Q − 25% = 50% ผลมีค่าเฉลี่ย 78.1% ≥ 75%, มี 2 เม็ด (57% และ 59%) ต่ำกว่า 60% ซึ่งยังไม่เกิน 2 และค่าต่ำสุด 57% สูงกว่า 50% จึงผ่าน S3 อย่างไรก็ตาม batch ที่ต้องไปถึง S3 ควรได้รับการทบทวนแนวโน้ม (trend) และหาสาเหตุของ variability ตามระบบคุณภาพ ไม่มี stage S4 ใน USP <711>",
      w: [
        "ถูก — mean ≥ 75%, หน่วย < 60% มี 2 หน่วย (ไม่เกิน 2) และไม่มีหน่วย < 50%",
        "S3 อนุญาตให้มีได้ไม่เกิน 2 หน่วยที่ต่ำกว่า Q − 15% ไม่ได้ห้ามเด็ดขาด",
        "Q + 5% เป็นเกณฑ์รายหน่วยของ S1 ไม่ใช่เกณฑ์ค่าเฉลี่ยที่ S3",
        "S3 มีเกณฑ์รายหน่วยด้วย (≤ 2 หน่วย < Q − 15% และไม่มี < Q − 25%)",
        "USP <711> มีเพียง 3 stage (S1–S3) ไม่มี S4",
      ],
      k: "S3: 24 หน่วย mean ≥ Q, ≤ 2 หน่วย < Q − 15%, ไม่มีหน่วยใด < Q − 25%",
      d: "hard",
      ref: "USP <711> Dissolution, Acceptance Table 1",
      c: [
        "Q − 15% = 75 − 15 = 60%; Q − 25% = 75 − 25 = 50%",
        "Mean 24 หน่วย = 78.1% ≥ 75% ✓",
        "หน่วย < 60% = 2 หน่วย (57, 59) ≤ 2 ✓; ค่าต่ำสุด 57% > 50% ✓ → ผ่าน S3",
      ],
    },
    {
      t: "Sink condition with surfactant medium",
      p: "ยาเม็ดมี API 50 mg ต่อเม็ด solubility ใน phosphate buffer pH 6.8 = 0.02 mg/mL ใช้ปริมาตร medium 900 mL เมื่อเติม sodium lauryl sulfate (SLS) 0.5% w/v solubility เพิ่มเป็น 0.30 mg/mL ข้อใดสรุปได้ถูกต้องที่สุดเกี่ยวกับ sink condition",
      o: [
        "Buffer อย่างเดียวละลายได้สูงสุดเพียง 18 mg (ไม่ถึง sink) แต่เมื่อเติม SLS 0.5% ปริมาตร 900 mL ละลายได้ประมาณ 5.4 เท่าของขนาดยา จึงเข้า sink condition",
        "Buffer อย่างเดียวเป็น sink condition แล้ว เพราะปริมาตร 900 mL มากกว่าขนาดยา 50 mg",
        "แม้เติม SLS ก็ยังไม่ถึง sink เพราะต้องละลายได้อย่างน้อย 10 เท่าของขนาดยา",
        "ควรเพิ่ม SLS เป็น 3% เพื่อให้ละลายได้สูงที่สุดโดยไม่ต้องคำนึงถึงความสามารถในการแยกแยะ",
        "ต้องลดปริมาตรเป็น 500 mL เพื่อเพิ่มความเข้มข้นให้วัดง่ายขึ้น",
      ],
      a: 0,
      r: "Sink condition ตาม USP <1092> หมายถึงปริมาตร medium อย่างน้อย 3 เท่าของปริมาตรที่ต้องใช้ในการทำ saturated solution ของขนาดยา เพื่อให้แรงขับการละลาย (Cs − C) ไม่ลดลงอย่างมีนัยสำคัญระหว่างทดสอบ\n\nใน buffer: Cs × V = 0.02 × 900 = 18 mg เท่านั้น (36% ของขนาดยา) จึงไม่ถึง sink และละลายได้ไม่หมด เมื่อเติม SLS 0.5%: 0.30 × 900 = 270 mg = 5.4 เท่าของ 50 mg จึงเข้า sink ข้อสำคัญคือควรใช้ surfactant ในความเข้มข้นต่ำสุดที่จำเป็นและต้องมีเหตุผลรองรับ เพราะ surfactant มากเกินไปจะลด discriminating power ของวิธี",
      w: [
        "ถูก — buffer ละลายได้ 18 mg (< ขนาดยา) ส่วน SLS 0.5% ละลายได้ 270 mg = 5.4 เท่า ≥ 3 เท่า",
        "ต้องพิจารณาจาก solubility × ปริมาตร ไม่ใช่เทียบปริมาตรกับมวล; buffer ละลายได้เพียง 18 mg",
        "เกณฑ์ทั่วไปคือ ≥ 3 เท่าของปริมาตร saturation ไม่ใช่ 10 เท่า",
        "Surfactant มากเกินจำเป็นทำให้วิธีไม่สามารถแยกความแตกต่างของสูตรหรือกระบวนการได้ (over-solubilization)",
        "การลดปริมาตรยิ่งทำให้ห่างจาก sink condition มากขึ้น",
      ],
      k: "Sink = V ≥ 3 × (Dose/Cs); ใช้ surfactant ความเข้มข้นต่ำสุดที่จำเป็นเพื่อคง discriminating power",
      d: "medium",
      ref: "USP <1092> The Dissolution Procedure: Development and Validation",
      c: [
        "Buffer: Cs × V = 0.02 mg/mL × 900 mL = 18 mg < 50 mg → ไม่ถึง sink",
        "SLS 0.5%: 0.30 × 900 = 270 mg",
        "270/50 = 5.4 เท่า ≥ 3 → sink condition",
      ],
    },
    {
      t: "f2 applicability prerequisites",
      p: "ผู้วิเคราะห์จะใช้ f2 เปรียบเทียบ dissolution profile ของยาเม็ดสูตรเดิมกับสูตรที่เปลี่ยนแหล่งผลิต excipient ข้อใดเป็นเงื่อนไขที่ถูกต้องตามแนวทาง FDA/EMA",
      o: [
        "ใช้ 12 หน่วยต่อผลิตภัณฑ์ อย่างน้อย 3 จุดเวลา (ไม่นับ 0) มีจุดที่เกิน 85% ได้ไม่เกิน 1 จุด และ CV ไม่เกิน 20% ที่จุดต้นและไม่เกิน 10% ที่จุดอื่น",
        "ใช้ 6 หน่วยต่อผลิตภัณฑ์ และใช้ทุกจุดเวลาจนถึงเมื่อละลาย 100%",
        "ใช้เพียง 2 จุดเวลาก็พอ หากทั้งสองจุดอยู่ช่วงที่ profile ชันที่สุด",
        "ไม่มีข้อจำกัดเรื่อง variability เพราะ f2 คิดจากค่าเฉลี่ยอยู่แล้ว",
        "ต้องใช้สภาวะการทดสอบต่างกันระหว่าง test และ reference เพื่อเพิ่มความไว",
      ],
      a: 0,
      r: "f2 เป็นสถิติที่อาศัยค่าเฉลี่ย จึงเชื่อถือได้เฉพาะเมื่อข้อมูลมีคุณภาพเพียงพอ แนวทาง FDA (1997) และ EMA กำหนดให้ใช้ 12 หน่วยต่อผลิตภัณฑ์ ทดสอบในสภาวะเดียวกัน ใช้จุดเวลาเดียวกัน อย่างน้อย 3 จุด (ไม่รวมเวลา 0) และใช้จุดที่เกิน 85% ได้ไม่เกิน 1 จุด เพราะจุดที่ plateau จะทำให้ f2 สูงเกินจริง\n\nVariability ต้องไม่สูงเกิน: CV ที่จุดแรก (เช่น ≤ 10–15 นาที) ไม่เกิน 20% และจุดอื่นไม่เกิน 10% หากเกินควรใช้วิธีอื่น เช่น bootstrap f2 หรือ multivariate statistical distance และหากทั้งสองผลิตภัณฑ์ละลาย ≥ 85% ใน 15 นาที อาจถือว่าคล้ายกันโดยไม่ต้องคำนวณ f2",
      w: [
        "ถูก — 12 หน่วย, ≥ 3 จุด, เกิน 85% ไม่เกิน 1 จุด, CV ≤ 20% (ต้น) และ ≤ 10% (ที่เหลือ)",
        "ต้องใช้ 12 หน่วย และการรวมหลายจุดหลัง plateau ทำให้ f2 สูงเกินจริง",
        "ต้องมีอย่างน้อย 3 จุดเวลา (ไม่รวม 0)",
        "Variability สูงทำให้ค่าเฉลี่ยไม่แทน profile จริง แนวทางจึงกำหนดเพดาน CV",
        "Test และ reference ต้องทดสอบในสภาวะเดียวกันทุกประการ",
      ],
      k: "f2 ใช้ได้เมื่อ: n = 12, ≥ 3 จุด, > 85% ได้แค่ 1 จุด, CV ≤ 20% (ต้น)/≤ 10% (ที่เหลือ)",
      d: "medium",
      ref: "FDA Guidance: Dissolution Testing of Immediate Release Solid Oral Dosage Forms (1997); EMA CPMP/EWP/QWP/1401/98 Rev.1 Appendix I",
    },
    {
      t: "Clearance from IV bolus data",
      p: "ให้ยาทางหลอดเลือดดำแบบ bolus ขนาด 500 mg (one-compartment) ได้ C₀ ที่ extrapolate = 25 mg/L และ elimination half-life = 4.0 ชั่วโมง ค่า total clearance (CL) ประมาณเท่าใด",
      o: ["0.17 L/h", "3.47 L/h", "5.00 L/h", "20.0 L/h", "80.0 L/h"],
      a: 1,
      r: "ใน one-compartment IV bolus: Vd = Dose/C₀ และ k = 0.693/t½ จากนั้น CL = k × Vd หรือคำนวณจาก CL = Dose/AUC₀–∞ โดย AUC₀–∞ = C₀/k\n\nVd = 500/25 = 20 L; k = 0.693/4 = 0.173 h⁻¹; CL = 0.173 × 20 = 3.47 L/h ตรวจสอบด้วย AUC = 25/0.173 = 144.3 mg·h/L → CL = 500/144.3 = 3.47 L/h CL และ Vd เป็น primary parameters ส่วน t½ เป็น secondary parameter ที่ขึ้นกับทั้งสอง (t½ = 0.693·Vd/CL)",
      w: [
        "0.17 คือค่า k (h⁻¹) ซึ่งยังไม่ได้คูณด้วย Vd",
        "ถูก — Vd = 20 L, k = 0.173 h⁻¹, CL = k·Vd = 3.47 L/h",
        "5.00 เกิดจากหาร Vd ด้วย t½ (20/4) โดยไม่คูณ 0.693",
        "20.0 คือ Vd (L) ไม่ใช่ clearance",
        "80.0 เกิดจากคูณ Vd กับ t½ ซึ่งไม่มีความหมายทาง PK",
      ],
      k: "Vd = Dose/C₀; k = 0.693/t½; CL = k·Vd = Dose/AUC",
      d: "medium",
      ref: "Shargel & Yu, Applied Biopharmaceutics & Pharmacokinetics 7th ed., Ch.3",
      c: [
        "Vd = 500 mg/25 mg/L = 20 L",
        "k = 0.693/4.0 h = 0.173 h⁻¹",
        "CL = 0.173 × 20 = 3.47 L/h (ตรวจ: AUC = 25/0.173 = 144.3; 500/144.3 = 3.47)",
      ],
    },
    {
      t: "ABEL widened limits for HVD Cmax",
      p: "BE study แบบ fully replicate (4-period) ของยา highly variable ยื่นต่อ EMA พบ within-subject CV ของ reference (CVwR) สำหรับ Cmax = 55% ผลของ Cmax: GMR = 118.0%, 90% CI = 98.5–139.0% และ AUC ผ่านเกณฑ์ 80.00–125.00% ข้อใดสรุปได้ถูกต้อง",
      o: [
        "Cmax ผ่าน เพราะช่วงขยายถูกจำกัดสูงสุดที่ 69.84–143.19% (ที่ CVwR 50%) CI อยู่ในช่วง และ GMR อยู่ใน 80.00–125.00%",
        "Cmax ไม่ผ่าน เพราะ upper limit เกิน 125.00% ซึ่งใช้กับยาทุกตัว",
        "Cmax ผ่าน และสามารถขยายเกณฑ์ของ AUC ได้ในลักษณะเดียวกัน",
        "ช่วงขยายคำนวณจาก CVwR 55% ได้กว้างกว่า 69.84–143.19% จึงผ่านอย่างสบาย",
        "Cmax ไม่ผ่าน เพราะ GMR ต้องอยู่ในช่วง 90.00–111.11%",
      ],
      a: 0,
      r: "EMA อนุญาต average bioequivalence with expanding limits (ABEL) สำหรับ Cmax เมื่อ CVwR > 30% และมีเหตุผลทางคลินิกว่าการขยายไม่กระทบความปลอดภัย/ประสิทธิภาพ ต้องใช้ replicate design เพื่อประมาณ CVwR ช่วงที่ขยายคือ exp(±0.760·sWR) แต่ถูกจำกัดสูงสุดที่ CVwR = 50% ซึ่งได้ 69.84–143.19%\n\nแม้ CVwR = 55% ช่วงก็ยังคงเป็น 69.84–143.19% CI ของ Cmax (98.5–139.0%) อยู่ในช่วงนี้ และ point estimate (GMR 118.0%) ต้องอยู่ใน 80.00–125.00% ซึ่งผ่าน จึงสรุปว่า Cmax เข้าเกณฑ์ ส่วน AUC ภายใต้ EMA ไม่สามารถขยายได้ (ยกเว้นกรณีพิเศษบางชนิดใน multiple-dose MR) ต้องผ่าน 80.00–125.00%",
      w: [
        "ถูก — ขยายได้สูงสุด 69.84–143.19% (cap ที่ CVwR 50%) CI อยู่ในช่วงและ GMR อยู่ใน 80–125%",
        "ยา highly variable ภายใต้ EMA สามารถขยายเกณฑ์ Cmax ได้เมื่อ CVwR > 30% ด้วย replicate design",
        "EMA อนุญาตให้ขยายเฉพาะ Cmax ไม่ใช่ AUC",
        "ช่วงขยายถูก cap ที่ CVwR 50% CVwR ที่สูงกว่านั้นไม่ทำให้ช่วงกว้างขึ้น",
        "90.00–111.11% เป็นเกณฑ์ของยา NTI ไม่ใช่เกณฑ์ point estimate ของ HVD",
      ],
      k: "EMA ABEL: เฉพาะ Cmax, CVwR > 30%, replicate design, cap 69.84–143.19%, GMR ต้องใน 80–125%",
      d: "hard",
      ref: "EMA Guideline on the Investigation of Bioequivalence CPMP/EWP/QWP/1401/98 Rev.1, Section 4.1.10",
    },
    {
      t: "Orange Book therapeutic equivalence codes",
      p: "เภสัชกรโรงพยาบาลตรวจสอบรายการยาใน FDA Orange Book เพื่อพิจารณาการใช้ generic แทนยาต้นแบบ ผลิตภัณฑ์ที่มีรหัส 'AB' หมายถึงข้อใด",
      o: [
        "เป็น therapeutic equivalent ที่มีปัญหา bioequivalence จริงหรือที่อาจเกิดขึ้น แต่ได้แสดง BE ด้วยข้อมูลที่เพียงพอแล้ว",
        "ไม่ใช่ therapeutic equivalent เพราะยังไม่มีข้อมูล bioequivalence",
        "เป็นยาต้นแบบ (reference listed drug) ที่ไม่มี generic",
        "เป็นยาที่ได้รับ biowaiver จึงไม่ต้องมีข้อมูลใด ๆ",
        "เป็นยาที่ใช้แทนกันได้เฉพาะในผู้ป่วยรายใหม่เท่านั้น",
      ],
      a: 0,
      r: "Orange Book ใช้รหัสสองตัวอักษร ตัวแรก 'A' หมายถึง therapeutically equivalent กับ reference product ส่วน 'B' หมายถึงยังไม่ถือว่า therapeutically equivalent (เช่น BX = ข้อมูลไม่เพียงพอ)\n\n'AB' คือผลิตภัณฑ์ที่มีปัญหาด้าน bioequivalence จริงหรือที่อาจเกิด (actual or potential BE problems) แต่ได้แสดง BE แล้วด้วย in vivo และ/หรือ in vitro data ที่เพียงพอ จึงใช้แทนกันได้ (substitutable) ส่วน 'AA' คือรูปแบบยาทั่วไปที่ไม่ถือว่ามีปัญหา BE หลักคิดคือ therapeutic equivalence = pharmaceutical equivalence + bioequivalence",
      w: [
        "ถูก — AB = therapeutically equivalent; มี (หรืออาจมี) BE problem แต่แสดง BE ไว้เพียงพอแล้ว",
        "ผลิตภัณฑ์ที่ยังไม่ถือว่า TE จะมีรหัสขึ้นต้นด้วย B เช่น BX ไม่ใช่ AB",
        "Reference listed drug ไม่ได้มีรหัส AB เพื่อบ่งบอกว่าไม่มี generic",
        "AB ต้องมีการแสดง BE แล้ว biowaiver เป็นเพียงวิธีหนึ่งในบางกรณี ไม่ใช่ความหมายของรหัส",
        "รหัส TE ไม่ได้แบ่งตามสถานะผู้ป่วยรายใหม่หรือรายเดิม",
      ],
      k: "Orange Book: A = TE (AA ไม่มีปัญหา BE, AB แสดง BE แล้ว); B = ไม่ TE (เช่น BX)",
      d: "easy",
      ref: "FDA Orange Book Preface (Approved Drug Products with Therapeutic Equivalence Evaluations), Therapeutic Equivalence Evaluations Codes",
    },
  ],
  // Mock Set 4
  [
    {
      t: "Intestinal lymphatic transport",
      p: "Testosterone undecanoate ซึ่งเป็น ester ที่ lipophilic สูงมาก (log P > 5) ถูกพัฒนาเป็น soft capsule ในน้ำมันที่มีกรดไขมันสายยาว และแนะนำให้รับประทานพร้อมอาหารที่มีไขมัน เหตุผลเชิง biopharmaceutics ที่สำคัญที่สุดคือข้อใด",
      o: [
        "ยาเข้าไปรวมกับ chylomicrons และถูกดูดซึมผ่าน intestinal lymphatics ทำให้เลี่ยง hepatic first-pass metabolism",
        "ไขมันในอาหารเพิ่ม gastric pH ทำให้ยาแตกตัวน้อยลงจึงดูดซึมผ่าน paracellular route",
        "กรดไขมันสายยาวยับยั้ง CYP3A4 ที่ตับแบบถาวร",
        "ไขมันทำให้ยาถูกดูดซึมผ่าน portal vein เร็วขึ้นจนเอนไซม์ในตับอิ่มตัว",
        "น้ำมันทำหน้าที่เป็น P-gp inducer ที่ลำไส้",
      ],
      a: 0,
      r: "ยาที่ lipophilic สูงมาก (log P > 5 และละลายใน long-chain triglyceride ได้ดี) เมื่อให้ร่วมกับไขมันสายยาว จะถูกนำเข้าไปใน chylomicrons ที่ enterocyte สร้างขึ้น chylomicrons มีขนาดใหญ่เกินกว่าจะเข้า blood capillaries จึงเข้าสู่ lacteals → mesenteric lymph → thoracic duct → systemic circulation โดยไม่ผ่านตับ\n\nTestosterone ถูก hepatic first-pass สูงมากหากดูดซึมผ่าน portal vein การอาศัย lymphatic transport จึงทำให้ได้ระดับยาในเลือดที่ใช้ได้ทางคลินิก อาหารที่มีไขมันกระตุ้นการสร้าง chylomicrons จึงเพิ่มการดูดซึมอย่างมาก ไขมันสายกลาง (medium-chain) ไม่ส่งเสริม lymphatic transport เท่าสายยาว เพราะถูกดูดซึมเข้า portal vein ได้โดยตรง",
      w: [
        "ถูก — ยา lipophilic สูงร่วมกับ long-chain lipids เข้าสู่ chylomicrons → lymphatic → เลี่ยงตับ",
        "อาหารไม่ได้เพิ่ม gastric pH ในลักษณะนี้ และยาที่ lipophilic สูงไม่ได้ใช้ paracellular route",
        "กรดไขมันสายยาวไม่ใช่ CYP3A4 inhibitor แบบถาวรที่ตับ",
        "การเข้า portal vein ยิ่งทำให้ถูก first-pass มากขึ้น ไม่ใช่กลไกที่ต้องการ",
        "น้ำมันไม่ได้เป็น P-gp inducer และการ induce P-gp จะลดการดูดซึม",
      ],
      k: "Log P > 5 + long-chain TG → chylomicron → lymphatic transport → เลี่ยง hepatic first-pass",
      d: "hard",
      ref: "Porter CJH, Trevaskis NL, Charman WN. Nat Rev Drug Discov 2007;6:231–248",
    },
    {
      t: "Acid-reducing agents and weak-base absorption",
      p: "ผู้ป่วยที่ได้รับ omeprazole เป็นประจำ ได้รับยาต้านเชื้อราที่เป็น weak base ซึ่งละลายได้ดีเฉพาะใน pH กรด (เช่น ketoconazole tablet) ผลที่คาดได้คือข้อใด",
      o: [
        "การละลายและการดูดซึมของยาต้านเชื้อราลดลง เพราะ gastric pH สูงขึ้น",
        "การดูดซึมเพิ่มขึ้น เพราะยาแตกตัวน้อยลงที่ pH สูง",
        "ไม่มีผล เพราะยาดูดซึมที่ลำไส้เล็กซึ่ง pH สูงอยู่แล้ว",
        "Omeprazole ยับยั้ง P-gp ทำให้ระดับยาต้านเชื้อราสูงขึ้น",
        "ยาต้านเชื้อราจะถูกทำลายในกรดน้อยลง จึงได้ระดับยาสูงขึ้น",
      ],
      a: 0,
      r: "Weak base ที่ละลายน้ำน้อยต้องอาศัยกรดในกระเพาะช่วยให้แตกตัวเป็นรูปที่มีประจุและละลายได้ เมื่อละลายแล้วจึงผ่านไปดูดซึมที่ลำไส้เล็ก หาก gastric pH สูงขึ้นจาก PPI หรือ H2-antagonist ยาจะละลายในกระเพาะได้น้อย และเมื่อลงไปถึงลำไส้ที่ pH สูงก็ยิ่งละลายยากขึ้น ทำให้ AUC ลดลง\n\nตัวอย่างสำคัญ ได้แก่ ketoconazole, itraconazole capsule, atazanavir, dasatinib ทางแก้ เช่น หลีกเลี่ยงการใช้ร่วม รับประทานพร้อมเครื่องดื่มที่เป็นกรด หรือเลือกยาที่ไม่ขึ้นกับ pH",
      w: [
        "ถูก — weak base ต้องการ pH ต่ำเพื่อละลาย PPI เพิ่ม gastric pH จึงลดการละลายและ AUC",
        "แม้รูปไม่แตกตัวผ่านเยื่อได้ดี แต่ขั้นจำกัดคือการละลาย ยาที่ไม่ละลายจะไม่ถูกดูดซึม",
        "ยาต้องละลายในกระเพาะก่อนลงลำไส้ หากไม่ละลายตั้งแต่กระเพาะ ที่ลำไส้ก็ยิ่งละลายยาก",
        "ไม่ใช่กลไกหลัก ปฏิกิริยานี้เกิดจากการเปลี่ยน pH",
        "Ketoconazole ไม่ได้ถูกทำลายในกรดเป็นปัญหาหลัก ยาต้องการกรดเพื่อละลาย",
      ],
      k: "Weak base ละลายยาก (ketoconazole, atazanavir) + PPI/H2RA → ละลายลดลง → AUC ลดลง",
      d: "easy",
      ref: "Shargel & Yu, Applied Biopharmaceutics & Pharmacokinetics 7th ed., Ch.14",
    },
    {
      t: "BCS class I biowaiver dissolution conditions",
      p: "บริษัทเตรียมข้อมูลขอ BCS-based biowaiver ของยาเม็ด IR ที่ API เป็น BCS class I ตาม ICH M9 สภาวะการทดสอบ dissolution เปรียบเทียบข้อใดถูกต้อง",
      o: [
        "Paddle 50 rpm หรือ basket 100 rpm, ปริมาตร ≤ 900 mL, pH 1.2, 4.5 และ 6.8 ที่ 37 °C, 12 หน่วย, ไม่ใช้ surfactant",
        "Paddle 75 rpm ใน 0.1 N HCl อย่างเดียว ปริมาตร 1,000 mL และเติม SLS 0.5%",
        "Basket 50 rpm ใน water และ FaSSIF ที่ 25 °C",
        "Flow-through cell ใน pH 7.4 เพื่อเลียนแบบเลือด",
        "Paddle 100 rpm ใน pH 1.2–7.5 ทุก 0.5 หน่วย pH รวม 6 หน่วยต่อสภาวะ",
      ],
      a: 0,
      r: "ICH M9 กำหนดการทดสอบ dissolution เปรียบเทียบสำหรับ BCS biowaiver: USP apparatus 2 (paddle) 50 rpm หรือ apparatus 1 (basket) 100 rpm, ปริมาตร ≤ 900 mL, ใน pH 1.2, 4.5 และ 6.8 buffer ที่ 37 ± 1 °C, ใช้ 12 หน่วยต่อผลิตภัณฑ์ และไม่ใช้ surfactant (enzyme ใช้ได้เฉพาะกรณี gelatin cross-linking)\n\nสำหรับ class I: ถ้าทั้ง test และ reference very rapid (≥ 85% ใน 15 นาที) ถือว่าคล้ายกันโดยไม่ต้องคำนวณ f2 ถ้า rapid (≥ 85% ใน 30 นาที) ต้องแสดง f2 ≥ 50 สภาวะที่ใช้ surfactant หรือ rpm สูงจะลด discriminating power จึงไม่เหมาะกับการพิสูจน์ความเทียบเท่า",
      w: [
        "ถูก — ตรงกับสภาวะของ ICH M9: paddle 50/basket 100 rpm, ≤ 900 mL, 3 pH, 37 °C, 12 หน่วย, ไม่มี surfactant",
        "ICH M9 ห้ามใช้ surfactant และต้องทดสอบ 3 pH ไม่ใช่เฉพาะ 0.1 N HCl",
        "ต้องใช้ 37 °C และ compendial buffers 3 pH ไม่ใช่ water/FaSSIF ที่ 25 °C",
        "ไม่ได้ใช้ flow-through cell และ pH 7.4 ไม่ใช่ medium ที่กำหนด",
        "ความเร็ว 100 rpm สำหรับ paddle สูงเกินไป และกำหนด 12 หน่วยไม่ใช่ 6",
      ],
      k: "ICH M9 biowaiver dissolution: paddle 50/basket 100 rpm, ≤ 900 mL, pH 1.2/4.5/6.8, 37 °C, n = 12, no surfactant",
      d: "medium",
      ref: "ICH M9 Biopharmaceutics Classification System-based Biowaivers (2019), Section 3.2.2",
    },
    {
      t: "Sinker use for floating capsules",
      p: "ระหว่างทดสอบ dissolution ของ hard gelatin capsule ด้วย Apparatus 2 (paddle) พบว่า capsule ลอยขึ้นที่ผิว medium และละลายไม่สม่ำเสมอ ตาม USP <711> ทางแก้ที่เหมาะสมที่สุดคือข้อใด",
      o: [
        "ใช้ sinker (เช่น ลวดขดเป็นเกลียวไม่กี่รอบ) ที่ทำจากวัสดุเฉื่อย โดยระบุชนิดของ sinker ไว้ใน method",
        "เพิ่มความเร็ว paddle เป็น 150 rpm เพื่อดึง capsule ลง",
        "ตัด capsule shell ออกก่อนทดสอบ",
        "ลดอุณหภูมิ medium เพื่อเพิ่มความหนาแน่น",
        "เปลี่ยนไปใช้ disintegration test แทน dissolution",
      ],
      a: 0,
      r: "USP <711> อนุญาตให้ใช้ sinker กับ dosage form ที่ลอยใน Apparatus 2 โดย sinker มาตรฐานคือขดลวดวัสดุเฉื่อย (เช่น stainless steel) ไม่กี่รอบ หรือ sinker แบบที่ validate แล้ว และต้องระบุไว้ใน procedure เพราะรูปแบบของ sinker มีผลต่อผล dissolution\n\nอีกทางหนึ่งคือใช้ Apparatus 1 (basket) ซึ่งนิยมกับ capsule การเปลี่ยน rpm หรืออุณหภูมิผิดไปจากที่กำหนดทำให้ผลไม่ biorelevant และไม่เป็นไปตามตำรายา",
      w: [
        "ถูก — USP <711> ให้ใช้ sinker วัสดุเฉื่อยกับ dosage form ที่ลอย และต้องระบุใน method",
        "การเพิ่ม rpm มากเกินไปลด discriminating power และไม่ได้แก้การลอยอย่างเป็นระบบ",
        "การทำลาย capsule shell เปลี่ยนสภาพผลิตภัณฑ์ ไม่ใช่การทดสอบผลิตภัณฑ์ตามจริง",
        "อุณหภูมิต้องเป็น 37 ± 0.5 °C การลดอุณหภูมิผิดเงื่อนไขของตำรายา",
        "Disintegration ไม่ได้ให้ข้อมูลการละลายของยาและไม่ใช่การทดแทน dissolution ที่กำหนดใน monograph",
      ],
      k: "Capsule ลอยใน paddle → ใช้ sinker ที่ระบุใน method (หรือใช้ basket); ห้ามเปลี่ยน rpm/อุณหภูมิตามใจ",
      d: "easy",
      ref: "USP <711> Dissolution, Apparatus 2",
    },
    {
      t: "Two-tier dissolution for gelatin cross-linking",
      p: "Soft gelatin capsule ที่เก็บในสภาวะความชื้นและอุณหภูมิสูง ให้ผล dissolution ใน 0.1 N HCl ต่ำกว่าเกณฑ์ เมื่อตรวจพบว่ามี pellicle ห่อหุ้ม (gelatin cross-linking) ตาม USP <711> แนวทางที่เหมาะสมคือข้อใด",
      o: [
        "ทำ Tier 2 โดยเติม enzyme ที่เหมาะกับ pH ของ medium (เช่น pepsin สำหรับ medium กรด) ตามปริมาณที่กำหนด แล้วประเมินผลตามเกณฑ์เดิม",
        "เติม SLS ในปริมาณสูงเพื่อละลาย pellicle",
        "บดแคปซูลก่อนทดสอบเพื่อตัดผลของ shell",
        "ปล่อยผ่านเพราะ cross-linking ไม่มีผลใด ๆ ต่อการดูดซึมในร่างกาย",
        "ใช้ pancreatin ใน 0.1 N HCl เพราะเป็น enzyme ที่แรงที่สุด",
      ],
      a: 0,
      r: "Gelatin cross-linking เกิดจากปฏิกิริยาของ gelatin กับ aldehydes หรือสภาวะความชื้น/อุณหภูมิสูง เกิดเป็นเยื่อที่ไม่ละลายน้ำ ทำให้ in vitro dissolution ช้าลง แต่ในร่างกาย enzyme ในทางเดินอาหารย่อยเยื่อได้ จึงอาจไม่กระทบ bioavailability อย่างที่ผล in vitro แสดง\n\nUSP <711> จึงให้ทำ Tier 2 โดยเติม enzyme ที่ทำงานได้ที่ pH ของ medium: pepsin สำหรับ pH ≤ 4.0, papain หรือ bromelain สำหรับ pH > 4.0 ถึง < 6.8 และ pancreatin สำหรับ pH ≥ 6.8 ในปริมาณ activity ที่ไม่เกินกำหนด และต้องผ่านเกณฑ์เดิม อย่างไรก็ตามต้องหาสาเหตุราก (เช่น aldehyde ใน excipient หรือบรรจุภัณฑ์) ตามระบบคุณภาพด้วย",
      w: [
        "ถูก — USP <711> two-tier test ใช้ enzyme ที่เหมาะกับ pH ของ medium และใช้เกณฑ์ acceptance เดิม",
        "Surfactant ไม่ได้ย่อย protein pellicle และเปลี่ยน discriminating power ของวิธี",
        "การบดผลิตภัณฑ์ไม่ใช่การทดสอบ dissolution ของผลิตภัณฑ์ตามจริง",
        "ต้องแสดงด้วย Tier 2 ตามตำรายา ไม่สามารถสรุปว่าไม่มีผลโดยไม่มีข้อมูล",
        "Pancreatin ทำงานที่ pH ≥ 6.8 ใน 0.1 N HCl ต้องใช้ pepsin",
      ],
      k: "Gelatin cross-linking → Tier 2 + enzyme ตาม pH (pepsin กรด, papain/bromelain pH กลาง, pancreatin ≥ 6.8)",
      d: "medium",
      ref: "USP <711> Dissolution, Dissolution Medium (two-tier testing for gelatin capsules); USP <1094>",
    },
    {
      t: "f1 difference factor calculation",
      p: "ค่าเฉลี่ย % dissolved (n = 12) ที่ 10, 15, 20, 30 นาที: Reference = 30, 55, 75, 90 และ Test = 36, 50, 79, 88 ค่า difference factor (f1) เป็นเท่าใด",
      o: ["1.2%", "4.3%", "6.8%", "17.0%", "93.2%"],
      a: 2,
      r: "f1 = [Σ|Rt − Tt| / ΣRt] × 100 วัดความต่างสัมพัทธ์ (percent error) ระหว่างสอง profile เทียบกับ reference ค่า 0 = เหมือนกันทุกจุด เกณฑ์ที่ใช้ทั่วไปคือ f1 0–15 ถือว่าคล้ายกัน (ใช้ร่วมกับ f2 50–100)\n\nค่าสัมบูรณ์ของผลต่าง = 6 + 5 + 4 + 2 = 17 และ ΣR = 30 + 55 + 75 + 90 = 250 จึงได้ f1 = 6.8% ต้องใช้ค่าสัมบูรณ์ ไม่เช่นนั้นผลต่างบวกและลบจะหักล้างกันจนประเมินความต่างต่ำเกินจริง และต้องหารด้วยผลรวมของ reference",
      w: [
        "1.2% เกิดจากรวมผลต่างแบบมีเครื่องหมาย (−6 + 5 − 4 + 2 = −3) ซึ่งหักล้างกัน",
        "4.3% คือค่าเฉลี่ยของผลต่างสัมบูรณ์ (17/4) ไม่ใช่ f1",
        "ถูก — Σ|R − T| = 17, ΣR = 250, f1 = 17/250 × 100 = 6.8%",
        "17.0% คือ Σ|R − T| ที่ยังไม่ได้หารด้วย ΣR",
        "93.2% เกิดจากนำ 100 − f1 ซึ่งไม่ใช่นิยามของ f1",
      ],
      k: "f1 = Σ|R − T|/ΣR × 100; ใช้ค่าสัมบูรณ์ หารด้วย reference; 0–15 = similar",
      d: "medium",
      ref: "Moore JW, Flanner HH. Pharm Tech 1996;20:64–74; FDA Guidance: Dissolution Testing of IR Solid Oral Dosage Forms (1997)",
      c: [
        "|R − T| = |30−36| + |55−50| + |75−79| + |90−88| = 6 + 5 + 4 + 2 = 17",
        "ΣR = 30 + 55 + 75 + 90 = 250",
        "f1 = 17/250 × 100 = 6.8%",
      ],
    },
    {
      t: "IVIVC internal predictability %PE",
      p: "IVIVC Level A ของ ER tablet สร้างจาก 3 สูตร ผลการตรวจ internal predictability ของ Cmax: สูตร slow %PE = 5.0%, สูตร medium %PE = 9.0% และสูตร fast มี Cmax ที่สังเกตได้ 120 ng/mL แต่ model ทำนายได้ 104 ng/mL (AUC ผ่านทุกสูตร) ข้อใดสรุปได้ถูกต้องตามแนวทาง FDA",
      o: [
        "%PE ของสูตร fast = 13.3% ค่าเฉลี่ย %PE ของ Cmax ≈ 9.1% ผ่านเกณฑ์ (เฉลี่ย ≤ 10% และแต่ละสูตร ≤ 15%)",
        "%PE ของสูตร fast = 15.4% เกิน 15% จึงไม่ผ่าน",
        "%PE ของสูตร fast = 13.3% ไม่ผ่าน เพราะแต่ละสูตรต้อง ≤ 10%",
        "ค่าเฉลี่ย %PE ≈ 9.1% ไม่ผ่าน เพราะค่าเฉลี่ยต้อง ≤ 5%",
        "สรุปไม่ได้ เพราะ %PE ต้องคำนวณจาก Tmax ไม่ใช่ Cmax",
      ],
      a: 0,
      r: "การ validate IVIVC แบบ internal predictability ทำโดยใช้ model ทำนาย plasma profile ของสูตรที่ใช้สร้าง model แล้วเทียบกับค่าที่สังเกตได้ %PE = |Observed − Predicted|/Observed × 100 สำหรับ Cmax และ AUC\n\nเกณฑ์ FDA (1997): ค่าเฉลี่ย absolute %PE ≤ 10% และ %PE ของแต่ละสูตร ≤ 15% สูตร fast: |120 − 104|/120 × 100 = 13.3% ค่าเฉลี่ย = (5.0 + 9.0 + 13.3)/3 ≈ 9.1% จึงผ่านเกณฑ์ ความผิดพลาดที่พบบ่อยคือหารด้วยค่าทำนาย (ได้ 15.4%) ซึ่งผิดนิยาม",
      w: [
        "ถูก — %PE = 16/120 = 13.3% ≤ 15% และค่าเฉลี่ย 9.1% ≤ 10%",
        "15.4% ได้จากหารด้วยค่าที่ทำนาย (16/104) ซึ่งผิด %PE ต้องหารด้วยค่าที่สังเกตได้",
        "เกณฑ์รายสูตรคือ ≤ 15% ไม่ใช่ ≤ 10% (10% เป็นเกณฑ์ค่าเฉลี่ย)",
        "เกณฑ์ค่าเฉลี่ยคือ ≤ 10% ไม่ใช่ ≤ 5%",
        "IVIVC validation ใช้ Cmax และ AUC ไม่ใช่ Tmax",
      ],
      k: "IVIVC internal predictability: %PE = |obs − pred|/obs; เฉลี่ย ≤ 10%, แต่ละสูตร ≤ 15% (Cmax และ AUC)",
      d: "hard",
      ref: "FDA Guidance: Extended Release Oral Dosage Forms — Development, Evaluation, and Application of IVIVC (1997)",
      c: [
        "%PE (fast) = |120 − 104|/120 × 100 = 13.3%",
        "Mean %PE = (5.0 + 9.0 + 13.3)/3 = 9.1%",
        "เกณฑ์: mean ≤ 10% ✓ และทุกสูตร ≤ 15% ✓",
      ],
    },
    {
      t: "Sampling adequacy AUC0-t coverage",
      p: "ใน pilot BE study ของยาเม็ด IR ที่มี half-life ประมาณ 12 ชั่วโมง เก็บตัวอย่างเลือดถึง 24 ชั่วโมง ได้ค่าเฉลี่ย AUC₀–24 = 410 ng·h/mL และ AUC₀–∞ = 560 ng·h/mL ข้อใดเป็นข้อสรุปและการแก้ไขที่เหมาะสมสำหรับ pivotal study",
      o: [
        "AUC₀–t ครอบคลุมเพียงประมาณ 73% ของ AUC₀–∞ (ต่ำกว่า 80%) ควรขยายเวลาเก็บตัวอย่างให้ยาวขึ้น เช่น ถึง 48–72 ชั่วโมง",
        "ครอบคลุม 137% จึงเพียงพอแล้ว",
        "ครอบคลุมประมาณ 73% ซึ่งเกิน 70% จึงยอมรับได้ไม่ต้องแก้ไข",
        "ควรเพิ่มจำนวนจุดเก็บตัวอย่างช่วง 0–2 ชั่วโมงเท่านั้น โดยไม่ต้องขยายเวลา",
        "ให้ใช้ Cmax อย่างเดียวในการประเมิน BE เพราะ AUC ไม่น่าเชื่อถือ",
      ],
      a: 0,
      r: "แนวทาง EMA กำหนดให้ช่วงเวลาเก็บตัวอย่างนานพอที่ AUC₀–t ครอบคลุมอย่างน้อย 80% ของ AUC₀–∞ (สำหรับยา IR ทั่วไปไม่จำเป็นต้องเก็บเกิน 72 ชั่วโมง) ในโจทย์ 410/560 = 73% หรือส่วน extrapolate 27% แสดงว่าเก็บตัวอย่างสั้นเกินไป (24 ชั่วโมงเท่ากับเพียง 2 half-lives)\n\nการแก้คือขยายเวลาเก็บตัวอย่างให้ครอบคลุมระยะ elimination อย่างเพียงพอ (เช่น 48–72 ชั่วโมง หรือ ≥ 3–5 half-lives) และกระจายจุดในช่วง terminal phase อย่างน้อย 3–4 จุดเพื่อประมาณ λz ได้น่าเชื่อถือ ส่วนจุดถี่ช่วงต้นช่วยเรื่อง Cmax แต่ไม่แก้ปัญหานี้",
      w: [
        "ถูก — 410/560 = 73% < 80% แสดงว่าช่วงเก็บตัวอย่างสั้นเกินไป ต้องขยายเวลา",
        "คำนวณกลับด้าน (560/410) ซึ่งไม่ใช่สัดส่วนการครอบคลุม",
        "เกณฑ์คือ ≥ 80% ไม่ใช่ 70%",
        "จุดช่วงต้นช่วยประมาณ Cmax/Tmax แต่ไม่ช่วยเพิ่มการครอบคลุม AUC ในช่วงท้าย",
        "BE ต้องประเมินทั้ง AUC และ Cmax ไม่สามารถตัด AUC ออกได้",
      ],
      k: "AUC₀–t ควร ≥ 80% ของ AUC₀–∞; ยา IR ไม่ต้องเก็บตัวอย่างเกิน 72 h",
      d: "medium",
      ref: "EMA Guideline on the Investigation of Bioequivalence CPMP/EWP/QWP/1401/98 Rev.1, Section 4.1.5",
      c: [
        "Coverage = AUC₀–24/AUC₀–∞ = 410/560 = 0.732 = 73.2%",
        "Extrapolated = 100 − 73.2 = 26.8% > 20% → sampling ไม่พอ",
      ],
    },
    {
      t: "Fed bioequivalence study meal",
      p: "บริษัทวางแผน fed BE study ตามแนวทาง FDA สำหรับยาที่ฉลากระบุว่ารับประทานพร้อมอาหารได้ ข้อใดเป็นการจัดการที่ถูกต้อง",
      o: [
        "ใช้อาหาร high-fat, high-calorie (ประมาณ 800–1,000 kcal โดยราว 50% ของพลังงานมาจากไขมัน) เริ่มรับประทานอาหาร 30 นาทีก่อนให้ยา และให้ยาพร้อมน้ำประมาณ 240 mL",
        "ใช้อาหาร low-fat 300 kcal และให้ยา 2 ชั่วโมงหลังอาหาร",
        "ให้อาสาสมัครเลือกอาหารเองตามความชอบเพื่อสะท้อนการใช้จริง",
        "ให้ยาก่อนอาหาร 1 ชั่วโมงแล้วตามด้วยอาหาร high-fat",
        "ใช้น้ำผลไม้ 500 mL แทนอาหารเพื่อควบคุมปริมาณไขมัน",
      ],
      a: 0,
      r: "Fed BE study มีวัตถุประสงค์ทดสอบภายใต้สภาวะที่อาหารมีผลต่อสรีรวิทยาทางเดินอาหารมากที่สุด (gastric emptying ช้า, หลั่ง bile มาก, pH และ splanchnic blood flow เปลี่ยน) จึงใช้อาหาร high-fat (ประมาณ 50% ของพลังงาน) high-calorie (800–1,000 kcal) แบบมาตรฐาน\n\nอาสาสมัครเริ่มรับประทานอาหารหลังอดอาหารข้ามคืนอย่างน้อย 10 ชั่วโมง ทานให้หมดภายใน 30 นาที และได้รับยา 30 นาทีหลังเริ่มอาหารพร้อมน้ำ 240 mL (8 oz) อาหารต้องเหมือนกันในทุก period และทุกคนเพื่อลด variability",
      w: [
        "ถูก — FDA กำหนดอาหาร high-fat (~50%) high-calorie (800–1,000 kcal) ให้ยา 30 นาทีหลังเริ่มอาหาร พร้อมน้ำ 240 mL",
        "อาหาร low-fat ไม่ใช่สภาวะมาตรฐานที่ทดสอบผลของอาหารสูงสุด และเวลาให้ยาไม่ถูกต้อง",
        "อาหารต้องเป็นมาตรฐานเดียวกันเพื่อลด variability ไม่ให้เลือกเอง",
        "ลำดับผิด ยาต้องให้หลังเริ่มอาหาร 30 นาที",
        "น้ำผลไม้ (เช่น grapefruit) อาจรบกวน PK และไม่ใช่อาหารมาตรฐาน",
      ],
      k: "Fed BE: high-fat ~50%, 800–1,000 kcal, เริ่มอาหาร 30 นาทีก่อนให้ยา, น้ำ 240 mL",
      d: "medium",
      ref: "FDA Guidance: Assessing the Effects of Food on Drugs in INDs and NDAs — Clinical Pharmacology Considerations (2022)",
    },
    {
      t: "Steady-state BE study in patients",
      p: "บริษัทพัฒนา generic clozapine tablet ซึ่งการให้ยาครั้งเดียวในอาสาสมัครสุขภาพดีมีความเสี่ยงด้านความปลอดภัย (เช่น orthostatic hypotension, ชัก, agranulocytosis) รูปแบบ BE study ใดเหมาะสมที่สุด",
      o: [
        "Multiple-dose steady-state crossover study ในผู้ป่วยที่ได้รับยาอยู่แล้ว โดยเปรียบเทียบ AUCτ และ Cmax,ss",
        "Single-dose study ในอาสาสมัครสุขภาพดีโดยลดขนาดยาลง 90% โดยไม่ต้องพิจารณาความเป็นเส้นตรงของ PK",
        "ใช้ BCS biowaiver แทนได้ทันทีเพราะยาเป็นยาจิตเวช",
        "Parallel design ในอาสาสมัครสุขภาพดีด้วยขนาดยาสูงสุด",
        "ใช้เฉพาะ dissolution f2 เทียบกับ reference ใน pH 1.2",
      ],
      a: 0,
      r: "โดยหลักแล้ว BE ทำแบบ single-dose ในอาสาสมัครสุขภาพดีเพราะไวต่อการตรวจจับความแตกต่างของการปลดปล่อยยามากที่สุด แต่หากยามีความเสี่ยงหรือทนไม่ได้ในคนสุขภาพดี (เช่น clozapine, ยาต้านมะเร็งบางชนิด) จะทำการศึกษาในผู้ป่วยที่ได้รับยาอยู่แล้ว ซึ่งในทางปฏิบัติต้องเป็นแบบ multiple-dose ที่ steady state เพราะไม่สามารถหยุดยาให้ผู้ป่วยได้\n\nตัวแปรหลักคือ AUC ในช่วงระหว่าง dose (AUCτ) และ Cmax,ss (อาจรวม Cmin,ss/Cτ) และต้องยืนยันว่าเข้าสู่ steady state ด้วยระดับยา trough หลายจุด การศึกษาแบบนี้ไวน้อยกว่าแบบ single dose แต่จำเป็นด้วยเหตุผลด้านจริยธรรม",
      w: [
        "ถูก — เมื่อ single dose ในคนสุขภาพดีไม่ปลอดภัย ใช้ steady-state crossover ในผู้ป่วย วัด AUCτ และ Cmax,ss",
        "การลดขนาดยาลงมากอาจไม่สะท้อน strength ที่ขอทะเบียน และยังไม่ตัดความเสี่ยงทั้งหมด",
        "BCS biowaiver ขึ้นกับ solubility/permeability ไม่ใช่กลุ่มยาทางคลินิก และต้องเข้าเกณฑ์ ICH M9",
        "การให้ขนาดยาสูงในคนสุขภาพดีเพิ่มความเสี่ยง ขัดหลักจริยธรรม",
        "Dissolution ที่ pH เดียวไม่เพียงพอใช้แทน in vivo BE ของยากลุ่มนี้",
      ],
      k: "ยาไม่ปลอดภัยในคนสุขภาพดี → steady-state BE ในผู้ป่วย; ประเมิน AUCτ, Cmax,ss",
      d: "hard",
      ref: "FDA Draft Product-Specific Guidance on Clozapine Tablets; EMA CPMP/EWP/QWP/1401/98 Rev.1, Section 4.1.1",
    },
  ],
];
