import type { Ip1MockDomainContent } from "@/lib/ip1-mock/types";

export const CALC: Ip1MockDomainContent = [
  // Mock Set 1 — การคำนวณและสถิติในการผลิต
  [
    {
      t: "Master formula batch scaling",
      p: "Master formula ของยาเม็ด paracetamol ระบุสูตรต่อ 1,000 เม็ดดังนี้: paracetamol 500 g, microcrystalline cellulose 120 g, PVP K30 15 g, croscarmellose sodium 20 g และ magnesium stearate 5 g หากต้องผลิต batch ขนาด 250,000 เม็ด ต้องเตรียม PVP K30 กี่ kg",
      o: ["0.375 kg", "1.5 kg", "3.75 kg", "15 kg", "37.5 kg"],
      a: 2,
      r: "การขยายสูตร (batch scaling) จาก master formula ใช้ scale factor = batch size ที่ต้องการ ÷ batch size ของสูตรอ้างอิง โดยคูณทุกส่วนประกอบด้วย factor เดียวกันเพื่อรักษาสัดส่วนสูตร\n\nScale factor = 250,000/1,000 = 250 ดังนั้น PVP K30 = 15 g × 250 = 3,750 g = 3.75 kg จุดที่มักพลาดคือการแปลงหน่วย g → kg (หาร 1,000) และการนับเลขศูนย์ของ batch size ผิด",
      w: [
        "ผิดหลักทศนิยม 1 ตำแหน่ง (เหมือนใช้ factor 25 แทน 250)",
        "ไม่ใช่ — เป็นตัวเลขที่ไม่มีที่มาจากสัดส่วนสูตร อาจเกิดจากคิด 15 g × 100",
        "ถูก — 15 g × (250,000/1,000) = 3,750 g = 3.75 kg",
        "เป็นการใช้ 15 g ต่อ 1,000 เม็ดแล้วคูณ 1,000 (นับ batch เป็น 1,000,000 เม็ด) ทำให้มากเกินจริง 4 เท่า",
        "ผิดหลักทศนิยม 1 ตำแหน่ง (คูณ 2,500 แทน 250)",
      ],
      k: "Scale factor = batch ที่ต้องการ ÷ batch ในสูตรอ้างอิง แล้วคูณทุกส่วนประกอบเท่ากัน ระวังการแปลงหน่วย",
      d: "easy",
      ref: "PIC/S GMP Guide PE 009 Part I Ch.4 (Manufacturing Formula and Processing Instructions)",
      c: ["Scale factor = 250,000 ÷ 1,000 = 250", "PVP K30 = 15 g × 250 = 3,750 g", "3,750 g ÷ 1,000 = 3.75 kg"],
    },
    {
      t: "Actual yield percentage",
      p: "Batch ยาเม็ด 200,000 เม็ด น้ำหนักเม็ด 300 mg (theoretical yield = 60.0 kg) เมื่อสิ้นสุดการตอก ได้ยาเม็ดที่ผ่านเกณฑ์ 57.3 kg, เก็บตัวอย่าง QC 0.3 kg และยาเม็ด reject 1.2 kg ค่า actual yield (%) ของยาเม็ดที่ผ่านเกณฑ์เท่าใด",
      o: ["93.5%", "95.5%", "96.0%", "97.4%", "98.0%"],
      a: 1,
      r: "Actual yield (%) = ปริมาณผลผลิตที่ได้จริง ÷ theoretical yield × 100 โดย theoretical yield คำนวณจากปริมาณที่ควรได้หากไม่มีการสูญเสีย (200,000 × 300 mg = 60.0 kg)\n\nดังนั้น yield = 57.3/60.0 × 100 = 95.5% ส่วนค่า 98.0% คือ accountability/reconciliation ((57.3+0.3+1.2)/60.0) ซึ่งใช้ตรวจว่ามวลสารถูกติดตามครบหรือไม่ ทั้งสองค่าต้องอยู่ในช่วงที่ validate ไว้ใน batch record หากนอกช่วงต้องสอบสวนตาม 21 CFR 211.192",
      w: [
        "เป็นการหัก reject ออกซ้ำจากยาเม็ดดี ((57.3−1.2)/60) ไม่มีหลักการรองรับ",
        "ถูก — 57.3/60.0 × 100 = 95.5%",
        "รวมตัวอย่าง QC เข้ากับยาเม็ดดี ((57.3+0.3)/60) ซึ่งไม่ใช่ yield ของผลผลิตที่จำหน่ายได้",
        "ใช้ผลรวมที่ติดตามได้ (58.8 kg) เป็นตัวหารแทน theoretical yield จึงผิดนิยาม",
        "เป็นค่า accountability (57.3+0.3+1.2 = 58.8 kg; 98.0%) ไม่ใช่ actual yield",
      ],
      k: "Yield = ผลผลิตที่ดี ÷ theoretical × 100; accountability = (ผลผลิต + ตัวอย่าง + reject + loss ที่ระบุได้) ÷ theoretical × 100",
      d: "easy",
      ref: "21 CFR 211.103 Calculation of yield; PIC/S GMP Guide PE 009 Part I Ch.5",
      c: [
        "Theoretical yield = 200,000 × 300 mg = 60,000,000 mg = 60.0 kg",
        "Actual yield = 57.3 / 60.0 × 100 = 95.5%",
        "(เปรียบเทียบ) Accountability = (57.3 + 0.3 + 1.2)/60.0 × 100 = 98.0%",
      ],
    },
    {
      t: "Overage with potency adjustment",
      p: "ยาเม็ด vitamin C label claim 100 mg/เม็ด บริษัทกำหนด manufacturing overage 7.5% (เติมเพิ่มจาก label claim เพื่อชดเชยการสลายตัวที่พิสูจน์แล้ว) วัตถุดิบ ascorbic acid lot ที่ใช้มี assay 98.0% (as-is) หากผลิต 400,000 เม็ด ต้องชั่ง ascorbic acid lot นี้ประมาณกี่ kg",
      o: ["40.00 kg", "40.82 kg", "43.00 kg", "43.88 kg", "44.13 kg"],
      a: 3,
      r: "Overage คิดเป็นเปอร์เซ็นต์เพิ่มจาก label claim: ปริมาณเป้าหมายต่อเม็ด = 100 × 1.075 = 107.5 mg (สาร 100%) จากนั้นแก้ potency ของวัตถุดิบโดยหารด้วย 0.980 ได้ 109.69 mg/เม็ด × 400,000 เม็ด = 43.88 kg\n\nICH Q8(R2) ระบุว่า overage ต้องมีเหตุผลรองรับ (เช่น ชดเชยการสูญเสียในกระบวนการผลิตหรือการสลายตัว) และต้องระบุใน dossier ไม่ควรใช้ overage เพื่อยืด shelf life โดยไม่มีข้อมูล ลำดับการคิด: label claim → บวก overage → หารด้วย potency → คูณจำนวนเม็ด",
      w: [
        "ไม่ได้คิดทั้ง overage และ potency (100 mg × 400,000)",
        "แก้เฉพาะ potency (100/0.98 × 400,000) ลืม overage 7.5%",
        "คิดเฉพาะ overage (107.5 mg × 400,000) ลืมแก้ potency 98.0%",
        "ถูก — 100 × 1.075 ÷ 0.980 = 109.69 mg/เม็ด × 400,000 = 43.88 kg",
        "ตีความ overage ผิดเป็นการหาร (100/0.925) ทำให้ได้ปริมาณเกินกว่าที่กำหนด",
      ],
      k: "ปริมาณชั่ง = label claim × (1 + %overage) ÷ potency (เศษส่วน) × จำนวนหน่วย",
      d: "medium",
      ref: "ICH Q8(R2) Pharmaceutical Development, section 2.2.1 (Overages)",
      c: [
        "เป้าหมายต่อเม็ด = 100 mg × 1.075 = 107.5 mg (pure)",
        "แก้ potency = 107.5 ÷ 0.980 = 109.69 mg ของวัตถุดิบ/เม็ด",
        "ทั้ง batch = 109.69 mg × 400,000 = 43,877,551 mg ≈ 43.88 kg",
      ],
    },
    {
      t: "Anhydrous-basis potency weighing",
      p: "Certificate of Analysis ของ API ระบุ assay 99.2% on anhydrous basis และ water content (KF) 4.8% สูตรการผลิตกำหนดให้ใช้ API (คิดเป็น 100% anhydrous) 25.0 kg ต่อ batch ต้องชั่ง API lot นี้ (as-is) ประมาณกี่ kg",
      o: ["23.61 kg", "25.20 kg", "26.26 kg", "26.40 kg", "26.47 kg"],
      a: 4,
      r: "เมื่อ assay รายงานบน anhydrous basis ต้องแปลงเป็น as-is ก่อน: potency as-is = assay(anhydrous) × (1 − water fraction) = 0.992 × 0.952 = 0.9444 (94.44%)\n\nปริมาณชั่ง = 25.0 ÷ 0.9444 = 26.47 kg การบวกเปอร์เซ็นต์รวมกัน (100 + 0.8 + 4.8 = 105.6%) เป็นการประมาณที่ผิดเล็กน้อยแต่ในงาน GMP ต้องใช้สูตรที่ถูกต้องเพราะ error สะสมใน batch ใหญ่ หลักคือ ‘แปลง basis ให้ตรงกับสภาพของวัตถุที่ชั่งจริง’",
      w: [
        "นำ potency ไปคูณแทนการหาร (25 × 0.992 × 0.952) ทำให้ได้ API ไม่ครบ",
        "แก้เฉพาะ assay 99.2% ลืมหักน้ำ 4.8%",
        "แก้เฉพาะ water 4.8% ลืมแก้ assay 99.2%",
        "บวกเปอร์เซ็นต์ขาดแบบเส้นตรง (25 × 1.056) เป็นการประมาณที่ไม่ถูกต้องตามหลักคณิตศาสตร์",
        "ถูก — 25.0 ÷ (0.992 × 0.952) = 25.0 ÷ 0.9444 = 26.47 kg",
      ],
      k: "Potency as-is = assay(anhydrous) × (1 − %water/100); ปริมาณชั่ง = ปริมาณที่ต้องการ ÷ potency as-is",
      d: "medium",
      ref: "Ansel's Pharmaceutical Calculations 15th ed.; USP <921> Water Determination",
      c: [
        "Potency as-is = 0.992 × (1 − 0.048) = 0.992 × 0.952 = 0.9444",
        "ปริมาณชั่ง = 25.0 kg ÷ 0.9444 = 26.47 kg",
      ],
    },
    {
      t: "Sample RSD of tablet weights",
      p: "IPC ระหว่างตอกยาเม็ดสุ่มชั่ง 5 เม็ดได้น้ำหนัก 248, 252, 250, 255 และ 245 mg ค่า relative standard deviation (%RSD) โดยใช้ sample standard deviation (n − 1) ใกล้เคียงข้อใด",
      o: ["0.30%", "1.36%", "1.52%", "4.00%", "5.80%"],
      a: 2,
      r: "Mean = 1,250/5 = 250 mg ผลรวมกำลังสองของส่วนเบี่ยงเบน = 4 + 4 + 0 + 25 + 25 = 58 จากนั้น sample variance = 58/(5−1) = 14.5 และ SD = √14.5 = 3.81 mg\n\n%RSD = 3.81/250 × 100 = 1.52% ในงาน QC ใช้ sample SD (n − 1) เพราะเป็นการประมาณค่าความแปรปรวนของประชากรจากตัวอย่าง (Bessel's correction) หากใช้ n จะได้ค่าต่ำเกินจริง (1.36%) โดยเฉพาะเมื่อ n น้อย",
      w: [
        "หาร RSD ด้วย n อีกครั้ง (คล้าย standard error) ไม่ใช่ RSD",
        "ใช้ population SD (หารด้วย n = 5) ทำให้ค่าต่ำกว่าความจริง",
        "ถูก — SD = √(58/4) = 3.81 mg; RSD = 3.81/250 × 100 = 1.52%",
        "เป็น range/mean (10/250) ไม่ใช่ RSD",
        "นำ variance (14.5) ไปหารด้วย mean แทน SD",
      ],
      k: "%RSD = (sample SD / mean) × 100 โดย sample SD ใช้ n − 1 ในตัวหาร",
      d: "medium",
      ref: "USP <1010> Analytical Data—Interpretation and Treatment",
      c: [
        "Mean = (248+252+250+255+245)/5 = 1,250/5 = 250 mg",
        "Σ(x − mean)² = 4 + 4 + 0 + 25 + 25 = 58",
        "SD = √(58/4) = √14.5 = 3.81 mg",
        "%RSD = 3.81/250 × 100 = 1.52%",
      ],
    },
    {
      t: "Square-root-of-N-plus-one sampling",
      p: "คลังรับ lactose monohydrate จาก supplier ที่ผ่านการรับรอง (qualified) 1 lot จำนวน 70 ถุง (containers) ตามแผน sampling แบบ √N + 1 ต้องเปิดเก็บตัวอย่างจากกี่ container",
      o: ["8", "9", "10", "11", "70"],
      a: 2,
      r: "สูตร n = √N + 1 ใช้กับวัตถุดิบที่มาจาก supplier ที่เชื่อถือได้และ lot เป็นเนื้อเดียวกัน: √70 = 8.37; 8.37 + 1 = 9.37 ปัดขึ้นเป็นจำนวนเต็มถัดไป = 10 containers\n\nWHO guideline กำหนดให้ปัดขึ้น (round up) เสมอ เพื่อไม่ให้ขนาดตัวอย่างต่ำกว่าแผน นอกจากนี้ PIC/S Annex 8 ยังกำหนดว่าการทดสอบ identity ควรทำจากทุก container เว้นแต่มีการ validate ขั้นตอนที่ลดได้ ดังนั้น √N + 1 เป็นแผนสำหรับ composite/full testing ไม่ได้ยกเว้น identity check",
      w: [
        "ใช้เพียง √70 แล้วปัดลง ลืม +1",
        "ปัด 9.37 ลงเป็น 9 ซึ่งขัดกับหลักการปัดขึ้น",
        "ถูก — √70 + 1 = 9.37 → ปัดขึ้นเป็น 10 containers",
        "ปัดขึ้นสองครั้ง (√70 ≈ 9 แล้ว +1 แล้วปัดอีก) เกินกว่าแผน",
        "การเปิดทุก container เป็นแนวทางของ identity test ไม่ใช่ขนาดตัวอย่างตามแผน √N + 1",
      ],
      k: "n = √N + 1 แล้วปัดขึ้นเป็นจำนวนเต็มเสมอ; identity test ยังต้องทำทุก container ตาม Annex 8 (เว้นแต่ validate แล้ว)",
      d: "medium",
      ref: "WHO TRS 929 Annex 4 (Guidelines for sampling of pharmaceutical products); PIC/S GMP Annex 8",
      c: ["√70 = 8.37", "n = 8.37 + 1 = 9.37", "ปัดขึ้น → 10 containers"],
    },
    {
      t: "Process capability index Cpk",
      p: "ผลการวิเคราะห์ assay ของยาเม็ด 30 batches ล่าสุดมี mean 101.2% LC และ SD 1.1% (process อยู่ใน statistical control) specification 95.0–105.0% LC ค่า Cpk ของกระบวนการเท่าใด",
      o: ["0.58", "1.15", "1.52", "1.88", "3.45"],
      a: 1,
      r: "Cpk = min[(USL − mean)/3σ, (mean − LSL)/3σ] แสดงความสามารถของกระบวนการที่คำนึงถึงตำแหน่งของ mean\n\nCPU = (105.0 − 101.2)/(3 × 1.1) = 3.8/3.3 = 1.15; CPL = (101.2 − 95.0)/3.3 = 1.88 → Cpk = 1.15 ขณะที่ Cp = (105 − 95)/(6 × 1.1) = 1.52 ความต่างระหว่าง Cp และ Cpk บอกว่ากระบวนการ off-center ไปทาง USL หากปรับ mean เข้ากลาง (100%) จะได้ Cpk ใกล้ Cp ค่า Cpk < 1.33 มักถือว่ายังไม่ capable เพียงพอสำหรับ critical quality attribute",
      w: [
        "ใช้ 6σ ในตัวหารของ CPU (3.8/6.6) ซึ่งผิดสูตร",
        "ถูก — Cpk = min(1.15, 1.88) = 1.15",
        "เป็นค่า Cp ซึ่งไม่คำนึงถึงตำแหน่ง mean",
        "เป็น CPL ซึ่งเป็นด้านที่ห่างจาก spec มากกว่า ต้องเลือกค่าต่ำสุด",
        "ไม่ได้หารด้วย 3 (3.8/1.1) เป็นระยะห่างในหน่วย σ ไม่ใช่ Cpk",
      ],
      k: "Cpk = ค่าน้อยกว่าระหว่าง (USL−x̄)/3σ และ (x̄−LSL)/3σ; Cp > Cpk แปลว่า process ไม่อยู่กลาง spec",
      d: "medium",
      ref: "Montgomery, Introduction to Statistical Quality Control 8th ed., Ch.8 (Process Capability)",
      c: [
        "CPU = (105.0 − 101.2)/(3 × 1.1) = 3.8/3.3 = 1.15",
        "CPL = (101.2 − 95.0)/(3 × 1.1) = 6.2/3.3 = 1.88",
        "Cpk = min(1.15, 1.88) = 1.15",
      ],
    },
    {
      t: "Water removal during granule drying",
      p: "Wet granules จาก high-shear granulator มีน้ำหนัก 120 kg และวัด LOD ได้ 22% (wet basis) ต้องการทำให้แห้งใน fluid bed dryer จนได้ LOD 2.5% (wet basis) จะต้องระเหยน้ำออกประมาณกี่ kg",
      o: ["23.4 kg", "24.0 kg", "26.4 kg", "93.6 kg", "96.0 kg"],
      a: 1,
      r: "LOD (wet basis) = น้ำ ÷ น้ำหนักรวม ดังนั้นต้องยึด ‘dry solids’ เป็นค่าคงที่ระหว่างการอบ: dry solids = 120 × (1 − 0.22) = 93.6 kg\n\nน้ำหนักสุดท้ายที่ LOD 2.5% = 93.6 ÷ (1 − 0.025) = 96.0 kg ดังนั้นน้ำที่ต้องระเหย = 120 − 96.0 = 24.0 kg ข้อผิดพลาดที่พบบ่อยคือนำ %LOD มาลบกันตรงๆ (22 − 2.5 = 19.5% ของ 120 kg) ซึ่งผิดเพราะตัวหาร (น้ำหนักรวม) เปลี่ยนไประหว่างการอบ การคำนวณนี้ใช้ประมาณ endpoint และ drying capacity",
      w: [
        "ลบ %LOD ตรงๆ (120 × 0.195) ผิดเพราะ basis ของ LOD เปลี่ยนเมื่อมวลรวมลดลง",
        "ถูก — dry solids 93.6 kg; มวลสุดท้าย 93.6/0.975 = 96.0 kg; น้ำที่ระเหย 120 − 96 = 24.0 kg",
        "เป็นปริมาณน้ำทั้งหมดใน wet granules (ทำให้แห้งสนิท LOD 0%) ไม่ตรงเป้าหมาย 2.5%",
        "เป็นน้ำหนัก dry solids ไม่ใช่น้ำที่ระเหย",
        "เป็นน้ำหนัก granules หลังอบแห้ง ไม่ใช่น้ำที่ระเหย",
      ],
      k: "ยึด dry solids คงที่: มวลสุดท้าย = มวลเปียก × (1 − LOD₁) ÷ (1 − LOD₂); น้ำที่ระเหย = มวลเปียก − มวลสุดท้าย",
      d: "hard",
      ref: "Aulton's Pharmaceutics 6th ed. (Drying chapter); USP <731> Loss on Drying",
      c: [
        "Dry solids = 120 × (1 − 0.22) = 93.6 kg",
        "มวลที่ LOD 2.5% = 93.6 ÷ 0.975 = 96.0 kg",
        "น้ำที่ระเหย = 120 − 96.0 = 24.0 kg",
      ],
    },
    {
      t: "Western Electric run rule",
      p: "X̄-chart ของน้ำหนักยาเม็ด (subgroup n = 5) มี control limits ที่คำนวณจาก Phase I ข้อมูล 9 subgroups ล่าสุดทุกจุดอยู่เหนือ center line โดยอยู่ระหว่าง center line ถึง +2σ ไม่มีจุดใดเกิน control limits และทุกเม็ดผ่าน specification ข้อสรุปและการดำเนินการใดเหมาะสมที่สุด",
      o: [
        "เป็น special-cause signal (≥ 8 จุดติดกันด้านเดียวของ center line) ควรสอบสวนหาสาเหตุ process shift แม้ยังอยู่ใน control limits",
        "Process อยู่ใน statistical control เพราะไม่มีจุดใดเกิน ±3σ จึงไม่ต้องดำเนินการใด",
        "ควรคำนวณ control limits ใหม่ทันทีโดยรวม 9 จุดล่าสุด เพื่อให้ center line สะท้อนระดับปัจจุบัน",
        "เป็น common-cause variation เพราะทุกจุดอยู่ใน zone B/C และยังผ่าน specification",
        "ควรปรับตั้งเครื่องลดน้ำหนักทุกครั้งที่จุดอยู่เหนือ center line เพื่อชดเชยทันที",
      ],
      a: 0,
      r: "Western Electric/Nelson rules ใช้ตรวจ non-random pattern นอกเหนือจากจุดที่เกิน 3σ: Rule 1 = 1 จุดเกิน 3σ, Rule 2 = 2 ใน 3 จุดเกิน 2σ ด้านเดียว, Rule 3 = 4 ใน 5 จุดเกิน 1σ ด้านเดียว, Rule 4 = 8 จุดติดกันด้านเดียวของ center line (Nelson ใช้ 9 จุด)\n\nความน่าจะเป็นที่จุด 8–9 จุดอยู่ด้านเดียวกันโดยบังเอิญเพียง ~0.4% (0.5^8) จึงบ่งชี้ว่าค่าเฉลี่ยขยับ (เช่น fill depth drift, granule density เปลี่ยน) ต้องหา assignable cause ก่อน ไม่ควรคำนวณ limits ใหม่จากข้อมูลที่มี special cause และไม่ควร tamper ทีละจุด เพราะจะเพิ่มความแปรปรวน ข้อสำคัญ: control limits สะท้อน ‘เสียงของกระบวนการ’ ส่วน spec คือ ‘เสียงของลูกค้า’ การผ่าน spec จึงไม่ได้แปลว่ากระบวนการ in control",
      w: [
        "ถูก — run ≥ 8 (หรือ 9 ตาม Nelson) จุดด้านเดียวเป็น special-cause signal ต้องสอบสวนหา process shift",
        "ดูเฉพาะ Rule 1 ละเลย run rules ที่ไวต่อการเลื่อนของ mean ขนาดเล็ก",
        "การคำนวณ limits ใหม่จากข้อมูลที่มี special cause จะกลบปัญหา ต้องหาสาเหตุและแก้ก่อน",
        "Pattern ที่ไม่สุ่มไม่ใช่ common cause; การผ่าน spec ไม่เกี่ยวกับ statistical control",
        "การปรับเครื่องทุกจุด (tampering/over-adjustment) จะเพิ่ม variation ตามการทดลอง funnel ของ Deming",
      ],
      k: "Spec ผ่าน ≠ in control; run 8–9 จุดด้านเดียวของ CL = special cause ต้องสอบสวน ไม่ใช่ปรับ limits หรือ tamper",
      d: "hard",
      ref: "Western Electric Statistical Quality Control Handbook (1956); Montgomery, Introduction to Statistical Quality Control 8th ed., Ch.6",
    },
    {
      t: "2x2 factorial main effect calculation",
      p: "การศึกษา 2² full factorial ของ wet granulation: Factor A = ปริมาณน้ำ granulating fluid (ต่ำ/สูง), Factor B = impeller speed (ต่ำ/สูง) ผล % dissolution ที่ 30 นาที: A−B− = 72%, A+B− = 80%, A−B+ = 76%, A+B+ = 90% Main effect ของ factor A เท่ากับเท่าใด",
      o: ["3.0%", "5.5%", "7.0%", "11.0%", "22.0%"],
      a: 3,
      r: "Main effect ของ factor = ค่าเฉลี่ยของ response ที่ระดับสูง − ค่าเฉลี่ยที่ระดับต่ำ (เฉลี่ยข้ามระดับของ factor อื่น)\n\nA: (80 + 90)/2 − (72 + 76)/2 = 85 − 74 = 11.0% ส่วน B = (76 + 90)/2 − (72 + 80)/2 = 7.0% และ interaction AB = (72 + 90)/2 − (80 + 76)/2 = 3.0% ค่า 5.5 คือ regression coefficient (effect/2) ใน coded model (−1/+1) ซึ่งต่างจาก ‘effect’ ระวังสับสนในการตีความผล DOE",
      w: [
        "เป็น interaction effect AB ไม่ใช่ main effect ของ A",
        "เป็น coded regression coefficient (effect ÷ 2) ไม่ใช่ effect",
        "เป็น main effect ของ factor B",
        "ถูก — (80 + 90)/2 − (72 + 76)/2 = 85 − 74 = 11.0%",
        "เป็นผลต่างของผลรวมโดยไม่หารด้วยจำนวน run ในแต่ละระดับ (170 − 148)",
      ],
      k: "Effect = x̄(+) − x̄(−); coefficient ใน coded model = effect/2",
      d: "hard",
      ref: "Montgomery, Design and Analysis of Experiments 9th ed., Ch.6 (2^k factorial); ICH Q8(R2)",
      c: [
        "x̄(A+) = (80 + 90)/2 = 85",
        "x̄(A−) = (72 + 76)/2 = 74",
        "Main effect A = 85 − 74 = 11.0%",
      ],
    },
  ],
  // Mock Set 2 — การคำนวณและสถิติในการผลิต
  [
    {
      t: "Rotary press batch run time",
      p: "เครื่องตอกยาเม็ดแบบ rotary ชนิด single-sided มี 36 stations ตั้ง turret speed 50 rpm (1 เม็ดต่อ station ต่อรอบ) หาก overall equipment efficiency (เวลาทำงานจริงรวมการหยุดเครื่อง) เท่ากับ 80% การตอก batch 540,000 เม็ดจะใช้เวลาประมาณกี่ชั่วโมง",
      o: ["2.5 h", "4.0 h", "5.0 h", "6.0 h", "6.25 h"],
      a: 4,
      r: "Output เชิงทฤษฎีของ rotary press = จำนวน stations × rpm × จำนวนเม็ดต่อ station ต่อรอบ × 60 = 36 × 50 × 1 × 60 = 108,000 เม็ด/ชั่วโมง\n\nที่ efficiency 80% output จริง = 86,400 เม็ด/ชั่วโมง → 540,000/86,400 = 6.25 ชั่วโมง ประสิทธิภาพต้องนำไป ‘หาร’ เวลาทฤษฎี (5.0/0.8) ไม่ใช่บวกเปอร์เซ็นต์แบบเส้นตรง และต้องตรวจว่าเครื่องเป็น single- หรือ double-sided (double-sided ให้ 2 เม็ดต่อ station ต่อรอบ)",
      w: [
        "สมมติว่าเป็น double-sided press (2 เม็ด/station/รอบ) และไม่คิด efficiency",
        "นำ efficiency ไปคูณเวลา (5.0 × 0.8) ทำให้เวลาสั้นลงซึ่งขัดกับความจริง",
        "เป็นเวลาทฤษฎีที่ efficiency 100% ยังไม่คิดการหยุดเครื่อง",
        "บวก 20% แบบเส้นตรง (5.0 × 1.2) ซึ่งไม่ถูกต้อง เพราะ efficiency ต้องหาร",
        "ถูก — 36 × 50 × 60 = 108,000 เม็ด/h; × 0.8 = 86,400 เม็ด/h; 540,000/86,400 = 6.25 h",
      ],
      k: "Output/h = stations × rpm × 60 × (เม็ด/station/รอบ); เวลาจริง = เวลาทฤษฎี ÷ efficiency",
      d: "easy",
      ref: "Aulton's Pharmaceutics 6th ed. (Tablets and compaction); Lachman/Lieberman's The Theory and Practice of Industrial Pharmacy 4th ed.",
      c: [
        "Output ทฤษฎี = 36 × 50 × 60 = 108,000 เม็ด/h",
        "Output จริง = 108,000 × 0.80 = 86,400 เม็ด/h",
        "เวลา = 540,000 ÷ 86,400 = 6.25 h",
      ],
    },
    {
      t: "Full factorial run count with center points",
      p: "ทีมพัฒนาสูตรต้องการคัดกรองผลของ 5 process parameters ใน fluid bed granulation ด้วย 2-level full factorial design (ไม่ทำซ้ำ) และเพิ่ม center points อีก 3 runs เพื่อประเมิน curvature และ pure error จำนวน experimental runs ทั้งหมดเท่าใด",
      o: ["13 runs", "28 runs", "32 runs", "35 runs", "246 runs"],
      a: 3,
      r: "จำนวน run ของ full factorial = (จำนวนระดับ)^(จำนวน factor) = 2^5 = 32 runs บวก center points 3 runs = 35 runs\n\nCenter points ไม่เปลี่ยนการประมาณ main effects/interactions แต่ใช้ตรวจ curvature (ถ้ามี curvature มากควรขยายเป็น response surface design) และให้ค่า pure error สำหรับทดสอบนัยสำคัญ เมื่อ factor มากขึ้น full factorial โตแบบ exponential จึงมักใช้ fractional factorial (เช่น 2^(5−1) = 16 runs) สำหรับ screening",
      w: [
        "ใช้ 2 × 5 + 3 ซึ่งเป็นการคิดแบบเส้นตรง ไม่ใช่ factorial",
        "ใช้ 5² + 3 สลับฐานกับเลขชี้กำลัง",
        "เป็นจำนวน factorial runs ที่ยังไม่รวม center points",
        "ถูก — 2^5 + 3 = 32 + 3 = 35 runs",
        "ใช้ 3^5 + 3 ซึ่งเป็น 3-level factorial ไม่ตรงกับโจทย์",
      ],
      k: "Full factorial = L^k runs (+ center points); 2-level 5 factors = 32 runs",
      d: "easy",
      ref: "Montgomery, Design and Analysis of Experiments 9th ed., Ch.6; ICH Q8(R2) Appendix 2",
      c: ["Factorial runs = 2^5 = 32", "รวม center points = 32 + 3 = 35 runs"],
    },
    {
      t: "Salt-to-base batch quantity",
      p: "ยาเม็ด amlodipine 10 mg (คิดเป็น amlodipine base) ผลิตจาก amlodipine besylate (MW 567.1; MW base 408.9) วัตถุดิบ lot ที่ใช้มี assay 99.5% (as-is) ต้องชั่ง amlodipine besylate ประมาณกี่ kg สำหรับ batch 500,000 เม็ด",
      o: ["3.62 kg", "5.00 kg", "5.03 kg", "6.93 kg", "6.97 kg"],
      a: 4,
      r: "เมื่อ label claim ระบุเป็น base แต่ใช้รูปเกลือ ต้องคูณด้วย salt factor = MW salt / MW base = 567.1/408.9 = 1.387 → besylate ที่ต้องการ = 10 × 1.387 = 13.87 mg ต่อเม็ด (เกลือบริสุทธิ์)\n\nแก้ potency: 13.87/0.995 = 13.94 mg ต่อเม็ด × 500,000 เม็ด = 6.97 kg ขั้นตอนต้องทำทั้งสอง (salt factor และ potency) และระวังกลับเศษส่วน (MW base/MW salt) ซึ่งให้ปริมาณต่ำกว่าจริง ทำให้ยาเม็ดมี base เพียง ~52% ของ label claim",
      w: [
        "กลับ salt factor (คูณ 408.9/567.1) ทำให้ได้ base ไม่ถึง label claim",
        "คิดเป็น base 10 mg × 500,000 โดยไม่แปลงเป็นเกลือและไม่แก้ potency",
        "แก้เฉพาะ potency แต่ลืมแปลงเป็นรูปเกลือ",
        "แปลงเป็นรูปเกลือแล้วแต่ลืมแก้ potency 99.5%",
        "ถูก — 10 × (567.1/408.9) ÷ 0.995 = 13.94 mg/เม็ด × 500,000 = 6.97 kg",
      ],
      k: "ปริมาณเกลือ = dose (base) × MW salt/MW base ÷ potency × จำนวนหน่วย",
      d: "medium",
      ref: "Ansel's Pharmaceutical Calculations 15th ed.; FDA Guidance for Industry: Naming of Drug Products Containing Salt Drug Substances (2015)",
      c: [
        "Salt factor = 567.1 ÷ 408.9 = 1.387",
        "Besylate บริสุทธิ์/เม็ด = 10 × 1.387 = 13.87 mg",
        "แก้ potency = 13.87 ÷ 0.995 = 13.94 mg/เม็ด",
        "Batch = 13.94 mg × 500,000 = 6,969,000 mg ≈ 6.97 kg",
      ],
    },
    {
      t: "Dry-basis moisture to LOD conversion",
      p: "Halogen moisture analyzer ของห้องผลิตรายงาน granule moisture เป็น moisture content (dry basis) = 8.0% แต่ specification ใน batch record กำหนดเป็น LOD (wet basis) ค่าที่ต้องบันทึกเป็น LOD (wet basis) คือเท่าใด",
      o: ["7.36%", "7.41%", "8.00%", "8.64%", "8.70%"],
      a: 1,
      r: "LOD (wet basis) = น้ำ ÷ (น้ำ + ของแข็งแห้ง) × 100 ส่วน MC (dry basis) = น้ำ ÷ ของแข็งแห้ง × 100 สองค่านี้สัมพันธ์กันด้วย LOD = MC/(100 + MC) × 100 และ MC = LOD/(100 − LOD) × 100\n\nMC 8.0% หมายถึงน้ำ 8 g ต่อของแข็งแห้ง 100 g → LOD = 8/108 × 100 = 7.41% ความต่างนี้เล็กเมื่อความชื้นต่ำ แต่สำคัญเมื่อ spec แคบหรือความชื้นสูง (wet granules) ต้องระบุ basis ให้ชัดใน batch record และ method",
      w: [
        "นำ 8% × 0.92 ซึ่งไม่ใช่สูตรแปลง basis",
        "ถูก — LOD = 8.0/(100 + 8.0) × 100 = 7.41%",
        "ไม่ได้แปลง basis — dry basis ≠ wet basis",
        "นำ 8% × 1.08 เป็นการแปลงทิศทางที่ผิดและไม่ใช่สูตรที่ถูก",
        "ใช้ 8/(100 − 8) ซึ่งเป็นการแปลงจาก LOD → MC (ทิศตรงข้าม)",
      ],
      k: "LOD(wet) = MC/(100+MC)×100; MC(dry) = LOD/(100−LOD)×100; MC ≥ LOD เสมอ",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed. (Drying: moisture content definitions); USP <731> Loss on Drying",
      c: ["น้ำ 8.0 g ต่อของแข็งแห้ง 100 g → มวลรวม 108 g", "LOD = 8.0/108 × 100 = 7.41%"],
    },
    {
      t: "Target tablet weight from blend assay",
      p: "สูตรยาเม็ด 200 mg ออกแบบให้ API = 40.0% w/w ของ final blend (น้ำหนักเม็ดเป้าหมาย 500 mg) แต่ผล assay ของ final lubricated blend ที่ผ่าน blend uniformity แล้วได้ API 38.5% w/w (SOP อนุญาตให้ปรับ target weight ตาม blend assay) ควรตั้ง target tablet weight เท่าใด",
      o: ["192.5 mg", "481.3 mg", "500.0 mg", "507.5 mg", "519.5 mg"],
      a: 4,
      r: "Target weight = label claim ÷ สัดส่วน API ใน blend ที่วัดได้จริง = 200 ÷ 0.385 = 519.5 mg\n\nแนวทางนี้ใช้เมื่อ assay ของ blend ต่างจากทฤษฎี (เช่น LOD ของ granules ต่างจากที่ออกแบบ หรือ granule loss ไม่สม่ำเสมอ) โดยต้องอยู่ในช่วงที่ registration/batch record อนุญาต และ blend uniformity ต้องผ่าน การปรับน้ำหนักชดเชยได้เฉพาะ ‘ความเข้มข้นเฉลี่ย’ ไม่ได้แก้ปัญหา content uniformity หาก blend ไม่เป็นเนื้อเดียวกัน",
      w: [
        "เป็นปริมาณ API ในเม็ด 500 mg (500 × 0.385) ไม่ใช่น้ำหนักเม็ด",
        "ใช้อัตราส่วนกลับ (500 × 38.5/40.0) ทำให้เม็ดเบาลงและ API ยิ่งต่ำ",
        "ไม่ได้ปรับ ทำให้แต่ละเม็ดมี API เพียง 192.5 mg (96.25% LC)",
        "บวกส่วนต่าง 1.5 จุดเปอร์เซ็นต์ของน้ำหนักแบบเส้นตรง (500 × 1.015) ไม่ถูกต้อง",
        "ถูก — 200 ÷ 0.385 = 519.5 mg ให้ API 200 mg ต่อเม็ด",
      ],
      k: "Target weight = dose ÷ (fraction API ใน blend ที่ assay จริง); ชดเชยความเข้มข้นเฉลี่ยได้ แต่ไม่ชดเชย non-uniformity",
      d: "medium",
      ref: "Lachman/Lieberman's The Theory and Practice of Industrial Pharmacy 4th ed.; PIC/S GMP Guide PE 009 Part I Ch.4",
      c: ["Target weight = 200 mg ÷ 0.385 = 519.5 mg", "ตรวจสอบ: 519.5 × 0.385 = 200.0 mg API"],
    },
    {
      t: "X-bar chart control limits using A2",
      p: "จัดทำ X̄–R chart ของน้ำหนักยาเม็ดจาก 25 subgroups (subgroup size n = 5) ได้ grand mean = 400.0 mg และ average range (R̄) = 8.0 mg (สำหรับ n = 5: A2 = 0.577, d2 = 2.326, D4 = 2.114) control limits ของ X̄-chart (LCL–UCL) คือข้อใด",
      o: ["376.0–424.0 mg", "383.1–416.9 mg", "389.7–410.3 mg", "395.4–404.6 mg", "397.9–402.1 mg"],
      a: 3,
      r: "X̄-chart limits = X̿ ± A2·R̄ = 400.0 ± 0.577 × 8.0 = 400.0 ± 4.6 → 395.4–404.6 mg A2 รวม 3/(d2√n) ไว้แล้ว (3/(2.326 × √5) = 0.577)\n\nค่า 389.7–410.3 คือ ±3σ ของ ‘น้ำหนักเม็ดเดี่ยว’ (σ = R̄/d2 = 3.44 mg) ซึ่งกว้างกว่าเพราะยังไม่หารด้วย √n ส่วน D4·R̄ = 16.9 mg คือ UCL ของ R-chart ไม่ใช่ X̄-chart ควรตรวจ R-chart ว่า in control ก่อนเสมอ เพราะ X̄ limits อาศัย R̄",
      w: [
        "ใช้ ±3R̄ ซึ่งไม่ใช่สูตร control limit",
        "นำ D4·R̄ (UCL ของ R-chart = 16.9 mg) มาบวกลบกับ mean ผิดชนิด chart",
        "เป็น ±3σ ของค่า individual (σ = R̄/d2) ไม่ได้หาร √n สำหรับค่าเฉลี่ย subgroup",
        "ถูก — 400.0 ± 0.577 × 8.0 = 400.0 ± 4.6 mg",
        "หาร √n ซ้ำซ้อน (A2 รวม √n ไว้แล้ว) ทำให้ limits แคบเกินจริงและเกิด false alarm",
      ],
      k: "X̄-chart: X̿ ± A2R̄; R-chart: D3R̄ ถึง D4R̄; σ̂ = R̄/d2",
      d: "medium",
      ref: "Montgomery, Introduction to Statistical Quality Control 8th ed., Ch.6 (X̄ and R charts); ASTM E2587",
      c: ["A2·R̄ = 0.577 × 8.0 = 4.6 mg", "UCL = 400.0 + 4.6 = 404.6 mg", "LCL = 400.0 − 4.6 = 395.4 mg"],
    },
    {
      t: "AQL single sampling accept/reject decision",
      p: "การตรวจรับ blister ที่ packaging ใช้ ANSI/ASQ Z1.4 single sampling, normal inspection: lot 10,000 แผง, general inspection level II ได้ sample size n = 200 สำหรับ major defect AQL 1.0 มี Ac = 5, Re = 6 ผลตรวจพบ major defects 5 แผง ข้อใดถูกต้องที่สุด",
      o: [
        "ยอมรับ lot เพราะจำนวน defect (5) ไม่เกิน Ac = 5",
        "ปฏิเสธ lot เพราะสัดส่วน defect ในตัวอย่าง 2.5% สูงกว่า AQL 1.0%",
        "ต้องเปลี่ยนเป็น tightened inspection ทันทีและตรวจ lot นี้ใหม่",
        "ต้องตรวจ 100% ของ lot ก่อนตัดสิน เพราะผลเท่ากับ Ac พอดี",
        "ต้องสุ่มตัวอย่างชุดที่สองอีก 200 แผงเพื่อยืนยันผล",
      ],
      a: 0,
      r: "ใน single sampling plan การตัดสินใช้จำนวน defect ในตัวอย่างเทียบกับ Acceptance number (Ac) และ Rejection number (Re) เท่านั้น: d ≤ Ac → accept; d ≥ Re → reject ที่นี่ d = 5 = Ac จึงยอมรับ lot\n\nAQL ไม่ใช่เกณฑ์ที่นำ % defect ในตัวอย่างมาเทียบตรงๆ แต่เป็นระดับคุณภาพของ process average ที่แผนจะยอมรับด้วยความน่าจะเป็นสูง (~95%) ส่วน switching rules (normal → tightened) ใช้เมื่อมี 2 ใน 5 lots ติดกันถูกปฏิเสธ ไม่ได้ใช้จากผลครั้งเดียวที่ยังยอมรับได้ ทั้งนี้ defect ที่พบยังต้องบันทึกและแจ้ง supplier เพื่อ trend",
      w: [
        "ถูก — d = 5 ≤ Ac = 5 จึง accept ตามแผน single sampling",
        "เข้าใจผิดว่าต้องเทียบ % defect ในตัวอย่างกับ AQL โดยตรง",
        "Switching ไป tightened ใช้เมื่อ 2 ใน 5 lots ติดกันถูก reject ไม่ใช่กรณีนี้",
        "ไม่มีข้อกำหนดให้ตรวจ 100% เมื่อ d = Ac; แผนตัดสินชัดเจนแล้ว",
        "การสุ่มชุดที่สองเป็นลักษณะของ double sampling plan ไม่ใช่ single sampling",
      ],
      k: "Single sampling: d ≤ Ac ยอมรับ, d ≥ Re ปฏิเสธ; AQL ไม่ใช่ % defect ที่ใช้เทียบกับตัวอย่างโดยตรง",
      d: "medium",
      ref: "ANSI/ASQ Z1.4-2003 (R2018) Sampling Procedures and Tables for Inspection by Attributes; ISO 2859-1",
    },
    {
      t: "Sample size to estimate a mean within a margin of error",
      p: "ทีม validation ต้องการประมาณค่าเฉลี่ย assay ของ final blend ให้มี margin of error (ครึ่งความกว้างของ 95% CI) ไม่เกิน ±0.5% LC จากข้อมูลย้อนหลังทราบ σ ของกระบวนการ ≈ 1.2% LC (ใช้ z(0.975) = 1.96) ต้องสุ่มตัวอย่างอย่างน้อยกี่ตัวอย่าง",
      o: ["5 ตัวอย่าง", "6 ตัวอย่าง", "22 ตัวอย่าง", "23 ตัวอย่าง", "89 ตัวอย่าง"],
      a: 3,
      r: "Margin of error ของค่าเฉลี่ย E = z × σ/√n จัดรูปได้ n = (z × σ/E)² = (1.96 × 1.2/0.5)² = 4.704² = 22.13\n\nขนาดตัวอย่างต้องปัดขึ้นเสมอ (ceiling) เพราะถ้าปัดลงเป็น 22 ครึ่งความกว้างจะเกิน 0.5% เล็กน้อย จึงต้องใช้ 23 ตัวอย่าง\n\nจุดที่มักพลาด: (1) ลืมยกกำลังสอง (2) สับสนระหว่างความกว้างทั้งช่วง (1.0%) กับครึ่งความกว้าง (0.5%) (3) ปัดลง Pearl: n แปรผกผันกับ E² — ต้องการความแม่นยำเพิ่มสองเท่า (E ลดครึ่ง) ต้องใช้ตัวอย่างเพิ่มสี่เท่า หากไม่ทราบ σ และใช้ s จากตัวอย่างน้อย ควรใช้ค่า t แทน z ซึ่งจะได้ n มากขึ้นเล็กน้อย",
      w: [
        "ลืมยกกำลังสอง (1.96 × 1.2/0.5 = 4.70 แล้วปัดขึ้นเป็น 5)",
        "ใช้ความกว้างทั้งช่วง 1.0% เป็น E แทนครึ่งความกว้าง 0.5% → (1.96 × 1.2/1.0)² = 5.53 ≈ 6",
        "คำนวณถูกจนได้ 22.13 แต่ปัดลง ทำให้ margin of error เกิน ±0.5%",
        "ถูก — n = (1.96 × 1.2/0.5)² = 22.13 → ปัดขึ้นเป็น 23",
        "ใช้ E = 0.25% (หาร 0.5 ด้วย 2 ซ้ำ) → (1.96 × 1.2/0.25)² = 88.5 ≈ 89 มากเกินจำเป็น",
      ],
      k: "n = (z·σ/E)² แล้วปัดขึ้นเสมอ; E คือครึ่งความกว้างของ CI และ n ∝ 1/E²",
      d: "hard",
      ref: "Montgomery & Runger, Applied Statistics and Probability for Engineers (Ch. Statistical intervals — choice of sample size)",
      c: [
        "z × σ / E = 1.96 × 1.2 / 0.5 = 4.704",
        "n = 4.704² = 22.13",
        "ปัดขึ้น → n = 23 ตัวอย่าง",
      ],
    },
    {
      t: "95% confidence interval of mean (t-based)",
      p: "Process validation วัด assay ของยาเม็ดจาก 6 ตำแหน่งตลอด batch ได้ mean 99.4% LC และ sample SD 0.80% กำหนด t(0.975, df = 5) = 2.571, t(0.975, df = 6) = 2.447 และ z(0.975) = 1.96 95% confidence interval ของค่าเฉลี่ย batch คือข้อใด",
      o: ["97.34–101.46%", "98.48–100.32%", "98.56–100.24%", "98.60–100.20%", "98.76–100.04%"],
      a: 2,
      r: "เมื่อ n น้อยและไม่ทราบ σ ของประชากร ใช้ t-distribution ที่ df = n − 1: CI = x̄ ± t × SD/√n\n\nSE = 0.80/√6 = 0.327; ครึ่งความกว้าง = 2.571 × 0.327 = 0.84 → 98.56–100.24% การใช้ z (1.96) ให้ CI แคบเกินจริงเมื่อ n เล็ก การใช้ SD แทน SE ให้ช่วงที่เป็นการประมาณการกระจายของค่าเดี่ยว (คล้าย prediction) ไม่ใช่ CI ของค่าเฉลี่ย CI นี้บอกว่า mean ของ batch น่าจะอยู่ระหว่าง ~98.6–100.2% ด้วยความเชื่อมั่น 95%",
      w: [
        "ใช้ SD แทน standard error (ไม่หาร √n) ทำให้ช่วงกว้างเกินจริง",
        "หารด้วย √(n − 1) แทน √n ผิดสูตร SE",
        "ถูก — 99.4 ± 2.571 × 0.80/√6 = 99.4 ± 0.84",
        "ใช้ df = n (6) แทน n − 1 (5)",
        "ใช้ z = 1.96 ซึ่งไม่เหมาะเมื่อ n = 6 และไม่ทราบ σ",
      ],
      k: "CI ของ mean = x̄ ± t(α/2, n−1) × s/√n; n เล็กใช้ t ไม่ใช่ z",
      d: "hard",
      ref: "USP <1010> Analytical Data—Interpretation and Treatment; Bolton & Bon, Pharmaceutical Statistics 5th ed.",
      c: [
        "SE = 0.80 ÷ √6 = 0.80 ÷ 2.449 = 0.327",
        "Half-width = 2.571 × 0.327 = 0.84",
        "CI = 99.4 ± 0.84 = 98.56–100.24%",
      ],
    },
    {
      t: "Cp versus Cpk off-center diagnosis",
      p: "Content uniformity data (process in statistical control) มี specification 90.0–110.0% LC คำนวณได้ Cp = 1.67 แต่ Cpk = 0.83 ข้อใดสรุปลักษณะกระบวนการและแนวทางแก้ไขได้ถูกต้องที่สุด",
      o: [
        "σ ≈ 2.0% และ mean อยู่ห่าง spec limit ที่ใกล้ที่สุดเพียง ≈ 5.0% ควรแก้ที่ centering ของ mean มากกว่าลด variation",
        "σ ≈ 3.3% ต้องลด variation เป็นหลักเพราะทั้ง Cp และ Cpk บ่งชี้ spread กว้าง",
        "Process capable แล้วเพราะ Cp > 1.33 จึงไม่จำเป็นต้องแก้ไขใด",
        "Cpk ต่ำแปลว่ากระบวนการไม่ stable ต้องคำนวณ control limits ใหม่ก่อน",
        "Mean อยู่ตรงกลาง spec พอดี แต่ data ไม่เป็น normal distribution จึงได้ Cpk ต่ำ",
      ],
      a: 0,
      r: "Cp = (USL − LSL)/6σ → σ = 20/(6 × 1.67) ≈ 2.0% ส่วน Cpk = ระยะจาก mean ถึง spec ที่ใกล้ที่สุด ÷ 3σ → ระยะ = 0.83 × 3 × 2.0 ≈ 5.0% แปลว่า mean อยู่ที่ราว 95% หรือ 105% LC (off-center)\n\nเมื่อ Cp สูงแต่ Cpk ต่ำ ปัญหาหลักคือ centering (เช่น target weight ตั้งผิด, blend potency ต่ำ/สูง) การปรับ mean เข้ากลางจะยก Cpk ขึ้นใกล้ 1.67 ทันทีโดยไม่ต้องลด variation ที่ระยะ 2.5σ จาก spec คาดว่ามีหน่วยนอก spec ~0.6% ซึ่งยอมรับไม่ได้สำหรับ CQA",
      w: [
        "ถูก — Cp บอก spread แคบ (σ ≈ 2.0) แต่ Cpk ต่ำเพราะ mean เลื่อนไปใกล้ spec limit",
        "คำนวณ σ ผิด และ Cp ที่สูงบ่งชี้ว่า spread ไม่ได้กว้าง",
        "Cp ไม่คำนึงถึงตำแหน่ง mean ต้องดู Cpk ซึ่งยังต่ำกว่า 1.0",
        "โจทย์ระบุว่า in control แล้ว; Cpk ต่ำเป็นเรื่อง capability ไม่ใช่ stability",
        "ถ้า mean อยู่ตรงกลาง Cp จะเท่ากับ Cpk; ความต่างนี้บ่งชี้ off-center",
      ],
      k: "Cp สูง + Cpk ต่ำ = process แคบแต่ไม่อยู่กลาง → แก้ centering; Cp ต่ำ = spread กว้าง → ลด variation",
      d: "hard",
      ref: "Montgomery, Introduction to Statistical Quality Control 8th ed., Ch.8; ICH Q10 (process performance monitoring)",
      c: [
        "σ = (110 − 90)/(6 × 1.67) = 20/10.0 ≈ 2.0%",
        "ระยะ mean ถึง spec ที่ใกล้สุด = Cpk × 3σ = 0.83 × 6.0 ≈ 5.0%",
        "Mean ≈ 95.0% หรือ 105.0% LC (off-center)",
      ],
    },
  ],
  // Mock Set 3 — การคำนวณและสถิติในการผลิต
  [
    {
      t: "Theoretical tablet count from final blend weight",
      p: "Final blend หลังขั้น lubrication ชั่งได้ 186.0 kg target tablet weight 310 mg หากไม่คิดการสูญเสียใด ๆ จะตอกได้เม็ดยาตามทฤษฎีกี่เม็ด",
      o: ["6,000 เม็ด", "60,000 เม็ด", "600,000 เม็ด", "1,670,000 เม็ด", "6,000,000 เม็ด"],
      a: 2,
      r: "จำนวนเม็ดตามทฤษฎี = น้ำหนัก blend ÷ น้ำหนักเม็ดเป้าหมาย โดยต้องแปลงหน่วยให้ตรงกัน 186.0 kg = 186,000 g = 186,000,000 mg\n\n186,000,000 mg ÷ 310 mg/เม็ด = 600,000 เม็ด\n\nค่านี้ใช้เป็นตัวหารในการคำนวณ yield ของขั้นตอก และวางแผนวัสดุบรรจุ ข้อผิดพลาดที่พบบ่อยคือแปลง kg → mg ผิด (คลาดเคลื่อนเป็นเท่าของ 10) หรือหารกลับด้าน วิธีตรวจเร็ว: 1 kg ของเม็ด 310 mg ≈ 3,226 เม็ด × 186 ≈ 600,000",
      w: [
        "แปลงหน่วยผิด (เหมือนใช้ 1.86 kg) ทำให้ค่าน้อยไป 100 เท่า",
        "แปลงหน่วยผิดไปหนึ่งหลัก (เหมือนใช้ 18.6 kg) ทำให้ค่าน้อยไป 10 เท่า",
        "ถูก — 186,000,000 mg ÷ 310 mg = 600,000 เม็ด",
        "หารกลับด้าน (310 ÷ 186 × 10⁶) ไม่มีความหมายทางกายภาพ",
        "แปลง kg → mg เกินไปหนึ่งหลัก (×10⁷) ทำให้ค่ามากไป 10 เท่า",
      ],
      k: "จำนวนเม็ดตามทฤษฎี = น้ำหนัก blend (mg) ÷ น้ำหนักเม็ด (mg); 1 kg = 10⁶ mg",
      d: "easy",
      ref: "Lachman/Lieberman's The Theory and Practice of Industrial Pharmacy 4th ed. (Tablets); Ansel's Pharmaceutical Calculations",
      c: [
        "186.0 kg = 186,000,000 mg",
        "จำนวนเม็ด = 186,000,000 ÷ 310 = 600,000 เม็ด",
      ],
    },
    {
      t: "Paired t-test selection",
      p: "ห้องผลิตต้องการเปลี่ยนจากวิธี LOD แบบ oven มาใช้ halogen moisture analyzer สำหรับ IPC จึงแบ่ง granule 12 ตัวอย่าง (แต่ละตัวอย่างมาจากคนละช่วงเวลาการอบ) ออกเป็นสองส่วน วัดส่วนหนึ่งด้วย oven และอีกส่วนด้วย halogen analyzer สถิติใดเหมาะสมที่สุดในการทดสอบว่าสองวิธีให้ค่าเฉลี่ยต่างกันหรือไม่",
      o: [
        "Paired t-test ของผลต่างรายคู่ (df = 11)",
        "Two-sample (independent) t-test ระหว่างสองกลุ่ม (df = 22)",
        "F-test เปรียบเทียบ variance ของสองวิธี",
        "Chi-square test of independence",
        "One-sample t-test ของค่าจาก halogen analyzer เทียบกับ 0",
      ],
      a: 0,
      r: "เมื่อแต่ละตัวอย่างถูกวัดด้วยทั้งสองวิธี ข้อมูลเป็นคู่ (paired) ความแปรปรวนระหว่างตัวอย่าง (granule ที่ความชื้นต่างกันมาก) ถูกตัดออกด้วยการวิเคราะห์ ‘ผลต่างรายคู่’ d = oven − halogen แล้วทดสอบว่า mean ของ d ต่างจาก 0 หรือไม่ (df = n − 1 = 11)\n\nหากใช้ independent t-test ความแปรปรวนระหว่างตัวอย่างจะรวมเข้าใน error ทำให้ test ไวน้อยลงมาก (อาจมองไม่เห็น bias ที่มีอยู่จริง) F-test ใช้เปรียบเทียบ precision ไม่ใช่ค่าเฉลี่ย นอกจากนี้การเทียบวิธีควรกำหนด equivalence margin ที่มีความหมายทางปฏิบัติด้วย ไม่ใช่ดูเพียง p-value",
      w: [
        "ถูก — ข้อมูลเป็นคู่จากตัวอย่างเดียวกัน จึงวิเคราะห์ผลต่างรายคู่",
        "ละเลยการจับคู่ ทำให้ความแปรปรวนระหว่างตัวอย่างกลบผลต่างของวิธี",
        "F-test เปรียบเทียบ variance/precision ไม่ได้ตอบคำถามเรื่องค่าเฉลี่ย",
        "Chi-square ใช้กับข้อมูล categorical ไม่ใช่ข้อมูลต่อเนื่องเชิงปริมาณ",
        "การเทียบกับ 0 ไม่มีความหมาย ต้องทดสอบผลต่างระหว่างสองวิธี",
      ],
      k: "วัดตัวอย่างเดียวกันด้วย 2 วิธี/2 สภาวะ → paired t-test; กลุ่มอิสระ → two-sample t-test; เทียบ variance → F-test",
      d: "easy",
      ref: "Bolton & Bon, Pharmaceutical Statistics: Practical and Clinical Applications 5th ed., Ch.5",
    },
    {
      t: "Potency compensation with filler adjustment",
      p: "สูตรยาเม็ดต่อเม็ด: API 50.0 mg (คิดที่ 100%), lactose 145.0 mg และ magnesium stearate 5.0 mg (น้ำหนักเม็ด 200 mg) SOP กำหนดให้ปรับ API ตาม potency และลด lactose เพื่อคงน้ำหนักเม็ด หาก API lot นี้มี potency 96.0% (as-is) ต้องใช้ lactose กี่ kg สำหรับ batch 300,000 เม็ด",
      o: ["15.63 kg", "41.76 kg", "42.88 kg", "43.50 kg", "44.13 kg"],
      a: 2,
      r: "API ที่ต้องชั่งต่อเม็ด = 50.0/0.960 = 52.08 mg ส่วนเกิน 2.08 mg (ซึ่งคือ inert portion ของวัตถุดิบ) ต้องหักออกจาก filler เพื่อคงน้ำหนักเม็ด 200 mg: lactose = 145.0 − 2.08 = 142.92 mg/เม็ด\n\nทั้ง batch = 142.92 × 300,000 = 42.88 kg การ compensate ด้วย filler นี้ (‘quantity sufficient’ ด้วย diluent) เป็นแนวปฏิบัติที่ต้องระบุใน master formula และอยู่ในขอบเขตที่ registration อนุญาต ไม่ควรลด/เพิ่ม excipient ที่มีหน้าที่สำคัญ เช่น disintegrant หรือ lubricant",
      w: [
        "เป็นปริมาณ API ที่ต้องชั่ง (52.08 mg × 300,000) ไม่ใช่ lactose",
        "นำ potency ไปคูณกับ lactose ซึ่งไม่มีหลักการรองรับ",
        "ถูก — (145.0 − 2.08) mg × 300,000 = 42.88 kg",
        "ไม่ได้ compensate ทำให้น้ำหนักเม็ดเกิน 200 mg",
        "บวกส่วนเกินเข้า lactose แทนที่จะลบ ทำให้เม็ดหนักขึ้นอีก",
      ],
      k: "API เพิ่มเท่าไร (เพราะ potency ต่ำ) ให้ลด filler เท่านั้น เพื่อคงน้ำหนักเม็ด",
      d: "medium",
      ref: "Lachman/Lieberman's The Theory and Practice of Industrial Pharmacy 4th ed.; PIC/S GMP Guide PE 009 Part I Ch.4.14",
      c: [
        "API/เม็ด = 50.0 ÷ 0.960 = 52.08 mg",
        "ส่วนเกิน = 52.08 − 50.0 = 2.08 mg",
        "Lactose/เม็ด = 145.0 − 2.08 = 142.92 mg",
        "Lactose ทั้ง batch = 142.92 × 300,000 = 42,875,000 mg ≈ 42.88 kg",
      ],
    },
    {
      t: "Overall equipment effectiveness (OEE) calculation",
      p: "เครื่องบรรจุ blister ในกะ 8 ชั่วโมง (480 นาที) มีเวลาพักตามแผน 30 นาที จึงมี planned production time 450 นาที ระหว่างกะเครื่องหยุดโดยไม่ได้วางแผน (เปลี่ยน foil, jam) รวม 45 นาที ideal rate ของเครื่อง 300 blisters/นาที ผลิตได้ทั้งหมด 109,350 blisters ในจำนวนนี้ผ่านเกณฑ์คุณภาพ 98% ค่า OEE ของกะนี้เท่าใด",
      o: ["74.4%", "79.4%", "81.0%", "88.2%", "90.0%"],
      a: 1,
      r: "OEE = Availability × Performance × Quality\n\nAvailability = run time/planned production time = (450 − 45)/450 = 405/450 = 0.90 (ฐานคือ planned production time ซึ่งหักเวลาพักตามแผนออกแล้ว) Performance = actual output/(run time × ideal rate) = 109,350/(405 × 300) = 109,350/121,500 = 0.90 Quality = good units/total units = 0.98\n\nOEE = 0.90 × 0.90 × 0.98 = 0.794 = 79.4% การแยกองค์ประกอบช่วยชี้ว่าความสูญเสียมาจากเครื่องหยุด (availability), เดินช้ากว่า ideal (performance) หรือของเสีย (quality) ซึ่งใช้วางแผนปรับปรุงได้ตรงจุด",
      w: [
        "ใช้ 480 นาทีเป็นฐาน availability (405/480 = 0.844) ทั้งที่เวลาพักตามแผนไม่ควรนับเป็นความสูญเสีย",
        "ถูก — 0.90 × 0.90 × 0.98 = 0.794 = 79.4%",
        "คิดแค่ Availability × Performance ไม่ได้คูณ Quality",
        "คิดแค่ Performance × Quality ไม่ได้รวมความสูญเสียจากเครื่องหยุด",
        "90.0% เป็นเพียง Availability (หรือ Performance) ตัวเดียว ไม่ใช่ OEE",
      ],
      k: "OEE = Availability × Performance × Quality; availability ใช้ planned production time เป็นฐาน",
      d: "medium",
      ref: "Nakajima S., Introduction to TPM: Total Productive Maintenance (OEE); ISPE Good Practice Guide: Operations Management",
      c: [
        "Run time = 450 − 45 = 405 นาที → Availability = 405/450 = 0.90",
        "Ideal output = 405 × 300 = 121,500 → Performance = 109,350/121,500 = 0.90",
        "Quality = 0.98 (good = 107,163 blisters)",
        "OEE = 0.90 × 0.90 × 0.98 = 0.794 = 79.4%",
      ],
    },
    {
      t: "Ethanol dilution for granulating solvent",
      p: "ต้องเตรียม ethanol 70% v/v จำนวน 200 L เป็น granulating solvent จาก ethanol 95% v/v และ purified water วิธีเตรียมใดถูกต้องที่สุด",
      o: [
        "52.6 L ethanol 95% แล้วเติมน้ำ q.s. ถึง 200 L",
        "140.0 L ethanol 95% แล้วเติมน้ำ q.s. ถึง 200 L",
        "147.4 L ethanol 95% แล้วเติมน้ำ q.s. ถึง 200 L",
        "147.4 L ethanol 95% ผสมกับน้ำ 52.6 L พอดี",
        "271.4 L ethanol 95% แล้วเติมน้ำ q.s. ถึง 200 L",
      ],
      a: 2,
      r: "ใช้ C1V1 = C2V2: V1 = 70 × 200/95 = 147.4 L ของ ethanol 95% แล้วปรับปริมาตรด้วยน้ำ q.s. ถึง 200 L\n\nไม่ควรผสมน้ำ 52.6 L ตรงๆ เพราะ ethanol–water เกิด volume contraction (ปริมาตรรวมน้อยกว่าผลบวก) จะได้ปริมาตรไม่ถึง 200 L และความเข้มข้น v/v ผิด ในการผลิตจริงอาจเตรียมเป็น w/w โดยใช้ตาราง alcoholometric เพื่อความแม่นยำ เพราะชั่งน้ำหนักแม่นกว่าการตวงปริมาตรในถังใหญ่",
      w: [
        "สลับปริมาณ ethanol กับน้ำ ได้ความเข้มข้นเพียง ~25% v/v",
        "คิดเป็น ethanol บริสุทธิ์ (200 × 0.70) ลืมว่าวัตถุดิบเป็น 95%",
        "ถูก — V1 = 70 × 200/95 = 147.4 L แล้ว q.s. ด้วยน้ำ",
        "ปริมาณ ethanol ถูกแต่การผสมน้ำตามปริมาตรตรงๆ ไม่ได้ 200 L เพราะ volume contraction",
        "กลับสัดส่วน (200 × 95/70) ได้ปริมาตร ethanol มากกว่าปริมาตรสุดท้าย",
      ],
      k: "C1V1 = C2V2 แล้ว q.s. ด้วยน้ำ; ethanol–water มี volume contraction จึงห้ามบวกปริมาตรตรงๆ",
      d: "medium",
      ref: "Ansel's Pharmaceutical Calculations 15th ed. (Dilution and concentration); USP Alcohol monograph/alcoholometric tables",
      c: ["V1 = C2V2/C1 = 70 × 200 ÷ 95 = 147.4 L", "เติมน้ำ q.s. ถึง 200 L (ไม่ใช่บวก 52.6 L ตรงๆ)"],
    },
    {
      t: "Impeller tip speed scale-up",
      p: "High-shear granulator ระดับ pilot มี impeller diameter 0.25 m ใช้ impeller speed 300 rpm เมื่อขยายไปเครื่อง production ที่ impeller diameter 0.75 m (geometrically similar) หากใช้หลัก ‘คง impeller tip speed’ ควรตั้ง impeller speed ประมาณเท่าใด",
      o: ["33 rpm", "100 rpm", "173 rpm", "300 rpm", "900 rpm"],
      a: 1,
      r: "Tip speed = π × D × N (/60 เพื่อแปลงเป็น m/s) ที่ pilot = π × 0.25 × 300/60 = 3.93 m/s การคง tip speed ต้องให้ D1N1 = D2N2 → N2 = 300 × 0.25/0.75 = 100 rpm\n\nTip speed สัมพันธ์กับ shear/impact ที่ปลายใบพัดจึงเป็นกฎ scale-up ที่ใช้บ่อย แต่ไม่ได้คงทุกอย่าง (เช่น Froude number หรือ swept volume) จึงมักต้องปรับ granulation time/endpoint ด้วย power consumption หรือ torque ร่วมด้วย ค่า 173 rpm คือผลจากการคง Froude number (N ∝ D^−0.5)",
      w: [
        "ใช้อัตราส่วน D² (N ∝ 1/D²) ไม่ใช่กฎ tip speed",
        "ถูก — N2 = 300 × (0.25/0.75) = 100 rpm คง tip speed ≈ 3.93 m/s",
        "เป็นผลของการคง Froude number (N ∝ 1/√D) ไม่ใช่ tip speed",
        "คง rpm เดิมทำให้ tip speed เพิ่ม 3 เท่า (11.8 m/s) เสี่ยง over-granulation",
        "คูณแทนการหาร ทำให้ tip speed เพิ่ม 9 เท่า",
      ],
      k: "คง tip speed: N2 = N1 × D1/D2; คง Froude: N2 = N1 × √(D1/D2)",
      d: "medium",
      ref: "Levin (ed.), Pharmaceutical Process Scale-Up 3rd ed.; Aulton's Pharmaceutics 6th ed. (Granulation)",
      c: [
        "Tip speed pilot = π × 0.25 × 300 ÷ 60 = 3.93 m/s",
        "D1N1 = D2N2 → N2 = 300 × 0.25 ÷ 0.75 = 100 rpm",
      ],
    },
    {
      t: "Alternating pattern (Nelson rule) on press",
      p: "Individual chart ของน้ำหนักเม็ดจาก double-sided rotary press เก็บตัวอย่างสลับกันระหว่าง discharge chute ด้าน A และ B ตามลำดับเวลา พบว่า 16 จุดติดกันขึ้น-ลงสลับกันอย่างสม่ำเสมอ (สูง-ต่ำ-สูง-ต่ำ) ไม่มีจุดใดเกิน control limits ข้อใดเป็นการตีความและการดำเนินการที่เหมาะสมที่สุด",
      o: [
        "เป็น non-random pattern (≥ 14 จุดสลับขึ้นลง) บ่งชี้ systematic difference ระหว่างสองด้านของเครื่อง ควรแยก chart/ตรวจ fill-cam และ weight control ของแต่ละด้าน",
        "เป็น random variation ปกติเพราะไม่มีจุดเกิน control limits และ pattern ขึ้นลงคือธรรมชาติของข้อมูล",
        "เป็นสัญญาณ trend ขาขึ้นจากการสึกหรอของ punch ต้องเปลี่ยน tooling ทั้งชุด",
        "เป็นผลจาก control limits ที่กว้างเกิน จึงควรลด limits ลงให้แคบเป็น ±2σ",
        "บ่งชี้ว่า process mean shift ทั้งระบบ ต้องปรับ target weight ของทั้งสองด้านพร้อมกัน",
      ],
      a: 0,
      r: "Nelson rule 4 (14 จุดติดกันสลับขึ้น-ลง) บ่งชี้ systematic effect จากสองแหล่งที่ถูกสลับกันเข้ามาในข้อมูล (stratification/mixture) เช่น สองด้านของ double-sided press, สองหัวบรรจุ หรือ operator สองคนที่ปรับเครื่องสลับกัน (over-control)\n\nการรวมข้อมูลสองแหล่งใน chart เดียวทำให้ทั้ง centering และ variation ของแต่ละด้านถูกบดบัง แนวทางคือแยก chart ตามแหล่ง (rational subgrouping) และหาสาเหตุ เช่น fill depth, feeder หรือ pressure roll ของแต่ละด้านต่างกัน",
      w: [
        "ถูก — pattern สลับขึ้นลงต่อเนื่องเป็น special cause จากสองแหล่ง ควรแยก chart และสอบสวนแต่ละด้าน",
        "Pattern ที่สม่ำเสมอขนาดนี้ไม่ใช่การสุ่ม แม้ทุกจุดจะอยู่ใน limits",
        "Trend ต้องเป็นจุดเพิ่ม/ลดต่อเนื่อง (≥ 6 จุด) ไม่ใช่สลับขึ้นลง",
        "การบีบ limits ไม่แก้สาเหตุ และทำให้ false alarm เพิ่ม",
        "Pattern นี้บ่งชี้ความต่างระหว่างสองด้าน ไม่ใช่ mean ของทั้งระบบเลื่อน",
      ],
      k: "สลับขึ้นลง ≥ 14 จุด = สองแหล่งผสมกัน (stratification/over-adjustment) → แยก rational subgroup",
      d: "medium",
      ref: "Nelson LS. The Shewhart control chart—tests for special causes. J Qual Technol 1984;16:237–239; Montgomery SQC 8th ed., Ch.6",
    },
    {
      t: "2x2 factorial interaction effect",
      p: "ศึกษา 2² factorial ต่อความแข็งของเม็ด (kP): Factor A = compression force (ต่ำ/สูง), Factor B = lubricant blending time กับ magnesium stearate (สั้น/ยาว) ผล: A−B− = 8, A+B− = 14, A−B+ = 6, A+B+ = 8 kP ค่า interaction effect AB เท่าใด",
      o: ["−4.0 kP", "−2.0 kP", "+2.0 kP", "+4.0 kP", "+11.0 kP"],
      a: 1,
      r: "Interaction AB = ½ × [effect ของ A ที่ B สูง − effect ของ A ที่ B ต่ำ] = ½ × [(8 − 6) − (14 − 8)] = ½ × (2 − 6) = −2.0 kP (เท่ากับ [(1) + ab − a − b]/2 = (8 + 8 − 14 − 6)/2)\n\nความหมาย: เมื่อ blend นาน (over-lubrication) การเพิ่มแรงตอกเพิ่มความแข็งได้น้อยลง (จาก +6 เหลือ +2 kP) เพราะฟิล์ม magnesium stearate ลด bonding ระหว่างอนุภาค เมื่อมี interaction ต้องตีความ main effect ร่วมกับระดับของอีก factor เสมอ",
      w: [
        "เป็นผลต่างของ effect ของ A ที่สองระดับ B โดยไม่หาร 2 (2 − 6)",
        "ถูก — ½[(8 − 6) − (14 − 8)] = −2.0 kP",
        "ผิดเครื่องหมาย; การ blend นานลดผลของ compression force",
        "เป็น main effect ของ A ((14 + 8)/2 − (8 + 6)/2)",
        "เป็นค่าเฉลี่ยของ response ที่ A สูง ไม่ใช่ effect",
      ],
      k: "AB = ½[(effect A ที่ B+) − (effect A ที่ B−)]; interaction ≠ 0 → อย่าตีความ main effect แยกเดี่ยว",
      d: "hard",
      ref: "Montgomery, Design and Analysis of Experiments 9th ed., Ch.6; ICH Q8(R2) Appendix 2",
      c: [
        "Effect A ที่ B− = 14 − 8 = 6 kP",
        "Effect A ที่ B+ = 8 − 6 = 2 kP",
        "AB = (2 − 6) ÷ 2 = −2.0 kP",
      ],
    },
    {
      t: "Expected out-of-spec fraction from normal distribution",
      p: "Capsule fill weight จาก process ที่ stable และเป็น normal distribution มี mean 302 mg และ SD 4 mg specification 290–310 mg กำหนดให้ P(Z > 2.0) = 0.0228 และ P(Z < −3.0) = 0.00135 สัดส่วนแคปซูลที่คาดว่าจะอยู่นอก specification รวมทั้งสองด้านใกล้เคียงข้อใด",
      o: ["0.13%", "0.27%", "2.28%", "2.41%", "4.55%"],
      a: 3,
      r: "คำนวณ z ของแต่ละ spec: z(USL) = (310 − 302)/4 = 2.0 → สัดส่วนเกิน USL = 2.28%; z(LSL) = (290 − 302)/4 = −3.0 → สัดส่วนต่ำกว่า LSL = 0.135%\n\nรวม ≈ 2.41% ซึ่งเกือบทั้งหมดมาจากด้านบนเพราะ mean เลื่อนจากกลาง spec (300 mg) ไป 2 mg การ re-center mean ที่ 300 mg จะทำให้ z = ±2.5 ทั้งสองด้าน ลด out-of-spec เหลือ ~1.24% ตัวอย่างนี้แสดงว่าการ centering มีผลมากต่อ % defect แม้ SD เท่าเดิม",
      w: [
        "คิดเฉพาะด้านล่าง (z = −3)",
        "เป็นสัดส่วนนอก ±3σ ทั้งสองด้านของ process ที่อยู่กลาง ไม่ตรงกับสถานการณ์",
        "คิดเฉพาะด้านบน (z = 2) ลืมด้านล่าง",
        "ถูก — 2.28% + 0.135% ≈ 2.41%",
        "เป็นสัดส่วนนอก ±2σ ทั้งสองด้าน สมมติผิดว่า spec สมมาตรรอบ mean",
      ],
      k: "%OOS = P(Z > (USL−μ)/σ) + P(Z < (LSL−μ)/σ); mean off-center เพิ่ม OOS ด้านใกล้อย่างมาก",
      d: "hard",
      ref: "Montgomery, Introduction to Statistical Quality Control 8th ed., Ch.3 & Ch.8",
      c: [
        "z(USL) = (310 − 302)/4 = 2.0 → 2.28%",
        "z(LSL) = (290 − 302)/4 = −3.0 → 0.135%",
        "รวม = 2.28 + 0.135 ≈ 2.41%",
      ],
    },
    {
      t: "Extragranular excipient adjustment to granule yield",
      p: "Master formula คิด extragranular excipients จาก dried milled granules ทางทฤษฎี 180.0 kg ได้แก่ croscarmellose sodium 6.0 kg และ magnesium stearate 1.8 kg หลังอบและบดได้ granules จริง 171.0 kg (ผ่าน LOD และ assay) ตาม SOP ให้ปรับ extragranular ตามสัดส่วน granules ที่ได้จริง ต้องใช้ magnesium stearate กี่ kg",
      o: ["0.09 kg", "1.62 kg", "1.71 kg", "1.80 kg", "1.89 kg"],
      a: 2,
      r: "สัดส่วน extragranular ต่อ granules ต้องคงที่เพื่อรักษาองค์ประกอบของ final blend (เช่น lubricant ~1% ของ granules) Factor = 171.0/180.0 = 0.95 → magnesium stearate = 1.8 × 0.95 = 1.71 kg (และ croscarmellose = 5.70 kg)\n\nถ้าใช้ 1.8 kg เต็ม จะได้ lubricant สูงเกินสัดส่วน ~5% ซึ่งอาจลด hardness และทำให้ dissolution ช้าลง (over-lubrication) จากนั้น target tablet weight ยังคงเดิม แต่จำนวนเม็ดที่ได้ลดลงตาม granule yield การปรับนี้ต้องเขียนไว้ใน master batch record และทำ double-check การคำนวณ",
      w: [
        "เป็นปริมาณที่ต้องลดออก (1.8 × 0.05) ไม่ใช่ปริมาณที่ต้องใช้",
        "ปรับซ้ำสองครั้ง (1.8 × 0.95 × 0.95)",
        "ถูก — 1.8 × (171.0/180.0) = 1.71 kg",
        "ไม่ได้ปรับตาม yield ทำให้ lubricant เกินสัดส่วน",
        "กลับอัตราส่วน (1.8 × 180/171) ทำให้ยิ่งเกินสัดส่วน",
      ],
      k: "Extragranular ปรับตาม factor = granules ที่ได้จริง ÷ granules ทฤษฎี เพื่อคงสัดส่วนสูตร",
      d: "hard",
      ref: "Lachman/Lieberman's The Theory and Practice of Industrial Pharmacy 4th ed.; PIC/S GMP Guide PE 009 Part I Ch.4",
      c: [
        "Factor = 171.0 ÷ 180.0 = 0.95",
        "Magnesium stearate = 1.8 × 0.95 = 1.71 kg",
        "(ตรวจ) Croscarmellose = 6.0 × 0.95 = 5.70 kg",
      ],
    },
  ],
  // Mock Set 4 — การคำนวณและสถิติในการผลิต
  [
    {
      t: "Alligation of binder solutions",
      p: "ห้องผลิตมี PVP binder solution เหลือจาก batch ก่อน 2 ชนิด คือ 12% w/w และ 4% w/w (ผ่านการตรวจ hold time แล้ว) ต้องการเตรียม binder solution 6% w/w จำนวน 40 kg โดยผสมสองชนิดนี้ ต้องใช้แต่ละชนิดกี่ kg",
      o: [
        "10 kg ของ 12% + 30 kg ของ 4%",
        "13.3 kg ของ 12% + 26.7 kg ของ 4%",
        "20 kg ของ 12% + 20 kg ของ 4%",
        "26.7 kg ของ 12% + 13.3 kg ของ 4%",
        "30 kg ของ 12% + 10 kg ของ 4%",
      ],
      a: 0,
      r: "Alligation alternate: ส่วนของสารละลายเข้มข้น = (เป้าหมาย − เจือจาง) = 6 − 4 = 2 ส่วน; ส่วนของสารละลายเจือจาง = (เข้มข้น − เป้าหมาย) = 12 − 6 = 6 ส่วน → อัตราส่วน 2 : 6 = 1 : 3\n\nรวม 4 ส่วน = 40 kg → 12% ใช้ 10 kg และ 4% ใช้ 30 kg ตรวจ: (10 × 12 + 30 × 4)/40 = 240/40 = 6% เนื่องจากเป็น % w/w การผสมโดยน้ำหนักจึงบวกกันได้ตรงๆ (ต่างจาก % v/v ของ ethanol–water ที่มี volume contraction)",
      w: [
        "ถูก — อัตราส่วน 12% : 4% = (6−4) : (12−6) = 1 : 3 → 10 kg + 30 kg",
        "ใช้อัตราส่วน 1 : 2 ไม่ตรงกับ alligation ให้ความเข้มข้น ≈ 6.7%",
        "ผสมเท่ากันได้ค่าเฉลี่ย 8% ไม่ใช่ 6%",
        "สลับอัตราส่วน 2 : 1 ได้ความเข้มข้น ≈ 9.3%",
        "สลับส่วนของสองสารละลาย ได้ความเข้มข้น 10%",
      ],
      k: "Alligation: ส่วนของสารเข้มข้น = |เป้า − เจือจาง|, ส่วนของสารเจือจาง = |เข้มข้น − เป้า|",
      d: "easy",
      ref: "Ansel's Pharmaceutical Calculations 15th ed. (Alligation)",
      c: [
        "ส่วน 12% = 6 − 4 = 2; ส่วน 4% = 12 − 6 = 6 → 1 : 3",
        "12% = 40 × 1/4 = 10 kg; 4% = 40 × 3/4 = 30 kg",
        "ตรวจ: (10×12 + 30×4)/40 = 6% w/w",
      ],
    },
    {
      t: "Producer's versus consumer's risk",
      p: "ในการออกแบบ acceptance sampling plan สำหรับตรวจรับวัสดุบรรจุ ข้อใดนิยาม consumer's risk (β) ได้ถูกต้องที่สุด",
      o: [
        "ความน่าจะเป็นที่จะยอมรับ lot ที่มีคุณภาพแย่ถึงระดับ LTPD/limiting quality",
        "ความน่าจะเป็นที่จะปฏิเสธ lot ที่มีคุณภาพดีถึงระดับ AQL",
        "สัดส่วน defect สูงสุดที่ยอมรับได้ใน process average ของ supplier",
        "ความน่าจะเป็นที่ผู้ตรวจจะนับ defect ผิดพลาดระหว่างการตรวจ",
        "ค่าเฉลี่ยคุณภาพที่ออกไปถึงผู้ใช้หลังจาก rectifying inspection",
      ],
      a: 0,
      r: "Sampling plan มีความเสี่ยงสองด้าน: producer's risk (α) = โอกาสที่ lot ดี (ที่ระดับ AQL) ถูกปฏิเสธ (มักออกแบบให้ ~5%) และ consumer's risk (β) = โอกาสที่ lot แย่ (ที่ระดับ LTPD/LQ) ถูกยอมรับ (มักกำหนด ~10%)\n\nทั้งสองจุดอ่านได้จาก operating characteristic (OC) curve การเพิ่ม sample size ทำให้ OC curve ชันขึ้น ลดทั้ง α และ β พร้อมกัน สำหรับผู้ใช้ยา β สำคัญกว่าเพราะหมายถึง defect หลุดไปถึงผลิตภัณฑ์",
      w: [
        "ถูก — β คือโอกาสยอมรับ lot คุณภาพแย่ (ที่ LTPD/LQ) ซึ่งเป็นความเสี่ยงของผู้รับ",
        "เป็นนิยามของ producer's risk (α)",
        "เป็นความหมายของ AQL ไม่ใช่ความเสี่ยง β",
        "เป็น inspection error ไม่ใช่ sampling risk ของแผน",
        "เป็นนิยามของ average outgoing quality (AOQ)",
      ],
      k: "α = producer's risk (reject lot ดีที่ AQL); β = consumer's risk (accept lot แย่ที่ LTPD/LQ)",
      d: "easy",
      ref: "ANSI/ASQ Z1.4-2003 (R2018); Montgomery, Introduction to Statistical Quality Control 8th ed., Ch.15",
    },
    {
      t: "Granulating liquid addition rate scale-up",
      p: "Pilot batch: dry powder 30 kg เติมน้ำ 7.5 kg (25% w/w ของ dry mass) ด้วยปั๊มในเวลา 5 นาที เมื่อขยายเป็น 240 kg ใน high-shear granulator ที่ geometrically similar หากคงสัดส่วนน้ำต่อ dry mass และคงเวลาเติมน้ำ 5 นาที ต้องตั้งอัตราการเติมน้ำกี่ kg/min",
      o: ["1.5 kg/min", "4.2 kg/min", "7.5 kg/min", "12.0 kg/min", "60.0 kg/min"],
      a: 3,
      r: "น้ำทั้งหมด = 240 × 0.25 = 60 kg เพื่อคงเวลาเติม 5 นาที อัตรา = 60/5 = 12.0 kg/min (= อัตรา pilot × scale factor 8)\n\nเหตุผลที่คง addition time คือให้ระยะเวลาการกระจายของเหลวและการ nucleation ใกล้เดิม อย่างไรก็ตาม การกระจายน้ำยังขึ้นกับ spray nozzle/droplet size และ powder flux ใต้หัวพ่น (dimensionless spray flux) จึงต้องยืนยัน endpoint ด้วย power/torque หรือ granule properties ไม่ใช่เวลาอย่างเดียว",
      w: [
        "ใช้อัตราเดิมของ pilot ทำให้เวลาเติมยาวเป็น 40 นาที",
        "Scale ตาม √8 ซึ่งไม่มีพื้นฐานจากเงื่อนไขที่โจทย์กำหนด",
        "เป็นปริมาณน้ำทั้งหมดของ pilot ไม่ใช่อัตราของ production",
        "ถูก — 240 × 0.25 = 60 kg; 60 ÷ 5 min = 12.0 kg/min",
        "เป็นปริมาณน้ำทั้งหมดของ production ไม่ใช่อัตราต่อนาที",
      ],
      k: "คงสัดส่วนของเหลว/ของแข็ง และ addition time → อัตราเติม scale ตามขนาด batch",
      d: "medium",
      ref: "Levin (ed.), Pharmaceutical Process Scale-Up 3rd ed. (High-shear granulation); Aulton's Pharmaceutics 6th ed.",
      c: ["น้ำ production = 240 × 0.25 = 60 kg", "อัตรา = 60 kg ÷ 5 min = 12.0 kg/min"],
    },
    {
      t: "Coating weight gain endpoint timing",
      p: "ระหว่าง film coating ชั่ง cores 100 เม็ดก่อนเคลือบได้ 40.00 g หลังพ่น 90 นาที สุ่ม 100 เม็ดชั่งได้ 41.40 g เป้าหมาย weight gain 4.0% (คิดจากน้ำหนัก core) สมมติอัตราการเกาะของฟิล์มคงที่ ข้อใดถูกต้อง",
      o: [
        "1.4% — ต้องพ่นต่ออีกประมาณ 167 นาที",
        "3.4% — ต้องพ่นต่ออีกประมาณ 16.5 นาที",
        "3.5% — ต้องพ่นต่ออีกประมาณ 11.3 นาที",
        "3.5% — ต้องพ่นต่ออีกประมาณ 12.9 นาที",
        "3.5% — ต้องพ่นต่ออีกประมาณ 102.9 นาที",
      ],
      a: 3,
      r: "Weight gain = (น้ำหนักหลังเคลือบ − core) ÷ core × 100 = (41.40 − 40.00)/40.00 × 100 = 3.5% ใน 90 นาที → อัตรา 3.5/90 = 0.0389%/นาที\n\nเหลืออีก 0.5% → 0.5/0.0389 = 12.9 นาที การชั่งเม็ดเป็นวิธีหลักในการกำหนด coating endpoint (ควรใช้น้ำหนักเฉลี่ยจากจำนวนเม็ดมากพอและคิดเทียบ core ที่ LOD ใกล้เคียงกัน เพราะความชื้นที่ core ดูด/สูญเสียทำให้ weight gain คลาดได้)",
      w: [
        "นำส่วนต่างกรัม (1.40 g) มาใช้เป็นเปอร์เซ็นต์โดยตรง",
        "คิด weight gain บนน้ำหนักหลังเคลือบ (1.40/41.40) ซึ่งผิด basis",
        "ใช้ 90 × 0.5/4.0 ซึ่งผิดตัวหาร (ต้องใช้ 3.5% ที่ทำได้ใน 90 นาที)",
        "ถูก — WG = 1.40/40.00 = 3.5%; เวลาเพิ่ม = 0.5 ÷ (3.5/90) = 12.9 นาที",
        "เป็นเวลารวมทั้งหมด (90 × 4.0/3.5) ไม่ใช่เวลาที่ต้องพ่นเพิ่ม",
      ],
      k: "%WG = (coated − core)/core × 100; เวลาพ่นเพิ่ม = WG ที่ขาด ÷ อัตรา WG ต่อนาที",
      d: "medium",
      ref: "Porter, Pharmaceutical Coating Technology; Aulton's Pharmaceutics 6th ed. (Film coating)",
      c: [
        "WG = (41.40 − 40.00)/40.00 × 100 = 3.5%",
        "อัตรา = 3.5% ÷ 90 min = 0.0389 %/min",
        "เวลาเพิ่ม = (4.0 − 3.5) ÷ 0.0389 = 12.9 min",
      ],
    },
    {
      t: "I-MR chart control limits",
      p: "จัดทำ Individuals–Moving Range (I-MR) chart ของ assay ของยาเม็ดรายbatch (1 ค่าต่อ batch) จาก 25 batches ได้ค่าเฉลี่ย 99.8% LC และ average moving range (MR̄, span 2) = 0.9% (สำหรับ n = 2: d2 = 1.128, D4 = 3.267) control limits ของ Individuals chart คือข้อใด",
      o: ["96.75–102.85%", "96.86–102.74%", "97.10–102.50%", "97.41–102.19%", "98.04–101.56%"],
      a: 3,
      r: "I-chart limits = x̄ ± 3 × MR̄/d2 = x̄ ± 2.66 × MR̄ = 99.8 ± 2.66 × 0.9 = 99.8 ± 2.39 → 97.41–102.19%\n\nI-MR chart ใช้เมื่อ subgroup ตามธรรมชาติมีขนาด 1 (เช่น ค่าต่อ batch ใน continued process verification) σ ประมาณจาก MR̄/d2 (short-term variation) ส่วน MR-chart มี UCL = D4 × MR̄ = 2.94% control limits เหล่านี้ไม่ใช่ specification และไม่ควรใช้ SD รวมของข้อมูลทั้งหมดถ้ามี shift เพราะจะทำให้ limits กว้างเกิน",
      w: [
        "คูณ MR̄ ด้วย d2 แทนการหาร (3 × 0.9 × 1.128)",
        "ใช้ D4 × MR̄ (UCL ของ MR-chart) มาบวกลบ mean ผิด chart",
        "ใช้ ±3 × MR̄ โดยไม่หาร d2",
        "ถูก — 99.8 ± 2.66 × 0.9 = 99.8 ± 2.39",
        "ใช้ ±1.96 × MR̄ ซึ่งไม่ใช่สูตร control limit",
      ],
      k: "I-chart: x̄ ± 2.66·MR̄ (= 3·MR̄/1.128); MR-chart UCL = 3.267·MR̄",
      d: "medium",
      ref: "Montgomery, Introduction to Statistical Quality Control 8th ed., Ch.6.4; ICH Q10 / FDA Process Validation Guidance (2011) Stage 3",
      c: ["σ̂ = MR̄/d2 = 0.9/1.128 = 0.798", "3σ̂ = 2.39 (= 2.66 × 0.9)", "Limits = 99.8 ± 2.39 = 97.41–102.19%"],
    },
    {
      t: "F-test comparing two blender variances",
      p: "เปรียบเทียบความสม่ำเสมอของ blend จาก blender A และ B (ตัวอย่างละ 10 ตำแหน่ง) ได้ SD ของ assay: A = 2.4%, B = 1.5% ต้องการทดสอบว่า variance ต่างกันหรือไม่ (two-sided, α = 0.05; F critical (9, 9) = 4.03) ข้อสรุปใดถูกต้อง",
      o: [
        "F = 2.56 ซึ่งน้อยกว่า 4.03 จึงยังไม่มีหลักฐานว่า variance ของสอง blender ต่างกันอย่างมีนัยสำคัญ",
        "F = 1.60 ซึ่งน้อยกว่า 4.03 จึงสรุปว่า variance ของสอง blender เท่ากันทุกประการ",
        "F = 2.56 ซึ่งมากกว่า 1.00 จึงสรุปว่า blender A แปรปรวนมากกว่าอย่างมีนัยสำคัญ",
        "F = 0.39 ซึ่งน้อยกว่า 1 จึงสรุปว่า blender B แปรปรวนมากกว่า",
        "ต้องใช้ paired t-test แทน เพราะเป็นการเปรียบเทียบสองเครื่อง",
      ],
      a: 0,
      r: "F-test เปรียบเทียบ variance: F = s₁²/s₂² โดยนำ variance ที่มากกว่าเป็นตัวตั้ง = 2.4²/1.5² = 5.76/2.25 = 2.56 เทียบกับ F critical (df 9, 9; two-sided α = 0.05) = 4.03\n\n2.56 < 4.03 จึงไม่ reject H₀ — ไม่ได้แปลว่า ‘เท่ากัน’ แต่ข้อมูล 10 ตำแหน่งยังไม่พอแสดงความต่าง (power ต่ำเมื่อ n น้อย) F-test ไวต่อการไม่เป็น normal distribution ด้วย ควรใช้ร่วมกับ engineering judgement (เช่น ผลต่อ content uniformity)",
      w: [
        "ถูก — F = 5.76/2.25 = 2.56 < 4.03 → fail to reject H₀",
        "ใช้อัตราส่วน SD แทน variance และสรุปเกินว่า ‘เท่ากันทุกประการ’",
        "ต้องเทียบกับ F critical ไม่ใช่ 1.00",
        "นำ variance ที่น้อยเป็นตัวตั้งและตีความกลับด้าน",
        "Paired t-test ใช้เทียบค่าเฉลี่ยของข้อมูลจับคู่ ไม่ใช่ variance",
      ],
      k: "F = s²(ใหญ่)/s²(เล็ก) เทียบ F critical; not significant ≠ เท่ากัน",
      d: "medium",
      ref: "Bolton & Bon, Pharmaceutical Statistics 5th ed., Ch.5; USP <1010>",
      c: ["s²A = 2.4² = 5.76; s²B = 1.5² = 2.25", "F = 5.76/2.25 = 2.56", "2.56 < F crit 4.03 → not significant"],
    },
    {
      t: "Blender working capacity batch size",
      p: "V-blender มี gross volume 500 L ผลการ validate ระบุว่า fill level ที่เหมาะสมคือ 60% ของ gross volume หาก final blend มี bulk density 0.48 g/mL ขนาด batch สูงสุดที่ผสมได้ในเครื่องนี้ประมาณกี่ kg",
      o: ["96 kg", "144 kg", "240 kg", "300 kg", "625 kg"],
      a: 1,
      r: "ปริมาตรทำงาน = 500 L × 0.60 = 300 L × bulk density 0.48 kg/L (= 0.48 g/mL) = 144 kg\n\nBlender แบบ tumbling ต้องมี headspace ให้ผงเคลื่อนที่ (cascading) การเติมเกิน (เช่น > 70%) ทำให้ผสมไม่ทั่ว ส่วนเติมน้อยเกิน (< 30%) อาจเกิด segregation/ผสมไม่มีประสิทธิภาพ ควรใช้ bulk density (ไม่ใช่ tapped) เพราะผงในเครื่องอยู่ในสภาพหลวม และเมื่อเปลี่ยน batch size ต้องอยู่ในช่วง fill level ที่ validate",
      w: [
        "ใช้ fill 40% (1 − 0.6) แทน 60%",
        "ถูก — 500 × 0.60 × 0.48 = 144 kg",
        "ไม่ได้คิด fill level (500 × 0.48)",
        "คิดปริมาตรเป็นน้ำหนักโดยไม่คูณ bulk density",
        "หารด้วย density แทนการคูณ",
      ],
      k: "Batch size (kg) = gross volume × fill fraction × bulk density",
      d: "medium",
      ref: "Levin (ed.), Pharmaceutical Process Scale-Up 3rd ed. (Blending); Aulton's Pharmaceutics 6th ed. (Mixing)",
      c: ["ปริมาตรทำงาน = 500 × 0.60 = 300 L", "Batch = 300 L × 0.48 kg/L = 144 kg"],
    },
    {
      t: "Ppk versus Cpk gap interpretation",
      p: "ข้อมูล assay (spec 95.0–105.0% LC) ของ 40 subgroups มี grand mean 100.6% ค่า within-subgroup SD (R̄/d2) = 1.0% แต่ overall SD ของข้อมูลทั้งหมด = 1.6% ข้อใดคำนวณและตีความถูกต้องที่สุด",
      o: [
        "Cpk = 1.47, Ppk = 0.92 — ความแปรปรวนระหว่าง subgroup/ช่วงเวลาสูง บ่งชี้ shift หรือ special cause ระยะยาวที่ต้องหาสาเหตุ",
        "Cpk = 0.92, Ppk = 1.47 — ความแปรปรวนระยะยาวต่ำกว่าระยะสั้น process จึงดีขึ้นตามเวลา",
        "Cpk = 1.87, Ppk = 1.17 — ทั้งสองค่าผ่านเกณฑ์ ไม่ต้องดำเนินการเพิ่ม",
        "Cp = 1.67, Pp = 1.04 — process capable เพราะ Cp > 1.33 ไม่จำเป็นต้องดู Ppk",
        "Cpk = 1.47, Ppk = 0.92 — ความต่างเป็นเรื่องปกติทางคณิตศาสตร์ ไม่มีความหมายในทางปฏิบัติ",
      ],
      a: 0,
      r: "Cpk ใช้ σ ระยะสั้น (within) และ Ppk ใช้ σ รวม (overall): ด้านที่ใกล้ spec คือ USL (105.0 − 100.6 = 4.4) → Cpk = 4.4/(3 × 1.0) = 1.47; Ppk = 4.4/(3 × 1.6) = 0.92\n\nเมื่อ Ppk ต่ำกว่า Cpk มาก แปลว่ามี variation ระหว่าง subgroup (เช่น batch-to-batch, raw material lot, shift ของเครื่อง) ที่ X̄-chart น่าจะแสดงเป็น out-of-control ด้วย Cpk จึง ‘มองโลกในแง่ดีเกินไป’ และ capability ที่ลูกค้าได้รับจริงสะท้อนด้วย Ppk ควรหาและกำจัดแหล่ง variation ระยะยาวก่อนอ้าง capability",
      w: [
        "ถูก — Cpk = 4.4/3.0 = 1.47; Ppk = 4.4/4.8 = 0.92; gap บ่งชี้ variation ระหว่าง subgroup",
        "สลับนิยาม — Ppk ใช้ overall SD ที่มากกว่า จึงต้องต่ำกว่า Cpk",
        "ใช้ระยะถึง LSL (5.6) ซึ่งไม่ใช่ด้านที่ใกล้ที่สุด",
        "Cp/Pp ไม่คำนึงตำแหน่ง mean และ Pp ~1.0 บ่งชี้ว่าไม่ capable ในระยะยาว",
        "Gap ใหญ่ระหว่าง Cpk–Ppk มีความหมาย: process ไม่ stable ระยะยาว",
      ],
      k: "Cpk ใช้ σ within (R̄/d2), Ppk ใช้ σ overall; Ppk << Cpk = มี between-subgroup variation/instability",
      d: "hard",
      ref: "AIAG Statistical Process Control Reference Manual 2nd ed.; Montgomery SQC 8th ed., Ch.8",
      c: [
        "ระยะ mean ถึง USL = 105.0 − 100.6 = 4.4 (ใกล้กว่า LSL ที่ 5.6)",
        "Cpk = 4.4/(3 × 1.0) = 1.47",
        "Ppk = 4.4/(3 × 1.6) = 0.92",
      ],
    },
    {
      t: "Fractional factorial aliasing (resolution IV)",
      p: "Screening DOE ใช้ 2^(4−1) fractional factorial (8 runs) โดย generator D = ABC (defining relation I = ABCD) ผลวิเคราะห์พบว่า effect ‘AB’ มีนัยสำคัญ ข้อใดตีความได้ถูกต้องที่สุด",
      o: [
        "Effect ที่เห็นคือผลรวมของ AB + CD (aliased กัน) ต้องใช้ความรู้เชิงกระบวนการหรือ fold-over/runs เพิ่มเพื่อแยก",
        "สรุปได้ทันทีว่า interaction ระหว่าง A และ B เป็นสาเหตุ เพราะ design มี resolution สูง",
        "AB aliased กับ main effect C จึงอาจเป็นผลของ factor C แทน",
        "Design นี้เป็น resolution III จึงประมาณ two-factor interaction ไม่ได้เลย",
        "Effect AB ไม่น่าเชื่อถือ เพราะ fractional factorial ประมาณได้เฉพาะ main effects",
      ],
      a: 0,
      r: "Alias หาได้โดยคูณ effect กับ defining relation (ตัวอักษรที่ซ้ำกันยกกำลังสอง = 1): AB × ABCD = A²B²CD = CD ดังนั้น AB และ CD เป็น alias กัน ส่วน main effect A aliased กับ BCD (three-factor interaction)\n\nDesign ที่ word สั้นสุดใน defining relation มี 4 ตัวอักษร = resolution IV: main effects ไม่ alias กับ 2FI แต่ 2FI alias กันเอง การแยก AB จาก CD ทำได้ด้วยความรู้เชิงกลไก (hierarchy/heredity: ถ้า A, B มี main effect ใหญ่ AB น่าจะจริง) หรือเพิ่ม runs (fold-over บางส่วน/augment เป็น full factorial)",
      w: [
        "ถูก — I = ABCD → AB = CD จึงต้องแยกด้วย process knowledge หรือ runs เพิ่ม",
        "Resolution IV ทำให้ 2FI ซ้อนกัน ไม่สามารถสรุปว่าเป็น AB เพียงอย่างเดียว",
        "AB × ABCD = CD ไม่ใช่ C; main effects ไม่ alias กับ 2FI ใน resolution IV",
        "Word ใน defining relation มี 4 ตัว จึงเป็น resolution IV ไม่ใช่ III",
        "Fractional factorial ประมาณ interaction ได้ แต่อยู่ในรูป alias chain",
      ],
      k: "Alias = effect × defining relation; Res III: main ↔ 2FI, Res IV: 2FI ↔ 2FI, Res V: 2FI ชัดเจน",
      d: "hard",
      ref: "Montgomery, Design and Analysis of Experiments 9th ed., Ch.8 (Two-level fractional factorial designs)",
    },
    {
      t: "Froude number scale-up of impeller speed",
      p: "Pilot high-shear granulator มี impeller diameter 0.20 m ใช้ 450 rpm หากขยายไปเครื่อง production ที่ geometrically similar มี impeller diameter 0.80 m โดยใช้หลัก ‘คง Froude number’ (Fr = N²D/g) ควรตั้ง impeller speed ประมาณเท่าใด",
      o: ["28 rpm", "113 rpm", "225 rpm", "450 rpm", "900 rpm"],
      a: 2,
      r: "คง Fr: N₁²D₁ = N₂²D₂ → N₂ = N₁ × √(D₁/D₂) = 450 × √(0.20/0.80) = 450 × 0.5 = 225 rpm\n\nFroude number คืออัตราส่วนแรงหนีศูนย์กลางต่อแรงโน้มถ่วง สัมพันธ์กับรูปแบบการไหลของ powder bed (bumping vs roping flow) ในเครื่อง high-shear เมื่อคง Fr tip speed จะเพิ่มขึ้น (จาก 4.71 เป็น 9.42 m/s) ขณะที่การคง tip speed (N₂ = 112.5 rpm) จะให้ Fr ต่ำลง จึงไม่มีกฎเดียวที่คงทุก dimensionless group ได้ ต้องเลือกตามกลไกที่เด่น และยืนยันด้วย granule properties",
      w: [
        "ใช้อัตราส่วน D² (450 × 1/16) ซึ่งไม่ใช่กฎ Froude",
        "เป็นผลของการคง tip speed (N ∝ 1/D) ไม่ใช่ Froude",
        "ถูก — 450 × √(0.20/0.80) = 450 × 0.5 = 225 rpm",
        "คง rpm เดิม ทำให้ Fr เพิ่ม 4 เท่า",
        "คูณแทนการหาร ทำให้ speed สูงเกินจริงมาก",
      ],
      k: "Froude constant: N₂ = N₁√(D₁/D₂); tip speed constant: N₂ = N₁(D₁/D₂)",
      d: "hard",
      ref: "Levin (ed.), Pharmaceutical Process Scale-Up 3rd ed.; Horsthuis GJB et al. Int J Pharm 1993;92:143–150",
      c: ["N₂ = N₁ × √(D₁/D₂)", "= 450 × √(0.20/0.80) = 450 × 0.5", "= 225 rpm"],
    },
  ],
  // Mock Set 5 — การคำนวณและสถิติในการผลิต
  [
    {
      t: "Cost of quality category classification",
      p: "โรงงานวิเคราะห์ cost of quality ประจำปี พบค่าใช้จ่ายจากการนำ batch ยาเม็ดที่ hardness ต่ำกว่า spec ระหว่าง IPC มา re-process (ก่อน release และก่อนออกสู่ตลาด) รวมค่าแรง เวลาเครื่อง และการทดสอบซ้ำ ค่าใช้จ่ายนี้จัดอยู่ในหมวดใด",
      o: [
        "Internal failure cost",
        "External failure cost",
        "Appraisal cost",
        "Prevention cost",
        "Opportunity cost ของ capacity planning",
      ],
      a: 0,
      r: "Cost of quality แบ่งเป็น cost of good quality (prevention + appraisal) และ cost of poor quality (internal + external failure) Internal failure คือความเสียหายที่พบ ‘ก่อน’ ผลิตภัณฑ์ถึงลูกค้า เช่น reject, rework/re-process, การสอบสวน deviation และการทดสอบซ้ำ\n\nExternal failure คือหลังถึงลูกค้า (complaint, recall, return) ซึ่งแพงที่สุดและทำลายชื่อเสียง Appraisal คือการตรวจสอบ/ทดสอบตามปกติ (incoming QC, IPC, release testing, calibration) ส่วน prevention เช่น training, validation, QbD, supplier qualification หลักคือการลงทุนใน prevention ช่วยลด failure costs โดยรวม",
      w: [
        "ถูก — rework/re-process ที่พบก่อน release เป็น internal failure",
        "External failure เกิดหลังผลิตภัณฑ์ถึงตลาด/ลูกค้า เช่น recall, complaint",
        "Appraisal คือค่าตรวจสอบตามปกติ ไม่ใช่ค่าแก้ไขสิ่งที่ล้มเหลว",
        "Prevention คือกิจกรรมป้องกันล่วงหน้า เช่น training, validation, FMEA",
        "ไม่ใช่หนึ่งในสี่หมวดหลักของ cost of quality",
      ],
      k: "CoQ = prevention + appraisal + internal failure (ก่อนถึงลูกค้า) + external failure (หลังถึงลูกค้า)",
      d: "easy",
      ref: "Juran's Quality Handbook 7th ed. (Cost of poor quality); ASQ Cost of Quality (PAF model)",
    },
    {
      t: "Capsule filling machine batch time",
      p: "Final blend 135 kg สำหรับบรรจุแคปซูล fill weight สุทธิ 375 mg/แคปซูล (ไม่รวมน้ำหนัก shell 75 mg) เครื่องบรรจุอัตโนมัติมีอัตรา 1,200 แคปซูล/นาที สมมติไม่มีการหยุดเครื่องและไม่มี loss การบรรจุทั้ง batch ใช้เวลาประมาณกี่ชั่วโมง",
      o: ["1.9 h", "3.0 h", "4.2 h", "5.0 h", "300 h"],
      a: 3,
      r: "จำนวนแคปซูล = น้ำหนัก blend ÷ fill weight สุทธิ = 135,000,000 mg ÷ 375 mg = 360,000 แคปซูล อัตราเครื่อง = 1,200 × 60 = 72,000 แคปซูล/ชั่วโมง\n\nเวลา = 360,000 ÷ 72,000 = 5.0 ชั่วโมง ต้องใช้ fill weight ‘สุทธิ’ ของผง (ไม่รวม shell) เพราะ blend ถูกแบ่งเป็นผงที่บรรจุเท่านั้น ในการวางแผนจริงต้องเผื่อเวลา set-up, IPC weight check, การ reject และ efficiency ของเครื่อง",
      w: [
        "นำกรัมของ blend (135,000 g) หารอัตราต่อชั่วโมงโดยตรง ไม่ได้แปลงเป็นจำนวนแคปซูล",
        "คำนวณได้ 300 นาทีแต่แปลงหน่วยผิดเป็น 3.0 ชั่วโมง",
        "ใช้น้ำหนักรวม shell (450 mg) คำนวณจำนวนแคปซูล ทำให้ได้จำนวนน้อยเกินจริง",
        "ถูก — 360,000 แคปซูล ÷ 72,000 แคปซูล/h = 5.0 h",
        "สับสนหน่วยนาทีกับชั่วโมง (300 นาทีไม่ใช่ 300 ชั่วโมง)",
      ],
      k: "จำนวนหน่วย = blend ÷ net fill weight; เวลา = จำนวนหน่วย ÷ (อัตรา/นาที × 60)",
      d: "easy",
      ref: "Aulton's Pharmaceutics 6th ed. (Hard capsules: filling machines); Lachman/Lieberman's Industrial Pharmacy 4th ed.",
      c: [
        "จำนวนแคปซูล = 135,000,000 mg ÷ 375 mg = 360,000",
        "อัตรา = 1,200 × 60 = 72,000 แคปซูล/h",
        "เวลา = 360,000 ÷ 72,000 = 5.0 h",
      ],
    },
    {
      t: "Cumulative multistage process yield",
      p: "ยาเม็ดเคลือบฟิล์มผลิตผ่าน 5 ขั้นตอนที่มี stage yield ดังนี้: granulation 98.0%, drying/milling 97.5%, final blending 99.5%, compression 96.0% และ coating 98.5% Overall yield ของกระบวนการ (เทียบกับวัตถุดิบเริ่มต้น) ใกล้เคียงข้อใด",
      o: ["10.1%", "89.5%", "89.9%", "96.0%", "97.9%"],
      a: 2,
      r: "Overall yield ของกระบวนการต่อเนื่อง = ผลคูณของ stage yields (เพราะแต่ละขั้นได้ผลผลิตเป็นสัดส่วนของ input ของขั้นนั้น): 0.980 × 0.975 × 0.995 × 0.960 × 0.985 = 0.899 → 89.9%\n\nการรวม % loss แบบบวก (100 − 10.5 = 89.5%) ให้ค่าประมาณที่ต่ำกว่าจริงเล็กน้อย ส่วนค่าเฉลี่ยของ yields ไม่มีความหมายเชิงกระบวนการ การดู overall yield ช่วยชี้ว่าขั้นตอนใด (ที่นี่คือ compression) เป็นแหล่ง loss หลักที่คุ้มค่าในการปรับปรุง และช่วยตั้ง yield limits ใน batch record",
      w: [
        "เป็น % loss รวม ไม่ใช่ overall yield",
        "ลบ % loss แบบบวกกันตรงๆ (2.0 + 2.5 + 0.5 + 4.0 + 1.5 = 10.5%) ซึ่งไม่ถูกหลัก",
        "ถูก — ผลคูณของ stage yields = 0.899 → 89.9%",
        "เป็น yield ของขั้นที่ต่ำที่สุดเท่านั้น",
        "เป็นค่าเฉลี่ยของ stage yields ซึ่งไม่มีความหมาย",
      ],
      k: "Overall yield = Π stage yields (คูณกัน) ไม่ใช่บวก loss หรือเฉลี่ย",
      d: "medium",
      ref: "21 CFR 211.103 Calculation of yield; Lachman/Lieberman's Industrial Pharmacy 4th ed.",
      c: [
        "0.980 × 0.975 = 0.9555",
        "× 0.995 = 0.9507",
        "× 0.960 = 0.9127",
        "× 0.985 = 0.8990 → 89.9%",
      ],
    },
    {
      t: "Linear regression inverse prediction",
      p: "Compression study ในช่วง 8–20 kN ได้สมการ regression: hardness (kP) = 1.8 + 0.92 × compression force (kN), r² = 0.96 หากต้องการ hardness เป้าหมาย 15 kP ควรตั้ง compression force ประมาณเท่าใด",
      o: ["13.2 kN", "13.8 kN", "14.3 kN", "15.6 kN", "16.3 kN"],
      a: 2,
      r: "Inverse prediction: force = (hardness − intercept)/slope = (15 − 1.8)/0.92 = 13.2/0.92 = 14.3 kN ซึ่งอยู่ในช่วงที่ศึกษา (8–20 kN) จึงเป็น interpolation ที่เชื่อถือได้\n\nr² = 0.96 แปลว่า 96% ของความแปรปรวนของ hardness อธิบายได้ด้วย compression force (ไม่ได้แปลว่าความแม่นยำ ±4%) ต้องตรวจ residual plot ว่าเป็นเส้นตรงจริง และไม่ควร extrapolate นอกช่วงที่ศึกษา เพราะที่แรงสูง hardness มักเข้าสู่ plateau หรือเกิด capping",
      w: [
        "ลบ intercept แล้วลืมหารด้วย slope",
        "นำ slope ไปคูณ 15 (ใช้สมการผิดทิศ)",
        "ถูก — (15 − 1.8)/0.92 = 14.3 kN",
        "แทนค่า 15 เป็น force แล้วคำนวณ hardness (ใช้สมการผิดทิศ)",
        "หาร 15 ด้วย slope โดยไม่หัก intercept",
      ],
      k: "Inverse prediction x = (y − b₀)/b₁; ใช้เฉพาะในช่วงที่ศึกษา; r² = สัดส่วน variance ที่อธิบายได้",
      d: "medium",
      ref: "Bolton & Bon, Pharmaceutical Statistics 5th ed., Ch.7 (Linear regression and correlation)",
      c: ["force = (15 − 1.8) ÷ 0.92", "= 13.2 ÷ 0.92 = 14.3 kN"],
    },
    {
      t: "Coating pan spray-rate scale-up by pan load",
      p: "Lab coating pan บรรจุ cores 5 kg ใช้ spray rate รวม 20 g/min เมื่อขยายไป production pan บรรจุ 150 kg โดยใช้หลักคง ‘spray rate ต่อ kg ของ pan load’ และเครื่องมี spray guns 6 กระบอก แต่ละกระบอกควรตั้ง spray rate ประมาณเท่าใด",
      o: ["3.3 g/min", "20 g/min", "24 g/min", "100 g/min", "600 g/min"],
      a: 3,
      r: "Spray rate ต่อ kg ที่ lab = 20/5 = 4 g/min/kg → production รวม = 4 × 150 = 600 g/min แบ่ง 6 guns = 100 g/min/gun\n\nการ scale ตาม pan load เป็นจุดเริ่มต้นที่ใช้บ่อย เพราะเม็ดยาต่อหน่วยมวลควรได้รับ coating ในอัตราใกล้เดิม แต่ต้องตรวจว่า drying capacity (inlet air volume/temperature) รองรับปริมาณน้ำที่เพิ่มขึ้น และ spray zone ของแต่ละ gun ไม่ทับกัน หากระบบอบแห้งไม่พอจะเกิด over-wetting (picking/sticking) จึงมักใช้ thermodynamic model (เช่น ค่า exhaust temperature/RH) ร่วมยืนยัน",
      w: [
        "หาร spray rate lab ด้วยจำนวน gun โดยไม่ scale ตาม load",
        "ใช้ spray rate เดิมของ lab โดยไม่ scale",
        "คูณ rate ต่อ kg ด้วยจำนวน gun ซึ่งไม่มีหลักการ",
        "ถูก — 20/5 × 150 = 600 g/min ÷ 6 guns = 100 g/min/gun",
        "เป็น spray rate รวมทั้งเครื่อง ไม่ใช่ต่อ gun",
      ],
      k: "Spray rate รวม ∝ pan load (g/min/kg คงที่) แล้วแบ่งตามจำนวน gun; ต้องยืนยัน drying capacity",
      d: "medium",
      ref: "Levin (ed.), Pharmaceutical Process Scale-Up 3rd ed. (Film coating scale-up); Porter, Pharmaceutical Coating Technology",
      c: ["Lab = 20 g/min ÷ 5 kg = 4 g/min/kg", "Production รวม = 4 × 150 = 600 g/min", "ต่อ gun = 600 ÷ 6 = 100 g/min"],
    },
    {
      t: "Maximum allowable SD for target Cpk",
      p: "Content uniformity specification 90.0–110.0% LC กระบวนการมี mean คงที่ที่ 101.0% LC บริษัทกำหนดให้ Cpk ≥ 1.33 ค่า SD สูงสุดของกระบวนการที่ยอมรับได้ใกล้เคียงข้อใด",
      o: ["1.13%", "2.26%", "2.51%", "2.76%", "3.38%"],
      a: 1,
      r: "Cpk ถูกกำหนดโดยด้านที่ใกล้ spec ที่สุด คือ USL: (110.0 − 101.0)/(3σ) ≥ 1.33 → σ ≤ 9.0/(3 × 1.33) = 9.0/3.99 = 2.26%\n\nถ้า mean อยู่กลาง (100%) σ สูงสุดจะเป็น 2.51% แสดงว่าการ off-center 1% ทำให้ต้องควบคุม variation เข้มขึ้น ~10% Cpk 1.33 เทียบได้กับระยะ 4σ จาก spec ที่ใกล้ที่สุด (~32 ppm นอก spec ด้านนั้นสำหรับ normal distribution)",
      w: [
        "ใช้ 6σ ในตัวหาร (สูตรของ Cp ไม่ใช่ Cpk ด้านเดียว)",
        "ถูก — σ ≤ (110 − 101)/(3 × 1.33) = 2.26%",
        "คิดเหมือน mean อยู่กลาง spec (10/3.99) ไม่ตรงกับ mean 101%",
        "ใช้ระยะถึง LSL (11) ซึ่งเป็นด้านที่ห่างกว่า",
        "ใช้ 2σ ในตัวหารแทน 3σ",
      ],
      k: "σ_max = (ระยะ mean ถึง spec ที่ใกล้สุด) ÷ (3 × Cpk เป้าหมาย); Cpk 1.33 ≈ 4σ ถึง spec",
      d: "medium",
      ref: "Montgomery, Introduction to Statistical Quality Control 8th ed., Ch.8",
      c: ["ด้านใกล้ = USL: 110.0 − 101.0 = 9.0", "σ ≤ 9.0 ÷ (3 × 1.33) = 9.0 ÷ 3.99 = 2.26%"],
    },
    {
      t: "Control limits versus specification limits",
      p: "ผู้จัดการฝ่ายผลิตเสนอให้ใช้ specification ของน้ำหนักเม็ด (±5% ของ target) เป็นเส้น UCL/LCL บน X̄-chart (n = 5) แทนการคำนวณ control limits จากข้อมูล ‘เพราะเข้าใจง่ายกว่า’ ข้อใดอธิบายปัญหาของข้อเสนอนี้ได้ถูกต้องที่สุด",
      o: [
        "Spec ใช้กับหน่วยเดี่ยวและสะท้อนความต้องการ ไม่ใช่ความแปรปรวนจริงของกระบวนการ chart จะไม่ไวต่อ special cause และค่าเฉลี่ย subgroup แทบไม่มีวันเกินเส้น",
        "Spec limits แคบกว่า control limits เสมอ จึงทำให้เกิด false alarm บ่อยเกินไป",
        "ไม่มีปัญหา เพราะเป้าหมายของ SPC คือการตรวจว่าผลิตภัณฑ์ผ่าน spec หรือไม่",
        "ปัญหาอยู่ที่ต้องใช้ spec ±3% แทน ±5% จึงจะเหมาะกับ X̄-chart",
        "ทำได้เฉพาะเมื่อ Cpk < 1.0 เพราะ spec และ control limits จะเท่ากันพอดี",
      ],
      a: 0,
      r: "Control limits (voice of the process) คำนวณจากความแปรปรวนจริงของกระบวนการ (common-cause) เพื่อแยก special cause ออกจาก common cause ส่วน specification (voice of the customer) กำหนดจากความต้องการของผลิตภัณฑ์และใช้ตัดสินหน่วยเดี่ยว\n\nX̄-chart plot ค่าเฉลี่ยของ subgroup ซึ่งแปรปรวนน้อยกว่าค่าเดี่ยว √n เท่า การใช้ spec ของค่าเดี่ยวเป็นเส้นบน X̄-chart ทำให้ chart แทบไม่เคยส่งสัญญาณ จนกว่าความเสียหายจะเกิดไปมากแล้ว การผ่าน spec กับการอยู่ใน statistical control เป็นคนละคำถามกัน และ process ที่ capable ดีมี control limits อยู่ภายใน spec ห่างพอสมควร",
      w: [
        "ถูก — spec ไม่ได้สะท้อน process variation และใช้กับค่าเดี่ยว ทำให้ chart ไม่ไวต่อ special cause",
        "ใน process ที่ capable control limits จะแคบกว่า spec ไม่ใช่กว้างกว่า",
        "SPC มุ่งตรวจความเสถียรของกระบวนการ ไม่ใช่การตรวจผ่าน/ไม่ผ่าน spec",
        "ไม่ว่าจะ ±กี่ % ก็ยังเป็น spec ไม่ใช่ limits ที่คำนวณจากข้อมูล",
        "ไม่มีกฎนี้ Cpk ไม่ได้ทำให้ spec กลายเป็น control limits",
      ],
      k: "Control limits = เสียงของกระบวนการ (คำนวณจากข้อมูล); spec = เสียงของลูกค้า; ห้ามใช้แทนกัน",
      d: "medium",
      ref: "Wheeler DJ, Understanding Variation 2nd ed.; Montgomery SQC 8th ed., Ch.5",
    },
    {
      t: "Probability of acceptance for c = 0 plan",
      p: "Supplier ของ aluminium foil เสนอ sampling plan แบบ zero-acceptance (n = 50, c = 0) หาก lot มีสัดส่วน defective จริง 2.0% ความน่าจะเป็นที่ lot นั้นจะถูกยอมรับ (Pa) ใกล้เคียงข้อใด (ใช้ binomial: Pa = (1 − p)^n)",
      o: ["2.0%", "13.3%", "36.4%", "63.6%", "98.0%"],
      a: 2,
      r: "สำหรับ c = 0 lot จะถูกยอมรับเมื่อไม่พบ defective เลยในตัวอย่าง: Pa = (1 − p)^n = 0.98^50 = 0.364 → 36.4%\n\nแปลว่าแม้ lot มี defective 2% (สูงกว่า AQL ทั่วไปมาก) ยังมีโอกาสผ่าน ~1 ใน 3 ครั้ง การคำนวณ Pa ที่ p หลายค่าแล้ว plot คือ OC curve ของแผน แผน c = 0 ปกป้องผู้ผลิตน้อย (Pa ลดเร็วเมื่อ p เพิ่มเล็กน้อย) แต่ก็ไม่ได้ ‘รับประกัน zero defect’ ต้องใช้ร่วมกับ supplier qualification และ process control",
      w: [
        "นำสัดส่วน defective มาใช้เป็น Pa โดยตรง",
        "เป็น Pa เมื่อ n = 100 (0.98^100)",
        "ถูก — 0.98^50 = 0.364 → 36.4%",
        "เป็นความน่าจะเป็นที่จะ reject (1 − 0.364)",
        "เป็น (1 − p) ของหน่วยเดียว ไม่ได้ยกกำลัง n",
      ],
      k: "c = 0: Pa = (1 − p)^n; plot Pa vs p = OC curve; c = 0 ไม่ได้แปลว่า lot ไม่มี defect",
      d: "hard",
      ref: "ANSI/ASQ Z1.4-2003 (R2018); Montgomery, Introduction to Statistical Quality Control 8th ed., Ch.15 (OC curves)",
      c: ["Pa = (1 − 0.02)^50 = 0.98^50", "ln Pa = 50 × ln 0.98 = 50 × (−0.0202) = −1.010", "Pa = e^−1.010 = 0.364 → 36.4%"],
    },
    {
      t: "Gauge R&R percent of tolerance",
      p: "ก่อนใช้ in-line NIR วัด content ของยาเม็ดเพื่อ release ทีมทำ Gauge R&R study (3 operators × 10 เม็ด × 3 ซ้ำ) ได้ σ repeatability = 0.24% LC และ σ reproducibility = 0.32% LC ข้อกำหนด content คือ 95.0–105.0% LC ค่า %GRR เทียบกับ tolerance (ใช้ 6σ) และข้อสรุปตามเกณฑ์ AIAG คือข้อใด",
      o: [
        "4.0% — ระบบวัดยอมรับได้ (< 10%)",
        "12.0% — ยอมรับได้แบบมีเงื่อนไข (10–30%)",
        "24.0% — ยอมรับได้แบบมีเงื่อนไข (10–30%) ขึ้นกับความสำคัญของการวัดและต้นทุนการปรับปรุง",
        "33.6% — ยอมรับไม่ได้ (> 30%) ต้องปรับปรุงระบบวัด",
        "48.0% — ยอมรับไม่ได้ (> 30%) ต้องปรับปรุงระบบวัด",
      ],
      a: 2,
      r: "ความแปรปรวนของระบบวัด (GRR) รวม repeatability (equipment variation — วัดซ้ำโดยคนเดิม) กับ reproducibility (appraiser variation — ต่างผู้วัด) แบบ variance (ไม่ใช่บวก SD ตรง ๆ): σGRR = √(0.24² + 0.32²) = √(0.0576 + 0.1024) = √0.16 = 0.40% LC\n\n%GRR (to tolerance) = 6σGRR/(USL − LSL) × 100 = 6 × 0.40/10 × 100 = 24% ตามเกณฑ์ AIAG MSA: < 10% ยอมรับได้, 10–30% ยอมรับได้แบบมีเงื่อนไข, > 30% ยอมรับไม่ได้\n\nแปลว่าระบบวัด 'กิน' ช่วง specification ไปเกือบหนึ่งในสี่ เสี่ยงตัดสินผิด (ปล่อยเม็ดที่ OOS หรือปฏิเสธเม็ดที่ดี) ใกล้ขอบ spec ถ้า repeatability หรือ reproducibility ตัวใดเด่น จะชี้ว่าควรปรับปรุงที่เครื่องมือ หรือการฝึกอบรม/วิธีปฏิบัติของผู้วัด",
      w: [
        "ใช้ σGRR/tolerance (0.40/10) โดยไม่คูณ 6 จึงต่ำเกินจริง",
        "ใช้ 3σ แทน 6σ ทำให้ %GRR ต่ำไปครึ่งหนึ่ง",
        "ถูก — σGRR = √(0.24² + 0.32²) = 0.40; 6 × 0.40/10 = 24% อยู่ในช่วง marginal",
        "บวก SD แบบเส้นตรง (0.24 + 0.32 = 0.56) ผิด เพราะต้องรวมกันแบบ variance",
        "หารด้วยครึ่ง tolerance (5%) แทนช่วงเต็ม USL − LSL (10%)",
      ],
      k: "σGRR = √(σrepeat² + σreprod²); %GRR = 6σGRR/(USL − LSL); <10% ดี, 10–30% มีเงื่อนไข, >30% ไม่ผ่าน",
      d: "hard",
      ref: "AIAG Measurement Systems Analysis (MSA) Reference Manual 4th ed.; Montgomery, Introduction to Statistical Quality Control",
      c: [
        "σGRR = √(0.24² + 0.32²) = √0.16 = 0.40% LC",
        "Tolerance = 105.0 − 95.0 = 10.0% LC",
        "%GRR = 6 × 0.40 / 10.0 × 100 = 24.0%",
        "24% อยู่ในช่วง 10–30% → ยอมรับได้แบบมีเงื่อนไข",
      ],
    },
    {
      t: "Central composite design run count",
      p: "หลัง screening พบ 3 factors สำคัญต่อ dissolution ของยาเม็ด และพบ curvature จาก center points ทีมต้องการสร้าง response surface (quadratic model) ด้วย central composite design (CCD) แบบ full factorial core + axial points + 6 center points ข้อใดถูกต้อง",
      o: [
        "8 runs — factorial core อย่างเดียวพอสำหรับ quadratic model",
        "14 runs — factorial + axial ไม่ต้องมี center points",
        "17 runs — CCD ของ 3 factors ที่มี 5 center points",
        "20 runs — 8 factorial + 6 axial + 6 center ประมาณ quadratic terms ได้",
        "27 runs — CCD ต้องใช้ 3 ระดับของทุก factor แบบ full factorial",
      ],
      a: 3,
      r: "CCD = 2^k factorial core + 2k axial (star) points + center points: k = 3 → 8 + 6 + 6 = 20 runs Axial points ทำให้แต่ละ factor มี 5 ระดับ (−α, −1, 0, +1, +α) จึงประมาณ quadratic (x²) terms ได้ ส่วน center points ให้ pure error และช่วยให้ prediction variance สม่ำเสมอ\n\n17 runs คือ Box–Behnken design ของ 3 factors (12 edge points + 5 center) ซึ่งไม่ใช่ CCD 27 runs คือ 3^3 full factorial ที่ประมาณ quadratic ได้เช่นกันแต่ใช้ runs มากกว่า Response surface ใช้หา design space ตาม ICH Q8(R2)",
      w: [
        "Factorial 2 ระดับประมาณได้เฉพาะ linear + interaction ไม่ได้ quadratic",
        "ขาด center points ทำให้ไม่มี pure error และ prediction ตรงกลางไม่ดี",
        "เป็นจำนวน runs ของ Box–Behnken design ไม่ใช่ CCD",
        "ถูก — 2³ + 2×3 + 6 = 20 runs; axial points ให้ 5 ระดับเพื่อประมาณ curvature",
        "เป็น 3^3 full factorial ไม่ใช่โครงสร้างของ CCD",
      ],
      k: "CCD runs = 2^k + 2k + n₀; Box–Behnken (3 factors) = 12 + n₀; ใช้สร้าง response surface/design space",
      d: "hard",
      ref: "Montgomery, Design and Analysis of Experiments 9th ed., Ch.11 (Response surface methods); ICH Q8(R2)",
      c: ["Factorial = 2³ = 8", "Axial = 2 × 3 = 6", "Center = 6", "รวม = 8 + 6 + 6 = 20 runs"],
    },
  ],
];
