import type { Ip1MockDomainContent } from "@/lib/ip1-mock/types";

export const CALC: Ip1MockDomainContent = [
  // Mock Set 1 — การคำนวณและสถิติในการผลิต
  [
    {
      t: "Master formula batch scaling",
      p: "Master formula ของยาเม็ด paracetamol ระบุสูตรต่อ 1,000 เม็ดดังนี้: paracetamol 500 g, microcrystalline cellulose 120 g, PVP K30 15 g, croscarmellose sodium 20 g และ magnesium stearate 5 g หากต้องผลิต batch ขนาด 250,000 เม็ด ต้องเตรียม PVP K30 กี่ kg",
      o: ["0.375 kg", "1.5 kg", "3.75 kg", "15 kg", "37.5 kg"],
      a: 2,
      r: "การขยายสูตร (batch scaling) จาก master formula ใช้ scale factor = batch size ที่ต้องการ ÷ batch size ของสูตรอ้างอิง โดยคูณทุกส่วนประกอบด้วย factor เดียวกันเพื่อรักษาสัดส่วนสูตร\n\nScale factor = 250,000/1,000 = 250 ดังนั้น PVP K30 = 15 g × 250 = 3,750 g = 3.75 kg จุดที่มักพลาดคือการแปลงหน่วย g → kg (หาร 1,000) และการนับเลขศูนย์ของ batch size ผิด",
      w: [
        "ผิดหลักทศนิยม 1 ตำแหน่ง (เหมือนใช้ factor 25 แทน 250)",
        "ไม่ใช่ — เป็นตัวเลขที่ไม่มีที่มาจากสัดส่วนสูตร อาจเกิดจากคิด 15 g × 100",
        "ถูก — 15 g × (250,000/1,000) = 3,750 g = 3.75 kg",
        "เป็นการใช้ 15 g ต่อ 1,000 เม็ดแล้วคูณ 1,000 (นับ batch เป็น 1,000,000 เม็ด) ทำให้มากเกินจริง 4 เท่า",
        "ผิดหลักทศนิยม 1 ตำแหน่ง (คูณ 2,500 แทน 250)",
      ],
      k: "Scale factor = batch ที่ต้องการ ÷ batch ในสูตรอ้างอิง แล้วคูณทุกส่วนประกอบเท่ากัน ระวังการแปลงหน่วย",
      d: "easy",
      ref: "PIC/S GMP Guide PE 009 Part I Ch.4 (Manufacturing Formula and Processing Instructions)",
      c: ["Scale factor = 250,000 ÷ 1,000 = 250", "PVP K30 = 15 g × 250 = 3,750 g", "3,750 g ÷ 1,000 = 3.75 kg"],
    },
    {
      t: "Actual yield percentage",
      p: "Batch ยาเม็ด 200,000 เม็ด น้ำหนักเม็ด 300 mg (theoretical yield = 60.0 kg) เมื่อสิ้นสุดการตอก ได้ยาเม็ดที่ผ่านเกณฑ์ 57.3 kg, เก็บตัวอย่าง QC 0.3 kg และยาเม็ด reject 1.2 kg ค่า actual yield (%) ของยาเม็ดที่ผ่านเกณฑ์เท่าใด",
      o: ["93.5%", "95.5%", "96.0%", "97.4%", "98.0%"],
      a: 1,
      r: "Actual yield (%) = ปริมาณผลผลิตที่ได้จริง ÷ theoretical yield × 100 โดย theoretical yield คำนวณจากปริมาณที่ควรได้หากไม่มีการสูญเสีย (200,000 × 300 mg = 60.0 kg)\n\nดังนั้น yield = 57.3/60.0 × 100 = 95.5% ส่วนค่า 98.0% คือ accountability/reconciliation ((57.3+0.3+1.2)/60.0) ซึ่งใช้ตรวจว่ามวลสารถูกติดตามครบหรือไม่ ทั้งสองค่าต้องอยู่ในช่วงที่ validate ไว้ใน batch record หากนอกช่วงต้องสอบสวนตาม 21 CFR 211.192",
      w: [
        "เป็นการหัก reject ออกซ้ำจากยาเม็ดดี ((57.3−1.2)/60) ไม่มีหลักการรองรับ",
        "ถูก — 57.3/60.0 × 100 = 95.5%",
        "รวมตัวอย่าง QC เข้ากับยาเม็ดดี ((57.3+0.3)/60) ซึ่งไม่ใช่ yield ของผลผลิตที่จำหน่ายได้",
        "ใช้ผลรวมที่ติดตามได้ (58.8 kg) เป็นตัวหารแทน theoretical yield จึงผิดนิยาม",
        "เป็นค่า accountability (57.3+0.3+1.2 = 58.8 kg; 98.0%) ไม่ใช่ actual yield",
      ],
      k: "Yield = ผลผลิตที่ดี ÷ theoretical × 100; accountability = (ผลผลิต + ตัวอย่าง + reject + loss ที่ระบุได้) ÷ theoretical × 100",
      d: "easy",
      ref: "21 CFR 211.103 Calculation of yield; PIC/S GMP Guide PE 009 Part I Ch.5",
      c: [
        "Theoretical yield = 200,000 × 300 mg = 60,000,000 mg = 60.0 kg",
        "Actual yield = 57.3 / 60.0 × 100 = 95.5%",
        "(เปรียบเทียบ) Accountability = (57.3 + 0.3 + 1.2)/60.0 × 100 = 98.0%",
      ],
    },
    {
      t: "Overage with potency adjustment",
      p: "ยาเม็ด vitamin C label claim 100 mg/เม็ด บริษัทกำหนด manufacturing overage 7.5% (เติมเพิ่มจาก label claim เพื่อชดเชยการสลายตัวที่พิสูจน์แล้ว) วัตถุดิบ ascorbic acid lot ที่ใช้มี assay 98.0% (as-is) หากผลิต 400,000 เม็ด ต้องชั่ง ascorbic acid lot นี้ประมาณกี่ kg",
      o: ["40.00 kg", "40.82 kg", "43.00 kg", "43.88 kg", "44.13 kg"],
      a: 3,
      r: "Overage คิดเป็นเปอร์เซ็นต์เพิ่มจาก label claim: ปริมาณเป้าหมายต่อเม็ด = 100 × 1.075 = 107.5 mg (สาร 100%) จากนั้นแก้ potency ของวัตถุดิบโดยหารด้วย 0.980 ได้ 109.69 mg/เม็ด × 400,000 เม็ด = 43.88 kg\n\nICH Q8(R2) ระบุว่า overage ต้องมีเหตุผลรองรับ (เช่น ชดเชยการสูญเสียในกระบวนการผลิตหรือการสลายตัว) และต้องระบุใน dossier ไม่ควรใช้ overage เพื่อยืด shelf life โดยไม่มีข้อมูล ลำดับการคิด: label claim → บวก overage → หารด้วย potency → คูณจำนวนเม็ด",
      w: [
        "ไม่ได้คิดทั้ง overage และ potency (100 mg × 400,000)",
        "แก้เฉพาะ potency (100/0.98 × 400,000) ลืม overage 7.5%",
        "คิดเฉพาะ overage (107.5 mg × 400,000) ลืมแก้ potency 98.0%",
        "ถูก — 100 × 1.075 ÷ 0.980 = 109.69 mg/เม็ด × 400,000 = 43.88 kg",
        "ตีความ overage ผิดเป็นการหาร (100/0.925) ทำให้ได้ปริมาณเกินกว่าที่กำหนด",
      ],
      k: "ปริมาณชั่ง = label claim × (1 + %overage) ÷ potency (เศษส่วน) × จำนวนหน่วย",
      d: "medium",
      ref: "ICH Q8(R2) Pharmaceutical Development, section 2.2.1 (Overages)",
      c: [
        "เป้าหมายต่อเม็ด = 100 mg × 1.075 = 107.5 mg (pure)",
        "แก้ potency = 107.5 ÷ 0.980 = 109.69 mg ของวัตถุดิบ/เม็ด",
        "ทั้ง batch = 109.69 mg × 400,000 = 43,877,551 mg ≈ 43.88 kg",
      ],
    },
    {
      t: "Anhydrous-basis potency weighing",
      p: "Certificate of Analysis ของ API ระบุ assay 99.2% on anhydrous basis และ water content (KF) 4.8% สูตรการผลิตกำหนดให้ใช้ API (คิดเป็น 100% anhydrous) 25.0 kg ต่อ batch ต้องชั่ง API lot นี้ (as-is) ประมาณกี่ kg",
      o: ["23.61 kg", "25.20 kg", "26.26 kg", "26.40 kg", "26.47 kg"],
      a: 4,
      r: "เมื่อ assay รายงานบน anhydrous basis ต้องแปลงเป็น as-is ก่อน: potency as-is = assay(anhydrous) × (1 − water fraction) = 0.992 × 0.952 = 0.9444 (94.44%)\n\nปริมาณชั่ง = 25.0 ÷ 0.9444 = 26.47 kg การบวกเปอร์เซ็นต์รวมกัน (100 + 0.8 + 4.8 = 105.6%) เป็นการประมาณที่ผิดเล็กน้อยแต่ในงาน GMP ต้องใช้สูตรที่ถูกต้องเพราะ error สะสมใน batch ใหญ่ หลักคือ ‘แปลง basis ให้ตรงกับสภาพของวัตถุที่ชั่งจริง’",
      w: [
        "นำ potency ไปคูณแทนการหาร (25 × 0.992 × 0.952) ทำให้ได้ API ไม่ครบ",
        "แก้เฉพาะ assay 99.2% ลืมหักน้ำ 4.8%",
        "แก้เฉพาะ water 4.8% ลืมแก้ assay 99.2%",
        "บวกเปอร์เซ็นต์ขาดแบบเส้นตรง (25 × 1.056) เป็นการประมาณที่ไม่ถูกต้องตามหลักคณิตศาสตร์",
        "ถูก — 25.0 ÷ (0.992 × 0.952) = 25.0 ÷ 0.9444 = 26.47 kg",
      ],
      k: "Potency as-is = assay(anhydrous) × (1 − %water/100); ปริมาณชั่ง = ปริมาณที่ต้องการ ÷ potency as-is",
      d: "medium",
      ref: "Ansel's Pharmaceutical Calculations 15th ed.; USP <921> Water Determination",
      c: [
        "Potency as-is = 0.992 × (1 − 0.048) = 0.992 × 0.952 = 0.9444",
        "ปริมาณชั่ง = 25.0 kg ÷ 0.9444 = 26.47 kg",
      ],
    },
    {
      t: "Sample RSD of tablet weights",
      p: "IPC ระหว่างตอกยาเม็ดสุ่มชั่ง 5 เม็ดได้น้ำหนัก 248, 252, 250, 255 และ 245 mg ค่า relative standard deviation (%RSD) โดยใช้ sample standard deviation (n − 1) ใกล้เคียงข้อใด",
      o: ["0.30%", "1.36%", "1.52%", "4.00%", "5.80%"],
      a: 2,
      r: "Mean = 1,250/5 = 250 mg ผลรวมกำลังสองของส่วนเบี่ยงเบน = 4 + 4 + 0 + 25 + 25 = 58 จากนั้น sample variance = 58/(5−1) = 14.5 และ SD = √14.5 = 3.81 mg\n\n%RSD = 3.81/250 × 100 = 1.52% ในงาน QC ใช้ sample SD (n − 1) เพราะเป็นการประมาณค่าความแปรปรวนของประชากรจากตัวอย่าง (Bessel's correction) หากใช้ n จะได้ค่าต่ำเกินจริง (1.36%) โดยเฉพาะเมื่อ n น้อย",
      w: [
        "หาร RSD ด้วย n อีกครั้ง (คล้าย standard error) ไม่ใช่ RSD",
        "ใช้ population SD (หารด้วย n = 5) ทำให้ค่าต่ำกว่าความจริง",
        "ถูก — SD = √(58/4) = 3.81 mg; RSD = 3.81/250 × 100 = 1.52%",
        "เป็น range/mean (10/250) ไม่ใช่ RSD",
        "นำ variance (14.5) ไปหารด้วย mean แทน SD",
      ],
      k: "%RSD = (sample SD / mean) × 100 โดย sample SD ใช้ n − 1 ในตัวหาร",
      d: "medium",
      ref: "USP <1010> Analytical Data—Interpretation and Treatment",
      c: [
        "Mean = (248+252+250+255+245)/5 = 1,250/5 = 250 mg",
        "Σ(x − mean)² = 4 + 4 + 0 + 25 + 25 = 58",
        "SD = √(58/4) = √14.5 = 3.81 mg",
        "%RSD = 3.81/250 × 100 = 1.52%",
      ],
    },
    {
      t: "Square-root-of-N-plus-one sampling",
      p: "คลังรับ lactose monohydrate จาก supplier ที่ผ่านการรับรอง (qualified) 1 lot จำนวน 70 ถุง (containers) ตามแผน sampling แบบ √N + 1 ต้องเปิดเก็บตัวอย่างจากกี่ container",
      o: ["8", "9", "10", "11", "70"],
      a: 2,
      r: "สูตร n = √N + 1 ใช้กับวัตถุดิบที่มาจาก supplier ที่เชื่อถือได้และ lot เป็นเนื้อเดียวกัน: √70 = 8.37; 8.37 + 1 = 9.37 ปัดขึ้นเป็นจำนวนเต็มถัดไป = 10 containers\n\nWHO guideline กำหนดให้ปัดขึ้น (round up) เสมอ เพื่อไม่ให้ขนาดตัวอย่างต่ำกว่าแผน นอกจากนี้ PIC/S Annex 8 ยังกำหนดว่าการทดสอบ identity ควรทำจากทุก container เว้นแต่มีการ validate ขั้นตอนที่ลดได้ ดังนั้น √N + 1 เป็นแผนสำหรับ composite/full testing ไม่ได้ยกเว้น identity check",
      w: [
        "ใช้เพียง √70 แล้วปัดลง ลืม +1",
        "ปัด 9.37 ลงเป็น 9 ซึ่งขัดกับหลักการปัดขึ้น",
        "ถูก — √70 + 1 = 9.37 → ปัดขึ้นเป็น 10 containers",
        "ปัดขึ้นสองครั้ง (√70 ≈ 9 แล้ว +1 แล้วปัดอีก) เกินกว่าแผน",
        "การเปิดทุก container เป็นแนวทางของ identity test ไม่ใช่ขนาดตัวอย่างตามแผน √N + 1",
      ],
      k: "n = √N + 1 แล้วปัดขึ้นเป็นจำนวนเต็มเสมอ; identity test ยังต้องทำทุก container ตาม Annex 8 (เว้นแต่ validate แล้ว)",
      d: "medium",
      ref: "WHO TRS 929 Annex 4 (Guidelines for sampling of pharmaceutical products); PIC/S GMP Annex 8",
      c: ["√70 = 8.37", "n = 8.37 + 1 = 9.37", "ปัดขึ้น → 10 containers"],
    },
    {
      t: "Process capability index Cpk",
      p: "ผลการวิเคราะห์ assay ของยาเม็ด 30 batches ล่าสุดมี mean 101.2% LC และ SD 1.1% (process อยู่ใน statistical control) specification 95.0–105.0% LC ค่า Cpk ของกระบวนการเท่าใด",
      o: ["0.58", "1.15", "1.52", "1.88", "3.45"],
      a: 1,
      r: "Cpk = min[(USL − mean)/3σ, (mean − LSL)/3σ] แสดงความสามารถของกระบวนการที่คำนึงถึงตำแหน่งของ mean\n\nCPU = (105.0 − 101.2)/(3 × 1.1) = 3.8/3.3 = 1.15; CPL = (101.2 − 95.0)/3.3 = 1.88 → Cpk = 1.15 ขณะที่ Cp = (105 − 95)/(6 × 1.1) = 1.52 ความต่างระหว่าง Cp และ Cpk บอกว่ากระบวนการ off-center ไปทาง USL หากปรับ mean เข้ากลาง (100%) จะได้ Cpk ใกล้ Cp ค่า Cpk < 1.33 มักถือว่ายังไม่ capable เพียงพอสำหรับ critical quality attribute",
      w: [
        "ใช้ 6σ ในตัวหารของ CPU (3.8/6.6) ซึ่งผิดสูตร",
        "ถูก — Cpk = min(1.15, 1.88) = 1.15",
        "เป็นค่า Cp ซึ่งไม่คำนึงถึงตำแหน่ง mean",
        "เป็น CPL ซึ่งเป็นด้านที่ห่างจาก spec มากกว่า ต้องเลือกค่าต่ำสุด",
        "ไม่ได้หารด้วย 3 (3.8/1.1) เป็นระยะห่างในหน่วย σ ไม่ใช่ Cpk",
      ],
      k: "Cpk = ค่าน้อยกว่าระหว่าง (USL−x̄)/3σ และ (x̄−LSL)/3σ; Cp > Cpk แปลว่า process ไม่อยู่กลาง spec",
      d: "medium",
      ref: "Montgomery, Introduction to Statistical Quality Control 8th ed., Ch.8 (Process Capability)",
      c: [
        "CPU = (105.0 − 101.2)/(3 × 1.1) = 3.8/3.3 = 1.15",
        "CPL = (101.2 − 95.0)/(3 × 1.1) = 6.2/3.3 = 1.88",
        "Cpk = min(1.15, 1.88) = 1.15",
      ],
    },
    {
      t: "Water removal during granule drying",
      p: "Wet granules จาก high-shear granulator มีน้ำหนัก 120 kg และวัด LOD ได้ 22% (wet basis) ต้องการทำให้แห้งใน fluid bed dryer จนได้ LOD 2.5% (wet basis) จะต้องระเหยน้ำออกประมาณกี่ kg",
      o: ["23.4 kg", "24.0 kg", "26.4 kg", "93.6 kg", "96.0 kg"],
      a: 1,
      r: "LOD (wet basis) = น้ำ ÷ น้ำหนักรวม ดังนั้นต้องยึด ‘dry solids’ เป็นค่าคงที่ระหว่างการอบ: dry solids = 120 × (1 − 0.22) = 93.6 kg\n\nน้ำหนักสุดท้ายที่ LOD 2.5% = 93.6 ÷ (1 − 0.025) = 96.0 kg ดังนั้นน้ำที่ต้องระเหย = 120 − 96.0 = 24.0 kg ข้อผิดพลาดที่พบบ่อยคือนำ %LOD มาลบกันตรงๆ (22 − 2.5 = 19.5% ของ 120 kg) ซึ่งผิดเพราะตัวหาร (น้ำหนักรวม) เปลี่ยนไประหว่างการอบ การคำนวณนี้ใช้ประมาณ endpoint และ drying capacity",
      w: [
        "ลบ %LOD ตรงๆ (120 × 0.195) ผิดเพราะ basis ของ LOD เปลี่ยนเมื่อมวลรวมลดลง",
        "ถูก — dry solids 93.6 kg; มวลสุดท้าย 93.6/0.975 = 96.0 kg; น้ำที่ระเหย 120 − 96 = 24.0 kg",
        "เป็นปริมาณน้ำทั้งหมดใน wet granules (ทำให้แห้งสนิท LOD 0%) ไม่ตรงเป้าหมาย 2.5%",
        "เป็นน้ำหนัก dry solids ไม่ใช่น้ำที่ระเหย",
        "เป็นน้ำหนัก granules หลังอบแห้ง ไม่ใช่น้ำที่ระเหย",
      ],
      k: "ยึด dry solids คงที่: มวลสุดท้าย = มวลเปียก × (1 − LOD₁) ÷ (1 − LOD₂); น้ำที่ระเหย = มวลเปียก − มวลสุดท้าย",
      d: "hard",
      ref: "Aulton's Pharmaceutics 6th ed. (Drying chapter); USP <731> Loss on Drying",
      c: [
        "Dry solids = 120 × (1 − 0.22) = 93.6 kg",
        "มวลที่ LOD 2.5% = 93.6 ÷ 0.975 = 96.0 kg",
        "น้ำที่ระเหย = 120 − 96.0 = 24.0 kg",
      ],
    },
    {
      t: "Western Electric run rule",
      p: "X̄-chart ของน้ำหนักยาเม็ด (subgroup n = 5) มี control limits ที่คำนวณจาก Phase I ข้อมูล 9 subgroups ล่าสุดทุกจุดอยู่เหนือ center line โดยอยู่ระหว่าง center line ถึง +2σ ไม่มีจุดใดเกิน control limits และทุกเม็ดผ่าน specification ข้อสรุปและการดำเนินการใดเหมาะสมที่สุด",
      o: [
        "เป็น special-cause signal (≥ 8 จุดติดกันด้านเดียวของ center line) ควรสอบสวนหาสาเหตุ process shift แม้ยังอยู่ใน control limits",
        "Process อยู่ใน statistical control เพราะไม่มีจุดใดเกิน ±3σ จึงไม่ต้องดำเนินการใด",
        "ควรคำนวณ control limits ใหม่ทันทีโดยรวม 9 จุดล่าสุด เพื่อให้ center line สะท้อนระดับปัจจุบัน",
        "เป็น common-cause variation เพราะทุกจุดอยู่ใน zone B/C และยังผ่าน specification",
        "ควรปรับตั้งเครื่องลดน้ำหนักทุกครั้งที่จุดอยู่เหนือ center line เพื่อชดเชยทันที",
      ],
      a: 0,
      r: "Western Electric/Nelson rules ใช้ตรวจ non-random pattern นอกเหนือจากจุดที่เกิน 3σ: Rule 1 = 1 จุดเกิน 3σ, Rule 2 = 2 ใน 3 จุดเกิน 2σ ด้านเดียว, Rule 3 = 4 ใน 5 จุดเกิน 1σ ด้านเดียว, Rule 4 = 8 จุดติดกันด้านเดียวของ center line (Nelson ใช้ 9 จุด)\n\nความน่าจะเป็นที่จุด 8–9 จุดอยู่ด้านเดียวกันโดยบังเอิญเพียง ~0.4% (0.5^8) จึงบ่งชี้ว่าค่าเฉลี่ยขยับ (เช่น fill depth drift, granule density เปลี่ยน) ต้องหา assignable cause ก่อน ไม่ควรคำนวณ limits ใหม่จากข้อมูลที่มี special cause และไม่ควร tamper ทีละจุด เพราะจะเพิ่มความแปรปรวน ข้อสำคัญ: control limits สะท้อน ‘เสียงของกระบวนการ’ ส่วน spec คือ ‘เสียงของลูกค้า’ การผ่าน spec จึงไม่ได้แปลว่ากระบวนการ in control",
      w: [
        "ถูก — run ≥ 8 (หรือ 9 ตาม Nelson) จุดด้านเดียวเป็น special-cause signal ต้องสอบสวนหา process shift",
        "ดูเฉพาะ Rule 1 ละเลย run rules ที่ไวต่อการเลื่อนของ mean ขนาดเล็ก",
        "การคำนวณ limits ใหม่จากข้อมูลที่มี special cause จะกลบปัญหา ต้องหาสาเหตุและแก้ก่อน",
        "Pattern ที่ไม่สุ่มไม่ใช่ common cause; การผ่าน spec ไม่เกี่ยวกับ statistical control",
        "การปรับเครื่องทุกจุด (tampering/over-adjustment) จะเพิ่ม variation ตามการทดลอง funnel ของ Deming",
      ],
      k: "Spec ผ่าน ≠ in control; run 8–9 จุดด้านเดียวของ CL = special cause ต้องสอบสวน ไม่ใช่ปรับ limits หรือ tamper",
      d: "hard",
      ref: "Western Electric Statistical Quality Control Handbook (1956); Montgomery, Introduction to Statistical Quality Control 8th ed., Ch.6",
    },
    {
      t: "2x2 factorial main effect calculation",
      p: "การศึกษา 2² full factorial ของ wet granulation: Factor A = ปริมาณน้ำ granulating fluid (ต่ำ/สูง), Factor B = impeller speed (ต่ำ/สูง) ผล % dissolution ที่ 30 นาที: A−B− = 72%, A+B− = 80%, A−B+ = 76%, A+B+ = 90% Main effect ของ factor A เท่ากับเท่าใด",
      o: ["3.0%", "5.5%", "7.0%", "11.0%", "22.0%"],
      a: 3,
      r: "Main effect ของ factor = ค่าเฉลี่ยของ response ที่ระดับสูง − ค่าเฉลี่ยที่ระดับต่ำ (เฉลี่ยข้ามระดับของ factor อื่น)\n\nA: (80 + 90)/2 − (72 + 76)/2 = 85 − 74 = 11.0% ส่วน B = (76 + 90)/2 − (72 + 80)/2 = 7.0% และ interaction AB = (72 + 90)/2 − (80 + 76)/2 = 3.0% ค่า 5.5 คือ regression coefficient (effect/2) ใน coded model (−1/+1) ซึ่งต่างจาก ‘effect’ ระวังสับสนในการตีความผล DOE",
      w: [
        "เป็น interaction effect AB ไม่ใช่ main effect ของ A",
        "เป็น coded regression coefficient (effect ÷ 2) ไม่ใช่ effect",
        "เป็น main effect ของ factor B",
        "ถูก — (80 + 90)/2 − (72 + 76)/2 = 85 − 74 = 11.0%",
        "เป็นผลต่างของผลรวมโดยไม่หารด้วยจำนวน run ในแต่ละระดับ (170 − 148)",
      ],
      k: "Effect = x̄(+) − x̄(−); coefficient ใน coded model = effect/2",
      d: "hard",
      ref: "Montgomery, Design and Analysis of Experiments 9th ed., Ch.6 (2^k factorial); ICH Q8(R2)",
      c: [
        "x̄(A+) = (80 + 90)/2 = 85",
        "x̄(A−) = (72 + 76)/2 = 74",
        "Main effect A = 85 − 74 = 11.0%",
      ],
    },
  ],
];
