import type { Ip1MockDomainContent } from "@/lib/ip1-mock/types";

export const CALC: Ip1MockDomainContent = [
  // Mock Set 1 — การคำนวณและสถิติในการผลิต
  [
    {
      t: "Master formula batch scaling",
      p: "Master formula ของยาเม็ด paracetamol ระบุสูตรต่อ 1,000 เม็ดดังนี้: paracetamol 500 g, microcrystalline cellulose 120 g, PVP K30 15 g, croscarmellose sodium 20 g และ magnesium stearate 5 g หากต้องผลิต batch ขนาด 250,000 เม็ด ต้องเตรียม PVP K30 กี่ kg",
      o: ["0.375 kg", "1.5 kg", "3.75 kg", "15 kg", "37.5 kg"],
      a: 2,
      r: "การขยายสูตร (batch scaling) จาก master formula ใช้ scale factor = batch size ที่ต้องการ ÷ batch size ของสูตรอ้างอิง โดยคูณทุกส่วนประกอบด้วย factor เดียวกันเพื่อรักษาสัดส่วนสูตร\n\nScale factor = 250,000/1,000 = 250 ดังนั้น PVP K30 = 15 g × 250 = 3,750 g = 3.75 kg จุดที่มักพลาดคือการแปลงหน่วย g → kg (หาร 1,000) และการนับเลขศูนย์ของ batch size ผิด",
      w: [
        "ผิดหลักทศนิยม 1 ตำแหน่ง (เหมือนใช้ factor 25 แทน 250)",
        "ไม่ใช่ — เป็นตัวเลขที่ไม่มีที่มาจากสัดส่วนสูตร อาจเกิดจากคิด 15 g × 100",
        "ถูก — 15 g × (250,000/1,000) = 3,750 g = 3.75 kg",
        "เป็นการใช้ 15 g ต่อ 1,000 เม็ดแล้วคูณ 1,000 (นับ batch เป็น 1,000,000 เม็ด) ทำให้มากเกินจริง 4 เท่า",
        "ผิดหลักทศนิยม 1 ตำแหน่ง (คูณ 2,500 แทน 250)",
      ],
      k: "Scale factor = batch ที่ต้องการ ÷ batch ในสูตรอ้างอิง แล้วคูณทุกส่วนประกอบเท่ากัน ระวังการแปลงหน่วย",
      d: "easy",
      ref: "PIC/S GMP Guide PE 009 Part I Ch.4 (Manufacturing Formula and Processing Instructions)",
      c: ["Scale factor = 250,000 ÷ 1,000 = 250", "PVP K30 = 15 g × 250 = 3,750 g", "3,750 g ÷ 1,000 = 3.75 kg"],
    },
    {
      t: "Actual yield percentage",
      p: "Batch ยาเม็ด 200,000 เม็ด น้ำหนักเม็ด 300 mg (theoretical yield = 60.0 kg) เมื่อสิ้นสุดการตอก ได้ยาเม็ดที่ผ่านเกณฑ์ 57.3 kg, เก็บตัวอย่าง QC 0.3 kg และยาเม็ด reject 1.2 kg ค่า actual yield (%) ของยาเม็ดที่ผ่านเกณฑ์เท่าใด",
      o: ["93.5%", "95.5%", "96.0%", "97.4%", "98.0%"],
      a: 1,
      r: "Actual yield (%) = ปริมาณผลผลิตที่ได้จริง ÷ theoretical yield × 100 โดย theoretical yield คำนวณจากปริมาณที่ควรได้หากไม่มีการสูญเสีย (200,000 × 300 mg = 60.0 kg)\n\nดังนั้น yield = 57.3/60.0 × 100 = 95.5% ส่วนค่า 98.0% คือ accountability/reconciliation ((57.3+0.3+1.2)/60.0) ซึ่งใช้ตรวจว่ามวลสารถูกติดตามครบหรือไม่ ทั้งสองค่าต้องอยู่ในช่วงที่ validate ไว้ใน batch record หากนอกช่วงต้องสอบสวนตาม 21 CFR 211.192",
      w: [
        "เป็นการหัก reject ออกซ้ำจากยาเม็ดดี ((57.3−1.2)/60) ไม่มีหลักการรองรับ",
        "ถูก — 57.3/60.0 × 100 = 95.5%",
        "รวมตัวอย่าง QC เข้ากับยาเม็ดดี ((57.3+0.3)/60) ซึ่งไม่ใช่ yield ของผลผลิตที่จำหน่ายได้",
        "ใช้ผลรวมที่ติดตามได้ (58.8 kg) เป็นตัวหารแทน theoretical yield จึงผิดนิยาม",
        "เป็นค่า accountability (57.3+0.3+1.2 = 58.8 kg; 98.0%) ไม่ใช่ actual yield",
      ],
      k: "Yield = ผลผลิตที่ดี ÷ theoretical × 100; accountability = (ผลผลิต + ตัวอย่าง + reject + loss ที่ระบุได้) ÷ theoretical × 100",
      d: "easy",
      ref: "21 CFR 211.103 Calculation of yield; PIC/S GMP Guide PE 009 Part I Ch.5",
      c: [
        "Theoretical yield = 200,000 × 300 mg = 60,000,000 mg = 60.0 kg",
        "Actual yield = 57.3 / 60.0 × 100 = 95.5%",
        "(เปรียบเทียบ) Accountability = (57.3 + 0.3 + 1.2)/60.0 × 100 = 98.0%",
      ],
    },
    {
      t: "Overage with potency adjustment",
      p: "ยาเม็ด vitamin C label claim 100 mg/เม็ด บริษัทกำหนด manufacturing overage 7.5% (เติมเพิ่มจาก label claim เพื่อชดเชยการสลายตัวที่พิสูจน์แล้ว) วัตถุดิบ ascorbic acid lot ที่ใช้มี assay 98.0% (as-is) หากผลิต 400,000 เม็ด ต้องชั่ง ascorbic acid lot นี้ประมาณกี่ kg",
      o: ["40.00 kg", "40.82 kg", "43.00 kg", "43.88 kg", "44.13 kg"],
      a: 3,
      r: "Overage คิดเป็นเปอร์เซ็นต์เพิ่มจาก label claim: ปริมาณเป้าหมายต่อเม็ด = 100 × 1.075 = 107.5 mg (สาร 100%) จากนั้นแก้ potency ของวัตถุดิบโดยหารด้วย 0.980 ได้ 109.69 mg/เม็ด × 400,000 เม็ด = 43.88 kg\n\nICH Q8(R2) ระบุว่า overage ต้องมีเหตุผลรองรับ (เช่น ชดเชยการสูญเสียในกระบวนการผลิตหรือการสลายตัว) และต้องระบุใน dossier ไม่ควรใช้ overage เพื่อยืด shelf life โดยไม่มีข้อมูล ลำดับการคิด: label claim → บวก overage → หารด้วย potency → คูณจำนวนเม็ด",
      w: [
        "ไม่ได้คิดทั้ง overage และ potency (100 mg × 400,000)",
        "แก้เฉพาะ potency (100/0.98 × 400,000) ลืม overage 7.5%",
        "คิดเฉพาะ overage (107.5 mg × 400,000) ลืมแก้ potency 98.0%",
        "ถูก — 100 × 1.075 ÷ 0.980 = 109.69 mg/เม็ด × 400,000 = 43.88 kg",
        "ตีความ overage ผิดเป็นการหาร (100/0.925) ทำให้ได้ปริมาณเกินกว่าที่กำหนด",
      ],
      k: "ปริมาณชั่ง = label claim × (1 + %overage) ÷ potency (เศษส่วน) × จำนวนหน่วย",
      d: "medium",
      ref: "ICH Q8(R2) Pharmaceutical Development, section 2.2.1 (Overages)",
      c: [
        "เป้าหมายต่อเม็ด = 100 mg × 1.075 = 107.5 mg (pure)",
        "แก้ potency = 107.5 ÷ 0.980 = 109.69 mg ของวัตถุดิบ/เม็ด",
        "ทั้ง batch = 109.69 mg × 400,000 = 43,877,551 mg ≈ 43.88 kg",
      ],
    },
    {
      t: "Anhydrous-basis potency weighing",
      p: "Certificate of Analysis ของ API ระบุ assay 99.2% on anhydrous basis และ water content (KF) 4.8% สูตรการผลิตกำหนดให้ใช้ API (คิดเป็น 100% anhydrous) 25.0 kg ต่อ batch ต้องชั่ง API lot นี้ (as-is) ประมาณกี่ kg",
      o: ["23.61 kg", "25.20 kg", "26.26 kg", "26.40 kg", "26.47 kg"],
      a: 4,
      r: "เมื่อ assay รายงานบน anhydrous basis ต้องแปลงเป็น as-is ก่อน: potency as-is = assay(anhydrous) × (1 − water fraction) = 0.992 × 0.952 = 0.9444 (94.44%)\n\nปริมาณชั่ง = 25.0 ÷ 0.9444 = 26.47 kg การบวกเปอร์เซ็นต์รวมกัน (100 + 0.8 + 4.8 = 105.6%) เป็นการประมาณที่ผิดเล็กน้อยแต่ในงาน GMP ต้องใช้สูตรที่ถูกต้องเพราะ error สะสมใน batch ใหญ่ หลักคือ ‘แปลง basis ให้ตรงกับสภาพของวัตถุที่ชั่งจริง’",
      w: [
        "นำ potency ไปคูณแทนการหาร (25 × 0.992 × 0.952) ทำให้ได้ API ไม่ครบ",
        "แก้เฉพาะ assay 99.2% ลืมหักน้ำ 4.8%",
        "แก้เฉพาะ water 4.8% ลืมแก้ assay 99.2%",
        "บวกเปอร์เซ็นต์ขาดแบบเส้นตรง (25 × 1.056) เป็นการประมาณที่ไม่ถูกต้องตามหลักคณิตศาสตร์",
        "ถูก — 25.0 ÷ (0.992 × 0.952) = 25.0 ÷ 0.9444 = 26.47 kg",
      ],
      k: "Potency as-is = assay(anhydrous) × (1 − %water/100); ปริมาณชั่ง = ปริมาณที่ต้องการ ÷ potency as-is",
      d: "medium",
      ref: "Ansel's Pharmaceutical Calculations 15th ed.; USP <921> Water Determination",
      c: [
        "Potency as-is = 0.992 × (1 − 0.048) = 0.992 × 0.952 = 0.9444",
        "ปริมาณชั่ง = 25.0 kg ÷ 0.9444 = 26.47 kg",
      ],
    },
    {
      t: "Sample RSD of tablet weights",
      p: "IPC ระหว่างตอกยาเม็ดสุ่มชั่ง 5 เม็ดได้น้ำหนัก 248, 252, 250, 255 และ 245 mg ค่า relative standard deviation (%RSD) โดยใช้ sample standard deviation (n − 1) ใกล้เคียงข้อใด",
      o: ["0.30%", "1.36%", "1.52%", "4.00%", "5.80%"],
      a: 2,
      r: "Mean = 1,250/5 = 250 mg ผลรวมกำลังสองของส่วนเบี่ยงเบน = 4 + 4 + 0 + 25 + 25 = 58 จากนั้น sample variance = 58/(5−1) = 14.5 และ SD = √14.5 = 3.81 mg\n\n%RSD = 3.81/250 × 100 = 1.52% ในงาน QC ใช้ sample SD (n − 1) เพราะเป็นการประมาณค่าความแปรปรวนของประชากรจากตัวอย่าง (Bessel's correction) หากใช้ n จะได้ค่าต่ำเกินจริง (1.36%) โดยเฉพาะเมื่อ n น้อย",
      w: [
        "หาร RSD ด้วย n อีกครั้ง (คล้าย standard error) ไม่ใช่ RSD",
        "ใช้ population SD (หารด้วย n = 5) ทำให้ค่าต่ำกว่าความจริง",
        "ถูก — SD = √(58/4) = 3.81 mg; RSD = 3.81/250 × 100 = 1.52%",
        "เป็น range/mean (10/250) ไม่ใช่ RSD",
        "นำ variance (14.5) ไปหารด้วย mean แทน SD",
      ],
      k: "%RSD = (sample SD / mean) × 100 โดย sample SD ใช้ n − 1 ในตัวหาร",
      d: "medium",
      ref: "USP <1010> Analytical Data—Interpretation and Treatment",
      c: [
        "Mean = (248+252+250+255+245)/5 = 1,250/5 = 250 mg",
        "Σ(x − mean)² = 4 + 4 + 0 + 25 + 25 = 58",
        "SD = √(58/4) = √14.5 = 3.81 mg",
        "%RSD = 3.81/250 × 100 = 1.52%",
      ],
    },
    {
      t: "Square-root-of-N-plus-one sampling",
      p: "คลังรับ lactose monohydrate จาก supplier ที่ผ่านการรับรอง (qualified) 1 lot จำนวน 70 ถุง (containers) ตามแผน sampling แบบ √N + 1 ต้องเปิดเก็บตัวอย่างจากกี่ container",
      o: ["8", "9", "10", "11", "70"],
      a: 2,
      r: "สูตร n = √N + 1 ใช้กับวัตถุดิบที่มาจาก supplier ที่เชื่อถือได้และ lot เป็นเนื้อเดียวกัน: √70 = 8.37; 8.37 + 1 = 9.37 ปัดขึ้นเป็นจำนวนเต็มถัดไป = 10 containers\n\nWHO guideline กำหนดให้ปัดขึ้น (round up) เสมอ เพื่อไม่ให้ขนาดตัวอย่างต่ำกว่าแผน นอกจากนี้ PIC/S Annex 8 ยังกำหนดว่าการทดสอบ identity ควรทำจากทุก container เว้นแต่มีการ validate ขั้นตอนที่ลดได้ ดังนั้น √N + 1 เป็นแผนสำหรับ composite/full testing ไม่ได้ยกเว้น identity check",
      w: [
        "ใช้เพียง √70 แล้วปัดลง ลืม +1",
        "ปัด 9.37 ลงเป็น 9 ซึ่งขัดกับหลักการปัดขึ้น",
        "ถูก — √70 + 1 = 9.37 → ปัดขึ้นเป็น 10 containers",
        "ปัดขึ้นสองครั้ง (√70 ≈ 9 แล้ว +1 แล้วปัดอีก) เกินกว่าแผน",
        "การเปิดทุก container เป็นแนวทางของ identity test ไม่ใช่ขนาดตัวอย่างตามแผน √N + 1",
      ],
      k: "n = √N + 1 แล้วปัดขึ้นเป็นจำนวนเต็มเสมอ; identity test ยังต้องทำทุก container ตาม Annex 8 (เว้นแต่ validate แล้ว)",
      d: "medium",
      ref: "WHO TRS 929 Annex 4 (Guidelines for sampling of pharmaceutical products); PIC/S GMP Annex 8",
      c: ["√70 = 8.37", "n = 8.37 + 1 = 9.37", "ปัดขึ้น → 10 containers"],
    },
    {
      t: "Process capability index Cpk",
      p: "ผลการวิเคราะห์ assay ของยาเม็ด 30 batches ล่าสุดมี mean 101.2% LC และ SD 1.1% (process อยู่ใน statistical control) specification 95.0–105.0% LC ค่า Cpk ของกระบวนการเท่าใด",
      o: ["0.58", "1.15", "1.52", "1.88", "3.45"],
      a: 1,
      r: "Cpk = min[(USL − mean)/3σ, (mean − LSL)/3σ] แสดงความสามารถของกระบวนการที่คำนึงถึงตำแหน่งของ mean\n\nCPU = (105.0 − 101.2)/(3 × 1.1) = 3.8/3.3 = 1.15; CPL = (101.2 − 95.0)/3.3 = 1.88 → Cpk = 1.15 ขณะที่ Cp = (105 − 95)/(6 × 1.1) = 1.52 ความต่างระหว่าง Cp และ Cpk บอกว่ากระบวนการ off-center ไปทาง USL หากปรับ mean เข้ากลาง (100%) จะได้ Cpk ใกล้ Cp ค่า Cpk < 1.33 มักถือว่ายังไม่ capable เพียงพอสำหรับ critical quality attribute",
      w: [
        "ใช้ 6σ ในตัวหารของ CPU (3.8/6.6) ซึ่งผิดสูตร",
        "ถูก — Cpk = min(1.15, 1.88) = 1.15",
        "เป็นค่า Cp ซึ่งไม่คำนึงถึงตำแหน่ง mean",
        "เป็น CPL ซึ่งเป็นด้านที่ห่างจาก spec มากกว่า ต้องเลือกค่าต่ำสุด",
        "ไม่ได้หารด้วย 3 (3.8/1.1) เป็นระยะห่างในหน่วย σ ไม่ใช่ Cpk",
      ],
      k: "Cpk = ค่าน้อยกว่าระหว่าง (USL−x̄)/3σ และ (x̄−LSL)/3σ; Cp > Cpk แปลว่า process ไม่อยู่กลาง spec",
      d: "medium",
      ref: "Montgomery, Introduction to Statistical Quality Control 8th ed., Ch.8 (Process Capability)",
      c: [
        "CPU = (105.0 − 101.2)/(3 × 1.1) = 3.8/3.3 = 1.15",
        "CPL = (101.2 − 95.0)/(3 × 1.1) = 6.2/3.3 = 1.88",
        "Cpk = min(1.15, 1.88) = 1.15",
      ],
    },
    {
      t: "Water removal during granule drying",
      p: "Wet granules จาก high-shear granulator มีน้ำหนัก 120 kg และวัด LOD ได้ 22% (wet basis) ต้องการทำให้แห้งใน fluid bed dryer จนได้ LOD 2.5% (wet basis) จะต้องระเหยน้ำออกประมาณกี่ kg",
      o: ["23.4 kg", "24.0 kg", "26.4 kg", "93.6 kg", "96.0 kg"],
      a: 1,
      r: "LOD (wet basis) = น้ำ ÷ น้ำหนักรวม ดังนั้นต้องยึด ‘dry solids’ เป็นค่าคงที่ระหว่างการอบ: dry solids = 120 × (1 − 0.22) = 93.6 kg\n\nน้ำหนักสุดท้ายที่ LOD 2.5% = 93.6 ÷ (1 − 0.025) = 96.0 kg ดังนั้นน้ำที่ต้องระเหย = 120 − 96.0 = 24.0 kg ข้อผิดพลาดที่พบบ่อยคือนำ %LOD มาลบกันตรงๆ (22 − 2.5 = 19.5% ของ 120 kg) ซึ่งผิดเพราะตัวหาร (น้ำหนักรวม) เปลี่ยนไประหว่างการอบ การคำนวณนี้ใช้ประมาณ endpoint และ drying capacity",
      w: [
        "ลบ %LOD ตรงๆ (120 × 0.195) ผิดเพราะ basis ของ LOD เปลี่ยนเมื่อมวลรวมลดลง",
        "ถูก — dry solids 93.6 kg; มวลสุดท้าย 93.6/0.975 = 96.0 kg; น้ำที่ระเหย 120 − 96 = 24.0 kg",
        "เป็นปริมาณน้ำทั้งหมดใน wet granules (ทำให้แห้งสนิท LOD 0%) ไม่ตรงเป้าหมาย 2.5%",
        "เป็นน้ำหนัก dry solids ไม่ใช่น้ำที่ระเหย",
        "เป็นน้ำหนัก granules หลังอบแห้ง ไม่ใช่น้ำที่ระเหย",
      ],
      k: "ยึด dry solids คงที่: มวลสุดท้าย = มวลเปียก × (1 − LOD₁) ÷ (1 − LOD₂); น้ำที่ระเหย = มวลเปียก − มวลสุดท้าย",
      d: "hard",
      ref: "Aulton's Pharmaceutics 6th ed. (Drying chapter); USP <731> Loss on Drying",
      c: [
        "Dry solids = 120 × (1 − 0.22) = 93.6 kg",
        "มวลที่ LOD 2.5% = 93.6 ÷ 0.975 = 96.0 kg",
        "น้ำที่ระเหย = 120 − 96.0 = 24.0 kg",
      ],
    },
    {
      t: "Western Electric run rule",
      p: "X̄-chart ของน้ำหนักยาเม็ด (subgroup n = 5) มี control limits ที่คำนวณจาก Phase I ข้อมูล 9 subgroups ล่าสุดทุกจุดอยู่เหนือ center line โดยอยู่ระหว่าง center line ถึง +2σ ไม่มีจุดใดเกิน control limits และทุกเม็ดผ่าน specification ข้อสรุปและการดำเนินการใดเหมาะสมที่สุด",
      o: [
        "เป็น special-cause signal (≥ 8 จุดติดกันด้านเดียวของ center line) ควรสอบสวนหาสาเหตุ process shift แม้ยังอยู่ใน control limits",
        "Process อยู่ใน statistical control เพราะไม่มีจุดใดเกิน ±3σ จึงไม่ต้องดำเนินการใด",
        "ควรคำนวณ control limits ใหม่ทันทีโดยรวม 9 จุดล่าสุด เพื่อให้ center line สะท้อนระดับปัจจุบัน",
        "เป็น common-cause variation เพราะทุกจุดอยู่ใน zone B/C และยังผ่าน specification",
        "ควรปรับตั้งเครื่องลดน้ำหนักทุกครั้งที่จุดอยู่เหนือ center line เพื่อชดเชยทันที",
      ],
      a: 0,
      r: "Western Electric/Nelson rules ใช้ตรวจ non-random pattern นอกเหนือจากจุดที่เกิน 3σ: Rule 1 = 1 จุดเกิน 3σ, Rule 2 = 2 ใน 3 จุดเกิน 2σ ด้านเดียว, Rule 3 = 4 ใน 5 จุดเกิน 1σ ด้านเดียว, Rule 4 = 8 จุดติดกันด้านเดียวของ center line (Nelson ใช้ 9 จุด)\n\nความน่าจะเป็นที่จุด 8–9 จุดอยู่ด้านเดียวกันโดยบังเอิญเพียง ~0.4% (0.5^8) จึงบ่งชี้ว่าค่าเฉลี่ยขยับ (เช่น fill depth drift, granule density เปลี่ยน) ต้องหา assignable cause ก่อน ไม่ควรคำนวณ limits ใหม่จากข้อมูลที่มี special cause และไม่ควร tamper ทีละจุด เพราะจะเพิ่มความแปรปรวน ข้อสำคัญ: control limits สะท้อน ‘เสียงของกระบวนการ’ ส่วน spec คือ ‘เสียงของลูกค้า’ การผ่าน spec จึงไม่ได้แปลว่ากระบวนการ in control",
      w: [
        "ถูก — run ≥ 8 (หรือ 9 ตาม Nelson) จุดด้านเดียวเป็น special-cause signal ต้องสอบสวนหา process shift",
        "ดูเฉพาะ Rule 1 ละเลย run rules ที่ไวต่อการเลื่อนของ mean ขนาดเล็ก",
        "การคำนวณ limits ใหม่จากข้อมูลที่มี special cause จะกลบปัญหา ต้องหาสาเหตุและแก้ก่อน",
        "Pattern ที่ไม่สุ่มไม่ใช่ common cause; การผ่าน spec ไม่เกี่ยวกับ statistical control",
        "การปรับเครื่องทุกจุด (tampering/over-adjustment) จะเพิ่ม variation ตามการทดลอง funnel ของ Deming",
      ],
      k: "Spec ผ่าน ≠ in control; run 8–9 จุดด้านเดียวของ CL = special cause ต้องสอบสวน ไม่ใช่ปรับ limits หรือ tamper",
      d: "hard",
      ref: "Western Electric Statistical Quality Control Handbook (1956); Montgomery, Introduction to Statistical Quality Control 8th ed., Ch.6",
    },
    {
      t: "2x2 factorial main effect calculation",
      p: "การศึกษา 2² full factorial ของ wet granulation: Factor A = ปริมาณน้ำ granulating fluid (ต่ำ/สูง), Factor B = impeller speed (ต่ำ/สูง) ผล % dissolution ที่ 30 นาที: A−B− = 72%, A+B− = 80%, A−B+ = 76%, A+B+ = 90% Main effect ของ factor A เท่ากับเท่าใด",
      o: ["3.0%", "5.5%", "7.0%", "11.0%", "22.0%"],
      a: 3,
      r: "Main effect ของ factor = ค่าเฉลี่ยของ response ที่ระดับสูง − ค่าเฉลี่ยที่ระดับต่ำ (เฉลี่ยข้ามระดับของ factor อื่น)\n\nA: (80 + 90)/2 − (72 + 76)/2 = 85 − 74 = 11.0% ส่วน B = (76 + 90)/2 − (72 + 80)/2 = 7.0% และ interaction AB = (72 + 90)/2 − (80 + 76)/2 = 3.0% ค่า 5.5 คือ regression coefficient (effect/2) ใน coded model (−1/+1) ซึ่งต่างจาก ‘effect’ ระวังสับสนในการตีความผล DOE",
      w: [
        "เป็น interaction effect AB ไม่ใช่ main effect ของ A",
        "เป็น coded regression coefficient (effect ÷ 2) ไม่ใช่ effect",
        "เป็น main effect ของ factor B",
        "ถูก — (80 + 90)/2 − (72 + 76)/2 = 85 − 74 = 11.0%",
        "เป็นผลต่างของผลรวมโดยไม่หารด้วยจำนวน run ในแต่ละระดับ (170 − 148)",
      ],
      k: "Effect = x̄(+) − x̄(−); coefficient ใน coded model = effect/2",
      d: "hard",
      ref: "Montgomery, Design and Analysis of Experiments 9th ed., Ch.6 (2^k factorial); ICH Q8(R2)",
      c: [
        "x̄(A+) = (80 + 90)/2 = 85",
        "x̄(A−) = (72 + 76)/2 = 74",
        "Main effect A = 85 − 74 = 11.0%",
      ],
    },
  ],
  // Mock Set 2 — การคำนวณและสถิติในการผลิต
  [
    {
      t: "Rotary press batch run time",
      p: "เครื่องตอกยาเม็ดแบบ rotary ชนิด single-sided มี 36 stations ตั้ง turret speed 50 rpm (1 เม็ดต่อ station ต่อรอบ) หาก overall equipment efficiency (เวลาทำงานจริงรวมการหยุดเครื่อง) เท่ากับ 80% การตอก batch 540,000 เม็ดจะใช้เวลาประมาณกี่ชั่วโมง",
      o: ["2.5 h", "4.0 h", "5.0 h", "6.0 h", "6.25 h"],
      a: 4,
      r: "Output เชิงทฤษฎีของ rotary press = จำนวน stations × rpm × จำนวนเม็ดต่อ station ต่อรอบ × 60 = 36 × 50 × 1 × 60 = 108,000 เม็ด/ชั่วโมง\n\nที่ efficiency 80% output จริง = 86,400 เม็ด/ชั่วโมง → 540,000/86,400 = 6.25 ชั่วโมง ประสิทธิภาพต้องนำไป ‘หาร’ เวลาทฤษฎี (5.0/0.8) ไม่ใช่บวกเปอร์เซ็นต์แบบเส้นตรง และต้องตรวจว่าเครื่องเป็น single- หรือ double-sided (double-sided ให้ 2 เม็ดต่อ station ต่อรอบ)",
      w: [
        "สมมติว่าเป็น double-sided press (2 เม็ด/station/รอบ) และไม่คิด efficiency",
        "นำ efficiency ไปคูณเวลา (5.0 × 0.8) ทำให้เวลาสั้นลงซึ่งขัดกับความจริง",
        "เป็นเวลาทฤษฎีที่ efficiency 100% ยังไม่คิดการหยุดเครื่อง",
        "บวก 20% แบบเส้นตรง (5.0 × 1.2) ซึ่งไม่ถูกต้อง เพราะ efficiency ต้องหาร",
        "ถูก — 36 × 50 × 60 = 108,000 เม็ด/h; × 0.8 = 86,400 เม็ด/h; 540,000/86,400 = 6.25 h",
      ],
      k: "Output/h = stations × rpm × 60 × (เม็ด/station/รอบ); เวลาจริง = เวลาทฤษฎี ÷ efficiency",
      d: "easy",
      ref: "Aulton's Pharmaceutics 6th ed. (Tablets and compaction); Lachman/Lieberman's The Theory and Practice of Industrial Pharmacy 4th ed.",
      c: [
        "Output ทฤษฎี = 36 × 50 × 60 = 108,000 เม็ด/h",
        "Output จริง = 108,000 × 0.80 = 86,400 เม็ด/h",
        "เวลา = 540,000 ÷ 86,400 = 6.25 h",
      ],
    },
    {
      t: "Full factorial run count with center points",
      p: "ทีมพัฒนาสูตรต้องการคัดกรองผลของ 5 process parameters ใน fluid bed granulation ด้วย 2-level full factorial design (ไม่ทำซ้ำ) และเพิ่ม center points อีก 3 runs เพื่อประเมิน curvature และ pure error จำนวน experimental runs ทั้งหมดเท่าใด",
      o: ["13 runs", "28 runs", "32 runs", "35 runs", "246 runs"],
      a: 3,
      r: "จำนวน run ของ full factorial = (จำนวนระดับ)^(จำนวน factor) = 2^5 = 32 runs บวก center points 3 runs = 35 runs\n\nCenter points ไม่เปลี่ยนการประมาณ main effects/interactions แต่ใช้ตรวจ curvature (ถ้ามี curvature มากควรขยายเป็น response surface design) และให้ค่า pure error สำหรับทดสอบนัยสำคัญ เมื่อ factor มากขึ้น full factorial โตแบบ exponential จึงมักใช้ fractional factorial (เช่น 2^(5−1) = 16 runs) สำหรับ screening",
      w: [
        "ใช้ 2 × 5 + 3 ซึ่งเป็นการคิดแบบเส้นตรง ไม่ใช่ factorial",
        "ใช้ 5² + 3 สลับฐานกับเลขชี้กำลัง",
        "เป็นจำนวน factorial runs ที่ยังไม่รวม center points",
        "ถูก — 2^5 + 3 = 32 + 3 = 35 runs",
        "ใช้ 3^5 + 3 ซึ่งเป็น 3-level factorial ไม่ตรงกับโจทย์",
      ],
      k: "Full factorial = L^k runs (+ center points); 2-level 5 factors = 32 runs",
      d: "easy",
      ref: "Montgomery, Design and Analysis of Experiments 9th ed., Ch.6; ICH Q8(R2) Appendix 2",
      c: ["Factorial runs = 2^5 = 32", "รวม center points = 32 + 3 = 35 runs"],
    },
    {
      t: "Salt-to-base batch quantity",
      p: "ยาเม็ด amlodipine 10 mg (คิดเป็น amlodipine base) ผลิตจาก amlodipine besylate (MW 567.1; MW base 408.9) วัตถุดิบ lot ที่ใช้มี assay 99.5% (as-is) ต้องชั่ง amlodipine besylate ประมาณกี่ kg สำหรับ batch 500,000 เม็ด",
      o: ["3.62 kg", "5.00 kg", "5.03 kg", "6.93 kg", "6.97 kg"],
      a: 4,
      r: "เมื่อ label claim ระบุเป็น base แต่ใช้รูปเกลือ ต้องคูณด้วย salt factor = MW salt / MW base = 567.1/408.9 = 1.387 → besylate ที่ต้องการ = 10 × 1.387 = 13.87 mg ต่อเม็ด (เกลือบริสุทธิ์)\n\nแก้ potency: 13.87/0.995 = 13.94 mg ต่อเม็ด × 500,000 เม็ด = 6.97 kg ขั้นตอนต้องทำทั้งสอง (salt factor และ potency) และระวังกลับเศษส่วน (MW base/MW salt) ซึ่งให้ปริมาณต่ำกว่าจริง ทำให้ยาเม็ดมี base เพียง ~52% ของ label claim",
      w: [
        "กลับ salt factor (คูณ 408.9/567.1) ทำให้ได้ base ไม่ถึง label claim",
        "คิดเป็น base 10 mg × 500,000 โดยไม่แปลงเป็นเกลือและไม่แก้ potency",
        "แก้เฉพาะ potency แต่ลืมแปลงเป็นรูปเกลือ",
        "แปลงเป็นรูปเกลือแล้วแต่ลืมแก้ potency 99.5%",
        "ถูก — 10 × (567.1/408.9) ÷ 0.995 = 13.94 mg/เม็ด × 500,000 = 6.97 kg",
      ],
      k: "ปริมาณเกลือ = dose (base) × MW salt/MW base ÷ potency × จำนวนหน่วย",
      d: "medium",
      ref: "Ansel's Pharmaceutical Calculations 15th ed.; FDA Guidance for Industry: Naming of Drug Products Containing Salt Drug Substances (2015)",
      c: [
        "Salt factor = 567.1 ÷ 408.9 = 1.387",
        "Besylate บริสุทธิ์/เม็ด = 10 × 1.387 = 13.87 mg",
        "แก้ potency = 13.87 ÷ 0.995 = 13.94 mg/เม็ด",
        "Batch = 13.94 mg × 500,000 = 6,969,000 mg ≈ 6.97 kg",
      ],
    },
    {
      t: "Dry-basis moisture to LOD conversion",
      p: "Halogen moisture analyzer ของห้องผลิตรายงาน granule moisture เป็น moisture content (dry basis) = 8.0% แต่ specification ใน batch record กำหนดเป็น LOD (wet basis) ค่าที่ต้องบันทึกเป็น LOD (wet basis) คือเท่าใด",
      o: ["7.36%", "7.41%", "8.00%", "8.64%", "8.70%"],
      a: 1,
      r: "LOD (wet basis) = น้ำ ÷ (น้ำ + ของแข็งแห้ง) × 100 ส่วน MC (dry basis) = น้ำ ÷ ของแข็งแห้ง × 100 สองค่านี้สัมพันธ์กันด้วย LOD = MC/(100 + MC) × 100 และ MC = LOD/(100 − LOD) × 100\n\nMC 8.0% หมายถึงน้ำ 8 g ต่อของแข็งแห้ง 100 g → LOD = 8/108 × 100 = 7.41% ความต่างนี้เล็กเมื่อความชื้นต่ำ แต่สำคัญเมื่อ spec แคบหรือความชื้นสูง (wet granules) ต้องระบุ basis ให้ชัดใน batch record และ method",
      w: [
        "นำ 8% × 0.92 ซึ่งไม่ใช่สูตรแปลง basis",
        "ถูก — LOD = 8.0/(100 + 8.0) × 100 = 7.41%",
        "ไม่ได้แปลง basis — dry basis ≠ wet basis",
        "นำ 8% × 1.08 เป็นการแปลงทิศทางที่ผิดและไม่ใช่สูตรที่ถูก",
        "ใช้ 8/(100 − 8) ซึ่งเป็นการแปลงจาก LOD → MC (ทิศตรงข้าม)",
      ],
      k: "LOD(wet) = MC/(100+MC)×100; MC(dry) = LOD/(100−LOD)×100; MC ≥ LOD เสมอ",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed. (Drying: moisture content definitions); USP <731> Loss on Drying",
      c: ["น้ำ 8.0 g ต่อของแข็งแห้ง 100 g → มวลรวม 108 g", "LOD = 8.0/108 × 100 = 7.41%"],
    },
    {
      t: "Target tablet weight from blend assay",
      p: "สูตรยาเม็ด 200 mg ออกแบบให้ API = 40.0% w/w ของ final blend (น้ำหนักเม็ดเป้าหมาย 500 mg) แต่ผล assay ของ final lubricated blend ที่ผ่าน blend uniformity แล้วได้ API 38.5% w/w (SOP อนุญาตให้ปรับ target weight ตาม blend assay) ควรตั้ง target tablet weight เท่าใด",
      o: ["192.5 mg", "481.3 mg", "500.0 mg", "507.5 mg", "519.5 mg"],
      a: 4,
      r: "Target weight = label claim ÷ สัดส่วน API ใน blend ที่วัดได้จริง = 200 ÷ 0.385 = 519.5 mg\n\nแนวทางนี้ใช้เมื่อ assay ของ blend ต่างจากทฤษฎี (เช่น LOD ของ granules ต่างจากที่ออกแบบ หรือ granule loss ไม่สม่ำเสมอ) โดยต้องอยู่ในช่วงที่ registration/batch record อนุญาต และ blend uniformity ต้องผ่าน การปรับน้ำหนักชดเชยได้เฉพาะ ‘ความเข้มข้นเฉลี่ย’ ไม่ได้แก้ปัญหา content uniformity หาก blend ไม่เป็นเนื้อเดียวกัน",
      w: [
        "เป็นปริมาณ API ในเม็ด 500 mg (500 × 0.385) ไม่ใช่น้ำหนักเม็ด",
        "ใช้อัตราส่วนกลับ (500 × 38.5/40.0) ทำให้เม็ดเบาลงและ API ยิ่งต่ำ",
        "ไม่ได้ปรับ ทำให้แต่ละเม็ดมี API เพียง 192.5 mg (96.25% LC)",
        "บวกส่วนต่าง 1.5 จุดเปอร์เซ็นต์ของน้ำหนักแบบเส้นตรง (500 × 1.015) ไม่ถูกต้อง",
        "ถูก — 200 ÷ 0.385 = 519.5 mg ให้ API 200 mg ต่อเม็ด",
      ],
      k: "Target weight = dose ÷ (fraction API ใน blend ที่ assay จริง); ชดเชยความเข้มข้นเฉลี่ยได้ แต่ไม่ชดเชย non-uniformity",
      d: "medium",
      ref: "Lachman/Lieberman's The Theory and Practice of Industrial Pharmacy 4th ed.; PIC/S GMP Guide PE 009 Part I Ch.4",
      c: ["Target weight = 200 mg ÷ 0.385 = 519.5 mg", "ตรวจสอบ: 519.5 × 0.385 = 200.0 mg API"],
    },
    {
      t: "X-bar chart control limits using A2",
      p: "จัดทำ X̄–R chart ของน้ำหนักยาเม็ดจาก 25 subgroups (subgroup size n = 5) ได้ grand mean = 400.0 mg และ average range (R̄) = 8.0 mg (สำหรับ n = 5: A2 = 0.577, d2 = 2.326, D4 = 2.114) control limits ของ X̄-chart (LCL–UCL) คือข้อใด",
      o: ["376.0–424.0 mg", "383.1–416.9 mg", "389.7–410.3 mg", "395.4–404.6 mg", "397.9–402.1 mg"],
      a: 3,
      r: "X̄-chart limits = X̿ ± A2·R̄ = 400.0 ± 0.577 × 8.0 = 400.0 ± 4.6 → 395.4–404.6 mg A2 รวม 3/(d2√n) ไว้แล้ว (3/(2.326 × √5) = 0.577)\n\nค่า 389.7–410.3 คือ ±3σ ของ ‘น้ำหนักเม็ดเดี่ยว’ (σ = R̄/d2 = 3.44 mg) ซึ่งกว้างกว่าเพราะยังไม่หารด้วย √n ส่วน D4·R̄ = 16.9 mg คือ UCL ของ R-chart ไม่ใช่ X̄-chart ควรตรวจ R-chart ว่า in control ก่อนเสมอ เพราะ X̄ limits อาศัย R̄",
      w: [
        "ใช้ ±3R̄ ซึ่งไม่ใช่สูตร control limit",
        "นำ D4·R̄ (UCL ของ R-chart = 16.9 mg) มาบวกลบกับ mean ผิดชนิด chart",
        "เป็น ±3σ ของค่า individual (σ = R̄/d2) ไม่ได้หาร √n สำหรับค่าเฉลี่ย subgroup",
        "ถูก — 400.0 ± 0.577 × 8.0 = 400.0 ± 4.6 mg",
        "หาร √n ซ้ำซ้อน (A2 รวม √n ไว้แล้ว) ทำให้ limits แคบเกินจริงและเกิด false alarm",
      ],
      k: "X̄-chart: X̿ ± A2R̄; R-chart: D3R̄ ถึง D4R̄; σ̂ = R̄/d2",
      d: "medium",
      ref: "Montgomery, Introduction to Statistical Quality Control 8th ed., Ch.6 (X̄ and R charts); ASTM E2587",
      c: ["A2·R̄ = 0.577 × 8.0 = 4.6 mg", "UCL = 400.0 + 4.6 = 404.6 mg", "LCL = 400.0 − 4.6 = 395.4 mg"],
    },
    {
      t: "AQL single sampling accept/reject decision",
      p: "การตรวจรับ blister ที่ packaging ใช้ ANSI/ASQ Z1.4 single sampling, normal inspection: lot 10,000 แผง, general inspection level II ได้ sample size n = 200 สำหรับ major defect AQL 1.0 มี Ac = 5, Re = 6 ผลตรวจพบ major defects 5 แผง ข้อใดถูกต้องที่สุด",
      o: [
        "ยอมรับ lot เพราะจำนวน defect (5) ไม่เกิน Ac = 5",
        "ปฏิเสธ lot เพราะสัดส่วน defect ในตัวอย่าง 2.5% สูงกว่า AQL 1.0%",
        "ต้องเปลี่ยนเป็น tightened inspection ทันทีและตรวจ lot นี้ใหม่",
        "ต้องตรวจ 100% ของ lot ก่อนตัดสิน เพราะผลเท่ากับ Ac พอดี",
        "ต้องสุ่มตัวอย่างชุดที่สองอีก 200 แผงเพื่อยืนยันผล",
      ],
      a: 0,
      r: "ใน single sampling plan การตัดสินใช้จำนวน defect ในตัวอย่างเทียบกับ Acceptance number (Ac) และ Rejection number (Re) เท่านั้น: d ≤ Ac → accept; d ≥ Re → reject ที่นี่ d = 5 = Ac จึงยอมรับ lot\n\nAQL ไม่ใช่เกณฑ์ที่นำ % defect ในตัวอย่างมาเทียบตรงๆ แต่เป็นระดับคุณภาพของ process average ที่แผนจะยอมรับด้วยความน่าจะเป็นสูง (~95%) ส่วน switching rules (normal → tightened) ใช้เมื่อมี 2 ใน 5 lots ติดกันถูกปฏิเสธ ไม่ได้ใช้จากผลครั้งเดียวที่ยังยอมรับได้ ทั้งนี้ defect ที่พบยังต้องบันทึกและแจ้ง supplier เพื่อ trend",
      w: [
        "ถูก — d = 5 ≤ Ac = 5 จึง accept ตามแผน single sampling",
        "เข้าใจผิดว่าต้องเทียบ % defect ในตัวอย่างกับ AQL โดยตรง",
        "Switching ไป tightened ใช้เมื่อ 2 ใน 5 lots ติดกันถูก reject ไม่ใช่กรณีนี้",
        "ไม่มีข้อกำหนดให้ตรวจ 100% เมื่อ d = Ac; แผนตัดสินชัดเจนแล้ว",
        "การสุ่มชุดที่สองเป็นลักษณะของ double sampling plan ไม่ใช่ single sampling",
      ],
      k: "Single sampling: d ≤ Ac ยอมรับ, d ≥ Re ปฏิเสธ; AQL ไม่ใช่ % defect ที่ใช้เทียบกับตัวอย่างโดยตรง",
      d: "medium",
      ref: "ANSI/ASQ Z1.4-2003 (R2018) Sampling Procedures and Tables for Inspection by Attributes; ISO 2859-1",
    },
    {
      t: "Film-coating suspension quantity",
      p: "เคลือบฟิล์ม tablet cores 150 kg ใน perforated pan ต้องการ weight gain 3.0% (คิดจากน้ำหนัก core) ใช้ coating suspension ที่มี total solids 15% w/w และจากข้อมูล validation coating efficiency = 85% ต้องเตรียม coating suspension อย่างน้อยกี่ kg",
      o: ["5.29 kg", "25.5 kg", "30.0 kg", "34.5 kg", "35.3 kg"],
      a: 4,
      r: "ของแข็งที่ต้องเกาะบนเม็ด = 150 × 0.030 = 4.5 kg เนื่องจาก efficiency 85% (ส่วนที่เหลือสูญเสียเป็น spray drying, เกาะผนัง pan, ออกทาง exhaust) ต้องพ่นของแข็ง = 4.5/0.85 = 5.29 kg\n\nSuspension ที่ต้องใช้ = 5.29/0.15 = 35.3 kg ในทางปฏิบัติมักเตรียมเผื่อ (เช่น 10–15%) สำหรับ dead volume ในสายและการ prime ปืนพ่น efficiency ต้องหาร ไม่ใช่คูณ หรือบวกเปอร์เซ็นต์ที่สูญเสียแบบเส้นตรง",
      w: [
        "เป็นปริมาณของแข็งที่ต้องพ่น ยังไม่ได้แปลงเป็นน้ำหนัก suspension",
        "นำ efficiency ไปคูณ (30.0 × 0.85) ทำให้ได้ suspension ไม่พอ",
        "ไม่ได้คิด coating efficiency (4.5/0.15)",
        "บวก 15% แบบเส้นตรง (30.0 × 1.15) ต่ำกว่าค่าที่ถูกต้องเล็กน้อย",
        "ถูก — 150 × 0.03 = 4.5 kg; ÷ 0.85 = 5.29 kg solids; ÷ 0.15 = 35.3 kg suspension",
      ],
      k: "Suspension = (core weight × %WG) ÷ efficiency ÷ %solids",
      d: "hard",
      ref: "Aulton's Pharmaceutics 6th ed. (Coating of tablets and multiparticulates); Porter, Pharmaceutical Coating Technology",
      c: [
        "Solids ที่ต้องเกาะ = 150 × 0.030 = 4.5 kg",
        "Solids ที่ต้องพ่น = 4.5 ÷ 0.85 = 5.29 kg",
        "Suspension = 5.29 ÷ 0.15 = 35.3 kg",
      ],
    },
    {
      t: "95% confidence interval of mean (t-based)",
      p: "Process validation วัด assay ของยาเม็ดจาก 6 ตำแหน่งตลอด batch ได้ mean 99.4% LC และ sample SD 0.80% กำหนด t(0.975, df = 5) = 2.571, t(0.975, df = 6) = 2.447 และ z(0.975) = 1.96 95% confidence interval ของค่าเฉลี่ย batch คือข้อใด",
      o: ["97.34–101.46%", "98.48–100.32%", "98.56–100.24%", "98.60–100.20%", "98.76–100.04%"],
      a: 2,
      r: "เมื่อ n น้อยและไม่ทราบ σ ของประชากร ใช้ t-distribution ที่ df = n − 1: CI = x̄ ± t × SD/√n\n\nSE = 0.80/√6 = 0.327; ครึ่งความกว้าง = 2.571 × 0.327 = 0.84 → 98.56–100.24% การใช้ z (1.96) ให้ CI แคบเกินจริงเมื่อ n เล็ก การใช้ SD แทน SE ให้ช่วงที่เป็นการประมาณการกระจายของค่าเดี่ยว (คล้าย prediction) ไม่ใช่ CI ของค่าเฉลี่ย CI นี้บอกว่า mean ของ batch น่าจะอยู่ระหว่าง ~98.6–100.2% ด้วยความเชื่อมั่น 95%",
      w: [
        "ใช้ SD แทน standard error (ไม่หาร √n) ทำให้ช่วงกว้างเกินจริง",
        "หารด้วย √(n − 1) แทน √n ผิดสูตร SE",
        "ถูก — 99.4 ± 2.571 × 0.80/√6 = 99.4 ± 0.84",
        "ใช้ df = n (6) แทน n − 1 (5)",
        "ใช้ z = 1.96 ซึ่งไม่เหมาะเมื่อ n = 6 และไม่ทราบ σ",
      ],
      k: "CI ของ mean = x̄ ± t(α/2, n−1) × s/√n; n เล็กใช้ t ไม่ใช่ z",
      d: "hard",
      ref: "USP <1010> Analytical Data—Interpretation and Treatment; Bolton & Bon, Pharmaceutical Statistics 5th ed.",
      c: [
        "SE = 0.80 ÷ √6 = 0.80 ÷ 2.449 = 0.327",
        "Half-width = 2.571 × 0.327 = 0.84",
        "CI = 99.4 ± 0.84 = 98.56–100.24%",
      ],
    },
    {
      t: "Cp versus Cpk off-center diagnosis",
      p: "Content uniformity data (process in statistical control) มี specification 90.0–110.0% LC คำนวณได้ Cp = 1.67 แต่ Cpk = 0.83 ข้อใดสรุปลักษณะกระบวนการและแนวทางแก้ไขได้ถูกต้องที่สุด",
      o: [
        "σ ≈ 2.0% และ mean อยู่ห่าง spec limit ที่ใกล้ที่สุดเพียง ≈ 5.0% ควรแก้ที่ centering ของ mean มากกว่าลด variation",
        "σ ≈ 3.3% ต้องลด variation เป็นหลักเพราะทั้ง Cp และ Cpk บ่งชี้ spread กว้าง",
        "Process capable แล้วเพราะ Cp > 1.33 จึงไม่จำเป็นต้องแก้ไขใด",
        "Cpk ต่ำแปลว่ากระบวนการไม่ stable ต้องคำนวณ control limits ใหม่ก่อน",
        "Mean อยู่ตรงกลาง spec พอดี แต่ data ไม่เป็น normal distribution จึงได้ Cpk ต่ำ",
      ],
      a: 0,
      r: "Cp = (USL − LSL)/6σ → σ = 20/(6 × 1.67) ≈ 2.0% ส่วน Cpk = ระยะจาก mean ถึง spec ที่ใกล้ที่สุด ÷ 3σ → ระยะ = 0.83 × 3 × 2.0 ≈ 5.0% แปลว่า mean อยู่ที่ราว 95% หรือ 105% LC (off-center)\n\nเมื่อ Cp สูงแต่ Cpk ต่ำ ปัญหาหลักคือ centering (เช่น target weight ตั้งผิด, blend potency ต่ำ/สูง) การปรับ mean เข้ากลางจะยก Cpk ขึ้นใกล้ 1.67 ทันทีโดยไม่ต้องลด variation ที่ระยะ 2.5σ จาก spec คาดว่ามีหน่วยนอก spec ~0.6% ซึ่งยอมรับไม่ได้สำหรับ CQA",
      w: [
        "ถูก — Cp บอก spread แคบ (σ ≈ 2.0) แต่ Cpk ต่ำเพราะ mean เลื่อนไปใกล้ spec limit",
        "คำนวณ σ ผิด และ Cp ที่สูงบ่งชี้ว่า spread ไม่ได้กว้าง",
        "Cp ไม่คำนึงถึงตำแหน่ง mean ต้องดู Cpk ซึ่งยังต่ำกว่า 1.0",
        "โจทย์ระบุว่า in control แล้ว; Cpk ต่ำเป็นเรื่อง capability ไม่ใช่ stability",
        "ถ้า mean อยู่ตรงกลาง Cp จะเท่ากับ Cpk; ความต่างนี้บ่งชี้ off-center",
      ],
      k: "Cp สูง + Cpk ต่ำ = process แคบแต่ไม่อยู่กลาง → แก้ centering; Cp ต่ำ = spread กว้าง → ลด variation",
      d: "hard",
      ref: "Montgomery, Introduction to Statistical Quality Control 8th ed., Ch.8; ICH Q10 (process performance monitoring)",
      c: [
        "σ = (110 − 90)/(6 × 1.67) = 20/10.0 ≈ 2.0%",
        "ระยะ mean ถึง spec ที่ใกล้สุด = Cpk × 3σ = 0.83 × 6.0 ≈ 5.0%",
        "Mean ≈ 95.0% หรือ 105.0% LC (off-center)",
      ],
    },
  ],
];
