import type { Ip1MockDomainContent } from "@/lib/ip1-mock/types";

export const LIQUID: Ip1MockDomainContent = [
  // Mock Set 1
  [
    {
      t: "Simple syrup self-preservation",
      p: "Simple Syrup ตามตำรับ USP มีน้ำตาล sucrose 85% w/v ข้อใดอธิบายได้ถูกต้องที่สุดว่าเหตุใดตำรับนี้จึงไม่จำเป็นต้องเติม preservative",
      o: [
        "ความเข้มข้นน้ำตาลสูงทำให้ free water (water activity) ต่ำ จุลินทรีย์เจริญไม่ได้",
        "sucrose มีฤทธิ์ฆ่าเชื้อโดยตรงผ่านการทำลายผนังเซลล์แบคทีเรีย",
        "ความหนืดสูงของ syrup ทำให้จุลินทรีย์เคลื่อนที่ไม่ได้จึงตายไป",
        "pH ของ simple syrup ต่ำกว่า 3 จึงยับยั้งการเจริญของเชื้อ",
        "sucrose ถูก hydrolyze เป็น invert sugar ซึ่งเป็นสารกันเสียที่แรง",
      ],
      a: 0,
      r: "Simple syrup 85% w/v มีน้ำตาลเกือบอิ่มตัว น้ำส่วนใหญ่ถูกใช้ในการละลาย sucrose จึงเหลือ free water น้อยมาก (water activity ต่ำ) และเกิด osmotic pressure สูงที่ดึงน้ำออกจากเซลล์จุลินทรีย์ ตำรับจึงเป็น self-preserving\n\nหากเจือจาง syrup ลง (เช่นผสมกับยาน้ำอื่น) ความเข้มข้นน้ำตาลลดลงจะสูญเสียคุณสมบัตินี้และต้องเติม preservative เช่น parabens หรือ sodium benzoate ข้อควรระวังอีกอย่างคือการระเหยที่ผิวหน้าแล้วหยดน้ำกลั่นตัวกลับ ทำให้ผิวบนเจือจางและขึ้นราได้",
      w: [
        "ถูก — water activity ต่ำและ osmotic pressure สูงทำให้จุลินทรีย์ขาดน้ำและเจริญไม่ได้",
        "sucrose ไม่ใช่สารฆ่าเชื้อโดยตรง ผลยับยั้งเกิดจากผลเชิง osmotic ไม่ใช่การทำลายผนังเซลล์",
        "ความหนืดไม่ได้ฆ่าเชื้อ ยาน้ำหนืดหลายชนิดยังต้องการ preservative",
        "simple syrup มี pH ใกล้เป็นกลาง ไม่ได้ต่ำถึงระดับยับยั้งเชื้อ",
        "invert sugar ไม่ใช่สารกันเสีย และการ hydrolysis ยังทำให้เกิดสีน้ำตาล (caramelization) ได้ง่ายขึ้น",
      ],
      k: "Syrup ใกล้อิ่มตัว (85% w/v) self-preserving เพราะ free water ต่ำ — เจือจางเมื่อไรต้องเติม preservative",
      d: "easy",
      ref: "Remington: The Science and Practice of Pharmacy 22nd ed. (Solutions, Syrups)",
    },
    {
      t: "Stokes' law sedimentation velocity",
      p: "สูตรยาแขวนตะกอนมีอนุภาคยาขนาดเส้นผ่านศูนย์กลาง 20 µm ความหนาแน่น 1.5 g/cm³ กระจายใน vehicle ที่มีความหนาแน่น 1.1 g/cm³ และความหนืด 0.05 Pa·s (50 cP) จงคำนวณความเร็วการตกตะกอนตาม Stokes' law (g = 9.81 m/s²)",
      o: ["0.44 µm/s", "0.87 µm/s", "1.74 µm/s", "3.49 µm/s", "6.98 µm/s"],
      a: 2,
      r: "Stokes' law: v = d²(ρs − ρ0)g / 18η เมื่อ d คือเส้นผ่านศูนย์กลาง ต้องแปลงทุกหน่วยเป็น SI ก่อน คือ d = 20 × 10⁻⁶ m, Δρ = 400 kg/m³, η = 0.05 Pa·s\n\nแทนค่าได้ v ≈ 1.74 × 10⁻⁶ m/s หรือ 1.74 µm/s (ประมาณ 0.63 cm/h) สมการแสดงว่าการลดขนาดอนุภาค การลดผลต่างความหนาแน่น และการเพิ่มความหนืดของ vehicle ช่วยชะลอการตกตะกอน โดยขนาดอนุภาคมีผลมากที่สุดเพราะยกกำลังสอง ทั้งนี้ Stokes' law ใช้ได้กับ dilute suspension ที่อนุภาคทรงกลมไม่ชนกัน",
      w: [
        "ได้ค่านี้หากใช้รัศมี (10 µm) แทนเส้นผ่านศูนย์กลางในสูตรที่ใช้ d ซึ่งทำให้ค่าลดลง 4 เท่า",
        "ค่านี้เป็นครึ่งหนึ่งของคำตอบ เกิดจากการใช้ 36η หรือแทนค่าผิดสัดส่วน",
        "ถูก — v = (20×10⁻⁶)² × 400 × 9.81 / (18 × 0.05) = 1.74 × 10⁻⁶ m/s",
        "ได้ค่านี้หากใช้ 9η แทน 18η (สับสนกับสูตรรัศมี 2r²Δρg/9η แต่แทน d)",
        "ได้ค่านี้หากใช้สูตรรัศมีแต่แทน d ลงไปเป็น r ทำให้ค่าสูงเกิน 4 เท่า",
      ],
      k: "v = d²Δρg/18η (หรือ 2r²Δρg/9η) — ขนาดอนุภาคยกกำลังสองจึงเป็นตัวแปรที่ทรงอิทธิพลที่สุด",
      d: "hard",
      ref: "Aulton's Pharmaceutics 6th ed. (Suspensions); Martin's Physical Pharmacy 7th ed.",
      c: [
        "d² = (20 × 10⁻⁶ m)² = 4.0 × 10⁻¹⁰ m²",
        "Δρ = 1500 − 1100 = 400 kg/m³",
        "ตัวเศษ = 4.0 × 10⁻¹⁰ × 400 × 9.81 = 1.570 × 10⁻⁶",
        "ตัวส่วน = 18 × 0.05 = 0.9",
        "v = 1.570 × 10⁻⁶ / 0.9 = 1.74 × 10⁻⁶ m/s = 1.74 µm/s",
      ],
    },
    {
      t: "Sedimentation volume F",
      p: "ในการพัฒนาสูตรยาแขวนตะกอน เทยาแขวนตะกอน 50 mL ลงกระบอกตวงแล้วตั้งทิ้งไว้ เมื่อเข้าสู่สมดุลพบว่าชั้นตะกอนมีปริมาตร 35 mL ค่า sedimentation volume (F) ของสูตรนี้เท่ากับเท่าใด",
      o: ["0.30", "0.70", "1.00", "1.43", "1.70"],
      a: 1,
      r: "Sedimentation volume F = Vu/Vo เมื่อ Vu คือปริมาตรตะกอนที่สมดุล และ Vo คือปริมาตรยาแขวนตะกอนทั้งหมดก่อนตกตะกอน จึงได้ F = 35/50 = 0.70\n\nค่า F อยู่ระหว่าง 0–1 โดยทั่วไป ยิ่งเข้าใกล้ 1 ยิ่งดี (ตะกอนฟูเต็มภาชนะ ไม่เห็นชั้นใส) ค่า F > 1 เกิดได้ในระบบ flocculated ที่ floc ขยายตัวเกินปริมาตรเดิม ซึ่งต้องเติม vehicle เพิ่มเพื่อเก็บตะกอนไว้ในระบบ",
      w: [
        "เป็นค่า 1 − F คือสัดส่วนของชั้นใส ไม่ใช่ sedimentation volume",
        "ถูก — F = Vu/Vo = 35/50 = 0.70",
        "F = 1 หมายถึงไม่มีชั้นใสเลย (flocculation equilibrium) ซึ่งไม่ตรงกับข้อมูล",
        "เป็นค่า Vo/Vu ซึ่งคำนวณกลับด้าน",
        "ไม่มีวิธีคำนวณที่ถูกต้องให้ค่านี้จากข้อมูลที่กำหนด",
      ],
      k: "F = Vu/Vo; ยิ่งใกล้ 1 ยิ่งดี — ใช้เปรียบเทียบสูตรยาแขวนตะกอนเชิงกายภาพ",
      d: "medium",
      ref: "Martin's Physical Pharmacy and Pharmaceutical Sciences 7th ed. (Coarse Dispersions)",
      c: ["F = Vu / Vo", "F = 35 mL / 50 mL = 0.70"],
    },
    {
      t: "Emulsifier blend for required HLB",
      p: "ต้องการเตรียม O/W emulsion ซึ่ง oil phase มี required HLB 12 โดยใช้สารก่ออิมัลชันผสมรวม 5 g ระหว่าง Span 80 (HLB 4.3) และ Tween 80 (HLB 15.0) ต้องใช้สารแต่ละชนิดเท่าใด",
      o: [
        "Tween 80 3.60 g + Span 80 1.40 g",
        "Tween 80 1.40 g + Span 80 3.60 g",
        "Tween 80 2.50 g + Span 80 2.50 g",
        "Tween 80 4.00 g + Span 80 1.00 g",
        "Tween 80 3.00 g + Span 80 2.00 g",
      ],
      a: 0,
      r: "HLB ของสารผสมเป็นค่าเฉลี่ยถ่วงน้ำหนัก: HLBmix = fA·HLBA + (1−fA)·HLBB ให้ f = สัดส่วน Tween 80 จะได้ 12 = 15f + 4.3(1−f) → f = (12 − 4.3)/(15 − 4.3) = 0.72\n\nTween 80 = 0.72 × 5 = 3.60 g และ Span 80 = 1.40 g การใช้คู่ surfactant HLB ต่ำ+สูงมักให้ interfacial film ที่แน่นกว่าการใช้ตัวเดียว ทำให้อิมัลชันคงตัวดีกว่า ตรวจคำตอบได้ว่า HLB ต้องอยู่ใกล้ฝั่ง Tween เพราะ 12 ใกล้ 15 มากกว่า 4.3",
      w: [
        "ถูก — f(Tween) = 7.7/10.7 = 0.72 → 3.60 g และ Span 80 1.40 g ให้ HLB ผสม 12",
        "สลับปริมาณ ทำให้ HLB ผสม ≈ 7.3 เหมาะกับ W/O มากกว่า",
        "ผสม 1:1 ได้ HLB ≈ 9.65 ต่ำกว่าที่ต้องการ",
        "ได้ HLB ≈ 12.9 สูงเกิน required HLB",
        "ได้ HLB ≈ 10.7 ยังต่ำกว่า 12",
      ],
      k: "สัดส่วนตัว HLB สูง = (HLBreq − HLBต่ำ)/(HLBสูง − HLBต่ำ)",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed. (Emulsions); Griffin WC, J Soc Cosmet Chem 1949",
      c: [
        "f(Tween 80) = (12 − 4.3)/(15.0 − 4.3) = 7.7/10.7 = 0.72",
        "Tween 80 = 0.72 × 5 g = 3.60 g",
        "Span 80 = 5 − 3.60 = 1.40 g",
      ],
    },
    {
      t: "Emulsion type by dilution test",
      p: "เภสัชกรนำอิมัลชันที่ไม่ทราบชนิดหยดลงในน้ำ พบว่าอิมัลชันกระจายตัวเข้ากับน้ำได้ทันทีโดยไม่จับเป็นก้อน ข้อใดสรุปได้ถูกต้อง",
      o: [
        "เป็น O/W emulsion เพราะ external phase คือน้ำ",
        "เป็น W/O emulsion เพราะ internal phase คือน้ำ",
        "เป็น W/O emulsion เพราะน้ำแทรกเข้าไปใน oil phase ได้",
        "สรุปไม่ได้ ต้องวัดความหนืดก่อนทุกครั้ง",
        "เป็นอิมัลชันที่แตกชั้น (cracked) แล้ว",
      ],
      a: 0,
      r: "Dilution test อาศัยหลักว่าอิมัลชันจะเจือจางได้ด้วยของเหลวที่เป็น external (continuous) phase เท่านั้น ถ้าหยดลงน้ำแล้วกระจายตัวได้ แสดงว่า continuous phase เป็นน้ำ คือ O/W emulsion\n\nการทดสอบอื่นที่ใช้ร่วมได้ ได้แก่ conductivity test (O/W นำไฟฟ้า), dye solubility test (water-soluble dye เช่น amaranth กระจายทั่วใน O/W; oil-soluble dye เช่น Sudan III กระจายทั่วใน W/O) และ fluorescence test",
      w: [
        "ถูก — อิมัลชันเจือจางได้ด้วย external phase เมื่อเข้ากับน้ำได้จึงเป็น O/W",
        "W/O มีน้ำมันเป็น external phase จะไม่กระจายในน้ำแต่จะจับตัวเป็นหยด",
        "ตีความผิด การที่น้ำเข้ากันได้บ่งชี้ว่าน้ำเป็น continuous phase ไม่ใช่ internal",
        "ความหนืดไม่ใช่การทดสอบชนิดอิมัลชัน dilution test ใช้สรุปได้โดยตรง",
        "อิมัลชันที่ cracked จะเห็นชั้นน้ำมันแยก ไม่กระจายเป็นเนื้อเดียวกับน้ำ",
      ],
      k: "Dilution test: อิมัลชันผสมได้กับ external phase — เข้ากับน้ำ = O/W, เข้ากับน้ำมัน = W/O",
      d: "easy",
      ref: "Aulton's Pharmaceutics 6th ed. (Emulsions); Ansel's Pharmaceutical Dosage Forms 11th ed.",
    },
    {
      t: "Hydrocarbon (oleaginous) ointment base",
      p: "ผู้ป่วยผิวแห้งมากต้องการยาทาที่มี occlusive effect สูงสุดเพื่อเพิ่มความชุ่มชื้นของ stratum corneum และตัวยาเป็นสาร hydrolysis ง่าย ควรเลือกยาพื้นชนิดใดเหมาะสมที่สุด",
      o: [
        "White petrolatum (hydrocarbon base)",
        "Hydrophilic ointment (water-removable base)",
        "PEG ointment (water-soluble base)",
        "Vanishing cream แบบ O/W",
        "Carbomer hydrogel",
      ],
      a: 0,
      r: "Hydrocarbon (oleaginous) base เช่น white petrolatum, white ointment ไม่มีน้ำและแทบไม่ดูดน้ำ จึงเป็นยาพื้นที่ occlusive ที่สุด ลด transepidermal water loss ช่วย hydrate ผิวและเพิ่มการซึมผ่านของยาบางชนิด อีกทั้งไม่มีน้ำจึงเหมาะกับยาที่ไวต่อ hydrolysis\n\nข้อเสียคือเหนียวเหนอะหนะ ล้างน้ำออกยาก และรับน้ำ (ส่วนประกอบที่เป็นน้ำ) ได้น้อยมาก ส่วน base ชนิดอื่นที่มีน้ำหรือละลายน้ำได้ occlusive น้อยกว่า",
      w: [
        "ถูก — hydrocarbon base ไม่มีน้ำ occlusive สูงสุด และเหมาะกับยาที่ hydrolysis ง่าย",
        "เป็น O/W ที่มีน้ำ ล้างออกง่าย occlusive ต่ำกว่าและไม่เหมาะกับยาที่ไวต่อน้ำ",
        "PEG ละลายน้ำและดูดน้ำจากผิว ไม่ occlusive จึงไม่ช่วย hydrate ผิว",
        "vanishing cream มีน้ำมาก ระเหยเย็นสบายแต่ occlusive ต่ำ",
        "hydrogel มีน้ำเป็นส่วนใหญ่ ไม่ occlusive และไม่เหมาะกับยาที่ hydrolysis ง่าย",
      ],
      k: "Occlusion: hydrocarbon > absorption > W/O cream > O/W cream > water-soluble base",
      d: "medium",
      ref: "USP <1151> Pharmaceutical Dosage Forms (Ointments); Ansel's Pharmaceutical Dosage Forms 11th ed.",
    },
    {
      t: "Carbomer gel neutralization",
      p: "นักพัฒนาสูตรกระจาย carbomer 940 0.5% ในน้ำ ได้ของเหลวขุ่นเล็กน้อยและความหนืดต่ำ ขั้นตอนใดต่อไปจะทำให้เกิดเจลใสที่มีความหนืดสูงได้ดีที่สุด",
      o: [
        "เติม triethanolamine หรือ NaOH ปรับ pH ให้ประมาณ 6–7",
        "เติม HCl ปรับ pH ให้ต่ำกว่า 3",
        "เติม NaCl ปริมาณมากเพื่อเพิ่ม ionic strength",
        "ให้ความร้อนถึง 90 °C แล้วทิ้งให้เย็น",
        "เติม ethanol 70% เพื่อตกตะกอน polymer",
      ],
      a: 0,
      r: "Carbomer เป็น crosslinked polyacrylic acid ในน้ำมี pH ประมาณ 3 กลุ่ม –COOH ยังไม่แตกตัว สายโพลิเมอร์ขดตัว ความหนืดต่ำ เมื่อ neutralize ด้วยเบส (TEA, NaOH) กลุ่ม carboxyl แตกตัวเป็น –COO⁻ เกิดแรงผลักทางไฟฟ้า ทำให้สายโพลิเมอร์ยืดขยายและบวมน้ำ ความหนืดสูงขึ้นทันที ได้เจลใส\n\nความหนืดสูงสุดในช่วง pH ประมาณ 5–9 ระวังว่า electrolyte ปริมาณมาก หรือยาที่เป็น cationic จะลดความหนืดของ carbomer gel ได้ (screening ประจุ) และ carbomer ไวต่อ UV/ไอออนโลหะบางชนิด",
      w: [
        "ถูก — neutralization ทำให้ –COOH แตกตัว สายโพลิเมอร์ผลักกันและยืดตัว เกิดเจลหนืดใส",
        "การลด pH ทำให้ carbomer ยิ่งไม่แตกตัว ความหนืดไม่เพิ่ม",
        "electrolyte ทำ charge screening ลดความหนืดของ carbomer",
        "ความร้อนไม่ทำให้ carbomer เกิดเจล กลไกขึ้นกับการแตกตัวของประจุ",
        "ethanol ปริมาณมากไม่ช่วยให้เกิดเจลในน้ำ และไม่ได้ neutralize กลุ่มกรด",
      ],
      k: "Carbomer หนืดเมื่อ neutralize (pH ~6–7) ด้วย TEA/NaOH; เกลือและยาประจุบวกทำให้ความหนืดลดลง",
      d: "medium",
      ref: "Handbook of Pharmaceutical Excipients 9th ed. (Carbomer)",
    },
    {
      t: "Cocoa butter polymorphism on overheating",
      p: "ระหว่างเตรียม suppository ด้วย cocoa butter โดยวิธี fusion พนักงานหลอมยาพื้นจนใสหมดที่ 60 °C แล้วเทลงแม่พิมพ์ พบว่าแท่งยาแข็งตัวช้า ติดแม่พิมพ์ และเมื่อเก็บที่อุณหภูมิห้องบางแท่งอ่อนตัว สาเหตุที่น่าจะเป็นมากที่สุดคือข้อใด",
      o: [
        "ร้อนเกินทำให้ผลึกเสถียร β หายหมด เกิดผลึก metastable (α, β′) ที่จุดหลอมเหลวต่ำ",
        "ความร้อนทำให้ cocoa butter เกิด hydrolysis เป็นกรดไขมันอิสระ",
        "cocoa butter ดูดความชื้นจากอากาศขณะร้อนจึงอ่อนตัว",
        "ความร้อนทำให้ cocoa butter เกิด crosslink จึงแข็งตัวช้า",
        "ตัวยาระเหยออกไปหมดทำให้แท่งยาไม่แข็งแรง",
      ],
      a: 0,
      r: "Cocoa butter (theobroma oil) มี polymorphism ผลึกที่เสถียรคือ β form ซึ่งหลอมที่ประมาณ 34–35 °C หากหลอมที่อุณหภูมิสูงเกินจนผลึก β หายหมด เมื่อเย็นลงจะตกผลึกเป็น α และ β′ ซึ่งมีจุดหลอมต่ำ (ราว 18–28 °C) ทำให้แข็งตัวช้า ติดแม่พิมพ์ และอ่อนตัวที่อุณหภูมิห้อง กว่าจะเปลี่ยนกลับเป็น β ต้องใช้เวลาหลายวัน\n\nวิธีป้องกันคือหลอมอย่างช้าๆ ด้วย water bath ไม่เกินประมาณ 34–35 °C ให้ได้ลักษณะครีมข้นที่ยังมีผลึก β เหลือเป็น seed หรือใช้ hard fat (semi-synthetic glycerides) ที่ไม่มีปัญหา polymorphism ชัดเจน",
      w: [
        "ถูก — overheating ทำลาย seed ผลึก β ได้ polymorph metastable จุดหลอมต่ำ",
        "การให้ความร้อนช่วงสั้นไม่ทำให้เกิด hydrolysis มีนัยสำคัญ และไม่อธิบายการแข็งตัวช้า",
        "cocoa butter เป็นไขมันไม่ดูดความชื้น จึงไม่ใช่สาเหตุการอ่อนตัว",
        "triglyceride ใน cocoa butter ไม่เกิด crosslink จากความร้อนระดับนี้",
        "ปัญหาที่พบเป็นคุณสมบัติของยาพื้น ไม่ใช่การระเหยของตัวยา",
      ],
      k: "หลอม cocoa butter ไม่เกิน ~34–35 °C เพื่อรักษา seed β crystal; ร้อนเกิน → α/β′ จุดหลอมต่ำ",
      d: "hard",
      ref: "Aulton's Pharmaceutics 6th ed. (Rectal and vaginal drug delivery); Remington 22nd ed.",
    },
    {
      t: "Benzoic acid preservative pH dependence",
      p: "ยาน้ำเชื่อมตำรับหนึ่งใช้ sodium benzoate เป็น preservative หาก benzoic acid มี pKa 4.2 และตำรับมี pH 5.2 สัดส่วนของ benzoic acid ในรูป unionized (ซึ่งเป็นรูปที่มีฤทธิ์ต้านจุลชีพ) เป็นร้อยละเท่าใดโดยประมาณ",
      o: ["0.9%", "9.1%", "50%", "90.9%", "99.0%"],
      a: 1,
      r: "Weak acid preservative เช่น benzoic acid และ sorbic acid ออกฤทธิ์ในรูป unionized ซึ่งผ่านเยื่อหุ้มเซลล์จุลินทรีย์ได้ สัดส่วน unionized = 1/(1 + 10^(pH − pKa)) ที่ pH 5.2 ซึ่งสูงกว่า pKa 1 หน่วย จะได้ 1/(1 + 10) = 9.1%\n\nดังนั้นเมื่อ pH ของตำรับสูงขึ้น ฤทธิ์กันเสียของ benzoate ลดลงอย่างรวดเร็ว จึงนิยมใช้ในตำรับที่ pH ≤ 4.5 หากตำรับต้องมี pH ใกล้เป็นกลาง ควรเลือก parabens ซึ่งไม่แตกตัวในช่วง pH 4–8",
      w: [
        "ได้ค่านี้หาก pH สูงกว่า pKa 2 หน่วย ไม่ตรงกับโจทย์",
        "ถูก — 1/(1 + 10^(5.2−4.2)) = 1/11 = 9.1%",
        "เป็นค่าที่ pH = pKa เท่านั้น",
        "เป็นสัดส่วน ionized (คำนวณกลับด้าน)",
        "เป็นค่าที่ pH ต่ำกว่า pKa 2 หน่วย",
      ],
      k: "Benzoic/sorbic acid ออกฤทธิ์ในรูป unionized — ใช้ได้ดีใน pH ต่ำ (< ~4.5); pH ใกล้กลางเลือก parabens",
      d: "hard",
      ref: "Handbook of Pharmaceutical Excipients 9th ed. (Benzoic acid; Sodium benzoate)",
      c: [
        "fraction unionized = 1 / (1 + 10^(pH − pKa))",
        "= 1 / (1 + 10^(5.2 − 4.2)) = 1 / (1 + 10)",
        "= 0.0909 ≈ 9.1%",
      ],
    },
    {
      t: "Wetting of hydrophobic powder in suspension",
      p: "ขณะเตรียมยาแขวนตะกอนจากผงยาที่ไม่ชอบน้ำ (hydrophobic) พบว่าผงยาลอยเป็นแพบนผิวน้ำ มีฟองอากาศเกาะ และกระจายตัวไม่ได้ วิธีแก้ไขที่เหมาะสมที่สุดคือข้อใด",
      o: [
        "levigate ผงยากับ wetting agent เช่น glycerin หรือ polysorbate ปริมาณน้อยก่อนเติม vehicle",
        "เติม vehicle ทั้งหมดทีเดียวแล้วเขย่าแรงๆ เป็นเวลานาน",
        "เพิ่มขนาดอนุภาคยาเพื่อให้จมน้ำได้เร็วขึ้น",
        "เติม sucrose เพิ่มเพื่อเพิ่มความหนาแน่นของ vehicle",
        "ลดอุณหภูมิของ vehicle ลงเพื่อเพิ่มแรงตึงผิว",
      ],
      a: 0,
      r: "ผงยา hydrophobic มี contact angle กับน้ำสูง มีอากาศเคลือบผิวอนุภาค จึงลอยและจับกลุ่ม ต้องใช้ wetting agent เพื่อลด interfacial tension ระหว่างของแข็งกับของเหลว และแทนที่อากาศบนผิวอนุภาค\n\nWetting agent ที่ใช้ได้แก่ surfactant HLB ประมาณ 7–9 หรือ polysorbate ความเข้มข้นต่ำ และ cosolvent ที่ชอบน้ำ เช่น glycerin, propylene glycol, alcohol โดยนำมา levigate กับผงยาเป็นเพสต์ก่อน แล้วค่อยๆ เติม vehicle ต้องระวังการใช้ surfactant มากเกินเพราะทำให้เกิดฟองและอาจทำให้เป็น deflocculated system ที่ cake ง่าย",
      w: [
        "ถูก — wetting agent ลด contact angle และไล่อากาศจากผิวอนุภาค ทำให้กระจายตัวได้",
        "การเขย่าแรงไม่แก้ปัญหา contact angle สูง และยิ่งเพิ่มฟองอากาศ",
        "อนุภาคใหญ่ตกตะกอนเร็วขึ้นและไม่ได้ทำให้เปียกน้ำดีขึ้น",
        "sucrose ไม่ใช่ wetting agent และไม่แก้ปัญหาการลอยของผงที่ไม่เปียกน้ำ",
        "แรงตึงผิวที่สูงขึ้นยิ่งทำให้ wetting แย่ลง",
      ],
      k: "ผง hydrophobic ต้อง levigate กับ wetting agent (glycerin, PG, surfactant HLB ~7–9) ก่อนเติม vehicle",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed. (Suspensions); Allen LV, The Art, Science and Technology of Pharmaceutical Compounding",
    },
  ],
  // Mock Set 2
  [
    {
      t: "Elixir characteristics",
      p: "ข้อใดอธิบายลักษณะของ elixir ได้ถูกต้องที่สุดเมื่อเปรียบเทียบกับ syrup",
      o: [
        "เป็นสารละลายใส hydroalcoholic มีรสหวาน ความหวานและความหนืดน้อยกว่า syrup",
        "เป็นยาแขวนตะกอนที่ใช้ alcohol เป็น suspending agent",
        "มีน้ำตาลสูงกว่า syrup จึงหนืดกว่าและไม่ต้องใช้ alcohol",
        "เป็นอิมัลชัน O/W ที่มีรสหวานสำหรับเด็ก",
        "เป็นสารละลายในน้ำล้วนที่ห้ามมี alcohol เกิน 1%",
      ],
      a: 0,
      r: "Elixir คือสารละลายใส รสหวาน มีน้ำและ alcohol เป็นตัวทำละลาย (hydroalcoholic) สำหรับรับประทาน alcohol ช่วยละลายตัวยาและส่วนประกอบที่ละลายน้ำได้น้อย เช่น flavoring oils และช่วยกันเสีย\n\nเมื่อเทียบกับ syrup, elixir มีน้ำตาลน้อยกว่าจึงหวานน้อยกว่าและหนืดน้อยกว่า กลบรสได้ไม่ดีเท่า ข้อจำกัดคือ alcohol ไม่เหมาะกับเด็กและผู้ที่ต้องเลี่ยงแอลกอฮอล์ ส่วนตัวยาที่ละลายดีใน alcohol อาจตกตะกอนเมื่อเจือจางด้วยน้ำ",
      w: [
        "ถูก — elixir คือ clear, sweetened, hydroalcoholic solution หวานและหนืดน้อยกว่า syrup",
        "elixir เป็นสารละลายใส ไม่ใช่ระบบแขวนตะกอน และ alcohol ไม่ใช่ suspending agent",
        "syrup ต่างหากที่มีน้ำตาลสูงกว่าและหนืดกว่า",
        "elixir เป็นสารละลายใสเนื้อเดียว ไม่ใช่อิมัลชัน",
        "ลักษณะเด่นของ elixir คือมี alcohol เป็นส่วนหนึ่งของตัวทำละลาย",
      ],
      k: "Elixir = clear, sweet, hydroalcoholic; หวาน/หนืดน้อยกว่า syrup แต่ละลายสารไม่ชอบน้ำได้ดีกว่า",
      d: "easy",
      ref: "USP <1151> Pharmaceutical Dosage Forms; Ansel's Pharmaceutical Dosage Forms 11th ed.",
    },
    {
      t: "Levigating agent selection",
      p: "ต้องการผสมผง zinc oxide ลงใน white petrolatum ให้เนียนไม่เป็นเม็ดทราย ควรใช้ levigating agent ชนิดใดเหมาะสมที่สุด",
      o: [
        "Mineral oil (liquid paraffin)",
        "Glycerin",
        "น้ำบริสุทธิ์",
        "Propylene glycol",
        "Ethanol 95%",
      ],
      a: 0,
      r: "Levigation คือการบดผงยากับของเหลวปริมาณน้อยบน ointment slab หรือในโกร่ง เพื่อลดขนาดอนุภาคและเคลือบผิวผงให้เปียก ก่อนผสมกับยาพื้น levigating agent ต้องเข้ากันได้กับยาพื้น\n\nสำหรับ hydrocarbon base เช่น white petrolatum ใช้ mineral oil ซึ่งเป็น hydrocarbon เช่นกัน ส่วน glycerin หรือ propylene glycol เหมาะกับยาพื้นที่ผสมน้ำได้ เช่น O/W cream หรือ PEG base การใช้ของเหลวที่ไม่เข้ากับยาพื้นจะแยกชั้นหรือทำให้เนื้อยาไม่เนียน",
      w: [
        "ถูก — mineral oil เข้ากันได้กับ petrolatum ทำให้ผงเปียกและกระจายตัวเนียน",
        "glycerin ไม่ผสมกับ petrolatum เหมาะกับยาพื้นที่ผสมน้ำได้",
        "น้ำไม่ผสมกับ hydrocarbon base และจะแยกออกเป็นหยด",
        "propylene glycol เข้ากับยาพื้นที่ชอบน้ำ ไม่เข้ากับ petrolatum",
        "ethanol ระเหยง่ายและไม่ผสมกับ petrolatum ไม่ใช่ levigating agent ที่เหมาะสม",
      ],
      k: "Levigating agent ต้องเข้ากับยาพื้น: mineral oil → hydrocarbon base; glycerin/PG → water-miscible base",
      d: "easy",
      ref: "USP <795> Pharmaceutical Compounding—Nonsterile Preparations; Allen LV, Pharmaceutical Compounding",
    },
    {
      t: "Flocculated vs deflocculated suspension",
      p: "ผลการทดสอบสูตรยาแขวนตะกอนสองสูตรหลังตั้งทิ้งไว้ 7 วัน สูตร A ตกตะกอนเร็ว มีรอยแยกชั้นใสชัดเจน ตะกอนฟูมีปริมาตรมาก เขย่าเพียงเล็กน้อยก็กระจายกลับ สูตร B ส่วนบนขุ่นนาน แต่ก้นขวดมีตะกอนแน่นปริมาตรน้อยและเขย่ากระจายยาก ข้อสรุปใดถูกต้อง",
      o: [
        "A เป็น flocculated system; B เป็น deflocculated system ที่เกิด caking",
        "A เป็น deflocculated system; B เป็น flocculated system",
        "ทั้ง A และ B เป็น deflocculated แต่ B มีอนุภาคใหญ่กว่า",
        "A เกิด caking เพราะตกตะกอนเร็วกว่า B",
        "B ดีกว่า A เพราะส่วนบนขุ่นนานกว่าแสดงว่ากระจายตัวดี",
      ],
      a: 0,
      r: "ใน flocculated system อนุภาครวมตัวกันหลวมๆ เป็น floc ตกตะกอนเร็วเป็นก้อนรวม เห็นรอยต่อชั้นใสชัด ตะกอนมีโครงสร้างโปร่ง ปริมาตรมาก (F สูง) และกระจายกลับง่าย ไม่เกิด cake\n\nDeflocculated system อนุภาคแยกเป็นอิสระ ตกตะกอนช้าทีละอนุภาค ส่วนบนขุ่นนาน แต่อนุภาคเล็กที่ตกลงไปเรียงตัวแน่นจนเกิด cake ซึ่ง redisperse ยาก ในทางปฏิบัตินิยมทำ controlled flocculation ร่วมกับ structured vehicle เพื่อให้ได้ข้อดีทั้งสองแบบ",
      w: [
        "ถูก — ตกเร็ว ตะกอนฟู กระจายง่าย = flocculated; ตกช้าแต่ตะกอนแน่นแข็ง = deflocculated/caking",
        "สลับลักษณะ ระบบที่ตกเร็วและตะกอนฟูคือ flocculated",
        "ลักษณะของ A ไม่ใช่ deflocculated และขนาดอนุภาคไม่ใช่ประเด็นหลัก",
        "การตกตะกอนเร็วแบบ floc ไม่ทำให้เกิด cake เพราะโครงสร้างโปร่ง",
        "ส่วนบนขุ่นนานไม่ได้แปลว่าดี เพราะผลสุดท้ายคือ cake ที่ทำให้ขนาดยาไม่สม่ำเสมอ",
      ],
      k: "Flocculated: ตกเร็ว ชั้นใสชัด ตะกอนฟู redisperse ง่าย; Deflocculated: ตกช้าแต่ cake",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed. (Suspensions); Martin's Physical Pharmacy 7th ed.",
    },
    {
      t: "Creaming of emulsion",
      p: "O/W emulsion ที่เก็บไว้ 2 สัปดาห์ มีชั้นบนที่ขาวขุ่นเข้มข้นกว่าชั้นล่าง แต่เมื่อเขย่าเบาๆ ก็กลับเป็นเนื้อเดียวกันและขนาดหยดน้ำมันไม่เปลี่ยน วิธีใดลดปัญหานี้ได้เหมาะสมที่สุด",
      o: [
        "เพิ่มความหนืดของ external phase และลดขนาดหยดน้ำมันด้วย homogenizer",
        "เพิ่มปริมาณน้ำมันในสูตรให้มากขึ้น",
        "เพิ่มอุณหภูมิการเก็บรักษาเพื่อลดความหนืด",
        "เปลี่ยนไปใช้สารก่ออิมัลชันที่มี HLB ต่ำกว่า 4",
        "เติม electrolyte ปริมาณมากเพื่อลดประจุบนหยดน้ำมัน",
      ],
      a: 0,
      r: "ปรากฏการณ์นี้คือ creaming ซึ่งหยดน้ำมันที่เบากว่าลอยขึ้นตาม Stokes' law แต่ interfacial film ยังสมบูรณ์ หยดไม่รวมกัน จึงเป็นความไม่คงตัวที่ผันกลับได้ด้วยการเขย่า (ต่างจาก coalescence/cracking ที่ผันกลับไม่ได้)\n\nการลด creaming ทำตามตัวแปรใน Stokes' law คือ ลดขนาดหยด (homogenization) เพิ่มความหนืดของ continuous phase (เช่น เติม methylcellulose, xanthan gum) และลดผลต่างความหนาแน่นระหว่างสองวัฏภาค แม้ creaming ไม่อันตรายแต่ทำให้ผลิตภัณฑ์ไม่สวยและเสี่ยงต่อ coalescence ในชั้นที่หยดอยู่ชิดกัน",
      w: [
        "ถูก — ลดขนาดหยดและเพิ่มความหนืดลดความเร็ว creaming ตาม Stokes' law",
        "เพิ่มน้ำมันทำให้หยดชิดกันมากขึ้น ไม่ได้แก้ creaming และเสี่ยงต่อ phase inversion",
        "อุณหภูมิสูงลดความหนืด ทำให้ creaming เร็วขึ้น",
        "HLB ต่ำเกินเหมาะกับ W/O อาจทำให้ O/W ไม่คงตัวหรือ invert",
        "electrolyte ลดประจุทำให้หยด flocculate และ creaming เร็วขึ้น",
      ],
      k: "Creaming = reversible ตาม Stokes' law; แก้โดยลดขนาดหยด เพิ่มความหนืด ลด Δρ",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed. (Emulsions)",
    },
    {
      t: "Absorption base and water number",
      p: "ร้านยาต้องการผสมสารละลายยาในน้ำปริมาณพอสมควรลงในยาพื้นที่ไม่มีน้ำ โดยยาพื้นต้องรับน้ำได้แล้วเกิดเป็น W/O emulsion และยังคงมีความ occlusive ค่อนข้างสูง ควรเลือกยาพื้นใด",
      o: [
        "Hydrophilic petrolatum หรือ anhydrous lanolin (absorption base)",
        "White petrolatum (hydrocarbon base)",
        "PEG ointment (water-soluble base)",
        "Hydrophilic ointment แบบ O/W",
        "Hydroxyethylcellulose gel",
      ],
      a: 0,
      r: "Absorption base แบ่งเป็นแบบไม่มีน้ำที่ดูดน้ำได้ (เช่น hydrophilic petrolatum, anhydrous lanolin) และแบบ W/O ที่มีน้ำอยู่แล้ว (เช่น lanolin, cold cream) ยาพื้นเหล่านี้มี W/O emulsifier เช่น cholesterol, lanolin alcohols จึงรับน้ำเข้าไปเป็น internal phase ได้\n\nความสามารถรับน้ำวัดด้วย water number คือปริมาณน้ำสูงสุด (g) ที่ยาพื้น 100 g รับได้ที่อุณหภูมิกำหนด ยาพื้นกลุ่มนี้ยังค่อนข้าง occlusive และล้างน้ำออกยาก ต่างจาก water-removable base ที่เป็น O/W",
      w: [
        "ถูก — absorption base ดูดน้ำเกิด W/O emulsion และยัง occlusive",
        "white petrolatum รับน้ำได้น้อยมาก ไม่เหมาะกับการผสมสารละลายในน้ำปริมาณมาก",
        "PEG base ละลายน้ำ ไม่ได้เกิด W/O และไม่ occlusive",
        "hydrophilic ointment เป็น O/W ที่มีน้ำอยู่แล้ว ไม่ตรงกับยาพื้นไม่มีน้ำที่ให้ W/O",
        "เจลเซลลูโลสเป็นระบบน้ำ ไม่ใช่ยาพื้นไม่มีน้ำและไม่ occlusive",
      ],
      k: "Absorption base (hydrophilic petrolatum, anhydrous lanolin) รับน้ำได้เป็น W/O; วัดด้วย water number",
      d: "medium",
      ref: "USP <1151> Pharmaceutical Dosage Forms (Ointments); Ansel's Pharmaceutical Dosage Forms 11th ed.",
    },
    {
      t: "Paraben partitioning into oil phase",
      p: "ตำรับครีม O/W ที่มี oil phase 40% ใช้ propylparaben 0.02% เป็น preservative เดี่ยว ผลการทดสอบ preservative efficacy ไม่ผ่าน ทั้งที่ความเข้มข้นรวมในตำรับถูกต้อง สาเหตุที่เป็นไปได้มากที่สุดคือข้อใด",
      o: [
        "propylparaben มี oil/water partition coefficient สูง จึงไปอยู่ใน oil phase มาก ความเข้มข้นอิสระในวัฏภาคน้ำต่ำเกินไป",
        "propylparaben ถูก ionize หมดที่ pH ของครีม จึงไม่มีฤทธิ์",
        "propylparaben ระเหยออกไประหว่างการผลิตทำให้ปริมาณจริงต่ำ",
        "propylparaben ออกฤทธิ์เฉพาะใน oil phase ซึ่งเชื้อไม่ได้อาศัย",
        "การทดสอบ preservative efficacy ใช้ไม่ได้กับครีม",
      ],
      a: 0,
      r: "จุลินทรีย์เจริญในวัฏภาคน้ำ ดังนั้นฤทธิ์กันเสียขึ้นกับความเข้มข้นอิสระของ preservative ในวัฏภาคน้ำ parabens สายยาว (propyl, butyl) มีความชอบไขมันสูง partition coefficient (oil/water) สูง จึงถูกดึงไปละลายใน oil phase เมื่อสัดส่วนน้ำมันมาก ความเข้มข้นในน้ำจึงต่ำกว่าระดับ MIC\n\nปัจจัยอื่นที่ลดความเข้มข้นอิสระคือการถูก solubilize ใน micelle ของ nonionic surfactant และการจับกับพอลิเมอร์หรือภาชนะ แนวทางแก้คือเพิ่มความเข้มข้นรวม ใช้ methylparaben ร่วม (ละลายน้ำดีกว่า) หรือเติม propylene glycol ที่ช่วยเพิ่มสัดส่วน preservative ในวัฏภาคน้ำ",
      w: [
        "ถูก — partition ไป oil phase ทำให้ความเข้มข้นอิสระในวัฏภาคน้ำซึ่งเป็นที่เชื้อเจริญต่ำเกิน",
        "parabens มี pKa ประมาณ 8.2–8.5 จึงแทบไม่แตกตัวในครีมที่ pH ทั่วไป",
        "propylparaben ไม่ใช่สารระเหยง่ายในสภาวะผลิตครีมทั่วไป",
        "ตรงกันข้าม preservative ต้องอยู่ในวัฏภาคน้ำเพราะเชื้อเจริญในน้ำ",
        "preservative efficacy test (เช่น USP <51>) ใช้กับผลิตภัณฑ์ทาภายนอกที่มีน้ำได้",
      ],
      k: "ประสิทธิภาพ preservative ในอิมัลชันขึ้นกับความเข้มข้นอิสระในวัฏภาคน้ำ — ระวัง partition เข้า oil และ micelle",
      d: "hard",
      ref: "Aulton's Pharmaceutics 6th ed. (Pharmaceutical preservation); Handbook of Pharmaceutical Excipients 9th ed. (Propylparaben)",
    },
    {
      t: "Powder for oral suspension rationale",
      p: "เหตุผลหลักที่ amoxicillin ยาน้ำสำหรับเด็กผลิตเป็นผงแห้งสำหรับผสมน้ำก่อนจ่าย (powder for oral suspension) แทนที่จะเป็นยาแขวนตะกอนสำเร็จรูปคือข้อใด",
      o: [
        "β-lactam ring ถูก hydrolysis ในน้ำ จึงคงตัวในรูปแห้งนานกว่า และมีอายุสั้นหลังผสมน้ำ",
        "amoxicillin ละลายน้ำได้ดีมากจึงไม่สามารถทำเป็นยาแขวนตะกอนได้",
        "เพื่อให้ผู้ป่วยเลือกปรับความแรงของยาเองได้ตามต้องการ",
        "ผงแห้งดูดซึมได้ดีกว่ายาน้ำเพราะไม่มีสารกันเสีย",
        "เพื่อหลีกเลี่ยงการใช้ suspending agent ในสูตร",
      ],
      a: 0,
      r: "ยาที่ไม่คงตัวในน้ำ เช่น penicillins และ cephalosporins (β-lactam ring ถูก hydrolysis) จึงผลิตเป็นผงหรือแกรนูลแห้งที่ประกอบด้วยตัวยา suspending agent สารแต่งรส buffer และ preservative เมื่อผสมน้ำแล้วต้องใช้ภายในเวลาจำกัด (มักเก็บในตู้เย็นและทิ้งส่วนที่เหลือตามฉลาก เช่นประมาณ 7–14 วัน)\n\nขั้นตอนการผสมสำคัญ: เคาะผงให้หลวม เติมน้ำตามปริมาตรที่ฉลากกำหนดเป็นสองส่วน เขย่าให้เข้ากัน และให้คำแนะนำผู้ป่วยเรื่องการเขย่าก่อนใช้และการเก็บรักษา",
      w: [
        "ถูก — β-lactam ไม่คงตัวในน้ำ ผงแห้งยืดอายุยา และหลังผสมมี beyond-use ที่สั้น",
        "amoxicillin trihydrate ละลายน้ำได้น้อย จึงผสมแล้วได้ยาแขวนตะกอน",
        "ความแรงหลังผสมถูกกำหนดตายตัวโดยปริมาตรน้ำที่ระบุบนฉลาก ไม่ได้ให้ผู้ป่วยปรับเอง",
        "ผงแห้งไม่ได้ดูดซึมดีกว่า และสูตรผงหลายสูตรก็มี preservative",
        "ผงสำหรับผสมน้ำยังต้องมี suspending agent ในสูตรเพื่อให้กระจายตัวสม่ำเสมอหลังผสม",
      ],
      k: "ยาที่ hydrolysis ง่าย (β-lactams) ทำเป็น powder for reconstitution; หลังผสมอายุสั้น มักเก็บในตู้เย็น",
      d: "medium",
      ref: "USP <1151> Pharmaceutical Dosage Forms (Powders for oral suspension); Remington 22nd ed.",
    },
    {
      t: "Required HLB of mixed oil phase",
      p: "oil phase ของครีม O/W ประกอบด้วย liquid paraffin 20 g (required HLB 12) และ cetyl alcohol 5 g (required HLB 15) required HLB ของ oil phase นี้มีค่าเท่าใด",
      o: ["12.0", "12.6", "13.5", "14.4", "15.0"],
      a: 1,
      r: "เมื่อ oil phase มีหลายส่วนประกอบ required HLB ของ oil phase เป็นค่าเฉลี่ยถ่วงน้ำหนักตามสัดส่วนของแต่ละส่วนประกอบใน oil phase (ไม่รวมน้ำและ emulsifier)\n\nRequired HLB = (20 × 12 + 5 × 15)/25 = 315/25 = 12.6 จากนั้นจึงเลือกคู่ emulsifier ที่ให้ HLB ผสมเท่ากับ 12.6 ค่าที่ได้ต้องอยู่ใกล้ส่วนประกอบที่มีปริมาณมากกว่า ซึ่งในที่นี้คือ liquid paraffin",
      w: [
        "เป็นค่าของ liquid paraffin อย่างเดียว ไม่ได้รวม cetyl alcohol",
        "ถูก — (20×12 + 5×15)/25 = 12.6",
        "เป็นค่าเฉลี่ยธรรมดาที่ไม่ได้ถ่วงน้ำหนักตามปริมาณ",
        "ถ่วงน้ำหนักสลับกัน (20×15 + 5×12)/25",
        "เป็นค่าของ cetyl alcohol อย่างเดียว",
      ],
      k: "Required HLB ของ oil phase ผสม = ค่าเฉลี่ยถ่วงน้ำหนักตามสัดส่วนน้ำหนักของแต่ละ oil",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed. (Emulsions); Allen LV, Ansel's Pharmaceutical Dosage Forms 11th ed.",
      c: [
        "น้ำหนักรวม oil phase = 20 + 5 = 25 g",
        "Required HLB = (20 × 12 + 5 × 15) / 25",
        "= (240 + 75)/25 = 315/25 = 12.6",
      ],
    },
    {
      t: "Suppository displacement factor",
      p: "ต้องการเตรียม suppository 10 แท่ง แต่ละแท่งมีตัวยา 200 mg แม่พิมพ์บรรจุ cocoa butter เปล่าได้แท่งละ 2.0 g และตัวยามี displacement factor 1.5 (ตัวยา 1.5 g แทนที่ยาพื้น 1 g) ต้องใช้ cocoa butter ทั้งหมดกี่กรัม",
      o: ["17.00 g", "18.00 g", "18.67 g", "19.70 g", "20.00 g"],
      a: 2,
      r: "Displacement factor (f) คือน้ำหนักตัวยาที่แทนที่ยาพื้น 1 ส่วนโดยน้ำหนัก ดังนั้นยาพื้นที่ถูกแทนที่ = น้ำหนักตัวยา/f\n\nยาพื้นที่ต้องใช้ = (จำนวนแท่ง × น้ำหนักแท่งเปล่า) − (น้ำหนักยารวม/f) = 20 − 2.0/1.5 = 18.67 g ในทางปฏิบัติมักคำนวณเผื่อเกิน 1–2 แท่งเพื่อชดเชยการสูญเสียระหว่างเท ตัวยาที่มีความหนาแน่นสูง (เช่น bismuth salts, zinc oxide) มี f สูง จึงแทนที่ยาพื้นได้น้อย",
      w: [
        "เกิดจากคูณ f แทนการหาร (2.0 × 1.5 = 3 g) ซึ่งผิดนิยาม",
        "สมมติว่ายาแทนที่ยาพื้น 1:1 โดยน้ำหนัก ไม่ได้ใช้ displacement factor",
        "ถูก — 20 − (2.0/1.5) = 20 − 1.33 = 18.67 g",
        "หักยาพื้นที่ถูกแทนที่เพียงแท่งเดียวและคูณ f ผิด",
        "ไม่ได้หักยาพื้นที่ถูกแทนที่ด้วยตัวยาเลย",
      ],
      k: "ยาพื้นที่ใช้ = N × น้ำหนักแท่งเปล่า − (น้ำหนักยารวม / displacement factor)",
      d: "hard",
      ref: "Aulton's Pharmaceutics 6th ed. (Rectal and vaginal drug delivery); Pharmaceutical Practice (Winfield) 5th ed.",
      c: [
        "น้ำหนักยาพื้นเปล่า 10 แท่ง = 10 × 2.0 = 20.0 g",
        "น้ำหนักยารวม = 10 × 0.2 = 2.0 g",
        "ยาพื้นที่ถูกแทนที่ = 2.0/1.5 = 1.33 g",
        "ยาพื้นที่ต้องใช้ = 20.0 − 1.33 = 18.67 g",
      ],
    },
    {
      t: "PEG suppository base properties",
      p: "โรงพยาบาลเปลี่ยนยาพื้น suppository จาก cocoa butter เป็น polyethylene glycol (PEG) blend เพื่อใช้ในพื้นที่อากาศร้อน ข้อใดเป็นคำแนะนำหรือข้อพิจารณาที่ถูกต้องที่สุด",
      o: [
        "PEG ปลดปล่อยยาโดยละลายในของเหลวในทวารหนัก และดูดน้ำจากเยื่อบุ จึงควรจุ่มน้ำก่อนสอดเพื่อลดการระคายเคือง",
        "PEG หลอมเหลวที่ 37 °C เหมือน cocoa butter จึงต้องเก็บในตู้เย็นเสมอ",
        "PEG ไม่ดูดความชื้นจึงไม่ทำให้ระคายเคืองเยื่อบุ",
        "PEG มี polymorphism รุนแรงจึงห้ามหลอมเกิน 34 °C",
        "PEG เข้ากันได้กับยาทุกชนิดและไม่มีปัญหาปฏิกิริยาระหว่างกัน",
      ],
      a: 0,
      r: "PEG base เป็น water-soluble base มีจุดหลอมสูงกว่าอุณหภูมิร่างกาย (ปรับได้ด้วยการผสม PEG ต่าง MW) จึงทนร้อน ไม่ต้องเก็บในตู้เย็น ปลดปล่อยยาด้วยการละลายในของเหลวปริมาณน้อยในทวารหนัก ไม่ใช่การหลอม\n\nเนื่องจาก PEG ดูดความชื้น (hygroscopic) สูง จะดึงน้ำจากเยื่อบุทำให้แสบระคายเคือง จึงแนะนำให้จุ่มน้ำก่อนสอด นอกจากนี้ PEG เกิดปฏิกิริยากับยาบางชนิดได้ (เช่น aspirin, benzocaine) และอาจทำให้ฤทธิ์ preservative บางชนิดลดลง ส่วน glycerinated gelatin เป็น water-soluble base อีกชนิดที่ละลายช้า นิยมใช้ทำ pessary",
      w: [
        "ถูก — PEG ละลายในของเหลวแทนการหลอม และ hygroscopic จึงควรจุ่มน้ำก่อนสอด",
        "PEG blend ออกแบบให้หลอมสูงกว่า 37 °C และปลดปล่อยด้วยการละลาย จึงไม่จำเป็นต้องแช่เย็น",
        "PEG ดูดความชื้นสูง เป็นสาเหตุหลักของการระคายเคือง",
        "ปัญหา polymorphism และข้อห้ามหลอมเกิน 34 °C เป็นของ cocoa butter",
        "PEG มี incompatibility กับยาหลายชนิด เช่น aspirin, benzocaine, silver salts",
      ],
      k: "PEG base: ทนร้อน ปลดปล่อยโดยละลาย hygroscopic → จุ่มน้ำก่อนสอด; ระวัง drug incompatibility",
      d: "hard",
      ref: "Ansel's Pharmaceutical Dosage Forms 11th ed. (Suppositories); Handbook of Pharmaceutical Excipients 9th ed. (Polyethylene glycol)",
    },
  ],
  // Mock Set 3
  [
    {
      t: "Cosolvent in oral solution",
      p: "ตัวยาชนิดหนึ่งละลายน้ำได้น้อยกว่าขนาดที่ต้องการในยาน้ำใส (oral solution) และไม่มีหมู่ที่แตกตัวได้ วิธีใดเหมาะสมที่สุดในการเพิ่มการละลายสำหรับตำรับรับประทาน",
      o: [
        "ใช้ cosolvent เช่น propylene glycol, glycerin หรือ ethanol ผสมกับน้ำ",
        "ปรับ pH ของตำรับให้เป็นด่างแก่",
        "เพิ่มขนาดอนุภาคยาก่อนละลาย",
        "เติม suspending agent เช่น xanthan gum",
        "ลดอุณหภูมิในการผสมให้ต่ำกว่า 10 °C",
      ],
      a: 0,
      r: "Cosolvent เป็นตัวทำละลายที่ผสมน้ำได้แต่มี polarity ต่ำกว่าน้ำ จึงลด polarity ของระบบให้ใกล้กับตัวยาที่ไม่ชอบน้ำ เพิ่มการละลายได้หลายเท่า cosolvent ที่ยอมรับสำหรับยารับประทาน ได้แก่ ethanol, propylene glycol, glycerin และ PEG 400\n\nเนื่องจากตัวยาไม่มีหมู่ที่แตกตัว การปรับ pH จึงไม่ช่วย ข้อควรระวังของ cosolvent คือยาอาจตกตะกอนเมื่อถูกเจือจางด้วยน้ำ (เช่นในกระเพาะหรือเมื่อผสมกับยาน้ำอื่น) และขีดจำกัดความปลอดภัยของ ethanol/PG โดยเฉพาะในเด็ก",
      w: [
        "ถูก — cosolvent ลด polarity ของตัวทำละลายเพิ่มการละลายของยาที่ไม่แตกตัว",
        "ยาไม่มีหมู่ที่แตกตัวได้ การปรับ pH จึงไม่เพิ่มการละลาย และ pH ด่างแก่ไม่เหมาะกับยารับประทาน",
        "ขนาดอนุภาคมีผลต่ออัตราการละลาย ไม่ได้เพิ่ม equilibrium solubility และการเพิ่มขนาดยิ่งละลายช้า",
        "suspending agent ทำให้เป็นยาแขวนตะกอน ไม่ได้ทำให้ยาละลายเป็นสารละลายใส",
        "การลดอุณหภูมิมักลดการละลายของของแข็งส่วนใหญ่",
      ],
      k: "ยาไม่แตกตัวที่ละลายน้ำน้อย → cosolvent (EtOH, PG, glycerin, PEG 400); ระวังตกตะกอนเมื่อเจือจาง",
      d: "easy",
      ref: "Aulton's Pharmaceutics 6th ed. (Solutions and their properties); Remington 22nd ed.",
    },
    {
      t: "Water-removable (O/W) ointment base",
      p: "Hydrophilic Ointment USP ซึ่งประกอบด้วย stearyl alcohol, white petrolatum, propylene glycol, sodium lauryl sulfate และน้ำ จัดเป็นยาพื้นประเภทใด และมีคุณสมบัติเด่นอย่างไร",
      o: [
        "Water-removable base (O/W) ล้างออกด้วยน้ำได้ง่าย เจือจางด้วยน้ำได้",
        "Hydrocarbon base ที่ occlusive สูงสุดและไม่มีน้ำ",
        "Absorption base แบบ W/O ที่ล้างออกยาก",
        "Water-soluble base ที่ไม่มีไขมันเลย",
        "Paste ที่มีผงของแข็งมากกว่า 50%",
      ],
      a: 0,
      r: "Hydrophilic ointment เป็น O/W emulsion base ใช้ sodium lauryl sulfate เป็น O/W emulsifier และ stearyl alcohol เป็น auxiliary emulsifier/stiffener มีน้ำเป็น external phase จึงล้างออกด้วยน้ำได้ (water-removable/washable) ไม่เหนอะหนะ และเจือจางด้วยน้ำได้\n\nยาพื้นกลุ่มนี้ occlusive น้อยกว่า hydrocarbon และ absorption base มีน้ำจึงต้องมี preservative (เช่น parabens) และน้ำอาจระเหยทำให้เนื้อครีมเปลี่ยนได้ เหมาะกับผิวที่มีของเหลวซึมและบริเวณที่มีขน",
      w: [
        "ถูก — เป็น O/W emulsion base ล้างน้ำออกได้ และเจือจางด้วยน้ำได้",
        "hydrocarbon base ไม่มีน้ำและ emulsifier ส่วนประกอบนี้มีทั้งน้ำและ SLS",
        "SLS เป็น O/W emulsifier ไม่ใช่ W/O จึงไม่ใช่ absorption base",
        "water-soluble base เช่น PEG ointment ไม่มีส่วนที่เป็นไขมันอย่าง petrolatum/stearyl alcohol",
        "สูตรนี้ไม่มีผงของแข็งปริมาณมากจึงไม่ใช่ paste",
      ],
      k: "Water-removable base = O/W cream (เช่น Hydrophilic Ointment USP) ล้างน้ำออกได้ ต้องมี preservative",
      d: "easy",
      ref: "USP–NF Monograph: Hydrophilic Ointment; USP <1151> Pharmaceutical Dosage Forms",
    },
    {
      t: "USP <51> criteria for oral products",
      p: "ยาน้ำเชื่อมรับประทานที่มี preservative ถูกทดสอบ Antimicrobial Effectiveness Testing ตาม USP <51> (Category 3, oral products) เกณฑ์ผ่านสำหรับแบคทีเรียคือข้อใด",
      o: [
        "ลดลงไม่น้อยกว่า 1.0 log จากค่าเริ่มต้นที่ 14 วัน และไม่เพิ่มขึ้นจากค่าที่ 14 วันเมื่อถึง 28 วัน",
        "ลดลงไม่น้อยกว่า 3.0 log ที่ 7 วัน และไม่พบเชื้อที่ 28 วัน",
        "ลดลงไม่น้อยกว่า 2.0 log ที่ 6 ชั่วโมง",
        "ไม่พบเชื้อเลยตั้งแต่วันที่ 1",
        "จำนวนเชื้อไม่เพิ่มขึ้นจากค่าเริ่มต้นที่ 28 วันเท่านั้น",
      ],
      a: 0,
      r: "USP <51> แบ่งผลิตภัณฑ์เป็น 4 categories โดย Category 3 คือผลิตภัณฑ์รับประทาน (oral products ที่ไม่ใช่ antacids) เกณฑ์สำหรับแบคทีเรียคือลดลง ≥ 1.0 log จากค่าเริ่มต้นที่ 14 วัน และไม่เพิ่มขึ้นจากค่าที่ 14 วันเมื่อถึง 28 วัน ส่วน yeast และ mold ต้องไม่เพิ่มขึ้นจากค่าเริ่มต้นที่ 14 และ 28 วัน\n\nเกณฑ์จะเข้มงวดขึ้นสำหรับผลิตภัณฑ์ parenteral/ophthalmic (Category 1) และผลิตภัณฑ์ทาภายนอก (Category 2 ต้องลด ≥ 2.0 log ที่ 14 วัน) เพราะความเสี่ยงต่อผู้ป่วยต่างกัน 'ไม่เพิ่มขึ้น' หมายถึงไม่เกิน 0.5 log จากค่าที่เปรียบเทียบ",
      w: [
        "ถูก — เป็นเกณฑ์แบคทีเรียของ Category 3 (oral products) ตาม USP <51>",
        "เป็นเกณฑ์ที่เข้มงวดคล้าย Category 1 (injections/ophthalmics) ไม่ใช่ผลิตภัณฑ์รับประทาน",
        "การนับที่ 6 ชั่วโมงอยู่ในเกณฑ์ของ Ph. Eur. สำหรับ parenteral ไม่ใช่ USP oral",
        "ไม่มีเกณฑ์ใดกำหนดให้ปลอดเชื้อทันที ผลิตภัณฑ์รับประทานไม่ใช่ยาปราศจากเชื้อ",
        "เกณฑ์ 'ไม่เพิ่มขึ้น' ใช้กับ yeast/mold ส่วนแบคทีเรียต้องลดลงอย่างน้อย 1 log ที่ 14 วัน",
      ],
      k: "USP <51> Cat. 3 (oral): bacteria ≥1 log ลดลงที่ 14 วัน ไม่เพิ่มที่ 28 วัน; yeast/mold ไม่เพิ่ม",
      d: "medium",
      ref: "USP <51> Antimicrobial Effectiveness Testing",
    },
    {
      t: "Colloid mill in liquid manufacturing",
      p: "โรงงานผลิตยาแขวนตะกอนชนิดข้นพบว่ายังมี agglomerate ของผงยาหลงเหลือหลังผสมด้วย propeller mixer จึงนำผ่านเครื่องที่มี rotor หมุนเร็วสูงใกล้กับ stator โดยมีช่องว่างแคบปรับได้ เครื่องนี้คือข้อใด และต้องระวังเรื่องใด",
      o: [
        "Colloid mill — ให้แรงเฉือนสูง ต้องระวังความร้อนที่เกิดขึ้นระหว่างการผ่านเครื่อง",
        "Ball mill — ลดขนาดด้วยการกระแทกของลูกบอล ต้องระวังเสียงดัง",
        "Ribbon blender — ผสมผงแห้ง ต้องระวังการแยกชั้นของผง",
        "Fluid energy mill — ใช้อากาศความเร็วสูง ต้องระวังไฟฟ้าสถิต",
        "Planetary mixer — ผสมเพสต์ ต้องระวังการเกิด dead zone",
      ],
      a: 0,
      r: "Colloid mill ประกอบด้วย rotor และ stator ที่มีช่องว่างแคบ (ประมาณ 0.005–0.75 mm ปรับได้) ของเหลวที่ผ่านช่องว่างได้รับแรงเฉือนสูงมาก ใช้ทำลาย agglomerate ในยาแขวนตะกอน และลดขนาดหยดในอิมัลชันหรือครีม\n\nข้อควรระวังคือพลังงานกลเปลี่ยนเป็นความร้อน ทำให้อุณหภูมิผลิตภัณฑ์เพิ่มขึ้น เครื่องจำนวนมากจึงมี cooling jacket นอกจากนี้อาจทำให้อากาศเข้าไปในผลิตภัณฑ์ได้ ต้องพิจารณาขั้นตอน deaeration ร่วม",
      w: [
        "ถูก — rotor-stator ช่องแคบให้แรงเฉือนสูงคือ colloid mill และเกิดความร้อนระหว่างใช้งาน",
        "ball mill ใช้ลูกบอลกระแทก ไม่มี rotor-stator ช่องแคบ และใช้กับผงแห้งเป็นหลัก",
        "ribbon blender ใช้ผสมผงแห้ง ไม่ได้ลด agglomerate ในของเหลว",
        "fluid energy (jet) mill ใช้ลดขนาดผงแห้งด้วยกระแสอากาศ ไม่ใช่ของเหลว",
        "planetary mixer เป็นเครื่องผสม ไม่ได้มี rotor-stator ที่ให้แรงเฉือนสูงในช่องแคบ",
      ],
      k: "Colloid mill = rotor-stator ช่องแคบ แรงเฉือนสูง ใช้กับ suspension/emulsion; ระวังความร้อนและอากาศ",
      d: "medium",
      ref: "Lachman/Lieberman's The Theory and Practice of Industrial Pharmacy 4th ed. (Liquids; Disperse systems)",
    },
    {
      t: "Gel syneresis",
      p: "ระหว่างการศึกษาความคงตัว พบว่าเจลมีของเหลวใสซึมออกมาเป็นชั้นบนผิวหน้า และตัวเจลหดตัวลงเล็กน้อย ปรากฏการณ์นี้เรียกว่าอะไร",
      o: [
        "Syneresis",
        "Thixotropy",
        "Swelling (imbibition)",
        "Creaming",
        "Bleeding ของ hydrocarbon base",
      ],
      a: 0,
      r: "Syneresis คือการที่โครงข่าย (network) ของเจลหดตัวเมื่อเวลาผ่านไป ทำให้ของเหลวที่อยู่ภายในถูกบีบออกมาที่ผิว มักเกิดเมื่อแรงยึดระหว่างสายพอลิเมอร์มากขึ้น เช่น ความเข้มข้นพอลิเมอร์ต่ำใกล้จุดเกิดเจล การเปลี่ยนอุณหภูมิ หรือการเปลี่ยน pH/ionic strength\n\nตรงข้ามกับ swelling (imbibition) ที่เจลดูดของเหลวเข้าไปแล้วพองตัว ส่วน thixotropy คือการเปลี่ยนจากเจลเป็น sol เมื่อมีแรงเฉือนแล้วกลับคืนเมื่อพัก ในทางปฏิบัติแก้ไขโดยปรับความเข้มข้นหรือชนิดของ gelling agent",
      w: [
        "ถูก — การหดตัวของโครงข่ายเจลจนของเหลวถูกบีบออกมาที่ผิวคือ syneresis",
        "thixotropy คือการลดความหนืดเมื่อเขย่าและกลับคืนเมื่อพัก ไม่ใช่การแยกของเหลว",
        "swelling คือการดูดของเหลวเข้าไป ตรงข้ามกับปรากฏการณ์ในโจทย์",
        "creaming เป็นปัญหาของอิมัลชันที่หยดน้ำมันลอยขึ้น",
        "bleeding เป็นการแยกน้ำมันออกจาก petrolatum ไม่ใช่การแยกของเหลวจากเจลน้ำ",
      ],
      k: "Syneresis = เจลหดตัวบีบของเหลวออก; ตรงข้าม imbibition/swelling",
      d: "medium",
      ref: "Martin's Physical Pharmacy 7th ed. (Colloidal dispersions; Gels); USP <1151>",
    },
    {
      t: "Ointment dilution with base",
      p: "ร้านยามี ointment ที่มีตัวยา 10% w/w อยู่ 100 g ต้องการเจือจางด้วยยาพื้นเปล่าให้ได้ความแรง 2.5% w/w ต้องเติมยาพื้นเปล่ากี่กรัม",
      o: ["25 g", "75 g", "250 g", "300 g", "400 g"],
      a: 3,
      r: "ปริมาณตัวยาคงที่ระหว่างการเจือจาง ใช้ C1 × W1 = C2 × W2 คือ 10% × 100 g = 2.5% × W2 ได้ W2 = 400 g ซึ่งเป็นน้ำหนักรวมหลังเจือจาง\n\nยาพื้นที่ต้องเติม = 400 − 100 = 300 g ข้อผิดพลาดที่พบบ่อยคือตอบน้ำหนักรวม (400 g) แทนปริมาณที่ต้องเติม ในการผสมจริงควรใช้เทคนิค geometric dilution เพื่อให้ตัวยากระจายสม่ำเสมอ",
      w: [
        "ได้จากการกลับสัดส่วน (100 × 2.5/10) ซึ่งเป็นการคำนวณแบบทำให้เข้มข้นขึ้น ไม่ใช่เจือจาง",
        "ได้จาก 100 − 25 ซึ่งต่อยอดจากการกลับสัดส่วนที่ผิด",
        "ได้จาก 10 × 100/4 ที่แทนค่าผิด ไม่ตรงกับ C1W1 = C2W2",
        "ถูก — น้ำหนักรวมใหม่ 400 g ต้องเติมยาพื้น 400 − 100 = 300 g",
        "เป็นน้ำหนักรวมหลังเจือจาง ไม่ใช่ปริมาณยาพื้นที่ต้องเติม",
      ],
      k: "C1W1 = C2W2 แล้วหักน้ำหนักเดิม จึงได้ปริมาณ diluent ที่ต้องเติม; ผสมแบบ geometric dilution",
      d: "medium",
      ref: "Ansel HC, Pharmaceutical Calculations 15th ed.",
      c: [
        "10% × 100 g = 2.5% × W2",
        "W2 = 1000/2.5 = 400 g",
        "ยาพื้นที่ต้องเติม = 400 − 100 = 300 g",
      ],
    },
    {
      t: "Continental 4:2:1 primary emulsion",
      p: "ต้องการเตรียมอิมัลชันจาก castor oil (fixed oil) 40 mL ด้วยวิธี dry gum (continental method) โดยใช้ acacia ใน primary emulsion ต้องใช้ acacia และน้ำอย่างละเท่าใด",
      o: [
        "acacia 10 g และน้ำ 20 mL",
        "acacia 20 g และน้ำ 20 mL",
        "acacia 13.3 g และน้ำ 26.7 mL",
        "acacia 10 g และน้ำ 40 mL",
        "acacia 5 g และน้ำ 10 mL",
      ],
      a: 0,
      r: "Dry gum method ใช้สัดส่วน oil : water : gum สำหรับ primary emulsion เป็น 4 : 2 : 1 สำหรับ fixed oil, 3 : 2 : 1 สำหรับ mineral oil และ 2 : 2 : 1 สำหรับ volatile oil\n\ncastor oil เป็น fixed oil จึงใช้ 4 : 2 : 1 → oil 40 mL : water 20 mL : acacia 10 g โดยบด acacia กับน้ำมันให้เข้ากันก่อน แล้วเติมน้ำทั้งหมดในครั้งเดียวและบดเร็วจนได้ primary emulsion ที่มีเสียงแตกเปาะ (crackling) จากนั้นจึงเจือจางด้วยน้ำส่วนที่เหลือ",
      w: [
        "ถูก — fixed oil ใช้ 4:2:1 → oil 40 : water 20 : acacia 10",
        "ใช้ acacia มากเกินสัดส่วน 4:2:1",
        "ไม่ตรงกับสัดส่วนมาตรฐานใด",
        "น้ำมากเกินสำหรับ primary emulsion ของ fixed oil",
        "เป็นปริมาณครึ่งหนึ่งของที่ต้องการ ใช้กับน้ำมัน 20 mL",
      ],
      k: "Primary emulsion (oil:water:gum): fixed 4:2:1, mineral 3:2:1, volatile 2:2:1",
      d: "medium",
      ref: "Ansel's Pharmaceutical Dosage Forms 11th ed. (Emulsions); Remington 22nd ed.",
      c: [
        "fixed oil → oil : water : gum = 4 : 2 : 1",
        "1 ส่วน = 40/4 = 10",
        "water = 2 × 10 = 20 mL; acacia = 1 × 10 = 10 g",
      ],
    },
    {
      t: "Controlled flocculation by electrolyte (zeta potential)",
      p: "อนุภาคยาในยาแขวนตะกอนมีประจุลบสูง (zeta potential ประมาณ −45 mV) เนื่องจากใช้ docusate sodium เป็น wetting agent ผู้พัฒนาค่อยๆ เติม AlCl₃ ทีละน้อยและวัด sedimentation volume ผลใดที่คาดว่าจะพบ",
      o: [
        "F เพิ่มขึ้นเมื่อ zeta potential ลดลงเข้าใกล้ศูนย์ (flocculation) แล้วลดลงอีกเมื่อเติมมากเกินจนประจุกลับเป็นบวก",
        "F ลดลงตลอดเพราะ Al³⁺ ทำให้อนุภาคละลาย",
        "F คงที่เพราะ electrolyte ไม่มีผลต่อ zeta potential",
        "F เพิ่มขึ้นเรื่อยๆ ไม่จำกัดตามปริมาณ AlCl₃",
        "เกิด caking ทันทีที่เติม AlCl₃ หยดแรก",
      ],
      a: 0,
      r: "อนุภาคที่มี zeta potential สูงจะผลักกัน กระจายตัวแบบ deflocculated และเสี่ยงต่อ caking เมื่อเติม flocculating agent ที่เป็นไอออนประจุตรงข้าม (Al³⁺ มีประสิทธิภาพสูงตาม Schulze–Hardy rule) zeta potential ลดลง แรงผลักลดลงจนอนุภาครวมเป็น floc หลวมๆ ค่า F สูงขึ้นและไม่เกิด cake\n\nหากเติมมากเกิน ไอออนบวกดูดซับจนประจุผิวกลับเป็นบวก zeta potential สูงขึ้นอีกครั้ง ระบบกลับเป็น deflocculated และ F ลดลง จึงต้องหาช่วงความเข้มข้นที่เหมาะสม (controlled flocculation) จากกราฟ F เทียบกับปริมาณ electrolyte",
      w: [
        "ถูก — ลด zeta potential → flocculation (F สูงสุด) แล้วเกิน → charge reversal → deflocculated อีก",
        "Al³⁺ ไม่ได้ทำให้อนุภาคละลาย ผลหลักคือการลดประจุผิว",
        "electrolyte โดยเฉพาะไอออนวาเลนซ์สูงลด zeta potential ได้ชัดเจน",
        "การเติมเกินทำให้ประจุกลับขั้วและ F ลดลง ไม่ได้เพิ่มไม่จำกัด",
        "การลด zeta potential ช่วงแรกทำให้เกิด floc ซึ่งป้องกัน caking",
      ],
      k: "Controlled flocculation: ลด zeta potential ด้วย electrolyte ประจุตรงข้ามจน F สูงสุด — เกินไปจะ charge reversal",
      d: "hard",
      ref: "Martin's Physical Pharmacy 7th ed. (Coarse Dispersions); Aulton's Pharmaceutics 6th ed.",
    },
    {
      t: "Phase inversion by divalent cation",
      p: "Lotion แบบ O/W ที่ใช้ sodium oleate เป็นสารก่ออิมัลชัน ถูกผสมกับสารละลายที่มี calcium chloride ปริมาณมาก ผลที่น่าจะเกิดขึ้นมากที่สุดคือข้อใด",
      o: [
        "เกิด phase inversion เป็น W/O เพราะเกิด calcium oleate ซึ่งเป็น W/O emulsifier",
        "อิมัลชันคงตัวดีขึ้นเพราะ Ca²⁺ เพิ่มความหนืดของวัฏภาคน้ำ",
        "เกิดแค่ creaming ที่เขย่ากลับได้โดยชนิดอิมัลชันไม่เปลี่ยน",
        "sodium oleate เปลี่ยนเป็น nonionic surfactant ที่มี HLB สูงขึ้น",
        "หยดน้ำมันมีขนาดเล็กลงเพราะ Ca²⁺ ลดแรงตึงผิว",
      ],
      a: 0,
      r: "Sodium oleate เป็นสบู่ไอออนวาเลนซ์เดียว ละลายน้ำดี (HLB สูง) จึงเป็น O/W emulsifier เมื่อมี Ca²⁺ มากจะเกิด calcium oleate ซึ่งเป็นสบู่วาเลนซ์สองที่ละลายในน้ำมันมากกว่า (HLB ต่ำ) ทำหน้าที่เป็น W/O emulsifier ระบบจึงพลิกกลับเป็น W/O (phase inversion)\n\nปัจจัยอื่นที่ทำให้เกิด phase inversion ได้แก่ การเพิ่มสัดส่วน internal phase สูงมาก (เกินราว 74% ตามทฤษฎี) และการเปลี่ยนอุณหภูมิในระบบ nonionic surfactant (phase inversion temperature) หลักการนี้ยังใช้ประโยชน์ได้ เช่น lime liniment ที่ตั้งใจให้เกิด calcium soap เป็น W/O",
      w: [
        "ถูก — Ca²⁺ เปลี่ยน sodium soap (O/W) เป็น calcium soap (W/O) ทำให้อิมัลชันพลิกกลับ",
        "Ca²⁺ ทำปฏิกิริยากับ emulsifier ไม่ได้ทำให้คงตัวขึ้น",
        "การเปลี่ยนชนิด emulsifier ทำให้ชนิดอิมัลชันเปลี่ยน ไม่ใช่แค่ creaming",
        "calcium oleate ยังเป็น anionic soap และมี HLB ต่ำลง ไม่ใช่สูงขึ้น",
        "ผลหลักคือชนิดอิมัลชันเปลี่ยน ไม่ใช่หยดเล็กลง",
      ],
      k: "Sodium/potassium soap = O/W; calcium/divalent soap = W/O — เติม Ca²⁺ ทำให้ O/W invert",
      d: "hard",
      ref: "Aulton's Pharmaceutics 6th ed. (Emulsions); Martin's Physical Pharmacy 7th ed.",
    },
    {
      t: "Drug release vs suppository base type",
      p: "ตัวยาที่ละลายในไขมันได้ดีมาก (lipophilic, log P สูง) ถูกบรรจุใน suppository ที่ใช้ cocoa butter เป็นยาพื้น พบว่าการปลดปล่อยยาช้าและ bioavailability ต่ำ ข้อใดอธิบายและแก้ไขได้เหมาะสมที่สุด",
      o: [
        "ยามี affinity สูงกับยาพื้นไขมันจึงไม่ partition ออกสู่ของเหลวในทวารหนัก ควรเปลี่ยนเป็นยาพื้นละลายน้ำ เช่น PEG",
        "cocoa butter หลอมไม่ได้ที่ 37 °C จึงควรเพิ่มอุณหภูมิในการหลอมระหว่างผลิต",
        "ควรเปลี่ยนตัวยาเป็นเกลือที่ละลายในไขมันมากขึ้นเพื่อเพิ่มการปลดปล่อย",
        "ควรเพิ่มขนาดอนุภาคยาเพื่อให้ตกตะกอนไปที่ผิวเยื่อบุเร็วขึ้น",
        "ปัญหานี้แก้ไม่ได้ด้วยการเปลี่ยนยาพื้น ต้องเปลี่ยนเป็นยารับประทาน",
      ],
      a: 0,
      r: "การปลดปล่อยยาจาก suppository ขึ้นกับการที่ยาต้อง partition ออกจากยาพื้นสู่ของเหลวปริมาณน้อยในทวารหนัก หลักทั่วไปคือ ยาที่ละลายน้ำดีควรอยู่ในยาพื้นไขมัน (fatty base) และยาที่ละลายในไขมันดีควรอยู่ในยาพื้นละลายน้ำ (water-soluble base เช่น PEG, glycerinated gelatin)\n\nหากใช้ยา lipophilic ในยาพื้นไขมัน ยาจะชอบอยู่ในยาพื้นมากกว่า (partition coefficient สูง) ปลดปล่อยช้า ส่วนยาพื้นละลายน้ำจะละลายออกพร้อมปล่อยยาให้สัมผัสกับเยื่อบุโดยตรง ขนาดอนุภาคที่เล็กของยาที่แขวนลอยในยาพื้นก็ช่วยเพิ่มอัตราการละลายด้วย",
      w: [
        "ถูก — ยา lipophilic ใน fatty base ไม่ partition ออก ควรใช้ water-soluble base",
        "cocoa butter หลอมที่ประมาณ 34–35 °C ซึ่งต่ำกว่าอุณหภูมิร่างกายอยู่แล้ว และการหลอมร้อนเกินยังทำให้เกิด polymorph ที่ไม่ต้องการ",
        "ยิ่งเพิ่มความชอบไขมันยิ่งทำให้ยาอยู่ในยาพื้นไขมันมากขึ้นและปลดปล่อยช้าลง",
        "อนุภาคใหญ่ละลายช้าลง ไม่ได้ช่วยการดูดซึม",
        "การเลือกชนิดยาพื้นให้เหมาะกับคุณสมบัติยาเป็นแนวทางหลักในการปรับปรุงการปลดปล่อย",
      ],
      k: "Suppository: ยาละลายน้ำ → fatty base; ยาละลายไขมัน → water-soluble base (เลือกยาพื้นที่ยา 'ไม่ชอบ')",
      d: "hard",
      ref: "Aulton's Pharmaceutics 6th ed. (Rectal and vaginal drug delivery); Ansel's Pharmaceutical Dosage Forms 11th ed.",
    },
  ],
  // Mock Set 4
  [
    {
      t: "Emulsion cracking (coalescence)",
      p: "อิมัลชันตัวอย่างจากคลังสินค้าแยกเป็นชั้นน้ำมันใสอยู่ด้านบนและชั้นน้ำด้านล่าง เมื่อเขย่าแรงๆ ก็ไม่กลับเป็นเนื้อเดียวกันอย่างถาวร ความไม่คงตัวนี้คือข้อใด",
      o: [
        "Cracking (breaking) จาก coalescence ของหยด ซึ่งผันกลับไม่ได้",
        "Creaming ซึ่งผันกลับได้ด้วยการเขย่า",
        "Flocculation แบบหลวมของหยดน้ำมัน",
        "Phase inversion จาก O/W เป็น W/O",
        "Ostwald ripening ของผลึกตัวยา",
      ],
      a: 0,
      r: "เมื่อ interfacial film รอบหยดถูกทำลาย หยดจะรวมตัวกัน (coalescence) เป็นหยดใหญ่ขึ้นเรื่อยๆ จนสุดท้ายแยกเป็นชั้นน้ำมันกับน้ำ เรียกว่า cracking หรือ breaking ซึ่งผันกลับไม่ได้ด้วยการเขย่า ต้องเตรียมอิมัลชันใหม่ด้วยการเติม emulsifier และให้พลังงานสูง\n\nลำดับความรุนแรงโดยทั่วไป: flocculation → creaming (ผันกลับได้) → coalescence → cracking (ผันกลับไม่ได้) สาเหตุได้แก่ อุณหภูมิสูงหรือแช่แข็ง การเติมสารที่ทำลาย emulsifier (เช่น กรด/ด่าง, electrolyte, alcohol) และการเจริญของจุลินทรีย์",
      w: [
        "ถูก — แยกชั้นน้ำมันใสและเขย่าไม่กลับคืน = cracking จาก coalescence",
        "creaming ไม่เกิดชั้นน้ำมันใส และเขย่าแล้วกลับเป็นเนื้อเดียวกันได้",
        "flocculation คือหยดเกาะกลุ่มหลวมๆ โดยยังไม่รวมตัว จึงกระจายกลับได้",
        "phase inversion ยังคงเป็นอิมัลชัน (เปลี่ยนชนิด) ไม่ได้แยกเป็นสองชั้นใส",
        "Ostwald ripening เป็นการโตของผลึกหรือหยดผ่านการละลาย ไม่ใช่ลักษณะที่เห็นในโจทย์",
      ],
      k: "Creaming/flocculation = reversible; coalescence → cracking = irreversible",
      d: "easy",
      ref: "Aulton's Pharmaceutics 6th ed. (Emulsions)",
    },
    {
      t: "Paste characteristics",
      p: "Zinc Oxide Paste ซึ่งมีผงของแข็ง (zinc oxide และ starch) ประมาณ 50% ในยาพื้น petrolatum มีคุณสมบัติเด่นข้อใดเมื่อเทียบกับ ointment ทั่วไป",
      o: [
        "แข็งกว่า อยู่กับที่ไม่ไหลเยิ้ม ดูดซับสารคัดหลั่ง และเป็นชั้นป้องกันผิว",
        "ซึมผ่านผิวเข้าสู่กระแสเลือดได้ดีกว่า ointment มาก",
        "ล้างออกด้วยน้ำได้ง่ายกว่า O/W cream",
        "ใสและไม่มีผงของแข็งจึงใช้กับเยื่อบุตาได้",
        "เหมาะกับการทาบริเวณหนังศีรษะที่มีขนดก",
      ],
      a: 0,
      r: "Paste คือ semisolid ที่มีผงของแข็งสัดส่วนสูง (มักราว 20–50% ขึ้นไป) ทำให้แข็งและหนืดกว่า ointment อยู่กับที่ไม่ไหลแม้ที่อุณหภูมิร่างกาย จึงใช้ทาเฉพาะจุดได้ดี\n\nผงในตำรับช่วยดูดซับสารคัดหลั่งจากแผล และเกิดชั้นป้องกันผิว (protective barrier) เช่น ใช้ป้องกันผื่นผ้าอ้อม paste มักซึมผ่านผิวน้อย และล้างออกยาก มักใช้น้ำมันพืชหรือ mineral oil ช่วยเช็ดออก",
      w: [
        "ถูก — ผงของแข็งสูงทำให้แข็ง อยู่กับที่ ดูดซับสารคัดหลั่ง และเป็น protective barrier",
        "paste ออกแบบให้ทำงานที่ผิวเป็นหลัก การซึมผ่านผิวไม่ได้ดีกว่า",
        "paste ในยาพื้น petrolatum ล้างน้ำออกยาก",
        "paste มีผงของแข็งมาก ทึบ และไม่ใช่ผลิตภัณฑ์สำหรับตา",
        "ความแข็งเหนียวของ paste ไม่เหมาะกับบริเวณที่มีขน ควรใช้ lotion หรือ gel",
      ],
      k: "Paste = ผงของแข็งสูง แข็ง อยู่กับที่ ดูดซับสารคัดหลั่ง ป้องกันผิว",
      d: "easy",
      ref: "USP <1151> Pharmaceutical Dosage Forms (Pastes); Ansel's Pharmaceutical Dosage Forms 11th ed.",
    },
    {
      t: "Xanthan gum structured vehicle",
      p: "ต้องการ suspending agent สำหรับยาแขวนตะกอนรับประทานที่มีความหนืดสูงขณะตั้งทิ้งไว้เพื่อพยุงอนุภาค แต่เทออกจากขวดได้ง่ายเมื่อเขย่า และทนต่อช่วง pH และ electrolyte ได้กว้าง ควรเลือกสารใด",
      o: [
        "Xanthan gum ซึ่งให้ pseudoplastic flow ที่มี yield value",
        "Sucrose ความเข้มข้นสูงซึ่งให้ Newtonian flow",
        "Glycerin ซึ่งให้ Newtonian flow",
        "Carbomer ที่ไม่ได้ neutralize",
        "Sodium chloride เพื่อเพิ่มความหนาแน่นของ vehicle",
      ],
      a: 0,
      r: "Structured vehicle ที่ดีควรมีความหนืดสูงเมื่ออยู่นิ่ง (ชะลอการตกตะกอน) แต่ความหนืดลดลงเมื่อมีแรงเฉือนจากการเขย่าหรือเท ซึ่งคือ pseudoplastic (shear-thinning) flow โดยมี yield value และ/หรือ thixotropy ช่วยพยุงอนุภาค\n\nXanthan gum เป็น anionic polysaccharide ที่ให้ลักษณะนี้ชัดเจนแม้ความเข้มข้นต่ำ ทนต่อ pH และ electrolyte ได้กว้าง จึงนิยมในยาแขวนตะกอนรับประทาน ส่วน Newtonian vehicle เช่น syrup/glycerin หากหนืดพอจะพยุงอนุภาคได้ก็จะเทยาก",
      w: [
        "ถูก — xanthan gum ให้ shear-thinning พร้อม yield value และทน pH/electrolyte ได้ดี",
        "syrup เป็น Newtonian ความหนืดไม่ลดเมื่อเขย่า ถ้าหนืดพอพยุงอนุภาคก็จะเทยาก",
        "glycerin เป็น Newtonian และต้องใช้ปริมาณมากจึงจะหนืดพอ",
        "carbomer ที่ไม่ neutralize มีความหนืดต่ำ และ carbomer ไวต่อ electrolyte",
        "NaCl ไม่ใช่ suspending agent และอาจรบกวนความคงตัวของระบบ",
      ],
      k: "Structured vehicle ที่ดี = pseudoplastic/thixotropic มี yield value เช่น xanthan gum",
      d: "medium",
      ref: "Handbook of Pharmaceutical Excipients 9th ed. (Xanthan gum); Aulton's Pharmaceutics 6th ed. (Suspensions)",
    },
    {
      t: "Methylcellulose dispersion technique",
      p: "พนักงานโรยผง methylcellulose ลงในน้ำอุณหภูมิห้องโดยตรง ได้ก้อนเจลที่ผิวนอกเปียก ข้างในเป็นผงแห้ง (fish-eyes) วิธีเตรียมที่ถูกต้องคือข้อใด",
      o: [
        "กระจายผงในน้ำร้อน (ราว 1/3 ของปริมาตร) ให้เปียกทั่วก่อน แล้วเติมน้ำเย็นส่วนที่เหลือพร้อมคน",
        "เติมผงลงในน้ำเดือดทั้งหมดแล้วต้มต่อจนเป็นเจลใส",
        "ผสมผงกับน้ำเย็นจัด 0 °C ในครั้งเดียวโดยไม่คน",
        "ละลายผงใน ethanol ทั้งหมดก่อนแล้วจึงระเหยออก",
        "เติมกรดเพื่อลด pH ให้ต่ำกว่า 2 ก่อนเติมผง",
      ],
      a: 0,
      r: "Methylcellulose มีคุณสมบัติละลายได้ในน้ำเย็นแต่ไม่ละลายในน้ำร้อน (inverse solubility/thermal gelation) ถ้าโรยลงน้ำเย็นโดยตรง ผิวนอกของกลุ่มผงจะ hydrate เป็นชั้นเจลห่อหุ้มผงด้านในไว้ เกิดเป็นก้อน\n\nวิธีที่ถูกคือกระจายผงในน้ำร้อนซึ่งผงไม่ละลายแต่เปียกและกระจายแยกอนุภาค จากนั้นเติมน้ำเย็นและคน เมื่ออุณหภูมิลดลง polymer จะละลายได้สารละลายหนืดใส อีกวิธีคือ pre-wet ผงด้วย glycerin หรือผสมแห้งกับส่วนประกอบผงอื่นก่อน",
      w: [
        "ถูก — ใช้ inverse solubility กระจายผงในน้ำร้อนก่อน แล้วเติมน้ำเย็นให้ละลาย",
        "MC ไม่ละลายในน้ำร้อนและเกิด thermal gelation จึงไม่ได้สารละลายใส",
        "การเทในครั้งเดียวโดยไม่คนยังทำให้เกิดก้อน fish-eyes",
        "MC ไม่ละลายใน ethanol ความเข้มข้นสูง และไม่ใช่วิธีมาตรฐาน",
        "pH ไม่ใช่ปัจจัยหลักในการกระจายตัวของ MC ซึ่งเป็น nonionic polymer",
      ],
      k: "Methylcellulose: ละลายในน้ำเย็น ไม่ละลายในน้ำร้อน — กระจายในน้ำร้อนก่อนแล้วเติมน้ำเย็น",
      d: "medium",
      ref: "Handbook of Pharmaceutical Excipients 9th ed. (Methylcellulose)",
    },
    {
      t: "PEG (water-soluble) ointment base",
      p: "PEG Ointment (polyethylene glycol ointment) ที่เตรียมจาก PEG 3350 ผสม PEG 400 มีคุณสมบัติข้อใดถูกต้อง",
      o: [
        "ไม่มีไขมัน ละลายน้ำและล้างออกด้วยน้ำได้ ไม่ occlusive และรับน้ำได้จำกัด",
        "occlusive สูงสุดเพราะไม่มีน้ำเป็นส่วนประกอบ",
        "เป็น W/O emulsion ที่รับน้ำได้มาก",
        "เพิ่มความหนืดได้ด้วยการเพิ่มสัดส่วน PEG 400",
        "เข้ากันได้กับยาทุกชนิดรวมถึง phenols และ silver salts",
      ],
      a: 0,
      r: "Water-soluble base เช่น PEG ointment ประกอบด้วย PEG น้ำหนักโมเลกุลสูง (ของแข็ง เช่น PEG 3350) ผสมกับ PEG น้ำหนักโมเลกุลต่ำ (ของเหลว เช่น PEG 400) ปรับความแข็งได้ตามสัดส่วน ไม่มีไขมัน ละลายและล้างออกด้วยน้ำได้ทั้งหมด\n\nแม้ไม่มีน้ำแต่ไม่ occlusive เพราะละลายน้ำและ hygroscopic รับน้ำได้จำกัด (น้ำมากทำให้อ่อนตัว ปรับได้โดยแทน PEG 400 บางส่วนด้วย stearyl alcohol) PEG ยังมี incompatibility กับยาหลายชนิด เช่น phenols, silver salts, tannic acid และลดฤทธิ์ preservative บางชนิด",
      w: [
        "ถูก — PEG base ไม่มีไขมัน ล้างน้ำออกได้ ไม่ occlusive และรับน้ำได้จำกัด",
        "การไม่มีน้ำไม่ได้แปลว่า occlusive PEG ละลายน้ำจึงไม่เกิดชั้นกั้นน้ำ",
        "PEG ointment ไม่ใช่ emulsion และไม่มี W/O emulsifier",
        "PEG 400 เป็นของเหลว เพิ่มสัดส่วนจะทำให้ยาพื้นอ่อนลง",
        "PEG มี incompatibility กับ phenols, silver salts และสารอื่นอีกหลายชนิด",
      ],
      k: "PEG ointment = water-soluble, greaseless, non-occlusive; ปรับความแข็งด้วยสัดส่วน PEG แข็ง:เหลว",
      d: "medium",
      ref: "USP–NF Monograph: Polyethylene Glycol Ointment; USP <1151>",
    },
    {
      t: "Alcohol content when blending elixirs",
      p: "ผสม low-alcoholic elixir (alcohol 10% v/v) 300 mL กับ high-alcoholic elixir (alcohol 75% v/v) 200 mL ส่วนผสมที่ได้มีความเข้มข้น alcohol ประมาณเท่าใด (ไม่คิดการหดตัวของปริมาตร)",
      o: ["10.0% v/v", "36.0% v/v", "42.5% v/v", "49.0% v/v", "85.0% v/v"],
      a: 1,
      r: "ปริมาณ alcohol รวมคงที่ เป็นค่าเฉลี่ยถ่วงน้ำหนักตามปริมาตร: alcohol จาก low elixir = 300 × 10% = 30 mL และจาก high elixir = 200 × 75% = 150 mL รวม 180 mL ในปริมาตรรวม 500 mL ได้ 36% v/v\n\nหลักการผสม elixir สองระดับ (iso-elixir concept) ใช้ปรับความเข้มข้น alcohol ให้พอละลายตัวยา ในทางปฏิบัติการผสม ethanol กับน้ำเกิดการหดตัวของปริมาตรเล็กน้อย ค่าจริงจึงอาจต่างไปเล็กน้อย",
      w: [
        "เป็นความเข้มข้นของ elixir ตัวแรกเท่านั้น",
        "ถูก — (300×10 + 200×75)/500 = 18000/500 = 36% v/v",
        "เป็นค่าเฉลี่ยธรรมดา (10+75)/2 ไม่ได้ถ่วงน้ำหนักตามปริมาตร",
        "ถ่วงน้ำหนักสลับกัน (300×75 + 200×10)/500",
        "เป็นผลบวกของเปอร์เซ็นต์ซึ่งไม่มีความหมายทางคำนวณ",
      ],
      k: "ผสมสารละลายต่างความเข้มข้น: C = ΣCiVi / ΣVi",
      d: "medium",
      ref: "Ansel HC, Pharmaceutical Calculations 15th ed.; Remington 22nd ed. (Elixirs)",
      c: [
        "alcohol จาก low elixir = 300 × 0.10 = 30 mL",
        "alcohol จาก high elixir = 200 × 0.75 = 150 mL",
        "รวม = 180 mL ในปริมาตร 500 mL",
        "ความเข้มข้น = 180/500 × 100 = 36% v/v",
      ],
    },
    {
      t: "Deaeration of viscous liquids",
      p: "ยาแขวนตะกอนรับประทานที่ใช้ xanthan gum ผลิตด้วย high-shear mixer พบฟองอากาศจำนวนมากค้างอยู่ ทำให้บรรจุขวดแบบ volumetric filling ได้ปริมาตรไม่สม่ำเสมอ และพบความแปรปรวนของปริมาณยาต่อขนาดรับประทาน แนวทางแก้ไขที่เหมาะสมที่สุดคือข้อใด",
      o: [
        "ทำ vacuum deaeration ก่อนบรรจุ และลดการดึงอากาศเข้า เช่น ผสมใต้ผิวของเหลว",
        "เพิ่มความเร็ว high-shear mixer ให้สูงขึ้นอีก",
        "เติม xanthan gum เพิ่มเพื่อให้ฟองคงตัวในเนื้อยา",
        "บรรจุขณะยังร้อนเพื่อให้ฟองขยายตัว",
        "เปลี่ยนเป็นบรรจุตามน้ำหนักโดยไม่ต้องแก้ปัญหาฟองอากาศ",
      ],
      a: 0,
      r: "อากาศที่ติดอยู่ในของเหลวหนืดลอยออกได้ช้ามาก (ตาม Stokes' law ความหนืดสูงทำให้ฟองลอยช้า) ทำให้ความหนาแน่นปรากฏและปริมาตรไม่สม่ำเสมอ บรรจุผิดปริมาตร และอากาศยังเร่ง oxidation ของตัวยาบางชนิด\n\nแนวทางคือออกแบบกระบวนการลดการดึงอากาศเข้า (ใช้ mixer จุ่มใต้ผิว ควบคุมความเร็ว เติมผงผ่านระบบที่ไม่ดูดอากาศ) และทำ vacuum deaeration ก่อนบรรจุ ซึ่งเป็นพารามิเตอร์ที่ควร validate ร่วมกับเวลาและความเร็วการผสม",
      w: [
        "ถูก — vacuum deaeration กำจัดอากาศ และการผสมใต้ผิวลดการดึงอากาศเข้า",
        "ความเร็วสูงขึ้นยิ่งทำให้ดึงอากาศเข้าเพิ่ม",
        "ความหนืดที่สูงขึ้นทำให้ฟองติดค้างนานขึ้น",
        "การบรรจุร้อนไม่ได้กำจัดอากาศ และอาจเปลี่ยนปริมาตรเมื่อเย็นลง",
        "แม้บรรจุตามน้ำหนัก ฟองอากาศยังทำให้ปริมาณยาต่อขนาดรับประทาน (ตามปริมาตร) ไม่สม่ำเสมอ",
      ],
      k: "ของเหลวหนืดดักอากาศ → ปริมาตร/ขนาดยาไม่สม่ำเสมอและ oxidation; แก้ด้วย vacuum deaeration",
      d: "medium",
      ref: "Lachman/Lieberman's The Theory and Practice of Industrial Pharmacy 4th ed. (Liquids)",
    },
    {
      t: "Ostwald ripening in suspension",
      p: "ยาแขวนตะกอนที่ตัวยาละลายน้ำได้เล็กน้อย ถูกขนส่งและเก็บในสภาวะที่อุณหภูมิขึ้นลงระหว่างกลางวันและกลางคืน หลัง 3 เดือนพบว่าอนุภาคขนาดใหญ่ขึ้น อนุภาคเล็กหายไป และตกตะกอนเร็วขึ้น ปรากฏการณ์และกลไกที่ถูกต้องคือข้อใด",
      o: [
        "Ostwald ripening — อนุภาคเล็กละลายได้มากกว่า ละลายตอนร้อนแล้วไปตกผลึกบนอนุภาคใหญ่ตอนเย็น",
        "Flocculation — อนุภาครวมตัวกันหลวมๆ จากแรงดึงดูด van der Waals",
        "Caking — อนุภาคเรียงตัวแน่นที่ก้นขวด",
        "Creaming — อนุภาคลอยขึ้นสู่ผิวเพราะเบากว่า vehicle",
        "Coalescence — อนุภาคหลอมรวมกันเป็นหยดใหญ่",
      ],
      a: 0,
      r: "ตามสมการ Ostwald–Freundlich อนุภาคขนาดเล็กมีความโค้งผิวสูงจึงมี solubility สูงกว่าอนุภาคใหญ่ เมื่ออุณหภูมิขึ้นลง (temperature cycling) อนุภาคเล็กละลายมากขึ้นตอนร้อน และเมื่อเย็นลงสารจะตกผลึกบนอนุภาคใหญ่ ทำให้การกระจายขนาดเลื่อนไปทางอนุภาคใหญ่\n\nผลคือตกตะกอนเร็วขึ้น ผิวสัมผัสหยาบ dissolution และ bioavailability อาจเปลี่ยน การป้องกันได้แก่ ใช้อนุภาคที่การกระจายขนาดแคบ เติมพอลิเมอร์ที่ดูดซับบนผิวผลึก (เช่น HPMC, PVP) เพื่อยับยั้งการโตของผลึก เลือกเกลือหรือรูปที่ละลายน้อย และควบคุมอุณหภูมิการเก็บ",
      w: [
        "ถูก — Ostwald ripening: ความต่างของ solubility ตามขนาด + temperature cycling ทำให้อนุภาคใหญ่โตขึ้น",
        "flocculation ไม่ได้ทำให้อนุภาคเดี่ยวโตขึ้นหรืออนุภาคเล็กหายไป",
        "caking คือการอัดแน่นของตะกอน ไม่ใช่การเปลี่ยนขนาดผลึก",
        "creaming เป็นปัญหาของอิมัลชันที่วัฏภาคภายในเบากว่า",
        "coalescence เป็นปรากฏการณ์ของหยดของเหลวในอิมัลชัน ไม่ใช่ผลึกของแข็ง",
      ],
      k: "Ostwald ripening: อนุภาคเล็กละลาย → ตกผลึกบนอนุภาคใหญ่; เร่งโดย temperature cycling; ยับยั้งด้วย polymer",
      d: "hard",
      ref: "Aulton's Pharmaceutics 6th ed. (Suspensions); Martin's Physical Pharmacy 7th ed.",
    },
    {
      t: "IVRT for semisolids",
      p: "ผู้ผลิตครีมเปลี่ยนผู้ผลิตวัตถุดิบ emulsifier (post-approval change) และต้องการทดสอบเปรียบเทียบการปลดปล่อยยาของครีมก่อนและหลังเปลี่ยน ข้อใดเป็นวิธีการและการวิเคราะห์ข้อมูลที่เหมาะสมที่สุด",
      o: [
        "In vitro release test ด้วย vertical diffusion cell (Franz cell) ผ่าน synthetic membrane แล้วพล็อตปริมาณยาสะสมกับรากที่สองของเวลา",
        "Dissolution test ด้วย USP Apparatus 2 แล้วพล็อตปริมาณยากับเวลาแบบ zero-order",
        "วัดความหนืดอย่างเดียวด้วย Brookfield viscometer",
        "Disintegration test ของครีมในน้ำ 37 °C",
        "วัด pH ของครีมก่อนและหลังเปลี่ยนเท่านั้น",
      ],
      a: 0,
      r: "In vitro release testing (IVRT) ของ semisolid ตามแนวทาง SUPAC-SS และ USP <1724> ใช้ vertical diffusion cell (Franz-type) โดยทาครีมบน synthetic inert membrane และเก็บตัวอย่างจาก receptor medium ที่อุณหภูมิประมาณ 32 °C (อุณหภูมิผิว)\n\nการปลดปล่อยจาก semisolid ที่ยาแขวนลอยหรือละลายในยาพื้นมักเป็นไปตาม Higuchi model ปริมาณยาสะสมต่อพื้นที่ (Q) แปรผันตรงกับ √t ความชันคือ release rate ที่ใช้เปรียบเทียบสูตร test กับ reference IVRT ไวต่อการเปลี่ยนแปลงสูตรหรือกระบวนการ จึงใช้รองรับ post-approval change ได้ ส่วนความหนืดเป็นเพียง QC ทางกายภาพที่ไม่สะท้อนการปลดปล่อยโดยตรง",
      w: [
        "ถูก — IVRT ด้วย vertical diffusion cell และวิเคราะห์ด้วย Higuchi (Q vs √t) เป็นแนวทาง SUPAC-SS/USP <1724>",
        "Apparatus 2 ออกแบบสำหรับ solid oral และการปลดปล่อยจาก semisolid ไม่เป็น zero-order โดยทั่วไป",
        "ความหนืดเป็น QC กายภาพ ไม่ได้วัดอัตราการปลดปล่อยยา",
        "ครีมไม่มีการแตกตัว (disintegration) จึงไม่ใช่การทดสอบที่เหมาะสม",
        "pH เป็นเพียงคุณสมบัติหนึ่ง ไม่ได้บอกการปลดปล่อยยา",
      ],
      k: "IVRT: Franz/vertical diffusion cell + synthetic membrane, ~32 °C; Q vs √t (Higuchi) → release rate",
      d: "hard",
      ref: "USP <1724> Semisolid Drug Products—Performance Tests; FDA SUPAC-SS Guidance (1997)",
    },
    {
      t: "Reconstitution to non-standard concentration",
      p: "ฉลากผงยาแขวนตะกอนระบุว่า 'เติมน้ำ 78 mL จะได้ยาแขวนตะกอน 100 mL ความแรง 125 mg/5 mL' แพทย์ต้องการความแรง 200 mg/5 mL จากขวดเดียวกัน ต้องเติมน้ำกี่ mL",
      o: ["22.0 mL", "40.5 mL", "48.8 mL", "62.5 mL", "78.0 mL"],
      a: 1,
      r: "ผงยาในขวดมีปริมาตรของตัวเอง (powder volume) = ปริมาตรสุดท้าย − น้ำที่เติม = 100 − 78 = 22 mL ปริมาณยาในขวด = 125 mg/5 mL × 100 mL = 2500 mg\n\nสำหรับความแรง 200 mg/5 mL (40 mg/mL) ปริมาตรสุดท้าย = 2500/40 = 62.5 mL จึงต้องเติมน้ำ = 62.5 − 22 = 40.5 mL ข้อผิดพลาดที่พบบ่อยคือการลืมหักปริมาตรผง หรือคำนวณน้ำโดยสัดส่วนตรง",
      w: [
        "เป็นปริมาตรของผงยา ไม่ใช่น้ำที่ต้องเติม",
        "ถูก — ปริมาตรสุดท้าย 62.5 mL − ปริมาตรผง 22 mL = 40.5 mL",
        "คิดสัดส่วนน้ำตรงๆ (78 × 62.5/100) โดยไม่แยกปริมาตรผง",
        "เป็นปริมาตรสุดท้ายของยาแขวนตะกอน ลืมหักปริมาตรผง",
        "เป็นปริมาตรน้ำตามฉลากซึ่งให้ความแรง 125 mg/5 mL",
      ],
      k: "Powder volume = ปริมาตรสุดท้าย − น้ำตามฉลาก; น้ำที่ต้องเติม = ปริมาตรสุดท้ายใหม่ − powder volume",
      d: "hard",
      ref: "Ansel HC, Pharmaceutical Calculations 15th ed. (Reconstitution of dry powders)",
      c: [
        "Powder volume = 100 − 78 = 22 mL",
        "ปริมาณยา = (125 mg/5 mL) × 100 mL = 2500 mg",
        "ปริมาตรสุดท้ายใหม่ = 2500 mg ÷ (200 mg/5 mL) = 62.5 mL",
        "น้ำที่ต้องเติม = 62.5 − 22 = 40.5 mL",
      ],
    },
  ],
];
