import type { Ip1MockDomainContent } from "@/lib/ip1-mock/types";

export const LIQUID: Ip1MockDomainContent = [
  // Mock Set 1
  [
    {
      t: "Simple syrup self-preservation",
      p: "Simple Syrup ตามตำรับ USP มีน้ำตาล sucrose 85% w/v ข้อใดอธิบายได้ถูกต้องที่สุดว่าเหตุใดตำรับนี้จึงไม่จำเป็นต้องเติม preservative",
      o: [
        "ความเข้มข้นน้ำตาลสูงทำให้ free water (water activity) ต่ำ จุลินทรีย์เจริญไม่ได้",
        "sucrose มีฤทธิ์ฆ่าเชื้อโดยตรงผ่านการทำลายผนังเซลล์แบคทีเรีย",
        "ความหนืดสูงของ syrup ทำให้จุลินทรีย์เคลื่อนที่ไม่ได้จึงตายไป",
        "pH ของ simple syrup ต่ำกว่า 3 จึงยับยั้งการเจริญของเชื้อ",
        "sucrose ถูก hydrolyze เป็น invert sugar ซึ่งเป็นสารกันเสียที่แรง",
      ],
      a: 0,
      r: "Simple syrup 85% w/v มีน้ำตาลเกือบอิ่มตัว น้ำส่วนใหญ่ถูกใช้ในการละลาย sucrose จึงเหลือ free water น้อยมาก (water activity ต่ำ) และเกิด osmotic pressure สูงที่ดึงน้ำออกจากเซลล์จุลินทรีย์ ตำรับจึงเป็น self-preserving\n\nหากเจือจาง syrup ลง (เช่นผสมกับยาน้ำอื่น) ความเข้มข้นน้ำตาลลดลงจะสูญเสียคุณสมบัตินี้และต้องเติม preservative เช่น parabens หรือ sodium benzoate ข้อควรระวังอีกอย่างคือการระเหยที่ผิวหน้าแล้วหยดน้ำกลั่นตัวกลับ ทำให้ผิวบนเจือจางและขึ้นราได้",
      w: [
        "ถูก — water activity ต่ำและ osmotic pressure สูงทำให้จุลินทรีย์ขาดน้ำและเจริญไม่ได้",
        "sucrose ไม่ใช่สารฆ่าเชื้อโดยตรง ผลยับยั้งเกิดจากผลเชิง osmotic ไม่ใช่การทำลายผนังเซลล์",
        "ความหนืดไม่ได้ฆ่าเชื้อ ยาน้ำหนืดหลายชนิดยังต้องการ preservative",
        "simple syrup มี pH ใกล้เป็นกลาง ไม่ได้ต่ำถึงระดับยับยั้งเชื้อ",
        "invert sugar ไม่ใช่สารกันเสีย และการ hydrolysis ยังทำให้เกิดสีน้ำตาล (caramelization) ได้ง่ายขึ้น",
      ],
      k: "Syrup ใกล้อิ่มตัว (85% w/v) self-preserving เพราะ free water ต่ำ — เจือจางเมื่อไรต้องเติม preservative",
      d: "easy",
      ref: "Remington: The Science and Practice of Pharmacy 22nd ed. (Solutions, Syrups)",
    },
    {
      t: "Stokes' law sedimentation velocity",
      p: "สูตรยาแขวนตะกอนมีอนุภาคยาขนาดเส้นผ่านศูนย์กลาง 20 µm ความหนาแน่น 1.5 g/cm³ กระจายใน vehicle ที่มีความหนาแน่น 1.1 g/cm³ และความหนืด 0.05 Pa·s (50 cP) จงคำนวณความเร็วการตกตะกอนตาม Stokes' law (g = 9.81 m/s²)",
      o: ["0.44 µm/s", "0.87 µm/s", "1.74 µm/s", "3.49 µm/s", "6.98 µm/s"],
      a: 2,
      r: "Stokes' law: v = d²(ρs − ρ0)g / 18η เมื่อ d คือเส้นผ่านศูนย์กลาง ต้องแปลงทุกหน่วยเป็น SI ก่อน คือ d = 20 × 10⁻⁶ m, Δρ = 400 kg/m³, η = 0.05 Pa·s\n\nแทนค่าได้ v ≈ 1.74 × 10⁻⁶ m/s หรือ 1.74 µm/s (ประมาณ 0.63 cm/h) สมการแสดงว่าการลดขนาดอนุภาค การลดผลต่างความหนาแน่น และการเพิ่มความหนืดของ vehicle ช่วยชะลอการตกตะกอน โดยขนาดอนุภาคมีผลมากที่สุดเพราะยกกำลังสอง ทั้งนี้ Stokes' law ใช้ได้กับ dilute suspension ที่อนุภาคทรงกลมไม่ชนกัน",
      w: [
        "ได้ค่านี้หากใช้รัศมี (10 µm) แทนเส้นผ่านศูนย์กลางในสูตรที่ใช้ d ซึ่งทำให้ค่าลดลง 4 เท่า",
        "ค่านี้เป็นครึ่งหนึ่งของคำตอบ เกิดจากการใช้ 36η หรือแทนค่าผิดสัดส่วน",
        "ถูก — v = (20×10⁻⁶)² × 400 × 9.81 / (18 × 0.05) = 1.74 × 10⁻⁶ m/s",
        "ได้ค่านี้หากใช้ 9η แทน 18η (สับสนกับสูตรรัศมี 2r²Δρg/9η แต่แทน d)",
        "ได้ค่านี้หากใช้สูตรรัศมีแต่แทน d ลงไปเป็น r ทำให้ค่าสูงเกิน 4 เท่า",
      ],
      k: "v = d²Δρg/18η (หรือ 2r²Δρg/9η) — ขนาดอนุภาคยกกำลังสองจึงเป็นตัวแปรที่ทรงอิทธิพลที่สุด",
      d: "hard",
      ref: "Aulton's Pharmaceutics 6th ed. (Suspensions); Martin's Physical Pharmacy 7th ed.",
      c: [
        "d² = (20 × 10⁻⁶ m)² = 4.0 × 10⁻¹⁰ m²",
        "Δρ = 1500 − 1100 = 400 kg/m³",
        "ตัวเศษ = 4.0 × 10⁻¹⁰ × 400 × 9.81 = 1.570 × 10⁻⁶",
        "ตัวส่วน = 18 × 0.05 = 0.9",
        "v = 1.570 × 10⁻⁶ / 0.9 = 1.74 × 10⁻⁶ m/s = 1.74 µm/s",
      ],
    },
    {
      t: "Sedimentation volume F",
      p: "ในการพัฒนาสูตรยาแขวนตะกอน เทยาแขวนตะกอน 50 mL ลงกระบอกตวงแล้วตั้งทิ้งไว้ เมื่อเข้าสู่สมดุลพบว่าชั้นตะกอนมีปริมาตร 35 mL ค่า sedimentation volume (F) ของสูตรนี้เท่ากับเท่าใด",
      o: ["0.30", "0.70", "1.00", "1.43", "1.70"],
      a: 1,
      r: "Sedimentation volume F = Vu/Vo เมื่อ Vu คือปริมาตรตะกอนที่สมดุล และ Vo คือปริมาตรยาแขวนตะกอนทั้งหมดก่อนตกตะกอน จึงได้ F = 35/50 = 0.70\n\nค่า F อยู่ระหว่าง 0–1 โดยทั่วไป ยิ่งเข้าใกล้ 1 ยิ่งดี (ตะกอนฟูเต็มภาชนะ ไม่เห็นชั้นใส) ค่า F > 1 เกิดได้ในระบบ flocculated ที่ floc ขยายตัวเกินปริมาตรเดิม ซึ่งต้องเติม vehicle เพิ่มเพื่อเก็บตะกอนไว้ในระบบ",
      w: [
        "เป็นค่า 1 − F คือสัดส่วนของชั้นใส ไม่ใช่ sedimentation volume",
        "ถูก — F = Vu/Vo = 35/50 = 0.70",
        "F = 1 หมายถึงไม่มีชั้นใสเลย (flocculation equilibrium) ซึ่งไม่ตรงกับข้อมูล",
        "เป็นค่า Vo/Vu ซึ่งคำนวณกลับด้าน",
        "ไม่มีวิธีคำนวณที่ถูกต้องให้ค่านี้จากข้อมูลที่กำหนด",
      ],
      k: "F = Vu/Vo; ยิ่งใกล้ 1 ยิ่งดี — ใช้เปรียบเทียบสูตรยาแขวนตะกอนเชิงกายภาพ",
      d: "medium",
      ref: "Martin's Physical Pharmacy and Pharmaceutical Sciences 7th ed. (Coarse Dispersions)",
      c: ["F = Vu / Vo", "F = 35 mL / 50 mL = 0.70"],
    },
    {
      t: "Emulsifier blend for required HLB",
      p: "ต้องการเตรียม O/W emulsion ซึ่ง oil phase มี required HLB 12 โดยใช้สารก่ออิมัลชันผสมรวม 5 g ระหว่าง Span 80 (HLB 4.3) และ Tween 80 (HLB 15.0) ต้องใช้สารแต่ละชนิดเท่าใด",
      o: [
        "Tween 80 3.60 g + Span 80 1.40 g",
        "Tween 80 1.40 g + Span 80 3.60 g",
        "Tween 80 2.50 g + Span 80 2.50 g",
        "Tween 80 4.00 g + Span 80 1.00 g",
        "Tween 80 3.00 g + Span 80 2.00 g",
      ],
      a: 0,
      r: "HLB ของสารผสมเป็นค่าเฉลี่ยถ่วงน้ำหนัก: HLBmix = fA·HLBA + (1−fA)·HLBB ให้ f = สัดส่วน Tween 80 จะได้ 12 = 15f + 4.3(1−f) → f = (12 − 4.3)/(15 − 4.3) = 0.72\n\nTween 80 = 0.72 × 5 = 3.60 g และ Span 80 = 1.40 g การใช้คู่ surfactant HLB ต่ำ+สูงมักให้ interfacial film ที่แน่นกว่าการใช้ตัวเดียว ทำให้อิมัลชันคงตัวดีกว่า ตรวจคำตอบได้ว่า HLB ต้องอยู่ใกล้ฝั่ง Tween เพราะ 12 ใกล้ 15 มากกว่า 4.3",
      w: [
        "ถูก — f(Tween) = 7.7/10.7 = 0.72 → 3.60 g และ Span 80 1.40 g ให้ HLB ผสม 12",
        "สลับปริมาณ ทำให้ HLB ผสม ≈ 7.3 เหมาะกับ W/O มากกว่า",
        "ผสม 1:1 ได้ HLB ≈ 9.65 ต่ำกว่าที่ต้องการ",
        "ได้ HLB ≈ 12.9 สูงเกิน required HLB",
        "ได้ HLB ≈ 10.7 ยังต่ำกว่า 12",
      ],
      k: "สัดส่วนตัว HLB สูง = (HLBreq − HLBต่ำ)/(HLBสูง − HLBต่ำ)",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed. (Emulsions); Griffin WC, J Soc Cosmet Chem 1949",
      c: [
        "f(Tween 80) = (12 − 4.3)/(15.0 − 4.3) = 7.7/10.7 = 0.72",
        "Tween 80 = 0.72 × 5 g = 3.60 g",
        "Span 80 = 5 − 3.60 = 1.40 g",
      ],
    },
    {
      t: "Emulsion type by dilution test",
      p: "เภสัชกรนำอิมัลชันที่ไม่ทราบชนิดหยดลงในน้ำ พบว่าอิมัลชันกระจายตัวเข้ากับน้ำได้ทันทีโดยไม่จับเป็นก้อน ข้อใดสรุปได้ถูกต้อง",
      o: [
        "เป็น O/W emulsion เพราะ external phase คือน้ำ",
        "เป็น W/O emulsion เพราะ internal phase คือน้ำ",
        "เป็น W/O emulsion เพราะน้ำแทรกเข้าไปใน oil phase ได้",
        "สรุปไม่ได้ ต้องวัดความหนืดก่อนทุกครั้ง",
        "เป็นอิมัลชันที่แตกชั้น (cracked) แล้ว",
      ],
      a: 0,
      r: "Dilution test อาศัยหลักว่าอิมัลชันจะเจือจางได้ด้วยของเหลวที่เป็น external (continuous) phase เท่านั้น ถ้าหยดลงน้ำแล้วกระจายตัวได้ แสดงว่า continuous phase เป็นน้ำ คือ O/W emulsion\n\nการทดสอบอื่นที่ใช้ร่วมได้ ได้แก่ conductivity test (O/W นำไฟฟ้า), dye solubility test (water-soluble dye เช่น amaranth กระจายทั่วใน O/W; oil-soluble dye เช่น Sudan III กระจายทั่วใน W/O) และ fluorescence test",
      w: [
        "ถูก — อิมัลชันเจือจางได้ด้วย external phase เมื่อเข้ากับน้ำได้จึงเป็น O/W",
        "W/O มีน้ำมันเป็น external phase จะไม่กระจายในน้ำแต่จะจับตัวเป็นหยด",
        "ตีความผิด การที่น้ำเข้ากันได้บ่งชี้ว่าน้ำเป็น continuous phase ไม่ใช่ internal",
        "ความหนืดไม่ใช่การทดสอบชนิดอิมัลชัน dilution test ใช้สรุปได้โดยตรง",
        "อิมัลชันที่ cracked จะเห็นชั้นน้ำมันแยก ไม่กระจายเป็นเนื้อเดียวกับน้ำ",
      ],
      k: "Dilution test: อิมัลชันผสมได้กับ external phase — เข้ากับน้ำ = O/W, เข้ากับน้ำมัน = W/O",
      d: "easy",
      ref: "Aulton's Pharmaceutics 6th ed. (Emulsions); Ansel's Pharmaceutical Dosage Forms 11th ed.",
    },
    {
      t: "Hydrocarbon (oleaginous) ointment base",
      p: "ผู้ป่วยผิวแห้งมากต้องการยาทาที่มี occlusive effect สูงสุดเพื่อเพิ่มความชุ่มชื้นของ stratum corneum และตัวยาเป็นสาร hydrolysis ง่าย ควรเลือกยาพื้นชนิดใดเหมาะสมที่สุด",
      o: [
        "White petrolatum (hydrocarbon base)",
        "Hydrophilic ointment (water-removable base)",
        "PEG ointment (water-soluble base)",
        "Vanishing cream แบบ O/W",
        "Carbomer hydrogel",
      ],
      a: 0,
      r: "Hydrocarbon (oleaginous) base เช่น white petrolatum, white ointment ไม่มีน้ำและแทบไม่ดูดน้ำ จึงเป็นยาพื้นที่ occlusive ที่สุด ลด transepidermal water loss ช่วย hydrate ผิวและเพิ่มการซึมผ่านของยาบางชนิด อีกทั้งไม่มีน้ำจึงเหมาะกับยาที่ไวต่อ hydrolysis\n\nข้อเสียคือเหนียวเหนอะหนะ ล้างน้ำออกยาก และรับน้ำ (ส่วนประกอบที่เป็นน้ำ) ได้น้อยมาก ส่วน base ชนิดอื่นที่มีน้ำหรือละลายน้ำได้ occlusive น้อยกว่า",
      w: [
        "ถูก — hydrocarbon base ไม่มีน้ำ occlusive สูงสุด และเหมาะกับยาที่ hydrolysis ง่าย",
        "เป็น O/W ที่มีน้ำ ล้างออกง่าย occlusive ต่ำกว่าและไม่เหมาะกับยาที่ไวต่อน้ำ",
        "PEG ละลายน้ำและดูดน้ำจากผิว ไม่ occlusive จึงไม่ช่วย hydrate ผิว",
        "vanishing cream มีน้ำมาก ระเหยเย็นสบายแต่ occlusive ต่ำ",
        "hydrogel มีน้ำเป็นส่วนใหญ่ ไม่ occlusive และไม่เหมาะกับยาที่ hydrolysis ง่าย",
      ],
      k: "Occlusion: hydrocarbon > absorption > W/O cream > O/W cream > water-soluble base",
      d: "medium",
      ref: "USP <1151> Pharmaceutical Dosage Forms (Ointments); Ansel's Pharmaceutical Dosage Forms 11th ed.",
    },
    {
      t: "Carbomer gel neutralization",
      p: "นักพัฒนาสูตรกระจาย carbomer 940 0.5% ในน้ำ ได้ของเหลวขุ่นเล็กน้อยและความหนืดต่ำ ขั้นตอนใดต่อไปจะทำให้เกิดเจลใสที่มีความหนืดสูงได้ดีที่สุด",
      o: [
        "เติม triethanolamine หรือ NaOH ปรับ pH ให้ประมาณ 6–7",
        "เติม HCl ปรับ pH ให้ต่ำกว่า 3",
        "เติม NaCl ปริมาณมากเพื่อเพิ่ม ionic strength",
        "ให้ความร้อนถึง 90 °C แล้วทิ้งให้เย็น",
        "เติม ethanol 70% เพื่อตกตะกอน polymer",
      ],
      a: 0,
      r: "Carbomer เป็น crosslinked polyacrylic acid ในน้ำมี pH ประมาณ 3 กลุ่ม –COOH ยังไม่แตกตัว สายโพลิเมอร์ขดตัว ความหนืดต่ำ เมื่อ neutralize ด้วยเบส (TEA, NaOH) กลุ่ม carboxyl แตกตัวเป็น –COO⁻ เกิดแรงผลักทางไฟฟ้า ทำให้สายโพลิเมอร์ยืดขยายและบวมน้ำ ความหนืดสูงขึ้นทันที ได้เจลใส\n\nความหนืดสูงสุดในช่วง pH ประมาณ 5–9 ระวังว่า electrolyte ปริมาณมาก หรือยาที่เป็น cationic จะลดความหนืดของ carbomer gel ได้ (screening ประจุ) และ carbomer ไวต่อ UV/ไอออนโลหะบางชนิด",
      w: [
        "ถูก — neutralization ทำให้ –COOH แตกตัว สายโพลิเมอร์ผลักกันและยืดตัว เกิดเจลหนืดใส",
        "การลด pH ทำให้ carbomer ยิ่งไม่แตกตัว ความหนืดไม่เพิ่ม",
        "electrolyte ทำ charge screening ลดความหนืดของ carbomer",
        "ความร้อนไม่ทำให้ carbomer เกิดเจล กลไกขึ้นกับการแตกตัวของประจุ",
        "ethanol ปริมาณมากไม่ช่วยให้เกิดเจลในน้ำ และไม่ได้ neutralize กลุ่มกรด",
      ],
      k: "Carbomer หนืดเมื่อ neutralize (pH ~6–7) ด้วย TEA/NaOH; เกลือและยาประจุบวกทำให้ความหนืดลดลง",
      d: "medium",
      ref: "Handbook of Pharmaceutical Excipients 9th ed. (Carbomer)",
    },
    {
      t: "Cocoa butter polymorphism on overheating",
      p: "ระหว่างเตรียม suppository ด้วย cocoa butter โดยวิธี fusion พนักงานหลอมยาพื้นจนใสหมดที่ 60 °C แล้วเทลงแม่พิมพ์ พบว่าแท่งยาแข็งตัวช้า ติดแม่พิมพ์ และเมื่อเก็บที่อุณหภูมิห้องบางแท่งอ่อนตัว สาเหตุที่น่าจะเป็นมากที่สุดคือข้อใด",
      o: [
        "ร้อนเกินทำให้ผลึกเสถียร β หายหมด เกิดผลึก metastable (α, β′) ที่จุดหลอมเหลวต่ำ",
        "ความร้อนทำให้ cocoa butter เกิด hydrolysis เป็นกรดไขมันอิสระ",
        "cocoa butter ดูดความชื้นจากอากาศขณะร้อนจึงอ่อนตัว",
        "ความร้อนทำให้ cocoa butter เกิด crosslink จึงแข็งตัวช้า",
        "ตัวยาระเหยออกไปหมดทำให้แท่งยาไม่แข็งแรง",
      ],
      a: 0,
      r: "Cocoa butter (theobroma oil) มี polymorphism ผลึกที่เสถียรคือ β form ซึ่งหลอมที่ประมาณ 34–35 °C หากหลอมที่อุณหภูมิสูงเกินจนผลึก β หายหมด เมื่อเย็นลงจะตกผลึกเป็น α และ β′ ซึ่งมีจุดหลอมต่ำ (ราว 18–28 °C) ทำให้แข็งตัวช้า ติดแม่พิมพ์ และอ่อนตัวที่อุณหภูมิห้อง กว่าจะเปลี่ยนกลับเป็น β ต้องใช้เวลาหลายวัน\n\nวิธีป้องกันคือหลอมอย่างช้าๆ ด้วย water bath ไม่เกินประมาณ 34–35 °C ให้ได้ลักษณะครีมข้นที่ยังมีผลึก β เหลือเป็น seed หรือใช้ hard fat (semi-synthetic glycerides) ที่ไม่มีปัญหา polymorphism ชัดเจน",
      w: [
        "ถูก — overheating ทำลาย seed ผลึก β ได้ polymorph metastable จุดหลอมต่ำ",
        "การให้ความร้อนช่วงสั้นไม่ทำให้เกิด hydrolysis มีนัยสำคัญ และไม่อธิบายการแข็งตัวช้า",
        "cocoa butter เป็นไขมันไม่ดูดความชื้น จึงไม่ใช่สาเหตุการอ่อนตัว",
        "triglyceride ใน cocoa butter ไม่เกิด crosslink จากความร้อนระดับนี้",
        "ปัญหาที่พบเป็นคุณสมบัติของยาพื้น ไม่ใช่การระเหยของตัวยา",
      ],
      k: "หลอม cocoa butter ไม่เกิน ~34–35 °C เพื่อรักษา seed β crystal; ร้อนเกิน → α/β′ จุดหลอมต่ำ",
      d: "hard",
      ref: "Aulton's Pharmaceutics 6th ed. (Rectal and vaginal drug delivery); Remington 22nd ed.",
    },
    {
      t: "Benzoic acid preservative pH dependence",
      p: "ยาน้ำเชื่อมตำรับหนึ่งใช้ sodium benzoate เป็น preservative หาก benzoic acid มี pKa 4.2 และตำรับมี pH 5.2 สัดส่วนของ benzoic acid ในรูป unionized (ซึ่งเป็นรูปที่มีฤทธิ์ต้านจุลชีพ) เป็นร้อยละเท่าใดโดยประมาณ",
      o: ["0.9%", "9.1%", "50%", "90.9%", "99.0%"],
      a: 1,
      r: "Weak acid preservative เช่น benzoic acid และ sorbic acid ออกฤทธิ์ในรูป unionized ซึ่งผ่านเยื่อหุ้มเซลล์จุลินทรีย์ได้ สัดส่วน unionized = 1/(1 + 10^(pH − pKa)) ที่ pH 5.2 ซึ่งสูงกว่า pKa 1 หน่วย จะได้ 1/(1 + 10) = 9.1%\n\nดังนั้นเมื่อ pH ของตำรับสูงขึ้น ฤทธิ์กันเสียของ benzoate ลดลงอย่างรวดเร็ว จึงนิยมใช้ในตำรับที่ pH ≤ 4.5 หากตำรับต้องมี pH ใกล้เป็นกลาง ควรเลือก parabens ซึ่งไม่แตกตัวในช่วง pH 4–8",
      w: [
        "ได้ค่านี้หาก pH สูงกว่า pKa 2 หน่วย ไม่ตรงกับโจทย์",
        "ถูก — 1/(1 + 10^(5.2−4.2)) = 1/11 = 9.1%",
        "เป็นค่าที่ pH = pKa เท่านั้น",
        "เป็นสัดส่วน ionized (คำนวณกลับด้าน)",
        "เป็นค่าที่ pH ต่ำกว่า pKa 2 หน่วย",
      ],
      k: "Benzoic/sorbic acid ออกฤทธิ์ในรูป unionized — ใช้ได้ดีใน pH ต่ำ (< ~4.5); pH ใกล้กลางเลือก parabens",
      d: "hard",
      ref: "Handbook of Pharmaceutical Excipients 9th ed. (Benzoic acid; Sodium benzoate)",
      c: [
        "fraction unionized = 1 / (1 + 10^(pH − pKa))",
        "= 1 / (1 + 10^(5.2 − 4.2)) = 1 / (1 + 10)",
        "= 0.0909 ≈ 9.1%",
      ],
    },
    {
      t: "Wetting of hydrophobic powder in suspension",
      p: "ขณะเตรียมยาแขวนตะกอนจากผงยาที่ไม่ชอบน้ำ (hydrophobic) พบว่าผงยาลอยเป็นแพบนผิวน้ำ มีฟองอากาศเกาะ และกระจายตัวไม่ได้ วิธีแก้ไขที่เหมาะสมที่สุดคือข้อใด",
      o: [
        "levigate ผงยากับ wetting agent เช่น glycerin หรือ polysorbate ปริมาณน้อยก่อนเติม vehicle",
        "เติม vehicle ทั้งหมดทีเดียวแล้วเขย่าแรงๆ เป็นเวลานาน",
        "เพิ่มขนาดอนุภาคยาเพื่อให้จมน้ำได้เร็วขึ้น",
        "เติม sucrose เพิ่มเพื่อเพิ่มความหนาแน่นของ vehicle",
        "ลดอุณหภูมิของ vehicle ลงเพื่อเพิ่มแรงตึงผิว",
      ],
      a: 0,
      r: "ผงยา hydrophobic มี contact angle กับน้ำสูง มีอากาศเคลือบผิวอนุภาค จึงลอยและจับกลุ่ม ต้องใช้ wetting agent เพื่อลด interfacial tension ระหว่างของแข็งกับของเหลว และแทนที่อากาศบนผิวอนุภาค\n\nWetting agent ที่ใช้ได้แก่ surfactant HLB ประมาณ 7–9 หรือ polysorbate ความเข้มข้นต่ำ และ cosolvent ที่ชอบน้ำ เช่น glycerin, propylene glycol, alcohol โดยนำมา levigate กับผงยาเป็นเพสต์ก่อน แล้วค่อยๆ เติม vehicle ต้องระวังการใช้ surfactant มากเกินเพราะทำให้เกิดฟองและอาจทำให้เป็น deflocculated system ที่ cake ง่าย",
      w: [
        "ถูก — wetting agent ลด contact angle และไล่อากาศจากผิวอนุภาค ทำให้กระจายตัวได้",
        "การเขย่าแรงไม่แก้ปัญหา contact angle สูง และยิ่งเพิ่มฟองอากาศ",
        "อนุภาคใหญ่ตกตะกอนเร็วขึ้นและไม่ได้ทำให้เปียกน้ำดีขึ้น",
        "sucrose ไม่ใช่ wetting agent และไม่แก้ปัญหาการลอยของผงที่ไม่เปียกน้ำ",
        "แรงตึงผิวที่สูงขึ้นยิ่งทำให้ wetting แย่ลง",
      ],
      k: "ผง hydrophobic ต้อง levigate กับ wetting agent (glycerin, PG, surfactant HLB ~7–9) ก่อนเติม vehicle",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed. (Suspensions); Allen LV, The Art, Science and Technology of Pharmaceutical Compounding",
    },
  ],
];
