import type { Ip1MockDomainContent } from "@/lib/ip1-mock/types";

export const NDDS: Ip1MockDomainContent = [
  // Mock Set 1 — ชุดที่ 1
  [
    {
      t: "HPMC hydrophilic matrix gel layer",
      p: "ยาเม็ดออกฤทธิ์นาน (extended-release) แบบ hydrophilic matrix ที่ใช้ HPMC K100M ประมาณ 30% w/w เมื่อสัมผัสของเหลวในทางเดินอาหาร กลไกหลักที่ควบคุมการปลดปล่อยยาคือข้อใด",
      o: [
        "HPMC ที่ผิวเม็ดดูดน้ำและพองตัวเป็นชั้น gel ยาละลายแล้วแพร่ผ่านชั้น gel ร่วมกับการกร่อน (erosion) ของ gel ด้านนอก",
        "แรงดัน osmotic ภายในเม็ดดันสารละลายยาออกทางรูที่เจาะด้วยเลเซอร์",
        "ยาแพร่ผ่านช่องว่าง (pore) ของโครงร่างที่ไม่ละลายน้ำซึ่งคงรูปตลอดทางเดินอาหาร",
        "ฟิล์มเคลือบที่ละลายเมื่อ pH สูงกว่า 5.5 ทำให้เม็ดยาแตกตัวในลำไส้เล็ก",
        "เอนไซม์ lipase ในลำไส้ย่อยสลายโครงร่างทำให้ยาถูกปลดปล่อยตามการย่อย",
      ],
      a: 0,
      r: "HPMC เป็น hydrophilic swellable polymer เมื่อเม็ดยาสัมผัสน้ำ polymer chain ที่ผิวจะ hydrate อย่างรวดเร็ว เกิดชั้น gel (gel layer) ที่หนืดล้อมรอบแกนแห้งด้านใน ชั้น gel นี้ทำหน้าที่เป็น diffusion barrier และป้องกันไม่ให้เม็ดแตกตัวทันที (ป้องกัน dose dumping)\n\nยาที่ละลายน้ำดีจะถูกปลดปล่อยส่วนใหญ่โดยการแพร่ผ่าน gel ส่วนยาที่ละลายน้ำน้อยจะออกมาด้วยการกร่อนของชั้น gel ด้านนอกที่ polymer chain คลายตัว (disentanglement) เป็นหลัก ปริมาณ HPMC ต้องเพียงพอ (โดยทั่วไปไม่น้อยกว่าประมาณ 20–30%) เพื่อให้ gel ต่อเนื่องเร็วพอ",
      w: [
        "ถูก — การเกิด gel layer ทำให้การปลดปล่อยถูกควบคุมด้วยทั้ง diffusion และ erosion ซึ่งเป็นลักษณะเฉพาะของ hydrophilic matrix",
        "เป็นกลไกของ osmotic pump ที่ต้องมี semipermeable membrane และ orifice ไม่ใช่ matrix ธรรมดา",
        "เป็นกลไกของ inert (insoluble) matrix เช่น ethylcellulose ซึ่งไม่พองตัวเป็น gel",
        "เป็นกลไกของ enteric (delayed-release) coating ซึ่งไม่ได้ยืดระยะเวลาการปลดปล่อย",
        "การย่อยด้วย lipase เกี่ยวกับ lipid matrix บางชนิด ไม่ใช่ HPMC ซึ่งเป็น cellulose ether ที่ไม่ถูกเอนไซม์ในลำไส้ย่อย",
      ],
      k: "HPMC matrix: hydration → gel layer → diffusion (ยาละลายดี) + erosion (ยาละลายน้อย)",
      d: "easy",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Modified-release oral drug delivery",
    },
    {
      t: "Korsmeyer-Peppas exponent for cylinder",
      p: "ยาเม็ด HPMC matrix รูปทรงกระบอก ปลดปล่อยยา (Mt/M∞) ได้ 0.20 ที่ 1 ชั่วโมง และ 0.40 ที่ 4 ชั่วโมง เมื่อวิเคราะห์ด้วย Korsmeyer–Peppas model (Mt/M∞ = k·tⁿ) ข้อใดแปลผลได้ถูกต้องที่สุด",
      o: [
        "n = 0.50 สำหรับรูปทรงกระบอกจัดเป็น anomalous (non-Fickian) transport คือ diffusion ร่วมกับ polymer relaxation/swelling",
        "n = 0.50 จัดเป็น Fickian diffusion อย่างสมบูรณ์เสมอไม่ว่าจะเป็นรูปทรงใด",
        "n = 1.00 จัดเป็น Case II transport ให้การปลดปล่อยแบบ zero-order",
        "n = 0.25 แสดงว่าการปลดปล่อยถูกควบคุมด้วย erosion อย่างเดียว",
        "n = 2.00 จัดเป็น Super Case II transport",
      ],
      a: 0,
      r: "สมการ Korsmeyer–Peppas ใช้กับข้อมูลช่วงต้น (Mt/M∞ ≤ 0.6) หาค่า n จาก log(Mt/M∞) = log k + n log t ได้ n = log(0.40/0.20)/log(4/1) = 0.301/0.602 = 0.50\n\nเกณฑ์แปลผลขึ้นกับรูปทรง: แผ่นบาง (thin film) n = 0.5 คือ Fickian, 0.5–1.0 anomalous, 1.0 Case II; ทรงกระบอก n = 0.45 คือ Fickian, 0.45 < n < 0.89 anomalous, 0.89 Case II; ทรงกลม 0.43 และ 0.85 ตามลำดับ ดังนั้นสำหรับเม็ดทรงกระบอก n = 0.50 จึงอยู่ในช่วง anomalous transport ซึ่งสอดคล้องกับ HPMC ที่ทั้งแพร่และพองตัว",
      w: [
        "ถูก — n = 0.50 อยู่ระหว่าง 0.45 และ 0.89 ของทรงกระบอก จึงเป็น anomalous transport (diffusion + relaxation)",
        "n = 0.5 เป็น Fickian เฉพาะ thin film; ทรงกระบอกใช้ค่าตัด 0.45",
        "คำนวณผิด ข้อมูลเพิ่มขึ้น 2 เท่าเมื่อเวลาเพิ่ม 4 เท่า ไม่ใช่เพิ่มตามเวลาแบบเส้นตรง",
        "คำนวณผิดและค่า n < 0.45 ไม่ได้หมายถึง erosion-controlled",
        "คำนวณผิด ข้อมูลไม่ได้เพิ่มแบบกำลังสองของเวลา",
      ],
      k: "Peppas: ทรงกระบอก 0.45 / 0.89, แผ่นบาง 0.5 / 1.0, ทรงกลม 0.43 / 0.85 — ใช้กับ Mt/M∞ ≤ 60%",
      d: "hard",
      ref: "Ritger PL, Peppas NA. J Control Release 1987;5:23–36 & 37–42",
      c: [
        "log(Mt/M∞) = log k + n·log t",
        "n = log(0.40/0.20) / log(4/1) = 0.301 / 0.602 = 0.50",
        "ทรงกระบอก: 0.45 < 0.50 < 0.89 → anomalous transport",
      ],
    },
    {
      t: "Zero-order maintenance release rate",
      p: "ต้องการออกแบบยาเม็ด extended-release ที่ปลดปล่อยแบบ zero-order เพื่อรักษาระดับยาในพลาสมาที่ steady state (Css) = 5 mg/L ยามี clearance = 4 L/h และ F = 1 อัตราการปลดปล่อยยา (k0) ที่ต้องการคือเท่าใด",
      o: ["1.25 mg/h", "5 mg/h", "20 mg/h", "60 mg/h", "240 mg/h"],
      a: 2,
      r: "ที่ steady state อัตราที่ยาเข้าสู่ร่างกายต้องเท่ากับอัตราการกำจัด เมื่อการปลดปล่อยเป็น rate-limiting step และ F = 1 จะได้ k0 = Css × CL = 5 mg/L × 4 L/h = 20 mg/h\n\nหลักนี้คือแนวคิดพื้นฐานของการออกแบบ ER ที่ต้องการให้ระบบนำส่งทำตัวเหมือน IV infusion ถ้าต้องการให้ครอบคลุม 12 ชั่วโมงก็ต้องบรรจุยาส่วน maintenance 20 × 12 = 240 mg (ไม่รวม loading dose)",
      w: [
        "เกิดจากการหาร Css ด้วย CL (5/4) ซึ่งไม่ถูกต้องตามมิติ",
        "เป็นค่า Css ไม่ใช่อัตราการปลดปล่อย",
        "ถูก — k0 = Css × CL = 5 × 4 = 20 mg/h",
        "เป็นการคูณกับเวลา 3 ชั่วโมงโดยไม่มีเหตุผล",
        "240 mg คือปริมาณยาที่ต้องปลดปล่อยใน 12 ชั่วโมง ไม่ใช่อัตราต่อชั่วโมง",
      ],
      k: "Zero-order ER: k0 = Css × CL / F (เหมือน infusion rate)",
      d: "medium",
      ref: "Shargel L, Yu A. Applied Biopharmaceutics & Pharmacokinetics 7th ed., Ch. Modified-release drug products",
      c: ["k0 = Css × CL / F", "k0 = 5 mg/L × 4 L/h / 1 = 20 mg/h"],
    },
    {
      t: "Eudragit L100-55 dissolution pH",
      p: "ต้องการเคลือบเม็ดยา pantoprazole ให้ทนกรดในกระเพาะอาหารและเริ่มปลดปล่อยยาที่ duodenum (pH ประมาณ 5.5–6) polymer ชนิดใดเหมาะสมที่สุด",
      o: [
        "Eudragit L100-55 (methacrylic acid–ethyl acrylate copolymer 1:1)",
        "Eudragit E100 (aminoalkyl methacrylate copolymer)",
        "Eudragit RS 100 (ammonio methacrylate copolymer type B)",
        "Eudragit S100 (methacrylic acid–methyl methacrylate copolymer 1:2)",
        "Eudragit NE 30 D (neutral ethyl acrylate–methyl methacrylate copolymer)",
      ],
      a: 0,
      r: "Enteric polymer ประเภท anionic methacrylate มีหมู่ carboxylic acid ซึ่งไม่แตกตัวและไม่ละลายใน pH ต่ำ แต่แตกตัวและละลายเมื่อ pH สูงกว่าค่าเฉพาะ: Eudragit L100-55 / L30 D-55 ละลายที่ pH > 5.5 (duodenum), L100 ที่ pH > 6.0 และ S100 / FS 30 D ที่ pH > 7.0 (ileum ส่วนปลาย/colon)\n\nEudragit E ละลายใน pH < 5 จึงใช้กันความชื้น/กลบรส ส่วน RS, RL และ NE ไม่ละลายทุก pH ใช้เป็น release-controlling membrane สำหรับ sustained release",
      w: [
        "ถูก — L100-55 ละลายที่ pH > 5.5 เหมาะกับการปลดปล่อยที่ duodenum",
        "E100 เป็น cationic polymer ละลายในกระเพาะ (pH < 5) จึงทำตรงข้ามกับ enteric",
        "RS 100 ไม่ละลายทุก pH ใช้ควบคุมการปลดปล่อยแบบ sustained ไม่ใช่ enteric",
        "S100 ละลายที่ pH > 7 ปลดปล่อยช้าเกินไป เหมาะกับ ileum/colon",
        "NE 30 D เป็น neutral polymer ไม่มีหมู่ที่แตกตัว จึงไม่ละลายตาม pH",
      ],
      k: "Eudragit: E < pH 5 | L100-55 > 5.5 | L100 > 6 | S100/FS > 7 | RL/RS/NE ไม่ละลาย",
      d: "easy",
      ref: "Evonik EUDRAGIT® technical information; Handbook of Pharmaceutical Excipients 9th ed. (Polymethacrylates)",
    },
    {
      t: "Transdermal steady-state flux calculation",
      p: "ทดสอบการซึมผ่าน membrane แบบ Franz cell ภายใต้ sink condition ยามี diffusion coefficient ในเมมเบรน (D) = 1 × 10⁻⁸ cm²/s, partition coefficient (K) = 0.5, ความเข้มข้นใน donor = 10 mg/mL และเมมเบรนหนา 20 µm ค่า steady-state flux (Jss) ใกล้เคียงข้อใดที่สุด",
      o: ["0.025 µg/cm²/h", "9 µg/cm²/h", "45 µg/cm²/h", "90 µg/cm²/h", "180 µg/cm²/h"],
      a: 3,
      r: "จาก Fick's first law ที่ steady state Jss = D·K·Cd / h (เมื่อ receptor เป็น sink) แปลงหน่วยให้สอดคล้อง: h = 20 µm = 0.002 cm, Cd = 10 mg/mL = 10 mg/cm³\n\nJss = (1×10⁻⁸ × 0.5 × 10) / 0.002 = 2.5×10⁻⁵ mg/cm²/s แปลงเป็นต่อชั่วโมง ×3600 = 0.09 mg/cm²/h = 90 µg/cm²/h ข้อสังเกตสำคัญคือ flux แปรผันตรงกับ K และ Cd และแปรผกผันกับความหนา ดังนั้นการเพิ่ม thermodynamic activity ของยาในตำรับ (ใกล้ saturation) จึงเพิ่ม flux ได้",
      w: [
        "ลืมคูณ 3600 และแปลงหน่วย mg เป็น µg ไม่ถูกต้อง",
        "แปลงหน่วยความหนาหรือเวลาผิด ทำให้ค่าต่ำเกิน 10 เท่า",
        "คูณด้วย K ซ้ำสองครั้ง (0.5 × 0.5) ทำให้ได้ครึ่งหนึ่งของค่าจริง",
        "ถูก — Jss = DKC/h = 2.5×10⁻⁵ mg/cm²/s = 90 µg/cm²/h",
        "ลืมคูณ partition coefficient (K = 0.5)",
      ],
      k: "Jss = D·K·Cd / h — แปลง µm → cm และ s → h ให้ถูก; flux ∝ thermodynamic activity",
      d: "hard",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Transdermal drug delivery; Martin's Physical Pharmacy 7th ed., Ch. Diffusion",
      c: [
        "h = 20 µm = 0.002 cm; Cd = 10 mg/cm³",
        "Jss = (1×10⁻⁸ cm²/s × 0.5 × 10 mg/cm³) / 0.002 cm = 2.5×10⁻⁵ mg/cm²/s",
        "× 3600 s/h = 0.09 mg/cm²/h = 90 µg/cm²/h",
      ],
    },
    {
      t: "MMAD and regional lung deposition",
      p: "ผลิตภัณฑ์ยาสูดพ่นตัวหนึ่งต้องการให้ยาเข้าถึงหลอดลมส่วนปลายและถุงลม (lower airways) ได้มากที่สุด ควรออกแบบให้อนุภาคมี mass median aerodynamic diameter (MMAD) อยู่ในช่วงใด",
      o: [
        "ประมาณ 1–5 µm",
        "ประมาณ 10–20 µm",
        "ประมาณ 5–10 µm",
        "น้อยกว่า 0.1 µm",
        "มากกว่า 30 µm",
      ],
      a: 0,
      r: "การตกค้างของอนุภาคในทางเดินหายใจขึ้นกับ aerodynamic diameter เป็นหลัก อนุภาค > 10 µm ตกที่ oropharynx ด้วย inertial impaction; 5–10 µm ตกที่ทางเดินหายใจส่วนบน/หลอดลมใหญ่; 1–5 µm (fine particles) เข้าถึงหลอดลมส่วนปลายและถุงลมด้วย sedimentation; อนุภาคเล็กมาก (< 0.5–1 µm) จำนวนมากถูกหายใจออกเพราะไม่ตกค้าง แม้อนุภาคระดับ nanometer จะตกค้างด้วย diffusion ได้บ้าง\n\nดังนั้นตำรับยาสูดส่วนใหญ่ออกแบบให้ MMAD อยู่ราว 1–5 µm และวัดด้วย cascade impactor",
      w: [
        "ถูก — ช่วง 1–5 µm คือ respirable fraction ที่เข้าถึงทางเดินหายใจส่วนล่างได้ดี",
        "อนุภาคขนาดนี้ตกที่คอและปากด้วย impaction เป็นส่วนใหญ่",
        "ตกที่ทางเดินหายใจส่วนต้นและหลอดลมใหญ่ ไม่ถึงถุงลม",
        "อนุภาคเล็กมากส่วนหนึ่งตกด้วย diffusion แต่จำนวนมากถูกหายใจออกและบรรจุมวลยาได้น้อย",
        "ใหญ่เกินไป ติดที่ปากและลำคอเกือบทั้งหมด",
      ],
      k: "> 10 µm ปาก/คอ | 5–10 µm ทางเดินหายใจส่วนบน | 1–5 µm ลึกถึงหลอดลมเล็ก/ถุงลม | < 1 µm หายใจออก",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Pulmonary drug delivery; USP <601>",
    },
    {
      t: "PLGA composition and degradation rate",
      p: "ทีมพัฒนาไมโครสเฟียร์ PLGA สำหรับ peptide ต้องการให้ polymer ย่อยสลายและปลดปล่อยยาหมดเร็วที่สุด (ประมาณ 1 เดือน) ควรเลือก PLGA แบบใด",
      o: [
        "PLGA 50:50 (lactide:glycolide) น้ำหนักโมเลกุลต่ำ ปลายสายเป็น free carboxylic acid",
        "PLGA 85:15 น้ำหนักโมเลกุลสูง ปลายสายเป็น ester (end-capped)",
        "PLA (100% lactide) น้ำหนักโมเลกุลสูง",
        "PLGA 75:25 น้ำหนักโมเลกุลสูง ปลายสายเป็น ester (end-capped)",
        "PLGA 50:50 น้ำหนักโมเลกุลสูง ปลายสายเป็น ester (end-capped)",
      ],
      a: 0,
      r: "PLGA ย่อยสลายด้วย hydrolysis ของ ester bond แบบ bulk erosion อัตราการย่อยสลายขึ้นกับ (1) สัดส่วน lactide:glycolide — lactide มีหมู่ methyl ที่ hydrophobic กว่า สัดส่วน lactide สูงจะดูดน้ำน้อยและย่อยช้า โดย 50:50 ย่อยเร็วที่สุดเพราะเป็น amorphous และ hydrophilic พอสมควร (2) น้ำหนักโมเลกุล — ต่ำย่อยเร็วกว่า (3) ปลายสาย — acid-terminated ดูดน้ำได้ดีกว่าและกรดที่ปลายเร่ง autocatalysis จึงย่อยเร็วกว่า ester end-capped\n\nผลิตภัณฑ์ระยะ 1 เดือนจึงมักใช้ PLGA 50:50 MW ต่ำ ส่วนระยะ 3–6 เดือนใช้ 75:25 หรือ 85:15 หรือ PLA",
      w: [
        "ถูก — 50:50, MW ต่ำ และ acid end group ล้วนเร่ง hydrolysis จึงย่อยสลายเร็วที่สุด",
        "lactide สูง MW สูงและ end-capped ทำให้ย่อยช้าเหมาะกับระยะหลายเดือน",
        "PLA hydrophobic และอาจมีความเป็นผลึก (L-PLA) ย่อยสลายช้ามาก",
        "75:25 MW สูงย่อยช้ากว่า 50:50 อย่างชัดเจน",
        "แม้เป็น 50:50 แต่ MW สูงและ end-capped จึงช้ากว่าตัวเลือกที่ถูก",
      ],
      k: "PLGA ย่อยเร็ว: 50:50 > 75:25 > 85:15 > PLA; MW ต่ำ และ acid-terminated เร็วกว่า",
      d: "medium",
      ref: "Makadia HK, Siegel SJ. Polymers 2011;3:1377–1397; Aulton's Pharmaceutics 6th ed.",
    },
    {
      t: "Push-pull osmotic pump design",
      p: "ต้องการพัฒนายาเม็ด osmotic ปลดปล่อยแบบ zero-order สำหรับยาที่ละลายน้ำได้น้อยมาก (เช่น nifedipine) การออกแบบแบบใดเหมาะสมที่สุด",
      o: [
        "Push-pull osmotic pump: เม็ด 2 ชั้น (drug layer + push layer ที่มี polyethylene oxide และ osmotic agent) เคลือบ semipermeable membrane และเจาะรูด้าน drug layer",
        "Elementary osmotic pump แกนยาชั้นเดียว อาศัยยาเป็น osmotic agent เอง",
        "Hydrophilic matrix HPMC ไม่มีฟิล์มเคลือบ",
        "เคลือบด้วย Eudragit L100-55 ให้ละลายใน duodenum",
        "เม็ดแกนยาเคลือบ semipermeable membrane โดยไม่เจาะรู",
      ],
      a: 0,
      r: "Elementary osmotic pump (EOP) อาศัยการที่ยาละลายเป็นสารละลายอิ่มตัวในแกนเพื่อสร้าง osmotic pressure จึงเหมาะกับยาที่ละลายน้ำได้ปานกลางถึงดี ยาที่ละลายน้ำน้อยมากจะสร้างแรงดันได้ไม่พอและออกทางรูได้น้อย\n\nPush-pull osmotic pump (เช่น nifedipine GITS) แก้ปัญหานี้: น้ำซึมผ่าน cellulose acetate membrane เข้าสู่ทั้งสองชั้น ชั้นยาจะกลายเป็น suspension ที่ไหลได้ ส่วน push layer ที่มี polyethylene oxide MW สูงและ NaCl จะพองตัวดันยาออกทางรูด้านชั้นยาด้วยอัตราคงที่ จึงได้ zero-order ที่ไม่ขึ้นกับ pH และการบีบตัวของทางเดินอาหาร",
      w: [
        "ถูก — push layer ที่พองตัวดัน drug suspension ออกทาง orifice ทำให้ยาละลายน้ำน้อยปลดปล่อยแบบ zero-order ได้",
        "EOP ต้องการยาที่ละลายน้ำได้พอสร้าง osmotic pressure ยาละลายน้ำน้อยมากจึงปลดปล่อยไม่สมบูรณ์",
        "HPMC matrix มักให้การปลดปล่อยแบบ diffusion/erosion ที่ไม่เป็น zero-order อย่างแท้จริงและไวต่อสภาวะทางเดินอาหารมากกว่า",
        "Enteric coating เป็น delayed-release ไม่ได้ทำให้ปลดปล่อยแบบ zero-order",
        "ไม่มี orifice ยาจะออกไม่ได้ หรือเมมเบรนแตกจากแรงดันแบบควบคุมไม่ได้",
      ],
      k: "ยาละลายน้ำน้อย → push-pull (2 ชั้น, PEO push layer); ยาละลายดี → EOP ได้",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed.; Theeuwes F. J Pharm Sci 1975;64:1987; Swanson DR et al. Am J Med 1987;83(6B):3–9",
    },
    {
      t: "Alcohol-induced dose dumping",
      p: "ยาแคปซูล opioid ชนิด extended-release รายหนึ่งถูกถอนออกจากตลาดหลังพบว่าเมื่อรับประทานร่วมกับเครื่องดื่มแอลกอฮอล์ ระดับยาสูงสุดในเลือดเพิ่มขึ้นหลายเท่า สาเหตุทางเภสัชกรรมที่สำคัญที่สุดคือข้อใด",
      o: [
        "Polymer หรือส่วนประกอบที่ควบคุมการปลดปล่อยละลายหรือเสียสภาพใน ethanol ทำให้ยาที่ตั้งใจปลดปล่อยใน 24 ชั่วโมงหลุดออกมาเกือบทั้งหมดในเวลาสั้น (dose dumping)",
        "Ethanol ยับยั้ง CYP3A4 อย่างแรง ทำให้ clearance ของยาลดลง",
        "Ethanol เพิ่ม gastric pH ทำให้ enteric coating ละลายก่อนเวลา",
        "Ethanol ทำให้กระเพาะอาหารบีบตัวช้า ยาจึงอยู่ในกระเพาะนานขึ้น",
        "Ethanol ทำให้ยาตกผลึกภายในแคปซูลและดูดซึมช้าลง",
      ],
      a: 0,
      r: "กรณีศึกษาสำคัญคือ hydromorphone ER capsule (Palladone) ซึ่งถูกระงับการจำหน่ายในปี 2005 เพราะ ethanol ทำให้กลไกควบคุมการปลดปล่อยล้มเหลว ยาจึงถูกปลดปล่อยออกมาเกือบหมดในคราวเดียว (dose dumping) ซึ่งอันตรายมากกับยาที่มีดัชนีการรักษาแคบและบรรจุปริมาณยามากสำหรับทั้งวัน\n\nPolymer หลายชนิดที่ใช้ใน ER เช่น ethylcellulose และ ammonio methacrylate copolymer ละลายได้ใน ethanol ความเข้มข้นสูง ผู้พัฒนาจึงต้องประเมินความทนทานต่อ ethanol ในหลอดทดลอง (เช่น 5–40% ethanol) และเลือกระบบที่ทน เช่น matrix ที่ใช้ polymer ที่ไม่ละลายใน ethanol ร่วมกับการให้คำแนะนำผู้ป่วยหลีกเลี่ยงแอลกอฮอล์",
      w: [
        "ถูก — dose dumping เกิดจาก ethanol ทำลายกลไกควบคุมการปลดปล่อยของตำรับ ไม่ใช่ PK interaction",
        "ethanol แบบ acute ไม่ได้เป็น strong CYP3A4 inhibitor และไม่ได้อธิบาย Cmax ที่เพิ่มเป็นหลายเท่าอย่างรวดเร็ว",
        "ethanol ไม่ได้เพิ่ม gastric pH อย่างมีนัยสำคัญ และตำรับนี้ไม่ใช่ enteric product",
        "การชะลอ gastric emptying จะทำให้ Cmax ลดลงหรือช้าลง ไม่ใช่เพิ่มขึ้นหลายเท่า",
        "การตกผลึกจะลดการดูดซึม ซึ่งตรงข้ามกับเหตุการณ์ที่เกิดขึ้น",
      ],
      k: "ER ที่บรรจุยาปริมาณมาก ต้องทดสอบ alcohol dose dumping (in vitro ใน ethanol 5–40%) — บทเรียนจาก Palladone",
      d: "hard",
      ref: "US FDA Alert: Palladone (hydromorphone) ER capsules, July 2005; Meyer RJ, Hussain AS. AAPS J 2005",
    },
    {
      t: "SEDDS composition and self-emulsification",
      p: "บริษัทต้องการเพิ่มชีวประสิทธิผลของยาที่มี log P = 5 และละลายน้ำได้น้อยมาก โดยพัฒนาเป็น self-emulsifying drug delivery system (SEDDS) บรรจุใน soft gelatin capsule ข้อใดอธิบายระบบนี้ได้ถูกต้องที่สุด",
      o: [
        "เป็นของผสมเนื้อเดียวที่ไม่มีน้ำของ oil, surfactant และ co-solvent ซึ่งเมื่อพบของเหลวในทางเดินอาหารและการบีบตัวเบาๆ จะเกิด emulsion ละเอียดได้เองโดยยายังอยู่ในสภาพละลาย",
        "เป็น o/w emulsion ที่เตรียมสำเร็จแล้วด้วย high-pressure homogenizer ก่อนบรรจุแคปซูล",
        "เป็นอนุภาคไขมันของแข็งที่ยาฝังอยู่ในผลึกไขมัน ปลดปล่อยด้วยการกร่อน",
        "เป็นผงยาผสม polymer ในสภาพอสัณฐานที่เตรียมด้วยการหลอม",
        "เป็นสารละลายยาในน้ำที่ใช้ cyclodextrin เป็นตัวช่วยละลาย",
      ],
      a: 0,
      r: "SEDDS คือ isotropic mixture ของน้ำมัน (เช่น medium-chain triglyceride) surfactant ที่มี HLB สูง (เช่น polysorbate 80, polyoxyl 35 castor oil) และ co-solvent (เช่น ethanol, PEG, propylene glycol) โดยไม่มีน้ำ ยาละลายอยู่ใน preconcentrate เมื่อสัมผัสของเหลวในทางเดินอาหารพร้อมการบีบตัวเพียงเล็กน้อยจะเกิด emulsion ละเอียดเอง ช่วยหลีกเลี่ยงขั้นตอน dissolution ที่เป็น rate-limiting step ของยา BCS class II\n\nนอกจากนี้ lipid ยังกระตุ้นการหลั่งน้ำดี เกิด mixed micelle และอาจส่งเสริม lymphatic transport สำหรับยาที่ lipophilic มาก ตัวอย่างผลิตภัณฑ์ได้แก่ cyclosporine microemulsion preconcentrate",
      w: [
        "ถูก — SEDDS เป็น anhydrous preconcentrate ที่ emulsify ได้เองในร่างกาย โดยยายังอยู่ในรูปละลาย",
        "SEDDS ไม่ได้ทำ emulsion ไว้ก่อน และการมีน้ำปริมาณมากไม่เข้ากับ soft gelatin capsule",
        "เป็นคำอธิบายของ solid lipid nanoparticle (SLN) ไม่ใช่ SEDDS",
        "เป็นคำอธิบายของ amorphous solid dispersion โดย hot-melt extrusion",
        "เป็นแนวทางเพิ่มการละลายด้วย inclusion complex ไม่ใช่ lipid-based self-emulsifying system",
      ],
      k: "SEDDS = oil + surfactant (HLB สูง) + co-solvent, ไม่มีน้ำ, emulsify เองในทางเดินอาหาร → ข้าม dissolution step",
      d: "medium",
      ref: "Pouton CW. Eur J Pharm Sci 2006;29:278–287; Aulton's Pharmaceutics 6th ed.",
    },
  ],
  // Mock Set 2 — ชุดที่ 2
  [
    {
      t: "Inert matrix ghost in stool",
      p: "ผู้ป่วยรายหนึ่งแจ้งเภสัชกรว่าพบเม็ดยาลักษณะคล้ายเม็ดเดิมในอุจจาระหลังรับประทานยาเม็ด extended-release ซึ่งผลิตเป็น insoluble (inert) matrix จาก ethylcellulose เภสัชกรควรอธิบายอย่างไรเหมาะสมที่สุด",
      o: [
        "เป็นโครงร่าง (ghost matrix) ที่ไม่ละลายน้ำ ยาถูกแพร่ออกผ่านช่องว่างและรูพรุนแล้ว จึงเป็นเรื่องปกติของตำรับชนิดนี้",
        "ยาไม่ถูกปลดปล่อยเลย ต้องหยุดยาและเปลี่ยนเป็นยาฉีดทันที",
        "แสดงว่าเกิด dose dumping ยาถูกปลดปล่อยหมดในกระเพาะอาหาร",
        "เป็นชั้น gel ของ HPMC ที่ยังไม่ถูกกร่อน แสดงว่าผู้ป่วยดื่มน้ำน้อยเกินไป",
        "เกิดจากผู้ป่วยเคี้ยวเม็ดยาก่อนกลืน",
      ],
      a: 0,
      r: "Inert matrix ใช้ polymer ที่ไม่ละลายน้ำ เช่น ethylcellulose, ammonio methacrylate copolymer หรือ polyvinyl acetate เป็นโครงร่าง ของเหลวซึมเข้าไปละลายยา แล้วยาแพร่ออกผ่าน pore และ channel ที่เกิดจากการละลายของยาและสารเติมแต่งที่ละลายน้ำ การปลดปล่อยมักเป็นไปตาม Higuchi model ที่มีพารามิเตอร์ porosity (ε) และ tortuosity (τ)\n\nเมื่อยาออกหมดแล้ว โครงร่างที่ว่างเปล่ายังคงรูปและถูกขับออกทางอุจจาระ (ghost tablet) ซึ่งไม่ใช่ความล้มเหลวของการรักษา แต่ถ้าผู้ป่วยมีอาการไม่ตอบสนองต่อยาหรือมีภาวะ GI transit เร็วผิดปกติ (เช่น ท้องเสียรุนแรง) ควรประเมินเพิ่มเติม",
      w: [
        "ถูก — insoluble matrix คงรูปหลังยาแพร่ออกหมด จึงพบ ghost matrix ในอุจจาระได้ตามปกติ",
        "การพบโครงร่างไม่ได้หมายความว่ายาไม่ถูกปลดปล่อย จึงไม่ต้องหยุดยา",
        "dose dumping คือการปลดปล่อยยาเร็วผิดปกติ ไม่เกี่ยวกับการพบโครงร่างในอุจจาระ",
        "ตำรับนี้เป็น ethylcellulose matrix ไม่ใช่ HPMC ซึ่งปกติจะกร่อนหมดไม่เหลือรูป",
        "การเคี้ยวจะทำลายโครงร่างและเสี่ยง dose dumping ไม่ทำให้พบเม็ดคงรูป",
      ],
      k: "Insoluble matrix (EC, Eudragit RS, PVAc) → ยาแพร่ผ่าน pore (Higuchi) → ghost matrix ในอุจจาระเป็นเรื่องปกติ",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Modified-release oral drug delivery",
    },
    {
      t: "Zero-order time to fractional release",
      p: "ยาเม็ด extended-release บรรจุตัวยา 200 mg ปลดปล่อยแบบ zero-order ด้วยอัตรา 8 mg/h ตั้งแต่เวลาศูนย์ (ไม่มี lag time) ต้องใช้เวลาเท่าใดจึงปลดปล่อยยาได้ 80% ของปริมาณที่ระบุบนฉลาก",
      o: ["10 h", "12.5 h", "20 h", "25 h", "40 h"],
      a: 2,
      r: "Zero-order release หมายถึงปริมาณยาที่ถูกปลดปล่อยเพิ่มขึ้นเป็นเส้นตรงกับเวลา Q = k0·t โดยอัตราไม่ขึ้นกับปริมาณยาที่เหลือ\n\n80% ของ 200 mg = 160 mg ดังนั้น t = 160/8 = 20 ชั่วโมง ส่วน 25 ชั่วโมงคือเวลาที่ปลดปล่อยครบ 100% ระบบที่ให้ zero-order ได้ใกล้เคียง ได้แก่ osmotic pump และ reservoir system ที่มี excess solid drug อยู่ภายใน",
      w: [
        "เป็นเวลาที่ปลดปล่อยได้ 40% (80 mg)",
        "ไม่สอดคล้องกับสมการ Q = k0·t (เท่ากับ 100/8)",
        "ถูก — 0.80 × 200 = 160 mg; 160/8 = 20 h",
        "เป็นเวลาที่ปลดปล่อยหมด 100% (200/8)",
        "เกิดจากการคำนวณกลับด้านหรือคิดว่าอัตราลดลงครึ่งหนึ่ง",
      ],
      k: "Zero-order: Q = k0·t → t = Q/k0",
      d: "easy",
      ref: "Aulton's Pharmaceutics 6th ed.; Shargel & Yu, Applied Biopharmaceutics & Pharmacokinetics 7th ed.",
      c: ["ปริมาณที่ต้องปลดปล่อย = 0.80 × 200 = 160 mg", "t = Q / k0 = 160 / 8 = 20 h"],
    },
    {
      t: "Reservoir coat thickness and release rate",
      p: "Pellet ชนิด reservoir เคลือบ ethylcellulose หนา 20 µm ปลดปล่อยยาแบบ zero-order ที่อัตรา 10 mg/h (มี excess solid drug ในแกน) หากเพิ่มความหนาของฟิล์มเป็น 30 µm โดยองค์ประกอบฟิล์มและพื้นที่ผิวเท่าเดิม อัตราการปลดปล่อยจะเป็นประมาณเท่าใด",
      o: ["3.3 mg/h", "4.4 mg/h", "6.7 mg/h", "10 mg/h", "15 mg/h"],
      a: 2,
      r: "สำหรับ reservoir (membrane-controlled) system อัตราการปลดปล่อยตาม Fick's first law คือ dM/dt = A·D·K·Cs / h เมื่อแกนมีตัวยาเป็นของแข็งเหลืออยู่ ความเข้มข้นภายในคงที่เท่ากับ Cs จึงได้ zero-order\n\nอัตราแปรผกผันกับความหนา h: 10 × (20/30) = 6.7 mg/h นอกจากนี้ฟิล์มที่หนาขึ้นยังทำให้ lag time ยาวขึ้นด้วย ในทางปฏิบัติผู้พัฒนาจึงปรับ release rate ด้วยการปรับ coating level หรือสัดส่วน pore former (เช่น HPMC) ในฟิล์ม",
      w: [
        "เป็นการหารด้วย 3 ไม่สอดคล้องกับความสัมพันธ์ 1/h",
        "คิดว่าอัตราแปรผกผันกับกำลังสองของความหนา ซึ่งไม่ถูกต้อง",
        "ถูก — dM/dt ∝ 1/h: 10 × 20/30 = 6.7 mg/h",
        "ความหนาเปลี่ยนแล้วอัตราต้องเปลี่ยน",
        "คิดว่าอัตราแปรผันตรงกับความหนา ซึ่งกลับด้าน",
      ],
      k: "Reservoir: dM/dt = A·D·K·Cs/h → อัตรา ∝ 1/ความหนาฟิล์ม; ฟิล์มหนาขึ้นยังเพิ่ม lag time",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed.; Martin's Physical Pharmacy 7th ed., Ch. Diffusion",
      c: ["dM/dt ∝ 1/h", "อัตราใหม่ = 10 × (20/30) = 6.67 ≈ 6.7 mg/h"],
    },
    {
      t: "Floating gastroretentive system",
      p: "ยาเม็ด floating gastroretentive ที่ประกอบด้วย HPMC, sodium bicarbonate และ citric acid ทำงานโดยหลักการใด",
      o: [
        "เกิดก๊าซ CO₂ ติดอยู่ใน gel ของ HPMC ทำให้ความหนาแน่นของเม็ดต่ำกว่าของเหลวในกระเพาะ จึงลอยและอยู่ในกระเพาะได้นาน",
        "เม็ดยามีความหนาแน่นสูงกว่า 2.5 g/cm³ จึงจมอยู่ที่ก้นกระเพาะ",
        "polymer ยึดเกาะกับเยื่อบุลำไส้เล็กส่วนต้นด้วยประจุบวก",
        "เม็ดยาพองตัวจนใหญ่กว่า pylorus ด้วย superporous hydrogel โดยไม่มีก๊าซ",
        "กรดซิตริกทำให้ pH กระเพาะสูงขึ้นจนยาเปลี่ยนเป็นรูปไม่แตกตัว",
      ],
      a: 0,
      r: "Floating drug delivery system (เช่น hydrodynamically balanced system และ effervescent system) ต้องมีความหนาแน่นต่ำกว่าน้ำย่อย (ประมาณ 1.004 g/cm³) เมื่อ HPMC เกิด gel ขณะที่ bicarbonate ทำปฏิกิริยากับกรด (กรดในกระเพาะหรือ citric acid ในตำรับ) จะเกิด CO₂ ถูกกักใน gel ทำให้เม็ดลอยตัวและปลดปล่อยยาอย่างช้าๆ ในกระเพาะ\n\nเหมาะกับยาที่มี absorption window แคบในทางเดินอาหารส่วนต้น ยาที่ออกฤทธิ์เฉพาะที่ในกระเพาะ หรือยาที่ไม่คงตัวใน pH ด่างของลำไส้ ระบบนี้ทำงานได้ดีเมื่อกระเพาะมีอาหารและของเหลวเพียงพอ จึงมักแนะนำให้รับประทานพร้อมอาหาร",
      w: [
        "ถูก — CO₂ ที่ติดอยู่ใน gel matrix ลดความหนาแน่นทำให้ลอยตัว",
        "เป็นหลักการของ high-density system ซึ่งไม่ใช้ bicarbonate",
        "เป็นหลักการ mucoadhesion ไม่ใช่ floating และตำแหน่งที่กล่าวถึงไม่ใช่กระเพาะ",
        "เป็นหลักการของ swelling/expandable system ที่ไม่ต้องอาศัยก๊าซ",
        "citric acid ในตำรับมีไว้ทำปฏิกิริยากับ bicarbonate ไม่ได้เปลี่ยน pH กระเพาะเพื่อปรับการแตกตัวของยา",
      ],
      k: "Floating GRDDS: density < 1.004 g/cm³, NaHCO₃ + กรด → CO₂ ติดใน gel; ได้ผลดีเมื่อรับประทานพร้อมอาหาร",
      d: "easy",
      ref: "Aulton's Pharmaceutics 6th ed.; Streubel A, Siepmann J, Bodmeier R. Curr Opin Pharmacol 2006;6:501–508",
    },
    {
      t: "Ideal drug properties for transdermal delivery",
      p: "ทีม R&D กำลังคัดเลือกตัวยาเพื่อพัฒนาเป็น passive transdermal patch ตัวยาที่มีคุณสมบัติใดเหมาะสมที่สุด",
      o: [
        "MW ประมาณ 300 Da, log P ประมาณ 2, จุดหลอมเหลวต่ำ และขนาดยาที่ต้องการต่อวันไม่กี่มิลลิกรัม",
        "MW ประมาณ 1,200 Da, log P ประมาณ −1 และขนาดยาต่อวัน 500 mg",
        "MW ประมาณ 250 Da, log P ประมาณ 6, ไม่ละลายน้ำ และขนาดยาต่อวัน 100 mg",
        "Peptide MW ประมาณ 5,000 Da ที่มีประจุสูงที่ pH ผิวหนัง",
        "MW ประมาณ 400 Da, ระคายเคืองผิวหนังรุนแรง และ log P ประมาณ 2",
      ],
      a: 0,
      r: "Stratum corneum เป็น barrier หลักที่มี lipid เรียงตัวแน่น ยาที่ซึมผ่านได้ดีควรมีน้ำหนักโมเลกุลต่ำ (โดยทั่วไป < 500 Da) มีความชอบไขมันพอเหมาะ (log P ประมาณ 1–3) เพื่อแบ่งเข้าสู่ lipid และออกสู่ชั้น viable epidermis ที่เป็นน้ำได้ มีจุดหลอมเหลวต่ำ (ละลายดีกว่า) และต้องมีความแรงสูงเพราะ flux ที่ได้ต่อพื้นที่ patch จำกัด ขนาดยาต่อวันจึงควรอยู่ในระดับไม่เกินประมาณ 10–20 mg\n\nนอกจากนี้ยาต้องไม่ระคายเคืองหรือก่อภูมิแพ้ต่อผิวหนัง ตัวอย่างยาที่สำเร็จ เช่น fentanyl, nicotine, estradiol, scopolamine, rivastigmine",
      w: [
        "ถูก — โมเลกุลเล็ก lipophilicity พอเหมาะ จุดหลอมเหลวต่ำ และขนาดยาต่ำ เป็นลักษณะของยาที่เหมาะกับ transdermal",
        "โมเลกุลใหญ่และ hydrophilic เกินไป ซึมผ่าน stratum corneum ได้น้อย และขนาดยาสูงเกิน",
        "log P สูงมากทำให้ยาค้างใน stratum corneum ไม่แบ่งออกสู่ชั้นน้ำ และขนาดยาสูงเกินไป",
        "peptide ขนาดใหญ่และมีประจุแทบไม่ซึมผ่านแบบ passive ต้องใช้วิธีทางกายภาพเช่น microneedle หรือ iontophoresis",
        "แม้ MW และ log P เหมาะสม แต่การระคายเคืองรุนแรงทำให้ใช้ patch ต่อเนื่องหลายวันไม่ได้",
      ],
      k: "Transdermal ideal: MW < 500, log P 1–3, mp ต่ำ, dose ≤ 10–20 mg/วัน, ไม่ระคายเคือง",
      d: "medium",
      ref: "Prausnitz MR, Langer R. Nat Biotechnol 2008;26:1261–1268; Aulton's Pharmaceutics 6th ed.",
    },
    {
      t: "Lactose fines in DPI carrier blends",
      p: "ตำรับ dry powder inhaler (DPI) แบบ carrier-based ใช้ micronized drug (1–5 µm) ผสมกับ coarse α-lactose monohydrate (ประมาณ 50–100 µm) พบว่า fine particle fraction ต่ำ ทีมพัฒนาเติม fine lactose (< 10 µm) จำนวนเล็กน้อยแล้ว FPF ดีขึ้น เหตุผลที่สำคัญที่สุดคือข้อใด",
      o: [
        "Fine lactose เข้าไปครอบครอง active (high-energy) sites บนผิว carrier ทำให้ยาเกาะกับ carrier หลวมลงและหลุดออกได้ง่ายขณะสูดพ่น",
        "Fine lactose เพิ่มความหนาแน่นของยาจนอนุภาคยาตกที่ปอดได้ดีขึ้น",
        "Fine lactose ละลายในทางเดินหายใจทำให้ยาละลายเร็วขึ้น",
        "Fine lactose ทำให้ผงยาดูดความชื้นมากขึ้นจึงเกาะกันน้อยลง",
        "Fine lactose ทำให้ carrier มีขนาดใหญ่ขึ้นจึงตกที่ลำคอน้อยลง",
      ],
      a: 0,
      r: "ใน DPI แบบ carrier ยาที่ micronized มี cohesive force สูงไหลไม่ดี จึงผสมกับ coarse lactose เพื่อช่วยการไหลและการแบ่งขนาดยา ขณะผู้ป่วยสูดพ่น แรง turbulence และการชนในอุปกรณ์ต้องเอาชนะแรงยึดเกาะระหว่างยากับ carrier เพื่อให้อนุภาคยาเดี่ยวเข้าสู่ปอด ส่วน carrier ขนาดใหญ่ตกที่ลำคอ\n\nผิว lactose มีบริเวณที่มีพลังงานสูง (ร่อง รอยแตก amorphous region) ซึ่งยึดยาไว้แน่น การเติม fine lactose ช่วยปิดตำแหน่งเหล่านี้ (active site hypothesis) และอาจเกิด agglomerate ของยากับ fines ที่แตกตัวง่าย ทำให้ FPF เพิ่มขึ้น",
      w: [
        "ถูก — เป็นกลไกตาม active site hypothesis ซึ่งอธิบายการเพิ่ม FPF เมื่อเติม ternary fines",
        "การตกที่ปอดขึ้นกับ aerodynamic diameter ของอนุภาคยาที่หลุดจาก carrier ไม่ใช่การเพิ่มความหนาแน่น",
        "lactose ไม่ได้เพิ่มการละลายของยาและ FPF วัดก่อนการละลาย",
        "ความชื้นที่มากขึ้นเพิ่ม capillary force ทำให้เกาะกันมากขึ้น ไม่ใช่น้อยลง",
        "fine lactose ไม่ได้ทำให้ carrier ใหญ่ขึ้น และ carrier ตั้งใจให้ตกที่ลำคออยู่แล้ว",
      ],
      k: "DPI carrier: coarse lactose ช่วยไหล/แบ่งขนาด; เติม fines ครอบครอง active sites → ยาหลุดง่าย → FPF ↑",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Pulmonary drug delivery; Jones MD, Price R. Pharm Res 2006;23:1665–1674",
    },
    {
      t: "SLN versus NLC drug loading",
      p: "Solid lipid nanoparticles (SLN) ที่ใช้ glyceryl tristearate บริสุทธิ์ พบว่าบรรจุยาได้น้อย และยาถูกขับออกจากอนุภาคระหว่างเก็บรักษา ทีมพัฒนาจึงเปลี่ยนเป็น nanostructured lipid carriers (NLC) การเปลี่ยนแปลงนี้แก้ปัญหาด้วยหลักการใด",
      o: [
        "ผสม liquid lipid (oil) เข้ากับ solid lipid ทำให้โครงสร้างผลึกไม่สมบูรณ์ มีที่ว่างรองรับยามากขึ้น และลดการเปลี่ยน polymorph ที่ขับยาออก",
        "เปลี่ยนเป็น lipid ที่มีความบริสุทธิ์สูงขึ้นเพื่อให้ผลึกเรียงตัวสมบูรณ์",
        "เพิ่มชั้น phospholipid bilayer ล้อมรอบแกนน้ำภายใน",
        "ใช้ polymer PLGA แทน lipid ทั้งหมด",
        "เพิ่มอุณหภูมิเก็บรักษาเพื่อให้ lipid หลอมเหลวตลอดเวลา",
      ],
      a: 0,
      r: "SLN ใช้ lipid ของแข็งเพียงชนิดเดียวซึ่งระหว่างเก็บรักษามักเปลี่ยนจาก polymorph ที่ไม่เสถียร (α) ไปเป็น β ที่เรียงตัวแน่นและสมบูรณ์ ทำให้มีที่ว่างสำหรับโมเลกุลยาน้อยลงและยาถูกขับออก (drug expulsion) อีกทั้ง loading capacity ตั้งแต่ต้นต่ำ\n\nNLC เป็นรุ่นที่สองที่ผสม liquid lipid เช่น medium-chain triglyceride หรือ oleic acid เข้ากับ solid lipid เกิด imperfect หรือ amorphous matrix ที่ยังเป็นของแข็งที่อุณหภูมิร่างกาย จึงบรรจุยาได้มากขึ้นและกักเก็บยาได้ดีกว่าระหว่างเก็บรักษา",
      w: [
        "ถูก — liquid lipid ทำให้ matrix ไม่เป็นผลึกสมบูรณ์ เพิ่ม loading และลด drug expulsion",
        "lipid ที่บริสุทธิ์มากยิ่งตกผลึกสมบูรณ์ ทำให้ปัญหาแย่ลง",
        "เป็นโครงสร้างของ vesicular carrier ไม่ใช่ NLC ซึ่งเป็นอนุภาค lipid matrix ทึบ",
        "เป็นการเปลี่ยนไปใช้ polymeric nanoparticle ไม่ใช่ NLC",
        "NLC ต้องคงสภาพของแข็งที่อุณหภูมิห้องและร่างกาย การทำให้หลอมไม่ใช่หลักการ",
      ],
      k: "SLN: lipid แข็งล้วน → ผลึกสมบูรณ์ → loading ต่ำ/drug expulsion; NLC: solid + liquid lipid → imperfect matrix → loading ↑",
      d: "medium",
      ref: "Müller RH, Radtke M, Wissing SA. Adv Drug Deliv Rev 2002;54 Suppl 1:S131–S155",
    },
    {
      t: "Colon targeting strategy selection",
      p: "ยาเม็ด mesalamine สำหรับ ulcerative colitis ที่เคลือบด้วย polymer ซึ่งละลายที่ pH > 7 เพียงอย่างเดียว มีรายงานว่าผู้ป่วยบางรายพบเม็ดยาไม่แตกออกมากับอุจจาระ ข้อใดอธิบายสาเหตุและแนวทางปรับปรุงได้ดีที่สุด",
      o: [
        "pH สูงสุดของทางเดินอาหารอยู่ที่ ileum ส่วนปลาย แล้วลดลงที่ caecum/colon และผู้ป่วยบางรายอาจไม่ถึง pH 7 นานพอ จึงควรใช้ร่วมกับกลไกที่อาศัยแบคทีเรียในลำไส้ใหญ่ เช่น polysaccharide หรือ azo-bond",
        "pH ในลำไส้ใหญ่สูงกว่า 9 เสมอ ฟิล์มจึงละลายช้า ควรเปลี่ยนเป็น Eudragit E",
        "เม็ดยาไม่แตกเพราะแบคทีเรียในลำไส้ใหญ่ทำลาย polymer ควรเพิ่มความหนาฟิล์ม",
        "เกิดจากเอนไซม์ pepsin ย่อยฟิล์ม ควรเติม protease inhibitor",
        "ควรเปลี่ยนเป็น HPMC matrix ไม่เคลือบ เพื่อให้ยาปลดปล่อยในกระเพาะ",
      ],
      a: 0,
      r: "pH ของทางเดินอาหารเพิ่มจากประมาณ 6 ใน duodenum ถึงสูงสุดราว 7–7.5 ที่ terminal ileum แต่เมื่อเข้าสู่ caecum pH จะลดลงเหลือราว 6–6.5 จากกรดไขมันสายสั้นที่แบคทีเรียสร้าง และในผู้ป่วย IBD pH อาจต่ำกว่าเดิม ระยะเวลาที่ pH > 7 อาจสั้นหรือไม่เกิดเลย ฟิล์ม pH > 7 (เช่น Eudragit S100) จึงอาจไม่ละลาย\n\nแนวทางที่น่าเชื่อถือกว่าคือ microbially triggered system ซึ่งอาศัยเอนไซม์ของแบคทีเรียในลำไส้ใหญ่ เช่น prodrug ที่มี azo bond (sulfasalazine, balsalazide, olsalazine) หรือ polysaccharide coating (resistant starch, pectin, guar gum) และอาจผสมกับ pH-dependent polymer เพื่อให้มีกลไกสำรอง (dual trigger)",
      w: [
        "ถูก — pH ที่ลดลงที่ caecum และความแปรปรวนในผู้ป่วยทำให้ pH-trigger เพียงอย่างเดียวไม่น่าเชื่อถือ การเพิ่ม bacterial trigger ช่วยได้",
        "pH ลำไส้ใหญ่ไม่ได้สูงถึง 9 และ Eudragit E ละลายในกระเพาะ",
        "ถ้าแบคทีเรียทำลาย polymer เม็ดยาจะแตก ไม่ใช่คงรูป และการเพิ่มความหนาทำให้แย่ลง",
        "pepsin ทำงานในกระเพาะและไม่ย่อย methacrylate polymer",
        "การปลดปล่อยในกระเพาะทำให้ยาถูกดูดซึมก่อนถึงลำไส้ใหญ่ ซึ่งขัดกับเป้าหมาย",
      ],
      k: "Colon targeting: pH-dependent อย่างเดียวไม่แน่นอน (pH ลดที่ caecum) → ใช้ microbial trigger (azo, polysaccharide) หรือ dual trigger",
      d: "hard",
      ref: "Amidon S, Brown JE, Dave VS. AAPS PharmSciTech 2015;16:731–741; Aulton's Pharmaceutics 6th ed.",
    },
    {
      t: "Hot-melt extrusion processing temperature",
      p: "นักพัฒนาต้องการเตรียม amorphous solid dispersion ของยาที่สลายตัวเมื่ออุณหภูมิสูงกว่า 160 °C ด้วยกระบวนการ hot-melt extrusion (HME) แต่ polymer ที่เลือกต้องใช้อุณหภูมิ barrel ประมาณ 180 °C จึงจะมีความหนืดเหมาะสม แนวทางใดเหมาะสมที่สุด",
      o: [
        "เติม plasticizer หรือเลือก polymer ที่มี Tg ต่ำกว่า เพื่อลด Tg และ melt viscosity ให้ extrude ได้ที่อุณหภูมิต่ำลง หากยังทำไม่ได้ให้พิจารณา spray drying",
        "เพิ่มอุณหภูมิ barrel เป็น 200 °C เพื่อลดเวลาที่ยาอยู่ใน extruder",
        "ลด screw speed ลงมากๆ เพื่อเพิ่ม residence time ให้ผสมทั่วถึง",
        "เปลี่ยน polymer เป็นชนิดที่มี Tg สูงขึ้นเพื่อให้ ASD คงตัวกว่า",
        "บดยาให้ละเอียดระดับ nano ก่อน extrude เพื่อลดการสลายตัวจากความร้อน",
      ],
      a: 0,
      r: "HME ต้องให้ความร้อนจน polymer อ่อนตัวเหนือ Tg มาก (โดยทั่วไปหลายสิบองศาเหนือ Tg) เพื่อให้มี melt viscosity ที่ผสมกับยาและไหลผ่าน die ได้ ยาและ polymer ต้องทนความร้อนในช่วงเวลาที่อยู่ใน extruder\n\nเมื่อยาไวต่อความร้อน วิธีลดอุณหภูมิกระบวนการคือเติม plasticizer (เช่น PEG, triethyl citrate, surfactant บางชนิด) หรือเลือก polymer ที่มี Tg ต่ำกว่า (เช่น copovidone หรือ polyvinyl caprolactam–polyvinyl acetate–PEG graft copolymer) ซึ่งยาบางชนิดเองก็ทำหน้าที่ plasticizer ได้ ถ้ายังไม่สามารถลดอุณหภูมิได้เพียงพอ spray drying ที่อาศัยตัวทำละลายและใช้เวลาสัมผัสความร้อนสั้นมากเป็นทางเลือกที่ดีกว่า",
      w: [
        "ถูก — plasticizer หรือ polymer Tg ต่ำ ลดอุณหภูมิที่ต้องใช้ และ spray drying เป็นทางเลือกเมื่อยาทนความร้อนไม่ได้",
        "อุณหภูมิที่สูงขึ้นเพิ่มอัตราการสลายตัวของยา แม้เวลาสั้นลงก็ไม่คุ้ม",
        "residence time ที่นานขึ้นยิ่งเพิ่มการสัมผัสความร้อนและการสลายตัว",
        "Tg สูงขึ้นต้องใช้อุณหภูมิกระบวนการสูงขึ้น ซึ่งขัดกับปัญหา",
        "การลดขนาดอนุภาคไม่ได้ลดอุณหภูมิที่ polymer ต้องใช้ในการไหล",
      ],
      k: "HME: T กระบวนการ ~ เหนือ Tg ของ polymer; ยาไวความร้อน → plasticizer/polymer Tg ต่ำ หรือเปลี่ยนเป็น spray drying",
      d: "hard",
      ref: "Crowley MM et al. Drug Dev Ind Pharm 2007;33:909–926; Aulton's Pharmaceutics 6th ed.",
    },
    {
      t: "Long-acting injectable suspension particle size",
      p: "ผลิตภัณฑ์ long-acting injectable (LAI) แบบ aqueous suspension ของ antipsychotic prodrug ที่ละลายน้ำได้น้อยมาก ฉีดเข้ากล้ามเนื้อทุก 1 เดือน หลังเปลี่ยนกระบวนการบดพบว่าขนาดอนุภาคเฉลี่ยเล็กลงครึ่งหนึ่ง ผลที่คาดว่าจะเกิดกับ PK มากที่สุดคือข้อใด",
      o: [
        "อัตราการละลายที่ตำแหน่งฉีดเพิ่มขึ้น ทำให้ Cmax สูงขึ้นและระยะเวลาที่ระดับยาคงอยู่สั้นลง เพราะการละลายเป็นขั้นที่ควบคุมการดูดซึม",
        "ไม่มีผลใดๆ เพราะยาฉีดเข้ากล้ามเนื้อมี bioavailability 100% เสมอ",
        "Cmax ลดลงและระยะเวลาออกฤทธิ์ยาวขึ้นเพราะอนุภาคเล็กจับตัวกันเป็นก้อน",
        "clearance ของยาลดลงเพราะอนุภาคเล็กเข้าสู่ตับได้น้อย",
        "elimination half-life ที่แท้จริงของยาเพิ่มขึ้นเป็นสองเท่า",
      ],
      a: 0,
      r: "LAI suspension สร้าง depot ที่ตำแหน่งฉีด ยาต้องละลายก่อนจึงดูดซึมเข้าสู่กระแสเลือด และ (สำหรับ prodrug) ถูก hydrolyze เป็นยาออกฤทธิ์ เนื่องจากอัตราการละลายต่ำมาก ขั้นนี้จึงช้ากว่าการกำจัดยา เกิด flip-flop kinetics ที่ apparent half-life สะท้อนอัตราการปลดปล่อยจาก depot ไม่ใช่การกำจัด\n\nตามสมการ Noyes–Whitney อนุภาคเล็กลงมีพื้นที่ผิวมากขึ้น ละลายเร็วขึ้น จึงเพิ่ม Cmax และทำให้ระยะเวลาครอบคลุมสั้นลง ขนาดอนุภาคจึงเป็น critical quality attribute ที่ต้องควบคุมใน LAI suspension และการเปลี่ยนกระบวนการบดต้องประเมินผลกระทบอย่างรัดกุม",
      w: [
        "ถูก — อนุภาคเล็กลงละลายเร็วขึ้น depot หมดเร็วขึ้น Cmax ↑ ระยะเวลาครอบคลุม ↓",
        "แม้ปริมาณที่ดูดซึมทั้งหมดอาจใกล้เคียงเดิม แต่รูปแบบเวลาของระดับยาเปลี่ยนชัดเจน",
        "ไม่สอดคล้องกับ Noyes–Whitney; การจับตัวเป็นก้อนเป็นปัญหาความคงตัวที่ควบคุมด้วยตำรับ ไม่ใช่ผลที่คาดหวังหลัก",
        "clearance เป็นคุณสมบัติของร่างกายต่อยาที่อยู่ในกระแสเลือด ไม่ขึ้นกับขนาดอนุภาคใน depot",
        "true elimination half-life ไม่เปลี่ยน; apparent half-life จะสั้นลงเพราะ depot ปลดปล่อยเร็วขึ้น",
      ],
      k: "LAI suspension: dissolution ที่ depot เป็น rate-limiting (flip-flop) → particle size คือ CQA หลักที่กำหนดระยะเวลาออกฤทธิ์",
      d: "hard",
      ref: "Wright JC, Burgess DJ (eds). Long Acting Injections and Implants. Springer 2012",
    },
  ],
  // Mock Set 3 — ชุดที่ 3
  [
    {
      t: "Hixson-Crowell cube root law",
      p: "ผงยาอนุภาคทรงกลมขนาดใกล้เคียงกันหนัก 64 mg ละลายภายใต้ sink condition เหลือของแข็ง 27 mg ที่เวลา 2 ชั่วโมง หากการละลายเป็นไปตาม Hixson–Crowell cube root law (จำนวนอนุภาคคงที่ และรูปร่างคงเดิม) ผงยาจะละลายหมดที่เวลาประมาณเท่าใด",
      o: ["3.5 h", "4 h", "6 h", "8 h", "12 h"],
      a: 3,
      r: "Hixson–Crowell อธิบายการละลายของอนุภาคที่พื้นที่ผิวลดลงตามการละลาย: W0^(1/3) − Wt^(1/3) = κ·t ซึ่งเหมาะกับอนุภาคขนาดเดียวกัน (monodisperse) ที่ลดขนาดลงอย่างสม่ำเสมอ หรือ matrix ที่กร่อนโดยรูปทรงคงเดิม\n\n64^(1/3) = 4 และ 27^(1/3) = 3 ดังนั้น κ = (4 − 3)/2 = 0.5 mg^(1/3)/h เมื่อละลายหมด Wt = 0 จะได้ t = 4/0.5 = 8 ชั่วโมง ถ้าคิดเป็นเส้นตรง (zero-order) จะได้เพียงประมาณ 3.5 ชั่วโมง ซึ่งประเมินเร็วเกินจริงเพราะพื้นที่ผิวลดลงเรื่อยๆ",
      w: [
        "เป็นการคิดแบบ zero-order (ละลาย 37 mg ใน 2 h → 64/18.5) ซึ่งไม่คำนึงว่าพื้นที่ผิวลดลง",
        "นำค่า W0^(1/3) = 4 มาใช้เป็นเวลาโดยตรง โดยไม่หารด้วย κ",
        "คำนวณ κ ผิดหรือใช้ Wt^(1/3) แทน W0^(1/3)",
        "ถูก — κ = (4 − 3)/2 = 0.5; t = 4/0.5 = 8 h",
        "ใช้ส่วนต่างของน้ำหนักผิดหน่วยหรือคูณเวลาเกิน",
      ],
      k: "Hixson–Crowell: W0^(1/3) − Wt^(1/3) = κt — ใช้กับอนุภาค monodisperse/erosion ที่รูปทรงคงที่",
      d: "medium",
      ref: "Hixson AW, Crowell JH. Ind Eng Chem 1931;23:923–931; Costa P, Sousa Lobo JM. Eur J Pharm Sci 2001;13:123–133",
      c: [
        "W0^(1/3) = 64^(1/3) = 4; W2h^(1/3) = 27^(1/3) = 3",
        "κ = (4 − 3) / 2 h = 0.5 mg^(1/3)/h",
        "ละลายหมดเมื่อ Wt = 0: t = 4 / 0.5 = 8 h",
      ],
    },
    {
      t: "Advantages of multiparticulate MR systems",
      p: "ข้อใดเป็นข้อได้เปรียบสำคัญของ multiparticulate modified-release (เช่น coated pellets บรรจุแคปซูล) เมื่อเทียบกับ single-unit tablet ขนาดใหญ่",
      o: [
        "กระจายตัวทั่วทางเดินอาหาร ผ่าน pylorus ได้แม้ในภาวะมีอาหาร ทำให้ transit time และการดูดซึมแปรปรวนน้อยกว่า และลดความเสี่ยง dose dumping ทั้งหมดในครั้งเดียว",
        "ต้นทุนการผลิตต่ำกว่าเพราะใช้ขั้นตอนน้อยกว่า",
        "สามารถบดหรือเคี้ยวเม็ด pellet ได้โดยไม่กระทบการปลดปล่อย",
        "ทุก pellet ปลดปล่อยยาแบบ first-order จึงไม่ต้องควบคุมคุณภาพการเคลือบ",
        "ทำให้ยาอยู่ในกระเพาะได้นานกว่า single-unit เสมอ",
      ],
      a: 0,
      r: "Multiparticulates (pellets, beads, mini-tablets) ประกอบด้วยหน่วยย่อยจำนวนมาก ขนาดเล็ก (โดยทั่วไป < 2–3 mm) จึงผ่าน pylorus ได้แม้กระเพาะมีอาหาร การ transit ใกล้เคียงของเหลว ลดความแปรปรวนจาก gastric emptying และอาหาร\n\nถ้า pellet บางส่วนมีข้อบกพร่องของฟิล์ม จะกระทบเพียงสัดส่วนเล็กๆ ของขนาดยา ไม่เกิด dose dumping ทั้งหมดเหมือน single unit นอกจากนี้ยังลดการระคายเคืองเฉพาะที่ ผสม pellet ที่มีอัตราการปลดปล่อยต่างกันได้ และบางผลิตภัณฑ์สามารถเปิดแคปซูลโรยบนอาหารอ่อนได้ (sprinkle) แต่ห้ามเคี้ยวหรือบด",
      w: [
        "ถูก — การกระจายตัวและการแบ่งขนาดยาเป็นหลายหน่วยลดความแปรปรวนและความเสี่ยง dose dumping",
        "การผลิต pellet (extrusion–spheronization, coating) มีหลายขั้นตอนและต้นทุนสูงกว่าโดยทั่วไป",
        "การบดหรือเคี้ยวทำลายฟิล์มควบคุมการปลดปล่อยของ pellet",
        "อัตราการปลดปล่อยขึ้นกับการออกแบบ และคุณภาพการเคลือบเป็น critical attribute ที่ต้องควบคุม",
        "pellet ขนาดเล็กออกจากกระเพาะได้เร็วกว่า ไม่ได้อยู่นานกว่า single unit",
      ],
      k: "Multiparticulates: GI transit สม่ำเสมอ, แปรปรวนจากอาหารน้อย, ลด dose dumping, ผสมหลายอัตราได้, sprinkle ได้แต่ห้ามเคี้ยว",
      d: "easy",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Modified-release oral drug delivery",
    },
    {
      t: "EOP release decline after core depletion",
      p: "Elementary osmotic pump (EOP) ของยาที่ละลายน้ำได้ดีปลดปล่อยยาแบบ zero-order จนถึงประมาณ 70% ของปริมาณยา หลังจากนั้นอัตราลดลงเรื่อยๆ ข้อใดอธิบายได้ถูกต้องที่สุด",
      o: [
        "เมื่อยาของแข็งในแกนละลายหมด ความเข้มข้นภายในต่ำกว่า saturation ทำให้ osmotic pressure และความเข้มข้นของสารละลายที่ถูกดันออกลดลง อัตราจึงลดลงแบบ first-order",
        "pH ในลำไส้ใหญ่สูงขึ้นทำให้ semipermeable membrane ละลาย",
        "รู orifice ถูกปิดด้วย gel ของ HPMC จากผิวเม็ด",
        "น้ำในลำไส้ใหญ่มีมากขึ้นทำให้ osmotic pressure ภายนอกเพิ่มเป็นสองเท่า",
        "ฟิล์ม cellulose acetate ถูกเอนไซม์ในลำไส้ย่อย",
      ],
      a: 0,
      r: "ใน EOP น้ำซึมผ่าน semipermeable membrane ด้วยอัตรา dV/dt = (A/h)·Lp·(σΔπ − ΔP) และดันสารละลายยาอิ่มตัวออกทาง orifice ดังนั้นอัตราปลดปล่อย dM/dt = (dV/dt)·Cs จะคงที่ตราบที่ในแกนยังมียาของแข็งเหลือ ทำให้ความเข้มข้นเท่ากับ Cs และ osmotic pressure คงที่\n\nเมื่อของแข็งละลายหมด ทั้ง osmotic pressure (แรงขับการดูดน้ำ) และความเข้มข้นของสารละลายที่ออกมาลดลงเรื่อยๆ อัตราจึงลดลงคล้าย first-order สัดส่วนที่ปลดปล่อยแบบ zero-order ขึ้นกับการละลายของยา: ยิ่งละลายดีมาก สัดส่วน zero-order ยิ่งน้อย (ประมาณ 1 − Cs/ρ) จึงอาจเติม osmotic agent หรือปรับความสามารถในการละลาย",
      w: [
        "ถูก — zero-order คงอยู่เฉพาะช่วงที่มี excess solid drug รักษาความเข้มข้นที่ saturation",
        "cellulose acetate ไม่ละลายตาม pH และการปลดปล่อยของ osmotic pump ไม่ขึ้นกับ pH",
        "EOP ไม่มี HPMC gel ที่ผิวเม็ด และรูถูกออกแบบไม่ให้อุดตัน",
        "ปริมาณน้ำภายนอกไม่ได้เพิ่ม osmotic pressure ภายนอก และหากเพิ่มจริงจะไม่อธิบายรูปแบบที่สัมพันธ์กับสัดส่วนยาที่เหลือ",
        "cellulose acetate ไม่ถูกย่อยในทางเดินอาหารและถูกขับออกเป็นเปลือกเปล่า",
      ],
      k: "EOP: zero-order เฉพาะช่วงที่มี excess solid drug ในแกน; ยาละลายดีมาก → สัดส่วน zero-order น้อยลง",
      d: "medium",
      ref: "Theeuwes F. J Pharm Sci 1975;64:1987–1991; Aulton's Pharmaceutics 6th ed.",
    },
    {
      t: "Buccal mucoadhesive tablet design",
      p: "ต้องการพัฒนายาเม็ดติดกระพุ้งแก้ม (buccal mucoadhesive tablet) สำหรับยาที่มี first-pass metabolism สูง ข้อใดถูกต้องที่สุดเกี่ยวกับการออกแบบ",
      o: [
        "ใช้ mucoadhesive polymer ที่มีหมู่ H-bonding และพองตัวในน้ำ เช่น carbomer, polycarbophil, chitosan หรือ NaCMC ร่วมกับ backing layer ที่ไม่ซึมน้ำเพื่อให้ยาซึมผ่านเยื่อบุทางเดียว",
        "ใช้ polymer ที่ไม่ดูดน้ำเลย เช่น paraffin wax เพื่อเกาะติดเยื่อบุได้นาน",
        "ควรเลือกยาที่มีขนาดยาต่อครั้งหลายร้อยมิลลิกรัมเพื่อให้ได้ระดับยาเพียงพอ",
        "ยาที่ดูดซึมผ่าน buccal mucosa จะเข้าสู่ hepatic portal vein ก่อนเข้าสู่ระบบไหลเวียน",
        "ควรเติม superdisintegrant ปริมาณสูงเพื่อให้เม็ดแตกตัวทันที",
      ],
      a: 0,
      r: "Mucoadhesion เกิดจาก polymer ดูดน้ำและพองตัว สาย polymer แทรกเข้ากับ mucin (interpenetration) และเกิดพันธะไฮโดรเจน แรงไฟฟ้าสถิต หรือ van der Waals polymer ที่ดีมักมีหมู่ carboxyl/hydroxyl, มีน้ำหนักโมเลกุลสูงและยืดหยุ่น เช่น carbomer, polycarbophil, NaCMC, HPMC และ chitosan (ประจุบวกจับ mucin ที่มีประจุลบ)\n\nยาที่ดูดซึมผ่าน buccal mucosa เข้าสู่ internal jugular vein แล้วเข้าสู่ systemic circulation โดยไม่ผ่านตับ จึงเลี่ยง first-pass ได้ ข้อจำกัดคือพื้นที่ดูดซึมน้อย มีน้ำลายชะล้าง จึงเหมาะกับยาที่มีความแรงสูง ขนาดยาต่ำ และไม่ระคายเคือง backing layer ช่วยลดการสูญเสียยาไปกับน้ำลาย",
      w: [
        "ถูก — polymer ที่มีหมู่ H-bonding และพองตัวได้ ร่วมกับ backing layer เป็นหลักการของ buccal mucoadhesive system",
        "polymer ที่ไม่ดูดน้ำไม่เกิด interpenetration กับ mucin จึงยึดเกาะไม่ดี",
        "พื้นที่ดูดซึมใน buccal จำกัด จึงเหมาะกับยาขนาดต่ำ",
        "buccal drainage เข้าสู่ jugular vein ไม่ผ่าน portal vein จึงเลี่ยง first-pass ได้",
        "การแตกตัวทันทีขัดกับแนวคิด mucoadhesive ที่ต้องติดและปลดปล่อยยาอย่างต่อเนื่อง",
      ],
      k: "Buccal: mucoadhesive polymer (carbomer, polycarbophil, chitosan, NaCMC) + backing layer; เลี่ยง first-pass ผ่าน jugular vein; เหมาะยาขนาดต่ำ",
      d: "medium",
      ref: "Smart JD. Adv Drug Deliv Rev 2005;57:1556–1568; Aulton's Pharmaceutics 6th ed.",
    },
    {
      t: "Matrix versus reservoir transdermal patch",
      p: "ผู้ป่วยมะเร็งใช้ fentanyl transdermal patch และสอบถามว่าสามารถตัดแผ่นแปะครึ่งหนึ่งเพื่อลดขนาดยาได้หรือไม่ ข้อใดเป็นคำอธิบายทางเภสัชกรรมที่ถูกต้องที่สุด",
      o: [
        "Patch ชนิด reservoir มียาในรูป gel/ของเหลวและมี rate-controlling membrane หากตัดหรือรั่วยาจะไหลออกจำนวนมาก (dose dumping) จึงห้ามตัด ส่วนชนิด matrix (drug-in-adhesive) ก็ไม่ควรตัดหากฉลากไม่อนุญาต",
        "ทุก patch ตัดได้อย่างปลอดภัยเพราะอัตราการปลดปล่อยขึ้นกับผิวหนังเท่านั้น",
        "Patch ชนิด reservoir ตัดได้ แต่ชนิด matrix ห้ามตัดเพราะยาจะไหลออก",
        "การตัด patch ทำให้ flux ต่อพื้นที่เพิ่มขึ้นสองเท่าจึงได้ยาเท่าเดิม",
        "สามารถตัดได้หากแปะบริเวณที่มีขนมากเพื่อชะลอการดูดซึม",
      ],
      a: 0,
      r: "Reservoir patch มีชั้นยาที่เป็นของเหลวหรือ gel แยกจาก adhesive และมี rate-controlling membrane (เช่น ethylene–vinyl acetate) กำหนดอัตราปลดปล่อย หากตัด เจาะ หรือ membrane เสียหาย ยาจะออกโดยไม่ผ่านการควบคุม เป็นอันตรายอย่างมากกับยาที่มี therapeutic index แคบอย่าง fentanyl\n\nMatrix หรือ drug-in-adhesive patch มียากระจายอยู่ในชั้น adhesive ปริมาณยาที่ส่งเป็นสัดส่วนกับพื้นที่ บางและยืดหยุ่นกว่า การปลดปล่อยถูกควบคุมโดยผิวหนังเป็นหลัก แต่การตัดยังไม่แนะนำหากไม่มีข้อมูลรับรองในฉลาก (ความคงตัว การยึดเกาะ ขอบแผ่น) ควรเลือกขนาดความแรงที่เหมาะสมแทน",
      w: [
        "ถูก — reservoir patch เสี่ยง dose dumping เมื่อถูกตัด ส่วน matrix patch ก็ควรใช้ตามฉลากเท่านั้น",
        "reservoir patch ปลดปล่อยผ่าน membrane และการตัดทำให้ยารั่วออกโดยไม่ควบคุม",
        "สลับกัน: reservoir คือชนิดที่ยารั่วออกเมื่อตัด",
        "flux ต่อพื้นที่ไม่เปลี่ยน การตัดลดพื้นที่จึงลดขนาดยาหรือก่อ dose dumping (reservoir) ไม่ใช่ชดเชย",
        "ขนรบกวนการยึดเกาะ ไม่ใช่วิธีควบคุมขนาดยา และไม่แก้ปัญหาการตัด",
      ],
      k: "Reservoir patch = ยาใน gel + rate-controlling membrane → ห้ามตัด (dose dumping); matrix = drug-in-adhesive, dose ∝ พื้นที่",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Transdermal drug delivery; Prausnitz MR, Langer R. Nat Biotechnol 2008",
    },
    {
      t: "HFA propellant reformulation of pMDI",
      p: "ในการเปลี่ยน pressurized metered-dose inhaler (pMDI) จาก CFC เป็น HFA-134a ผู้พัฒนามักต้องเติม ethanol ในตำรับ เหตุผลสำคัญคือข้อใด",
      o: [
        "Surfactant และ valve lubricant ที่ใช้กับ CFC เช่น sorbitan trioleate และ oleic acid ละลายใน HFA ได้น้อย จึงต้องใช้ ethanol เป็น co-solvent ช่วยละลาย surfactant หรือตัวยา",
        "ethanol ช่วยเพิ่มความดันไอของ HFA ให้สูงกว่า CFC",
        "ethanol ทำหน้าที่เป็น antimicrobial preservative ที่จำเป็นในทุก pMDI",
        "HFA ติดไฟง่าย จึงต้องใช้ ethanol ลดความไวไฟ",
        "ethanol ช่วยให้อนุภาคยามีขนาดใหญ่ขึ้นจึงตกที่ลำคอน้อยลง",
      ],
      a: 0,
      r: "CFC ถูกเลิกใช้ตาม Montreal Protocol เนื่องจากทำลายชั้นโอโซน HFA-134a และ HFA-227ea เป็นสารขับดันทดแทน แต่มีความเป็นขั้วและสมบัติการละลายต่างจาก CFC ทำให้ surfactant แบบดั้งเดิมละลายได้น้อย ethanol จึงถูกใช้เป็น co-solvent ทั้งในตำรับ suspension (ช่วยละลาย surfactant) และตำรับ solution (ช่วยละลายตัวยา)\n\nตำรับ solution ใน HFA เช่น beclomethasone dipropionate ให้ละอองที่มีอนุภาคเล็กมาก (extrafine) และ lung deposition สูงขึ้น จึงต้องปรับขนาดยาเมื่อเปลี่ยนผลิตภัณฑ์ นอกจากนี้ ethanol ในสัดส่วนสูงยังลดความดันไอ เพิ่มขนาดหยดละออง และอาจทำให้รู้สึกแสบหรือมีรส",
      w: [
        "ถูก — HFA ละลาย surfactant ดั้งเดิมได้น้อย ethanol จึงเป็น co-solvent สำคัญ",
        "ethanol มีความดันไอต่ำกว่า HFA การเติมจะลดความดันไอของระบบ ไม่ใช่เพิ่ม",
        "pMDI ส่วนใหญ่ไม่ต้องใช้ preservative เพราะระบบปิดและไม่มีน้ำ",
        "HFA-134a ไม่ติดไฟ และ ethanol เองติดไฟได้",
        "ตำรับ solution ที่ใช้ ethanol กลับให้อนุภาคเล็ก (extrafine) ไม่ได้มีเป้าหมายให้ใหญ่ขึ้น",
      ],
      k: "CFC → HFA-134a/227ea: surfactant เดิมละลายน้อย → เติม ethanol co-solvent; solution HFA ให้ extrafine particles",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Pulmonary drug delivery; Montreal Protocol",
    },
    {
      t: "Spacer device for pMDI",
      p: "ผู้ป่วยที่ใช้ inhaled corticosteroid ชนิด pMDI มีปัญหาเชื้อราในช่องปากและกดพ่นไม่สัมพันธ์กับการหายใจเข้า การใช้ spacer (valved holding chamber) ช่วยได้ด้วยเหตุผลใดมากที่สุด",
      o: [
        "ละอองที่มีความเร็วสูงและอนุภาคใหญ่ตกค้างใน spacer แทนลำคอ ขณะที่ propellant ระเหยและอนุภาคเล็กลง ทำให้ไม่ต้องประสานการกดกับการหายใจเข้าอย่างแม่นยำ",
        "spacer เพิ่มขนาดยาที่ออกจาก canister ในแต่ละครั้ง",
        "spacer เปลี่ยนตำรับจาก suspension เป็น solution",
        "spacer ทำให้ไม่ต้องบ้วนปากหลังใช้ยาสเตียรอยด์อีกต่อไป",
        "spacer เพิ่มความเร็วของละอองเพื่อให้ยาไปถึงถุงลมได้ลึกขึ้น",
      ],
      a: 0,
      r: "ละอองจาก pMDI ออกมาด้วยความเร็วสูงและหยดละอองยังมี propellant ทำให้ขนาดใหญ่ ส่วนมากกระแทกที่ oropharynx (inertial impaction) เป็นสาเหตุของ oral candidiasis และเสียงแหบจาก ICS\n\nSpacer เพิ่มระยะทางและเวลาให้ละอองชะลอความเร็ว propellant ระเหยจนอนุภาคเล็กลง อนุภาคใหญ่ตกค้างในอุปกรณ์แทนปาก และ valve ช่วยให้หายใจเข้าหลังกดได้ จึงลดปัญหาการประสานจังหวะ ควรล้าง spacer พลาสติกด้วยน้ำผสมสารทำความสะอาดแล้วปล่อยให้แห้งเองเพื่อลด static charge และยังคงแนะนำให้บ้วนปากหลังใช้ ICS",
      w: [
        "ถูก — spacer ลด oropharyngeal deposition และลดปัญหาการประสานจังหวะ",
        "ขนาดยาที่ออกจาก canister ถูกกำหนดโดย metering valve ไม่ใช่ spacer",
        "spacer ไม่เปลี่ยนชนิดตำรับ",
        "ยังคงควรบ้วนปากหลังใช้ ICS แม้ใช้ spacer",
        "spacer ชะลอความเร็วของละออง ไม่ได้เพิ่ม",
      ],
      k: "Spacer: ชะลอละออง + propellant ระเหย → ลด oropharyngeal deposition และปัญหา hand–breath coordination",
      d: "easy",
      ref: "GINA 2024 Report; Aulton's Pharmaceutics 6th ed., Ch. Pulmonary drug delivery",
    },
    {
      t: "PEGylation benefits and drawbacks",
      p: "เมื่อนำ protein drug มาทำ PEGylation (ต่อสาย polyethylene glycol แบบ covalent) ข้อใดอธิบายผลที่เกิดขึ้นได้ถูกต้องและครบถ้วนที่สุด",
      o: [
        "ขนาด hydrodynamic ใหญ่ขึ้นลด renal filtration และ PEG บดบังโปรตีนจาก protease และระบบภูมิคุ้มกัน จึงยืด half-life แต่ in vitro activity มักลดลงและอาจเกิด anti-PEG antibody",
        "PEG เพิ่ม affinity ต่อ receptor ทำให้ activity ต่อโมเลกุลเพิ่มขึ้นเสมอ",
        "PEGylation ทำให้โปรตีนดูดซึมทางปากได้ดีจนใช้แทนยาฉีด",
        "PEG ถูกตัดออกทันทีในกระแสเลือดจึงไม่มีผลต่อ PK",
        "PEGylation ลดน้ำหนักโมเลกุลของโปรตีนจึงกรองผ่านไตได้เร็วขึ้น",
      ],
      a: 0,
      r: "PEG เป็น polymer ชอบน้ำ ยืดหยุ่น และจับน้ำไว้มาก เมื่อต่อกับโปรตีนจะเพิ่ม hydrodynamic radius อย่างมาก จนเกินขีดการกรองของ glomerulus และสร้างชั้นป้องกัน (steric shielding) จาก proteolytic enzymes และการจดจำของระบบภูมิคุ้มกัน ทำให้ half-life ยาวขึ้น ความถี่ในการฉีดลดลง ตัวอย่างเช่น peginterferon alfa, pegfilgrastim และ pegloticase\n\nข้อเสียคือ PEG อาจบังบริเวณ active site ทำให้ in vitro activity ต่ำลง (ชดเชยด้วย PK ที่ดีขึ้น) ปัญหาความไม่เป็นเนื้อเดียว (positional isomers) และมีรายงาน anti-PEG antibodies ซึ่งอาจเร่งการกำจัด (accelerated blood clearance) หรือก่อ hypersensitivity",
      w: [
        "ถูก — ครอบคลุมทั้งกลไกยืด half-life และข้อเสีย (activity ลดลง, anti-PEG antibodies)",
        "PEG มักบดบังตำแหน่งจับ receptor ทำให้ activity ต่อโมเลกุลลดลง ไม่ใช่เพิ่ม",
        "PEGylation ไม่ได้แก้ปัญหาการดูดซึมทางปากของโปรตีน ยังต้องให้โดยการฉีด",
        "พันธะ covalent ของ PEG ส่วนใหญ่คงตัวในเลือด จึงเปลี่ยน PK อย่างชัดเจน",
        "PEGylation เพิ่มขนาดโมเลกุล ลด renal filtration",
      ],
      k: "PEGylation: hydrodynamic size ↑ → renal clearance ↓, shielding จาก protease/immune → t½ ↑; แลกกับ activity ↓ และ anti-PEG antibody",
      d: "hard",
      ref: "Harris JM, Chess RB. Nat Rev Drug Discov 2003;2:214–221; Veronese FM, Pasut G. Drug Discov Today 2005;10:1451–1458",
    },
    {
      t: "Spray drying for heat-labile amorphous dispersion",
      p: "ยา BCS class II มีจุดหลอมเหลว 245 °C และสลายตัวขณะหลอม แต่ละลายได้ดีใน acetone ร่วมกับ HPMCAS ผู้พัฒนาจึงเลือกทำ amorphous solid dispersion ด้วย spray drying ข้อใดถูกต้องที่สุดเกี่ยวกับกระบวนการนี้",
      o: [
        "ตัวทำละลายระเหยในเวลาสั้นมาก (มิลลิวินาที–วินาที) จึงตรึงยาในสภาพอสัณฐานใน polymer ได้ และ evaporative cooling ทำให้อนุภาคร้อนไม่มาก แต่ต้องมี secondary drying เพื่อลด residual solvent ให้อยู่ในเกณฑ์ ICH Q3C",
        "ต้องให้ความร้อนจนยาหลอมเหลวที่ 245 °C ก่อนพ่นแห้ง",
        "ผลิตภัณฑ์ที่ได้ไม่มีตัวทำละลายตกค้างเลย จึงไม่ต้องตรวจ residual solvent",
        "spray drying ให้ผลิตภัณฑ์ที่เป็นผลึกขนาดใหญ่ซึ่งคงตัวกว่าอสัณฐาน",
        "เหมาะเฉพาะยาที่ไม่ละลายในตัวทำละลายอินทรีย์ใดเลย",
      ],
      a: 0,
      r: "Spray drying ละลายยาและ polymer ใน common volatile solvent (เช่น acetone, methanol) แล้วพ่นเป็นหยดละเอียดในกระแสก๊าซร้อน ตัวทำละลายระเหยเร็วมากจน molecule ของยาไม่มีเวลาจัดเรียงเป็นผลึก จึงได้ amorphous solid dispersion ที่ยากระจายในระดับโมเลกุล\n\nขณะตัวทำละลายระเหย อุณหภูมิหยดจะต่ำกว่าก๊าซขาเข้า (evaporative cooling) จึงเหมาะกับยาที่หลอมแล้วสลายตัว ซึ่งทำ HME ได้ยาก ข้อจำกัดคือใช้ตัวทำละลายอินทรีย์ปริมาณมาก ผงที่ได้มักละเอียดและ bulk density ต่ำ และมี residual solvent สูงหลังพ่นแห้ง จึงต้องทำ secondary drying (เช่น tray หรือ fluid-bed drying) ให้ได้ตาม ICH Q3C",
      w: [
        "ถูก — การระเหยเร็วตรึงสภาพอสัณฐาน เหมาะกับยาที่ไวต่อความร้อน และต้องควบคุม residual solvent",
        "spray drying ไม่ต้องหลอมยา การหลอมคือหลักการของ HME ซึ่งยาตัวนี้ไม่ทน",
        "spray-dried dispersion มักมี residual solvent ต้องทำ secondary drying และตรวจตาม ICH Q3C",
        "จุดประสงค์คือทำให้เป็นอสัณฐานเพื่อเพิ่มการละลาย ไม่ใช่ผลึก",
        "spray drying ต้องการตัวทำละลายร่วมที่ละลายทั้งยาและ polymer",
      ],
      k: "Spray drying ASD: common solvent + ระเหยเร็ว → amorphous; เหมาะยาที่หลอมแล้วสลาย; ต้อง secondary drying (ICH Q3C)",
      d: "hard",
      ref: "Singh A, Van den Mooter G. Adv Drug Deliv Rev 2016;100:27–50; ICH Q3C(R9)",
    },
    {
      t: "Immediate plus maintenance dose design for ER",
      p: "ออกแบบยาเม็ด sustained-release ให้มีส่วน immediate-release (Di) = 50 mg เพื่อให้ถึงระดับการรักษาทันที และส่วน maintenance ที่ปลดปล่อยแบบ zero-order เพื่อคงระดับนั้นไว้ 12 ชั่วโมง ยามี elimination rate constant (k) = 0.2 h⁻¹ ตามแนวทาง Robinson–Eriksen (ไม่ปรับค่าเวลาถึงจุดสูงสุด) ปริมาณยาทั้งหมดต่อเม็ดควรเป็นเท่าใด",
      o: ["60 mg", "120 mg", "170 mg", "223 mg", "650 mg"],
      a: 2,
      r: "หลักการคือส่วน maintenance ต้องปลดปล่อยด้วยอัตราเท่ากับอัตราการกำจัดยาที่ระดับที่ได้จาก Di: kr0 = k·Di = 0.2 × 50 = 10 mg/h\n\nปริมาณยาส่วน maintenance สำหรับ 12 ชั่วโมง Dm = kr0 × Td = 10 × 12 = 120 mg ปริมาณรวม Dt = Di + Dm = 50 + 120 = 170 mg ในทางปฏิบัติถ้าส่วน maintenance เริ่มปลดปล่อยพร้อม Di อาจลด Dm ลงด้วย kr0·tmax เพื่อไม่ให้ระดับยาสูงเกินในช่วงต้น",
      w: [
        "เป็น Di บวก kr0 เพียงหนึ่งชั่วโมง (50 + 10)",
        "เป็นเฉพาะส่วน maintenance ยังไม่รวม immediate dose",
        "ถูก — kr0 = 0.2 × 50 = 10 mg/h; Dt = 50 + 10×12 = 170 mg",
        "ใช้ kr0 = Di/t½ (50/3.47) แทน k·Di ซึ่งไม่ถูกต้อง",
        "ลืมคูณ k ทำให้คิดว่าต้องปลดปล่อย 50 mg ทุกชั่วโมง",
      ],
      k: "Robinson–Eriksen: kr0 = k·Di; Dt = Di + kr0·Td",
      d: "hard",
      ref: "Robinson JR, Eriksen SP. J Pharm Sci 1966;55:1254–1263; Shargel & Yu, Applied Biopharmaceutics & Pharmacokinetics 7th ed.",
      c: [
        "kr0 = k × Di = 0.2 h⁻¹ × 50 mg = 10 mg/h",
        "Dm = kr0 × Td = 10 × 12 = 120 mg",
        "Dt = Di + Dm = 50 + 120 = 170 mg",
      ],
    },
  ],
];
