import type { Ip1MockDomainContent } from "@/lib/ip1-mock/types";

export const NDDS: Ip1MockDomainContent = [
  // Mock Set 1 — ชุดที่ 1
  [
    {
      t: "HPMC hydrophilic matrix gel layer",
      p: "ยาเม็ดออกฤทธิ์นาน (extended-release) แบบ hydrophilic matrix ที่ใช้ HPMC K100M ประมาณ 30% w/w เมื่อสัมผัสของเหลวในทางเดินอาหาร กลไกหลักที่ควบคุมการปลดปล่อยยาคือข้อใด",
      o: [
        "HPMC ที่ผิวเม็ดดูดน้ำและพองตัวเป็นชั้น gel ยาละลายแล้วแพร่ผ่านชั้น gel ร่วมกับการกร่อน (erosion) ของ gel ด้านนอก",
        "แรงดัน osmotic ภายในเม็ดดันสารละลายยาออกทางรูที่เจาะด้วยเลเซอร์",
        "ยาแพร่ผ่านช่องว่าง (pore) ของโครงร่างที่ไม่ละลายน้ำซึ่งคงรูปตลอดทางเดินอาหาร",
        "ฟิล์มเคลือบที่ละลายเมื่อ pH สูงกว่า 5.5 ทำให้เม็ดยาแตกตัวในลำไส้เล็ก",
        "เอนไซม์ lipase ในลำไส้ย่อยสลายโครงร่างทำให้ยาถูกปลดปล่อยตามการย่อย",
      ],
      a: 0,
      r: "HPMC เป็น hydrophilic swellable polymer เมื่อเม็ดยาสัมผัสน้ำ polymer chain ที่ผิวจะ hydrate อย่างรวดเร็ว เกิดชั้น gel (gel layer) ที่หนืดล้อมรอบแกนแห้งด้านใน ชั้น gel นี้ทำหน้าที่เป็น diffusion barrier และป้องกันไม่ให้เม็ดแตกตัวทันที (ป้องกัน dose dumping)\n\nยาที่ละลายน้ำดีจะถูกปลดปล่อยส่วนใหญ่โดยการแพร่ผ่าน gel ส่วนยาที่ละลายน้ำน้อยจะออกมาด้วยการกร่อนของชั้น gel ด้านนอกที่ polymer chain คลายตัว (disentanglement) เป็นหลัก ปริมาณ HPMC ต้องเพียงพอ (โดยทั่วไปไม่น้อยกว่าประมาณ 20–30%) เพื่อให้ gel ต่อเนื่องเร็วพอ",
      w: [
        "ถูก — การเกิด gel layer ทำให้การปลดปล่อยถูกควบคุมด้วยทั้ง diffusion และ erosion ซึ่งเป็นลักษณะเฉพาะของ hydrophilic matrix",
        "เป็นกลไกของ osmotic pump ที่ต้องมี semipermeable membrane และ orifice ไม่ใช่ matrix ธรรมดา",
        "เป็นกลไกของ inert (insoluble) matrix เช่น ethylcellulose ซึ่งไม่พองตัวเป็น gel",
        "เป็นกลไกของ enteric (delayed-release) coating ซึ่งไม่ได้ยืดระยะเวลาการปลดปล่อย",
        "การย่อยด้วย lipase เกี่ยวกับ lipid matrix บางชนิด ไม่ใช่ HPMC ซึ่งเป็น cellulose ether ที่ไม่ถูกเอนไซม์ในลำไส้ย่อย",
      ],
      k: "HPMC matrix: hydration → gel layer → diffusion (ยาละลายดี) + erosion (ยาละลายน้อย)",
      d: "easy",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Modified-release oral drug delivery",
    },
    {
      t: "Korsmeyer-Peppas exponent for cylinder",
      p: "ยาเม็ด HPMC matrix รูปทรงกระบอก ปลดปล่อยยา (Mt/M∞) ได้ 0.20 ที่ 1 ชั่วโมง และ 0.40 ที่ 4 ชั่วโมง เมื่อวิเคราะห์ด้วย Korsmeyer–Peppas model (Mt/M∞ = k·tⁿ) ข้อใดแปลผลได้ถูกต้องที่สุด",
      o: [
        "n = 0.50 สำหรับรูปทรงกระบอกจัดเป็น anomalous (non-Fickian) transport คือ diffusion ร่วมกับ polymer relaxation/swelling",
        "n = 0.50 จัดเป็น Fickian diffusion อย่างสมบูรณ์เสมอไม่ว่าจะเป็นรูปทรงใด",
        "n = 1.00 จัดเป็น Case II transport ให้การปลดปล่อยแบบ zero-order",
        "n = 0.25 แสดงว่าการปลดปล่อยถูกควบคุมด้วย erosion อย่างเดียว",
        "n = 2.00 จัดเป็น Super Case II transport",
      ],
      a: 0,
      r: "สมการ Korsmeyer–Peppas ใช้กับข้อมูลช่วงต้น (Mt/M∞ ≤ 0.6) หาค่า n จาก log(Mt/M∞) = log k + n log t ได้ n = log(0.40/0.20)/log(4/1) = 0.301/0.602 = 0.50\n\nเกณฑ์แปลผลขึ้นกับรูปทรง: แผ่นบาง (thin film) n = 0.5 คือ Fickian, 0.5–1.0 anomalous, 1.0 Case II; ทรงกระบอก n = 0.45 คือ Fickian, 0.45 < n < 0.89 anomalous, 0.89 Case II; ทรงกลม 0.43 และ 0.85 ตามลำดับ ดังนั้นสำหรับเม็ดทรงกระบอก n = 0.50 จึงอยู่ในช่วง anomalous transport ซึ่งสอดคล้องกับ HPMC ที่ทั้งแพร่และพองตัว",
      w: [
        "ถูก — n = 0.50 อยู่ระหว่าง 0.45 และ 0.89 ของทรงกระบอก จึงเป็น anomalous transport (diffusion + relaxation)",
        "n = 0.5 เป็น Fickian เฉพาะ thin film; ทรงกระบอกใช้ค่าตัด 0.45",
        "คำนวณผิด ข้อมูลเพิ่มขึ้น 2 เท่าเมื่อเวลาเพิ่ม 4 เท่า ไม่ใช่เพิ่มตามเวลาแบบเส้นตรง",
        "คำนวณผิดและค่า n < 0.45 ไม่ได้หมายถึง erosion-controlled",
        "คำนวณผิด ข้อมูลไม่ได้เพิ่มแบบกำลังสองของเวลา",
      ],
      k: "Peppas: ทรงกระบอก 0.45 / 0.89, แผ่นบาง 0.5 / 1.0, ทรงกลม 0.43 / 0.85 — ใช้กับ Mt/M∞ ≤ 60%",
      d: "hard",
      ref: "Ritger PL, Peppas NA. J Control Release 1987;5:23–36 & 37–42",
      c: [
        "log(Mt/M∞) = log k + n·log t",
        "n = log(0.40/0.20) / log(4/1) = 0.301 / 0.602 = 0.50",
        "ทรงกระบอก: 0.45 < 0.50 < 0.89 → anomalous transport",
      ],
    },
    {
      t: "Zero-order maintenance release rate",
      p: "ต้องการออกแบบยาเม็ด extended-release ที่ปลดปล่อยแบบ zero-order เพื่อรักษาระดับยาในพลาสมาที่ steady state (Css) = 5 mg/L ยามี clearance = 4 L/h และ F = 1 อัตราการปลดปล่อยยา (k0) ที่ต้องการคือเท่าใด",
      o: ["1.25 mg/h", "5 mg/h", "20 mg/h", "60 mg/h", "240 mg/h"],
      a: 2,
      r: "ที่ steady state อัตราที่ยาเข้าสู่ร่างกายต้องเท่ากับอัตราการกำจัด เมื่อการปลดปล่อยเป็น rate-limiting step และ F = 1 จะได้ k0 = Css × CL = 5 mg/L × 4 L/h = 20 mg/h\n\nหลักนี้คือแนวคิดพื้นฐานของการออกแบบ ER ที่ต้องการให้ระบบนำส่งทำตัวเหมือน IV infusion ถ้าต้องการให้ครอบคลุม 12 ชั่วโมงก็ต้องบรรจุยาส่วน maintenance 20 × 12 = 240 mg (ไม่รวม loading dose)",
      w: [
        "เกิดจากการหาร Css ด้วย CL (5/4) ซึ่งไม่ถูกต้องตามมิติ",
        "เป็นค่า Css ไม่ใช่อัตราการปลดปล่อย",
        "ถูก — k0 = Css × CL = 5 × 4 = 20 mg/h",
        "เป็นการคูณกับเวลา 3 ชั่วโมงโดยไม่มีเหตุผล",
        "240 mg คือปริมาณยาที่ต้องปลดปล่อยใน 12 ชั่วโมง ไม่ใช่อัตราต่อชั่วโมง",
      ],
      k: "Zero-order ER: k0 = Css × CL / F (เหมือน infusion rate)",
      d: "medium",
      ref: "Shargel L, Yu A. Applied Biopharmaceutics & Pharmacokinetics 7th ed., Ch. Modified-release drug products",
      c: ["k0 = Css × CL / F", "k0 = 5 mg/L × 4 L/h / 1 = 20 mg/h"],
    },
    {
      t: "Eudragit L100-55 dissolution pH",
      p: "ต้องการเคลือบเม็ดยา pantoprazole ให้ทนกรดในกระเพาะอาหารและเริ่มปลดปล่อยยาที่ duodenum (pH ประมาณ 5.5–6) polymer ชนิดใดเหมาะสมที่สุด",
      o: [
        "Eudragit L100-55 (methacrylic acid–ethyl acrylate copolymer 1:1)",
        "Eudragit E100 (aminoalkyl methacrylate copolymer)",
        "Eudragit RS 100 (ammonio methacrylate copolymer type B)",
        "Eudragit S100 (methacrylic acid–methyl methacrylate copolymer 1:2)",
        "Eudragit NE 30 D (neutral ethyl acrylate–methyl methacrylate copolymer)",
      ],
      a: 0,
      r: "Enteric polymer ประเภท anionic methacrylate มีหมู่ carboxylic acid ซึ่งไม่แตกตัวและไม่ละลายใน pH ต่ำ แต่แตกตัวและละลายเมื่อ pH สูงกว่าค่าเฉพาะ: Eudragit L100-55 / L30 D-55 ละลายที่ pH > 5.5 (duodenum), L100 ที่ pH > 6.0 และ S100 / FS 30 D ที่ pH > 7.0 (ileum ส่วนปลาย/colon)\n\nEudragit E ละลายใน pH < 5 จึงใช้กันความชื้น/กลบรส ส่วน RS, RL และ NE ไม่ละลายทุก pH ใช้เป็น release-controlling membrane สำหรับ sustained release",
      w: [
        "ถูก — L100-55 ละลายที่ pH > 5.5 เหมาะกับการปลดปล่อยที่ duodenum",
        "E100 เป็น cationic polymer ละลายในกระเพาะ (pH < 5) จึงทำตรงข้ามกับ enteric",
        "RS 100 ไม่ละลายทุก pH ใช้ควบคุมการปลดปล่อยแบบ sustained ไม่ใช่ enteric",
        "S100 ละลายที่ pH > 7 ปลดปล่อยช้าเกินไป เหมาะกับ ileum/colon",
        "NE 30 D เป็น neutral polymer ไม่มีหมู่ที่แตกตัว จึงไม่ละลายตาม pH",
      ],
      k: "Eudragit: E < pH 5 | L100-55 > 5.5 | L100 > 6 | S100/FS > 7 | RL/RS/NE ไม่ละลาย",
      d: "easy",
      ref: "Evonik EUDRAGIT® technical information; Handbook of Pharmaceutical Excipients 9th ed. (Polymethacrylates)",
    },
    {
      t: "Transdermal steady-state flux calculation",
      p: "ทดสอบการซึมผ่าน membrane แบบ Franz cell ภายใต้ sink condition ยามี diffusion coefficient ในเมมเบรน (D) = 1 × 10⁻⁸ cm²/s, partition coefficient (K) = 0.5, ความเข้มข้นใน donor = 10 mg/mL และเมมเบรนหนา 20 µm ค่า steady-state flux (Jss) ใกล้เคียงข้อใดที่สุด",
      o: ["0.025 µg/cm²/h", "9 µg/cm²/h", "45 µg/cm²/h", "90 µg/cm²/h", "180 µg/cm²/h"],
      a: 3,
      r: "จาก Fick's first law ที่ steady state Jss = D·K·Cd / h (เมื่อ receptor เป็น sink) แปลงหน่วยให้สอดคล้อง: h = 20 µm = 0.002 cm, Cd = 10 mg/mL = 10 mg/cm³\n\nJss = (1×10⁻⁸ × 0.5 × 10) / 0.002 = 2.5×10⁻⁵ mg/cm²/s แปลงเป็นต่อชั่วโมง ×3600 = 0.09 mg/cm²/h = 90 µg/cm²/h ข้อสังเกตสำคัญคือ flux แปรผันตรงกับ K และ Cd และแปรผกผันกับความหนา ดังนั้นการเพิ่ม thermodynamic activity ของยาในตำรับ (ใกล้ saturation) จึงเพิ่ม flux ได้",
      w: [
        "ลืมคูณ 3600 และแปลงหน่วย mg เป็น µg ไม่ถูกต้อง",
        "แปลงหน่วยความหนาหรือเวลาผิด ทำให้ค่าต่ำเกิน 10 เท่า",
        "คูณด้วย K ซ้ำสองครั้ง (0.5 × 0.5) ทำให้ได้ครึ่งหนึ่งของค่าจริง",
        "ถูก — Jss = DKC/h = 2.5×10⁻⁵ mg/cm²/s = 90 µg/cm²/h",
        "ลืมคูณ partition coefficient (K = 0.5)",
      ],
      k: "Jss = D·K·Cd / h — แปลง µm → cm และ s → h ให้ถูก; flux ∝ thermodynamic activity",
      d: "hard",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Transdermal drug delivery; Martin's Physical Pharmacy 7th ed., Ch. Diffusion",
      c: [
        "h = 20 µm = 0.002 cm; Cd = 10 mg/cm³",
        "Jss = (1×10⁻⁸ cm²/s × 0.5 × 10 mg/cm³) / 0.002 cm = 2.5×10⁻⁵ mg/cm²/s",
        "× 3600 s/h = 0.09 mg/cm²/h = 90 µg/cm²/h",
      ],
    },
    {
      t: "MMAD and regional lung deposition",
      p: "ผลิตภัณฑ์ยาสูดพ่นตัวหนึ่งต้องการให้ยาเข้าถึงหลอดลมส่วนปลายและถุงลม (lower airways) ได้มากที่สุด ควรออกแบบให้อนุภาคมี mass median aerodynamic diameter (MMAD) อยู่ในช่วงใด",
      o: [
        "ประมาณ 1–5 µm",
        "ประมาณ 10–20 µm",
        "ประมาณ 5–10 µm",
        "น้อยกว่า 0.1 µm",
        "มากกว่า 30 µm",
      ],
      a: 0,
      r: "การตกค้างของอนุภาคในทางเดินหายใจขึ้นกับ aerodynamic diameter เป็นหลัก อนุภาค > 10 µm ตกที่ oropharynx ด้วย inertial impaction; 5–10 µm ตกที่ทางเดินหายใจส่วนบน/หลอดลมใหญ่; 1–5 µm (fine particles) เข้าถึงหลอดลมส่วนปลายและถุงลมด้วย sedimentation; อนุภาคเล็กมาก (< 0.5–1 µm) จำนวนมากถูกหายใจออกเพราะไม่ตกค้าง แม้อนุภาคระดับ nanometer จะตกค้างด้วย diffusion ได้บ้าง\n\nดังนั้นตำรับยาสูดส่วนใหญ่ออกแบบให้ MMAD อยู่ราว 1–5 µm และวัดด้วย cascade impactor",
      w: [
        "ถูก — ช่วง 1–5 µm คือ respirable fraction ที่เข้าถึงทางเดินหายใจส่วนล่างได้ดี",
        "อนุภาคขนาดนี้ตกที่คอและปากด้วย impaction เป็นส่วนใหญ่",
        "ตกที่ทางเดินหายใจส่วนต้นและหลอดลมใหญ่ ไม่ถึงถุงลม",
        "อนุภาคเล็กมากส่วนหนึ่งตกด้วย diffusion แต่จำนวนมากถูกหายใจออกและบรรจุมวลยาได้น้อย",
        "ใหญ่เกินไป ติดที่ปากและลำคอเกือบทั้งหมด",
      ],
      k: "> 10 µm ปาก/คอ | 5–10 µm ทางเดินหายใจส่วนบน | 1–5 µm ลึกถึงหลอดลมเล็ก/ถุงลม | < 1 µm หายใจออก",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Pulmonary drug delivery; USP <601>",
    },
    {
      t: "PLGA composition and degradation rate",
      p: "ทีมพัฒนาไมโครสเฟียร์ PLGA สำหรับ peptide ต้องการให้ polymer ย่อยสลายและปลดปล่อยยาหมดเร็วที่สุด (ประมาณ 1 เดือน) ควรเลือก PLGA แบบใด",
      o: [
        "PLGA 50:50 (lactide:glycolide) น้ำหนักโมเลกุลต่ำ ปลายสายเป็น free carboxylic acid",
        "PLGA 85:15 น้ำหนักโมเลกุลสูง ปลายสายเป็น ester (end-capped)",
        "PLA (100% lactide) น้ำหนักโมเลกุลสูง",
        "PLGA 75:25 น้ำหนักโมเลกุลสูง ปลายสายเป็น ester (end-capped)",
        "PLGA 50:50 น้ำหนักโมเลกุลสูง ปลายสายเป็น ester (end-capped)",
      ],
      a: 0,
      r: "PLGA ย่อยสลายด้วย hydrolysis ของ ester bond แบบ bulk erosion อัตราการย่อยสลายขึ้นกับ (1) สัดส่วน lactide:glycolide — lactide มีหมู่ methyl ที่ hydrophobic กว่า สัดส่วน lactide สูงจะดูดน้ำน้อยและย่อยช้า โดย 50:50 ย่อยเร็วที่สุดเพราะเป็น amorphous และ hydrophilic พอสมควร (2) น้ำหนักโมเลกุล — ต่ำย่อยเร็วกว่า (3) ปลายสาย — acid-terminated ดูดน้ำได้ดีกว่าและกรดที่ปลายเร่ง autocatalysis จึงย่อยเร็วกว่า ester end-capped\n\nผลิตภัณฑ์ระยะ 1 เดือนจึงมักใช้ PLGA 50:50 MW ต่ำ ส่วนระยะ 3–6 เดือนใช้ 75:25 หรือ 85:15 หรือ PLA",
      w: [
        "ถูก — 50:50, MW ต่ำ และ acid end group ล้วนเร่ง hydrolysis จึงย่อยสลายเร็วที่สุด",
        "lactide สูง MW สูงและ end-capped ทำให้ย่อยช้าเหมาะกับระยะหลายเดือน",
        "PLA hydrophobic และอาจมีความเป็นผลึก (L-PLA) ย่อยสลายช้ามาก",
        "75:25 MW สูงย่อยช้ากว่า 50:50 อย่างชัดเจน",
        "แม้เป็น 50:50 แต่ MW สูงและ end-capped จึงช้ากว่าตัวเลือกที่ถูก",
      ],
      k: "PLGA ย่อยเร็ว: 50:50 > 75:25 > 85:15 > PLA; MW ต่ำ และ acid-terminated เร็วกว่า",
      d: "medium",
      ref: "Makadia HK, Siegel SJ. Polymers 2011;3:1377–1397; Aulton's Pharmaceutics 6th ed.",
    },
    {
      t: "Push-pull osmotic pump design",
      p: "ต้องการพัฒนายาเม็ด osmotic ปลดปล่อยแบบ zero-order สำหรับยาที่ละลายน้ำได้น้อยมาก (เช่น nifedipine) การออกแบบแบบใดเหมาะสมที่สุด",
      o: [
        "Push-pull osmotic pump: เม็ด 2 ชั้น (drug layer + push layer ที่มี polyethylene oxide และ osmotic agent) เคลือบ semipermeable membrane และเจาะรูด้าน drug layer",
        "Elementary osmotic pump แกนยาชั้นเดียว อาศัยยาเป็น osmotic agent เอง",
        "Hydrophilic matrix HPMC ไม่มีฟิล์มเคลือบ",
        "เคลือบด้วย Eudragit L100-55 ให้ละลายใน duodenum",
        "เม็ดแกนยาเคลือบ semipermeable membrane โดยไม่เจาะรู",
      ],
      a: 0,
      r: "Elementary osmotic pump (EOP) อาศัยการที่ยาละลายเป็นสารละลายอิ่มตัวในแกนเพื่อสร้าง osmotic pressure จึงเหมาะกับยาที่ละลายน้ำได้ปานกลางถึงดี ยาที่ละลายน้ำน้อยมากจะสร้างแรงดันได้ไม่พอและออกทางรูได้น้อย\n\nPush-pull osmotic pump (เช่น nifedipine GITS) แก้ปัญหานี้: น้ำซึมผ่าน cellulose acetate membrane เข้าสู่ทั้งสองชั้น ชั้นยาจะกลายเป็น suspension ที่ไหลได้ ส่วน push layer ที่มี polyethylene oxide MW สูงและ NaCl จะพองตัวดันยาออกทางรูด้านชั้นยาด้วยอัตราคงที่ จึงได้ zero-order ที่ไม่ขึ้นกับ pH และการบีบตัวของทางเดินอาหาร",
      w: [
        "ถูก — push layer ที่พองตัวดัน drug suspension ออกทาง orifice ทำให้ยาละลายน้ำน้อยปลดปล่อยแบบ zero-order ได้",
        "EOP ต้องการยาที่ละลายน้ำได้พอสร้าง osmotic pressure ยาละลายน้ำน้อยมากจึงปลดปล่อยไม่สมบูรณ์",
        "HPMC matrix มักให้การปลดปล่อยแบบ diffusion/erosion ที่ไม่เป็น zero-order อย่างแท้จริงและไวต่อสภาวะทางเดินอาหารมากกว่า",
        "Enteric coating เป็น delayed-release ไม่ได้ทำให้ปลดปล่อยแบบ zero-order",
        "ไม่มี orifice ยาจะออกไม่ได้ หรือเมมเบรนแตกจากแรงดันแบบควบคุมไม่ได้",
      ],
      k: "ยาละลายน้ำน้อย → push-pull (2 ชั้น, PEO push layer); ยาละลายดี → EOP ได้",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed.; Theeuwes F. J Pharm Sci 1975;64:1987; Swanson DR et al. Am J Med 1987;83(6B):3–9",
    },
    {
      t: "Alcohol-induced dose dumping",
      p: "ยาแคปซูล opioid ชนิด extended-release รายหนึ่งถูกถอนออกจากตลาดหลังพบว่าเมื่อรับประทานร่วมกับเครื่องดื่มแอลกอฮอล์ ระดับยาสูงสุดในเลือดเพิ่มขึ้นหลายเท่า สาเหตุทางเภสัชกรรมที่สำคัญที่สุดคือข้อใด",
      o: [
        "Polymer หรือส่วนประกอบที่ควบคุมการปลดปล่อยละลายหรือเสียสภาพใน ethanol ทำให้ยาที่ตั้งใจปลดปล่อยใน 24 ชั่วโมงหลุดออกมาเกือบทั้งหมดในเวลาสั้น (dose dumping)",
        "Ethanol ยับยั้ง CYP3A4 อย่างแรง ทำให้ clearance ของยาลดลง",
        "Ethanol เพิ่ม gastric pH ทำให้ enteric coating ละลายก่อนเวลา",
        "Ethanol ทำให้กระเพาะอาหารบีบตัวช้า ยาจึงอยู่ในกระเพาะนานขึ้น",
        "Ethanol ทำให้ยาตกผลึกภายในแคปซูลและดูดซึมช้าลง",
      ],
      a: 0,
      r: "กรณีศึกษาสำคัญคือ hydromorphone ER capsule (Palladone) ซึ่งถูกระงับการจำหน่ายในปี 2005 เพราะ ethanol ทำให้กลไกควบคุมการปลดปล่อยล้มเหลว ยาจึงถูกปลดปล่อยออกมาเกือบหมดในคราวเดียว (dose dumping) ซึ่งอันตรายมากกับยาที่มีดัชนีการรักษาแคบและบรรจุปริมาณยามากสำหรับทั้งวัน\n\nPolymer หลายชนิดที่ใช้ใน ER เช่น ethylcellulose และ ammonio methacrylate copolymer ละลายได้ใน ethanol ความเข้มข้นสูง ผู้พัฒนาจึงต้องประเมินความทนทานต่อ ethanol ในหลอดทดลอง (เช่น 5–40% ethanol) และเลือกระบบที่ทน เช่น matrix ที่ใช้ polymer ที่ไม่ละลายใน ethanol ร่วมกับการให้คำแนะนำผู้ป่วยหลีกเลี่ยงแอลกอฮอล์",
      w: [
        "ถูก — dose dumping เกิดจาก ethanol ทำลายกลไกควบคุมการปลดปล่อยของตำรับ ไม่ใช่ PK interaction",
        "ethanol แบบ acute ไม่ได้เป็น strong CYP3A4 inhibitor และไม่ได้อธิบาย Cmax ที่เพิ่มเป็นหลายเท่าอย่างรวดเร็ว",
        "ethanol ไม่ได้เพิ่ม gastric pH อย่างมีนัยสำคัญ และตำรับนี้ไม่ใช่ enteric product",
        "การชะลอ gastric emptying จะทำให้ Cmax ลดลงหรือช้าลง ไม่ใช่เพิ่มขึ้นหลายเท่า",
        "การตกผลึกจะลดการดูดซึม ซึ่งตรงข้ามกับเหตุการณ์ที่เกิดขึ้น",
      ],
      k: "ER ที่บรรจุยาปริมาณมาก ต้องทดสอบ alcohol dose dumping (in vitro ใน ethanol 5–40%) — บทเรียนจาก Palladone",
      d: "hard",
      ref: "US FDA Alert: Palladone (hydromorphone) ER capsules, July 2005; Meyer RJ, Hussain AS. AAPS J 2005",
    },
    {
      t: "SEDDS composition and self-emulsification",
      p: "บริษัทต้องการเพิ่มชีวประสิทธิผลของยาที่มี log P = 5 และละลายน้ำได้น้อยมาก โดยพัฒนาเป็น self-emulsifying drug delivery system (SEDDS) บรรจุใน soft gelatin capsule ข้อใดอธิบายระบบนี้ได้ถูกต้องที่สุด",
      o: [
        "เป็นของผสมเนื้อเดียวที่ไม่มีน้ำของ oil, surfactant และ co-solvent ซึ่งเมื่อพบของเหลวในทางเดินอาหารและการบีบตัวเบาๆ จะเกิด emulsion ละเอียดได้เองโดยยายังอยู่ในสภาพละลาย",
        "เป็น o/w emulsion ที่เตรียมสำเร็จแล้วด้วย high-pressure homogenizer ก่อนบรรจุแคปซูล",
        "เป็นอนุภาคไขมันของแข็งที่ยาฝังอยู่ในผลึกไขมัน ปลดปล่อยด้วยการกร่อน",
        "เป็นผงยาผสม polymer ในสภาพอสัณฐานที่เตรียมด้วยการหลอม",
        "เป็นสารละลายยาในน้ำที่ใช้ cyclodextrin เป็นตัวช่วยละลาย",
      ],
      a: 0,
      r: "SEDDS คือ isotropic mixture ของน้ำมัน (เช่น medium-chain triglyceride) surfactant ที่มี HLB สูง (เช่น polysorbate 80, polyoxyl 35 castor oil) และ co-solvent (เช่น ethanol, PEG, propylene glycol) โดยไม่มีน้ำ ยาละลายอยู่ใน preconcentrate เมื่อสัมผัสของเหลวในทางเดินอาหารพร้อมการบีบตัวเพียงเล็กน้อยจะเกิด emulsion ละเอียดเอง ช่วยหลีกเลี่ยงขั้นตอน dissolution ที่เป็น rate-limiting step ของยา BCS class II\n\nนอกจากนี้ lipid ยังกระตุ้นการหลั่งน้ำดี เกิด mixed micelle และอาจส่งเสริม lymphatic transport สำหรับยาที่ lipophilic มาก ตัวอย่างผลิตภัณฑ์ได้แก่ cyclosporine microemulsion preconcentrate",
      w: [
        "ถูก — SEDDS เป็น anhydrous preconcentrate ที่ emulsify ได้เองในร่างกาย โดยยายังอยู่ในรูปละลาย",
        "SEDDS ไม่ได้ทำ emulsion ไว้ก่อน และการมีน้ำปริมาณมากไม่เข้ากับ soft gelatin capsule",
        "เป็นคำอธิบายของ solid lipid nanoparticle (SLN) ไม่ใช่ SEDDS",
        "เป็นคำอธิบายของ amorphous solid dispersion โดย hot-melt extrusion",
        "เป็นแนวทางเพิ่มการละลายด้วย inclusion complex ไม่ใช่ lipid-based self-emulsifying system",
      ],
      k: "SEDDS = oil + surfactant (HLB สูง) + co-solvent, ไม่มีน้ำ, emulsify เองในทางเดินอาหาร → ข้าม dissolution step",
      d: "medium",
      ref: "Pouton CW. Eur J Pharm Sci 2006;29:278–287; Aulton's Pharmaceutics 6th ed.",
    },
  ],
];
