import type { Ip1MockDomainContent } from "@/lib/ip1-mock/types";

export const NDDS: Ip1MockDomainContent = [
  // Mock Set 1 — ชุดที่ 1
  [
    {
      t: "HPMC hydrophilic matrix gel layer",
      p: "ยาเม็ดออกฤทธิ์นาน (extended-release) แบบ hydrophilic matrix ที่ใช้ HPMC K100M ประมาณ 30% w/w เมื่อสัมผัสของเหลวในทางเดินอาหาร กลไกหลักที่ควบคุมการปลดปล่อยยาคือข้อใด",
      o: [
        "HPMC ที่ผิวเม็ดดูดน้ำและพองตัวเป็นชั้น gel ยาละลายแล้วแพร่ผ่านชั้น gel ร่วมกับการกร่อน (erosion) ของ gel ด้านนอก",
        "แรงดัน osmotic ภายในเม็ดดันสารละลายยาออกทางรูที่เจาะด้วยเลเซอร์",
        "ยาแพร่ผ่านช่องว่าง (pore) ของโครงร่างที่ไม่ละลายน้ำซึ่งคงรูปตลอดทางเดินอาหาร",
        "ฟิล์มเคลือบที่ละลายเมื่อ pH สูงกว่า 5.5 ทำให้เม็ดยาแตกตัวในลำไส้เล็ก",
        "เอนไซม์ lipase ในลำไส้ย่อยสลายโครงร่างทำให้ยาถูกปลดปล่อยตามการย่อย",
      ],
      a: 0,
      r: "HPMC เป็น hydrophilic swellable polymer เมื่อเม็ดยาสัมผัสน้ำ polymer chain ที่ผิวจะ hydrate อย่างรวดเร็ว เกิดชั้น gel (gel layer) ที่หนืดล้อมรอบแกนแห้งด้านใน ชั้น gel นี้ทำหน้าที่เป็น diffusion barrier และป้องกันไม่ให้เม็ดแตกตัวทันที (ป้องกัน dose dumping)\n\nยาที่ละลายน้ำดีจะถูกปลดปล่อยส่วนใหญ่โดยการแพร่ผ่าน gel ส่วนยาที่ละลายน้ำน้อยจะออกมาด้วยการกร่อนของชั้น gel ด้านนอกที่ polymer chain คลายตัว (disentanglement) เป็นหลัก ปริมาณ HPMC ต้องเพียงพอ (โดยทั่วไปไม่น้อยกว่าประมาณ 20–30%) เพื่อให้ gel ต่อเนื่องเร็วพอ",
      w: [
        "ถูก — การเกิด gel layer ทำให้การปลดปล่อยถูกควบคุมด้วยทั้ง diffusion และ erosion ซึ่งเป็นลักษณะเฉพาะของ hydrophilic matrix",
        "เป็นกลไกของ osmotic pump ที่ต้องมี semipermeable membrane และ orifice ไม่ใช่ matrix ธรรมดา",
        "เป็นกลไกของ inert (insoluble) matrix เช่น ethylcellulose ซึ่งไม่พองตัวเป็น gel",
        "เป็นกลไกของ enteric (delayed-release) coating ซึ่งไม่ได้ยืดระยะเวลาการปลดปล่อย",
        "การย่อยด้วย lipase เกี่ยวกับ lipid matrix บางชนิด ไม่ใช่ HPMC ซึ่งเป็น cellulose ether ที่ไม่ถูกเอนไซม์ในลำไส้ย่อย",
      ],
      k: "HPMC matrix: hydration → gel layer → diffusion (ยาละลายดี) + erosion (ยาละลายน้อย)",
      d: "easy",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Modified-release oral drug delivery",
    },
    {
      t: "Korsmeyer-Peppas exponent for cylinder",
      p: "ยาเม็ด HPMC matrix รูปทรงกระบอก ปลดปล่อยยา (Mt/M∞) ได้ 0.20 ที่ 1 ชั่วโมง และ 0.40 ที่ 4 ชั่วโมง เมื่อวิเคราะห์ด้วย Korsmeyer–Peppas model (Mt/M∞ = k·tⁿ) ข้อใดแปลผลได้ถูกต้องที่สุด",
      o: [
        "n = 0.50 สำหรับรูปทรงกระบอกจัดเป็น anomalous (non-Fickian) transport คือ diffusion ร่วมกับ polymer relaxation/swelling",
        "n = 0.50 จัดเป็น Fickian diffusion อย่างสมบูรณ์เสมอไม่ว่าจะเป็นรูปทรงใด",
        "n = 1.00 จัดเป็น Case II transport ให้การปลดปล่อยแบบ zero-order",
        "n = 0.25 แสดงว่าการปลดปล่อยถูกควบคุมด้วย erosion อย่างเดียว",
        "n = 2.00 จัดเป็น Super Case II transport",
      ],
      a: 0,
      r: "สมการ Korsmeyer–Peppas ใช้กับข้อมูลช่วงต้น (Mt/M∞ ≤ 0.6) หาค่า n จาก log(Mt/M∞) = log k + n log t ได้ n = log(0.40/0.20)/log(4/1) = 0.301/0.602 = 0.50\n\nเกณฑ์แปลผลขึ้นกับรูปทรง: แผ่นบาง (thin film) n = 0.5 คือ Fickian, 0.5–1.0 anomalous, 1.0 Case II; ทรงกระบอก n = 0.45 คือ Fickian, 0.45 < n < 0.89 anomalous, 0.89 Case II; ทรงกลม 0.43 และ 0.85 ตามลำดับ ดังนั้นสำหรับเม็ดทรงกระบอก n = 0.50 จึงอยู่ในช่วง anomalous transport ซึ่งสอดคล้องกับ HPMC ที่ทั้งแพร่และพองตัว",
      w: [
        "ถูก — n = 0.50 อยู่ระหว่าง 0.45 และ 0.89 ของทรงกระบอก จึงเป็น anomalous transport (diffusion + relaxation)",
        "n = 0.5 เป็น Fickian เฉพาะ thin film; ทรงกระบอกใช้ค่าตัด 0.45",
        "คำนวณผิด ข้อมูลเพิ่มขึ้น 2 เท่าเมื่อเวลาเพิ่ม 4 เท่า ไม่ใช่เพิ่มตามเวลาแบบเส้นตรง",
        "คำนวณผิดและค่า n < 0.45 ไม่ได้หมายถึง erosion-controlled",
        "คำนวณผิด ข้อมูลไม่ได้เพิ่มแบบกำลังสองของเวลา",
      ],
      k: "Peppas: ทรงกระบอก 0.45 / 0.89, แผ่นบาง 0.5 / 1.0, ทรงกลม 0.43 / 0.85 — ใช้กับ Mt/M∞ ≤ 60%",
      d: "hard",
      ref: "Ritger PL, Peppas NA. J Control Release 1987;5:23–36 & 37–42",
      c: [
        "log(Mt/M∞) = log k + n·log t",
        "n = log(0.40/0.20) / log(4/1) = 0.301 / 0.602 = 0.50",
        "ทรงกระบอก: 0.45 < 0.50 < 0.89 → anomalous transport",
      ],
    },
    {
      t: "Zero-order maintenance release rate",
      p: "ต้องการออกแบบยาเม็ด extended-release ที่ปลดปล่อยแบบ zero-order เพื่อรักษาระดับยาในพลาสมาที่ steady state (Css) = 5 mg/L ยามี clearance = 4 L/h และ F = 1 อัตราการปลดปล่อยยา (k0) ที่ต้องการคือเท่าใด",
      o: ["1.25 mg/h", "5 mg/h", "20 mg/h", "60 mg/h", "240 mg/h"],
      a: 2,
      r: "ที่ steady state อัตราที่ยาเข้าสู่ร่างกายต้องเท่ากับอัตราการกำจัด เมื่อการปลดปล่อยเป็น rate-limiting step และ F = 1 จะได้ k0 = Css × CL = 5 mg/L × 4 L/h = 20 mg/h\n\nหลักนี้คือแนวคิดพื้นฐานของการออกแบบ ER ที่ต้องการให้ระบบนำส่งทำตัวเหมือน IV infusion ถ้าต้องการให้ครอบคลุม 12 ชั่วโมงก็ต้องบรรจุยาส่วน maintenance 20 × 12 = 240 mg (ไม่รวม loading dose)",
      w: [
        "เกิดจากการหาร Css ด้วย CL (5/4) ซึ่งไม่ถูกต้องตามมิติ",
        "เป็นค่า Css ไม่ใช่อัตราการปลดปล่อย",
        "ถูก — k0 = Css × CL = 5 × 4 = 20 mg/h",
        "เป็นการคูณกับเวลา 3 ชั่วโมงโดยไม่มีเหตุผล",
        "240 mg คือปริมาณยาที่ต้องปลดปล่อยใน 12 ชั่วโมง ไม่ใช่อัตราต่อชั่วโมง",
      ],
      k: "Zero-order ER: k0 = Css × CL / F (เหมือน infusion rate)",
      d: "medium",
      ref: "Shargel L, Yu A. Applied Biopharmaceutics & Pharmacokinetics 7th ed., Ch. Modified-release drug products",
      c: ["k0 = Css × CL / F", "k0 = 5 mg/L × 4 L/h / 1 = 20 mg/h"],
    },
    {
      t: "Eudragit L100-55 dissolution pH",
      p: "ต้องการเคลือบเม็ดยา pantoprazole ให้ทนกรดในกระเพาะอาหารและเริ่มปลดปล่อยยาที่ duodenum (pH ประมาณ 5.5–6) polymer ชนิดใดเหมาะสมที่สุด",
      o: [
        "Eudragit L100-55 (methacrylic acid–ethyl acrylate copolymer 1:1)",
        "Eudragit E100 (aminoalkyl methacrylate copolymer)",
        "Eudragit RS 100 (ammonio methacrylate copolymer type B)",
        "Eudragit S100 (methacrylic acid–methyl methacrylate copolymer 1:2)",
        "Eudragit NE 30 D (neutral ethyl acrylate–methyl methacrylate copolymer)",
      ],
      a: 0,
      r: "Enteric polymer ประเภท anionic methacrylate มีหมู่ carboxylic acid ซึ่งไม่แตกตัวและไม่ละลายใน pH ต่ำ แต่แตกตัวและละลายเมื่อ pH สูงกว่าค่าเฉพาะ: Eudragit L100-55 / L30 D-55 ละลายที่ pH > 5.5 (duodenum), L100 ที่ pH > 6.0 และ S100 / FS 30 D ที่ pH > 7.0 (ileum ส่วนปลาย/colon)\n\nEudragit E ละลายใน pH < 5 จึงใช้กันความชื้น/กลบรส ส่วน RS, RL และ NE ไม่ละลายทุก pH ใช้เป็น release-controlling membrane สำหรับ sustained release",
      w: [
        "ถูก — L100-55 ละลายที่ pH > 5.5 เหมาะกับการปลดปล่อยที่ duodenum",
        "E100 เป็น cationic polymer ละลายในกระเพาะ (pH < 5) จึงทำตรงข้ามกับ enteric",
        "RS 100 ไม่ละลายทุก pH ใช้ควบคุมการปลดปล่อยแบบ sustained ไม่ใช่ enteric",
        "S100 ละลายที่ pH > 7 ปลดปล่อยช้าเกินไป เหมาะกับ ileum/colon",
        "NE 30 D เป็น neutral polymer ไม่มีหมู่ที่แตกตัว จึงไม่ละลายตาม pH",
      ],
      k: "Eudragit: E < pH 5 | L100-55 > 5.5 | L100 > 6 | S100/FS > 7 | RL/RS/NE ไม่ละลาย",
      d: "easy",
      ref: "Evonik EUDRAGIT® technical information; Handbook of Pharmaceutical Excipients 9th ed. (Polymethacrylates)",
    },
    {
      t: "Transdermal steady-state flux calculation",
      p: "ทดสอบการซึมผ่าน membrane แบบ Franz cell ภายใต้ sink condition ยามี diffusion coefficient ในเมมเบรน (D) = 1 × 10⁻⁸ cm²/s, partition coefficient (K) = 0.5, ความเข้มข้นใน donor = 10 mg/mL และเมมเบรนหนา 20 µm ค่า steady-state flux (Jss) ใกล้เคียงข้อใดที่สุด",
      o: ["0.025 µg/cm²/h", "9 µg/cm²/h", "45 µg/cm²/h", "90 µg/cm²/h", "180 µg/cm²/h"],
      a: 3,
      r: "จาก Fick's first law ที่ steady state Jss = D·K·Cd / h (เมื่อ receptor เป็น sink) แปลงหน่วยให้สอดคล้อง: h = 20 µm = 0.002 cm, Cd = 10 mg/mL = 10 mg/cm³\n\nJss = (1×10⁻⁸ × 0.5 × 10) / 0.002 = 2.5×10⁻⁵ mg/cm²/s แปลงเป็นต่อชั่วโมง ×3600 = 0.09 mg/cm²/h = 90 µg/cm²/h ข้อสังเกตสำคัญคือ flux แปรผันตรงกับ K และ Cd และแปรผกผันกับความหนา ดังนั้นการเพิ่ม thermodynamic activity ของยาในตำรับ (ใกล้ saturation) จึงเพิ่ม flux ได้",
      w: [
        "ลืมคูณ 3600 และแปลงหน่วย mg เป็น µg ไม่ถูกต้อง",
        "แปลงหน่วยความหนาหรือเวลาผิด ทำให้ค่าต่ำเกิน 10 เท่า",
        "คูณด้วย K ซ้ำสองครั้ง (0.5 × 0.5) ทำให้ได้ครึ่งหนึ่งของค่าจริง",
        "ถูก — Jss = DKC/h = 2.5×10⁻⁵ mg/cm²/s = 90 µg/cm²/h",
        "ลืมคูณ partition coefficient (K = 0.5)",
      ],
      k: "Jss = D·K·Cd / h — แปลง µm → cm และ s → h ให้ถูก; flux ∝ thermodynamic activity",
      d: "hard",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Transdermal drug delivery; Martin's Physical Pharmacy 7th ed., Ch. Diffusion",
      c: [
        "h = 20 µm = 0.002 cm; Cd = 10 mg/cm³",
        "Jss = (1×10⁻⁸ cm²/s × 0.5 × 10 mg/cm³) / 0.002 cm = 2.5×10⁻⁵ mg/cm²/s",
        "× 3600 s/h = 0.09 mg/cm²/h = 90 µg/cm²/h",
      ],
    },
    {
      t: "MMAD and regional lung deposition",
      p: "ผลิตภัณฑ์ยาสูดพ่นตัวหนึ่งต้องการให้ยาเข้าถึงหลอดลมส่วนปลายและถุงลม (lower airways) ได้มากที่สุด ควรออกแบบให้อนุภาคมี mass median aerodynamic diameter (MMAD) อยู่ในช่วงใด",
      o: [
        "ประมาณ 1–5 µm",
        "ประมาณ 10–20 µm",
        "ประมาณ 5–10 µm",
        "น้อยกว่า 0.1 µm",
        "มากกว่า 30 µm",
      ],
      a: 0,
      r: "การตกค้างของอนุภาคในทางเดินหายใจขึ้นกับ aerodynamic diameter เป็นหลัก อนุภาค > 10 µm ตกที่ oropharynx ด้วย inertial impaction; 5–10 µm ตกที่ทางเดินหายใจส่วนบน/หลอดลมใหญ่; 1–5 µm (fine particles) เข้าถึงหลอดลมส่วนปลายและถุงลมด้วย sedimentation; อนุภาคเล็กมาก (< 0.5–1 µm) จำนวนมากถูกหายใจออกเพราะไม่ตกค้าง แม้อนุภาคระดับ nanometer จะตกค้างด้วย diffusion ได้บ้าง\n\nดังนั้นตำรับยาสูดส่วนใหญ่ออกแบบให้ MMAD อยู่ราว 1–5 µm และวัดด้วย cascade impactor",
      w: [
        "ถูก — ช่วง 1–5 µm คือ respirable fraction ที่เข้าถึงทางเดินหายใจส่วนล่างได้ดี",
        "อนุภาคขนาดนี้ตกที่คอและปากด้วย impaction เป็นส่วนใหญ่",
        "ตกที่ทางเดินหายใจส่วนต้นและหลอดลมใหญ่ ไม่ถึงถุงลม",
        "อนุภาคเล็กมากส่วนหนึ่งตกด้วย diffusion แต่จำนวนมากถูกหายใจออกและบรรจุมวลยาได้น้อย",
        "ใหญ่เกินไป ติดที่ปากและลำคอเกือบทั้งหมด",
      ],
      k: "> 10 µm ปาก/คอ | 5–10 µm ทางเดินหายใจส่วนบน | 1–5 µm ลึกถึงหลอดลมเล็ก/ถุงลม | < 1 µm หายใจออก",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Pulmonary drug delivery; USP <601>",
    },
    {
      t: "PLGA composition and degradation rate",
      p: "ทีมพัฒนาไมโครสเฟียร์ PLGA สำหรับ peptide ต้องการให้ polymer ย่อยสลายและปลดปล่อยยาหมดเร็วที่สุด (ประมาณ 1 เดือน) ควรเลือก PLGA แบบใด",
      o: [
        "PLGA 50:50 (lactide:glycolide) น้ำหนักโมเลกุลต่ำ ปลายสายเป็น free carboxylic acid",
        "PLGA 85:15 น้ำหนักโมเลกุลสูง ปลายสายเป็น ester (end-capped)",
        "PLA (100% lactide) น้ำหนักโมเลกุลสูง",
        "PLGA 75:25 น้ำหนักโมเลกุลสูง ปลายสายเป็น ester (end-capped)",
        "PLGA 50:50 น้ำหนักโมเลกุลสูง ปลายสายเป็น ester (end-capped)",
      ],
      a: 0,
      r: "PLGA ย่อยสลายด้วย hydrolysis ของ ester bond แบบ bulk erosion อัตราการย่อยสลายขึ้นกับ (1) สัดส่วน lactide:glycolide — lactide มีหมู่ methyl ที่ hydrophobic กว่า สัดส่วน lactide สูงจะดูดน้ำน้อยและย่อยช้า โดย 50:50 ย่อยเร็วที่สุดเพราะเป็น amorphous และ hydrophilic พอสมควร (2) น้ำหนักโมเลกุล — ต่ำย่อยเร็วกว่า (3) ปลายสาย — acid-terminated ดูดน้ำได้ดีกว่าและกรดที่ปลายเร่ง autocatalysis จึงย่อยเร็วกว่า ester end-capped\n\nผลิตภัณฑ์ระยะ 1 เดือนจึงมักใช้ PLGA 50:50 MW ต่ำ ส่วนระยะ 3–6 เดือนใช้ 75:25 หรือ 85:15 หรือ PLA",
      w: [
        "ถูก — 50:50, MW ต่ำ และ acid end group ล้วนเร่ง hydrolysis จึงย่อยสลายเร็วที่สุด",
        "lactide สูง MW สูงและ end-capped ทำให้ย่อยช้าเหมาะกับระยะหลายเดือน",
        "PLA hydrophobic และอาจมีความเป็นผลึก (L-PLA) ย่อยสลายช้ามาก",
        "75:25 MW สูงย่อยช้ากว่า 50:50 อย่างชัดเจน",
        "แม้เป็น 50:50 แต่ MW สูงและ end-capped จึงช้ากว่าตัวเลือกที่ถูก",
      ],
      k: "PLGA ย่อยเร็ว: 50:50 > 75:25 > 85:15 > PLA; MW ต่ำ และ acid-terminated เร็วกว่า",
      d: "medium",
      ref: "Makadia HK, Siegel SJ. Polymers 2011;3:1377–1397; Aulton's Pharmaceutics 6th ed.",
    },
    {
      t: "Push-pull osmotic pump design",
      p: "ต้องการพัฒนายาเม็ด osmotic ปลดปล่อยแบบ zero-order สำหรับยาที่ละลายน้ำได้น้อยมาก (เช่น nifedipine) การออกแบบแบบใดเหมาะสมที่สุด",
      o: [
        "Push-pull osmotic pump: เม็ด 2 ชั้น (drug layer + push layer ที่มี polyethylene oxide และ osmotic agent) เคลือบ semipermeable membrane และเจาะรูด้าน drug layer",
        "Elementary osmotic pump แกนยาชั้นเดียว อาศัยยาเป็น osmotic agent เอง",
        "Hydrophilic matrix HPMC ไม่มีฟิล์มเคลือบ",
        "เคลือบด้วย Eudragit L100-55 ให้ละลายใน duodenum",
        "เม็ดแกนยาเคลือบ semipermeable membrane โดยไม่เจาะรู",
      ],
      a: 0,
      r: "Elementary osmotic pump (EOP) อาศัยการที่ยาละลายเป็นสารละลายอิ่มตัวในแกนเพื่อสร้าง osmotic pressure จึงเหมาะกับยาที่ละลายน้ำได้ปานกลางถึงดี ยาที่ละลายน้ำน้อยมากจะสร้างแรงดันได้ไม่พอและออกทางรูได้น้อย\n\nPush-pull osmotic pump (เช่น nifedipine GITS) แก้ปัญหานี้: น้ำซึมผ่าน cellulose acetate membrane เข้าสู่ทั้งสองชั้น ชั้นยาจะกลายเป็น suspension ที่ไหลได้ ส่วน push layer ที่มี polyethylene oxide MW สูงและ NaCl จะพองตัวดันยาออกทางรูด้านชั้นยาด้วยอัตราคงที่ จึงได้ zero-order ที่ไม่ขึ้นกับ pH และการบีบตัวของทางเดินอาหาร",
      w: [
        "ถูก — push layer ที่พองตัวดัน drug suspension ออกทาง orifice ทำให้ยาละลายน้ำน้อยปลดปล่อยแบบ zero-order ได้",
        "EOP ต้องการยาที่ละลายน้ำได้พอสร้าง osmotic pressure ยาละลายน้ำน้อยมากจึงปลดปล่อยไม่สมบูรณ์",
        "HPMC matrix มักให้การปลดปล่อยแบบ diffusion/erosion ที่ไม่เป็น zero-order อย่างแท้จริงและไวต่อสภาวะทางเดินอาหารมากกว่า",
        "Enteric coating เป็น delayed-release ไม่ได้ทำให้ปลดปล่อยแบบ zero-order",
        "ไม่มี orifice ยาจะออกไม่ได้ หรือเมมเบรนแตกจากแรงดันแบบควบคุมไม่ได้",
      ],
      k: "ยาละลายน้ำน้อย → push-pull (2 ชั้น, PEO push layer); ยาละลายดี → EOP ได้",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed.; Theeuwes F. J Pharm Sci 1975;64:1987; Swanson DR et al. Am J Med 1987;83(6B):3–9",
    },
    {
      t: "Alcohol-induced dose dumping",
      p: "ยาแคปซูล opioid ชนิด extended-release รายหนึ่งถูกถอนออกจากตลาดหลังพบว่าเมื่อรับประทานร่วมกับเครื่องดื่มแอลกอฮอล์ ระดับยาสูงสุดในเลือดเพิ่มขึ้นหลายเท่า สาเหตุทางเภสัชกรรมที่สำคัญที่สุดคือข้อใด",
      o: [
        "Polymer หรือส่วนประกอบที่ควบคุมการปลดปล่อยละลายหรือเสียสภาพใน ethanol ทำให้ยาที่ตั้งใจปลดปล่อยใน 24 ชั่วโมงหลุดออกมาเกือบทั้งหมดในเวลาสั้น (dose dumping)",
        "Ethanol ยับยั้ง CYP3A4 อย่างแรง ทำให้ clearance ของยาลดลง",
        "Ethanol เพิ่ม gastric pH ทำให้ enteric coating ละลายก่อนเวลา",
        "Ethanol ทำให้กระเพาะอาหารบีบตัวช้า ยาจึงอยู่ในกระเพาะนานขึ้น",
        "Ethanol ทำให้ยาตกผลึกภายในแคปซูลและดูดซึมช้าลง",
      ],
      a: 0,
      r: "กรณีศึกษาสำคัญคือ hydromorphone ER capsule (Palladone) ซึ่งถูกระงับการจำหน่ายในปี 2005 เพราะ ethanol ทำให้กลไกควบคุมการปลดปล่อยล้มเหลว ยาจึงถูกปลดปล่อยออกมาเกือบหมดในคราวเดียว (dose dumping) ซึ่งอันตรายมากกับยาที่มีดัชนีการรักษาแคบและบรรจุปริมาณยามากสำหรับทั้งวัน\n\nPolymer หลายชนิดที่ใช้ใน ER เช่น ethylcellulose และ ammonio methacrylate copolymer ละลายได้ใน ethanol ความเข้มข้นสูง ผู้พัฒนาจึงต้องประเมินความทนทานต่อ ethanol ในหลอดทดลอง (เช่น 5–40% ethanol) และเลือกระบบที่ทน เช่น matrix ที่ใช้ polymer ที่ไม่ละลายใน ethanol ร่วมกับการให้คำแนะนำผู้ป่วยหลีกเลี่ยงแอลกอฮอล์",
      w: [
        "ถูก — dose dumping เกิดจาก ethanol ทำลายกลไกควบคุมการปลดปล่อยของตำรับ ไม่ใช่ PK interaction",
        "ethanol แบบ acute ไม่ได้เป็น strong CYP3A4 inhibitor และไม่ได้อธิบาย Cmax ที่เพิ่มเป็นหลายเท่าอย่างรวดเร็ว",
        "ethanol ไม่ได้เพิ่ม gastric pH อย่างมีนัยสำคัญ และตำรับนี้ไม่ใช่ enteric product",
        "การชะลอ gastric emptying จะทำให้ Cmax ลดลงหรือช้าลง ไม่ใช่เพิ่มขึ้นหลายเท่า",
        "การตกผลึกจะลดการดูดซึม ซึ่งตรงข้ามกับเหตุการณ์ที่เกิดขึ้น",
      ],
      k: "ER ที่บรรจุยาปริมาณมาก ต้องทดสอบ alcohol dose dumping (in vitro ใน ethanol 5–40%) — บทเรียนจาก Palladone",
      d: "hard",
      ref: "US FDA Alert: Palladone (hydromorphone) ER capsules, July 2005; Meyer RJ, Hussain AS. AAPS J 2005",
    },
    {
      t: "SEDDS composition and self-emulsification",
      p: "บริษัทต้องการเพิ่มชีวประสิทธิผลของยาที่มี log P = 5 และละลายน้ำได้น้อยมาก โดยพัฒนาเป็น self-emulsifying drug delivery system (SEDDS) บรรจุใน soft gelatin capsule ข้อใดอธิบายระบบนี้ได้ถูกต้องที่สุด",
      o: [
        "เป็นของผสมเนื้อเดียวที่ไม่มีน้ำของ oil, surfactant และ co-solvent ซึ่งเมื่อพบของเหลวในทางเดินอาหารและการบีบตัวเบาๆ จะเกิด emulsion ละเอียดได้เองโดยยายังอยู่ในสภาพละลาย",
        "เป็น o/w emulsion ที่เตรียมสำเร็จแล้วด้วย high-pressure homogenizer ก่อนบรรจุแคปซูล",
        "เป็นอนุภาคไขมันของแข็งที่ยาฝังอยู่ในผลึกไขมัน ปลดปล่อยด้วยการกร่อน",
        "เป็นผงยาผสม polymer ในสภาพอสัณฐานที่เตรียมด้วยการหลอม",
        "เป็นสารละลายยาในน้ำที่ใช้ cyclodextrin เป็นตัวช่วยละลาย",
      ],
      a: 0,
      r: "SEDDS คือ isotropic mixture ของน้ำมัน (เช่น medium-chain triglyceride) surfactant ที่มี HLB สูง (เช่น polysorbate 80, polyoxyl 35 castor oil) และ co-solvent (เช่น ethanol, PEG, propylene glycol) โดยไม่มีน้ำ ยาละลายอยู่ใน preconcentrate เมื่อสัมผัสของเหลวในทางเดินอาหารพร้อมการบีบตัวเพียงเล็กน้อยจะเกิด emulsion ละเอียดเอง ช่วยหลีกเลี่ยงขั้นตอน dissolution ที่เป็น rate-limiting step ของยา BCS class II\n\nนอกจากนี้ lipid ยังกระตุ้นการหลั่งน้ำดี เกิด mixed micelle และอาจส่งเสริม lymphatic transport สำหรับยาที่ lipophilic มาก ตัวอย่างผลิตภัณฑ์ได้แก่ cyclosporine microemulsion preconcentrate",
      w: [
        "ถูก — SEDDS เป็น anhydrous preconcentrate ที่ emulsify ได้เองในร่างกาย โดยยายังอยู่ในรูปละลาย",
        "SEDDS ไม่ได้ทำ emulsion ไว้ก่อน และการมีน้ำปริมาณมากไม่เข้ากับ soft gelatin capsule",
        "เป็นคำอธิบายของ solid lipid nanoparticle (SLN) ไม่ใช่ SEDDS",
        "เป็นคำอธิบายของ amorphous solid dispersion โดย hot-melt extrusion",
        "เป็นแนวทางเพิ่มการละลายด้วย inclusion complex ไม่ใช่ lipid-based self-emulsifying system",
      ],
      k: "SEDDS = oil + surfactant (HLB สูง) + co-solvent, ไม่มีน้ำ, emulsify เองในทางเดินอาหาร → ข้าม dissolution step",
      d: "medium",
      ref: "Pouton CW. Eur J Pharm Sci 2006;29:278–287; Aulton's Pharmaceutics 6th ed.",
    },
  ],
  // Mock Set 2 — ชุดที่ 2
  [
    {
      t: "Inert matrix ghost in stool",
      p: "ผู้ป่วยรายหนึ่งแจ้งเภสัชกรว่าพบเม็ดยาลักษณะคล้ายเม็ดเดิมในอุจจาระหลังรับประทานยาเม็ด extended-release ซึ่งผลิตเป็น insoluble (inert) matrix จาก ethylcellulose เภสัชกรควรอธิบายอย่างไรเหมาะสมที่สุด",
      o: [
        "เป็นโครงร่าง (ghost matrix) ที่ไม่ละลายน้ำ ยาถูกแพร่ออกผ่านช่องว่างและรูพรุนแล้ว จึงเป็นเรื่องปกติของตำรับชนิดนี้",
        "ยาไม่ถูกปลดปล่อยเลย ต้องหยุดยาและเปลี่ยนเป็นยาฉีดทันที",
        "แสดงว่าเกิด dose dumping ยาถูกปลดปล่อยหมดในกระเพาะอาหาร",
        "เป็นชั้น gel ของ HPMC ที่ยังไม่ถูกกร่อน แสดงว่าผู้ป่วยดื่มน้ำน้อยเกินไป",
        "เกิดจากผู้ป่วยเคี้ยวเม็ดยาก่อนกลืน",
      ],
      a: 0,
      r: "Inert matrix ใช้ polymer ที่ไม่ละลายน้ำ เช่น ethylcellulose, ammonio methacrylate copolymer หรือ polyvinyl acetate เป็นโครงร่าง ของเหลวซึมเข้าไปละลายยา แล้วยาแพร่ออกผ่าน pore และ channel ที่เกิดจากการละลายของยาและสารเติมแต่งที่ละลายน้ำ การปลดปล่อยมักเป็นไปตาม Higuchi model ที่มีพารามิเตอร์ porosity (ε) และ tortuosity (τ)\n\nเมื่อยาออกหมดแล้ว โครงร่างที่ว่างเปล่ายังคงรูปและถูกขับออกทางอุจจาระ (ghost tablet) ซึ่งไม่ใช่ความล้มเหลวของการรักษา แต่ถ้าผู้ป่วยมีอาการไม่ตอบสนองต่อยาหรือมีภาวะ GI transit เร็วผิดปกติ (เช่น ท้องเสียรุนแรง) ควรประเมินเพิ่มเติม",
      w: [
        "ถูก — insoluble matrix คงรูปหลังยาแพร่ออกหมด จึงพบ ghost matrix ในอุจจาระได้ตามปกติ",
        "การพบโครงร่างไม่ได้หมายความว่ายาไม่ถูกปลดปล่อย จึงไม่ต้องหยุดยา",
        "dose dumping คือการปลดปล่อยยาเร็วผิดปกติ ไม่เกี่ยวกับการพบโครงร่างในอุจจาระ",
        "ตำรับนี้เป็น ethylcellulose matrix ไม่ใช่ HPMC ซึ่งปกติจะกร่อนหมดไม่เหลือรูป",
        "การเคี้ยวจะทำลายโครงร่างและเสี่ยง dose dumping ไม่ทำให้พบเม็ดคงรูป",
      ],
      k: "Insoluble matrix (EC, Eudragit RS, PVAc) → ยาแพร่ผ่าน pore (Higuchi) → ghost matrix ในอุจจาระเป็นเรื่องปกติ",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Modified-release oral drug delivery",
    },
    {
      t: "Zero-order time to fractional release",
      p: "ยาเม็ด extended-release บรรจุตัวยา 200 mg ปลดปล่อยแบบ zero-order ด้วยอัตรา 8 mg/h ตั้งแต่เวลาศูนย์ (ไม่มี lag time) ต้องใช้เวลาเท่าใดจึงปลดปล่อยยาได้ 80% ของปริมาณที่ระบุบนฉลาก",
      o: ["10 h", "12.5 h", "20 h", "25 h", "40 h"],
      a: 2,
      r: "Zero-order release หมายถึงปริมาณยาที่ถูกปลดปล่อยเพิ่มขึ้นเป็นเส้นตรงกับเวลา Q = k0·t โดยอัตราไม่ขึ้นกับปริมาณยาที่เหลือ\n\n80% ของ 200 mg = 160 mg ดังนั้น t = 160/8 = 20 ชั่วโมง ส่วน 25 ชั่วโมงคือเวลาที่ปลดปล่อยครบ 100% ระบบที่ให้ zero-order ได้ใกล้เคียง ได้แก่ osmotic pump และ reservoir system ที่มี excess solid drug อยู่ภายใน",
      w: [
        "เป็นเวลาที่ปลดปล่อยได้ 40% (80 mg)",
        "ไม่สอดคล้องกับสมการ Q = k0·t (เท่ากับ 100/8)",
        "ถูก — 0.80 × 200 = 160 mg; 160/8 = 20 h",
        "เป็นเวลาที่ปลดปล่อยหมด 100% (200/8)",
        "เกิดจากการคำนวณกลับด้านหรือคิดว่าอัตราลดลงครึ่งหนึ่ง",
      ],
      k: "Zero-order: Q = k0·t → t = Q/k0",
      d: "easy",
      ref: "Aulton's Pharmaceutics 6th ed.; Shargel & Yu, Applied Biopharmaceutics & Pharmacokinetics 7th ed.",
      c: ["ปริมาณที่ต้องปลดปล่อย = 0.80 × 200 = 160 mg", "t = Q / k0 = 160 / 8 = 20 h"],
    },
    {
      t: "Reservoir coat thickness and release rate",
      p: "Pellet ชนิด reservoir เคลือบ ethylcellulose หนา 20 µm ปลดปล่อยยาแบบ zero-order ที่อัตรา 10 mg/h (มี excess solid drug ในแกน) หากเพิ่มความหนาของฟิล์มเป็น 30 µm โดยองค์ประกอบฟิล์มและพื้นที่ผิวเท่าเดิม อัตราการปลดปล่อยจะเป็นประมาณเท่าใด",
      o: ["3.3 mg/h", "4.4 mg/h", "6.7 mg/h", "10 mg/h", "15 mg/h"],
      a: 2,
      r: "สำหรับ reservoir (membrane-controlled) system อัตราการปลดปล่อยตาม Fick's first law คือ dM/dt = A·D·K·Cs / h เมื่อแกนมีตัวยาเป็นของแข็งเหลืออยู่ ความเข้มข้นภายในคงที่เท่ากับ Cs จึงได้ zero-order\n\nอัตราแปรผกผันกับความหนา h: 10 × (20/30) = 6.7 mg/h นอกจากนี้ฟิล์มที่หนาขึ้นยังทำให้ lag time ยาวขึ้นด้วย ในทางปฏิบัติผู้พัฒนาจึงปรับ release rate ด้วยการปรับ coating level หรือสัดส่วน pore former (เช่น HPMC) ในฟิล์ม",
      w: [
        "เป็นการหารด้วย 3 ไม่สอดคล้องกับความสัมพันธ์ 1/h",
        "คิดว่าอัตราแปรผกผันกับกำลังสองของความหนา ซึ่งไม่ถูกต้อง",
        "ถูก — dM/dt ∝ 1/h: 10 × 20/30 = 6.7 mg/h",
        "ความหนาเปลี่ยนแล้วอัตราต้องเปลี่ยน",
        "คิดว่าอัตราแปรผันตรงกับความหนา ซึ่งกลับด้าน",
      ],
      k: "Reservoir: dM/dt = A·D·K·Cs/h → อัตรา ∝ 1/ความหนาฟิล์ม; ฟิล์มหนาขึ้นยังเพิ่ม lag time",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed.; Martin's Physical Pharmacy 7th ed., Ch. Diffusion",
      c: ["dM/dt ∝ 1/h", "อัตราใหม่ = 10 × (20/30) = 6.67 ≈ 6.7 mg/h"],
    },
    {
      t: "Floating gastroretentive system",
      p: "ยาเม็ด floating gastroretentive ที่ประกอบด้วย HPMC, sodium bicarbonate และ citric acid ทำงานโดยหลักการใด",
      o: [
        "เกิดก๊าซ CO₂ ติดอยู่ใน gel ของ HPMC ทำให้ความหนาแน่นของเม็ดต่ำกว่าของเหลวในกระเพาะ จึงลอยและอยู่ในกระเพาะได้นาน",
        "เม็ดยามีความหนาแน่นสูงกว่า 2.5 g/cm³ จึงจมอยู่ที่ก้นกระเพาะ",
        "polymer ยึดเกาะกับเยื่อบุลำไส้เล็กส่วนต้นด้วยประจุบวก",
        "เม็ดยาพองตัวจนใหญ่กว่า pylorus ด้วย superporous hydrogel โดยไม่มีก๊าซ",
        "กรดซิตริกทำให้ pH กระเพาะสูงขึ้นจนยาเปลี่ยนเป็นรูปไม่แตกตัว",
      ],
      a: 0,
      r: "Floating drug delivery system (เช่น hydrodynamically balanced system และ effervescent system) ต้องมีความหนาแน่นต่ำกว่าน้ำย่อย (ประมาณ 1.004 g/cm³) เมื่อ HPMC เกิด gel ขณะที่ bicarbonate ทำปฏิกิริยากับกรด (กรดในกระเพาะหรือ citric acid ในตำรับ) จะเกิด CO₂ ถูกกักใน gel ทำให้เม็ดลอยตัวและปลดปล่อยยาอย่างช้าๆ ในกระเพาะ\n\nเหมาะกับยาที่มี absorption window แคบในทางเดินอาหารส่วนต้น ยาที่ออกฤทธิ์เฉพาะที่ในกระเพาะ หรือยาที่ไม่คงตัวใน pH ด่างของลำไส้ ระบบนี้ทำงานได้ดีเมื่อกระเพาะมีอาหารและของเหลวเพียงพอ จึงมักแนะนำให้รับประทานพร้อมอาหาร",
      w: [
        "ถูก — CO₂ ที่ติดอยู่ใน gel matrix ลดความหนาแน่นทำให้ลอยตัว",
        "เป็นหลักการของ high-density system ซึ่งไม่ใช้ bicarbonate",
        "เป็นหลักการ mucoadhesion ไม่ใช่ floating และตำแหน่งที่กล่าวถึงไม่ใช่กระเพาะ",
        "เป็นหลักการของ swelling/expandable system ที่ไม่ต้องอาศัยก๊าซ",
        "citric acid ในตำรับมีไว้ทำปฏิกิริยากับ bicarbonate ไม่ได้เปลี่ยน pH กระเพาะเพื่อปรับการแตกตัวของยา",
      ],
      k: "Floating GRDDS: density < 1.004 g/cm³, NaHCO₃ + กรด → CO₂ ติดใน gel; ได้ผลดีเมื่อรับประทานพร้อมอาหาร",
      d: "easy",
      ref: "Aulton's Pharmaceutics 6th ed.; Streubel A, Siepmann J, Bodmeier R. Curr Opin Pharmacol 2006;6:501–508",
    },
    {
      t: "Ideal drug properties for transdermal delivery",
      p: "ทีม R&D กำลังคัดเลือกตัวยาเพื่อพัฒนาเป็น passive transdermal patch ตัวยาที่มีคุณสมบัติใดเหมาะสมที่สุด",
      o: [
        "MW ประมาณ 300 Da, log P ประมาณ 2, จุดหลอมเหลวต่ำ และขนาดยาที่ต้องการต่อวันไม่กี่มิลลิกรัม",
        "MW ประมาณ 1,200 Da, log P ประมาณ −1 และขนาดยาต่อวัน 500 mg",
        "MW ประมาณ 250 Da, log P ประมาณ 6, ไม่ละลายน้ำ และขนาดยาต่อวัน 100 mg",
        "Peptide MW ประมาณ 5,000 Da ที่มีประจุสูงที่ pH ผิวหนัง",
        "MW ประมาณ 400 Da, ระคายเคืองผิวหนังรุนแรง และ log P ประมาณ 2",
      ],
      a: 0,
      r: "Stratum corneum เป็น barrier หลักที่มี lipid เรียงตัวแน่น ยาที่ซึมผ่านได้ดีควรมีน้ำหนักโมเลกุลต่ำ (โดยทั่วไป < 500 Da) มีความชอบไขมันพอเหมาะ (log P ประมาณ 1–3) เพื่อแบ่งเข้าสู่ lipid และออกสู่ชั้น viable epidermis ที่เป็นน้ำได้ มีจุดหลอมเหลวต่ำ (ละลายดีกว่า) และต้องมีความแรงสูงเพราะ flux ที่ได้ต่อพื้นที่ patch จำกัด ขนาดยาต่อวันจึงควรอยู่ในระดับไม่เกินประมาณ 10–20 mg\n\nนอกจากนี้ยาต้องไม่ระคายเคืองหรือก่อภูมิแพ้ต่อผิวหนัง ตัวอย่างยาที่สำเร็จ เช่น fentanyl, nicotine, estradiol, scopolamine, rivastigmine",
      w: [
        "ถูก — โมเลกุลเล็ก lipophilicity พอเหมาะ จุดหลอมเหลวต่ำ และขนาดยาต่ำ เป็นลักษณะของยาที่เหมาะกับ transdermal",
        "โมเลกุลใหญ่และ hydrophilic เกินไป ซึมผ่าน stratum corneum ได้น้อย และขนาดยาสูงเกิน",
        "log P สูงมากทำให้ยาค้างใน stratum corneum ไม่แบ่งออกสู่ชั้นน้ำ และขนาดยาสูงเกินไป",
        "peptide ขนาดใหญ่และมีประจุแทบไม่ซึมผ่านแบบ passive ต้องใช้วิธีทางกายภาพเช่น microneedle หรือ iontophoresis",
        "แม้ MW และ log P เหมาะสม แต่การระคายเคืองรุนแรงทำให้ใช้ patch ต่อเนื่องหลายวันไม่ได้",
      ],
      k: "Transdermal ideal: MW < 500, log P 1–3, mp ต่ำ, dose ≤ 10–20 mg/วัน, ไม่ระคายเคือง",
      d: "medium",
      ref: "Prausnitz MR, Langer R. Nat Biotechnol 2008;26:1261–1268; Aulton's Pharmaceutics 6th ed.",
    },
    {
      t: "Lactose fines in DPI carrier blends",
      p: "ตำรับ dry powder inhaler (DPI) แบบ carrier-based ใช้ micronized drug (1–5 µm) ผสมกับ coarse α-lactose monohydrate (ประมาณ 50–100 µm) พบว่า fine particle fraction ต่ำ ทีมพัฒนาเติม fine lactose (< 10 µm) จำนวนเล็กน้อยแล้ว FPF ดีขึ้น เหตุผลที่สำคัญที่สุดคือข้อใด",
      o: [
        "Fine lactose เข้าไปครอบครอง active (high-energy) sites บนผิว carrier ทำให้ยาเกาะกับ carrier หลวมลงและหลุดออกได้ง่ายขณะสูดพ่น",
        "Fine lactose เพิ่มความหนาแน่นของยาจนอนุภาคยาตกที่ปอดได้ดีขึ้น",
        "Fine lactose ละลายในทางเดินหายใจทำให้ยาละลายเร็วขึ้น",
        "Fine lactose ทำให้ผงยาดูดความชื้นมากขึ้นจึงเกาะกันน้อยลง",
        "Fine lactose ทำให้ carrier มีขนาดใหญ่ขึ้นจึงตกที่ลำคอน้อยลง",
      ],
      a: 0,
      r: "ใน DPI แบบ carrier ยาที่ micronized มี cohesive force สูงไหลไม่ดี จึงผสมกับ coarse lactose เพื่อช่วยการไหลและการแบ่งขนาดยา ขณะผู้ป่วยสูดพ่น แรง turbulence และการชนในอุปกรณ์ต้องเอาชนะแรงยึดเกาะระหว่างยากับ carrier เพื่อให้อนุภาคยาเดี่ยวเข้าสู่ปอด ส่วน carrier ขนาดใหญ่ตกที่ลำคอ\n\nผิว lactose มีบริเวณที่มีพลังงานสูง (ร่อง รอยแตก amorphous region) ซึ่งยึดยาไว้แน่น การเติม fine lactose ช่วยปิดตำแหน่งเหล่านี้ (active site hypothesis) และอาจเกิด agglomerate ของยากับ fines ที่แตกตัวง่าย ทำให้ FPF เพิ่มขึ้น",
      w: [
        "ถูก — เป็นกลไกตาม active site hypothesis ซึ่งอธิบายการเพิ่ม FPF เมื่อเติม ternary fines",
        "การตกที่ปอดขึ้นกับ aerodynamic diameter ของอนุภาคยาที่หลุดจาก carrier ไม่ใช่การเพิ่มความหนาแน่น",
        "lactose ไม่ได้เพิ่มการละลายของยาและ FPF วัดก่อนการละลาย",
        "ความชื้นที่มากขึ้นเพิ่ม capillary force ทำให้เกาะกันมากขึ้น ไม่ใช่น้อยลง",
        "fine lactose ไม่ได้ทำให้ carrier ใหญ่ขึ้น และ carrier ตั้งใจให้ตกที่ลำคออยู่แล้ว",
      ],
      k: "DPI carrier: coarse lactose ช่วยไหล/แบ่งขนาด; เติม fines ครอบครอง active sites → ยาหลุดง่าย → FPF ↑",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Pulmonary drug delivery; Jones MD, Price R. Pharm Res 2006;23:1665–1674",
    },
    {
      t: "SLN versus NLC drug loading",
      p: "Solid lipid nanoparticles (SLN) ที่ใช้ glyceryl tristearate บริสุทธิ์ พบว่าบรรจุยาได้น้อย และยาถูกขับออกจากอนุภาคระหว่างเก็บรักษา ทีมพัฒนาจึงเปลี่ยนเป็น nanostructured lipid carriers (NLC) การเปลี่ยนแปลงนี้แก้ปัญหาด้วยหลักการใด",
      o: [
        "ผสม liquid lipid (oil) เข้ากับ solid lipid ทำให้โครงสร้างผลึกไม่สมบูรณ์ มีที่ว่างรองรับยามากขึ้น และลดการเปลี่ยน polymorph ที่ขับยาออก",
        "เปลี่ยนเป็น lipid ที่มีความบริสุทธิ์สูงขึ้นเพื่อให้ผลึกเรียงตัวสมบูรณ์",
        "เพิ่มชั้น phospholipid bilayer ล้อมรอบแกนน้ำภายใน",
        "ใช้ polymer PLGA แทน lipid ทั้งหมด",
        "เพิ่มอุณหภูมิเก็บรักษาเพื่อให้ lipid หลอมเหลวตลอดเวลา",
      ],
      a: 0,
      r: "SLN ใช้ lipid ของแข็งเพียงชนิดเดียวซึ่งระหว่างเก็บรักษามักเปลี่ยนจาก polymorph ที่ไม่เสถียร (α) ไปเป็น β ที่เรียงตัวแน่นและสมบูรณ์ ทำให้มีที่ว่างสำหรับโมเลกุลยาน้อยลงและยาถูกขับออก (drug expulsion) อีกทั้ง loading capacity ตั้งแต่ต้นต่ำ\n\nNLC เป็นรุ่นที่สองที่ผสม liquid lipid เช่น medium-chain triglyceride หรือ oleic acid เข้ากับ solid lipid เกิด imperfect หรือ amorphous matrix ที่ยังเป็นของแข็งที่อุณหภูมิร่างกาย จึงบรรจุยาได้มากขึ้นและกักเก็บยาได้ดีกว่าระหว่างเก็บรักษา",
      w: [
        "ถูก — liquid lipid ทำให้ matrix ไม่เป็นผลึกสมบูรณ์ เพิ่ม loading และลด drug expulsion",
        "lipid ที่บริสุทธิ์มากยิ่งตกผลึกสมบูรณ์ ทำให้ปัญหาแย่ลง",
        "เป็นโครงสร้างของ vesicular carrier ไม่ใช่ NLC ซึ่งเป็นอนุภาค lipid matrix ทึบ",
        "เป็นการเปลี่ยนไปใช้ polymeric nanoparticle ไม่ใช่ NLC",
        "NLC ต้องคงสภาพของแข็งที่อุณหภูมิห้องและร่างกาย การทำให้หลอมไม่ใช่หลักการ",
      ],
      k: "SLN: lipid แข็งล้วน → ผลึกสมบูรณ์ → loading ต่ำ/drug expulsion; NLC: solid + liquid lipid → imperfect matrix → loading ↑",
      d: "medium",
      ref: "Müller RH, Radtke M, Wissing SA. Adv Drug Deliv Rev 2002;54 Suppl 1:S131–S155",
    },
    {
      t: "Colon targeting strategy selection",
      p: "ยาเม็ด mesalamine สำหรับ ulcerative colitis ที่เคลือบด้วย polymer ซึ่งละลายที่ pH > 7 เพียงอย่างเดียว มีรายงานว่าผู้ป่วยบางรายพบเม็ดยาไม่แตกออกมากับอุจจาระ ข้อใดอธิบายสาเหตุและแนวทางปรับปรุงได้ดีที่สุด",
      o: [
        "pH สูงสุดของทางเดินอาหารอยู่ที่ ileum ส่วนปลาย แล้วลดลงที่ caecum/colon และผู้ป่วยบางรายอาจไม่ถึง pH 7 นานพอ จึงควรใช้ร่วมกับกลไกที่อาศัยแบคทีเรียในลำไส้ใหญ่ เช่น polysaccharide หรือ azo-bond",
        "pH ในลำไส้ใหญ่สูงกว่า 9 เสมอ ฟิล์มจึงละลายช้า ควรเปลี่ยนเป็น Eudragit E",
        "เม็ดยาไม่แตกเพราะแบคทีเรียในลำไส้ใหญ่ทำลาย polymer ควรเพิ่มความหนาฟิล์ม",
        "เกิดจากเอนไซม์ pepsin ย่อยฟิล์ม ควรเติม protease inhibitor",
        "ควรเปลี่ยนเป็น HPMC matrix ไม่เคลือบ เพื่อให้ยาปลดปล่อยในกระเพาะ",
      ],
      a: 0,
      r: "pH ของทางเดินอาหารเพิ่มจากประมาณ 6 ใน duodenum ถึงสูงสุดราว 7–7.5 ที่ terminal ileum แต่เมื่อเข้าสู่ caecum pH จะลดลงเหลือราว 6–6.5 จากกรดไขมันสายสั้นที่แบคทีเรียสร้าง และในผู้ป่วย IBD pH อาจต่ำกว่าเดิม ระยะเวลาที่ pH > 7 อาจสั้นหรือไม่เกิดเลย ฟิล์ม pH > 7 (เช่น Eudragit S100) จึงอาจไม่ละลาย\n\nแนวทางที่น่าเชื่อถือกว่าคือ microbially triggered system ซึ่งอาศัยเอนไซม์ของแบคทีเรียในลำไส้ใหญ่ เช่น prodrug ที่มี azo bond (sulfasalazine, balsalazide, olsalazine) หรือ polysaccharide coating (resistant starch, pectin, guar gum) และอาจผสมกับ pH-dependent polymer เพื่อให้มีกลไกสำรอง (dual trigger)",
      w: [
        "ถูก — pH ที่ลดลงที่ caecum และความแปรปรวนในผู้ป่วยทำให้ pH-trigger เพียงอย่างเดียวไม่น่าเชื่อถือ การเพิ่ม bacterial trigger ช่วยได้",
        "pH ลำไส้ใหญ่ไม่ได้สูงถึง 9 และ Eudragit E ละลายในกระเพาะ",
        "ถ้าแบคทีเรียทำลาย polymer เม็ดยาจะแตก ไม่ใช่คงรูป และการเพิ่มความหนาทำให้แย่ลง",
        "pepsin ทำงานในกระเพาะและไม่ย่อย methacrylate polymer",
        "การปลดปล่อยในกระเพาะทำให้ยาถูกดูดซึมก่อนถึงลำไส้ใหญ่ ซึ่งขัดกับเป้าหมาย",
      ],
      k: "Colon targeting: pH-dependent อย่างเดียวไม่แน่นอน (pH ลดที่ caecum) → ใช้ microbial trigger (azo, polysaccharide) หรือ dual trigger",
      d: "hard",
      ref: "Amidon S, Brown JE, Dave VS. AAPS PharmSciTech 2015;16:731–741; Aulton's Pharmaceutics 6th ed.",
    },
    {
      t: "Hot-melt extrusion processing temperature",
      p: "นักพัฒนาต้องการเตรียม amorphous solid dispersion ของยาที่สลายตัวเมื่ออุณหภูมิสูงกว่า 160 °C ด้วยกระบวนการ hot-melt extrusion (HME) แต่ polymer ที่เลือกต้องใช้อุณหภูมิ barrel ประมาณ 180 °C จึงจะมีความหนืดเหมาะสม แนวทางใดเหมาะสมที่สุด",
      o: [
        "เติม plasticizer หรือเลือก polymer ที่มี Tg ต่ำกว่า เพื่อลด Tg และ melt viscosity ให้ extrude ได้ที่อุณหภูมิต่ำลง หากยังทำไม่ได้ให้พิจารณา spray drying",
        "เพิ่มอุณหภูมิ barrel เป็น 200 °C เพื่อลดเวลาที่ยาอยู่ใน extruder",
        "ลด screw speed ลงมากๆ เพื่อเพิ่ม residence time ให้ผสมทั่วถึง",
        "เปลี่ยน polymer เป็นชนิดที่มี Tg สูงขึ้นเพื่อให้ ASD คงตัวกว่า",
        "บดยาให้ละเอียดระดับ nano ก่อน extrude เพื่อลดการสลายตัวจากความร้อน",
      ],
      a: 0,
      r: "HME ต้องให้ความร้อนจน polymer อ่อนตัวเหนือ Tg มาก (โดยทั่วไปหลายสิบองศาเหนือ Tg) เพื่อให้มี melt viscosity ที่ผสมกับยาและไหลผ่าน die ได้ ยาและ polymer ต้องทนความร้อนในช่วงเวลาที่อยู่ใน extruder\n\nเมื่อยาไวต่อความร้อน วิธีลดอุณหภูมิกระบวนการคือเติม plasticizer (เช่น PEG, triethyl citrate, surfactant บางชนิด) หรือเลือก polymer ที่มี Tg ต่ำกว่า (เช่น copovidone หรือ polyvinyl caprolactam–polyvinyl acetate–PEG graft copolymer) ซึ่งยาบางชนิดเองก็ทำหน้าที่ plasticizer ได้ ถ้ายังไม่สามารถลดอุณหภูมิได้เพียงพอ spray drying ที่อาศัยตัวทำละลายและใช้เวลาสัมผัสความร้อนสั้นมากเป็นทางเลือกที่ดีกว่า",
      w: [
        "ถูก — plasticizer หรือ polymer Tg ต่ำ ลดอุณหภูมิที่ต้องใช้ และ spray drying เป็นทางเลือกเมื่อยาทนความร้อนไม่ได้",
        "อุณหภูมิที่สูงขึ้นเพิ่มอัตราการสลายตัวของยา แม้เวลาสั้นลงก็ไม่คุ้ม",
        "residence time ที่นานขึ้นยิ่งเพิ่มการสัมผัสความร้อนและการสลายตัว",
        "Tg สูงขึ้นต้องใช้อุณหภูมิกระบวนการสูงขึ้น ซึ่งขัดกับปัญหา",
        "การลดขนาดอนุภาคไม่ได้ลดอุณหภูมิที่ polymer ต้องใช้ในการไหล",
      ],
      k: "HME: T กระบวนการ ~ เหนือ Tg ของ polymer; ยาไวความร้อน → plasticizer/polymer Tg ต่ำ หรือเปลี่ยนเป็น spray drying",
      d: "hard",
      ref: "Crowley MM et al. Drug Dev Ind Pharm 2007;33:909–926; Aulton's Pharmaceutics 6th ed.",
    },
    {
      t: "Long-acting injectable suspension particle size",
      p: "ผลิตภัณฑ์ long-acting injectable (LAI) แบบ aqueous suspension ของ antipsychotic prodrug ที่ละลายน้ำได้น้อยมาก ฉีดเข้ากล้ามเนื้อทุก 1 เดือน หลังเปลี่ยนกระบวนการบดพบว่าขนาดอนุภาคเฉลี่ยเล็กลงครึ่งหนึ่ง ผลที่คาดว่าจะเกิดกับ PK มากที่สุดคือข้อใด",
      o: [
        "อัตราการละลายที่ตำแหน่งฉีดเพิ่มขึ้น ทำให้ Cmax สูงขึ้นและระยะเวลาที่ระดับยาคงอยู่สั้นลง เพราะการละลายเป็นขั้นที่ควบคุมการดูดซึม",
        "ไม่มีผลใดๆ เพราะยาฉีดเข้ากล้ามเนื้อมี bioavailability 100% เสมอ",
        "Cmax ลดลงและระยะเวลาออกฤทธิ์ยาวขึ้นเพราะอนุภาคเล็กจับตัวกันเป็นก้อน",
        "clearance ของยาลดลงเพราะอนุภาคเล็กเข้าสู่ตับได้น้อย",
        "elimination half-life ที่แท้จริงของยาเพิ่มขึ้นเป็นสองเท่า",
      ],
      a: 0,
      r: "LAI suspension สร้าง depot ที่ตำแหน่งฉีด ยาต้องละลายก่อนจึงดูดซึมเข้าสู่กระแสเลือด และ (สำหรับ prodrug) ถูก hydrolyze เป็นยาออกฤทธิ์ เนื่องจากอัตราการละลายต่ำมาก ขั้นนี้จึงช้ากว่าการกำจัดยา เกิด flip-flop kinetics ที่ apparent half-life สะท้อนอัตราการปลดปล่อยจาก depot ไม่ใช่การกำจัด\n\nตามสมการ Noyes–Whitney อนุภาคเล็กลงมีพื้นที่ผิวมากขึ้น ละลายเร็วขึ้น จึงเพิ่ม Cmax และทำให้ระยะเวลาครอบคลุมสั้นลง ขนาดอนุภาคจึงเป็น critical quality attribute ที่ต้องควบคุมใน LAI suspension และการเปลี่ยนกระบวนการบดต้องประเมินผลกระทบอย่างรัดกุม",
      w: [
        "ถูก — อนุภาคเล็กลงละลายเร็วขึ้น depot หมดเร็วขึ้น Cmax ↑ ระยะเวลาครอบคลุม ↓",
        "แม้ปริมาณที่ดูดซึมทั้งหมดอาจใกล้เคียงเดิม แต่รูปแบบเวลาของระดับยาเปลี่ยนชัดเจน",
        "ไม่สอดคล้องกับ Noyes–Whitney; การจับตัวเป็นก้อนเป็นปัญหาความคงตัวที่ควบคุมด้วยตำรับ ไม่ใช่ผลที่คาดหวังหลัก",
        "clearance เป็นคุณสมบัติของร่างกายต่อยาที่อยู่ในกระแสเลือด ไม่ขึ้นกับขนาดอนุภาคใน depot",
        "true elimination half-life ไม่เปลี่ยน; apparent half-life จะสั้นลงเพราะ depot ปลดปล่อยเร็วขึ้น",
      ],
      k: "LAI suspension: dissolution ที่ depot เป็น rate-limiting (flip-flop) → particle size คือ CQA หลักที่กำหนดระยะเวลาออกฤทธิ์",
      d: "hard",
      ref: "Wright JC, Burgess DJ (eds). Long Acting Injections and Implants. Springer 2012",
    },
  ],
  // Mock Set 5
  [
    {
      t: "Starting material sampling with square-root-plus-one plan",
      p: "รับ excipient lot เดียวจากผู้ขายที่ผ่านการรับรองแล้ว จำนวน 50 ภาชนะ (homogeneous lot) ตามแผนการสุ่ม n = √N + 1 ที่ใช้ทั่วไปในแนวทาง WHO ต้องสุ่มตัวอย่างอย่างน้อยกี่ภาชนะ",
      o: ["5 ภาชนะ", "8 ภาชนะ", "9 ภาชนะ", "25 ภาชนะ", "50 ภาชนะ"],
      a: 2,
      r: "แผน '√N + 1' ใช้กับ starting materials ที่ถือว่า homogeneous จาก supplier ที่เชื่อถือได้ โดยปัดเศษขึ้นเป็นจำนวนเต็มถัดไป: √50 = 7.07 → 7.07 + 1 = 8.07 → ปัดขึ้นเป็น 9 ภาชนะ\n\nตัวอย่างจากภาชนะเหล่านี้อาจรวมเป็น composite sample สำหรับการทดสอบเต็ม specification ได้ ส่วน identity test ตาม GMP ยังคงต้องทำกับตัวอย่างจากทุกภาชนะ เว้นแต่มีขั้นตอน validated ที่ยกเว้นได้ แนวทาง WHO ยังมีแผน 'p' (0.4√N) และ 'r' (1.5√N) สำหรับวัตถุประสงค์อื่น",
      w: [
        "น้อยเกินไป ไม่เป็นไปตามสูตร √N + 1",
        "ลืมปัดเศษขึ้น: √50 + 1 = 8.07 ต้องปัดขึ้นเป็น 9",
        "ถูก — √50 + 1 = 8.07 ปัดขึ้นเป็น 9 ภาชนะ",
        "เป็นครึ่งหนึ่งของ N ไม่ใช่แผน √N + 1",
        "การสุ่มทุกภาชนะเป็นข้อกำหนดของ identity testing ไม่ใช่แผนการสุ่มเพื่อทดสอบเต็ม spec",
      ],
      k: "แผน n = √N + 1 (ปัดขึ้น) สำหรับ starting materials homogeneous; identity ยังต้องทุกภาชนะ",
      d: "easy",
      ref: "WHO TRS 929 Annex 4 (WHO guidelines for sampling of pharmaceutical products and related materials); PIC/S GMP Guide PE 009 Annex 8",
      c: ["√50 = 7.07", "n = 7.07 + 1 = 8.07", "ปัดขึ้น → 9 ภาชนะ"],
    },
    {
      t: "System suitability failure on replicate injection RSD",
      p: "ก่อนวิเคราะห์ตัวอย่าง assay ด้วย HPLC ฉีด standard solution ซ้ำ 5 ครั้งได้ %RSD ของ peak area = 2.6% (เกณฑ์ SST ≤ 2.0%) แต่ resolution และ tailing ผ่าน นักวิเคราะห์ควรทำอย่างไร",
      o: [
        "หยุดการวิเคราะห์ ไม่ใช้ผลตัวอย่างใดในการรายงาน ตรวจหาสาเหตุของระบบ (เช่น injector, ฟองอากาศ, การรั่ว) แก้ไขแล้วทำ SST ใหม่ให้ผ่านก่อน",
        "วิเคราะห์ตัวอย่างต่อได้เพราะ resolution และ tailing ผ่านแล้ว",
        "ตัด injection ที่มี area ต่างมากที่สุดออกแล้วคำนวณ %RSD ใหม่จาก 4 ค่า",
        "วิเคราะห์ตัวอย่างต่อ แล้วค่อยรายงานผลพร้อมหมายเหตุว่า SST ไม่ผ่าน",
        "เปลี่ยนเกณฑ์ SST เป็น ≤ 3.0% เพื่อให้ผ่านในครั้งนี้",
      ],
      a: 0,
      r: "System suitability test ยืนยันว่าระบบทั้งหมด (เครื่องมือ คอลัมน์ สารละลาย นักวิเคราะห์) ทำงานได้เหมาะสม ณ เวลาวิเคราะห์ ต้องผ่านทุกเกณฑ์ก่อนหรือระหว่างการวิเคราะห์ ถ้าไม่ผ่านข้อใดข้อหนึ่ง ผลตัวอย่างใน run นั้นใช้ไม่ได้\n\n%RSD ของ replicate injections สะท้อน injection precision; ค่าสูงมักเกิดจาก autosampler/injector ผิดปกติ ฟองอากาศใน syringe/pump การรั่ว หรือ peak integration ไม่สม่ำเสมอ ความล้มเหลวของ SST ไม่ใช่ OOS ของตัวอย่าง แต่ต้องบันทึก สืบหาสาเหตุ และแก้ไขตาม SOP การตัดค่าหรือเปลี่ยนเกณฑ์เพื่อให้ผ่านเป็นการละเมิด data integrity",
      w: [
        "ถูก — SST ไม่ผ่านข้อใดข้อหนึ่ง run นั้นใช้ไม่ได้ ต้องหาสาเหตุ แก้ไข และทำ SST ใหม่",
        "ต้องผ่านทุกเกณฑ์ของ SST ไม่ใช่เพียงบางข้อ",
        "การตัด injection โดยไม่มีเหตุผลที่บันทึกไว้ล่วงหน้าเป็นการเลือกข้อมูล (data manipulation)",
        "ผลจาก run ที่ SST ไม่ผ่านไม่สามารถใช้รายงานได้",
        "การเปลี่ยนเกณฑ์ที่ validate แล้วต้องผ่าน change control ไม่ใช่ปรับเพื่อให้ผ่านเฉพาะครั้ง",
      ],
      k: "SST ไม่ผ่านแม้ข้อเดียว → หยุด run, ผลตัวอย่างใช้ไม่ได้, หาสาเหตุ/แก้ไข แล้วทำ SST ใหม่",
      d: "easy",
      ref: "USP <621> Chromatography (System Suitability); USP <1058> Analytical Instrument Qualification",
    },
    {
      t: "LOQ from standard deviation of response and slope",
      p: "ในการ validate HPLC method สำหรับ impurity D ได้ calibration curve ช่วงความเข้มข้นต่ำ มี slope = 15,000 area/(µg/mL) และ residual standard deviation ของ regression = 450 area ค่า quantitation limit (QL) ตาม ICH Q2 คือเท่าใด",
      o: ["0.03 µg/mL", "0.10 µg/mL", "0.30 µg/mL", "3.0 µg/mL", "33 µg/mL"],
      a: 2,
      r: "ICH Q2 อนุญาตให้คำนวณ DL และ QL จาก standard deviation ของ response (σ) และ slope (S): DL = 3.3σ/S และ QL = 10σ/S โดย σ อาจได้จาก residual SD ของ regression line, SD ของ y-intercept หรือ SD ของ blank\n\nQL = 10 × 450 / 15,000 = 0.30 µg/mL (DL = 3.3 × 450/15,000 ≈ 0.10 µg/mL) ค่าที่คำนวณได้ต้องยืนยันโดยวิเคราะห์ตัวอย่างที่ความเข้มข้นระดับ QL จริงเพื่อแสดง precision/accuracy ที่ยอมรับได้ อีกวิธีคือใช้ signal-to-noise (DL ~3:1, QL ~10:1)",
      w: [
        "ค่าเป็น σ/S โดยไม่คูณ 10 (หรือผิดหลักทศนิยม)",
        "นี่คือ DL (3.3σ/S ≈ 0.099) ไม่ใช่ QL",
        "ถูก — QL = 10 × 450 / 15,000 = 0.30 µg/mL",
        "ผิดหลักทศนิยม 10 เท่า",
        "เป็นผลจากการกลับสูตร (S/σ) ซึ่งผิด",
      ],
      k: "DL = 3.3σ/S, QL = 10σ/S (หรือ S/N 3:1 และ 10:1); ต้องยืนยัน QL ด้วยการทดลองจริง",
      d: "medium",
      ref: "ICH Q2(R2) Validation of Analytical Procedures (Detection and Quantitation Limits)",
      c: ["QL = 10σ / S", "= 10 × 450 / 15,000", "= 0.30 µg/mL"],
    },
    {
      t: "Capsule assay by HPLC external standard",
      p: "Assay แคปซูล 250 mg (น้ำหนักบรรจุเฉลี่ย 0.5150 g): ชั่งผงยา 0.4120 g ละลายปรับปริมาตรเป็น 200 mL แล้วปิเปต 5.0 mL เจือจางเป็น 50 mL; standard solution เข้มข้น 0.1010 mg/mL (reference standard purity 99.6% as is) ได้ peak area ของ standard = 1,250,400 และ sample = 1,226,800 ปริมาณยาเป็นเท่าใดของ label claim",
      o: ["96.4%", "98.3%", "98.7%", "99.1%", "101.9%"],
      a: 2,
      r: "External standard: C sample = (A sample/A std) × C std × purity\n\n= (1,226,800/1,250,400) × 0.1010 × 0.996 = 0.98113 × 0.10060 = 0.09870 mg/mL คูณ dilution (50/5 = 10) และปริมาตร 200 mL → 197.4 mg ในผง 0.4120 g คิดต่อแคปซูล: 197.4 × 0.5150/0.4120 = 246.7 mg = 98.7% LC\n\nความผิดพลาดที่พบบ่อย: ลืม purity ของ standard (ได้ 99.1%), กลับอัตราส่วน area (ได้ 101.9%), และลืมแปลงน้ำหนักผงเป็นต่อแคปซูลด้วยน้ำหนักบรรจุเฉลี่ย",
      w: [
        "ค่าต่ำเกินจริง ไม่สอดคล้องกับการคำนวณ",
        "ค่าไม่ตรงกับการคำนวณที่ถูกต้อง",
        "ถูก — 0.98113 × 0.1010 × 0.996 × 10 × 200 × (0.5150/0.4120) = 246.7 mg = 98.7% LC",
        "เป็นผลจากการลืมแก้ purity 99.6% ของ reference standard",
        "เป็นผลจากการกลับอัตราส่วน A std/A sample",
      ],
      k: "%LC = (Aspl/Astd) × Cstd × P × DF × V × (avg fill wt/sample wt) / LC × 100 — อย่าลืม purity และ DF",
      d: "medium",
      ref: "USP <621> Chromatography; USP general notices 5.40 (Reference Standards) and typical USP capsule monograph assay calculation",
      c: [
        "Area ratio = 1,226,800 / 1,250,400 = 0.98113",
        "C sample = 0.98113 × 0.1010 × 0.996 = 0.09870 mg/mL",
        "ในผง: 0.09870 × (50/5) × 200 = 197.4 mg",
        "ต่อแคปซูล: 197.4 × 0.5150/0.4120 = 246.7 mg",
        "%LC = 246.7 / 250 × 100 = 98.7%",
      ],
    },
    {
      t: "Ion-pair reversed-phase chromatography",
      p: "ยาที่เป็น quaternary ammonium (ประจุบวกถาวรทุก pH) elute ใกล้ void volume บนคอลัมน์ C18 ด้วย mobile phase phosphate buffer pH 3/methanol การเติมสารใดลงใน mobile phase น่าจะเพิ่ม retention ได้มากที่สุด",
      o: [
        "Sodium 1-octanesulfonate เป็น ion-pair reagent",
        "Tetrabutylammonium hydrogen sulfate",
        "เพิ่มสัดส่วน methanol",
        "Triethylamine เพื่อปิด silanol",
        "ปรับ pH เป็น 7 เพื่อลดการแตกตัว",
      ],
      a: 0,
      r: "Ion-pair chromatography เติม reagent ที่มีประจุตรงข้ามกับสารและมีหาง hydrophobic (เช่น alkyl sulfonate สำหรับสารประจุบวก, tetraalkylammonium สำหรับสารประจุลบ) reagent จะ adsorb บน C18 และ/หรือจับคู่กับสารเป็น neutral ion pair ทำให้ retention เพิ่มขึ้น ยิ่งหาง alkyl ยาว (C5 → C12) หรือความเข้มข้นสูง retention ยิ่งเพิ่ม\n\nQuaternary ammonium มีประจุถาวร การปรับ pH จึงไม่เปลี่ยนการแตกตัว ข้อเสียของ ion-pair: equilibrate คอลัมน์นาน ไม่เหมาะกับ gradient/MS และควรกำหนดคอลัมน์ไว้ใช้เฉพาะ",
      w: [
        "ถูก — alkyl sulfonate (ประจุลบ) จับคู่กับสารประจุบวก เพิ่ม hydrophobicity และ retention",
        "Tetrabutylammonium เป็น ion-pair reagent สำหรับสารประจุลบ ไม่ใช่สารประจุบวก",
        "เพิ่ม organic solvent ลด retention ใน RP-HPLC",
        "TEA ช่วยลด tailing จาก silanol แต่ไม่เพิ่ม retention อย่างมีนัยสำคัญ (อาจลดด้วยซ้ำ)",
        "Quaternary ammonium มีประจุถาวร pH ไม่เปลี่ยนการแตกตัว",
      ],
      k: "Ion-pair: สารประจุ + → alkyl sulfonate; สารประจุ − → tetraalkylammonium; หางยาว/เข้มข้นสูง → retain มากขึ้น",
      d: "medium",
      ref: "Snyder, Kirkland & Dolan, Introduction to Modern Liquid Chromatography 3rd ed. (Ion-pair chromatography)",
    },
    {
      t: "Specificity via forced degradation and peak purity",
      p: "การพิสูจน์ว่า HPLC assay เป็น stability-indicating method ข้อใดเป็นแนวทางที่เหมาะสมที่สุดตาม ICH Q2(R2)",
      o: [
        "ทำ forced degradation (acid, base, oxidation, heat, light) ให้เกิดการสลาย ~5–20% แล้วแสดงว่า peak ของยาแยกจาก degradants และผ่าน peak purity (PDA หรือ MS)",
        "ฉีด standard 6 ครั้งให้ %RSD ≤ 2.0%",
        "แสดง linearity r ≥ 0.999 ในช่วง 80–120%",
        "ทดสอบ recovery ของยาที่ spike ในยาหลอกที่ 3 ระดับ",
        "สลายตัวอย่างจนยาหายไปหมดเพื่อดู degradants ทั้งหมด",
      ],
      a: 0,
      r: "Specificity คือความสามารถวัดสารที่สนใจได้อย่างถูกต้องเมื่อมีสารอื่นที่คาดว่าจะมี (impurities, degradants, excipients) สำหรับ stability-indicating method ต้องพิสูจน์ด้วย stress testing ให้ได้ degradation พอประมาณ (มักตั้งเป้า ~5–20%) เพื่อสร้าง degradants จริง แล้วแสดงว่า peak ของยามี resolution จาก degradants และ peak purity ผ่าน (PDA spectral homogeneity หรือ MS)\n\nการสลายมากเกินไปทำให้เกิด secondary degradants ที่ไม่สะท้อนสภาวะจริง ส่วน precision, linearity และ accuracy เป็น characteristics อื่นที่ไม่พิสูจน์ specificity",
      w: [
        "ถูก — forced degradation + resolution + peak purity คือการพิสูจน์ specificity ของ stability-indicating method",
        "เป็น system precision/SST ไม่ใช่ specificity",
        "เป็น linearity ไม่ได้บอกว่ามีสารอื่นซ้อนทับ peak หรือไม่",
        "เป็นการพิสูจน์ accuracy (และ placebo interference บางส่วน) ไม่ครอบคลุม degradants",
        "การสลายมากเกินไปสร้าง secondary degradants ที่ไม่เกี่ยวข้อง",
      ],
      k: "Stability-indicating = forced degradation (~5–20%) + resolution จาก degradants + peak purity (PDA/MS)",
      d: "medium",
      ref: "ICH Q2(R2) Validation of Analytical Procedures (Specificity); ICH Q1A(R2) Stress testing",
    },
    {
      t: "Indicator selection for weak acid–strong base titration",
      p: "Assay กรดอินทรีย์อ่อน (pKa 4.2) ในเอทานอลผสมน้ำ ด้วย 0.1 M NaOH แบบ direct titration ควรเลือก indicator ใดเหมาะสมที่สุด",
      o: [
        "Phenolphthalein (ช่วงเปลี่ยนสี pH ~8.2–10.0)",
        "Methyl orange (ช่วงเปลี่ยนสี pH ~3.1–4.4)",
        "Methyl red (ช่วงเปลี่ยนสี pH ~4.4–6.2)",
        "Bromophenol blue (ช่วงเปลี่ยนสี pH ~3.0–4.6)",
        "Eriochrome black T",
      ],
      a: 0,
      r: "ที่ equivalence point ของการไทเทรตกรดอ่อนด้วยเบสแก่ สารละลายมี conjugate base (A⁻) ซึ่งไฮโดรไลซ์ให้ OH⁻ ทำให้ pH ที่จุดสมมูลสูงกว่า 7 (ประมาณ 8–9) จึงต้องเลือก indicator ที่เปลี่ยนสีในช่วงด่าง เช่น phenolphthalein หรือ thymol blue\n\nIndicator ที่เปลี่ยนสีในช่วงกรด (methyl orange, methyl red, bromophenol blue) จะเปลี่ยนสีก่อนถึงจุดสมมูล ทำให้ผล assay ต่ำกว่าความจริง ในทางกลับกัน การไทเทรตเบสอ่อนด้วยกรดแก่ (pH equivalence < 7) จึงเลือก methyl orange/methyl red",
      w: [
        "ถูก — pH ที่ equivalence point ของกรดอ่อน + เบสแก่ อยู่ในช่วงด่าง (~8–9) ตรงกับ phenolphthalein",
        "เปลี่ยนสีในช่วงกรด ก่อนถึงจุดสมมูล เหมาะกับเบสอ่อน + กรดแก่",
        "เปลี่ยนสีก่อนถึงจุดสมมูลของการไทเทรตนี้ ทำให้ผลต่ำ",
        "เปลี่ยนสีในช่วงกรด ไม่เหมาะกับการไทเทรตนี้",
        "เป็น metallochromic indicator สำหรับ complexometric titration",
      ],
      k: "กรดอ่อน + เบสแก่ → equivalence pH > 7 → phenolphthalein; เบสอ่อน + กรดแก่ → methyl orange/red",
      d: "medium",
      ref: "Beckett & Stenlake, Practical Pharmaceutical Chemistry Part 1 (Acid–base titrations); Skoog, Fundamentals of Analytical Chemistry",
    },
    {
      t: "Class 3 solvents controlled by loss on drying",
      p: "API ผลิตโดยใช้ ethanol และ ethyl acetate (ทั้งคู่เป็น ICH Q3C Class 3) เท่านั้น ไม่มี Class 1/2 ใดเกี่ยวข้องในกระบวนการ ผล loss on drying ของ lot ล่าสุดได้ 0.3% ข้อใดสรุปได้ถูกต้องที่สุด",
      o: [
        "ยอมรับได้ เพราะเมื่อมีเฉพาะ Class 3 solvents สามารถใช้ LOD ควบคุมได้ และ ≤ 0.5% ไม่ต้องระบุ solvent แต่ละชนิดด้วยวิธีจำเพาะ",
        "ต้องทำ GC ทุก lot เสมอ เพราะ LOD ไม่สามารถใช้ควบคุม residual solvents ได้ในทุกกรณี",
        "ไม่ผ่าน เพราะ Class 3 solvents ต้องไม่เกิน 0.05%",
        "ยอมรับได้เฉพาะเมื่อ LOD ≤ 0.1% เท่านั้น",
        "ต้องคำนวณ PDE ของแต่ละ solvent เทียบกับ Option 2 ก่อนเสมอแม้ LOD ต่ำกว่า 0.5%",
      ],
      a: 0,
      r: "ICH Q3C: Class 3 solvents มีความเป็นพิษต่ำ (PDE ≥ 50 mg/day) ปริมาณ ≤ 50 mg/day (≈ 0.5% ภายใต้ Option 1) ยอมรับได้โดยไม่ต้องให้เหตุผลเพิ่มเติม\n\nถ้าในกระบวนการมีเฉพาะ Class 3 solvents สามารถใช้การทดสอบที่ไม่จำเพาะ เช่น loss on drying ควบคุมได้ โดย LOD ≤ 0.5% ถือว่ายอมรับได้ ถ้า LOD > 0.5% หรือมี Class 1/2 ร่วมด้วยจึงต้องใช้วิธีจำเพาะ (เช่น GC) ระบุและหาปริมาณแต่ละ solvent ข้อควรระวัง: LOD รวมน้ำด้วย ถ้า API เป็น hydrate อาจต้องใช้ KF แยกน้ำออก",
      w: [
        "ถูก — มีเฉพาะ Class 3 จึงใช้ LOD ควบคุมได้ และ ≤ 0.5% ยอมรับได้โดยไม่ต้องระบุ solvent จำเพาะ",
        "ICH Q3C อนุญาตให้ใช้ LOD กรณีมีเฉพาะ Class 3 solvents",
        "0.05% ไม่ใช่เกณฑ์ของ Class 3 (เกณฑ์คือ 0.5%)",
        "เกณฑ์ที่ยอมรับได้คือ 0.5% ไม่ใช่ 0.1%",
        "ภายใต้ 0.5% (50 mg/day) ไม่ต้องคำนวณ Option 2 สำหรับ Class 3",
      ],
      k: "เฉพาะ Class 3 → ใช้ LOD ได้; ≤ 0.5% ยอมรับได้; > 0.5% หรือมี Class 1/2 → ใช้ GC จำเพาะ",
      d: "hard",
      ref: "ICH Q3C(R9) Impurities: Guideline for Residual Solvents (Class 3; Analytical procedures); USP <467>",
    },
    {
      t: "OOS resampling versus retesting",
      p: "ผล OOS ของ assay ยาน้ำแขวนตะกอน (suspension) ระหว่าง Phase I investigation พบหลักฐานว่าผู้สุ่มตัวอย่างไม่ได้เขย่าขวดตาม SOP ก่อนดูดตัวอย่าง ทำให้ตัวอย่างที่ส่งห้องปฏิบัติการไม่เป็นตัวแทนของ batch ข้อใดถูกต้องที่สุด",
      o: [
        "สามารถ resample (เก็บตัวอย่างใหม่จาก batch) ได้ตาม SOP เพราะมีหลักฐานว่าการสุ่มตัวอย่างเดิมผิดพลาด โดยต้องบันทึกเหตุผลและเก็บผลเดิมไว้ในรายงานการสืบสวน",
        "ห้าม resample ในทุกกรณี ต้อง retest จากตัวอย่างเดิมเท่านั้น",
        "Resample ได้ทุกครั้งที่ผล OOS เพื่อยืนยันผล",
        "ทดสอบตัวอย่างเดิมซ้ำโดยไม่เขย่า เพื่อให้สภาวะเหมือนครั้งแรก",
        "เฉลี่ยผลจากตัวอย่างเดิมและตัวอย่างใหม่เพื่อรายงานผลสุดท้าย",
      ],
      a: 0,
      r: "FDA OOS guidance แยก retesting (ทดสอบซ้ำจาก portion ของตัวอย่างเดิมที่เป็น homogeneous) กับ resampling (เก็บตัวอย่างใหม่จาก batch) Resampling ควรทำน้อยครั้งและต้องมีเหตุผล เช่น มีหลักฐานว่าตัวอย่างเดิมไม่เป็นตัวแทน (sampling error) หรือเตรียม/เก็บรักษาไม่ถูกต้อง โดยใช้วิธีสุ่มที่ถูกต้อง (และอาจเป็นวิธีเดียวกับที่ validate แล้ว)\n\nผลเดิมต้องไม่ถูกลบ ต้องบันทึกไว้พร้อมเหตุผล การ resample โดยไม่มีหลักฐานเพื่อหวังให้ผ่านถือเป็น testing into compliance ในกรณี suspension การไม่เขย่าเป็น sampling error ที่ชัดเจนเพราะยาตกตะกอน",
      w: [
        "ถูก — มีหลักฐาน sampling error ชัดเจน จึง resample ได้ตาม SOP พร้อมบันทึกเหตุผลและเก็บผลเดิม",
        "Resampling ทำได้เมื่อมีเหตุผลรองรับ เช่น ตัวอย่างเดิมไม่เป็นตัวแทน",
        "Resampling โดยไม่มีเหตุผลเป็นการหลีกเลี่ยงผล OOS (testing into compliance)",
        "ตัวอย่างเดิมไม่เป็นตัวแทนอยู่แล้ว การทดสอบซ้ำจากตัวอย่างนั้นไม่แก้ปัญหา",
        "ผลจากตัวอย่างที่ไม่เป็นตัวแทนไม่ควรนำมาเฉลี่ยกับผลจากตัวอย่างที่ถูกต้อง",
      ],
      k: "Retest = ตัวอย่างเดิม; Resample = ตัวอย่างใหม่จาก batch — ทำได้เมื่อมีหลักฐานว่าตัวอย่างเดิมไม่เป็นตัวแทน",
      d: "hard",
      ref: "FDA Guidance for Industry: Investigating OOS Test Results for Pharmaceutical Production (Resampling)",
    },
    {
      t: "Audit trail review of chromatography data system",
      p: "ระหว่างการตรวจ audit trail ของ chromatography data system (CDS) พบว่าก่อนฉีดชุด official ของ batch หนึ่ง มีการฉีดตัวอย่างจาก vial เดียวกันในชื่อ 'test injection' 2 ครั้งแล้วลบ (delete) ข้อมูลเหล่านั้น และมีการ manual reintegration ของ impurity peak หลายครั้งโดยไม่มีเหตุผลบันทึก ข้อใดเป็นการประเมินที่เหมาะสมที่สุด",
      o: [
        "เป็นข้อบ่งชี้ร้ายแรงของ data integrity (trial injections/testing into compliance และ integration ที่ไม่มีเหตุผล) ต้องสืบสวน ประเมินผลกระทบต่อ batch ที่เกี่ยวข้อง และแก้ไขระบบ (สิทธิ์ผู้ใช้, SOP การ integrate, การทบทวน audit trail)",
        "ยอมรับได้ เพราะ test injection เป็นการ equilibrate ระบบตามปกติ",
        "ยอมรับได้ ถ้าผล official injection ผ่าน spec",
        "Manual reintegration ทำได้อิสระโดยไม่ต้องบันทึกเหตุผล ถ้าผู้ทำเป็นนักวิเคราะห์อาวุโส",
        "แก้ไขโดยปิด audit trail ชั่วคราวระหว่างทำ method development เพื่อลดข้อมูลที่ต้องทบทวน",
      ],
      a: 0,
      r: "แนวทาง data integrity (FDA 2018, MHRA 2018, PIC/S PI 041) ระบุว่าการฉีดตัวอย่างจริงเป็น 'trial/test injection' เพื่อดูผลก่อน แล้วลบหรือไม่รายงาน คือการ 'testing into compliance' ข้อมูลทั้งหมดที่สร้างใน GMP ถือเป็น CGMP records ต้องเก็บและทบทวน การ equilibrate ระบบควรใช้ standard หรือ blank ที่กำหนดใน SOP ไม่ใช่ตัวอย่างจริง\n\nManual integration ต้องมี SOP ควบคุม มีเหตุผลทางวิทยาศาสตร์ บันทึกไว้ และทบทวนโดยผู้ตรวจสอบ ระบบต้องจำกัดสิทธิ์ลบข้อมูล และมีการทบทวน audit trail เป็นส่วนหนึ่งของ data review ก่อน release การพบเหตุการณ์ดังกล่าวต้องสืบสวนย้อนหลัง ประเมินผลกระทบกับ batch อื่น และทำ CAPA",
      w: [
        "ถูก — trial injections ที่ถูกลบและ reintegration ที่ไม่มีเหตุผลเป็นสัญญาณ data integrity ร้ายแรง ต้องสืบสวนและแก้ไขระบบ",
        "การ equilibrate ต้องใช้ standard/blank ไม่ใช่ตัวอย่างจริง และไม่ลบข้อมูล",
        "ผลที่ผ่านไม่ได้ทำให้การลบข้อมูลและการเลือกผลเป็นที่ยอมรับ",
        "Manual integration ต้องมี SOP เหตุผลที่บันทึก และการทบทวน ไม่ว่าผู้ทำเป็นใคร",
        "Audit trail ต้องเปิดใช้งานตลอดใน GMP environment การปิดเป็นการละเมิด 21 CFR Part 11/Annex 11",
      ],
      k: "ห้าม trial injection ของตัวอย่างจริง/ลบข้อมูล; manual integration ต้องมี SOP + เหตุผล; ทบทวน audit trail ก่อน release",
      d: "hard",
      ref: "FDA Guidance: Data Integrity and Compliance With Drug CGMP — Questions and Answers (2018); PIC/S PI 041-1; EU GMP Annex 11",
    },
  ],
];
