import type { Ip1MockDomainContent } from "@/lib/ip1-mock/types";

// หมวด Preformulation และเภสัชกรรมเชิงฟิสิกส์ (Physical pharmacy)
export const PREFORM: Ip1MockDomainContent = [
  // Mock Set 1
  [
    {
      t: "Henderson-Hasselbalch percent ionized of weak acid",
      p: "ยา A เป็น weak acid มี pKa 3.4 นักวิจัย preformulation ต้องการประเมินสัดส่วนการแตกตัวของยาในบัฟเฟอร์ pH 5.4 ที่ใช้ทดสอบ solubility ร้อยละของยาที่อยู่ในรูป ionized มีค่าประมาณเท่าใด",
      o: ["1.0%", "9.1%", "50%", "90.9%", "99.0%"],
      a: 4,
      r: "สำหรับ weak acid สมการ Henderson–Hasselbalch คือ pH = pKa + log([A⁻]/[HA]) ดังนั้น log([A⁻]/[HA]) = 5.4 − 3.4 = 2 หรือ [A⁻]/[HA] = 100\n\nสัดส่วน ionized = 100/(100+1) = 0.990 หรือ 99.0% กล่าวคือเมื่อ pH สูงกว่า pKa ของกรด 2 หน่วย ยาแตกตัวเกือบทั้งหมด\n\nวิธีจำเร็ว: ทุก 1 หน่วย pH ที่ห่างจาก pKa สัดส่วนเปลี่ยน 10 เท่า (1 หน่วย ≈ 91%, 2 หน่วย ≈ 99%, 3 หน่วย ≈ 99.9%) ทิศทางขึ้นกับว่าเป็นกรดหรือเบส: กรดแตกตัวมากเมื่อ pH > pKa",
      w: [
        "1.0% คือสัดส่วน unionized ไม่ใช่ ionized (เป็นการกลับทิศของกรดกับเบส)",
        "9.1% ได้จากการคิดว่าห่างเพียง 1 หน่วยและกลับทิศ ไม่ตรงกับ ΔpH = 2",
        "50% เกิดเฉพาะเมื่อ pH = pKa เท่านั้น",
        "90.9% คือกรณี pH − pKa = 1 หน่วย แต่โจทย์ห่าง 2 หน่วย",
        "ถูก — [A⁻]/[HA] = 10² = 100 จึง ionized = 100/101 ≈ 99.0%",
      ],
      k: "Weak acid: % ionized = 100/(1+10^(pKa−pH)); pH สูงกว่า pKa 2 หน่วย → ionized ≈ 99%",
      d: "easy",
      ref: "Martin's Physical Pharmacy and Pharmaceutical Sciences 7th ed., Ch.8 Buffered and Isotonic Solutions",
      c: [
        "log([A⁻]/[HA]) = pH − pKa = 5.4 − 3.4 = 2",
        "[A⁻]/[HA] = 10² = 100",
        "% ionized = 100/(100 + 1) × 100 = 99.0%",
      ],
    },
    {
      t: "pH-solubility profile of weak base below pHmax",
      p: "ยา B เป็น weak base มี pKa 7.8 และ intrinsic solubility (S₀ ของ free base) 0.015 mg/mL หากต้องการเตรียมสารละลายในบัฟเฟอร์ pH 5.8 (สมมติว่า pH นี้ยังสูงกว่า pHmax จึงยังมี free base เป็น solid phase ที่สมดุล) total solubility ที่คาดได้มีค่าประมาณเท่าใด",
      o: ["0.015 mg/mL", "0.030 mg/mL", "0.15 mg/mL", "1.52 mg/mL", "15.2 mg/mL"],
      a: 3,
      r: "สำหรับ weak base ที่มี free base เป็น solid phase total solubility S = S₀[1 + 10^(pKa − pH)] เพราะรูป unionized ถูกจำกัดที่ S₀ ส่วนรูป ionized (BH⁺) เพิ่มขึ้นตามอัตราส่วน Henderson–Hasselbalch\n\nแทนค่า: 10^(7.8 − 5.8) = 100 ดังนั้น S = 0.015 × 101 = 1.515 ≈ 1.52 mg/mL\n\nข้อควรระวัง: สมการนี้ใช้ได้เมื่อ pH > pHmax เท่านั้น ถ้า pH ต่ำกว่า pHmax solid phase จะกลายเป็นเกลือ และ solubility ถูกจำกัดด้วย Ksp ของเกลือแทน กราฟจึงแบนราบ ไม่เพิ่มขึ้นไม่สิ้นสุด",
      w: [
        "0.015 mg/mL คือ S₀ ซึ่งเป็น solubility เฉพาะเมื่อ pH สูงกว่า pKa มากจนยาไม่แตกตัว",
        "0.030 mg/mL คือค่าที่ pH = pKa (S = 2S₀) ไม่ใช่ pH 5.8",
        "0.15 mg/mL เกิดจากการคิดว่า ΔpH = 1 หน่วยหรือคูณ 10 แทน 101",
        "ถูก — S = 0.015 × (1 + 10²) = 1.52 mg/mL",
        "15.2 mg/mL ใช้ ΔpH = 3 หน่วย (คูณ ~1000) ซึ่งคำนวณเกินจริง",
      ],
      k: "Weak base: S = S₀(1 + 10^(pKa − pH)) ใช้ได้เฉพาะช่วง pH > pHmax",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed., Ch.23 Pharmaceutical preformulation; Avdeef, Absorption and Drug Development 2nd ed.",
      c: [
        "pKa − pH = 7.8 − 5.8 = 2 → 10² = 100",
        "S = S₀ × (1 + 100) = 0.015 × 101",
        "S = 1.515 ≈ 1.52 mg/mL",
      ],
    },
    {
      t: "Counterion selection by delta pKa rule",
      p: "ทีม salt screening ต้องการเตรียมเกลือที่เสถียรของยา C ซึ่งเป็น weak base มี pKa (ของ conjugate acid) 3.5 กรดใดเหมาะสมที่สุดที่จะใช้เป็น counterion เพื่อให้เกิด proton transfer สมบูรณ์และได้เกลือที่ไม่แยกตัวกลับเป็น free base ง่าย",
      o: [
        "Methanesulfonic acid (pKa ≈ −1.9)",
        "Acetic acid (pKa ≈ 4.8)",
        "Citric acid (pKa₁ ≈ 3.1)",
        "Fumaric acid (pKa₁ ≈ 3.0)",
        "Succinic acid (pKa₁ ≈ 4.2)",
      ],
      a: 0,
      r: "กฎ ΔpKa ที่ใช้ใน salt selection: ให้ pKa(base) − pKa(acid) ≥ 2–3 หน่วย เพื่อให้เกิด proton transfer เกือบสมบูรณ์และได้เกลือที่เสถียร\n\nยา C มี pKa เพียง 3.5 (เบสอ่อนมาก) จึงต้องใช้กรดแก่ที่มี pKa ≤ ~1 เช่น HCl, methanesulfonic, sulfuric, benzenesulfonic acid ใน option มีเพียง methanesulfonic acid (pKa ≈ −1.9) ที่ให้ ΔpKa ≈ 5.4\n\nกรดคาร์บอกซิลิกทั่วไป (acetic, citric, fumaric, succinic) ให้ ΔpKa < 1 หรือติดลบ ซึ่งมักได้ co-crystal หรือเกลือที่ disproportionate กลับเป็น free base เมื่อสัมผัสความชื้น",
      w: [
        "ถูก — ΔpKa = 3.5 − (−1.9) ≈ 5.4 มากกว่า 3 จึงเกิด proton transfer สมบูรณ์ ได้ mesylate salt ที่เสถียร",
        "ΔpKa = 3.5 − 4.8 ติดลบ ไม่เกิด proton transfer จึงไม่ได้เกลือ",
        "ΔpKa ≈ 0.4 น้อยเกินไป เกลือที่ได้ (ถ้าเกิด) มักไม่เสถียรและแยกตัวง่าย",
        "ΔpKa ≈ 0.5 ไม่ถึงเกณฑ์ 2–3 หน่วย เสี่ยงได้ co-crystal หรือเกลือไม่เสถียร",
        "ΔpKa ติดลบ (3.5 − 4.2) ไม่สามารถ protonate เบสได้เพียงพอ",
      ],
      k: "Salt formation ที่เสถียรต้องการ ΔpKa (base − acid) ≥ 2–3; เบสอ่อนมากต้องใช้กรดแก่ (HCl, mesylate, besylate)",
      d: "medium",
      ref: "Stahl & Wermuth, Handbook of Pharmaceutical Salts: Properties, Selection, and Use 2nd ed.",
    },
    {
      t: "Enantiotropy by heat of fusion rule",
      p: "การคัดกรองผลึกของยา D พบ 2 polymorphs จาก DSC: Form I มี melting point 162 °C และ ΔHf 27 kJ/mol ส่วน Form II มี melting point 151 °C และ ΔHf 33 kJ/mol ตามกฎของ Burger–Ramberger ข้อสรุปใดถูกต้องที่สุด",
      o: [
        "Enantiotropic; Form II น่าจะเป็นรูปที่เสถียรที่อุณหภูมิห้อง (ต่ำกว่า transition temperature)",
        "Monotropic; Form I เสถียรกว่าทุกอุณหภูมิเพราะ melting point สูงกว่า",
        "Monotropic; Form II เสถียรกว่าทุกอุณหภูมิเพราะ ΔHf สูงกว่า",
        "Enantiotropic; Form I เสถียรที่อุณหภูมิห้องเพราะมี melting point สูงกว่า",
        "สรุปความสัมพันธ์ไม่ได้จนกว่าจะทราบ density ของทั้งสองรูป",
      ],
      a: 0,
      r: "Heat of fusion rule (Burger–Ramberger): ถ้ารูปที่มี melting point สูงกว่ามี ΔHf ต่ำกว่า ทั้งสองรูปมีความสัมพันธ์แบบ enantiotropic (มี transition temperature อยู่ต่ำกว่า melting point) แต่ถ้ารูปที่ mp สูงกว่ามี ΔHf สูงกว่าด้วย จะเป็น monotropic\n\nกรณีนี้ Form I mp สูงกว่าแต่ ΔHf ต่ำกว่า → enantiotropic ดังนั้นที่อุณหภูมิต่ำกว่า Tt รูปที่เสถียรคือ Form II (รูปที่ mp ต่ำกว่าแต่มี lattice enthalpy สูงกว่า) และเหนือ Tt Form I จะเสถียรกว่า\n\nในทางปฏิบัติควรยืนยันด้วย competitive slurry หรือ solubility ที่หลายอุณหภูมิ เพราะการเลือกผิดรูปอาจทำให้เกิด solid-state transformation ระหว่างเก็บรักษา",
      w: [
        "ถูก — mp สูงกว่าแต่ ΔHf ต่ำกว่า = enantiotropic; ต่ำกว่า Tt รูปที่ ΔHf สูง (Form II) เสถียร",
        "Melting point สูงกว่าอย่างเดียวไม่พอสรุป monotropy ต้องดู ΔHf ร่วมด้วย",
        "ข้อมูลไม่เข้ากับ monotropy เพราะรูปที่ mp สูงมี ΔHf ต่ำกว่า",
        "ระบุความสัมพันธ์ถูกแต่รูปที่เสถียรที่อุณหภูมิห้องผิด Form I เสถียรเฉพาะเหนือ Tt",
        "Density rule เป็นกฎเสริม ข้อมูล mp และ ΔHf เพียงพอใช้ heat of fusion rule ได้แล้ว",
      ],
      k: "Heat of fusion rule: รูป mp สูงแต่ ΔHf ต่ำ → enantiotropic; รูป mp สูงและ ΔHf สูง → monotropic",
      d: "hard",
      ref: "Burger A, Ramberger R. Mikrochim Acta 1979; Brittain, Polymorphism in Pharmaceutical Solids 2nd ed.",
    },
    {
      t: "Ph. Eur. hygroscopicity classification",
      p: "ทดสอบ hygroscopicity ของผงยา E ตาม Ph. Eur. โดยชั่งตัวอย่าง 1.000 g เก็บที่ 25 °C/80% RH นาน 24 ชั่วโมง ชั่งได้ 1.064 g และผงยังคงเป็นของแข็ง ควรจัดยา E อยู่ในกลุ่มใด",
      o: [
        "Hygroscopic (น้ำหนักเพิ่ม 6.4%)",
        "Slightly hygroscopic (น้ำหนักเพิ่ม 6.4%)",
        "Very hygroscopic (น้ำหนักเพิ่ม 6.4%)",
        "Deliquescent เพราะน้ำหนักเพิ่มเกิน 5%",
        "Non-hygroscopic เพราะน้ำหนักเพิ่มน้อยกว่า 10%",
      ],
      a: 0,
      r: "Ph. Eur. 5.11 จัดระดับ hygroscopicity จาก % น้ำหนักที่เพิ่มขึ้นหลังเก็บที่ 25 °C/80% RH นาน 24 ชม.: slightly hygroscopic ≥ 0.2% แต่ < 2%; hygroscopic ≥ 2% แต่ < 15%; very hygroscopic ≥ 15%; deliquescent คือดูดน้ำจนกลายเป็นของเหลว\n\n% เพิ่ม = (1.064 − 1.000)/1.000 × 100 = 6.4% จึงอยู่ในกลุ่ม hygroscopic\n\nผลนี้ใช้กำหนดสภาวะการผลิต (ควบคุม RH ในห้องผลิต) การเลือกบรรจุภัณฑ์ และอาจเป็นเหตุผลให้พิจารณาเปลี่ยน salt form",
      w: [
        "ถูก — 6.4% อยู่ในช่วง ≥ 2% และ < 15% = hygroscopic",
        "Slightly hygroscopic คือ 0.2–<2% ต่ำกว่าค่าที่ได้",
        "Very hygroscopic ต้องเพิ่ม ≥ 15%",
        "Deliquescent ตัดสินจากการกลายเป็นของเหลว ไม่ใช่เกณฑ์ 5% และโจทย์ระบุว่ายังเป็นของแข็ง",
        "ไม่มีเกณฑ์ 10% สำหรับ non-hygroscopic; เพิ่มเกิน 0.2% ก็ถือว่าดูดความชื้นแล้ว",
      ],
      k: "Ph. Eur. 5.11 (25 °C/80% RH, 24 h): 0.2–<2% slightly; 2–<15% hygroscopic; ≥15% very; กลายเป็นของเหลว = deliquescent",
      d: "medium",
      ref: "Ph. Eur. 5.11 Characters section in monographs (hygroscopicity)",
      c: ["% เพิ่ม = (1.064 − 1.000)/1.000 × 100 = 6.4%", "2% ≤ 6.4% < 15% → hygroscopic"],
    },
    {
      t: "Bulk porosity from true density",
      p: "ผง excipient ชนิดหนึ่งวัด true density ด้วย helium pycnometer ได้ 1.52 g/cm³ วัด bulk density ได้ 0.48 g/mL และ tapped density 0.64 g/mL ค่า porosity ของ powder bed ในสภาพ bulk (untapped) มีค่าประมาณเท่าใด",
      o: ["25.0%", "31.6%", "57.9%", "68.4%", "75.0%"],
      a: 3,
      r: "Porosity (ε) ของ powder bed คือสัดส่วนของปริมาตรช่องว่าง (ทั้ง inter- และ intraparticulate) ต่อปริมาตร bed ทั้งหมด คำนวณได้จาก ε = 1 − (ρbulk/ρtrue)\n\nε = 1 − 0.48/1.52 = 1 − 0.316 = 0.684 หรือ 68.4%\n\nTrue density วัดด้วย helium pycnometry เพราะ He โมเลกุลเล็กแทรกเข้ารูพรุนได้ จึงได้ปริมาตรของแข็งจริง ส่วน bulk/tapped density รวมช่องว่างด้วย จึงใช้ร่วมกันประเมิน packing, compressibility และ porosity",
      w: [
        "25.0% คือ Carr's index = (0.64 − 0.48)/0.64 ไม่ใช่ porosity",
        "31.6% คือ ρbulk/ρtrue ซึ่งเป็น packing fraction (solid fraction) ไม่ใช่ porosity",
        "57.9% คือ porosity ของ tapped bed (1 − 0.64/1.52) ไม่ใช่ bulk",
        "ถูก — ε = 1 − 0.48/1.52 = 68.4%",
        "75.0% คือ ρbulk/ρtapped (1/Hausner ratio) ไม่ใช่ porosity",
      ],
      k: "Porosity ε = 1 − ρbulk/ρtrue; true density วัดด้วย helium pycnometry",
      d: "medium",
      ref: "USP <699> Density of Solids; USP <616> Bulk Density and Tapped Density of Powders",
      c: ["ρbulk/ρtrue = 0.48/1.52 = 0.316", "ε = 1 − 0.316 = 0.684 → 68.4%"],
    },
    {
      t: "Noyes-Whitney combined surface area and concentration gradient",
      p: "ยา F มี Cs ในตัวกลาง 1.6 mg/mL เดิมทดสอบ dissolution ในสภาวะ sink (C ≈ 0) ต่อมาลด particle size ลง 4 เท่า (มวลเท่าเดิม) และทดสอบในปริมาตรน้อยลงจน C ในตัวกลางขณะวัดเท่ากับ 1.2 mg/mL ถ้า D และ h คงที่ อัตราการละลาย ณ ขณะนั้นเทียบกับการทดลองเดิมเป็นกี่เท่า",
      o: ["0.25 เท่า", "0.5 เท่า", "1.0 เท่า", "2.0 เท่า", "4.0 เท่า"],
      a: 2,
      r: "Noyes–Whitney: dM/dt = (D·A/h)(Cs − C) อัตราการละลายเป็นสัดส่วนกับพื้นที่ผิว A และ concentration gradient (Cs − C)\n\nลดขนาดอนุภาคลง 4 เท่าที่มวลเท่าเดิม พื้นที่ผิวจำเพาะ (∝ 1/d) เพิ่ม 4 เท่า แต่ gradient ลดจาก 1.6 เหลือ 1.6 − 1.2 = 0.4 mg/mL (เหลือ 0.25 เท่า) ผลรวม = 4 × 0.25 = 1.0 เท่า\n\nบทเรียน: การ micronize จะได้ประโยชน์เต็มที่ต้องรักษา sink condition (มักให้ C < Cs/3 หรือปริมาตรตัวกลาง ≥ 3 เท่าของที่ต้องใช้ละลายยาทั้งหมด) ในความเป็นจริง h ยังลดลงเล็กน้อยเมื่ออนุภาคเล็กลง จึงอาจเร็วกว่าค่าประมาณนี้",
      w: [
        "0.25 เท่า คิดเฉพาะ gradient ที่ลดลง ลืมพื้นที่ผิวที่เพิ่ม 4 เท่า",
        "0.5 เท่า ไม่สอดคล้องกับปัจจัยใดในสมการ",
        "ถูก — A เพิ่ม 4 เท่า × (Cs − C) เหลือ 0.25 เท่า = 1.0 เท่า",
        "2.0 เท่า เกิดจากคิดว่า gradient เหลือครึ่งหนึ่ง (0.5) แทนที่จะเหลือ 0.4/1.6 = 0.25",
        "4.0 เท่า คิดเฉพาะพื้นที่ผิว โดยลืมว่า C ที่สะสมทำให้ gradient ลดลง",
      ],
      k: "Noyes–Whitney: rate ∝ A(Cs − C); ลด particle size เพิ่ม A แต่ต้องคง sink condition จึงได้ประโยชน์",
      d: "hard",
      ref: "Aulton's Pharmaceutics 6th ed., Ch.2 Dissolution and solubility; Noyes AA, Whitney WR. J Am Chem Soc 1897",
      c: [
        "A ∝ 1/d → ลด d 4 เท่า → A เพิ่ม 4 เท่า",
        "เดิม (Cs − C) = 1.6 − 0 = 1.6; ใหม่ = 1.6 − 1.2 = 0.4 → 0.4/1.6 = 0.25",
        "Rate ใหม่/เดิม = 4 × 0.25 = 1.0 เท่า",
      ],
    },
    {
      t: "CMC from surface tension plot",
      p: "นักวิจัยวัด surface tension ของสารละลาย polysorbate 80 ที่ความเข้มข้นต่างๆ แล้ว plot surface tension กับ log concentration พบว่า surface tension ลดลงเป็นเส้นตรง แล้วเกิดจุดหักเห (break point) หลังจากนั้นค่าแทบคงที่ ข้อใดอธิบายจุดหักเหและพฤติกรรมหลังจุดนั้นได้ถูกต้องที่สุด",
      o: [
        "จุดหักเหคือ CMC หลังจากนั้นสารลดแรงตึงผิวที่เติมเพิ่มส่วนใหญ่รวมตัวเป็น micelle ความเข้มข้น monomer ค่อนข้างคงที่",
        "จุดหักเหคือ Krafft point หลังจากนั้นสารลดแรงตึงผิวตกตะกอน",
        "จุดหักเหคือ cloud point หลังจากนั้นสารละลายขุ่นเพราะ phase separation",
        "จุดหักเหคือจุดที่ผิวหน้าอิ่มตัว หลังจากนั้นสารลดแรงตึงผิวไม่ละลายในน้ำอีก",
        "จุดหักเหคือ HLB ที่เหมาะสม หลังจากนั้นความสามารถ solubilize ยาลดลง",
      ],
      a: 0,
      r: "ก่อน CMC โมเลกุล surfactant (monomer) ไปดูดซับที่ผิวหน้าอากาศ–น้ำมากขึ้นตามความเข้มข้น surface tension จึงลดลงเป็นเส้นตรงกับ log C (สอดคล้องกับ Gibbs adsorption)\n\nเมื่อถึง critical micelle concentration (CMC) ผิวหน้าเกือบอิ่มตัว สารที่เติมเพิ่มจะรวมตัวเป็น micelle แทน ทำให้ความเข้มข้น monomer อิสระแทบคงที่ surface tension จึงไม่ลดลงอีก\n\nCMC หาได้จากจุดหักเหของคุณสมบัติหลายอย่าง (surface tension, conductivity สำหรับ ionic surfactant, light scattering, solubilization ของ dye) และยาที่ไม่ชอบน้ำจะถูก solubilize เพิ่มขึ้นอย่างชัดเจนเมื่อความเข้มข้นเกิน CMC",
      w: [
        "ถูก — break point คือ CMC; เกินจากนี้เกิด micelle และ monomer คงที่ surface tension จึงแบนราบ",
        "Krafft point เป็นอุณหภูมิ (ของ ionic surfactant) ไม่ใช่ความเข้มข้นในกราฟนี้",
        "Cloud point เป็นอุณหภูมิที่ nonionic surfactant แยกเฟสเมื่อให้ความร้อน ไม่ใช่จุดหักเหตามความเข้มข้น",
        "สารลดแรงตึงผิวยังละลายได้ต่อ แต่ไปอยู่ในรูป micelle ไม่ใช่หยุดละลาย",
        "HLB เป็นคุณสมบัติของโมเลกุล ไม่ได้หาจากกราฟนี้ และ solubilization เพิ่มขึ้นหลัง CMC",
      ],
      k: "Surface tension vs log C แบนราบที่ CMC; micelle เกิดเหนือ CMC และเป็นตัว solubilize ยาไม่ชอบน้ำ",
      d: "medium",
      ref: "Martin's Physical Pharmacy and Pharmaceutical Sciences 7th ed., Ch.15 Interfacial Phenomena & Ch.16 Colloidal Dispersions",
    },
    {
      t: "Pseudoplastic flow of polymer dispersions",
      p: "สารละลาย sodium carboxymethylcellulose 2% w/v เมื่อวัดด้วย rotational viscometer พบว่า apparent viscosity ลดลงเมื่อเพิ่ม shear rate และ rheogram ผ่านจุดกำเนิด (ไม่มี yield value) พฤติกรรมการไหลนี้คือข้อใด",
      o: [
        "Pseudoplastic (shear-thinning) flow",
        "Newtonian flow",
        "Bingham plastic flow",
        "Dilatant (shear-thickening) flow",
        "Rheopexy",
      ],
      a: 0,
      r: "Pseudoplastic flow พบบ่อยในสารละลาย polymer เช่น NaCMC, methylcellulose, tragacanth, sodium alginate สายโซ่ polymer ที่พันกันแบบสุ่มจะเรียงตัวตามทิศการไหลเมื่อได้รับ shear และปล่อยน้ำที่ถูกตรึงไว้ออกมา จึงทำให้ apparent viscosity ลดลงเมื่อ shear rate เพิ่ม\n\nRheogram ของ pseudoplastic เป็นเส้นโค้งที่ผ่านจุดกำเนิด (ไม่มี yield value) ต่างจาก plastic flow ที่ต้องมีแรงเกินค่า yield value ก่อนจึงไหล และมักอธิบายด้วย power law: F^N = η′G (N > 1 สำหรับ pseudoplastic)\n\nข้อดีในทางเภสัชกรรม: ผลิตภัณฑ์หนืดขณะตั้งทิ้งไว้ แต่เทหรือบีบออกจากหลอดได้ง่ายเมื่อเขย่า/บีบ",
      w: [
        "ถูก — viscosity ลดลงเมื่อ shear rate เพิ่ม และไม่มี yield value คือ pseudoplastic",
        "Newtonian มี viscosity คงที่ไม่ขึ้นกับ shear rate",
        "Bingham plastic ต้องมี yield value เส้นจึงไม่ผ่านจุดกำเนิด",
        "Dilatant viscosity เพิ่มขึ้นเมื่อ shear rate เพิ่ม ตรงข้ามกับข้อมูล",
        "Rheopexy เป็นพฤติกรรมขึ้นกับเวลา (ข้นขึ้นเมื่อเขย่าเบาๆ) ไม่ใช่สิ่งที่โจทย์บรรยาย",
      ],
      k: "Polymer solutions (NaCMC, MC, tragacanth) = pseudoplastic: shear-thinning, ไม่มี yield value",
      d: "easy",
      ref: "Martin's Physical Pharmacy and Pharmaceutical Sciences 7th ed., Ch.19 Rheology",
    },
    {
      t: "Maillard reaction amine drug with lactose",
      p: "ในการศึกษา drug–excipient compatibility ยา G ซึ่งมีหมู่ primary amine ผสมแบบ binary mixture 1:1 กับ excipient ต่างๆ แล้วเก็บที่ 40 °C/75% RH นาน 4 สัปดาห์ พบว่าเฉพาะส่วนผสมกับ lactose monohydrate เกิดสีน้ำตาลเหลืองและมี degradant ใหม่ คำอธิบายและแนวทางแก้ไขใดเหมาะสมที่สุด",
      o: [
        "เกิด Maillard reaction ระหว่าง amine กับ reducing sugar ควรเปลี่ยน filler เป็นสารที่ไม่ใช่ reducing sugar เช่น microcrystalline cellulose หรือ dibasic calcium phosphate",
        "เกิด hydrolysis ของ lactose จากความชื้น ควรเปลี่ยนเป็น anhydrous lactose",
        "เกิด polymorphic transformation ของยา ควรเปลี่ยน particle size ของ lactose",
        "เกิด oxidation จาก peroxide ใน lactose ควรเติม antioxidant โดยยังใช้ lactose ต่อได้",
        "เกิด photodegradation ของ lactose ควรเก็บในภาชนะทึบแสงเท่านั้น",
      ],
      a: 0,
      r: "Lactose เป็น reducing sugar (มี hemiacetal ที่เปิดเป็น aldehyde ได้) ทำปฏิกิริยากับ primary/secondary amine ผ่าน Maillard reaction ได้ Schiff base → Amadori rearrangement → ผลิตภัณฑ์สีน้ำตาล ความร้อนและความชื้นเร่งปฏิกิริยา ตัวอย่างที่รู้จัก เช่น fluoxetine HCl, amlodipine กับ lactose\n\nแนวทางแก้ที่ตรงจุดคือเลี่ยง reducing sugar โดยใช้ MCC, dibasic calcium phosphate, mannitol (sugar alcohol ไม่มีหมู่ reducing) แทน\n\nการใช้ anhydrous lactose ลดความชื้นแต่ไม่ได้ตัดสาเหตุ (หมู่ reducing ยังอยู่) ส่วน peroxide เป็นปัญหาของ povidone/crospovidone/polysorbate มากกว่า lactose",
      w: [
        "ถูก — amine + reducing sugar = Maillard (สีน้ำตาล) แก้โดยใช้ filler ที่ไม่มีหมู่ reducing",
        "Lactose hydrolysis ไม่ใช่สาเหตุของ degradant ของยา และ anhydrous lactose ยังเป็น reducing sugar",
        "Polymorphic change ไม่ทำให้เกิดสีน้ำตาลหรือ degradant ใหม่ และไม่จำเพาะต่อ lactose",
        "Peroxide เป็น impurity เด่นใน povidone/PEG/polysorbate และไม่อธิบายการเกิดสีน้ำตาลจำเพาะกับ amine",
        "สภาวะทดสอบเป็นความร้อน/ความชื้น ไม่ใช่แสง และ lactose ไม่ใช่ตัวที่ photodegrade",
      ],
      k: "Primary/secondary amine + lactose (reducing sugar) → Maillard browning; ใช้ MCC/DCP/mannitol แทน",
      d: "hard",
      ref: "Rowe RC et al., Handbook of Pharmaceutical Excipients 9th ed. (Lactose monograph); Narang AS et al., J Pharm Sci 2012 (excipient reactivity)",
    },
  ],
  // Mock Set 2
  [
    {
      t: "Salt form selection from screening data",
      p: "ยา H เป็น weak base ที่ free base ละลายน้ำได้เพียง 0.005 mg/mL ทีม preformulation ต้องการเกลือที่มี solubility ≥ 1 mg/mL เพื่อพัฒนาเป็นยาเม็ด ผล salt screening เป็นดังนี้ เกลือใดเหมาะสมที่สุดในการพัฒนาต่อ",
      o: [
        "Mesylate: solubility 12 mg/mL, crystalline รูปเดียว, น้ำหนักเพิ่ม 0.8% ที่ 80% RH",
        "Hydrochloride: solubility 25 mg/mL, deliquescent ที่ 60% RH, พบ 3 polymorphs",
        "Phosphate: solubility 4 mg/mL, ได้เป็น amorphous, น้ำหนักเพิ่ม 12% ที่ 80% RH",
        "Tartrate: solubility 2 mg/mL, เปลี่ยนไปมาระหว่าง hydrate/anhydrate ที่ 40–60% RH",
        "Free base: solubility 0.005 mg/mL, crystalline, ไม่ดูดความชื้น",
      ],
      a: 0,
      r: "Salt selection ไม่ได้เลือกเกลือที่ละลายได้มากที่สุดเสมอไป แต่ต้องชั่งน้ำหนักหลายคุณสมบัติ: solubility/dissolution เพียงพอต่อขนาดยา, crystallinity, hygroscopicity ต่ำ, polymorphic/hydrate form ที่คงตัว, melting point เหมาะสม และความเป็นไปได้ในการผลิต\n\nMesylate ผ่านเกณฑ์ solubility (12 > 1 mg/mL) เป็นผลึกรูปเดียว และดูดความชื้นเพียง 0.8% (slightly hygroscopic) จึงผลิตและควบคุมคุณภาพได้ง่ายที่สุด\n\nHCl แม้ละลายดีที่สุด แต่ deliquescent ที่ 60% RH ทำให้ผลิตยากมาก และมีหลาย polymorphs เสี่ยง form change; amorphous phosphate ไม่คงตัวทางกายภาพ; tartrate เปลี่ยน hydrate state ในช่วง RH ที่พบในการผลิตและเก็บรักษาจริง",
      w: [
        "ถูก — solubility เพียงพอ ผลึกรูปเดียว และดูดความชื้นต่ำ สมดุลที่สุดสำหรับการพัฒนา",
        "Solubility สูงสุดแต่ deliquescent ที่ 60% RH และมีหลาย polymorphs ผลิตและเก็บรักษาลำบาก",
        "Amorphous และดูดความชื้นสูง (hygroscopic) เสี่ยง recrystallization และปัญหาความคงตัวทางกายภาพ",
        "การเปลี่ยน hydrate/anhydrate ในช่วง RH ปกติทำให้ solid form ไม่คงที่ระหว่างผลิตและเก็บ",
        "Solubility ต่ำกว่าเป้าหมาย 200 เท่า จึงไม่บรรลุวัตถุประสงค์ของการทำเกลือ",
      ],
      k: "เลือกเกลือจากภาพรวม: solubility พอ + crystalline รูปเดียว + hygroscopicity ต่ำ ไม่ใช่เลือกจาก solubility สูงสุดอย่างเดียว",
      d: "medium",
      ref: "Stahl & Wermuth, Handbook of Pharmaceutical Salts 2nd ed.; Morris KR et al., Int J Pharm 1994 (tiered salt selection)",
    },
    {
      t: "logD calculation for weak acid at pH 7.4",
      p: "ยา J เป็น weak acid มี logP (ของรูป unionized) 3.2 และ pKa 4.2 ค่า logD ที่ pH 7.4 (สมมติว่ารูป ionized ไม่ partition เข้า octanol) มีค่าประมาณเท่าใด",
      o: ["≈ 0.0", "1.6", "2.9", "3.2", "6.4"],
      a: 0,
      r: "Distribution coefficient (D) คือ partition ของยาทุกรูป (ionized + unionized) ระหว่าง octanol กับน้ำที่ pH หนึ่ง สำหรับ weak acid: logD = logP − log(1 + 10^(pH − pKa))\n\npH − pKa = 7.4 − 4.2 = 3.2 → 10^3.2 ≈ 1585 → log(1586) ≈ 3.2 ดังนั้น logD ≈ 3.2 − 3.2 ≈ 0.0\n\nความหมาย: แม้ logP สูง แต่ที่ pH 7.4 ยาแตกตัวเกือบหมด ความชอบไขมันที่ปรากฏลดลงราว 1,600 เท่า ค่า logD จึงสะท้อนพฤติกรรมจริงในสภาวะทางสรีรวิทยาได้ดีกว่า logP",
      w: [
        "ถูก — logD = 3.2 − log(1 + 10^3.2) ≈ 3.2 − 3.2 ≈ 0.0",
        "1.6 เป็นการหารครึ่ง logP โดยไม่มีหลักการรองรับ",
        "2.9 คือค่าที่ pH = pKa (ลดลง log 2 ≈ 0.3) ไม่ใช่ที่ pH 7.4",
        "3.2 คือ logP ซึ่งใช้ได้เฉพาะเมื่อยาไม่แตกตัว",
        "6.4 เกิดจากบวกเทอม ionization แทนการลบ",
      ],
      k: "Weak acid: logD = logP − log(1 + 10^(pH − pKa)); weak base: logD = logP − log(1 + 10^(pKa − pH))",
      d: "hard",
      ref: "Avdeef A, Absorption and Drug Development 2nd ed.; Martin's Physical Pharmacy 7th ed., Ch.10",
      c: [
        "pH − pKa = 7.4 − 4.2 = 3.2",
        "1 + 10^3.2 = 1 + 1585 = 1586 → log 1586 ≈ 3.20",
        "logD = 3.2 − 3.2 ≈ 0.0",
      ],
    },
    {
      t: "Co-crystal versus salt by delta pKa",
      p: "ยา K มีหมู่ pyridine (pKa ของ conjugate acid ≈ 3.0) ตกผลึกร่วมกับ succinic acid (pKa₁ ≈ 4.2) ได้ผลึกใหม่ที่มี stoichiometry 2:1 และ PXRD ต่างจากสารตั้งต้นทั้งคู่ ข้อใดอธิบายผลึกนี้ได้ถูกต้องที่สุด",
      o: [
        "เป็น co-crystal เพราะ ΔpKa < 0 จึงไม่เกิด proton transfer องค์ประกอบยึดกันด้วย hydrogen bond ในสภาพ neutral",
        "เป็น salt เพราะ coformer เป็นกรดและยามีหมู่เบส",
        "เป็น solvate เพราะ succinic acid ทำหน้าที่เป็น solvent ใน crystal lattice",
        "เป็น physical mixture แบบ eutectic เพราะมีสององค์ประกอบ",
        "เป็น salt เพราะ ΔpKa > 3 ทำให้เกิด proton transfer สมบูรณ์",
      ],
      a: 0,
      r: "Co-crystal คือผลึกที่มี API และ coformer ที่เป็นของแข็งที่อุณหภูมิห้องอยู่ใน lattice เดียวกันในสภาพ neutral ยึดกันด้วย non-ionic interaction (เช่น hydrogen bond pyridine···COOH) ต่างจาก salt ที่ต้องมี proton transfer\n\nใช้ ΔpKa = pKa(base) − pKa(acid) ทำนาย: ΔpKa < 0 มักได้ co-crystal, > 3 มักได้ salt, ช่วง 0–3 เป็น continuum ต้องยืนยันด้วย single-crystal XRD หรือ solid-state NMR/IR กรณีนี้ 3.0 − 4.2 = −1.2 จึงคาดว่าเป็น co-crystal\n\nUS FDA guidance (2018) จัด co-crystal คล้าย polymorph ของ API (ไม่ใช่ API ใหม่) หาก API และ coformer แยกจากกันได้ก่อนถึงตำแหน่งออกฤทธิ์ ประโยชน์คือเพิ่ม solubility/dissolution หรือความคงตัวให้ยาที่ไม่มีหมู่ ionizable พอจะทำเกลือ",
      w: [
        "ถูก — ΔpKa = −1.2 ไม่เกิด proton transfer จึงเป็น co-crystal ที่ยึดกันด้วย hydrogen bond",
        "การมีกรดและเบสไม่พอ ต้องมี ΔpKa มากพอให้เกิด proton transfer จึงเป็นเกลือ",
        "Solvate ต้องมี solvent (ของเหลวที่อุณหภูมิห้อง) ใน lattice ส่วน coformer ใน co-crystal เป็นของแข็ง",
        "Eutectic mixture ไม่ให้ PXRD pattern ใหม่ แต่เป็นผลรวมของ pattern สององค์ประกอบ",
        "ΔpKa จริงติดลบ (−1.2) ไม่ใช่ > 3",
      ],
      k: "ΔpKa < 0 → co-crystal (neutral, H-bond); > 3 → salt; 0–3 ต้องพิสูจน์ตำแหน่ง proton",
      d: "medium",
      ref: "US FDA Guidance for Industry: Regulatory Classification of Pharmaceutical Co-Crystals (2018); Childs SL et al., Mol Pharm 2007",
    },
    {
      t: "Water plasticization lowering Tg of amorphous drug",
      p: "Amorphous solid dispersion ของยา L มี Tg (สภาวะแห้ง) 85 °C ข้อมูล DVS พบว่าที่ 75% RH ดูดน้ำ 8% w/w และ Tg ลดลงเหลือประมาณ 35 °C หลังเก็บใน open dish ที่ 40 °C/75% RH 2 สัปดาห์ PXRD พบ Bragg peaks ของผลึกยา คำอธิบายและแนวทางป้องกันใดเหมาะสมที่สุด",
      o: [
        "น้ำทำหน้าที่ plasticizer ลด Tg ต่ำกว่าอุณหภูมิเก็บ โมเลกุลเคลื่อนที่ได้มากจึงตกผลึก ควรป้องกันความชื้นและเก็บที่อุณหภูมิต่ำกว่า Tg อย่างน้อยราว 50 °C",
        "ความร้อน 40 °C สูงกว่า Tg แห้งจึงตกผลึก ควรเพิ่ม drug loading เพื่อให้ Tg สูงขึ้น",
        "น้ำทำให้ Tg สูงขึ้นจนเกิด phase separation ควรเติมน้ำเพื่อคงสภาพ amorphous",
        "เป็นการเปลี่ยนเป็น polymorph ที่ไม่เสถียร ควรเก็บที่ RH สูงเพื่อให้กลับเป็น amorphous",
        "Tg ไม่เกี่ยวกับการตกผลึก ปัญหามาจาก particle size ที่เล็กเกินไป",
      ],
      a: 0,
      r: "Glass transition temperature (Tg) เป็นจุดที่ amorphous solid เปลี่ยนจาก glassy (mobility ต่ำ) เป็น rubbery (mobility สูง) น้ำมี Tg ต่ำมาก (≈ −135 °C) เมื่อถูกดูดซับจึงทำหน้าที่ plasticizer ลด Tg ของระบบตามสมการ Gordon–Taylor\n\nเมื่อ Tg ลดเหลือ 35 °C ซึ่งต่ำกว่าอุณหภูมิเก็บ 40 °C ระบบอยู่ในสภาพ rubbery โมเลกุลเคลื่อนที่ได้มาก จึง nucleate และตกผลึก (Bragg peaks ใน PXRD)\n\nกฎทั่วไป (Hancock 1995): เก็บที่อุณหภูมิต่ำกว่า Tg ประมาณ 50 °C molecular mobility จะต่ำพอสำหรับความคงตัวทางกายภาพระยะยาว ร่วมกับบรรจุภัณฑ์กันชื้น/desiccant และเลือก polymer ที่มี Tg สูงและดูดน้ำน้อย",
      w: [
        "ถูก — water plasticization ลด Tg ต่ำกว่าอุณหภูมิเก็บ ทำให้ตกผลึก; ป้องกันความชื้นและเก็บที่ ≤ Tg − 50 °C",
        "40 °C ยังต่ำกว่า Tg แห้ง (85 °C) และการเพิ่ม drug loading มักลด Tg และเพิ่มแนวโน้มตกผลึก",
        "น้ำลด Tg ไม่ได้เพิ่ม และการเติมน้ำยิ่งเร่งการตกผลึก",
        "Bragg peaks บ่งชี้การตกผลึก การเก็บที่ RH สูงยิ่งเร่ง ไม่ทำให้กลับเป็น amorphous",
        "Tg เป็นตัวกำหนดหลักของ molecular mobility และการตกผลึกของ amorphous",
      ],
      k: "น้ำเป็น plasticizer ลด Tg ของ amorphous; เก็บต่ำกว่า Tg ≥ 50 °C และกันชื้นเพื่อป้องกัน recrystallization",
      d: "hard",
      ref: "Hancock BC, Zografi G. J Pharm Sci 1997; Hancock BC et al., Pharm Res 1995 (molecular mobility below Tg)",
    },
    {
      t: "Hydrate versus anhydrate aqueous solubility",
      p: "ทดสอบ dissolution ของ theophylline anhydrous ในน้ำที่ 25 °C พบความเข้มข้นขึ้นสูงในช่วงแรกแล้วลดลงมาคงที่ที่ค่าต่ำกว่า เมื่อเก็บตะกอนมาวิเคราะห์พบว่าเป็น monohydrate ข้อใดอธิบายปรากฏการณ์นี้ได้ถูกต้องที่สุด",
      o: [
        "ในน้ำ hydrate เป็นรูปที่เสถียรทาง thermodynamics และมี solubility ต่ำกว่า anhydrate จึงเกิด solution-mediated transformation และตกตะกอนเป็น hydrate",
        "Hydrate มี solubility สูงกว่า anhydrate จึงทำให้ความเข้มข้นสูงในช่วงแรก",
        "Anhydrate เกิด chemical degradation ในน้ำ จึงทำให้ความเข้มข้นลดลง",
        "ความเข้มข้นที่ลดลงเกิดจากยาดูดซับบนผนังภาชนะ ไม่เกี่ยวกับ solid form",
        "Monohydrate เกิดจากการดูดความชื้นในอากาศหลังกรองตะกอน จึงไม่มีความหมาย",
      ],
      a: 0,
      r: "ในตัวกลางที่มี water activity สูง hydrate มักเป็นรูปที่มี free energy ต่ำกว่า จึงละลายได้น้อยกว่า anhydrate (anhydrate เป็น metastable ในน้ำ)\n\nเมื่อ anhydrate ละลาย ความเข้มข้นจะขึ้นสูงกว่า solubility ของ hydrate (supersaturated เทียบกับ hydrate) จากนั้น hydrate จะ nucleate และตกผลึก ความเข้มข้นจึงลดลงมาคงที่ที่ solubility ของ hydrate เรียกว่า solution-mediated phase transformation ตัวอย่างคลาสสิกคือ theophylline, carbamazepine\n\nผลต่อการพัฒนา: dissolution rate ของรูป anhydrate อาจไม่คงที่ และการ wet granulation อาจเปลี่ยน anhydrate เป็น hydrate ได้",
      w: [
        "ถูก — hydrate เสถียรกว่าในน้ำ solubility ต่ำกว่า จึงเกิด solution-mediated transformation",
        "กลับกัน: ในน้ำ hydrate โดยทั่วไปละลายได้น้อยกว่า anhydrate",
        "Theophylline ไม่สลายทางเคมีอย่างรวดเร็วในน้ำ และตะกอนที่พบคือ hydrate ของตัวยาเอง",
        "Adsorption ไม่อธิบายการพบ monohydrate ในตะกอน",
        "Hydrate formation เกิดใน slurry จริง สอดคล้องกับ profile ความเข้มข้นที่ลดลง",
      ],
      k: "ในน้ำ hydrate มัก solubility ต่ำกว่า anhydrate; anhydrate อาจเปลี่ยนเป็น hydrate ระหว่าง dissolution/wet granulation",
      d: "medium",
      ref: "Brittain HG, Polymorphism in Pharmaceutical Solids 2nd ed.; Shefter E, Higuchi T. J Pharm Sci 1963",
    },
    {
      t: "Specific surface area from particle diameter",
      p: "ยา M หลัง micronization มีอนุภาคใกล้ทรงกลมขนาดเส้นผ่านศูนย์กลางเฉลี่ย 4 µm และ true density 1.5 g/cm³ ค่า specific surface area (ต่อหน่วยมวล) โดยประมาณคือข้อใด",
      o: ["0.10 m²/g", "0.17 m²/g", "1.0 m²/g", "2.0 m²/g", "10 m²/g"],
      a: 2,
      r: "สำหรับอนุภาคทรงกลมขนาด d: specific surface area ต่อหน่วยมวล Sw = พื้นที่ผิว/มวล = πd²/(ρπd³/6) = 6/(ρd)\n\nแปลงหน่วย d = 4 µm = 4 × 10⁻⁴ cm → Sw = 6/(1.5 × 4 × 10⁻⁴) = 10,000 cm²/g = 1.0 m²/g (1 m² = 10⁴ cm²)\n\nSw แปรผกผันกับ d จึงเป็นเหตุผลที่ micronization เพิ่ม dissolution rate ในทางปฏิบัติวัดจริงด้วย BET gas adsorption ซึ่งรวมพื้นที่ผิวของรูพรุนและความขรุขระ จึงมักได้ค่าสูงกว่าค่าที่คำนวณจากทรงกลม",
      w: [
        "0.10 m²/g เกิดจากแปลงหน่วย cm² → m² ผิดสิบเท่า",
        "0.17 m²/g ลืมตัวเลข 6 ในสูตร (ใช้ 1/(ρd))",
        "ถูก — Sw = 6/(1.5 × 4×10⁻⁴ cm) = 10,000 cm²/g = 1.0 m²/g",
        "2.0 m²/g ใช้รัศมี 2 µm แทนเส้นผ่านศูนย์กลาง",
        "10 m²/g แปลงหน่วย µm → cm ผิดสิบเท่า",
      ],
      k: "ทรงกลม: Sw = 6/(ρ·d); ลด d ลงครึ่งหนึ่ง Sw เพิ่ม 2 เท่า",
      d: "medium",
      ref: "Martin's Physical Pharmacy and Pharmaceutical Sciences 7th ed., Ch.18 Micromeritics",
      c: [
        "d = 4 µm = 4 × 10⁻⁴ cm",
        "Sw = 6/(ρd) = 6/(1.5 × 4 × 10⁻⁴) = 10,000 cm²/g",
        "10,000 cm²/g ÷ 10⁴ = 1.0 m²/g",
      ],
    },
    {
      t: "USP descriptive solubility terms",
      p: "ในการทดสอบ solubility เบื้องต้นของ API ใหม่ พบว่าตัวยา 1 g ละลายหมดในน้ำ 250 mL ที่ 25 °C ตามคำศัพท์ descriptive solubility ของ USP ควรรายงานว่าอย่างไร",
      o: ["Slightly soluble", "Sparingly soluble", "Very slightly soluble", "Soluble", "Practically insoluble"],
      a: 0,
      r: "USP กำหนดคำบรรยาย solubility จากจำนวน parts ของตัวทำละลายที่ใช้ละลายตัวถูกละลาย 1 part: very soluble < 1; freely soluble 1–10; soluble 10–30; sparingly soluble 30–100; slightly soluble 100–1,000; very slightly soluble 1,000–10,000; practically insoluble ≥ 10,000\n\n1 g ใน 250 mL = 250 parts จึงอยู่ในช่วง 100–1,000 = slightly soluble (เทียบเท่าประมาณ 1–10 mg/mL)\n\nคำศัพท์เหล่านี้ใช้ใน monograph และเป็นข้อมูลแรกที่ใช้คาดการณ์ว่าอาจมีปัญหา dissolution",
      w: [
        "ถูก — 250 parts อยู่ในช่วง 100–1,000 parts = slightly soluble",
        "Sparingly soluble คือ 30–100 parts (ละลายได้ดีกว่ากรณีนี้)",
        "Very slightly soluble คือ 1,000–10,000 parts ต้องใช้น้ำมากกว่านี้",
        "Soluble คือ 10–30 parts",
        "Practically insoluble ต้องใช้ ≥ 10,000 parts",
      ],
      k: "USP: sparingly 30–100, slightly 100–1,000, very slightly 1,000–10,000 parts solvent ต่อ 1 part solute",
      d: "easy",
      ref: "USP General Notices 5.30 Description and Solubility; USP Reference Tables: Description and Relative Solubility",
    },
    {
      t: "Fick's first law membrane permeation amount",
      p: "การทดลอง permeation ผ่าน membrane ใน Franz diffusion cell ใช้ membrane หนา 100 µm พื้นที่ 2 cm² ยามี D ใน membrane 2 × 10⁻⁷ cm²/s, partition coefficient (membrane/donor) K = 5, ความเข้มข้นใน donor 10 mg/mL (คงที่) และ receptor อยู่ใน sink condition ปริมาณยาที่ผ่าน membrane ใน 1 ชั่วโมงที่ steady state เท่ากับเท่าใด",
      o: ["0.72 mg", "1.44 mg", "7.2 mg", "36 mg", "72 mg"],
      a: 2,
      r: "Fick's first law ที่ steady state: J = D·K·ΔC/h โดย K แปลงความเข้มข้นใน donor เป็นความเข้มข้นที่ผิว membrane และ sink condition ทำให้ ΔC ≈ C donor\n\nh = 100 µm = 0.01 cm → J = (2 × 10⁻⁷ × 5 × 10)/0.01 = 1 × 10⁻³ mg/cm²/s\n\nปริมาณ = J × A × t = 1 × 10⁻³ × 2 × 3,600 = 7.2 mg\n\nPermeability coefficient P = DK/h = 1 × 10⁻⁴ cm/s; ฟลักซ์เพิ่มได้โดยเพิ่ม K (ความชอบ membrane), เพิ่ม C donor (สูงสุดที่ saturation) หรือลดความหนา h",
      w: [
        "0.72 mg ลืมทั้ง K และพื้นที่ (คิดผิดหลายจุด)",
        "1.44 mg ลืมคูณ partition coefficient K = 5",
        "ถูก — J = DKC/h = 1×10⁻³ mg/cm²/s × 2 cm² × 3,600 s = 7.2 mg",
        "36 mg คูณ K ซ้ำสองครั้ง",
        "72 mg แปลงความหนา 100 µm เป็น 0.001 cm ผิด",
      ],
      k: "Fick's first law: J = DKΔC/h; ปริมาณ = J·A·t (ระวังแปลง µm → cm และ h → s)",
      d: "medium",
      ref: "Martin's Physical Pharmacy and Pharmaceutical Sciences 7th ed., Ch.11 Diffusion",
      c: [
        "h = 100 µm = 0.01 cm; ΔC = 10 mg/mL (sink)",
        "J = (2×10⁻⁷ × 5 × 10)/0.01 = 1×10⁻³ mg·cm⁻²·s⁻¹",
        "Q = J × A × t = 1×10⁻³ × 2 × 3,600 = 7.2 mg",
      ],
    },
    {
      t: "Cyclodextrin AL phase-solubility binding constant",
      p: "ศึกษา phase-solubility ของยา N กับ hydroxypropyl-β-cyclodextrin ตามวิธีของ Higuchi–Connors ได้กราฟชนิด AL (เส้นตรง) มี intercept (S₀) 0.40 mM และ slope 0.20 ค่า stability constant K₁:₁ ของ inclusion complex เท่ากับเท่าใด",
      o: ["0.0016 M⁻¹", "500 M⁻¹", "625 M⁻¹", "2,000 M⁻¹", "2,500 M⁻¹"],
      a: 2,
      r: "กราฟ AL ที่ slope < 1 บ่งชี้ inclusion complex แบบ 1:1 ที่ละลายน้ำได้ Higuchi–Connors: K₁:₁ = slope/[S₀(1 − slope)] โดย S₀ ต้องใช้หน่วย M\n\nS₀ = 0.40 mM = 4.0 × 10⁻⁴ M → K = 0.20/(4.0 × 10⁻⁴ × 0.80) = 0.20/3.2 × 10⁻⁴ = 625 M⁻¹\n\nค่า K ของยาส่วนใหญ่กับ cyclodextrin อยู่ในช่วงประมาณ 50–5,000 M⁻¹; slope ที่ใกล้ 1 หรือกราฟแบบ AP บ่งชี้ complex ลำดับสูงกว่า ส่วนแบบ B (BS, BI) บ่งชี้ complex ที่ละลายได้จำกัด\n\nนอกจากนี้ complexation efficiency (CE) = slope/(1 − slope) = 0.25 ใช้เปรียบเทียบ cyclodextrin ต่างชนิดได้ดีกว่า K เมื่อ S₀ วัดไม่แม่น",
      w: [
        "0.0016 M⁻¹ เป็นการกลับเศษส่วนของสูตร",
        "500 M⁻¹ ลืมเทอม (1 − slope)",
        "ถูก — K = 0.20/(4.0×10⁻⁴ × 0.80) = 625 M⁻¹",
        "2,000 M⁻¹ ใช้ (1 − slope)/S₀ ไม่ใช่สูตรที่ถูกต้อง",
        "2,500 M⁻¹ คือ 1/S₀ โดยไม่นำ slope มาคิด",
      ],
      k: "AL plot: K₁:₁ = slope/[S₀(1 − slope)] (S₀ ในหน่วย M); slope < 1 → complex 1:1",
      d: "hard",
      ref: "Higuchi T, Connors KA. Adv Anal Chem Instrum 1965; Loftsson T, Brewster ME. J Pharm Pharmacol 2010",
      c: [
        "S₀ = 0.40 mM = 4.0 × 10⁻⁴ M; 1 − slope = 0.80",
        "S₀(1 − slope) = 4.0 × 10⁻⁴ × 0.80 = 3.2 × 10⁻⁴",
        "K₁:₁ = 0.20/3.2 × 10⁻⁴ = 625 M⁻¹",
      ],
    },
    {
      t: "Bingham plastic yield value",
      p: "rheogram ของ flocculated suspension ที่มีของแข็งสูงชนิดหนึ่งเป็นเส้นตรงเมื่อ shear stress สูงพอ แต่เมื่อลากเส้นตรงลงมาจะตัดแกน shear stress ที่ค่าบวก (ไม่ผ่านจุดกำเนิด) ข้อใดอธิบายได้ถูกต้องที่สุด",
      o: [
        "เป็น plastic (Bingham) flow ค่าที่ตัดแกน shear stress คือ yield value ต้องให้แรงเกินค่านี้ระบบจึงเริ่มไหล",
        "เป็น Newtonian flow ค่าที่ตัดแกนคือ viscosity",
        "เป็น pseudoplastic flow ค่าที่ตัดแกนคือ consistency index",
        "เป็น dilatant flow ค่าที่ตัดแกนคือ critical shear rate",
        "เป็น thixotropic flow ค่าที่ตัดแกนคือพื้นที่ hysteresis loop",
      ],
      a: 0,
      r: "Plastic (Bingham) flow: ระบบมีโครงสร้าง (เช่น flocs ที่เชื่อมต่อกันใน concentrated flocculated suspension) ต้องใช้แรงจำนวนหนึ่ง คือ yield value (f) ทำลายโครงสร้างก่อนจึงจะไหล หลังจากนั้นความสัมพันธ์เป็นเส้นตรง\n\nสมการ: U = (F − f)/G โดย U = plastic viscosity (slope ของส่วนเส้นตรง), F = shear stress, G = shear rate\n\nYield value มีประโยชน์ในผลิตภัณฑ์ที่ต้องการไม่ให้ไหลหรือตกตะกอนขณะตั้งไว้ แต่กระจายหรือบีบออกได้เมื่อให้แรงเกิน yield value",
      w: [
        "ถูก — rheogram เส้นตรงที่ตัดแกน shear stress คือ Bingham plastic; intercept = yield value",
        "Newtonian ต้องเป็นเส้นตรงผ่านจุดกำเนิด และ viscosity คือส่วนกลับของ slope (ไม่ใช่ intercept)",
        "Pseudoplastic เป็นเส้นโค้งผ่านจุดกำเนิด ไม่มี yield value",
        "Dilatant เป็นเส้นโค้งผ่านจุดกำเนิดและหนืดขึ้นเมื่อ shear rate เพิ่ม",
        "Thixotropy ดูจาก hysteresis ของ up/down curve ไม่ใช่จาก intercept",
      ],
      k: "Bingham plastic: เส้นตรงที่มี yield value (intercept บนแกน shear stress); U = (F − f)/G",
      d: "easy",
      ref: "Martin's Physical Pharmacy and Pharmaceutical Sciences 7th ed., Ch.19 Rheology",
    },
  ],
  // Mock Set 3
  [
    {
      t: "Colligative property depends on particle number",
      p: "สารละลายในน้ำต่อไปนี้มี molality ตามที่ระบุ สารละลายใดน่าจะมีจุดเยือกแข็งต่ำที่สุด (freezing point depression มากที่สุด)",
      o: [
        "Calcium chloride 0.10 m",
        "Glucose 0.15 m",
        "Sodium chloride 0.10 m",
        "Urea 0.20 m",
        "Sucrose 0.18 m",
      ],
      a: 0,
      r: "Colligative properties (freezing point depression, boiling point elevation, vapor pressure lowering, osmotic pressure) ขึ้นกับจำนวนอนุภาคของตัวถูกละลาย ไม่ขึ้นกับชนิดของอนุภาค: ΔTf = i·Kf·m โดย i คือ van't Hoff factor\n\nเทียบ i·m: CaCl₂ แตกตัวได้ 3 อนุภาค (i จริง ≈ 2.6) → ≈ 0.26; NaCl i ≈ 1.9 → ≈ 0.19; urea, glucose, sucrose เป็น nonelectrolyte (i = 1) → 0.20, 0.15, 0.18 ตามลำดับ\n\nดังนั้น CaCl₂ 0.10 m มีจำนวนอนุภาคมากที่สุดและ ΔTf มากที่สุด หลักนี้เป็นพื้นฐานของการคำนวณ isotonicity (เช่น วิธี freezing point depression และ NaCl equivalent)",
      w: [
        "ถูก — CaCl₂ ให้ 3 ไอออน effective particle ≈ 0.26 m สูงสุดในกลุ่ม",
        "Glucose ไม่แตกตัว อนุภาครวมเพียง 0.15 m",
        "NaCl ให้ 2 ไอออน (i ≈ 1.9) อนุภาครวม ≈ 0.19 m น้อยกว่า CaCl₂",
        "Urea ไม่แตกตัว อนุภาค 0.20 m ยังน้อยกว่า CaCl₂ (≈ 0.26 m)",
        "Sucrose ไม่แตกตัว อนุภาค 0.18 m",
      ],
      k: "Colligative property ∝ จำนวนอนุภาค (i × m) ไม่ขึ้นกับชนิดสาร; electrolyte ต้องคูณ van't Hoff factor",
      d: "easy",
      ref: "Martin's Physical Pharmacy and Pharmaceutical Sciences 7th ed., Ch.5 Nonelectrolytes & Ch.6 Electrolyte Solutions",
    },
    {
      t: "pHmax and salt disproportionation",
      p: "ยา P เป็น weak base มี pKa 6.5 intrinsic solubility ของ free base 0.01 mg/mL และ solubility ของ HCl salt (คิดเทียบเป็น base) 10 mg/mL ยาเม็ดที่ใช้ HCl salt ร่วมกับ excipient ที่เป็นด่างทำให้ microenvironmental pH ในเม็ดยาเปียกชื้นประมาณ 6 หลังเก็บพบ dissolution ช้าลง ข้อใดอธิบายได้ถูกต้องที่สุด",
      o: [
        "pHmax ≈ 3.5; microenvironmental pH สูงกว่า pHmax ทำให้เกลือ disproportionate เป็น free base ที่ละลายน้อย",
        "pHmax ≈ 9.5; เกลือจึงเสถียรที่ pH 6 ปัญหาน่าจะมาจาก tablet hardness",
        "pHmax เท่ากับ pKa (6.5) เสมอ ที่ pH 6 เกลือจึงยังเสถียร",
        "pHmax ≈ 3.5; ที่ pH สูงกว่า pHmax free base เปลี่ยนเป็นเกลือ dissolution จึงควรเร็วขึ้น",
        "pHmax ≈ 5.5; microenvironmental pH ต่ำกว่า pHmax จึงไม่มีการเปลี่ยน solid form",
      ],
      a: 0,
      r: "pHmax คือ pH ที่ทั้ง free base และ salt อิ่มตัวพร้อมกัน (solubility สูงสุด) สำหรับ weak base: pHmax = pKa + log(S₀/Ssalt)\n\nแทนค่า: pHmax = 6.5 + log(0.01/10) = 6.5 − 3 = 3.5\n\nเมื่อ pH ของ microenvironment > pHmax รูปที่เสถียรทาง thermodynamics คือ free base เกลือจึงแยกตัว (disproportionation) เป็น free base ที่ผิวเม็ด ทำให้ dissolution ช้าลง โดยเฉพาะเมื่อมีความชื้นและ excipient ที่เป็นด่าง (เช่น magnesium stearate, croscarmellose sodium, carbonate)\n\nแนวป้องกัน: เลือกเกลือที่ pHmax สูงกว่า (counterion/salt ที่ Ssalt ไม่สูงเกินไป), เติม acidifier, หลีกเลี่ยง excipient ด่าง และควบคุมความชื้น",
      w: [
        "ถูก — pHmax = 6.5 + log(0.001) = 3.5; pH 6 > pHmax จึงเกิด disproportionation เป็น free base",
        "ใช้เครื่องหมายผิด (บวก 3) และโยงไปที่ hardness ซึ่งไม่อธิบาย solid-form change",
        "pHmax ขึ้นกับอัตราส่วน S₀/Ssalt ด้วย จึงไม่เท่ากับ pKa",
        "คำนวณ pHmax ถูกแต่ทิศทางผิด เหนือ pHmax เกลือเปลี่ยนเป็น free base ไม่ใช่กลับกัน",
        "คำนวณ pHmax ผิด และ pH 6 ไม่ได้ต่ำกว่า pHmax ที่ถูกต้อง",
      ],
      k: "Weak base: pHmax = pKa + log(S₀/Ssalt); เหนือ pHmax เกลือ disproportionate เป็น free base",
      d: "hard",
      ref: "Serajuddin ATM. Adv Drug Deliv Rev 2007 (Salt formation to improve drug solubility); Merritt JM et al., Pharm Res 2013",
      c: [
        "S₀/Ssalt = 0.01/10 = 0.001 → log = −3",
        "pHmax = pKa + log(S₀/Ssalt) = 6.5 − 3 = 3.5",
        "Microenvironment pH 6 > 3.5 → free base เป็นรูปที่เสถียร → disproportionation",
      ],
    },
    {
      t: "Common-ion effect on hydrochloride salt solubility",
      p: "ยา Q ในรูป hydrochloride salt ละลายในน้ำบริสุทธิ์ได้ดี แต่ในการทดสอบ solubility ใน 0.1 N HCl กลับได้ค่าต่ำกว่าในน้ำอย่างชัดเจน (ทั้งที่ยาเป็น weak base ซึ่งควรละลายได้ดีในกรด) ปรากฏการณ์นี้อธิบายได้ดีที่สุดด้วยข้อใด",
      o: [
        "Common-ion effect: Cl⁻ จากตัวกลางทำให้ผลคูณ [BH⁺][Cl⁻] ถึง Ksp ที่ความเข้มข้นยาต่ำลง",
        "ยาแตกตัวน้อยลงในกรด จึงละลายลดลง",
        "เกลือเกิด disproportionation เป็น free base ใน 0.1 N HCl",
        "HCl ทำให้ยาเกิด hydrolysis จึงวัดได้น้อยลง",
        "Ionic strength สูงทำให้ยาเปลี่ยนเป็น polymorph ที่ละลายน้อย",
      ],
      a: 0,
      r: "Solubility ของเกลือ BH⁺Cl⁻ ในบริเวณที่ solid phase เป็นเกลือถูกควบคุมด้วย solubility product: Ksp = [BH⁺][Cl⁻] เมื่อมี Cl⁻ จากแหล่งอื่น (เช่น 0.1 N HCl หรือ NaCl) [BH⁺] ที่สมดุลต้องลดลงตาม เรียกว่า common-ion effect\n\nผลนี้เด่นสำหรับเกลือ HCl ที่มี Ksp ค่อนข้างต่ำ จึงอาจทำให้ dissolution ในกระเพาะอาหาร (มี Cl⁻ ≈ 0.1 M) ต่ำกว่าที่คาด\n\nทางเลือกคือใช้ counterion อื่น (เช่น mesylate, tosylate) ที่ไม่มี common ion ในทางเดินอาหาร หรือประเมิน solubility ในตัวกลางที่มี chloride ระหว่าง salt screening",
      w: [
        "ถูก — Cl⁻ จากตัวกลางกด solubility ของเกลือ HCl ตาม Ksp",
        "ในกรด weak base แตกตัวมากขึ้น ไม่ใช่น้อยลง",
        "Disproportionation เกิดเมื่อ pH สูงกว่า pHmax ไม่ใช่ใน 0.1 N HCl",
        "ไม่มีข้อมูลบ่งชี้ chemical degradation และ hydrolysis ไม่ได้ทำให้ solubility สมดุลต่ำลงเฉพาะในตัวกลางที่มี chloride",
        "ไม่มีหลักฐาน polymorphic change; ปรากฏการณ์อธิบายได้ด้วย Ksp โดยตรง",
      ],
      k: "เกลือ HCl อาจละลายน้อยลงในตัวกลางที่มี Cl⁻ (common-ion effect) — สำคัญในกระเพาะอาหาร",
      d: "medium",
      ref: "Bighley LD, Berge SM, Monkhouse DC. Encyclopedia of Pharmaceutical Technology (Salt forms of drugs); Serajuddin ATM. Adv Drug Deliv Rev 2007",
    },
    {
      t: "Ostwald's rule of stages in crystallization",
      p: "ระหว่างพัฒนากระบวนการตกผลึก API พบว่าเมื่อทำ crash cooling จะได้ Form II (metastable) ก่อนเสมอ แต่หากทิ้งไว้ใน mother liquor ต่ออีกหลายชั่วโมงจะเปลี่ยนเป็น Form I (stable) ปรากฏการณ์นี้สอดคล้องกับหลักการใดมากที่สุด",
      o: [
        "Ostwald's rule of stages: รูป metastable มักเกิดก่อนเพราะ nucleate ได้เร็วกว่า แล้วเปลี่ยนเป็นรูปที่เสถียรกว่าผ่าน solution-mediated transformation",
        "Ostwald ripening: ผลึกเล็กละลายแล้วไปเกาะผลึกใหญ่ของรูปเดิม",
        "Heat of transition rule: การเปลี่ยนรูปที่อุณหภูมิต่ำแสดงว่าเป็น monotropic",
        "Kelvin equation: ผลึกใหญ่มี vapor pressure สูงกว่า จึงเปลี่ยนรูป",
        "Le Chatelier principle: ความร้อนจากการตกผลึกเปลี่ยน Form II เป็น Form I",
      ],
      a: 0,
      r: "Ostwald's rule of stages ระบุว่าระบบที่ supersaturated สูงมักตกผลึกเป็นรูปที่ไม่เสถียรที่สุด (ใกล้สถานะ solution มากที่สุดในทางพลังงาน) ก่อน เพราะ kinetic barrier ของ nucleation ต่ำกว่า จากนั้นจึงเปลี่ยนเป็นรูปที่เสถียรกว่าตามลำดับ\n\nใน mother liquor Form II ซึ่ง solubility สูงกว่าจะละลาย ขณะที่ Form I ที่ solubility ต่ำกว่า nucleate และโต (solution-mediated transformation) จนเหลือ Form I ทั้งหมด\n\nนัยต่อการผลิต: ต้องควบคุม supersaturation, seeding ด้วยรูปที่ต้องการ, อุณหภูมิ และเวลา aging เพื่อให้ได้ polymorph ที่สม่ำเสมอทุก batch",
      w: [
        "ถูก — metastable เกิดก่อน (kinetic control) แล้วเปลี่ยนเป็น stable form (thermodynamic control)",
        "Ostwald ripening เป็นการโตของผลึกรูปเดิม ไม่ใช่การเปลี่ยน polymorph",
        "Heat of transition rule ใช้ตัดสิน enantiotropy/monotropy จากการเปลี่ยนรูปแบบ endo/exothermic ไม่ได้อธิบายลำดับการเกิด",
        "อนุภาคเล็กต่างหากที่มี vapor pressure/solubility สูงกว่า และไม่ได้อธิบายการเปลี่ยนรูปผลึก",
        "Le Chatelier ไม่ใช่หลักที่อธิบายลำดับการเกิด polymorph",
      ],
      k: "Ostwald's rule of stages: crash crystallization มักได้ metastable form ก่อน แล้วเปลี่ยนเป็น stable form เมื่อ aging ใน solvent",
      d: "medium",
      ref: "Bernstein J, Polymorphism in Molecular Crystals 2nd ed.; Hilfiker R, Polymorphism in the Pharmaceutical Industry",
    },
    {
      t: "PXRD halo versus Bragg peaks",
      p: "Spray-dried dispersion ของยา R วัด PXRD ทันทีหลังผลิตได้ broad halo ไม่มีพีคแหลม หลังเก็บที่ 40 °C/75% RH 3 เดือน พบพีคแหลมที่ตำแหน่ง 2θ ตรงกับผลึกยาบริสุทธิ์ ข้อสรุปใดถูกต้องที่สุด",
      o: [
        "เดิมยาอยู่ในรูป amorphous และเกิด recrystallization ระหว่างเก็บ",
        "เดิมยาเป็นผลึกขนาดใหญ่มาก จึงไม่เห็นพีค",
        "พีคแหลมที่เกิดขึ้นแสดงว่ายาถูก degrade ทางเคมี",
        "Broad halo แสดงว่ายาเป็น hydrate และพีคใหม่คือการสูญเสียน้ำ",
        "การเปลี่ยนแปลงเกิดจาก polymer เกิดผลึก ไม่เกี่ยวกับยา",
      ],
      a: 0,
      r: "PXRD ของสาร crystalline ให้ Bragg peaks แหลมที่ตำแหน่ง 2θ เฉพาะตาม d-spacing ของ lattice ส่วนสาร amorphous ไม่มี long-range order จึงให้ broad diffuse halo\n\nพีคที่เกิดใหม่ตรงกับ pattern ของผลึกยาบริสุทธิ์ จึงบ่งชี้ว่ายาตกผลึกกลับ (recrystallization) ซึ่งทำให้เสียข้อได้เปรียบด้าน solubility/dissolution ของ amorphous form\n\nPXRD ยังใช้แยก polymorph ต่างๆ (pattern ต่างกัน) และประมาณ % crystallinity ได้ แต่มี limit of detection ราว 1–5% จึงมักใช้ร่วมกับ DSC (Tg, recrystallization exotherm) และ polarized light microscopy",
      w: [
        "ถูก — halo = amorphous; Bragg peaks ที่ตรงกับผลึกยา = recrystallization",
        "ผลึกขนาดใหญ่ให้พีคคมชัด ไม่ใช่ halo; พีคจะกว้างขึ้นเมื่อผลึกเล็กระดับ nano",
        "PXRD บอก solid form ไม่ได้บอก chemical degradation และพีคตรงกับผลึกยาเดิม",
        "Hydrate ก็เป็นผลึกที่ให้ Bragg peaks ได้ ไม่ใช่ halo",
        "พีคตรงกับ pattern ของยา ไม่ใช่ของ polymer",
      ],
      k: "PXRD: crystalline = Bragg peaks แหลม; amorphous = broad halo; พีคใหม่ตรงกับ API = recrystallization",
      d: "easy",
      ref: "USP <941> Characterization of Crystalline and Partially Crystalline Solids by X-Ray Powder Diffraction (XRPD)",
    },
    {
      t: "TGA weight loss to hydrate stoichiometry",
      p: "ยา S ในรูป anhydrous มี MW 342 g/mol ผลึกตัวอย่างจาก batch ใหม่วัด TGA พบน้ำหนักลดลงขั้นเดียว 5.0% ในช่วง 80–120 °C ตรงกับ DSC endotherm ที่ช่วงเดียวกัน และ Karl Fischer ให้ปริมาณน้ำใกล้เคียงกัน ผลึกนี้น่าจะเป็นรูปใด",
      o: [
        "Monohydrate",
        "Hemihydrate",
        "Sesquihydrate",
        "Dihydrate",
        "Anhydrate ที่มีความชื้นผิว 5%",
      ],
      a: 0,
      r: "หาจำนวนโมลน้ำ n จาก % weight loss = 18n/(MW anhydrous + 18n) × 100\n\n0.050 = 18n/(342 + 18n) → 17.1 + 0.9n = 18n → 17.1n = 17.1 → n = 1.0 จึงเป็น monohydrate (MW hydrate = 360; 18/360 = 5.0%)\n\nการสูญเสียน้ำแบบขั้นเดียวที่ช่วงอุณหภูมิค่อนข้างแคบพร้อม DSC endotherm บ่งชี้น้ำที่อยู่ใน lattice (stoichiometric hydrate) ต่างจาก surface moisture ที่มักระเหยตั้งแต่อุณหภูมิต่ำแบบค่อยเป็นค่อยไป การยืนยันด้วย KF ช่วยแยกการสูญเสียน้ำจาก solvent อื่น",
      w: [
        "ถูก — n = 1.0 (18/360 = 5.0%)",
        "Hemihydrate (n = 0.5) จะสูญเสียน้ำ 9/351 ≈ 2.6%",
        "Sesquihydrate (n = 1.5) จะสูญเสีย 27/369 ≈ 7.3%",
        "Dihydrate (n = 2) จะสูญเสีย 36/378 ≈ 9.5%",
        "Surface moisture มักหายไปตั้งแต่อุณหภูมิต่ำแบบไม่เป็นขั้นชัด และไม่ให้ endotherm ที่ช่วงแคบตรงกับ stoichiometry",
      ],
      k: "% water = 18n/(MW + 18n); TGA step + DSC endotherm + KF ใช้ยืนยัน stoichiometric hydrate",
      d: "hard",
      ref: "USP <891> Thermal Analysis; Brittain HG, Polymorphism in Pharmaceutical Solids 2nd ed. (hydrates and solvates)",
      c: [
        "0.050 = 18n/(342 + 18n)",
        "0.050 × 342 + 0.050 × 18n = 18n → 17.1 = 18n − 0.9n = 17.1n",
        "n = 1.0 → monohydrate (18/360 = 5.0%)",
      ],
    },
    {
      t: "Log-linear cosolvency model",
      p: "ยา T มี aqueous solubility 0.02 mg/mL จากข้อมูลพบว่า cosolvent ชนิดหนึ่งมี solubilization power (σ) สำหรับยานี้เท่ากับ 4.0 ตาม log-linear model ของ Yalkowsky ถ้าใช้ระบบตัวทำละลายที่มี cosolvent 50% v/v (f = 0.5) solubility ของยาจะเป็นประมาณเท่าใด",
      o: ["0.04 mg/mL", "0.15 mg/mL", "2.0 mg/mL", "20 mg/mL", "200 mg/mL"],
      a: 2,
      r: "Log-linear cosolvency model: log Sm = log Sw + σ·f โดย Sm = solubility ในส่วนผสม, Sw = solubility ในน้ำ, f = volume fraction ของ cosolvent, σ = solubilization power (สัมพันธ์กับ logP ของยา; ยิ่งไม่ชอบน้ำ σ ยิ่งสูง)\n\nσ·f = 4.0 × 0.5 = 2 → Sm = Sw × 10² = 0.02 × 100 = 2.0 mg/mL\n\nสังเกตว่า solubility เพิ่มแบบ exponential กับ f ไม่ใช่เส้นตรง ข้อควรระวังของ cosolvent: อาจตกตะกอนเมื่อเจือจาง (เช่น ฉีดเข้าหลอดเลือดหรือผสมใน infusion) เพราะ solubility ลดลงแบบ log ขณะที่ความเข้มข้นยาลดแบบเส้นตรง",
      w: [
        "0.04 mg/mL คิดว่า solubility เพิ่มแบบเส้นตรง (คูณ 2) ไม่ใช่ log-linear",
        "0.15 mg/mL ใช้ natural log (e²) แทน log ฐาน 10",
        "ถูก — log Sm = log 0.02 + 2 → Sm = 0.02 × 10² = 2.0 mg/mL",
        "20 mg/mL ยกกำลังเกินไป 1 หน่วย (คิด σf = 3)",
        "200 mg/mL ลืมคูณ f (ใช้ σ = 4 ทั้งหมด)",
      ],
      k: "Cosolvency: log Sm = log Sw + σf — solubility เพิ่ม exponential กับสัดส่วน cosolvent และลดแบบ exponential เมื่อเจือจาง",
      d: "medium",
      ref: "Yalkowsky SH, Solubility and Solubilization in Aqueous Media (1999); Millard JW et al., Int J Pharm 2002",
      c: ["σ·f = 4.0 × 0.5 = 2.0", "log Sm = log Sw + 2 → Sm = Sw × 10²", "Sm = 0.02 × 100 = 2.0 mg/mL"],
    },
    {
      t: "Contact angle and wettability of powders",
      p: "ผงยา U มี contact angle กับน้ำ 120° เมื่อโรยลงบนผิวตัวกลาง dissolution ผงลอยเป็นแพและไม่จมตัว หากเติม polysorbate 80 ความเข้มข้นต่ำลงในตัวกลาง ผลที่คาดว่าจะเกิดขึ้นและเหตุผลข้อใดถูกต้องที่สุด",
      o: [
        "Contact angle ลดลงเพราะ surfactant ลด γLV และ γSL ตาม Young's equation ทำให้ผงเปียกและจมได้ดีขึ้น",
        "Contact angle เพิ่มขึ้นเพราะ surfactant เพิ่ม surface tension ของน้ำ",
        "Contact angle ไม่เปลี่ยน เพราะขึ้นกับผงยาเพียงอย่างเดียว",
        "ผงจะจมเพราะ surfactant เพิ่ม density ของตัวกลาง",
        "Contact angle ลดลงเพราะ surfactant เพิ่ม γSL",
      ],
      a: 0,
      r: "Young's equation: γSV = γSL + γLV cos θ → cos θ = (γSV − γSL)/γLV contact angle θ > 90° แสดงว่าเปียกน้ำได้ไม่ดี (hydrophobic) θ < 90° เปียกได้ และ θ = 0° เปียกได้สมบูรณ์\n\nSurfactant ดูดซับที่ผิวหน้า liquid–vapor และ solid–liquid ทำให้ γLV และ γSL ลดลง cos θ จึงมากขึ้น (θ ลดลง) ผงจึงเปียก อากาศที่ติดผิวถูกแทนที่ และจมลงไปละลายได้\n\nWettability ที่ไม่ดีทำให้พื้นที่ผิวที่สัมผัสตัวกลางจริงน้อยกว่าพื้นที่ผิวทางทฤษฎี บางครั้ง micronization ของยาที่ hydrophobic กลับทำให้ dissolution แย่ลงเพราะเกาะกลุ่มและลอย จึงมักต้องใช้ wetting agent ร่วมด้วย",
      w: [
        "ถูก — surfactant ลด γLV และ γSL → cos θ เพิ่ม → θ ลดลง ผงเปียกดีขึ้น",
        "Surfactant ลด surface tension ไม่ใช่เพิ่ม",
        "Contact angle ขึ้นกับแรงตึงผิวทั้งสามระหว่างของแข็ง ของเหลว และไอ ไม่ใช่ของแข็งอย่างเดียว",
        "Surfactant ความเข้มข้นต่ำแทบไม่เปลี่ยน density; กลไกคือการเปียก",
        "ถ้า γSL เพิ่ม cos θ จะลดลง (θ เพิ่ม) ตรงข้ามกับผลจริง",
      ],
      k: "θ > 90° = เปียกยาก; wetting agent ลด γLV และ γSL → θ ลดลง (Young: γSV = γSL + γLV cos θ)",
      d: "medium",
      ref: "Martin's Physical Pharmacy and Pharmaceutical Sciences 7th ed., Ch.15 Interfacial Phenomena",
    },
    {
      t: "Critical relative humidity of mixtures (Elder)",
      p: "ยา V (water-soluble crystalline salt) มี critical relative humidity (CRH) 80% และ excipient ที่ละลายน้ำได้ดีซึ่งจะผสมในสูตรมี CRH 75% ที่ 25 °C ห้องผลิตควบคุม RH ไว้ที่ 65% ข้อใดประเมินความเสี่ยงได้ถูกต้องที่สุด",
      o: [
        "CRH ของส่วนผสมประมาณ 60% ซึ่งต่ำกว่า RH ห้องผลิต จึงเสี่ยงดูดน้ำจน deliquescence/caking ควรลด RH ห้องผลิต",
        "CRH ของส่วนผสมเท่ากับค่าต่ำสุดของสองสาร (75%) จึงปลอดภัยที่ RH 65%",
        "CRH ของส่วนผสมเท่ากับค่าเฉลี่ย (77.5%) จึงปลอดภัยที่ RH 65%",
        "CRH ของส่วนผสมเท่ากับผลบวกของสองสาร (155%) จึงไม่มีทาง deliquesce",
        "CRH ใช้กับสารเดี่ยวเท่านั้น ไม่สามารถประเมินส่วนผสมได้",
      ],
      a: 0,
      r: "Critical relative humidity (CRH) คือ RH ที่สารผลึกที่ละลายน้ำได้เริ่มดูดน้ำอย่างมากจนละลายในน้ำที่ดูดเข้ามา (deliquescence) ซึ่งเท่ากับ water activity ของสารละลายอิ่มตัวของสารนั้น\n\nElder hypothesis: สำหรับส่วนผสมของสารที่ละลายน้ำได้และไม่ทำปฏิกิริยาต่อกัน CRH_AB ≈ CRH_A × CRH_B = 0.80 × 0.75 = 0.60 หรือ 60% RH ซึ่งต่ำกว่าแต่ละสาร\n\nRH ห้องผลิต 65% สูงกว่า CRH ของส่วนผสม จึงเสี่ยงดูดน้ำ จับก้อน ไหลไม่ดี และกระทบความคงตัว ควรลด RH ห้องผลิต/เก็บ และเลือกบรรจุภัณฑ์กันชื้น",
      w: [
        "ถูก — CRH_mix ≈ 0.80 × 0.75 = 60% < 65% RH ของห้อง จึงเสี่ยง",
        "CRH ของส่วนผสมต่ำกว่าค่าต่ำสุดของสารเดี่ยว ไม่ใช่เท่ากับค่าต่ำสุด",
        "ไม่ได้ใช้ค่าเฉลี่ย ส่วนผสมมี CRH ต่ำลงเสมอ",
        "การบวกค่า RH ไม่มีความหมายทางกายภาพ",
        "Elder hypothesis ใช้ประเมินส่วนผสมของสารที่ละลายน้ำได้โดยเฉพาะ",
      ],
      k: "Elder: CRH_mix ≈ CRH_A × CRH_B — ส่วนผสมดูดความชื้นที่ RH ต่ำกว่าสารเดี่ยว",
      d: "hard",
      ref: "Salameh AK, Taylor LS. J Pharm Sci 2005 (Deliquescence in binary mixtures); Carstensen JT, Pharmaceutical Preformulation",
      c: ["CRH_mix ≈ 0.80 × 0.75 = 0.60 → 60% RH", "RH ห้องผลิต 65% > 60% → เสี่ยง deliquescence"],
    },
    {
      t: "Dilatant flow of concentrated deflocculated dispersions",
      p: "ระหว่าง scale-up การผสม slurry ของผงที่มีอนุภาคละเอียด deflocculated ความเข้มข้นของแข็งประมาณ 55% w/w ในเครื่องผสมความเร็วสูง พบว่าเมื่อเพิ่มความเร็วใบกวน slurry กลับหนืดขึ้นจนเครื่องติดขัด พฤติกรรมนี้คือข้อใดและเกิดจากอะไร",
      o: [
        "Dilatant flow: อนุภาคที่อัดแน่นเมื่อถูก shear จะขยายตัวเป็น open packing น้ำไม่พอเคลือบอนุภาค ความหนืดจึงเพิ่ม",
        "Pseudoplastic flow: polymer chains จัดเรียงตัวตามทิศการไหล ความหนืดจึงเพิ่ม",
        "Thixotropy: โครงสร้าง gel ถูกทำลายเมื่อกวน ความหนืดจึงเพิ่ม",
        "Plastic flow: เกิดเพราะ shear stress ยังไม่ถึง yield value",
        "Newtonian flow: ความหนืดเพิ่มเพราะอุณหภูมิจากการกวนสูงขึ้น",
      ],
      a: 0,
      r: "Dilatant (shear-thickening) flow พบในระบบที่มีของแข็งความเข้มข้นสูง (มัก ≥ ~50%) อนุภาคเล็กและ deflocculated ขณะพักอนุภาคจัดเรียงแบบ close-packed ที่ช่องว่างน้อย น้ำเพียงพอจะหล่อลื่น\n\nเมื่อได้รับ shear สูง อนุภาคต้องเลื่อนผ่านกันและเปลี่ยนเป็น open packing (dilate) ปริมาตรช่องว่างเพิ่ม น้ำไม่พอเติมเต็ม ความหนืดจึงเพิ่มขึ้นมาก หรือแข็งเหมือนของแข็ง\n\nนัยในการผลิต: ระวังเครื่องผสม/บด/ปั๊มติดขัดหรือเสียหาย ควรลดความเร็วหรือปรับสัดส่วนของแข็ง",
      w: [
        "ถูก — dilatant: shear ทำให้อนุภาคเปลี่ยนเป็น open packing น้ำไม่พอ viscosity เพิ่ม",
        "Pseudoplastic ความหนืดลดลงเมื่อ shear เพิ่ม ไม่ใช่เพิ่ม",
        "Thixotropy ความหนืดลดลงเมื่อกวนแล้วค่อยกลับคืน ไม่ใช่หนืดขึ้น",
        "Plastic flow คือยังไม่ไหลจนเกิน yield value ไม่ได้อธิบายการหนืดขึ้นเมื่อเร่งความเร็ว",
        "อุณหภูมิสูงขึ้นมักทำให้ความหนืดลดลง และ Newtonian ไม่ขึ้นกับ shear rate",
      ],
      k: "Dilatant: ของแข็งเข้มข้นสูง deflocculated → หนืดขึ้นเมื่อ shear เพิ่ม; ระวังเครื่องติดขัดตอนผสม/บด",
      d: "medium",
      ref: "Martin's Physical Pharmacy and Pharmaceutical Sciences 7th ed., Ch.19 Rheology",
    },
  ],
];
