import type { Ip1MockDomainContent } from "@/lib/ip1-mock/types";

// หมวด Preformulation และเภสัชกรรมเชิงฟิสิกส์ (Physical pharmacy)
export const PREFORM: Ip1MockDomainContent = [
  // Mock Set 1
  [
    {
      t: "Henderson-Hasselbalch percent ionized of weak acid",
      p: "ยา A เป็น weak acid มี pKa 3.4 นักวิจัย preformulation ต้องการประเมินสัดส่วนการแตกตัวของยาในบัฟเฟอร์ pH 5.4 ที่ใช้ทดสอบ solubility ร้อยละของยาที่อยู่ในรูป ionized มีค่าประมาณเท่าใด",
      o: ["1.0%", "9.1%", "50%", "90.9%", "99.0%"],
      a: 4,
      r: "สำหรับ weak acid สมการ Henderson–Hasselbalch คือ pH = pKa + log([A⁻]/[HA]) ดังนั้น log([A⁻]/[HA]) = 5.4 − 3.4 = 2 หรือ [A⁻]/[HA] = 100\n\nสัดส่วน ionized = 100/(100+1) = 0.990 หรือ 99.0% กล่าวคือเมื่อ pH สูงกว่า pKa ของกรด 2 หน่วย ยาแตกตัวเกือบทั้งหมด\n\nวิธีจำเร็ว: ทุก 1 หน่วย pH ที่ห่างจาก pKa สัดส่วนเปลี่ยน 10 เท่า (1 หน่วย ≈ 91%, 2 หน่วย ≈ 99%, 3 หน่วย ≈ 99.9%) ทิศทางขึ้นกับว่าเป็นกรดหรือเบส: กรดแตกตัวมากเมื่อ pH > pKa",
      w: [
        "1.0% คือสัดส่วน unionized ไม่ใช่ ionized (เป็นการกลับทิศของกรดกับเบส)",
        "9.1% ได้จากการคิดว่าห่างเพียง 1 หน่วยและกลับทิศ ไม่ตรงกับ ΔpH = 2",
        "50% เกิดเฉพาะเมื่อ pH = pKa เท่านั้น",
        "90.9% คือกรณี pH − pKa = 1 หน่วย แต่โจทย์ห่าง 2 หน่วย",
        "ถูก — [A⁻]/[HA] = 10² = 100 จึง ionized = 100/101 ≈ 99.0%",
      ],
      k: "Weak acid: % ionized = 100/(1+10^(pKa−pH)); pH สูงกว่า pKa 2 หน่วย → ionized ≈ 99%",
      d: "easy",
      ref: "Martin's Physical Pharmacy and Pharmaceutical Sciences 7th ed., Ch.8 Buffered and Isotonic Solutions",
      c: [
        "log([A⁻]/[HA]) = pH − pKa = 5.4 − 3.4 = 2",
        "[A⁻]/[HA] = 10² = 100",
        "% ionized = 100/(100 + 1) × 100 = 99.0%",
      ],
    },
    {
      t: "pH-solubility profile of weak base below pHmax",
      p: "ยา B เป็น weak base มี pKa 7.8 และ intrinsic solubility (S₀ ของ free base) 0.015 mg/mL หากต้องการเตรียมสารละลายในบัฟเฟอร์ pH 5.8 (สมมติว่า pH นี้ยังสูงกว่า pHmax จึงยังมี free base เป็น solid phase ที่สมดุล) total solubility ที่คาดได้มีค่าประมาณเท่าใด",
      o: ["0.015 mg/mL", "0.030 mg/mL", "0.15 mg/mL", "1.52 mg/mL", "15.2 mg/mL"],
      a: 3,
      r: "สำหรับ weak base ที่มี free base เป็น solid phase total solubility S = S₀[1 + 10^(pKa − pH)] เพราะรูป unionized ถูกจำกัดที่ S₀ ส่วนรูป ionized (BH⁺) เพิ่มขึ้นตามอัตราส่วน Henderson–Hasselbalch\n\nแทนค่า: 10^(7.8 − 5.8) = 100 ดังนั้น S = 0.015 × 101 = 1.515 ≈ 1.52 mg/mL\n\nข้อควรระวัง: สมการนี้ใช้ได้เมื่อ pH > pHmax เท่านั้น ถ้า pH ต่ำกว่า pHmax solid phase จะกลายเป็นเกลือ และ solubility ถูกจำกัดด้วย Ksp ของเกลือแทน กราฟจึงแบนราบ ไม่เพิ่มขึ้นไม่สิ้นสุด",
      w: [
        "0.015 mg/mL คือ S₀ ซึ่งเป็น solubility เฉพาะเมื่อ pH สูงกว่า pKa มากจนยาไม่แตกตัว",
        "0.030 mg/mL คือค่าที่ pH = pKa (S = 2S₀) ไม่ใช่ pH 5.8",
        "0.15 mg/mL เกิดจากการคิดว่า ΔpH = 1 หน่วยหรือคูณ 10 แทน 101",
        "ถูก — S = 0.015 × (1 + 10²) = 1.52 mg/mL",
        "15.2 mg/mL ใช้ ΔpH = 3 หน่วย (คูณ ~1000) ซึ่งคำนวณเกินจริง",
      ],
      k: "Weak base: S = S₀(1 + 10^(pKa − pH)) ใช้ได้เฉพาะช่วง pH > pHmax",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed., Ch.23 Pharmaceutical preformulation; Avdeef, Absorption and Drug Development 2nd ed.",
      c: [
        "pKa − pH = 7.8 − 5.8 = 2 → 10² = 100",
        "S = S₀ × (1 + 100) = 0.015 × 101",
        "S = 1.515 ≈ 1.52 mg/mL",
      ],
    },
    {
      t: "Counterion selection by delta pKa rule",
      p: "ทีม salt screening ต้องการเตรียมเกลือที่เสถียรของยา C ซึ่งเป็น weak base มี pKa (ของ conjugate acid) 3.5 กรดใดเหมาะสมที่สุดที่จะใช้เป็น counterion เพื่อให้เกิด proton transfer สมบูรณ์และได้เกลือที่ไม่แยกตัวกลับเป็น free base ง่าย",
      o: [
        "Methanesulfonic acid (pKa ≈ −1.9)",
        "Acetic acid (pKa ≈ 4.8)",
        "Citric acid (pKa₁ ≈ 3.1)",
        "Fumaric acid (pKa₁ ≈ 3.0)",
        "Succinic acid (pKa₁ ≈ 4.2)",
      ],
      a: 0,
      r: "กฎ ΔpKa ที่ใช้ใน salt selection: ให้ pKa(base) − pKa(acid) ≥ 2–3 หน่วย เพื่อให้เกิด proton transfer เกือบสมบูรณ์และได้เกลือที่เสถียร\n\nยา C มี pKa เพียง 3.5 (เบสอ่อนมาก) จึงต้องใช้กรดแก่ที่มี pKa ≤ ~1 เช่น HCl, methanesulfonic, sulfuric, benzenesulfonic acid ใน option มีเพียง methanesulfonic acid (pKa ≈ −1.9) ที่ให้ ΔpKa ≈ 5.4\n\nกรดคาร์บอกซิลิกทั่วไป (acetic, citric, fumaric, succinic) ให้ ΔpKa < 1 หรือติดลบ ซึ่งมักได้ co-crystal หรือเกลือที่ disproportionate กลับเป็น free base เมื่อสัมผัสความชื้น",
      w: [
        "ถูก — ΔpKa = 3.5 − (−1.9) ≈ 5.4 มากกว่า 3 จึงเกิด proton transfer สมบูรณ์ ได้ mesylate salt ที่เสถียร",
        "ΔpKa = 3.5 − 4.8 ติดลบ ไม่เกิด proton transfer จึงไม่ได้เกลือ",
        "ΔpKa ≈ 0.4 น้อยเกินไป เกลือที่ได้ (ถ้าเกิด) มักไม่เสถียรและแยกตัวง่าย",
        "ΔpKa ≈ 0.5 ไม่ถึงเกณฑ์ 2–3 หน่วย เสี่ยงได้ co-crystal หรือเกลือไม่เสถียร",
        "ΔpKa ติดลบ (3.5 − 4.2) ไม่สามารถ protonate เบสได้เพียงพอ",
      ],
      k: "Salt formation ที่เสถียรต้องการ ΔpKa (base − acid) ≥ 2–3; เบสอ่อนมากต้องใช้กรดแก่ (HCl, mesylate, besylate)",
      d: "medium",
      ref: "Stahl & Wermuth, Handbook of Pharmaceutical Salts: Properties, Selection, and Use 2nd ed.",
    },
    {
      t: "Enantiotropy by heat of fusion rule",
      p: "การคัดกรองผลึกของยา D พบ 2 polymorphs จาก DSC: Form I มี melting point 162 °C และ ΔHf 27 kJ/mol ส่วน Form II มี melting point 151 °C และ ΔHf 33 kJ/mol ตามกฎของ Burger–Ramberger ข้อสรุปใดถูกต้องที่สุด",
      o: [
        "Enantiotropic; Form II น่าจะเป็นรูปที่เสถียรที่อุณหภูมิห้อง (ต่ำกว่า transition temperature)",
        "Monotropic; Form I เสถียรกว่าทุกอุณหภูมิเพราะ melting point สูงกว่า",
        "Monotropic; Form II เสถียรกว่าทุกอุณหภูมิเพราะ ΔHf สูงกว่า",
        "Enantiotropic; Form I เสถียรที่อุณหภูมิห้องเพราะมี melting point สูงกว่า",
        "สรุปความสัมพันธ์ไม่ได้จนกว่าจะทราบ density ของทั้งสองรูป",
      ],
      a: 0,
      r: "Heat of fusion rule (Burger–Ramberger): ถ้ารูปที่มี melting point สูงกว่ามี ΔHf ต่ำกว่า ทั้งสองรูปมีความสัมพันธ์แบบ enantiotropic (มี transition temperature อยู่ต่ำกว่า melting point) แต่ถ้ารูปที่ mp สูงกว่ามี ΔHf สูงกว่าด้วย จะเป็น monotropic\n\nกรณีนี้ Form I mp สูงกว่าแต่ ΔHf ต่ำกว่า → enantiotropic ดังนั้นที่อุณหภูมิต่ำกว่า Tt รูปที่เสถียรคือ Form II (รูปที่ mp ต่ำกว่าแต่มี lattice enthalpy สูงกว่า) และเหนือ Tt Form I จะเสถียรกว่า\n\nในทางปฏิบัติควรยืนยันด้วย competitive slurry หรือ solubility ที่หลายอุณหภูมิ เพราะการเลือกผิดรูปอาจทำให้เกิด solid-state transformation ระหว่างเก็บรักษา",
      w: [
        "ถูก — mp สูงกว่าแต่ ΔHf ต่ำกว่า = enantiotropic; ต่ำกว่า Tt รูปที่ ΔHf สูง (Form II) เสถียร",
        "Melting point สูงกว่าอย่างเดียวไม่พอสรุป monotropy ต้องดู ΔHf ร่วมด้วย",
        "ข้อมูลไม่เข้ากับ monotropy เพราะรูปที่ mp สูงมี ΔHf ต่ำกว่า",
        "ระบุความสัมพันธ์ถูกแต่รูปที่เสถียรที่อุณหภูมิห้องผิด Form I เสถียรเฉพาะเหนือ Tt",
        "Density rule เป็นกฎเสริม ข้อมูล mp และ ΔHf เพียงพอใช้ heat of fusion rule ได้แล้ว",
      ],
      k: "Heat of fusion rule: รูป mp สูงแต่ ΔHf ต่ำ → enantiotropic; รูป mp สูงและ ΔHf สูง → monotropic",
      d: "hard",
      ref: "Burger A, Ramberger R. Mikrochim Acta 1979; Brittain, Polymorphism in Pharmaceutical Solids 2nd ed.",
    },
    {
      t: "Ph. Eur. hygroscopicity classification",
      p: "ทดสอบ hygroscopicity ของผงยา E ตาม Ph. Eur. โดยชั่งตัวอย่าง 1.000 g เก็บที่ 25 °C/80% RH นาน 24 ชั่วโมง ชั่งได้ 1.064 g และผงยังคงเป็นของแข็ง ควรจัดยา E อยู่ในกลุ่มใด",
      o: [
        "Hygroscopic (น้ำหนักเพิ่ม 6.4%)",
        "Slightly hygroscopic (น้ำหนักเพิ่ม 6.4%)",
        "Very hygroscopic (น้ำหนักเพิ่ม 6.4%)",
        "Deliquescent เพราะน้ำหนักเพิ่มเกิน 5%",
        "Non-hygroscopic เพราะน้ำหนักเพิ่มน้อยกว่า 10%",
      ],
      a: 0,
      r: "Ph. Eur. 5.11 จัดระดับ hygroscopicity จาก % น้ำหนักที่เพิ่มขึ้นหลังเก็บที่ 25 °C/80% RH นาน 24 ชม.: slightly hygroscopic ≥ 0.2% แต่ < 2%; hygroscopic ≥ 2% แต่ < 15%; very hygroscopic ≥ 15%; deliquescent คือดูดน้ำจนกลายเป็นของเหลว\n\n% เพิ่ม = (1.064 − 1.000)/1.000 × 100 = 6.4% จึงอยู่ในกลุ่ม hygroscopic\n\nผลนี้ใช้กำหนดสภาวะการผลิต (ควบคุม RH ในห้องผลิต) การเลือกบรรจุภัณฑ์ และอาจเป็นเหตุผลให้พิจารณาเปลี่ยน salt form",
      w: [
        "ถูก — 6.4% อยู่ในช่วง ≥ 2% และ < 15% = hygroscopic",
        "Slightly hygroscopic คือ 0.2–<2% ต่ำกว่าค่าที่ได้",
        "Very hygroscopic ต้องเพิ่ม ≥ 15%",
        "Deliquescent ตัดสินจากการกลายเป็นของเหลว ไม่ใช่เกณฑ์ 5% และโจทย์ระบุว่ายังเป็นของแข็ง",
        "ไม่มีเกณฑ์ 10% สำหรับ non-hygroscopic; เพิ่มเกิน 0.2% ก็ถือว่าดูดความชื้นแล้ว",
      ],
      k: "Ph. Eur. 5.11 (25 °C/80% RH, 24 h): 0.2–<2% slightly; 2–<15% hygroscopic; ≥15% very; กลายเป็นของเหลว = deliquescent",
      d: "medium",
      ref: "Ph. Eur. 5.11 Characters section in monographs (hygroscopicity)",
      c: ["% เพิ่ม = (1.064 − 1.000)/1.000 × 100 = 6.4%", "2% ≤ 6.4% < 15% → hygroscopic"],
    },
    {
      t: "Bulk porosity from true density",
      p: "ผง excipient ชนิดหนึ่งวัด true density ด้วย helium pycnometer ได้ 1.52 g/cm³ วัด bulk density ได้ 0.48 g/mL และ tapped density 0.64 g/mL ค่า porosity ของ powder bed ในสภาพ bulk (untapped) มีค่าประมาณเท่าใด",
      o: ["25.0%", "31.6%", "57.9%", "68.4%", "75.0%"],
      a: 3,
      r: "Porosity (ε) ของ powder bed คือสัดส่วนของปริมาตรช่องว่าง (ทั้ง inter- และ intraparticulate) ต่อปริมาตร bed ทั้งหมด คำนวณได้จาก ε = 1 − (ρbulk/ρtrue)\n\nε = 1 − 0.48/1.52 = 1 − 0.316 = 0.684 หรือ 68.4%\n\nTrue density วัดด้วย helium pycnometry เพราะ He โมเลกุลเล็กแทรกเข้ารูพรุนได้ จึงได้ปริมาตรของแข็งจริง ส่วน bulk/tapped density รวมช่องว่างด้วย จึงใช้ร่วมกันประเมิน packing, compressibility และ porosity",
      w: [
        "25.0% คือ Carr's index = (0.64 − 0.48)/0.64 ไม่ใช่ porosity",
        "31.6% คือ ρbulk/ρtrue ซึ่งเป็น packing fraction (solid fraction) ไม่ใช่ porosity",
        "57.9% คือ porosity ของ tapped bed (1 − 0.64/1.52) ไม่ใช่ bulk",
        "ถูก — ε = 1 − 0.48/1.52 = 68.4%",
        "75.0% คือ ρbulk/ρtapped (1/Hausner ratio) ไม่ใช่ porosity",
      ],
      k: "Porosity ε = 1 − ρbulk/ρtrue; true density วัดด้วย helium pycnometry",
      d: "medium",
      ref: "USP <699> Density of Solids; USP <616> Bulk Density and Tapped Density of Powders",
      c: ["ρbulk/ρtrue = 0.48/1.52 = 0.316", "ε = 1 − 0.316 = 0.684 → 68.4%"],
    },
    {
      t: "Noyes-Whitney combined surface area and concentration gradient",
      p: "ยา F มี Cs ในตัวกลาง 1.6 mg/mL เดิมทดสอบ dissolution ในสภาวะ sink (C ≈ 0) ต่อมาลด particle size ลง 4 เท่า (มวลเท่าเดิม) และทดสอบในปริมาตรน้อยลงจน C ในตัวกลางขณะวัดเท่ากับ 1.2 mg/mL ถ้า D และ h คงที่ อัตราการละลาย ณ ขณะนั้นเทียบกับการทดลองเดิมเป็นกี่เท่า",
      o: ["0.25 เท่า", "0.5 เท่า", "1.0 เท่า", "2.0 เท่า", "4.0 เท่า"],
      a: 2,
      r: "Noyes–Whitney: dM/dt = (D·A/h)(Cs − C) อัตราการละลายเป็นสัดส่วนกับพื้นที่ผิว A และ concentration gradient (Cs − C)\n\nลดขนาดอนุภาคลง 4 เท่าที่มวลเท่าเดิม พื้นที่ผิวจำเพาะ (∝ 1/d) เพิ่ม 4 เท่า แต่ gradient ลดจาก 1.6 เหลือ 1.6 − 1.2 = 0.4 mg/mL (เหลือ 0.25 เท่า) ผลรวม = 4 × 0.25 = 1.0 เท่า\n\nบทเรียน: การ micronize จะได้ประโยชน์เต็มที่ต้องรักษา sink condition (มักให้ C < Cs/3 หรือปริมาตรตัวกลาง ≥ 3 เท่าของที่ต้องใช้ละลายยาทั้งหมด) ในความเป็นจริง h ยังลดลงเล็กน้อยเมื่ออนุภาคเล็กลง จึงอาจเร็วกว่าค่าประมาณนี้",
      w: [
        "0.25 เท่า คิดเฉพาะ gradient ที่ลดลง ลืมพื้นที่ผิวที่เพิ่ม 4 เท่า",
        "0.5 เท่า ไม่สอดคล้องกับปัจจัยใดในสมการ",
        "ถูก — A เพิ่ม 4 เท่า × (Cs − C) เหลือ 0.25 เท่า = 1.0 เท่า",
        "2.0 เท่า เกิดจากคิดว่า gradient เหลือครึ่งหนึ่ง (0.5) แทนที่จะเหลือ 0.4/1.6 = 0.25",
        "4.0 เท่า คิดเฉพาะพื้นที่ผิว โดยลืมว่า C ที่สะสมทำให้ gradient ลดลง",
      ],
      k: "Noyes–Whitney: rate ∝ A(Cs − C); ลด particle size เพิ่ม A แต่ต้องคง sink condition จึงได้ประโยชน์",
      d: "hard",
      ref: "Aulton's Pharmaceutics 6th ed., Ch.2 Dissolution and solubility; Noyes AA, Whitney WR. J Am Chem Soc 1897",
      c: [
        "A ∝ 1/d → ลด d 4 เท่า → A เพิ่ม 4 เท่า",
        "เดิม (Cs − C) = 1.6 − 0 = 1.6; ใหม่ = 1.6 − 1.2 = 0.4 → 0.4/1.6 = 0.25",
        "Rate ใหม่/เดิม = 4 × 0.25 = 1.0 เท่า",
      ],
    },
    {
      t: "CMC from surface tension plot",
      p: "นักวิจัยวัด surface tension ของสารละลาย polysorbate 80 ที่ความเข้มข้นต่างๆ แล้ว plot surface tension กับ log concentration พบว่า surface tension ลดลงเป็นเส้นตรง แล้วเกิดจุดหักเห (break point) หลังจากนั้นค่าแทบคงที่ ข้อใดอธิบายจุดหักเหและพฤติกรรมหลังจุดนั้นได้ถูกต้องที่สุด",
      o: [
        "จุดหักเหคือ CMC หลังจากนั้นสารลดแรงตึงผิวที่เติมเพิ่มส่วนใหญ่รวมตัวเป็น micelle ความเข้มข้น monomer ค่อนข้างคงที่",
        "จุดหักเหคือ Krafft point หลังจากนั้นสารลดแรงตึงผิวตกตะกอน",
        "จุดหักเหคือ cloud point หลังจากนั้นสารละลายขุ่นเพราะ phase separation",
        "จุดหักเหคือจุดที่ผิวหน้าอิ่มตัว หลังจากนั้นสารลดแรงตึงผิวไม่ละลายในน้ำอีก",
        "จุดหักเหคือ HLB ที่เหมาะสม หลังจากนั้นความสามารถ solubilize ยาลดลง",
      ],
      a: 0,
      r: "ก่อน CMC โมเลกุล surfactant (monomer) ไปดูดซับที่ผิวหน้าอากาศ–น้ำมากขึ้นตามความเข้มข้น surface tension จึงลดลงเป็นเส้นตรงกับ log C (สอดคล้องกับ Gibbs adsorption)\n\nเมื่อถึง critical micelle concentration (CMC) ผิวหน้าเกือบอิ่มตัว สารที่เติมเพิ่มจะรวมตัวเป็น micelle แทน ทำให้ความเข้มข้น monomer อิสระแทบคงที่ surface tension จึงไม่ลดลงอีก\n\nCMC หาได้จากจุดหักเหของคุณสมบัติหลายอย่าง (surface tension, conductivity สำหรับ ionic surfactant, light scattering, solubilization ของ dye) และยาที่ไม่ชอบน้ำจะถูก solubilize เพิ่มขึ้นอย่างชัดเจนเมื่อความเข้มข้นเกิน CMC",
      w: [
        "ถูก — break point คือ CMC; เกินจากนี้เกิด micelle และ monomer คงที่ surface tension จึงแบนราบ",
        "Krafft point เป็นอุณหภูมิ (ของ ionic surfactant) ไม่ใช่ความเข้มข้นในกราฟนี้",
        "Cloud point เป็นอุณหภูมิที่ nonionic surfactant แยกเฟสเมื่อให้ความร้อน ไม่ใช่จุดหักเหตามความเข้มข้น",
        "สารลดแรงตึงผิวยังละลายได้ต่อ แต่ไปอยู่ในรูป micelle ไม่ใช่หยุดละลาย",
        "HLB เป็นคุณสมบัติของโมเลกุล ไม่ได้หาจากกราฟนี้ และ solubilization เพิ่มขึ้นหลัง CMC",
      ],
      k: "Surface tension vs log C แบนราบที่ CMC; micelle เกิดเหนือ CMC และเป็นตัว solubilize ยาไม่ชอบน้ำ",
      d: "medium",
      ref: "Martin's Physical Pharmacy and Pharmaceutical Sciences 7th ed., Ch.15 Interfacial Phenomena & Ch.16 Colloidal Dispersions",
    },
    {
      t: "Pseudoplastic flow of polymer dispersions",
      p: "สารละลาย sodium carboxymethylcellulose 2% w/v เมื่อวัดด้วย rotational viscometer พบว่า apparent viscosity ลดลงเมื่อเพิ่ม shear rate และ rheogram ผ่านจุดกำเนิด (ไม่มี yield value) พฤติกรรมการไหลนี้คือข้อใด",
      o: [
        "Pseudoplastic (shear-thinning) flow",
        "Newtonian flow",
        "Bingham plastic flow",
        "Dilatant (shear-thickening) flow",
        "Rheopexy",
      ],
      a: 0,
      r: "Pseudoplastic flow พบบ่อยในสารละลาย polymer เช่น NaCMC, methylcellulose, tragacanth, sodium alginate สายโซ่ polymer ที่พันกันแบบสุ่มจะเรียงตัวตามทิศการไหลเมื่อได้รับ shear และปล่อยน้ำที่ถูกตรึงไว้ออกมา จึงทำให้ apparent viscosity ลดลงเมื่อ shear rate เพิ่ม\n\nRheogram ของ pseudoplastic เป็นเส้นโค้งที่ผ่านจุดกำเนิด (ไม่มี yield value) ต่างจาก plastic flow ที่ต้องมีแรงเกินค่า yield value ก่อนจึงไหล และมักอธิบายด้วย power law: F^N = η′G (N > 1 สำหรับ pseudoplastic)\n\nข้อดีในทางเภสัชกรรม: ผลิตภัณฑ์หนืดขณะตั้งทิ้งไว้ แต่เทหรือบีบออกจากหลอดได้ง่ายเมื่อเขย่า/บีบ",
      w: [
        "ถูก — viscosity ลดลงเมื่อ shear rate เพิ่ม และไม่มี yield value คือ pseudoplastic",
        "Newtonian มี viscosity คงที่ไม่ขึ้นกับ shear rate",
        "Bingham plastic ต้องมี yield value เส้นจึงไม่ผ่านจุดกำเนิด",
        "Dilatant viscosity เพิ่มขึ้นเมื่อ shear rate เพิ่ม ตรงข้ามกับข้อมูล",
        "Rheopexy เป็นพฤติกรรมขึ้นกับเวลา (ข้นขึ้นเมื่อเขย่าเบาๆ) ไม่ใช่สิ่งที่โจทย์บรรยาย",
      ],
      k: "Polymer solutions (NaCMC, MC, tragacanth) = pseudoplastic: shear-thinning, ไม่มี yield value",
      d: "easy",
      ref: "Martin's Physical Pharmacy and Pharmaceutical Sciences 7th ed., Ch.19 Rheology",
    },
    {
      t: "Maillard reaction amine drug with lactose",
      p: "ในการศึกษา drug–excipient compatibility ยา G ซึ่งมีหมู่ primary amine ผสมแบบ binary mixture 1:1 กับ excipient ต่างๆ แล้วเก็บที่ 40 °C/75% RH นาน 4 สัปดาห์ พบว่าเฉพาะส่วนผสมกับ lactose monohydrate เกิดสีน้ำตาลเหลืองและมี degradant ใหม่ คำอธิบายและแนวทางแก้ไขใดเหมาะสมที่สุด",
      o: [
        "เกิด Maillard reaction ระหว่าง amine กับ reducing sugar ควรเปลี่ยน filler เป็นสารที่ไม่ใช่ reducing sugar เช่น microcrystalline cellulose หรือ dibasic calcium phosphate",
        "เกิด hydrolysis ของ lactose จากความชื้น ควรเปลี่ยนเป็น anhydrous lactose",
        "เกิด polymorphic transformation ของยา ควรเปลี่ยน particle size ของ lactose",
        "เกิด oxidation จาก peroxide ใน lactose ควรเติม antioxidant โดยยังใช้ lactose ต่อได้",
        "เกิด photodegradation ของ lactose ควรเก็บในภาชนะทึบแสงเท่านั้น",
      ],
      a: 0,
      r: "Lactose เป็น reducing sugar (มี hemiacetal ที่เปิดเป็น aldehyde ได้) ทำปฏิกิริยากับ primary/secondary amine ผ่าน Maillard reaction ได้ Schiff base → Amadori rearrangement → ผลิตภัณฑ์สีน้ำตาล ความร้อนและความชื้นเร่งปฏิกิริยา ตัวอย่างที่รู้จัก เช่น fluoxetine HCl, amlodipine กับ lactose\n\nแนวทางแก้ที่ตรงจุดคือเลี่ยง reducing sugar โดยใช้ MCC, dibasic calcium phosphate, mannitol (sugar alcohol ไม่มีหมู่ reducing) แทน\n\nการใช้ anhydrous lactose ลดความชื้นแต่ไม่ได้ตัดสาเหตุ (หมู่ reducing ยังอยู่) ส่วน peroxide เป็นปัญหาของ povidone/crospovidone/polysorbate มากกว่า lactose",
      w: [
        "ถูก — amine + reducing sugar = Maillard (สีน้ำตาล) แก้โดยใช้ filler ที่ไม่มีหมู่ reducing",
        "Lactose hydrolysis ไม่ใช่สาเหตุของ degradant ของยา และ anhydrous lactose ยังเป็น reducing sugar",
        "Polymorphic change ไม่ทำให้เกิดสีน้ำตาลหรือ degradant ใหม่ และไม่จำเพาะต่อ lactose",
        "Peroxide เป็น impurity เด่นใน povidone/PEG/polysorbate และไม่อธิบายการเกิดสีน้ำตาลจำเพาะกับ amine",
        "สภาวะทดสอบเป็นความร้อน/ความชื้น ไม่ใช่แสง และ lactose ไม่ใช่ตัวที่ photodegrade",
      ],
      k: "Primary/secondary amine + lactose (reducing sugar) → Maillard browning; ใช้ MCC/DCP/mannitol แทน",
      d: "hard",
      ref: "Rowe RC et al., Handbook of Pharmaceutical Excipients 9th ed. (Lactose monograph); Narang AS et al., J Pharm Sci 2012 (excipient reactivity)",
    },
  ],
];
