import type { Ip1MockDomainContent } from "@/lib/ip1-mock/types";

export const QA: Ip1MockDomainContent = [
  // Mock Set 1 — ชุดที่ 1
  [
    {
      t: "FMEA RPN prioritization",
      p: "ทีม QRM ทำ FMEA กระบวนการบรรจุแคปซูล ได้คะแนน (S, O, D) ดังนี้ A = (8, 3, 4), B = (6, 5, 5), C = (9, 2, 7), D = (5, 6, 3), E = (7, 4, 6) หากองค์กรจัดลำดับความสำคัญด้วย RPN เพียงอย่างเดียว failure mode ใดควรได้รับการจัดการเป็นลำดับแรก",
      o: [
        "Failure mode E (RPN = 168)",
        "Failure mode B (RPN = 150)",
        "Failure mode C (RPN = 126) เพราะ severity สูงสุด",
        "Failure mode A (RPN = 96)",
        "Failure mode D (RPN = 90) เพราะ occurrence สูงสุด",
      ],
      a: 0,
      r: "RPN (Risk Priority Number) = Severity × Occurrence × Detectability โดยแต่ละปัจจัยมักให้คะแนน 1–10 และ D ที่สูงหมายถึงตรวจจับได้ยาก\n\nคำนวณได้ A = 96, B = 150, C = 126, D = 90, E = 168 ดังนั้นถ้าใช้ RPN อย่างเดียว E มีลำดับสูงสุด อย่างไรก็ตามในทางปฏิบัติ ICH Q9(R1) เตือนว่าคะแนนเชิงตัวเลขมี subjectivity และหลายองค์กรกำหนดกฎเสริม เช่น S ≥ 9 ต้องพิจารณาเสมอแม้ RPN ต่ำ ซึ่งทำให้ C ควรถูกทบทวนด้วยเช่นกัน",
      w: [
        "ถูก — 7 × 4 × 6 = 168 สูงที่สุดในทั้ง 5 failure modes เมื่อใช้ RPN เป็นเกณฑ์เดียว",
        "B = 6 × 5 × 5 = 150 เป็นลำดับที่สอง ไม่ใช่สูงสุด",
        "C = 9 × 2 × 7 = 126 แม้ S สูงสุดแต่โจทย์กำหนดให้จัดลำดับด้วย RPN เพียงอย่างเดียว (ในชีวิตจริงควรมีกฎเสริมสำหรับ S สูง)",
        "A = 8 × 3 × 4 = 96 ต่ำกว่า E, B และ C",
        "D = 5 × 6 × 3 = 90 ต่ำสุด แม้ O สูงสุดแต่ RPN รวมไม่ได้สูง",
      ],
      k: "RPN = S × O × D; ใช้จัดลำดับได้แต่ควรมีกฎเสริมสำหรับ severity สูง เพราะ RPN เท่ากันอาจมี risk profile ต่างกัน",
      d: "medium",
      ref: "ICH Q9(R1) Quality Risk Management, Annex I (FMEA)",
      c: [
        "A = 8 × 3 × 4 = 96",
        "B = 6 × 5 × 5 = 150",
        "C = 9 × 2 × 7 = 126",
        "D = 5 × 6 × 3 = 90",
        "E = 7 × 4 × 6 = 168 → สูงสุด",
      ],
    },
    {
      t: "ICH Q9 risk assessment components",
      p: "ตาม ICH Q9(R1) กระบวนการ risk assessment ประกอบด้วยขั้นตอนย่อยใดบ้าง",
      o: [
        "Risk identification, risk analysis และ risk evaluation",
        "Risk reduction, risk acceptance และ risk review",
        "Risk identification, risk communication และ risk acceptance",
        "Risk analysis, risk control และ risk review",
        "Hazard identification, CAPA และ management review",
      ],
      a: 0,
      r: "ICH Q9(R1) แบ่ง QRM process เป็น risk assessment → risk control → risk communication → risk review โดย risk assessment ประกอบด้วย risk identification (มีอะไรผิดพลาดได้), risk analysis (โอกาสเกิดและความรุนแรง รวมถึงการตรวจจับ) และ risk evaluation (เทียบกับเกณฑ์ว่าเสี่ยงยอมรับได้หรือไม่)\n\nRisk control ประกอบด้วย risk reduction และ risk acceptance ส่วน risk communication และ risk review เป็นกิจกรรมที่ดำเนินตลอดวงจร",
      w: [
        "ถูก — สามขั้นตอนของ risk assessment ตาม ICH Q9(R1) คือ identification, analysis, evaluation",
        "Risk reduction และ risk acceptance เป็นส่วนของ risk control ส่วน risk review เป็นขั้นตอนทบทวนภายหลัง",
        "Risk communication และ risk acceptance ไม่ได้อยู่ใน risk assessment",
        "Risk control และ risk review เป็นขั้นตอนถัดไปหลัง risk assessment",
        "CAPA และ management review เป็นองค์ประกอบของ PQS (ICH Q10) ไม่ใช่ขั้นตอนย่อยของ risk assessment",
      ],
      k: "Risk assessment = identify → analyze → evaluate; Risk control = reduce + accept",
      d: "easy",
      ref: "ICH Q9(R1) Quality Risk Management, Section 4",
    },
    {
      t: "Critical deviation classification",
      p: "ระหว่าง line clearance ของวันถัดมา พบว่ากล่องยาเม็ด Amlodipine 10 mg ที่บรรจุเสร็จแล้วบางกล่องมีแผง blister ของ Amlodipine 5 mg ปะปนอยู่ ควรจัดระดับ deviation นี้อย่างไรเหมาะสมที่สุด",
      o: [
        "Critical deviation เพราะเป็น product mix-up ที่อาจทำให้ผู้ป่วยได้รับยาผิดความแรง",
        "Major deviation เพราะพบก่อนปล่อยยาจึงไม่กระทบผู้ป่วย",
        "Minor deviation เพราะเป็นยาตัวเดียวกันต่างกันแค่ความแรง",
        "ไม่ต้องจัดเป็น deviation แค่คัดแยกกล่องที่ผิดออกก็เพียงพอ",
        "Minor deviation หากผล assay ของ batch อยู่ในเกณฑ์",
      ],
      a: 0,
      r: "การจัดระดับ deviation อิงกับผลกระทบต่อคุณภาพและความปลอดภัยของผู้ป่วย: critical คือมีโอกาสก่อให้เกิดอันตรายต่อผู้ป่วยหรือผลิตภัณฑ์ไม่เป็นไปตาม MA อย่างร้ายแรง, major คือมีผลกระทบต่อคุณภาพอย่างมีนัยสำคัญแต่ไม่ถึงขั้นอันตรายโดยตรง, minor คือไม่มีผลกระทบต่อคุณภาพ\n\nMix-up ของความแรงเป็นตัวอย่างคลาสสิกของ critical เพราะผู้ป่วยอาจได้รับยาผิดขนาด และบ่งชี้ความล้มเหลวของ line clearance/segregation การพบก่อนปล่อยยาไม่ได้ลดระดับของความล้มเหลวของระบบ ต้อง quarantine ทั้ง batch, ขยายการสอบสวนไป batch อื่นที่ใช้ line เดียวกัน และทำ CAPA",
      w: [
        "ถูก — mix-up ต่างความแรงมีโอกาสก่อให้เกิดอันตรายต่อผู้ป่วยโดยตรง จัดเป็น critical",
        "การตรวจพบก่อนปล่อยไม่ลดความรุนแรงของความล้มเหลวของระบบ ศักยภาพในการเกิดอันตรายยังเป็นตัวกำหนดระดับ",
        "ความแรงต่างกันสองเท่าเป็นความเสี่ยงต่อผู้ป่วยชัดเจน ไม่ใช่เรื่องเล็กน้อย",
        "ทุกเหตุการณ์ที่เบี่ยงเบนจาก procedure ต้องบันทึกเป็น deviation และสอบสวนหา root cause ไม่ใช่แค่ correction",
        "ผล assay ไม่สะท้อน mix-up ระดับหน่วยบรรจุ และไม่ลดความเสี่ยงที่ผู้ป่วยได้ยาผิดความแรง",
      ],
      k: "Mix-up (ผิดความแรง/ผิดตัวยา/ผิดฉลาก) = critical deviation เสมอ ต้อง quarantine และขยายขอบเขตการสอบสวน",
      d: "medium",
      ref: "PIC/S GMP Guide PE 009 Part I Ch.1 & Ch.8; WHO TRS 1025 Annex (deviation handling)",
    },
    {
      t: "Ishikawa 6M categorization",
      p: "ในการทำ Ishikawa (fishbone) diagram ของปัญหา tablet weight variation ทีมระบุสาเหตุที่เป็นไปได้ว่า “excipient lot ใหม่มี particle size ละเอียดกว่าเดิม ทำให้การไหลแย่ลง” สาเหตุนี้ควรจัดอยู่ในหมวดใดของ 6M",
      o: ["Material", "Machine", "Method", "Man", "Measurement"],
      a: 0,
      r: "Ishikawa diagram ใช้จัดกลุ่มสาเหตุที่เป็นไปได้ตามหมวด 6M ได้แก่ Man (คน), Machine (เครื่องจักร), Method (วิธีการ/SOP/พารามิเตอร์), Material (วัตถุดิบ/บรรจุภัณฑ์), Measurement (การวัด/เครื่องมือวัด) และ Mother Nature/Milieu (สิ่งแวดล้อม)\n\nสาเหตุที่มาจากคุณสมบัติของวัตถุดิบ เช่น particle size, moisture, lot-to-lot variability ของ excipient จัดเป็น Material Ishikawa เป็นเครื่องมือระดมสมองเพื่อหา potential causes ต้องตรวจยืนยันด้วยข้อมูลก่อนสรุปเป็น root cause",
      w: [
        "ถูก — คุณสมบัติของ excipient lot ใหม่เป็นสาเหตุด้านวัตถุดิบ (Material)",
        "Machine ใช้กับสาเหตุจากเครื่องตอก เช่น feeder, punch wear ไม่ใช่คุณสมบัติผง",
        "Method ใช้กับวิธีการ/พารามิเตอร์ใน MBR เช่น เวลาผสม ความเร็ว turret",
        "Man ใช้กับสาเหตุด้านบุคลากร เช่น การฝึกอบรม การปฏิบัติไม่ตาม SOP",
        "Measurement ใช้กับความผิดพลาดของการวัด เช่น เครื่องชั่ง IPC ไม่ได้ calibrate",
      ],
      k: "6M = Man, Machine, Method, Material, Measurement, Mother nature; Ishikawa ให้ potential causes ต้องยืนยันด้วยข้อมูล",
      d: "easy",
      ref: "ICH Q9(R1) Annex I (basic risk management facilitation methods)",
    },
    {
      t: "Process validation Stage 2 activities",
      p: "ตามแนวทาง process validation แบบ lifecycle (FDA 2011) กิจกรรมใดจัดอยู่ใน Stage 2 (Process Qualification)",
      o: [
        "การทำ PPQ batches ตาม protocol ที่อนุมัติล่วงหน้า หลังจาก qualify facility, utilities และ equipment แล้ว",
        "การทำ DoE เพื่อกำหนด design space และ critical process parameters",
        "การเก็บข้อมูล CPP/CQA จาก commercial batches อย่างต่อเนื่องเพื่อติดตามแนวโน้ม",
        "การทำ Product Quality Review ประจำปี",
        "การ scale-up จาก lab scale ไป pilot scale เพื่อหา control strategy",
      ],
      a: 0,
      r: "FDA Process Validation Guidance (2011) แบ่ง 3 stage: Stage 1 Process Design (สร้างความเข้าใจกระบวนการ, DoE, กำหนด control strategy), Stage 2 Process Qualification (2a: qualify facility/utilities/equipment, 2b: PPQ ที่ commercial scale ตาม protocol) และ Stage 3 Continued Process Verification (ติดตามข้อมูลต่อเนื่องระหว่างการผลิตเชิงพาณิชย์)\n\nPPQ จึงเป็นหัวใจของ Stage 2 ซึ่งต้องผ่านก่อนการจำหน่ายเชิงพาณิชย์ (commercial distribution)",
      w: [
        "ถูก — equipment/utility qualification และ PPQ เป็นกิจกรรมของ Stage 2",
        "DoE และการกำหนด design space เป็นกิจกรรม Stage 1 (Process Design)",
        "การติดตามข้อมูล commercial batches อย่างต่อเนื่องคือ Stage 3 (CPV)",
        "PQR เป็นการทบทวนระดับ PQS ที่สนับสนุน Stage 3 ไม่ใช่ Process Qualification",
        "การ scale-up เพื่อสร้างความรู้และ control strategy เป็นส่วนของ Stage 1",
      ],
      k: "Stage 1 = Design, Stage 2 = Qualification (equipment + PPQ), Stage 3 = Continued Process Verification",
      d: "medium",
      ref: "FDA Guidance for Industry: Process Validation — General Principles and Practices (2011)",
    },
    {
      t: "Cleaning limit by 10 ppm criterion",
      p: "เครื่องผสมใช้ร่วมกันระหว่างยา A (ผลิตก่อน) และยา B (ผลิตถัดไป) บริษัทใช้เกณฑ์ 10 ppm สำหรับ residue ของยา A ในยา B ขนาด batch ของยา B = 150 kg พื้นที่ผิวสัมผัสรวม = 30,000 cm² และพื้นที่ swab = 25 cm² ต่อจุด ค่า acceptance limit ต่อ swab คือข้อใด",
      o: ["50 µg/swab", "125 µg/swab", "1,250 µg/swab", "12,500 µg/swab", "60,000 µg/swab"],
      a: 2,
      r: "เกณฑ์ 10 ppm หมายถึงยา A ปนเปื้อนในยา B ได้ไม่เกิน 10 mg ต่อยา B 1 kg ดังนั้น MACO = 10 mg/kg × ขนาด batch ของยาถัดไป จากนั้นสมมติว่า residue กระจายสม่ำเสมอบนพื้นผิวสัมผัสทั้งหมด หารด้วยพื้นที่รวมได้ limit ต่อ cm² แล้วคูณพื้นที่ swab\n\nMACO = 10 × 150 = 1,500 mg; ต่อ cm² = 1,500 mg / 30,000 cm² = 0.05 mg/cm² = 50 µg/cm²; ต่อ swab 25 cm² = 1,250 µg ปัจจุบันแนวทาง EMA/PIC/S แนะนำให้ใช้ HBEL (PDE) เป็นหลัก โดย 10 ppm อาจใช้เป็นเกณฑ์เสริม",
      w: [
        "50 µg คือ limit ต่อ cm² ลืมคูณพื้นที่ swab 25 cm²",
        "125 µg เกิดจากคำนวณ MACO ผิดเป็น 150 mg (ใช้ 1 ppm แทน 10 ppm)",
        "ถูก — 1,500 mg ÷ 30,000 cm² × 25 cm² = 1.25 mg = 1,250 µg ต่อ swab",
        "12,500 µg เกิดจาก error หลักทศนิยม 10 เท่า",
        "60,000 µg เกิดจากเอา MACO 1,500 mg หารด้วยพื้นที่ swab โดยตรง ไม่ได้คิดพื้นที่ผิวรวม",
      ],
      k: "10 ppm: MACO (mg) = 10 × batch size ถัดไป (kg); limit/swab = MACO ÷ พื้นที่รวม × พื้นที่ swab",
      d: "hard",
      ref: "PIC/S PI 006-3 Recommendations on Validation Master Plan, IQ, OQ, Non-sterile Process Validation, Cleaning Validation",
      c: [
        "MACO = 10 mg/kg × 150 kg = 1,500 mg",
        "Limit ต่อพื้นที่ = 1,500 mg ÷ 30,000 cm² = 0.05 mg/cm² = 50 µg/cm²",
        "Limit ต่อ swab = 50 µg/cm² × 25 cm² = 1,250 µg",
      ],
    },
    {
      t: "Operational qualification test scope",
      p: "บริษัทติดตั้ง fluid bed dryer เครื่องใหม่ การทดสอบใดจัดเป็น Operational Qualification (OQ) ที่เหมาะสมที่สุด",
      o: [
        "ทดสอบการควบคุม inlet air temperature และ airflow ตลอดช่วงการใช้งาน รวมถึง alarm และ interlock โดยยังไม่ใช้ผลิตภัณฑ์จริง",
        "ตรวจสอบว่า utilities ต่อถูกต้อง วัสดุผิวสัมผัสเป็น SS316L และมีเอกสาร as-built drawing ครบ",
        "อบแกรนูลของผลิตภัณฑ์จริง 3 batches แล้วได้ LOD อยู่ในเกณฑ์อย่างสม่ำเสมอ",
        "จัดทำ user requirement specification ระบุกำลังการผลิตและช่วงอุณหภูมิที่ต้องการ",
        "ตรวจรับเครื่องที่โรงงานผู้ผลิตก่อนส่งมอบ (FAT)",
      ],
      a: 0,
      r: "Equipment qualification เรียงเป็น URS → DQ → (FAT/SAT) → IQ → OQ → PQ โดย IQ ยืนยันว่าติดตั้งถูกต้องตามแบบ (วัสดุ, utilities, เอกสาร, calibration ของเครื่องมือวัด), OQ ยืนยันว่าเครื่องทำงานตามที่ออกแบบตลอดช่วงการใช้งานที่คาดไว้ รวมถึง upper/lower limits, alarm, interlock มักทดสอบโดยไม่มีผลิตภัณฑ์หรือใช้ placebo, PQ ยืนยันว่าเครื่องทำงานได้สม่ำเสมอภายใต้สภาวะการผลิตจริง\n\nการทดสอบ control range และ alarm/interlock จึงเป็น OQ",
      w: [
        "ถูก — การทดสอบ function, operating range, alarm และ interlock คือหัวใจของ OQ",
        "การตรวจวัสดุ, utilities และเอกสารเป็น IQ",
        "การใช้ผลิตภัณฑ์จริงซ้ำๆ เพื่อแสดงความสม่ำเสมอภายใต้สภาวะจริงเป็น PQ",
        "URS เป็นเอกสารต้นทางที่ระบุความต้องการของผู้ใช้ จัดทำก่อน DQ",
        "FAT ทำที่โรงงานผู้ผลิตเครื่อง ช่วยลดงานแต่ไม่ใช่ OQ ที่ไซต์ผู้ใช้",
      ],
      k: "IQ = ติดตั้งถูก, OQ = ทำงานถูกตลอด operating range + alarm/interlock, PQ = ทำงานสม่ำเสมอในสภาวะจริง",
      d: "medium",
      ref: "PIC/S GMP Guide PE 009 Annex 15 Qualification and Validation, Section 3",
    },
    {
      t: "CAPA effectiveness check design",
      p: "หลังเกิด deviation ซ้ำเรื่องการบันทึกน้ำหนักวัตถุดิบผิดใน batch record ทีมกำหนด CAPA คือปรับ SOP ให้ใช้เครื่องชั่งที่พิมพ์ผลอัตโนมัติและฝึกอบรมพนักงาน ข้อใดเป็น effectiveness check ที่เหมาะสมที่สุด",
      o: [
        "ติดตามว่าไม่มี deviation ชนิดเดียวกันเกิดซ้ำใน batch ที่ผลิตช่วง 6 เดือนถัดไป ตามเกณฑ์ที่กำหนดไว้ล่วงหน้า",
        "ยืนยันว่าพนักงานทุกคนลงนามในใบบันทึกการฝึกอบรมครบ",
        "ยืนยันว่า SOP ฉบับใหม่ได้รับอนุมัติและแจกจ่ายแล้ว",
        "ปิด CAPA ทันทีเมื่อเครื่องชั่งใหม่ผ่าน IQ",
        "ให้หัวหน้าแผนกยืนยันด้วยวาจาว่าปัญหาหมดไปแล้ว",
      ],
      a: 0,
      r: "ICH Q10 กำหนดให้ CAPA ต้องมีการประเมิน effectiveness ซึ่งต่างจากการยืนยันว่าดำเนินการเสร็จ (implementation/completion) Effectiveness check ควรตอบว่า CAPA ขจัด root cause และป้องกันการเกิดซ้ำได้จริงหรือไม่ โดยกำหนด metric, ช่วงเวลา และเกณฑ์ผ่านไว้ล่วงหน้า เช่น อัตราการเกิดซ้ำเป็นศูนย์ใน N batches หรือ X เดือน\n\nการลงนามฝึกอบรม การอนุมัติ SOP หรือการติดตั้งเครื่องเป็นเพียงหลักฐานว่าได้ทำ action แล้ว ไม่ใช่หลักฐานว่าได้ผล",
      w: [
        "ถูก — วัดผลลัพธ์จริง (recurrence) ในช่วงเวลาที่กำหนดด้วยเกณฑ์ที่ตั้งไว้ล่วงหน้า",
        "การลงนามฝึกอบรมเป็นหลักฐานการดำเนินการ ไม่ได้แสดงว่าพฤติกรรมหรือผลลัพธ์เปลี่ยน",
        "การอนุมัติ SOP เป็น implementation ไม่ใช่ effectiveness",
        "IQ ยืนยันการติดตั้งเครื่อง ยังไม่ได้แสดงว่าปัญหาการบันทึกหายไป",
        "การยืนยันด้วยวาจาไม่ใช่หลักฐานที่เป็นเอกสารและไม่มีเกณฑ์เชิงวัตถุวิสัย",
      ],
      k: "CAPA completion ≠ effectiveness; effectiveness check ต้องวัดผลลัพธ์ด้วย metric/เกณฑ์/ระยะเวลาที่กำหนดล่วงหน้า",
      d: "medium",
      ref: "ICH Q10 Pharmaceutical Quality System, Section 3.2.2",
    },
    {
      t: "Batch certification with open deviation",
      p: "Batch ยาเม็ดเคลือบฟิล์มผ่านการตรวจวิเคราะห์ครบตาม specification แต่ยังมี major deviation เรื่อง granulation endpoint เกินเวลาที่ validate ไว้ ซึ่งการสอบสวนยังไม่ปิด ฝ่ายขายต้องการให้ปล่อยยาด่วน ผู้มีอำนาจปล่อยผลิตภัณฑ์ (authorized person) ควรทำอย่างไร",
      o: [
        "ยังไม่รับรองปล่อย batch จนกว่าการสอบสวนจะสรุป impact ต่อคุณภาพและได้รับการประเมินอนุมัติแล้ว",
        "ปล่อยได้ทันทีเพราะผล QC ผ่าน specification ครบทุกข้อ",
        "ปล่อยได้หากฝ่ายผลิตรับรองว่าไม่มีผลกระทบ",
        "ปล่อยแบบมีเงื่อนไขแล้วค่อยปิด deviation ภายหลัง หากพบปัญหาจึงเรียกคืน",
        "ส่งตัวอย่างเพิ่มไปตรวจ dissolution ซ้ำแล้วปล่อยหากผ่านโดยไม่ต้องรอสอบสวน",
      ],
      a: 0,
      r: "การรับรองปล่อย batch ของ authorized person (AP/QP) ต้องยืนยันว่า batch ผลิตและตรวจสอบตาม GMP และ marketing authorization และว่า deviation ทั้งหมดได้รับการสอบสวนและประเมินผลกระทบจนเป็นที่ยอมรับแล้ว ผลตรวจผ่าน specification เป็นเงื่อนไขจำเป็นแต่ไม่เพียงพอ เพราะการทดสอบมีขนาดตัวอย่างจำกัดและอาจตรวจไม่พบปัญหาที่เกิดจากกระบวนการนอก validated state\n\nการปล่อยก่อนแล้ว 'ค่อยเรียกคืน' เป็นการผลักความเสี่ยงไปให้ผู้ป่วย และแรงกดดันทางธุรกิจต้องไม่มีผลต่อการตัดสินใจของ AP ซึ่งต้องเป็นอิสระจากฝ่ายผลิต",
      w: [
        "ถูก — deviation ที่อาจกระทบคุณภาพต้องสอบสวนและประเมินเสร็จก่อนการรับรองปล่อย",
        "ผล QC ผ่านไม่ได้พิสูจน์ว่าการผลิตนอก validated parameter ไม่มีผลกระทบ (quality cannot be tested into product)",
        "ความรับผิดชอบการปล่อยเป็นของ AP/QA ที่เป็นอิสระ ไม่สามารถมอบให้ฝ่ายผลิตรับรองแทน",
        "การปล่อยโดยหวังพึ่ง recall เป็นการยอมรับความเสี่ยงต่อผู้ป่วยโดยไม่จำเป็น ขัดหลัก GMP",
        "การทดสอบซ้ำไม่ใช่สิ่งทดแทนการสอบสวน root cause และ impact assessment",
      ],
      k: "AP ปล่อย batch ได้เมื่อ (1) ตาม MA/GMP (2) ผล QC ผ่าน และ (3) deviation ทั้งหมดสอบสวน/ประเมินเสร็จ — ผลตรวจผ่านอย่างเดียวไม่พอ",
      d: "hard",
      ref: "PIC/S GMP Guide PE 009 Annex 16 (Certification by an Authorised Person and Batch Release); Part I Ch.1.4",
    },
    {
      t: "Reduced testing based on supplier qualification",
      p: "โรงงานต้องการเปลี่ยนการรับ excipient (microcrystalline cellulose) จากผู้ขายรายหนึ่งเป็นแบบ reduced testing คือยอมรับผลตาม CoA ของผู้ผลิต ข้อใดเป็นเงื่อนไขที่ถูกต้องที่สุด",
      o: [
        "ต้องประเมินและ qualify ผู้ผลิต (เช่น audit/questionnaire) ตรวจสอบความน่าเชื่อถือของ CoA ด้วยการตรวจเต็มเป็นระยะ และยังคงทดสอบ identity ตามที่กำหนด",
        "ยอมรับ CoA ได้ทันทีหากผู้ขายเป็นตัวแทนจำหน่ายรายใหญ่ที่มีใบอนุญาต",
        "หากใช้ CoA แล้วสามารถยกเลิกการทดสอบ identity ทั้งหมดได้",
        "ต้องตรวจเต็มทุก lot ตลอดไป เพราะ GMP ไม่อนุญาตให้ใช้ CoA ของผู้ผลิต",
        "ทำ audit ผู้ผลิตครั้งเดียวตอนเริ่มต้น หลังจากนั้นไม่ต้องทบทวนอีก",
      ],
      a: 0,
      r: "GMP อนุญาตให้ลดการทดสอบวัตถุดิบโดยอาศัย CoA ของผู้ผลิตได้ ถ้าระบบ supplier qualification แสดงความน่าเชื่อถือ ได้แก่ การประเมิน/ตรวจสอบผู้ผลิต (risk-based audit), การยืนยันว่า supply chain โปร่งใสและสืบย้อนถึงผู้ผลิตจริงได้, มี quality agreement, และการตรวจสอบความถูกต้องของ CoA ด้วยการทดสอบเต็มเป็นระยะ (CoA validation) แต่การทดสอบ identity ยังคงต้องทำตามข้อกำหนด GMP\n\nสถานะของผู้ขายต้องได้รับการทบทวนเป็นระยะ (re-qualification) โดยพิจารณาข้อมูลคุณภาพ เช่น การปฏิเสธ lot, complaint และผล audit",
      w: [
        "ถูก — ครอบคลุม qualification ผู้ผลิต, การยืนยันความน่าเชื่อถือ CoA เป็นระยะ และคง identity test",
        "การเป็นตัวแทนจำหน่ายรายใหญ่ไม่ใช่หลักฐานคุณภาพ ต้องสืบย้อนและประเมินผู้ผลิตจริง",
        "Identity test ไม่สามารถยกเลิกได้แม้ใช้ CoA เพราะเป็นการป้องกันการรับวัตถุดิบผิดชนิด",
        "GMP อนุญาต reduced testing ได้ภายใต้ระบบ supplier qualification ที่เหมาะสม",
        "Supplier qualification เป็น lifecycle ต้องมี re-evaluation และ periodic audit ตามความเสี่ยง",
      ],
      k: "Reduced testing ได้เมื่อ supplier qualified + CoA ถูก verify เป็นระยะ + ยังทำ identity test เสมอ",
      d: "hard",
      ref: "PIC/S GMP Guide PE 009 Part I Ch.5 (5.29–5.36) and Ch.7; ICH Q7 Section 7.3",
    },
  ],
  // Mock Set 2 — ชุดที่ 2
  [
    {
      t: "Preliminary hazard analysis use",
      p: "ทีมพัฒนาผลิตภัณฑ์อยู่ในช่วงต้นของโครงการ ยังมีข้อมูลกระบวนการและ design รายละเอียดน้อย ต้องการระบุ hazard หลักและจัดลำดับความเสี่ยงอย่างกว้างๆ เพื่อวางแผนการพัฒนา เครื่องมือ QRM ใดเหมาะสมที่สุด",
      o: [
        "Preliminary Hazard Analysis (PHA)",
        "Failure Mode, Effects and Criticality Analysis (FMECA) ระดับ component",
        "Hazard Analysis and Critical Control Points (HACCP)",
        "Fault Tree Analysis (FTA) ของ failure ที่เกิดขึ้นแล้ว",
        "Statistical process control chart",
      ],
      a: 0,
      r: "ICH Q9(R1) Annex I อธิบายว่า PHA ใช้ประสบการณ์หรือความรู้ที่มีเกี่ยวกับ hazard เพื่อระบุ hazard, สถานการณ์อันตราย และเหตุการณ์ที่อาจก่ออันตราย แล้วประเมินโอกาสเกิดและความรุนแรงอย่างกว้างๆ เหมาะกับช่วงต้นของการพัฒนาเมื่อข้อมูล design/procedure ยังน้อย\n\nผลของ PHA มักใช้เป็นฐานสำหรับการทำเครื่องมือที่ละเอียดกว่า เช่น FMEA หรือ HACCP เมื่อกระบวนการชัดเจนขึ้น",
      w: [
        "ถูก — PHA ออกแบบมาสำหรับช่วงต้นเมื่อข้อมูลรายละเอียดยังมีน้อย",
        "FMECA ต้องรู้รายละเอียดกระบวนการ/อุปกรณ์ระดับ component จึงไม่เหมาะกับช่วงต้น",
        "HACCP ต้องมี process flow ที่ชัดเจนเพื่อกำหนด CCP เหมาะกับกระบวนการที่กำหนดแล้ว",
        "FTA เป็นการวิเคราะห์ย้อนจาก top event มักใช้สอบสวนความล้มเหลวที่ชัดเจน ไม่ใช่การกวาด hazard แบบกว้าง",
        "SPC ใช้ติดตามความแปรปรวนของกระบวนการที่มีข้อมูลการผลิตแล้ว ไม่ใช่เครื่องมือระบุ hazard",
      ],
      k: "ข้อมูลน้อย ช่วงต้นโครงการ → PHA; กระบวนการชัดแล้ว → FMEA/HACCP; สืบสาเหตุ failure → FTA",
      d: "easy",
      ref: "ICH Q9(R1) Annex I.6 Preliminary Hazard Analysis",
    },
    {
      t: "HACCP principle sequence",
      p: "ในการประยุกต์ HACCP กับการควบคุม metal contamination ในสายการผลิตยาเม็ด ทีมได้ทำ hazard analysis และกำหนดให้ metal detector หลังเครื่องตอกเป็น Critical Control Point (CCP) แล้ว ขั้นตอนตามหลักการ HACCP ลำดับถัดไปคือข้อใด",
      o: [
        "กำหนด critical limits เช่น ขนาดของ test piece Fe/non-Fe/SS ที่ต้องตรวจจับและคัดออกได้",
        "กำหนด corrective actions เมื่อ CCP หลุดการควบคุม",
        "จัดทำ verification procedures เพื่อยืนยันว่าระบบ HACCP ทำงาน",
        "ทำ hazard analysis ใหม่ทั้งหมดอีกรอบ",
        "จัดทำระบบเอกสารและบันทึก",
      ],
      a: 0,
      r: "HACCP มี 7 หลักการตามลำดับ: (1) hazard analysis, (2) กำหนด CCP, (3) กำหนด critical limits, (4) กำหนดระบบ monitoring ของ CCP, (5) กำหนด corrective actions, (6) verification procedures, (7) documentation/record keeping\n\nเมื่อกำหนด CCP แล้วต้องกำหนดเกณฑ์ที่วัดได้ซึ่งแยกการยอมรับกับไม่ยอมรับ (critical limit) ก่อน จากนั้นจึงออกแบบการ monitoring และ corrective action ที่อ้างอิง limit นั้น",
      w: [
        "ถูก — หลักการที่ 3 ต่อจากการกำหนด CCP คือ critical limits",
        "Corrective actions เป็นหลักการที่ 5 ต้องมี limit และ monitoring ก่อน",
        "Verification เป็นหลักการที่ 6",
        "Hazard analysis ทำแล้วในหลักการที่ 1 ไม่ต้องเริ่มใหม่ เว้นแต่มีการเปลี่ยนแปลง",
        "Documentation เป็นหลักการที่ 7 (สุดท้าย)",
      ],
      k: "HACCP 7 principles: hazard analysis → CCP → critical limits → monitoring → corrective action → verification → records",
      d: "medium",
      ref: "ICH Q9(R1) Annex I.7 HACCP; WHO TRS 908 Annex 7 (Application of HACCP to pharmaceuticals)",
    },
    {
      t: "5 Why root cause identification",
      p: "ทีมใช้ 5 Why สอบสวนปัญหา tablet capping ได้ลำดับดังนี้: (1) capping เพราะ upper punch สึก → (2) punch สึกเพราะไม่ได้ทำ preventive maintenance ตามกำหนด → (3) ไม่ได้ทำ PM เพราะเครื่องตอกเครื่องนี้ไม่อยู่ในตาราง PM ของระบบ CMMS → (4) ไม่อยู่ในตารางเพราะตอนรับเครื่องใหม่ checklist ของ change control ไม่มีขั้นตอนลงทะเบียนเครื่องเข้า PM program ข้อใดคือ root cause ที่ควรแก้ด้วย CAPA",
      o: [
        "Checklist ของ change control สำหรับเครื่องจักรใหม่ไม่มีขั้นตอนลงทะเบียนเข้า PM program",
        "Upper punch สึก",
        "พนักงานซ่อมบำรุงละเลยการทำ PM",
        "Tablet capping",
        "เครื่องตอกเครื่องนี้คุณภาพต่ำ",
      ],
      a: 0,
      r: "5 Why เป็นการถาม 'ทำไม' ซ้ำจนถึงระดับที่เป็นสาเหตุเชิงระบบซึ่งถ้าแก้แล้วจะป้องกันการเกิดซ้ำได้ ไม่หยุดที่อาการ (symptom) หรือสาเหตุทางตรง (direct cause)\n\nในกรณีนี้ capping เป็นอาการ punch สึกเป็นสาเหตุทางตรง ส่วนช่องโหว่ของ change control checklist เป็น root cause เชิงระบบ การแก้แค่เปลี่ยน punch (correction) จะไม่ป้องกันเครื่องใหม่เครื่องอื่นตกหล่นจาก PM ในอนาคต",
      w: [
        "ถูก — เป็นสาเหตุเชิงระบบระดับลึกสุดที่ควบคุมได้ แก้แล้วป้องกันการเกิดซ้ำกับทุกเครื่อง",
        "Punch สึกเป็น direct cause แก้ด้วยการเปลี่ยน punch เป็นเพียง correction",
        "ข้อมูลไม่ได้บ่งชี้ว่าพนักงานละเลย เครื่องไม่อยู่ในตารางตั้งแต่ต้น การโทษคนเป็นข้อสรุปที่ผิด",
        "Capping คือปัญหา/อาการเริ่มต้น ไม่ใช่สาเหตุ",
        "ไม่มีหลักฐานจากการสอบสวนสนับสนุนว่าเครื่องคุณภาพต่ำ",
      ],
      k: "5 Why: ถามจนถึงสาเหตุเชิงระบบที่แก้แล้วป้องกันการเกิดซ้ำ ไม่หยุดที่ symptom หรือ human error",
      d: "easy",
      ref: "ICH Q10 Section 3.2.2; PIC/S GMP Guide PE 009 Part I Ch.1.4(xiv)",
    },
    {
      t: "Dose-based MACO per surface area",
      p: "ยา A (ผลิตก่อน) มี minimum therapeutic daily dose = 5 mg ยา B (ผลิตถัดไป) มี maximum daily dose = 1,200 mg และขนาด batch = 80 kg ใช้ safety factor 1/1,000 อุปกรณ์มีพื้นที่ผิวสัมผัสรวม 40,000 cm² acceptance limit ของ residue ยา A ต่อพื้นที่คือข้อใด",
      o: ["0.0083 µg/cm²", "0.83 µg/cm²", "8.3 µg/cm²", "83 µg/cm²", "833 µg/cm²"],
      a: 2,
      r: "Dose-based (therapeutic dose) criterion: MACO = (TDD_prev × MBS_next) / (SF × MDD_next) แนวคิดคือผู้ป่วยที่ได้ยา B ในขนาดสูงสุดต่อวัน ต้องไม่ได้รับยา A เกิน 1/1,000 ของขนาดรักษาต่ำสุด\n\nMACO = (5 mg × 80,000,000 mg) / (1,000 × 1,200 mg) = 333.3 mg แล้วหารพื้นที่รวม 40,000 cm² = 0.00833 mg/cm² = 8.3 µg/cm² ปัจจุบัน EMA แนะนำให้ใช้ HBEL/PDE แทน 1/1,000 ของ dose แต่สูตร dose-based ยังใช้กันแพร่หลายและออกสอบบ่อย",
      w: [
        "เป็นค่าที่ได้เมื่อไม่ได้แปลง mg เป็น µg (0.0083 คือหน่วย mg/cm²)",
        "เกิดจากใช้ safety factor 1/100,000 หรือคลาดเคลื่อนทศนิยม 10 เท่า",
        "ถูก — 333.3 mg ÷ 40,000 cm² = 8.3 µg/cm²",
        "เกิดจากใช้ safety factor 1/100 แทน 1/1,000",
        "เป็น limit ต่อ swab 100 cm² ไม่ใช่ต่อ cm²",
      ],
      k: "MACO = (TDD_prev × MBS_next)/(SF × MDD_next); ระวังแปลงหน่วย kg→mg และ mg→µg",
      d: "hard",
      ref: "PIC/S PI 006-3 Cleaning Validation; APIC Guidance on Aspects of Cleaning Validation in API Plants (2021)",
      c: [
        "MBS_B = 80 kg = 80,000,000 mg",
        "MACO = (5 × 80,000,000) ÷ (1,000 × 1,200) = 400,000,000 ÷ 1,200,000 = 333.3 mg",
        "Limit ต่อพื้นที่ = 333.3 mg ÷ 40,000 cm² = 0.00833 mg/cm² = 8.3 µg/cm²",
      ],
    },
    {
      t: "Number of PPQ batches rationale",
      p: "บริษัทกำลังวางแผน Process Performance Qualification (PPQ) ของยาเม็ดใหม่ ตามแนวคิด lifecycle validation (FDA 2011) การกำหนดจำนวน PPQ batches ควรอาศัยหลักการใด",
      o: [
        "อาศัยความรู้จาก Stage 1, ความแปรปรวนของกระบวนการ และ risk assessment พร้อมเหตุผลทางสถิติที่ระบุใน protocol",
        "ต้องเป็น 3 batches ติดต่อกันเสมอตามที่ guideline กำหนดตายตัว",
        "1 batch ก็เพียงพอถ้าผลผ่าน specification",
        "จำนวนเท่ากับจำนวน batches ที่ใช้ใน stability study",
        "ใช้จำนวนเท่าใดก็ได้ตามความสะดวกของฝ่ายผลิต โดยไม่ต้องให้เหตุผล",
      ],
      a: 0,
      r: "FDA Process Validation Guidance (2011) ไม่กำหนดจำนวน batch ตายตัว แต่ให้ผู้ผลิตให้เหตุผลว่าจำนวน PPQ batches และการสุ่มตัวอย่างเพียงพอต่อการแสดงว่ากระบวนการ reproducible ด้วยระดับความเชื่อมั่นที่เหมาะสม โดยพิจารณาความรู้จาก Stage 1 ความแปรปรวน ความซับซ้อนของกระบวนการ และประสบการณ์กับผลิตภัณฑ์ที่คล้ายกัน\n\nตัวเลข 3 batches เป็นธรรมเนียมเดิมและยังใช้อยู่บ่อยใน PIC/S Annex 15 สำหรับ traditional approach แต่ก็ต้องมีเหตุผลรองรับ ผลผ่าน specification เพียง batch เดียวไม่แสดง reproducibility",
      w: [
        "ถูก — จำนวน PPQ batches เป็นการตัดสินใจแบบ science/risk-based ที่ต้องให้เหตุผลใน protocol",
        "Guideline ไม่ได้บังคับ 3 batches ตายตัว แม้จะเป็นจำนวนที่ใช้บ่อย",
        "Batch เดียวไม่แสดงความสม่ำเสมอระหว่าง batch (inter-batch variability)",
        "Stability study และ PPQ มีวัตถุประสงค์ต่างกัน จำนวน batch ไม่ต้องเท่ากัน",
        "จำนวนต้องมีเหตุผลทางวิทยาศาสตร์/สถิติและอนุมัติโดย QA ไม่ใช่ตามความสะดวก",
      ],
      k: "จำนวน PPQ batches = science- and risk-based justification ไม่มีตัวเลขบังคับตายตัว",
      d: "medium",
      ref: "FDA Guidance: Process Validation — General Principles and Practices (2011), Section IV.C.2; PIC/S PE 009 Annex 15 Section 5",
    },
    {
      t: "GAMP 5 V-model test pairing",
      p: "ตาม V-model ใน GAMP 5 สำหรับการ validate ระบบคอมพิวเตอร์ (เช่น LIMS ที่ configure แล้ว) เอกสาร User Requirements Specification (URS) จับคู่กับการทดสอบระดับใด",
      o: [
        "Performance Qualification / User Acceptance Testing",
        "Installation Qualification",
        "Operational Qualification ของแต่ละ function",
        "Unit testing ของ source code",
        "Design Qualification",
      ],
      a: 0,
      r: "V-model แสดงด้านซ้ายเป็น specification จากระดับสูงลงล่าง (URS → Functional Specification → Design/Configuration Specification) และด้านขวาเป็นการ verification ที่จับคู่กันจากล่างขึ้นบน: Design/Configuration Spec ↔ IQ (installation/configuration verification), Functional Spec ↔ OQ (functional testing), URS ↔ PQ/UAT (ยืนยันว่าระบบตอบสนองความต้องการของผู้ใช้ในการใช้งานจริง)\n\nGAMP 5 เน้น risk-based และให้นำผลทดสอบของ supplier มาใช้ได้เพื่อลดงานซ้ำ",
      w: [
        "ถูก — URS ถูกยืนยันด้วย PQ/UAT ซึ่งทดสอบตาม business process ของผู้ใช้",
        "IQ จับคู่กับ design/configuration specification",
        "OQ จับคู่กับ functional specification",
        "Unit/code testing จับคู่กับ module design ใช้กับ custom software (Category 5)",
        "DQ เป็นการยืนยันว่า design ตรงกับ URS ก่อนติดตั้ง ไม่ใช่การทดสอบด้านขวาของ V",
      ],
      k: "V-model: URS ↔ PQ/UAT, FS ↔ OQ, DS/CS ↔ IQ",
      d: "medium",
      ref: "ISPE GAMP 5: A Risk-Based Approach to Compliant GxP Computerized Systems (2nd ed., 2022)",
    },
    {
      t: "Planned deviation versus change control",
      p: "ผู้ผลิต povidone รายเดิมขาดส่งชั่วคราว ฝ่ายจัดซื้อเสนอใช้ povidone เกรดเดียวกันจากผู้ผลิตอีกรายที่อยู่ในทะเบียนตำรับแล้ว (approved alternate source) สำหรับ 3 batches ถัดไปเท่านั้น จากนั้นจะกลับไปใช้ผู้ผลิตเดิม ข้อใดเป็นการจัดการเชิงระบบคุณภาพที่เหมาะสมที่สุด",
      o: [
        "ทำ planned deviation ที่มี risk assessment และ QA อนุมัติก่อนดำเนินการ ระบุจำนวน batch ขอบเขต และการติดตามผล",
        "ใช้ได้เลยโดยไม่ต้องบันทึก เพราะเป็นแหล่งที่อยู่ในทะเบียนแล้ว",
        "เปิด unplanned deviation หลังผลิตเสร็จทั้ง 3 batches",
        "ต้องยื่น variation ต่อหน่วยงานกำกับก่อนผลิตทุกครั้ง แม้เป็นแหล่งที่อนุมัติแล้ว",
        "ทำ change control ถาวรเพื่อเปลี่ยนผู้ผลิตหลัก แล้วค่อยเปลี่ยนกลับด้วย change control อีกครั้ง",
      ],
      a: 0,
      r: "Planned deviation ใช้กับการเบี่ยงเบนชั่วคราวที่รู้ล่วงหน้าและมีขอบเขตจำกัด (จำนวน batch/ระยะเวลา) จาก procedure หรือ MBR ที่อนุมัติ โดยต้องมี risk assessment และ QA อนุมัติก่อนดำเนินการ ส่วน change control ใช้กับการเปลี่ยนแปลงถาวรของระบบ/กระบวนการ\n\nเนื่องจากแหล่งทางเลือกอยู่ใน marketing authorization แล้ว จึงไม่ต้องยื่น variation แต่การผลิตจาก source ที่ไม่ใช่ตาม MBR ปัจจุบันยังต้องได้รับการควบคุม เช่น ยืนยัน supplier qualification ยังมีผล และพิจารณาการติดตามผล (เช่น เพิ่ม stability หรือ IPC) ตามความเสี่ยง การเปิด deviation หลังทำไปแล้วแสดงว่าระบบควบคุมล้มเหลว",
      w: [
        "ถูก — เหตุการณ์ชั่วคราว ทราบล่วงหน้า มีขอบเขตชัด เหมาะกับ planned deviation ที่อนุมัติก่อน",
        "การเบี่ยงเบนจาก MBR/ผู้ผลิตที่ระบุต้องมีการบันทึกและอนุมัติ แม้แหล่งอยู่ในทะเบียน",
        "เหตุการณ์ที่วางแผนได้ล่วงหน้าต้องอนุมัติก่อนทำ การเปิด deviation ย้อนหลังไม่เหมาะสม",
        "แหล่งที่ระบุใน MA อยู่แล้วไม่ต้องยื่น variation ใหม่",
        "การทำ change control สองรอบสำหรับการใช้ชั่วคราวเป็นภาระเกินจำเป็นและสื่อผิดว่าเป็นการเปลี่ยนถาวร",
      ],
      k: "ชั่วคราว + วางแผนล่วงหน้า + ขอบเขตจำกัด → planned deviation (อนุมัติก่อน); ถาวร → change control",
      d: "hard",
      ref: "ICH Q10 Section 3.2.3 (change management); PIC/S GMP Guide PE 009 Part I Ch.1.4",
    },
    {
      t: "Product quality review contents",
      p: "ในการจัดทำ Product Quality Review (PQR) ประจำปีตาม PIC/S GMP หัวข้อใด “ไม่ใช่” เนื้อหาที่ต้องทบทวน",
      o: [
        "ยอดขายและส่วนแบ่งการตลาดของผลิตภัณฑ์เทียบกับคู่แข่ง",
        "Batch ที่ไม่ผ่าน specification และผลการสอบสวน",
        "Change ที่เกิดขึ้นกับกระบวนการหรือวิธีวิเคราะห์",
        "ผลของ ongoing stability programme และแนวโน้มที่ไม่พึงประสงค์",
        "Complaint, การคืนสินค้า และการเรียกคืนที่เกี่ยวกับคุณภาพ",
      ],
      a: 0,
      r: "PQR มีวัตถุประสงค์เพื่อยืนยันความสม่ำเสมอของกระบวนการ ความเหมาะสมของ specification และหาแนวโน้มเพื่อปรับปรุง เนื้อหาตาม PIC/S Ch.1.10 ได้แก่ starting materials (โดยเฉพาะแหล่งใหม่), ผล IPC และ finished product ที่สำคัญ, batch ที่ล้มเหลวและการสอบสวน, deviation ที่สำคัญ, change, variation ต่อ MA, ผล stability, complaint/return/recall, ความเหมาะสมของ CAPA, post-marketing commitments, สถานะ qualification ของเครื่องจักร/utilities และ technical agreements\n\nข้อมูลเชิงการตลาดไม่เกี่ยวกับคุณภาพจึงไม่อยู่ใน PQR",
      w: [
        "ถูก — ยอดขาย/ส่วนแบ่งตลาดไม่ใช่ข้อมูลคุณภาพ ไม่ได้กำหนดให้อยู่ใน PQR",
        "Batch ที่ fail และการสอบสวนเป็นหัวข้อบังคับของ PQR",
        "Change ทั้งหมดที่เกิดในรอบปีต้องทบทวนใน PQR",
        "ผล ongoing stability และ adverse trend ต้องทบทวนใน PQR",
        "Complaint, return และ recall ที่เกี่ยวกับคุณภาพต้องทบทวนใน PQR",
      ],
      k: "PQR ทบทวนข้อมูลคุณภาพทั้งหมดของรอบปี (materials, IPC/FP results, deviations, changes, stability, complaints, CAPA, qualification) เพื่อหา trend",
      d: "medium",
      ref: "PIC/S GMP Guide PE 009 Part I Ch.1.10 Product Quality Review",
    },
    {
      t: "Recall classification and depth",
      p: "ผู้ผลิตพบว่ายาเม็ด warfarin 5 mg lot หนึ่งที่จำหน่ายไปแล้วมีบางเม็ดมีปริมาณตัวยาประมาณ 150% ของที่ระบุ เนื่องจาก segregation ของ blend การตัดสินใจเรื่อง recall ข้อใดเหมาะสมที่สุด",
      o: [
        "จัดเป็น recall ระดับร้ายแรงสูงสุด (Class I) และเรียกคืนถึงระดับผู้ป่วย/ผู้บริโภค",
        "จัดเป็น Class III และเรียกคืนเฉพาะระดับผู้แทนจำหน่าย",
        "จัดเป็น Class II เพราะยังไม่มีรายงานผู้ป่วยเลือดออก และเรียกคืนเฉพาะระดับร้านยา",
        "ไม่ต้อง recall แต่ให้ข้อมูลแพทย์ติดตาม INR ผู้ป่วยแทน",
        "รอผลการวิเคราะห์ retained sample ทั้งหมดและ PQR ประจำปีก่อนตัดสินใจ",
      ],
      a: 0,
      r: "การจัดระดับ recall อิงกับความเสี่ยงต่อสุขภาพ: Class I คือมีโอกาสสมเหตุสมผลที่จะทำให้เกิดผลเสียร้ายแรงหรือเสียชีวิต, Class II อาจทำให้เกิดผลเสียชั่วคราวหรือแก้ไขได้ทางการแพทย์, Class III ไม่น่าจะก่อผลเสียต่อสุขภาพ\n\nWarfarin เป็นยาดัชนีการรักษาแคบ การได้รับเกิน 50% อาจทำให้เลือดออกรุนแรง จึงเป็น Class I และความลึกของการเรียกคืนต้องถึงระดับผู้ป่วยเพราะยาอยู่ในมือผู้ใช้แล้ว การไม่มีรายงานผลเสียไม่ได้ลดระดับความเสี่ยง และการตัดสินใจต้องรวดเร็ว ไม่รอ PQR",
      w: [
        "ถูก — ยา NTI ได้รับเกินขนาดมีโอกาสเกิดอันตรายร้ายแรง ต้อง Class I และเรียกคืนถึงระดับผู้บริโภค",
        "Class III ใช้กับข้อบกพร่องที่ไม่น่าก่อผลเสีย เช่น ข้อผิดพลาดเล็กน้อยของบรรจุภัณฑ์",
        "การจัดระดับอิงศักยภาพความเสี่ยง ไม่ใช่การรอให้มีรายงานผู้ป่วย และการหยุดที่ร้านยาไม่ครอบคลุมยาที่ผู้ป่วยถืออยู่",
        "การแจ้งแพทย์ไม่ทดแทนการนำผลิตภัณฑ์บกพร่องออกจากตลาด",
        "การรอข้อมูลที่ไม่จำเป็นทำให้ผู้ป่วยได้รับความเสี่ยงนานขึ้น PQR ไม่ใช่เครื่องมือตัดสินใจ recall",
      ],
      k: "Recall class ขึ้นกับ health hazard (Class I = อันตรายร้ายแรง/เสียชีวิต); ความลึกของ recall ขึ้นกับว่ายาไปถึงระดับใด",
      d: "hard",
      ref: "PIC/S GMP Guide PE 009 Part I Ch.8 Complaints and Product Recalls; WHO TRS 961 Annex 9 / FDA 21 CFR 7.3(m)",
    },
    {
      t: "Lot acceptance and complaint rate metrics",
      p: "ในปีที่ผ่านมาโรงงานมี lot ที่ผ่านการพิจารณาปล่อย/ไม่ปล่อย (dispositioned) ทั้งหมด 250 lots ถูก reject 4 lots และจำหน่ายผลิตภัณฑ์ 5,000,000 หน่วย มี product quality complaint 35 เรื่อง ข้อใดคำนวณ quality metrics ได้ถูกต้อง",
      o: [
        "Lot acceptance rate 98.4% และ complaint rate 7 เรื่องต่อ 1 ล้านหน่วย",
        "Lot acceptance rate 1.6% และ complaint rate 7 เรื่องต่อ 1 ล้านหน่วย",
        "Lot acceptance rate 98.4% และ complaint rate 0.7 เรื่องต่อ 1 ล้านหน่วย",
        "Lot acceptance rate 96.0% และ complaint rate 70 เรื่องต่อ 1 ล้านหน่วย",
        "Lot acceptance rate 98.4% และ complaint rate 14% ของ lots",
      ],
      a: 0,
      r: "Quality metrics ที่ FDA เสนอในร่าง guidance ได้แก่ Lot Acceptance Rate (LAR) = จำนวน lot ที่ยอมรับ / จำนวน lot ที่ dispositioned, Product Quality Complaint Rate = จำนวน complaint / จำนวนหน่วยที่จำหน่าย (มักแสดงต่อ 1 ล้านหน่วย) และ Invalidated OOS rate\n\nLAR = (250 − 4)/250 = 98.4%; complaint rate = 35/5,000,000 × 1,000,000 = 7 ต่อล้านหน่วย Metrics เหล่านี้ใช้ใน management review เพื่อดูแนวโน้มประสิทธิภาพของ PQS และควรตีความร่วมกับข้อมูลอื่น ไม่ใช่ตัวเลขเดี่ยว",
      w: [
        "ถูก — 246/250 = 98.4% และ 35 ÷ 5 ล้าน = 7 ต่อล้านหน่วย",
        "1.6% คือ lot rejection rate ไม่ใช่ acceptance rate",
        "Complaint rate คำนวณผิดหลักทศนิยม 10 เท่า",
        "96.0% เกิดจากใช้ 10 lots เป็นจำนวน reject และ complaint rate คลาดเคลื่อน 10 เท่า",
        "Complaint rate ต้องเทียบกับจำนวนหน่วยที่จำหน่าย ไม่ใช่จำนวน lot",
      ],
      k: "LAR = accepted lots / dispositioned lots; complaint rate = complaints / units distributed (ต่อล้านหน่วย)",
      d: "medium",
      ref: "FDA Draft Guidance: Submission of Quality Metrics Data (2016); ICH Q10 Section 4.1 (management review)",
      c: [
        "Accepted lots = 250 − 4 = 246",
        "LAR = 246 ÷ 250 × 100 = 98.4%",
        "Complaint rate = 35 ÷ 5,000,000 × 1,000,000 = 7 ต่อ 1 ล้านหน่วย",
      ],
    },
  ],
  // Mock Set 3 — ชุดที่ 3
  [
    {
      t: "Fault tree analysis logic",
      p: "ทีม QA ใช้ Fault Tree Analysis (FTA) สอบสวนเหตุการณ์ “พบอนุภาคโลหะในยาเม็ด” ข้อใดอธิบายลักษณะของ FTA ได้ถูกต้องที่สุด",
      o: [
        "เริ่มจาก top event แล้ววิเคราะห์ย้อนลงหาสาเหตุ โดยใช้ AND/OR gate แสดงว่าสาเหตุต้องเกิดร่วมกันหรือเกิดเพียงอย่างเดียวก็พอ",
        "เริ่มจาก failure ของแต่ละ component แล้วไล่ไปข้างหน้าหาผลกระทบ พร้อมให้คะแนน RPN",
        "ใช้แผนภาพก้างปลาจัดสาเหตุตามหมวด 6M โดยไม่มีตรรกะเชื่อมโยง",
        "เป็นการจัดลำดับความเสี่ยงด้วยการเปรียบเทียบเป็นคู่ (pairwise comparison)",
        "ใช้ระบุจุดควบคุมวิกฤตและกำหนด critical limits ในกระบวนการ",
      ],
      a: 0,
      r: "FTA เป็นวิธี top-down (deductive): กำหนด undesired event ไว้ด้านบน แล้วแตกลงเป็นสาเหตุที่เป็นไปได้ด้วย logic gate — OR gate หมายถึงสาเหตุใดสาเหตุหนึ่งทำให้เกิดเหตุการณ์ด้านบนได้, AND gate หมายถึงต้องเกิดร่วมกัน เหมาะกับการสอบสวน complaint/deviation และการประเมินว่ามีหลายสาเหตุร่วมกันหรือไม่\n\nตรงข้ามกับ FMEA ที่เป็น bottom-up (inductive) เริ่มจาก failure mode ของแต่ละขั้นแล้วหาผลกระทบ การรู้ว่า AND gate มี redundancy ช่วยให้เห็นว่าการควบคุมซ้อนกันลดความน่าจะเป็นของ top event ได้อย่างไร",
      w: [
        "ถูก — FTA เป็น top-down และใช้ logic gate AND/OR",
        "นี่คือ FMEA ซึ่งเป็นแบบ bottom-up และใช้ RPN",
        "นี่คือ Ishikawa diagram ซึ่งไม่มี logic gate",
        "Pairwise comparison เป็นเทคนิคของ risk ranking and filtering",
        "การกำหนด CCP และ critical limits เป็น HACCP",
      ],
      k: "FTA = top-down + AND/OR gates; FMEA = bottom-up + RPN",
      d: "medium",
      ref: "ICH Q9(R1) Annex I.5 Fault Tree Analysis",
    },
    {
      t: "ICH Q10 PQS elements",
      p: "ICH Q10 กำหนด Pharmaceutical Quality System elements หลัก 4 ประการ ข้อใดถูกต้อง",
      o: [
        "Process performance & product quality monitoring, CAPA, change management, และ management review",
        "Quality risk management, knowledge management, CAPA และ validation",
        "Deviation, OOS, complaint และ recall",
        "GMP, GLP, GCP และ GDP",
        "Documentation, training, self-inspection และ supplier audit",
      ],
      a: 0,
      r: "ICH Q10 Section 3.2 ระบุ PQS elements 4 ประการ คือ (1) process performance and product quality monitoring system, (2) corrective action and preventive action (CAPA) system, (3) change management system และ (4) management review of process performance and product quality โดยใช้ตลอด lifecycle ของผลิตภัณฑ์\n\nส่วน knowledge management และ quality risk management เป็น enablers ที่ช่วยให้ PQS บรรลุเป้าหมาย ไม่ใช่ elements",
      w: [
        "ถูก — 4 elements ตาม ICH Q10 Section 3.2",
        "QRM และ knowledge management เป็น enablers ส่วน validation ไม่ได้ถูกระบุเป็น element",
        "Deviation, OOS, complaint และ recall เป็น input ของ CAPA/monitoring ไม่ใช่ elements",
        "GxP เป็นกฎเกณฑ์คนละระดับ ไม่ใช่ elements ของ PQS",
        "เป็นระบบสนับสนุนของ GMP ไม่ใช่ 4 elements ที่ ICH Q10 กำหนด",
      ],
      k: "ICH Q10 elements = monitoring, CAPA, change management, management review; enablers = KM + QRM",
      d: "easy",
      ref: "ICH Q10 Pharmaceutical Quality System, Section 3.2 and 1.6",
    },
    {
      t: "Management review outputs",
      p: "ในการประชุม management review ของ PQS ตาม ICH Q10 ข้อใดเป็น “output” ที่คาดหวังจากการทบทวน",
      o: [
        "การตัดสินใจจัดสรรทรัพยากร การปรับปรุงกระบวนการ/ผลิตภัณฑ์ และการปรับปรุง PQS",
        "ผลการตรวจประเมินภายในและผลการตรวจของหน่วยงานกำกับ",
        "ข้อมูล complaint และ recall ในรอบที่ผ่านมา",
        "ผล PQR และ process capability ของผลิตภัณฑ์",
        "ผลการติดตาม CAPA effectiveness",
      ],
      a: 0,
      r: "Management review ต้องมี input เช่น ผล regulatory inspection/audit, PQR, complaint/recall, CAPA effectiveness, ผล process performance monitoring, quality metrics และ output ที่เป็นการตัดสินใจของผู้บริหารระดับสูง เช่น การปรับปรุงกระบวนการและผลิตภัณฑ์, การจัดสรร/ฝึกอบรมทรัพยากร, การทบทวนนโยบายและวัตถุประสงค์คุณภาพ\n\nหัวใจคือ senior management มีความรับผิดชอบสูงสุดต่อ PQS (management responsibility) ผลของการทบทวนต้องนำไปสู่ action ที่บันทึกและติดตามได้",
      w: [
        "ถูก — output ของ management review คือการตัดสินใจ/action ด้านทรัพยากรและการปรับปรุง",
        "ผล audit/inspection เป็น input ของการทบทวน",
        "ข้อมูล complaint และ recall เป็น input",
        "PQR และ process capability เป็น input",
        "ผล CAPA effectiveness เป็น input เพื่อประกอบการตัดสินใจ",
      ],
      k: "Management review: input = ข้อมูลคุณภาพ (audit, PQR, complaints, CAPA, metrics); output = decisions & resources for improvement",
      d: "medium",
      ref: "ICH Q10 Section 2.6 and 4.1–4.2",
    },
    {
      t: "PDE derivation with adjustment factors",
      p: "สารออกฤทธิ์ที่ใช้เครื่องมือร่วมกันมี NOAEL จากการศึกษาพิษเรื้อรัง 2 ปีในหนูขาว (rat) = 0.5 mg/kg/day ใช้น้ำหนักตัว 50 kg และ adjustment factors F1 = 5 (rat→human), F2 = 10 (inter-individual), F3 = 1, F4 = 1, F5 = 1 ค่า Permitted Daily Exposure (PDE) คือข้อใด",
      o: ["0.1 mg/day", "0.5 mg/day", "2.5 mg/day", "5 mg/day", "25 mg/day"],
      a: 1,
      r: "PDE = (NOAEL × body weight) / (F1 × F2 × F3 × F4 × F5) ตามแนวทาง ICH Q3C ที่ EMA นำมาใช้กับการกำหนด HBEL สำหรับ shared facilities โดย F1 = ความต่างระหว่าง species, F2 = ความแปรปรวนระหว่างบุคคล, F3 = ระยะเวลาการศึกษา (ศึกษาเรื้อรังตลอดช่วงชีวิตได้ 1), F4 = ความรุนแรงของพิษ (เช่น teratogenic/carcinogenic), F5 = ใช้ LOAEL แทน NOAEL\n\nPDE = (0.5 × 50)/(5 × 10 × 1 × 1 × 1) = 25/50 = 0.5 mg/day ค่า PDE นี้นำไปคำนวณ MACO = PDE × MBS_next / MDD_next และเป็นฐานของ cleaning limit ตามแนวคิด HBEL ปัจจุบัน",
      w: [
        "เกิดจากใส่ F3 = 5 ซึ่งใช้กับการศึกษาระยะสั้น ไม่ใช่ศึกษาเรื้อรัง 2 ปี",
        "ถูก — 25 ÷ 50 = 0.5 mg/day",
        "เกิดจากลืมหารด้วย F1 = 5 (ใช้แค่ F2 = 10)",
        "เกิดจากลืมหารด้วย F2 = 10 (ใช้แค่ F1 = 5)",
        "เป็น NOAEL × น้ำหนักตัว โดยไม่ใช้ adjustment factor เลย",
      ],
      k: "PDE = NOAEL × BW / (F1×F2×F3×F4×F5); เป็นฐานของ HBEL cleaning limits",
      d: "hard",
      ref: "EMA Guideline on setting health based exposure limits for use in risk identification in the manufacture of different medicinal products in shared facilities (EMA/CHMP/CVMP/SWP/169430/2012); ICH Q3C(R8) Appendix 3",
      c: [
        "NOAEL × BW = 0.5 mg/kg/day × 50 kg = 25 mg/day",
        "ผลคูณ F = 5 × 10 × 1 × 1 × 1 = 50",
        "PDE = 25 ÷ 50 = 0.5 mg/day",
      ],
    },
    {
      t: "Swab recovery factor correction",
      p: "ผลวิเคราะห์ swab จากจุด worst-case (พื้นที่ 25 cm²) พบ residue 3.2 µg ต่อ swab จาก recovery study บนพื้นผิว stainless steel ได้ recovery 80% หาก acceptance limit คือ 0.15 µg/cm² ข้อใดสรุปผลถูกต้อง",
      o: [
        "0.102 µg/cm² ผ่านเกณฑ์",
        "0.128 µg/cm² ผ่านเกณฑ์",
        "0.16 µg/cm² ไม่ผ่านเกณฑ์",
        "0.16 µg/cm² ผ่านเกณฑ์ เพราะต่างจาก limit ไม่ถึง 10%",
        "4.0 µg/cm² ไม่ผ่านเกณฑ์",
      ],
      a: 2,
      r: "Swab sampling เก็บ residue กลับมาได้ไม่ครบ 100% จึงต้องทำ recovery study (spiking พื้นผิววัสดุเดียวกันที่ระดับใกล้ limit) แล้วแก้ค่าผลจริงด้วย recovery factor: ค่าแท้จริง = ค่าที่วัดได้ ÷ recovery\n\n3.2 ÷ 0.80 = 4.0 µg ต่อ swab ÷ 25 cm² = 0.16 µg/cm² ซึ่งเกิน 0.15 µg/cm² จึงไม่ผ่าน การไม่แก้ค่า recovery ทำให้ประเมิน residue ต่ำเกินจริง (0.128) และสรุปผ่านอย่างผิดๆ โดยทั่วไป recovery ที่ยอมรับได้มักกำหนด ≥ 70% หรือตามที่ validate ไว้ ถ้าต่ำกว่านั้นควรปรับวิธี swab",
      w: [
        "เกิดจากคูณด้วย recovery (3.2 × 0.8) แทนการหาร ทำให้ค่าต่ำลงผิดทิศ",
        "ไม่ได้แก้ค่าด้วย recovery factor ทำให้ประเมิน residue ต่ำกว่าความจริง",
        "ถูก — 3.2/0.8 = 4.0 µg; 4.0/25 = 0.16 µg/cm² > 0.15 จึงไม่ผ่าน",
        "Acceptance limit เป็นค่าสูงสุด ไม่มี tolerance ±10% ให้ปัดผ่าน",
        "ลืมหารด้วยพื้นที่ swab 25 cm² (4.0 µg คือค่าต่อ swab)",
      ],
      k: "ค่าที่แก้แล้ว = ค่าที่วัดได้ ÷ recovery; หารพื้นที่ swab แล้วเทียบ limit ต่อ cm²",
      d: "medium",
      ref: "PIC/S PI 006-3 Cleaning Validation (sampling & recovery); APIC Cleaning Validation Guidance (2021) Section 8",
      c: [
        "ค่าที่แก้ recovery = 3.2 µg ÷ 0.80 = 4.0 µg ต่อ swab",
        "ต่อพื้นที่ = 4.0 µg ÷ 25 cm² = 0.16 µg/cm²",
        "0.16 > 0.15 µg/cm² → ไม่ผ่านเกณฑ์",
      ],
    },
    {
      t: "Equipment requalification triggers",
      p: "Tablet press ที่ผ่าน IQ/OQ/PQ มาแล้ว 3 ปี มีการเปลี่ยนแปลงต่อไปนี้ เหตุการณ์ใดควรนำไปสู่การ requalification (อย่างน้อยบางส่วน) ผ่านระบบ change control มากที่สุด",
      o: [
        "เปลี่ยนระบบ force-feeder และ software ควบคุมน้ำหนักเม็ดเป็นรุ่นใหม่",
        "เปลี่ยน punch ชุดใหม่ที่มี specification เหมือนเดิมทุกประการ (like-for-like)",
        "ทำความสะอาดเครื่องตามรอบ SOP",
        "เปลี่ยนผู้ควบคุมเครื่องที่ผ่านการฝึกอบรมแล้ว",
        "ปรับ turret speed ภายในช่วงที่ validate ไว้แล้ว",
      ],
      a: 0,
      r: "สถานะ qualified ต้องคงอยู่ตลอด lifecycle ของเครื่อง การเปลี่ยนแปลงที่อาจกระทบการทำงานหรือคุณภาพผลิตภัณฑ์ต้องผ่าน change control และประเมินขอบเขตของ requalification ตามความเสี่ยง รวมถึงการทบทวนเป็นระยะ (periodic review) ว่ายังอยู่ใน qualified state\n\nการเปลี่ยน feeder และ software ควบคุมน้ำหนักกระทบ function สำคัญ ต้องทำ IQ/OQ บางส่วนและอาจต้อง PQ/CSV ส่วน like-for-like replacement, การทำงานตามปกติ และการปรับพารามิเตอร์ภายในช่วงที่ validate แล้ว ไม่ต้อง requalify",
      w: [
        "ถูก — เปลี่ยน hardware/software ที่ควบคุม CQA (น้ำหนักเม็ด) ต้องประเมินและ requalify ผ่าน change control",
        "Like-for-like replacement จัดการผ่าน maintenance โดยไม่ต้อง requalification",
        "การทำความสะอาดตาม SOP เป็นกิจกรรมปกติที่ validate แล้ว",
        "การเปลี่ยนผู้ควบคุมที่ฝึกอบรมแล้วไม่ใช่การเปลี่ยนแปลงของเครื่อง",
        "การทำงานภายใน proven acceptable range ไม่ถือเป็นการเปลี่ยนแปลงที่ต้อง requalify",
      ],
      k: "Requalification: เมื่อมี change ที่อาจกระทบ function/คุณภาพ (ผ่าน change control) และ periodic review; like-for-like ไม่ต้อง",
      d: "medium",
      ref: "PIC/S GMP Guide PE 009 Annex 15 Section 4 (Re-qualification) and Section 11 (Change control)",
    },
    {
      t: "Concurrent validation justification",
      p: "สถานการณ์ใดที่ concurrent validation (ปล่อย batch PPQ ก่อนที่ validation ทั้งโครงการจะเสร็จ) อาจยอมรับได้ตาม PIC/S Annex 15",
      o: [
        "ผลิตยาที่มีความจำเป็นต่อผู้ป่วยในภาวะขาดแคลน (strong benefit-risk) โดยมีเหตุผลบันทึกใน VMP และ QA/AP อนุมัติ",
        "ต้องการลดต้นทุนการเก็บ stock ระหว่างรอผล validation",
        "เป็นผลิตภัณฑ์ใหม่ที่ยังไม่มีข้อมูล Stage 1 เพียงพอ",
        "ฝ่ายขายต้องการวางตลาดให้ทันแคมเปญ",
        "เมื่อ PPQ batch แรกไม่ผ่าน specification และต้องการปล่อย batch ที่สองก่อน",
      ],
      a: 0,
      r: "Annex 15 ระบุว่าในสถานการณ์พิเศษที่มี benefit-risk ต่อผู้ป่วยสูง (เช่น ยาจำเป็นที่ขาดแคลน) อาจยอมรับการไม่รอให้ validation programme เสร็จก่อนผลิตเพื่อจำหน่าย (concurrent validation) ได้ แต่ต้องมีเหตุผลบันทึกใน VMP เพื่อให้เห็นชัดเจน และ AP อนุมัติ โดยแต่ละ batch ต้องมีข้อมูลเพียงพอสนับสนุนว่าเป็นไปตามข้อกำหนด\n\nเหตุผลทางธุรกิจหรือการตลาดไม่ใช่เหตุผลที่ยอมรับได้",
      w: [
        "ถูก — ต้องมี benefit-risk ต่อผู้ป่วยชัดเจน บันทึกใน VMP และ AP อนุมัติ",
        "การลดต้นทุนเป็นเหตุผลทางธุรกิจ ไม่ใช่ข้อยกเว้นที่ GMP ยอมรับ",
        "การขาดความรู้จาก Stage 1 ยิ่งเพิ่มความเสี่ยง ไม่ใช่เหตุผลสำหรับ concurrent validation",
        "แรงกดดันทางการตลาดไม่ใช่เหตุผลที่ยอมรับได้",
        "เมื่อ PPQ ล้มเหลวต้องสอบสวน root cause ก่อน ไม่ใช่เร่งปล่อย batch ถัดไป",
      ],
      k: "Concurrent validation = ข้อยกเว้นเพื่อประโยชน์ผู้ป่วยเท่านั้น ต้อง justify ใน VMP และ AP อนุมัติ",
      d: "medium",
      ref: "PIC/S GMP Guide PE 009 Annex 15 Section 5.27–5.29 (Concurrent validation)",
    },
    {
      t: "Self-inspection independence",
      p: "ข้อใดเป็นหลักการที่ถูกต้องของโปรแกรม self-inspection (internal audit) ตาม GMP",
      o: [
        "ดำเนินการตามแผนที่กำหนดล่วงหน้า โดยผู้ตรวจที่เป็นอิสระจากพื้นที่ที่ถูกตรวจ และบันทึกข้อบกพร่องพร้อม CAPA",
        "ให้หัวหน้าแต่ละแผนกตรวจพื้นที่ของตนเองเพื่อความรวดเร็ว",
        "ทำเฉพาะเมื่อทราบว่าจะมีหน่วยงานกำกับมาตรวจ",
        "ตรวจเฉพาะฝ่ายผลิต ไม่ต้องครอบคลุม QC หรือคลังสินค้า",
        "บันทึกเฉพาะข้อบกพร่องร้ายแรง ส่วนข้อเล็กน้อยแจ้งด้วยวาจา",
      ],
      a: 0,
      r: "PIC/S GMP Ch.9 กำหนดให้มี self-inspection เพื่อติดตามการปฏิบัติตาม GMP และเสนอ corrective action โดยครอบคลุมทุกเรื่อง (personnel, premises, equipment, documentation, production, QC, distribution, complaints/recalls, self-inspection) ตามแผนที่กำหนดล่วงหน้า ผู้ตรวจต้องเป็นอิสระ (independent) และทำอย่างละเอียด\n\nผลการตรวจทั้งหมดต้องบันทึก รายงานต้องมีข้อสังเกตและข้อเสนอ corrective measures และมีการติดตามผล ข้อมูลนี้เป็น input สำคัญของ management review",
      w: [
        "ถูก — มีแผน, ผู้ตรวจอิสระ, บันทึกและติดตาม CAPA",
        "การตรวจพื้นที่ตนเองขาดความเป็นอิสระ ทำให้มองไม่เห็นปัญหา",
        "Self-inspection ต้องเป็นโปรแกรมต่อเนื่องตามแผน ไม่ใช่เตรียมรับการตรวจเท่านั้น",
        "ต้องครอบคลุมทุกระบบที่เกี่ยวกับ GMP รวมถึง QC และคลังสินค้า",
        "ผลการตรวจทุกข้อต้องบันทึกเป็นลายลักษณ์อักษร",
      ],
      k: "Self-inspection: ตามแผน ครอบคลุมทุกระบบ ผู้ตรวจอิสระ บันทึกและติดตาม CAPA",
      d: "easy",
      ref: "PIC/S GMP Guide PE 009 Part I Ch.9 Self Inspection",
    },
    {
      t: "Quality agreement for outsourced manufacturing",
      p: "บริษัท A (ผู้รับอนุญาตทะเบียนตำรับ) ว่าจ้างบริษัท B ผลิตยาเม็ดแบบ contract manufacturing ข้อใดเป็นการแบ่งความรับผิดชอบด้านคุณภาพที่ถูกต้องที่สุดตาม GMP",
      o: [
        "A ยังคงรับผิดชอบต่อคุณภาพผลิตภัณฑ์ ต้องประเมินความสามารถของ B ก่อนว่าจ้าง ทำ written quality agreement ระบุหน้าที่ชัดเจน และติดตามผลงานของ B",
        "เมื่อทำสัญญาแล้ว ความรับผิดชอบด้านคุณภาพทั้งหมดโอนไปที่ B",
        "B สามารถจ้างช่วงต่อ (subcontract) ให้บริษัท C ได้โดยไม่ต้องแจ้ง A",
        "A ไม่จำเป็นต้อง audit B ถ้า B มีใบรับรอง GMP จากหน่วยงานกำกับ",
        "Quality agreement เป็นเพียงเอกสารทางการค้า ระบุราคาและเวลาส่งมอบก็เพียงพอ",
      ],
      a: 0,
      r: "PIC/S GMP Ch.7 Outsourced Activities กำหนดว่า contract giver รับผิดชอบสูงสุดต่อการจัดการกิจกรรมที่ว่าจ้าง ต้องประเมินความถูกต้องตามกฎหมาย ความเหมาะสม และความสามารถของ contract acceptor ก่อน (เช่น audit), จัดทำ written contract/technical (quality) agreement ที่ระบุชัดเจนว่าใครทำอะไร รวมถึงใครรับรองปล่อย batch, และติดตาม/ทบทวนผลการปฏิบัติงานอย่างต่อเนื่อง\n\nContract acceptor ห้ามจ้างช่วงต่อโดยไม่ได้รับการประเมินและอนุมัติล่วงหน้าจาก contract giver ใบรับรอง GMP ช่วยในการประเมินแต่ไม่ทดแทนความรับผิดชอบในการประเมินของผู้ว่าจ้าง",
      w: [
        "ถูก — ผู้ว่าจ้างยังรับผิดชอบ ต้องประเมินก่อน มี quality agreement และติดตามผล",
        "ความรับผิดชอบต่อคุณภาพและต่อทะเบียนไม่โอนไปกับสัญญา",
        "การจ้างช่วงต้องได้รับการประเมินและอนุมัติล่วงหน้าจากผู้ว่าจ้าง",
        "GMP certificate เป็นข้อมูลประกอบ แต่ผู้ว่าจ้างยังต้องประเมิน B ตามความเสี่ยงของผลิตภัณฑ์ตนเอง",
        "Quality agreement ต้องระบุความรับผิดชอบด้าน GMP เช่น การปล่อย batch การจัดการ deviation/change ไม่ใช่เรื่องการค้า",
      ],
      k: "Outsourcing: contract giver รับผิดชอบสูงสุด → assess, quality agreement, monitor; ห้าม subcontract โดยไม่อนุมัติ",
      d: "hard",
      ref: "PIC/S GMP Guide PE 009 Part I Ch.7 Outsourced Activities; ICH Q10 Section 2.7",
    },
    {
      t: "Human error as root cause",
      p: "การสอบสวน deviation ที่พนักงานตั้งค่าเวลาผสมผิดจาก 10 นาทีเป็น 100 นาทีในเครื่องผสม สรุปว่า root cause คือ “human error” และ CAPA คือ “ฝึกอบรมพนักงานซ้ำ” ในฐานะ QA ผู้ทบทวน ควรตอบสนองอย่างไรเหมาะสมที่สุด",
      o: [
        "ส่งกลับให้สอบสวนเพิ่มว่าทำไมระบบจึงยอมให้เกิด error นี้ เช่น ไม่มี limit/confirmation ใน HMI หรือ SOP ไม่ชัด แล้วกำหนด CAPA เชิงระบบ",
        "อนุมัติปิด deviation เพราะพนักงานยอมรับว่าทำผิดแล้ว",
        "อนุมัติและเพิ่มการลงโทษทางวินัยเพื่อป้องกันการเกิดซ้ำ",
        "อนุมัติหาก batch ผ่าน specification แม้ root cause จะไม่ชัดเจน",
        "ให้เปลี่ยนพนักงานคนนั้นไปทำงานอื่น แล้วปิด deviation",
      ],
      a: 0,
      r: "Human error มักเป็นอาการของปัญหาเชิงระบบ ไม่ใช่ root cause สุดท้าย หน่วยงานกำกับและ PIC/S เน้นว่าการสรุปว่า human error ควรมีการสอบสวนที่เหมาะสมเพื่อหาปัจจัยที่ทำให้เกิด (human factors) เช่น การออกแบบ HMI ที่ให้ใส่ค่าได้ไม่จำกัด, ไม่มี double check, SOP กำกวม, ภาระงาน/ความเหนื่อยล้า\n\nCAPA ที่ดีควรเป็นการควบคุมเชิงวิศวกรรมหรือระบบ (เช่น recipe lock, จำกัดช่วงค่าที่ใส่ได้, การยืนยันค่าโดยคนที่สอง) ซึ่งมีประสิทธิภาพมากกว่าการฝึกอบรมซ้ำหรือการลงโทษ และต้องประเมินผลกระทบต่อคุณภาพของ batch แยกต่างหาก",
      w: [
        "ถูก — ขุดหาสาเหตุเชิงระบบที่ทำให้ error เกิดได้ และใช้ CAPA ที่ป้องกันได้จริง",
        "การยอมรับผิดไม่ใช่หลักฐานของ root cause และการฝึกซ้ำมักไม่ป้องกันการเกิดซ้ำ",
        "การลงโทษไม่แก้ปัจจัยเชิงระบบ และทำให้คนไม่กล้ารายงาน deviation",
        "ผลผ่าน specification ไม่ทดแทนการหา root cause และไม่ป้องกันการเกิดซ้ำ",
        "เปลี่ยนคนไม่แก้ช่องโหว่ของระบบ พนักงานคนใหม่ก็ผิดซ้ำได้",
      ],
      k: "Human error ≠ root cause สุดท้าย; ถามต่อว่าระบบเปิดโอกาสให้ผิดได้อย่างไร แล้วใช้ engineering/system controls",
      d: "hard",
      ref: "PIC/S GMP Guide PE 009 Part I Ch.1.4(xiv); ICH Q10 Section 3.2.2",
    },
  ],
  // Mock Set 4 — ชุดที่ 4
  [
    {
      t: "FMEA detectability scoring",
      p: "ใน FMEA ของสายบรรจุยาเม็ดลงขวด failure mode “จำนวนเม็ดในขวดไม่ครบ” ถ้าเปลี่ยนการควบคุมจากสุ่มตรวจด้วยสายตาเป็นการชั่งน้ำหนักทุกขวดด้วย in-line checkweigher ที่ reject อัตโนมัติ คะแนน Detectability (D) ควรเปลี่ยนไปอย่างไร",
      o: [
        "D ลดลง เพราะโอกาสที่ข้อบกพร่องจะหลุดรอดไปถึงผู้ใช้ลดลง",
        "D เพิ่มขึ้น เพราะมีการตรวจที่ละเอียดขึ้น",
        "D ไม่เปลี่ยน แต่ Severity ลดลง",
        "D ไม่เปลี่ยน แต่ Occurrence ลดลงเป็น 1",
        "D ลดลงเป็น 0 ทำให้ RPN เป็นศูนย์",
      ],
      a: 0,
      r: "ใน FMEA สเกล Detectability มักกำหนดให้คะแนนสูง = ตรวจจับได้ยาก (โอกาสหลุดรอดสูง) และคะแนนต่ำ = ตรวจจับได้แน่นอนก่อนถึงผู้ใช้ ดังนั้นการเพิ่มการตรวจ 100% แบบอัตโนมัติที่ reject ได้ทำให้ D ลดลงและ RPN ลดลง\n\nการตรวจจับไม่ได้ลด Severity (ผลต่อผู้ป่วยถ้าเกิดขึ้นยังเท่าเดิม) และไม่ได้ลด Occurrence (ความถี่ที่กระบวนการเกิด failure ยังเท่าเดิม) ต้องแก้ที่กระบวนการต้นทางถ้าต้องการลด O สเกลมักเริ่มที่ 1 จึงไม่มีค่า 0",
      w: [
        "ถูก — การตรวจจับดีขึ้นทำให้คะแนน D ต่ำลง (D สูง = ตรวจจับยาก)",
        "สับสนทิศของสเกล D สูงหมายถึงตรวจจับได้ยาก",
        "Severity ขึ้นกับผลกระทบถ้าเกิด failure ไม่เปลี่ยนเพราะมีการตรวจจับ",
        "การตรวจจับไม่ได้ลดความถี่ที่กระบวนการผลิตเกิด failure",
        "สเกลคะแนนเริ่มที่ 1 และไม่มีระบบตรวจจับใดสมบูรณ์จน RPN เป็นศูนย์",
      ],
      k: "D สูง = ตรวจจับยาก; detection controls ลด D เท่านั้น ไม่ลด S หรือ O",
      d: "easy",
      ref: "ICH Q9(R1) Annex I.2 FMEA; IEC 60812:2018",
    },
    {
      t: "Documentation hierarchy levels",
      p: "ในลำดับชั้นเอกสารของระบบคุณภาพ เอกสารใดอยู่ระดับสูงสุดและบรรยายนโยบายคุณภาพ ขอบเขต และโครงสร้างของ Pharmaceutical Quality System ขององค์กร",
      o: [
        "Quality Manual",
        "Standard Operating Procedure (SOP)",
        "Work instruction",
        "Batch manufacturing record",
        "Logbook ของเครื่องมือ",
      ],
      a: 0,
      r: "เอกสารระบบคุณภาพจัดเป็นลำดับชั้น: Quality Manual (นโยบายคุณภาพ, ขอบเขต, โครงสร้าง PQS, ความรับผิดชอบของผู้บริหาร) → policies/SOPs (กระบวนการว่าทำอะไร ใคร เมื่อไร) → work instructions/methods (ทำอย่างไรในรายละเอียด) → records/forms (หลักฐานว่าทำแล้ว เช่น BMR, logbook)\n\nICH Q10 ระบุให้มี Quality Manual หรือเอกสารเทียบเท่าที่บรรยาย PQS เอกสารระดับล่างต้องสอดคล้องกับระดับบน",
      w: [
        "ถูก — Quality Manual เป็นเอกสารระดับสูงสุดที่บรรยายนโยบายและ PQS",
        "SOP อธิบายขั้นตอนการปฏิบัติงาน อยู่ระดับรองลงมา",
        "Work instruction ให้รายละเอียดวิธีทำงานเฉพาะ อยู่ต่ำกว่า SOP",
        "BMR เป็น record/หลักฐานการผลิตแต่ละ batch อยู่ระดับล่าง",
        "Logbook เป็นบันทึก (record) ไม่ได้กำหนดนโยบาย",
      ],
      k: "Hierarchy: Quality Manual → SOP → Work instruction → Records/Forms",
      d: "easy",
      ref: "ICH Q10 Section 2.5 Quality Manual; PIC/S GMP Guide PE 009 Part I Ch.4",
    },
    {
      t: "RPN reduction after risk control",
      p: "Failure mode “การปนเปื้อนเศษโลหะจาก sieve ขาด” มีคะแนนก่อนควบคุม S = 8, O = 6, D = 7 ทีมเพิ่มการตรวจความสมบูรณ์ของ sieve ก่อนและหลังใช้ทุกครั้ง (ทำให้ O = 3) และติดตั้ง metal detector ทุกเม็ด (ทำให้ D = 2) RPN หลังควบคุมและร้อยละที่ลดลงคือข้อใด",
      o: [
        "24 (ลดลง 92.9%)",
        "48 (ลดลง 85.7%)",
        "96 (ลดลง 71.4%)",
        "168 (ลดลง 50.0%)",
        "288 (ลดลง 14.3%)",
      ],
      a: 1,
      r: "RPN ก่อนควบคุม = 8 × 6 × 7 = 336 หลังควบคุม S คงเดิม (ผลของเศษโลหะต่อผู้ป่วยยังรุนแรงเท่าเดิม) O = 3, D = 2 → RPN = 8 × 3 × 2 = 48 ลดลง (336 − 48)/336 = 85.7%\n\nหลังทำ risk control ต้องประเมิน residual risk และพิจารณาว่ามี risk ใหม่เกิดจาก control หรือไม่ (เช่น metal detector ต้อง challenge test ประจำ) ตาม ICH Q9(R1)",
      w: [
        "เกิดจากลด S ลงด้วย (4 × 3 × 2) ซึ่งผิด เพราะ control ทั้งสองไม่เปลี่ยนความรุนแรง",
        "ถูก — 8 × 3 × 2 = 48 ลดลง 288/336 = 85.7%",
        "คิดเฉพาะการเปลี่ยน D (8 × 6 × 2) ลืมเปลี่ยน O",
        "คิดเฉพาะการเปลี่ยน O (8 × 3 × 7) ลืมเปลี่ยน D",
        "288 คือปริมาณที่ลดลง ไม่ใช่ RPN ที่เหลือ",
      ],
      k: "Risk control ลด O (ป้องกัน) หรือ D (ตรวจจับ); S มักคงเดิม; ต้องประเมิน residual risk และ risk ใหม่",
      d: "medium",
      ref: "ICH Q9(R1) Section 4.4 Risk Control and Annex I.2",
      c: [
        "RPN ก่อน = 8 × 6 × 7 = 336",
        "RPN หลัง = 8 × 3 × 2 = 48",
        "% ลดลง = (336 − 48) ÷ 336 × 100 = 85.7%",
      ],
    },
    {
      t: "Dirty hold time exceedance",
      p: "Cleaning validation ของเครื่อง granulator กำหนด dirty hold time (DHT) ที่ validate ไว้ 48 ชั่วโมง แต่เนื่องจากวันหยุดยาว เครื่องถูกทิ้งไว้หลังใช้งาน 96 ชั่วโมงก่อนทำความสะอาด ข้อใดเป็นการจัดการที่เหมาะสมที่สุด",
      o: [
        "บันทึก deviation ทำความสะอาดตาม SOP แล้วยืนยันความสะอาดด้วยการสุ่มตัวอย่างเพิ่ม (เช่น swab/rinse) ก่อนปล่อยเครื่องไปใช้ และพิจารณา validate DHT ที่ยาวขึ้นถ้าเกิดเป็นประจำ",
        "ทำความสะอาดตาม SOP ตามปกติ ไม่ต้องบันทึกอะไร เพราะ SOP ผ่าน validation แล้ว",
        "ปรับ SOP ให้ DHT เป็น 96 ชั่วโมงทันทีโดยอ้างว่าครั้งนี้ทำความสะอาดได้",
        "ใช้เครื่องผลิตยาตัวเดิมต่อโดยไม่ต้องทำความสะอาด",
        "นับเป็น clean hold time แทน เพราะไม่มีการผลิตระหว่างนั้น",
      ],
      a: 0,
      r: "Dirty hold time คือเวลาสูงสุดตั้งแต่ใช้งานเสร็จจนเริ่มทำความสะอาดที่พิสูจน์แล้วว่ายังทำความสะอาดได้ เพราะ residue ที่ทิ้งไว้นานอาจแห้ง แข็ง หรือมีเชื้อเจริญ ทำให้ล้างออกยากขึ้น ส่วน clean hold time คือเวลาสูงสุดที่เก็บเครื่องที่สะอาดแล้วก่อนใช้โดยไม่ปนเปื้อนซ้ำ (โดยเฉพาะ microbial)\n\nการเกินเวลาที่ validate ไว้คือการทำงานนอก validated state ต้องบันทึก deviation และพิสูจน์ความสะอาดสำหรับครั้งนั้น การขยาย DHT ต้องทำผ่าน change control และ validation study ที่มีข้อมูลรองรับ ไม่ใช่สรุปจากเหตุการณ์ครั้งเดียว",
      w: [
        "ถูก — นอก validated state ต้องเป็น deviation พร้อม verification เพิ่ม และขยาย DHT อย่างเป็นระบบหากจำเป็น",
        "Validation ครอบคลุมเฉพาะเงื่อนไข ≤ 48 ชั่วโมง การเกินเวลาต้องบันทึกและประเมิน",
        "การเปลี่ยนค่า validated parameter ต้องผ่าน change control และข้อมูลหลายครั้ง ไม่ใช่ครั้งเดียว",
        "Campaign ต่อเนื่องต้อง validate แยก และเครื่องที่ทิ้งไว้ 96 ชั่วโมงมีความเสี่ยง microbial",
        "เครื่องยังไม่ได้ทำความสะอาด จึงเป็นสถานะ dirty ไม่ใช่ clean hold",
      ],
      k: "DHT = ใช้เสร็จ→เริ่มล้าง; CHT = ล้างเสร็จ→ใช้ใหม่; เกินค่าที่ validate = deviation + verify ความสะอาด",
      d: "medium",
      ref: "PIC/S GMP Guide PE 009 Annex 15 Section 10 (Cleaning Validation)",
    },
    {
      t: "Retrospective validation acceptability",
      p: "ยาเม็ดตำรับเก่าผลิตมา 15 ปีโดยไม่เคยมีเอกสาร process validation ฝ่ายผลิตเสนอให้รวบรวมผลวิเคราะห์ batch ย้อนหลัง 30 batches เพื่อประกาศว่ากระบวนการ “validated” แบบ retrospective ตาม PIC/S Annex 15 ฉบับปัจจุบัน ข้อใดถูกต้องที่สุด",
      o: [
        "Retrospective validation ไม่ถือเป็นแนวทางที่ยอมรับได้แล้ว ต้องทำ validation แบบ prospective (หรือ concurrent ที่มีเหตุผล) โดยใช้ข้อมูลย้อนหลังประกอบ risk assessment และการกำหนด control strategy",
        "ยอมรับได้ ถ้าข้อมูลย้อนหลังมีอย่างน้อย 30 batches และผ่าน specification ทั้งหมด",
        "ยอมรับได้ ถ้า Cpk ของ assay จากข้อมูลย้อนหลังมากกว่า 1.33",
        "ไม่ต้อง validate เพราะผลิตภัณฑ์จำหน่ายมานานโดยไม่มี complaint",
        "ให้ยื่นข้อมูลย้อนหลังต่อหน่วยงานกำกับแทนการ validate",
      ],
      a: 0,
      r: "Annex 15 ฉบับปรับปรุง (2015) ระบุว่า retrospective validation ไม่ถือเป็นแนวทางที่ยอมรับได้อีกต่อไป เพราะข้อมูลย้อนหลังมักไม่ได้เก็บตามแผนที่ออกแบบให้แสดง reproducibility, ไม่ครอบคลุม CPP ทั้งหมด และไม่มี protocol/เกณฑ์ที่กำหนดล่วงหน้า\n\nสำหรับ legacy product ควรใช้ข้อมูลย้อนหลังเพื่อสร้าง process understanding, ระบุ CPP/CQA และทำ risk assessment แล้วทำ prospective validation (หรือ concurrent ในกรณีพิเศษที่มีเหตุผล) จากนั้นเข้าสู่ ongoing process verification การไม่มี complaint ไม่ได้พิสูจน์ว่ากระบวนการอยู่ภายใต้การควบคุม",
      w: [
        "ถูก — retrospective ไม่ยอมรับแล้ว ข้อมูลย้อนหลังใช้ประกอบการออกแบบ validation ใหม่",
        "จำนวน batch มากไม่แก้ข้อจำกัดที่ข้อมูลไม่ได้เก็บตาม protocol ที่กำหนดล่วงหน้า",
        "Capability index จากข้อมูลย้อนหลังเป็นข้อมูลประกอบ ไม่ใช่การ validate กระบวนการ",
        "การไม่มี complaint ไม่ได้แสดงว่ากระบวนการ reproducible และควบคุมได้",
        "การยื่นข้อมูลต่อหน่วยงานกำกับไม่ได้ทดแทนข้อกำหนด GMP ด้าน validation",
      ],
      k: "Annex 15 (2015): retrospective validation ไม่ยอมรับแล้ว → legacy product ใช้ข้อมูลเก่าประกอบ prospective validation",
      d: "hard",
      ref: "PIC/S GMP Guide PE 009 Annex 15 Section 5 (Process Validation) and Glossary",
    },
    {
      t: "Design qualification purpose",
      p: "ข้อใดอธิบายวัตถุประสงค์ของ Design Qualification (DQ) ได้ถูกต้องที่สุด",
      o: [
        "ยืนยันเป็นเอกสารว่าการออกแบบที่เสนอของเครื่องจักร/ระบบสอดคล้องกับ URS และข้อกำหนด GMP ก่อนสั่งซื้อหรือสร้าง",
        "ยืนยันว่าเครื่องติดตั้งถูกต้องตาม drawing และต่อ utilities ครบ",
        "ทดสอบการทำงานของเครื่องในช่วง operating range ที่กำหนด",
        "ยืนยันว่าเครื่องให้ผลิตภัณฑ์ที่มีคุณภาพสม่ำเสมอในการผลิตจริง",
        "เป็นการตรวจรับเครื่องที่ไซต์ผู้ใช้หลังขนส่ง (SAT)",
      ],
      a: 0,
      r: "Annex 15 กำหนดว่าองค์ประกอบถัดจาก URS คือ DQ ซึ่งต้องแสดงและบันทึกว่าการออกแบบสอดคล้องกับ URS และ GMP (เช่น วัสดุผิวสัมผัส, cleanability, ระบบควบคุม, ช่วงการทำงาน) ข้อกำหนดใน URS ต้องตรวจสอบได้ในขั้น DQ\n\nการพบข้อบกพร่องของการออกแบบใน DQ มีต้นทุนต่ำกว่าการแก้หลังติดตั้งมาก จากนั้นจึงเป็น FAT/SAT, IQ, OQ และ PQ ตามลำดับ",
      w: [
        "ถูก — DQ ยืนยันว่าการออกแบบตรงกับ URS และ GMP ก่อนสร้าง/ซื้อ",
        "การติดตั้งถูกต้องเป็นวัตถุประสงค์ของ IQ",
        "การทดสอบตาม operating range เป็น OQ",
        "การแสดงความสม่ำเสมอในการผลิตจริงเป็น PQ",
        "SAT เป็นการทดสอบหลังส่งมอบ ไม่ใช่การยืนยันการออกแบบ",
      ],
      k: "URS → DQ (design ตรง URS/GMP) → FAT/SAT → IQ → OQ → PQ",
      d: "medium",
      ref: "PIC/S GMP Guide PE 009 Annex 15 Section 3.2–3.3 (URS and DQ)",
    },
    {
      t: "Electronic signature required elements",
      p: "ระบบ eBMR ใหม่ใช้ electronic signature ในการอนุมัติขั้นตอนการผลิต ตามหลักของ 21 CFR Part 11 และ PIC/S Annex 11 ลายมือชื่ออิเล็กทรอนิกส์ที่แสดงบน record ต้องมีข้อมูลใดครบ",
      o: [
        "ชื่อผู้ลงนาม วันที่และเวลาที่ลงนาม และความหมายของการลงนาม (เช่น ผู้ปฏิบัติ ผู้ตรวจสอบ ผู้อนุมัติ)",
        "เฉพาะ username ของผู้ลงนาม",
        "ชื่อผู้ลงนามและรหัสผ่านที่ใช้",
        "วันที่ลงนามเท่านั้น เพราะระบบมี audit trail อยู่แล้ว",
        "ภาพสแกนลายมือชื่อจริงของผู้ลงนาม",
      ],
      a: 0,
      r: "21 CFR 11.50 กำหนดให้ signed electronic record แสดง (1) ชื่อของผู้ลงนาม (printed name), (2) วันที่และเวลาที่ลงนาม และ (3) ความหมายของการลงนาม เช่น review, approval, responsibility, authorship Annex 11 ก็กำหนดให้ e-signature มีผลเทียบเท่าลายมือชื่อ เชื่อมโยงกับ record อย่างถาวร และมีเวลาและวันที่\n\nนอกจากนี้ e-signature ต้องเป็นของบุคคลเฉพาะ ไม่ใช้ซ้ำหรือโอนให้ผู้อื่น และการลงนามที่ไม่ใช่ biometric ต้องใช้ identification component อย่างน้อย 2 อย่าง (เช่น user ID + password)",
      w: [
        "ถูก — ชื่อ, วันเวลา และความหมายของการลงนาม คือ 3 องค์ประกอบที่ต้องแสดง",
        "Username อย่างเดียวไม่บอกเวลาและความหมายของการลงนาม",
        "ห้ามแสดงรหัสผ่านบน record เพราะเป็นข้อมูลยืนยันตัวตนที่ต้องเป็นความลับ",
        "Audit trail ไม่ทดแทนข้อกำหนดการแสดงข้อมูลลงนามบน record",
        "ภาพสแกนลายมือชื่อไม่ผูกกับตัวตนและอาจคัดลอกได้ ไม่ใช่ e-signature ที่สอดคล้อง",
      ],
      k: "e-signature ต้องแสดง: ชื่อผู้ลงนาม + วันเวลา + ความหมายของการลงนาม และผูกกับ record ถาวร",
      d: "medium",
      ref: "21 CFR Part 11 §11.50 and §11.200; PIC/S GMP Guide PE 009 Annex 11 Section 14",
    },
    {
      t: "Training effectiveness evaluation",
      p: "หลังจัดอบรม Good Documentation Practice (GDP) ให้พนักงานฝ่ายผลิต วิธีใดประเมิน training effectiveness ได้ในระดับ “พฤติกรรมการทำงานจริง” (behavior level) ดีที่สุด",
      o: [
        "ทบทวน batch record ที่พนักงานกลุ่มนี้กรอกหลังอบรม 3 เดือนเทียบกับก่อนอบรม โดยดูจำนวน GDP error",
        "ให้ทำแบบทดสอบหลังอบรมทันทีและผ่าน 80%",
        "ให้กรอกแบบประเมินความพึงพอใจต่อวิทยากร",
        "ตรวจว่าพนักงานลงชื่อเข้าอบรมครบทุกคน",
        "ให้พนักงานอ่าน SOP แล้วลงนามรับทราบ",
      ],
      a: 0,
      r: "PIC/S Ch.2 กำหนดให้ประเมิน practical effectiveness ของการฝึกอบรมเป็นระยะ แบบจำลองของ Kirkpatrick แบ่งเป็น 4 ระดับ: Reaction (ความพึงพอใจ), Learning (ความรู้ เช่น แบบทดสอบ), Behavior (การนำไปใช้ในงานจริง) และ Results (ผลลัพธ์ต่อองค์กร เช่น deviation ลดลง)\n\nการติดตามข้อผิดพลาด GDP ใน batch record จริงหลังอบรมเป็นหลักฐานระดับ behavior ที่บอกได้ว่าการฝึกอบรมเปลี่ยนการปฏิบัติงานจริงหรือไม่ แบบทดสอบวัดได้แค่ความรู้ ส่วนการลงชื่อเป็นหลักฐานการเข้าร่วมเท่านั้น",
      w: [
        "ถูก — วัดการปฏิบัติงานจริงหลังอบรมเทียบ baseline เป็นระดับ behavior",
        "แบบทดสอบวัดระดับ learning (ความรู้) ไม่ได้บอกว่านำไปปฏิบัติจริง",
        "ความพึงพอใจเป็นระดับ reaction ซึ่งต่ำสุด",
        "การลงชื่อเป็นหลักฐานการเข้าร่วม ไม่ใช่ effectiveness",
        "Read-and-sign ไม่ได้ยืนยันทั้งความเข้าใจและการปฏิบัติ",
      ],
      k: "Training effectiveness: reaction → learning → behavior → results; GMP ต้องการหลักฐานว่าการปฏิบัติจริงเปลี่ยน",
      d: "medium",
      ref: "PIC/S GMP Guide PE 009 Part I Ch.2.11; Kirkpatrick Four-Level Training Evaluation Model",
    },
    {
      t: "Continued process verification after PPQ",
      p: "ยาเม็ดใหม่ผ่าน PPQ 3 batches และเริ่มผลิตเชิงพาณิชย์ ข้อใดเป็นแผน Stage 3 (Continued Process Verification) ที่เหมาะสมที่สุดในช่วงแรก",
      o: [
        "คงระดับการสุ่มตัวอย่างและการติดตามที่เข้มข้นใกล้เคียง PPQ ไว้จนมีข้อมูล commercial batches เพียงพอประเมินความแปรปรวน แล้วจึงปรับลดตามหลักฐานทางสถิติ",
        "ลดการสุ่มตัวอย่างเหลือเท่า routine release ทันที เพราะ PPQ ผ่านแล้ว",
        "ไม่ต้องติดตาม CPP เพราะทุก batch ผ่าน finished product testing อยู่แล้ว",
        "ทำ PPQ ซ้ำ 3 batches ทุกปีแทนการติดตามต่อเนื่อง",
        "ติดตามเฉพาะ complaint จากตลาดเป็นข้อมูลหลักของ CPV",
      ],
      a: 0,
      r: "FDA (2011) แนะนำว่าหลัง PPQ ควรคงการติดตามและสุ่มตัวอย่างในระดับที่สูง (heightened monitoring) ใกล้เคียง PPQ ต่อไป จนกว่าจะมีข้อมูลเพียงพอสำหรับประมาณความแปรปรวนของกระบวนการอย่างน่าเชื่อถือ แล้วจึงปรับระดับการติดตามตามข้อมูลทางสถิติ\n\nCPV ต้องเก็บและวิเคราะห์ข้อมูล CPP, IPC และ CQA ทั้ง intra-batch และ inter-batch เพื่อหา trend และ unplanned variation ก่อนที่จะเกิด OOS การทำ PPQ ซ้ำเป็นรอบไม่ทดแทนการติดตามต่อเนื่อง และ complaint เป็นสัญญาณที่ช้าเกินไป",
      w: [
        "ถูก — heightened monitoring ต่อจาก PPQ แล้วลดลงอย่างมีเหตุผลทางสถิติ",
        "PPQ ไม่กี่ batch ยังประเมิน inter-batch variability ได้จำกัด การลดทันทีเสี่ยงพลาดสัญญาณ",
        "Finished product testing ตรวจจับ trend ของกระบวนการได้ช้าและจำกัด CPV ต้องรวม CPP",
        "PPQ ซ้ำไม่ใช่ CPV และไม่ได้ให้ข้อมูลต่อเนื่องของทุก batch",
        "Complaint เป็นข้อมูลปลายทางที่ช้า ไม่เพียงพอต่อการยืนยัน state of control",
      ],
      k: "Stage 3: เริ่มด้วย heightened monitoring หลัง PPQ → ปรับลดตามข้อมูลทางสถิติ; ติดตาม CPP/CQA ทั้ง intra และ inter-batch",
      d: "hard",
      ref: "FDA Guidance: Process Validation — General Principles and Practices (2011), Section IV.D Stage 3",
    },
    {
      t: "Printed label reconciliation review",
      p: "ระหว่างทบทวน batch packaging record ก่อนปล่อยยา QA พบข้อมูลฉลากพิมพ์ (printed labels): เบิก 5,000 ดวง ใช้ติดบนผลิตภัณฑ์ 4,812 ดวง เสียหาย/ทำลายระหว่างผลิตมีบันทึก 150 ดวง คืนคลัง 30 ดวง ข้อใดเป็นการประเมินที่ถูกต้องที่สุด",
      o: [
        "ฉลากขาดหายไป 8 ดวง (0.16%) ต้องสอบสวนหาคำอธิบายให้ได้ก่อนพิจารณาปล่อย batch เพราะฉลากพิมพ์ที่หายอาจไปอยู่บนผลิตภัณฑ์อื่น",
        "ฉลากขาดหายไป 8 ดวง แต่น้อยกว่า 1% จึงยอมรับได้โดยไม่ต้องสอบสวน",
        "ยอดตรงกันพอดี เพราะ 4,812 + 150 + 30 = 5,000",
        "ฉลากเกินมา 8 ดวง แสดงว่ามีการนับซ้ำ ปล่อย batch ได้",
        "ฉลากขาดหายไป 38 ดวง ต้องทำลายทั้ง batch ทันที",
      ],
      a: 0,
      r: "การ reconciliation วัสดุบรรจุภัณฑ์พิมพ์ (printed packaging materials) ต้องเทียบจำนวนที่เบิก กับที่ใช้ ทำลาย และคืน ความคลาดเคลื่อนที่ผิดปกติหรือมีนัยสำคัญต้องสอบสวนและอธิบายได้ก่อนปล่อย เพราะฉลากพิมพ์เป็นแหล่งของ mix-up ที่ร้ายแรง (ฉลากของ batch/ผลิตภัณฑ์นี้อาจไปติดบนผลิตภัณฑ์อื่น)\n\nยอดรวม = 4,812 + 150 + 30 = 4,992 ดวง ขาดไป 8 ดวง (8/5,000 = 0.16%) แม้จำนวนน้อยแต่สำหรับฉลากพิมพ์ต้องได้รับคำอธิบาย การกำหนดเกณฑ์ความคลาดเคลื่อนต้องอิงความเสี่ยงและกำหนดไว้ล่วงหน้า",
      w: [
        "ถูก — 5,000 − 4,992 = 8 ดวงหาย ต้องสอบสวนก่อนปล่อย",
        "ฉลากพิมพ์เป็นวัสดุเสี่ยง mix-up ความคลาดเคลื่อนต้องอธิบายได้ ไม่ใช่ยอมรับอัตโนมัติด้วยเกณฑ์ % ทั่วไป",
        "คำนวณผิด ผลรวมจริงคือ 4,992 ไม่ใช่ 5,000",
        "ทิศของความคลาดเคลื่อนผิด ยอดที่นับได้น้อยกว่าที่เบิก",
        "ตัวเลข 38 คำนวณผิด และการทำลายทั้ง batch ก่อนสอบสวนไม่ใช่ขั้นตอนแรกที่เหมาะสม",
      ],
      k: "Reconciliation ฉลากพิมพ์: เบิก = ใช้ + ทำลาย + คืน; ส่วนต่างต้องสอบสวนและอธิบายได้ก่อนปล่อย batch",
      d: "hard",
      ref: "PIC/S GMP Guide PE 009 Part I Ch.5 (Packaging materials and packaging operations); Annex 16",
      c: [
        "ยอดที่ตรวจนับได้ = 4,812 + 150 + 30 = 4,992 ดวง",
        "ส่วนต่าง = 5,000 − 4,992 = 8 ดวง",
        "% = 8 ÷ 5,000 × 100 = 0.16%",
      ],
    },
  ],
];
