import type { Ip1MockDomainContent } from "@/lib/ip1-mock/types";

export const QA: Ip1MockDomainContent = [
  // Mock Set 1 — ชุดที่ 1
  [
    {
      t: "FMEA RPN prioritization",
      p: "ทีม QRM ทำ FMEA กระบวนการบรรจุแคปซูล ได้คะแนน (S, O, D) ดังนี้ A = (8, 3, 4), B = (6, 5, 5), C = (9, 2, 7), D = (5, 6, 3), E = (7, 4, 6) หากองค์กรจัดลำดับความสำคัญด้วย RPN เพียงอย่างเดียว failure mode ใดควรได้รับการจัดการเป็นลำดับแรก",
      o: [
        "Failure mode E (RPN = 168)",
        "Failure mode B (RPN = 150)",
        "Failure mode C (RPN = 126) เพราะ severity สูงสุด",
        "Failure mode A (RPN = 96)",
        "Failure mode D (RPN = 90) เพราะ occurrence สูงสุด",
      ],
      a: 0,
      r: "RPN (Risk Priority Number) = Severity × Occurrence × Detectability โดยแต่ละปัจจัยมักให้คะแนน 1–10 และ D ที่สูงหมายถึงตรวจจับได้ยาก\n\nคำนวณได้ A = 96, B = 150, C = 126, D = 90, E = 168 ดังนั้นถ้าใช้ RPN อย่างเดียว E มีลำดับสูงสุด อย่างไรก็ตามในทางปฏิบัติ ICH Q9(R1) เตือนว่าคะแนนเชิงตัวเลขมี subjectivity และหลายองค์กรกำหนดกฎเสริม เช่น S ≥ 9 ต้องพิจารณาเสมอแม้ RPN ต่ำ ซึ่งทำให้ C ควรถูกทบทวนด้วยเช่นกัน",
      w: [
        "ถูก — 7 × 4 × 6 = 168 สูงที่สุดในทั้ง 5 failure modes เมื่อใช้ RPN เป็นเกณฑ์เดียว",
        "B = 6 × 5 × 5 = 150 เป็นลำดับที่สอง ไม่ใช่สูงสุด",
        "C = 9 × 2 × 7 = 126 แม้ S สูงสุดแต่โจทย์กำหนดให้จัดลำดับด้วย RPN เพียงอย่างเดียว (ในชีวิตจริงควรมีกฎเสริมสำหรับ S สูง)",
        "A = 8 × 3 × 4 = 96 ต่ำกว่า E, B และ C",
        "D = 5 × 6 × 3 = 90 ต่ำสุด แม้ O สูงสุดแต่ RPN รวมไม่ได้สูง",
      ],
      k: "RPN = S × O × D; ใช้จัดลำดับได้แต่ควรมีกฎเสริมสำหรับ severity สูง เพราะ RPN เท่ากันอาจมี risk profile ต่างกัน",
      d: "medium",
      ref: "ICH Q9(R1) Quality Risk Management, Annex I (FMEA)",
      c: [
        "A = 8 × 3 × 4 = 96",
        "B = 6 × 5 × 5 = 150",
        "C = 9 × 2 × 7 = 126",
        "D = 5 × 6 × 3 = 90",
        "E = 7 × 4 × 6 = 168 → สูงสุด",
      ],
    },
    {
      t: "ICH Q9 risk assessment components",
      p: "ตาม ICH Q9(R1) กระบวนการ risk assessment ประกอบด้วยขั้นตอนย่อยใดบ้าง",
      o: [
        "Risk identification, risk analysis และ risk evaluation",
        "Risk reduction, risk acceptance และ risk review",
        "Risk identification, risk communication และ risk acceptance",
        "Risk analysis, risk control และ risk review",
        "Hazard identification, CAPA และ management review",
      ],
      a: 0,
      r: "ICH Q9(R1) แบ่ง QRM process เป็น risk assessment → risk control → risk communication → risk review โดย risk assessment ประกอบด้วย risk identification (มีอะไรผิดพลาดได้), risk analysis (โอกาสเกิดและความรุนแรง รวมถึงการตรวจจับ) และ risk evaluation (เทียบกับเกณฑ์ว่าเสี่ยงยอมรับได้หรือไม่)\n\nRisk control ประกอบด้วย risk reduction และ risk acceptance ส่วน risk communication และ risk review เป็นกิจกรรมที่ดำเนินตลอดวงจร",
      w: [
        "ถูก — สามขั้นตอนของ risk assessment ตาม ICH Q9(R1) คือ identification, analysis, evaluation",
        "Risk reduction และ risk acceptance เป็นส่วนของ risk control ส่วน risk review เป็นขั้นตอนทบทวนภายหลัง",
        "Risk communication และ risk acceptance ไม่ได้อยู่ใน risk assessment",
        "Risk control และ risk review เป็นขั้นตอนถัดไปหลัง risk assessment",
        "CAPA และ management review เป็นองค์ประกอบของ PQS (ICH Q10) ไม่ใช่ขั้นตอนย่อยของ risk assessment",
      ],
      k: "Risk assessment = identify → analyze → evaluate; Risk control = reduce + accept",
      d: "easy",
      ref: "ICH Q9(R1) Quality Risk Management, Section 4",
    },
    {
      t: "Critical deviation classification",
      p: "ระหว่าง line clearance ของวันถัดมา พบว่ากล่องยาเม็ด Amlodipine 10 mg ที่บรรจุเสร็จแล้วบางกล่องมีแผง blister ของ Amlodipine 5 mg ปะปนอยู่ ควรจัดระดับ deviation นี้อย่างไรเหมาะสมที่สุด",
      o: [
        "Critical deviation เพราะเป็น product mix-up ที่อาจทำให้ผู้ป่วยได้รับยาผิดความแรง",
        "Major deviation เพราะพบก่อนปล่อยยาจึงไม่กระทบผู้ป่วย",
        "Minor deviation เพราะเป็นยาตัวเดียวกันต่างกันแค่ความแรง",
        "ไม่ต้องจัดเป็น deviation แค่คัดแยกกล่องที่ผิดออกก็เพียงพอ",
        "Minor deviation หากผล assay ของ batch อยู่ในเกณฑ์",
      ],
      a: 0,
      r: "การจัดระดับ deviation อิงกับผลกระทบต่อคุณภาพและความปลอดภัยของผู้ป่วย: critical คือมีโอกาสก่อให้เกิดอันตรายต่อผู้ป่วยหรือผลิตภัณฑ์ไม่เป็นไปตาม MA อย่างร้ายแรง, major คือมีผลกระทบต่อคุณภาพอย่างมีนัยสำคัญแต่ไม่ถึงขั้นอันตรายโดยตรง, minor คือไม่มีผลกระทบต่อคุณภาพ\n\nMix-up ของความแรงเป็นตัวอย่างคลาสสิกของ critical เพราะผู้ป่วยอาจได้รับยาผิดขนาด และบ่งชี้ความล้มเหลวของ line clearance/segregation การพบก่อนปล่อยยาไม่ได้ลดระดับของความล้มเหลวของระบบ ต้อง quarantine ทั้ง batch, ขยายการสอบสวนไป batch อื่นที่ใช้ line เดียวกัน และทำ CAPA",
      w: [
        "ถูก — mix-up ต่างความแรงมีโอกาสก่อให้เกิดอันตรายต่อผู้ป่วยโดยตรง จัดเป็น critical",
        "การตรวจพบก่อนปล่อยไม่ลดความรุนแรงของความล้มเหลวของระบบ ศักยภาพในการเกิดอันตรายยังเป็นตัวกำหนดระดับ",
        "ความแรงต่างกันสองเท่าเป็นความเสี่ยงต่อผู้ป่วยชัดเจน ไม่ใช่เรื่องเล็กน้อย",
        "ทุกเหตุการณ์ที่เบี่ยงเบนจาก procedure ต้องบันทึกเป็น deviation และสอบสวนหา root cause ไม่ใช่แค่ correction",
        "ผล assay ไม่สะท้อน mix-up ระดับหน่วยบรรจุ และไม่ลดความเสี่ยงที่ผู้ป่วยได้ยาผิดความแรง",
      ],
      k: "Mix-up (ผิดความแรง/ผิดตัวยา/ผิดฉลาก) = critical deviation เสมอ ต้อง quarantine และขยายขอบเขตการสอบสวน",
      d: "medium",
      ref: "PIC/S GMP Guide PE 009 Part I Ch.1 & Ch.8; WHO TRS 1025 Annex (deviation handling)",
    },
    {
      t: "Ishikawa 6M categorization",
      p: "ในการทำ Ishikawa (fishbone) diagram ของปัญหา tablet weight variation ทีมระบุสาเหตุที่เป็นไปได้ว่า “excipient lot ใหม่มี particle size ละเอียดกว่าเดิม ทำให้การไหลแย่ลง” สาเหตุนี้ควรจัดอยู่ในหมวดใดของ 6M",
      o: ["Material", "Machine", "Method", "Man", "Measurement"],
      a: 0,
      r: "Ishikawa diagram ใช้จัดกลุ่มสาเหตุที่เป็นไปได้ตามหมวด 6M ได้แก่ Man (คน), Machine (เครื่องจักร), Method (วิธีการ/SOP/พารามิเตอร์), Material (วัตถุดิบ/บรรจุภัณฑ์), Measurement (การวัด/เครื่องมือวัด) และ Mother Nature/Milieu (สิ่งแวดล้อม)\n\nสาเหตุที่มาจากคุณสมบัติของวัตถุดิบ เช่น particle size, moisture, lot-to-lot variability ของ excipient จัดเป็น Material Ishikawa เป็นเครื่องมือระดมสมองเพื่อหา potential causes ต้องตรวจยืนยันด้วยข้อมูลก่อนสรุปเป็น root cause",
      w: [
        "ถูก — คุณสมบัติของ excipient lot ใหม่เป็นสาเหตุด้านวัตถุดิบ (Material)",
        "Machine ใช้กับสาเหตุจากเครื่องตอก เช่น feeder, punch wear ไม่ใช่คุณสมบัติผง",
        "Method ใช้กับวิธีการ/พารามิเตอร์ใน MBR เช่น เวลาผสม ความเร็ว turret",
        "Man ใช้กับสาเหตุด้านบุคลากร เช่น การฝึกอบรม การปฏิบัติไม่ตาม SOP",
        "Measurement ใช้กับความผิดพลาดของการวัด เช่น เครื่องชั่ง IPC ไม่ได้ calibrate",
      ],
      k: "6M = Man, Machine, Method, Material, Measurement, Mother nature; Ishikawa ให้ potential causes ต้องยืนยันด้วยข้อมูล",
      d: "easy",
      ref: "ICH Q9(R1) Annex I (basic risk management facilitation methods)",
    },
    {
      t: "Process validation Stage 2 activities",
      p: "ตามแนวทาง process validation แบบ lifecycle (FDA 2011) กิจกรรมใดจัดอยู่ใน Stage 2 (Process Qualification)",
      o: [
        "การทำ PPQ batches ตาม protocol ที่อนุมัติล่วงหน้า หลังจาก qualify facility, utilities และ equipment แล้ว",
        "การทำ DoE เพื่อกำหนด design space และ critical process parameters",
        "การเก็บข้อมูล CPP/CQA จาก commercial batches อย่างต่อเนื่องเพื่อติดตามแนวโน้ม",
        "การทำ Product Quality Review ประจำปี",
        "การ scale-up จาก lab scale ไป pilot scale เพื่อหา control strategy",
      ],
      a: 0,
      r: "FDA Process Validation Guidance (2011) แบ่ง 3 stage: Stage 1 Process Design (สร้างความเข้าใจกระบวนการ, DoE, กำหนด control strategy), Stage 2 Process Qualification (2a: qualify facility/utilities/equipment, 2b: PPQ ที่ commercial scale ตาม protocol) และ Stage 3 Continued Process Verification (ติดตามข้อมูลต่อเนื่องระหว่างการผลิตเชิงพาณิชย์)\n\nPPQ จึงเป็นหัวใจของ Stage 2 ซึ่งต้องผ่านก่อนการจำหน่ายเชิงพาณิชย์ (commercial distribution)",
      w: [
        "ถูก — equipment/utility qualification และ PPQ เป็นกิจกรรมของ Stage 2",
        "DoE และการกำหนด design space เป็นกิจกรรม Stage 1 (Process Design)",
        "การติดตามข้อมูล commercial batches อย่างต่อเนื่องคือ Stage 3 (CPV)",
        "PQR เป็นการทบทวนระดับ PQS ที่สนับสนุน Stage 3 ไม่ใช่ Process Qualification",
        "การ scale-up เพื่อสร้างความรู้และ control strategy เป็นส่วนของ Stage 1",
      ],
      k: "Stage 1 = Design, Stage 2 = Qualification (equipment + PPQ), Stage 3 = Continued Process Verification",
      d: "medium",
      ref: "FDA Guidance for Industry: Process Validation — General Principles and Practices (2011)",
    },
    {
      t: "Cleaning limit by 10 ppm criterion",
      p: "เครื่องผสมใช้ร่วมกันระหว่างยา A (ผลิตก่อน) และยา B (ผลิตถัดไป) บริษัทใช้เกณฑ์ 10 ppm สำหรับ residue ของยา A ในยา B ขนาด batch ของยา B = 150 kg พื้นที่ผิวสัมผัสรวม = 30,000 cm² และพื้นที่ swab = 25 cm² ต่อจุด ค่า acceptance limit ต่อ swab คือข้อใด",
      o: ["50 µg/swab", "125 µg/swab", "1,250 µg/swab", "12,500 µg/swab", "60,000 µg/swab"],
      a: 2,
      r: "เกณฑ์ 10 ppm หมายถึงยา A ปนเปื้อนในยา B ได้ไม่เกิน 10 mg ต่อยา B 1 kg ดังนั้น MACO = 10 mg/kg × ขนาด batch ของยาถัดไป จากนั้นสมมติว่า residue กระจายสม่ำเสมอบนพื้นผิวสัมผัสทั้งหมด หารด้วยพื้นที่รวมได้ limit ต่อ cm² แล้วคูณพื้นที่ swab\n\nMACO = 10 × 150 = 1,500 mg; ต่อ cm² = 1,500 mg / 30,000 cm² = 0.05 mg/cm² = 50 µg/cm²; ต่อ swab 25 cm² = 1,250 µg ปัจจุบันแนวทาง EMA/PIC/S แนะนำให้ใช้ HBEL (PDE) เป็นหลัก โดย 10 ppm อาจใช้เป็นเกณฑ์เสริม",
      w: [
        "50 µg คือ limit ต่อ cm² ลืมคูณพื้นที่ swab 25 cm²",
        "125 µg เกิดจากคำนวณ MACO ผิดเป็น 150 mg (ใช้ 1 ppm แทน 10 ppm)",
        "ถูก — 1,500 mg ÷ 30,000 cm² × 25 cm² = 1.25 mg = 1,250 µg ต่อ swab",
        "12,500 µg เกิดจาก error หลักทศนิยม 10 เท่า",
        "60,000 µg เกิดจากเอา MACO 1,500 mg หารด้วยพื้นที่ swab โดยตรง ไม่ได้คิดพื้นที่ผิวรวม",
      ],
      k: "10 ppm: MACO (mg) = 10 × batch size ถัดไป (kg); limit/swab = MACO ÷ พื้นที่รวม × พื้นที่ swab",
      d: "hard",
      ref: "PIC/S PI 006-3 Recommendations on Validation Master Plan, IQ, OQ, Non-sterile Process Validation, Cleaning Validation",
      c: [
        "MACO = 10 mg/kg × 150 kg = 1,500 mg",
        "Limit ต่อพื้นที่ = 1,500 mg ÷ 30,000 cm² = 0.05 mg/cm² = 50 µg/cm²",
        "Limit ต่อ swab = 50 µg/cm² × 25 cm² = 1,250 µg",
      ],
    },
    {
      t: "Operational qualification test scope",
      p: "บริษัทติดตั้ง fluid bed dryer เครื่องใหม่ การทดสอบใดจัดเป็น Operational Qualification (OQ) ที่เหมาะสมที่สุด",
      o: [
        "ทดสอบการควบคุม inlet air temperature และ airflow ตลอดช่วงการใช้งาน รวมถึง alarm และ interlock โดยยังไม่ใช้ผลิตภัณฑ์จริง",
        "ตรวจสอบว่า utilities ต่อถูกต้อง วัสดุผิวสัมผัสเป็น SS316L และมีเอกสาร as-built drawing ครบ",
        "อบแกรนูลของผลิตภัณฑ์จริง 3 batches แล้วได้ LOD อยู่ในเกณฑ์อย่างสม่ำเสมอ",
        "จัดทำ user requirement specification ระบุกำลังการผลิตและช่วงอุณหภูมิที่ต้องการ",
        "ตรวจรับเครื่องที่โรงงานผู้ผลิตก่อนส่งมอบ (FAT)",
      ],
      a: 0,
      r: "Equipment qualification เรียงเป็น URS → DQ → (FAT/SAT) → IQ → OQ → PQ โดย IQ ยืนยันว่าติดตั้งถูกต้องตามแบบ (วัสดุ, utilities, เอกสาร, calibration ของเครื่องมือวัด), OQ ยืนยันว่าเครื่องทำงานตามที่ออกแบบตลอดช่วงการใช้งานที่คาดไว้ รวมถึง upper/lower limits, alarm, interlock มักทดสอบโดยไม่มีผลิตภัณฑ์หรือใช้ placebo, PQ ยืนยันว่าเครื่องทำงานได้สม่ำเสมอภายใต้สภาวะการผลิตจริง\n\nการทดสอบ control range และ alarm/interlock จึงเป็น OQ",
      w: [
        "ถูก — การทดสอบ function, operating range, alarm และ interlock คือหัวใจของ OQ",
        "การตรวจวัสดุ, utilities และเอกสารเป็น IQ",
        "การใช้ผลิตภัณฑ์จริงซ้ำๆ เพื่อแสดงความสม่ำเสมอภายใต้สภาวะจริงเป็น PQ",
        "URS เป็นเอกสารต้นทางที่ระบุความต้องการของผู้ใช้ จัดทำก่อน DQ",
        "FAT ทำที่โรงงานผู้ผลิตเครื่อง ช่วยลดงานแต่ไม่ใช่ OQ ที่ไซต์ผู้ใช้",
      ],
      k: "IQ = ติดตั้งถูก, OQ = ทำงานถูกตลอด operating range + alarm/interlock, PQ = ทำงานสม่ำเสมอในสภาวะจริง",
      d: "medium",
      ref: "PIC/S GMP Guide PE 009 Annex 15 Qualification and Validation, Section 3",
    },
    {
      t: "CAPA effectiveness check design",
      p: "หลังเกิด deviation ซ้ำเรื่องการบันทึกน้ำหนักวัตถุดิบผิดใน batch record ทีมกำหนด CAPA คือปรับ SOP ให้ใช้เครื่องชั่งที่พิมพ์ผลอัตโนมัติและฝึกอบรมพนักงาน ข้อใดเป็น effectiveness check ที่เหมาะสมที่สุด",
      o: [
        "ติดตามว่าไม่มี deviation ชนิดเดียวกันเกิดซ้ำใน batch ที่ผลิตช่วง 6 เดือนถัดไป ตามเกณฑ์ที่กำหนดไว้ล่วงหน้า",
        "ยืนยันว่าพนักงานทุกคนลงนามในใบบันทึกการฝึกอบรมครบ",
        "ยืนยันว่า SOP ฉบับใหม่ได้รับอนุมัติและแจกจ่ายแล้ว",
        "ปิด CAPA ทันทีเมื่อเครื่องชั่งใหม่ผ่าน IQ",
        "ให้หัวหน้าแผนกยืนยันด้วยวาจาว่าปัญหาหมดไปแล้ว",
      ],
      a: 0,
      r: "ICH Q10 กำหนดให้ CAPA ต้องมีการประเมิน effectiveness ซึ่งต่างจากการยืนยันว่าดำเนินการเสร็จ (implementation/completion) Effectiveness check ควรตอบว่า CAPA ขจัด root cause และป้องกันการเกิดซ้ำได้จริงหรือไม่ โดยกำหนด metric, ช่วงเวลา และเกณฑ์ผ่านไว้ล่วงหน้า เช่น อัตราการเกิดซ้ำเป็นศูนย์ใน N batches หรือ X เดือน\n\nการลงนามฝึกอบรม การอนุมัติ SOP หรือการติดตั้งเครื่องเป็นเพียงหลักฐานว่าได้ทำ action แล้ว ไม่ใช่หลักฐานว่าได้ผล",
      w: [
        "ถูก — วัดผลลัพธ์จริง (recurrence) ในช่วงเวลาที่กำหนดด้วยเกณฑ์ที่ตั้งไว้ล่วงหน้า",
        "การลงนามฝึกอบรมเป็นหลักฐานการดำเนินการ ไม่ได้แสดงว่าพฤติกรรมหรือผลลัพธ์เปลี่ยน",
        "การอนุมัติ SOP เป็น implementation ไม่ใช่ effectiveness",
        "IQ ยืนยันการติดตั้งเครื่อง ยังไม่ได้แสดงว่าปัญหาการบันทึกหายไป",
        "การยืนยันด้วยวาจาไม่ใช่หลักฐานที่เป็นเอกสารและไม่มีเกณฑ์เชิงวัตถุวิสัย",
      ],
      k: "CAPA completion ≠ effectiveness; effectiveness check ต้องวัดผลลัพธ์ด้วย metric/เกณฑ์/ระยะเวลาที่กำหนดล่วงหน้า",
      d: "medium",
      ref: "ICH Q10 Pharmaceutical Quality System, Section 3.2.2",
    },
    {
      t: "Batch certification with open deviation",
      p: "Batch ยาเม็ดเคลือบฟิล์มผ่านการตรวจวิเคราะห์ครบตาม specification แต่ยังมี major deviation เรื่อง granulation endpoint เกินเวลาที่ validate ไว้ ซึ่งการสอบสวนยังไม่ปิด ฝ่ายขายต้องการให้ปล่อยยาด่วน ผู้มีอำนาจปล่อยผลิตภัณฑ์ (authorized person) ควรทำอย่างไร",
      o: [
        "ยังไม่รับรองปล่อย batch จนกว่าการสอบสวนจะสรุป impact ต่อคุณภาพและได้รับการประเมินอนุมัติแล้ว",
        "ปล่อยได้ทันทีเพราะผล QC ผ่าน specification ครบทุกข้อ",
        "ปล่อยได้หากฝ่ายผลิตรับรองว่าไม่มีผลกระทบ",
        "ปล่อยแบบมีเงื่อนไขแล้วค่อยปิด deviation ภายหลัง หากพบปัญหาจึงเรียกคืน",
        "ส่งตัวอย่างเพิ่มไปตรวจ dissolution ซ้ำแล้วปล่อยหากผ่านโดยไม่ต้องรอสอบสวน",
      ],
      a: 0,
      r: "การรับรองปล่อย batch ของ authorized person (AP/QP) ต้องยืนยันว่า batch ผลิตและตรวจสอบตาม GMP และ marketing authorization และว่า deviation ทั้งหมดได้รับการสอบสวนและประเมินผลกระทบจนเป็นที่ยอมรับแล้ว ผลตรวจผ่าน specification เป็นเงื่อนไขจำเป็นแต่ไม่เพียงพอ เพราะการทดสอบมีขนาดตัวอย่างจำกัดและอาจตรวจไม่พบปัญหาที่เกิดจากกระบวนการนอก validated state\n\nการปล่อยก่อนแล้ว 'ค่อยเรียกคืน' เป็นการผลักความเสี่ยงไปให้ผู้ป่วย และแรงกดดันทางธุรกิจต้องไม่มีผลต่อการตัดสินใจของ AP ซึ่งต้องเป็นอิสระจากฝ่ายผลิต",
      w: [
        "ถูก — deviation ที่อาจกระทบคุณภาพต้องสอบสวนและประเมินเสร็จก่อนการรับรองปล่อย",
        "ผล QC ผ่านไม่ได้พิสูจน์ว่าการผลิตนอก validated parameter ไม่มีผลกระทบ (quality cannot be tested into product)",
        "ความรับผิดชอบการปล่อยเป็นของ AP/QA ที่เป็นอิสระ ไม่สามารถมอบให้ฝ่ายผลิตรับรองแทน",
        "การปล่อยโดยหวังพึ่ง recall เป็นการยอมรับความเสี่ยงต่อผู้ป่วยโดยไม่จำเป็น ขัดหลัก GMP",
        "การทดสอบซ้ำไม่ใช่สิ่งทดแทนการสอบสวน root cause และ impact assessment",
      ],
      k: "AP ปล่อย batch ได้เมื่อ (1) ตาม MA/GMP (2) ผล QC ผ่าน และ (3) deviation ทั้งหมดสอบสวน/ประเมินเสร็จ — ผลตรวจผ่านอย่างเดียวไม่พอ",
      d: "hard",
      ref: "PIC/S GMP Guide PE 009 Annex 16 (Certification by an Authorised Person and Batch Release); Part I Ch.1.4",
    },
    {
      t: "Reduced testing based on supplier qualification",
      p: "โรงงานต้องการเปลี่ยนการรับ excipient (microcrystalline cellulose) จากผู้ขายรายหนึ่งเป็นแบบ reduced testing คือยอมรับผลตาม CoA ของผู้ผลิต ข้อใดเป็นเงื่อนไขที่ถูกต้องที่สุด",
      o: [
        "ต้องประเมินและ qualify ผู้ผลิต (เช่น audit/questionnaire) ตรวจสอบความน่าเชื่อถือของ CoA ด้วยการตรวจเต็มเป็นระยะ และยังคงทดสอบ identity ตามที่กำหนด",
        "ยอมรับ CoA ได้ทันทีหากผู้ขายเป็นตัวแทนจำหน่ายรายใหญ่ที่มีใบอนุญาต",
        "หากใช้ CoA แล้วสามารถยกเลิกการทดสอบ identity ทั้งหมดได้",
        "ต้องตรวจเต็มทุก lot ตลอดไป เพราะ GMP ไม่อนุญาตให้ใช้ CoA ของผู้ผลิต",
        "ทำ audit ผู้ผลิตครั้งเดียวตอนเริ่มต้น หลังจากนั้นไม่ต้องทบทวนอีก",
      ],
      a: 0,
      r: "GMP อนุญาตให้ลดการทดสอบวัตถุดิบโดยอาศัย CoA ของผู้ผลิตได้ ถ้าระบบ supplier qualification แสดงความน่าเชื่อถือ ได้แก่ การประเมิน/ตรวจสอบผู้ผลิต (risk-based audit), การยืนยันว่า supply chain โปร่งใสและสืบย้อนถึงผู้ผลิตจริงได้, มี quality agreement, และการตรวจสอบความถูกต้องของ CoA ด้วยการทดสอบเต็มเป็นระยะ (CoA validation) แต่การทดสอบ identity ยังคงต้องทำตามข้อกำหนด GMP\n\nสถานะของผู้ขายต้องได้รับการทบทวนเป็นระยะ (re-qualification) โดยพิจารณาข้อมูลคุณภาพ เช่น การปฏิเสธ lot, complaint และผล audit",
      w: [
        "ถูก — ครอบคลุม qualification ผู้ผลิต, การยืนยันความน่าเชื่อถือ CoA เป็นระยะ และคง identity test",
        "การเป็นตัวแทนจำหน่ายรายใหญ่ไม่ใช่หลักฐานคุณภาพ ต้องสืบย้อนและประเมินผู้ผลิตจริง",
        "Identity test ไม่สามารถยกเลิกได้แม้ใช้ CoA เพราะเป็นการป้องกันการรับวัตถุดิบผิดชนิด",
        "GMP อนุญาต reduced testing ได้ภายใต้ระบบ supplier qualification ที่เหมาะสม",
        "Supplier qualification เป็น lifecycle ต้องมี re-evaluation และ periodic audit ตามความเสี่ยง",
      ],
      k: "Reduced testing ได้เมื่อ supplier qualified + CoA ถูก verify เป็นระยะ + ยังทำ identity test เสมอ",
      d: "hard",
      ref: "PIC/S GMP Guide PE 009 Part I Ch.5 (5.29–5.36) and Ch.7; ICH Q7 Section 7.3",
    },
  ],
  // Mock Set 2 — ชุดที่ 2
  [
    {
      t: "Preliminary hazard analysis use",
      p: "ทีมพัฒนาผลิตภัณฑ์อยู่ในช่วงต้นของโครงการ ยังมีข้อมูลกระบวนการและ design รายละเอียดน้อย ต้องการระบุ hazard หลักและจัดลำดับความเสี่ยงอย่างกว้างๆ เพื่อวางแผนการพัฒนา เครื่องมือ QRM ใดเหมาะสมที่สุด",
      o: [
        "Preliminary Hazard Analysis (PHA)",
        "Failure Mode, Effects and Criticality Analysis (FMECA) ระดับ component",
        "Hazard Analysis and Critical Control Points (HACCP)",
        "Fault Tree Analysis (FTA) ของ failure ที่เกิดขึ้นแล้ว",
        "Statistical process control chart",
      ],
      a: 0,
      r: "ICH Q9(R1) Annex I อธิบายว่า PHA ใช้ประสบการณ์หรือความรู้ที่มีเกี่ยวกับ hazard เพื่อระบุ hazard, สถานการณ์อันตราย และเหตุการณ์ที่อาจก่ออันตราย แล้วประเมินโอกาสเกิดและความรุนแรงอย่างกว้างๆ เหมาะกับช่วงต้นของการพัฒนาเมื่อข้อมูล design/procedure ยังน้อย\n\nผลของ PHA มักใช้เป็นฐานสำหรับการทำเครื่องมือที่ละเอียดกว่า เช่น FMEA หรือ HACCP เมื่อกระบวนการชัดเจนขึ้น",
      w: [
        "ถูก — PHA ออกแบบมาสำหรับช่วงต้นเมื่อข้อมูลรายละเอียดยังมีน้อย",
        "FMECA ต้องรู้รายละเอียดกระบวนการ/อุปกรณ์ระดับ component จึงไม่เหมาะกับช่วงต้น",
        "HACCP ต้องมี process flow ที่ชัดเจนเพื่อกำหนด CCP เหมาะกับกระบวนการที่กำหนดแล้ว",
        "FTA เป็นการวิเคราะห์ย้อนจาก top event มักใช้สอบสวนความล้มเหลวที่ชัดเจน ไม่ใช่การกวาด hazard แบบกว้าง",
        "SPC ใช้ติดตามความแปรปรวนของกระบวนการที่มีข้อมูลการผลิตแล้ว ไม่ใช่เครื่องมือระบุ hazard",
      ],
      k: "ข้อมูลน้อย ช่วงต้นโครงการ → PHA; กระบวนการชัดแล้ว → FMEA/HACCP; สืบสาเหตุ failure → FTA",
      d: "easy",
      ref: "ICH Q9(R1) Annex I.6 Preliminary Hazard Analysis",
    },
    {
      t: "HACCP principle sequence",
      p: "ในการประยุกต์ HACCP กับการควบคุม metal contamination ในสายการผลิตยาเม็ด ทีมได้ทำ hazard analysis และกำหนดให้ metal detector หลังเครื่องตอกเป็น Critical Control Point (CCP) แล้ว ขั้นตอนตามหลักการ HACCP ลำดับถัดไปคือข้อใด",
      o: [
        "กำหนด critical limits เช่น ขนาดของ test piece Fe/non-Fe/SS ที่ต้องตรวจจับและคัดออกได้",
        "กำหนด corrective actions เมื่อ CCP หลุดการควบคุม",
        "จัดทำ verification procedures เพื่อยืนยันว่าระบบ HACCP ทำงาน",
        "ทำ hazard analysis ใหม่ทั้งหมดอีกรอบ",
        "จัดทำระบบเอกสารและบันทึก",
      ],
      a: 0,
      r: "HACCP มี 7 หลักการตามลำดับ: (1) hazard analysis, (2) กำหนด CCP, (3) กำหนด critical limits, (4) กำหนดระบบ monitoring ของ CCP, (5) กำหนด corrective actions, (6) verification procedures, (7) documentation/record keeping\n\nเมื่อกำหนด CCP แล้วต้องกำหนดเกณฑ์ที่วัดได้ซึ่งแยกการยอมรับกับไม่ยอมรับ (critical limit) ก่อน จากนั้นจึงออกแบบการ monitoring และ corrective action ที่อ้างอิง limit นั้น",
      w: [
        "ถูก — หลักการที่ 3 ต่อจากการกำหนด CCP คือ critical limits",
        "Corrective actions เป็นหลักการที่ 5 ต้องมี limit และ monitoring ก่อน",
        "Verification เป็นหลักการที่ 6",
        "Hazard analysis ทำแล้วในหลักการที่ 1 ไม่ต้องเริ่มใหม่ เว้นแต่มีการเปลี่ยนแปลง",
        "Documentation เป็นหลักการที่ 7 (สุดท้าย)",
      ],
      k: "HACCP 7 principles: hazard analysis → CCP → critical limits → monitoring → corrective action → verification → records",
      d: "medium",
      ref: "ICH Q9(R1) Annex I.7 HACCP; WHO TRS 908 Annex 7 (Application of HACCP to pharmaceuticals)",
    },
    {
      t: "5 Why root cause identification",
      p: "ทีมใช้ 5 Why สอบสวนปัญหา tablet capping ได้ลำดับดังนี้: (1) capping เพราะ upper punch สึก → (2) punch สึกเพราะไม่ได้ทำ preventive maintenance ตามกำหนด → (3) ไม่ได้ทำ PM เพราะเครื่องตอกเครื่องนี้ไม่อยู่ในตาราง PM ของระบบ CMMS → (4) ไม่อยู่ในตารางเพราะตอนรับเครื่องใหม่ checklist ของ change control ไม่มีขั้นตอนลงทะเบียนเครื่องเข้า PM program ข้อใดคือ root cause ที่ควรแก้ด้วย CAPA",
      o: [
        "Checklist ของ change control สำหรับเครื่องจักรใหม่ไม่มีขั้นตอนลงทะเบียนเข้า PM program",
        "Upper punch สึก",
        "พนักงานซ่อมบำรุงละเลยการทำ PM",
        "Tablet capping",
        "เครื่องตอกเครื่องนี้คุณภาพต่ำ",
      ],
      a: 0,
      r: "5 Why เป็นการถาม 'ทำไม' ซ้ำจนถึงระดับที่เป็นสาเหตุเชิงระบบซึ่งถ้าแก้แล้วจะป้องกันการเกิดซ้ำได้ ไม่หยุดที่อาการ (symptom) หรือสาเหตุทางตรง (direct cause)\n\nในกรณีนี้ capping เป็นอาการ punch สึกเป็นสาเหตุทางตรง ส่วนช่องโหว่ของ change control checklist เป็น root cause เชิงระบบ การแก้แค่เปลี่ยน punch (correction) จะไม่ป้องกันเครื่องใหม่เครื่องอื่นตกหล่นจาก PM ในอนาคต",
      w: [
        "ถูก — เป็นสาเหตุเชิงระบบระดับลึกสุดที่ควบคุมได้ แก้แล้วป้องกันการเกิดซ้ำกับทุกเครื่อง",
        "Punch สึกเป็น direct cause แก้ด้วยการเปลี่ยน punch เป็นเพียง correction",
        "ข้อมูลไม่ได้บ่งชี้ว่าพนักงานละเลย เครื่องไม่อยู่ในตารางตั้งแต่ต้น การโทษคนเป็นข้อสรุปที่ผิด",
        "Capping คือปัญหา/อาการเริ่มต้น ไม่ใช่สาเหตุ",
        "ไม่มีหลักฐานจากการสอบสวนสนับสนุนว่าเครื่องคุณภาพต่ำ",
      ],
      k: "5 Why: ถามจนถึงสาเหตุเชิงระบบที่แก้แล้วป้องกันการเกิดซ้ำ ไม่หยุดที่ symptom หรือ human error",
      d: "easy",
      ref: "ICH Q10 Section 3.2.2; PIC/S GMP Guide PE 009 Part I Ch.1.4(xiv)",
    },
    {
      t: "Dose-based MACO per surface area",
      p: "ยา A (ผลิตก่อน) มี minimum therapeutic daily dose = 5 mg ยา B (ผลิตถัดไป) มี maximum daily dose = 1,200 mg และขนาด batch = 80 kg ใช้ safety factor 1/1,000 อุปกรณ์มีพื้นที่ผิวสัมผัสรวม 40,000 cm² acceptance limit ของ residue ยา A ต่อพื้นที่คือข้อใด",
      o: ["0.0083 µg/cm²", "0.83 µg/cm²", "8.3 µg/cm²", "83 µg/cm²", "833 µg/cm²"],
      a: 2,
      r: "Dose-based (therapeutic dose) criterion: MACO = (TDD_prev × MBS_next) / (SF × MDD_next) แนวคิดคือผู้ป่วยที่ได้ยา B ในขนาดสูงสุดต่อวัน ต้องไม่ได้รับยา A เกิน 1/1,000 ของขนาดรักษาต่ำสุด\n\nMACO = (5 mg × 80,000,000 mg) / (1,000 × 1,200 mg) = 333.3 mg แล้วหารพื้นที่รวม 40,000 cm² = 0.00833 mg/cm² = 8.3 µg/cm² ปัจจุบัน EMA แนะนำให้ใช้ HBEL/PDE แทน 1/1,000 ของ dose แต่สูตร dose-based ยังใช้กันแพร่หลายและออกสอบบ่อย",
      w: [
        "เป็นค่าที่ได้เมื่อไม่ได้แปลง mg เป็น µg (0.0083 คือหน่วย mg/cm²)",
        "เกิดจากใช้ safety factor 1/100,000 หรือคลาดเคลื่อนทศนิยม 10 เท่า",
        "ถูก — 333.3 mg ÷ 40,000 cm² = 8.3 µg/cm²",
        "เกิดจากใช้ safety factor 1/100 แทน 1/1,000",
        "เป็น limit ต่อ swab 100 cm² ไม่ใช่ต่อ cm²",
      ],
      k: "MACO = (TDD_prev × MBS_next)/(SF × MDD_next); ระวังแปลงหน่วย kg→mg และ mg→µg",
      d: "hard",
      ref: "PIC/S PI 006-3 Cleaning Validation; APIC Guidance on Aspects of Cleaning Validation in API Plants (2021)",
      c: [
        "MBS_B = 80 kg = 80,000,000 mg",
        "MACO = (5 × 80,000,000) ÷ (1,000 × 1,200) = 400,000,000 ÷ 1,200,000 = 333.3 mg",
        "Limit ต่อพื้นที่ = 333.3 mg ÷ 40,000 cm² = 0.00833 mg/cm² = 8.3 µg/cm²",
      ],
    },
    {
      t: "Number of PPQ batches rationale",
      p: "บริษัทกำลังวางแผน Process Performance Qualification (PPQ) ของยาเม็ดใหม่ ตามแนวคิด lifecycle validation (FDA 2011) การกำหนดจำนวน PPQ batches ควรอาศัยหลักการใด",
      o: [
        "อาศัยความรู้จาก Stage 1, ความแปรปรวนของกระบวนการ และ risk assessment พร้อมเหตุผลทางสถิติที่ระบุใน protocol",
        "ต้องเป็น 3 batches ติดต่อกันเสมอตามที่ guideline กำหนดตายตัว",
        "1 batch ก็เพียงพอถ้าผลผ่าน specification",
        "จำนวนเท่ากับจำนวน batches ที่ใช้ใน stability study",
        "ใช้จำนวนเท่าใดก็ได้ตามความสะดวกของฝ่ายผลิต โดยไม่ต้องให้เหตุผล",
      ],
      a: 0,
      r: "FDA Process Validation Guidance (2011) ไม่กำหนดจำนวน batch ตายตัว แต่ให้ผู้ผลิตให้เหตุผลว่าจำนวน PPQ batches และการสุ่มตัวอย่างเพียงพอต่อการแสดงว่ากระบวนการ reproducible ด้วยระดับความเชื่อมั่นที่เหมาะสม โดยพิจารณาความรู้จาก Stage 1 ความแปรปรวน ความซับซ้อนของกระบวนการ และประสบการณ์กับผลิตภัณฑ์ที่คล้ายกัน\n\nตัวเลข 3 batches เป็นธรรมเนียมเดิมและยังใช้อยู่บ่อยใน PIC/S Annex 15 สำหรับ traditional approach แต่ก็ต้องมีเหตุผลรองรับ ผลผ่าน specification เพียง batch เดียวไม่แสดง reproducibility",
      w: [
        "ถูก — จำนวน PPQ batches เป็นการตัดสินใจแบบ science/risk-based ที่ต้องให้เหตุผลใน protocol",
        "Guideline ไม่ได้บังคับ 3 batches ตายตัว แม้จะเป็นจำนวนที่ใช้บ่อย",
        "Batch เดียวไม่แสดงความสม่ำเสมอระหว่าง batch (inter-batch variability)",
        "Stability study และ PPQ มีวัตถุประสงค์ต่างกัน จำนวน batch ไม่ต้องเท่ากัน",
        "จำนวนต้องมีเหตุผลทางวิทยาศาสตร์/สถิติและอนุมัติโดย QA ไม่ใช่ตามความสะดวก",
      ],
      k: "จำนวน PPQ batches = science- and risk-based justification ไม่มีตัวเลขบังคับตายตัว",
      d: "medium",
      ref: "FDA Guidance: Process Validation — General Principles and Practices (2011), Section IV.C.2; PIC/S PE 009 Annex 15 Section 5",
    },
    {
      t: "GAMP 5 V-model test pairing",
      p: "ตาม V-model ใน GAMP 5 สำหรับการ validate ระบบคอมพิวเตอร์ (เช่น LIMS ที่ configure แล้ว) เอกสาร User Requirements Specification (URS) จับคู่กับการทดสอบระดับใด",
      o: [
        "Performance Qualification / User Acceptance Testing",
        "Installation Qualification",
        "Operational Qualification ของแต่ละ function",
        "Unit testing ของ source code",
        "Design Qualification",
      ],
      a: 0,
      r: "V-model แสดงด้านซ้ายเป็น specification จากระดับสูงลงล่าง (URS → Functional Specification → Design/Configuration Specification) และด้านขวาเป็นการ verification ที่จับคู่กันจากล่างขึ้นบน: Design/Configuration Spec ↔ IQ (installation/configuration verification), Functional Spec ↔ OQ (functional testing), URS ↔ PQ/UAT (ยืนยันว่าระบบตอบสนองความต้องการของผู้ใช้ในการใช้งานจริง)\n\nGAMP 5 เน้น risk-based และให้นำผลทดสอบของ supplier มาใช้ได้เพื่อลดงานซ้ำ",
      w: [
        "ถูก — URS ถูกยืนยันด้วย PQ/UAT ซึ่งทดสอบตาม business process ของผู้ใช้",
        "IQ จับคู่กับ design/configuration specification",
        "OQ จับคู่กับ functional specification",
        "Unit/code testing จับคู่กับ module design ใช้กับ custom software (Category 5)",
        "DQ เป็นการยืนยันว่า design ตรงกับ URS ก่อนติดตั้ง ไม่ใช่การทดสอบด้านขวาของ V",
      ],
      k: "V-model: URS ↔ PQ/UAT, FS ↔ OQ, DS/CS ↔ IQ",
      d: "medium",
      ref: "ISPE GAMP 5: A Risk-Based Approach to Compliant GxP Computerized Systems (2nd ed., 2022)",
    },
    {
      t: "Planned deviation versus change control",
      p: "ผู้ผลิต povidone รายเดิมขาดส่งชั่วคราว ฝ่ายจัดซื้อเสนอใช้ povidone เกรดเดียวกันจากผู้ผลิตอีกรายที่อยู่ในทะเบียนตำรับแล้ว (approved alternate source) สำหรับ 3 batches ถัดไปเท่านั้น จากนั้นจะกลับไปใช้ผู้ผลิตเดิม ข้อใดเป็นการจัดการเชิงระบบคุณภาพที่เหมาะสมที่สุด",
      o: [
        "ทำ planned deviation ที่มี risk assessment และ QA อนุมัติก่อนดำเนินการ ระบุจำนวน batch ขอบเขต และการติดตามผล",
        "ใช้ได้เลยโดยไม่ต้องบันทึก เพราะเป็นแหล่งที่อยู่ในทะเบียนแล้ว",
        "เปิด unplanned deviation หลังผลิตเสร็จทั้ง 3 batches",
        "ต้องยื่น variation ต่อหน่วยงานกำกับก่อนผลิตทุกครั้ง แม้เป็นแหล่งที่อนุมัติแล้ว",
        "ทำ change control ถาวรเพื่อเปลี่ยนผู้ผลิตหลัก แล้วค่อยเปลี่ยนกลับด้วย change control อีกครั้ง",
      ],
      a: 0,
      r: "Planned deviation ใช้กับการเบี่ยงเบนชั่วคราวที่รู้ล่วงหน้าและมีขอบเขตจำกัด (จำนวน batch/ระยะเวลา) จาก procedure หรือ MBR ที่อนุมัติ โดยต้องมี risk assessment และ QA อนุมัติก่อนดำเนินการ ส่วน change control ใช้กับการเปลี่ยนแปลงถาวรของระบบ/กระบวนการ\n\nเนื่องจากแหล่งทางเลือกอยู่ใน marketing authorization แล้ว จึงไม่ต้องยื่น variation แต่การผลิตจาก source ที่ไม่ใช่ตาม MBR ปัจจุบันยังต้องได้รับการควบคุม เช่น ยืนยัน supplier qualification ยังมีผล และพิจารณาการติดตามผล (เช่น เพิ่ม stability หรือ IPC) ตามความเสี่ยง การเปิด deviation หลังทำไปแล้วแสดงว่าระบบควบคุมล้มเหลว",
      w: [
        "ถูก — เหตุการณ์ชั่วคราว ทราบล่วงหน้า มีขอบเขตชัด เหมาะกับ planned deviation ที่อนุมัติก่อน",
        "การเบี่ยงเบนจาก MBR/ผู้ผลิตที่ระบุต้องมีการบันทึกและอนุมัติ แม้แหล่งอยู่ในทะเบียน",
        "เหตุการณ์ที่วางแผนได้ล่วงหน้าต้องอนุมัติก่อนทำ การเปิด deviation ย้อนหลังไม่เหมาะสม",
        "แหล่งที่ระบุใน MA อยู่แล้วไม่ต้องยื่น variation ใหม่",
        "การทำ change control สองรอบสำหรับการใช้ชั่วคราวเป็นภาระเกินจำเป็นและสื่อผิดว่าเป็นการเปลี่ยนถาวร",
      ],
      k: "ชั่วคราว + วางแผนล่วงหน้า + ขอบเขตจำกัด → planned deviation (อนุมัติก่อน); ถาวร → change control",
      d: "hard",
      ref: "ICH Q10 Section 3.2.3 (change management); PIC/S GMP Guide PE 009 Part I Ch.1.4",
    },
    {
      t: "Product quality review contents",
      p: "ในการจัดทำ Product Quality Review (PQR) ประจำปีตาม PIC/S GMP หัวข้อใด “ไม่ใช่” เนื้อหาที่ต้องทบทวน",
      o: [
        "ยอดขายและส่วนแบ่งการตลาดของผลิตภัณฑ์เทียบกับคู่แข่ง",
        "Batch ที่ไม่ผ่าน specification และผลการสอบสวน",
        "Change ที่เกิดขึ้นกับกระบวนการหรือวิธีวิเคราะห์",
        "ผลของ ongoing stability programme และแนวโน้มที่ไม่พึงประสงค์",
        "Complaint, การคืนสินค้า และการเรียกคืนที่เกี่ยวกับคุณภาพ",
      ],
      a: 0,
      r: "PQR มีวัตถุประสงค์เพื่อยืนยันความสม่ำเสมอของกระบวนการ ความเหมาะสมของ specification และหาแนวโน้มเพื่อปรับปรุง เนื้อหาตาม PIC/S Ch.1.10 ได้แก่ starting materials (โดยเฉพาะแหล่งใหม่), ผล IPC และ finished product ที่สำคัญ, batch ที่ล้มเหลวและการสอบสวน, deviation ที่สำคัญ, change, variation ต่อ MA, ผล stability, complaint/return/recall, ความเหมาะสมของ CAPA, post-marketing commitments, สถานะ qualification ของเครื่องจักร/utilities และ technical agreements\n\nข้อมูลเชิงการตลาดไม่เกี่ยวกับคุณภาพจึงไม่อยู่ใน PQR",
      w: [
        "ถูก — ยอดขาย/ส่วนแบ่งตลาดไม่ใช่ข้อมูลคุณภาพ ไม่ได้กำหนดให้อยู่ใน PQR",
        "Batch ที่ fail และการสอบสวนเป็นหัวข้อบังคับของ PQR",
        "Change ทั้งหมดที่เกิดในรอบปีต้องทบทวนใน PQR",
        "ผล ongoing stability และ adverse trend ต้องทบทวนใน PQR",
        "Complaint, return และ recall ที่เกี่ยวกับคุณภาพต้องทบทวนใน PQR",
      ],
      k: "PQR ทบทวนข้อมูลคุณภาพทั้งหมดของรอบปี (materials, IPC/FP results, deviations, changes, stability, complaints, CAPA, qualification) เพื่อหา trend",
      d: "medium",
      ref: "PIC/S GMP Guide PE 009 Part I Ch.1.10 Product Quality Review",
    },
    {
      t: "Recall classification and depth",
      p: "ผู้ผลิตพบว่ายาเม็ด warfarin 5 mg lot หนึ่งที่จำหน่ายไปแล้วมีบางเม็ดมีปริมาณตัวยาประมาณ 150% ของที่ระบุ เนื่องจาก segregation ของ blend การตัดสินใจเรื่อง recall ข้อใดเหมาะสมที่สุด",
      o: [
        "จัดเป็น recall ระดับร้ายแรงสูงสุด (Class I) และเรียกคืนถึงระดับผู้ป่วย/ผู้บริโภค",
        "จัดเป็น Class III และเรียกคืนเฉพาะระดับผู้แทนจำหน่าย",
        "จัดเป็น Class II เพราะยังไม่มีรายงานผู้ป่วยเลือดออก และเรียกคืนเฉพาะระดับร้านยา",
        "ไม่ต้อง recall แต่ให้ข้อมูลแพทย์ติดตาม INR ผู้ป่วยแทน",
        "รอผลการวิเคราะห์ retained sample ทั้งหมดและ PQR ประจำปีก่อนตัดสินใจ",
      ],
      a: 0,
      r: "การจัดระดับ recall อิงกับความเสี่ยงต่อสุขภาพ: Class I คือมีโอกาสสมเหตุสมผลที่จะทำให้เกิดผลเสียร้ายแรงหรือเสียชีวิต, Class II อาจทำให้เกิดผลเสียชั่วคราวหรือแก้ไขได้ทางการแพทย์, Class III ไม่น่าจะก่อผลเสียต่อสุขภาพ\n\nWarfarin เป็นยาดัชนีการรักษาแคบ การได้รับเกิน 50% อาจทำให้เลือดออกรุนแรง จึงเป็น Class I และความลึกของการเรียกคืนต้องถึงระดับผู้ป่วยเพราะยาอยู่ในมือผู้ใช้แล้ว การไม่มีรายงานผลเสียไม่ได้ลดระดับความเสี่ยง และการตัดสินใจต้องรวดเร็ว ไม่รอ PQR",
      w: [
        "ถูก — ยา NTI ได้รับเกินขนาดมีโอกาสเกิดอันตรายร้ายแรง ต้อง Class I และเรียกคืนถึงระดับผู้บริโภค",
        "Class III ใช้กับข้อบกพร่องที่ไม่น่าก่อผลเสีย เช่น ข้อผิดพลาดเล็กน้อยของบรรจุภัณฑ์",
        "การจัดระดับอิงศักยภาพความเสี่ยง ไม่ใช่การรอให้มีรายงานผู้ป่วย และการหยุดที่ร้านยาไม่ครอบคลุมยาที่ผู้ป่วยถืออยู่",
        "การแจ้งแพทย์ไม่ทดแทนการนำผลิตภัณฑ์บกพร่องออกจากตลาด",
        "การรอข้อมูลที่ไม่จำเป็นทำให้ผู้ป่วยได้รับความเสี่ยงนานขึ้น PQR ไม่ใช่เครื่องมือตัดสินใจ recall",
      ],
      k: "Recall class ขึ้นกับ health hazard (Class I = อันตรายร้ายแรง/เสียชีวิต); ความลึกของ recall ขึ้นกับว่ายาไปถึงระดับใด",
      d: "hard",
      ref: "PIC/S GMP Guide PE 009 Part I Ch.8 Complaints and Product Recalls; WHO TRS 961 Annex 9 / FDA 21 CFR 7.3(m)",
    },
    {
      t: "Lot acceptance and complaint rate metrics",
      p: "ในปีที่ผ่านมาโรงงานมี lot ที่ผ่านการพิจารณาปล่อย/ไม่ปล่อย (dispositioned) ทั้งหมด 250 lots ถูก reject 4 lots และจำหน่ายผลิตภัณฑ์ 5,000,000 หน่วย มี product quality complaint 35 เรื่อง ข้อใดคำนวณ quality metrics ได้ถูกต้อง",
      o: [
        "Lot acceptance rate 98.4% และ complaint rate 7 เรื่องต่อ 1 ล้านหน่วย",
        "Lot acceptance rate 1.6% และ complaint rate 7 เรื่องต่อ 1 ล้านหน่วย",
        "Lot acceptance rate 98.4% และ complaint rate 0.7 เรื่องต่อ 1 ล้านหน่วย",
        "Lot acceptance rate 96.0% และ complaint rate 70 เรื่องต่อ 1 ล้านหน่วย",
        "Lot acceptance rate 98.4% และ complaint rate 14% ของ lots",
      ],
      a: 0,
      r: "Quality metrics ที่ FDA เสนอในร่าง guidance ได้แก่ Lot Acceptance Rate (LAR) = จำนวน lot ที่ยอมรับ / จำนวน lot ที่ dispositioned, Product Quality Complaint Rate = จำนวน complaint / จำนวนหน่วยที่จำหน่าย (มักแสดงต่อ 1 ล้านหน่วย) และ Invalidated OOS rate\n\nLAR = (250 − 4)/250 = 98.4%; complaint rate = 35/5,000,000 × 1,000,000 = 7 ต่อล้านหน่วย Metrics เหล่านี้ใช้ใน management review เพื่อดูแนวโน้มประสิทธิภาพของ PQS และควรตีความร่วมกับข้อมูลอื่น ไม่ใช่ตัวเลขเดี่ยว",
      w: [
        "ถูก — 246/250 = 98.4% และ 35 ÷ 5 ล้าน = 7 ต่อล้านหน่วย",
        "1.6% คือ lot rejection rate ไม่ใช่ acceptance rate",
        "Complaint rate คำนวณผิดหลักทศนิยม 10 เท่า",
        "96.0% เกิดจากใช้ 10 lots เป็นจำนวน reject และ complaint rate คลาดเคลื่อน 10 เท่า",
        "Complaint rate ต้องเทียบกับจำนวนหน่วยที่จำหน่าย ไม่ใช่จำนวน lot",
      ],
      k: "LAR = accepted lots / dispositioned lots; complaint rate = complaints / units distributed (ต่อล้านหน่วย)",
      d: "medium",
      ref: "FDA Draft Guidance: Submission of Quality Metrics Data (2016); ICH Q10 Section 4.1 (management review)",
      c: [
        "Accepted lots = 250 − 4 = 246",
        "LAR = 246 ÷ 250 × 100 = 98.4%",
        "Complaint rate = 35 ÷ 5,000,000 × 1,000,000 = 7 ต่อ 1 ล้านหน่วย",
      ],
    },
  ],
];
