import type { Ip1MockDomainContent } from "@/lib/ip1-mock/types";

export const QA: Ip1MockDomainContent = [
  // Mock Set 1 — ชุดที่ 1
  [
    {
      t: "FMEA RPN prioritization",
      p: "ทีม QRM ทำ FMEA กระบวนการบรรจุแคปซูล ได้คะแนน (S, O, D) ดังนี้ A = (8, 3, 4), B = (6, 5, 5), C = (9, 2, 7), D = (5, 6, 3), E = (7, 4, 6) หากองค์กรจัดลำดับความสำคัญด้วย RPN เพียงอย่างเดียว failure mode ใดควรได้รับการจัดการเป็นลำดับแรก",
      o: [
        "Failure mode E (RPN = 168)",
        "Failure mode B (RPN = 150)",
        "Failure mode C (RPN = 126) เพราะ severity สูงสุด",
        "Failure mode A (RPN = 96)",
        "Failure mode D (RPN = 90) เพราะ occurrence สูงสุด",
      ],
      a: 0,
      r: "RPN (Risk Priority Number) = Severity × Occurrence × Detectability โดยแต่ละปัจจัยมักให้คะแนน 1–10 และ D ที่สูงหมายถึงตรวจจับได้ยาก\n\nคำนวณได้ A = 96, B = 150, C = 126, D = 90, E = 168 ดังนั้นถ้าใช้ RPN อย่างเดียว E มีลำดับสูงสุด อย่างไรก็ตามในทางปฏิบัติ ICH Q9(R1) เตือนว่าคะแนนเชิงตัวเลขมี subjectivity และหลายองค์กรกำหนดกฎเสริม เช่น S ≥ 9 ต้องพิจารณาเสมอแม้ RPN ต่ำ ซึ่งทำให้ C ควรถูกทบทวนด้วยเช่นกัน",
      w: [
        "ถูก — 7 × 4 × 6 = 168 สูงที่สุดในทั้ง 5 failure modes เมื่อใช้ RPN เป็นเกณฑ์เดียว",
        "B = 6 × 5 × 5 = 150 เป็นลำดับที่สอง ไม่ใช่สูงสุด",
        "C = 9 × 2 × 7 = 126 แม้ S สูงสุดแต่โจทย์กำหนดให้จัดลำดับด้วย RPN เพียงอย่างเดียว (ในชีวิตจริงควรมีกฎเสริมสำหรับ S สูง)",
        "A = 8 × 3 × 4 = 96 ต่ำกว่า E, B และ C",
        "D = 5 × 6 × 3 = 90 ต่ำสุด แม้ O สูงสุดแต่ RPN รวมไม่ได้สูง",
      ],
      k: "RPN = S × O × D; ใช้จัดลำดับได้แต่ควรมีกฎเสริมสำหรับ severity สูง เพราะ RPN เท่ากันอาจมี risk profile ต่างกัน",
      d: "medium",
      ref: "ICH Q9(R1) Quality Risk Management, Annex I (FMEA)",
      c: [
        "A = 8 × 3 × 4 = 96",
        "B = 6 × 5 × 5 = 150",
        "C = 9 × 2 × 7 = 126",
        "D = 5 × 6 × 3 = 90",
        "E = 7 × 4 × 6 = 168 → สูงสุด",
      ],
    },
    {
      t: "ICH Q9 risk assessment components",
      p: "ตาม ICH Q9(R1) กระบวนการ risk assessment ประกอบด้วยขั้นตอนย่อยใดบ้าง",
      o: [
        "Risk identification, risk analysis และ risk evaluation",
        "Risk reduction, risk acceptance และ risk review",
        "Risk identification, risk communication และ risk acceptance",
        "Risk analysis, risk control และ risk review",
        "Hazard identification, CAPA และ management review",
      ],
      a: 0,
      r: "ICH Q9(R1) แบ่ง QRM process เป็น risk assessment → risk control → risk communication → risk review โดย risk assessment ประกอบด้วย risk identification (มีอะไรผิดพลาดได้), risk analysis (โอกาสเกิดและความรุนแรง รวมถึงการตรวจจับ) และ risk evaluation (เทียบกับเกณฑ์ว่าเสี่ยงยอมรับได้หรือไม่)\n\nRisk control ประกอบด้วย risk reduction และ risk acceptance ส่วน risk communication และ risk review เป็นกิจกรรมที่ดำเนินตลอดวงจร",
      w: [
        "ถูก — สามขั้นตอนของ risk assessment ตาม ICH Q9(R1) คือ identification, analysis, evaluation",
        "Risk reduction และ risk acceptance เป็นส่วนของ risk control ส่วน risk review เป็นขั้นตอนทบทวนภายหลัง",
        "Risk communication และ risk acceptance ไม่ได้อยู่ใน risk assessment",
        "Risk control และ risk review เป็นขั้นตอนถัดไปหลัง risk assessment",
        "CAPA และ management review เป็นองค์ประกอบของ PQS (ICH Q10) ไม่ใช่ขั้นตอนย่อยของ risk assessment",
      ],
      k: "Risk assessment = identify → analyze → evaluate; Risk control = reduce + accept",
      d: "easy",
      ref: "ICH Q9(R1) Quality Risk Management, Section 4",
    },
    {
      t: "Critical deviation classification",
      p: "ระหว่าง line clearance ของวันถัดมา พบว่ากล่องยาเม็ด Amlodipine 10 mg ที่บรรจุเสร็จแล้วบางกล่องมีแผง blister ของ Amlodipine 5 mg ปะปนอยู่ ควรจัดระดับ deviation นี้อย่างไรเหมาะสมที่สุด",
      o: [
        "Critical deviation เพราะเป็น product mix-up ที่อาจทำให้ผู้ป่วยได้รับยาผิดความแรง",
        "Major deviation เพราะพบก่อนปล่อยยาจึงไม่กระทบผู้ป่วย",
        "Minor deviation เพราะเป็นยาตัวเดียวกันต่างกันแค่ความแรง",
        "ไม่ต้องจัดเป็น deviation แค่คัดแยกกล่องที่ผิดออกก็เพียงพอ",
        "Minor deviation หากผล assay ของ batch อยู่ในเกณฑ์",
      ],
      a: 0,
      r: "การจัดระดับ deviation อิงกับผลกระทบต่อคุณภาพและความปลอดภัยของผู้ป่วย: critical คือมีโอกาสก่อให้เกิดอันตรายต่อผู้ป่วยหรือผลิตภัณฑ์ไม่เป็นไปตาม MA อย่างร้ายแรง, major คือมีผลกระทบต่อคุณภาพอย่างมีนัยสำคัญแต่ไม่ถึงขั้นอันตรายโดยตรง, minor คือไม่มีผลกระทบต่อคุณภาพ\n\nMix-up ของความแรงเป็นตัวอย่างคลาสสิกของ critical เพราะผู้ป่วยอาจได้รับยาผิดขนาด และบ่งชี้ความล้มเหลวของ line clearance/segregation การพบก่อนปล่อยยาไม่ได้ลดระดับของความล้มเหลวของระบบ ต้อง quarantine ทั้ง batch, ขยายการสอบสวนไป batch อื่นที่ใช้ line เดียวกัน และทำ CAPA",
      w: [
        "ถูก — mix-up ต่างความแรงมีโอกาสก่อให้เกิดอันตรายต่อผู้ป่วยโดยตรง จัดเป็น critical",
        "การตรวจพบก่อนปล่อยไม่ลดความรุนแรงของความล้มเหลวของระบบ ศักยภาพในการเกิดอันตรายยังเป็นตัวกำหนดระดับ",
        "ความแรงต่างกันสองเท่าเป็นความเสี่ยงต่อผู้ป่วยชัดเจน ไม่ใช่เรื่องเล็กน้อย",
        "ทุกเหตุการณ์ที่เบี่ยงเบนจาก procedure ต้องบันทึกเป็น deviation และสอบสวนหา root cause ไม่ใช่แค่ correction",
        "ผล assay ไม่สะท้อน mix-up ระดับหน่วยบรรจุ และไม่ลดความเสี่ยงที่ผู้ป่วยได้ยาผิดความแรง",
      ],
      k: "Mix-up (ผิดความแรง/ผิดตัวยา/ผิดฉลาก) = critical deviation เสมอ ต้อง quarantine และขยายขอบเขตการสอบสวน",
      d: "medium",
      ref: "PIC/S GMP Guide PE 009 Part I Ch.1 & Ch.8; WHO TRS 1025 Annex (deviation handling)",
    },
    {
      t: "Ishikawa 6M categorization",
      p: "ในการทำ Ishikawa (fishbone) diagram ของปัญหา tablet weight variation ทีมระบุสาเหตุที่เป็นไปได้ว่า “excipient lot ใหม่มี particle size ละเอียดกว่าเดิม ทำให้การไหลแย่ลง” สาเหตุนี้ควรจัดอยู่ในหมวดใดของ 6M",
      o: ["Material", "Machine", "Method", "Man", "Measurement"],
      a: 0,
      r: "Ishikawa diagram ใช้จัดกลุ่มสาเหตุที่เป็นไปได้ตามหมวด 6M ได้แก่ Man (คน), Machine (เครื่องจักร), Method (วิธีการ/SOP/พารามิเตอร์), Material (วัตถุดิบ/บรรจุภัณฑ์), Measurement (การวัด/เครื่องมือวัด) และ Mother Nature/Milieu (สิ่งแวดล้อม)\n\nสาเหตุที่มาจากคุณสมบัติของวัตถุดิบ เช่น particle size, moisture, lot-to-lot variability ของ excipient จัดเป็น Material Ishikawa เป็นเครื่องมือระดมสมองเพื่อหา potential causes ต้องตรวจยืนยันด้วยข้อมูลก่อนสรุปเป็น root cause",
      w: [
        "ถูก — คุณสมบัติของ excipient lot ใหม่เป็นสาเหตุด้านวัตถุดิบ (Material)",
        "Machine ใช้กับสาเหตุจากเครื่องตอก เช่น feeder, punch wear ไม่ใช่คุณสมบัติผง",
        "Method ใช้กับวิธีการ/พารามิเตอร์ใน MBR เช่น เวลาผสม ความเร็ว turret",
        "Man ใช้กับสาเหตุด้านบุคลากร เช่น การฝึกอบรม การปฏิบัติไม่ตาม SOP",
        "Measurement ใช้กับความผิดพลาดของการวัด เช่น เครื่องชั่ง IPC ไม่ได้ calibrate",
      ],
      k: "6M = Man, Machine, Method, Material, Measurement, Mother nature; Ishikawa ให้ potential causes ต้องยืนยันด้วยข้อมูล",
      d: "easy",
      ref: "ICH Q9(R1) Annex I (basic risk management facilitation methods)",
    },
    {
      t: "Process validation Stage 2 activities",
      p: "ตามแนวทาง process validation แบบ lifecycle (FDA 2011) กิจกรรมใดจัดอยู่ใน Stage 2 (Process Qualification)",
      o: [
        "การทำ PPQ batches ตาม protocol ที่อนุมัติล่วงหน้า หลังจาก qualify facility, utilities และ equipment แล้ว",
        "การทำ DoE เพื่อกำหนด design space และ critical process parameters",
        "การเก็บข้อมูล CPP/CQA จาก commercial batches อย่างต่อเนื่องเพื่อติดตามแนวโน้ม",
        "การทำ Product Quality Review ประจำปี",
        "การ scale-up จาก lab scale ไป pilot scale เพื่อหา control strategy",
      ],
      a: 0,
      r: "FDA Process Validation Guidance (2011) แบ่ง 3 stage: Stage 1 Process Design (สร้างความเข้าใจกระบวนการ, DoE, กำหนด control strategy), Stage 2 Process Qualification (2a: qualify facility/utilities/equipment, 2b: PPQ ที่ commercial scale ตาม protocol) และ Stage 3 Continued Process Verification (ติดตามข้อมูลต่อเนื่องระหว่างการผลิตเชิงพาณิชย์)\n\nPPQ จึงเป็นหัวใจของ Stage 2 ซึ่งต้องผ่านก่อนการจำหน่ายเชิงพาณิชย์ (commercial distribution)",
      w: [
        "ถูก — equipment/utility qualification และ PPQ เป็นกิจกรรมของ Stage 2",
        "DoE และการกำหนด design space เป็นกิจกรรม Stage 1 (Process Design)",
        "การติดตามข้อมูล commercial batches อย่างต่อเนื่องคือ Stage 3 (CPV)",
        "PQR เป็นการทบทวนระดับ PQS ที่สนับสนุน Stage 3 ไม่ใช่ Process Qualification",
        "การ scale-up เพื่อสร้างความรู้และ control strategy เป็นส่วนของ Stage 1",
      ],
      k: "Stage 1 = Design, Stage 2 = Qualification (equipment + PPQ), Stage 3 = Continued Process Verification",
      d: "medium",
      ref: "FDA Guidance for Industry: Process Validation — General Principles and Practices (2011)",
    },
    {
      t: "Cleaning limit by 10 ppm criterion",
      p: "เครื่องผสมใช้ร่วมกันระหว่างยา A (ผลิตก่อน) และยา B (ผลิตถัดไป) บริษัทใช้เกณฑ์ 10 ppm สำหรับ residue ของยา A ในยา B ขนาด batch ของยา B = 150 kg พื้นที่ผิวสัมผัสรวม = 30,000 cm² และพื้นที่ swab = 25 cm² ต่อจุด ค่า acceptance limit ต่อ swab คือข้อใด",
      o: ["50 µg/swab", "125 µg/swab", "1,250 µg/swab", "12,500 µg/swab", "60,000 µg/swab"],
      a: 2,
      r: "เกณฑ์ 10 ppm หมายถึงยา A ปนเปื้อนในยา B ได้ไม่เกิน 10 mg ต่อยา B 1 kg ดังนั้น MACO = 10 mg/kg × ขนาด batch ของยาถัดไป จากนั้นสมมติว่า residue กระจายสม่ำเสมอบนพื้นผิวสัมผัสทั้งหมด หารด้วยพื้นที่รวมได้ limit ต่อ cm² แล้วคูณพื้นที่ swab\n\nMACO = 10 × 150 = 1,500 mg; ต่อ cm² = 1,500 mg / 30,000 cm² = 0.05 mg/cm² = 50 µg/cm²; ต่อ swab 25 cm² = 1,250 µg ปัจจุบันแนวทาง EMA/PIC/S แนะนำให้ใช้ HBEL (PDE) เป็นหลัก โดย 10 ppm อาจใช้เป็นเกณฑ์เสริม",
      w: [
        "50 µg คือ limit ต่อ cm² ลืมคูณพื้นที่ swab 25 cm²",
        "125 µg เกิดจากคำนวณ MACO ผิดเป็น 150 mg (ใช้ 1 ppm แทน 10 ppm)",
        "ถูก — 1,500 mg ÷ 30,000 cm² × 25 cm² = 1.25 mg = 1,250 µg ต่อ swab",
        "12,500 µg เกิดจาก error หลักทศนิยม 10 เท่า",
        "60,000 µg เกิดจากเอา MACO 1,500 mg หารด้วยพื้นที่ swab โดยตรง ไม่ได้คิดพื้นที่ผิวรวม",
      ],
      k: "10 ppm: MACO (mg) = 10 × batch size ถัดไป (kg); limit/swab = MACO ÷ พื้นที่รวม × พื้นที่ swab",
      d: "hard",
      ref: "PIC/S PI 006-3 Recommendations on Validation Master Plan, IQ, OQ, Non-sterile Process Validation, Cleaning Validation",
      c: [
        "MACO = 10 mg/kg × 150 kg = 1,500 mg",
        "Limit ต่อพื้นที่ = 1,500 mg ÷ 30,000 cm² = 0.05 mg/cm² = 50 µg/cm²",
        "Limit ต่อ swab = 50 µg/cm² × 25 cm² = 1,250 µg",
      ],
    },
    {
      t: "Operational qualification test scope",
      p: "บริษัทติดตั้ง fluid bed dryer เครื่องใหม่ การทดสอบใดจัดเป็น Operational Qualification (OQ) ที่เหมาะสมที่สุด",
      o: [
        "ทดสอบการควบคุม inlet air temperature และ airflow ตลอดช่วงการใช้งาน รวมถึง alarm และ interlock โดยยังไม่ใช้ผลิตภัณฑ์จริง",
        "ตรวจสอบว่า utilities ต่อถูกต้อง วัสดุผิวสัมผัสเป็น SS316L และมีเอกสาร as-built drawing ครบ",
        "อบแกรนูลของผลิตภัณฑ์จริง 3 batches แล้วได้ LOD อยู่ในเกณฑ์อย่างสม่ำเสมอ",
        "จัดทำ user requirement specification ระบุกำลังการผลิตและช่วงอุณหภูมิที่ต้องการ",
        "ตรวจรับเครื่องที่โรงงานผู้ผลิตก่อนส่งมอบ (FAT)",
      ],
      a: 0,
      r: "Equipment qualification เรียงเป็น URS → DQ → (FAT/SAT) → IQ → OQ → PQ โดย IQ ยืนยันว่าติดตั้งถูกต้องตามแบบ (วัสดุ, utilities, เอกสาร, calibration ของเครื่องมือวัด), OQ ยืนยันว่าเครื่องทำงานตามที่ออกแบบตลอดช่วงการใช้งานที่คาดไว้ รวมถึง upper/lower limits, alarm, interlock มักทดสอบโดยไม่มีผลิตภัณฑ์หรือใช้ placebo, PQ ยืนยันว่าเครื่องทำงานได้สม่ำเสมอภายใต้สภาวะการผลิตจริง\n\nการทดสอบ control range และ alarm/interlock จึงเป็น OQ",
      w: [
        "ถูก — การทดสอบ function, operating range, alarm และ interlock คือหัวใจของ OQ",
        "การตรวจวัสดุ, utilities และเอกสารเป็น IQ",
        "การใช้ผลิตภัณฑ์จริงซ้ำๆ เพื่อแสดงความสม่ำเสมอภายใต้สภาวะจริงเป็น PQ",
        "URS เป็นเอกสารต้นทางที่ระบุความต้องการของผู้ใช้ จัดทำก่อน DQ",
        "FAT ทำที่โรงงานผู้ผลิตเครื่อง ช่วยลดงานแต่ไม่ใช่ OQ ที่ไซต์ผู้ใช้",
      ],
      k: "IQ = ติดตั้งถูก, OQ = ทำงานถูกตลอด operating range + alarm/interlock, PQ = ทำงานสม่ำเสมอในสภาวะจริง",
      d: "medium",
      ref: "PIC/S GMP Guide PE 009 Annex 15 Qualification and Validation, Section 3",
    },
    {
      t: "CAPA effectiveness check design",
      p: "หลังเกิด deviation ซ้ำเรื่องการบันทึกน้ำหนักวัตถุดิบผิดใน batch record ทีมกำหนด CAPA คือปรับ SOP ให้ใช้เครื่องชั่งที่พิมพ์ผลอัตโนมัติและฝึกอบรมพนักงาน ข้อใดเป็น effectiveness check ที่เหมาะสมที่สุด",
      o: [
        "ติดตามว่าไม่มี deviation ชนิดเดียวกันเกิดซ้ำใน batch ที่ผลิตช่วง 6 เดือนถัดไป ตามเกณฑ์ที่กำหนดไว้ล่วงหน้า",
        "ยืนยันว่าพนักงานทุกคนลงนามในใบบันทึกการฝึกอบรมครบ",
        "ยืนยันว่า SOP ฉบับใหม่ได้รับอนุมัติและแจกจ่ายแล้ว",
        "ปิด CAPA ทันทีเมื่อเครื่องชั่งใหม่ผ่าน IQ",
        "ให้หัวหน้าแผนกยืนยันด้วยวาจาว่าปัญหาหมดไปแล้ว",
      ],
      a: 0,
      r: "ICH Q10 กำหนดให้ CAPA ต้องมีการประเมิน effectiveness ซึ่งต่างจากการยืนยันว่าดำเนินการเสร็จ (implementation/completion) Effectiveness check ควรตอบว่า CAPA ขจัด root cause และป้องกันการเกิดซ้ำได้จริงหรือไม่ โดยกำหนด metric, ช่วงเวลา และเกณฑ์ผ่านไว้ล่วงหน้า เช่น อัตราการเกิดซ้ำเป็นศูนย์ใน N batches หรือ X เดือน\n\nการลงนามฝึกอบรม การอนุมัติ SOP หรือการติดตั้งเครื่องเป็นเพียงหลักฐานว่าได้ทำ action แล้ว ไม่ใช่หลักฐานว่าได้ผล",
      w: [
        "ถูก — วัดผลลัพธ์จริง (recurrence) ในช่วงเวลาที่กำหนดด้วยเกณฑ์ที่ตั้งไว้ล่วงหน้า",
        "การลงนามฝึกอบรมเป็นหลักฐานการดำเนินการ ไม่ได้แสดงว่าพฤติกรรมหรือผลลัพธ์เปลี่ยน",
        "การอนุมัติ SOP เป็น implementation ไม่ใช่ effectiveness",
        "IQ ยืนยันการติดตั้งเครื่อง ยังไม่ได้แสดงว่าปัญหาการบันทึกหายไป",
        "การยืนยันด้วยวาจาไม่ใช่หลักฐานที่เป็นเอกสารและไม่มีเกณฑ์เชิงวัตถุวิสัย",
      ],
      k: "CAPA completion ≠ effectiveness; effectiveness check ต้องวัดผลลัพธ์ด้วย metric/เกณฑ์/ระยะเวลาที่กำหนดล่วงหน้า",
      d: "medium",
      ref: "ICH Q10 Pharmaceutical Quality System, Section 3.2.2",
    },
    {
      t: "Batch certification with open deviation",
      p: "Batch ยาเม็ดเคลือบฟิล์มผ่านการตรวจวิเคราะห์ครบตาม specification แต่ยังมี major deviation เรื่อง granulation endpoint เกินเวลาที่ validate ไว้ ซึ่งการสอบสวนยังไม่ปิด ฝ่ายขายต้องการให้ปล่อยยาด่วน ผู้มีอำนาจปล่อยผลิตภัณฑ์ (authorized person) ควรทำอย่างไร",
      o: [
        "ยังไม่รับรองปล่อย batch จนกว่าการสอบสวนจะสรุป impact ต่อคุณภาพและได้รับการประเมินอนุมัติแล้ว",
        "ปล่อยได้ทันทีเพราะผล QC ผ่าน specification ครบทุกข้อ",
        "ปล่อยได้หากฝ่ายผลิตรับรองว่าไม่มีผลกระทบ",
        "ปล่อยแบบมีเงื่อนไขแล้วค่อยปิด deviation ภายหลัง หากพบปัญหาจึงเรียกคืน",
        "ส่งตัวอย่างเพิ่มไปตรวจ dissolution ซ้ำแล้วปล่อยหากผ่านโดยไม่ต้องรอสอบสวน",
      ],
      a: 0,
      r: "การรับรองปล่อย batch ของ authorized person (AP/QP) ต้องยืนยันว่า batch ผลิตและตรวจสอบตาม GMP และ marketing authorization และว่า deviation ทั้งหมดได้รับการสอบสวนและประเมินผลกระทบจนเป็นที่ยอมรับแล้ว ผลตรวจผ่าน specification เป็นเงื่อนไขจำเป็นแต่ไม่เพียงพอ เพราะการทดสอบมีขนาดตัวอย่างจำกัดและอาจตรวจไม่พบปัญหาที่เกิดจากกระบวนการนอก validated state\n\nการปล่อยก่อนแล้ว 'ค่อยเรียกคืน' เป็นการผลักความเสี่ยงไปให้ผู้ป่วย และแรงกดดันทางธุรกิจต้องไม่มีผลต่อการตัดสินใจของ AP ซึ่งต้องเป็นอิสระจากฝ่ายผลิต",
      w: [
        "ถูก — deviation ที่อาจกระทบคุณภาพต้องสอบสวนและประเมินเสร็จก่อนการรับรองปล่อย",
        "ผล QC ผ่านไม่ได้พิสูจน์ว่าการผลิตนอก validated parameter ไม่มีผลกระทบ (quality cannot be tested into product)",
        "ความรับผิดชอบการปล่อยเป็นของ AP/QA ที่เป็นอิสระ ไม่สามารถมอบให้ฝ่ายผลิตรับรองแทน",
        "การปล่อยโดยหวังพึ่ง recall เป็นการยอมรับความเสี่ยงต่อผู้ป่วยโดยไม่จำเป็น ขัดหลัก GMP",
        "การทดสอบซ้ำไม่ใช่สิ่งทดแทนการสอบสวน root cause และ impact assessment",
      ],
      k: "AP ปล่อย batch ได้เมื่อ (1) ตาม MA/GMP (2) ผล QC ผ่าน และ (3) deviation ทั้งหมดสอบสวน/ประเมินเสร็จ — ผลตรวจผ่านอย่างเดียวไม่พอ",
      d: "hard",
      ref: "PIC/S GMP Guide PE 009 Annex 16 (Certification by an Authorised Person and Batch Release); Part I Ch.1.4",
    },
    {
      t: "Reduced testing based on supplier qualification",
      p: "โรงงานต้องการเปลี่ยนการรับ excipient (microcrystalline cellulose) จากผู้ขายรายหนึ่งเป็นแบบ reduced testing คือยอมรับผลตาม CoA ของผู้ผลิต ข้อใดเป็นเงื่อนไขที่ถูกต้องที่สุด",
      o: [
        "ต้องประเมินและ qualify ผู้ผลิต (เช่น audit/questionnaire) ตรวจสอบความน่าเชื่อถือของ CoA ด้วยการตรวจเต็มเป็นระยะ และยังคงทดสอบ identity ตามที่กำหนด",
        "ยอมรับ CoA ได้ทันทีหากผู้ขายเป็นตัวแทนจำหน่ายรายใหญ่ที่มีใบอนุญาต",
        "หากใช้ CoA แล้วสามารถยกเลิกการทดสอบ identity ทั้งหมดได้",
        "ต้องตรวจเต็มทุก lot ตลอดไป เพราะ GMP ไม่อนุญาตให้ใช้ CoA ของผู้ผลิต",
        "ทำ audit ผู้ผลิตครั้งเดียวตอนเริ่มต้น หลังจากนั้นไม่ต้องทบทวนอีก",
      ],
      a: 0,
      r: "GMP อนุญาตให้ลดการทดสอบวัตถุดิบโดยอาศัย CoA ของผู้ผลิตได้ ถ้าระบบ supplier qualification แสดงความน่าเชื่อถือ ได้แก่ การประเมิน/ตรวจสอบผู้ผลิต (risk-based audit), การยืนยันว่า supply chain โปร่งใสและสืบย้อนถึงผู้ผลิตจริงได้, มี quality agreement, และการตรวจสอบความถูกต้องของ CoA ด้วยการทดสอบเต็มเป็นระยะ (CoA validation) แต่การทดสอบ identity ยังคงต้องทำตามข้อกำหนด GMP\n\nสถานะของผู้ขายต้องได้รับการทบทวนเป็นระยะ (re-qualification) โดยพิจารณาข้อมูลคุณภาพ เช่น การปฏิเสธ lot, complaint และผล audit",
      w: [
        "ถูก — ครอบคลุม qualification ผู้ผลิต, การยืนยันความน่าเชื่อถือ CoA เป็นระยะ และคง identity test",
        "การเป็นตัวแทนจำหน่ายรายใหญ่ไม่ใช่หลักฐานคุณภาพ ต้องสืบย้อนและประเมินผู้ผลิตจริง",
        "Identity test ไม่สามารถยกเลิกได้แม้ใช้ CoA เพราะเป็นการป้องกันการรับวัตถุดิบผิดชนิด",
        "GMP อนุญาต reduced testing ได้ภายใต้ระบบ supplier qualification ที่เหมาะสม",
        "Supplier qualification เป็น lifecycle ต้องมี re-evaluation และ periodic audit ตามความเสี่ยง",
      ],
      k: "Reduced testing ได้เมื่อ supplier qualified + CoA ถูก verify เป็นระยะ + ยังทำ identity test เสมอ",
      d: "hard",
      ref: "PIC/S GMP Guide PE 009 Part I Ch.5 (5.29–5.36) and Ch.7; ICH Q7 Section 7.3",
    },
  ],
];
