import type { Ip1MockDomainContent } from "@/lib/ip1-mock/types";

export const SOLID: Ip1MockDomainContent = [
  // Mock Set 1 — ชุดที่ 1
  [
    {
      t: "Percolation segregation in hopper",
      p: "ระหว่างตอกยาเม็ดโดยตรง (direct compression) พบว่าเม็ดยาช่วงท้าย batch มี assay สูงขึ้นเรื่อย ๆ ตรวจพบว่า API มีขนาดอนุภาคละเอียด (~15 µm) ส่วน filler เป็น granular grade (~200 µm) และ hopper สั่นสะเทือนตลอดการตอก กลไกการแยกชั้น (segregation) ใดอธิบายเหตุการณ์นี้ได้ดีที่สุด",
      o: [
        "Percolation (sifting) — อนุภาคละเอียดร่อนผ่านช่องว่างระหว่างอนุภาคหยาบลงไปสะสมด้านล่าง",
        "Trajectory segregation — อนุภาคใหญ่กระเด็นไกลกว่าเมื่อตกลงบนกองผง",
        "Elutriation — อนุภาคละเอียดลอยขึ้นด้านบนเพราะกระแสอากาศ",
        "Agglomeration — อนุภาคละเอียดจับกันเป็นก้อนจนกลายเป็นอนุภาคใหญ่",
        "Electrostatic adhesion — อนุภาคละเอียดเกาะผนัง hopper จนหมดไปจาก blend",
      ],
      a: 0,
      r: "Segregation เกิดเมื่อผงมีความแตกต่างของขนาด รูปร่าง หรือความหนาแน่นของอนุภาค และได้รับแรงกระทำ เช่น การสั่น การไหล หรือการเท กลไกหลักมี 3 แบบ คือ percolation (sifting), trajectory และ air entrainment/elutriation\n\nในกรณีนี้ API ละเอียดมากเมื่อเทียบกับ filler (อัตราส่วนขนาดสูง) และมีการสั่นต่อเนื่อง อนุภาคละเอียดจึงร่อนผ่านช่องว่างของอนุภาคหยาบลงไปสะสมที่ส่วนล่างของ hopper ซึ่งเป็นส่วนที่ไหลออกมาภายหลังในบางรูปแบบการไหล (หรือกระจุกตัวไม่สม่ำเสมอ) ทำให้ content ของเม็ดยาเปลี่ยนตามเวลา\n\nการแก้ไขที่ตรงจุดคือทำให้ขนาดอนุภาคใกล้เคียงกัน (เช่น ใช้ filler ที่ละเอียดขึ้น ทำ granulation หรือ ordered mixing) ลดการสั่นและระยะการตก และออกแบบ hopper ให้เป็น mass flow",
      w: [
        "ถูก — อัตราส่วนขนาดอนุภาคสูงร่วมกับการสั่นเป็นเงื่อนไขคลาสสิกของ percolation segregation",
        "Trajectory segregation เกิดเมื่อผงพุ่งออกจากสายพานหรือปลายท่อแล้วตกลงกอง ไม่ใช่กลไกหลักเมื่อมีการสั่นใน hopper",
        "Elutriation/air entrainment ต้องมีกระแสอากาศแรงพาอนุภาคละเอียดขึ้นด้านบน เช่น ขณะเติมผงลง bin ซึ่งโจทย์ไม่ได้บ่งชี้",
        "Agglomeration ไม่ใช่กลไก segregation และถ้าเกิดจริงจะทำให้ API กระจายไม่สม่ำเสมอแบบสุ่ม ไม่ใช่แนวโน้มสูงขึ้นตามเวลา",
        "การเกาะผนังด้วยไฟฟ้าสถิตจะทำให้ assay ต่ำลง ไม่ใช่สูงขึ้นในช่วงท้าย batch",
      ],
      k: "อนุภาคต่างขนาดมาก + การสั่น = percolation segregation; แก้ด้วยการทำขนาดให้ใกล้กัน/granulation และลดการสั่น",
      d: "easy",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Mixing",
    },
    {
      t: "High-shear granulation power endpoint",
      p: "โรงงานผลิตยาเม็ดด้วย high-shear wet granulation โดยกำหนด endpoint จากเวลา wet massing คงที่ 3 นาที หลังเปลี่ยน lot ของ MCC พบว่า granule บาง lot เปียกเกินไปและบาง lot แห้งเกินไป แนวทางใดเหมาะสมที่สุดในการควบคุม endpoint ให้สม่ำเสมอ",
      o: [
        "ใช้การวัด impeller power consumption หรือ torque แล้วหยุดเมื่อถึงช่วง plateau ที่กำหนดไว้",
        "เพิ่มเวลา wet massing เป็น 5 นาทีทุก batch เพื่อให้แน่ใจว่าแกรนูลก่อตัวสมบูรณ์",
        "เพิ่มความเร็ว chopper ตลอดกระบวนการเพื่อชดเชยความแปรปรวนของวัตถุดิบ",
        "กำหนดปริมาณน้ำคงที่และอบแห้งนานขึ้นใน batch ที่เปียกเกินไป",
        "ใช้การดูด้วยตาเปล่าของผู้ปฏิบัติงานเป็นเกณฑ์หลักแทนเวลา",
      ],
      a: 0,
      r: "ใน high-shear granulator ค่า power consumption/torque ของ impeller สะท้อนแรงต้านของมวลเปียก ซึ่งสัมพันธ์กับระดับ liquid saturation ของ granule โปรไฟล์มักแบ่งเป็นช่วง moistening, nucleation, ช่วง plateau (สะพานของเหลวแบบ funicular–capillary) และช่วงที่ power พุ่ง/ไม่เสถียรเมื่อ overwet\n\nเมื่อวัตถุดิบเปลี่ยน lot (เช่น MCC มีความสามารถดูดน้ำต่างกัน) เวลาคงที่ไม่สามารถชดเชยได้ การใช้ power/torque endpoint เป็นการควบคุมตามคุณสมบัติจริงของมวลเปียก จึงให้ granule สม่ำเสมอกว่า และเป็นแนวทาง PAT ที่ยอมรับกันทั่วไป",
      w: [
        "ถูก — power/torque สะท้อน liquid saturation ของมวลเปียกโดยตรง จึงชดเชยความแปรปรวนของวัตถุดิบได้",
        "การเพิ่มเวลาคงที่ไม่แก้ปัญหาความแปรปรวน และ lot ที่ดูดน้ำน้อยจะยิ่ง overgranulate",
        "Chopper ช่วยตัดก้อนใหญ่ แต่การเพิ่มความเร็วตลอดเวลาไม่ได้เป็นตัวบอก endpoint และอาจทำให้ granule แน่นเกิน",
        "การอบแห้งนานขึ้นแก้ได้แค่ปริมาณน้ำคงเหลือ แต่โครงสร้าง granule ที่ overgranulate แล้วกลับคืนไม่ได้",
        "การประเมินด้วยตา (squeeze test) ขึ้นกับบุคคล ไม่สามารถทำซ้ำได้ดีพอเป็นเกณฑ์หลัก",
      ],
      k: "Endpoint ของ high-shear granulation ควรควบคุมด้วย power consumption/torque มากกว่าเวลาคงที่",
      d: "medium",
      ref: "Parikh, Handbook of Pharmaceutical Granulation Technology 3rd ed.",
    },
    {
      t: "SSG gel blocking at high level",
      p: "สูตรยาเม็ด wet granulation มี sodium starch glycolate (SSG) 12% w/w เป็น disintegrant ผู้พัฒนาคาดว่าการเพิ่มจาก 6% เป็น 12% จะทำให้แตกตัวเร็วขึ้น แต่ disintegration time กลับนานขึ้นจาก 4 เป็น 9 นาที คำอธิบายและการแก้ไขที่เหมาะสมที่สุดคือข้อใด",
      o: [
        "SSG ที่ระดับสูงพองตัวเป็นชั้นเจลหนืดที่ขวางการแทรกซึมของน้ำ ควรลดเหลือช่วง ~2–8% หรือเปลี่ยนไปใช้ crospovidone ร่วม",
        "SSG ที่ระดับสูงทำให้เม็ดยาแข็งเกินไป ควรเพิ่มแรงตอกเพื่อให้แตกตัวเร็วขึ้น",
        "SSG ทำปฏิกิริยากับ magnesium stearate เป็นสารประกอบไม่ละลายน้ำ ควรเปลี่ยน lubricant",
        "SSG ระดับสูงทำให้ pH ภายในเม็ดยาเป็นกรด ควรเติม buffer ด่างในสูตร",
        "SSG ที่มากขึ้นทำให้ porosity ของเม็ดยาเพิ่ม ควรเพิ่ม binder เพื่อลด porosity",
      ],
      a: 0,
      r: "SSG เป็น superdisintegrant ที่ทำงานหลักโดยการดูดน้ำและพองตัวอย่างรวดเร็ว (swelling หลายเท่าของปริมาตรเดิม) ช่วงความเข้มข้นที่ใช้ทั่วไปประมาณ 2–8% โดยมีจุดเหมาะสมราว 4%\n\nเมื่อใช้มากเกินไป อนุภาคที่พองตัวจะเกิดเป็นเจลหนืดต่อเนื่อง (gel blocking) ปิดกั้นรูพรุนและช่อง capillary ทำให้น้ำแทรกเข้าสู่ภายในเม็ดยาช้าลง disintegration จึงช้าลงแทนที่จะเร็วขึ้น\n\nการแก้ไขคือกลับไปใช้ระดับที่เหมาะสม หรือใช้ disintegrant ที่ไม่เกิดเจล เช่น crospovidone (ทำงานโดย wicking และ strain recovery) ร่วมด้วย",
      w: [
        "ถูก — SSG ความเข้มข้นสูงเกิด gel blocking ทำให้ disintegration ช้าลง จึงต้องลดระดับหรือเปลี่ยน/ผสม disintegrant ที่ไม่เกิดเจล",
        "การเพิ่มแรงตอกลด porosity และยิ่งทำให้แตกตัวช้าลง ไม่ใช่การแก้ไข",
        "SSG ไม่ทำปฏิกิริยาเคมีกับ magnesium stearate ในลักษณะนี้",
        "SSG ไม่ได้ทำให้ pH ภายในเม็ดยาเป็นกรดจนรบกวนการแตกตัว",
        "การเพิ่ม binder เพื่อลด porosity จะทำให้การแทรกซึมของน้ำแย่ลงอีก",
      ],
      k: "Superdisintegrant มากไม่ได้แปลว่าดีกว่า: SSG > ~8% อาจเกิด gel blocking ทำให้แตกตัวช้าลง",
      d: "hard",
      ref: "Handbook of Pharmaceutical Excipients 9th ed. — Sodium Starch Glycolate",
    },
    {
      t: "Capping from overdried granules and fines",
      p: "ยาเม็ดแบบ wet granulation เกิด capping สูงหลังเปลี่ยนตัวตั้งค่าการอบแห้ง ผลตรวจพบ granule มี LOD 0.3% (เป้าหมาย 1.5–2.5%) และมี fines ผ่านแร่ง 100 mesh 38% (ปกติ ~15%) โดยแรงตอกและ tooling ไม่เปลี่ยน การแก้ไขที่ตรงสาเหตุที่สุดคือข้อใด",
      o: [
        "ปรับการอบแห้งให้ LOD กลับมาอยู่ในช่วงเป้าหมายและลดปริมาณ fines ของ granule",
        "เพิ่ม magnesium stearate เป็น 2% เพื่อลดแรงเสียดทานขณะดันเม็ดยาออก",
        "เพิ่มแรงตอกหลัก (main compression force) ให้สูงขึ้นอีก 30%",
        "เปลี่ยน disintegrant เป็น superdisintegrant ที่ประสิทธิภาพสูงกว่า",
        "เพิ่มความเร็วของ turret เพื่อลดเวลาที่ granule สัมผัสความชื้นในอากาศ",
      ],
      a: 0,
      r: "Capping คือการที่ส่วนบน (หรือล่าง) ของเม็ดยาแยกออกเป็นฝา มักเกิดจากพลังงานยืดหยุ่น (elastic recovery) ที่ปลดปล่อยหลังแรงตอกถูกยกออก มากกว่าความแข็งแรงของพันธะระหว่างอนุภาค\n\nปัจจัยที่ทำให้เกิด capping ได้แก่ granule แห้งเกินไป (ความชื้นเล็กน้อยช่วยให้เกิด plastic deformation และพันธะ) และ fines มากเกินไป (อากาศถูกกักในเม็ดยาและการจัดเรียงอนุภาคไม่ดี) ในกรณีนี้ทั้งสองตัวแปรผิดไปจากปกติพร้อมกันหลังเปลี่ยนการอบแห้ง จึงควรแก้ที่ต้นเหตุ\n\nแนวทางอื่น เช่น ใช้ precompression หรือลดความเร็วเครื่อง ช่วยได้เป็นมาตรการเสริม แต่ไม่ใช่การแก้ที่ต้นเหตุเมื่อทราบว่าคุณภาพ granule เปลี่ยน",
      w: [
        "ถูก — ความชื้นต่ำเกินและ fines มากเป็นสาเหตุคลาสสิกของ capping และเป็นตัวแปรที่เปลี่ยนไปจริงในกรณีนี้",
        "Lubricant มากขึ้นยิ่งลดพันธะระหว่างอนุภาค อาจทำให้ capping แย่ลง",
        "แรงตอกที่สูงขึ้นเพิ่ม elastic recovery และมักทำให้ capping รุนแรงขึ้น",
        "Disintegrant เกี่ยวกับการแตกตัว ไม่ได้แก้ปัญหาความแข็งแรงเชิงโครงสร้างของเม็ดยา",
        "ความเร็ว turret ที่สูงขึ้นลด dwell time และเพิ่มอากาศที่ถูกกัก ทำให้ capping แย่ลง",
      ],
      k: "Capping: นึกถึง granule แห้งเกิน, fines มาก, อากาศถูกกัก, แรงตอกสูง/เร็วเกิน และ tooling สึก",
      d: "medium",
      ref: "Lachman/Lieberman's The Theory and Practice of Industrial Pharmacy 4th ed., Ch. Tablets",
    },
    {
      t: "Friability test calculation",
      p: "ทดสอบ friability ของยาเม็ดน้ำหนัก 325 mg ตาม USP <1216> โดยใช้เม็ดยา 20 เม็ด น้ำหนักเริ่มต้น (หลังปัดฝุ่น) 6.500 g หมุน 100 รอบ แล้วปัดฝุ่นชั่งได้ 6.458 g และไม่มีเม็ดใดแตกหัก ข้อใดสรุปผลได้ถูกต้อง",
      o: [
        "น้ำหนักหาย 0.65% ผ่านเกณฑ์ทั่วไป (ไม่เกิน 1.0%)",
        "น้ำหนักหาย 0.042% ผ่านเกณฑ์อย่างมาก",
        "น้ำหนักหาย 0.65% ไม่ผ่าน เพราะเกณฑ์ต้องไม่เกิน 0.5%",
        "น้ำหนักหาย 6.5% ไม่ผ่านเกณฑ์",
        "สรุปไม่ได้ เพราะต้องใช้เม็ดยา 10 เม็ดเสมอ",
      ],
      a: 0,
      r: "USP <1216> กำหนดให้ใช้เม็ดยาที่มีน้ำหนักรวมใกล้เคียง 6.5 g สำหรับเม็ดยาน้ำหนักไม่เกิน 650 mg (ถ้าเกิน 650 mg ใช้ 10 เม็ด) ปัดฝุ่นก่อนชั่ง หมุน 100 รอบ (25 rpm × 4 นาที) แล้วปัดฝุ่นและชั่งใหม่\n\n% friability = (น้ำหนักก่อน − น้ำหนักหลัง)/น้ำหนักก่อน × 100 = (6.500 − 6.458)/6.500 × 100 = 0.65% เกณฑ์ทั่วไปคือ weight loss เฉลี่ยไม่เกิน 1.0% และต้องไม่มีเม็ดที่แตก ร้าว หรือบิ่นชัดเจน จึงสรุปว่าผ่าน\n\nถ้าผลไม่ชัดเจนหรือเกิน 1.0% ให้ทำซ้ำอีก 2 ครั้งและใช้ค่าเฉลี่ยของ 3 ครั้ง",
      w: [
        "ถูก — (6.500 − 6.458)/6.500 × 100 = 0.65% ต่ำกว่าเกณฑ์ทั่วไป 1.0% และไม่มีเม็ดแตก",
        "0.042 คือน้ำหนักที่หายไปเป็นกรัม ไม่ใช่ร้อยละ ต้องหารด้วยน้ำหนักเริ่มต้น",
        "เกณฑ์ทั่วไปของ USP คือไม่เกิน 1.0% ไม่ใช่ 0.5%",
        "คำนวณผิดตำแหน่งทศนิยม 10 เท่า",
        "ใช้ 10 เม็ดเฉพาะเมื่อเม็ดยาหนักเกิน 650 mg เม็ด 325 mg ใช้จำนวนเม็ดที่รวมได้ ~6.5 g",
      ],
      k: "Friability: ~6.5 g (หรือ 10 เม็ดถ้า >650 mg), 100 รอบ, weight loss ≤ 1.0% และไม่มีเม็ดแตก",
      d: "easy",
      ref: "USP <1216> Tablet Friability",
      c: [
        "น้ำหนักที่หายไป = 6.500 − 6.458 = 0.042 g",
        "% friability = 0.042 / 6.500 × 100 = 0.65%",
        "0.65% ≤ 1.0% และไม่มีเม็ดแตก → ผ่าน",
      ],
    },
    {
      t: "Film coating suspension quantity",
      p: "ต้องการเคลือบฟิล์ม core tablets 100 kg ให้มี weight gain 3.0% w/w (คิดจากน้ำหนัก core) ใช้ coating suspension ที่มีของแข็ง 15% w/w และจากข้อมูลเดิม coating efficiency ของ pan นี้เท่ากับ 90% ต้องเตรียม coating suspension อย่างน้อยประมาณเท่าใด",
      o: ["3.3 kg", "18.0 kg", "20.0 kg", "22.2 kg", "24.7 kg"],
      a: 3,
      r: "ปริมาณของแข็งที่ต้องไปอยู่บนเม็ดยา = 3.0% × 100 kg = 3.0 kg แต่ด้วย coating efficiency 90% (ส่วนที่เหลือสูญเสียไปกับ spray drying, ผนัง pan และระบบดูดอากาศ) จึงต้องพ่นของแข็งทั้งหมด = 3.0/0.90 = 3.33 kg\n\nเนื่องจาก suspension มีของแข็ง 15% w/w ปริมาณ suspension = 3.33/0.15 = 22.2 kg ในทางปฏิบัติมักเตรียมเผื่อเพิ่มเล็กน้อยสำหรับ dead volume ของสายและปั๊ม",
      w: [
        "3.3 kg คือปริมาณของแข็งที่ต้องพ่น ยังไม่ได้แปลงเป็นน้ำหนัก suspension",
        "คูณด้วย efficiency แทนที่จะหาร ทำให้ได้ปริมาณน้อยกว่าที่ต้องใช้",
        "ไม่ได้ชดเชย coating efficiency 90% ซึ่งจะทำให้ weight gain จริงได้เพียง ~2.7%",
        "ถูก — ของแข็ง 3.0/0.90 = 3.33 kg แล้วหารด้วย 0.15 = 22.2 kg",
        "ชดเชย efficiency ซ้ำสองครั้ง (หาร 0.9 สองรอบ) ทำให้เกินความจำเป็น",
      ],
      k: "Suspension ที่ต้องใช้ = (core × %WG) ÷ efficiency ÷ %solids",
      d: "hard",
      ref: "Porter SC. Coating of Pharmaceutical Dosage Forms, in Remington 22nd ed.",
      c: [
        "ของแข็งที่ต้องอยู่บนเม็ด = 100 kg × 0.03 = 3.0 kg",
        "ของแข็งที่ต้องพ่น = 3.0 / 0.90 = 3.33 kg",
        "Suspension = 3.33 / 0.15 = 22.2 kg",
      ],
    },
    {
      t: "Hard capsule size selection by fill volume",
      p: "ต้องการบรรจุผงยา 450 mg ต่อแคปซูล ผงยามี tapped density 0.72 g/mL (ถือว่าความหนาแน่นในแคปซูลใกล้เคียงค่านี้) โดยใช้ความจุโดยประมาณของ hard gelatin capsule ดังนี้ size 00 = 0.95 mL, 0 = 0.68 mL, 1 = 0.50 mL, 2 = 0.37 mL ควรเลือกขนาดใดเหมาะสมที่สุด",
      o: [
        "Size 0 เพราะปริมาตรผงที่ต้องบรรจุ ~0.63 mL",
        "Size 1 เพราะปริมาตรผงที่ต้องบรรจุ ~0.45 mL",
        "Size 2 เพราะปริมาตรผงที่ต้องบรรจุ ~0.32 mL",
        "Size 00 เพราะปริมาตรผงที่ต้องบรรจุ ~0.90 mL",
        "Size 1 เพราะ 450 mg น้อยกว่าน้ำหนักบรรจุสูงสุด 500 mg",
      ],
      a: 0,
      r: "การเลือกขนาดแคปซูลขึ้นกับ ปริมาตร ของผงที่ต้องบรรจุ ไม่ใช่น้ำหนัก ปริมาตร = มวล/ความหนาแน่น = 0.450 g ÷ 0.72 g/mL = 0.625 mL\n\nSize 1 (0.50 mL) เล็กเกินไป ส่วน size 0 (0.68 mL) รองรับได้โดยมีที่ว่างเหลือเล็กน้อย จึงเหมาะที่สุด ในทางปฏิบัติความหนาแน่นในแคปซูลขึ้นกับแรง tamp/compress ของเครื่อง จึงต้องยืนยันด้วยการบรรจุจริง และถ้าผงฟูมากอาจต้องเพิ่มความหนาแน่น (เช่น granulation) เพื่อใช้แคปซูลเล็กลงซึ่งกลืนง่ายกว่า",
      w: [
        "ถูก — 0.450/0.72 = 0.625 mL ซึ่งพอดีกับ size 0 (0.68 mL)",
        "ใช้ทั้งน้ำหนักเป็นปริมาตรตรง ๆ (คิดเหมือน density 1 g/mL) ทำให้เลือกแคปซูลเล็กเกินไป",
        "คูณมวลด้วยความหนาแน่นแทนการหาร ทำให้ปริมาตรต่ำเกินจริง",
        "Size 00 บรรจุได้แต่ใหญ่เกินความจำเป็น กลืนยากกว่าและแคปซูลไม่เต็ม",
        "แคปซูลไม่มี น้ำหนักบรรจุสูงสุด คงที่ ความจุขึ้นกับปริมาตรและความหนาแน่นของผง",
      ],
      k: "เลือกขนาดแคปซูลจากปริมาตร = น้ำหนักบรรจุ ÷ ความหนาแน่น (size 0 ≈ 0.68 mL, size 1 ≈ 0.50 mL)",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Hard capsules",
      c: [
        "ปริมาตรผง = 0.450 g ÷ 0.72 g/mL = 0.625 mL",
        "Size 1 = 0.50 mL < 0.625 mL (ไม่พอ)",
        "Size 0 = 0.68 mL ≥ 0.625 mL → เลือก size 0",
      ],
    },
    {
      t: "Effervescent tablet humidity control",
      p: "ห้องผลิตยาเม็ดฟู่ (citric acid + sodium bicarbonate) ในฤดูฝนมีความชื้นสัมพัทธ์ 55% RH พบว่าเม็ดยาบวม ผิวเป็นจุด และ blister บางแผงพองออก มาตรการใดสำคัญที่สุดในการป้องกันปัญหานี้",
      o: [
        "ควบคุมสภาวะห้องผลิตและบรรจุให้มีความชื้นต่ำมาก (ประมาณ ≤ 25% RH) ตลอดกระบวนการ",
        "เพิ่มแรงตอกเพื่อลด porosity ของเม็ดยาให้น้ำซึมเข้าได้ยาก",
        "เพิ่ม sodium bicarbonate ให้มากเกินพอเพื่อชดเชยส่วนที่ทำปฏิกิริยาไป",
        "ใช้ magnesium stearate 2% เพื่อเคลือบผิวอนุภาคให้กันน้ำ",
        "อบเม็ดยาที่ตอกแล้วที่ 80 °C เพื่อไล่ความชื้นก่อนบรรจุ",
      ],
      a: 0,
      r: "ปฏิกิริยาระหว่างกรดอินทรีย์และ bicarbonate ต้องอาศัยน้ำเป็นตัวกลาง เมื่อมีความชื้นเพียงเล็กน้อยจะเริ่มเกิดปฏิกิริยาซึ่งปลดปล่อยทั้ง CO2 และ น้ำ ออกมา น้ำที่เกิดขึ้นจะเร่งปฏิกิริยาต่อเนื่อง (autocatalytic) ทำให้เม็ดบวม เสียรูป และแผงพอง\n\nดังนั้นการผลิตและบรรจุยาเม็ดฟู่ต้องทำในห้องที่ควบคุมความชื้นต่ำมาก (โดยทั่วไปประมาณ 25% RH หรือต่ำกว่า) ร่วมกับใช้วัตถุดิบที่แห้ง และบรรจุในภาชนะกันชื้นพร้อมสารดูดความชื้น\n\nการใช้ water-soluble lubricant (เช่น sodium benzoate, PEG, L-leucine) แทน magnesium stearate ก็เป็นสิ่งที่ต้องทำเพื่อให้ละลายใสในน้ำ",
      w: [
        "ถูก — ความชื้นเป็นตัวเริ่มปฏิกิริยาลูกโซ่ของระบบฟู่ การควบคุม RH ต่ำเป็นมาตรการหลัก",
        "การเพิ่มแรงตอกไม่ป้องกันการดูดความชื้นจากอากาศ และทำให้เม็ดฟู่ละลายช้าลง",
        "Bicarbonate เกินไม่หยุดปฏิกิริยา และน้ำที่เกิดขึ้นยังเร่งการเสื่อมต่อไป",
        "Magnesium stearate ไม่ละลายน้ำ ทำให้เกิดฝ้าลอยในสารละลาย ไม่เหมาะกับยาเม็ดฟู่และไม่ได้กันชื้น",
        "Sodium bicarbonate สลายตัวด้วยความร้อนให้ CO2 และน้ำ การอบที่อุณหภูมิสูงจึงทำลายเม็ดยา",
      ],
      k: "ยาเม็ดฟู่: ผลิตและบรรจุที่ RH ต่ำมาก (~≤25%) เพราะน้ำที่เกิดจากปฏิกิริยาเร่งปฏิกิริยาต่อเนื่อง",
      d: "medium",
      ref: "Lachman/Lieberman's The Theory and Practice of Industrial Pharmacy 4th ed., Ch. Tablets (effervescent)",
    },
    {
      t: "Orange peel film coating defect",
      p: "หลังเปลี่ยนสูตร coating ให้มีของแข็งสูงขึ้นจาก 12% เป็น 20% เพื่อลดเวลาเคลือบ พบว่าผิวเม็ดยาขรุขระคล้ายเปลือกส้ม ไม่เรียบเงา สาเหตุและการแก้ไขที่เหมาะสมที่สุดคือข้อใด",
      o: [
        "Orange peel จากความหนืดสูงทำให้ละอองหยาบและไม่แผ่เรียบ แก้โดยลดของแข็ง/ความหนืดหรือเพิ่ม atomizing air pressure",
        "Picking จากเม็ดยาเปียกเกินไป แก้โดยเพิ่ม spray rate ให้เม็ดยาเคลือบเร็วขึ้น",
        "Logo bridging จากพลาสติไซเซอร์มากเกินไป แก้โดยลดพลาสติไซเซอร์ลงครึ่งหนึ่ง",
        "Cracking จาก internal stress สูง แก้โดยเปลี่ยนเป็น polymer ที่มี Tg สูงขึ้น",
        "Mottling จากสีกระจายไม่สม่ำเสมอ แก้โดยเพิ่มปริมาณ pigment",
      ],
      a: 0,
      r: "Orange peel (roughness) เกิดเมื่อหยดของเหลวที่พ่นออกมามีขนาดใหญ่หรือหนืดเกินไป จนไม่สามารถแผ่ (spread) และรวมตัวเป็นฟิล์มเรียบได้ก่อนแห้ง ปัจจัยที่เกี่ยวข้องได้แก่ ความหนืดของ coating fluid สูง atomizing air pressure ต่ำ และการระเหยเร็วเกินไป\n\nการเพิ่มของแข็งจาก 12% เป็น 20% ทำให้ความหนืดเพิ่มขึ้นมาก ละอองจึงหยาบ การแก้ไขคือลดของแข็ง/ใช้ polymer grade ความหนืดต่ำ เพิ่มแรงดัน atomizing air หรือปรับสมดุลระหว่าง spray rate กับ drying condition",
      w: [
        "ถูก — ความหนืดสูงทำให้การ atomization และการแผ่ของละอองไม่ดี เกิดผิว orange peel",
        "Picking เกิดจากผิวเปียกเหนียวติดกัน และการเพิ่ม spray rate จะทำให้แย่ลง",
        "Logo bridging เกิดจากฟิล์มดึงตัวข้ามร่องตัวอักษร มักแก้โดยเพิ่ม (ไม่ใช่ลด) พลาสติไซเซอร์",
        "อาการที่พบเป็นผิวขรุขระ ไม่ใช่รอยแตก และ Tg สูงขึ้นยิ่งเพิ่มความเปราะ",
        "Mottling คือสีไม่สม่ำเสมอ ไม่ใช่ผิวขรุขระ และการเพิ่ม pigment ยิ่งเพิ่มความหนืด",
      ],
      k: "Orange peel = ละอองหยาบ/หนืดเกิน → ลด viscosity/solids หรือเพิ่ม atomizing air",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Coating of tablets and multiparticulates",
    },
    {
      t: "Lubricant sensitivity plastic vs brittle filler",
      p: "สูตรเดิมใช้ dibasic calcium phosphate (DCP) เป็น filler ผสม magnesium stearate 1% นาน 15 นาที ได้ความแข็งดี เมื่อเปลี่ยน filler เป็น microcrystalline cellulose (MCC) โดยคงสภาวะผสม lubricant เดิม ความแข็งของเม็ดยาลดลงมากที่แรงตอกเท่าเดิม คำอธิบายที่ดีที่สุดคือข้อใด",
      o: [
        "MCC เปลี่ยนรูปแบบ plastic deformation ไม่เกิดผิวใหม่ระหว่างตอก ฟิล์ม Mg stearate ที่เคลือบผิวจึงลดพันธะได้มาก ต่างจาก DCP ที่แตกเป็นชิ้น (fragmentation) สร้างผิวสะอาดใหม่",
        "MCC มีความชื้นสูงจึงทำปฏิกิริยากับ magnesium stearate กลายเป็นสบู่ที่ไม่มีแรงยึดเกาะ",
        "DCP เป็นสาร plastic ส่วน MCC เป็นสาร brittle จึงต้องใช้แรงตอกสูงกว่ามาก",
        "MCC มี bulk density สูงกว่า DCP ทำให้น้ำหนักในเบ้าเพิ่มและความแข็งลดลง",
        "Magnesium stearate ละลายใน MCC ทำให้ MCC เปลี่ยนเป็น amorphous",
      ],
      a: 0,
      r: "Lubricant sensitivity ขึ้นกับกลไกการเปลี่ยนรูปของ filler ภายใต้แรงตอก Magnesium stearate เป็นสาร hydrophobic ที่เมื่อผสมนานจะแผ่เป็นฟิล์มบางเคลือบผิวอนุภาค ขัดขวางการเกิดพันธะระหว่างอนุภาค\n\nวัสดุที่เปลี่ยนรูปแบบ plastic (MCC, starch) ไม่ค่อยแตกเป็นชิ้นใหม่ ผิวที่สัมผัสกันในเม็ดยาจึงเป็นผิวที่ถูกเคลือบ lubricant แล้ว ความแข็งจึงลดลงมาก (lubricant sensitive) ส่วนวัสดุ brittle (DCP, lactose บางชนิด) แตกเป็นชิ้นเล็กระหว่างตอก เกิดผิวสะอาดใหม่ที่สร้างพันธะได้ จึงไวต่อ lubricant น้อย\n\nเมื่อเปลี่ยนเป็น MCC จึงควรลดเวลาผสม lubricant (เช่น 2–5 นาที) หรือลดความเข้มข้นของ magnesium stearate",
      w: [
        "ถูก — วัสดุ plastic ไวต่อ lubricant เพราะไม่สร้างผิวใหม่ ส่วน brittle filler สร้างผิวสะอาดจาก fragmentation",
        "ไม่มีปฏิกิริยาเกิดสบู่ระหว่าง MCC กับ magnesium stearate ในสภาวะการผสมปกติ",
        "สลับกัน — DCP เป็น brittle และ MCC เป็น plastic",
        "MCC มี bulk density ต่ำกว่า DCP และน้ำหนักในเบ้าไม่ใช่สาเหตุของความแข็งลดลงที่แรงตอกเดียวกัน",
        "Magnesium stearate ไม่ละลายใน MCC และไม่ทำให้ MCC เปลี่ยนเป็น amorphous",
      ],
      k: "Plastic filler (MCC, starch) = lubricant sensitive; brittle filler (DCP) = lubricant insensitive",
      d: "hard",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Tablets and compaction",
    },
  ],
  // Mock Set 2 — ชุดที่ 2
  [
    {
      t: "Jet mill for heat-sensitive micronization",
      p: "API ชนิดหนึ่งมีจุดหลอมเหลวต่ำ (~70 °C) และไวต่อความร้อน ต้องการลดขนาดอนุภาคให้ได้ d90 < 10 µm เพื่อใช้ในสูตรยาเม็ดขนาดยาต่ำ เครื่องบดชนิดใดเหมาะสมที่สุด",
      o: [
        "Fluid energy mill (jet mill) เพราะได้อนุภาคละเอียดระดับไมครอนและการขยายตัวของแก๊สช่วยระบายความร้อน",
        "Hammer mill ความเร็วสูง เพราะแรงกระแทกสูงให้อนุภาคละเอียดที่สุด",
        "Cutting mill เพราะเหมาะกับการลดขนาดผงผลึกให้ต่ำกว่า 10 µm",
        "Oscillating granulator เพราะใช้แรงเฉือนต่ำและไม่เกิดความร้อน",
        "Conical screen mill (cone mill) ที่ใช้ screen ขนาด 0.5 mm",
      ],
      a: 0,
      r: "Fluid energy mill หรือ jet mill ใช้ลมหรือแก๊สความดันสูงพาอนุภาคให้ชนกันเองด้วยความเร็วสูง (particle–particle impact) ร่วมกับ classifier ที่คัดเฉพาะอนุภาคละเอียดออก จึงได้ขนาดระดับ 1–10 µm\n\nการขยายตัวของแก๊สที่ออกจาก nozzle ทำให้เกิดการเย็นตัว (Joule–Thomson effect) ช่วยชดเชยความร้อนจากการชน จึงเหมาะกับสารที่จุดหลอมเหลวต่ำหรือไวต่อความร้อน และไม่มีชิ้นส่วนเคลื่อนไหวที่สัมผัสผลิตภัณฑ์จึงลดการปนเปื้อนจากโลหะ\n\nเครื่องบดแบบอื่นในตัวเลือกให้ขนาดหยาบกว่ามาก (ระดับหลายสิบถึงหลายร้อยไมครอน) และ hammer mill ก่อความร้อนสูง",
      w: [
        "ถูก — jet mill ให้ขนาดระดับไมครอนและการขยายตัวของแก๊สช่วยลดความร้อน เหมาะกับสารไวต่อความร้อน",
        "Hammer mill ให้อนุภาคละเอียดได้จำกัด (มักใหญ่กว่า 10–20 µm) และเกิดความร้อนสะสมซึ่งอาจทำให้ API หลอมหรือเกาะติด",
        "Cutting mill เหมาะกับวัสดุเหนียวหรือเป็นเส้นใย ให้อนุภาคหยาบ ไม่ได้ระดับไมครอน",
        "Oscillating granulator ใช้ทำ sizing ของ granule ผ่านตะแกรง ไม่สามารถทำให้เป็นระดับไมครอนได้",
        "Cone mill ใช้ลดขนาด granule หรือก้อนผงให้ได้ขนาดสม่ำเสมอ ไม่ใช่ micronization",
      ],
      k: "ต้องการ micronization ของสารไวต่อความร้อน → jet (fluid energy) mill",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Particle-size reduction and size separation",
    },
    {
      t: "Fluid-bed granulation overwetting",
      p: "ระหว่าง top-spray fluid-bed granulation พบว่าการ fluidize ของ bed ลดลงเรื่อย ๆ มีก้อนใหญ่เกาะกันและ bed เริ่มยุบตัว (defluidization) โดย product temperature ลดลงต่ำกว่าปกติ สาเหตุที่น่าจะเป็นมากที่สุดคือข้อใด",
      o: [
        "อัตราการพ่น binder สูงเกินเมื่อเทียบกับความสามารถในการระเหยของลมร้อน ทำให้ bed เปียกเกินไป",
        "Inlet air temperature สูงเกินไปจน binder แห้งก่อนถึงผิวอนุภาค",
        "Atomizing air pressure สูงเกินไปจนละอองเล็กมาก",
        "Air flow สูงเกินไปจนอนุภาคละเอียดถูกพาไปติด filter bag",
        "ความเข้มข้นของ binder solution ต่ำเกินไปจน granule ไม่เกิด",
      ],
      a: 0,
      r: "Fluid-bed granulation อาศัยสมดุลระหว่าง การเติมของเหลว (spray rate, droplet size) กับ การระเหย (inlet air temperature, air flow, humidity) ถ้า spray rate สูงเกินกว่าที่ลมร้อนระเหยได้ ความชื้นใน bed จะสะสม granule โตเร็วและเกาะกันเป็นก้อน น้ำหนักและความเหนียวทำให้ลมไม่สามารถยก bed ได้ เกิด defluidization หรือ bed collapse\n\nสัญญาณที่ช่วยวินิจฉัยคือ product/exhaust temperature ลดลง (พลังงานถูกใช้ไปกับการระเหยน้ำจำนวนมาก) ซึ่งตรงกับโจทย์ การแก้ไขคือลด spray rate เพิ่ม inlet temperature/air volume หรือใช้ละอองที่เล็กลง",
      w: [
        "ถูก — spray rate สูงเกินการระเหย ทำให้ overwetting, product temperature ต่ำ และ bed collapse",
        "Inlet temperature สูงเกินจะทำให้เกิด spray drying ของ binder ได้ fines มาก ไม่ใช่ก้อนเปียก",
        "Atomizing pressure สูงให้ละอองเล็ก แห้งเร็ว มักได้ granule เล็กและ fines มากขึ้น",
        "Air flow สูงทำให้ fines ไปติด filter และ bed ฟุ้งมากขึ้น ไม่ใช่ bed ยุบตัว",
        "Binder เจือจางเกินไปทำให้ granule อ่อนและเล็ก ไม่ได้ทำให้ bed เปียกจนยุบตัว",
      ],
      k: "Fluid-bed: spray rate > drying capacity → overwet, product temp ต่ำ, defluidization",
      d: "medium",
      ref: "Parikh, Handbook of Pharmaceutical Granulation Technology 3rd ed., Ch. Fluid-bed granulation",
    },
    {
      t: "Roller compaction loss of compactability",
      p: "สูตรยาเม็ดที่มี MCC สูงผลิตด้วย roller compaction เมื่อเพิ่ม roll pressure เพื่อให้ ribbon แน่นขึ้นและลด fines พบว่า granule ไหลดีขึ้น แต่เม็ดยาที่ตอกด้วยแรงเท่าเดิมมี tensile strength ลดลงมาก ปรากฏการณ์นี้คืออะไร และแนวทางแก้ไขใดเหมาะสมที่สุด",
      o: [
        "Loss of compactability (work hardening) จากการอัดซ้ำสองครั้ง — ลด roll pressure ให้เหมาะสมและ/หรือเติม MCC ส่วน extragranular",
        "Overlubrication จาก magnesium stearate — เพิ่มเวลาผสม lubricant ให้กระจายสม่ำเสมอ",
        "Capping จากอากาศที่ถูกกัก — เพิ่มความเร็ว turret ให้ dwell time สั้นลง",
        "Polymorphic transformation ของ MCC — เปลี่ยนเป็น wet granulation ทุกกรณี",
        "Segregation ของ granule — เพิ่มขนาด screen ของ mill ให้ granule ใหญ่ขึ้น",
      ],
      a: 0,
      r: "ใน dry granulation ผงถูกอัดสองครั้ง คือครั้งแรกเป็น ribbon และครั้งที่สองเป็นเม็ดยา วัสดุที่เปลี่ยนรูปแบบ plastic เช่น MCC จะใช้ความสามารถในการเปลี่ยนรูปไปบางส่วนในการอัดครั้งแรก (work hardening) และขนาด granule ที่โตขึ้นลดพื้นที่ผิวสำหรับสร้างพันธะ ทำให้ compactability ลดลงเมื่อตอกเป็นเม็ด\n\nยิ่ง roll pressure สูง (ribbon solid fraction สูง) granule ยิ่งแน่น ไหลดีและ fines น้อยลง แต่ความแข็งของเม็ดยาลดลง จึงต้องหาจุดสมดุล ribbon solid fraction ที่เหมาะสม (มักอยู่ราว 0.6–0.8) และอาจเพิ่ม filler/binder ที่ compactable สูงส่วน extragranular เพื่อชดเชย",
      w: [
        "ถูก — การอัดซ้ำทำให้วัสดุ plastic สูญเสีย compactability ต้องปรับ roll pressure และเพิ่ม extragranular excipient",
        "Overlubrication ทำให้ความแข็งลดได้ แต่การเพิ่มเวลาผสมจะยิ่งแย่ลง และไม่อธิบายความสัมพันธ์กับ roll pressure",
        "การเพิ่มความเร็ว turret ลด dwell time ทำให้ capping และความแข็งแย่ลง",
        "MCC ไม่เกิด polymorphic transformation จากการ roller compaction และไม่จำเป็นต้องเปลี่ยนกระบวนการทั้งหมด",
        "Granule ที่ใหญ่ขึ้นยิ่งลดพื้นที่ผิวสำหรับสร้างพันธะ และไม่ได้แก้ปัญหา compactability",
      ],
      k: "Roller compaction: roll pressure ↑ → flow ดีขึ้นแต่ tabletability ↓ (work hardening) ต้องหาจุดสมดุล",
      d: "hard",
      ref: "Parikh, Handbook of Pharmaceutical Granulation Technology 3rd ed., Ch. Roller compaction",
    },
    {
      t: "Direct compression filler grade",
      p: "ผู้พัฒนาต้องการเตรียมยาเม็ดด้วย direct compression ซึ่งไม่มีขั้นตอน granulation filler ข้อใด ไม่เหมาะสม สำหรับกระบวนการนี้",
      o: [
        "Lactose monohydrate ชนิดบดละเอียด (milled, ~200 mesh)",
        "Spray-dried lactose",
        "Microcrystalline cellulose (เช่น grade PH 102)",
        "Anhydrous dibasic calcium phosphate (granular grade)",
        "Partially pregelatinized starch",
      ],
      a: 0,
      r: "Direct compression ต้องใช้ excipient ที่ไหลดี (flowability) และอัดเป็นเม็ดได้ดี (compressibility/compactability) ในตัวเอง เพราะไม่มีขั้นตอน granulation มาช่วยปรับปรุงคุณสมบัติ\n\nExcipient ชนิด DC grade ผ่านการปรับรูปแบบอนุภาค เช่น spray drying, agglomeration หรือ pregelatinization ทำให้อนุภาคกลม ใหญ่ และมีโครงสร้างที่อัดได้ดี ในขณะที่ lactose monohydrate ชนิดบดละเอียดเป็นผงละเอียด cohesive ไหลไม่ดีและอัดเป็นเม็ดได้ไม่ดี เหมาะกับ wet granulation มากกว่า",
      w: [
        "ถูก — lactose monohydrate บดละเอียดไหลไม่ดีและ compactability ต่ำ จึงไม่เหมาะกับ direct compression",
        "Spray-dried lactose มีอนุภาคกลม มีส่วน amorphous ช่วยให้ไหลดีและอัดได้ดี เป็น DC grade",
        "MCC PH 102 อัดได้ดีมาก (plastic deformation) และมีขนาดอนุภาคใหญ่พอที่จะไหลได้",
        "Anhydrous DCP granular grade ไหลดี แตกเป็นชิ้นเมื่อตอก (brittle) เหมาะกับ DC",
        "Partially pregelatinized starch ใช้ใน DC ได้ ทำหน้าที่ทั้ง filler/binder และ disintegrant",
      ],
      k: "DC excipient ต้องไหลดี + อัดได้ดี: MCC, spray-dried lactose, DCP anhydrous, pregelatinized starch",
      d: "easy",
      ref: "Handbook of Pharmaceutical Excipients 9th ed.; Aulton's Pharmaceutics 6th ed.",
    },
    {
      t: "Picking at embossed punch faces",
      p: "ระหว่างตอกยาเม็ดที่มีตราสัญลักษณ์นูน (embossed) ตัวอักษร A, B, O พบว่ามีผงติดค้างอยู่ตรงกลางตัวอักษรบนหน้าสาก และเม็ดยามีตัวอักษรไม่คม ตรวจพบ LOD ของ granule สูงกว่าปกติ ข้อใดสรุปปัญหาและแนวทางแก้ไขได้ดีที่สุด",
      o: [
        "Picking — ลดความชื้นของ granule ให้อยู่ในเกณฑ์ ร่วมกับพิจารณาเพิ่ม glidant/anti-adherent หรือปรับแบบตัวอักษรให้มุมกว้างขึ้น",
        "Capping — เพิ่ม precompression เพื่อไล่อากาศออกจากเม็ดยา",
        "Lamination — เปลี่ยน tooling เป็นแบบ flat-faced ทุกกรณี",
        "Mottling — ใช้ dye ที่เป็น lake แทน soluble dye",
        "Chipping — ลดแรงตอกให้ต่ำลงเพื่อลดแรงกระแทกบริเวณขอบ",
      ],
      a: 0,
      r: "Picking คือการที่ผงจากผิวเม็ดยาหลุดติดหน้าสาก โดยเฉพาะบริเวณตัวอักษรหรือโลโก้ที่มีพื้นที่ปิด (เช่น ใจกลางตัว A, B, O) ส่วน sticking คือการติดของผงกับหน้าสากหรือผนังเบ้าโดยรวม ทั้งสองเกิดเมื่อแรงยึดเกาะระหว่างผงกับโลหะมากกว่าแรงยึดภายในเม็ดยา\n\nสาเหตุสำคัญคือ granule ชื้นเกินไป สารที่จุดหลอมเหลวต่ำ lubricant/anti-adherent ไม่เพียงพอ และการออกแบบตัวอักษรที่คม/ลึก การแก้ไขจึงเริ่มจากควบคุม LOD ให้ถูกต้อง เพิ่ม colloidal silica/talc ปรับแบบตัวอักษร หรือใช้หน้าสากเคลือบโครเมียม",
      w: [
        "ถูก — ผงติดใจกลางตัวอักษรคือ picking และ LOD สูงเป็นสาเหตุที่พบได้ชัด",
        "Capping คือการแยกส่วนฝาของเม็ดยา ไม่ใช่ผงติดหน้าสาก",
        "Lamination คือการแยกเป็นชั้นตามแนวขวาง ไม่ใช่การติดตรงตัวอักษร และการเลิกใช้ embossing ไม่ใช่ทางเลือกแรก",
        "Mottling คือสีไม่สม่ำเสมอบนเม็ดยา ไม่เกี่ยวกับผงติดหน้าสาก",
        "Chipping คือขอบเม็ดยาบิ่น และการลดแรงตอกอาจทำให้เม็ดยาอ่อนจน picking มากขึ้น",
      ],
      k: "Picking = ผงติดหน้าสากบริเวณตัวอักษร; แก้ด้วยลดความชื้น, anti-adherent, ปรับ embossing, chrome-plated punch",
      d: "medium",
      ref: "Lachman/Lieberman's The Theory and Practice of Industrial Pharmacy 4th ed., Ch. Tablets",
    },
    {
      t: "Diametral tensile strength calculation",
      p: "ยาเม็ดแบนกลม (flat-faced) เส้นผ่านศูนย์กลาง 10.0 mm หนา 4.0 mm ทดสอบ breaking force (diametral compression) ได้ 120 N จงคำนวณ tensile strength ของเม็ดยา",
      o: ["0.76 MPa", "0.95 MPa", "1.91 MPa", "3.00 MPa", "3.82 MPa"],
      a: 2,
      r: "ค่า breaking force (hardness) ขึ้นกับขนาดและความหนาของเม็ดยา จึงเปรียบเทียบข้ามขนาดไม่ได้ การแปลงเป็น tensile strength ช่วย normalize ผลต่อมิติ สำหรับเม็ดแบนกลมใช้สมการของ Fell & Newton: σ = 2F/(πDt)\n\nσ = 2 × 120 N/(π × 10.0 mm × 4.0 mm) = 240/125.7 = 1.91 N/mm² = 1.91 MPa (1 N/mm² = 1 MPa) ค่า tensile strength ประมาณ 1.7–2 MPa ขึ้นไปมักถือว่าเม็ดยาแข็งแรงพอสำหรับการเคลือบ บรรจุ และขนส่ง สมการนี้ใช้กับเม็ดแบนกลมเท่านั้น เม็ดนูนต้องใช้สมการที่ปรับตามรูปทรง",
      w: [
        "ใช้ D² แทน D × t ในตัวส่วน ซึ่งไม่ถูกต้องสำหรับการแตกตามแนวเส้นผ่านศูนย์กลาง",
        "ลืมคูณ 2 ในตัวเศษ (ใช้ F/πDt)",
        "ถูก — σ = 2 × 120/(π × 10 × 4) = 1.91 MPa",
        "หาร F ด้วย D × t โดยไม่มี π และไม่คูณ 2",
        "ใช้ 4F แทน 2F ซึ่งเป็นการสับสนกับสมการพื้นที่หน้าตัดวงกลม",
      ],
      k: "Tensile strength (flat round) = 2F/(πDt); N/mm² = MPa; ใช้เปรียบเทียบความแข็งข้ามขนาดเม็ด",
      d: "medium",
      ref: "USP <1217> Tablet Breaking Force; Fell JT, Newton JM. J Pharm Sci 1970",
      c: [
        "σ = 2F/(πDt)",
        "πDt = 3.1416 × 10.0 × 4.0 = 125.7 mm²",
        "σ = 240 / 125.7 = 1.91 N/mm² = 1.91 MPa",
      ],
    },
    {
      t: "Sugar coating step sequence",
      p: "ลำดับขั้นตอนของการเคลือบน้ำตาล (sugar coating) แบบดั้งเดิมข้อใดถูกต้อง",
      o: [
        "Sealing → Subcoating → Smoothing (syrup coating) → Colour coating → Polishing",
        "Subcoating → Sealing → Colour coating → Smoothing → Polishing",
        "Sealing → Colour coating → Subcoating → Polishing → Smoothing",
        "Polishing → Sealing → Subcoating → Smoothing → Colour coating",
        "Smoothing → Subcoating → Sealing → Colour coating → Polishing",
      ],
      a: 0,
      r: "Sugar coating เริ่มด้วย sealing (เคลือบด้วย polymer กันน้ำ เช่น shellac หรือ CAP เพื่อป้องกันความชื้นจาก syrup เข้าสู่ core) ตามด้วย subcoating (เพิ่มขนาดและปรับขอบให้มนด้วย syrup ร่วมกับผงเช่น talc, CaCO3 ซึ่งเป็นช่วงที่เพิ่มน้ำหนักมาก) แล้ว smoothing (ใช้ syrup ให้ผิวเรียบ) จากนั้น colour coating (syrup ที่มีสีหลายชั้นบาง ๆ) และจบด้วย polishing (wax เช่น carnauba/beeswax) อาจมี printing ต่อท้าย\n\nกระบวนการนี้ใช้เวลานาน น้ำหนักเม็ดเพิ่มได้ 50–100% และต้องใช้ทักษะสูง จึงถูกแทนที่ด้วย film coating ในผลิตภัณฑ์ส่วนใหญ่",
      w: [
        "ถูก — sealing ต้องมาก่อนเพื่อกันน้ำ ตามด้วย subcoating, smoothing, colour และ polishing",
        "Sealing ต้องมาก่อน subcoating เพื่อกันน้ำจาก syrup เข้าสู่ core",
        "Colour coating ต้องทำบนผิวที่เรียบแล้วหลัง subcoating/smoothing และ polishing ต้องอยู่ท้ายสุด",
        "Polishing เป็นขั้นสุดท้าย ไม่ใช่ขั้นแรก",
        "Sealing ต้องอยู่ก่อนขั้นตอนที่ใช้ syrup ทุกขั้น",
      ],
      k: "Sugar coating: Seal → Subcoat → Smooth → Colour → Polish (→ Print)",
      d: "easy",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Coating of tablets and multiparticulates",
    },
    {
      t: "Soft gelatin capsule fill compatibility",
      p: "ทีมพัฒนาต้องการบรรจุยาในรูป soft gelatin capsule สูตร fill ใดต่อไปนี้มีความเสี่ยงต่อความเข้ากันได้กับเปลือกแคปซูล น้อยที่สุด",
      o: [
        "ยาละลายใน medium-chain triglyceride (MCT oil) มีน้ำในสูตร < 1%",
        "ยาละลายในน้ำ 30% ร่วมกับ PEG 400",
        "ยาละลายใน ethanol 40% เป็นตัวทำละลายหลัก",
        "สารละลายยาที่ปรับ pH เป็น 1.5 เพื่อเพิ่มการละลาย",
        "ยาในตัวทำละลายที่มี aldehyde impurity สูง",
      ],
      a: 0,
      r: "เปลือก soft gelatin ประกอบด้วย gelatin, plasticizer (glycerin/sorbitol) และน้ำ จึงต้องเลือก fill ที่ไม่ทำลายเปลือก ข้อกำหนดทั่วไปได้แก่ fill ควรเป็นของเหลวไม่มีน้ำหรือมีน้อย (โดยทั่วไปไม่เกินราว 5%) pH ราว 2.5–7.5 หลีกเลี่ยงตัวทำละลายระเหยง่ายความเข้มข้นสูง (เช่น ethanol) และหลีกเลี่ยงสารที่มี aldehyde ซึ่งทำให้ gelatin เกิด crosslinking\n\nน้ำมันพืชหรือ MCT เป็นพาหะที่เข้ากันได้ดีที่สุด ส่วน PEG 400 ใช้ได้แต่ต้องควบคุมน้ำ เพราะน้ำปริมาณมากละลาย/ทำให้เปลือกอ่อนตัวและรั่ว",
      w: [
        "ถูก — MCT oil ที่มีน้ำน้อยมากเข้ากันได้ดีกับเปลือก gelatin",
        "น้ำ 30% เกินขีดจำกัดมาก จะทำให้เปลือกนิ่ม ละลาย และรั่ว",
        "Ethanol ความเข้มข้นสูงระเหยผ่านเปลือกและทำให้ยาตกผลึก/เปลือกเสียรูป",
        "pH ที่ต่ำมากทำให้ gelatin ถูก hydrolyze เปลือกอ่อนแอและรั่ว",
        "Aldehyde ทำให้ gelatin เกิด crosslinking เปลือกละลายช้าลง",
      ],
      k: "Softgel fill: น้ำน้อย (~≤5%), pH ~2.5–7.5, เลี่ยง ethanol สูงและ aldehyde; น้ำมันเหมาะที่สุด",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Soft capsules",
    },
    {
      t: "Fluid-bed drying rate periods and endpoint",
      p: "ระหว่างอบ wet granule ใน fluid-bed dryer ที่ตั้ง inlet air 60 °C พบว่าช่วงแรก product temperature คงที่ราว 25–28 °C นานประมาณ 20 นาที จากนั้นจึงเริ่มสูงขึ้นต่อเนื่องพร้อมกับ outlet air temperature ข้อใดอธิบายปรากฏการณ์นี้ได้ถูกต้องที่สุด",
      o: [
        "ช่วงแรกเป็น constant-rate period ผิว granule ยังเปียก อุณหภูมิผลิตภัณฑ์จึงใกล้ wet-bulb temperature ของอากาศ เมื่อเข้าสู่ falling-rate period อุณหภูมิจึงสูงขึ้นและใช้เป็นสัญญาณใกล้ endpoint",
        "ช่วงแรก heater ยังให้ความร้อนไม่เต็มที่ อุณหภูมิผลิตภัณฑ์จึงต่ำ ควรอุ่นเครื่องให้นานขึ้นก่อน load เพื่อตัดช่วงนี้ออก",
        "อุณหภูมิที่สูงขึ้นในช่วงหลังแสดงว่าน้ำระเหยเร็วขึ้น เป็นช่วงที่อัตราการอบแห้งสูงที่สุดของกระบวนการ",
        "ช่วงที่อุณหภูมิคงที่คือ falling-rate period ที่น้ำภายในรูพรุนแพร่ออกช้า ส่วนช่วงที่อุณหภูมิสูงขึ้นคือ constant-rate period",
        "Product temperature ควรเท่ากับ inlet air ตลอดการอบ ส่วนต่างที่เห็นบ่งชี้ว่า airflow ไม่พอและเกิด channeling ใน bed",
      ],
      a: 0,
      r: "การอบแห้งด้วยลมร้อน (convective drying) แบ่งเป็น constant-rate period และ falling-rate period ในช่วงแรกผิว granule มีชั้นน้ำอิสระต่อเนื่อง การระเหยถูกจำกัดด้วยการถ่ายเทความร้อน/มวลที่ผิว พลังงานความร้อนเกือบทั้งหมดถูกใช้เป็น latent heat ของการระเหย อุณหภูมิผลิตภัณฑ์จึงคงที่ใกล้ wet-bulb temperature ของอากาศเข้า และอัตราการอบคงที่สูงสุด\n\nเมื่อความชื้นลดถึง critical moisture content ผิวเริ่มแห้ง น้ำต้องเคลื่อนที่จากภายในรูพรุนออกมา (capillary/diffusion) อัตราการอบจึงลดลง (falling-rate period) ความร้อนส่วนเกินทำให้อุณหภูมิผลิตภัณฑ์และ outlet air สูงขึ้น ในทางปฏิบัติจึงใช้ product/outlet temperature เป็นสัญญาณ endpoint ร่วมกับ LOD หรือ NIR\n\nPearl: ช่วง falling-rate คือช่วงที่ยาไวต่อความร้อนเสี่ยงต่อการสลายตัว เพราะอุณหภูมิผลิตภัณฑ์เริ่มเข้าใกล้ inlet",
      w: [
        "ถูก — product temperature ≈ wet-bulb ในช่วง constant-rate และสูงขึ้นเมื่อเข้าสู่ falling-rate ซึ่งบ่งบอกว่าใกล้ endpoint",
        "อุณหภูมิต่ำในช่วงแรกเกิดจากการใช้ความร้อนเป็น latent heat ของการระเหย ไม่ใช่ heater ทำงานไม่เต็มที่",
        "อุณหภูมิที่สูงขึ้นเกิดเพราะอัตราการระเหยลดลง ความร้อนจึงเหลือไปเพิ่มอุณหภูมิ ไม่ใช่อัตราการอบสูงสุด",
        "สลับลำดับ ช่วงอุณหภูมิคงที่คือ constant-rate ส่วน falling-rate มาทีหลังเมื่อผิวเริ่มแห้ง",
        "Product temperature ต่ำกว่า inlet เป็นเรื่องปกติจาก evaporative cooling ไม่ได้บ่งชี้ channeling",
      ],
      k: "Constant-rate: product temp ≈ wet-bulb; falling-rate: อุณหภูมิผลิตภัณฑ์/outlet สูงขึ้น → ใช้เป็นสัญญาณ endpoint",
      d: "hard",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Drying",
    },
    {
      t: "Bilayer tablet layer separation and first-layer force",
      p: "การผลิต bilayer tablet (IR layer + SR layer) บนเครื่องตอกแบบ bilayer พบว่าเม็ดยาแยกชั้นตรงรอยต่อ (layer separation) ระหว่างทดสอบ friability และในขั้นเคลือบฟิล์ม ตรวจ batch record พบว่าตั้งแรงตอกชั้นแรก (first-layer tamping force) ไว้สูงใกล้เคียงแรงตอกหลัก ข้อใดเป็นแนวทางแก้ไขที่เหมาะสมที่สุด",
      o: [
        "ลด first-layer tamping force ให้ต่ำพอเพียงจัดระเบียบผงชั้นแรก เพื่อให้ผิวชั้นแรกยังพรุน/หยาบและเกิด interlocking กับชั้นที่สองระหว่าง main compression",
        "เพิ่ม first-layer tamping force ให้สูงขึ้นอีก เพื่อให้ชั้นแรกแข็งแรงเต็มที่ก่อนเติมผงชั้นที่สอง",
        "เพิ่ม magnesium stearate ในชั้นที่สอง เพื่อให้ผงไหลเติม die ได้สม่ำเสมอและลดแรงเสียดทานที่รอยต่อ",
        "เพิ่มความเร็ว turret เพื่อลดเวลาที่ผิวชั้นแรกสัมผัสอากาศก่อนเติมชั้นที่สอง",
        "สลับให้ชั้น SR ที่มี HPMC สูงเป็นชั้นที่สองเสมอ เพราะลำดับชั้นเป็นปัจจัยเดียวที่กำหนดการยึดเกาะ",
      ],
      a: 0,
      r: "ความแข็งแรงของรอยต่อระหว่างชั้นใน bilayer tablet ขึ้นกับการที่อนุภาคของสองชั้นได้สัมผัสและเกิดพันธะ/interlocking กันในขั้น main compression ถ้า first-layer force สูงเกินไป ชั้นแรกจะถูกอัดจนผิวเรียบ หนาแน่น และ 'ใช้' ความสามารถในการเกิดพันธะไปแล้ว เมื่อตอกชั้นที่สองจึงยึดเกาะที่รอยต่อได้น้อย และเมื่อคลายแรงแต่ละชั้นคืนตัว (elastic recovery) ไม่เท่ากัน รอยต่อจึงแยก\n\nแนวทางมาตรฐานคือใช้ first-layer (tamping) force ต่ำ เพียงพอให้ผิวชั้นแรกเรียบระดับและไม่ปนกับชั้นที่สอง ปัจจัยอื่นที่เกี่ยวข้อง ได้แก่ ความต่างของ elastic recovery ระหว่างสองชั้น อัตราส่วนน้ำหนักชั้น ปริมาณ lubricant ที่ผิวรอยต่อ และ cross-contamination ระหว่างชั้น\n\nPearl: lubricant ที่ผิวรอยต่อยิ่งมากยิ่งลดการยึดเกาะ — การเพิ่ม Mg stearate จึงทำให้ปัญหาแย่ลง",
      w: [
        "ถูก — first-layer force ต่ำคงความพรุน/หยาบของผิวชั้นแรก ทำให้สองชั้นยึดเกาะกันได้ดีใน main compression",
        "First-layer force สูงทำให้ผิวชั้นแรกแน่นเรียบและ bonding ที่รอยต่อลดลง เป็นต้นเหตุของปัญหา ไม่ใช่วิธีแก้",
        "Mg stearate เป็น hydrophobic film ที่ลดการเกิดพันธะระหว่างอนุภาค การเพิ่มยิ่งทำให้รอยต่ออ่อนแอ",
        "เวลาสัมผัสอากาศไม่ใช่กลไกหลัก และความเร็วที่สูงขึ้นลด dwell time ทำให้การยึดเกาะลดลงอีก",
        "ลำดับชั้นมีผลบ้าง แต่ไม่ใช่ปัจจัยเดียว และไม่แก้สาเหตุที่ชี้ชัดคือ first-layer force สูงเกิน",
      ],
      k: "Bilayer tablet แยกชั้น → ลด first-layer tamping force, คุมความต่าง elastic recovery และ lubricant ที่รอยต่อ",
      d: "hard",
      ref: "Abebe A. et al., Int J Pharm 2014;461:549–558 (Review of bilayer tablet technology); Lachman/Lieberman's The Theory and Practice of Industrial Pharmacy 4th ed.",
    },
  ],
  // Mock Set 3 — ชุดที่ 3
  [
    {
      t: "Rationale for granulation",
      p: "สูตรยาเม็ดที่มี API ขนาดยาสูง (70% ของน้ำหนักเม็ด) เป็นผงละเอียด cohesive ไหลไม่ดี และฟุ้งกระจายมาก เหตุผลหลักในการเลือกทำ granulation ก่อนตอกเม็ดคือข้อใด",
      o: [
        "ปรับปรุงการไหลและการอัดตัว ลดฝุ่น และป้องกันการแยกชั้นของส่วนประกอบในสูตร",
        "เพิ่มความคงตัวทางเคมีของ API ทุกชนิดเพราะน้ำช่วยปกป้องยา",
        "ลดความจำเป็นในการใช้ lubricant ในสูตรทั้งหมด",
        "ทำให้ยาออกฤทธิ์นานขึ้นเหมือนยาออกฤทธิ์ควบคุม",
        "ลดขนาดอนุภาคของ API ให้ละเอียดลงเพื่อเพิ่มการละลาย",
      ],
      a: 0,
      r: "Granulation คือการรวมอนุภาคผงขนาดเล็กเข้าเป็นก้อนที่ใหญ่ขึ้น (granule) ด้วย binder หรือแรงอัด วัตถุประสงค์หลักได้แก่ (1) ป้องกัน segregation เพราะส่วนประกอบถูกยึดอยู่ใน granule เดียวกัน (2) ปรับปรุงการไหล ทำให้เติมเบ้าได้สม่ำเสมอ น้ำหนักเม็ดไม่แปรปรวน (3) ปรับปรุงการอัดตัว (compressibility/compactability) (4) ลดฝุ่นและการสัมผัสสารพิษ\n\nสูตรที่มี API ขนาดยาสูง ไหลไม่ดี และอัดตัวไม่ดี จึงมักต้องทำ granulation เพราะ direct compression ไม่สามารถเติม excipient ได้มากพอที่จะชดเชยคุณสมบัติที่ไม่ดีของ API",
      w: [
        "ถูก — granulation ปรับปรุง flow, compactability ลดฝุ่น และป้องกัน segregation",
        "Wet granulation ใช้น้ำและความร้อน อาจลดความคงตัวของยาที่ไวต่อความชื้น ไม่ได้เพิ่มความคงตัวเสมอ",
        "สูตร granule ยังต้องการ lubricant เพื่อลดแรงเสียดทานกับผนังเบ้า",
        "Granulation แบบทั่วไปไม่ได้มีจุดประสงค์เพื่อควบคุมการปลดปล่อยยา",
        "Granulation ทำให้อนุภาคใหญ่ขึ้น ไม่ได้ลดขนาดอนุภาคของ API",
      ],
      k: "เหตุผลหลักของ granulation: flow ↑, compactability ↑, ฝุ่น ↓, segregation ↓",
      d: "easy",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Granulation",
    },
    {
      t: "Colloidal silica glidant function",
      p: "Colloidal silicon dioxide (เช่น Aerosil 200) ถูกเติมในสูตรผงสำหรับตอกเม็ดในระดับประมาณ 0.1–0.5% w/w หน้าที่หลักและกลไกของสารนี้คือข้อใด",
      o: [
        "Glidant — อนุภาคละเอียดมากเกาะบนผิวอนุภาคอื่น ลดแรงยึดเหนี่ยวระหว่างอนุภาคทำให้ผงไหลดีขึ้น",
        "Lubricant — สร้างฟิล์มระหว่างเม็ดยากับผนังเบ้าเพื่อลดแรงดันเม็ดออก",
        "Binder — สร้างพันธะระหว่างอนุภาคทำให้เม็ดยาแข็งขึ้น",
        "Disintegrant — พองตัวในน้ำทำให้เม็ดยาแตก",
        "Filler — เพิ่มน้ำหนักให้เม็ดยาที่มีขนาดยาต่ำ",
      ],
      a: 0,
      r: "Glidant ทำหน้าที่ปรับปรุงการไหลของผงโดยลดแรงเสียดทานและแรงยึดเหนี่ยวระหว่างอนุภาค Colloidal silicon dioxide มีอนุภาคระดับนาโนและพื้นที่ผิวสูง เมื่อผสมจะเกาะบนผิวอนุภาคอื่น ทำให้ผิวขรุขระระดับเล็ก ลดพื้นที่สัมผัสและแรง van der Waals ระหว่างอนุภาคหลัก จึงไหลดีขึ้น และยังช่วยดูดความชื้นที่ผิว\n\nใช้ในความเข้มข้นต่ำ (ราว 0.1–0.5% และไม่เกินราว 1%) การใช้มากเกินไม่ช่วยเพิ่มการไหลต่อและอาจทำให้แย่ลงได้ ต่างจาก lubricant (เช่น magnesium stearate) ที่ทำหน้าที่ลดแรงเสียดทานระหว่างเม็ดยากับผนังเบ้า",
      w: [
        "ถูก — colloidal silica เป็น glidant ที่ลดแรงยึดเหนี่ยวระหว่างอนุภาคด้วยการเกาะบนผิว",
        "หน้าที่ลดแรงเสียดทานกับผนังเบ้าเป็นของ lubricant เช่น magnesium stearate",
        "Colloidal silica ไม่ใช่ binder และที่ระดับ 0.1–0.5% ไม่ได้เพิ่มความแข็งอย่างมีนัยสำคัญ",
        "Colloidal silica ไม่พองตัวในน้ำและไม่ได้ทำหน้าที่ disintegrant",
        "ใช้ในปริมาณน้อยมาก ไม่ได้ทำหน้าที่เพิ่มน้ำหนักเม็ดยา",
      ],
      k: "Glidant (colloidal SiO2 ~0.1–0.5%) ช่วยการไหลระหว่างอนุภาค; lubricant ลดแรงเสียดทานเม็ดยา–ผนังเบ้า",
      d: "easy",
      ref: "Handbook of Pharmaceutical Excipients 9th ed. — Colloidal Silicon Dioxide",
    },
    {
      t: "Over-granulation consequences",
      p: "ระหว่าง scale-up ของ high-shear wet granulation ผู้ปฏิบัติงานเติม granulating liquid มากกว่าที่กำหนด 20% และ wet massing นานขึ้น หลังอบและบดได้ granule ที่แข็ง หนาแน่น ข้อใดคือผลที่คาดว่าจะเกิดกับเม็ดยามากที่สุด",
      o: [
        "เม็ดยาที่แรงตอกเท่าเดิมมีความแข็งต่ำลงและ disintegration/dissolution ช้าลง",
        "เม็ดยามีความแข็งสูงขึ้นมากและแตกตัวเร็วขึ้นเพราะ granule แน่น",
        "เม็ดยาไม่เปลี่ยนแปลง เพราะความชื้นส่วนเกินถูกกำจัดออกไปหมดในการอบ",
        "เม็ดยามี weight variation มากขึ้นเพราะ granule ไหลแย่ลง",
        "เม็ดยาเกิด capping เพราะ granule ชื้นเกินไปขณะตอก",
      ],
      a: 0,
      r: "เมื่อใช้ของเหลวมากเกินหรือ massing นานเกิน granule จะถูกบีบอัดแน่น (densification) porosity ต่ำ และแข็ง (over-granulation) granule ลักษณะนี้มีพื้นที่ผิวและความสามารถเปลี่ยนรูปเหลือน้อย เมื่อตอกจึงเกิดพันธะระหว่าง granule ได้น้อย ทำให้ความแข็งของเม็ดยาลดลงที่แรงตอกเท่าเดิม (tabletability ลด)\n\nนอกจากนี้ granule ที่หนาแน่นทำให้น้ำแทรกซึมได้ยาก disintegrant ภายใน granule ทำงานได้ไม่ดี จึงแตกตัวและละลายช้าลง การแก้ไขคือควบคุมปริมาณของเหลวและ endpoint (เช่น power consumption) ไม่ใช่แก้ที่ขั้นตอนอบแห้ง",
      w: [
        "ถูก — over-granulation ลด porosity และ compactability ทำให้เม็ดอ่อนลงและแตกตัว/ละลายช้า",
        "Granule แน่นไม่ได้ทำให้เม็ดยาแข็งขึ้นเสมอ และการแตกตัวจะช้าลงไม่ใช่เร็วขึ้น",
        "การอบแห้งกำจัดน้ำได้ แต่โครงสร้างที่แน่นของ granule ไม่กลับคืน",
        "Granule แน่นและกลมมักไหลได้ดีขึ้น ไม่ใช่แย่ลง",
        "หลังอบแห้งตามมาตรฐาน granule ไม่ได้ชื้นเกิน ปัญหาหลักคือโครงสร้างแน่น ไม่ใช่ความชื้น",
      ],
      k: "Over-granulation → granule แน่น porosity ต่ำ → tabletability ↓ และ DT/dissolution ช้าลง",
      d: "medium",
      ref: "Parikh, Handbook of Pharmaceutical Granulation Technology 3rd ed.",
    },
    {
      t: "HPMC capsule shell advantages",
      p: "ยาเตรียมแคปซูลมีตัวยาที่ไวต่อความชื้นและมี excipient ที่อาจมี aldehyde ปนเล็กน้อย ทีมพัฒนาพิจารณาเปลี่ยนจาก hard gelatin capsule เป็น HPMC capsule ข้อใดเป็นข้อได้เปรียบของ HPMC capsule ที่ตรงกับปัญหานี้มากที่สุด",
      o: [
        "เปลือกมีความชื้นต่ำกว่า gelatin มาก และไม่เกิด crosslinking กับ aldehyde",
        "เปลือกละลายเร็วกว่า gelatin ในทุกสภาวะ pH และอุณหภูมิ",
        "เปลือกกันออกซิเจนได้ดีกว่า gelatin มากจนไม่ต้องใช้บรรจุภัณฑ์กันชื้น",
        "เปลือกมีความชื้นสูงกว่า gelatin จึงช่วยดูดความชื้นออกจากตัวยา",
        "เปลือกทนความร้อนต่ำกว่า gelatin จึงต้องเก็บในตู้เย็น",
      ],
      a: 0,
      r: "Hard gelatin capsule มีความชื้นในเปลือกประมาณ 13–16% ซึ่งสามารถถ่ายเทไปยังตัวยาที่ไวต่อความชื้นได้ และ gelatin มีหมู่ amino (lysine) ที่ทำปฏิกิริยากับ aldehyde เกิด crosslinking (pellicle) ทำให้เปลือกละลายช้า\n\nHPMC capsule มีความชื้นต่ำกว่ามาก (ประมาณ 3–7%) และไม่มีหมู่ amino จึงไม่เกิด crosslinking กับ aldehyde อีกทั้งไม่เปราะเมื่ออยู่ในความชื้นต่ำ และเป็นวัสดุจากพืช (vegetarian) จึงเป็นทางเลือกที่เหมาะในกรณีนี้\n\nข้อควรระวังคือ HPMC บางชนิด (โดยเฉพาะที่ใช้ gelling agent) อาจแตกตัวช้ากว่า gelatin ในบางสภาวะ และ HPMC ไม่ได้กันออกซิเจนดีกว่า gelatin",
      w: [
        "ถูก — ความชื้นในเปลือกต่ำและไม่ crosslink กับ aldehyde ตรงกับทั้งสองปัญหา",
        "HPMC capsule ไม่ได้ละลายเร็วกว่าในทุกสภาวะ บางชนิดแตกตัวช้ากว่า gelatin",
        "HPMC มี oxygen permeability สูงกว่า gelatin และยังต้องใช้บรรจุภัณฑ์ที่เหมาะสม",
        "HPMC มีความชื้นต่ำกว่า gelatin ไม่ใช่สูงกว่า",
        "HPMC capsule ทนอุณหภูมิได้ดี ไม่ต้องเก็บในตู้เย็น",
      ],
      k: "HPMC capsule: ความชื้นต่ำ (~3–7%), ไม่ crosslink กับ aldehyde, ไม่เปราะที่ RH ต่ำ, vegetarian",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Hard capsules",
    },
    {
      t: "Mottling from soluble dye migration",
      p: "ยาเม็ดสีชมพูผลิตโดยเติม water-soluble dye ใน binder solution แล้วอบ granule ใน tray dryer พบว่าเม็ดยามีจุดสีเข้มและอ่อนกระจายไม่สม่ำเสมอ (mottling) การแก้ไขที่เหมาะสมที่สุดคือข้อใด",
      o: [
        "เปลี่ยนเป็น aluminium lake (pigment ไม่ละลายน้ำ) ผสมแบบแห้ง หรือเปลี่ยนไปอบด้วย fluid-bed dryer",
        "เพิ่มความเข้มข้นของ soluble dye ให้สีเข้มจนกลบความไม่สม่ำเสมอ",
        "เพิ่มแรงตอกเพื่อให้ผิวเม็ดยาเรียบและสีสม่ำเสมอขึ้น",
        "เพิ่มเวลาผสม lubricant เพื่อให้สีกระจายทั่วเม็ดยา",
        "เพิ่มอุณหภูมิ tray dryer ให้ granule แห้งเร็วขึ้นแต่ใช้ถาดชั้นหนาขึ้น",
      ],
      a: 0,
      r: "Mottling คือการกระจายของสีบนผิวเม็ดยาไม่สม่ำเสมอ สาเหตุคลาสสิกคือ soluble dye ละลายอยู่ใน granulating liquid แล้วเคลื่อนที่ตามน้ำไปยังผิวของ granule หรือผิวของชั้น granule ระหว่างการอบใน tray dryer (solute migration) ทำให้ granule บางส่วนสีเข้มบางส่วนสีอ่อน เมื่อบดและตอกจึงเห็นเป็นจุด\n\nแนวทางแก้ไขคือใช้ lake/pigment ที่ไม่ละลายน้ำ (ไม่เคลื่อนที่ตามน้ำ) ลดขนาดอนุภาคของสารสีและผสมแห้ง หรือใช้ fluid-bed drying ที่ granule เคลื่อนที่ตลอดจึงไม่เกิด migration ไปผิวด้านบนของชั้นผง นอกจากนี้ mottling อาจเกิดจากยาที่มีสีต่างจาก excipient หรือ binder ที่กระจายไม่ทั่วถึง",
      w: [
        "ถูก — lake ไม่ละลายจึงไม่ migrate และ fluid-bed drying ลดการเคลื่อนที่ของสารละลายไปที่ผิว",
        "สีที่เข้มขึ้นไม่แก้ migration และอาจทำให้ความต่างของสีชัดขึ้น",
        "แรงตอกไม่ได้เปลี่ยนการกระจายของสีภายใน granule",
        "Lubricant ไม่ได้ช่วยกระจายสี และการผสมนานเกินอาจเกิด overlubrication",
        "Tray drying ที่ชั้นหนาและอุณหภูมิสูงยิ่งส่งเสริม solute migration",
      ],
      k: "Mottling จาก soluble dye migration ระหว่าง tray drying → ใช้ lake, ผสมแห้ง, หรือ fluid-bed drying",
      d: "medium",
      ref: "Lachman/Lieberman's The Theory and Practice of Industrial Pharmacy 4th ed., Ch. Tablets",
    },
    {
      t: "Logo bridging in film coating",
      p: "ยาเม็ดเคลือบฟิล์มที่มีตัวอักษรเว้า (debossed logo) พบว่าฟิล์มบริเวณร่องตัวอักษรยกตัวขึ้นเป็นสะพานข้ามร่อง ทำให้มองไม่เห็นตัวอักษร ข้อใดเป็นแนวทางแก้ไขที่เหมาะสมที่สุด",
      o: [
        "เพิ่มปริมาณ plasticizer หรือใช้ polymer ที่ความหนืด/molecular weight ต่ำลงเพื่อลด internal stress และเพิ่ม adhesion",
        "เพิ่มความเข้มข้นของ polymer เพื่อให้ฟิล์มหนาขึ้นและแข็งแรงขึ้น",
        "ลดอุณหภูมิ inlet air ให้ต่ำมากเพื่อให้ฟิล์มแห้งช้าลงจนเปียกแฉะ",
        "เพิ่มความลึกและลดมุมของร่องตัวอักษรให้แคบลง",
        "เปลี่ยนจาก film coating เป็น enteric coating",
      ],
      a: 0,
      r: "Logo bridging เกิดเมื่อแรงตึงภายในฟิล์ม (internal stress) ซึ่งเกิดจากการหดตัวขณะแห้งมีค่ามากกว่าแรงยึดเกาะ (adhesion) ระหว่างฟิล์มกับผิว core ฟิล์มจึงดึงตัวออกจากร่องเว้ากลายเป็นสะพานข้ามร่อง\n\nการแก้ไขจึงมุ่งลด internal stress หรือเพิ่ม adhesion ได้แก่ เพิ่ม plasticizer (ลด Tg และ elastic modulus) ใช้ polymer grade ที่ molecular weight/ความหนืดต่ำลง ปรับ core ให้ adhesion ดีขึ้น และออกแบบตัวอักษรให้มุมผนังกว้าง ร่องไม่ลึกและแคบเกินไป",
      w: [
        "ถูก — plasticizer ลด internal stress และ polymer ความหนืดต่ำช่วย adhesion ลด bridging",
        "ฟิล์มที่หนาขึ้นและเข้มข้นขึ้นมี internal stress สูงขึ้น ทำให้ bridging แย่ลง",
        "การทำให้เม็ดยาเปียกแฉะทำให้เกิด picking/sticking และไม่แก้ internal stress",
        "ร่องลึกและแคบขึ้นยิ่งเพิ่มโอกาสเกิด bridging ควรออกแบบให้มุมกว้างขึ้น",
        "Enteric coating มีวัตถุประสงค์ต่างกัน และไม่ใช่การแก้ข้อบกพร่องของฟิล์ม",
      ],
      k: "Logo bridging = internal stress > adhesion → เพิ่ม plasticizer, polymer MW ต่ำ, ปรับแบบ logo",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Coating of tablets and multiparticulates",
    },
    {
      t: "Effervescent couple stoichiometry",
      p: "สูตรยาเม็ดฟู่ใช้ citric acid anhydrous (MW 192.1) 0.60 g ต่อเม็ด ต้องการ sodium bicarbonate (MW 84.0) ในปริมาณพอดีตามปริมาณสัมพันธ์ (stoichiometric) ตามสมการ C6H8O7 + 3 NaHCO3 → Na3C6H5O7 + 3 H2O + 3 CO2 ต้องใช้ sodium bicarbonate ประมาณกี่กรัมต่อเม็ด",
      o: ["0.26 g", "0.60 g", "0.72 g", "0.79 g", "2.36 g"],
      a: 3,
      r: "Citric acid เป็นกรด triprotic จึงทำปฏิกิริยากับ NaHCO3 ในอัตราส่วนโมล 1 : 3\n\nโมลของ citric acid = 0.60/192.1 = 0.003123 mol → NaHCO3 ที่ต้องใช้ = 3 × 0.003123 = 0.009370 mol → มวล = 0.009370 × 84.0 = 0.787 g ≈ 0.79 g\n\nในทางปฏิบัติมักใช้ bicarbonate เกินเล็กน้อยเพื่อให้รสชาติไม่เปรี้ยวเกินและให้ CO2 เพียงพอ และต้องระวังว่าถ้าใช้ citric acid monohydrate (MW 210.1) จะต้องใช้ค่า MW ที่ต่างกัน",
      w: [
        "ใช้อัตราส่วนโมล 1:1 ลืมว่า citric acid มี 3 หมู่กรด",
        "ใช้อัตราส่วนน้ำหนัก 1:1 โดยไม่ได้คำนวณตามโมล",
        "ใช้ MW ของ citric acid monohydrate (210.1) ทั้งที่โจทย์ระบุ anhydrous",
        "ถูก — 0.60/192.1 × 3 × 84.0 = 0.787 g",
        "นับซ้ำสัมประสิทธิ์ 3 สองครั้ง ทำให้ได้มากเกินไป 3 เท่า",
      ],
      k: "Citric acid : NaHCO3 = 1 : 3 โดยโมล (anhydrous 1 g ต้องการ NaHCO3 ~1.31 g)",
      d: "medium",
      ref: "Lachman/Lieberman's The Theory and Practice of Industrial Pharmacy 4th ed., Ch. Tablets (effervescent)",
      c: [
        "mol citric acid = 0.60 / 192.1 = 0.003123 mol",
        "mol NaHCO3 = 3 × 0.003123 = 0.009370 mol",
        "มวล NaHCO3 = 0.009370 × 84.0 = 0.787 g ≈ 0.79 g",
      ],
    },
    {
      t: "Turret speed dwell time strain-rate sensitivity",
      p: "สูตรยาเม็ดที่มี MCC และ pregelatinized starch สูง ตอกบนเครื่อง R&D ที่ 20 rpm ได้ความแข็งดี แต่เมื่อย้ายไปเครื่องผลิตความเร็วสูงที่ turret 70 rpm (punch และแรงตอกเท่าเดิม) เม็ดยาอ่อนลงและเริ่มเกิด capping แนวทางใดตรงกับกลไกของปัญหามากที่สุด",
      o: [
        "เพิ่ม dwell time เช่น ลดความเร็ว turret ใช้ precompression หรือใช้ punch ที่ head flat กว้างขึ้น เพราะวัสดุ plastic ไวต่ออัตราการอัด (strain-rate sensitive)",
        "เพิ่ม magnesium stearate เพื่อลดแรงเสียดทานที่เพิ่มขึ้นตามความเร็ว",
        "เปลี่ยน MCC เป็น filler ที่ plastic มากขึ้นอีกเพื่อเพิ่มการเปลี่ยนรูป",
        "เพิ่มความชื้นของผงให้สูงกว่า 8% เพื่อเพิ่มพันธะ",
        "ลดขนาด granule ให้ละเอียดลงเพื่อเพิ่มพื้นที่สัมผัส",
      ],
      a: 0,
      r: "Dwell time คือช่วงเวลาที่ head flat ของ punch อยู่ใต้ compression roller ซึ่งเป็นช่วงที่แรงอัดสูงสุดคงอยู่ dwell time แปรผกผันกับความเร็วของ turret\n\nวัสดุที่เปลี่ยนรูปแบบ plastic หรือ viscoelastic (MCC, starch) ต้องการเวลาในการเปลี่ยนรูปและสร้างพันธะ เมื่อความเร็วสูงขึ้น (strain rate สูง) การเปลี่ยนรูปแบบ plastic ไม่สมบูรณ์ ส่วนที่ยืดหยุ่นกลับมากขึ้น ทำให้ความแข็งลดลงและเกิด capping ได้ (strain-rate sensitivity) ส่วนวัสดุ brittle เช่น DCP ไวต่อความเร็วน้อยกว่า\n\nการแก้ไขจึงต้องเพิ่มเวลาสัมผัสแรงอัด ได้แก่ ลดความเร็ว turret ใช้ precompression ใช้ roller ขนาดใหญ่หรือ punch head flat กว้างขึ้น",
      w: [
        "ถูก — วัสดุ plastic ไวต่อความเร็ว การเพิ่ม dwell time ช่วยให้เกิด plastic deformation และพันธะสมบูรณ์",
        "Lubricant ที่มากขึ้นยิ่งลดพันธะของวัสดุ plastic และไม่แก้ปัญหา dwell time",
        "วัสดุที่ plastic มากขึ้นยิ่งไวต่อความเร็ว ควรเพิ่มสัดส่วน brittle filler ถ้าจะแก้ที่สูตร",
        "ความชื้นสูงเกินทำให้เกิด sticking/picking และปัญหาความคงตัว",
        "Fines มากขึ้นเพิ่มอากาศที่ถูกกักและการไหลแย่ลง อาจทำให้ capping มากขึ้น",
      ],
      k: "ตอกเร็วขึ้น = dwell time สั้นลง → วัสดุ plastic (MCC, starch) อ่อนลง/capping; แก้ด้วย precompression หรือลดความเร็ว",
      d: "hard",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Tablets and compaction",
    },
    {
      t: "Hydrate formation during wet granulation",
      p: "API anhydrous form ละลายน้ำได้ปานกลางและมี hydrate form ที่เสถียรกว่าเมื่อสัมผัสน้ำ หลัง aqueous wet granulation พบว่า XRPD ของ granule แสดงพีคของ hydrate และ dissolution ของเม็ดยาช้าลง แนวทางการผลิตใดเหมาะสมที่สุดในการคง anhydrous form",
      o: [
        "เปลี่ยนเป็น dry granulation (roller compaction) หรือ direct compression หรือใช้ granulating liquid ที่ไม่ใช่น้ำ เช่น ethanol",
        "เพิ่มปริมาณน้ำในการ granulate เพื่อให้ API ละลายและตกผลึกกลับสมบูรณ์",
        "อบ granule ที่อุณหภูมิต่ำ 30 °C นานขึ้นเพื่อป้องกันการเปลี่ยนรูปผลึก",
        "เพิ่มแรงตอกเพื่อให้ hydrate กลับเป็น anhydrous ระหว่างการตอก",
        "เพิ่มเวลา wet massing ให้ hydrate กระจายสม่ำเสมอทั่ว granule",
      ],
      a: 0,
      r: "ใน wet granulation ส่วนของ API ที่ละลายในน้ำที่ใช้ granulate จะตกผลึกใหม่ระหว่างอบแห้ง (เกิดเป็น solid bridge) ถ้า hydrate เป็นรูปที่เสถียรในสภาวะที่มีน้ำ API อาจเปลี่ยนเป็น hydrate (solution-mediated transformation) ซึ่งมักละลายช้ากว่า anhydrous ส่งผลต่อ dissolution\n\nการป้องกันที่ตรงจุดคือหลีกเลี่ยงการสัมผัสน้ำ ได้แก่ ใช้ dry granulation หรือ direct compression หรือใช้ non-aqueous granulation (เช่น ethanol ร่วมกับ binder ที่ละลายในแอลกอฮอล์ เช่น PVP) ทั้งนี้ต้องยืนยัน solid form ด้วย XRPD/DSC หลังกระบวนการ",
      w: [
        "ถูก — การหลีกเลี่ยงน้ำตัดกลไก solution-mediated transformation เป็น hydrate",
        "น้ำมากขึ้นทำให้ API ละลายและเปลี่ยนเป็น hydrate มากขึ้น",
        "การอบที่อุณหภูมิต่ำไม่ป้องกันการเกิด hydrate ที่เกิดขึ้นแล้วระหว่าง wet massing และอาจยิ่งคง hydrate ไว้",
        "แรงตอกไม่ได้ทำให้ hydrate กลับเป็น anhydrous อย่างควบคุมได้ และอาจทำให้เกิดการเปลี่ยนรูปอื่น",
        "การ massing นานขึ้นเพิ่มเวลาสัมผัสน้ำ ทำให้ hydrate เกิดมากขึ้น",
      ],
      k: "API ที่เกิด hydrate ได้ → เลี่ยง aqueous granulation: ใช้ DC, roller compaction หรือ non-aqueous granulation",
      d: "hard",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Granulation; ICH Q6A Decision Tree #4 (polymorphism)",
    },
    {
      t: "ODT manufacturing route selection",
      p: "บริษัทต้องการพัฒนา orally disintegrating tablet (ODT) ของยาขนาด 20 mg รสไม่ขม เพื่อจำหน่ายในขวด HDPE แบบหลายเม็ด (multi-dose bottle) ในประเทศเขตร้อน แนวทางใดเหมาะสมที่สุด",
      o: [
        "ตอกเม็ดจาก mannitol-based DC excipient ร่วมกับ superdisintegrant ให้แตกตัวภายใน ~30 วินาที และมีความแข็ง/friability พอสำหรับขวด",
        "ใช้เทคนิค lyophilization (freeze-dried wafer) เพราะแตกตัวเร็วที่สุด และบรรจุในขวดได้ตามปกติ",
        "ตอกเม็ดแบบเดิมด้วยแรงตอกสูงให้ disintegration time ประมาณ 10–15 นาที",
        "ทำเป็นยาเม็ดฟู่ที่ต้องละลายน้ำก่อนรับประทาน",
        "ใช้ lactose monohydrate บดละเอียดร่วมกับ starch paste ด้วย wet granulation โดยไม่มี superdisintegrant",
      ],
      a: 0,
      r: "ODT ต้องแตกตัวในช่องปากอย่างรวดเร็ว (FDA guidance แนะนำ in vitro disintegration ประมาณ 30 วินาทีหรือน้อยกว่า ตามวิธี USP <701>) เทคโนโลยีหลักได้แก่ lyophilization, molding และ direct compression ที่ใช้ sugar alcohol กับ superdisintegrant\n\nODT แบบ freeze-dried แตกตัวในไม่กี่วินาทีแต่เปราะมาก ต้องบรรจุใน blister แบบ peel-off และแกะอย่างระวัง จึงไม่เหมาะกับขวดหลายเม็ด โดยเฉพาะในสภาวะความชื้นสูง ส่วน compressed ODT ใช้ mannitol (ไม่ดูดความชื้น ให้ความรู้สึกเย็นและหวาน) ร่วมกับ crospovidone หรือ superdisintegrant อื่น ได้เม็ดที่ทนการบรรจุขวดและผลิตด้วยเครื่องตอกเดิม จึงเป็นทางเลือกที่เหมาะสม",
      w: [
        "ถูก — compressed ODT ด้วย mannitol + superdisintegrant แตกตัวเร็วและแข็งแรงพอสำหรับขวด",
        "Freeze-dried ODT เปราะมากและดูดความชื้นง่าย ต้องใช้ blister พิเศษ ไม่เหมาะกับขวดหลายเม็ด",
        "DT 10–15 นาทีเป็นของยาเม็ดทั่วไป ไม่ใช่ ODT",
        "ยาเม็ดฟู่ต้องละลายน้ำก่อน ไม่ใช่การแตกตัวในช่องปาก",
        "สูตรนี้ไม่มี superdisintegrant และ starch paste binder จะทำให้แตกตัวช้า ไม่ถึงระดับ ODT",
      ],
      k: "ODT: DT ~≤30 s; freeze-dried เร็วแต่เปราะ (ต้อง peelable blister); compressed ODT (mannitol + superdisintegrant) ทนกว่า",
      d: "hard",
      ref: "US FDA Guidance for Industry: Orally Disintegrating Tablets (2008); USP <701>",
    },
  ],
  // Mock Set 4 — ชุดที่ 4
  [
    {
      t: "Chewable tablet filler choice",
      p: "ผู้พัฒนาต้องการทำยาเม็ดเคี้ยว (chewable tablet) สำหรับเด็ก ต้องการ filler ที่ให้รสหวาน ให้ความรู้สึกเย็นในปาก ไม่ดูดความชื้น และไม่เป็นทราย filler ใดเหมาะสมที่สุด",
      o: [
        "Mannitol",
        "Dibasic calcium phosphate",
        "Microcrystalline cellulose ล้วน",
        "Sorbitol ชนิดดูดความชื้นสูง โดยไม่ควบคุมความชื้น",
        "Corn starch",
      ],
      a: 0,
      r: "ยาเม็ดเคี้ยวต้องมีรสชาติและความรู้สึกในปาก (mouthfeel) ที่ดี เพราะผู้ป่วยเคี้ยวก่อนกลืน Mannitol เป็น sugar alcohol ที่มีรสหวานปานกลาง มี negative heat of solution จึงให้ความรู้สึกเย็นเมื่อละลายในปาก ดูดความชื้นต่ำมาก (non-hygroscopic) และไม่ทำปฏิกิริยา Maillard กับยาที่มีหมู่ amine เหมือน lactose จึงเป็น filler มาตรฐานของ chewable tablet และ ODT\n\nยาเม็ดเคี้ยวมักไม่จำเป็นต้องพึ่ง disintegrant เป็นหลักเพราะถูกบดด้วยการเคี้ยว แต่ต้องมีความแข็งที่พอดี ไม่แข็งจนเคี้ยวยาก",
      w: [
        "ถูก — mannitol หวาน เย็น ไม่ดูดความชื้น เป็น filler มาตรฐานของ chewable tablet",
        "DCP ไม่ละลายน้ำ ให้ความรู้สึกเป็นทรายและไม่มีรสหวาน",
        "MCC ไม่ละลายน้ำ ให้ความรู้สึกเป็นเส้นใย/แห้งในปาก และไม่หวาน",
        "Sorbitol หวานและเย็นได้ แต่ดูดความชื้นสูง ถ้าไม่ควบคุมความชื้นเม็ดยาจะนิ่มและเหนียว",
        "Starch ไม่หวาน ทำให้รู้สึกเป็นแป้งในปาก และอัดตัวได้ไม่ดี",
      ],
      k: "Chewable/ODT filler ยอดนิยม = mannitol (หวาน เย็น ไม่ดูดความชื้น)",
      d: "easy",
      ref: "Handbook of Pharmaceutical Excipients 9th ed. — Mannitol",
    },
    {
      t: "Rotary press compression cycle",
      p: "ลำดับขั้นตอนการทำงานของเครื่องตอกยาเม็ดแบบ rotary press ในหนึ่งรอบการหมุนของ punch แต่ละคู่ข้อใดถูกต้อง",
      o: [
        "Die filling (overfill) → weight adjustment (scrape-off) → precompression → main compression → ejection",
        "Precompression → die filling → main compression → weight adjustment → ejection",
        "Die filling → main compression → precompression → ejection → weight adjustment",
        "Weight adjustment → die filling → ejection → main compression → precompression",
        "Die filling → ejection → weight adjustment → precompression → main compression",
      ],
      a: 0,
      r: "ใน rotary press lower punch จะถูกดึงลงด้วย fill cam ให้ผงจาก feed frame ไหลลงเบ้าเกินปริมาณ (overfill) จากนั้น weight control cam ยก lower punch ขึ้นไปยังตำแหน่งที่กำหนดเพื่อดันผงส่วนเกินออกและปาดทิ้ง (scrape-off) ซึ่งเป็นตัวกำหนดน้ำหนักเม็ด\n\nต่อมา upper และ lower punch ผ่าน precompression roller (อัดเบา ๆ ไล่อากาศ) แล้วผ่าน main compression roller ที่ให้แรงอัดสูงสุด สุดท้าย ejection cam ดัน lower punch ขึ้นจนเม็ดยาโผล่พ้นผิว die table และ take-off blade ปาดเม็ดยาออกไปยัง discharge chute",
      w: [
        "ถูก — fill → ปรับน้ำหนัก → precompression → main compression → ejection",
        "Precompression ต้องเกิดหลังเติมผงลงเบ้าและปรับน้ำหนักแล้ว",
        "Precompression ต้องมาก่อน main compression และการปรับน้ำหนักต้องทำก่อนอัด",
        "การปรับน้ำหนักต้องทำหลังเติมผง และ ejection เป็นขั้นตอนสุดท้าย",
        "Ejection เกิดหลังการอัดเท่านั้น",
      ],
      k: "Rotary press: Fill → Weight adjust → Precompress → Main compress → Eject",
      d: "easy",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Tablets and compaction",
    },
    {
      t: "Ordered mixing for low-dose API",
      p: "ยาเม็ดขนาดยา 0.25 mg ในเม็ดน้ำหนัก 100 mg ใช้ API micronized (d50 ~5 µm) แนวทางการผสมใดช่วยให้ได้ความสม่ำเสมอของปริมาณยาและลดความเสี่ยง segregation ได้ดีที่สุด",
      o: [
        "ทำ ordered (interactive) mixing โดยให้ API ละเอียดเกาะบนผิว carrier ที่ใหญ่กว่า ร่วมกับ geometric dilution",
        "ใส่ API ทั้งหมดลงใน blender พร้อม excipient ทุกตัวในคราวเดียวแล้วผสมนานขึ้นเป็นสองเท่า",
        "เลือก filler ที่ละเอียดใกล้เคียง API และไหลไม่ดีเพื่อป้องกันการเคลื่อนที่",
        "ผสม magnesium stearate กับ API ก่อนเพื่อให้ API ไหลดีขึ้น",
        "ใช้ API ขนาดใหญ่ (~200 µm) เพื่อให้ไหลดีเหมือน filler",
      ],
      a: 0,
      r: "สำหรับยาขนาดต่ำ จำนวนอนุภาค API ต่อเม็ดต้องมากพอและต้องกระจายทั่วถึง Ordered หรือ interactive mixing คือการที่อนุภาค API ละเอียดมากเกาะติดบนผิวอนุภาค carrier ที่ใหญ่กว่าด้วยแรงยึดเหนี่ยว (van der Waals, electrostatic) ทำให้ระบบทำตัวเหมือนอนุภาคเดี่ยว ลด segregation และได้ความสม่ำเสมอดีกว่าการผสมแบบสุ่ม (random mixing)\n\nGeometric dilution (ผสม API กับ excipient ปริมาณเท่ากัน แล้วค่อย ๆ เพิ่มเป็นเท่าตัว) ช่วยให้กระจายดีตั้งแต่ต้น ส่วน API ขนาดใหญ่จะทำให้ content uniformity แย่ลงเพราะจำนวนอนุภาคต่อเม็ดน้อยเกินไป",
      w: [
        "ถูก — interactive mixing บน carrier ร่วมกับ geometric dilution ให้ CU ดีและลด segregation",
        "การผสมทั้งหมดในครั้งเดียวสำหรับยาขนาดต่ำมากเสี่ยงต่อการกระจายไม่ทั่ว และการผสมนานเกินอาจเกิด demixing",
        "ผงละเอียด cohesive ทั้งระบบจะไหลไม่ดี ทำให้มีปัญหาน้ำหนักเม็ดและการผลิต",
        "Magnesium stearate เคลือบ API จะลดการละลายและไม่ใช่วิธีกระจายยา",
        "API ขนาดใหญ่ทำให้จำนวนอนุภาคต่อเม็ดน้อย ความแปรปรวนของ content สูงขึ้นมาก",
      ],
      k: "ยาขนาดต่ำ: ใช้ API ละเอียด + ordered mixing บน carrier + geometric dilution",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Mixing",
    },
    {
      t: "Cyclic weight variation from tooling",
      p: "บนเครื่องตอก 36 สถานี พบว่าน้ำหนักเม็ดยาแปรปรวนเป็นรูปแบบซ้ำทุกรอบการหมุนของ turret โดยเม็ดจากสถานีหมายเลข 7 และ 22 หนักกว่าเป้าหมายประมาณ 4% เสมอ ในขณะที่การไหลของผงและ feed frame ปกติ สาเหตุที่น่าจะเป็นมากที่สุดคือข้อใด",
      o: [
        "Lower punch ของสถานีนั้นมี working length สั้นกว่าชุดอื่น (สึกหรอหรือไม่ได้มาตรฐาน) ทำให้ fill depth ลึกกว่า",
        "ผงเกิด segregation ใน hopper ทำให้ bulk density เปลี่ยนตามเวลา",
        "Magnesium stearate ผสมนานเกินไปจนผงไหลดีเกินไป",
        "ความชื้นในห้องผลิตสูงขึ้นในช่วงบ่าย",
        "Upper punch มีหน้าสากที่สกปรกทำให้ picking",
      ],
      a: 0,
      r: "น้ำหนักเม็ดยาถูกกำหนดโดยปริมาตรของเบ้าเมื่อ lower punch อยู่ที่ตำแหน่ง weight adjustment ถ้า lower punch บางอันมีความยาวใช้งาน (working length) ต่างจากอันอื่น ปริมาตรเบ้าที่สถานีนั้นจะต่างไปทุกครั้งที่หมุนผ่าน ทำให้เกิดรูปแบบน้ำหนักผิดปกติซ้ำเป็นรอบ (cyclic) เฉพาะสถานี\n\nความแปรปรวนที่มาจากวัสดุ (segregation, การไหล, ความชื้น) จะเปลี่ยนแปลงตามเวลาหรือแบบสุ่ม ไม่ผูกกับสถานีใดสถานีหนึ่ง การแก้ไขคือตรวจวัดความยาว punch ด้วย tooling gauge ตามโปรแกรม tooling inspection และเปลี่ยนชุดที่ไม่ได้มาตรฐาน",
      w: [
        "ถูก — ความต่างที่ผูกกับสถานีเฉพาะและซ้ำทุกรอบบ่งชี้ความยาว lower punch ที่ไม่เท่ากัน",
        "Segregation ทำให้คุณสมบัติผงเปลี่ยนตามเวลา ไม่ใช่เฉพาะบางสถานีซ้ำทุกรอบ",
        "การผสม lubricant ไม่ได้ทำให้น้ำหนักเพิ่มเฉพาะบางสถานี",
        "ความชื้นเปลี่ยนตามเวลาและส่งผลกับทุกสถานี ไม่ใช่เฉพาะสถานี 7 และ 22",
        "Picking ทำให้เม็ดยาเสียผิวและอาจเบาลงเล็กน้อย ไม่ได้ทำให้หนักขึ้นอย่างสม่ำเสมอ",
      ],
      k: "Weight variation ซ้ำเฉพาะสถานีทุกรอบ turret → สงสัยความยาว lower punch/tooling ไม่เท่ากัน",
      d: "medium",
      ref: "Lachman/Lieberman's The Theory and Practice of Industrial Pharmacy 4th ed., Ch. Tablets; TSM (Tableting Specification Manual)",
    },
    {
      t: "Intragranular vs extragranular disintegrant",
      p: "ยาเม็ด wet granulation เม็ดแตกออกเป็น granule ได้เร็วภายใน 1 นาที แต่ granule เหล่านั้นไม่แตกต่อเป็นอนุภาคละเอียด ทำให้ยาละลายช้า ปัจจุบันเติม croscarmellose sodium ทั้งหมดในส่วน extragranular การปรับสูตรใดเหมาะสมที่สุด",
      o: [
        "แบ่ง disintegrant ส่วนหนึ่ง (เช่น ครึ่งหนึ่ง) ไปเติมในส่วน intragranular ก่อน granulation",
        "เพิ่ม croscarmellose ในส่วน extragranular เป็นสองเท่า",
        "เพิ่มแรงตอกเพื่อให้ granule แตกละเอียดขึ้นระหว่างการตอก",
        "เพิ่ม binder ใน granule เพื่อให้ granule แข็งแรงขึ้น",
        "เพิ่ม magnesium stearate เพื่อเพิ่มการ wetting ของ granule",
      ],
      a: 0,
      r: "ตำแหน่งของ disintegrant กำหนดว่าเม็ดยาจะแตกถึงระดับใด Disintegrant ส่วน extragranular (อยู่ระหว่าง granule) ทำให้เม็ดยาแตกออกเป็น granule อย่างรวดเร็ว ส่วน disintegrant ส่วน intragranular (อยู่ภายใน granule) ทำให้ granule แตกต่อเป็นอนุภาคละเอียด ซึ่งเพิ่มพื้นที่ผิวสำหรับการละลาย\n\nในกรณีนี้เม็ดแตกเป็น granule ได้ดีแล้วแต่ granule ไม่แตกต่อ จึงควรย้าย disintegrant บางส่วนเข้าไปใน granule สูตรทั่วไปมักแบ่ง intra : extra ประมาณ 50 : 50 Croscarmellose sodium ยังคงทำงานได้ดีแม้ผ่าน wet granulation มาแล้ว",
      w: [
        "ถูก — disintegrant ภายใน granule ช่วยให้ granule แตกเป็นอนุภาคละเอียด เพิ่มการละลาย",
        "การเพิ่มเฉพาะส่วน extragranular ช่วยให้เม็ดแตกเป็น granule เร็วขึ้น ซึ่งไม่ใช่ปัญหาของกรณีนี้",
        "แรงตอกที่สูงขึ้นทำให้ porosity ลดลงและแตกตัวช้าลง",
        "Binder มากขึ้นทำให้ granule แข็งแรงและแตกยากขึ้นอีก",
        "Magnesium stearate เป็น hydrophobic ลด wetting ไม่ใช่เพิ่ม",
      ],
      k: "Extragranular disintegrant → เม็ดแตกเป็น granule; intragranular → granule แตกเป็นอนุภาค; มักแบ่ง 50:50",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Tablets and compaction",
    },
    {
      t: "Film cracking internal stress",
      p: "ยาเม็ดเคลือบฟิล์มด้วย HPMC grade ความหนืดสูงโดยไม่มี plasticizer หลังเก็บ 1 เดือนพบรอยแตกของฟิล์มบริเวณขอบเม็ด (edge cracking) โดยเฉพาะเม็ดที่ core มีการขยายตัวเล็กน้อยเมื่อดูดความชื้น ข้อใดเป็นการแก้ไขที่เหมาะสมที่สุด",
      o: [
        "เติม plasticizer (เช่น PEG หรือ triethyl citrate) และ/หรือใช้ HPMC grade ความหนืดต่ำลง เพื่อเพิ่มความยืดหยุ่นของฟิล์ม",
        "เพิ่มความหนาของฟิล์มด้วย HPMC grade เดิมโดยไม่เติม plasticizer",
        "เพิ่ม pigment (titanium dioxide) ในปริมาณมากเพื่อเสริมความแข็งแรง",
        "เพิ่มอุณหภูมิอบหลังเคลือบเป็น 90 °C เพื่อให้ฟิล์มแข็งขึ้น",
        "เปลี่ยนเป็น sugar coating ทุกกรณี",
      ],
      a: 0,
      r: "Film cracking เกิดเมื่อ internal stress ในฟิล์ม (จากการหดตัวขณะแห้ง, ความต่างของการขยายตัวระหว่างฟิล์มกับ core ทั้งจากความร้อนและความชื้น) มีค่ามากกว่า tensile strength ของฟิล์ม ขอบเม็ดยาเป็นจุดที่ฟิล์มบางและมีความเค้นสะสมสูงที่สุด\n\nฟิล์มจาก polymer molecular weight สูงที่ไม่มี plasticizer มี Tg สูงและ elastic modulus สูง (แข็งแต่เปราะ) การเติม plasticizer ช่วยลด Tg และ modulus ทำให้ฟิล์มยืดหยุ่น รองรับการขยายตัวของ core ได้ ส่วน polymer grade ความหนืดต่ำช่วยลด internal stress นอกจากนี้ควรลดการขยายตัวของ core (เช่น ควบคุมความชื้น)",
      w: [
        "ถูก — plasticizer ลด Tg/modulus และ polymer ความหนืดต่ำลด internal stress ป้องกันการแตก",
        "ฟิล์มที่หนาขึ้นโดยไม่มี plasticizer ยังเปราะและ internal stress เพิ่มขึ้น",
        "Pigment ปริมาณสูงเพิ่ม modulus และลดความยืดหยุ่นของฟิล์ม ทำให้แตกง่ายขึ้น",
        "อุณหภูมิสูงเพิ่มความเค้นจากการหดตัวและการขยายตัวต่างกัน และอาจทำลาย core",
        "การเปลี่ยนเป็น sugar coating เป็นการเปลี่ยนกระบวนการใหญ่โดยไม่จำเป็น เมื่อแก้สูตรฟิล์มได้",
      ],
      k: "Film cracking = internal stress > film strength → เพิ่ม plasticizer, ลด MW polymer, ลด pigment, คุมการขยายตัวของ core",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Coating of tablets and multiparticulates",
    },
    {
      t: "Dosator vs dosing-disc capsule filling",
      p: "ผงยาสำหรับบรรจุแคปซูลไหลดีมาก แต่มีความเกาะตัว (cohesion) ต่ำ เมื่อใช้เครื่องแบบ dosator พบว่า plug หลุดออกจาก nozzle ระหว่างเคลื่อนย้ายไปยัง capsule body ทำให้น้ำหนักบรรจุแปรปรวน แนวทางใดเหมาะสมที่สุด",
      o: [
        "เปลี่ยนเป็นเครื่องแบบ dosing disc (tamping) ซึ่งอาศัยแผ่นรองใต้ disc จึงพึ่งความแข็งแรงของ plug น้อยกว่า และเหมาะกับผงที่ไหลดี",
        "เพิ่ม glidant เป็น 2% เพื่อให้ผงไหลดียิ่งขึ้น",
        "ใช้ dosator ต่อไปแต่ลดแรงอัด (compression) ของ piston ให้ต่ำลง",
        "เปลี่ยนเป็นแคปซูลขนาดเล็กลงเพื่อให้ plug สั้นลง",
        "เพิ่มความเร็วของเครื่องเพื่อให้ plug อยู่ใน nozzle เวลาสั้นลง",
      ],
      a: 0,
      r: "เครื่องบรรจุแคปซูลอัตโนมัติแบบ plug-forming มีสองหลักการ Dosator ใช้ท่อ nozzle จุ่มลงในชั้นผง piston อัดผงเป็น plug แล้วยกขึ้นไปปล่อยลงในตัวแคปซูล plug ต้องมีความแข็งแรงพอที่จะไม่หลุดจาก nozzle ระหว่างเคลื่อนที่ จึงต้องการผงที่มีความเกาะตัวในระดับหนึ่ง\n\nDosing disc (tamping) ใช้แผ่น disc ที่มีรู ผงไหลลงรูและถูก tamping pin อัดซ้ำหลายสถานี โดยมีแผ่นรอง (brass/tamping plate) ด้านล่าง จากนั้นจึงดันออกลงตัวแคปซูล จึงพึ่งความแข็งแรงของ plug น้อยกว่า แต่ต้องการผงที่ไหลดีเพื่อเติมรูได้สม่ำเสมอ ซึ่งตรงกับลักษณะผงในกรณีนี้",
      w: [
        "ถูก — dosing disc เหมาะกับผงไหลดีและพึ่งความแข็งแรงของ plug น้อยกว่า dosator",
        "Glidant เพิ่มการไหลแต่ลดความเกาะตัว ทำให้ plug ยิ่งหลุดง่าย และ 2% สูงเกินความจำเป็น",
        "แรงอัดที่ต่ำลงทำให้ plug อ่อนลงและหลุดง่ายขึ้น",
        "การเปลี่ยนขนาดแคปซูลไม่แก้ปัญหาความแข็งแรงของ plug และอาจบรรจุไม่พอ",
        "ความเร็วสูงเพิ่มแรงเหวี่ยงและแรงกระชาก ทำให้ plug หลุดง่ายขึ้น",
      ],
      k: "Dosator ต้องการ plug ที่เกาะตัวพอ; dosing disc (tamping) ต้องการผงที่ไหลดี",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Hard capsules",
    },
    {
      t: "Heckel yield pressure interpretation",
      p: "จาก Heckel plot ของสาร 2 ชนิดภายใต้สภาวะเดียวกัน สาร X มี mean yield pressure (Py) ประมาณ 60 MPa และสาร Y มี Py ประมาณ 500 MPa ข้อใดแปลผลได้ถูกต้องที่สุด",
      o: [
        "สาร X เปลี่ยนรูปแบบ plastic ได้ง่าย (ความชันของ Heckel plot สูง) ส่วนสาร Y แข็งและมักลดปริมาตรด้วยการแตกเป็นชิ้น (fragmentation)",
        "สาร X แข็งกว่าสาร Y เพราะ Py ต่ำหมายถึงต้องใช้แรงมากกว่าในการเปลี่ยนรูป",
        "สาร Y มีความชันของ Heckel plot สูงกว่าสาร X จึงอัดตัวได้ง่ายกว่า",
        "ค่า Py บอกความแข็งของเม็ดยาสุดท้ายโดยตรง สาร Y จึงให้เม็ดที่แข็งกว่าเสมอ",
        "ทั้งสองสารมีพฤติกรรมเหมือนกันเพราะ Heckel plot ใช้ได้กับสาร plastic เท่านั้น",
      ],
      a: 0,
      r: "Heckel equation: ln[1/(1 − D)] = KP + A โดย D คือ relative density ของผงอัดที่ความดัน P ความชัน K ของช่วงเส้นตรงมีความสัมพันธ์ผกผันกับ mean yield pressure (Py = 1/K)\n\nPy ต่ำ (ความชันสูง) หมายถึงสารเปลี่ยนรูปแบบ plastic ได้ง่ายที่ความดันต่ำ เช่น MCC, PEG, starch ส่วน Py สูง (ความชันต่ำ) หมายถึงสารแข็ง ลดปริมาตรส่วนใหญ่ด้วยการแตกเป็นชิ้น เช่น dibasic calcium phosphate, lactose บางชนิด\n\nPy อธิบายกลไกการอัดตัว ไม่ได้บอกความแข็งของเม็ดยาโดยตรง เพราะความแข็งขึ้นกับพื้นที่สัมผัสและความแข็งแรงของพันธะด้วย",
      w: [
        "ถูก — Py ต่ำ = plastic deformation ง่าย; Py สูง = วัสดุแข็ง/brittle ที่อาศัย fragmentation",
        "กลับกัน Py ต่ำหมายถึงเปลี่ยนรูปได้ที่ความดันต่ำ คือ อ่อนกว่า",
        "Py สูงสอดคล้องกับความชันต่ำ (K = 1/Py)",
        "Py ไม่ได้บอกความแข็งของเม็ดยาโดยตรง และวัสดุ brittle ไม่ได้ให้เม็ดแข็งกว่าเสมอ",
        "Heckel analysis ใช้เปรียบเทียบทั้งวัสดุ plastic และ brittle ได้",
      ],
      k: "Heckel: Py = 1/slope; Py ต่ำ = plastic (MCC), Py สูง = brittle/fragmenting (DCP)",
      d: "hard",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Tablets and compaction",
    },
    {
      t: "Disintegration test retest rule",
      p: "ทดสอบ disintegration ของยาเม็ดไม่เคลือบตาม USP <701> ในน้ำที่ 37 ± 2 °C ครั้งแรก 6 เม็ด มี 2 เม็ดยังไม่แตกตัวสมบูรณ์ภายในเวลาที่กำหนด จึงทดสอบเพิ่มอีก 12 เม็ด พบไม่แตกตัว 1 เม็ด ข้อใดสรุปได้ถูกต้อง",
      o: [
        "ไม่ผ่าน เพราะแตกตัว 15 จาก 18 เม็ด ต่ำกว่าเกณฑ์ไม่น้อยกว่า 16 จาก 18 เม็ด",
        "ผ่าน เพราะการทดสอบรอบที่สองแตกตัว 11 จาก 12 เม็ด",
        "ผ่าน เพราะแตกตัวรวม 15 จาก 18 เม็ด เกิน 80%",
        "ไม่ผ่านตั้งแต่ครั้งแรก เพราะไม่ควรทดสอบเพิ่มเมื่อมี 2 เม็ดไม่แตก",
        "ต้องทดสอบเพิ่มอีก 24 เม็ดก่อนสรุปผล",
      ],
      a: 0,
      r: "USP <701> กำหนดให้ทดสอบ 6 หน่วย ถ้าทุกหน่วยแตกตัวสมบูรณ์ถือว่าผ่าน ถ้ามี 1 หรือ 2 หน่วยไม่แตกตัวสมบูรณ์ ให้ทดสอบเพิ่มอีก 12 หน่วย และต้องแตกตัวไม่น้อยกว่า 16 จากทั้งหมด 18 หน่วย\n\nในกรณีนี้ไม่แตก 2 + 1 = 3 หน่วย แตกตัว 15/18 จึงไม่ผ่าน (ยอมให้ไม่แตกได้สูงสุด 2 หน่วยจาก 18) การแตกตัวสมบูรณ์หมายถึงไม่มีส่วนที่เหลือบนตะแกรง หรือที่เหลือเป็นมวลอ่อนไม่มีแกนแข็ง (หรือเป็นเพียงชิ้นส่วนของเปลือกเคลือบ/แคปซูล)",
      w: [
        "ถูก — รวมไม่แตก 3 หน่วย แตกตัว 15/18 ต่ำกว่าเกณฑ์ ≥16/18",
        "ต้องประเมินรวมทั้ง 18 หน่วย ไม่ใช่เฉพาะรอบที่สอง",
        "เกณฑ์เป็นจำนวนหน่วย (≥16/18) ไม่ใช่ร้อยละ 80%",
        "เมื่อมี 1–2 หน่วยไม่แตก เกณฑ์ให้ทดสอบเพิ่มอีก 12 หน่วย ไม่ใช่ตัดสินไม่ผ่านทันที",
        "USP <701> ไม่มีขั้นตอนทดสอบเพิ่ม 24 หน่วย",
      ],
      k: "Disintegration USP <701>: 6 หน่วย; ถ้าไม่แตก 1–2 ทดสอบเพิ่ม 12; ต้องแตก ≥16/18",
      d: "hard",
      ref: "USP <701> Disintegration",
    },
    {
      t: "Tablet porosity from dimensions",
      p: "ยาเม็ดแบนกลม (flat-faced) น้ำหนัก 400 mg เส้นผ่านศูนย์กลาง 10.0 mm หนา 4.0 mm ผงสูตรมี true density 1.50 g/cm³ จงคำนวณ porosity ของเม็ดยา",
      o: ["15.1%", "17.8%", "33.3%", "78.8%", "84.9%"],
      a: 0,
      r: "Porosity ของเม็ดยาคือสัดส่วนปริมาตรช่องว่างต่อปริมาตรทั้งหมด หาได้จาก ε = 1 − (apparent density/true density) = 1 − solid fraction\n\nปริมาตรเม็ด = π r² h = π × (0.50 cm)² × 0.40 cm = 0.3142 cm³ ความหนาแน่นปรากฏ = 0.400 g/0.3142 cm³ = 1.273 g/cm³ solid fraction = 1.273/1.50 = 0.849 → porosity = 15.1%\n\nPorosity และ solid fraction เป็นตัวแปรสำคัญที่สัมพันธ์กับ tensile strength และ disintegration โดยยาเม็ดทั่วไปมี porosity ราว 5–20%",
      w: [
        "ถูก — V = 0.3142 cm³, ρapp = 1.273 g/cm³, SF = 0.849, porosity = 15.1%",
        "คำนวณจาก (ρtrue/ρapp − 1) ซึ่งไม่ใช่นิยามของ porosity",
        "ใช้ปริมาตรแบบปริซึมสี่เหลี่ยม (D² × h = 0.40 cm³) แทนทรงกระบอก",
        "ใช้เส้นผ่านศูนย์กลางแทนรัศมีในสูตร πr²h ทำให้ปริมาตรสูงเกินจริง 4 เท่า",
        "84.9% คือ solid fraction ไม่ใช่ porosity",
      ],
      k: "Porosity = 1 − ρapparent/ρtrue; ρapparent = น้ำหนัก ÷ ปริมาตรเม็ด (πr²h สำหรับเม็ดแบน)",
      d: "hard",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Tablets and compaction",
      c: [
        "V = π × (0.50)² × 0.40 = 0.3142 cm³",
        "ρapparent = 0.400 / 0.3142 = 1.273 g/cm³",
        "Solid fraction = 1.273 / 1.50 = 0.849",
        "Porosity = 1 − 0.849 = 0.151 = 15.1%",
      ],
    },
  ],
  // Mock Set 5 — ชุดที่ 5
  [
    {
      t: "Tumbling vs convective blender mechanism",
      p: "V-blender (หรือ double-cone/bin blender) และ ribbon blender เป็นเครื่องผสมผงที่ใช้ในการผลิตยาเม็ด ข้อใดอธิบายกลไกการผสมหลักของเครื่องทั้งสองได้ถูกต้อง",
      o: [
        "V-blender ผสมด้วยการพลิกกลิ้ง (diffusive/tumbling mixing) ส่วน ribbon blender ผสมด้วยการเคลื่อนย้ายมวลผงด้วยใบกวน (convective mixing)",
        "V-blender ผสมด้วย convective mixing ส่วน ribbon blender ผสมด้วย diffusive mixing",
        "ทั้งสองเครื่องอาศัยแรงเฉือนสูง (high shear) ทำลายก้อนผงเป็นหลัก",
        "V-blender ใช้กระแสอากาศพาผงให้ลอยผสมกันเหมือน fluid bed",
        "Ribbon blender ใช้การสั่นสะเทือนให้อนุภาคเรียงตัวเป็นชั้น",
      ],
      a: 0,
      r: "กลไกการผสมผงมี 3 แบบ ได้แก่ convective mixing (การเคลื่อนย้ายกลุ่มอนุภาคจากตำแหน่งหนึ่งไปอีกตำแหน่งด้วยใบกวนหรือสกรู), shear mixing (การเลื่อนไถลของชั้นผงตามระนาบ) และ diffusive mixing (อนุภาคเดี่ยวเคลื่อนที่สุ่มเมื่อผงถูกพลิกกลิ้งและผิวผงขยายตัว)\n\nTumbling mixer เช่น V-blender, double-cone และ bin blender อาศัยการหมุนภาชนะ ให้ผงพลิกกลิ้ง (diffusive เป็นหลักร่วมกับ shear) เหมาะกับผงที่ไหลได้ แรงเฉือนต่ำ และใช้บ่อยในขั้นผสม lubricant ส่วน ribbon blender ใช้ใบกวนรูปเกลียวในถังนิ่ง ดันผงไปมา (convective) จึงผสมผง cohesive ได้ดีกว่า แต่ทำความสะอาดยากและอาจมี dead zone",
      w: [
        "ถูก — tumbling = diffusive เป็นหลัก; ribbon = convective",
        "สลับกลไกกัน",
        "ทั้งสองเครื่องไม่ใช่ high-shear mixer ซึ่งเป็นอุปกรณ์อีกประเภท",
        "การใช้กระแสอากาศเป็นหลักการของ fluid bed ไม่ใช่ V-blender",
        "Ribbon blender ไม่ได้ใช้การสั่นสะเทือน และการสั่นมักทำให้เกิด segregation",
      ],
      k: "Tumbling blender (V, bin) = diffusive; ribbon/planetary = convective; high-shear = shear/convective แรงสูง",
      d: "easy",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Mixing",
    },
    {
      t: "Roller compaction vs slugging",
      p: "โรงงานต้องการทำ dry granulation สำหรับผลิตภัณฑ์ปริมาณมาก ข้อใดเป็นข้อได้เปรียบของ roller compaction เมื่อเทียบกับ slugging",
      o: [
        "เป็นกระบวนการต่อเนื่อง ผลผลิตสูง ควบคุมแรงอัดได้สม่ำเสมอกว่า และไม่ต้องใช้เครื่องตอกขนาดใหญ่ทำ slug",
        "ไม่ต้องมีขั้นตอนบด (milling) หลังการอัด",
        "ใช้น้ำปริมาณเล็กน้อยช่วยให้ ribbon แข็งแรงขึ้น",
        "ได้ granule ที่มีความชื้นสูงกว่าจึงตอกง่ายกว่า",
        "ไม่ต้องใช้ lubricant ในสูตรสุดท้ายเลย",
      ],
      a: 0,
      r: "Dry granulation ทำได้สองวิธี Slugging ใช้เครื่องตอกขนาดใหญ่ (heavy-duty press) ตอกผงเป็นเม็ดใหญ่ (slug) แล้วนำไปบด ข้อเสียคือช้า สิ้นเปลือง ต้องการให้ผงไหลพอเติมเบ้าได้ และน้ำหนัก/ความแน่นของ slug แปรปรวน\n\nRoller compaction ป้อนผงด้วย feed screw ระหว่างลูกกลิ้งคู่ที่หมุนสวนกัน ได้ ribbon/flake อย่างต่อเนื่อง แล้วบดผ่าน screen เป็น granule ข้อดีคือผลผลิตสูง ควบคุม roll pressure, gap และ roll speed ได้แม่นยำ ได้ granule สม่ำเสมอกว่า และขยายขนาดได้ง่าย ทั้งสองวิธียังต้องบดหลังอัดและไม่ใช้น้ำ",
      w: [
        "ถูก — roller compaction เป็นกระบวนการต่อเนื่อง ควบคุมพารามิเตอร์ได้ดีและผลผลิตสูงกว่า slugging",
        "ทั้งสองวิธีต้องบด ribbon หรือ slug ให้เป็น granule ตามขนาดที่ต้องการ",
        "Dry granulation ไม่ใช้น้ำหรือของเหลว",
        "Granule จาก dry granulation ไม่ได้มีความชื้นสูงกว่าผงตั้งต้น",
        "สูตรสุดท้ายยังต้องใช้ lubricant เพื่อการตอกและดันเม็ดออก",
      ],
      k: "Roller compaction > slugging: ต่อเนื่อง, ผลผลิตสูง, ควบคุมแรงอัดได้แม่นยำ; ทั้งสองต้องบดต่อ",
      d: "easy",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Granulation",
    },
    {
      t: "Melt granulation binder selection",
      p: "API ไวต่อความชื้น แต่คงตัวที่อุณหภูมิถึง 80 °C ผู้พัฒนาต้องการทำ melt (thermoplastic) granulation ใน high-shear mixer แบบมีแจ็คเก็ตให้ความร้อน โดยไม่ใช้น้ำหรือตัวทำละลาย binder ใดเหมาะสมที่สุด",
      o: [
        "PEG 6000 (จุดหลอมเหลวประมาณ 55–63 °C)",
        "PEG 400 (เป็นของเหลวที่อุณหภูมิห้อง)",
        "PVP K30 ละลายในน้ำ 10%",
        "Starch paste 10%",
        "Gelatin solution 5%",
      ],
      a: 0,
      r: "Melt granulation ใช้ binder ที่เป็นของแข็งที่อุณหภูมิห้องแต่หลอมเหลวที่อุณหภูมิปานกลาง (ประมาณ 50–90 °C) เช่น PEG 4000–6000, poloxamer 188, glyceryl behenate หรือ stearic acid เมื่อให้ความร้อนระหว่างผสม binder หลอมเป็นของเหลวเคลือบและเชื่อมอนุภาค เมื่อเย็นตัวลงจะแข็งตัวเป็น solid bridge\n\nข้อดีคือไม่ต้องใช้น้ำหรือตัวทำละลาย ไม่ต้องอบแห้ง จึงเหมาะกับยาที่ไวต่อความชื้น ข้อจำกัดคือยาต้องทนความร้อนที่ใช้ PEG 6000 หลอมที่ประมาณ 55–63 °C ซึ่งต่ำกว่าอุณหภูมิที่ยายังคงตัว จึงเหมาะสม",
      w: [
        "ถูก — PEG 6000 เป็นของแข็งที่อุณหภูมิห้อง หลอมได้ต่ำกว่า 80 °C และไม่ต้องใช้น้ำ",
        "PEG 400 เป็นของเหลวที่อุณหภูมิห้อง จะไม่แข็งตัวเป็นสะพาน ทำให้ granule เหนียวและนิ่ม",
        "ใช้น้ำเป็นตัวทำละลาย ขัดกับข้อจำกัดเรื่องความชื้น",
        "Starch paste เตรียมด้วยน้ำ ไม่ใช่ melt binder",
        "Gelatin solution เป็นสารละลายในน้ำ ไม่เหมาะกับยาไวต่อความชื้น",
      ],
      k: "Melt granulation: binder เป็นของแข็งที่หลอม ~50–90 °C (PEG 6000, poloxamer, glyceryl behenate); ไม่ใช้น้ำ ไม่ต้องอบ",
      d: "medium",
      ref: "Parikh, Handbook of Pharmaceutical Granulation Technology 3rd ed., Ch. Melt granulation",
    },
    {
      t: "Edge chipping from damaged punch tips",
      p: "ระหว่างตอกยาเม็ดนูน (concave) พบเม็ดยาบิ่นที่ขอบ (chipping) เพิ่มขึ้นเรื่อย ๆ ในบางสถานี ขณะที่ความชื้นและขนาด granule อยู่ในเกณฑ์ปกติ การตรวจสอบใดควรทำเป็นอันดับแรก",
      o: [
        "ตรวจสภาพปลายสาก (punch tip) และขอบ die ว่ามีการบิ่น สึก หรือเป็นครีบ (burr) แล้วขัดหรือเปลี่ยน tooling",
        "เพิ่มปริมาณ disintegrant เพื่อลดความแข็งของเม็ด",
        "ลดปริมาณ glidant เพื่อให้ granule เกาะกันมากขึ้น",
        "เพิ่มเวลาผสม lubricant เป็นสองเท่า",
        "ลดอุณหภูมิห้องผลิตเพื่อป้องกันการหลอมของ binder",
      ],
      a: 0,
      r: "Chipping คือการบิ่นของขอบเม็ดยา อาจเกิดระหว่างการตอก การดันออก หรือการลำเลียง/เคลือบ เมื่อเกิดเฉพาะบางสถานีและเพิ่มขึ้นตามเวลา ในขณะที่คุณภาพ granule ปกติ สาเหตุที่น่าจะเป็นที่สุดคือ tooling ของสถานีนั้นเสียหาย เช่น ปลายสากบิ่นหรือม้วน (tip curling) ขอบสากคมเป็นครีบ หรือ die สึกเป็นวงแหวน (die ringing)\n\nการแก้ไขคือตรวจและบำรุงรักษา tooling ตามโปรแกรม ขัดหรือเปลี่ยนชุดที่เสียหาย และปรับ take-off/ejection ให้เหมาะสม ส่วนสาเหตุด้านสูตร เช่น granule แห้งเกินหรือ binder น้อย จะส่งผลกับทุกสถานี",
      w: [
        "ถูก — ปัญหาที่เกิดเฉพาะบางสถานีและเพิ่มขึ้นตามเวลาชี้ไปที่ tooling เสียหาย",
        "Disintegrant ไม่เกี่ยวกับการบิ่นที่ขอบจาก tooling และการทำให้เม็ดอ่อนลงอาจทำให้ chipping มากขึ้น",
        "Glidant ไม่ได้เป็นตัวยึด granule และไม่ใช่สาเหตุของปัญหาเฉพาะสถานี",
        "Lubricant มากเกินลดความแข็งแรงของเม็ด อาจทำให้บิ่นง่ายขึ้น",
        "ไม่มีข้อมูลบ่งชี้ว่า binder หลอม และจะส่งผลทุกสถานีไม่ใช่บางสถานี",
      ],
      k: "Chipping เฉพาะบางสถานี → ตรวจ punch tip/die (บิ่น ม้วน ครีบ สึก) ก่อนแก้สูตร",
      d: "medium",
      ref: "Lachman/Lieberman's The Theory and Practice of Industrial Pharmacy 4th ed., Ch. Tablets; TSM (Tableting Specification Manual)",
    },
    {
      t: "Twinning of capsule-shaped tablets in coating",
      p: "ระหว่างเคลือบฟิล์มยาเม็ดรูปแคปซูล (caplet) ที่มีด้านข้างแบน พบเม็ดยาติดกันเป็นคู่ (twinning) จำนวนมาก แนวทางแก้ไขใดเหมาะสมที่สุด",
      o: [
        "ลด spray rate หรือเพิ่ม pan speed/drying ให้สมดุล และพิจารณาปรับรูปทรงเม็ดให้ด้านข้างโค้งเล็กน้อย",
        "เพิ่ม spray rate เพื่อให้เคลือบเสร็จเร็วขึ้น",
        "ลด pan speed ลงมากเพื่อลดการชนกันของเม็ด",
        "เพิ่มความเข้มข้นของ plasticizer เป็นสองเท่าเพื่อให้ฟิล์มนิ่มขึ้น",
        "ลด inlet air temperature เพื่อป้องกัน spray drying",
      ],
      a: 0,
      r: "Twinning คือการที่เม็ดยาสองเม็ดติดกันระหว่างเคลือบ เกิดเมื่อผิวเม็ดเปียกเหนียวสัมผัสกันในพื้นที่กว้าง (เช่น ด้านข้างแบนของ caplet หรือหน้าแบน) แล้วฟิล์มแห้งเชื่อมกัน\n\nการแก้ไขคือลดความเปียกของผิว (ลด spray rate หรือเพิ่ม drying capacity) เพิ่ม pan speed เพื่อให้เม็ดแยกจากกันเร็ว และในระยะยาวควรออกแบบเม็ดให้ด้านข้างโค้งเล็กน้อยเพื่อลดพื้นที่สัมผัสแบบแนบสนิท",
      w: [
        "ถูก — ลดความเปียก เพิ่มการเคลื่อนที่ และลดพื้นที่ผิวแบนที่แนบกันได้",
        "Spray rate สูงทำให้ผิวเปียกมากขึ้นและ twinning รุนแรงขึ้น",
        "Pan speed ต่ำทำให้เม็ดที่เปียกสัมผัสกันนานขึ้น เพิ่มโอกาสติดกัน",
        "Plasticizer มากเกินทำให้ฟิล์มเหนียว (tacky) ยิ่งติดกันง่าย",
        "การลด inlet temperature ทำให้แห้งช้าลง ผิวเปียกนานขึ้น เพิ่ม twinning",
      ],
      k: "Twinning = เม็ดหน้าแบนติดกันจากผิวเปียก → ลด spray rate, เพิ่ม drying/pan speed, ปรับรูปทรงเม็ด",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Coating of tablets and multiparticulates",
    },
    {
      t: "Hard gelatin shell brittleness from hygroscopic fill",
      p: "แคปซูลแข็ง gelatin ที่บรรจุผงยาเกลือที่ดูดความชื้นสูง (hygroscopic) หลังเก็บในขวดปิดสนิท 3 เดือน พบเปลือกแคปซูลเปราะ แตกง่ายเมื่อกด คำอธิบายที่ดีที่สุดคือข้อใด",
      o: [
        "ผงยาดึงความชื้นออกจากเปลือก ทำให้ความชื้นในเปลือกต่ำกว่าช่วงปกติ (~13–16%) เปลือกจึงเปราะ",
        "ความชื้นจากผงยาซึมเข้าสู่เปลือก ทำให้เปลือกบวมและนิ่มเกินไป",
        "Gelatin ทำปฏิกิริยา Maillard กับเกลือของยาจนเปลือกแข็ง",
        "ขวดปิดสนิททำให้ออกซิเจนสะสมและ oxidize เปลือกแคปซูล",
        "เปลือกแคปซูลเปลี่ยนเป็นผลึกเมื่อเก็บนานเกิน 1 เดือน",
      ],
      a: 0,
      r: "Gelatin ใช้น้ำเป็น plasticizer ในเปลือก hard gelatin capsule มีความชื้นประมาณ 13–16% ซึ่งทำให้เปลือกมีความยืดหยุ่น ความชื้นในเปลือกจะเข้าสู่สมดุลกับสภาพแวดล้อมและกับ fill\n\nเมื่อ fill ดูดความชื้นสูง (หรือเก็บในสภาวะ RH ต่ำมาก) น้ำจะเคลื่อนจากเปลือกไปสู่ผงยา ความชื้นในเปลือกลดต่ำกว่าช่วงปกติ (ต่ำกว่าราว 10–12%) เปลือกจึงเปราะและแตกง่าย ในทางกลับกันถ้า RH สูงเกิน เปลือกจะนิ่ม เหนียวติดกัน หรือเสียรูป\n\nแนวทางแก้ไข เช่น ใช้เปลือกที่มีความชื้นต่ำโดยธรรมชาติ ปรับ fill ให้ดูดความชื้นน้อยลง (เติม excipient ที่ช่วยกันความชื้น) และควบคุมสภาวะเก็บและบรรจุภัณฑ์",
      w: [
        "ถูก — fill ที่ดูดความชื้นดึงน้ำซึ่งเป็น plasticizer ออกจากเปลือก ทำให้เปราะ",
        "ทิศทางกลับกัน fill ที่ดูดความชื้นจะดึงน้ำออกจากเปลือก และเปลือกที่ชื้นจะนิ่มไม่ใช่เปราะ",
        "Maillard reaction เกิดระหว่าง reducing sugar กับ amine ไม่ใช่สาเหตุของเปลือกเปราะในกรณีนี้",
        "ออกซิเจนในขวดไม่ใช่กลไกหลักที่ทำให้เปลือก gelatin เปราะ",
        "เปลือก gelatin ไม่ได้เปลี่ยนเป็นผลึกเมื่อเก็บไว้นาน",
      ],
      k: "Hard gelatin shell ความชื้น ~13–16%; fill ที่ดูดความชื้นหรือ RH ต่ำ → เปลือกเปราะ; RH สูง → นิ่มเหนียว",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Hard capsules",
    },
    {
      t: "Compressed vs hard-candy lozenge",
      p: "ต้องการผลิตยาอม (lozenge) ที่มีตัวยาไวต่อความร้อน ให้ค่อย ๆ ละลายในปากเป็นเวลาหลายนาที วิธีการผลิตและลักษณะสูตรใดเหมาะสมที่สุด",
      o: [
        "Compressed lozenge ตอกด้วยแรงสูงจาก filler ที่ละลายน้ำได้ ไม่ใส่ disintegrant",
        "Hard candy lozenge โดยต้มน้ำตาลรวมกับยาที่อุณหภูมิสูงแล้วเทแม่พิมพ์",
        "Compressed lozenge ที่ใส่ superdisintegrant 5% เพื่อให้แตกตัวเร็ว",
        "ยาเม็ดเคลือบฟิล์มทั่วไปที่ตอกด้วยแรงต่ำ",
        "Effervescent tablet ที่ละลายในปาก",
      ],
      a: 0,
      r: "Lozenge ออกแบบให้ค่อย ๆ ละลายหรือกร่อนในปากเพื่อให้ยาออกฤทธิ์เฉพาะที่ในช่องปาก/ลำคอ มีสองรูปแบบหลัก คือ hard candy (molded) lozenge ที่ผลิตโดยต้มน้ำตาลกับ corn syrup ที่อุณหภูมิสูงมาก (ราว 140–160 °C) แล้วเติมยาและขึ้นรูป และ compressed lozenge ที่ตอกด้วยเครื่องตอกยาเม็ด\n\nสำหรับยาที่ไวต่อความร้อน compressed lozenge เหมาะกว่าเพราะไม่ต้องใช้ความร้อนสูง สูตรใช้ filler/binder ที่ละลายน้ำได้และให้รสดี (เช่น mannitol, sorbitol, dextrose) ตอกด้วยแรงสูงให้เม็ดแข็ง เส้นผ่านศูนย์กลางใหญ่ และ ไม่ใส่ disintegrant เพื่อให้ละลายช้าแทนการแตกตัว",
      w: [
        "ถูก — compressed lozenge ไม่ใช้ความร้อนสูง ตอกแข็งและไม่มี disintegrant จึงละลายช้า",
        "Hard candy ต้องใช้อุณหภูมิสูงมาก ไม่เหมาะกับยาที่ไวต่อความร้อน",
        "Superdisintegrant ทำให้เม็ดแตกเร็ว ขัดกับวัตถุประสงค์ของ lozenge",
        "ยาเม็ดทั่วไปที่ตอกแรงต่ำออกแบบให้กลืนและแตกตัว ไม่ใช่อมละลายช้า",
        "Effervescent tablet ต้องละลายในน้ำก่อนรับประทาน ไม่ใช่การอมในปาก",
      ],
      k: "Lozenge ไวต่อความร้อน → compressed lozenge (แรงตอกสูง, ไม่ใส่ disintegrant); hard candy ใช้ความร้อนสูง",
      d: "medium",
      ref: "Remington: The Science and Practice of Pharmacy 22nd ed., Ch. Oral Solid Dosage Forms",
    },
    {
      t: "Rising ejection force and die-wall scoring",
      p: "ระหว่างการผลิต ระบบ instrumented press แสดงค่า ejection force เพิ่มขึ้นต่อเนื่องจาก 300 N เป็น 1,200 N เม็ดยาเริ่มมีรอยขีดตามแนวตั้งบนด้านข้าง (vertical scoring) และเสียงเครื่องดังผิดปกติ ขณะที่แรงตอกหลักคงที่ ข้อใดเป็นสาเหตุและการแก้ไขที่เหมาะสมที่สุด",
      o: [
        "การหล่อลื่นระหว่างเม็ดยากับผนัง die ไม่เพียงพอ (under-lubrication) หรือ die สึก — ทบทวนปริมาณ/การผสม lubricant และตรวจ die",
        "Overlubrication — ลดเวลาผสม magnesium stearate ลงครึ่งหนึ่ง",
        "Disintegrant มากเกินไป — ลด superdisintegrant ในสูตร",
        "Granule ใหญ่เกินไป — ลดขนาด screen ของ mill ลง",
        "Precompression สูงเกินไป — ปิด precompression roller",
      ],
      a: 0,
      r: "Ejection force คือแรงที่ต้องใช้ดันเม็ดยาออกจาก die ซึ่งสัมพันธ์กับแรงเสียดทานระหว่างเม็ดยากับผนัง die ค่า ejection force ที่สูงขึ้นต่อเนื่องร่วมกับรอยขีดแนวตั้งบนด้านข้างเม็ดยาและเสียงผิดปกติ เป็นสัญญาณคลาสสิกของ die-wall friction สูง จากการหล่อลื่นไม่เพียงพอ (lubricant น้อยไป กระจายไม่ทั่ว หรือผงสะสมบนผนัง die) หรือ die ที่สึก/เป็นรอย\n\nถ้าไม่แก้ไขอาจทำให้เกิด capping/lamination ระหว่างดันออก เม็ดแตก และ tooling เสียหาย การแก้ไขคือทบทวนปริมาณและการกระจายของ lubricant ตรวจและขัด/เปลี่ยน die และติดตาม ejection force เป็น in-process monitoring",
      w: [
        "ถูก — ejection force สูง + รอยขีดแนวตั้ง = แรงเสียดทานกับผนัง die สูงจากหล่อลื่นไม่พอหรือ die สึก",
        "Overlubrication ทำให้ ejection force ต่ำลง ไม่ใช่สูงขึ้น ปัญหาหลักของ overlubrication คือเม็ดอ่อนและละลายช้า",
        "Disintegrant ไม่ใช่ตัวกำหนดแรงเสียดทานกับผนัง die",
        "ขนาด granule ไม่อธิบายแนวโน้ม ejection force ที่เพิ่มขึ้นต่อเนื่องระหว่างการผลิต",
        "Precompression ไม่ได้ทำให้ ejection force สูงขึ้นแบบต่อเนื่องและไม่ทำให้เกิดรอยขีดตามแนวตั้ง",
      ],
      k: "Ejection force ↑ + vertical scoring → under-lubrication หรือ die สึก; overlubrication ทำให้ ejection force ↓",
      d: "hard",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Tablets and compaction",
    },
    {
      t: "Weight-corrected potency of single tablet",
      p: "ยาเม็ดมีน้ำหนักเป้าหมาย 250 mg และตัวยา 40 mg (16.0% w/w) ระหว่าง IPC เม็ดหนึ่งชั่งได้ 235 mg และวิเคราะห์ได้ตัวยา 40.0 mg ข้อใดแปลผลได้ถูกต้องที่สุด",
      o: [
        "ความเข้มข้นของยาในเม็ดนี้ ~17.0% w/w (weight-corrected ~106% ของเป้าหมาย) บ่งชี้ความไม่สม่ำเสมอของ blend มากกว่าปัญหาน้ำหนัก",
        "เม็ดนี้มีตัวยา 100% ตาม label จึงไม่มีปัญหาใด ๆ",
        "เม็ดนี้มีตัวยาต่ำกว่าเป้าหมาย 6% เพราะน้ำหนักเม็ดน้อยกว่าเป้าหมาย",
        "ผลนี้บ่งชี้เฉพาะปัญหาเครื่องตอกที่ปรับน้ำหนักผิดเท่านั้น",
        "ควรสรุปว่า assay ผิดพลาด เพราะเม็ดที่หนัก 235 mg ไม่สามารถมีตัวยา 40 mg ได้",
      ],
      a: 0,
      r: "ถ้า blend สม่ำเสมอ ปริมาณยาในเม็ดจะแปรตามน้ำหนักเม็ด เม็ดที่หนัก 235 mg ควรมีตัวยา 235 × 0.160 = 37.6 mg (94% LC) แต่วัดได้ 40.0 mg\n\nความเข้มข้นจริงของยาในเม็ดนี้ = 40.0/235 = 17.0% w/w ซึ่งคิดเป็น 17.0/16.0 = 106% ของความเข้มข้นเป้าหมาย (หรือ weight-corrected content = 40.0 × 250/235 = 42.6 mg = 106%) แสดงว่าบริเวณของ blend ที่เม็ดนี้มาจากมียาเข้มข้นกว่าปกติ ซึ่งบ่งชี้ปัญหา blend uniformity หรือ segregation\n\nการแยกแหล่งความแปรปรวนระหว่าง น้ำหนัก กับ ความเข้มข้นของ blend จึงช่วยชี้ทิศทางการสอบสวน (weight control ของเครื่องตอก vs การผสม/segregation)",
      w: [
        "ถูก — 40.0/235 = 17.0% เทียบกับ 16.0% = 106% บ่งชี้ความเข้มข้นของ blend ไม่สม่ำเสมอ",
        "แม้ได้ 40 mg ตรง label แต่เกิดจากความผิดปกติสองทาง (น้ำหนักต่ำ + ความเข้มข้นสูง) หักล้างกัน ซึ่งเป็นสัญญาณปัญหา",
        "คาดว่าจะต่ำ 6% ถ้า blend สม่ำเสมอ แต่ผลจริงได้ 40 mg จึงไม่ใช่ข้อสรุปที่ถูก",
        "ปัญหาน้ำหนักมีอยู่ แต่ความเข้มข้นที่สูงผิดปกติบ่งชี้ปัญหาการผสมด้วย",
        "เป็นไปได้ถ้าความเข้มข้นของยาใน blend ส่วนนั้นสูงกว่าปกติ ไม่ใช่หลักฐานว่า assay ผิด",
      ],
      k: "แยก weight effect กับ blend concentration: weight-corrected content = assay × (น้ำหนักเป้าหมาย/น้ำหนักจริง)",
      d: "hard",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Mixing; USP <905> Uniformity of Dosage Units",
      c: [
        "ปริมาณที่คาดถ้า blend สม่ำเสมอ = 235 × 0.160 = 37.6 mg (94.0%)",
        "ความเข้มข้นจริง = 40.0 / 235 × 100 = 17.0% w/w",
        "Weight-corrected = 40.0 × 250/235 = 42.6 mg = 106% ของ 40 mg",
      ],
    },
    {
      t: "Binder solution quantity for wet granulation",
      p: "สูตร wet granulation มีผงแห้งส่วนอื่น (API + filler + disintegrant) รวม 48.0 kg ต้องการให้ PVP K30 เป็น 4.0% w/w ของ granule แห้งทั้งหมด โดยเติมในรูป binder solution ในน้ำที่มี PVP 12% w/w ต้องเตรียม binder solution ทั้งหมดประมาณเท่าใด",
      o: ["2.0 kg", "14.7 kg", "16.0 kg", "16.7 kg", "18.7 kg"],
      a: 3,
      r: "PVP เป็น 4% ของ granule แห้งทั้งหมด (ผงอื่น + PVP) ดังนั้นผงอื่นคิดเป็น 96% → มวล granule แห้ง = 48.0/0.96 = 50.0 kg และ PVP = 50.0 × 0.04 = 2.0 kg\n\nBinder solution 12% w/w หมายถึง PVP 12 kg ใน solution 100 kg → solution = 2.0/0.12 = 16.7 kg (PVP 2.0 kg + น้ำ 14.7 kg)\n\nในทางปฏิบัติ ปริมาณของเหลวทั้งหมดอาจต้องปรับตาม granulation endpoint (อาจเติมน้ำเพิ่มหลัง binder solution) แต่ปริมาณ PVP ต้องคงตามสูตร",
      w: [
        "2.0 kg คือปริมาณ PVP ไม่ใช่น้ำหนัก binder solution",
        "14.7 kg คือปริมาณน้ำในสารละลาย ไม่รวม PVP",
        "คิด 4% จาก 48 kg (1.92 kg) แทนที่จะคิดจาก granule แห้งทั้งหมด",
        "ถูก — granule แห้ง 50.0 kg, PVP 2.0 kg, solution = 2.0/0.12 = 16.7 kg",
        "ตีความ 12% เป็นอัตราส่วน PVP ต่อน้ำ (2.0 kg ในน้ำ 16.7 kg) แทนที่จะเป็น w/w ของสารละลาย",
      ],
      k: "% ของ granule แห้ง → หาร (1 − %binder) ก่อน; solution = มวล binder ÷ ความเข้มข้น w/w",
      d: "hard",
      ref: "Parikh, Handbook of Pharmaceutical Granulation Technology 3rd ed.",
      c: [
        "Granule แห้งทั้งหมด = 48.0 / 0.96 = 50.0 kg",
        "PVP = 50.0 × 0.04 = 2.0 kg",
        "Binder solution = 2.0 / 0.12 = 16.7 kg (น้ำ 14.7 kg)",
      ],
    },
  ],
];
