import type { Ip1MockDomainContent } from "@/lib/ip1-mock/types";

export const STABILITY: Ip1MockDomainContent = [
  // Mock Set 1 — ชุดที่ 1
  [
    {
      t: "Ester hydrolysis susceptibility",
      p: "ทีมพัฒนาสูตรได้รับตัวยา 5 ชนิดเพื่อทำ oral solution ในน้ำ (pH 6–7) หากพิจารณาเฉพาะหมู่ฟังก์ชันที่ไวต่อ hydrolysis ตัวยาใดมีแนวโน้มเสื่อมสลายด้วย hydrolysis เร็วที่สุด",
      o: [
        "Acetylsalicylic acid (มี phenolic ester)",
        "Paracetamol (มี anilide/amide)",
        "Phenobarbital (มี imide ในวง barbiturate)",
        "Ibuprofen (มี carboxylic acid)",
        "Chlorpheniramine (มี tertiary amine)",
      ],
      a: 0,
      r: "Hydrolysis เกิดได้ง่ายที่หมู่ carbonyl ที่ถูก nucleophile (น้ำ/OH⁻) โจมตี ลำดับความไวโดยทั่วไปคือ ester > amide/imide ส่วน carboxylic acid และ amine ไม่ hydrolyze\n\nAspirin เป็น phenyl ester ซึ่ง leaving group (phenoxide ของ salicylate) เสถียรด้วย resonance จึงยิ่ง hydrolyze ง่ายกว่า alkyl ester ทั่วไป ได้ salicylic acid + acetic acid (กลิ่นน้ำส้มสายชู) ด้วยเหตุนี้ aspirin จึงแทบไม่ทำเป็น aqueous solution สำเร็จรูป แต่ทำเป็นเม็ดแห้งหรือ effervescent ที่ละลายก่อนใช้",
      w: [
        "ถูก — phenolic ester ของ aspirin เป็นหมู่ที่ hydrolyze ง่ายที่สุดในตัวเลือก ได้ salicylic acid + acetic acid",
        "Amide ของ paracetamol เสถียรกว่า ester มาก เพราะ nitrogen ให้ resonance กับ carbonyl ทำให้ carbonyl carbon electrophilic น้อยลง hydrolysis เกิดช้าที่ pH ใกล้กลาง",
        "Barbiturate ring hydrolyze ได้ แต่เด่นในสภาวะด่างแรง ที่ pH 6–7 ช้ากว่า aspirin มาก",
        "Carboxylic acid ไม่มี leaving group ให้ hydrolysis จึงไม่ใช่ pathway หลักของ ibuprofen",
        "Tertiary amine ไม่ hydrolyze; ปัญหาของ amine มักเป็น oxidation (N-oxide) มากกว่า",
      ],
      k: "ความไวต่อ hydrolysis: ester (โดยเฉพาะ phenyl ester) > lactam/imide > amide; acid/amine ไม่ hydrolyze",
      d: "easy",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Chemical stability of drugs; Connors, Chemical Stability of Pharmaceuticals 2nd ed.",
    },
    {
      t: "Antioxidant phase selection",
      p: "ครีม o/w มีวิตามิน A palmitate (ละลายในน้ำมัน ไวต่อ oxidation) อยู่ในวัฏภาคน้ำมัน การเลือก antioxidant ข้อใดเหมาะสมที่สุด",
      o: [
        "เติม BHT หรือ α-tocopherol ลงในวัฏภาคน้ำมัน",
        "เติม sodium metabisulfite ลงในวัฏภาคน้ำ",
        "เติม ascorbic acid ลงในวัฏภาคน้ำเท่านั้น",
        "เติม disodium EDTA แทน antioxidant ทั้งหมด",
        "เติม sodium chloride เพื่อลด oxygen solubility",
      ],
      a: 0,
      r: "Antioxidant ต้องอยู่วัฏภาคเดียวกับตัวยาที่ต้องการปกป้อง Vitamin A palmitate อยู่ในน้ำมัน จึงต้องใช้ oil-soluble antioxidant ชนิด free-radical chain terminator เช่น BHT, BHA, α-tocopherol หรือ ascorbyl palmitate\n\nWater-soluble antioxidant (ascorbic acid, sodium metabisulfite, sodium sulfite) ใช้กับยาในวัฏภาคน้ำ ส่วน EDTA เป็น synergist ที่จับโลหะ ช่วยเสริมแต่ไม่หยุด radical chain ด้วยตัวเอง",
      w: [
        "ถูก — BHT/tocopherol ละลายในน้ำมัน อยู่ใกล้ตัวยาและหยุด radical chain ได้โดยตรง",
        "Metabisulfite เป็น water-soluble reducing agent อยู่คนละวัฏภาคกับ vitamin A palmitate จึงปกป้องได้น้อย",
        "Ascorbic acid ละลายน้ำ ไม่เข้าไปในหยดน้ำมัน (ถ้าต้องการ ascorbate ในน้ำมันต้องใช้ ascorbyl palmitate)",
        "EDTA เป็นเพียง chelator/synergist ลด metal catalysis แต่ไม่ใช่ chain-breaking antioxidant ใช้แทนทั้งหมดไม่ได้",
        "การเติมเกลือไม่ใช่กลยุทธ์ป้องกัน oxidation ที่ใช้จริงและไม่ได้ปกป้องยาในวัฏภาคน้ำมัน",
      ],
      k: "เลือก antioxidant ให้อยู่วัฏภาคเดียวกับยา: น้ำมัน → BHT/BHA/tocopherol; น้ำ → ascorbic acid/sulfites",
      d: "easy",
      ref: "Handbook of Pharmaceutical Excipients 9th ed.; Aulton's Pharmaceutics 6th ed.",
    },
    {
      t: "First-order t90 calculation",
      p: "Oral solution ตัวหนึ่งเสื่อมสลายแบบ first-order ที่ 25°C ด้วย k = 2.1 × 10⁻³ day⁻¹ เวลาที่ตัวยาเหลือ 90% ของเริ่มต้น (t90) ประมาณเท่าใด",
      o: ["5.0 วัน", "47.6 วัน", "50.2 วัน", "330 วัน", "1,096 วัน"],
      a: 2,
      r: "สำหรับ first-order: ln(C0/C) = kt เมื่อ C = 0.9C0 จะได้ t90 = ln(1/0.9)/k = 0.1054/k\n\nt90 = 0.1054 / 0.0021 = 50.2 วัน ซึ่งไม่ขึ้นกับความเข้มข้นเริ่มต้น ต่างจาก zero-order ที่ t90 = 0.1C0/k0\n\nตัวเลือกอื่นเกิดจากความสับสนสูตร: 0.693/k คือ t1/2 และ 2.303/k คือเวลาที่เหลือเพียง 10%",
      w: [
        "ผิดหลักทศนิยม (เลื่อนตำแหน่ง) ไม่สอดคล้องกับ 0.1054/0.0021",
        "ใช้ 0.1/k ซึ่งเป็นการคิดแบบประมาณผิดสูตร (คล้าย zero-order) ได้ 47.6 วัน",
        "ถูก — t90 = 0.1054/k = 0.1054/0.0021 = 50.2 วัน",
        "เป็น t1/2 = 0.693/k ไม่ใช่ t90",
        "เป็น ln10/k คือเวลาที่ยาเหลือ 10% (สลายไป 90%)",
      ],
      k: "First-order: t90 = 0.105/k, t1/2 = 0.693/k (ทั้งคู่ไม่ขึ้นกับ C0)",
      d: "medium",
      ref: "Martin's Physical Pharmacy and Pharmaceutical Sciences 7th ed., Ch. Kinetics",
      c: [
        "First-order: t90 = ln(100/90)/k = 0.1054/k",
        "t90 = 0.1054 / (2.1 × 10⁻³ day⁻¹)",
        "t90 = 50.2 วัน",
      ],
    },
    {
      t: "Q10 refrigerated product at room temperature",
      p: "ยาน้ำชนิดหนึ่งมี t90 = 24 เดือนเมื่อเก็บที่ 5°C ร้านยาเก็บผิดไว้ที่ 25°C ตลอดเวลา หากประมาณด้วย Q10 = 3 ตัวยาจะมี t90 ที่ 25°C ประมาณเท่าใด",
      o: ["0.9 เดือน", "2.7 เดือน", "4.0 เดือน", "8.0 เดือน", "12.0 เดือน"],
      a: 1,
      r: "Q10 คือสัดส่วนที่อัตราการเสื่อมเพิ่มขึ้นเมื่ออุณหภูมิเพิ่ม 10°C ใช้ได้กับ shelf life ในลักษณะ t90(T2) = t90(T1) / Q10^(ΔT/10)\n\nΔT = 25 − 5 = 20°C → Q10^2 = 3² = 9 → t90 = 24/9 = 2.7 เดือน\n\nQ10 = 2, 3, 4 สอดคล้องกับ Ea ประมาณ 50, 80, 105 kJ/mol ตามลำดับ (Connors) ใช้เป็นการประมาณคร่าวๆ เมื่อไม่มีข้อมูล Arrhenius จริง",
      w: [
        "ใช้ Q10^3 = 27 (นับ ΔT ผิดเป็น 30°C) ได้ 24/27 ≈ 0.9 เดือน",
        "ถูก — ΔT = 20°C → Q10^(20/10) = 9 → 24/9 ≈ 2.7 เดือน",
        "คูณ Q10 × 2 = 6 แทนการยกกำลัง ได้ 4 เดือน ซึ่งผิดหลัก Q10",
        "หารด้วย Q10 เพียงครั้งเดียว (คิดเหมือน ΔT = 10°C)",
        "หารด้วย 2 คือใช้ Q10 = 2 เพียงขั้นเดียว ไม่ตรงกับเงื่อนไขโจทย์",
      ],
      k: "t90(T2) = t90(T1)/Q10^(ΔT/10); ยาตู้เย็นที่หลุดไปอยู่ 25°C อายุลดลงหลายเท่า",
      d: "medium",
      ref: "Connors KA, Amidon GL, Stella VJ. Chemical Stability of Pharmaceuticals 2nd ed.",
      c: [
        "ΔT = 25 − 5 = 20°C",
        "Factor = Q10^(ΔT/10) = 3^2 = 9",
        "t90(25°C) = 24 เดือน / 9 = 2.67 ≈ 2.7 เดือน",
      ],
    },
    {
      t: "Maillard reaction with lactose",
      p: "ยาเม็ด Drug X (มีหมู่ primary amine) ใช้ lactose monohydrate เป็น filler หลัง accelerated 40°C/75%RH 3 เดือน เม็ดยาเปลี่ยนเป็นสีเหลือง-น้ำตาล และพบ degradant ใหม่ที่ไม่พบใน API เดี่ยว การแก้ไขสูตรข้อใดตรงสาเหตุที่สุด",
      o: [
        "เปลี่ยน filler เป็น microcrystalline cellulose หรือ mannitol ซึ่งไม่ใช่ reducing sugar",
        "เปลี่ยนเป็น anhydrous lactose เพื่อลดความชื้นและยังคงใช้ lactose ได้ตามเดิม",
        "เพิ่ม BHT ในสูตรเพื่อป้องกันการเปลี่ยนสี",
        "เพิ่มปริมาณ magnesium stearate เพื่อเคลือบผิวอนุภาค",
        "บรรจุใน amber glass เพื่อป้องกันแสง",
      ],
      a: 0,
      r: "Lactose เป็น reducing sugar (มี hemiacetal เปิดเป็น aldehyde ได้) ทำปฏิกิริยากับ primary/secondary amine ได้ glycosylamine → Amadori rearrangement → สารสีน้ำตาล (Maillard reaction) ความชื้นและอุณหภูมิเร่งปฏิกิริยา ตัวอย่างที่รายงาน เช่น fluoxetine, amlodipine, metoclopramide\n\nการแก้ที่ต้นเหตุคือตัด reducing sugar ออก ใช้ MCC, dibasic calcium phosphate หรือ mannitol (sugar alcohol ไม่มี carbonyl) แทน anhydrous lactose ลดความชื้นได้บ้างแต่ยังเป็น reducing sugar",
      w: [
        "ถูก — ตัด reducing sugar ออกจากสูตร จึงไม่มี aldehyde ให้ทำปฏิกิริยากับ amine",
        "Anhydrous lactose ยังเป็น reducing sugar ลดความเร็วได้บ้างแต่ไม่แก้สาเหตุ โดยเฉพาะในเขต Zone IVb",
        "BHT เป็น radical scavenger สำหรับ oxidation ไม่ได้ยับยั้ง Maillard condensation",
        "Magnesium stearate ไม่ป้องกันการสัมผัสระหว่าง amine กับ lactose อย่างมีนัยสำคัญ และอาจเพิ่มปัญหาอื่น",
        "การเปลี่ยนสีครั้งนี้เกิดจากปฏิกิริยาเคมีระหว่างยากับ excipient ไม่ใช่ photolysis",
      ],
      k: "Primary/secondary amine + reducing sugar (lactose, glucose) → Maillard browning; ใช้ MCC/DCP/mannitol แทน",
      d: "medium",
      ref: "Handbook of Pharmaceutical Excipients 9th ed. (Lactose monograph: incompatibilities)",
    },
    {
      t: "Significant change criteria (drug product)",
      p: "ผลศึกษา accelerated 40°C/75%RH ที่ 6 เดือนของยาเม็ด (assay spec 95.0–105.0%) ข้อใดถือเป็น significant change ตาม ICH Q1A(R2)",
      o: [
        "Assay ลดลงจาก 101.8% เป็น 96.5% แม้ยังอยู่ใน specification",
        "Assay ลดลงจาก 100.4% เป็น 97.0%",
        "Total degradant เพิ่มจาก 0.2% เป็น 0.6% โดย spec ≤ 1.0%",
        "Dissolution ลดลงจาก 92% เป็น 85% ที่ 30 นาที โดย spec Q = 80%",
        "Hardness ลดลงเล็กน้อยแต่ friability ยังผ่านเกณฑ์",
      ],
      a: 0,
      r: "ICH Q1A(R2) นิยาม significant change ของ drug product ได้แก่ (1) assay เปลี่ยนจากค่าเริ่มต้น 5% (2) degradation product ใดเกิน acceptance criterion (3) ไม่ผ่านเกณฑ์ appearance/physical/functionality (4) pH ไม่ผ่าน (5) dissolution ไม่ผ่านใน 12 dosage units\n\nจุดสำคัญคือเกณฑ์ assay วัดจาก 'การเปลี่ยนแปลงจากค่าเริ่มต้น' ไม่ใช่แค่ผ่าน/ไม่ผ่าน spec: 101.8 → 96.5 = ลดลง 5.3% จึงเป็น significant change ทั้งที่ยังอยู่ใน spec ผลคือต้องพิจารณา intermediate (ถ้ามี) และจำกัดการ extrapolate shelf life",
      w: [
        "ถูก — ลดลง 5.3% จากค่าเริ่มต้น เกินเกณฑ์ 5% แม้ยังผ่าน spec",
        "ลดลง 3.4% ยังไม่ถึง 5% และอยู่ใน spec",
        "Degradant เพิ่มขึ้นแต่ยังไม่เกิน acceptance criterion จึงไม่เข้าเกณฑ์",
        "Dissolution ยังผ่าน Q จึงไม่ใช่ significant change (ต้องเป็นการ fail เกณฑ์)",
        "การเปลี่ยนแปลงทางกายภาพที่ยังผ่าน acceptance criteria ไม่ถือเป็น significant change",
      ],
      k: "Significant change: assay เปลี่ยน ≥5% จากค่าเริ่มต้น หรือ attribute ใด fail spec (degradant, appearance, pH, dissolution)",
      d: "medium",
      ref: "ICH Q1A(R2) Stability Testing of New Drug Substances and Products, Section 2.2.7",
    },
    {
      t: "Alu-Alu cold-form blister for hygroscopic tablet",
      p: "ยาเม็ด effervescent-like ที่ดูดความชื้นสูงมาก (assay และ dissolution เปลี่ยนเมื่อดูดน้ำ > 1%) จะวางจำหน่ายในประเทศไทย (Zone IVb) ต้องการบรรจุแบบ unit-dose blister ข้อใดเหมาะสมที่สุด",
      o: [
        "Cold-form Alu-Alu (OPA/Al/PVC + lidding aluminium foil)",
        "PVC 250 µm + aluminium lidding foil",
        "PVC/PVDC 40 g/m² + aluminium lidding foil",
        "PET blister ใส + paper/PET lidding",
        "PP blister + aluminium lidding foil",
      ],
      a: 0,
      r: "ความสามารถกันความชื้น (MVTR ต่ำ → ดี) เรียงคร่าวๆ: PVC < PP ≈ PVC/PVDC < PVC/Aclar (PCTFE) < Alu-Alu (cold form) ซึ่ง aluminium foil หนาที่ไม่มีรูเข็มให้ MVTR เกือบเป็นศูนย์และกันแสงได้ด้วย\n\nสำหรับยาไวความชื้นสูงในสภาวะ 30°C/75%RH Alu-Alu เป็นตัวเลือกที่ปลอดภัยที่สุด ข้อเสียคือ cavity ใหญ่ขึ้น (ขึ้นรูปเย็นยืดได้น้อย) ต้นทุนสูง และมองไม่เห็นเม็ดยา การเลือกต้องยืนยันด้วย stability data ใน pack จริงที่ 30°C/75%RH",
      w: [
        "ถูก — Alu-Alu ให้ barrier ต่อความชื้น แสง และออกซิเจนสูงสุดในกลุ่ม blister",
        "PVC เดี่ยวมี MVTR สูงที่สุด ไม่เหมาะกับยาไวความชื้นใน Zone IVb",
        "PVC/PVDC ดีกว่า PVC มากแต่ยังมีการซึมผ่านความชื้นได้ ไม่พอสำหรับยาที่ไวสูงมาก",
        "PET และ paper lidding ไม่ใช่ moisture barrier ระดับสูง",
        "PP กันความชื้นได้ดีกว่า PVC แต่ยังด้อยกว่า Alu-Alu อย่างชัดเจน",
      ],
      k: "Moisture barrier ของ blister: PVC < PVC/PVDC < PVC/Aclar < Alu-Alu; ยาไวความชื้นสูงใน Zone IVb → Alu-Alu",
      d: "medium",
      ref: "WHO TRS 902 Annex 9 Guidelines on packaging for pharmaceutical products; Aulton's Pharmaceutics 6th ed., Ch. Packaging",
    },
    {
      t: "Arrhenius prediction of t90 at 25°C",
      p: "การศึกษา stress พบว่ายาในสารละลายเสื่อมแบบ first-order ที่ 60°C ด้วย k = 0.020 day⁻¹ และมี Ea = 80 kJ/mol (R = 8.314 J/mol·K) ถ้ากลไกไม่เปลี่ยน t90 ที่ 25°C ประมาณเท่าใด",
      o: ["5.3 วัน", "59.6 วัน", "156 วัน", "1,029 วัน", "3,417 วัน"],
      a: 2,
      r: "Arrhenius: ln(k2/k1) = −(Ea/R)(1/T2 − 1/T1) โดยต้องใช้ Kelvin\n\nT1 = 333.15 K, T2 = 298.15 K → 1/T2 − 1/T1 = 3.522 × 10⁻⁴ K⁻¹; Ea/R = 80,000/8.314 = 9,622 K → ln(k25/k60) = −3.39 → k25/k60 = 0.0337 → k25 = 6.74 × 10⁻⁴ day⁻¹\n\nt90 = 0.1054/k25 = 156 วัน (≈5 เดือน) ข้อควรระวัง: การทำนายจากอุณหภูมิสูงใช้ได้เมื่อกลไกและลำดับปฏิกิริยาไม่เปลี่ยนในช่วงอุณหภูมิ และไม่มีการเปลี่ยนสถานะ/ความชื้นมาเกี่ยวข้อง",
      w: [
        "เป็น t90 ที่ 60°C (0.1054/0.020) ยังไม่ได้แปลงไป 25°C",
        "ใช้กฎ Q10 = 2 (2^3.5 ≈ 11.3) ซึ่งประเมินต่ำกว่าเมื่อ Ea จริง 80 kJ/mol (เทียบ Q10 ≈ 2.7–3)",
        "ถูก — k25 = 6.74 × 10⁻⁴ day⁻¹ → t90 = 0.1054/k25 ≈ 156 วัน",
        "เป็น t1/2 ที่ 25°C (0.693/k25) ไม่ใช่ t90",
        "เป็นเวลาที่ยาเหลือ 10% (2.303/k25) ไม่ใช่ t90",
      ],
      k: "Arrhenius ใช้ Kelvin เสมอ: ln(k2/k1) = −Ea/R (1/T2 − 1/T1) แล้ว t90 = 0.105/k",
      d: "hard",
      ref: "Martin's Physical Pharmacy and Pharmaceutical Sciences 7th ed.; Connors, Chemical Stability of Pharmaceuticals",
      c: [
        "T1 = 60 + 273.15 = 333.15 K; T2 = 25 + 273.15 = 298.15 K",
        "1/T2 − 1/T1 = 0.0033540 − 0.0030017 = 3.522 × 10⁻⁴ K⁻¹",
        "Ea/R = 80,000 / 8.314 = 9,622 K",
        "ln(k25/k60) = −9,622 × 3.522 × 10⁻⁴ = −3.39 → k25/k60 = 0.0337",
        "k25 = 0.020 × 0.0337 = 6.74 × 10⁻⁴ day⁻¹",
        "t90 = 0.1054 / 6.74 × 10⁻⁴ = 156 วัน",
      ],
    },
    {
      t: "No intermediate condition when long-term is 30°C",
      p: "บริษัทยื่นทะเบียนยาเม็ดในอาเซียน ทำ long-term ที่ 30°C/75%RH และ accelerated ที่ 40°C/75%RH พบ significant change ที่ accelerated เดือนที่ 6 ขั้นตอนข้อใดสอดคล้องกับ ICH Q1A(R2)/ASEAN guideline มากที่สุด",
      o: [
        "ไม่มี intermediate condition ให้ทำ; กำหนด shelf life จากข้อมูล long-term จริงที่ 30°C/75%RH โดยไม่ extrapolate จากข้อมูลเร่ง",
        "ต้องเพิ่ม intermediate 30°C/65%RH 12 เดือนก่อนกำหนด shelf life",
        "ต้องเพิ่ม intermediate 25°C/60%RH เพื่อเทียบกับเขต Zone II",
        "ใช้ข้อมูล accelerated คำนวณ shelf life ด้วย Arrhenius แทน long-term",
        "ผลที่ accelerated ไม่มีผลต่อการกำหนด shelf life เพราะ long-term ยังผ่าน",
      ],
      a: 0,
      r: "ICH Q1A(R2) ระบุว่า intermediate condition (30°C/65%RH) ใช้เมื่อ long-term คือ 25°C/60%RH และเกิด significant change ที่ accelerated แต่ถ้า long-term เป็น 30°C/65%RH หรือ 30°C/75%RH (ตาม Zone IVb ที่อาเซียนใช้) จะไม่มี intermediate condition\n\nเมื่อเกิด significant change ที่ accelerated ICH Q1E ระบุว่าไม่ควรอาศัยการ extrapolate เกินข้อมูล long-term ดังนั้น shelf life ต้องอิงข้อมูล real-time ที่ 30°C/75%RH และผล accelerated ยังใช้ประเมินผลของ excursion ระยะสั้นระหว่างขนส่งได้",
      w: [
        "ถูก — long-term 30°C/75%RH ไม่มี intermediate และ significant change ที่ accelerated ทำให้ต้องอิงข้อมูล long-term จริง",
        "30°C/65%RH เป็นสภาวะที่อ่อนกว่า long-term 30°C/75%RH ที่ใช้อยู่แล้ว จึงไม่ให้ข้อมูลเพิ่ม",
        "25°C/60%RH เป็น long-term ของ Zone I/II ไม่ใช่ intermediate และไม่แทนสภาวะในอาเซียน",
        "Significant change ที่ accelerated บ่งว่ากลไกอาจไม่ linear ตาม Arrhenius การทำนายจากข้อมูลเร่งจึงไม่น่าเชื่อถือ",
        "Significant change ที่ accelerated มีผลจำกัดการ extrapolate และต้องอภิปรายในเอกสาร ไม่ใช่ละเลย",
      ],
      k: "Long-term 30°C/65% หรือ 30°C/75% → ไม่มี intermediate; significant change ที่ accelerated → ห้าม extrapolate เกินข้อมูล long-term",
      d: "hard",
      ref: "ICH Q1A(R2) Section 2.2.7; ICH Q1E; ASEAN Guideline on Stability Study of Drug Product (R1)",
    },
    {
      t: "Hydrate conversion of carbamazepine on storage",
      p: "ยาเม็ด carbamazepine (anhydrous form III) ที่บรรจุใน PVC blister หลังเก็บที่ 30°C/75%RH 6 เดือน พบ dissolution ลดลงมาก และ XRPD พบ peak ใหม่ แม้ assay และ degradant ปกติ คำอธิบายใดน่าจะเป็นสาเหตุที่สุด",
      o: [
        "เกิด solution-mediated/solid-state conversion เป็น carbamazepine dihydrate ซึ่งละลายช้ากว่า เพราะความชื้นซึมผ่าน PVC",
        "เกิด hydrolysis ของ carbamazepine เป็น iminostilbene ทำให้ dissolution ต่ำ",
        "ตัวยาเกิด photolysis จากแสงผ่าน PVC ใส",
        "เกิด Maillard reaction ระหว่าง carbamazepine กับ excipient",
        "ตัวยาเปลี่ยนเป็น amorphous ทำให้ละลายช้าลง",
      ],
      a: 0,
      r: "การเปลี่ยน solid form ระหว่างเก็บเป็นปัญหา physical stability ที่ assay ไม่ช่วยตรวจจับ Carbamazepine anhydrous ดูดความชื้นแล้วเปลี่ยนเป็น dihydrate ซึ่งเป็นรูปแบบที่เสถียรในน้ำและมี solubility/dissolution rate ต่ำกว่า มีรายงานความล้มเหลวทางคลินิกจากเม็ดที่เก็บในที่ชื้น\n\nหลักฐานคือ XRPD peak ใหม่ (lattice เปลี่ยน) ขณะที่เคมีไม่เปลี่ยน การแก้: pack กันความชื้น (Alu-Alu/ขวด + desiccant), ฉลาก 'Protect from moisture' และเพิ่ม dissolution/solid-form monitoring ใน stability protocol",
      w: [
        "ถูก — anhydrous → dihydrate ในที่ชื้นทำให้ dissolution ลดลง สอดคล้องกับ XRPD ที่เปลี่ยน ขณะ assay ปกติ",
        "ถ้าเป็น chemical degradation ต้องพบ assay ลดและ degradant เพิ่ม ซึ่งโจทย์ระบุว่าปกติ",
        "Photolysis เป็นการเปลี่ยนเคมี ต้องเห็น degradant ไม่ใช่ XRPD peak ใหม่โดย assay ปกติ",
        "Carbamazepine ไม่มีหมู่ amine อิสระแบบ primary/secondary ที่ทำ Maillard และ assay ไม่ลด",
        "Amorphous จะละลายเร็วขึ้นและให้ halo ใน XRPD ไม่ใช่ peak ใหม่",
      ],
      k: "Polymorph/hydrate conversion ระหว่างเก็บ → dissolution เปลี่ยนโดย assay ปกติ; ต้องติดตามด้วย XRPD/dissolution และใช้ pack กันชื้น",
      d: "hard",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Solid-state properties; Brittain HG, Polymorphism in Pharmaceutical Solids 2nd ed.",
    },
  ],
  // Mock Set 2 — ชุดที่ 2
  [
    {
      t: "Retest period vs shelf life",
      p: "ข้อใดอธิบายความแตกต่างระหว่าง retest period ของ API (drug substance) กับ shelf life ของ drug product ได้ถูกต้องที่สุด",
      o: [
        "API ที่ครบ retest period อาจตรวจซ้ำแล้วนำไปใช้ผลิตได้ทันทีหากผ่าน spec แต่ drug product ที่เกิน shelf life ห้ามจำหน่ายแม้ตรวจซ้ำผ่าน",
        "Retest period และ shelf life มีความหมายเดียวกัน ใช้แทนกันได้ทั้ง API และ drug product",
        "Drug product ที่ครบ shelf life สามารถตรวจซ้ำและขยายวันหมดอายุทีละ lot ได้",
        "Retest period ใช้เฉพาะยาชีววัตถุ ส่วน API สังเคราะห์ใช้ shelf life เท่านั้น",
        "API ที่ครบ retest period ต้องทำลายทิ้งทุกกรณี",
      ],
      a: 0,
      r: "ICH Q1A(R2) นิยาม retest period ว่าเป็นช่วงเวลาที่ API คาดว่าจะยังอยู่ใน spec หากเก็บตามที่กำหนด เมื่อครบแล้วต้องตรวจซ้ำก่อนใช้ ถ้าผ่านสามารถใช้ผลิตได้ทันที (ควรใช้ภายในระยะหนึ่งหลังตรวจ)\n\nShelf life (expiration dating period) ของ drug product คือระยะเวลาที่ผลิตภัณฑ์ต้องอยู่ใน spec ตลอดอายุ วันหมดอายุบนฉลากเป็นข้อจำกัดเด็ดขาด ไม่สามารถตรวจซ้ำแล้วขยายรายล็อตได้ สำหรับ API บางชนิด เช่น ชีววัตถุ/antibiotic ที่ไม่เสถียร อาจกำหนดเป็น shelf life แทน retest period",
      w: [
        "ถูก — retest period ของ API ตรวจซ้ำแล้วใช้ต่อได้ ส่วน shelf life ของ drug product เป็นวันหมดอายุเด็ดขาด",
        "สองคำนี้มีความหมายและผลทางปฏิบัติต่างกันชัดเจนตาม ICH Q1A(R2)",
        "การขยาย shelf life ต้องผ่าน variation/ข้อมูล stability ไม่ใช่ตรวจซ้ำทีละ lot หลังหมดอายุ",
        "กลับกัน — API ทั่วไปใช้ retest period ส่วนชีววัตถุหลายชนิดใช้ shelf life",
        "API ที่ครบ retest period สามารถตรวจซ้ำและใช้ได้ถ้าผ่าน spec ไม่จำเป็นต้องทำลาย",
      ],
      k: "API: retest period (ตรวจซ้ำแล้วใช้ได้); Drug product: shelf life (หมดอายุแล้วห้ามใช้)",
      d: "easy",
      ref: "ICH Q1A(R2) Glossary; ICH Q7 Section 11.6",
    },
    {
      t: "Inert gas headspace replacement",
      p: "ยาน้ำรับประทานที่ไวต่อ oxidation บรรจุขวดแก้ว พบ assay ลดเร็วโดยเฉพาะขวดที่มี headspace มาก มาตรการด้านกระบวนการข้อใดตรงกับปัญหานี้ที่สุด",
      o: [
        "Sparge สารละลายและ flush headspace ด้วย nitrogen ก่อนปิดฝา",
        "เพิ่มอุณหภูมิระหว่างผสมเพื่อให้ตัวยาละลายเร็ว",
        "เติมอากาศเข้าสารละลายเพื่อให้ฟองหายเร็ว",
        "ใช้ฝาที่หลวมขึ้นเพื่อระบายความดัน",
        "เพิ่มปริมาตร headspace เพื่อลดการกระเพื่อม",
      ],
      a: 0,
      r: "ออกซิเจนที่ละลายในสารละลายและที่อยู่ใน headspace เป็นแหล่งของ autoxidation การไล่ออกซิเจนด้วย inert gas (nitrogen หรือ argon) ทั้งการ sparging ระหว่างผสมและการ flush headspace ก่อนปิด ช่วยลดออกซิเจนตั้งต้นได้มาก\n\nมักใช้ร่วมกับ antioxidant, chelator, การควบคุม pH และภาชนะที่กันออกซิเจนได้ดี ปริมาณ residual O₂ ใน headspace สามารถกำหนดเป็น in-process control ได้",
      w: [
        "ถูก — ไล่ dissolved O₂ และ O₂ ใน headspace ด้วย nitrogen ลดแหล่งตั้งต้นของ oxidation",
        "ความร้อนเร่ง oxidation และไม่ลดออกซิเจน",
        "การเติมอากาศเพิ่ม dissolved oxygen ทำให้ oxidation แย่ลง",
        "ฝาหลวมทำให้ออกซิเจนและความชื้นเข้าได้ง่ายขึ้น",
        "Headspace มากขึ้นหมายถึงปริมาณออกซิเจนมากขึ้น",
      ],
      k: "ยาไว oxidation: nitrogen sparging + headspace flushing ลด O₂ ตั้งต้น ใช้คู่กับ antioxidant/chelator",
      d: "easy",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Chemical stability; Remington: The Science and Practice of Pharmacy 23rd ed.",
    },
    {
      t: "Catechol oxidation of epinephrine",
      p: "สารละลาย epinephrine เปลี่ยนเป็นสีชมพูแล้วกลายเป็นสีน้ำตาลเมื่อเก็บในภาชนะที่เปิดใช้บ่อย กลไกและมาตรการป้องกันข้อใดสอดคล้องกันที่สุด",
      o: [
        "Catechol ถูก oxidize เป็น adrenochrome และ melanin-like pigment; ป้องกันด้วย pH ต่ำ, sodium metabisulfite, EDTA และไล่ออกซิเจน",
        "Ester hydrolysis ได้ catechol อิสระ; ป้องกันโดยปรับ pH เป็นด่าง",
        "Maillard reaction กับน้ำตาล; ป้องกันด้วยการตัดน้ำตาลออก",
        "Decarboxylation ของ side chain; ป้องกันด้วยการแช่แข็ง",
        "Photo-polymerization; ป้องกันด้วย BHT ในวัฏภาคน้ำ",
      ],
      a: 0,
      r: "Epinephrine มีหมู่ catechol (1,2-dihydroxybenzene) ซึ่ง autoxidize ได้ง่ายโดยเฉพาะที่ pH สูง มีโลหะหนัก แสง และออกซิเจน ได้ o-quinone → cyclize เป็น adrenochrome (สีชมพู-แดง) → polymer สีน้ำตาล\n\nการป้องกัน: ปรับ pH ให้เป็นกรด (ประมาณ 2.5–5) ซึ่งเป็นช่วงที่ phenol ไม่แตกตัว, ใช้ sodium metabisulfite ที่เหมาะกับ pH ต่ำ, เติม EDTA จับโลหะ, ไล่ O₂ และกันแสง ข้อพึงระวังคือ bisulfite อาจทำปฏิกิริยาเกิด epinephrine sulfonate และ pH ต่ำเกินไปเร่ง racemization",
      w: [
        "ถูก — catechol oxidation เป็นกลไกหลักและมาตรการทั้งหมดลด oxidation ตรงจุด",
        "Epinephrine ไม่มีหมู่ ester และ pH ด่างกลับเร่ง oxidation ของ catechol",
        "การเปลี่ยนสีของ epinephrine เกิดจาก oxidation ไม่ใช่ Maillard",
        "Decarboxylation ไม่ใช่ pathway หลักของ epinephrine และไม่อธิบายสีชมพู",
        "BHT ไม่ละลายน้ำและการเปลี่ยนสีไม่ได้เกิดจาก photo-polymerization เป็นหลัก",
      ],
      k: "Catechol (epinephrine, levodopa, isoprenaline) → oxidation เป็น quinone มีสี; ใช้ pH ต่ำ + metabisulfite + EDTA + N₂",
      d: "medium",
      ref: "Connors, Chemical Stability of Pharmaceuticals 2nd ed. (Epinephrine monograph); Aulton's Pharmaceutics 6th ed.",
    },
    {
      t: "Pseudo-first-order hydrolysis concept",
      p: "การ hydrolysis ของยา ester ในสารละลาย buffer pH 4 จริงๆ เป็นปฏิกิริยา bimolecular ระหว่างยากับน้ำ (และ H⁺) แต่ข้อมูลกลับเข้ากับ first-order kinetics เหตุผลข้อใดถูกต้องที่สุด",
      o: [
        "น้ำมีปริมาณมากเกินมากและ [H⁺] คงที่ด้วย buffer จึงรวมเข้าเป็นค่าคงที่ kobs ได้ (pseudo-first-order)",
        "ปฏิกิริยาเกิดเฉพาะบนผิวภาชนะ จึงไม่ขึ้นกับความเข้มข้น",
        "ยาละลายไม่หมดจึงเป็น zero-order แต่ดูเหมือน first-order",
        "Buffer ทำหน้าที่เป็น catalyst ที่ถูกใช้หมดไประหว่างปฏิกิริยา",
        "ปฏิกิริยา bimolecular ทุกชนิดเป็น first-order เสมอ",
      ],
      a: 0,
      r: "อัตรา = k[ester][H₂O][H⁺] แต่ในสารละลายน้ำ ความเข้มข้นน้ำ (~55.5 M) แทบไม่เปลี่ยน และ buffer ตรึง [H⁺] ไว้ จึงรวมเป็น kobs = k[H₂O][H⁺] ทำให้อัตรา = kobs[ester] ซึ่งเป็น pseudo-first-order\n\nดังนั้น kobs ขึ้นกับ pH ชนิดและความเข้มข้นของ buffer (general acid–base catalysis) และ ionic strength เมื่อเปลี่ยนสภาวะเหล่านี้ต้องหา kobs ใหม่ เป็นพื้นฐานของการสร้าง pH-rate profile",
      w: [
        "ถูก — สารตั้งต้นอื่นมีมากเกินหรือถูกตรึงความเข้มข้น จึงเหลือการขึ้นกับยาเพียงตัวเดียว",
        "ปฏิกิริยาบนผิวภาชนะไม่ใช่เหตุผลของ pseudo-order ใน hydrolysis",
        "Apparent zero-order เกิดใน suspension ที่ความเข้มข้นในสารละลายคงที่ ไม่ใช่กรณีนี้",
        "Buffer/catalyst ไม่ถูกใช้หมด และถ้าถูกใช้หมด kobs จะไม่คงที่",
        "ปฏิกิริยา bimolecular เป็น second-order โดยแท้ จะเป็น first-order เฉพาะเมื่อมีสารหนึ่งมากเกินหรือคงที่",
      ],
      k: "Pseudo-first-order: สารร่วมปฏิกิริยา (น้ำ, H⁺/OH⁻ ใน buffer) มีมากเกินหรือคงที่ → rate = kobs[ยา]",
      d: "medium",
      ref: "Martin's Physical Pharmacy and Pharmaceutical Sciences 7th ed., Ch. Kinetics",
    },
    {
      t: "Photostability dark control purpose",
      p: "ในการทดสอบ photostability ตาม ICH Q1B ของยาเม็ด analyst วางตัวอย่างที่ห่อด้วย aluminium foil ไว้ในตู้ทดสอบข้างตัวอย่างที่รับแสง วัตถุประสงค์หลักของตัวอย่างห่อ foil คืออะไร",
      o: [
        "เป็น dark control เพื่อแยกการเปลี่ยนแปลงจากความร้อน/ความชื้นในตู้ ออกจากผลของแสง",
        "ใช้วัดปริมาณแสงที่ได้รับแทน lux meter",
        "ใช้เป็นตัวอย่างสำรองกรณีตัวอย่างหลักแตก",
        "เพื่อจำลอง Alu-Alu blister ซึ่งเป็นภาชนะจำหน่าย",
        "เพื่อพิสูจน์ว่า aluminium foil ไม่ปล่อย leachables",
      ],
      a: 0,
      r: "ระหว่างการฉายแสงในตู้ อุณหภูมิของตัวอย่างอาจสูงขึ้น ICH Q1B จึงกำหนดให้วางตัวอย่างที่ป้องกันแสง (เช่น ห่อ aluminium foil) เป็น dark control ไว้คู่กันในสภาวะเดียวกัน\n\nหาก degradant เกิดทั้งใน exposed และ dark control แสดงว่าเกิดจากความร้อน ไม่ใช่แสง ส่วนที่เกิดเฉพาะใน exposed จึงเป็นผลของ photodegradation การแปลผลจึงต้องเทียบระหว่างสองกลุ่ม ปริมาณแสงวัดด้วย calibrated radiometer/lux meter หรือ chemical actinometer",
      w: [
        "ถูก — dark control ใช้แยก thermal effect ออกจาก photolytic effect",
        "Foil ไม่ใช่เครื่องมือวัดแสง ปริมาณแสงต้องวัดด้วย radiometer/lux meter หรือ actinometry",
        "ไม่ใช่ตัวอย่างสำรอง แต่เป็นกลุ่มควบคุมที่ต้องวิเคราะห์ด้วย",
        "การทดสอบใน marketing pack ใช้ pack จริง ไม่ใช่การห่อ foil แทน",
        "Leachables ไม่ใช่วัตถุประสงค์ของ Q1B",
      ],
      k: "Q1B dark control (ห่อ foil วางข้างกัน) = แยกผลความร้อนในตู้ออกจากผลของแสง",
      d: "medium",
      ref: "ICH Q1B Photostability Testing of New Drug Substances and Products",
    },
    {
      t: "HDPE vs PET bottle barrier",
      p: "ยาเม็ดตัวหนึ่งไวต่อ oxidation มาก แต่ไม่ค่อยไวความชื้น ทีมบรรจุภัณฑ์กำลังเลือกระหว่างขวด HDPE ทึบกับขวด PET สีชา (ความหนาเท่ากัน) ข้อสรุปใดถูกต้องที่สุด",
      o: [
        "PET กันออกซิเจนได้ดีกว่า HDPE ชัดเจน แม้จะกันความชื้นได้ด้อยกว่า จึงเหมาะกับยานี้มากกว่า",
        "HDPE กันทั้งออกซิเจนและความชื้นได้ดีกว่า PET ในทุกกรณี",
        "PET กันความชื้นได้ดีที่สุดในพลาสติก แต่กันออกซิเจนไม่ได้",
        "พลาสติกทุกชนิดกันออกซิเจนได้เท่ากัน ต่างกันเพียงความชื้น",
        "ควรใช้ LDPE เพราะยืดหยุ่นและกันออกซิเจนได้ดีที่สุด",
      ],
      a: 0,
      r: "Polyolefin (HDPE, PP) กันไอน้ำได้ดีเพราะไม่มีขั้ว แต่ให้ออกซิเจนซึมผ่านได้สูง ส่วน PET เป็น polyester มีขั้ว chain แน่น ให้ oxygen barrier ดีกว่า HDPE หลายเท่า แต่ moisture barrier ด้อยกว่า HDPE\n\nดังนั้นการเลือกภาชนะต้องดูว่ายาไวต่อปัจจัยใด ยาไว oxidation ได้ประโยชน์จาก PET (หรือแก้ว) ส่วนยาไวความชื้นนิยม HDPE + induction seal + desiccant ส่วน LDPE ให้ barrier ต่ำทั้งสองด้าน",
      w: [
        "ถูก — PET มี oxygen barrier ดีกว่า HDPE ชัดเจน ขณะที่ HDPE เด่นเรื่องกันความชื้น",
        "HDPE เด่นเฉพาะ moisture barrier แต่ oxygen permeability สูง",
        "สลับคุณสมบัติ — PET เด่นที่ oxygen barrier ไม่ใช่ moisture barrier สูงสุด",
        "Oxygen permeability ของพลาสติกแต่ละชนิดต่างกันได้หลายระดับขนาด",
        "LDPE มี density ต่ำ ให้ทั้งออกซิเจนและความชื้นซึมผ่านมากที่สุดในกลุ่มนี้",
      ],
      k: "HDPE/PP: moisture barrier ดี O₂ barrier แย่; PET: O₂ barrier ดีกว่า moisture barrier ด้อยกว่า HDPE",
      d: "medium",
      ref: "WHO TRS 902 Annex 9; Aulton's Pharmaceutics 6th ed., Ch. Pharmaceutical packaging",
    },
    {
      t: "Water loss in semi-permeable container",
      p: "ยาน้ำรับประทานบรรจุขวด LDPE (semi-permeable) ทำ accelerated ที่ 40°C/RH ไม่เกิน 25% น้ำหนักสุทธิเริ่มต้น 100.0 g หลัง 3 เดือนเหลือ 94.6 g (น้ำหนักที่หายเป็นน้ำ) ข้อใดสรุปได้ถูกต้องที่สุดตาม ICH Q1A(R2)",
      o: [
        "สูญเสียน้ำ 5.4% ถือเป็น significant change สำหรับภาชนะ semi-permeable ขนาดนี้",
        "สูญเสียน้ำ 5.4% ยังไม่เป็น significant change เพราะเกณฑ์คือ 10%",
        "สูญเสียน้ำ 0.54% ไม่มีผลต่อการประเมิน",
        "การสูญเสียน้ำไม่ใช่ประเด็น เพราะประเมินเฉพาะ assay ของตัวยา",
        "สูญเสียน้ำ 5.4% ทำให้ต้องเปลี่ยน long-term เป็น 25°C/60%RH",
      ],
      a: 0,
      r: "ผลิตภัณฑ์ในน้ำที่บรรจุภาชนะ semi-permeable (LDPE bottle, bag) อาจสูญเสียน้ำผ่านผนังทำให้ความเข้มข้นยาสูงขึ้น ICH Q1A(R2) ให้ศึกษาที่ RH ต่ำและกำหนดว่า การสูญเสียน้ำ 5% จากค่าเริ่มต้นหลังเก็บเทียบเท่า 3 เดือนที่ 40°C/RH ไม่เกิน 25% ถือเป็น significant change\n\nกรณีนี้ (100.0 − 94.6)/100.0 × 100 = 5.4% จึงเป็น significant change ข้อยกเว้นคือภาชนะขนาดเล็ก (≤1 mL) หรือ unit-dose ซึ่งอาจยอมรับการสูญเสีย ≥5% ได้หากมีเหตุผลรองรับ",
      w: [
        "ถูก — สูญเสีย 5.4% ≥ 5% ภายใน 3 เดือนที่ 40°C/≤25%RH เป็น significant change",
        "เกณฑ์ของ ICH คือ 5% ไม่ใช่ 10%",
        "คำนวณผิดหลัก — 5.4 g จาก 100 g คือ 5.4% ไม่ใช่ 0.54%",
        "การสูญเสียน้ำทำให้ความเข้มข้นเพิ่ม/ปริมาตรลด จึงเป็นเกณฑ์สำคัญของ semi-permeable container",
        "สภาวะ long-term ขึ้นกับ climatic zone ที่จำหน่าย ไม่ได้เปลี่ยนเพราะผลการสูญเสียน้ำ",
      ],
      k: "Semi-permeable container: สูญเสียน้ำ ≥5% หลัง 3 เดือนที่ 40°C/≤25%RH = significant change (ยกเว้น ≤1 mL/unit-dose ที่มีเหตุผล)",
      d: "medium",
      ref: "ICH Q1A(R2) Section 2.2.7.3 Drug products packaged in semi-permeable containers",
      c: [
        "Water loss = 100.0 − 94.6 = 5.4 g",
        "% loss = 5.4 / 100.0 × 100 = 5.4%",
        "5.4% ≥ 5% (เกณฑ์ ICH ที่ 40°C/≤25%RH, 3 เดือน) → significant change",
      ],
    },
    {
      t: "Activation energy from two temperatures",
      p: "การศึกษา stress ของยาในสารละลาย (first-order) ได้ k = 0.0060 day⁻¹ ที่ 40°C และ k = 0.0420 day⁻¹ ที่ 60°C (R = 8.314 J/mol·K) Activation energy (Ea) ของปฏิกิริยานี้ประมาณเท่าใด",
      o: ["1.94 kJ/mol", "20.2 kJ/mol", "36.6 kJ/mol", "84.4 kJ/mol", "194 kJ/mol"],
      a: 3,
      r: "จาก Arrhenius สองจุด: ln(k2/k1) = (Ea/R)(1/T1 − 1/T2)\n\nk2/k1 = 0.0420/0.0060 = 7.0 → ln 7 = 1.946; 1/313.15 − 1/333.15 = 1.917 × 10⁻⁴ K⁻¹ → Ea = 8.314 × 1.946 / 1.917 × 10⁻⁴ = 84,400 J/mol ≈ 84.4 kJ/mol\n\nค่านี้อยู่ในช่วงทั่วไปของการเสื่อมสลายของยา (ประมาณ 50–120 kJ/mol) Ea สูงหมายถึงอัตราไวต่ออุณหภูมิมาก การทำนาย shelf life จากอุณหภูมิสูงจึงต้องการ Ea ที่แม่นยำ",
      w: [
        "ใช้อุณหภูมิเป็น °C แทน Kelvin (1/40 − 1/60) ทำให้ค่าผิดมาก",
        "ใช้ R = 1.987 cal/mol·K แต่รายงานเป็น kJ (ที่จริงได้ ≈ 20.2 kcal/mol ซึ่งเท่ากับ ≈ 84 kJ/mol)",
        "ใช้ log10 แทน ln โดยไม่คูณ 2.303",
        "ถูก — Ea = R·ln(k2/k1)/(1/T1 − 1/T2) ≈ 84.4 kJ/mol",
        "เลื่อนทศนิยมผิด/ไม่ได้ใช้ ln ratio ที่ถูกต้อง",
      ],
      k: "Ea = R·ln(k2/k1) / (1/T1 − 1/T2) ใช้ K และ ln; ระวังหน่วย cal vs J",
      d: "hard",
      ref: "Martin's Physical Pharmacy and Pharmaceutical Sciences 7th ed., Ch. Kinetics (Arrhenius equation)",
      c: [
        "T1 = 313.15 K, T2 = 333.15 K",
        "k2/k1 = 0.0420/0.0060 = 7.0 → ln 7.0 = 1.946",
        "1/T1 − 1/T2 = 0.0031934 − 0.0030017 = 1.917 × 10⁻⁴ K⁻¹",
        "Ea = 8.314 × 1.946 / 1.917 × 10⁻⁴ = 84,400 J/mol ≈ 84.4 kJ/mol",
      ],
    },
    {
      t: "Suspension apparent zero-order shelf life",
      p: "ยาแขวนตะกอน 250 mg/5 mL (50 mg/mL) ตัวยามี solubility 2.0 mg/mL และในสารละลายเสื่อมแบบ first-order ด้วย k1 = 5.0 × 10⁻³ day⁻¹ โดยถือว่าเฉพาะส่วนที่ละลายเท่านั้นที่เสื่อม t90 ของผลิตภัณฑ์ suspension นี้ประมาณเท่าใด",
      o: ["20 วัน", "21.1 วัน", "139 วัน", "500 วัน", "5,000 วัน"],
      a: 3,
      r: "ใน suspension ส่วนของยาที่ละลายถูกเติมกลับจาก reservoir ที่เป็นของแข็ง ความเข้มข้นในสารละลายจึงคงที่เท่ากับ Cs ทำให้อัตราเสื่อมรวมคงที่ = apparent zero-order ด้วย k0 = k1 × Cs\n\nk0 = 5.0 × 10⁻³ × 2.0 = 0.010 mg/mL/day → t90 = 0.1 × C0/k0 = 0.1 × 50/0.010 = 500 วัน\n\nเทียบกับถ้าเป็นสารละลายทั้งหมด t90 = 0.105/k1 = 21 วัน จึงเห็นว่าการทำเป็น suspension (หรือใช้ salt/prodrug ที่ละลายน้อย) เป็นกลยุทธ์เพิ่มความคงตัวของยาที่ hydrolyze ง่าย เช่น penicillin บางชนิด",
      w: [
        "ใช้ Cs (2.0 mg/mL) เป็น C0 ผิด ต้องใช้ความเข้มข้นรวมของผลิตภัณฑ์ 50 mg/mL",
        "เป็น t90 ของยาในรูปสารละลาย (0.105/k1) ไม่ได้คำนึงถึง reservoir ของแข็ง",
        "เป็น t1/2 ของสารละลาย (0.693/k1)",
        "ถูก — k0 = k1·Cs = 0.010 mg/mL/day; t90 = 0.1 × 50/0.010 = 500 วัน",
        "ลืมคูณ 0.1 (คำนวณเวลาที่ยาสลายหมด 100% แบบ zero-order)",
      ],
      k: "Suspension: apparent zero-order k0 = k1·Cs; t90 = 0.1C0/k0 (ใช้ได้ตราบที่ยังมีของแข็งเหลือ)",
      d: "hard",
      ref: "Martin's Physical Pharmacy and Pharmaceutical Sciences 7th ed., Ch. Kinetics (Suspensions)",
      c: [
        "k0 = k1 × Cs = 5.0 × 10⁻³ day⁻¹ × 2.0 mg/mL = 0.010 mg/mL/day",
        "t90 = 0.1 × C0 / k0 = 0.1 × 50 / 0.010",
        "t90 = 500 วัน",
      ],
    },
    {
      t: "Gelatin capsule cross-linking on storage",
      p: "Hard gelatin capsule ที่บรรจุ granule ซึ่งมี PEG และ povidone (มี peroxide/aldehyde ตกค้าง) หลังเก็บที่ 40°C/75%RH พบ dissolution ใน 0.1 N HCl ลดลงมาก แต่ assay ปกติ และเห็นเปลือกเป็นแผ่นเยื่อ (pellicle) ไม่แตก การจัดการเบื้องต้นข้อใดถูกต้องที่สุด",
      o: [
        "สงสัย gelatin cross-linking จาก aldehyde ทดสอบซ้ำด้วยตัวกลางที่เติม enzyme (pepsin) ตาม USP <711> และแก้ที่แหล่ง aldehyde/เปลี่ยนเป็น HPMC capsule",
        "สรุปว่าตัวยาเปลี่ยน polymorph จึงต้องเปลี่ยน API supplier",
        "เพิ่ม rotation speed ของ dissolution apparatus จนได้ผลผ่าน",
        "เพิ่มปริมาณ magnesium stearate เพื่อให้ granule กระจายตัวดีขึ้น",
        "สรุปว่าเป็น analytical error และเปลี่ยน HPLC column",
      ],
      a: 0,
      r: "Gelatin มีหมู่ amino (lysine) ที่ทำ cross-link กับ aldehyde (formaldehyde, furfural) ที่มาจาก excipient degradation (PEG, povidone, polysorbate), สี หรือบรรจุภัณฑ์ ความร้อนและความชื้นเร่งปฏิกิริยา เกิด pellicle ที่ละลายช้า ทำให้ dissolution ลดแม้ตัวยาไม่เสื่อม\n\nUSP <711> อนุญาตให้ทำ dissolution ซ้ำโดยเติม enzyme (pepsin สำหรับ pH ≤ 6.8, pancreatin สำหรับ pH > 6.8) เพื่อย่อย cross-link หากผ่านเกณฑ์จึงยอมรับได้ ส่วนการแก้ระยะยาวคือควบคุม peroxide/aldehyde ของ excipient หรือใช้ HPMC capsule ซึ่งไม่ cross-link",
      w: [
        "ถูก — อาการ pellicle + dissolution ลด + assay ปกติ เข้ากับ gelatin cross-linking; ทดสอบด้วย enzyme และแก้ที่ต้นเหตุ",
        "Polymorph change ไม่ทำให้เกิดแผ่นเยื่อเปลือก capsule และไม่ได้มีหลักฐาน solid-state",
        "การปรับ apparatus ตามใจเพื่อให้ผ่านขัดกับวิธีที่ validate แล้วและไม่แก้ปัญหา",
        "Magnesium stearate เพิ่มความไม่ชอบน้ำ อาจทำให้ dissolution แย่ลง และไม่ใช่สาเหตุ",
        "อาการทางกายภาพของเปลือกบ่งชี้ปัญหาผลิตภัณฑ์จริง ไม่ใช่ปัญหา HPLC",
      ],
      k: "Gelatin + aldehyde → cross-link/pellicle → dissolution ช้า; ใช้ enzyme-containing medium (USP <711>) หรือเปลี่ยนเป็น HPMC capsule",
      d: "hard",
      ref: "USP <711> Dissolution (Capsules—gelatin cross-linking); Digenis GA et al. J Pharm Sci 1994;83:915",
    },
  ],
  // Mock Set 3 — ชุดที่ 3
  [
    {
      t: "Long-term testing frequency",
      p: "ยาเม็ดใหม่เสนอ shelf life 36 เดือน ตาม ICH Q1A(R2) ตารางดึงตัวอย่าง (pull points) ของ long-term study ข้อใดเหมาะสมขั้นต่ำ",
      o: [
        "0, 3, 6, 9, 12, 18, 24, 36 เดือน",
        "0, 6, 12, 24, 36 เดือน",
        "0, 12, 24, 36 เดือน",
        "0, 3, 6 เดือน แล้วจึงตรวจที่ 36 เดือน",
        "ทุกเดือนตลอด 36 เดือน",
      ],
      a: 0,
      r: "ICH Q1A(R2) แนะนำความถี่สำหรับผลิตภัณฑ์ที่เสนอ shelf life อย่างน้อย 12 เดือน: ปีแรกทุก 3 เดือน, ปีที่สองทุก 6 เดือน และหลังจากนั้นปีละครั้งจนครบ shelf life → 0, 3, 6, 9, 12, 18, 24, 36\n\nส่วน accelerated ต้องมีอย่างน้อย 3 จุดรวมจุดเริ่มต้นและสุดท้าย (0, 3, 6 เดือน) และ intermediate (ถ้าต้องทำ) อย่างน้อย 4 จุดรวมต้นและท้ายในการศึกษา 12 เดือน (0, 6, 9, 12)",
      w: [
        "ถูก — ปีแรกทุก 3 เดือน ปีที่สองทุก 6 เดือน หลังจากนั้นทุกปี",
        "ปีแรกตรวจถี่ไม่พอ (ขาด 3 และ 9 เดือน) ทำให้ประเมินแนวโน้มช่วงแรกได้ไม่ดี",
        "ห่างเกินไปมาก ไม่เป็นไปตามความถี่ที่ ICH แนะนำ",
        "เป็นรูปแบบของ accelerated ไม่ใช่ long-term และขาดข้อมูลช่วงกลาง",
        "ถี่เกินความจำเป็น สิ้นเปลืองตัวอย่างและทรัพยากรโดยไม่เพิ่มคุณค่า",
      ],
      k: "Long-term: q3 เดือนปีแรก, q6 เดือนปีที่สอง, ปีละครั้งหลังจากนั้น; Accelerated: 0, 3, 6 เดือน",
      d: "easy",
      ref: "ICH Q1A(R2) Section 2.2.6 Testing frequency",
    },
    {
      t: "Nifedipine photodegradation protection",
      p: "Nifedipine (dihydropyridine) เปลี่ยนเป็น nitrosophenylpyridine derivative อย่างรวดเร็วเมื่อโดนแสง มาตรการใดสำคัญที่สุดในการผลิตและออกแบบยาเม็ด",
      o: [
        "ผลิตภายใต้แสงที่มีความยาวคลื่นยาว (เช่น หลอด sodium/แสงสีเหลือง) และเคลือบฟิล์มทึบแสงที่มี iron oxide/TiO₂ ร่วมกับบรรจุภัณฑ์กันแสง",
        "เติม sodium metabisulfite ในเม็ดยาเพื่อป้องกันแสง",
        "ลดความชื้นของ granule ให้ต่ำกว่า 0.5% เพียงอย่างเดียว",
        "ใช้ blister PVC ใสเพื่อให้ผู้ป่วยตรวจสอบเม็ดยาได้",
        "เก็บเม็ดยาในตู้เย็นเพื่อชะลอ photolysis",
      ],
      a: 0,
      r: "Photolysis เกิดเมื่อโมเลกุลดูดกลืนแสงที่ความยาวคลื่นที่ตรงกับ chromophore ของมัน Nifedipine ดูดกลืน UV และแสงม่วง-น้ำเงิน (ถึงประมาณ 450 nm) จึงไวต่อทั้ง daylight และหลอดไฟทั่วไป\n\nมาตรการ: ควบคุมแสงในห้องผลิตเป็นแสงความยาวคลื่นยาว, ใช้ film coat ทึบแสงที่มี pigment (iron oxide สีแดง/ส้ม และ TiO₂) และบรรจุภัณฑ์ทึบแสง/สีชา พร้อมระบุ 'Protect from light' อุณหภูมิไม่ใช่ปัจจัยหลักของ photochemical reaction",
      w: [
        "ถูก — กันแสงทุกขั้นตอน ตั้งแต่ผลิต เคลือบ จนถึงบรรจุภัณฑ์",
        "Metabisulfite เป็น antioxidant ไม่ได้ดูดกลืนหรือกั้นแสง",
        "ความชื้นไม่ใช่ปัจจัยหลักของ photolysis ของ nifedipine",
        "PVC ใสให้แสงผ่าน จะเร่ง photodegradation",
        "Photolysis ขึ้นกับพลังงานแสงมากกว่าอุณหภูมิ การแช่เย็นไม่ได้กันแสง",
      ],
      k: "ยาไวแสง: ควบคุมแสงในห้องผลิต + opaque film coat (TiO₂/iron oxide) + pack กันแสง + ฉลาก Protect from light",
      d: "easy",
      ref: "Tønnesen HH, Photostability of Drugs and Drug Formulations 2nd ed.; ICH Q1B",
    },
    {
      t: "Amide vs ester hydrolytic stability",
      p: "Procaine (ester) และ procainamide (amide) มีโครงสร้างคล้ายกันมาก เหตุใด procainamide จึงทนต่อ hydrolysis ในสารละลายได้ดีกว่า procaine อย่างชัดเจน",
      o: [
        "Lone pair ของ nitrogen ใน amide ให้ resonance กับ carbonyl ทำให้ carbonyl carbon electrophilic น้อยลง และ amine เป็น leaving group ที่แย่กว่า alkoxide",
        "Amide มีน้ำหนักโมเลกุลสูงกว่า จึงละลายน้ำน้อยกว่า",
        "Amide ไม่มีหมู่ carbonyl จึงไม่ถูก nucleophile โจมตี",
        "Procainamide เป็น salt ส่วน procaine เป็น free base เสมอ",
        "Amide ถูก oxidize แทน hydrolysis จึงดูเหมือนเสถียร",
      ],
      a: 0,
      r: "Nucleophilic acyl substitution ขึ้นกับ (1) ความเป็น electrophile ของ carbonyl carbon และ (2) ความสามารถของ leaving group ใน amide, nitrogen ให้อิเล็กตรอนผ่าน resonance แรงกว่า oxygen ใน ester ทำให้ C=O มีลักษณะ partial double bond กับ N และ carbonyl carbon ถูกโจมตีได้ยาก อีกทั้ง amide anion/amine เป็น leaving group ที่แย่กว่า alkoxide\n\nจึงเป็นเหตุผลหนึ่งที่ procainamide มีความคงตัวและออกฤทธิ์นานกว่า procaine (ซึ่งยังถูก esterase ในพลาสมาตัดอย่างรวดเร็วด้วย) ลำดับทั่วไป: ester > amide",
      w: [
        "ถูก — resonance ของ amide ลด electrophilicity และ leaving group แย่กว่า",
        "น้ำหนักโมเลกุล/solubility ไม่ใช่เหตุผลของอัตรา hydrolysis ในสารละลาย",
        "Amide มีหมู่ carbonyl แต่ถูกทำให้ reactive น้อยลงด้วย resonance",
        "รูปแบบ salt ไม่ใช่เหตุผลเชิงโครงสร้างของความต่างนี้ ทั้งคู่ใช้ในรูป HCl salt",
        "Procainamide ไม่ได้เสื่อมด้วย oxidation แทน แต่ hydrolysis ช้ากว่าจริง",
      ],
      k: "Amide ทน hydrolysis มากกว่า ester เพราะ resonance ของ N และ leaving group ที่แย่กว่า",
      d: "medium",
      ref: "Connors, Chemical Stability of Pharmaceuticals 2nd ed.; Aulton's Pharmaceutics 6th ed.",
    },
    {
      t: "Tetracycline epimerization and anhydro degradants",
      p: "Tetracycline capsule ที่เก็บในที่ร้อนชื้นจนเลยวันหมดอายุ มีรายงานทำให้เกิดพิษต่อ renal tubule (Fanconi-like syndrome) degradant ใดเป็นสาเหตุ และเกิดจากกระบวนการใด",
      o: [
        "4-Epianhydrotetracycline ซึ่งเกิดจาก epimerization ที่ C-4 ร่วมกับ dehydration ในสภาวะกรด",
        "Isotetracycline จาก hydrolysis ในสภาวะด่าง",
        "Tetracycline N-oxide จาก oxidation ของ tertiary amine",
        "Tetracycline-lactose adduct จาก Maillard reaction",
        "Decarboxylated tetracycline จากความร้อน",
      ],
      a: 0,
      r: "Tetracycline เกิด reversible epimerization ที่ C-4 (ช่วง pH ประมาณ 2–6) ได้ 4-epitetracycline ซึ่งฤทธิ์ต่ำ และในสภาวะกรด/ความชื้น/ความร้อนเกิด dehydration (เสีย OH ที่ C-6) ได้ anhydrotetracycline และ 4-epianhydrotetracycline ซึ่งเป็นพิษต่อไต\n\nในสภาวะด่างจะเกิด isotetracycline (ring cleavage) ซึ่งไม่ใช่สาเหตุพิษดังกล่าว ด้วยเหตุนี้ pharmacopoeia จึงกำหนด limit ของ 4-epianhydrotetracycline และ anhydrotetracycline ใน tetracycline ไว้อย่างเข้มงวด",
      w: [
        "ถูก — epimerization + dehydration ในกรดได้ 4-epianhydrotetracycline ที่ก่อพิษต่อไต",
        "Isotetracycline เกิดในด่างและไม่ใช่สาเหตุของ Fanconi-like syndrome",
        "N-oxide ไม่ใช่ degradant สำคัญที่สัมพันธ์กับพิษนี้",
        "ไม่ใช่กลไกที่รายงานเป็นสาเหตุพิษต่อไตของ tetracycline หมดอายุ",
        "Decarboxylation ไม่ใช่ pathway หลักของ tetracycline",
      ],
      k: "Tetracycline: กรด → 4-epi และ anhydro → 4-epianhydrotetracycline (พิษต่อไต); ด่าง → isotetracycline",
      d: "medium",
      ref: "Connors, Chemical Stability of Pharmaceuticals 2nd ed. (Tetracycline); USP Tetracycline Hydrochloride monograph",
    },
    {
      t: "First-order shelf life from one time point",
      p: "ยาเม็ดมี assay เริ่มต้น 100.0% label claim และที่ 12 เดือน (long-term) เหลือ 95.0% หากการเสื่อมเป็น first-order และ spec ล่างคือ 90.0% เวลาที่ assay ถึง 90.0% ประมาณเท่าใด",
      o: ["5.8 เดือน", "12.0 เดือน", "24.0 เดือน", "24.6 เดือน", "162 เดือน"],
      a: 3,
      r: "First-order: ln(C0/C) = kt → k = ln(100/95)/12 = 0.05129/12 = 4.274 × 10⁻³ month⁻¹\n\nt(90%) = ln(100/90)/k = 0.10536/4.274 × 10⁻³ = 24.6 เดือน\n\nหาก (ผิด) ใช้ linear/zero-order จะได้ 24.0 เดือนพอดี ความต่างน้อยในช่วงสลายไม่เกิน 10% ซึ่งเป็นเหตุผลที่การแยก order จากข้อมูล stability ช่วงต้นทำได้ยาก การกำหนด shelf life จริงต้องใช้ข้อมูลหลายจุดและวิเคราะห์ตาม ICH Q1E",
      w: [
        "กลับสัดส่วน (12 × ln0.95/ln0.90) ได้ค่าที่ไม่มีความหมาย",
        "เป็นเพียงเวลาที่มีข้อมูลจริง ไม่ใช่เวลาที่ถึง 90%",
        "เป็นคำตอบแบบ zero-order (ลด 5% ต่อ 12 เดือน) ไม่ตรงกับสมมติฐาน first-order",
        "ถูก — k = 4.274 × 10⁻³ month⁻¹ → t = 0.10536/k ≈ 24.6 เดือน",
        "เป็น t1/2 (0.693/k) ไม่ใช่เวลาที่ถึง 90%",
      ],
      k: "หา k จากข้อมูลจริงก่อน (k = ln(C0/C)/t) แล้วจึงหาเวลาถึง limit; first-order กับ zero-order ต่างกันน้อยในช่วง 10% แรก",
      d: "medium",
      ref: "Martin's Physical Pharmacy and Pharmaceutical Sciences 7th ed., Ch. Kinetics",
      c: [
        "k = ln(100/95)/12 = 0.05129/12 = 4.274 × 10⁻³ month⁻¹",
        "t(90%) = ln(100/90)/k = 0.10536 / 4.274 × 10⁻³",
        "t(90%) ≈ 24.6 เดือน",
      ],
    },
    {
      t: "Extractables vs leachables",
      p: "ยาน้ำรับประทานบรรจุขวด LDPE ที่พิมพ์ฉลากด้วยหมึกโดยตรงบนขวด ระหว่าง stability study พบสาร photoinitiator จากหมึกในตัวยาน้ำ ข้อใดอธิบายสารนี้และแนวทางได้ถูกต้องที่สุด",
      o: [
        "เป็น leachable คือสารที่ migrate เข้าสู่ผลิตภัณฑ์ภายใต้สภาวะเก็บจริง ต้องระบุชนิด ประเมินความปลอดภัย (เช่น เทียบ threshold) และพิจารณาเปลี่ยนวัสดุ/วิธีพิมพ์",
        "เป็น extractable จึงไม่ต้องประเมิน เพราะเกิดในห้องปฏิบัติการเท่านั้น",
        "เป็น degradation product ของตัวยา ต้องรายงานตาม ICH Q3B เท่านั้น",
        "เป็นสิ่งปนเปื้อนจุลชีพ ต้องทำ microbial limit test",
        "ไม่ใช่ปัญหาเพราะ LDPE เป็นวัสดุ food grade",
      ],
      a: 0,
      r: "Extractables คือสารที่ถูกสกัดจากวัสดุบรรจุภัณฑ์ภายใต้สภาวะรุนแรงกว่าปกติ (ตัวทำละลายแรง ความร้อน เวลานาน) เพื่อหาสารที่ 'อาจ' ออกมาได้ ส่วน leachables คือสารที่ migrate เข้าสู่ผลิตภัณฑ์จริงภายใต้สภาวะเก็บปกติหรือ accelerated โดยทั่วไป leachables เป็น subset ของ extractables\n\nสารจากหมึก/กาว/ฉลากสามารถซึมผ่านผนัง LDPE ที่บางและ permeable ได้ จึงพบได้บ่อยในขวดพลาสติก แนวทางคือระบุชนิด ประเมินด้าน toxicology (เช่น เทียบกับ AET/SCT/PDE) และแก้ที่วัสดุหรือกระบวนการพิมพ์",
      w: [
        "ถูก — สารที่พบในผลิตภัณฑ์ระหว่างเก็บจริงคือ leachable ต้องระบุและประเมินความปลอดภัย",
        "นิยามผิด — extractables มาจากการสกัดในสภาวะรุนแรง สารที่พบในผลิตภัณฑ์จริงคือ leachables",
        "สารนี้มาจากบรรจุภัณฑ์ ไม่ใช่การสลายของตัวยา",
        "สารเคมีจากหมึกไม่ใช่สิ่งปนเปื้อนจุลชีพ",
        "Food-grade ไม่ได้รับประกันว่าจะไม่มี migration ของหมึก/สารเติมแต่งเข้าสู่ผลิตภัณฑ์ยา",
      ],
      k: "Extractables = สกัดได้ในสภาวะรุนแรง (สิ่งที่อาจออกมา); Leachables = ออกมาจริงในผลิตภัณฑ์ระหว่างเก็บ ต้องประเมินความปลอดภัย",
      d: "medium",
      ref: "USP <1663> Assessment of Extractables; USP <1664> Assessment of Drug Product Leachables",
    },
    {
      t: "Storage label statement for Zone IVb",
      p: "ยาเม็ดสามัญที่ศึกษา long-term ที่ 30°C/75%RH ใน Alu-Alu blister 24 เดือน ผ่านทุกเกณฑ์ และไม่มี significant change ที่ accelerated ข้อความเก็บรักษาบนฉลากข้อใดเหมาะสมที่สุดตามแนวทาง WHO/ASEAN",
      o: [
        "Store below 30°C",
        "Store at room temperature",
        "Store at ambient conditions",
        "Store in refrigerator 2–8°C",
        "Store below 40°C",
      ],
      a: 0,
      r: "ข้อความเก็บรักษาต้องสะท้อนสภาวะที่มีข้อมูลรองรับ และต้องเป็นค่าที่ชัดเจน แนวทาง WHO (TRS 953 Annex 2) แนะนำข้อความ เช่น 'Do not store above 30°C/Store below 30°C', 'Do not store above 25°C', 'Store in a refrigerator (2°C to 8°C)', 'Protect from moisture/light' และระบุว่าไม่ควรใช้คำคลุมเครือ เช่น 'ambient' หรือ 'room temperature'\n\nเมื่อข้อมูล long-term 30°C/75%RH ผ่าน ฉลาก 'Store below 30°C' จึงเหมาะสม ไม่จำเป็นต้องแช่เย็นซึ่งเข้มเกินข้อมูล และห้ามอ้าง 40°C ซึ่งเป็นสภาวะเร่ง ไม่ใช่สภาวะเก็บจริง",
      w: [
        "ถูก — สอดคล้องกับข้อมูล long-term 30°C/75%RH และเป็นข้อความที่ชัดเจน",
        "'Room temperature' คลุมเครือ แต่ละประเทศตีความต่างกัน ไม่ควรใช้",
        "'Ambient conditions' คลุมเครือ ไม่ใช่ข้อความที่แนวทางยอมรับ",
        "ข้อมูลรองรับการเก็บที่ 30°C จึงไม่จำเป็นต้องแช่เย็น และเพิ่มภาระ cold chain โดยไม่จำเป็น",
        "40°C เป็นสภาวะ accelerated 6 เดือน ไม่ใช่ข้อมูลรองรับการเก็บตลอดอายุ",
      ],
      k: "ฉลากต้องอิงข้อมูล long-term และใช้ข้อความชัดเจน เช่น Store below 30°C; หลีกเลี่ยง room temperature/ambient",
      d: "medium",
      ref: "WHO TRS 953 Annex 2 (Stability testing of APIs and FPPs), Appendix on labelling statements; ASEAN Guideline on Stability Study of Drug Product",
    },
    {
      t: "Second-order half-life dependence on C0",
      p: "ยาสองชนิดในสูตรผสมทำปฏิกิริยากันแบบ second-order (rate = k[A][B]) โดยเริ่มที่ความเข้มข้นเท่ากัน 0.040 M และ k = 0.50 M⁻¹h⁻¹ t1/2 ของ A เป็นเท่าใด และถ้าเริ่มที่ 0.080 M ทั้งคู่ t1/2 จะเป็นเท่าใด (ตามลำดับ)",
      o: ["1.39 h; 1.39 h", "25 h; 50 h", "50 h; 25 h", "50 h; 50 h", "50 h; 100 h"],
      a: 2,
      r: "Second-order ที่ [A]0 = [B]0: 1/[A] − 1/[A]0 = kt → t1/2 = 1/(k[A]0)\n\nt1/2 = 1/(0.50 × 0.040) = 50 h และเมื่อ [A]0 = 0.080 M → t1/2 = 1/(0.50 × 0.080) = 25 h\n\nลักษณะเด่น: second-order มี t1/2 แปรผกผันกับความเข้มข้นเริ่มต้น ขณะที่ first-order t1/2 คงที่ และ zero-order t1/2 แปรผันตรงกับ C0 จึงใช้ข้อมูล t1/2 ที่ C0 ต่างกันแยก order ได้",
      w: [
        "ใช้สูตร first-order (0.693/k) ซึ่งหน่วยไม่สอดคล้องกับ k ของ second-order",
        "สลับคำตอบ — ความเข้มข้นสูงขึ้นทำให้ t1/2 สั้นลง ไม่ใช่ยาวขึ้น",
        "ถูก — t1/2 = 1/(k[A]0): 50 h ที่ 0.040 M และ 25 h ที่ 0.080 M",
        "t1/2 คงที่เป็นลักษณะของ first-order ไม่ใช่ second-order",
        "t1/2 แปรผันตรงกับ C0 เป็นลักษณะของ zero-order",
      ],
      k: "t1/2: zero-order ∝ C0, first-order คงที่, second-order ∝ 1/C0 (= 1/(kC0))",
      d: "hard",
      ref: "Martin's Physical Pharmacy and Pharmaceutical Sciences 7th ed., Ch. Kinetics",
      c: [
        "Second-order (equal C0): t1/2 = 1/(k × [A]0)",
        "[A]0 = 0.040 M: t1/2 = 1/(0.50 × 0.040) = 50 h",
        "[A]0 = 0.080 M: t1/2 = 1/(0.50 × 0.080) = 25 h",
      ],
    },
    {
      t: "pH of maximum stability from kH and kOH",
      p: "Ester ตัวหนึ่ง hydrolyze ด้วย specific acid และ specific base catalysis โดย kobs = kH[H⁺] + kOH[OH⁻] (ส่วน uncatalyzed ละได้) ที่ 25°C kH = 0.50 M⁻¹h⁻¹ และ kOH = 5.0 × 10³ M⁻¹h⁻¹ (Kw = 1.0 × 10⁻¹⁴) pH ที่ยาคงตัวสูงสุดประมาณเท่าใด",
      o: ["pH 4.0", "pH 5.0", "pH 7.0", "pH 9.0", "pH 10.0"],
      a: 1,
      r: "kobs ต่ำสุดเมื่อ d(kobs)/d[H⁺] = 0 ซึ่งเกิดเมื่อ kH[H⁺] = kOH[OH⁻] = kOH·Kw/[H⁺] → [H⁺]² = kOH·Kw/kH\n\n[H⁺]² = (5.0 × 10³ × 1.0 × 10⁻¹⁴)/0.50 = 1.0 × 10⁻¹⁰ → [H⁺] = 1.0 × 10⁻⁵ M → pH 5.0 หรือใช้ pHmin = ½[pKw + log(kH/kOH)] = ½(14 − 4) = 5\n\nเนื่องจาก kOH มักสูงกว่า kH หลายเท่า ester ส่วนใหญ่จึงมี pH ของความคงตัวสูงสุดอยู่ฝั่งกรดอ่อน (ประมาณ 3–5) ไม่ใช่ pH 7 จากนั้นจึงเลือก buffer ที่ความเข้มข้นต่ำสุดที่พอคุม pH เพื่อลด general acid–base catalysis",
      w: [
        "นำ log(kOH/kH) = 4 มาตอบตรงๆ ไม่ได้ใช้ความสัมพันธ์กับ Kw",
        "ถูก — [H⁺] = √(kOH·Kw/kH) = 10⁻⁵ M → pH 5.0",
        "pH 7 เป็นจุดกลางของน้ำ ไม่ใช่จุดที่อัตรา acid และ base catalysis เท่ากันเมื่อ kOH ≫ kH",
        "สลับ kH และ kOH ในสูตร ทำให้ได้ด้านด่าง",
        "ลืมถอดรากที่สอง (ใช้ [H⁺] = kOH·Kw/kH)",
      ],
      k: "pHmin = ½[pKw + log(kH/kOH)]; kOH ≫ kH ทำให้ ester คงตัวสุดที่ pH กรดอ่อน",
      d: "hard",
      ref: "Connors, Chemical Stability of Pharmaceuticals 2nd ed.; Martin's Physical Pharmacy 7th ed. (pH-rate profiles)",
      c: [
        "ที่ kobs ต่ำสุด: kH[H⁺] = kOH[OH⁻] = kOH·Kw/[H⁺]",
        "[H⁺]² = kOH·Kw/kH = (5.0 × 10³ × 1.0 × 10⁻¹⁴)/0.50 = 1.0 × 10⁻¹⁰",
        "[H⁺] = 1.0 × 10⁻⁵ M → pH = 5.0",
      ],
    },
    {
      t: "ICH Q1E confidence-limit shelf-life estimation",
      p: "ข้อมูล long-term 24 เดือนของ 3 batches (poolable) ที่ 30°C/75%RH ทำ linear regression ของ assay กับเวลา: เส้น mean ตัด lower spec 95.0% ที่ 40 เดือน, lower one-sided 95% confidence limit ของ mean ตัด 95.0% ที่ 30 เดือน ไม่มี significant change ที่ accelerated และข้อมูลมี variability ต่ำ shelf life สูงสุดที่ข้อมูลรองรับคือเท่าใด",
      o: [
        "24 เดือน — ห้ามเกินช่วงข้อมูลจริงทุกกรณี",
        "30 เดือน — จุดที่ lower 95% confidence limit ตัด spec และไม่เกินเพดาน extrapolation",
        "36 เดือน — เพดาน extrapolation (+12 เดือน) เมื่อข้อมูลดี",
        "40 เดือน — จุดที่เส้น mean ตัด spec",
        "48 เดือน — สองเท่าของข้อมูล long-term",
      ],
      a: 1,
      r: "ICH Q1E: สำหรับ attribute ที่ลดลงตามเวลา (assay) shelf life ประเมินจากเวลาที่ one-sided 95% confidence limit ของเส้น mean ตัด acceptance criterion ไม่ใช่จุดที่เส้น mean ตัด ซึ่งให้ความเชื่อมั่นเพียง ~50%\n\nเมื่อมีข้อมูล long-term และ accelerated ดี (ไม่มี significant change, variability ต่ำ) อนุญาตให้ extrapolate ได้ไม่เกิน 2 เท่าของข้อมูลและไม่เกินข้อมูล long-term + 12 เดือน คือเพดาน 36 เดือนในกรณีนี้ แต่ผลสถิติให้เพียง 30 เดือน จึงต้องใช้ค่าที่น้อยกว่าคือ 30 เดือน",
      w: [
        "Q1E อนุญาตให้ extrapolate ได้อย่างจำกัดเมื่อข้อมูลสนับสนุน จึงไม่ต้องหยุดที่ 24 เดือน",
        "ถูก — ใช้จุดที่ lower 95% CL ตัด spec (30 เดือน) ซึ่งต่ำกว่าเพดาน 36 เดือน",
        "36 เดือนเป็นเพียงเพดานของการ extrapolate แต่สถิติรองรับแค่ 30 เดือน",
        "เส้น mean ไม่ได้ครอบคลุมความไม่แน่นอนของการประมาณ ทำให้ shelf life ยาวเกินจริง",
        "เกินเพดาน long-term + 12 เดือน และเกินผลสถิติ",
      ],
      k: "Shelf life = เวลาที่ one-sided 95% CL ของ mean ตัด spec และต้องไม่เกินเพดาน extrapolation (≤2X และ ≤ +12 เดือน)",
      d: "hard",
      ref: "ICH Q1E Evaluation for Stability Data, Sections 2.4 and Appendix B",
    },
  ],
  // Mock Set 4 — ชุดที่ 4
  [
    {
      t: "Minimum stability data at submission (ICH)",
      p: "บริษัทยื่นทะเบียนยาเม็ดตัวยาใหม่ตาม ICH Q1A(R2) ชุดข้อมูล stability ของ drug product ขั้นต่ำ ณ วันยื่นข้อใดถูกต้อง",
      o: [
        "1 batch production scale ข้อมูล long-term 6 เดือน",
        "2 batches laboratory scale ข้อมูล accelerated 3 เดือน",
        "3 primary batches (อย่างน้อย 2 batches เป็น pilot scale) ข้อมูล long-term ≥12 เดือน และ accelerated 6 เดือน",
        "3 batches pilot scale ข้อมูล accelerated 6 เดือนเท่านั้น ไม่ต้องมี long-term",
        "3 batches production scale ข้อมูล long-term ครบ shelf life ที่เสนอ",
      ],
      a: 2,
      r: "ICH Q1A(R2) กำหนดให้ข้อมูลของ drug product มาจาก primary batches อย่างน้อย 3 batches ที่สูตรและบรรจุภัณฑ์เหมือนที่จะจำหน่าย อย่างน้อย 2 ใน 3 เป็น pilot scale ขึ้นไป (batch ที่สามเล็กกว่าได้) และ ณ วันยื่นต้องมี long-term อย่างน้อย 12 เดือน และ accelerated 6 เดือน\n\nถ้า primary batches ไม่ใช่ production scale ผู้ยื่นต้องให้คำมั่น (post-approval commitment) ทำ stability กับ production batches แรกต่อ และติดตามข้อมูลจน shelf life ที่อนุมัติ",
      w: [
        "จำนวน batch และระยะข้อมูลไม่พอตาม Q1A",
        "Laboratory scale และข้อมูล 3 เดือนไม่เพียงพอ",
        "ถูก — 3 primary batches, ≥2 pilot scale, long-term ≥12 เดือน + accelerated 6 เดือน",
        "ต้องมีข้อมูล long-term เสมอ ข้อมูลเร่งใช้ประกอบเท่านั้น",
        "ไม่จำเป็นต้องมีข้อมูลครบ shelf life ณ วันยื่น สามารถ extrapolate และ commit ต่อได้",
      ],
      k: "ICH Q1A: 3 primary batches (≥2 pilot), long-term ≥12 เดือน + accelerated 6 เดือน ณ วันยื่น พร้อม commitment",
      d: "easy",
      ref: "ICH Q1A(R2) Sections 2.2.3 and 2.2.7",
    },
    {
      t: "Induction seal liner function",
      p: "ขวด HDPE สำหรับยาเม็ดไวความชื้น ใช้ฝาเกลียว PP ร่วมกับ induction seal (aluminium foil liner ที่ถูกทำให้ร้อนด้วยสนามแม่เหล็กไฟฟ้าจนติดกับปากขวด) หน้าที่หลักของ induction seal คืออะไร",
      o: [
        "ปิดผนึกรอยต่อระหว่างฝากับปากขวดให้กันความชื้น/ออกซิเจน และเป็นหลักฐานการเปิด (tamper-evident)",
        "ทำหน้าที่เป็น desiccant ดูดความชื้นภายในขวด",
        "ทำให้ขวดทนแรงกดในการขนส่งมากขึ้น",
        "ป้องกันแสงที่ผ่านผนังขวดด้านข้าง",
        "ทำให้ฝาเปิดง่ายสำหรับผู้สูงอายุ",
      ],
      a: 0,
      r: "แม้ผนัง HDPE กันความชื้นได้ดี แต่ช่องทางรั่วสำคัญคือรอยต่อระหว่างฝาและปากขวด induction seal ใช้ foil เคลือบ polymer ที่หลอมติดกับปากขวดเมื่อผ่าน induction coil ทำให้เกิด hermetic-like seal ลดการซึมผ่านความชื้นและออกซิเจนอย่างมากจนกว่าจะเปิดใช้ และยังเป็น tamper-evident feature\n\nหลังเปิดใช้ barrier นี้หายไป จึงต้องพิจารณา in-use stability และอาจใช้ desiccant ร่วม การยืนยันประสิทธิภาพทำได้ด้วยการทดสอบ moisture permeation ตาม USP <671>",
      w: [
        "ถูก — ปิดช่องรั่วที่ฝา เพิ่ม moisture/oxygen barrier และแสดงการถูกเปิด",
        "Foil ไม่ดูดความชื้น ต้องใช้ desiccant แยกต่างหาก",
        "ไม่ได้ออกแบบเพื่อความแข็งแรงเชิงกลของขวด",
        "Seal อยู่ที่ปากขวด ไม่ครอบคลุมผนังด้านข้าง",
        "Induction seal ไม่เกี่ยวกับความสะดวกในการเปิด (และเพิ่มขั้นตอนการเปิด)",
      ],
      k: "Induction seal = ปิดรอยต่อฝา-ปากขวด กันความชื้น/O₂ + tamper-evident; หมดผลหลังเปิดใช้",
      d: "easy",
      ref: "USP <671> Containers—Performance Testing; WHO TRS 902 Annex 9",
    },
    {
      t: "Decarboxylation of aminosalicylic acid",
      p: "Para-aminosalicylic acid (PAS) ในรูป granule เมื่อสัมผัสความร้อนและความชื้นจะเปลี่ยนเป็นสีน้ำตาลและเกิดสารที่เป็นพิษมากกว่าตัวยาเดิม ปฏิกิริยาหลักและผลิตภัณฑ์ที่เกิดคืออะไร",
      o: [
        "Decarboxylation ได้ m-aminophenol และ CO₂",
        "Ester hydrolysis ได้ salicylic acid",
        "Racemization ได้ enantiomer ที่ไม่มีฤทธิ์",
        "Maillard reaction ได้ glycosylamine",
        "Polymerization ได้ dimer ที่ก่อภูมิแพ้",
      ],
      a: 0,
      r: "Aminosalicylic acid มีหมู่ carboxyl ที่ตำแหน่ง ortho ต่อ OH และมี amino ที่ช่วยดึงอิเล็กตรอนให้ ring จึงเกิด decarboxylation ได้ง่ายเมื่อโดนความร้อน/ความชื้น/กรด ได้ m-aminophenol ซึ่งเป็นพิษ และถูก oxidize ต่อเป็นสารสีน้ำตาล\n\nตำรับจึงกำหนดให้เก็บในที่เย็น กันความชื้น และไม่ใช้ผลิตภัณฑ์ที่เปลี่ยนสีเป็นน้ำตาล/ม่วง Decarboxylation เป็น pathway ที่พบน้อยกว่า hydrolysis/oxidation แต่เป็นจุดออกข้อสอบคลาสสิกของ PAS",
      w: [
        "ถูก — PAS decarboxylate เป็น m-aminophenol + CO₂ เร่งด้วยความร้อนและความชื้น",
        "PAS ไม่มีหมู่ ester จึงไม่เกิด ester hydrolysis",
        "PAS ไม่มี chiral center จึงไม่มี racemization",
        "ไม่มี reducing sugar ในโจทย์ และ pathway หลักของ PAS คือ decarboxylation",
        "Polymerization ที่ก่อภูมิแพ้เป็นลักษณะของ β-lactam เช่น ampicillin",
      ],
      k: "PAS → decarboxylation → m-aminophenol (พิษ, เปลี่ยนสี); เก็บเย็นและแห้ง",
      d: "medium",
      ref: "Connors, Chemical Stability of Pharmaceuticals 2nd ed.; Martindale: The Complete Drug Reference (Aminosalicylic acid)",
    },
    {
      t: "Trace-metal catalysis and chelating agents",
      p: "สารละลายยาที่มี phenolic group เสื่อมด้วย autoxidation แม้เติม ascorbic acid แล้ว ตรวจพบ Cu²⁺ และ Fe³⁺ ระดับ ppb จาก excipient เมื่อเติม disodium EDTA 0.05% ความคงตัวดีขึ้นชัดเจน กลไกที่อธิบายผลของ EDTA ได้ดีที่สุดคือข้อใด",
      o: [
        "EDTA จับไอออนโลหะเป็น complex ทำให้โลหะไม่สามารถเร่งขั้น initiation (สร้าง free radical และสลาย hydroperoxide) ของ autoxidation",
        "EDTA ถูก oxidize แทนตัวยาโดยตรงเหมือน reducing agent",
        "EDTA เป็น free-radical chain terminator แบบเดียวกับ BHT",
        "EDTA ปรับ pH ให้เป็นด่างจึงลด oxidation",
        "EDTA ดูดกลืนแสง UV ทำให้ไม่เกิด photo-oxidation",
      ],
      a: 0,
      r: "Autoxidation เป็น free-radical chain reaction: initiation (เกิด R• จาก RH โดยมีโลหะ แสง ความร้อน เป็นตัวเร่ง), propagation (R• + O₂ → ROO•; ROO• + RH → ROOH + R•) และ termination โลหะทรานซิชัน (Cu, Fe) เร่งทั้งการเกิด radical และการสลาย ROOH ให้เป็น radical ใหม่ผ่าน redox cycling\n\nChelating agent เช่น EDTA, citric acid จับโลหะทำให้หมดฤทธิ์ catalysis จึงเป็น 'synergist' ที่เสริม antioxidant ascorbic acid เองยังเร่ง oxidation ได้ (pro-oxidant) เมื่อมีโลหะอิสระ การใช้ EDTA ร่วมจึงสำคัญ",
      w: [
        "ถูก — EDTA จับโลหะ หยุด metal-catalyzed initiation และการสลาย hydroperoxide",
        "EDTA ไม่ใช่ reducing agent ที่ถูก oxidize แทนยา",
        "EDTA ไม่ได้ทำปฏิกิริยากับ radical เพื่อหยุด chain แบบ BHT/tocopherol",
        "Disodium EDTA มี pH ประมาณ 4–5 ไม่ได้ทำให้ด่าง และ pH สูงกลับเร่ง oxidation ของ phenol",
        "EDTA ไม่ใช่ UV absorber ที่มีนัยสำคัญ",
      ],
      k: "Chelator (EDTA, citric acid) = synergist จับโลหะที่เร่ง initiation; ใช้ร่วมกับ antioxidant",
      d: "medium",
      ref: "Aulton's Pharmaceutics 6th ed.; Handbook of Pharmaceutical Excipients 9th ed. (Edetic acid)",
    },
    {
      t: "Converting t1/2 to t90 (first-order)",
      p: "รายงานวิจัยระบุว่ายาในสารละลาย pH 6 ที่ 25°C มี t1/2 = 300 วัน โดยเสื่อมแบบ first-order ยาน้ำนี้ควรมีอายุ (t90) ประมาณเท่าใด",
      o: ["30.0 วัน", "45.6 วัน", "60.0 วัน", "150 วัน", "270 วัน"],
      a: 1,
      r: "First-order: t1/2 = 0.693/k และ t90 = 0.1054/k → t90/t1/2 = 0.1054/0.693 = 0.152\n\nt90 = 0.152 × 300 = 45.6 วัน ความผิดพลาดที่พบบ่อยคือคิดว่ายาที่ t1/2 ยาวจะมีอายุใกล้ t1/2 แต่จริงๆ เวลาที่ยาสลาย 10% เป็นเพียงราว 15% ของ t1/2 สำหรับ first-order",
      w: [
        "หาร t1/2 ด้วย 10 ไม่ใช่ความสัมพันธ์ของ first-order",
        "ถูก — t90 = 0.152 × t1/2 = 0.152 × 300 ≈ 45.6 วัน",
        "หารด้วย 5 ไม่มีพื้นฐานทาง kinetics",
        "หารด้วย 2 ผิดหลัก (ไม่ใช่ความสัมพันธ์ของ t90)",
        "คิดว่ายาสลายแบบ linear ตามสัดส่วน 0.9 × t1/2 ซึ่งผิด",
      ],
      k: "First-order: t90 = 0.152 × t1/2 (≈ 1/6.6 ของ t1/2)",
      d: "medium",
      ref: "Martin's Physical Pharmacy and Pharmaceutical Sciences 7th ed., Ch. Kinetics",
      c: [
        "k = 0.693/t1/2 = 0.693/300 = 2.31 × 10⁻³ day⁻¹",
        "t90 = 0.1054/k = 0.1054/2.31 × 10⁻³",
        "t90 ≈ 45.6 วัน (= 0.152 × 300)",
      ],
    },
    {
      t: "ICH Q1C new dosage form data package",
      p: "บริษัทเดิมที่มียาเม็ดได้รับอนุมัติแล้ว ต้องการยื่นทะเบียน dosage form ใหม่เป็น oral solution ของตัวยาเดียวกัน ตาม ICH Q1C ข้อใดถูกต้องเกี่ยวกับข้อมูล stability",
      o: [
        "ทำตามหลัก Q1A(R2) แต่ในกรณีมีเหตุผลรองรับ อาจยอมรับข้อมูล ณ วันยื่นที่ลดลง เช่น accelerated 6 เดือนและ long-term 6 เดือน",
        "ไม่ต้องทำ stability เพราะตัวยาเดิมได้รับอนุมัติแล้ว",
        "ใช้ shelf life ของยาเม็ดเดิมได้ทันทีโดยไม่ต้องมีข้อมูลใหม่",
        "ต้องมีข้อมูล long-term ครบ 36 เดือนก่อนยื่น",
        "ใช้ข้อมูล stress testing ของ API แทน stability ของผลิตภัณฑ์ได้",
      ],
      a: 0,
      r: "ICH Q1C (Stability Testing for New Dosage Forms) ครอบคลุม dosage form ใหม่ของตัวยาที่ได้รับอนุมัติแล้วโดยผู้ยื่นรายเดิม หลักการทดสอบต้องตาม Q1A(R2) แต่เนื่องจากรู้จักตัวยาดีอยู่แล้ว ในกรณีที่มีเหตุผลรองรับ ข้อมูล ณ วันยื่นอาจลดลงได้ (เช่น 6 เดือน accelerated และ 6 เดือน long-term จากการศึกษาที่ดำเนินอยู่)\n\nOral solution เป็นระบบที่ต่างจากยาเม็ด (ยาอยู่ในสารละลาย อาจเกิด hydrolysis/oxidation/interaction กับภาชนะได้มากกว่า) จึงต้องมีข้อมูล stability ของผลิตภัณฑ์ใหม่เสมอ",
      w: [
        "ถูก — Q1C ใช้หลัก Q1A แต่อนุโลมข้อมูลขั้นต่ำ ณ วันยื่นได้ เช่น 6+6 เดือน",
        "Dosage form ใหม่มี stability profile ต่างจากเดิม ต้องมีข้อมูลของผลิตภัณฑ์ใหม่",
        "Shelf life ใช้ข้ามรูปแบบยาไม่ได้ เพราะกลไกและอัตราการเสื่อมต่างกัน",
        "ไม่จำเป็นต้องมีข้อมูลครบ shelf life ณ วันยื่น",
        "Stress testing ของ API ใช้หา degradation pathway ไม่ใช่ใช้แทนข้อมูลผลิตภัณฑ์",
      ],
      k: "ICH Q1C: dosage form ใหม่ ทำตาม Q1A แต่อาจยื่นด้วย 6 เดือน accelerated + 6 เดือน long-term หากมีเหตุผลรองรับ",
      d: "medium",
      ref: "ICH Q1C Stability Testing for New Dosage Forms",
    },
    {
      t: "Preservative loss by sorption/permeation into LDPE",
      p: "ยาหยอดจมูก (non-sterile) ใช้ chlorobutanol 0.5% เป็น preservative บรรจุในขวด LDPE หลังเก็บ 6 เดือนพบ chlorobutanol ลดเหลือ 0.2% ขณะที่ตัวยาสำคัญคงที่ สาเหตุและการแก้ไขที่เหมาะสมที่สุดคือข้อใด",
      o: [
        "Chlorobutanol ระเหยง่ายและ sorb/permeate ผ่าน LDPE; ควรเปลี่ยนภาชนะเป็นแก้วหรือเปลี่ยน preservative และทดสอบ preservative efficacy ตลอดอายุ",
        "Chlorobutanol เกิด Maillard reaction กับตัวยา",
        "Chlorobutanol ถูกจุลชีพในขวดใช้จนหมด",
        "เป็นความคลาดเคลื่อนของการวิเคราะห์ ให้ตรวจซ้ำจนได้ผล 0.5%",
        "เพิ่มความเข้มข้นเริ่มต้นเป็น 5% เพื่อชดเชยการสูญเสีย",
      ],
      a: 0,
      r: "สารที่ไม่มีขั้ว/ระเหยได้ เช่น chlorobutanol, benzyl alcohol, phenylethyl alcohol และสารแต่งกลิ่น สามารถถูกดูดซับเข้าเนื้อพลาสติก (sorption) และซึมผ่านผนัง polyolefin (permeation) โดยเฉพาะ LDPE ซึ่งเป็น barrier ต่ำ ทำให้ความเข้มข้นของ preservative ลดลงจนต่ำกว่าระดับที่มีประสิทธิภาพ\n\nแนวทาง: เลือกภาชนะที่ไม่ดูดซับ (แก้ว) หรือ preservative ที่เข้ากับภาชนะ, ตั้ง spec ของ preservative content ใน stability protocol และทดสอบ antimicrobial effectiveness ที่ระดับต่ำสุดตลอดอายุ",
      w: [
        "ถูก — chlorobutanol สูญเสียผ่าน sorption/permeation ใน LDPE ต้องแก้ที่ภาชนะ/preservative และยืนยันประสิทธิภาพ",
        "Chlorobutanol ไม่ใช่ reducing sugar และไม่ทำ Maillard",
        "Preservative ไม่ได้ถูกใช้หมดจนลดลงมากขนาดนั้นในผลิตภัณฑ์ปิดสนิท สาเหตุหลักคือการสูญเสียสู่ภาชนะ",
        "Testing into compliance ขัดหลัก GMP และผลสอดคล้องกับกลไกที่รู้จักดี",
        "การเพิ่ม 10 เท่าเกินขีดความปลอดภัย/ความละลาย และไม่แก้ต้นเหตุ",
      ],
      k: "Preservative ระเหย/ไม่มีขั้ว (chlorobutanol, benzyl alcohol) สูญเสียสู่ LDPE ได้ → ติดตาม preservative content + AET ตลอดอายุ",
      d: "medium",
      ref: "Handbook of Pharmaceutical Excipients 9th ed. (Chlorobutanol: incompatibilities); Aulton's Pharmaceutics 6th ed., Ch. Packaging",
    },
    {
      t: "Desiccant quantity sizing",
      p: "ขวด HDPE + induction seal ของยาเม็ดไวความชื้น วัด moisture ingress ได้ 0.40 mg/วัน ที่ 30°C/75%RH ต้องการให้ desiccant (silica gel) ดูดน้ำที่ซึมเข้าได้ตลอด 24 เดือน (730 วัน) silica gel ดูดน้ำได้ 10% w/w ที่ RH ภายในที่ต้องการ และใช้ safety factor 1.5 ต้องใช้ silica gel อย่างน้อยกี่กรัม",
      o: ["0.29 g", "0.44 g", "2.92 g", "4.38 g", "43.8 g"],
      a: 3,
      r: "ปริมาณน้ำที่ซึมเข้าตลอดอายุ = 0.40 mg/วัน × 730 วัน = 292 mg เมื่อคูณ safety factor 1.5 = 438 mg\n\nSilica gel 1 g ดูดน้ำได้ 0.10 g (10% w/w) → ต้องใช้ 0.438/0.10 = 4.38 g ในทางปฏิบัติต้องคิดน้ำที่มาจากตัวเม็ดยาและ headspace ตั้งต้น และเลือก desiccant ตาม isotherm (silica gel ดูดได้มากที่ RH สูง, molecular sieve ดูดแรงที่ RH ต่ำ) แล้วยืนยันด้วย stability data จริง",
      w: [
        "ใช้ capacity 100% และไม่มี safety factor (ใช้ 0.292 g)",
        "ใช้ capacity 100% แม้คิด safety factor แล้ว — silica gel ดูดน้ำได้แค่ 10% ของน้ำหนัก",
        "ไม่ได้คูณ safety factor 1.5",
        "ถูก — 0.40 × 730 × 1.5 / 0.10 = 4,380 mg ≈ 4.38 g",
        "ใช้ capacity 1% แทน 10% ทำให้มากเกินจริง 10 เท่า",
      ],
      k: "Desiccant (g) = ingress rate × เวลา × safety factor ÷ capacity (g น้ำ/g desiccant)",
      d: "hard",
      ref: "USP <671> Containers—Performance Testing; USP <670> Auxiliary Packaging Components",
      c: [
        "Water ingress = 0.40 mg/วัน × 730 วัน = 292 mg",
        "With safety factor: 292 × 1.5 = 438 mg = 0.438 g",
        "Silica gel needed = 0.438 g ÷ 0.10 g/g = 4.38 g",
      ],
    },
    {
      t: "ICH Q1E batch poolability test",
      p: "ข้อมูล assay vs time ของ 3 batches ทำ ANCOVA ตาม ICH Q1E ได้ p-value ของการทดสอบความเท่ากันของ slopes = 0.12 ข้อสรุปและวิธีกำหนด shelf life ที่ถูกต้องคือข้อใด",
      o: [
        "ไม่ควร pool เพราะ p < 0.25; ประเมิน shelf life แยกแต่ละ batch และใช้ค่าที่สั้นที่สุด",
        "Pool ได้เพราะ p > 0.05 ตามเกณฑ์สถิติทั่วไป",
        "Pool ได้เสมอเพราะทุก batch ผ่าน spec",
        "ใช้ค่าเฉลี่ย shelf life ของสาม batches",
        "ใช้ batch ที่ shelf life ยาวที่สุดเป็นตัวแทน",
      ],
      a: 0,
      r: "ICH Q1E ใช้ระดับนัยสำคัญ 0.25 (ไม่ใช่ 0.05) สำหรับทดสอบความเท่ากันของ slopes และ intercepts เพื่อเพิ่ม power ในการตรวจพบความต่างระหว่าง batch ถ้า p ของ slopes < 0.25 แสดงว่า slopes ต่างกัน ไม่ควร pool\n\nเมื่อ pool ไม่ได้ ให้ประเมิน shelf life ของแต่ละ batch ด้วย 95% confidence limit แล้วใช้ค่าที่สั้นที่สุด (worst case) เป็น shelf life ของผลิตภัณฑ์ หาก slopes เท่ากันแต่ intercepts ต่าง อาจใช้ common slope กับ intercept แยก และยังใช้ batch ที่ worst case",
      w: [
        "ถูก — p = 0.12 < 0.25 → slopes ต่างกัน ไม่ pool และใช้ batch ที่สั้นที่สุด",
        "Q1E กำหนด 0.25 ไม่ใช่ 0.05 เพื่อเป็นการทดสอบที่ conservative ต่อการ pool",
        "การผ่าน spec ไม่ใช่เกณฑ์ poolability",
        "ค่าเฉลี่ยจะให้ shelf life ยาวเกินจริงสำหรับ batch ที่เสื่อมเร็ว",
        "ใช้ batch ที่ดีที่สุดขัดกับหลัก worst case",
      ],
      k: "Q1E poolability ใช้ α = 0.25; pool ไม่ได้ → shelf life = batch ที่สั้นที่สุด",
      d: "hard",
      ref: "ICH Q1E Evaluation for Stability Data, Appendix B.2",
    },
    {
      t: "Moisture-induced recrystallization of amorphous dispersion",
      p: "ยาเม็ด amorphous solid dispersion (ยา + PVP-VA) มี Tg (แห้ง) 85°C หลังเก็บใน HDPE ไม่มี desiccant ที่ 30°C/75%RH เม็ดดูดน้ำ 6% และ Tg วัดได้ลดเหลือ 38°C ต่อมาพบ crystalline peak และ dissolution ลดลง คำอธิบายและการแก้ไขที่ดีที่สุดคือข้อใด",
      o: [
        "น้ำเป็น plasticizer ลด Tg ใกล้อุณหภูมิเก็บ ทำให้ molecular mobility สูงและตกผลึก; ควรใช้ pack กันชื้นสูง/desiccant และพิจารณา polymer ที่ hygroscopic น้อยกว่า",
        "น้ำทำให้ยา hydrolyze เป็น degradant ที่ตกตะกอน",
        "Tg ลดลงทำให้ยาละลายเร็วขึ้น ไม่น่าเกี่ยวกับ dissolution ที่ลดลง",
        "ความชื้นทำให้ PVP-VA cross-link เหมือน gelatin",
        "ควรเก็บที่ 40°C เพื่อไล่ความชื้นออกจากเม็ด",
      ],
      a: 0,
      r: "Amorphous form มีพลังงานอิสระสูงและอยากกลับเป็น crystal ความคงตัวทางกายภาพขึ้นกับ molecular mobility ซึ่งต่ำเมื่อเก็บต่ำกว่า Tg มากพอ (แนวทางทั่วไปคือ ~Tg − 50 K) น้ำมี Tg ต่ำมาก (≈ −135°C) จึงเป็น plasticizer ที่ลด Tg ของระบบตามสมการ Gordon–Taylor\n\nเมื่อ Tg ลดเหลือ 38°C ซึ่งใกล้อุณหภูมิเก็บ 30°C mobility สูงพอให้เกิด nucleation/crystal growth ทำให้สูญเสีย solubility advantage และ dissolution ลดลง การแก้: Alu-Alu/ขวด + desiccant, ฉลาก protect from moisture, เลือก polymer ที่ Tg สูง/hygroscopic น้อย (เช่น HPMCAS) และติดตาม XRPD/DSC ใน stability",
      w: [
        "ถูก — moisture plasticization → Tg ใกล้อุณหภูมิเก็บ → recrystallization; แก้ด้วยการกันชื้นและเลือก polymer",
        "โจทย์ชี้การเปลี่ยนทางกายภาพ (crystalline peak) ไม่ใช่ degradant ทางเคมี",
        "Crystallization ทำให้สูญเสีย supersaturation advantage จึงทำให้ dissolution ลดลง",
        "PVP-VA ไม่ได้ cross-link แบบ gelatin-aldehyde",
        "อุณหภูมิสูงยิ่งเพิ่ม mobility และเร่ง crystallization",
      ],
      k: "Amorphous: น้ำ = plasticizer ลด Tg; เก็บให้ต่ำกว่า Tg มาก (~Tg − 50 K) และกันความชื้น",
      d: "hard",
      ref: "Hancock BC, Zografi G. J Pharm Sci 1997;86:1–12; Aulton's Pharmaceutics 6th ed., Ch. Solid-state properties",
    },
  ],
  // Mock Set 5 — ชุดที่ 5
  [
    {
      t: "Amber glass light protection",
      p: "ยาน้ำเชื่อมที่ไวต่อแสงบรรจุในขวดแก้วใสพบสีเปลี่ยนเมื่อวางบนชั้นร้านยา การเปลี่ยนเป็นขวดแก้วสีชา (amber glass) ช่วยป้องกันได้ด้วยหลักการใด",
      o: [
        "แก้วสีชาดูดกลืน UV และแสงช่วงคลื่นสั้น (ประมาณ 290–450 nm) ซึ่งเป็นช่วงที่ยาส่วนใหญ่ดูดกลืนและเกิด photolysis",
        "แก้วสีชากันความชื้นได้ดีกว่าแก้วใส",
        "แก้วสีชาปล่อย antioxidant ออกมาในยา",
        "แก้วสีชาสะท้อนความร้อนทำให้ยาเย็นลง",
        "แก้วสีชาดูดซับออกซิเจนจาก headspace",
      ],
      a: 0,
      r: "Photodegradation เกิดเมื่อยาดูดกลืนพลังงานแสงที่ความยาวคลื่นที่ตรงกับ chromophore ส่วนใหญ่อยู่ในช่วง UV และ visible ช่วงคลื่นสั้น แก้วสีชามีสาร (เช่น iron oxide/sulfur) ที่ดูดกลืนแสงในช่วงนี้\n\nUSP <671> และ USP <660> กำหนดการทดสอบ light transmission ของ light-resistant container ในช่วง 290–450 nm แก้วใสและสีชามี moisture barrier เท่ากัน (แก้วไม่ให้ความชื้นผ่าน) ดังนั้นผลต่างอยู่ที่การกันแสงเท่านั้น และฉลากควรระบุ 'Protect from light' หรือ 'Keep in the outer carton'",
      w: [
        "ถูก — แก้วสีชาลดการส่งผ่านแสงในช่วง UV/คลื่นสั้นที่ก่อ photolysis",
        "แก้วทุกชนิดเป็น moisture barrier ที่สมบูรณ์อยู่แล้ว สีไม่ได้เพิ่มการกันความชื้น",
        "แก้วสีชาไม่ได้ปล่อย antioxidant",
        "ไม่ได้ป้องกันด้วยการสะท้อนความร้อน",
        "แก้วไม่ดูดซับออกซิเจน",
      ],
      k: "Amber glass กันแสง UV/คลื่นสั้น (290–450 nm ตาม USP light transmission test) ไม่ได้เพิ่ม moisture/O₂ barrier",
      d: "easy",
      ref: "USP <671> Containers—Performance Testing (Light transmission); USP <660> Containers—Glass",
    },
    {
      t: "Oxygen absorber sachet",
      p: "ผลิตภัณฑ์ softgel ที่ไวต่อ oxidation บรรจุในขวดแก้วพร้อมซองเล็กที่บรรจุผงเหล็ก (iron-based sachet) ซองนี้ทำหน้าที่อะไร",
      o: [
        "เป็น oxygen absorber ที่ทำปฏิกิริยากับ O₂ ใน headspace ลดออกซิเจนในขวดลงมาก",
        "เป็น desiccant ที่ดูดความชื้นด้วย silica",
        "เป็น antioxidant ที่ละลายเข้าไปใน softgel",
        "เป็นตัวบ่งชี้อุณหภูมิระหว่างขนส่ง",
        "เป็นตัวดูดกลืนแสงแทนขวดสีชา",
      ],
      a: 0,
      r: "Oxygen absorber (oxygen scavenger) ชนิดผงเหล็กอาศัย oxidation ของเหล็ก (Fe → iron oxide) ดึง O₂ จาก headspace ลงได้ต่ำมาก ใช้กับยาที่ไว oxidation เช่น softgel ที่มี unsaturated oil หรือวิตามิน\n\nเงื่อนไขสำคัญ: ภาชนะต้องเป็น oxygen barrier ที่ดี (แก้ว, Alu-Alu, ขวดพร้อม induction seal) มิฉะนั้นออกซิเจนจะซึมเข้าใหม่จน absorber หมดความจุ และชนิดผงเหล็กต้องการความชื้นในการทำงาน จึงต้องเลือกให้เข้ากับระดับความชื้นของผลิตภัณฑ์",
      w: [
        "ถูก — iron-based absorber จับ O₂ ใน headspace ผ่านการ oxidize ของเหล็ก",
        "Desiccant (silica gel, molecular sieve) ดูดน้ำ ไม่ใช่ผงเหล็ก",
        "Absorber ไม่ได้สัมผัสหรือละลายเข้าในตัวยา",
        "Temperature indicator เป็นอุปกรณ์คนละประเภท",
        "ผงเหล็กในซองไม่ได้ทำหน้าที่กันแสง",
      ],
      k: "Oxygen absorber (ผงเหล็ก) ลด O₂ ใน headspace ใช้ได้ผลเมื่อภาชนะเป็น O₂ barrier ที่ดี",
      d: "easy",
      ref: "USP <670> Auxiliary Packaging Components; WHO TRS 902 Annex 9",
    },
    {
      t: "Reconstituted antibiotic suspension stability",
      p: "Amoxicillin จำหน่ายเป็น dry powder for oral suspension ให้ผสมน้ำก่อนจ่าย แทนที่จะผลิตเป็น suspension พร้อมใช้ เหตุผลหลักและคำแนะนำที่สอดคล้องคือข้อใด",
      o: [
        "β-lactam ring ถูก hydrolyze ในน้ำ ทำให้อายุหลังผสมสั้น จึงต้องระบุอายุหลังผสม (ตามข้อมูล in-use) และสภาวะเก็บ เช่น ในตู้เย็น บนฉลาก",
        "ผงแห้งช่วยให้ amoxicillin ละลายน้ำได้มากขึ้น",
        "Amoxicillin ไวต่อแสงอย่างเดียว ผงแห้งจึงกันแสงได้ดีกว่า",
        "เพื่อลดต้นทุนการขนส่งเท่านั้น ไม่เกี่ยวกับความคงตัว",
        "เพื่อป้องกัน Maillard reaction กับน้ำตาลในผงแห้ง",
      ],
      a: 0,
      r: "β-lactam ring ของ penicillins มีความเครียดของวงสูง จึงถูก hydrolyze ในน้ำได้ง่าย (เร่งด้วยกรด ด่าง ความร้อน) ได้ penicilloic acid ที่ไม่มีฤทธิ์ ในรูปผงแห้งคงตัวได้หลายปี แต่หลังผสมน้ำมีอายุเพียงช่วงสั้น\n\nอายุหลังผสม (in-use/reconstituted shelf life) และสภาวะเก็บ (เช่น ในตู้เย็นหรืออุณหภูมิที่กำหนด) ต้องกำหนดจากการศึกษา reconstituted stability ภายใต้สภาวะที่ผู้ป่วยใช้จริง และระบุบนฉลาก/เอกสารกำกับ พร้อมให้ทิ้งยาที่เหลือ เภสัชกรควรเขียนวันผสมและวันที่ต้องทิ้งบนขวด",
      w: [
        "ถูก — β-lactam hydrolysis ในน้ำจำกัดอายุหลังผสม จึงต้องมีข้อมูล reconstituted stability และฉลากสภาวะเก็บ/อายุหลังผสม",
        "ไม่เกี่ยวกับการเพิ่ม solubility (amoxicillin ใน suspension ส่วนใหญ่ไม่ละลายอยู่แล้ว)",
        "ปัญหาหลักคือ hydrolysis ไม่ใช่แสง",
        "เหตุผลหลักคือความคงตัว ไม่ใช่ต้นทุน",
        "ไม่ใช่ประเด็นหลัก amoxicillin ในผงแห้งไม่เสื่อมเร็วด้วย Maillard",
      ],
      k: "ยาที่ hydrolyze ง่าย (β-lactam) → dry powder for reconstitution + กำหนดอายุ/สภาวะเก็บหลังผสมจากข้อมูล in-use",
      d: "medium",
      ref: "Connors, Chemical Stability of Pharmaceuticals 2nd ed. (Penicillins); WHO TRS 953 Annex 2 (In-use stability)",
    },
    {
      t: "Forced degradation and stability-indicating concept",
      p: "บริษัทใช้ UV spectrophotometry วัด assay ของยาน้ำระหว่าง stability ผลคงที่ 100% ตลอด 12 เดือน แต่เมื่อตรวจด้วย stability-indicating method พบตัวยาเหลือ 91% และมี degradant หลายชนิด เหตุการณ์นี้สะท้อนหลักการใดมากที่สุด",
      o: [
        "วิธี UV เดิมไม่ใช่ stability-indicating เพราะ degradant ดูดกลืนแสงใกล้เคียงตัวยา ต้องพิสูจน์ specificity ด้วย forced degradation ก่อนใช้ใน stability study",
        "วิธี UV ถูกต้องกว่าเพราะง่ายกว่า ให้ใช้ผล UV ต่อไป",
        "Forced degradation มีไว้เพื่อหา shelf life โดยตรง ไม่เกี่ยวกับวิธีวิเคราะห์",
        "Degradant ไม่มีผลต่อคุณภาพหากผลรวมยังเป็น 100%",
        "ควรเฉลี่ยผล UV และ stability-indicating method เข้าด้วยกัน",
      ],
      a: 0,
      r: "Stability-indicating method ต้องวัดตัวยาได้อย่างจำเพาะ (specificity) โดยไม่ถูกรบกวนจาก degradant, impurity และ excipient ถ้า degradant ดูดกลืนแสงใกล้เคียงตัวยา วิธีที่ไม่มีการแยก (เช่น UV โดยตรง) จะให้ assay สูงเกินจริงและซ่อนการเสื่อม\n\nICH Q1A(R2) ระบุว่า stress testing (forced degradation) ของ API ช่วยระบุ degradation products, pathway, intrinsic stability และใช้พิสูจน์ความเป็น stability-indicating ของวิธีวิเคราะห์ (ภาวะทั่วไป: กรด, ด่าง, oxidation, ความร้อน, ความชื้น, แสง โดยนิยมให้เสื่อมราว 5–20%) จึงต้องทำก่อนเริ่ม formal stability",
      w: [
        "ถูก — วิธีที่ไม่ specific ซ่อน degradation ต้องพิสูจน์ด้วย forced degradation ว่าเป็น stability-indicating",
        "ความง่ายไม่ชดเชยการขาด specificity ผล UV ไม่สะท้อนปริมาณยาที่เหลือจริง",
        "Forced degradation ไม่ได้ใช้กำหนด shelf life โดยตรง แต่ใช้เข้าใจ pathway และพิสูจน์วิธีวิเคราะห์",
        "Degradant ต้องควบคุมตาม spec (ICH Q3B) และ assay จริงลดลงแล้ว",
        "การเฉลี่ยผลจากวิธีที่ไม่ specific กับวิธีที่ถูกต้องไม่มีหลักวิชาการรองรับ",
      ],
      k: "Stability study ต้องใช้ stability-indicating method ที่พิสูจน์ specificity ด้วย forced degradation (5–20% degradation)",
      d: "medium",
      ref: "ICH Q1A(R2) Section 2.1.2 Stress testing; ICH Q2(R2) Specificity",
    },
    {
      t: "Reaction order from half-life vs initial concentration",
      p: "ศึกษาการเสื่อมของยาในสารละลายที่ความเข้มข้นเริ่มต้นต่างกัน: C0 = 0.10 M มี t1/2 = 40 h, C0 = 0.050 M มี t1/2 = 80 h, C0 = 0.025 M มี t1/2 = 160 h ข้อใดสรุป order และค่า k ได้ถูกต้อง",
      o: [
        "Second-order, k = 0.25 M⁻¹h⁻¹",
        "First-order, k = 0.0173 h⁻¹",
        "Zero-order, k = 1.25 × 10⁻³ M h⁻¹",
        "Second-order, k = 4.0 M⁻¹h⁻¹",
        "First-order, k = 0.0087 h⁻¹",
      ],
      a: 0,
      r: "เมื่อ C0 ลดลงครึ่งหนึ่ง t1/2 เพิ่มขึ้นสองเท่า แสดงว่า t1/2 ∝ 1/C0 ซึ่งเป็นลักษณะของ second-order (t1/2 = 1/(kC0))\n\nk = 1/(t1/2 × C0) = 1/(40 × 0.10) = 0.25 M⁻¹h⁻¹ (ตรวจสอบ: 1/(80 × 0.050) = 0.25 และ 1/(160 × 0.025) = 0.25 คงที่)\n\nถ้าเป็น first-order t1/2 ต้องคงที่ทุก C0 และถ้าเป็น zero-order t1/2 ต้องลดลงเมื่อ C0 ลดลง",
      w: [
        "ถูก — t1/2 แปรผกผันกับ C0 → second-order และ k = 1/(t1/2·C0) = 0.25 M⁻¹h⁻¹",
        "ใช้ 0.693/40 โดยไม่ดูว่า t1/2 เปลี่ยนตาม C0 ซึ่งขัดกับ first-order",
        "Zero-order t1/2 = C0/2k ต้องสั้นลงเมื่อ C0 ลดลง ตรงข้ามกับข้อมูล",
        "Order ถูกแต่คำนวณกลับด้าน (t1/2 × C0 = 4)",
        "ใช้ 0.693/80 และ first-order ไม่สอดคล้องกับข้อมูล",
      ],
      k: "แยก order จาก t1/2: คงที่ = first; ∝ C0 = zero; ∝ 1/C0 = second",
      d: "medium",
      ref: "Martin's Physical Pharmacy and Pharmaceutical Sciences 7th ed., Ch. Kinetics (Determination of order)",
      c: [
        "C0 ลดครึ่ง (0.10 → 0.050 M) t1/2 เพิ่มสองเท่า (40 → 80 h) → t1/2 ∝ 1/C0 → second-order",
        "k = 1/(t1/2 × C0) = 1/(40 h × 0.10 M) = 0.25 M⁻¹h⁻¹",
        "ตรวจสอบ: 1/(160 × 0.025) = 0.25 M⁻¹h⁻¹",
      ],
    },
    {
      t: "Ea from Arrhenius plot slope",
      p: "จากข้อมูล stress ที่หลายอุณหภูมิ ได้กราฟ ln k กับ 1/T (K⁻¹) เป็นเส้นตรงที่มี slope = −1.00 × 10⁴ K (R = 8.314 J/mol·K) Activation energy มีค่าประมาณเท่าใด",
      o: ["1.20 kJ/mol", "19.9 kJ/mol", "83.1 kJ/mol", "191 kJ/mol", "831 kJ/mol"],
      a: 2,
      r: "Arrhenius: ln k = ln A − Ea/(RT) ดังนั้นกราฟ ln k vs 1/T มี slope = −Ea/R\n\nEa = −slope × R = 1.00 × 10⁴ × 8.314 = 83,140 J/mol ≈ 83.1 kJ/mol\n\nถ้าเป็นกราฟ log k (ฐาน 10) slope = −Ea/(2.303R) ต้องคูณ 2.303 เพิ่ม การอ่านแกนให้ถูกจึงสำคัญ จาก intercept (ln A) และ Ea สามารถคำนวณ k ที่ 25°C หรือ 30°C เพื่อประมาณ shelf life ได้ (ภายใต้สมมติฐานว่ากลไกไม่เปลี่ยน)",
      w: [
        "หาร slope ด้วย R แทนการคูณ",
        "ใช้ R = 1.987 cal/mol·K ได้ 19.9 kcal/mol แต่รายงานเป็น kJ ผิดหน่วย",
        "ถูก — Ea = −slope × R = 10⁴ × 8.314 J/mol ≈ 83.1 kJ/mol",
        "คูณ 2.303 เพิ่มซึ่งใช้เฉพาะกราฟ log10 k ไม่ใช่ ln k",
        "เลื่อนหน่วย/ทศนิยมผิด 10 เท่า",
      ],
      k: "ln k vs 1/T: slope = −Ea/R; log k vs 1/T: slope = −Ea/(2.303R)",
      d: "medium",
      ref: "Martin's Physical Pharmacy and Pharmaceutical Sciences 7th ed., Ch. Kinetics (Arrhenius plot)",
      c: [
        "Slope = −Ea/R",
        "Ea = −(−1.00 × 10⁴ K) × 8.314 J/mol·K = 83,140 J/mol",
        "Ea ≈ 83.1 kJ/mol",
      ],
    },
    {
      t: "Accelerated study for refrigerated products",
      p: "ยาน้ำที่กำหนดให้เก็บในตู้เย็น ทำ long-term ที่ 5°C ± 3°C และ accelerated ที่ 25°C ± 2°C/60%RH ± 5%RH พบ significant change ตั้งแต่เดือนที่ 2 ของ accelerated ข้อใดถูกต้องตาม ICH Q1A(R2)",
      o: [
        "กำหนด shelf life จากข้อมูล long-term และต้องอภิปรายผลของ excursion ระยะสั้นนอกฉลาก (เช่น ระหว่างขนส่ง) ซึ่งอาจสนับสนุนด้วยการทดสอบ 1 batch ช่วงสั้นกว่า 3 เดือนที่ตรวจถี่ขึ้น",
        "ผลที่ 25°C ไม่เกี่ยวข้องเลยกับผลิตภัณฑ์แช่เย็น จึงไม่ต้องรายงาน",
        "ต้องเปลี่ยน accelerated เป็น 40°C/75%RH ตามยาทั่วไป",
        "สามารถ extrapolate shelf life ได้ 2 เท่าของข้อมูล long-term",
        "ต้องเปลี่ยนฉลากเป็น 'Store below 25°C' เพื่อให้สอดคล้องกับ accelerated",
      ],
      a: 0,
      r: "สำหรับยาที่เก็บในตู้เย็น ICH Q1A(R2) ใช้ long-term 5°C ± 3°C และ accelerated 25°C ± 2°C/60%RH ± 5%RH 6 เดือน หาก significant change เกิดระหว่าง 3–6 เดือน ให้กำหนด shelf life จากข้อมูล long-term ที่มีจริง\n\nหาก significant change เกิดภายใน 3 เดือนแรก ต้องอภิปรายผลของการออกนอกสภาวะฉลากช่วงสั้น (เช่น ระหว่างขนส่งหรือการใช้) ซึ่งอาจสนับสนุนด้วยการทดสอบเพิ่มเติม 1 batch ในช่วงสั้นกว่า 3 เดือนด้วยความถี่ที่ถี่กว่าปกติ และไม่ควรทำ accelerated ต่อจนครบ 6 เดือนถ้าเกิด significant change แล้ว",
      w: [
        "ถูก — อิงข้อมูล long-term และอภิปราย/ทดสอบผลของ excursion ช่วงสั้นตาม Q1A",
        "ผลที่ 25°C ใช้ประเมินความเสี่ยงของ excursion จึงต้องรายงานและอภิปราย",
        "40°C/75%RH ไม่ใช่ accelerated condition ของยาแช่เย็น",
        "เมื่อมี significant change ที่ accelerated ไม่ควร extrapolate เกินข้อมูล long-term",
        "ข้อมูลแสดงว่าไม่คงตัวที่ 25°C การฉลากเช่นนั้นไม่มีข้อมูลรองรับ",
      ],
      k: "ยาตู้เย็น: long-term 5°C, accelerated 25°C/60%RH; significant change < 3 เดือน → อภิปราย/ทดสอบ excursion ระยะสั้น",
      d: "medium",
      ref: "ICH Q1A(R2) Section 2.2.7.4 Drug products intended for storage in a refrigerator",
    },
    {
      t: "PVDC vs Aclar for oxygen-sensitive tablets",
      p: "ยาเม็ดที่ไวต่อ oxidation มาก แต่ไวความชื้นปานกลาง ฝ่ายการตลาดต้องการ blister ใสให้เห็นเม็ดยา (จึงใช้ Alu-Alu ไม่ได้) ตัวเลือก forming film ใดเหมาะสมที่สุดเมื่อพิจารณาทั้ง oxygen และ moisture barrier",
      o: [
        "PVC/PVDC (PVDC coating หนา) เพราะ PVDC ให้ทั้ง oxygen barrier ที่ดีมากและ moisture barrier ระดับดี",
        "PVC/Aclar (PCTFE) เพราะเป็น oxygen barrier ที่ดีที่สุดในฟิล์มใส",
        "PVC เดี่ยวหนา 250 µm เพราะความหนาชดเชย barrier ได้",
        "PP เพราะกันออกซิเจนได้ดีกว่า PVDC",
        "PET/PE laminate เพราะ PE เป็น oxygen barrier ที่ดีที่สุด",
      ],
      a: 0,
      r: "ฟิล์มใสสำหรับ blister มีจุดเด่นต่างกัน: PCTFE (Aclar) ให้ moisture barrier ดีที่สุดในกลุ่มฟิล์มใส แต่ oxygen barrier ปานกลาง ส่วน PVDC ให้ทั้ง oxygen barrier ที่ดีมากและ moisture barrier ระดับดี (เพิ่มขึ้นตาม coating weight เช่น 40, 60, 90 g/m²) ขณะที่ PVC และ polyolefin (PP, PE) มี oxygen permeability สูง\n\nสำหรับยาที่ปัจจัยหลักคือออกซิเจนและต้องการความใส PVC/PVDC coating หนาจึงเหมาะกว่า PVC/Aclar ถ้าปัจจัยหลักคือความชื้นสูงมาก Aclar จะได้เปรียบ และถ้าไวทั้งสองอย่างมากต้องยอมใช้ Alu-Alu หรือ pack เสริม (aluminium pouch/oxygen absorber) แล้วยืนยันด้วย stability data",
      w: [
        "ถูก — PVDC เด่น oxygen barrier และกันความชื้นได้ดี เหมาะกับยาไว O₂ ที่ต้องการ blister ใส",
        "Aclar เด่นด้าน moisture barrier แต่ oxygen barrier ด้อยกว่า PVDC",
        "PVC มี barrier ต่ำ เพิ่มความหนาช่วยได้จำกัดและยังด้อยกว่า PVDC มาก",
        "PP กันความชื้นได้ดีกว่า PVC แต่ oxygen permeability สูง",
        "PE เป็น oxygen barrier ที่แย่ ไม่ใช่ดีที่สุด",
      ],
      k: "ฟิล์มใส: Aclar = moisture barrier สูงสุด; PVDC = oxygen barrier ดีมาก + moisture ดี; PVC/PP/PE = O₂ barrier ต่ำ",
      d: "hard",
      ref: "Pilchik R. Pharmaceutical blister packaging, Part I. Pharm Technol 2000;24(11):68–78; WHO TRS 902 Annex 9",
    },
    {
      t: "Ampicillin polymerization in concentrated solution",
      p: "ทีมพัฒนาพบว่าสารละลาย ampicillin sodium ความเข้มข้นสูงที่ตั้งทิ้งไว้มี high-molecular-weight species เพิ่มขึ้นตามความเข้มข้นอย่างไม่เป็นสัดส่วน ซึ่งมีรายงานสัมพันธ์กับการแพ้ยา กลไกใดอธิบายได้ดีที่สุด",
      o: [
        "Aminolysis: หมู่ α-amino ใน side chain ของโมเลกุลหนึ่งโจมตี β-lactam ของอีกโมเลกุล เกิด dimer/polymer อัตราจึงเพิ่มตามความเข้มข้นมากกว่าแบบ first-order",
        "Hydrolysis ของ β-lactam โดยน้ำ ซึ่งเป็น pseudo-first-order ไม่ขึ้นกับความเข้มข้นของยา",
        "Oxidation ของ thioether ใน thiazolidine ring เป็น sulfoxide",
        "Racemization ของ side chain เป็น L-ampicillin",
        "Maillard reaction กับ dextrose ในสารละลาย",
      ],
      a: 0,
      r: "Aminopenicillins (ampicillin, amoxicillin) มีหมู่ amino อิสระที่เป็น nucleophile โจมตี carbonyl ของ β-lactam ของอีกโมเลกุลได้ (intermolecular aminolysis) ได้ dimer, trimer และ polymer ปฏิกิริยานี้เป็น bimolecular ระหว่างโมเลกุลยาด้วยกัน อัตราจึงเพิ่มเร็วกว่าเชิงเส้นเมื่อความเข้มข้นสูงขึ้น (second-order ต่อยา) ต่างจาก hydrolysis โดยน้ำที่เป็น pseudo-first-order\n\nPolymer ที่เกิดมีรายงานว่าเป็น antigenic determinant ของ penicillin allergy จึงควรเตรียมสารละลายความเข้มข้นสูงก่อนใช้เท่านั้น และหลีกเลี่ยงการตั้งทิ้ง Dextrose ก็เร่งการเสื่อมของ ampicillin ได้ (ผ่านกลไก catalysis) แต่ไม่อธิบายการเพิ่มตามความเข้มข้นยาแบบนี้",
      w: [
        "ถูก — intermolecular aminolysis ระหว่างโมเลกุลยา ทำให้เกิด polymer และอัตราขึ้นกับความเข้มข้นสูง",
        "Hydrolysis โดยน้ำเป็น pseudo-first-order สัดส่วนการสลายไม่ขึ้นกับความเข้มข้นยา และไม่ได้ high-MW species",
        "Sulfoxide เป็น degradant ได้ แต่ไม่ให้ polymer และไม่ขึ้นกับความเข้มข้นแบบนี้",
        "Epimerization ไม่ทำให้เกิด high-molecular-weight species",
        "โจทย์ไม่มี dextrose และ Maillard ไม่อธิบายการเกิด polymer ของยาเอง",
      ],
      k: "Aminopenicillin เข้มข้นสูง → polymerization (aminolysis ระหว่างโมเลกุล) อัตราขึ้นกับความเข้มข้น และเกี่ยวกับการแพ้ยา",
      d: "hard",
      ref: "Bundgaard H. Polymerization of penicillins. Acta Pharm Suec 1976; Connors, Chemical Stability of Pharmaceuticals 2nd ed.",
    },
    {
      t: "Tablet hardening on storage",
      p: "ยาเม็ด wet granulation (binder: povidone, filler มี sucrose) ตอกที่ความชื้น granule 4% บรรจุ PVC blister หลังเก็บที่ 30°C/75%RH 6 เดือน hardness เพิ่มจาก 8 เป็น 15 kp และ disintegration time เพิ่มจาก 4 เป็น 22 นาที ขณะที่ assay ปกติ สาเหตุและการแก้ที่ดีที่สุดคือข้อใด",
      o: [
        "ความชื้นทำให้ส่วนที่ละลายได้ (sucrose/povidone) ละลายและตกผลึก/แข็งตัวใหม่เป็น solid bridge ระหว่างอนุภาค; ควบคุม LOD ของ granule, ลด excipient ที่ละลายน้ำ/hygroscopic และใช้ pack กันความชื้น",
        "ตัวยาเกิด hydrolysis ทำให้เม็ดแข็งขึ้น",
        "Blister PVC ปล่อย plasticizer เข้าไปในเม็ด ทำให้เม็ดแข็ง",
        "เกิด gelatin cross-linking ในเม็ดยา",
        "เป็นผลปกติที่ไม่ต้องแก้ไข เพราะ assay ยังผ่าน",
      ],
      a: 0,
      r: "Tablet hardening ระหว่างเก็บเป็นปัญหา physical stability ที่พบบ่อยกับเม็ดที่มี soluble/hygroscopic excipient และความชื้นสูง ความชื้นที่เข้าออกตามสภาวะแวดล้อมละลายส่วนที่ละลายน้ำได้ที่ผิวอนุภาค เมื่อน้ำระเหยหรือกระจายตัวใหม่จะเกิด solid bridge (recrystallization/การแข็งตัวของ binder) ทำให้ hardness เพิ่ม และ disintegration/dissolution ช้าลง\n\nการแก้: กำหนด LOD ของ granule ให้เหมาะสม, ลดหรือเปลี่ยน excipient ที่ละลายน้ำ/hygroscopic, เลือก pack ที่กันความชื้นดีกว่า PVC และเพิ่ม hardness, disintegration, dissolution ใน stability protocol เพราะ assay ไม่สะท้อนปัญหานี้",
      w: [
        "ถูก — moisture-mediated solid bridging ทำให้เม็ดแข็งขึ้นและแตกตัวช้า แก้ที่ความชื้นของ granule, สูตร และบรรจุภัณฑ์",
        "Assay ปกติ ไม่มีหลักฐานการเสื่อมทางเคมี และ hydrolysis ไม่ทำให้เม็ดแข็ง",
        "Rigid PVC สำหรับ blister ไม่ได้ปล่อย plasticizer ในระดับที่ทำให้เม็ดแข็ง",
        "สูตรไม่มี gelatin capsule ปรากฏการณ์นี้เป็นของเม็ดอัด",
        "Disintegration/dissolution ที่ช้าลงกระทบ bioavailability และอาจไม่ผ่าน spec ต้องแก้ไข",
      ],
      k: "Tablet hardening: ความชื้น + soluble excipient → solid bridge → DT/dissolution ช้า; ติดตาม physical tests ใน stability",
      d: "hard",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Tablets and compaction; Lieberman, Pharmaceutical Dosage Forms: Tablets Vol. 1",
    },
  ],
];
