import type { Ip1MockDomainContent } from "@/lib/ip1-mock/types";

export const STABILITY: Ip1MockDomainContent = [
  // Mock Set 1 — ชุดที่ 1
  [
    {
      t: "Ester hydrolysis susceptibility",
      p: "ทีมพัฒนาสูตรได้รับตัวยา 5 ชนิดเพื่อทำ oral solution ในน้ำ (pH 6–7) หากพิจารณาเฉพาะหมู่ฟังก์ชันที่ไวต่อ hydrolysis ตัวยาใดมีแนวโน้มเสื่อมสลายด้วย hydrolysis เร็วที่สุด",
      o: [
        "Acetylsalicylic acid (มี phenolic ester)",
        "Paracetamol (มี anilide/amide)",
        "Phenobarbital (มี imide ในวง barbiturate)",
        "Ibuprofen (มี carboxylic acid)",
        "Chlorpheniramine (มี tertiary amine)",
      ],
      a: 0,
      r: "Hydrolysis เกิดได้ง่ายที่หมู่ carbonyl ที่ถูก nucleophile (น้ำ/OH⁻) โจมตี ลำดับความไวโดยทั่วไปคือ ester > amide/imide ส่วน carboxylic acid และ amine ไม่ hydrolyze\n\nAspirin เป็น phenyl ester ซึ่ง leaving group (phenoxide ของ salicylate) เสถียรด้วย resonance จึงยิ่ง hydrolyze ง่ายกว่า alkyl ester ทั่วไป ได้ salicylic acid + acetic acid (กลิ่นน้ำส้มสายชู) ด้วยเหตุนี้ aspirin จึงแทบไม่ทำเป็น aqueous solution สำเร็จรูป แต่ทำเป็นเม็ดแห้งหรือ effervescent ที่ละลายก่อนใช้",
      w: [
        "ถูก — phenolic ester ของ aspirin เป็นหมู่ที่ hydrolyze ง่ายที่สุดในตัวเลือก ได้ salicylic acid + acetic acid",
        "Amide ของ paracetamol เสถียรกว่า ester มาก เพราะ nitrogen ให้ resonance กับ carbonyl ทำให้ carbonyl carbon electrophilic น้อยลง hydrolysis เกิดช้าที่ pH ใกล้กลาง",
        "Barbiturate ring hydrolyze ได้ แต่เด่นในสภาวะด่างแรง ที่ pH 6–7 ช้ากว่า aspirin มาก",
        "Carboxylic acid ไม่มี leaving group ให้ hydrolysis จึงไม่ใช่ pathway หลักของ ibuprofen",
        "Tertiary amine ไม่ hydrolyze; ปัญหาของ amine มักเป็น oxidation (N-oxide) มากกว่า",
      ],
      k: "ความไวต่อ hydrolysis: ester (โดยเฉพาะ phenyl ester) > lactam/imide > amide; acid/amine ไม่ hydrolyze",
      d: "easy",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Chemical stability of drugs; Connors, Chemical Stability of Pharmaceuticals 2nd ed.",
    },
    {
      t: "Antioxidant phase selection",
      p: "ครีม o/w มีวิตามิน A palmitate (ละลายในน้ำมัน ไวต่อ oxidation) อยู่ในวัฏภาคน้ำมัน การเลือก antioxidant ข้อใดเหมาะสมที่สุด",
      o: [
        "เติม BHT หรือ α-tocopherol ลงในวัฏภาคน้ำมัน",
        "เติม sodium metabisulfite ลงในวัฏภาคน้ำ",
        "เติม ascorbic acid ลงในวัฏภาคน้ำเท่านั้น",
        "เติม disodium EDTA แทน antioxidant ทั้งหมด",
        "เติม sodium chloride เพื่อลด oxygen solubility",
      ],
      a: 0,
      r: "Antioxidant ต้องอยู่วัฏภาคเดียวกับตัวยาที่ต้องการปกป้อง Vitamin A palmitate อยู่ในน้ำมัน จึงต้องใช้ oil-soluble antioxidant ชนิด free-radical chain terminator เช่น BHT, BHA, α-tocopherol หรือ ascorbyl palmitate\n\nWater-soluble antioxidant (ascorbic acid, sodium metabisulfite, sodium sulfite) ใช้กับยาในวัฏภาคน้ำ ส่วน EDTA เป็น synergist ที่จับโลหะ ช่วยเสริมแต่ไม่หยุด radical chain ด้วยตัวเอง",
      w: [
        "ถูก — BHT/tocopherol ละลายในน้ำมัน อยู่ใกล้ตัวยาและหยุด radical chain ได้โดยตรง",
        "Metabisulfite เป็น water-soluble reducing agent อยู่คนละวัฏภาคกับ vitamin A palmitate จึงปกป้องได้น้อย",
        "Ascorbic acid ละลายน้ำ ไม่เข้าไปในหยดน้ำมัน (ถ้าต้องการ ascorbate ในน้ำมันต้องใช้ ascorbyl palmitate)",
        "EDTA เป็นเพียง chelator/synergist ลด metal catalysis แต่ไม่ใช่ chain-breaking antioxidant ใช้แทนทั้งหมดไม่ได้",
        "การเติมเกลือไม่ใช่กลยุทธ์ป้องกัน oxidation ที่ใช้จริงและไม่ได้ปกป้องยาในวัฏภาคน้ำมัน",
      ],
      k: "เลือก antioxidant ให้อยู่วัฏภาคเดียวกับยา: น้ำมัน → BHT/BHA/tocopherol; น้ำ → ascorbic acid/sulfites",
      d: "easy",
      ref: "Handbook of Pharmaceutical Excipients 9th ed.; Aulton's Pharmaceutics 6th ed.",
    },
    {
      t: "First-order t90 calculation",
      p: "Oral solution ตัวหนึ่งเสื่อมสลายแบบ first-order ที่ 25°C ด้วย k = 2.1 × 10⁻³ day⁻¹ เวลาที่ตัวยาเหลือ 90% ของเริ่มต้น (t90) ประมาณเท่าใด",
      o: ["5.0 วัน", "47.6 วัน", "50.2 วัน", "330 วัน", "1,096 วัน"],
      a: 2,
      r: "สำหรับ first-order: ln(C0/C) = kt เมื่อ C = 0.9C0 จะได้ t90 = ln(1/0.9)/k = 0.1054/k\n\nt90 = 0.1054 / 0.0021 = 50.2 วัน ซึ่งไม่ขึ้นกับความเข้มข้นเริ่มต้น ต่างจาก zero-order ที่ t90 = 0.1C0/k0\n\nตัวเลือกอื่นเกิดจากความสับสนสูตร: 0.693/k คือ t1/2 และ 2.303/k คือเวลาที่เหลือเพียง 10%",
      w: [
        "ผิดหลักทศนิยม (เลื่อนตำแหน่ง) ไม่สอดคล้องกับ 0.1054/0.0021",
        "ใช้ 0.1/k ซึ่งเป็นการคิดแบบประมาณผิดสูตร (คล้าย zero-order) ได้ 47.6 วัน",
        "ถูก — t90 = 0.1054/k = 0.1054/0.0021 = 50.2 วัน",
        "เป็น t1/2 = 0.693/k ไม่ใช่ t90",
        "เป็น ln10/k คือเวลาที่ยาเหลือ 10% (สลายไป 90%)",
      ],
      k: "First-order: t90 = 0.105/k, t1/2 = 0.693/k (ทั้งคู่ไม่ขึ้นกับ C0)",
      d: "medium",
      ref: "Martin's Physical Pharmacy and Pharmaceutical Sciences 7th ed., Ch. Kinetics",
      c: [
        "First-order: t90 = ln(100/90)/k = 0.1054/k",
        "t90 = 0.1054 / (2.1 × 10⁻³ day⁻¹)",
        "t90 = 50.2 วัน",
      ],
    },
    {
      t: "Q10 refrigerated product at room temperature",
      p: "ยาน้ำชนิดหนึ่งมี t90 = 24 เดือนเมื่อเก็บที่ 5°C ร้านยาเก็บผิดไว้ที่ 25°C ตลอดเวลา หากประมาณด้วย Q10 = 3 ตัวยาจะมี t90 ที่ 25°C ประมาณเท่าใด",
      o: ["0.9 เดือน", "2.7 เดือน", "4.0 เดือน", "8.0 เดือน", "12.0 เดือน"],
      a: 1,
      r: "Q10 คือสัดส่วนที่อัตราการเสื่อมเพิ่มขึ้นเมื่ออุณหภูมิเพิ่ม 10°C ใช้ได้กับ shelf life ในลักษณะ t90(T2) = t90(T1) / Q10^(ΔT/10)\n\nΔT = 25 − 5 = 20°C → Q10^2 = 3² = 9 → t90 = 24/9 = 2.7 เดือน\n\nQ10 = 2, 3, 4 สอดคล้องกับ Ea ประมาณ 50, 80, 105 kJ/mol ตามลำดับ (Connors) ใช้เป็นการประมาณคร่าวๆ เมื่อไม่มีข้อมูล Arrhenius จริง",
      w: [
        "ใช้ Q10^3 = 27 (นับ ΔT ผิดเป็น 30°C) ได้ 24/27 ≈ 0.9 เดือน",
        "ถูก — ΔT = 20°C → Q10^(20/10) = 9 → 24/9 ≈ 2.7 เดือน",
        "คูณ Q10 × 2 = 6 แทนการยกกำลัง ได้ 4 เดือน ซึ่งผิดหลัก Q10",
        "หารด้วย Q10 เพียงครั้งเดียว (คิดเหมือน ΔT = 10°C)",
        "หารด้วย 2 คือใช้ Q10 = 2 เพียงขั้นเดียว ไม่ตรงกับเงื่อนไขโจทย์",
      ],
      k: "t90(T2) = t90(T1)/Q10^(ΔT/10); ยาตู้เย็นที่หลุดไปอยู่ 25°C อายุลดลงหลายเท่า",
      d: "medium",
      ref: "Connors KA, Amidon GL, Stella VJ. Chemical Stability of Pharmaceuticals 2nd ed.",
      c: [
        "ΔT = 25 − 5 = 20°C",
        "Factor = Q10^(ΔT/10) = 3^2 = 9",
        "t90(25°C) = 24 เดือน / 9 = 2.67 ≈ 2.7 เดือน",
      ],
    },
    {
      t: "Maillard reaction with lactose",
      p: "ยาเม็ด Drug X (มีหมู่ primary amine) ใช้ lactose monohydrate เป็น filler หลัง accelerated 40°C/75%RH 3 เดือน เม็ดยาเปลี่ยนเป็นสีเหลือง-น้ำตาล และพบ degradant ใหม่ที่ไม่พบใน API เดี่ยว การแก้ไขสูตรข้อใดตรงสาเหตุที่สุด",
      o: [
        "เปลี่ยน filler เป็น microcrystalline cellulose หรือ mannitol ซึ่งไม่ใช่ reducing sugar",
        "เปลี่ยนเป็น anhydrous lactose เพื่อลดความชื้นและยังคงใช้ lactose ได้ตามเดิม",
        "เพิ่ม BHT ในสูตรเพื่อป้องกันการเปลี่ยนสี",
        "เพิ่มปริมาณ magnesium stearate เพื่อเคลือบผิวอนุภาค",
        "บรรจุใน amber glass เพื่อป้องกันแสง",
      ],
      a: 0,
      r: "Lactose เป็น reducing sugar (มี hemiacetal เปิดเป็น aldehyde ได้) ทำปฏิกิริยากับ primary/secondary amine ได้ glycosylamine → Amadori rearrangement → สารสีน้ำตาล (Maillard reaction) ความชื้นและอุณหภูมิเร่งปฏิกิริยา ตัวอย่างที่รายงาน เช่น fluoxetine, amlodipine, metoclopramide\n\nการแก้ที่ต้นเหตุคือตัด reducing sugar ออก ใช้ MCC, dibasic calcium phosphate หรือ mannitol (sugar alcohol ไม่มี carbonyl) แทน anhydrous lactose ลดความชื้นได้บ้างแต่ยังเป็น reducing sugar",
      w: [
        "ถูก — ตัด reducing sugar ออกจากสูตร จึงไม่มี aldehyde ให้ทำปฏิกิริยากับ amine",
        "Anhydrous lactose ยังเป็น reducing sugar ลดความเร็วได้บ้างแต่ไม่แก้สาเหตุ โดยเฉพาะในเขต Zone IVb",
        "BHT เป็น radical scavenger สำหรับ oxidation ไม่ได้ยับยั้ง Maillard condensation",
        "Magnesium stearate ไม่ป้องกันการสัมผัสระหว่าง amine กับ lactose อย่างมีนัยสำคัญ และอาจเพิ่มปัญหาอื่น",
        "การเปลี่ยนสีครั้งนี้เกิดจากปฏิกิริยาเคมีระหว่างยากับ excipient ไม่ใช่ photolysis",
      ],
      k: "Primary/secondary amine + reducing sugar (lactose, glucose) → Maillard browning; ใช้ MCC/DCP/mannitol แทน",
      d: "medium",
      ref: "Handbook of Pharmaceutical Excipients 9th ed. (Lactose monograph: incompatibilities)",
    },
    {
      t: "Significant change criteria (drug product)",
      p: "ผลศึกษา accelerated 40°C/75%RH ที่ 6 เดือนของยาเม็ด (assay spec 95.0–105.0%) ข้อใดถือเป็น significant change ตาม ICH Q1A(R2)",
      o: [
        "Assay ลดลงจาก 101.8% เป็น 96.5% แม้ยังอยู่ใน specification",
        "Assay ลดลงจาก 100.4% เป็น 97.0%",
        "Total degradant เพิ่มจาก 0.2% เป็น 0.6% โดย spec ≤ 1.0%",
        "Dissolution ลดลงจาก 92% เป็น 85% ที่ 30 นาที โดย spec Q = 80%",
        "Hardness ลดลงเล็กน้อยแต่ friability ยังผ่านเกณฑ์",
      ],
      a: 0,
      r: "ICH Q1A(R2) นิยาม significant change ของ drug product ได้แก่ (1) assay เปลี่ยนจากค่าเริ่มต้น 5% (2) degradation product ใดเกิน acceptance criterion (3) ไม่ผ่านเกณฑ์ appearance/physical/functionality (4) pH ไม่ผ่าน (5) dissolution ไม่ผ่านใน 12 dosage units\n\nจุดสำคัญคือเกณฑ์ assay วัดจาก 'การเปลี่ยนแปลงจากค่าเริ่มต้น' ไม่ใช่แค่ผ่าน/ไม่ผ่าน spec: 101.8 → 96.5 = ลดลง 5.3% จึงเป็น significant change ทั้งที่ยังอยู่ใน spec ผลคือต้องพิจารณา intermediate (ถ้ามี) และจำกัดการ extrapolate shelf life",
      w: [
        "ถูก — ลดลง 5.3% จากค่าเริ่มต้น เกินเกณฑ์ 5% แม้ยังผ่าน spec",
        "ลดลง 3.4% ยังไม่ถึง 5% และอยู่ใน spec",
        "Degradant เพิ่มขึ้นแต่ยังไม่เกิน acceptance criterion จึงไม่เข้าเกณฑ์",
        "Dissolution ยังผ่าน Q จึงไม่ใช่ significant change (ต้องเป็นการ fail เกณฑ์)",
        "การเปลี่ยนแปลงทางกายภาพที่ยังผ่าน acceptance criteria ไม่ถือเป็น significant change",
      ],
      k: "Significant change: assay เปลี่ยน ≥5% จากค่าเริ่มต้น หรือ attribute ใด fail spec (degradant, appearance, pH, dissolution)",
      d: "medium",
      ref: "ICH Q1A(R2) Stability Testing of New Drug Substances and Products, Section 2.2.7",
    },
    {
      t: "Alu-Alu cold-form blister for hygroscopic tablet",
      p: "ยาเม็ด effervescent-like ที่ดูดความชื้นสูงมาก (assay และ dissolution เปลี่ยนเมื่อดูดน้ำ > 1%) จะวางจำหน่ายในประเทศไทย (Zone IVb) ต้องการบรรจุแบบ unit-dose blister ข้อใดเหมาะสมที่สุด",
      o: [
        "Cold-form Alu-Alu (OPA/Al/PVC + lidding aluminium foil)",
        "PVC 250 µm + aluminium lidding foil",
        "PVC/PVDC 40 g/m² + aluminium lidding foil",
        "PET blister ใส + paper/PET lidding",
        "PP blister + aluminium lidding foil",
      ],
      a: 0,
      r: "ความสามารถกันความชื้น (MVTR ต่ำ → ดี) เรียงคร่าวๆ: PVC < PP ≈ PVC/PVDC < PVC/Aclar (PCTFE) < Alu-Alu (cold form) ซึ่ง aluminium foil หนาที่ไม่มีรูเข็มให้ MVTR เกือบเป็นศูนย์และกันแสงได้ด้วย\n\nสำหรับยาไวความชื้นสูงในสภาวะ 30°C/75%RH Alu-Alu เป็นตัวเลือกที่ปลอดภัยที่สุด ข้อเสียคือ cavity ใหญ่ขึ้น (ขึ้นรูปเย็นยืดได้น้อย) ต้นทุนสูง และมองไม่เห็นเม็ดยา การเลือกต้องยืนยันด้วย stability data ใน pack จริงที่ 30°C/75%RH",
      w: [
        "ถูก — Alu-Alu ให้ barrier ต่อความชื้น แสง และออกซิเจนสูงสุดในกลุ่ม blister",
        "PVC เดี่ยวมี MVTR สูงที่สุด ไม่เหมาะกับยาไวความชื้นใน Zone IVb",
        "PVC/PVDC ดีกว่า PVC มากแต่ยังมีการซึมผ่านความชื้นได้ ไม่พอสำหรับยาที่ไวสูงมาก",
        "PET และ paper lidding ไม่ใช่ moisture barrier ระดับสูง",
        "PP กันความชื้นได้ดีกว่า PVC แต่ยังด้อยกว่า Alu-Alu อย่างชัดเจน",
      ],
      k: "Moisture barrier ของ blister: PVC < PVC/PVDC < PVC/Aclar < Alu-Alu; ยาไวความชื้นสูงใน Zone IVb → Alu-Alu",
      d: "medium",
      ref: "WHO TRS 902 Annex 9 Guidelines on packaging for pharmaceutical products; Aulton's Pharmaceutics 6th ed., Ch. Packaging",
    },
    {
      t: "Arrhenius prediction of t90 at 25°C",
      p: "การศึกษา stress พบว่ายาในสารละลายเสื่อมแบบ first-order ที่ 60°C ด้วย k = 0.020 day⁻¹ และมี Ea = 80 kJ/mol (R = 8.314 J/mol·K) ถ้ากลไกไม่เปลี่ยน t90 ที่ 25°C ประมาณเท่าใด",
      o: ["5.3 วัน", "59.6 วัน", "156 วัน", "1,029 วัน", "3,417 วัน"],
      a: 2,
      r: "Arrhenius: ln(k2/k1) = −(Ea/R)(1/T2 − 1/T1) โดยต้องใช้ Kelvin\n\nT1 = 333.15 K, T2 = 298.15 K → 1/T2 − 1/T1 = 3.522 × 10⁻⁴ K⁻¹; Ea/R = 80,000/8.314 = 9,622 K → ln(k25/k60) = −3.39 → k25/k60 = 0.0337 → k25 = 6.74 × 10⁻⁴ day⁻¹\n\nt90 = 0.1054/k25 = 156 วัน (≈5 เดือน) ข้อควรระวัง: การทำนายจากอุณหภูมิสูงใช้ได้เมื่อกลไกและลำดับปฏิกิริยาไม่เปลี่ยนในช่วงอุณหภูมิ และไม่มีการเปลี่ยนสถานะ/ความชื้นมาเกี่ยวข้อง",
      w: [
        "เป็น t90 ที่ 60°C (0.1054/0.020) ยังไม่ได้แปลงไป 25°C",
        "ใช้กฎ Q10 = 2 (2^3.5 ≈ 11.3) ซึ่งประเมินต่ำกว่าเมื่อ Ea จริง 80 kJ/mol (เทียบ Q10 ≈ 2.7–3)",
        "ถูก — k25 = 6.74 × 10⁻⁴ day⁻¹ → t90 = 0.1054/k25 ≈ 156 วัน",
        "เป็น t1/2 ที่ 25°C (0.693/k25) ไม่ใช่ t90",
        "เป็นเวลาที่ยาเหลือ 10% (2.303/k25) ไม่ใช่ t90",
      ],
      k: "Arrhenius ใช้ Kelvin เสมอ: ln(k2/k1) = −Ea/R (1/T2 − 1/T1) แล้ว t90 = 0.105/k",
      d: "hard",
      ref: "Martin's Physical Pharmacy and Pharmaceutical Sciences 7th ed.; Connors, Chemical Stability of Pharmaceuticals",
      c: [
        "T1 = 60 + 273.15 = 333.15 K; T2 = 25 + 273.15 = 298.15 K",
        "1/T2 − 1/T1 = 0.0033540 − 0.0030017 = 3.522 × 10⁻⁴ K⁻¹",
        "Ea/R = 80,000 / 8.314 = 9,622 K",
        "ln(k25/k60) = −9,622 × 3.522 × 10⁻⁴ = −3.39 → k25/k60 = 0.0337",
        "k25 = 0.020 × 0.0337 = 6.74 × 10⁻⁴ day⁻¹",
        "t90 = 0.1054 / 6.74 × 10⁻⁴ = 156 วัน",
      ],
    },
    {
      t: "No intermediate condition when long-term is 30°C",
      p: "บริษัทยื่นทะเบียนยาเม็ดในอาเซียน ทำ long-term ที่ 30°C/75%RH และ accelerated ที่ 40°C/75%RH พบ significant change ที่ accelerated เดือนที่ 6 ขั้นตอนข้อใดสอดคล้องกับ ICH Q1A(R2)/ASEAN guideline มากที่สุด",
      o: [
        "ไม่มี intermediate condition ให้ทำ; กำหนด shelf life จากข้อมูล long-term จริงที่ 30°C/75%RH โดยไม่ extrapolate จากข้อมูลเร่ง",
        "ต้องเพิ่ม intermediate 30°C/65%RH 12 เดือนก่อนกำหนด shelf life",
        "ต้องเพิ่ม intermediate 25°C/60%RH เพื่อเทียบกับเขต Zone II",
        "ใช้ข้อมูล accelerated คำนวณ shelf life ด้วย Arrhenius แทน long-term",
        "ผลที่ accelerated ไม่มีผลต่อการกำหนด shelf life เพราะ long-term ยังผ่าน",
      ],
      a: 0,
      r: "ICH Q1A(R2) ระบุว่า intermediate condition (30°C/65%RH) ใช้เมื่อ long-term คือ 25°C/60%RH และเกิด significant change ที่ accelerated แต่ถ้า long-term เป็น 30°C/65%RH หรือ 30°C/75%RH (ตาม Zone IVb ที่อาเซียนใช้) จะไม่มี intermediate condition\n\nเมื่อเกิด significant change ที่ accelerated ICH Q1E ระบุว่าไม่ควรอาศัยการ extrapolate เกินข้อมูล long-term ดังนั้น shelf life ต้องอิงข้อมูล real-time ที่ 30°C/75%RH และผล accelerated ยังใช้ประเมินผลของ excursion ระยะสั้นระหว่างขนส่งได้",
      w: [
        "ถูก — long-term 30°C/75%RH ไม่มี intermediate และ significant change ที่ accelerated ทำให้ต้องอิงข้อมูล long-term จริง",
        "30°C/65%RH เป็นสภาวะที่อ่อนกว่า long-term 30°C/75%RH ที่ใช้อยู่แล้ว จึงไม่ให้ข้อมูลเพิ่ม",
        "25°C/60%RH เป็น long-term ของ Zone I/II ไม่ใช่ intermediate และไม่แทนสภาวะในอาเซียน",
        "Significant change ที่ accelerated บ่งว่ากลไกอาจไม่ linear ตาม Arrhenius การทำนายจากข้อมูลเร่งจึงไม่น่าเชื่อถือ",
        "Significant change ที่ accelerated มีผลจำกัดการ extrapolate และต้องอภิปรายในเอกสาร ไม่ใช่ละเลย",
      ],
      k: "Long-term 30°C/65% หรือ 30°C/75% → ไม่มี intermediate; significant change ที่ accelerated → ห้าม extrapolate เกินข้อมูล long-term",
      d: "hard",
      ref: "ICH Q1A(R2) Section 2.2.7; ICH Q1E; ASEAN Guideline on Stability Study of Drug Product (R1)",
    },
    {
      t: "Hydrate conversion of carbamazepine on storage",
      p: "ยาเม็ด carbamazepine (anhydrous form III) ที่บรรจุใน PVC blister หลังเก็บที่ 30°C/75%RH 6 เดือน พบ dissolution ลดลงมาก และ XRPD พบ peak ใหม่ แม้ assay และ degradant ปกติ คำอธิบายใดน่าจะเป็นสาเหตุที่สุด",
      o: [
        "เกิด solution-mediated/solid-state conversion เป็น carbamazepine dihydrate ซึ่งละลายช้ากว่า เพราะความชื้นซึมผ่าน PVC",
        "เกิด hydrolysis ของ carbamazepine เป็น iminostilbene ทำให้ dissolution ต่ำ",
        "ตัวยาเกิด photolysis จากแสงผ่าน PVC ใส",
        "เกิด Maillard reaction ระหว่าง carbamazepine กับ excipient",
        "ตัวยาเปลี่ยนเป็น amorphous ทำให้ละลายช้าลง",
      ],
      a: 0,
      r: "การเปลี่ยน solid form ระหว่างเก็บเป็นปัญหา physical stability ที่ assay ไม่ช่วยตรวจจับ Carbamazepine anhydrous ดูดความชื้นแล้วเปลี่ยนเป็น dihydrate ซึ่งเป็นรูปแบบที่เสถียรในน้ำและมี solubility/dissolution rate ต่ำกว่า มีรายงานความล้มเหลวทางคลินิกจากเม็ดที่เก็บในที่ชื้น\n\nหลักฐานคือ XRPD peak ใหม่ (lattice เปลี่ยน) ขณะที่เคมีไม่เปลี่ยน การแก้: pack กันความชื้น (Alu-Alu/ขวด + desiccant), ฉลาก 'Protect from moisture' และเพิ่ม dissolution/solid-form monitoring ใน stability protocol",
      w: [
        "ถูก — anhydrous → dihydrate ในที่ชื้นทำให้ dissolution ลดลง สอดคล้องกับ XRPD ที่เปลี่ยน ขณะ assay ปกติ",
        "ถ้าเป็น chemical degradation ต้องพบ assay ลดและ degradant เพิ่ม ซึ่งโจทย์ระบุว่าปกติ",
        "Photolysis เป็นการเปลี่ยนเคมี ต้องเห็น degradant ไม่ใช่ XRPD peak ใหม่โดย assay ปกติ",
        "Carbamazepine ไม่มีหมู่ amine อิสระแบบ primary/secondary ที่ทำ Maillard และ assay ไม่ลด",
        "Amorphous จะละลายเร็วขึ้นและให้ halo ใน XRPD ไม่ใช่ peak ใหม่",
      ],
      k: "Polymorph/hydrate conversion ระหว่างเก็บ → dissolution เปลี่ยนโดย assay ปกติ; ต้องติดตามด้วย XRPD/dissolution และใช้ pack กันชื้น",
      d: "hard",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Solid-state properties; Brittain HG, Polymorphism in Pharmaceutical Solids 2nd ed.",
    },
  ],
  // Mock Set 2 — ชุดที่ 2
  [
    {
      t: "Retest period vs shelf life",
      p: "ข้อใดอธิบายความแตกต่างระหว่าง retest period ของ API (drug substance) กับ shelf life ของ drug product ได้ถูกต้องที่สุด",
      o: [
        "API ที่ครบ retest period อาจตรวจซ้ำแล้วนำไปใช้ผลิตได้ทันทีหากผ่าน spec แต่ drug product ที่เกิน shelf life ห้ามจำหน่ายแม้ตรวจซ้ำผ่าน",
        "Retest period และ shelf life มีความหมายเดียวกัน ใช้แทนกันได้ทั้ง API และ drug product",
        "Drug product ที่ครบ shelf life สามารถตรวจซ้ำและขยายวันหมดอายุทีละ lot ได้",
        "Retest period ใช้เฉพาะยาชีววัตถุ ส่วน API สังเคราะห์ใช้ shelf life เท่านั้น",
        "API ที่ครบ retest period ต้องทำลายทิ้งทุกกรณี",
      ],
      a: 0,
      r: "ICH Q1A(R2) นิยาม retest period ว่าเป็นช่วงเวลาที่ API คาดว่าจะยังอยู่ใน spec หากเก็บตามที่กำหนด เมื่อครบแล้วต้องตรวจซ้ำก่อนใช้ ถ้าผ่านสามารถใช้ผลิตได้ทันที (ควรใช้ภายในระยะหนึ่งหลังตรวจ)\n\nShelf life (expiration dating period) ของ drug product คือระยะเวลาที่ผลิตภัณฑ์ต้องอยู่ใน spec ตลอดอายุ วันหมดอายุบนฉลากเป็นข้อจำกัดเด็ดขาด ไม่สามารถตรวจซ้ำแล้วขยายรายล็อตได้ สำหรับ API บางชนิด เช่น ชีววัตถุ/antibiotic ที่ไม่เสถียร อาจกำหนดเป็น shelf life แทน retest period",
      w: [
        "ถูก — retest period ของ API ตรวจซ้ำแล้วใช้ต่อได้ ส่วน shelf life ของ drug product เป็นวันหมดอายุเด็ดขาด",
        "สองคำนี้มีความหมายและผลทางปฏิบัติต่างกันชัดเจนตาม ICH Q1A(R2)",
        "การขยาย shelf life ต้องผ่าน variation/ข้อมูล stability ไม่ใช่ตรวจซ้ำทีละ lot หลังหมดอายุ",
        "กลับกัน — API ทั่วไปใช้ retest period ส่วนชีววัตถุหลายชนิดใช้ shelf life",
        "API ที่ครบ retest period สามารถตรวจซ้ำและใช้ได้ถ้าผ่าน spec ไม่จำเป็นต้องทำลาย",
      ],
      k: "API: retest period (ตรวจซ้ำแล้วใช้ได้); Drug product: shelf life (หมดอายุแล้วห้ามใช้)",
      d: "easy",
      ref: "ICH Q1A(R2) Glossary; ICH Q7 Section 11.6",
    },
    {
      t: "Inert gas headspace replacement",
      p: "ยาน้ำรับประทานที่ไวต่อ oxidation บรรจุขวดแก้ว พบ assay ลดเร็วโดยเฉพาะขวดที่มี headspace มาก มาตรการด้านกระบวนการข้อใดตรงกับปัญหานี้ที่สุด",
      o: [
        "Sparge สารละลายและ flush headspace ด้วย nitrogen ก่อนปิดฝา",
        "เพิ่มอุณหภูมิระหว่างผสมเพื่อให้ตัวยาละลายเร็ว",
        "เติมอากาศเข้าสารละลายเพื่อให้ฟองหายเร็ว",
        "ใช้ฝาที่หลวมขึ้นเพื่อระบายความดัน",
        "เพิ่มปริมาตร headspace เพื่อลดการกระเพื่อม",
      ],
      a: 0,
      r: "ออกซิเจนที่ละลายในสารละลายและที่อยู่ใน headspace เป็นแหล่งของ autoxidation การไล่ออกซิเจนด้วย inert gas (nitrogen หรือ argon) ทั้งการ sparging ระหว่างผสมและการ flush headspace ก่อนปิด ช่วยลดออกซิเจนตั้งต้นได้มาก\n\nมักใช้ร่วมกับ antioxidant, chelator, การควบคุม pH และภาชนะที่กันออกซิเจนได้ดี ปริมาณ residual O₂ ใน headspace สามารถกำหนดเป็น in-process control ได้",
      w: [
        "ถูก — ไล่ dissolved O₂ และ O₂ ใน headspace ด้วย nitrogen ลดแหล่งตั้งต้นของ oxidation",
        "ความร้อนเร่ง oxidation และไม่ลดออกซิเจน",
        "การเติมอากาศเพิ่ม dissolved oxygen ทำให้ oxidation แย่ลง",
        "ฝาหลวมทำให้ออกซิเจนและความชื้นเข้าได้ง่ายขึ้น",
        "Headspace มากขึ้นหมายถึงปริมาณออกซิเจนมากขึ้น",
      ],
      k: "ยาไว oxidation: nitrogen sparging + headspace flushing ลด O₂ ตั้งต้น ใช้คู่กับ antioxidant/chelator",
      d: "easy",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Chemical stability; Remington: The Science and Practice of Pharmacy 23rd ed.",
    },
    {
      t: "Catechol oxidation of epinephrine",
      p: "สารละลาย epinephrine เปลี่ยนเป็นสีชมพูแล้วกลายเป็นสีน้ำตาลเมื่อเก็บในภาชนะที่เปิดใช้บ่อย กลไกและมาตรการป้องกันข้อใดสอดคล้องกันที่สุด",
      o: [
        "Catechol ถูก oxidize เป็น adrenochrome และ melanin-like pigment; ป้องกันด้วย pH ต่ำ, sodium metabisulfite, EDTA และไล่ออกซิเจน",
        "Ester hydrolysis ได้ catechol อิสระ; ป้องกันโดยปรับ pH เป็นด่าง",
        "Maillard reaction กับน้ำตาล; ป้องกันด้วยการตัดน้ำตาลออก",
        "Decarboxylation ของ side chain; ป้องกันด้วยการแช่แข็ง",
        "Photo-polymerization; ป้องกันด้วย BHT ในวัฏภาคน้ำ",
      ],
      a: 0,
      r: "Epinephrine มีหมู่ catechol (1,2-dihydroxybenzene) ซึ่ง autoxidize ได้ง่ายโดยเฉพาะที่ pH สูง มีโลหะหนัก แสง และออกซิเจน ได้ o-quinone → cyclize เป็น adrenochrome (สีชมพู-แดง) → polymer สีน้ำตาล\n\nการป้องกัน: ปรับ pH ให้เป็นกรด (ประมาณ 2.5–5) ซึ่งเป็นช่วงที่ phenol ไม่แตกตัว, ใช้ sodium metabisulfite ที่เหมาะกับ pH ต่ำ, เติม EDTA จับโลหะ, ไล่ O₂ และกันแสง ข้อพึงระวังคือ bisulfite อาจทำปฏิกิริยาเกิด epinephrine sulfonate และ pH ต่ำเกินไปเร่ง racemization",
      w: [
        "ถูก — catechol oxidation เป็นกลไกหลักและมาตรการทั้งหมดลด oxidation ตรงจุด",
        "Epinephrine ไม่มีหมู่ ester และ pH ด่างกลับเร่ง oxidation ของ catechol",
        "การเปลี่ยนสีของ epinephrine เกิดจาก oxidation ไม่ใช่ Maillard",
        "Decarboxylation ไม่ใช่ pathway หลักของ epinephrine และไม่อธิบายสีชมพู",
        "BHT ไม่ละลายน้ำและการเปลี่ยนสีไม่ได้เกิดจาก photo-polymerization เป็นหลัก",
      ],
      k: "Catechol (epinephrine, levodopa, isoprenaline) → oxidation เป็น quinone มีสี; ใช้ pH ต่ำ + metabisulfite + EDTA + N₂",
      d: "medium",
      ref: "Connors, Chemical Stability of Pharmaceuticals 2nd ed. (Epinephrine monograph); Aulton's Pharmaceutics 6th ed.",
    },
    {
      t: "Pseudo-first-order hydrolysis concept",
      p: "การ hydrolysis ของยา ester ในสารละลาย buffer pH 4 จริงๆ เป็นปฏิกิริยา bimolecular ระหว่างยากับน้ำ (และ H⁺) แต่ข้อมูลกลับเข้ากับ first-order kinetics เหตุผลข้อใดถูกต้องที่สุด",
      o: [
        "น้ำมีปริมาณมากเกินมากและ [H⁺] คงที่ด้วย buffer จึงรวมเข้าเป็นค่าคงที่ kobs ได้ (pseudo-first-order)",
        "ปฏิกิริยาเกิดเฉพาะบนผิวภาชนะ จึงไม่ขึ้นกับความเข้มข้น",
        "ยาละลายไม่หมดจึงเป็น zero-order แต่ดูเหมือน first-order",
        "Buffer ทำหน้าที่เป็น catalyst ที่ถูกใช้หมดไประหว่างปฏิกิริยา",
        "ปฏิกิริยา bimolecular ทุกชนิดเป็น first-order เสมอ",
      ],
      a: 0,
      r: "อัตรา = k[ester][H₂O][H⁺] แต่ในสารละลายน้ำ ความเข้มข้นน้ำ (~55.5 M) แทบไม่เปลี่ยน และ buffer ตรึง [H⁺] ไว้ จึงรวมเป็น kobs = k[H₂O][H⁺] ทำให้อัตรา = kobs[ester] ซึ่งเป็น pseudo-first-order\n\nดังนั้น kobs ขึ้นกับ pH ชนิดและความเข้มข้นของ buffer (general acid–base catalysis) และ ionic strength เมื่อเปลี่ยนสภาวะเหล่านี้ต้องหา kobs ใหม่ เป็นพื้นฐานของการสร้าง pH-rate profile",
      w: [
        "ถูก — สารตั้งต้นอื่นมีมากเกินหรือถูกตรึงความเข้มข้น จึงเหลือการขึ้นกับยาเพียงตัวเดียว",
        "ปฏิกิริยาบนผิวภาชนะไม่ใช่เหตุผลของ pseudo-order ใน hydrolysis",
        "Apparent zero-order เกิดใน suspension ที่ความเข้มข้นในสารละลายคงที่ ไม่ใช่กรณีนี้",
        "Buffer/catalyst ไม่ถูกใช้หมด และถ้าถูกใช้หมด kobs จะไม่คงที่",
        "ปฏิกิริยา bimolecular เป็น second-order โดยแท้ จะเป็น first-order เฉพาะเมื่อมีสารหนึ่งมากเกินหรือคงที่",
      ],
      k: "Pseudo-first-order: สารร่วมปฏิกิริยา (น้ำ, H⁺/OH⁻ ใน buffer) มีมากเกินหรือคงที่ → rate = kobs[ยา]",
      d: "medium",
      ref: "Martin's Physical Pharmacy and Pharmaceutical Sciences 7th ed., Ch. Kinetics",
    },
    {
      t: "Photostability dark control purpose",
      p: "ในการทดสอบ photostability ตาม ICH Q1B ของยาเม็ด analyst วางตัวอย่างที่ห่อด้วย aluminium foil ไว้ในตู้ทดสอบข้างตัวอย่างที่รับแสง วัตถุประสงค์หลักของตัวอย่างห่อ foil คืออะไร",
      o: [
        "เป็น dark control เพื่อแยกการเปลี่ยนแปลงจากความร้อน/ความชื้นในตู้ ออกจากผลของแสง",
        "ใช้วัดปริมาณแสงที่ได้รับแทน lux meter",
        "ใช้เป็นตัวอย่างสำรองกรณีตัวอย่างหลักแตก",
        "เพื่อจำลอง Alu-Alu blister ซึ่งเป็นภาชนะจำหน่าย",
        "เพื่อพิสูจน์ว่า aluminium foil ไม่ปล่อย leachables",
      ],
      a: 0,
      r: "ระหว่างการฉายแสงในตู้ อุณหภูมิของตัวอย่างอาจสูงขึ้น ICH Q1B จึงกำหนดให้วางตัวอย่างที่ป้องกันแสง (เช่น ห่อ aluminium foil) เป็น dark control ไว้คู่กันในสภาวะเดียวกัน\n\nหาก degradant เกิดทั้งใน exposed และ dark control แสดงว่าเกิดจากความร้อน ไม่ใช่แสง ส่วนที่เกิดเฉพาะใน exposed จึงเป็นผลของ photodegradation การแปลผลจึงต้องเทียบระหว่างสองกลุ่ม ปริมาณแสงวัดด้วย calibrated radiometer/lux meter หรือ chemical actinometer",
      w: [
        "ถูก — dark control ใช้แยก thermal effect ออกจาก photolytic effect",
        "Foil ไม่ใช่เครื่องมือวัดแสง ปริมาณแสงต้องวัดด้วย radiometer/lux meter หรือ actinometry",
        "ไม่ใช่ตัวอย่างสำรอง แต่เป็นกลุ่มควบคุมที่ต้องวิเคราะห์ด้วย",
        "การทดสอบใน marketing pack ใช้ pack จริง ไม่ใช่การห่อ foil แทน",
        "Leachables ไม่ใช่วัตถุประสงค์ของ Q1B",
      ],
      k: "Q1B dark control (ห่อ foil วางข้างกัน) = แยกผลความร้อนในตู้ออกจากผลของแสง",
      d: "medium",
      ref: "ICH Q1B Photostability Testing of New Drug Substances and Products",
    },
    {
      t: "HDPE vs PET bottle barrier",
      p: "ยาเม็ดตัวหนึ่งไวต่อ oxidation มาก แต่ไม่ค่อยไวความชื้น ทีมบรรจุภัณฑ์กำลังเลือกระหว่างขวด HDPE ทึบกับขวด PET สีชา (ความหนาเท่ากัน) ข้อสรุปใดถูกต้องที่สุด",
      o: [
        "PET กันออกซิเจนได้ดีกว่า HDPE ชัดเจน แม้จะกันความชื้นได้ด้อยกว่า จึงเหมาะกับยานี้มากกว่า",
        "HDPE กันทั้งออกซิเจนและความชื้นได้ดีกว่า PET ในทุกกรณี",
        "PET กันความชื้นได้ดีที่สุดในพลาสติก แต่กันออกซิเจนไม่ได้",
        "พลาสติกทุกชนิดกันออกซิเจนได้เท่ากัน ต่างกันเพียงความชื้น",
        "ควรใช้ LDPE เพราะยืดหยุ่นและกันออกซิเจนได้ดีที่สุด",
      ],
      a: 0,
      r: "Polyolefin (HDPE, PP) กันไอน้ำได้ดีเพราะไม่มีขั้ว แต่ให้ออกซิเจนซึมผ่านได้สูง ส่วน PET เป็น polyester มีขั้ว chain แน่น ให้ oxygen barrier ดีกว่า HDPE หลายเท่า แต่ moisture barrier ด้อยกว่า HDPE\n\nดังนั้นการเลือกภาชนะต้องดูว่ายาไวต่อปัจจัยใด ยาไว oxidation ได้ประโยชน์จาก PET (หรือแก้ว) ส่วนยาไวความชื้นนิยม HDPE + induction seal + desiccant ส่วน LDPE ให้ barrier ต่ำทั้งสองด้าน",
      w: [
        "ถูก — PET มี oxygen barrier ดีกว่า HDPE ชัดเจน ขณะที่ HDPE เด่นเรื่องกันความชื้น",
        "HDPE เด่นเฉพาะ moisture barrier แต่ oxygen permeability สูง",
        "สลับคุณสมบัติ — PET เด่นที่ oxygen barrier ไม่ใช่ moisture barrier สูงสุด",
        "Oxygen permeability ของพลาสติกแต่ละชนิดต่างกันได้หลายระดับขนาด",
        "LDPE มี density ต่ำ ให้ทั้งออกซิเจนและความชื้นซึมผ่านมากที่สุดในกลุ่มนี้",
      ],
      k: "HDPE/PP: moisture barrier ดี O₂ barrier แย่; PET: O₂ barrier ดีกว่า moisture barrier ด้อยกว่า HDPE",
      d: "medium",
      ref: "WHO TRS 902 Annex 9; Aulton's Pharmaceutics 6th ed., Ch. Pharmaceutical packaging",
    },
    {
      t: "Water loss in semi-permeable container",
      p: "ยาน้ำรับประทานบรรจุขวด LDPE (semi-permeable) ทำ accelerated ที่ 40°C/RH ไม่เกิน 25% น้ำหนักสุทธิเริ่มต้น 100.0 g หลัง 3 เดือนเหลือ 94.6 g (น้ำหนักที่หายเป็นน้ำ) ข้อใดสรุปได้ถูกต้องที่สุดตาม ICH Q1A(R2)",
      o: [
        "สูญเสียน้ำ 5.4% ถือเป็น significant change สำหรับภาชนะ semi-permeable ขนาดนี้",
        "สูญเสียน้ำ 5.4% ยังไม่เป็น significant change เพราะเกณฑ์คือ 10%",
        "สูญเสียน้ำ 0.54% ไม่มีผลต่อการประเมิน",
        "การสูญเสียน้ำไม่ใช่ประเด็น เพราะประเมินเฉพาะ assay ของตัวยา",
        "สูญเสียน้ำ 5.4% ทำให้ต้องเปลี่ยน long-term เป็น 25°C/60%RH",
      ],
      a: 0,
      r: "ผลิตภัณฑ์ในน้ำที่บรรจุภาชนะ semi-permeable (LDPE bottle, bag) อาจสูญเสียน้ำผ่านผนังทำให้ความเข้มข้นยาสูงขึ้น ICH Q1A(R2) ให้ศึกษาที่ RH ต่ำและกำหนดว่า การสูญเสียน้ำ 5% จากค่าเริ่มต้นหลังเก็บเทียบเท่า 3 เดือนที่ 40°C/RH ไม่เกิน 25% ถือเป็น significant change\n\nกรณีนี้ (100.0 − 94.6)/100.0 × 100 = 5.4% จึงเป็น significant change ข้อยกเว้นคือภาชนะขนาดเล็ก (≤1 mL) หรือ unit-dose ซึ่งอาจยอมรับการสูญเสีย ≥5% ได้หากมีเหตุผลรองรับ",
      w: [
        "ถูก — สูญเสีย 5.4% ≥ 5% ภายใน 3 เดือนที่ 40°C/≤25%RH เป็น significant change",
        "เกณฑ์ของ ICH คือ 5% ไม่ใช่ 10%",
        "คำนวณผิดหลัก — 5.4 g จาก 100 g คือ 5.4% ไม่ใช่ 0.54%",
        "การสูญเสียน้ำทำให้ความเข้มข้นเพิ่ม/ปริมาตรลด จึงเป็นเกณฑ์สำคัญของ semi-permeable container",
        "สภาวะ long-term ขึ้นกับ climatic zone ที่จำหน่าย ไม่ได้เปลี่ยนเพราะผลการสูญเสียน้ำ",
      ],
      k: "Semi-permeable container: สูญเสียน้ำ ≥5% หลัง 3 เดือนที่ 40°C/≤25%RH = significant change (ยกเว้น ≤1 mL/unit-dose ที่มีเหตุผล)",
      d: "medium",
      ref: "ICH Q1A(R2) Section 2.2.7.3 Drug products packaged in semi-permeable containers",
      c: [
        "Water loss = 100.0 − 94.6 = 5.4 g",
        "% loss = 5.4 / 100.0 × 100 = 5.4%",
        "5.4% ≥ 5% (เกณฑ์ ICH ที่ 40°C/≤25%RH, 3 เดือน) → significant change",
      ],
    },
    {
      t: "Activation energy from two temperatures",
      p: "การศึกษา stress ของยาในสารละลาย (first-order) ได้ k = 0.0060 day⁻¹ ที่ 40°C และ k = 0.0420 day⁻¹ ที่ 60°C (R = 8.314 J/mol·K) Activation energy (Ea) ของปฏิกิริยานี้ประมาณเท่าใด",
      o: ["1.94 kJ/mol", "20.2 kJ/mol", "36.6 kJ/mol", "84.4 kJ/mol", "194 kJ/mol"],
      a: 3,
      r: "จาก Arrhenius สองจุด: ln(k2/k1) = (Ea/R)(1/T1 − 1/T2)\n\nk2/k1 = 0.0420/0.0060 = 7.0 → ln 7 = 1.946; 1/313.15 − 1/333.15 = 1.917 × 10⁻⁴ K⁻¹ → Ea = 8.314 × 1.946 / 1.917 × 10⁻⁴ = 84,400 J/mol ≈ 84.4 kJ/mol\n\nค่านี้อยู่ในช่วงทั่วไปของการเสื่อมสลายของยา (ประมาณ 50–120 kJ/mol) Ea สูงหมายถึงอัตราไวต่ออุณหภูมิมาก การทำนาย shelf life จากอุณหภูมิสูงจึงต้องการ Ea ที่แม่นยำ",
      w: [
        "ใช้อุณหภูมิเป็น °C แทน Kelvin (1/40 − 1/60) ทำให้ค่าผิดมาก",
        "ใช้ R = 1.987 cal/mol·K แต่รายงานเป็น kJ (ที่จริงได้ ≈ 20.2 kcal/mol ซึ่งเท่ากับ ≈ 84 kJ/mol)",
        "ใช้ log10 แทน ln โดยไม่คูณ 2.303",
        "ถูก — Ea = R·ln(k2/k1)/(1/T1 − 1/T2) ≈ 84.4 kJ/mol",
        "เลื่อนทศนิยมผิด/ไม่ได้ใช้ ln ratio ที่ถูกต้อง",
      ],
      k: "Ea = R·ln(k2/k1) / (1/T1 − 1/T2) ใช้ K และ ln; ระวังหน่วย cal vs J",
      d: "hard",
      ref: "Martin's Physical Pharmacy and Pharmaceutical Sciences 7th ed., Ch. Kinetics (Arrhenius equation)",
      c: [
        "T1 = 313.15 K, T2 = 333.15 K",
        "k2/k1 = 0.0420/0.0060 = 7.0 → ln 7.0 = 1.946",
        "1/T1 − 1/T2 = 0.0031934 − 0.0030017 = 1.917 × 10⁻⁴ K⁻¹",
        "Ea = 8.314 × 1.946 / 1.917 × 10⁻⁴ = 84,400 J/mol ≈ 84.4 kJ/mol",
      ],
    },
    {
      t: "Suspension apparent zero-order shelf life",
      p: "ยาแขวนตะกอน 250 mg/5 mL (50 mg/mL) ตัวยามี solubility 2.0 mg/mL และในสารละลายเสื่อมแบบ first-order ด้วย k1 = 5.0 × 10⁻³ day⁻¹ โดยถือว่าเฉพาะส่วนที่ละลายเท่านั้นที่เสื่อม t90 ของผลิตภัณฑ์ suspension นี้ประมาณเท่าใด",
      o: ["20 วัน", "21.1 วัน", "139 วัน", "500 วัน", "5,000 วัน"],
      a: 3,
      r: "ใน suspension ส่วนของยาที่ละลายถูกเติมกลับจาก reservoir ที่เป็นของแข็ง ความเข้มข้นในสารละลายจึงคงที่เท่ากับ Cs ทำให้อัตราเสื่อมรวมคงที่ = apparent zero-order ด้วย k0 = k1 × Cs\n\nk0 = 5.0 × 10⁻³ × 2.0 = 0.010 mg/mL/day → t90 = 0.1 × C0/k0 = 0.1 × 50/0.010 = 500 วัน\n\nเทียบกับถ้าเป็นสารละลายทั้งหมด t90 = 0.105/k1 = 21 วัน จึงเห็นว่าการทำเป็น suspension (หรือใช้ salt/prodrug ที่ละลายน้อย) เป็นกลยุทธ์เพิ่มความคงตัวของยาที่ hydrolyze ง่าย เช่น penicillin บางชนิด",
      w: [
        "ใช้ Cs (2.0 mg/mL) เป็น C0 ผิด ต้องใช้ความเข้มข้นรวมของผลิตภัณฑ์ 50 mg/mL",
        "เป็น t90 ของยาในรูปสารละลาย (0.105/k1) ไม่ได้คำนึงถึง reservoir ของแข็ง",
        "เป็น t1/2 ของสารละลาย (0.693/k1)",
        "ถูก — k0 = k1·Cs = 0.010 mg/mL/day; t90 = 0.1 × 50/0.010 = 500 วัน",
        "ลืมคูณ 0.1 (คำนวณเวลาที่ยาสลายหมด 100% แบบ zero-order)",
      ],
      k: "Suspension: apparent zero-order k0 = k1·Cs; t90 = 0.1C0/k0 (ใช้ได้ตราบที่ยังมีของแข็งเหลือ)",
      d: "hard",
      ref: "Martin's Physical Pharmacy and Pharmaceutical Sciences 7th ed., Ch. Kinetics (Suspensions)",
      c: [
        "k0 = k1 × Cs = 5.0 × 10⁻³ day⁻¹ × 2.0 mg/mL = 0.010 mg/mL/day",
        "t90 = 0.1 × C0 / k0 = 0.1 × 50 / 0.010",
        "t90 = 500 วัน",
      ],
    },
    {
      t: "Gelatin capsule cross-linking on storage",
      p: "Hard gelatin capsule ที่บรรจุ granule ซึ่งมี PEG และ povidone (มี peroxide/aldehyde ตกค้าง) หลังเก็บที่ 40°C/75%RH พบ dissolution ใน 0.1 N HCl ลดลงมาก แต่ assay ปกติ และเห็นเปลือกเป็นแผ่นเยื่อ (pellicle) ไม่แตก การจัดการเบื้องต้นข้อใดถูกต้องที่สุด",
      o: [
        "สงสัย gelatin cross-linking จาก aldehyde ทดสอบซ้ำด้วยตัวกลางที่เติม enzyme (pepsin) ตาม USP <711> และแก้ที่แหล่ง aldehyde/เปลี่ยนเป็น HPMC capsule",
        "สรุปว่าตัวยาเปลี่ยน polymorph จึงต้องเปลี่ยน API supplier",
        "เพิ่ม rotation speed ของ dissolution apparatus จนได้ผลผ่าน",
        "เพิ่มปริมาณ magnesium stearate เพื่อให้ granule กระจายตัวดีขึ้น",
        "สรุปว่าเป็น analytical error และเปลี่ยน HPLC column",
      ],
      a: 0,
      r: "Gelatin มีหมู่ amino (lysine) ที่ทำ cross-link กับ aldehyde (formaldehyde, furfural) ที่มาจาก excipient degradation (PEG, povidone, polysorbate), สี หรือบรรจุภัณฑ์ ความร้อนและความชื้นเร่งปฏิกิริยา เกิด pellicle ที่ละลายช้า ทำให้ dissolution ลดแม้ตัวยาไม่เสื่อม\n\nUSP <711> อนุญาตให้ทำ dissolution ซ้ำโดยเติม enzyme (pepsin สำหรับ pH ≤ 6.8, pancreatin สำหรับ pH > 6.8) เพื่อย่อย cross-link หากผ่านเกณฑ์จึงยอมรับได้ ส่วนการแก้ระยะยาวคือควบคุม peroxide/aldehyde ของ excipient หรือใช้ HPMC capsule ซึ่งไม่ cross-link",
      w: [
        "ถูก — อาการ pellicle + dissolution ลด + assay ปกติ เข้ากับ gelatin cross-linking; ทดสอบด้วย enzyme และแก้ที่ต้นเหตุ",
        "Polymorph change ไม่ทำให้เกิดแผ่นเยื่อเปลือก capsule และไม่ได้มีหลักฐาน solid-state",
        "การปรับ apparatus ตามใจเพื่อให้ผ่านขัดกับวิธีที่ validate แล้วและไม่แก้ปัญหา",
        "Magnesium stearate เพิ่มความไม่ชอบน้ำ อาจทำให้ dissolution แย่ลง และไม่ใช่สาเหตุ",
        "อาการทางกายภาพของเปลือกบ่งชี้ปัญหาผลิตภัณฑ์จริง ไม่ใช่ปัญหา HPLC",
      ],
      k: "Gelatin + aldehyde → cross-link/pellicle → dissolution ช้า; ใช้ enzyme-containing medium (USP <711>) หรือเปลี่ยนเป็น HPMC capsule",
      d: "hard",
      ref: "USP <711> Dissolution (Capsules—gelatin cross-linking); Digenis GA et al. J Pharm Sci 1994;83:915",
    },
  ],
];
