import type { Ip1MockDomainContent } from "@/lib/ip1-mock/types";

export const STABILITY: Ip1MockDomainContent = [
  // Mock Set 1 — ชุดที่ 1
  [
    {
      t: "Ester hydrolysis susceptibility",
      p: "ทีมพัฒนาสูตรได้รับตัวยา 5 ชนิดเพื่อทำ oral solution ในน้ำ (pH 6–7) หากพิจารณาเฉพาะหมู่ฟังก์ชันที่ไวต่อ hydrolysis ตัวยาใดมีแนวโน้มเสื่อมสลายด้วย hydrolysis เร็วที่สุด",
      o: [
        "Acetylsalicylic acid (มี phenolic ester)",
        "Paracetamol (มี anilide/amide)",
        "Phenobarbital (มี imide ในวง barbiturate)",
        "Ibuprofen (มี carboxylic acid)",
        "Chlorpheniramine (มี tertiary amine)",
      ],
      a: 0,
      r: "Hydrolysis เกิดได้ง่ายที่หมู่ carbonyl ที่ถูก nucleophile (น้ำ/OH⁻) โจมตี ลำดับความไวโดยทั่วไปคือ ester > amide/imide ส่วน carboxylic acid และ amine ไม่ hydrolyze\n\nAspirin เป็น phenyl ester ซึ่ง leaving group (phenoxide ของ salicylate) เสถียรด้วย resonance จึงยิ่ง hydrolyze ง่ายกว่า alkyl ester ทั่วไป ได้ salicylic acid + acetic acid (กลิ่นน้ำส้มสายชู) ด้วยเหตุนี้ aspirin จึงแทบไม่ทำเป็น aqueous solution สำเร็จรูป แต่ทำเป็นเม็ดแห้งหรือ effervescent ที่ละลายก่อนใช้",
      w: [
        "ถูก — phenolic ester ของ aspirin เป็นหมู่ที่ hydrolyze ง่ายที่สุดในตัวเลือก ได้ salicylic acid + acetic acid",
        "Amide ของ paracetamol เสถียรกว่า ester มาก เพราะ nitrogen ให้ resonance กับ carbonyl ทำให้ carbonyl carbon electrophilic น้อยลง hydrolysis เกิดช้าที่ pH ใกล้กลาง",
        "Barbiturate ring hydrolyze ได้ แต่เด่นในสภาวะด่างแรง ที่ pH 6–7 ช้ากว่า aspirin มาก",
        "Carboxylic acid ไม่มี leaving group ให้ hydrolysis จึงไม่ใช่ pathway หลักของ ibuprofen",
        "Tertiary amine ไม่ hydrolyze; ปัญหาของ amine มักเป็น oxidation (N-oxide) มากกว่า",
      ],
      k: "ความไวต่อ hydrolysis: ester (โดยเฉพาะ phenyl ester) > lactam/imide > amide; acid/amine ไม่ hydrolyze",
      d: "easy",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Chemical stability of drugs; Connors, Chemical Stability of Pharmaceuticals 2nd ed.",
    },
    {
      t: "Antioxidant phase selection",
      p: "ครีม o/w มีวิตามิน A palmitate (ละลายในน้ำมัน ไวต่อ oxidation) อยู่ในวัฏภาคน้ำมัน การเลือก antioxidant ข้อใดเหมาะสมที่สุด",
      o: [
        "เติม BHT หรือ α-tocopherol ลงในวัฏภาคน้ำมัน",
        "เติม sodium metabisulfite ลงในวัฏภาคน้ำ",
        "เติม ascorbic acid ลงในวัฏภาคน้ำเท่านั้น",
        "เติม disodium EDTA แทน antioxidant ทั้งหมด",
        "เติม sodium chloride เพื่อลด oxygen solubility",
      ],
      a: 0,
      r: "Antioxidant ต้องอยู่วัฏภาคเดียวกับตัวยาที่ต้องการปกป้อง Vitamin A palmitate อยู่ในน้ำมัน จึงต้องใช้ oil-soluble antioxidant ชนิด free-radical chain terminator เช่น BHT, BHA, α-tocopherol หรือ ascorbyl palmitate\n\nWater-soluble antioxidant (ascorbic acid, sodium metabisulfite, sodium sulfite) ใช้กับยาในวัฏภาคน้ำ ส่วน EDTA เป็น synergist ที่จับโลหะ ช่วยเสริมแต่ไม่หยุด radical chain ด้วยตัวเอง",
      w: [
        "ถูก — BHT/tocopherol ละลายในน้ำมัน อยู่ใกล้ตัวยาและหยุด radical chain ได้โดยตรง",
        "Metabisulfite เป็น water-soluble reducing agent อยู่คนละวัฏภาคกับ vitamin A palmitate จึงปกป้องได้น้อย",
        "Ascorbic acid ละลายน้ำ ไม่เข้าไปในหยดน้ำมัน (ถ้าต้องการ ascorbate ในน้ำมันต้องใช้ ascorbyl palmitate)",
        "EDTA เป็นเพียง chelator/synergist ลด metal catalysis แต่ไม่ใช่ chain-breaking antioxidant ใช้แทนทั้งหมดไม่ได้",
        "การเติมเกลือไม่ใช่กลยุทธ์ป้องกัน oxidation ที่ใช้จริงและไม่ได้ปกป้องยาในวัฏภาคน้ำมัน",
      ],
      k: "เลือก antioxidant ให้อยู่วัฏภาคเดียวกับยา: น้ำมัน → BHT/BHA/tocopherol; น้ำ → ascorbic acid/sulfites",
      d: "easy",
      ref: "Handbook of Pharmaceutical Excipients 9th ed.; Aulton's Pharmaceutics 6th ed.",
    },
    {
      t: "First-order t90 calculation",
      p: "Oral solution ตัวหนึ่งเสื่อมสลายแบบ first-order ที่ 25°C ด้วย k = 2.1 × 10⁻³ day⁻¹ เวลาที่ตัวยาเหลือ 90% ของเริ่มต้น (t90) ประมาณเท่าใด",
      o: ["5.0 วัน", "47.6 วัน", "50.2 วัน", "330 วัน", "1,096 วัน"],
      a: 2,
      r: "สำหรับ first-order: ln(C0/C) = kt เมื่อ C = 0.9C0 จะได้ t90 = ln(1/0.9)/k = 0.1054/k\n\nt90 = 0.1054 / 0.0021 = 50.2 วัน ซึ่งไม่ขึ้นกับความเข้มข้นเริ่มต้น ต่างจาก zero-order ที่ t90 = 0.1C0/k0\n\nตัวเลือกอื่นเกิดจากความสับสนสูตร: 0.693/k คือ t1/2 และ 2.303/k คือเวลาที่เหลือเพียง 10%",
      w: [
        "ผิดหลักทศนิยม (เลื่อนตำแหน่ง) ไม่สอดคล้องกับ 0.1054/0.0021",
        "ใช้ 0.1/k ซึ่งเป็นการคิดแบบประมาณผิดสูตร (คล้าย zero-order) ได้ 47.6 วัน",
        "ถูก — t90 = 0.1054/k = 0.1054/0.0021 = 50.2 วัน",
        "เป็น t1/2 = 0.693/k ไม่ใช่ t90",
        "เป็น ln10/k คือเวลาที่ยาเหลือ 10% (สลายไป 90%)",
      ],
      k: "First-order: t90 = 0.105/k, t1/2 = 0.693/k (ทั้งคู่ไม่ขึ้นกับ C0)",
      d: "medium",
      ref: "Martin's Physical Pharmacy and Pharmaceutical Sciences 7th ed., Ch. Kinetics",
      c: [
        "First-order: t90 = ln(100/90)/k = 0.1054/k",
        "t90 = 0.1054 / (2.1 × 10⁻³ day⁻¹)",
        "t90 = 50.2 วัน",
      ],
    },
    {
      t: "Q10 refrigerated product at room temperature",
      p: "ยาน้ำชนิดหนึ่งมี t90 = 24 เดือนเมื่อเก็บที่ 5°C ร้านยาเก็บผิดไว้ที่ 25°C ตลอดเวลา หากประมาณด้วย Q10 = 3 ตัวยาจะมี t90 ที่ 25°C ประมาณเท่าใด",
      o: ["0.9 เดือน", "2.7 เดือน", "4.0 เดือน", "8.0 เดือน", "12.0 เดือน"],
      a: 1,
      r: "Q10 คือสัดส่วนที่อัตราการเสื่อมเพิ่มขึ้นเมื่ออุณหภูมิเพิ่ม 10°C ใช้ได้กับ shelf life ในลักษณะ t90(T2) = t90(T1) / Q10^(ΔT/10)\n\nΔT = 25 − 5 = 20°C → Q10^2 = 3² = 9 → t90 = 24/9 = 2.7 เดือน\n\nQ10 = 2, 3, 4 สอดคล้องกับ Ea ประมาณ 50, 80, 105 kJ/mol ตามลำดับ (Connors) ใช้เป็นการประมาณคร่าวๆ เมื่อไม่มีข้อมูล Arrhenius จริง",
      w: [
        "ใช้ Q10^3 = 27 (นับ ΔT ผิดเป็น 30°C) ได้ 24/27 ≈ 0.9 เดือน",
        "ถูก — ΔT = 20°C → Q10^(20/10) = 9 → 24/9 ≈ 2.7 เดือน",
        "คูณ Q10 × 2 = 6 แทนการยกกำลัง ได้ 4 เดือน ซึ่งผิดหลัก Q10",
        "หารด้วย Q10 เพียงครั้งเดียว (คิดเหมือน ΔT = 10°C)",
        "หารด้วย 2 คือใช้ Q10 = 2 เพียงขั้นเดียว ไม่ตรงกับเงื่อนไขโจทย์",
      ],
      k: "t90(T2) = t90(T1)/Q10^(ΔT/10); ยาตู้เย็นที่หลุดไปอยู่ 25°C อายุลดลงหลายเท่า",
      d: "medium",
      ref: "Connors KA, Amidon GL, Stella VJ. Chemical Stability of Pharmaceuticals 2nd ed.",
      c: [
        "ΔT = 25 − 5 = 20°C",
        "Factor = Q10^(ΔT/10) = 3^2 = 9",
        "t90(25°C) = 24 เดือน / 9 = 2.67 ≈ 2.7 เดือน",
      ],
    },
    {
      t: "Maillard reaction with lactose",
      p: "ยาเม็ด Drug X (มีหมู่ primary amine) ใช้ lactose monohydrate เป็น filler หลัง accelerated 40°C/75%RH 3 เดือน เม็ดยาเปลี่ยนเป็นสีเหลือง-น้ำตาล และพบ degradant ใหม่ที่ไม่พบใน API เดี่ยว การแก้ไขสูตรข้อใดตรงสาเหตุที่สุด",
      o: [
        "เปลี่ยน filler เป็น microcrystalline cellulose หรือ mannitol ซึ่งไม่ใช่ reducing sugar",
        "เปลี่ยนเป็น anhydrous lactose เพื่อลดความชื้นและยังคงใช้ lactose ได้ตามเดิม",
        "เพิ่ม BHT ในสูตรเพื่อป้องกันการเปลี่ยนสี",
        "เพิ่มปริมาณ magnesium stearate เพื่อเคลือบผิวอนุภาค",
        "บรรจุใน amber glass เพื่อป้องกันแสง",
      ],
      a: 0,
      r: "Lactose เป็น reducing sugar (มี hemiacetal เปิดเป็น aldehyde ได้) ทำปฏิกิริยากับ primary/secondary amine ได้ glycosylamine → Amadori rearrangement → สารสีน้ำตาล (Maillard reaction) ความชื้นและอุณหภูมิเร่งปฏิกิริยา ตัวอย่างที่รายงาน เช่น fluoxetine, amlodipine, metoclopramide\n\nการแก้ที่ต้นเหตุคือตัด reducing sugar ออก ใช้ MCC, dibasic calcium phosphate หรือ mannitol (sugar alcohol ไม่มี carbonyl) แทน anhydrous lactose ลดความชื้นได้บ้างแต่ยังเป็น reducing sugar",
      w: [
        "ถูก — ตัด reducing sugar ออกจากสูตร จึงไม่มี aldehyde ให้ทำปฏิกิริยากับ amine",
        "Anhydrous lactose ยังเป็น reducing sugar ลดความเร็วได้บ้างแต่ไม่แก้สาเหตุ โดยเฉพาะในเขต Zone IVb",
        "BHT เป็น radical scavenger สำหรับ oxidation ไม่ได้ยับยั้ง Maillard condensation",
        "Magnesium stearate ไม่ป้องกันการสัมผัสระหว่าง amine กับ lactose อย่างมีนัยสำคัญ และอาจเพิ่มปัญหาอื่น",
        "การเปลี่ยนสีครั้งนี้เกิดจากปฏิกิริยาเคมีระหว่างยากับ excipient ไม่ใช่ photolysis",
      ],
      k: "Primary/secondary amine + reducing sugar (lactose, glucose) → Maillard browning; ใช้ MCC/DCP/mannitol แทน",
      d: "medium",
      ref: "Handbook of Pharmaceutical Excipients 9th ed. (Lactose monograph: incompatibilities)",
    },
    {
      t: "Significant change criteria (drug product)",
      p: "ผลศึกษา accelerated 40°C/75%RH ที่ 6 เดือนของยาเม็ด (assay spec 95.0–105.0%) ข้อใดถือเป็น significant change ตาม ICH Q1A(R2)",
      o: [
        "Assay ลดลงจาก 101.8% เป็น 96.5% แม้ยังอยู่ใน specification",
        "Assay ลดลงจาก 100.4% เป็น 97.0%",
        "Total degradant เพิ่มจาก 0.2% เป็น 0.6% โดย spec ≤ 1.0%",
        "Dissolution ลดลงจาก 92% เป็น 85% ที่ 30 นาที โดย spec Q = 80%",
        "Hardness ลดลงเล็กน้อยแต่ friability ยังผ่านเกณฑ์",
      ],
      a: 0,
      r: "ICH Q1A(R2) นิยาม significant change ของ drug product ได้แก่ (1) assay เปลี่ยนจากค่าเริ่มต้น 5% (2) degradation product ใดเกิน acceptance criterion (3) ไม่ผ่านเกณฑ์ appearance/physical/functionality (4) pH ไม่ผ่าน (5) dissolution ไม่ผ่านใน 12 dosage units\n\nจุดสำคัญคือเกณฑ์ assay วัดจาก 'การเปลี่ยนแปลงจากค่าเริ่มต้น' ไม่ใช่แค่ผ่าน/ไม่ผ่าน spec: 101.8 → 96.5 = ลดลง 5.3% จึงเป็น significant change ทั้งที่ยังอยู่ใน spec ผลคือต้องพิจารณา intermediate (ถ้ามี) และจำกัดการ extrapolate shelf life",
      w: [
        "ถูก — ลดลง 5.3% จากค่าเริ่มต้น เกินเกณฑ์ 5% แม้ยังผ่าน spec",
        "ลดลง 3.4% ยังไม่ถึง 5% และอยู่ใน spec",
        "Degradant เพิ่มขึ้นแต่ยังไม่เกิน acceptance criterion จึงไม่เข้าเกณฑ์",
        "Dissolution ยังผ่าน Q จึงไม่ใช่ significant change (ต้องเป็นการ fail เกณฑ์)",
        "การเปลี่ยนแปลงทางกายภาพที่ยังผ่าน acceptance criteria ไม่ถือเป็น significant change",
      ],
      k: "Significant change: assay เปลี่ยน ≥5% จากค่าเริ่มต้น หรือ attribute ใด fail spec (degradant, appearance, pH, dissolution)",
      d: "medium",
      ref: "ICH Q1A(R2) Stability Testing of New Drug Substances and Products, Section 2.2.7",
    },
    {
      t: "Alu-Alu cold-form blister for hygroscopic tablet",
      p: "ยาเม็ด effervescent-like ที่ดูดความชื้นสูงมาก (assay และ dissolution เปลี่ยนเมื่อดูดน้ำ > 1%) จะวางจำหน่ายในประเทศไทย (Zone IVb) ต้องการบรรจุแบบ unit-dose blister ข้อใดเหมาะสมที่สุด",
      o: [
        "Cold-form Alu-Alu (OPA/Al/PVC + lidding aluminium foil)",
        "PVC 250 µm + aluminium lidding foil",
        "PVC/PVDC 40 g/m² + aluminium lidding foil",
        "PET blister ใส + paper/PET lidding",
        "PP blister + aluminium lidding foil",
      ],
      a: 0,
      r: "ความสามารถกันความชื้น (MVTR ต่ำ → ดี) เรียงคร่าวๆ: PVC < PP ≈ PVC/PVDC < PVC/Aclar (PCTFE) < Alu-Alu (cold form) ซึ่ง aluminium foil หนาที่ไม่มีรูเข็มให้ MVTR เกือบเป็นศูนย์และกันแสงได้ด้วย\n\nสำหรับยาไวความชื้นสูงในสภาวะ 30°C/75%RH Alu-Alu เป็นตัวเลือกที่ปลอดภัยที่สุด ข้อเสียคือ cavity ใหญ่ขึ้น (ขึ้นรูปเย็นยืดได้น้อย) ต้นทุนสูง และมองไม่เห็นเม็ดยา การเลือกต้องยืนยันด้วย stability data ใน pack จริงที่ 30°C/75%RH",
      w: [
        "ถูก — Alu-Alu ให้ barrier ต่อความชื้น แสง และออกซิเจนสูงสุดในกลุ่ม blister",
        "PVC เดี่ยวมี MVTR สูงที่สุด ไม่เหมาะกับยาไวความชื้นใน Zone IVb",
        "PVC/PVDC ดีกว่า PVC มากแต่ยังมีการซึมผ่านความชื้นได้ ไม่พอสำหรับยาที่ไวสูงมาก",
        "PET และ paper lidding ไม่ใช่ moisture barrier ระดับสูง",
        "PP กันความชื้นได้ดีกว่า PVC แต่ยังด้อยกว่า Alu-Alu อย่างชัดเจน",
      ],
      k: "Moisture barrier ของ blister: PVC < PVC/PVDC < PVC/Aclar < Alu-Alu; ยาไวความชื้นสูงใน Zone IVb → Alu-Alu",
      d: "medium",
      ref: "WHO TRS 902 Annex 9 Guidelines on packaging for pharmaceutical products; Aulton's Pharmaceutics 6th ed., Ch. Packaging",
    },
    {
      t: "Arrhenius prediction of t90 at 25°C",
      p: "การศึกษา stress พบว่ายาในสารละลายเสื่อมแบบ first-order ที่ 60°C ด้วย k = 0.020 day⁻¹ และมี Ea = 80 kJ/mol (R = 8.314 J/mol·K) ถ้ากลไกไม่เปลี่ยน t90 ที่ 25°C ประมาณเท่าใด",
      o: ["5.3 วัน", "59.6 วัน", "156 วัน", "1,029 วัน", "3,417 วัน"],
      a: 2,
      r: "Arrhenius: ln(k2/k1) = −(Ea/R)(1/T2 − 1/T1) โดยต้องใช้ Kelvin\n\nT1 = 333.15 K, T2 = 298.15 K → 1/T2 − 1/T1 = 3.522 × 10⁻⁴ K⁻¹; Ea/R = 80,000/8.314 = 9,622 K → ln(k25/k60) = −3.39 → k25/k60 = 0.0337 → k25 = 6.74 × 10⁻⁴ day⁻¹\n\nt90 = 0.1054/k25 = 156 วัน (≈5 เดือน) ข้อควรระวัง: การทำนายจากอุณหภูมิสูงใช้ได้เมื่อกลไกและลำดับปฏิกิริยาไม่เปลี่ยนในช่วงอุณหภูมิ และไม่มีการเปลี่ยนสถานะ/ความชื้นมาเกี่ยวข้อง",
      w: [
        "เป็น t90 ที่ 60°C (0.1054/0.020) ยังไม่ได้แปลงไป 25°C",
        "ใช้กฎ Q10 = 2 (2^3.5 ≈ 11.3) ซึ่งประเมินต่ำกว่าเมื่อ Ea จริง 80 kJ/mol (เทียบ Q10 ≈ 2.7–3)",
        "ถูก — k25 = 6.74 × 10⁻⁴ day⁻¹ → t90 = 0.1054/k25 ≈ 156 วัน",
        "เป็น t1/2 ที่ 25°C (0.693/k25) ไม่ใช่ t90",
        "เป็นเวลาที่ยาเหลือ 10% (2.303/k25) ไม่ใช่ t90",
      ],
      k: "Arrhenius ใช้ Kelvin เสมอ: ln(k2/k1) = −Ea/R (1/T2 − 1/T1) แล้ว t90 = 0.105/k",
      d: "hard",
      ref: "Martin's Physical Pharmacy and Pharmaceutical Sciences 7th ed.; Connors, Chemical Stability of Pharmaceuticals",
      c: [
        "T1 = 60 + 273.15 = 333.15 K; T2 = 25 + 273.15 = 298.15 K",
        "1/T2 − 1/T1 = 0.0033540 − 0.0030017 = 3.522 × 10⁻⁴ K⁻¹",
        "Ea/R = 80,000 / 8.314 = 9,622 K",
        "ln(k25/k60) = −9,622 × 3.522 × 10⁻⁴ = −3.39 → k25/k60 = 0.0337",
        "k25 = 0.020 × 0.0337 = 6.74 × 10⁻⁴ day⁻¹",
        "t90 = 0.1054 / 6.74 × 10⁻⁴ = 156 วัน",
      ],
    },
    {
      t: "No intermediate condition when long-term is 30°C",
      p: "บริษัทยื่นทะเบียนยาเม็ดในอาเซียน ทำ long-term ที่ 30°C/75%RH และ accelerated ที่ 40°C/75%RH พบ significant change ที่ accelerated เดือนที่ 6 ขั้นตอนข้อใดสอดคล้องกับ ICH Q1A(R2)/ASEAN guideline มากที่สุด",
      o: [
        "ไม่มี intermediate condition ให้ทำ; กำหนด shelf life จากข้อมูล long-term จริงที่ 30°C/75%RH โดยไม่ extrapolate จากข้อมูลเร่ง",
        "ต้องเพิ่ม intermediate 30°C/65%RH 12 เดือนก่อนกำหนด shelf life",
        "ต้องเพิ่ม intermediate 25°C/60%RH เพื่อเทียบกับเขต Zone II",
        "ใช้ข้อมูล accelerated คำนวณ shelf life ด้วย Arrhenius แทน long-term",
        "ผลที่ accelerated ไม่มีผลต่อการกำหนด shelf life เพราะ long-term ยังผ่าน",
      ],
      a: 0,
      r: "ICH Q1A(R2) ระบุว่า intermediate condition (30°C/65%RH) ใช้เมื่อ long-term คือ 25°C/60%RH และเกิด significant change ที่ accelerated แต่ถ้า long-term เป็น 30°C/65%RH หรือ 30°C/75%RH (ตาม Zone IVb ที่อาเซียนใช้) จะไม่มี intermediate condition\n\nเมื่อเกิด significant change ที่ accelerated ICH Q1E ระบุว่าไม่ควรอาศัยการ extrapolate เกินข้อมูล long-term ดังนั้น shelf life ต้องอิงข้อมูล real-time ที่ 30°C/75%RH และผล accelerated ยังใช้ประเมินผลของ excursion ระยะสั้นระหว่างขนส่งได้",
      w: [
        "ถูก — long-term 30°C/75%RH ไม่มี intermediate และ significant change ที่ accelerated ทำให้ต้องอิงข้อมูล long-term จริง",
        "30°C/65%RH เป็นสภาวะที่อ่อนกว่า long-term 30°C/75%RH ที่ใช้อยู่แล้ว จึงไม่ให้ข้อมูลเพิ่ม",
        "25°C/60%RH เป็น long-term ของ Zone I/II ไม่ใช่ intermediate และไม่แทนสภาวะในอาเซียน",
        "Significant change ที่ accelerated บ่งว่ากลไกอาจไม่ linear ตาม Arrhenius การทำนายจากข้อมูลเร่งจึงไม่น่าเชื่อถือ",
        "Significant change ที่ accelerated มีผลจำกัดการ extrapolate และต้องอภิปรายในเอกสาร ไม่ใช่ละเลย",
      ],
      k: "Long-term 30°C/65% หรือ 30°C/75% → ไม่มี intermediate; significant change ที่ accelerated → ห้าม extrapolate เกินข้อมูล long-term",
      d: "hard",
      ref: "ICH Q1A(R2) Section 2.2.7; ICH Q1E; ASEAN Guideline on Stability Study of Drug Product (R1)",
    },
    {
      t: "Hydrate conversion of carbamazepine on storage",
      p: "ยาเม็ด carbamazepine (anhydrous form III) ที่บรรจุใน PVC blister หลังเก็บที่ 30°C/75%RH 6 เดือน พบ dissolution ลดลงมาก และ XRPD พบ peak ใหม่ แม้ assay และ degradant ปกติ คำอธิบายใดน่าจะเป็นสาเหตุที่สุด",
      o: [
        "เกิด solution-mediated/solid-state conversion เป็น carbamazepine dihydrate ซึ่งละลายช้ากว่า เพราะความชื้นซึมผ่าน PVC",
        "เกิด hydrolysis ของ carbamazepine เป็น iminostilbene ทำให้ dissolution ต่ำ",
        "ตัวยาเกิด photolysis จากแสงผ่าน PVC ใส",
        "เกิด Maillard reaction ระหว่าง carbamazepine กับ excipient",
        "ตัวยาเปลี่ยนเป็น amorphous ทำให้ละลายช้าลง",
      ],
      a: 0,
      r: "การเปลี่ยน solid form ระหว่างเก็บเป็นปัญหา physical stability ที่ assay ไม่ช่วยตรวจจับ Carbamazepine anhydrous ดูดความชื้นแล้วเปลี่ยนเป็น dihydrate ซึ่งเป็นรูปแบบที่เสถียรในน้ำและมี solubility/dissolution rate ต่ำกว่า มีรายงานความล้มเหลวทางคลินิกจากเม็ดที่เก็บในที่ชื้น\n\nหลักฐานคือ XRPD peak ใหม่ (lattice เปลี่ยน) ขณะที่เคมีไม่เปลี่ยน การแก้: pack กันความชื้น (Alu-Alu/ขวด + desiccant), ฉลาก 'Protect from moisture' และเพิ่ม dissolution/solid-form monitoring ใน stability protocol",
      w: [
        "ถูก — anhydrous → dihydrate ในที่ชื้นทำให้ dissolution ลดลง สอดคล้องกับ XRPD ที่เปลี่ยน ขณะ assay ปกติ",
        "ถ้าเป็น chemical degradation ต้องพบ assay ลดและ degradant เพิ่ม ซึ่งโจทย์ระบุว่าปกติ",
        "Photolysis เป็นการเปลี่ยนเคมี ต้องเห็น degradant ไม่ใช่ XRPD peak ใหม่โดย assay ปกติ",
        "Carbamazepine ไม่มีหมู่ amine อิสระแบบ primary/secondary ที่ทำ Maillard และ assay ไม่ลด",
        "Amorphous จะละลายเร็วขึ้นและให้ halo ใน XRPD ไม่ใช่ peak ใหม่",
      ],
      k: "Polymorph/hydrate conversion ระหว่างเก็บ → dissolution เปลี่ยนโดย assay ปกติ; ต้องติดตามด้วย XRPD/dissolution และใช้ pack กันชื้น",
      d: "hard",
      ref: "Aulton's Pharmaceutics 6th ed., Ch. Solid-state properties; Brittain HG, Polymorphism in Pharmaceutical Solids 2nd ed.",
    },
  ],
];
