import type { Ip1MockDomainContent } from "@/lib/ip1-mock/types";

export const STERILE: Ip1MockDomainContent = [
  // Mock Set 1
  [
    {
      t: "NaCl equivalent isotonic adjustment",
      p: "เภสัชกรต้องเตรียม Procaine HCl injection 2% w/v ปริมาตร 50 mL ให้ isotonic ด้วย NaCl กำหนดให้ NaCl equivalent (E) ของ procaine HCl = 0.21 ต้องเติม NaCl กี่ mg",
      o: ["30 mg", "90 mg", "210 mg", "240 mg", "450 mg"],
      a: 3,
      r: "วิธี sodium chloride equivalent: E คือปริมาณ NaCl (g) ที่ให้ผลทาง osmotic เท่ากับยา 1 g สารละลาย 0.9% NaCl เป็น isotonic ดังนั้นปริมาตร 50 mL ต้องการ 'NaCl equivalent' รวม 0.45 g\n\nยาที่ใช้ = 2% × 50 mL = 1.0 g ให้ผลเทียบเท่า NaCl = 1.0 × 0.21 = 0.21 g จึงต้องเติม NaCl จริงอีก 0.45 − 0.21 = 0.24 g = 240 mg ขั้นตอนสำคัญคืออย่าลืมคูณ E กับน้ำหนักยา (ไม่ใช่ความเข้มข้น %) และหักออกจากปริมาณ NaCl ที่ต้องการทั้งหมดของปริมาตรนั้น",
      w: [
        "คิดน้ำหนักยาผิดเป็น 2 g (ตีความ 2% ว่า 2 g ต่อปริมาตรทั้งหมด) จึงหัก 0.42 g เหลือ 0.03 g",
        "คำนวณจากการคูณผิดขั้น เช่น 0.45 × 0.21 ≈ 0.09 g ซึ่งไม่ได้มีความหมายทาง isotonicity",
        "เป็นค่า NaCl equivalent ของตัวยา (1 g × 0.21) ไม่ใช่ปริมาณ NaCl ที่ต้องเติม",
        "ถูก — NaCl ที่ต้องการ 0.45 g ลบส่วนที่ยาให้ไปแล้ว 0.21 g เหลือต้องเติม 0.24 g",
        "เป็นปริมาณ NaCl สำหรับทำ 50 mL ให้ isotonic โดยไม่หักผลของยา จะได้สารละลาย hypertonic",
      ],
      k: "NaCl ที่ต้องเติม = (0.009 × V mL) − Σ(น้ำหนักยา g × E)",
      d: "medium",
      ref: "Remington: The Science and Practice of Pharmacy 23rd ed., Ch. Tonicity, Osmoticity, Osmolality and Osmolarity",
      c: [
        "NaCl ที่ต้องการสำหรับ 50 mL = 0.9/100 × 50 = 0.45 g",
        "น้ำหนัก procaine HCl = 2/100 × 50 = 1.0 g",
        "NaCl equivalent ของยา = 1.0 × 0.21 = 0.21 g",
        "NaCl ที่ต้องเติม = 0.45 − 0.21 = 0.24 g = 240 mg",
      ],
    },
    {
      t: "Endotoxin limit K/M",
      p: "ยาฉีดปฏิชีวนะชนิด IV bolus มีขนาดยาสูงสุด 25 mg/kg ต่อครั้ง (ให้ภายใน 1 ชั่วโมง) ห้อง QC ต้องกำหนด endotoxin limit ตาม USP <85> ข้อใดถูกต้อง",
      o: ["0.0029 EU/mg", "0.008 EU/mg", "0.2 EU/mg", "14 EU/mg", "125 EU/mg"],
      a: 2,
      r: "Endotoxin limit (EL) = K/M โดย K คือ threshold pyrogenic dose (5 EU/kg สำหรับทางให้ยา parenteral ทั่วไป และ 0.2 EU/kg สำหรับ intrathecal) และ M คือขนาดยาสูงสุดต่อ kg ที่ให้ภายใน 1 ชั่วโมง\n\nกรณีนี้ EL = 5 EU/kg ÷ 25 mg/kg = 0.2 EU/mg หน่วย kg ตัดกันไปแล้ว จึงไม่ต้องคูณหรือหารน้ำหนักตัวอีก ค่า M ต้องเป็นขนาดยาสูงสุดต่อชั่วโมง ถ้าให้ยาหลายครั้งใน 1 ชั่วโมงต้องรวมกัน",
      w: [
        "นำ 0.2 EU/mg ไปหารด้วยน้ำหนักตัว 70 kg ซ้ำอีกครั้ง ซึ่งผิดเพราะ K และ M เป็นค่าต่อ kg อยู่แล้ว",
        "ใช้ K = 0.2 EU/kg ซึ่งเป็นค่าสำหรับ intrathecal ไม่ใช่ IV",
        "ถูก — EL = K/M = 5/25 = 0.2 EU/mg",
        "คูณ 0.2 EU/mg ด้วยน้ำหนักตัว 70 kg ซึ่งผิดหน่วยและหลักการ",
        "นำ K × M (5 × 25) แทนการหาร ได้ค่าที่ไม่มีความหมายและหย่อนเกินจริงมาก",
      ],
      k: "EL = K/M; K = 5 EU/kg (parenteral ทั่วไป), 0.2 EU/kg (intrathecal); M = ขนาดยาสูงสุด/kg/ชั่วโมง",
      d: "medium",
      ref: "USP <85> Bacterial Endotoxins Test",
      c: ["K = 5 EU/kg (IV)", "M = 25 mg/kg/h", "EL = 5 ÷ 25 = 0.2 EU/mg"],
    },
    {
      t: "D-value from survivor curve",
      p: "ในการศึกษา thermal resistance ของ spore ที่ 121 °C พบจำนวน spore รอดชีวิต 2.0 × 10^6 CFU ที่เวลา 0 นาที และเหลือ 4.0 × 10^2 CFU หลังให้ความร้อน 10 นาที (survivor curve เป็น first-order) D121 ของ spore นี้มีค่าประมาณเท่าใด",
      o: ["0.37 min", "1.2 min", "2.5 min", "2.7 min", "3.7 min"],
      a: 3,
      r: "D-value คือเวลาที่ทำให้จำนวนจุลชีพลดลง 1 log (90%) ที่อุณหภูมิกำหนด คำนวณได้จาก D = t / (log N0 − log N)\n\nlog(2.0 × 10^6) = 6.301 และ log(4.0 × 10^2) = 2.602 ต่างกัน 3.699 log ดังนั้น D = 10/3.699 ≈ 2.7 นาที กับดักที่พบบ่อยคือปัด log reduction เป็นเลขจำนวนเต็ม (4 log) ทำให้ได้ 2.5 นาที หรือสับสนว่า log reduction คือ D-value เอง",
      w: [
        "กลับเศษส่วน (log reduction ÷ เวลา = 3.699/10) ได้เป็น 'log ต่อนาที' ไม่ใช่ D-value",
        "ใช้ natural log (ln reduction ≈ 8.52) แทน log ฐาน 10 ทำให้ D ต่ำเกินจริง",
        "ประมาณ log reduction เป็น 4 log (นับเลขชี้กำลังอย่างเดียว) โดยไม่คิดสัมประสิทธิ์ 2.0 และ 4.0",
        "ถูก — log reduction = 6.301 − 2.602 = 3.699; D = 10/3.699 ≈ 2.7 นาที",
        "เป็นจำนวน log reduction (3.7) ไม่ใช่เวลาต่อ 1 log",
      ],
      k: "D = t / (log N0 − log Nt); อย่าปัด log reduction โดยลืมสัมประสิทธิ์หน้าเลขยกกำลัง",
      d: "hard",
      ref: "USP <1229.1> Steam Sterilization by Direct Contact; USP <1229> Sterilization of Compendial Articles",
      c: [
        "log N0 = log(2.0 × 10^6) = 6.301",
        "log Nt = log(4.0 × 10^2) = 2.602",
        "log reduction = 6.301 − 2.602 = 3.699",
        "D121 = 10 min ÷ 3.699 = 2.70 min",
      ],
    },
    {
      t: "Glass container types",
      p: "ยาฉีดชนิดสารละลายน้ำ pH 8.0 บรรจุ ampule และจะผ่าน terminal sterilization ด้วย autoclave ควรเลือกภาชนะแก้วชนิดใดเหมาะสมที่สุดตามเภสัชตำรับ",
      o: [
        "Type I borosilicate glass",
        "Type II treated soda-lime glass",
        "Type III soda-lime glass",
        "Type NP general-purpose soda-lime glass",
        "แก้วสีชาชนิด soda-lime ทั่วไป",
      ],
      a: 0,
      r: "Type I (borosilicate) มี hydrolytic resistance สูงสุด เพราะมี SiO2 และ B2O3 สูง ปลดปล่อย alkali น้อย จึงเหมาะกับยาฉีดทุกชนิด โดยเฉพาะสารละลายน้ำที่มี pH เป็นกลางถึงด่างและต้องผ่าน autoclave\n\nType II เป็น soda-lime ที่ผ่าน surface treatment (dealkalization ด้วย sulfur) ใช้ได้กับสารละลายน้ำที่เป็นกรดหรือกลางและไม่ autoclave ซ้ำ ส่วน Type III ใช้กับผงแห้งหรือยาในน้ำมัน Type NP ไม่ใช้กับ parenteral",
      w: [
        "ถูก — borosilicate ทนการชะ alkali ได้ดีที่สุด เหมาะกับสารละลายน้ำ pH สูงที่ผ่าน autoclave",
        "ความทนทานมาจากผิวที่ผ่านการ treat เท่านั้น ไม่เหมาะกับสารละลายด่างที่ผ่านความร้อนซึ่งกัดผิวได้",
        "ปลดปล่อย alkali มาก ใช้กับผงแห้งหรือ non-aqueous parenteral ไม่ใช่สารละลายน้ำ pH สูง",
        "เป็นแก้วสำหรับ non-parenteral (เช่น ยารับประทาน) ไม่ใช้กับยาฉีด",
        "สีชาช่วยกันแสงแต่ไม่ได้แก้ปัญหา hydrolytic resistance ของ soda-lime",
      ],
      k: "Type I = ยาฉีดทุกชนิด; Type II = สารละลายน้ำกรด/กลาง; Type III = ผงแห้ง/น้ำมัน; NP = ไม่ใช่ยาฉีด",
      d: "easy",
      ref: "USP <660> Containers—Glass; Ph. Eur. 3.2.1 Glass containers for pharmaceutical use",
    },
    {
      t: "Sterility test media",
      p: "ห้องปฏิบัติการทดสอบ sterility test ของยาฉีดตาม USP <71> ข้อใดเป็นการเลือกอาหารเลี้ยงเชื้อและสภาวะบ่มที่ถูกต้อง",
      o: [
        "Fluid thioglycollate medium บ่ม 30–35 °C และ Soybean-casein digest medium บ่ม 20–25 °C นาน 14 วัน",
        "Soybean-casein digest medium บ่ม 30–35 °C เพียงชนิดเดียว นาน 7 วัน",
        "Fluid thioglycollate medium บ่ม 20–25 °C และ Sabouraud dextrose agar บ่ม 30–35 °C นาน 5 วัน",
        "Nutrient agar plate บ่ม 37 °C นาน 48 ชั่วโมง แล้วนับโคโลนี",
        "Fluid thioglycollate medium บ่ม 30–35 °C เพียงชนิดเดียว นาน 14 วัน",
      ],
      a: 0,
      r: "USP <71>/Ph. Eur. 2.6.1 ใช้อาหาร 2 ชนิดคู่กัน: Fluid thioglycollate medium (FTM) สำหรับ anaerobic และ aerobic bacteria บ่ม 30–35 °C และ Soybean-casein digest medium (SCDM หรือ TSB) สำหรับเชื้อรา และ aerobic bacteria บ่ม 20–25 °C บ่มอย่างน้อย 14 วัน\n\nเหตุที่ต้องใช้ 2 อาหาร 2 อุณหภูมิ เพราะต้องครอบคลุมเชื้อที่ต้องการออกซิเจนต่างกัน และเชื้อราเติบโตได้ดีที่อุณหภูมิต่ำกว่า การทดสอบเป็นแบบ qualitative (มี/ไม่มี growth) ไม่ใช่การนับโคโลนี",
      w: [
        "ถูก — FTM 30–35 °C + SCDM 20–25 °C บ่มไม่น้อยกว่า 14 วัน",
        "ขาด FTM สำหรับ anaerobes และระยะเวลาบ่มสั้นเกินไป",
        "สลับอุณหภูมิ และ Sabouraud agar ไม่ใช่อาหารของ compendial sterility test",
        "เป็นแนวทาง bioburden/plate count ไม่ใช่ sterility test",
        "ขาด SCDM ที่บ่มอุณหภูมิต่ำเพื่อตรวจเชื้อราและ aerobes",
      ],
      k: "Sterility test: FTM 30–35 °C (anaerobes/aerobes) + SCDM 20–25 °C (fungi/aerobes) ≥ 14 วัน",
      d: "easy",
      ref: "USP <71> Sterility Tests; Ph. Eur. 2.6.1",
    },
    {
      t: "Bubble point test interpretation",
      p: "หลังกรอง bulk solution ผ่าน 0.22 µm PVDF sterilizing-grade filter ทำ post-use bubble point test (ใช้น้ำเป็น wetting fluid) ได้ 2.6 bar ขณะที่ค่าต่ำสุดที่ผู้ผลิต filter กำหนดคือ 3.5 bar ข้อสรุปและการดำเนินการใดเหมาะสมที่สุด",
      o: [
        "ผลบ่งชี้ว่ามีรูขนาดใหญ่กว่ากำหนดหรือการ wetting ไม่สมบูรณ์ ให้ flush/re-wet แล้วทดสอบซ้ำตาม SOP หากยังต่ำถือว่า filter ไม่ integral และต้องสอบสวนผลกระทบต่อ batch",
        "ค่าต่ำกว่าแสดงว่ารูเล็กกว่ากำหนด filter มีประสิทธิภาพสูงขึ้น ปล่อย batch ได้",
        "Bubble point ไม่เกี่ยวกับขนาดรู จึงใช้ผล sterility test ตัดสินแทนได้",
        "ให้ปรับ specification ลงเป็น 2.5 bar เพราะเป็นผลหลังใช้งานซึ่งต่ำลงเสมอ",
        "เปลี่ยนไปใช้ 0.45 µm filter ใน batch ถัดไปเพื่อให้ bubble point ผ่าน",
      ],
      a: 0,
      r: "Bubble point คือความดันต่ำสุดที่ gas ขับของเหลวออกจากรูที่ใหญ่ที่สุดของ membrane ที่เปียกอยู่ (P = 4kγcosθ/d) ความดันจึงแปรผกผันกับขนาดรู ค่าที่ต่ำกว่า specification หมายถึงมีรูใหญ่กว่าที่ validated หรือมีรอยรั่ว/seal เสีย\n\nอย่างไรก็ตาม bubble point ต่ำเทียมได้จากการ wetting ไม่สมบูรณ์หรือ product ตกค้างที่ลด surface tension จึงต้อง flush ด้วย wetting fluid ที่กำหนดแล้วทดสอบซ้ำตาม procedure หากยืนยันว่า fail ต้องถือว่า sterility assurance ของ batch ถูกกระทบ และต้องสอบสวน (เช่น พิจารณา refiltration ตามที่ validated) ไม่สามารถใช้ sterility test มาชดเชยได้",
      w: [
        "ถูก — bubble point ต่ำ = รูใหญ่/รอยรั่ว หรือ wetting ไม่ดี ต้องทดสอบซ้ำอย่างถูกวิธีและสอบสวนผลกระทบหากยืนยัน",
        "ตีความกลับด้าน รูเล็กลงจะทำให้ bubble point สูงขึ้น ไม่ใช่ต่ำลง",
        "Bubble point สัมพันธ์โดยตรงกับขนาดรูที่ใหญ่ที่สุด และ sterility test มีข้อจำกัดเชิงสถิติ ไม่ใช้แทน integrity test",
        "การลด specification เพื่อให้ผลผ่านไม่มีหลักวิชาการรองรับและเป็นการปิดบังความล้มเหลว",
        "0.45 µm ไม่ใช่ sterilizing-grade filter และไม่ได้แก้ปัญหา batch ที่กรองไปแล้ว",
      ],
      k: "Bubble point แปรผกผันกับขนาดรู; ต่ำกว่าเกณฑ์ = สงสัย breach — ตรวจ wetting ก่อนสรุปและสอบสวน batch",
      d: "medium",
      ref: "PDA Technical Report No. 26 Sterilizing Filtration of Liquids; EU GMP Annex 1 (2022) section 8",
    },
    {
      t: "Collapse temperature in primary drying",
      p: "สูตรยา lyophilized ที่มี sucrose เป็น lyoprotectant หลัก วัด collapse temperature (Tc) ด้วย freeze-drying microscopy ได้ −32 °C ข้อใดเป็นแนวทางตั้งค่า primary drying ที่เหมาะสมที่สุด",
      o: [
        "ควบคุม product temperature ให้ต่ำกว่า Tc ประมาณ 2–5 °C (เช่น −35 °C) โดยปรับ shelf temperature และ chamber pressure",
        "ตั้ง shelf temperature ที่ −32 °C ตลอด primary drying เพราะ shelf กับ product มีอุณหภูมิเท่ากัน",
        "ควบคุม product temperature ให้สูงกว่า Tc เล็กน้อยเพื่อเร่ง sublimation",
        "ควบคุม product temperature ที่ 0 °C เพราะ sucrose เป็น crystalline ไม่ collapse",
        "เพิ่ม chamber pressure ให้สูงใกล้ความดันบรรยากาศเพื่อเพิ่ม heat transfer สูงสุด",
      ],
      a: 0,
      r: "ในสูตร amorphous เช่น sucrose ค่า critical คือ collapse temperature (ใกล้ Tg' ของ freeze-concentrate) ถ้า product temperature ที่ sublimation front สูงกว่า Tc โครงสร้างจะยุบ เกิด cake collapse ความชื้นค้างสูงและ reconstitution ช้า\n\nแนวทางคือให้ product temperature ต่ำกว่า Tc ประมาณ 2–5 °C ซึ่งเป็นการแลกระหว่างความปลอดภัยกับความเร็ว เพราะทุก 1 °C ที่ product อุ่นขึ้นจะเร่ง primary drying ได้ราว 13% ทั้งนี้ product temperature ต่ำกว่า shelf temperature มากเนื่องจาก sublimation ใช้ความร้อนแฝง จึงควบคุมผ่าน shelf temperature ร่วมกับ chamber pressure",
      w: [
        "ถูก — product temperature ต้องอยู่ต่ำกว่า Tc เล็กน้อย โดยใช้ shelf temperature และ pressure เป็นตัวควบคุม",
        "Product temperature ระหว่าง sublimation ต่ำกว่า shelf มาก ตั้ง shelf ที่ Tc จะทำให้การอบช้ามากโดยไม่จำเป็น",
        "สูงกว่า Tc ทำให้ cake collapse แม้ sublimation จะเร็วขึ้น",
        "Sucrose เป็น amorphous ใน freeze-concentrate ไม่ใช่ crystalline จึง collapse ได้ที่อุณหภูมิสูง",
        "Pressure สูงมากทำให้ product temperature สูงเกิน Tc และลดแรงขับของการระเหิด",
      ],
      k: "Primary drying: product temperature < Tc (หรือ Teu ของสูตร crystalline) 2–5 °C; ควบคุมด้วย shelf T + chamber P",
      d: "medium",
      ref: "Tang X, Pikal MJ. Design of freeze-drying processes for pharmaceuticals: practical advice. Pharm Res 2004;21:191–200",
    },
    {
      t: "Preservative-free parenteral routes",
      p: "ผู้ผลิตต้องการพัฒนายาฉีดหลายรูปแบบจาก API เดียวกัน รูปแบบใดต่อไปนี้ห้ามเติม antimicrobial preservative ในตำรับ",
      o: [
        "ยาฉีดสำหรับ intrathecal ขนาด single-dose 5 mL",
        "ยาฉีด IM multiple-dose vial ขนาด 10 mL",
        "ยาฉีด SC multiple-dose cartridge ขนาด 3 mL",
        "ยาฉีด IV multiple-dose vial ขนาด 20 mL",
        "ยาฉีด IM single-dose vial ที่บรรจุแบบ aseptic ขนาด 2 mL",
      ],
      a: 0,
      r: "ยาที่ให้เข้าสู่ระบบประสาทส่วนกลางหรือบริเวณที่ไวต่อสารพิษ ได้แก่ intrathecal, intracisternal, epidural และ intraocular ต้องปราศจาก preservative เพราะ preservative เช่น benzyl alcohol, phenol, parabens มี neurotoxicity หรือทำลายเนื้อเยื่อตา\n\nนอกจากนี้ LVP ก็ไม่เติม preservative เพราะปริมาณรวมที่ผู้ป่วยได้รับจะสูงเกินขนาดปลอดภัย ส่วน single-dose container อื่น ๆ ไม่จำเป็นต้องมี preservative แต่ก็ไม่ได้ถูกห้าม ขณะที่ multiple-dose ต้องมี preservative",
      w: [
        "ถูก — intrathecal ต้อง preservative-free เพราะสารกันเสียเป็นพิษต่อระบบประสาท",
        "Multiple-dose ต้องมี preservative เพื่อป้องกันการปนเปื้อนจากการเจาะซ้ำ",
        "Multiple-dose cartridge (เช่น insulin) ต้องมี preservative เช่น m-cresol",
        "IV multiple-dose vial ขนาดเล็กใส่ preservative ได้และจำเป็นต้องใส่",
        "Single-dose IM ไม่จำเป็นต้องใส่ preservative แต่ไม่ได้ถูกห้ามโดยหลักการ",
      ],
      k: "ห้ามใส่ preservative: intrathecal, intracisternal, epidural, intraocular และ LVP",
      d: "medium",
      ref: "USP <1> Injections and Implanted Drug Products; Remington 23rd ed., Parenteral Preparations",
    },
    {
      t: "Isotonic vs iso-osmotic (boric acid)",
      p: "สารละลาย boric acid 1.9% w/v มีจุดเยือกแข็งลดลง 0.52 °C เท่ากับ 0.9% NaCl แต่เมื่อนำไปทดสอบกับเม็ดเลือดแดงพบ hemolysis เกือบทั้งหมด ข้อใดอธิบายได้ดีที่สุด",
      o: [
        "Boric acid ซึมผ่านเยื่อหุ้มเม็ดเลือดแดงได้อย่างอิสระ สารละลายจึง iso-osmotic แต่ไม่ isotonic ต่อเม็ดเลือดแดง",
        "Boric acid แตกตัวเป็นไอออนสมบูรณ์ทำให้ osmotic pressure จริงสูงกว่าที่วัดได้",
        "การวัดจุดเยือกแข็งไม่สัมพันธ์กับ osmotic pressure ของสารละลายใด ๆ",
        "Boric acid ทำให้ pH เป็นด่างจัดจนเยื่อหุ้มเซลล์ถูกย่อยสลาย",
        "สารละลายนี้ hypertonic จึงทำให้เม็ดเลือดแดงเหี่ยวและแตก",
      ],
      a: 0,
      r: "Iso-osmotic หมายถึงมี osmotic pressure (colligative property) เท่ากับเลือดเมื่อวัดผ่าน ideal semipermeable membrane ส่วน isotonic หมายถึงไม่ทำให้ปริมาตรเซลล์เปลี่ยนเมื่อสัมผัสกับเยื่อหุ้มเซลล์จริง\n\nสารที่ซึมผ่านเยื่อหุ้มเม็ดเลือดแดงได้ เช่น boric acid, urea, glycerin, ethanol, ammonium chloride จะเคลื่อนเข้าเซลล์ ทำให้น้ำตามเข้าไปจนเซลล์บวมและแตก จึงมีพฤติกรรมเหมือน hypotonic แม้ค่า osmotic จะเท่ากัน อย่างไรก็ตาม 1.9% boric acid ใช้เป็น vehicle ของยาตาได้เพราะเยื่อบุตาตอบสนองต่างจากเม็ดเลือดแดง",
      w: [
        "ถูก — สารที่ผ่านเยื่อหุ้มเซลล์ได้ไม่ช่วยรักษาสมดุล tonicity จึงเกิด hemolysis แม้ iso-osmotic",
        "Boric acid เป็นกรดอ่อนมาก (pKa ≈ 9.2) แตกตัวน้อยมาก ไม่ใช่สาเหตุ",
        "Freezing point depression เป็น colligative property ที่สัมพันธ์กับ osmotic pressure โดยตรง",
        "สารละลาย boric acid มี pH เป็นกรดอ่อน ไม่ใช่ด่างจัด",
        "Hypertonic ทำให้เซลล์เหี่ยว (crenation) ไม่ใช่ hemolysis และสารละลายนี้ iso-osmotic",
      ],
      k: "Iso-osmotic ≠ isotonic: สารที่ซึมผ่านเยื่อหุ้ม RBC (boric acid, urea, glycerin) ทำให้ hemolysis",
      d: "hard",
      ref: "Martin's Physical Pharmacy and Pharmaceutical Sciences 7th ed., Ch. Buffered and Isotonic Solutions",
    },
    {
      t: "Sterilization method decision tree",
      p: "ยาฉีดสารละลายน้ำใน glass vial เมื่อผ่าน autoclave 121 °C 15 นาทีพบ degradation product เกิน specification แต่หากใช้ cycle 115 °C ที่ให้ F0 = 12 นาที ผลิตภัณฑ์ยังผ่าน specification บริษัทเสนอเปลี่ยนเป็น sterile filtration ร่วมกับ aseptic filling ตามแนวทาง EMA sterilisation decision tree ข้อใดถูกต้อง",
      o: [
        "ต้องใช้ terminal moist heat cycle ที่ F0 ≥ 8 นาทีซึ่งพิสูจน์ได้ว่าให้ SAL ≤ 10^-6 พร้อมควบคุม bioburden แทนการเลือก aseptic processing",
        "เลือก aseptic processing ได้ทันทีเพราะสูตรไม่ทน 121 °C 15 นาที",
        "ใช้ dry heat 160 °C 2 ชั่วโมงแทน เพราะไม่มีความชื้นที่เร่ง hydrolysis",
        "ใช้ sterile filtration แล้วตามด้วย sterility test 100% ของทุก vial",
        "ลดความเข้มงวดโดยใช้ cycle F0 = 3 นาทีเพื่อลด degradation ให้มากที่สุด",
      ],
      a: 0,
      r: "แนวทาง EMA (Guideline on the sterilisation of the medicinal product, active substance, excipient and primary container, 2019) กำหนดลำดับความสำคัญ: เริ่มจาก reference cycle 121 °C ≥ 15 นาที ถ้าไม่ได้ ให้พิจารณา moist heat ที่ F0 ≥ 8 นาทีซึ่งทำ SAL ≤ 10^-6 ได้ (ต้องมีการควบคุม bioburden และความทนความร้อนของเชื้อ) ถ้ายังไม่ได้จึงพิจารณาวิธีอื่น เช่น irradiation และสุดท้ายคือ sterile filtration + aseptic processing\n\nเนื่องจาก terminal sterilization ให้ sterility assurance สูงกว่า aseptic processing อย่างชัดเจน การที่สูตรทน cycle F0 = 12 ได้จึงต้องเลือก terminal sterilization ไม่ใช่กระโดดไป aseptic processing",
      w: [
        "ถูก — decision tree กำหนดให้ใช้ moist heat ที่ F0 ≥ 8 (SAL ≤ 10^-6) ก่อนจะยอมรับ aseptic processing",
        "การไม่ทน reference cycle ยังไม่พอ ต้องพิสูจน์ก่อนว่าไม่สามารถใช้ cycle F0 ≥ 8 ได้",
        "Dry heat ไม่เหมาะกับสารละลายน้ำในภาชนะปิดและอุณหภูมิสูงกว่ามาก",
        "Sterility test เป็นการทดสอบทำลายและมีข้อจำกัดทางสถิติ ทำ 100% ไม่ได้และไม่เพิ่ม assurance ของกระบวนการ",
        "F0 = 3 ไม่ถึงเกณฑ์ขั้นต่ำ (F0 ≥ 8 พร้อม SAL ≤ 10^-6) ของ terminal sterilization",
      ],
      k: "EMA decision tree: 121 °C/15 min → F0 ≥ 8 (SAL ≤ 10^-6) → วิธีอื่น → filtration + aseptic เป็นทางเลือกสุดท้าย",
      d: "hard",
      ref: "EMA/CHMP/CVMP/QWP/850374/2015 Guideline on the sterilisation of the medicinal product, active substance, excipient and primary container (2019)",
    },
  ],
  // Mock Set 2
  [
    {
      t: "Freezing point depression isotonicity",
      p: "สารละลายยา A 1% w/v มีจุดเยือกแข็งลดลง (ΔTf) 0.11 °C ต้องการเตรียมยา A 2% w/v ปริมาตร 100 mL ให้ isotonic กับเลือด (ΔTf = 0.52 °C) โดยใช้ NaCl ซึ่ง 1% NaCl มี ΔTf = 0.58 °C ต้องเติม NaCl ประมาณเท่าใด",
      o: ["0.30 g", "0.38 g", "0.52 g", "0.71 g", "0.90 g"],
      a: 2,
      r: "วิธี freezing point depression ใช้สมการ W = (0.52 − a)/b โดย a คือ ΔTf ที่ได้จากตัวยาที่ความเข้มข้นจริง และ b คือ ΔTf ของ 1% NaCl (0.58 °C) ผลลัพธ์ W คือ %w/v ของ NaCl ที่ต้องเติม\n\nยา 2% ให้ ΔTf = 2 × 0.11 = 0.22 °C (สมมติว่าเป็นสัดส่วนตรงในช่วงเจือจาง) ต้องการเพิ่มอีก 0.30 °C จึงต้องใช้ NaCl = 0.30/0.58 = 0.517% หรือประมาณ 0.52 g ใน 100 mL กับดักคือใช้ ΔTf ของยาที่ 1% แทนความเข้มข้นจริง",
      w: [
        "นำ ΔTf ที่ต้องการเพิ่ม (0.30 °C) มาใช้เป็นกรัมโดยตรง โดยไม่หารด้วย 0.58",
        "คิดเฉพาะ ΔTf ของยา (0.22/0.58) แทนที่จะเป็นส่วนที่ยังขาด",
        "ถูก — (0.52 − 0.22)/0.58 = 0.517% ≈ 0.52 g ต่อ 100 mL",
        "ใช้ ΔTf ของยาที่ 1% (0.11) แทนที่ 2% ได้ (0.52 − 0.11)/0.58 = 0.71 g ทำให้ hypertonic",
        "เป็นปริมาณ NaCl สำหรับ 100 mL โดยไม่หักผลของยา",
      ],
      k: "NaCl (%w/v) = (0.52 − ΔTf ยาที่ความเข้มข้นจริง) / 0.58",
      d: "medium",
      ref: "Remington: The Science and Practice of Pharmacy 23rd ed., Ch. Tonicity, Osmoticity, Osmolality and Osmolarity",
      c: [
        "ΔTf ของยา 2% = 2 × 0.11 = 0.22 °C",
        "ΔTf ที่ยังขาด = 0.52 − 0.22 = 0.30 °C",
        "NaCl = 0.30 / 0.58 = 0.517% w/v",
        "ใน 100 mL ต้องเติม NaCl ≈ 0.52 g",
      ],
    },
    {
      t: "Maximum valid dilution",
      p: "ยาฉีดผงแห้ง 1 g/vial ละลายด้วยน้ำ 20 mL (ไม่คิด displacement) ได้สารละลาย 50 mg/mL มี endotoxin limit 0.2 EU/mg ทดสอบด้วย gel-clot LAL ที่มี labeled sensitivity (λ) 0.125 EU/mL หากตัวอย่างมี interference ต้องเจือจาง ค่า maximum valid dilution (MVD) คือเท่าใด",
      o: ["1:1.6", "1:40", "1:80", "1:160", "1:400"],
      a: 2,
      r: "MVD = (Endotoxin limit × Concentration of sample) / λ เมื่อ EL มีหน่วย EU/mg ความเข้มข้นต้องมีหน่วย mg/mL จึงได้ค่าไม่มีหน่วย\n\nMVD = (0.2 EU/mg × 50 mg/mL) / 0.125 EU/mL = 80 หมายความว่าสามารถเจือจางตัวอย่างได้ถึง 1:80 เพื่อลด inhibition/enhancement โดยยังตรวจพบ endotoxin ที่ระดับ limit ได้ ถ้าต้องเจือจางมากกว่า MVD จึงจะหายจาก interference แสดงว่าวิธีนั้นใช้ไม่ได้ ต้องหาวิธี neutralize อื่นหรือใช้ reagent ที่ไวกว่า (λ ต่ำกว่าจะได้ MVD สูงขึ้น)",
      w: [
        "หาร EL ด้วย λ โดยลืมคูณความเข้มข้นของตัวอย่าง",
        "ใช้ความเข้มข้นผิดเป็น 25 mg/mL หรือ λ ผิดเป็น 0.25 EU/mL ทำให้ได้ค่าครึ่งหนึ่ง",
        "ถูก — MVD = (0.2 × 50)/0.125 = 80",
        "ใช้ความเข้มข้น 100 mg/mL (ละลายด้วย 10 mL) ซึ่งไม่ตรงกับโจทย์",
        "คำนวณ concentration/λ (50/0.125) โดยไม่คูณ endotoxin limit",
      ],
      k: "MVD = (EL × C)/λ; λ ยิ่งต่ำ (reagent ไวขึ้น) MVD ยิ่งสูง เจือจางเกิน MVD ไม่ได้",
      d: "hard",
      ref: "USP <85> Bacterial Endotoxins Test; Ph. Eur. 2.6.14",
      c: [
        "C = 1000 mg / 20 mL = 50 mg/mL",
        "EL × C = 0.2 EU/mg × 50 mg/mL = 10 EU/mL",
        "MVD = 10 EU/mL ÷ 0.125 EU/mL = 80 → เจือจางได้สูงสุด 1:80",
      ],
    },
    {
      t: "Radiation sterilization dose",
      p: "Single-use plastic syringe ที่ sterilize ด้วย gamma irradiation (Cobalt-60) ขนาดรังสีที่ใช้เป็น reference dose ที่ยอมรับกันอย่างกว้างขวางสำหรับ SAL 10^-6 คือเท่าใด",
      o: ["2.5 kGy", "10 kGy", "25 kGy", "50 kGy", "100 kGy"],
      a: 2,
      r: "25 kGy (2.5 Mrad) เป็น dose ที่ใช้กันมาอย่างยาวนานและเป็นฐานของวิธี VDmax25 ใน ISO 11137-2 โดยต้องแสดงว่า bioburden ของผลิตภัณฑ์อยู่ในระดับที่ dose นี้ให้ SAL 10^-6 ได้\n\nการเลือก dose ต้องสมดุลระหว่าง lethality กับผลเสียต่อวัสดุ เช่น polypropylene เปราะ, PVC เปลี่ยนสี, glass เป็นสีน้ำตาล รังสีแกมมาทะลุทะลวงสูงจึง sterilize ได้ในบรรจุภัณฑ์ปิดสนิท และไม่ทิ้ง residue เหมือน EtO",
      w: [
        "ต่ำเกินไปสำหรับ SAL 10^-6 ของ bioburden ทั่วไป",
        "ต่ำกว่า reference dose; dose ระดับนี้ใช้ได้เฉพาะเมื่อ bioburden ต่ำมากและมีการ substantiate",
        "ถูก — 25 kGy เป็น reference sterilization dose (VDmax25) ที่ใช้แพร่หลาย",
        "สูงเกินความจำเป็นและเพิ่มการเสื่อมของพลาสติก",
        "สูงมากจนวัสดุส่วนใหญ่เสียหาย ไม่ใช่ dose มาตรฐาน",
      ],
      k: "Radiation sterilization: reference dose 25 kGy (ISO 11137 VDmax25); ระวังผลต่อวัสดุ",
      d: "easy",
      ref: "ISO 11137-2 Sterilization of health care products — Radiation — Establishing the sterilization dose",
    },
    {
      t: "SVP vs LVP definition",
      p: "ตาม USP ข้อใดเป็นคำจำกัดความของ Large-Volume Parenteral (LVP) ที่ถูกต้อง",
      o: [
        "ยาฉีด single-dose สำหรับให้ทาง IV ที่บรรจุมากกว่า 100 mL",
        "ยาฉีดทุกชนิดที่บรรจุมากกว่า 10 mL ไม่ว่าทางให้ยาใด",
        "ยาฉีด multiple-dose ที่บรรจุมากกว่า 30 mL",
        "ยาฉีดที่บรรจุ 50 mL ขึ้นไปและต้องมี preservative",
        "ยาฉีดผงแห้งสำหรับละลายที่ให้ปริมาตรหลังละลายเกิน 20 mL",
      ],
      a: 0,
      r: "USP นิยาม LVP ว่าเป็น single-dose injection สำหรับให้ทางหลอดเลือดดำ บรรจุมากกว่า 100 mL ส่วน SVP คือยาฉีดที่บรรจุ 100 mL หรือน้อยกว่า\n\nความแตกต่างนี้มีผลต่อข้อกำหนด เช่น LVP ห้ามมี preservative, มีเกณฑ์ particulate matter ต่อ mL (USP <788>) ต่างจาก SVP ที่คิดต่อ container และ LVP มักผ่าน terminal sterilization",
      w: [
        "ถูก — LVP = single-dose IV > 100 mL",
        "เกณฑ์ปริมาตรผิดและ LVP จำกัดเฉพาะทาง IV",
        "LVP เป็น single-dose ไม่ใช่ multiple-dose และ multiple-dose จำกัดไม่เกิน 30 mL",
        "LVP ห้ามใส่ preservative และเกณฑ์ปริมาตรไม่ใช่ 50 mL",
        "ผงแห้งสำหรับละลายจัดเป็น SVP โดยทั่วไป ไม่ใช่นิยาม LVP",
      ],
      k: "LVP = single-dose IV > 100 mL (ห้าม preservative); SVP ≤ 100 mL",
      d: "easy",
      ref: "USP <1> Injections and Implanted Drug Products; USP <788> Particulate Matter in Injections",
    },
    {
      t: "Biological indicator selection",
      p: "บริษัทจะ validate cycle ethylene oxide (EtO) สำหรับ sterilize ชุด administration set พลาสติก ควรเลือก biological indicator (BI) ชนิดใดตามแนวทางเภสัชตำรับ",
      o: [
        "Spores ของ Bacillus atrophaeus",
        "Spores ของ Geobacillus stearothermophilus",
        "Brevundimonas diminuta",
        "Spores ของ Clostridium sporogenes",
        "Candida albicans",
      ],
      a: 0,
      r: "BI ต้องเป็นเชื้อที่ทนต่อวิธี sterilization นั้นสูงและมีความต้านทานที่คงที่ Bacillus atrophaeus (เดิม B. subtilis var. niger) ใช้กับ EtO และ dry heat ส่วน Geobacillus stearothermophilus ใช้กับ moist heat (และ VHP) เพราะทนความร้อนชื้นสูง\n\nสำหรับ radiation เดิมใช้ Bacillus pumilus แต่ปัจจุบันเน้น dose setting จาก bioburden มากกว่า BI ส่วน B. diminuta เป็น challenge organism ของ filter validation ไม่ใช่ BI",
      w: [
        "ถูก — B. atrophaeus spores เป็น BI มาตรฐานของ EtO (และ dry heat)",
        "เป็น BI ของ moist heat ไม่เหมาะเป็น worst case ของ EtO",
        "เป็นแบคทีเรียขนาดเล็กใช้ทดสอบ bacterial retention ของ filter",
        "เป็น challenge organism สำหรับ growth promotion ของ FTM ไม่ใช่ BI ของ EtO",
        "เป็นยีสต์ใช้ใน growth promotion test ไม่ทนต่อ sterilization",
      ],
      k: "BI: moist heat = G. stearothermophilus; dry heat/EtO = B. atrophaeus; radiation (เดิม) = B. pumilus",
      d: "medium",
      ref: "USP <1229.5> Biological Indicators for Sterilization; ISO 11138 series",
    },
    {
      t: "Media fill acceptance criteria",
      p: "Aseptic process simulation (media fill) ของ vial filling line บรรจุ 12,000 units หลังบ่มพบ contaminated unit 1 unit ตาม EU GMP Annex 1 (2022) ข้อใดเป็นการตัดสินที่ถูกต้อง",
      o: [
        "ถือว่า APS ล้มเหลว ต้องสอบสวนหา root cause ประเมิน batch ที่ผลิตตั้งแต่ APS ที่ผ่านครั้งล่าสุด และต้องทำ APS ซ้ำให้ผ่านก่อนกลับมาผลิต",
        "ผ่าน เพราะอัตราการปนเปื้อน < 0.1% ตามเกณฑ์เดิม",
        "ผ่าน หากตรวจพบว่าเชื้อเป็นชนิดเดียวกับใน environmental monitoring",
        "ให้คัด unit ที่ปนเปื้อนทิ้งแล้วรายงานว่าผ่าน เพราะจำนวน unit มากกว่า 10,000",
        "ผ่านแบบมีเงื่อนไข โดยเพิ่มจำนวน sterility test ของ batch ถัดไปเป็นสองเท่า",
      ],
      a: 0,
      r: "EU GMP Annex 1 (2022) กำหนดเป้าหมายของ APS คือ zero growth และ contaminated unit ใด ๆ ทำให้ APS ล้มเหลว (ต่างจากแนวคิดเดิมที่ยอมรับอัตราปนเปื้อน < 0.1% ที่ 95% confidence)\n\nเมื่อล้มเหลวต้องสอบสวนอย่างครอบคลุม (การระบุชนิดเชื้อ, interventions, บุคลากร, environmental data, เครื่องจักร) ประเมินผลกระทบต่อ batch ที่ผลิตตั้งแต่ APS ที่ผ่านครั้งล่าสุด ดำเนิน CAPA และต้องทำ APS ซ้ำให้สำเร็จก่อนกลับมาผลิตเชิงพาณิชย์ ผล sterility test ของผลิตภัณฑ์ไม่สามารถชดเชยได้",
      w: [
        "ถูก — Annex 1 (2022): target zero growth; contaminated unit ใด ๆ = APS ล้มเหลว",
        "เกณฑ์อัตราส่วน < 0.1% เป็นแนวคิดเก่า ไม่สอดคล้องกับ Annex 1 ฉบับปัจจุบัน",
        "การรู้แหล่งเชื้อช่วยการสอบสวน แต่ไม่เปลี่ยนผลว่า APS ล้มเหลว",
        "การตัด unit ปนเปื้อนออกเป็นการบิดเบือนข้อมูล (data integrity)",
        "Sterility test มีความไวต่ำ เพิ่มจำนวนไม่ได้พิสูจน์ความสามารถของ aseptic process",
      ],
      k: "Annex 1 (2022): APS target = zero growth; 1 contaminated unit = fail → investigate, batch impact, repeat APS",
      d: "medium",
      ref: "EU GMP Annex 1 Manufacture of Sterile Medicinal Products (2022), section 9 Aseptic process simulation",
    },
    {
      t: "Cosolvent precipitation on dilution",
      p: "ยาฉีด diazepam 5 mg/mL ในตัวทำละลาย propylene glycol 40% และ ethanol 10% เมื่อพยาบาลเจือจางลงใน 0.9% NaCl 100 mL พบสารละลายขุ่น ข้อใดอธิบายปรากฏการณ์และแนวทางแก้ไขได้ถูกต้องที่สุด",
      o: [
        "การละลายในระบบ cosolvent ลดลงแบบ log-linear เมื่อสัดส่วน cosolvent ลดลง จึงลดลงเร็วกว่าความเข้มข้นยาที่ลดตามการเจือจาง เกิด supersaturation และตกตะกอน",
        "NaCl ทำปฏิกิริยาเคมีกับ diazepam เกิดเกลือที่ไม่ละลายน้ำ",
        "Propylene glycol ระเหยออกระหว่างผสมจึงเหลือยาเกินจุดอิ่มตัว",
        "Ethanol ทำให้ pH เปลี่ยนจนยาแตกตัวเป็นไอออนและตกตะกอน",
        "ความเข้มข้นยาหลังเจือจางสูงขึ้นเพราะ volume contraction ของ cosolvent",
      ],
      a: 0,
      r: "ในระบบ cosolvent ค่าการละลายเป็นไปตามสมการ log-linear (log Sm = log Sw + σf) เมื่อเจือจางด้วยน้ำ สัดส่วน cosolvent (f) ลดลง ค่าการละลายจะลดลงแบบ exponential ในขณะที่ความเข้มข้นยาลดลงแบบเส้นตรงตาม dilution จึงเกิดจุดที่ยาอยู่ในภาวะ supersaturated และตกตะกอน\n\nการแก้ไขในทางปฏิบัติ เช่น ให้ยาโดยฉีดตรงช้า ๆ (slow IV push) ผ่าน line ที่ไหลอยู่ หรือในการพัฒนาตำรับ ใช้ surfactant (micellar solubilization), cyclodextrin หรือ emulsion ซึ่งทนต่อการเจือจางได้ดีกว่า นอกจากนี้ cosolvent ปริมาณสูงยังทำให้เจ็บที่ตำแหน่งฉีด phlebitis และ hemolysis ได้",
      w: [
        "ถูก — การละลายลดลงแบบ exponential เมื่อ cosolvent ถูกเจือจาง ทำให้เกิด supersaturation",
        "Diazepam ไม่ได้เกิดเกลือกับ NaCl ปัญหาเป็นเรื่องการละลายทางกายภาพ",
        "Propylene glycol ระเหยยากมาก ไม่ได้ระเหยระหว่างผสมยา",
        "Diazepam เป็นเบสอ่อนมาก ethanol ไม่ได้ทำให้ pH เปลี่ยนจนเป็นสาเหตุหลัก",
        "การเจือจางทำให้ความเข้มข้นยาลดลง ไม่ใช่เพิ่มขึ้น",
      ],
      k: "Cosolvent: log S ลดแบบเส้นตรงกับ f → เจือจางแล้วเสี่ยงตกตะกอน; แก้ด้วย surfactant/cyclodextrin หรือวิธีให้ยา",
      d: "medium",
      ref: "Yalkowsky SH. Solubility and Solubilization in Aqueous Media; Aulton's Pharmaceutics 6th ed., Parenteral products",
    },
    {
      t: "Glass delamination risk",
      p: "ผู้ผลิตยาฉีดพบ glass flakes ในยาที่เก็บไว้ 18 เดือน ข้อใดเป็นชุดปัจจัยที่เพิ่มความเสี่ยงต่อ glass delamination มากที่สุด",
      o: [
        "Type I tubing vial, สารละลาย sodium citrate buffer pH 8.0, ผ่าน terminal sterilization และเก็บที่อุณหภูมิห้อง",
        "Type I molded vial, ยาผงแห้ง lyophilized, เก็บที่ 2–8 °C",
        "Type I tubing vial, สารละลาย acetate buffer pH 4.5, aseptic fill, เก็บที่ 2–8 °C",
        "Type I molded vial, สารละลายในน้ำมันงา, เก็บที่ 2–8 °C",
        "Prefilled syringe แก้ว Type I, สารละลาย pH 6.0 ไม่มี buffer, เก็บที่ 2–8 °C",
      ],
      a: 0,
      r: "Delamination คือการที่ชั้นผิวแก้วด้านในหลุดเป็นแผ่นบาง (lamellae) เกิดจากการกัดกร่อนของผิวแก้วที่มีองค์ประกอบไม่สม่ำเสมอ โดยเฉพาะ tubing vial ที่ขึ้นรูปที่อุณหภูมิสูงจนมีการระเหยของ borate/sodium บริเวณก้น vial\n\nปัจจัยเสี่ยงสำคัญได้แก่ pH สูง (ด่าง), buffer ที่จับกับซิลิเกต/โลหะ เช่น citrate และ phosphate, ความแรงไอออนสูง, terminal sterilization (ความร้อนเร่งปฏิกิริยา) และอายุการเก็บที่อุณหภูมิห้องนาน มาตรการแก้ไขได้แก่ใช้ vial ที่ผ่าน surface treatment/coated vial, molded glass, หรือปรับ formulation และทำ screening ตาม USP <1660>",
      w: [
        "ถูก — รวมปัจจัย tubing glass, pH ด่าง, citrate, terminal sterilization และเก็บอุณหภูมิห้อง",
        "ผงแห้งไม่สัมผัสผิวแก้วในรูปสารละลายและเก็บเย็น ความเสี่ยงต่ำมาก",
        "pH กรดและอุณหภูมิต่ำ ไม่ผ่านความร้อน ความเสี่ยงต่ำกว่ามาก",
        "Non-aqueous vehicle ไม่กัดกร่อนผิวแก้วเหมือนสารละลายน้ำด่าง",
        "pH กลาง ไม่มี chelating buffer และเก็บเย็น ความเสี่ยงต่ำกว่า",
      ],
      k: "Delamination risk ↑: tubing vial, pH สูง, citrate/phosphate, terminal sterilization, เก็บนานที่อุณหภูมิห้อง",
      d: "medium",
      ref: "USP <1660> Evaluation of the Inner Surface Durability of Glass Containers; FDA Advisory to Drug Manufacturers on glass lamellae (2011)",
    },
    {
      t: "LAL beta-glucan interference",
      p: "ยาฉีดชีววัตถุที่ผ่านการกรองด้วย cellulose-based depth filter ให้ผล kinetic chromogenic LAL เกิน limit หลายครั้ง แต่เมื่อทดสอบด้วย recombinant Factor C (rFC) assay และ Monocyte Activation Test กลับไม่พบ endotoxin/pyrogen ข้อใดอธิบายได้ดีที่สุด",
      o: [
        "(1→3)-β-D-glucan จาก cellulose filter กระตุ้น Factor G pathway ใน LAL ทำให้เกิด false positive ส่วน rFC ไม่มี Factor G จึงไม่ถูกรบกวน",
        "ผลิตภัณฑ์มี endotoxin จริงแต่ rFC ตรวจไม่พบเพราะไวต่ำกว่า LAL เสมอ",
        "ผลิตภัณฑ์มีโปรตีนที่จับ endotoxin ทำให้ LAL เกิด enhancement จาก low endotoxin recovery",
        "Cellulose filter ปล่อย Gram-negative bacteria ที่มีชีวิตลงในผลิตภัณฑ์",
        "LAL ถูกยับยั้งโดย pH ของผลิตภัณฑ์จึงอ่านผลบวกเกินจริง",
      ],
      a: 0,
      r: "LAL มี 2 pathway: Factor C ที่ถูกกระตุ้นโดย endotoxin และ Factor G ที่ถูกกระตุ้นโดย (1→3)-β-D-glucan ซึ่งมาจากวัสดุ cellulose (depth filter, dialysis membrane), เชื้อรา หรือสารสกัดจากพืช ทำให้เกิด false-positive endotoxin\n\nวิธีแก้ได้แก่ใช้ glucan-blocking buffer หรือ endotoxin-specific reagent, ใช้ rFC ซึ่งมีแต่ Factor C จึงจำเพาะต่อ endotoxin หรือเปลี่ยนวัสดุ filter การที่ MAT ไม่พบ pyrogen ยืนยันว่าไม่ใช่ endotoxin จริง ส่วน Low endotoxin recovery (LER) เป็นปรากฏการณ์ที่ทำให้ผล 'ต่ำ' เกินจริง (masking) ไม่ใช่สูงเกินจริง",
      w: [
        "ถูก — β-glucan กระตุ้น Factor G ใน LAL; rFC ไม่มี pathway นี้จึงไม่ให้ผลบวกปลอม",
        "rFC มีความไวเทียบเท่าตาม validation และ MAT ก็ไม่พบ pyrogen จึงไม่สนับสนุนว่ามี endotoxin จริง",
        "LER ทำให้ recovery ต่ำ (false negative) ไม่ใช่ผลสูงเกิน limit",
        "Depth filter ไม่ได้ปล่อยแบคทีเรียมีชีวิต และหากมีจริง MAT ควรให้ผลบวก",
        "การยับยั้ง (inhibition) ทำให้ผลต่ำลง ไม่ใช่ผลบวกเกินจริง",
      ],
      k: "LAL false positive จาก β-glucan (Factor G) — แก้ด้วย glucan blocker หรือ rFC; LER คือ false negative",
      d: "hard",
      ref: "USP <85> Bacterial Endotoxins Test; USP <86> Bacterial Endotoxins Test Using Recombinant Reagents; Ph. Eur. 2.6.32",
    },
    {
      t: "Mannitol annealing in lyophilization",
      p: "สูตร lyophilized ที่มี mannitol เป็น bulking agent และ sucrose เป็น lyoprotectant พบปัญหา vial แตกบางส่วนและ cake มี residual moisture สูงไม่สม่ำเสมอ เมื่อวิเคราะห์พบ mannitol บางส่วนยังเป็น amorphous หลัง freezing ข้อใดเป็นการแก้ไขกระบวนการที่เหมาะสมที่สุด",
      o: [
        "เพิ่มขั้น annealing หลัง freezing โดยอุ่น product ไปประมาณ −20 °C ค้างไว้ระยะหนึ่งแล้วแช่แข็งลงใหม่ เพื่อให้ mannitol ตกผลึกสมบูรณ์ก่อน primary drying",
        "ลด shelf temperature ระหว่าง freezing ให้เร็วที่สุดเพื่อให้ mannitol คงสภาพ amorphous ตลอดกระบวนการ",
        "ตัดขั้น secondary drying ออกเพื่อลดความเครียดต่อแก้ว",
        "เพิ่ม chamber pressure ระหว่าง primary drying เพื่อให้ mannitol ละลายกลับ",
        "เปลี่ยน mannitol เป็น glycine ในปริมาณเท่ากันโดยไม่ต้องปรับ cycle",
      ],
      a: 0,
      r: "Mannitol ควรตกผลึกสมบูรณ์เพื่อทำหน้าที่เป็น crystalline scaffold ที่ให้ cake แข็งแรงและอบแห้งได้ที่อุณหภูมิสูง ถ้า freezing เร็ว mannitol บางส่วนจะค้างเป็น amorphous แล้วตกผลึกภายหลัง (ระหว่าง primary drying หรือระหว่างเก็บ) ปลดปล่อยน้ำ ทำให้ cake ไม่สม่ำเสมอ/ความชื้นสูง และการขยายตัวจากการตกผลึกในชั้นที่แข็งตัวทำให้ vial แตกได้ (พบบ่อยเมื่อ fill volume สูง)\n\nAnnealing คือการอุ่น product ไปที่อุณหภูมิสูงกว่า Tg' ของ freeze-concentrate แต่ต่ำกว่าจุดหลอม (ประมาณ −15 ถึง −25 °C) ค้างไว้ เพื่อให้ mannitol ตกผลึกสมบูรณ์ และยังช่วยให้ผลึกน้ำแข็งใหญ่ขึ้น (Ostwald ripening) ลด dried-layer resistance ทำให้ primary drying เร็วขึ้น",
      w: [
        "ถูก — annealing ทำให้ mannitol ตกผลึกสมบูรณ์ ลดการตกผลึกภายหลังที่ทำให้ vial แตกและความชื้นไม่สม่ำเสมอ",
        "การคง mannitol เป็น amorphous คือสาเหตุของปัญหา ไม่ใช่ทางแก้",
        "Secondary drying จำเป็นต่อการลด residual moisture การตัดออกทำให้ความชื้นสูงขึ้น",
        "Pressure สูงไม่ทำให้ mannitol ตกผลึก และเสี่ยงให้ product temperature เกิน collapse",
        "Glycine ก็ต้องการการ annealing/ควบคุมการตกผลึกเช่นกัน และเปลี่ยน excipient ต้องพัฒนาใหม่",
      ],
      k: "Annealing (~ −20 °C) → mannitol ตกผลึกสมบูรณ์ + ผลึกน้ำแข็งใหญ่ขึ้น → ลด vial breakage และเร่ง primary drying",
      d: "hard",
      ref: "Liu J. Physical characterization of pharmaceutical formulations in frozen and freeze-dried solid states. Pharm Dev Technol 2006;11:3–28; Aulton's Pharmaceutics 6th ed., Freeze drying",
    },
  ],
  // Mock Set 3
  [
    {
      t: "Z-value calculation",
      p: "ผลการศึกษา thermal resistance ของ bioburden isolate จากสาย filling พบว่า D-value ที่ 115 °C = 6.0 นาที และที่ 121 °C = 1.5 นาที ค่า z-value ของเชื้อนี้ประมาณเท่าใด",
      o: ["4.0 °C", "4.3 °C", "6.0 °C", "10 °C", "24 °C"],
      a: 3,
      r: "z-value คือจำนวนองศาที่ต้องเปลี่ยนอุณหภูมิเพื่อให้ D-value เปลี่ยนไป 10 เท่า (1 log) คำนวณจาก z = (T2 − T1) / (log D1 − log D2)\n\nz = (121 − 115) / log(6.0/1.5) = 6 / log 4 = 6 / 0.602 ≈ 10 °C ซึ่งตรงกับค่า z ที่ใช้เป็นมาตรฐานในการคำนวณ F0 สำหรับ moist heat ค่า z ใช้ประเมินว่าการเปลี่ยนอุณหภูมิเล็กน้อยมีผลต่อ lethality มากเพียงใด",
      w: [
        "เป็นอัตราส่วน D115/D121 ไม่ใช่ z-value",
        "ใช้ natural log (ln 4 = 1.386) แทน log ฐาน 10",
        "เป็นเพียงผลต่างอุณหภูมิ ยังไม่ได้หารด้วยจำนวน log ที่ D เปลี่ยน",
        "ถูก — z = 6/log 4 = 6/0.602 ≈ 10 °C",
        "คูณผลต่างอุณหภูมิกับอัตราส่วน D แทนการหารด้วย log",
      ],
      k: "z = ΔT / log(D1/D2); moist heat ใช้ z = 10 °C เป็นค่ามาตรฐานในการคำนวณ F0",
      d: "medium",
      ref: "USP <1229.1> Steam Sterilization by Direct Contact; USP <1229> Sterilization of Compendial Articles",
      c: [
        "D115/D121 = 6.0/1.5 = 4",
        "log 4 = 0.602",
        "z = (121 − 115)/0.602 = 9.97 ≈ 10 °C",
      ],
    },
    {
      t: "Osmolarity of IV admixture",
      p: "สารละลาย IV ประกอบด้วย dextrose anhydrous 5% w/v (MW 180), NaCl 0.45% w/v (MW 58.5) และ KCl 20 mEq/L คำนวณ osmolarity ทางทฤษฎี (ถือว่า NaCl และ KCl แตกตัวสมบูรณ์) ได้ประมาณเท่าใด",
      o: ["375 mOsm/L", "432 mOsm/L", "452 mOsm/L", "472 mOsm/L", "586 mOsm/L"],
      a: 3,
      r: "Osmolarity (mOsm/L) = (g/L ÷ MW) × จำนวนอนุภาคที่แตกตัว × 1000 สารที่ไม่แตกตัว เช่น dextrose ให้ 1 osmole ต่อ mole ส่วน NaCl และ KCl ให้ 2\n\nDextrose 50 g/L ÷ 180 = 278 mOsm/L; NaCl 4.5 g/L ÷ 58.5 = 76.9 mmol/L × 2 = 154 mOsm/L; KCl 20 mEq/L = 20 mmol/L × 2 = 40 mOsm/L รวม ≈ 472 mOsm/L ซึ่งสูงกว่าพลาสมา (~290) แต่ยังให้ทาง peripheral vein ได้ (โดยทั่วไปควร < ~900 mOsm/L) ทั้งนี้ค่าจริงที่วัดได้จะต่ำกว่าทางทฤษฎีเล็กน้อยเพราะ osmotic coefficient < 1",
      w: [
        "ไม่คิดการแตกตัวของ NaCl และ KCl (278 + 77 + 20)",
        "ลืมรวม KCl",
        "นับ KCl เป็น 20 mOsm/L โดยไม่คิดว่าแตกตัวเป็น K⁺ และ Cl⁻",
        "ถูก — 278 + 154 + 40 ≈ 472 mOsm/L",
        "ใช้ NaCl 0.9% แทน 0.45% (278 + 308) และไม่รวม KCl",
      ],
      k: "mOsm/L = mmol/L × จำนวนอนุภาค; 1 mEq KCl = 1 mmol = 2 mOsm",
      d: "medium",
      ref: "Remington: The Science and Practice of Pharmacy 23rd ed., Ch. Tonicity, Osmoticity, Osmolality and Osmolarity",
      c: [
        "Dextrose: 50 g/L ÷ 180 = 0.278 mol/L → 278 mOsm/L",
        "NaCl: 4.5 g/L ÷ 58.5 = 0.0769 mol/L × 2 = 154 mOsm/L",
        "KCl: 20 mEq/L = 20 mmol/L × 2 = 40 mOsm/L",
        "รวม = 278 + 154 + 40 = 472 mOsm/L",
      ],
    },
    {
      t: "Dry heat sterilization applications",
      p: "วัตถุดิบหรือวัสดุใดต่อไปนี้เหมาะสมที่สุดที่จะทำให้ปราศจากเชื้อด้วย dry heat (เช่น 160 °C นาน 2 ชั่วโมง หรือ cycle ที่ validated เทียบเท่า)",
      o: [
        "Sesame oil ที่จะใช้เป็น vehicle ของ oily injection",
        "Rubber stopper ชนิด bromobutyl ก่อนใช้ปิด vial",
        "สารละลาย dextrose 5% ที่บรรจุใน vial ปิดสนิท",
        "Administration set ที่ทำจาก PVC",
        "สารละลายโปรตีน monoclonal antibody",
      ],
      a: 0,
      r: "Dry heat ใช้กับวัสดุที่ทนอุณหภูมิสูงแต่ไอน้ำแทรกผ่านไม่ได้หรือความชื้นทำให้เสื่อม เช่น น้ำมัน (fixed oils), ปิโตรเลียมเจล, ผงที่ทนความร้อน และเครื่องแก้ว/โลหะ กลไกหลักคือ oxidation ของส่วนประกอบเซลล์ ซึ่งมีประสิทธิภาพต่ำกว่าความร้อนชื้น จึงต้องใช้อุณหภูมิสูงและเวลานานกว่า\n\nวัสดุที่ไม่ทนอุณหภูมิสูง เช่น ยาง พลาสติก และสารละลายน้ำ จะใช้วิธีอื่น: moist heat สำหรับ stopper และสารละลายน้ำ, EtO/radiation สำหรับพลาสติก, filtration สำหรับโปรตีน",
      w: [
        "ถูก — น้ำมันไม่ให้ไอน้ำผ่าน จึงต้องใช้ dry heat",
        "ยางไม่ทนอุณหภูมิ dry heat และนิยม sterilize ด้วย moist heat (autoclave)",
        "สารละลายน้ำในภาชนะปิดใช้ moist heat; dry heat ทำให้แรงดันสูงและไม่ใช่วิธีมาตรฐาน",
        "PVC ไม่ทนความร้อนสูง ใช้ EtO หรือ radiation",
        "โปรตีนเสียสภาพด้วยความร้อน ต้องใช้ sterile filtration",
      ],
      k: "Dry heat: น้ำมัน, ผงทนร้อน, แก้ว/โลหะ (≥160 °C/2 h หรือเทียบเท่า); ไม่ใช้กับยาง พลาสติก และสารละลายน้ำ",
      d: "easy",
      ref: "Ph. Eur. 5.1.1 Methods of preparation of sterile products; USP <1229.8> Dry Heat Sterilization",
    },
    {
      t: "Multiple-dose container requirements",
      p: "บริษัทต้องการผลิตยาฉีด IM แบบ multiple-dose vial ข้อกำหนดใดถูกต้องตาม USP",
      o: [
        "ต้องมี antimicrobial preservative ที่ผ่าน antimicrobial effectiveness test และปริมาตรโดยทั่วไปไม่เกิน 30 mL",
        "ไม่จำเป็นต้องมี preservative หากบรรจุด้วยวิธี aseptic processing",
        "บรรจุได้ไม่จำกัดปริมาตรหากมี preservative",
        "ต้องผ่าน terminal sterilization เสมอเพราะเป็น multiple-dose",
        "สามารถใช้กับทาง intrathecal ได้หากใช้ preservative ความเข้มข้นต่ำ",
      ],
      a: 0,
      r: "Multiple-dose container ถูกเจาะซ้ำหลายครั้ง จึงเสี่ยงต่อการปนเปื้อนจุลชีพหลังเปิดใช้ ต้องมี antimicrobial preservative ในความเข้มข้นที่พิสูจน์ด้วย Antimicrobial Effectiveness Testing (USP <51>) และ USP จำกัดปริมาตรของ multiple-dose container ไม่เกิน 30 mL (เว้นแต่ monograph กำหนดเป็นอย่างอื่น) เพื่อจำกัดจำนวนครั้งที่เจาะและปริมาณ preservative ที่ผู้ป่วยได้รับ\n\nการผลิตแบบ aseptic ไม่ได้ป้องกันการปนเปื้อนระหว่างใช้งาน และ multiple-dose ห้ามใช้กับทางที่ต้อง preservative-free เช่น intrathecal",
      w: [
        "ถูก — multiple-dose ต้องมี preservative ที่พิสูจน์ประสิทธิภาพแล้ว และปริมาตรไม่เกิน 30 mL",
        "ความเสี่ยงอยู่ที่การเจาะซ้ำระหว่างใช้ ไม่เกี่ยวกับวิธีผลิต",
        "USP จำกัดปริมาตร multiple-dose container ไว้ที่ 30 mL",
        "การเลือกวิธี sterilization ขึ้นกับความทนของผลิตภัณฑ์ ไม่ได้บังคับเพราะเป็น multiple-dose",
        "Intrathecal ต้อง preservative-free เสมอ ไม่ว่าความเข้มข้นเท่าใด",
      ],
      k: "Multiple-dose: ต้องมี preservative (ผ่าน USP <51>) และ ≤ 30 mL",
      d: "easy",
      ref: "USP <659> Packaging and Storage Requirements; USP <1> Injections and Implanted Drug Products; USP <51>",
    },
    {
      t: "Fixed oil vehicles",
      p: "ยาฉีด haloperidol decanoate ใช้ sesame oil เป็น vehicle ข้อใดถูกต้องเกี่ยวกับ non-aqueous vehicle ชนิด fixed oil ในยาฉีด",
      o: [
        "ใช้ฉีดได้เฉพาะ IM (หรือ SC) ห้ามฉีด IV และต้องเป็นน้ำมันพืชที่ร่างกายเมตาบอลิซึมได้ ไม่ใช้ mineral oil",
        "ใช้ฉีด IV ได้หากผ่านการกรอง 0.22 µm และ sterile",
        "Mineral oil เหมาะกว่าน้ำมันพืชเพราะไม่เหม็นหืน",
        "Fixed oil ทำให้ยาปลดปล่อยเร็วขึ้นเมื่อเทียบกับสารละลายน้ำ",
        "Fixed oil sterilize ด้วย autoclave 121 °C 15 นาทีเป็นวิธีหลัก",
      ],
      a: 0,
      r: "Fixed oils (เช่น sesame, cottonseed, peanut, castor oil) ใช้เป็น vehicle ของยาที่ละลายในไขมัน และ ester prodrug เช่น decanoate/enanthate เพื่อให้เกิด depot ที่ปลดปล่อยช้า ยาในน้ำมันให้ได้เฉพาะ IM/SC เท่านั้น ห้ามให้ IV เพราะเสี่ยงต่อ oil embolism\n\nตามเภสัชตำรับ น้ำมันต้องมาจากพืช ไม่มีกลิ่นหืน และควบคุมค่าทางเคมี เช่น acid value, saponification value, iodine value ไม่ใช้ mineral oil/paraffin เพราะร่างกายเมตาบอลิซึมไม่ได้และก่อ granuloma การ sterilize ใช้ dry heat เพราะไอน้ำผ่านน้ำมันไม่ได้ และต้องระบุชนิดน้ำมันบนฉลากเพราะอาจแพ้ได้ (เช่น peanut oil)",
      w: [
        "ถูก — oily injection ใช้ IM/SC เท่านั้น และต้องเป็นน้ำมันพืชที่ metabolizable",
        "การกรองไม่ได้ลดความเสี่ยง oil embolism; ห้ามฉีด IV",
        "Mineral oil ร่างกายย่อยไม่ได้ ก่อ granuloma จึงไม่ใช้เป็น parenteral vehicle",
        "น้ำมันทำให้เกิด depot และปลดปล่อยช้ากว่า เป็นเหตุผลที่ใช้ใน long-acting injection",
        "ไอน้ำไม่แทรกผ่านน้ำมัน ต้องใช้ dry heat",
      ],
      k: "Oily injection: IM/SC เท่านั้น, น้ำมันพืช metabolizable, sterilize ด้วย dry heat, ระบุชนิดน้ำมันบนฉลาก",
      d: "medium",
      ref: "USP <1> Injections and Implanted Drug Products (Vehicles and added substances); Remington 23rd ed., Parenteral Preparations",
    },
    {
      t: "Air removal and Bowie-Dick test",
      p: "เช้าวันจันทร์ ทดสอบ Bowie-Dick ใน prevacuum steam sterilizer ที่ใช้ sterilize porous load (ชุดเสื้อผ้า gowning และ filter) พบว่าแผ่นทดสอบตรงกลางมีสีจางกว่าบริเวณขอบ ข้อใดคือการตีความและการดำเนินการที่ถูกต้อง",
      o: [
        "การไล่อากาศหรือการแทรกซึมของไอน้ำล้มเหลว (อาจมี air leak หรือ non-condensable gases) ห้ามใช้เครื่องกับ porous load จนกว่าจะแก้ไขและทดสอบผ่าน",
        "แสดงว่าอุณหภูมิสูงเกินไปที่ตรงกลาง ให้ลดเวลา exposure ลง",
        "ผลนี้ยอมรับได้เพราะ Bowie-Dick ทดสอบเพียง sterilizer ของ liquid load",
        "แสดงว่า biological indicator ไม่ทำงาน ให้เปลี่ยน lot ของ BI",
        "ใช้เครื่องต่อได้หาก chart อุณหภูมิของ drain probe ถึง 121 °C",
      ],
      a: 0,
      r: "Moist heat ฆ่าเชื้อโดยไอน้ำอิ่มตัวควบแน่นบนพื้นผิวและถ่ายเทความร้อนแฝง (latent heat) ทำให้โปรตีนเสียสภาพ หากมีอากาศค้าง (air pocket) ใน porous load ไอน้ำจะเข้าไม่ถึง อุณหภูมิบริเวณนั้นต่ำและไม่เกิดการควบแน่น\n\nBowie-Dick (steam penetration/air removal test) ทำทุกวันก่อนใช้งานในรอบแรกกับ chamber ว่าง สำหรับเครื่อง prevacuum ที่ใช้กับ porous load การเปลี่ยนสีไม่สม่ำเสมอ (ตรงกลางจาง) บ่งชี้ว่ามีอากาศค้าง จาก vacuum ไม่พอ, รอยรั่วของ chamber หรือ non-condensable gases ในไอน้ำ ต้องหยุดใช้ แก้ไข และทดสอบซ้ำจนผ่าน การที่ drain probe ถึงอุณหภูมิไม่ได้ยืนยันว่าไอน้ำแทรกเข้า load",
      w: [
        "ถูก — สีจางตรงกลาง = air removal/steam penetration ล้มเหลว ต้องหยุดใช้และแก้ไข",
        "สีจางแสดงว่าไอน้ำเข้าไม่ถึง (อุณหภูมิต่ำกว่า) ไม่ใช่ร้อนเกิน",
        "Bowie-Dick ใช้กับ porous load ใน prevacuum sterilizer โดยตรง",
        "Bowie-Dick เป็น chemical test ไม่เกี่ยวกับ biological indicator",
        "Drain probe วัดอุณหภูมิในท่อ ไม่สะท้อนอากาศที่ค้างใน porous load",
      ],
      k: "Bowie-Dick = daily air removal/steam penetration test ของ prevacuum sterilizer สำหรับ porous load; สีไม่สม่ำเสมอ = fail",
      d: "medium",
      ref: "ISO 17665-1 Sterilization of health care products — Moist heat; ISO 11140-4; USP <1229.1>",
    },
    {
      t: "USP <788> LVP limits",
      p: "ทดสอบ particulate matter ของ IV infusion 1,000 mL (LVP) ด้วย light obscuration ได้ผลเฉลี่ย 14 particles/mL ที่ ≥ 10 µm และ 5 particles/mL ที่ ≥ 25 µm ข้อใดสรุปได้ถูกต้องตาม USP <788>",
      o: [
        "ไม่ผ่านเกณฑ์ light obscuration เพราะ ≥ 25 µm เกิน 3 particles/mL ต้องทดสอบต่อด้วย microscopic particle count test ก่อนตัดสินขั้นสุดท้าย",
        "ผ่าน เพราะ ≥ 10 µm ไม่เกิน 25 particles/mL ซึ่งเป็นเกณฑ์เดียวของ LVP",
        "ผ่าน เพราะเกณฑ์ LVP คิดต่อ container (6000 และ 600 particles/container)",
        "ไม่ผ่าน เพราะ ≥ 10 µm เกิน 12 particles/mL",
        "ผ่าน เพราะ ≥ 25 µm ไม่เกิน 50 particles/mL",
      ],
      a: 0,
      r: "USP <788> Method 1 (light obscuration) สำหรับ LVP: ≥ 10 µm ไม่เกิน 25 particles/mL และ ≥ 25 µm ไม่เกิน 3 particles/mL ส่วน SVP คิดต่อ container (≥ 10 µm ไม่เกิน 6000 และ ≥ 25 µm ไม่เกิน 600 ต่อ container)\n\nผลนี้ ≥ 10 µm ผ่าน (14 ≤ 25) แต่ ≥ 25 µm ไม่ผ่าน (5 > 3) ตาม USP <788> ผลิตภัณฑ์ที่ไม่ผ่าน light obscuration ให้ทดสอบด้วย Method 2 (microscopic) ซึ่งมีเกณฑ์ LVP 12 และ 2 particles/mL และต้องผ่านเกณฑ์นั้น พร้อมสอบสวนแหล่งของอนุภาค",
      w: [
        "ถูก — ≥ 25 µm เกินเกณฑ์ 3/mL ของ LVP; ไม่ผ่าน LO แล้วต้องทดสอบ microscopic ต่อ",
        "LVP มีเกณฑ์ทั้ง ≥ 10 µm และ ≥ 25 µm ต้องผ่านทั้งสองขนาด",
        "เกณฑ์ต่อ container (6000/600) เป็นของ SVP",
        "12 particles/mL เป็นเกณฑ์ของ microscopic method ไม่ใช่ light obscuration",
        "ไม่มีเกณฑ์ 50 particles/mL ใน USP <788>",
      ],
      k: "USP <788> LO: LVP ≤ 25/mL (≥10 µm), ≤ 3/mL (≥25 µm); SVP ≤ 6000 และ ≤ 600 ต่อ container",
      d: "medium",
      ref: "USP <788> Particulate Matter in Injections",
    },
    {
      t: "PUPSIT",
      p: "ระหว่าง GMP inspection ผู้ตรวจพบว่าบริษัททำ integrity test ของ sterilizing filter เฉพาะก่อนนำ filter ไป steam sterilize และหลังกรองผลิตภัณฑ์เสร็จ (post-use) ตาม EU GMP Annex 1 (2022) ข้อใดอธิบายเหตุผลที่ต้องมี PUPSIT ได้ถูกต้องที่สุด",
      o: [
        "เพื่อตรวจความเสียหายของ filter ที่เกิดจากการ sterilize และติดตั้ง และเพราะ post-use test อาจผ่านทั้งที่มีรอยรั่ว เนื่องจากอนุภาคในผลิตภัณฑ์อุดรอยรั่วไว้ (filter masking)",
        "เพื่อพิสูจน์ว่า filter ปราศจาก endotoxin ก่อนใช้",
        "เพื่อแทนการทำ bacterial retention validation ในแต่ละ batch",
        "เพื่อวัด bioburden ของ bulk solution ก่อนกรอง",
        "เพื่อลดเวลา filtration เนื่องจาก PUPSIT ทำให้ membrane เปียกล่วงหน้า",
      ],
      a: 0,
      r: "PUPSIT (pre-use post-sterilisation integrity test) คือการทดสอบ integrity ของ filter assembly หลัง sterilize และก่อนใช้กรองผลิตภัณฑ์ Annex 1 (2022) ระบุว่าควรทำเพื่อตรวจความเสียหายจากการเตรียม filter (เช่น การ steam sterilize, การติดตั้ง) ก่อนใช้งาน\n\nเหตุผลสำคัญคือ 'filter masking' — ในระหว่างกรอง อนุภาคหรือโปรตีนในผลิตภัณฑ์อาจอุดรอยรั่วของ membrane ทำให้ post-use integrity test ผ่านทั้งที่ระหว่างกรองมีจุลชีพเล็ดลอดได้ หากทำ PUPSIT ไม่ได้ (เช่น ระบบ single-use ที่เสี่ยงต่อการปนเปื้อนด้านปลายน้ำจากการทดสอบ) ต้องมี risk assessment และหลักฐานรองรับ ส่วน post-use test ยังจำเป็นเสมอ",
      w: [
        "ถูก — PUPSIT ตรวจความเสียหายหลัง sterilization และป้องกันความเสี่ยง filter masking ที่ post-use test อาจตรวจไม่พบ",
        "Integrity test ไม่ได้ตรวจ endotoxin",
        "Bacterial retention validation ทำครั้งเดียวในการ validate และ integrity test ไม่ได้แทน",
        "Bioburden ตรวจจากตัวอย่าง bulk ก่อนกรอง ไม่เกี่ยวกับ PUPSIT",
        "PUPSIT ไม่ได้มีวัตถุประสงค์เพื่อลดเวลาและอาจเพิ่มความซับซ้อนของระบบด้วยซ้ำ",
      ],
      k: "PUPSIT = integrity test หลัง sterilize ก่อนใช้; ป้องกันความเสียหายจาก sterilization และ filter masking; post-use test ยังต้องทำ",
      d: "hard",
      ref: "EU GMP Annex 1 (2022) para 8.87; PDA Technical Report No. 26",
    },
    {
      t: "Primary drying endpoint detection",
      p: "ใน lyophilization cycle ของยาฉีด 20,000 vials ใช้ thermocouple ใน vial แถวหน้า 6 vial พบว่าอุณหภูมิ product ขึ้นมาเท่ากับ shelf temperature แล้ว แต่ Pirani gauge ยังอ่านค่าสูงกว่า capacitance manometer อย่างชัดเจน ข้อใดเป็นการตีความที่ถูกต้อง",
      o: [
        "Primary drying ของทั้ง batch ยังไม่เสร็จ เพราะยังมีไอน้ำในห้อง (Pirani ไวต่อไอน้ำ) และ vial ที่มี thermocouple มักแห้งเร็วกว่า vial ทั่วไป ควรรอจนค่าทั้งสองบรรจบกัน",
        "Primary drying เสร็จแล้ว ให้เข้าสู่ secondary drying ทันทีตามสัญญาณจาก thermocouple",
        "Capacitance manometer เสีย เพราะควรอ่านค่าสูงกว่า Pirani เสมอ",
        "ความต่างของ gauge แสดงว่ามี collapse เกิดขึ้นทั้ง batch",
        "ต้องเพิ่ม chamber pressure เพื่อให้ Pirani และ capacitance manometer อ่านค่าเท่ากัน",
      ],
      a: 0,
      r: "Comparative pressure measurement: capacitance manometer วัดความดันสัมบูรณ์ไม่ขึ้นกับชนิดก๊าซ ส่วน Pirani gauge วัดจาก thermal conductivity ซึ่งไอน้ำนำความร้อนได้มากกว่าไนโตรเจนราว 1.6 เท่า ขณะที่ยังมี sublimation Pirani จึงอ่านค่าสูงกว่า เมื่อไอน้ำหมดค่าทั้งสองจะบรรจบกัน ซึ่งเป็นตัวบ่งชี้ end point ของ primary drying ของทั้ง batch\n\nThermocouple vial ไม่เป็นตัวแทน batch: การมี probe ทำให้ ice nucleation เกิดที่อุณหภูมิสูงกว่า ผลึกน้ำแข็งใหญ่กว่า แห้งเร็วกว่า และ vial แถวหน้า/ขอบได้รับความร้อนจากการแผ่รังสีมากกว่า (edge effect) การเข้าสู่ secondary drying เร็วเกินไปทำให้ vial ที่ยังมีน้ำแข็งเกิด collapse/melt-back",
      w: [
        "ถูก — Pirani > capacitance manometer = ยังมีไอน้ำ; thermocouple vial แห้งก่อน batch",
        "Thermocouple vial มักแห้งเร็วกว่าจึงให้สัญญาณ end point ก่อนเวลา",
        "Pirani ต่างหากที่อ่านสูงกว่าเมื่อมีไอน้ำ ส่วน capacitance manometer อ่านค่าจริง",
        "ความต่างของ gauge สะท้อนองค์ประกอบก๊าซ (ไอน้ำ) ไม่ใช่การ collapse",
        "Gauge ทั้งสองต่างกันจากชนิดก๊าซ การเพิ่ม pressure ไม่ได้ทำให้ไอน้ำหมด",
      ],
      k: "End of primary drying: Pirani บรรจบกับ capacitance manometer; thermocouple vial ไม่เป็นตัวแทน (แห้งเร็วกว่า)",
      d: "hard",
      ref: "Patel SM, Doen T, Pikal MJ. Determination of end point of primary drying in freeze-drying process control. AAPS PharmSciTech 2010;11:73–84",
    },
    {
      t: "Non-endotoxin pyrogens and MAT",
      p: "ยาฉีดชีววัตถุที่ผลิตจากระบบ Gram-positive bacteria ผ่าน Bacterial Endotoxins Test ทุก batch แต่มีรายงานผู้ป่วยไข้สูงหลังได้รับยาจาก batch หนึ่ง ข้อใดเป็นการทดสอบที่เหมาะสมที่สุดในการสอบสวน",
      o: [
        "Monocyte Activation Test (MAT) ซึ่งตรวจได้ทั้ง endotoxin และ non-endotoxin pyrogens ผ่านการหลั่ง cytokine ของ human monocytes",
        "ทำ LAL gel-clot ซ้ำด้วย reagent lot อื่น เพราะ LAL ตรวจ pyrogen ได้ทุกชนิด",
        "Sterility test ตาม USP <71> เพื่อหาสาเหตุของไข้",
        "ทดสอบ recombinant Factor C เพื่อหา lipoteichoic acid",
        "ทดสอบ bioburden ของ bulk ก่อนกรอง",
      ],
      a: 0,
      r: "Pyrogen แบ่งเป็น endotoxin (LPS จาก Gram-negative) และ non-endotoxin pyrogens (NEP) เช่น lipoteichoic acid และ peptidoglycan จาก Gram-positive, ส่วนประกอบเชื้อรา, flagellin หรือสาร process-related BET (LAL/rFC) จำเพาะต่อ endotoxin จึงตรวจ NEP ไม่ได้\n\nMAT (Ph. Eur. 2.6.30) เลียนแบบการตอบสนองไข้ในมนุษย์ โดยวัด cytokine (เช่น IL-6, IL-1β) จาก human monocytes จึงตรวจได้ทั้ง endotoxin และ NEP และเป็นทางเลือกแทน rabbit pyrogen test ที่ Ph. Eur. ส่งเสริมให้เปลี่ยนมาใช้ เหมาะกับการสอบสวนกรณี BET ผ่านแต่มีอาการไข้",
      w: [
        "ถูก — MAT ตรวจ endotoxin และ NEP ได้ จึงเหมาะกับ pyrogenic reaction ที่ BET ตรวจไม่พบ",
        "LAL จำเพาะต่อ endotoxin (และ β-glucan) ไม่ตรวจ NEP จาก Gram-positive",
        "Sterility test ตรวจจุลชีพมีชีวิต ไม่ใช่สาร pyrogen ที่ทนความร้อน",
        "rFC จำเพาะต่อ endotoxin (LPS) ไม่ตรวจ lipoteichoic acid",
        "Bioburden ไม่บอกปริมาณ pyrogen ในผลิตภัณฑ์สุดท้าย",
      ],
      k: "BET (LAL/rFC) = endotoxin เท่านั้น; MAT ตรวจทั้ง endotoxin และ non-endotoxin pyrogens",
      d: "hard",
      ref: "Ph. Eur. 2.6.30 Monocyte-activation test; USP <151> Pyrogen Test; USP <85>",
    },
  ],
];
