import type { Ip1MockDomainContent } from "@/lib/ip1-mock/types";

export const STERILE: Ip1MockDomainContent = [
  // Mock Set 1
  [
    {
      t: "NaCl equivalent isotonic adjustment",
      p: "เภสัชกรต้องเตรียม Procaine HCl injection 2% w/v ปริมาตร 50 mL ให้ isotonic ด้วย NaCl กำหนดให้ NaCl equivalent (E) ของ procaine HCl = 0.21 ต้องเติม NaCl กี่ mg",
      o: ["30 mg", "90 mg", "210 mg", "240 mg", "450 mg"],
      a: 3,
      r: "วิธี sodium chloride equivalent: E คือปริมาณ NaCl (g) ที่ให้ผลทาง osmotic เท่ากับยา 1 g สารละลาย 0.9% NaCl เป็น isotonic ดังนั้นปริมาตร 50 mL ต้องการ 'NaCl equivalent' รวม 0.45 g\n\nยาที่ใช้ = 2% × 50 mL = 1.0 g ให้ผลเทียบเท่า NaCl = 1.0 × 0.21 = 0.21 g จึงต้องเติม NaCl จริงอีก 0.45 − 0.21 = 0.24 g = 240 mg ขั้นตอนสำคัญคืออย่าลืมคูณ E กับน้ำหนักยา (ไม่ใช่ความเข้มข้น %) และหักออกจากปริมาณ NaCl ที่ต้องการทั้งหมดของปริมาตรนั้น",
      w: [
        "คิดน้ำหนักยาผิดเป็น 2 g (ตีความ 2% ว่า 2 g ต่อปริมาตรทั้งหมด) จึงหัก 0.42 g เหลือ 0.03 g",
        "คำนวณจากการคูณผิดขั้น เช่น 0.45 × 0.21 ≈ 0.09 g ซึ่งไม่ได้มีความหมายทาง isotonicity",
        "เป็นค่า NaCl equivalent ของตัวยา (1 g × 0.21) ไม่ใช่ปริมาณ NaCl ที่ต้องเติม",
        "ถูก — NaCl ที่ต้องการ 0.45 g ลบส่วนที่ยาให้ไปแล้ว 0.21 g เหลือต้องเติม 0.24 g",
        "เป็นปริมาณ NaCl สำหรับทำ 50 mL ให้ isotonic โดยไม่หักผลของยา จะได้สารละลาย hypertonic",
      ],
      k: "NaCl ที่ต้องเติม = (0.009 × V mL) − Σ(น้ำหนักยา g × E)",
      d: "medium",
      ref: "Remington: The Science and Practice of Pharmacy 23rd ed., Ch. Tonicity, Osmoticity, Osmolality and Osmolarity",
      c: [
        "NaCl ที่ต้องการสำหรับ 50 mL = 0.9/100 × 50 = 0.45 g",
        "น้ำหนัก procaine HCl = 2/100 × 50 = 1.0 g",
        "NaCl equivalent ของยา = 1.0 × 0.21 = 0.21 g",
        "NaCl ที่ต้องเติม = 0.45 − 0.21 = 0.24 g = 240 mg",
      ],
    },
    {
      t: "Endotoxin limit K/M",
      p: "ยาฉีดปฏิชีวนะชนิด IV bolus มีขนาดยาสูงสุด 25 mg/kg ต่อครั้ง (ให้ภายใน 1 ชั่วโมง) ห้อง QC ต้องกำหนด endotoxin limit ตาม USP <85> ข้อใดถูกต้อง",
      o: ["0.0029 EU/mg", "0.008 EU/mg", "0.2 EU/mg", "14 EU/mg", "125 EU/mg"],
      a: 2,
      r: "Endotoxin limit (EL) = K/M โดย K คือ threshold pyrogenic dose (5 EU/kg สำหรับทางให้ยา parenteral ทั่วไป และ 0.2 EU/kg สำหรับ intrathecal) และ M คือขนาดยาสูงสุดต่อ kg ที่ให้ภายใน 1 ชั่วโมง\n\nกรณีนี้ EL = 5 EU/kg ÷ 25 mg/kg = 0.2 EU/mg หน่วย kg ตัดกันไปแล้ว จึงไม่ต้องคูณหรือหารน้ำหนักตัวอีก ค่า M ต้องเป็นขนาดยาสูงสุดต่อชั่วโมง ถ้าให้ยาหลายครั้งใน 1 ชั่วโมงต้องรวมกัน",
      w: [
        "นำ 0.2 EU/mg ไปหารด้วยน้ำหนักตัว 70 kg ซ้ำอีกครั้ง ซึ่งผิดเพราะ K และ M เป็นค่าต่อ kg อยู่แล้ว",
        "ใช้ K = 0.2 EU/kg ซึ่งเป็นค่าสำหรับ intrathecal ไม่ใช่ IV",
        "ถูก — EL = K/M = 5/25 = 0.2 EU/mg",
        "คูณ 0.2 EU/mg ด้วยน้ำหนักตัว 70 kg ซึ่งผิดหน่วยและหลักการ",
        "นำ K × M (5 × 25) แทนการหาร ได้ค่าที่ไม่มีความหมายและหย่อนเกินจริงมาก",
      ],
      k: "EL = K/M; K = 5 EU/kg (parenteral ทั่วไป), 0.2 EU/kg (intrathecal); M = ขนาดยาสูงสุด/kg/ชั่วโมง",
      d: "medium",
      ref: "USP <85> Bacterial Endotoxins Test",
      c: ["K = 5 EU/kg (IV)", "M = 25 mg/kg/h", "EL = 5 ÷ 25 = 0.2 EU/mg"],
    },
    {
      t: "D-value from survivor curve",
      p: "ในการศึกษา thermal resistance ของ spore ที่ 121 °C พบจำนวน spore รอดชีวิต 2.0 × 10^6 CFU ที่เวลา 0 นาที และเหลือ 4.0 × 10^2 CFU หลังให้ความร้อน 10 นาที (survivor curve เป็น first-order) D121 ของ spore นี้มีค่าประมาณเท่าใด",
      o: ["1.35 min", "2.5 min", "2.7 min", "3.7 min", "5.0 min"],
      a: 2,
      r: "D-value คือเวลาที่ทำให้จำนวนจุลชีพลดลง 1 log (90%) ที่อุณหภูมิกำหนด คำนวณได้จาก D = t / (log N0 − log N)\n\nlog(2.0 × 10^6) = 6.301 และ log(4.0 × 10^2) = 2.602 ต่างกัน 3.699 log ดังนั้น D = 10/3.699 ≈ 2.7 นาที กับดักที่พบบ่อยคือปัด log reduction เป็นเลขจำนวนเต็ม (4 log) ทำให้ได้ 2.5 นาที หรือสับสนว่า log reduction คือ D-value เอง",
      w: [
        "เป็นค่าครึ่งหนึ่งของคำตอบ เกิดจากใช้ ln/คำนวณ log ผิดสเกล",
        "ประมาณ log reduction เป็น 4 log (นับเลขชี้กำลังอย่างเดียว) โดยไม่คิดสัมประสิทธิ์ 2.0 และ 4.0",
        "ถูก — log reduction = 6.301 − 2.602 = 3.699; D = 10/3.699 ≈ 2.7 นาที",
        "เป็นจำนวน log reduction (3.7) ไม่ใช่เวลาต่อ 1 log",
        "หาร 10 นาทีด้วย 2 แบบไม่มีเหตุผลทาง kinetics",
      ],
      k: "D = t / (log N0 − log Nt); อย่าปัด log reduction โดยลืมสัมประสิทธิ์หน้าเลขยกกำลัง",
      d: "hard",
      ref: "USP <1229.1> Steam Sterilization by Direct Contact; USP <1229> Sterilization of Compendial Articles",
      c: [
        "log N0 = log(2.0 × 10^6) = 6.301",
        "log Nt = log(4.0 × 10^2) = 2.602",
        "log reduction = 6.301 − 2.602 = 3.699",
        "D121 = 10 min ÷ 3.699 = 2.70 min",
      ],
    },
    {
      t: "Glass container types",
      p: "ยาฉีดชนิดสารละลายน้ำ pH 8.0 บรรจุ ampule และจะผ่าน terminal sterilization ด้วย autoclave ควรเลือกภาชนะแก้วชนิดใดเหมาะสมที่สุดตามเภสัชตำรับ",
      o: [
        "Type I borosilicate glass",
        "Type II treated soda-lime glass",
        "Type III soda-lime glass",
        "Type NP general-purpose soda-lime glass",
        "แก้วสีชาชนิด soda-lime ทั่วไป",
      ],
      a: 0,
      r: "Type I (borosilicate) มี hydrolytic resistance สูงสุด เพราะมี SiO2 และ B2O3 สูง ปลดปล่อย alkali น้อย จึงเหมาะกับยาฉีดทุกชนิด โดยเฉพาะสารละลายน้ำที่มี pH เป็นกลางถึงด่างและต้องผ่าน autoclave\n\nType II เป็น soda-lime ที่ผ่าน surface treatment (dealkalization ด้วย sulfur) ใช้ได้กับสารละลายน้ำที่เป็นกรดหรือกลางและไม่ autoclave ซ้ำ ส่วน Type III ใช้กับผงแห้งหรือยาในน้ำมัน Type NP ไม่ใช้กับ parenteral",
      w: [
        "ถูก — borosilicate ทนการชะ alkali ได้ดีที่สุด เหมาะกับสารละลายน้ำ pH สูงที่ผ่าน autoclave",
        "ความทนทานมาจากผิวที่ผ่านการ treat เท่านั้น ไม่เหมาะกับสารละลายด่างที่ผ่านความร้อนซึ่งกัดผิวได้",
        "ปลดปล่อย alkali มาก ใช้กับผงแห้งหรือ non-aqueous parenteral ไม่ใช่สารละลายน้ำ pH สูง",
        "เป็นแก้วสำหรับ non-parenteral (เช่น ยารับประทาน) ไม่ใช้กับยาฉีด",
        "สีชาช่วยกันแสงแต่ไม่ได้แก้ปัญหา hydrolytic resistance ของ soda-lime",
      ],
      k: "Type I = ยาฉีดทุกชนิด; Type II = สารละลายน้ำกรด/กลาง; Type III = ผงแห้ง/น้ำมัน; NP = ไม่ใช่ยาฉีด",
      d: "easy",
      ref: "USP <660> Containers—Glass; Ph. Eur. 3.2.1 Glass containers for pharmaceutical use",
    },
    {
      t: "Sterility test media",
      p: "ห้องปฏิบัติการทดสอบ sterility test ของยาฉีดตาม USP <71> ข้อใดเป็นการเลือกอาหารเลี้ยงเชื้อและสภาวะบ่มที่ถูกต้อง",
      o: [
        "Fluid thioglycollate medium บ่ม 30–35 °C และ Soybean-casein digest medium บ่ม 20–25 °C นาน 14 วัน",
        "Soybean-casein digest medium บ่ม 30–35 °C เพียงชนิดเดียว นาน 7 วัน",
        "Fluid thioglycollate medium บ่ม 20–25 °C และ Sabouraud dextrose agar บ่ม 30–35 °C นาน 5 วัน",
        "Nutrient agar plate บ่ม 37 °C นาน 48 ชั่วโมง แล้วนับโคโลนี",
        "Fluid thioglycollate medium บ่ม 30–35 °C เพียงชนิดเดียว นาน 14 วัน",
      ],
      a: 0,
      r: "USP <71>/Ph. Eur. 2.6.1 ใช้อาหาร 2 ชนิดคู่กัน: Fluid thioglycollate medium (FTM) สำหรับ anaerobic และ aerobic bacteria บ่ม 30–35 °C และ Soybean-casein digest medium (SCDM หรือ TSB) สำหรับเชื้อรา และ aerobic bacteria บ่ม 20–25 °C บ่มอย่างน้อย 14 วัน\n\nเหตุที่ต้องใช้ 2 อาหาร 2 อุณหภูมิ เพราะต้องครอบคลุมเชื้อที่ต้องการออกซิเจนต่างกัน และเชื้อราเติบโตได้ดีที่อุณหภูมิต่ำกว่า การทดสอบเป็นแบบ qualitative (มี/ไม่มี growth) ไม่ใช่การนับโคโลนี",
      w: [
        "ถูก — FTM 30–35 °C + SCDM 20–25 °C บ่มไม่น้อยกว่า 14 วัน",
        "ขาด FTM สำหรับ anaerobes และระยะเวลาบ่มสั้นเกินไป",
        "สลับอุณหภูมิ และ Sabouraud agar ไม่ใช่อาหารของ compendial sterility test",
        "เป็นแนวทาง bioburden/plate count ไม่ใช่ sterility test",
        "ขาด SCDM ที่บ่มอุณหภูมิต่ำเพื่อตรวจเชื้อราและ aerobes",
      ],
      k: "Sterility test: FTM 30–35 °C (anaerobes/aerobes) + SCDM 20–25 °C (fungi/aerobes) ≥ 14 วัน",
      d: "easy",
      ref: "USP <71> Sterility Tests; Ph. Eur. 2.6.1",
    },
    {
      t: "Bubble point test interpretation",
      p: "หลังกรอง bulk solution ผ่าน 0.22 µm PVDF sterilizing-grade filter ทำ post-use bubble point test (ใช้น้ำเป็น wetting fluid) ได้ 2.6 bar ขณะที่ค่าต่ำสุดที่ผู้ผลิต filter กำหนดคือ 3.5 bar ข้อสรุปและการดำเนินการใดเหมาะสมที่สุด",
      o: [
        "ผลบ่งชี้ว่ามีรูขนาดใหญ่กว่ากำหนดหรือการ wetting ไม่สมบูรณ์ ให้ flush/re-wet แล้วทดสอบซ้ำตาม SOP หากยังต่ำถือว่า filter ไม่ integral และต้องสอบสวนผลกระทบต่อ batch",
        "ค่าต่ำกว่าแสดงว่ารูเล็กกว่ากำหนด filter มีประสิทธิภาพสูงขึ้น ปล่อย batch ได้",
        "Bubble point ไม่เกี่ยวกับขนาดรู จึงใช้ผล sterility test ตัดสินแทนได้",
        "ให้ปรับ specification ลงเป็น 2.5 bar เพราะเป็นผลหลังใช้งานซึ่งต่ำลงเสมอ",
        "เปลี่ยนไปใช้ 0.45 µm filter ใน batch ถัดไปเพื่อให้ bubble point ผ่าน",
      ],
      a: 0,
      r: "Bubble point คือความดันต่ำสุดที่ gas ขับของเหลวออกจากรูที่ใหญ่ที่สุดของ membrane ที่เปียกอยู่ (P = 4kγcosθ/d) ความดันจึงแปรผกผันกับขนาดรู ค่าที่ต่ำกว่า specification หมายถึงมีรูใหญ่กว่าที่ validated หรือมีรอยรั่ว/seal เสีย\n\nอย่างไรก็ตาม bubble point ต่ำเทียมได้จากการ wetting ไม่สมบูรณ์หรือ product ตกค้างที่ลด surface tension จึงต้อง flush ด้วย wetting fluid ที่กำหนดแล้วทดสอบซ้ำตาม procedure หากยืนยันว่า fail ต้องถือว่า sterility assurance ของ batch ถูกกระทบ และต้องสอบสวน (เช่น พิจารณา refiltration ตามที่ validated) ไม่สามารถใช้ sterility test มาชดเชยได้",
      w: [
        "ถูก — bubble point ต่ำ = รูใหญ่/รอยรั่ว หรือ wetting ไม่ดี ต้องทดสอบซ้ำอย่างถูกวิธีและสอบสวนผลกระทบหากยืนยัน",
        "ตีความกลับด้าน รูเล็กลงจะทำให้ bubble point สูงขึ้น ไม่ใช่ต่ำลง",
        "Bubble point สัมพันธ์โดยตรงกับขนาดรูที่ใหญ่ที่สุด และ sterility test มีข้อจำกัดเชิงสถิติ ไม่ใช้แทน integrity test",
        "การลด specification เพื่อให้ผลผ่านไม่มีหลักวิชาการรองรับและเป็นการปิดบังความล้มเหลว",
        "0.45 µm ไม่ใช่ sterilizing-grade filter และไม่ได้แก้ปัญหา batch ที่กรองไปแล้ว",
      ],
      k: "Bubble point แปรผกผันกับขนาดรู; ต่ำกว่าเกณฑ์ = สงสัย breach — ตรวจ wetting ก่อนสรุปและสอบสวน batch",
      d: "medium",
      ref: "PDA Technical Report No. 26 Sterilizing Filtration of Liquids; EU GMP Annex 1 (2022) section 8",
    },
    {
      t: "Collapse temperature in primary drying",
      p: "สูตรยา lyophilized ที่มี sucrose เป็น lyoprotectant หลัก วัด collapse temperature (Tc) ด้วย freeze-drying microscopy ได้ −32 °C ข้อใดเป็นแนวทางตั้งค่า primary drying ที่เหมาะสมที่สุด",
      o: [
        "ควบคุม product temperature ให้ต่ำกว่า Tc ประมาณ 2–5 °C (เช่น −35 °C) โดยปรับ shelf temperature และ chamber pressure",
        "ตั้ง shelf temperature ที่ −32 °C ตลอด primary drying เพราะ shelf กับ product มีอุณหภูมิเท่ากัน",
        "ควบคุม product temperature ให้สูงกว่า Tc เล็กน้อยเพื่อเร่ง sublimation",
        "ควบคุม product temperature ที่ 0 °C เพราะ sucrose เป็น crystalline ไม่ collapse",
        "เพิ่ม chamber pressure ให้สูงใกล้ความดันบรรยากาศเพื่อเพิ่ม heat transfer สูงสุด",
      ],
      a: 0,
      r: "ในสูตร amorphous เช่น sucrose ค่า critical คือ collapse temperature (ใกล้ Tg' ของ freeze-concentrate) ถ้า product temperature ที่ sublimation front สูงกว่า Tc โครงสร้างจะยุบ เกิด cake collapse ความชื้นค้างสูงและ reconstitution ช้า\n\nแนวทางคือให้ product temperature ต่ำกว่า Tc ประมาณ 2–5 °C ซึ่งเป็นการแลกระหว่างความปลอดภัยกับความเร็ว เพราะทุก 1 °C ที่ product อุ่นขึ้นจะเร่ง primary drying ได้ราว 13% ทั้งนี้ product temperature ต่ำกว่า shelf temperature มากเนื่องจาก sublimation ใช้ความร้อนแฝง จึงควบคุมผ่าน shelf temperature ร่วมกับ chamber pressure",
      w: [
        "ถูก — product temperature ต้องอยู่ต่ำกว่า Tc เล็กน้อย โดยใช้ shelf temperature และ pressure เป็นตัวควบคุม",
        "Product temperature ระหว่าง sublimation ต่ำกว่า shelf มาก ตั้ง shelf ที่ Tc จะทำให้การอบช้ามากโดยไม่จำเป็น",
        "สูงกว่า Tc ทำให้ cake collapse แม้ sublimation จะเร็วขึ้น",
        "Sucrose เป็น amorphous ใน freeze-concentrate ไม่ใช่ crystalline จึง collapse ได้ที่อุณหภูมิสูง",
        "Pressure สูงมากทำให้ product temperature สูงเกิน Tc และลดแรงขับของการระเหิด",
      ],
      k: "Primary drying: product temperature < Tc (หรือ Teu ของสูตร crystalline) 2–5 °C; ควบคุมด้วย shelf T + chamber P",
      d: "medium",
      ref: "Tang X, Pikal MJ. Design of freeze-drying processes for pharmaceuticals: practical advice. Pharm Res 2004;21:191–200",
    },
    {
      t: "Preservative-free parenteral routes",
      p: "ผู้ผลิตต้องการพัฒนายาฉีดหลายรูปแบบจาก API เดียวกัน รูปแบบใดต่อไปนี้ห้ามเติม antimicrobial preservative ในตำรับ",
      o: [
        "ยาฉีดสำหรับ intrathecal ขนาด single-dose 5 mL",
        "ยาฉีด IM multiple-dose vial ขนาด 10 mL",
        "ยาฉีด SC multiple-dose cartridge ขนาด 3 mL",
        "ยาฉีด IV multiple-dose vial ขนาด 20 mL",
        "ยาฉีด IM single-dose vial ที่บรรจุแบบ aseptic ขนาด 2 mL",
      ],
      a: 0,
      r: "ยาที่ให้เข้าสู่ระบบประสาทส่วนกลางหรือบริเวณที่ไวต่อสารพิษ ได้แก่ intrathecal, intracisternal, epidural และ intraocular ต้องปราศจาก preservative เพราะ preservative เช่น benzyl alcohol, phenol, parabens มี neurotoxicity หรือทำลายเนื้อเยื่อตา\n\nนอกจากนี้ LVP ก็ไม่เติม preservative เพราะปริมาณรวมที่ผู้ป่วยได้รับจะสูงเกินขนาดปลอดภัย ส่วน single-dose container อื่น ๆ ไม่จำเป็นต้องมี preservative แต่ก็ไม่ได้ถูกห้าม ขณะที่ multiple-dose ต้องมี preservative",
      w: [
        "ถูก — intrathecal ต้อง preservative-free เพราะสารกันเสียเป็นพิษต่อระบบประสาท",
        "Multiple-dose ต้องมี preservative เพื่อป้องกันการปนเปื้อนจากการเจาะซ้ำ",
        "Multiple-dose cartridge (เช่น insulin) ต้องมี preservative เช่น m-cresol",
        "IV multiple-dose vial ขนาดเล็กใส่ preservative ได้และจำเป็นต้องใส่",
        "Single-dose IM ไม่จำเป็นต้องใส่ preservative แต่ไม่ได้ถูกห้ามโดยหลักการ",
      ],
      k: "ห้ามใส่ preservative: intrathecal, intracisternal, epidural, intraocular และ LVP",
      d: "medium",
      ref: "USP <1> Injections and Implanted Drug Products; Remington 23rd ed., Parenteral Preparations",
    },
    {
      t: "Isotonic vs iso-osmotic (boric acid)",
      p: "สารละลาย boric acid 1.9% w/v มีจุดเยือกแข็งลดลง 0.52 °C เท่ากับ 0.9% NaCl แต่เมื่อนำไปทดสอบกับเม็ดเลือดแดงพบ hemolysis เกือบทั้งหมด ข้อใดอธิบายได้ดีที่สุด",
      o: [
        "Boric acid ซึมผ่านเยื่อหุ้มเม็ดเลือดแดงได้อย่างอิสระ สารละลายจึง iso-osmotic แต่ไม่ isotonic ต่อเม็ดเลือดแดง",
        "Boric acid แตกตัวเป็นไอออนสมบูรณ์ทำให้ osmotic pressure จริงสูงกว่าที่วัดได้",
        "การวัดจุดเยือกแข็งไม่สัมพันธ์กับ osmotic pressure ของสารละลายใด ๆ",
        "Boric acid ทำให้ pH เป็นด่างจัดจนเยื่อหุ้มเซลล์ถูกย่อยสลาย",
        "สารละลายนี้ hypertonic จึงทำให้เม็ดเลือดแดงเหี่ยวและแตก",
      ],
      a: 0,
      r: "Iso-osmotic หมายถึงมี osmotic pressure (colligative property) เท่ากับเลือดเมื่อวัดผ่าน ideal semipermeable membrane ส่วน isotonic หมายถึงไม่ทำให้ปริมาตรเซลล์เปลี่ยนเมื่อสัมผัสกับเยื่อหุ้มเซลล์จริง\n\nสารที่ซึมผ่านเยื่อหุ้มเม็ดเลือดแดงได้ เช่น boric acid, urea, glycerin, ethanol, ammonium chloride จะเคลื่อนเข้าเซลล์ ทำให้น้ำตามเข้าไปจนเซลล์บวมและแตก จึงมีพฤติกรรมเหมือน hypotonic แม้ค่า osmotic จะเท่ากัน อย่างไรก็ตาม 1.9% boric acid ใช้เป็น vehicle ของยาตาได้เพราะเยื่อบุตาตอบสนองต่างจากเม็ดเลือดแดง",
      w: [
        "ถูก — สารที่ผ่านเยื่อหุ้มเซลล์ได้ไม่ช่วยรักษาสมดุล tonicity จึงเกิด hemolysis แม้ iso-osmotic",
        "Boric acid เป็นกรดอ่อนมาก (pKa ≈ 9.2) แตกตัวน้อยมาก ไม่ใช่สาเหตุ",
        "Freezing point depression เป็น colligative property ที่สัมพันธ์กับ osmotic pressure โดยตรง",
        "สารละลาย boric acid มี pH เป็นกรดอ่อน ไม่ใช่ด่างจัด",
        "Hypertonic ทำให้เซลล์เหี่ยว (crenation) ไม่ใช่ hemolysis และสารละลายนี้ iso-osmotic",
      ],
      k: "Iso-osmotic ≠ isotonic: สารที่ซึมผ่านเยื่อหุ้ม RBC (boric acid, urea, glycerin) ทำให้ hemolysis",
      d: "hard",
      ref: "Martin's Physical Pharmacy and Pharmaceutical Sciences 7th ed., Ch. Buffered and Isotonic Solutions",
    },
    {
      t: "Sterilization method decision tree",
      p: "ยาฉีดสารละลายน้ำใน glass vial เมื่อผ่าน autoclave 121 °C 15 นาทีพบ degradation product เกิน specification แต่หากใช้ cycle 115 °C ที่ให้ F0 = 12 นาที ผลิตภัณฑ์ยังผ่าน specification บริษัทเสนอเปลี่ยนเป็น sterile filtration ร่วมกับ aseptic filling ตามแนวทาง EMA sterilisation decision tree ข้อใดถูกต้อง",
      o: [
        "ต้องใช้ terminal moist heat cycle ที่ F0 ≥ 8 นาทีซึ่งพิสูจน์ได้ว่าให้ SAL ≤ 10^-6 พร้อมควบคุม bioburden แทนการเลือก aseptic processing",
        "เลือก aseptic processing ได้ทันทีเพราะสูตรไม่ทน 121 °C 15 นาที",
        "ใช้ dry heat 160 °C 2 ชั่วโมงแทน เพราะไม่มีความชื้นที่เร่ง hydrolysis",
        "ใช้ sterile filtration แล้วตามด้วย sterility test 100% ของทุก vial",
        "ลดความเข้มงวดโดยใช้ cycle F0 = 3 นาทีเพื่อลด degradation ให้มากที่สุด",
      ],
      a: 0,
      r: "แนวทาง EMA (Guideline on the sterilisation of the medicinal product, active substance, excipient and primary container, 2019) กำหนดลำดับความสำคัญ: เริ่มจาก reference cycle 121 °C ≥ 15 นาที ถ้าไม่ได้ ให้พิจารณา moist heat ที่ F0 ≥ 8 นาทีซึ่งทำ SAL ≤ 10^-6 ได้ (ต้องมีการควบคุม bioburden และความทนความร้อนของเชื้อ) ถ้ายังไม่ได้จึงพิจารณาวิธีอื่น เช่น irradiation และสุดท้ายคือ sterile filtration + aseptic processing\n\nเนื่องจาก terminal sterilization ให้ sterility assurance สูงกว่า aseptic processing อย่างชัดเจน การที่สูตรทน cycle F0 = 12 ได้จึงต้องเลือก terminal sterilization ไม่ใช่กระโดดไป aseptic processing",
      w: [
        "ถูก — decision tree กำหนดให้ใช้ moist heat ที่ F0 ≥ 8 (SAL ≤ 10^-6) ก่อนจะยอมรับ aseptic processing",
        "การไม่ทน reference cycle ยังไม่พอ ต้องพิสูจน์ก่อนว่าไม่สามารถใช้ cycle F0 ≥ 8 ได้",
        "Dry heat ไม่เหมาะกับสารละลายน้ำในภาชนะปิดและอุณหภูมิสูงกว่ามาก",
        "Sterility test เป็นการทดสอบทำลายและมีข้อจำกัดทางสถิติ ทำ 100% ไม่ได้และไม่เพิ่ม assurance ของกระบวนการ",
        "F0 = 3 ไม่ถึงเกณฑ์ขั้นต่ำ (F0 ≥ 8 พร้อม SAL ≤ 10^-6) ของ terminal sterilization",
      ],
      k: "EMA decision tree: 121 °C/15 min → F0 ≥ 8 (SAL ≤ 10^-6) → วิธีอื่น → filtration + aseptic เป็นทางเลือกสุดท้าย",
      d: "hard",
      ref: "EMA/CHMP/CVMP/QWP/850374/2015 Guideline on the sterilisation of the medicinal product, active substance, excipient and primary container (2019)",
    },
  ],
];
